### DISCUSSION TITLE
Multisite: Preferred redirection strategy from the domain root?

### DISCUSSION THREAD

**Discussion by helloDanuk** [statamic/cms#10163] [Q&A] [answered]
What is the best strategy to redirect example.com to example.com/de in this setup below? Is this something I should do somehow in Statamic or is it a server level redirect? I would prefer to run the main language under the /de folder, as I do with the second language. Thanks for a little help in advance.

**main language:**

- example.com/de 
- example.com/de/page-1

**second language:**

- example.com/fr
- example.com/fr/page-1

**my sites.yaml looks like this:**

```
de:
  name: '{{ config:app:name }} DE'
  url: /de
  locale: de_CH
  lang: de_CH
fr:
  name: '{{ config:app:name }} FR'
  url: /fr
  locale: fr_CH
  lang: fr_CH
```
