### DISCUSSION TITLE
Not all fields on entries list are clickable

### DISCUSSION THREAD

**Discussion by IVoyt** [statamic/cms#10289] [Q&A]
I have the following Blueprint and some of it's fields are not clickable on Entries list and I can not understand why. Are there any requirements to fields to be clickable?
Worth to notice this is a Runway-blueprint

```
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: type
            field:
              options:
                123: News
              type: select
              display: type
              localizable: false
              validate:
                - required
          -
            handle: translations_ua
            field:
              tab_icon: translate
              type: tab
              display: 'Translations UA'
              localizable: false
              listable: true
          -
            import: news_translations_ua
          -
            handle: translations_ru
            field:
              tab_icon: translate
              type: tab
              display: 'Translations RU'
              localizable: false
          -
            import: news_translations_ru
          -
            handle: translations_en
            field:
              tab_icon: translate
              type: tab
              display: 'Translations EN'
              localizable: false
          -
            import: news_translations_en
  sidebar:
    display: Sidebar
    sections:
      - {  }
title: News

```

here is the blueprint of one of fieldsets if needed
```
title: news_translations_ua
fields:
  -
    handle: title_ua
    field:
      type: text
      display: 'Title UA'
      localizable: false
      listable: true
      width: 50
      validate:
        - required
  -
    handle: slug_ua
    field:
      show_regenerate: true
      type: slug
      display: 'Slug UA'
      localizable: false
      listable: true
      from: title_ua
      width: 50
  -
    handle: body_ua
    field:
      type: tinymce_cloud
      display: 'Body UA'
      localizable: false
```

<img width="2090" alt="image" src="https://github.com/statamic/cms/assets/10925772/ee8a8f4a-6441-487d-ba53-dd7533f457b2">
