### DISCUSSION TITLE
I know it's me - Routing issue

### DISCUSSION THREAD

**Discussion by fpolli** [statamic/cms#11070] [Troubleshooting] [answered]
I am having a problem with routing on a collection that I cannot figure out. My site is multisite using domain names. I installed with the Landtamic starter kit. I have a "posts" collection, and I have entries for each site. On one site (the primary site), the navigation works. On the other, I get a 404 error. I can see no difference between the setup of the two sites.

The folder structure of my content folder:

```
content
     - collections
         - pages
         - posts
             - siteone
                 -- 2024-11-05.a-post.md 
             - sitetwo
                 -- 2024-11-05.a-nother-post.md
        -- pages.yaml
        -- posts.yaml
    - trees
        - collections
            -- pages.yaml 
        - navigation 
            - siteone
                -- nav.yaml 
            - sitetwo
                -- nav.yaml
```

My resources/sites.yaml file:

```
siteone:
  name: 'My Site'
  locale: en_US
  url: 'http://mysiteone.test'
sitetwo:
  name: 'My Other Site'
  url: 'http://mysecondsight.test'
  locale: en_US
```
 My posts.yaml file:

```
title: Works
sites:
  - siteone
  - sitetwo
propagate: false
template: posts/show
layout: layout
taxonomies:
  - categories
  - tags
  - genres
  - medium
revisions: false
route: 'posts/{slug}'
date: true
sort_dir: desc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
inject:
  view_model: App\ViewModels\OgImage
```

For site one, all of that produces a url of:

http://mysiteone.test/posts/a-post
http://mysecondsight.test/posts/a-nother-post

The first one returns the post page.
The second one returns a 404 error.

Thank you.
