### DISCUSSION TITLE
Refactor Bard content

### DISCUSSION THREAD

**Discussion by carstenjaksch** [statamic/cms#11253] [Q&A]
Hi,

I have a very hard time to refactor Bard content to a new fieldset structure.

There is a fieldset that contained only a Bard field, now the Bard field is inside a group field.

On a page is a replicator with three times the same set and each of them import the updated fieldset.

I updated the first set to the new structure, works like a charme. But everything after that don't work?!

They have the exact same structure as the first one but it does not show the content in CP. I am very confused ...

The Bard structure (content wrapper after richtext is new):

```yaml
            richtext:
                content:
                    - type: paragraph
                      attrs:
                        textAlign: left
                        class: null
                      content:
                          - type: text
                            text: "Bei einem fremdverschuldeten Unfall erhalten Sie von uns eine kostenlose Erstberatung zu Ihrem Kfz-Gutachten."
                          - type: hardBreak
                          - type: text
                            marks:
                                - type: bold
                            text: "Lassen Sie sich beraten!"
```

Again, the first (working) and all others (don't working) have the exact same structure and indentation. What's going on here?
