### DISCUSSION TITLE
Can antlers be nested inside markdown links?

### DISCUSSION THREAD

**Discussion by NoelDeMartin** [statamic/cms#11350] [Q&A]
Hi there,

I recently started migrating my Laravel site to Statamic, so forgive me if this question is too stupid 🙈. Previously I had many content pages hard-coded in html, and I'm going through the process of migrating most of them to Markdown which is pretty nice.

However, I've been struggling to understand where I can or can't use the antlers syntax. For example, it seems like by default it is disabled inside of markdown. But I could enable it with the [`antlers` option](https://statamic.dev/fieldtypes/markdown#options) for the field.

But now I'm facing a new issue. Whenever I use antlers inside of Markdown links, it doesn't work.

To see a specific example, this is what I write in the markdown (I defined `contact:email` as a [global variable](https://statamic.dev/globals)):

```markdown
1. [Email me]({{ contact:email }})
2. [Email me]({{contact:email}})
3. <a href="{{ contact:email }}">Email me</a>
4. <a href="{{contact:email}}">Email me</a>
```

And this is how it gets rendered:

```html
<ol>
    <li>[Email me](hello@example.com)</li>
    <li><a href="%7B%7Bcontact:email%7D%7D">Email me</a></li>
    <li><a href="hello@example.com">Email me</a></li>
    <li><a href="hello@example.com">Email me</a></li>
</ol>
```

As you can see, both 1 and 2 are broken. The first because it doesn't render a link, and the second because it's escaping the antlers syntax. But it works writing a link by hand :/. Is there any way to work around that?

**Comment by edalzell** [comment]
OK first, are you using markdown for your content intentionally, instead of a Bard field?

**Reply by NoelDeMartin** [reply]
Hi there, I'm very new to Statamic so I didn't even know this Bard field existed 😅. Since the markdown field was the default one for the content of the Home page, I thought it was fine.

In any case, I've taken a look and yes, I still prefer to use Markdown (at least for now). I also tried using antlers inside of Bard though, and it didn't work either. So I guess my question is how to use global variables inside of content links?

This is how the link got saved using Bard:

```yaml
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: link
            attrs:
              href: 'mailto:{{ contact:email }}'
              rel: null
              target: null
              title: null
        text: 'Email me'
```

But it still rendered like this:

```html
<p>
    <a href="mailto:{{ contact:email }}">Email me</a>
</p>
```
