### DISCUSSION TITLE
Issues with Published Pages Across Different Repos

### DISCUSSION THREAD

**Discussion by ivang76** [statamic/cms#11539] [Q&A]
Hi there,

I have a project based on Statamic, and I noticed that if I push the entire repo (or even if I clone/copy the entire filesystem and database) to another space and domain, all the pages on the new instance return 404 errors. I then have to enter the control panel and republish all of them manually.

However, this creates a problem because it introduces differences in the .md files. Every time I merge or update the repo, it causes the pages to be unpublished in the original repo. I then have to republish them again, and with the next git push/pull, the pages on the production site become unpublished once more, creating a continuous loop.

Any ideas on how to fix this?
Thanks!

**Comment by edalzell** [comment]
what are you using in `sites.yaml`?

**Reply by ivang76** [reply]
something like this:

````
it:
  name: it
  url: '{{ config:app:url }}'
  locale: it_IT
  lang: it
en:
  name: en
  url: '{{ config:app:url }}/en/'
  locale: en_US
  lang: en
````
