### DISCUSSION TITLE
entries ordering in collection

### DISCUSSION THREAD

**Discussion by lostika86** [statamic/cms#4481] [Troubleshooting] [answered]
I need some help  I have  collection which is orderable, 
```
title: 'Pred a po zateplení'
template: default
layout: layout
revisions: false
sort_dir: desc
date_behavior:
  past: public
  future: private
structure:
  root: false
  max_depth: 1
```
on `/cp/collections/before_after_collection` I click 'reorder' , make some reordering, click on 'save' .. after that collection entries are not ordered as I ordered, even I change entry listing to 'reorder' state 
Entries on tree are ordered correctly, checked many times!
Do I making something wrong?
