### DISCUSSION TITLE
Using prefixes in partials

### DISCUSSION THREAD

**Discussion by SenseAndImage** [statamic/cms#4551] [Q&A]
Hello everyone,

I want to use a linked fieldset multiple times in a replicator set and use prefixes to differentiate between them. In the antlers template, i use partials to render the content of the linked fieldsets.

However, i am struggling a bit with the use of prefixes here, as i can't find a way to combine the prefix with the regular fieldnames.

For Example: 
fieldset is prefixed with: `right_`
the prefix gets passed to the partial with `{{ partial:x prefix="right_" }}`  //i know, horrible way, since this breaks if the prefix is changed in backend, but haven't found a better way yet.
in the partial, i want to use something along the lines of `{{ {prefix} + fieldname }}` to access `{{ right_fieldname }}`, but nothing i tried is working

is there something i am missing/doing wrong or is such a functionality currently not possible? Any other way to differentiate between the multiple instances of the linked fieldset and accessing the correct data would be fine aswell.

**Comment by edalzell** [comment]
I don't really understand what you're trying to do, can we see some data (the `.md` file) please?

**Comment by SenseAndImage** [comment]
Shorted to be relevant:

debug_fieldset.md
```
title: debug_fieldset
fields:
  -
    import: button
  -
    import: button
    prefix: prefix_
```

Debug page
```
---
( ... )
blueprint: page
title: Debug
( ... )
page_builder:
  -
    label: 'Button 1'
    target_blank: true
    link_type: url
    url: 'https://statamic.com/'
    button_type: button
    prefix_label: 'Button 2'
    prefix_target_blank: true
    prefix_link_type: url
    prefix_url: 'https://peak.studio1902.nl/'
    prefix_button_type: button
    type: debug_fieldset
    enabled: true
---

```

debug_fieldset.antlers.html
```
<div>
    {{ partial:components/button }}
    {{ partial:components/button prefix="prefix_" }}
</div>
```

button.antlers.html
```
{{ { prefix } + label }}
{{ { prefix }label }}

{{ if label }}
    <{{ as or 'a' }}
        {{ attribute }}
        {{ if button_type == 'inline' }}
            class="font-bold text-base uppercase text-stargreen focus:text-white {{ class }}
            {{ inverted ? 'text-white focus:text-stargreen' : '' }}"
        {{ else }}
            class="font-bold text-base bg-stargreen border-0 rounded focus:outline-none focus-visible:ring focus-visible:ring-offset-2 shadow-xl {{ class }} inline-flex items-center py-4 px-12 leading-none uppercase tracking-widest text-sm no-underline select-none whitespace-nowrap motion-safe:transition
            {{ inverted ? 'text-white focus-visible:ring-white' : 'border-primary text-primary focus-visible:ring-primary' }}"
        {{ /if }}
        "
        {{ unless faux }}
            {{ partial:snippets/button_attributes }}
        {{ /unless }}
    >
        {{ label }}
    </{{ as or 'a' }}>
{{ /if }}
```

the first two lines of `button.antlers.html` are tries to access the values of the prefixed button, which don't work. How am i able to access the different values if both use the same partial?
