### DISCUSSION TITLE
Change field listings for link field on entries

### DISCUSSION THREAD

**Discussion by ARCHES-Academy** [statamic/cms#4560] [Troubleshooting] [answered]
I have an entry with a link field, and when you click on the "`link existing entry`" link, it brings up the pane with all the options. My issue is that it only shows the title and slug. I need another field to show on the listing, because the employees working on this page need more data to select the needed entry. Is there a way to customize it, to show more fields (content, or other custom fields)?

**Comment by edalzell** [comment, marked as answer]
Are the blueprint fields `hidden: true`? Let's see the blueprint.

**Reply by ARCHES-Academy** [reply]
Here's the blueprint:

``` yaml
title: Standards
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
          display: Abbreviation
          instructions: 'Standard Abbreviation (K.RL.1)'
          listable: true
          input_type: text
          antlers: false
      -
        handle: grade_level
        field:
          options:
            1: '1st Grade'
            2: '2nd Grade'
            3: '3rd Grade'
            4: '4th Grade'
            5: '5th Grade'
            6: '6th Grade'
            7: '7th Grade'
            8: '8th Grade'
            K: Kindergarten
          multiple: false
          max_items: 1
          clearable: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          display: 'Grade Level'
          type: select
          icon: select
          listable: hidden
      -
        handle: content
        field:
          input_type: text
          antlers: false
          display: 'Full Standard'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: standard_number
        field:
          display: 'Standard Number'
          type: integer
          icon: integer
          listable: hidden
      -
        handle: standards_category
        field:
          options:
            LA: 'Language Arts'
            M: Math
            SS: 'Social Studies'
            S: Science
          multiple: false
          max_items: 1
          clearable: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          display: 'Standards Category'
          type: select
          icon: select
          listable: hidden
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
            - 'unique_entry_value:{collection},{id},{site}'
```

Is it the `listable: hidden` that I should change?
