### DISCUSSION TITLE
Specific page blueprint not working after upgrading from 3.2.16 to 3.2.17 or 3.2.18

### DISCUSSION THREAD

**Discussion by ronvdc** [statamic/cms#4577] [Troubleshooting] [answered]
I have two pages on a site based on a blueprint called "Segments." They worked great in version 3.2.16. However, after upgrading to version 3.2.17 or 3.2.18, I see a server 500 error, and only for pages based on that blueprint. All other pages in the site (based on other blueprints) work as expected, and the pages based on the "Segment" blueprint worked fine in 3.2.16 and earlier.

The segments.yaml code is below. Excuse the unelegant, repetitive way of dealing with each segment (title_1, content_1, photo_1, image_position_1, title_2, content_2, etc.). I'm only a very amateur coder, so I didn't know how to code this more elegantly and iteratively (yet).

Any idea why this could be failing in 3.2.17 and 3.2.18, but not in 3.2.16?

```
order: 1
title: Segments
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          localizable: true
          display: 'Page Title'
          validate:
            - required
          instructions: 'This is the title shown as the heading on the page.'
          listable: hidden
          input_type: text
          antlers: false
          width: 66
      -
        handle: slug
        field:
          type: text
          required: true
          localizable: true
          width: 33
          validate:
            - required
            - 'unique_entry_value:{collection},{id},{site}'
      -
        handle: custom_page_heading
        field:
          input_type: text
          antlers: false
          display: 'Custom Page Heading'
          type: text
          icon: text
          instructions: 'Optionally, enter a custom page heading. If nothing is provided here, the page title is used as the heading.'
          listable: hidden
      -
        handle: intro
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: true
          display: Intro
          type: markdown
          icon: markdown
          listable: hidden
      -
        handle: title_1
        field:
          input_type: text
          antlers: true
          display: 'Title 1'
          type: text
          icon: text
          listable: hidden
      -
        handle: content_1
        field:
          type: markdown
          display: 'Content 1'
          localizable: true
          cheatsheet: true
          restrict_assets: false
          container: assets
          antlers: true
          folder: /
          listable: hidden
          restrict: false
          automatic_line_breaks: true
          automatic_links: true
          escape_markup: false
          smartypants: true
      -
        handle: photo_1
        field:
          type: assets
          container: assets
          folder: /
          restrict: false
          display: 'Photo 1'
          listable: hidden
          mode: grid
          allow_uploads: true
          max_files: 1
          width: 66
      -
        handle: image_position_1
        field:
          options:
            right: Right
            left: Left
          multiple: false
          clearable: false
          searchable: false
          taggable: false
          push_tags: false
          cast_booleans: false
          default: right
          display: 'Image Position 1'
          type: select
          icon: select
          width: 33
          listable: hidden
          instructions_position: above
      -
        handle: title_2
        field:
          input_type: text
          antlers: true
          display: 'Title 2'
          type: text
          icon: text
          listable: hidden
      -
        handle: content_2
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: true
          display: 'Content 2'
          type: markdown
          icon: markdown
          listable: hidden
      -
        handle: photo_2
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          display: 'Photo 2'
          type: assets
          icon: assets
          listable: hidden
          container: assets
          max_files: 1
          width: 66
          instructions_position: above
          show_filename: true
      -
        handle: image_position_2
        field:
          options:
            right: Right
            left: Left
          multiple: false
          clearable: false
          searchable: false
          taggable: false
          push_tags: false
          cast_booleans: false
          default: left
          display: 'Image Position 2'
          type: select
          icon: select
          width: 33
          listable: hidden
          instructions_position: above
      -
        handle: title_3
        field:
          input_type: text
          antlers: true
          display: 'Title 3'
          type: text
          icon: text
          listable: hidden
      -
        handle: content_3
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: true
          display: 'Content 3'
          type: markdown
          icon: markdown
          listable: hidden
      -
        handle: photo_3
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          display: 'Photo 3'
          type: assets
          icon: assets
          listable: hidden
          container: assets
          max_files: 1
          width: 66
          instructions_position: above
          show_filename: true
      -
        handle: image_position_3
        field:
          options:
            right: Right
            left: Left
          multiple: false
          clearable: false
          searchable: false
          taggable: false
          push_tags: false
          cast_booleans: false
          default: right
          display: 'Image Position 3'
          type: select
          icon: select
          width: 33
          listable: hidden
          instructions_position: above
      -
        handle: title_4
        field:
          input_type: text
          antlers: true
          display: 'Title 4'
          type: text
          icon: text
          listable: hidden
      -
        handle: content_4
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: true
          display: 'Content 4'
          type: markdown
          icon: markdown
          listable: hidden
      -
        handle: photo_4
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          display: 'Photo 4'
          type: assets
          icon: assets
          listable: hidden
          container: assets
          max_files: 1
          width: 66
          instructions_position: above
          show_filename: true
      -
        handle: image_position_4
        field:
          options:
            right: Right
            left: Left
          multiple: false
          clearable: false
          searchable: false
          taggable: false
          push_tags: false
          cast_booleans: false
          default: left
          display: 'Image Position 4'
          type: select
          icon: select
          width: 33
          listable: hidden
          instructions_position: above
      -
        handle: title_5
        field:
          input_type: text
          antlers: true
          display: 'Title 5'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: content_5
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: true
          display: 'Content 5'
          type: markdown
          icon: markdown
          listable: hidden
      -
        handle: photo_5
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          display: 'Photo 5'
          type: assets
          icon: assets
          listable: hidden
          container: assets
          max_files: 1
          width: 66
          instructions_position: above
          show_filename: true
      -
        handle: image_position_5
        field:
          options:
            right: Right
            left: Left
          multiple: false
          clearable: false
          searchable: false
          taggable: false
          push_tags: false
          cast_booleans: false
          default: right
          display: 'Image Position 5'
          type: select
          icon: select
          width: 33
          listable: hidden
          instructions_position: above
      -
        handle: title_6
        field:
          input_type: text
          antlers: false
          display: 'Title 6'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: content_6
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: 'Content 6'
          type: markdown
          icon: markdown
          listable: hidden
          instructions_position: above
      -
        handle: photo_6
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          show_filename: true
          display: 'Photo 6'
          type: assets
          icon: assets
          width: 66
          listable: hidden
          instructions_position: above
          max_files: 1
          container: assets
      -
        handle: image_position_6
        field:
          options:
            right: Right
            left: Left
          multiple: false
          clearable: false
          searchable: false
          taggable: false
          push_tags: false
          cast_booleans: false
          default: left
          display: 'Image Position 6'
          type: select
          icon: select
          width: 33
          listable: hidden
          instructions_position: above
      -
        handle: title_7
        field:
          input_type: text
          antlers: false
          display: 'Title 7'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: content_7
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: 'Content 7'
          type: markdown
          icon: markdown
          listable: hidden
          instructions_position: above
      -
        handle: photo_7
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          show_filename: true
          display: 'Photo 7'
          type: assets
          icon: assets
          width: 66
          listable: hidden
          instructions_position: above
          max_files: 1
          container: assets
      -
        handle: image_position_7
        field:
          multiple: false
          clearable: false
          searchable: false
          taggable: false
          push_tags: false
          cast_booleans: false
          default: Right
          display: 'Image Position 7'
          type: select
          icon: select
          width: 33
          listable: hidden
          instructions_position: above
          options:
            right: Right
            left: Left
      -
        handle: title_8
        field:
          input_type: text
          antlers: false
          display: 'Title 8'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: content_8
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: 'Content 8'
          type: markdown
          icon: markdown
          listable: hidden
          instructions_position: above
      -
        handle: photo_8
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          show_filename: true
          display: 'Photo 8'
          type: assets
          icon: assets
          width: 66
          listable: hidden
          instructions_position: above
          max_files: 1
          container: assets
      -
        handle: image_positon_8
        field:
          options:
            right: Right
            left: Left
          multiple: false
          clearable: false
          searchable: false
          taggable: false
          push_tags: false
          cast_booleans: false
          default: Left
          display: 'Image Positon 8'
          type: select
          icon: select
          width: 33
          listable: hidden
          instructions_position: above
      -
        handle: title_9
        field:
          input_type: text
          antlers: false
          display: 'Title 9'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: content_9
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: 'Content 9'
          type: markdown
          icon: markdown
          listable: hidden
          instructions_position: above
      -
        handle: photo_9
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          show_filename: true
          display: 'Photo 9'
          type: assets
          icon: assets
          width: 66
          listable: hidden
          instructions_position: above
          max_files: 1
          container: assets
      -
        handle: image_position_9
        field:
          multiple: false
          clearable: false
          searchable: false
          taggable: false
          push_tags: false
          cast_booleans: false
          default: right
          display: 'Image Position 9'
          type: select
          icon: select
          width: 33
          listable: hidden
          instructions_position: above
      -
        handle: title_10
        field:
          input_type: text
          antlers: false
          display: 'Title 10'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: content_10
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: 'Content 10'
          type: markdown
          icon: markdown
          listable: hidden
          instructions_position: above
      -
        handle: photo_10
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          show_filename: true
          display: 'Photo 10'
          type: assets
          icon: assets
          width: 66
          listable: hidden
          instructions_position: above
          max_files: 1
          container: assets
      -
        handle: image_position_10
        field:
          options:
            right: Right
            left: Left
          multiple: false
          clearable: false
          searchable: false
          taggable: false
          push_tags: false
          cast_booleans: false
          default: left
          display: 'Image Position 10'
          type: select
          icon: select
          width: 33
          listable: hidden
          instructions_position: above
  sidebar:
    display: Sidebar
    fields:
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
  meta:
    display: Meta
    fields:
      -
        handle: template
        field:
          type: template
          display: Template
          default: default
          width: 50
      -
        handle: page_description
        field:
          input_type: text
          antlers: false
          display: 'Page Description'
          type: text
          icon: text
          listable: hidden
      -
        handle: page_keywords
        field:
          input_type: text
          type: text
          listable: hidden
          display: 'Page Keywords'
          antlers: false
          instructions: 'Enter any specific keywords for this page. Each page will already have all global keywords.'
      -
        handle: is_hidden
        field:
          type: toggle
          instructions: 'Turn this option on if you don''t want the page to be included in the navigation menu.'
          display: 'Hide From Navigation'
```
