### DISCUSSION TITLE
Trouble with field-context

### DISCUSSION THREAD

**Discussion by jarnalyrkar** [statamic/cms#4691] [Troubleshooting]
I have a fieldset with a replicator-field, and need to check a value outside it. I found this in the documentation: https://statamic.dev/conditional-fields#field-context, and from what I can gather I only need to prefix with a "root." in order to access to the other field.

I want to show or hide fields based on the toggle-field images_instead_of_heading_text, but it doesn't work. Any suggestions?

This is the yaml-file for my fieldset:
```
title: 'Hero, Stats'
fields:
  -
    handle: title
    field:
      input_type: text
      antlers: false
      display: Title
      type: text
      icon: text
      listable: hidden
      width: 66
  -
    handle: white_background
    field:
      display: 'White background?'
      type: toggle
      icon: toggle
      width: 33
      listable: hidden
  -
    handle: text
    field:
      always_show_set_button: false
      buttons:
        - bold
        - italic
        - removeformat
        - anchor
      save_html: false
      toolbar_mode: fixed
      link_noopener: false
      link_noreferrer: false
      target_blank: false
      reading_time: false
      fullscreen: true
      allow_source: true
      enable_input_rules: true
      enable_paste_rules: true
      display: Text
      type: bard
      icon: bard
      listable: hidden
  -
    handle: image_gallery
    field:
      mode: list
      restrict: false
      allow_uploads: true
      display: 'Image Gallery'
      type: assets
      icon: assets
      listable: hidden
  -
    handle: images_instead_of_heading_text
    field:
      display: 'Images instead of heading-text'
      type: toggle
      icon: toggle
      listable: hidden
      width: 50
  -
    handle: stats_light_background
    field:
      display: 'Stats: Light Background ?'
      type: toggle
      icon: toggle
      width: 50
      listable: hidden
  -
    handle: stats
    field:
      collapse: false
      sets:
        stats:
          display: Stats
          fields:
            -
              handle: image
              field:
                mode: list
                restrict: false
                allow_uploads: true
                display: Image
                type: assets
                icon: assets
                width: 66
                listable: hidden
                max_files: 1
                instructions_position: above
                show_filename: true
                if:
                  root.images_instead_of_heading_text: 'equals true'
            -
              handle: number
              field:
                input_type: text
                antlers: false
                display: Number
                type: text
                icon: text
                listable: hidden
                width: 66
                instructions_position: above
                unless:
                  root.images_instead_of_heading_text: equals true
            -
              handle: description
              field:
                input_type: text
                antlers: false
                display: Description
                type: text
                icon: text
                listable: hidden
      display: Stats
      type: replicator
      icon: replicator
      listable: hidden
      instructions_position: above

```
