### DISCUSSION TITLE
How do I format a timestamp in the control-panel list?

### DISCUSSION THREAD

**Discussion by chucktrukk** [statamic/cms#4719] [Q&A] [answered]
I have a field called linked_at

```
      - handle: linked_at
        field:
          type: integer
          display: LinkedAt
          validate: required
```

How can I show this in the control-panel list as "Y-m-d"
