### DISCUSSION TITLE
Is there a way to identify the actual item in a replicator for validation?

### DISCUSSION THREAD

**Discussion by kroeker-studio** [statamic/cms#4788] [Q&A]
The following yaml-file is a fieldset loaded in an replicator called 'content'.
The field titel_des_abschnitts should be required if the toggle abschnittstitel_anzeigen is true.
Now the validation looks only for the first replicator element. But I always want the field in the same element.
Is there a way to do this?

The yaml-file:

```
title: Spalte
fields:
  -
    handle: optionen-spalte
    field:
      default: false
      display: 'Optionen anzeigen'
      type: toggle
      icon: toggle
      listable: hidden
      instructions_position: above
  -
    handle: abschnittstitel_anzeigen
    field:
      default: false
      display: 'Abschnittstitel anzeigen'
      type: toggle
      icon: toggle
      listable: hidden
      instructions_position: above
      width: 25
      if:
        optionen-spalte: 'equals true'
  -
    handle: titel_des_abschnitts
    field:
      placeholder: 'Titel des Abschnitts'
      input_type: text
      antlers: false
      display: 'Titel des Abschnitts'
      type: text
      icon: text
      listable: hidden
      instructions_position: above
      width: 75
      validate:
        - 'required_if:content.0.abschnittstitel_anzeigen,true'
      if:
        optionen-spalte: 'equals true'

...

```
