### DISCUSSION TITLE
unique_entry_values not able to update

### DISCUSSION THREAD

**Discussion by mundgold** [statamic/cms#4816] [Troubleshooting] [answered]
PHP Version | 7.4.25
Statamic 3.2.23

I have a "reihen_id-field" in my collection - the entered value has to be unique.

My Validation Rule: unique_entry_value:series,reihen_id

```
title: Series
sections:
  main:
    display: Main
    fields:
      -
        handle: reihen_id
        field:
          input_type: text
          antlers: false
          display: 'Reihen Id'
          type: text
          icon: text
          width: 25
          listable: hidden
          instructions_position: above
          validate:
            - required
            - 'unique_entry_value:series,reihen_id'
      -
```

If I create a new Entry everything works like expected. But if I update an entry I get an error-message "This value has already been taken."

Thanks for any hints!
Roland
