### DISCUSSION TITLE
Taxonomies: Topics are not being shown once the title changed

### DISCUSSION THREAD

**Discussion by ahoiroman** [statamic/cms#4860] [Q&A]
Hey there,

I am using the Cool Writings Startet Kit. Once I change the title of the Topics page (https://statamic-starter-cool-writings.netlify.app/topics/) to something else, e.g. "Themen", no content is shown in the taxonomy-list:

In the `article.yaml` the definition looks like this:

```
title: Articles
template: articles.show
layout: layout
mount: b9e4bfe3-9c12-4553-b7ef-f43c22ffaa63
taxonomies:
  - topics
revisions: false
route: '{slug}'
date: true
sort_dir: asc
date_behavior:
  past: public
  future: private
 ```

This is `topics.md`:

```
---
id: f5a53468-017e-4725-b5b6-a745df7e94cb
title: Themen
template: topics/index
updated_by: a406016b-1009-4ba7-8bae-0093c2ab1356
updated_at: 1638572051
---
```

Any ideas?
