### DISCUSSION TITLE
Problem with search index which cannot find text field in imported fieldset

### DISCUSSION THREAD

**Discussion by jensolafkoch** [statamic/cms#5260] [Troubleshooting]
I can't get a search index to work which should index fields in sets in a fieldset.

I defined the index as such in config/seacrh.php:

```
    'indexes' => [

        'artikel' => [
            'driver' => 'local',
            'searchables' => 'collection:artikel',
            'fields' => ['title'],
        ],

    ],
```

This is the part from the collection config for artikel.yaml:

```
        handle: section_aside_meta
        field:
          display: 'Sektion mit Meta-Sitebar'
          type: section
          icon: section
          listable: hidden
          instructions_position: above
      -
        import: section
        prefix: aside_meta_
```

This is the imported fieldset "section" with the first set as example:

```
title: Sektion
fields:
  -
    handle: section
    field:
      always_show_set_button: false
      sets:
        text_md:
          display: 'Markdown Editor'
          fields:
            -
              handle: text
              field:
                container: assets
                restrict: false
                automatic_line_breaks: true
                automatic_links: true
                escape_markup: false
                smartypants: false
                antlers: false
                display: Text
                type: markdown
                icon: markdown
                listable: hidden
                instructions_position: above
```

Now I want to add another field to the index definition which would index the field with the handle `text` in all sets `text_md` in the field with handle `section` in fieldset `section`. (The names here are not mine, I know that this is a bit confusing in itself.)

I tried various combinations like 'aside_meta_section_text' or 'aside_meta_section_section_text_md_text' but to no avail. The updated index always show the fieldname and a content of null, which means I didn't hit my target.

I even don't know if it's possible at all.

Any help appreciated!!

**Comment by jasonvarga** [comment]
Look in one of the content markdown files for that field. What is it named?

**Reply by jensolafkoch** [reply]
The field itself looks like this (excerpt, is quite long), but it's just the name of the whole imported field set, and using `aside_meta_section` in the index definition does not work. 

```
aside_meta_section:
  -
    type: paragraph
    content:
      -
        type: text
        text: '18 Etagen tief: Die antike Höhlenstadt Derinkuyu in Kappadokien (Türkei) ist seit 1986 UNESCO-Weltkulturerbe'
  -
    type: set
    attrs:
      values:
        type: figure
        image: Hoehlenstadt_Derinkuyu-AdobeStock.jpeg
        caption: 'Die Höhlenstadt Derinkuyu ist riesig. Gefunden wurde sie zufällig. Foto: AdobeStock'
  -
    type: paragraph
    content:
      -
        type: text
        text: "Der Mann wollte eigentlich nur sein Haus renovieren. Beim Versuch, in seinem Keller eine Wand einzureißen,\_"
      -
        type: text
        marks:
          -
            type: bold
        text: 'stand er plötzlich vor einem gigantischen Tunnelsystem'
      -
        type: text
        text: ', das zu einer unterirdischen Stadt gehörte. So geschehen vor knapp 60 Jahren im türkischen Kappadokien.'
  -
```
