### DISCUSSION TITLE
issue with conditional field dependent on nested grid value

### DISCUSSION THREAD

**Discussion by fredbouin** [statamic/cms#5353] [Q&A]
I have this content generated with a grid
```
seat_options:
  -
    seat_type: upholstered
    price_difference: '0'
  -
    seat_type: wood
    price_difference: '100'
```
I want to show another field in my blueprint only if seat_type contains upholstered, 
I tried         
```
if:
    seat_options.seat_type: 'contains upholstered'
```
this does not work, I'm not sure what the proper syntax would be or if it is possible at all.
