### DISCUSSION TITLE
How to filter a collection by using a replicator field?

### DISCUSSION THREAD

**Discussion by sebabal** [statamic/cms#5660] [Q&A] [answered]
I have a collection with custom fields and one of those is a replicator field which contains other fields.

Here is a piece of the blueprint:

![image](https://user-images.githubusercontent.com/210946/160217617-411945e8-83da-47fe-9829-b92d3148aa68.png)

On the front end I have the listing and also a form in order to filter the results once they select the options and click "Search"

![image](https://user-images.githubusercontent.com/210946/160217700-d77be5c7-2d34-42ef-9521-3576f070590c.png)

I am failing to get a grasp on how to access those fields in order to filter by them, I can easily filter by "regular" so maybe this is not possible if use a replicator and should avoid them but wanted to check first here.

Best.

**Comment by ryanmitchell** [comment, marked as answer]
I would suggest putting the dealers into a collection and then that gives the option to filter using a query scope.

**Reply by sebabal** [reply]
> I would suggest putting the dealers into a collection and then that gives the option to filter using a query scope.

It is already a collection but even when using a query scope I am not clear from the documentation how to modify the query to filter by a replicator field, are there any examples? Are replicators basically arrays? so I am guessing I should be using whereIn method for the filter right?

**Reply by ryanmitchell** [reply]
They are arrays but I’m not sure how you are structuring things. Can you share your blueprints / collection setup?

**Reply by sebabal** [reply]
Of course sorry:

Here is a content example:

```
---
id: bfc805b5-1e26-4410-b684-3f46b7b91f76
blueprint: dealers
title: 'Specialty Hearse'
email: jim@specialtyvehiclesinc.com
address: '60 Engineers Lane East Farmingdale, New York 11735'
phone: 888-725-5185
fax: 516-349-0482
website: 'http://www.specialtyhearse.com'
coverage:
  -
    brand: federal
    states:
      - NY
      - NJ
      - TX
    region: us
    type: covering
    enabled: true
brands:
  - federal
updated_by: 961b36e6-30b7-4401-a046-3a479ffeb600
updated_at: 1643732900
logo: dealer_logos/specialty_hearse.png
type: Dealer
---
```

Here is the entire blueprint:

```
title: Dealer
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: logo
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Logo
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          folder: dealer_logos
      -
        handle: content
        field:
          type: markdown
          localizable: true
      -
        handle: email
        field:
          input_type: email
          antlers: false
          display: Email
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: address
        field:
          input_type: text
          antlers: false
          display: Address
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: toll_free
        field:
          input_type: tel
          antlers: false
          display: 'Toll Free'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: phone
        field:
          input_type: tel
          antlers: false
          display: Phone
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: fax
        field:
          input_type: tel
          antlers: false
          display: Fax
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: website
        field:
          input_type: url
          antlers: false
          display: Website
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: coverage
        field:
          collapse: false
          sets:
            covering:
              display: Covering
              fields:
                -
                  handle: brand
                  field:
                    options:
                      federal: Federal
                      eagle: Eagle
                    multiple: false
                    clearable: true
                    searchable: true
                    taggable: false
                    push_tags: false
                    cast_booleans: false
                    display: Brand
                    type: select
                    icon: select
                    listable: hidden
                    instructions_position: above
                -
                  handle: states
                  field:
                    options:
                      AL: Alabama
                      AK: Alaska
                      AZ: Arizona
                      AR: Arkansas
                      CA: California
                      CO: Colorado
                      CT: Connecticut
                      DE: Delaware
                      DC: 'District of Columbia'
                      FL: Florida
                      GA: Georgia
                      HI: Hawaii
                      ID: Idaho
                      IL: Illinois
                      IN: Indiana
                      IA: Iowa
                      KS: Kansas
                      KY: Kentucky
                      LA: Louisiana
                      ME: Maine
                      MD: Maryland
                      MA: Massachusetts
                      MI: Michigan
                      MN: Minnesota
                      MS: Mississippi
                      MO: Missouri
                      MT: Montana
                      NE: Nebraska
                      NV: Nevada
                      NH: 'New Hampshire'
                      NJ: 'New Jersey'
                      NM: 'New Mexico'
                      NY: 'New York'
                      NC: 'North Carolina'
                      ND: 'North Dakota'
                      OH: Ohio
                      OK: Oklahoma
                      OR: Oregon
                      PA: Pennsylvania
                      RI: 'Rhode Island'
                      SC: 'South Carolina'
                      SD: 'South Dakota'
                      TN: Tennessee
                      TX: Texas
                      UT: Utah
                      VT: Vermont
                      VA: Virginia
                      WA: Washington
                      WV: 'West Virginia'
                      WI: Wisconsin
                      WY: Wyoming
                    multiple: true
                    clearable: true
                    searchable: true
                    taggable: false
                    push_tags: false
                    cast_booleans: false
                    display: States
                    type: select
                    icon: select
                    listable: hidden
                    instructions_position: above
                -
                  handle: region
                  field:
                    options:
                      us: 'United States'
                      canada: Canada
                      Europe: Europe
                    multiple: false
                    clearable: true
                    searchable: true
                    taggable: false
                    push_tags: false
                    cast_booleans: false
                    display: Region
                    type: select
                    icon: select
                    listable: hidden
                    instructions_position: above
          display: Coverage
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: type
        field:
          options:
            Dealer: null
            'Body Shop': null
          inline: false
          cast_booleans: false
          display: Type
          type: radio
          icon: radio
          listable: hidden
          instructions_position: above
          validate:
            - required
      -
        handle: brands
        field:
          type: terms
          taxonomies:
            - brands
          display: Brands
          mode: select
          instructions_position: above
          listable: hidden
          create: true
          validate:
            - required
```
