### DISCUSSION TITLE
overriding fields from fieldset

### DISCUSSION THREAD

**Discussion by dadaxr** [statamic/cms#5737] [Q&A] [answered]
After importing all fields from a fieldset in a blueprint with something like : 

```
...
      -
        import: bubble_picture
        prefix: hero_
...
```

Is is possible to override some field parameters (like "instruction") inside the blueprint ? 

For instance, I have the "bubble_picture" fieldset defined as : 
```
title: 'bubble picture'
fields:
  -
    handle: picture
    field:
      mode: grid
      container: assets
      restrict: false
      allow_uploads: true
      show_filename: true
      max_files: 1
      display: picture
      type: assets
      icon: assets
      listable: hidden
      instructions_position: above
      read_only: false
      width: 75
      instructions: test
  -
    ... (other fields)
```

Inside my blueprint, I tried to redefined the "imported" field ie : 
```
      ...
      -
        import: bubble_picture
        prefix: hero_
      -
        handle: hero_picture
        field: bubble_picture.picture
        config:
          instructions: 'test-override'
     ...
```

But this lead to a 500 error... 

Of course, importing field one by one ( ie https://statamic.dev/blueprints#customizing-fields ) is working ... but dont want to import all fields by hand.

Any ideas :) ?
