### DISCUSSION TITLE
Form with Collection linked to Select menu rendering as empty text input

### DISCUSSION THREAD

**Discussion by seventyoneindustries** [statamic/cms#5804] [Troubleshooting] [answered]
Hi all, I'm new to Statamic, and have been trying it out for a couple of potential projects. I see the potential, but have run into an issue that I can't seem to figure out or find any answers to online. It could be that I just am misunderstanding things. 

I am setting up a custom quote form. I have set up collections for the various options. For example, there are collections for Enclosures, UV Printing Services, and Engraving Services. 

The form blueprint has Collection: Entries fields set up for these, with the assumption those fields, when rendered on the front end, would populate select menus with the collection entries. 

What I am seeing is that when I go to the form on the front end of the site, those fields are just blank text input fields. I've tried it with Collection: Entries and Entry select mapped to the collection with the same results. If I just do a basic select field type with a couple static values, it renders the select just fine. So, something is amiss with mapping collections to select menus on my installation, it would seem. 

I thought maybe the starter kit I was using (Peak) was lacking some templates to render those fields, so I tried another theme with the same results. I have Statamic running on my personal cPanel server, I have run npm commands to generate the css and js files. 

Here is an excerpt from the form blueprint yaml ( created entirely on the front end):

```
      handle: select_an_enclosure
        field: collection.collection
        config:
          mode: select
          display: 'Select an Enclosure'
          validate: required
          max_items: 1
          create: false
          collections:
            - inventory
```

I am sure I am overlooking some simple thing, but I am hoping someone here can nudge me in the right direction. 

Thanks!

-Bret
