### DISCUSSION TITLE
taxonomy_terms_field not accepting multiple taxonomies?

### DISCUSSION THREAD

**Discussion by stephenmeehanuk** [statamic/cms#5980] [Troubleshooting] [answered]
Is `taxonomy_terms_field` limited to only one taxonomy? I can't get it to work with more than one taxonomy?

My fieldset looks like this:

```
title: 'Terms Products'
fields:
  -
    handle: product_taxonomy_terms_field
    field:
      mode: default
      create: false
      taxonomies:
        - p1
        - p2
        - p3
      display: Products
      type: terms
      icon: taxonomy
      listable: hidden
      instructions_position: above
      read_only: false
```
When I try to use the fieldset on a page, I see this screen.
![Screenshot 2022-05-03 at 17 14 10](https://user-images.githubusercontent.com/72254741/166493571-dbc21901-984f-4a77-bfe0-94cf92e38a54.png)

laravel.log show this (only shown first few lines):

```
[2022-05-03 16:17:05] local.ERROR: Call to a member function visible() on null {"userId":"a22581f2-580e-4041-81e2-e343df73d946","exception":"[object] (Error(code: 0): Call to a member function visible() on null at /Users/xxxxxx/Repositories/lbf-2022/vendor/statamic/cms/src/Http/Resources/CP/Concerns/HasRequestedColumns.php:26)
[stacktrace]
#0 [internal function]: Statamic\\Http\\Resources\\CP\\Taxonomies\\Terms->Statamic\\Http\\Resources\\CP\\Concerns\\{closure}('taxonomy', 1)
#1 /Users/xxxxxx/Repositories/lbf-2022/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(721): array_map(Object(Closure), Array, Array)
#2 /Users/xxxxxx/Repositories/lbf-2022/vendor/statamic/cms/src/Http/Resources/CP/Concerns/HasRequestedColumns.php(27): Illuminate\\Support\\Collection->map(Object(Closure))
#3 /Users/xxxxxx/Repositories/lbf-2022/vendor/statamic/cms/src/Http/Resources/CP/Taxonomies/Terms.php(53): Statamic\\Http\\Resources\\CP\\Taxonomies\\Terms->visibleColumns()

...

```

```
Statamic 3.3.10 Pro
Laravel 9.5.1
PHP 8.0.8
simonhamp/statamic-heroicons 1.0.1
statamic/collaboration 0.4.0
```
