### DISCUSSION TITLE
how to specify additional language home

### DISCUSSION THREAD

**Discussion by breizhwave** [statamic/cms#6027] [General]
Hi followed the procedure for converting a site to multi site

works perfectly for all pages

but how do I specify the root page ? home page for the new language ? internal pages url work but not the home, I see you specify home page with id home but I suppose you can't use 2 home id ? 

thanks for the answers

**Comment by joshuablum** [comment]
Hey Erwan!

If you're using a multi-site setup and you have localized entries the "home" page just stays that _one_ entry. But only its _origin_ entry has the id `home` and the localized ones just use a UUID. With the `origin` value you reference the id of the, well, origin entry which in this case is `home` (usually a UUID but `home` is _special_).  If you switched from a single-site to a multi-site setup you may have to update that entry manually.

The YAML front-matter of your `home` entry should something like this:
Origin entry (e.g. English)
```yaml
---
id: home
blueprint: pages
title: Home
template: default
---
```

Localized entry (e.g. German)
```yaml
---
id: c6212a03-19fe-45c3-84ea-5b803db6ae0a
origin: home
---
```

More on that in the [docs](https://statamic.dev/tips/localizing-entries#entry-origins)

Hope that helps! :)
