### DISCUSSION TITLE
Issue with form?

### DISCUSSION THREAD

**Discussion by stephenmeehanuk** [statamic/cms#6042] [Troubleshooting]
Hi

Spotted this error in `laravel.log`
```
[2022-05-16 09:38:13] local.DEBUG: Cannot render an object variable as a string: {{ placeholder }}  
```
I figured it's related to a handle called `{{ placeholder }} `, but this handle isn't part of the current view template?

The error only appears when there's a form on the page. And it repeats based on the number of fields the form has.

As a test, I created this basic, one field form, `resources/blueprints/forms/test.yaml`

```
sections:
  main:
    display: Main
    fields:
      -
        handle: text_field
        field:
          input_type: text
          antlers: false
          display: 'Text Field'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          read_only: false

```
I add the form to my view
```
  {{ form:test }}

  {{ /form:test }}
 ```

If remove `{{ form:test }}{{ /form:test }}` the error goes away?

It's odd because the error references a handle that's not being used by the view?

As a final test I cleared everything from the  `layout` except ` {{ template_content }}`. Then removed everything from the view, except `{{ form:test }}{{ /form:test }}` then I ran `php artisan optimize:clear`, the error still persists?

I've tried this on a fresh install and there's no error. I'm running the same version of Statamic 

```
Statamic 3.3.11 Pro
Laravel 9.12.2
PHP 8.0.8
```

Is there anything else I can try to debug this?

**Comment by joshuablum** [comment]
Hi @stephenmeehanuk,

My guess would be that the `{{ placeholder }}` handle comes from the default form fields. So it doesn't have to be in your template explicitly to show you that log message.

Have a look at https://github.com/statamic/cms/pull/2354.
Form fields have a conditional display of the `{{ placeholder }}` handle.

```html
<input type="text" name="{{ handle }}" {{ if placeholder }}placeholder="{{ placeholder }}"{{ /if }}{{ if old }}value="{{ old }}"{{ /if }}>
```

Also, Laravel uses the [RFC 5424 specification](https://tools.ietf.org/html/rfc5424) for logging messages.
It has different levels that are as follow.
1. emergency
2. alert
3. critical
4. error
5. warning
6. notice
7. info
8. debug

As you can see, you got a `debug` message logged which is the lowest level. So there is nothing necessarily wrong.
More on that in the Laravel [docs](https://laravel.com/docs/9.x/logging#log-levels)

Hope that helps!

**Reply by stephenmeehanuk** [reply]
Ah, good guess!

I created another test form, added some placeholder text and there's no error. Great... kinda. 

However, I can't get the `{{ if placeholder }}placeholder="{{ placeholder }}"{{ /if }}` to work?

If there's no placeholder text the `{{ if placeholder }}` check fails to work. I feel like the `{{ if placeholder }}` check shouldn't be required in the first place, if there's no placeholder.

You're right, `debug` is the lowest bug report, but I'd rather there be no messages! :)

**Comment by stephenmeehanuk** [comment]
Got a bit further with this...

On a **fresh install** this works great, there's no `local.DEBUG` message when `text_field` doesn't have a `placeholder`

```
// resources/blueprints/forms/test.yaml
sections:
  main:
    display: Main
    fields:
      -
        handle: text_field
        field:
          input_type: text
          antlers: false
          display: 'Text Field'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          read_only: false

```

```
{{ form:test }}
    {{ fields where="handle:text_field" }}
        {{ placeholder }}
    {{ /fields  }}
{{ /form:test }}
```

But, on another install - A site I upgraded to 3.3.11, 

```
// resources/blueprints/forms/test_form.yaml
sections:
  main:
    display: Main
    fields:
      -
        handle: text_field
        field:
          input_type: text
          antlers: false
          display: 'Text Field'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          read_only: false

```

```

{{ form:test_form }}
    {{ fields where="handle:text_field" }}
        {{ placeholder }}
    {{ /fields  }}
{{ /form:test_form }}
```

this generates an error
```
local.DEBUG: Cannot render an object variable as a string: {{ placeholder }}  
```

Is there a known reason why this is happening? It's worth mentioning, when `placeholder` exists it is shown. It just triggers a debug message when it's not there?

Both test forms only have a single text field. Both sites running locally on Valet
```
Statamic 3.3.11 Pro
Laravel 9.12.2
PHP 8.0.8
```
