### DISCUSSION TITLE
Custom field to set value of another field

### DISCUSSION THREAD

**Discussion by georgobermayr** [statamic/cms#6077] [Q&A]
Hi,

I try to create a custom field that extends a toggle. Once the toggle is checked, it should set the value of another field by fetching data from an internal API endpoint. My blueprint looks like this:

```yml 
        handle: overwrite_cast
        field:
          field_name: cast
          default: false
          display: 'Overwrite Cast'
          type: overwrite_production_data
          icon: toggle
          listable: hidden
          instructions_position: below
          read_only: false
      -
        handle: cast
        field:
          collapse: true
          sets:
            cast_member:
              display: 'Cast Member'
              fields:
                -
                  import: cast
          display: Cast
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above
          read_only: false
          if:
            overwrite_cast: 'equals 1'
```

So my custom filed is named `overwrite_production_data` and the vue.js component looks like this:

```vue
<template>

    <div>
        <Toggle :value="value" @input="update" />
    </div>

</template>

<script>
const Toggle = Vue.component('toggle-fieldtype')

export default {

    mixins: [Fieldtype],
    inject: ['storeName'],

    components: {
        Toggle,
    },

    mounted() {
        this.fieldName = this.config.field_name;
        this.collection = 'production';
        this.production = this.$store.state.publish[this.storeName].values.production[0]
        this.endpoint = `https://my-site.test/api/collections/${this.collection}/entries/raw/${this.production}`;
    },

    watch: {
        value: function (value) {
            if (value) {
                this.fetchData();
            }
        }
    },

    methods: {
        fetchData() {
            this.$axios.get(this.endpoint).then(response => {
                const data = response.data[this.fieldName]

                this.$store.commit('publish/base/setFieldValue', {
                    handle: this.fieldName,
                    user: '',
                    value: data,
                })
            });
        },
    },
};
</script>
```

Basically on toggle I call a custom endpoint that delivers the data and then I commit an event to the Vuex store and set the value of the Replicator field. The data I receive is correct and has the data structure the Replicator field excepts. 

The value of the Replicator field looks fine after I commit the new value via Vuex. However the value is not displayed in the Control panel. I have to save the page manually and reload it in order to view the new value of the field. 

I think the commit to the Vuex store is not doing everything the Replicator field expects in order to view the data. The Replicator component seems to do a bit more, when a new entry is added via the user interface. Is there any way to trigger this chain of events? Or is there another approach to set the value of a field once something happens in another field?

Thanks,
Georg
