### DISCUSSION TITLE
Using `nav`, can I access `previous_page` or `next_page` ?

### DISCUSSION THREAD

**Discussion by austriker27** [statamic/cms#6100] [Q&A] [answered]
Okay, so I've got a bit of an odd one I've been stumped on - I'm trying to use `previous_page` and `next_page` in a navigation. 

I've got a list of pages in the navigation in the CP, and a navigation element on the page that is for "next" and "previous" page.

`page_nav.yaml`:
```yaml
tree:
  -
    id: dab76d62-5986-44d9-8743-766ed4e067d7
    entry: home
  -
    id: 67e182f7-be23-4ca4-8517-28936d8cef0e
    entry: 351403b5-9909-40b8-bffb-307ac7586c53
  -
    id: 96b2131e-bbcf-4830-acd5-79bddefd05ca
    entry: 69c7dfd5-74ed-46c8-b393-217d241ba8df
  -
    id: 86305995-1f04-4859-a11e-503af40b4805
    entry: 4e541678-29ab-4940-93a4-279e6e88c999
```

What's odd is that `next_page` seems to be working, but I cant find anything about it in the docs so I think it's probably just an undocumented fluke. (previous page is not working)

```handlebars
{{ nav:page_nav as="page_nav" include_home="true" }}


<a aria-label="Go to {{ prev_page:title }} Page"
    href="{{ prev_page:url }}"
    class="link opacity-70 hover:opacity-100">
        {{ svg src="arrow-left" class="h-4 w-4 shrink-0" }}
</a>

{{ /nav:page_nav }}

```

I've tried `previous_page` and `prev_page` and a bunch of other solutions including use local variables for the `total_pages` but can't get this working.

Example of going down the local variable rabbit hole:
```handlebars
{{ previous_page_number = {page_number | subtract:1} }}
{{ previous_page_url = page_nav:previous_page_number:url }}
```
