### DISCUSSION TITLE
SyntaxError | Unexpected Identifier issue after 3.3.7 version upgrade

### DISCUSSION THREAD

**Discussion by andrew-ireland** [statamic/cms#6115] [Troubleshooting] [answered]
I'm running into an issue on  a client site when I update them to 3.3.7 or newer.

When saving pages in the CP, I'm seeing 'SyntaxError | Unexpected Identifier', and can't save the page — If I downgrade functionality returns to normal.

No message in my logs, but If I turn on the debug bar I see: 

```
LOG.warning: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /Users/[user]/www/[site]/vendor/statamic/cms/src/Fieldtypes/Bard.php on line 372
```
...I'm guessing this is probably related. 

I have the following in use in my 'common.yaml' fieldset — am I missing something here?
```
    handle: text_basic
    field:
      buttons:
        - bold
        - removeformat
        - anchor
      type: bard
      save_html: false
      toolbar_mode: fixed
      link_noopener: false
      link_noreferrer: false
      target_blank: false
      reading_time: false
      fullscreen: true
      allow_source: true
      localizable: true
      listable: hidden
      display: Text
```

No luck working it out so far... posting here in the hope someone recognises the issue 🥲

**Comment by afonic** [comment]
It may be caused by an addon. Can you post the results of `php please support:details` ?

**Comment by edalzell** [comment]
Which field is causing the issue? To determine, slowly take fields out of the blueprint and content and try saving.

**Comment by andrew-ireland** [comment]
Thank you both for your suggestions!

Definitely wasn't an addon (disabled the few addons in place, which didn't resolve the issue).

Ended up doing the slow but sure needle in a haystack process of taking fields out of the blueprint as Erin suggested... Seems like a button component  within the page_builder is the culprit (this site is built on Peak, so it's pretty much the standard button component from Peak).

I believe this line in the 'components__button.yaml' blueprint is causing the problem (If I remove it, the errors resolves):
```
      if:
        link_type: 'equals entry'
```

No idea why this isn't working now, the show/hide conditional renders correctly in the CMS. Seems to be a regression? 

The flow to get here as follows:

[MAIN CALL TO ACTION BLOCK/COMPONENT.yaml]
```
title: 'Call to action'
fields:
  -
    handle: title
    field:
      input_type: text
      type: text
      localizable: true
      listable: hidden
      display: Title
      instructions: 'The title you want to display above the text.'
      validate:
        - required
  -
    handle: text
    field: common.text_plain
    config:
      instructions: 'The text you want to display above the button.'
      validate:
        - required
  -
    handle: button_section
    field:
      type: section
      display: Button
  -
    import: components__buttons
```

[BUTTONS COMPONENT components__buttons.yaml]
```
title: Buttons
fields:
  -
    handle: buttons
    field:
      fields:
        -
          import: components__button
      mode: stacked
      add_row: 'Add button'
      max_rows: 1
      reorderable: true
      type: grid
      localizable: false
      listable: hidden
      display: Buttons
      instructions: 'Add a button.'
      replicator_preview: false
```
[BUTTON COMPONENT (EXCERPT OF SYNTAX ERROR) components__button.yaml]

```
  -
    handle: entry
    field:
      max_items: 1
      mode: default
      type: entries
      instructions: 'Choose the collection entry you want to link.'
      localizable: false
      listable: false
      display: Entry
      replicator_preview: false
      validate:
        - 'required_if:{this}.link_type,entry'
      if:
        link_type: 'entry'
  -
    handle: url
    field:
      placeholder: 'https://site.com'
      input_type: url
      type: text
      instructions: 'The URL you want to link.'
      localizable: false
      listable: false
      display: URL
      validate:
        - 'required_if:{this}.link_type,url'
      if:
        link_type: 'url'
```

CMS visual reference of component:
<img width="868" alt="171072125-0f67e207-accd-4d7b-b18a-8f3707980065" src="https://user-images.githubusercontent.com/18650897/171072997-177776a3-fb8f-4499-82d5-9b574a41bf23.png">
