### DISCUSSION TITLE
exclude Pages item from partial:nav

### DISCUSSION THREAD

**Discussion by martinoak** [statamic/cms#6313] [Troubleshooting] [answered]
Hello,
I need to add a Page that contains information about Cookies usage. Everything was fine, until I struggled to remove the page from navigation.

The whole navigation is shown as
```
<div class="uk-margin-remove">
    {{ partial:nav }}
</div>
```

and the page I want to exclude is called **Cookies**. I tried everything I could think of - creating a navigation that has links to the pages and then tried to do `exclude="cookies"`; I also tried adding the toggle _exclude_from_nav_ and then do `{{ partial:nav exclude_from_nav:not="true" }}` and other stuff.

Anyone got a hint?
Thanks.

EDIT: I must conserve `{{ partial:nav }}` navigation type.

EDIT2: 
_cookies.md_ page:
```
---
id: 8df2d5ab-c22f-4a3f-9b55-c9be91286847
blueprint: pages
title: Cookies
template_field: cookies
updated_by: ###
updated_at: ###
template: cookies
content:
  -
    type: heading
    attrs:
      level: 1
    content:
      -
        type: text
        text: 'Cookies files'
---
```
and the page itself is generated by a JS file.
