### DISCUSSION TITLE
How to apply a "doesn't contain" modifier and how to apply it to a 2-level deep multidim array

### DISCUSSION THREAD

**Discussion by mangrovestudios** [statamic/cms#6433] [Q&A]
Hi there, this is a two-part question regarding display in antlers. I'm using the Simple Commerce add-on. I have a product with variants like so:

```
product_variants:
  variants:
    -
      name: Size
      values:
        - S
        - M
  options:
    -
      key: S
      variant: S
      original_price: 4990
    -
      key: M
      variant: M
      original_price: 0
```

I would like to condition content on the front-end based upon the existence of `0` in the product's variants' options `original_price` fields. For that, I would imagine something like this:

`if product_variants:options:original_price | contains:0`

How could I achieve that? Ie. apply the `contains` modifier to an array of _plucked_ `original_prices`.

Additionally, is there a way to effect a _doesn't contain_ modifier? Something akin to `!contains`?
