### DISCUSSION TITLE
Dynamically load partials

### DISCUSSION THREAD

**Discussion by iannngit** [statamic/cms#6531] [Q&A] [answered]
Blueprint
```
content_modules:
  -
    type: headline_row
    headline: 'Our expertise'
    content: ...
    enabled: true
  -
    type: division_row
  -
    type: ..._row
```

Antlers
```
{{ content_modules }}
    {{ if type == 'headline_row' }}
        {{ partial:if_exists src="partials/headline_row" }}
    {{ elseif type == 'division_row' }}
        {{ partial:if_exists src="partials/division_row" }}
    {{ /if }}
{{ /content_modules }}
```

I wonder if there would be a better way to load partials dynamically please? Can I use `type` in `src` param? Like,
```
{{ partial:if_exists src="partials/the_type_goes_here" }}
```

Thank you 😄
