### DISCUSSION TITLE
Why is my checkboxes accepted validation not working?

### DISCUSSION THREAD

**Discussion by Sennik** [statamic/cms#6873] [Troubleshooting] [answered]
Why is accepted not working on my checkbox?
```
handle: terms_en_conditions
field:
    inline: false
    options:
        terms_and_conditions_accepted: "I have carefully read and I accept the terms & conditions."
    display: 'Terms & Conditions'
    type: checkboxes
    icon: checkboxes
    listable: hidden
    instructions_position: above
    visibility: visible
    always_save: false
    validate:
      - accepted
```
'required' is working BUT...

When I have multiple options (checkboxes)  and i choose 'required' they are validated together like a radio button list: One of the options selected is Ok for Statamic while I want them validated both seperately.
