### DISCUSSION TITLE
Looking for advice on how to sort collection titles by natsort on the CP

### DISCUSSION THREAD

**Discussion by beatwiz** [statamic/cms#6929] [Q&A] [answered]
Hi guys!
What would be the best approach to implement natsort on the CP considering I have collection titles: Title 01, Title 10, Title 02?
Thanks in advance

**Comment by jasonvarga** [comment, marked as answer]
You might also be able to use the new computed values feature. https://statamic.dev/computed-values

Make a computed value that pulls the number out of the title and use that field for sorting.

```php
// AppServiceProvider.php boot method

Collection::computed('numbered', 'order', function ($entry) {
    return (int) (string) str($entry->title)->afterLast(' ');
});
```

Tell the collection to sort by that field.

```yaml
# content/collections/collectionname.yaml

sort_by: order
```

Optionally create a computed field in your blueprint that you could use to display the column in the listing:

```yaml
  -
    handle: order
    field:
      type: integer
      visibility: computed
      listable: visible
```
