### DISCUSSION TITLE
Control panel fails to show singular taxonomy term field in list

### DISCUSSION THREAD

**Discussion by martbock** [statamic/cms#6942] [Troubleshooting] [answered]
I have a collection with a taxonomy term field using `max_items: 1` as a limit. When I create an entry, Statamic will store the term value as a string because of the limit. The view in the control panel listing all entries for the collection then fails to render if I select the term field as a column to show.

> foreach() argument must be of type arraylobject, string given

The control panel's list view seems to expect a list of terms and not a single one. The edit view will however save a string instead of a list if `max_items: 1` is present in the blueprint.

What am I doing wrong? Could this be a bug?

<details>
<summary>Expand for config excerpts</summary>

`content/collections/partners.yml`:
```yml
title: Partners
template: partners/show
layout: layout
mount: 1392
taxonomies:
  - partner_categories
revisions: false
route: '{mount}/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
```

`resources/blueprints/collections/partners/partners.yml`:
```yml
...
- handle: partner_categories
  field:
    type: terms
    taxonomies:
      - partner_categories
    display: Category
    mode: select
    instructions_position: above
    listable: hidden
    visibility: visible
    always_save: false
    max_items: 1
    create: false
```

`resources/blueprints/taxonomies/partner_categories/partner_category.yml`:
```yml
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: content
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          type: markdown
          icon: markdown
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          validate:
            - required
title: Partner Categories

```

Entry (using Eloquent driver, thus JSON and not YAML):
```json
{
    "partner_categories": "foo",
    ...
}
```
</details>
