### DISCUSSION TITLE
Listing Globals with Field-sets Display Name

### DISCUSSION THREAD

**Discussion by arslancb** [statamic/cms#7248] [Q&A]
Hi, 

I have created a Global with Pricing Plans so that I can use it across the website. 

I have used fieldsets as feature lists. 

I can list the values like this 

  
```
{{ foreach:pricing_features }}

  {{ if key | contains:standard }}
    {{ key }}: {{ value }}<br>
  {{ /if }}

{{ /foreach:pricing_features }}
```

but I do not know how to display the Name of the field for example I can print "1000GB" but I cannnot get "Bandwidth"

I hope I mentioned the required info

## Globals pricing_features.yaml
```
title: 'Pricing Features'
data:
  standard_bandwidth: '1000'
  standard_tv_apps: 'No'
  standard_number_of_content: '1000'
  standard_concurrent_users: '1000'
  standard_monthly_bandwidth: '1000'
  standard_storage: '1000'
  standard_number_of_administrators: '1000'
  standard_movie_manager: 'no'
  pro_bandwidth: '2000'
  pro_tv_apps: 'No'
  pro_number_of_content: '2000'
  pro_concurrent_users: '2000'
  pro_monthly_bandwidth: '2000'
  pro_storage: '2000'
  pro_number_of_administrators: '2000'
  pro_movie_manager: 'no'
  enterprise_bandwidth: '3000'
  enterprise_tv_apps: 'No'
  enterprise_number_of_content: '3000'
  enterprise_concurrent_users: '3000'
  enterprise_monthly_bandwidth: '3000'
  enterprise_storage: '3000'
  enterprise_number_of_administrators: '3000'
  enterprise_movie_manager: 'no'

```

## Fieldset pricing_features.yaml
```
title: 'Pricing Features'
fields:
  -
    handle: bandwidth
    field:
      input_type: text
      antlers: false
      display: Bandwidth
      type: text
      icon: text
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
      width: 50
  -
    handle: tv_apps
    field:
      options:
        - 'No'
        - 'Yes'
      inline: true
      cast_booleans: true
      default: '0'
      display: 'TV Apps'
      type: radio
      icon: radio
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
      width: 50
  -
    handle: number_of_content
    field:
      input_type: text
      antlers: false
      display: 'Number of Content'
      type: text
      icon: text
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
  -
    handle: concurrent_users
    field:
      input_type: text
      antlers: false
      display: 'Concurrent Users'
      type: text
      icon: text
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
  -
    handle: monthly_bandwidth
    field:
      input_type: text
      antlers: false
      display: 'Monthly Bandwidth'
      type: text
      icon: text
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
  -
    handle: storage
    field:
      input_type: text
      antlers: false
      display: Storage
      type: text
      icon: text
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
  -
    handle: number_of_administrators
    field:
      input_type: text
      antlers: false
      display: 'Number of Administrators'
      type: text
      icon: text
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
  -
    handle: movie_manager
    field:
      options:
        'yes': 'Yes'
        'no': 'No'
      inline: true
      cast_booleans: false
      default: 'no'
      display: 'Movie Manager'
      type: radio
      icon: radio
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false

```
