### DISCUSSION TITLE
Making a Conditional Fields based on Taxonomy value

### DISCUSSION THREAD

**Discussion by bomshteyn** [statamic/cms#7546] [Q&A] [answered]
I am trying to make a field conditional on taxonomy category selection. But can't get it to work, the fields just stay hidden no matter what i select in the taxonomy select field.

Here is my yaml file:
```yaml
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: content
        field:
          type: markdown
          localizable: true
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
      -
        handle: date
        field:
          type: date
          required: true
          validate:
            - required
      -
        handle: lesson_type
        field:
          type: terms
          taxonomies:
            - lesson_type
          display: 'Lesson Type'
          mode: select
          instructions_position: above
          listable: hidden
          visibility: visible
          create: false
          validate:
            - required
          max_items: 1
      -
        handle: video
        field:
          display: Video
          type: video
          icon: video
          listable: hidden
          instructions_position: above
          visibility: visible
          validate:
            - required
            - sometimes
          if:
            lesson_type: 'equals Video'
      -
        handle: audio
        field:
          mode: list
          container: files
          restrict: true
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Audio
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          validate:
            - sometimes
            - required
          if:
            lesson_type: 'equals Audio'
title: Lesson
```
