### DISCUSSION TITLE
Customising the Bard nodes

### DISCUSSION THREAD

**Discussion by sptv2reg** [statamic/cms#7743] [Q&A] [answered]
The Bard functionality is excellent and the best block editor experience I've seen around. 

I wonder how hard it would be to introduce the possibility of customising the preview content in the collapsed node?

![image](https://user-images.githubusercontent.com/103186488/226920083-e0ba0751-4b70-491d-bbcc-522820c05e9e.png)

Ideally it would be great if you could grab the node content and transform it into some html, for example if the node contained an image, I could chose to display it as a small icon. If it's a timeline like above, I could grab a few entries and display those in a compact nice way.

In the most elegant solution we could even remove all the standard styling and render it almost wysiwyg wise (clicking it would still open up the standard view with fields, etc.)

**Comment by joshuablum** [comment, marked as answer]
Hey @sptv2reg,

Having a full-fledged and maybe even rendered preview is not (yet) possible.
It's however possible to have a preview text by setting the `replicator_preview` to `false` on all the fields and then have _one_ text field that essentially works as something like the `replicator_preview_text`.

Not the most elegant solution but it works.

And those "Bard nodes" you're referring to are sets of fields inside of the [Replicator fieldtype](https://statamic.dev/fieldtypes/replicator).

So in your case you might have a `timeline.yaml` with a few fields inside.
Set `replicator_preview: false` for all fields except for one text field like so:
```yaml
-
  handle: title_text
  field:
    replicator_preview: false
    # ...
-
  handle: subtitle_text
  field:
    replicator_preview: false
    # ...
-
  handle: image
  field:
    replicator_preview: false
    # ...
-
  handle: replicator_preview_text
  field:
    input_type: text
    type: text
    display: "Replicator preview"
    instructions: "The text you want to display for the Replicator preview."
```

That would look something like this:
![CleanShot 2023-03-27 at 3 04 00](https://user-images.githubusercontent.com/3824203/227946905-dced3813-429c-455e-a090-67f195a91d6a.png)

There are a few issues in the [statamic/ideas](https://github.com/statamic/ideas/issues) repo related to this.
- https://github.com/statamic/ideas/issues/249
- https://github.com/statamic/ideas/issues/735
- https://github.com/statamic/ideas/issues/774

Hope that helps :)
