### DISCUSSION TITLE
PHP version in `php please support:details` does not match CP > Utilities > PHP

### DISCUSSION THREAD

**Discussion by danielfowler** [statamic/cms#8259] [Troubleshooting]
### Bug description

I asked about this in Discord a week ago but never figured it out, and now I think it's a bug since the protocol for bug reporting involves using the `php please support:details` command instead of the PHP version recognized by the CP.

In CP > Utilities > PHP, Statamic thinks I'm running PHP 8.1.12 but I don't have that version installed anywhere on my PC.

When I `php -v` in Bash it says (correctly) that I'm on 8.2.3. This is consistent with `php please support:details` as seen below.

I'm using Valet for Windows which runs off my `path` in my system environment variables where I only have a single PHP version installed.

### How to reproduce

I'm not sure. 

### Environment

```yaml
Environment
Application Name: Brella Studio
Laravel Version: 10.13.1
PHP Version: 8.2.3
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: brella.localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.5.0 PRO

Statamic Addons
duncanmcclean/guest-entries: 3.1.0
statamic/migrator: dev-master
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

> ### Bug description
> 
> I asked about this in Discord a week ago but never figured it now, and now I think it's a bug since the protocol for bug reporting involves using the `php please support:details` command instead of the PHP version recognized by the CP.
> 
> In CP > Utilities > PHP, Statamic thinks I'm running PHP 8.1.12 but I don't have that version installed anywhere on my PC.
> 
> When I `php -v` in Bash it says (correctly) that I'm on 8.2.3. This is consistent with `php please support:details` as seen below.
> 
> I'm using Valet for Windows which runs off my `path` in my system environment variables where I only have a single PHP version installed.
> 
> ### How to reproduce
> 
> I'm not sure. 
> 
> ### Logs
> 
> _No response_
> 
> ### Environment
> 
> ```yaml
> Environment
> Application Name: Brella Studio
> Laravel Version: 10.13.1
> PHP Version: 8.2.3
> Composer Version: 2.5.4
> Environment: local
> Debug Mode: ENABLED
> URL: brella.localhost
> Maintenance Mode: OFF
> 
> Cache
> Config: NOT CACHED
> Events: NOT CACHED
> Routes: NOT CACHED
> Views: NOT CACHED
> 
> Drivers
> Broadcasting: log
> Cache: statamic
> Database: mysql
> Logs: stack / single
> Mail: smtp
> Queue: sync
> Session: file
> 
> Statamic
> Addons: 2
> Antlers: runtime
> Stache Watcher: Enabled
> Static Caching: Disabled
> Version: 4.5.0 PRO
> 
> Statamic Addons
> duncanmcclean/guest-entries: 3.1.0
> statamic/migrator: dev-master
> ```
> 
> 
> ### Installation
> 
> Fresh statamic/statamic site via CLI
> 
> ### Antlers Parser
> 
> None
> 
> ### Additional details
> 
> _No response_
