### DISCUSSION TITLE
Optional Date fieldset errors when saving new entry

### DISCUSSION THREAD

**Discussion by katwlodarczyk** [statamic/cms#8304] [Troubleshooting] [answered]
Hello, Im working in Statamic 4 and have events collection. 
Each entry has start_date (date fieldset), multi_day_event (toggle) and end_date (date fieldset).
If multi_day_event toggle is true then end_date field will appear, however if its false (so its a 1 day event), I can't save the entry and the error "end_date must be an array".
Obviously end_date is empty. 

end_date has set 
```
 validate:
     - sometimes
  if:
    multi_day_event: 'equals true'
```

I've also tried without any validation, with the same outcome.
How can I fix this so 1 day events are possible? 
Thanks!
