### DISCUSSION TITLE
Default ordering of collection columns

### DISCUSSION THREAD

**Discussion by earthwytch** [statamic/cms#8514] [Q&A] [answered]
I have seen this asked elsewhere but no answer was provided.

Can we set a default column display/order for entry tables? This is super useful when a user is selecting an entry from a list within another entry and only has the column headings to go on to work out which one to select.

![image](https://github.com/statamic/cms/assets/4753015/e5582f6a-17d6-489f-9e0e-8530f51e7af3)

**Set these globally?**
```
preferences:
  collections:
    documents:
      columns:
        - title
        - description
        - file
        - published_on
    pages:
      per_page: 500
```

Statamic 4.13.2
