### DISCUSSION TITLE
Query using nested field by Entry facade

### DISCUSSION THREAD

**Discussion by saqueib** [statamic/cms#8667] [Q&A]
how I can query entry by nested relation using Entry facade

```php
$entry = \Statamic\Facades\Entry::query()
->where(????)
```

I have data like this in yaml file, `days` is a replicator field with sessions entries 

```yaml
---
id: 5923d4f9-14fa-4012-b06c-28e0b2b190ec
blueprint: conference
title: 'Super Conference 3'
days:
  -
    id: YxernXku
    title: 'Conference Day 1'
    type: day
    enabled: true
    sessions:
      - 5cf7e474-6261-4c61-90bb-790e742950eb
      - c7dda0b8-6036-4a12-93a1-3d77d94f5a1c
      - cefd29b2-0cb1-4ce7-bdb2-938c0d8b053f
  -
    id: JesxrnXku
    title: 'Conference Day 2'
    type: day
    enabled: true
    sessions:
      - aa16074e-75dd-4444-8983-51b7eb081129
      - b2ad339f-6c37-42ee-b4f6-b24556e7b94a
      - 1dc5dafb-4d07-433c-a898-d3dbaef536e1
```

I want to get conference by session id like `5cf7e474-6261-4c61-90bb-790e742950eb` ???
