### DISCUSSION TITLE
Performance issue regarding taxonomy terms

### DISCUSSION THREAD

**Discussion by dries-dekeersgieter** [statamic/cms#8702] [Troubleshooting]
I'm facing slow performance issues while displaying 70 taxonomy terms like this:

    {{ taxonomy:brands }}
        <div>{{ title }}</div>
    {{ /taxonomy:brands }}
    
The antlers profiler warns me about slow performance regarding this line: {{ taxonomy:brands }}
19.13 MB
1.31 s
    
The taxonomy blueprint only contains a title and an asset. But even without the asset, the iteration is slow.

Term blueprint:

```

  tabs:
    main:
      display: Main
      sections:
        -
          fields:
            -
              handle: title
              field:
                type: text
                required: true
                width: 50
                validate:
                  - required
            -
              handle: logo
              field:
                max_files: 1
                mode: grid
                container: cars
                restrict: false
                allow_uploads: true
                show_filename: true
                show_set_alt: true
                type: assets
                display: Logo
                icon: assets
                width: 50
                listable: hidden
                instructions_position: above
                visibility: visible
                hide_display: false
    sidebar:
      display: Sidebar
      sections:
        -
          fields:
            -
              handle: slug
              field:
                type: slug
                required: true
                validate:
                  - required
  title: Brands

```

Profiling another taxonomy which only contains a title and 6 terms:

1.43 MB
123.71 ms

Seems way too slow for me...
