### DISCUSSION TITLE
Query entries from a related entry

### DISCUSSION THREAD

**Discussion by JeremyWorkWork** [statamic/cms#8706] [Troubleshooting] [answered]
Feel like i am just missing something really simple here, i can't seem to be able to query entries by a related entry id:
```        
Entry::whereCollection('products')
    ->whereIn('categories', ['30c98aff-3df2-4fbd-ae0f-c21d3c0542ba'])
    ->all();
```
Always returns empty result. If i just get all product entries and inspect the data, it has a categories array of category entry ids with the id i am looking for.

I have a collection called Products
I have a collection called Categories

Products has a Entry field type relation
```
  handle: categories
  field:
    type: entries
    taxonomies:
      - categories
    display: categories
    mode: default
    create: true
    collections:
      - categories
    icon: entries
    listable: hidden
    instructions_position: above
    visibility: visible
    hide_display: false
```
Data from product a markdown entry file:
```
categories:
  - 30c98aff-3df2-4fbd-ae0f-c21d3c0542ba
  - b79e58c1-0cc4-4f87-b3b0-2b5e5c18aee0
 ```
