### DISCUSSION TITLE
Importing Author Field breaks Permissions

### DISCUSSION THREAD

**Discussion by binoclard** [statamic/cms#8803] [Troubleshooting]
Hi,

Not sure, but there might be a bug with Permissions… but at the same time, I can not replicate it on a clean fresh new install.

I have a bunch of Collections, and a bunch of Groups with Permissions that grant access to the related Collection.
For example, an "Experimentation" Collection and a "Prof Experimentation" Permissions set, all on the same model:
```
prof-experimentation:
  title: 'Prof Expérimentation'
  permissions:
    - 'view experimentation entries'
    - 'edit experimentation entries'
    - 'create experimentation entries'
    - 'delete experimentation entries'
    - 'publish experimentation entries'
    - 'reorder experimentation entries'
```
Trouble is… I cannot view nor create any Entry when I impersonate one User that has such a Permission (same problem when I log in with the User credentials).

Important detail, I am not just denied access, I get an `Undefined array key "author"` error.

Unless I add     `- 'edit other authors experimentation entries'` , then I can create a new Entry.

Am I doing something wrong, or did I stumble on a weird bug?

Thanks in advance for your insight.

**Comment by binoclard** [comment]
I tend to think it is a bug, but at the Blueprint/Fieldset level.

I have a Fieldset with this:
```yaml
title: Enseignant
fields:
  -
    handle: author
    field:
      max_items: 1
      mode: select
      display: 'Enseignant·e responsable de ce rapport'
      type: users
      default: current
```

that I import in my various Collections with this:
`import: enseignant_responsable`

if I paste the Fieldset content directly in the Blueprint, it works.

And if I import the Field and not the entire Fieldset, it also works.
```yaml
fields:
    -
     handle: my_content_field
     field: enseignant_responsable.author
```
