### DISCUSSION TITLE
optional parameters

### DISCUSSION THREAD

**Discussion by ivang76** [statamic/cms#9150] [Q&A] [answered]
Hi all,
I'm wondering if should be possible to define an optional parameter, within the route field in the collection's yaml file.
For example something like this (usual laravel approach) for a specific param:

````
title: Pages
sites:
  - de
  - en
propagate: true
template: default
layout: layout
revisions: false
route: 'page/{slug}/{special_id?}'
sort_dir: asc
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
structure:
  root: true
````

the page goes in 404 if it is not present or if its value is not exactly "spacial_id" (so it is not a dynamic value). why?
I would need to use **special_id** in a _view model_ to query a model and create some logic to return value at the view...

thanks!
