### DISCUSSION TITLE
Redis causing issues with complicated form?

### DISCUSSION THREAD

**Discussion by dnrdigital** [statamic/cms#9425] [Troubleshooting]
Is it possible to turn off Redis for (eg) emails, but keep it on for everything else? And does email have its own log that I can access - if not, where would errors that occur when an email layout is generated appear?

I've been trying to debug a form that has a custom fieldtype which interacts with Stripe. On my local machine, with no Redis enabled, submitting the form generates a submission, an email (via the postmark mailer), and then redirects to Stripe checkout. 

On my dev server, with Redis enabled, the submission and redirect work perfectly, but the email sends without any {{ fields }} content - both plaintext and HTML emails come through, but without any data. Other forms on the same server, but without the custom fieldtype, work perfectly.

If I turn off Redis, everything works. But I'd like to keep Redis on for Git automation and other background tasks. I've looked in logs and used debugbar, but I don't get any errors that I can see that could explain the issue.

My best guess is that Redis allows the email to send or the redirect to Stripe to happen before the form has finished processing data. 

But I can't find much documentation either on Redis and Statamic, or on the exact process for form submission / emailing, particularly when Ajax is being used to validate / submit (I'm using a recent version of the Peak starter kit: the forms use Laravel precognition and submit with an ajax form handler, with a minor alteration so the redirect url returned by the Ajax call takes the user to Stripe Checkout.) Would really appreciate a pointer if someone's had a similar issue...

**Comment by edalzell** [comment]
So you're handling the email sending on your own?

**Comment by dnrdigital** [comment]
Nope - it's just the form implementation that doing something nonstandard with the redirect to Stripe. The email is sent via out of the box Statamic mailer / Laravel Mail Driver / Postmark.

The only other thing that's not out of the box is that I had to manually update my Peak with the changes to the form handler and emails templates required for the shift to Laravel Precognition support. As mentioned, form submission and email send all works exactly as expected with Redis turned off, but maybe there's another change that I missed that might explain it?

**Comment by dnrdigital** [comment]
Also I don't know if there's some Redis config I need to do? I have other Statamic / Peak sites with redis handling Git that are sending form emails as expected, where I've done nothing beyond enabling the redis queue in Forge and making sure the deploy scripts are all set up exactly as per the Statamic docs. These would all be pre v16 Peak and without the new form stuff mentioned above.

**Comment by edalzell** [comment]
That's very weird, let's see the form yaml and blueprint

**Reply by dnrdigital** [reply]
Posted below - any clue?

**Reply by edalzell** [reply]
That's not the form blueprint

**Reply by dnrdigital** [reply]
Oh! I thought the second one was the blueprint - It's resources > blueprints > forms > donation.yaml. 

Where should I be looking? Sorry if I'm being dense...

**Reply by edalzell** [reply]
ah ok, then I wanted to see a submission data yaml, but I don't really have an idea of why, just looking for something weird.

**Reply by edalzell** [reply]
also, is it possible you made changes and didn't restart your queue watcher?

**Reply by dnrdigital** [reply]
Difficult to share the live form data as it's full of PID stuff - can do a test later and share that.

It's quite possible I did something wrong with Redis! Can you point me at anywhere I can read up about it? In the statamic docs it only seems to come up in the sections on Git and Cacheing. I don't know if there's more I need to do in config or if it's meant to 'just work' as long as i follow those instructions. 

FWIW i also followed the instructions here: https://peak.1902.studio/other/redis-queue.html. My deploy script on Forge includes $FORGE_PHP artisan queue:restart and I definitely deployed multiple times, and also tried clearing cache etc to resolve the problem - didn't help.

**Comment by dnrdigital** [comment]
**Form yaml**

```
title: 'Donation form'
honeypot: home_address
email:
  -
    id: ls10nkx2
    to: fundraising@[clientdomain].org.uk
    cc: 'communications@[clientdomain].org.uk'
    subject: 'Donation received on the [clientname] Website'
    html: email/form_owner
    text: email/form_owner_text
```


**Blueprint**

```
tabs:
  main:
    display: Main
    sections:
      -
        display: 'Your donation'
        fields:
          -
            handle: donation
            field:
              currency_code: GBP
              mode: payment
              mode_choice: 'yes'
              recurring_interval: month
              recurring_interval_count: 1
              allow_promotion_codes: 'no'
              customer_email: email
              customer_creation: if_required
              success_url: 'entry::01557207-b501-4ec2-9b30-f370fa5ea4d0'
              success_url_include_session: 'yes'
              cancel_url: 'entry::970e8e4a-7398-46cf-b0de-96294eedbefa'
              type: stripe_checkout
              display: 'Frequency of donation'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
              products:
                -
                  id: lrasu1tc
                  product_id: prod_PBFDOejPnTfuFY
                  handle: amount_variable
          -
            handle: amount_variable
            field:
              options:
                -
                  id: Sy0yY4vV
                  number: 6
                  default: false
                -
                  id: lralvo2c
                  number: 25
                  default: false
                -
                  id: lralvqdp
                  number: 34
                  default: false
                -
                  id: lrhs7sde
                  number: 85
                  default: false
                -
                  id: ls0zekc2
                  number: 6
                  default: false
                -
                  id: ls0zelzh
                  number: 10
                  default: false
                -
                  id: ls0zen9p
                  number: 15
                  default: false
                -
                  id: ls0zeo6n
                  number: 20
                  default: false
              allow_custom: true
              custom_display: visible
              custom_min: 5
              custom_max: 500
              format: currency
              currency: GBP
              decimals: 2
              layout: custom
              url_override: true
              type: variable_number
              display: 'Donation amount'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              layout_custom: snippets/variable_number_donation_form
              validate:
                - required
              custom_placeholder: ...
      -
        display: 'Donation details'
        fields:
          -
            handle: why_are_you_donating
            field:
              options:
                own_money: 'Donating my own money'
                in_memory: 'Donating in memory of someone'
                fundraising_amount: 'Paying in a fundraising amount'
                for_organisation: 'Donating on behalf of an organisation'
                other: 'Something else'
              taggable: false
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              type: select
              display: 'What type of donation are you making?'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: in_memory_name
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Please tell us their name'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              if:
                why_are_you_donating: 'equals in_memory'
          -
            handle: organisation_name
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Name of organisation'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              if:
                why_are_you_donating: 'contains for_organisation'
          -
            handle: more_information
            field:
              antlers: false
              type: textarea
              display: 'Add more information if you would like to'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              if_any:
                why_are_you_donating: 'contains_any own_money|in_memory|for_organisation|fundraising_amount|other'
          -
            handle: gift_aid_confirmation
            field:
              options:
                'yes': 'Yes, I would like to Gift Aid this donation.'
                'no': 'No, this payment is not eligible.'
              inline: false
              type: radio
              display: 'Gift aid'
              instructions: 'Donating through Gift Aid means we can claim an extra 25p for every £1 you give at no cost to you. If you would like to Gift Aid your donation, please confirm the following statements:<br><br>✓&nbsp;&nbsp;I want to Gift Aid this donation and any donations I make in the future or have made in the past four years to [Clientname].<br><br>✓&nbsp;&nbsp;I am a UK taxpayer and understand that if I pay less Income Tax and/or Capital Gains Tax than the amount of Gift Aid claimed on all my donations in that tax year it is my responsibility to pay any difference.'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - 'required_if:why_are_you_donating,in_memory,other'
              cast_booleans: false
              if:
                why_are_you_donating: 'contains_any own_money|in_memory|other'
      -
        display: 'Your details'
        instructions: '[Clientname] takes its responsibilities in relation to data protection very seriously. Details on this form will be stored, recorded and shared in accordance with GDPR. Further information can be found in our <a class="text-white" href="/our-policies/data-protection-and-privacy-policy">data protection and privacy policy</a>.'
        fields:
          -
            handle: first_name
            field:
              input_type: text
              antlers: false
              type: text
              display: 'First name'
              width: 50
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: last_name
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Last name'
              width: 50
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: email
            field:
              input_type: email
              antlers: false
              type: text
              display: Email
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
                - email
          -
            handle: street_address
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Street address'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              width: 66
              validate:
                - required
          -
            handle: street_address_line_2
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Street address line 2'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              width: 66
          -
            handle: city
            field:
              input_type: text
              antlers: false
              type: text
              display: City
              width: 50
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: region
            field:
              input_type: text
              antlers: false
              type: text
              display: Region
              width: 50
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: postcode
            field:
              input_type: text
              antlers: false
              type: text
              display: Postcode
              width: 50
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: country
            field:
              options:
                AF: Afghanistan
                AX: 'Åland Islands'
                AL: Albania
                DZ: Algeria
                AS: 'American Samoa'
                AD: Andorra
                AO: Angola
                AI: Anguilla
                AQ: Antarctica
                AG: 'Antigua & Barbuda'
                AR: Argentina
                AM: Armenia
                AW: Aruba
                AU: Australia
                AT: Austria
                AZ: Azerbaijan
                BS: Bahamas
                BH: Bahrain
                BD: Bangladesh
                BB: Barbados
                BY: Belarus
                BE: Belgium
                BZ: Belize
                BJ: Benin
                BM: Bermuda
                BT: Bhutan
                BO: Bolivia
                BA: 'Bosnia & Herzegovina'
                BW: Botswana
                BV: 'Bouvet Island'
                BR: Brazil
                IO: 'British Indian Ocean Territory'
                VG: 'British Virgin Islands'
                BN: Brunei
                BG: Bulgaria
                BF: 'Burkina Faso'
                BI: Burundi
                KH: Cambodia
                CM: Cameroon
                CA: Canada
                CV: 'Cape Verde'
                BQ: 'Caribbean Netherlands'
                KY: 'Cayman Islands'
                CF: 'Central African Republic'
                TD: Chad
                CL: Chile
                CN: China
                CX: 'Christmas Island'
                CC: 'Cocos (Keeling) Islands'
                CO: Colombia
                KM: Comoros
                CG: 'Congo - Brazzaville'
                CD: 'Congo - Kinshasa'
                CK: 'Cook Islands'
                CR: 'Costa Rica'
                CI: 'Côte d’Ivoire'
                HR: Croatia
                CU: Cuba
                CW: Curaçao
                CY: Cyprus
                CZ: Czechia
                DK: Denmark
                DJ: Djibouti
                DM: Dominica
                DO: 'Dominican Republic'
                EC: Ecuador
                EG: Egypt
                SV: 'El Salvador'
                GQ: 'Equatorial Guinea'
                ER: Eritrea
                EE: Estonia
                SZ: Eswatini
                ET: Ethiopia
                FK: 'Falkland Islands'
                FO: 'Faroe Islands'
                FJ: Fiji
                FI: Finland
                FR: France
                GF: 'French Guiana'
                PF: 'French Polynesia'
                TF: 'French Southern Territories'
                GA: Gabon
                GM: Gambia
                GE: Georgia
                DE: Germany
                GH: Ghana
                GI: Gibraltar
                GR: Greece
                GL: Greenland
                GD: Grenada
                GP: Guadeloupe
                GU: Guam
                GT: Guatemala
                GG: Guernsey
                GN: Guinea
                GW: Guinea-Bissau
                GY: Guyana
                HT: Haiti
                HM: 'Heard & McDonald Islands'
                HN: Honduras
                HK: 'Hong Kong SAR China'
                HU: Hungary
                IS: Iceland
                IN: India
                ID: Indonesia
                IR: Iran
                IQ: Iraq
                IE: Ireland
                IM: 'Isle of Man'
                IL: Israel
                IT: Italy
                JM: Jamaica
                JP: Japan
                JE: Jersey
                JO: Jordan
                KZ: Kazakhstan
                KE: Kenya
                KI: Kiribati
                KW: Kuwait
                KG: Kyrgyzstan
                LA: Laos
                LV: Latvia
                LB: Lebanon
                LS: Lesotho
                LR: Liberia
                LY: Libya
                LI: Liechtenstein
                LT: Lithuania
                LU: Luxembourg
                MO: 'Macao SAR China'
                MG: Madagascar
                MW: Malawi
                MY: Malaysia
                MV: Maldives
                ML: Mali
                MT: Malta
                MH: 'Marshall Islands'
                MQ: Martinique
                MR: Mauritania
                MU: Mauritius
                YT: Mayotte
                MX: Mexico
                FM: Micronesia
                MD: Moldova
                MC: Monaco
                MN: Mongolia
                ME: Montenegro
                MS: Montserrat
                MA: Morocco
                MZ: Mozambique
                MM: 'Myanmar (Burma)'
                NA: Namibia
                NR: Nauru
                NP: Nepal
                NL: Netherlands
                NC: 'New Caledonia'
                NZ: 'New Zealand'
                NI: Nicaragua
                NE: Niger
                NG: Nigeria
                NU: Niue
                NF: 'Norfolk Island'
                KP: 'North Korea'
                MK: 'North Macedonia'
                MP: 'Northern Mariana Islands'
                'NO': Norway
                OM: Oman
                PK: Pakistan
                PW: Palau
                PS: 'Palestinian Territories'
                PA: Panama
                PG: 'Papua New Guinea'
                PY: Paraguay
                PE: Peru
                PH: Philippines
                PN: 'Pitcairn Islands'
                PL: Poland
                PT: Portugal
                PR: 'Puerto Rico'
                QA: Qatar
                RE: Réunion
                RO: Romania
                RU: Russia
                RW: Rwanda
                WS: Samoa
                SM: 'San Marino'
                ST: 'São Tomé & Príncipe'
                SA: 'Saudi Arabia'
                SN: Senegal
                RS: Serbia
                SC: Seychelles
                SL: 'Sierra Leone'
                SG: Singapore
                SX: 'Sint Maarten'
                SK: Slovakia
                SI: Slovenia
                SB: 'Solomon Islands'
                SO: Somalia
                ZA: 'South Africa'
                GS: 'South Georgia & South Sandwich Islands'
                KR: 'South Korea'
                SS: 'South Sudan'
                ES: Spain
                LK: 'Sri Lanka'
                BL: 'St. Barthélemy'
                SH: 'St. Helena'
                KN: 'St. Kitts & Nevis'
                LC: 'St. Lucia'
                MF: 'St. Martin'
                PM: 'St. Pierre & Miquelon'
                VC: 'St. Vincent & Grenadines'
                SD: Sudan
                SR: Suriname
                SJ: 'Svalbard & Jan Mayen'
                SE: Sweden
                CH: Switzerland
                SY: Syria
                TW: Taiwan
                TJ: Tajikistan
                TZ: Tanzania
                TH: Thailand
                TL: Timor-Leste
                TG: Togo
                TK: Tokelau
                TO: Tonga
                TT: 'Trinidad & Tobago'
                TN: Tunisia
                TR: Turkey
                TM: Turkmenistan
                TC: 'Turks & Caicos Islands'
                TV: Tuvalu
                UM: 'U.S. Outlying Islands'
                VI: 'U.S. Virgin Islands'
                UG: Uganda
                UA: Ukraine
                AE: 'United Arab Emirates'
                GB: 'United Kingdom'
                US: 'United States'
                UY: Uruguay
                UZ: Uzbekistan
                VU: Vanuatu
                VA: 'Vatican City'
                VE: Venezuela
                VN: Vietnam
                WF: 'Wallis & Futuna'
                EH: 'Western Sahara'
                YE: Yemen
                ZM: Zambia
                ZW: Zimbabwe
              taggable: false
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              type: select
              display: Country
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              width: 50
              default: GB
          -
            handle: phone
            field:
              input_type: tel
              antlers: false
              type: text
              display: Phone
              width: 66
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: communication_consent
            field:
              options:
                email: Email
                post: Post
                sms: SMS
              inline: false
              type: checkboxes
              display: "Please select all the ways you'd like to hear from us"
              instructions: 'We''ll use this information to to keep you updated on our news, events, fundraising campaigns and support we offer. You can <a class="text-white" href="mailto:communications@[clientname].org.uk?subject=Change communications preferences">change your preferences</a> at any time.'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false

```
