### ISSUE TITLE
Invalid error thrown on recursive editing check

### ISSUE THREAD

**Issue by caseydwyer** [statamic/cms#10005]
### Bug description

Believe this is a regression introduced in #9841. I've got a Runway resource using standard primary keys (ie, not UUIDs). Resource `A` belongs to resource `B`. From the publish form for `A` which has an `ID = 1`, I try to pop open a modal for the parent `B` relationship field which _**also**_ has an `ID = 1`. This throws **[the "already editing" error from line 81 in that PR](https://github.com/statamic/cms/blame/f7575f65813feed8069c781af2edef9a792fea03/resources/js/components/inputs/relationship/Item.vue#L80)**.

Not 100% sure, but I think there maybe needs to be an _additional_ check against record/collection type, instead of just the ID. Let me know if there's anything I can do to help fix that!

### How to reproduce

1. Setup Runway with two resources, `A` and `B`
2. Ensure both have an auto-incrementing `id` column
3. Create two records, one for each resource (ensure both have ID of 1)
4. Add a `belongsTo` relationship field on `A` blueprint, making `B` the parent
5. Create a `B#1` record
6. Create an `A#1` record, and assign `B#1` as the parent in the relationship field
7. Open the publish form for `A#1` and attempt to click/open the `B#1` record
8. See "already editing" toast error

### Environment

```yaml
<details>
<summary>Environment</summary>

Environment
Application Name: TF
Laravel Version: 10.48.10
PHP Version: 8.2.5
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: tf.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single, bugsnag
Mail: smtp
Queue: database
Session: database

Livewire
Livewire: v3.4.12

Statamic
Addons: 6
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.57.3 PRO

Statamic Addons
doefom/currency-fieldtype: dev-main
eminos/statamic-group: 2.0.1
eminos/statamic-tabs: 1.1.0
jacksleight/statamic-miniset: 1.1.1
statamic-rad-pack/runway: 6.7.0
statamic/eloquent-driver: 2.10.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: eloquent
Navigation Trees: file
Navigations: file
Revisions: eloquent
Taxonomies: file
Terms: file
</details>
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
