### ISSUE TITLE
Paths when accessing revisions via a linked entry (i.e. Relationship/Entries fieldtype) are incorrect

### ISSUE THREAD

**Issue by Artsiom-Kashyn** [statamic/cms#10034]
### Bug description

When accessing revisions by navigating to an entry, clicking on a linked entry (via
Relationship/Entries fieldtype), then clicking "View History" and selecting one of the revisions, the collection path points to the original collection, instead of the linked one.

For example `articles` collection has a linked `article_translations` entry (via relationship/entries
fieldtype). When opening such linked entry via `article` form and selecting one of its revisions the revision path points to the
original collection (i.e. `articles`), instead of `article_translations`

![1_article_form](https://github.com/statamic/cms/assets/81701403/54a989aa-20ff-48d4-8f4b-d940f187032a)
![2_article-translation_form](https://github.com/statamic/cms/assets/81701403/7208ff01-81d6-4971-b943-4f7312398666)
![3_article-translation_form_revisions](https://github.com/statamic/cms/assets/81701403/ad615b19-69f8-436d-9103-77ef93a8df53)

### How to reproduce

1. Create an “articles” collection
2. Configure blueprint and add Relationship/Entries (let’s keep the default handle “entries_field”)
3. Save blueprint
4. Create an “article_translations” collection
5. Edit collection settings for articles and article_translation and enable revisions
6. Create a new entry in “articles” collection
7. Create a new entry in “article_translations” collection
8. Edit and save newly created entry in “article_translations” a few times to create revision history.
9. Open an entry from “articles” collection and click “link existing item” then select an entry from “article_translations” and save and publish
10. Click on linked entry (article_translations collection)
11. Click on view history
12. Open network tab in dev tools
13. Select one of published revision history entries

Please note that the request URL directs to the “articles” collection rather than the “article_translations”.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.4
PHP Version: 8.3.3
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
URL: localhost:8000
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Cache: statamic
Database: pgsql
Logs: stack / daily, stdout
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.55.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
