### ISSUE TITLE
Field config toggles with default `true` can't be set to `false`

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#10040]
### Bug description

It's not possible to set a field config toggle value that has a default of `true` to `false` through the blueprint editor. When you save the key is removed from the YAML. I'm guessing this is caused by https://github.com/statamic/cms/pull/9685.

### How to reproduce

1. Open a blueprint
2. Add a field
3. Switch off one of the enabled toggles eg. Duplicate
4. Apply, Save, Reload
5. Open the field config, the toggle is back on

### Environment

```yaml
Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.0.1 PRO
```

### Installation

Fresh statamic/statamic site via CLI
