### ISSUE TITLE
Not able to upload files with form

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#10047]
### Bug description

I am not able to upload files when sending the form via AlpineJS. The error message states that "Dateien" has to be an array. I also tried setting `max_files` to 1, but then the error states that 1 file is required, even though a file has been added.

<img width="852" alt="Screenshot 2024-05-13 at 10 04 51" src="https://github.com/statamic/cms/assets/3603346/9cde34cd-53c2-44af-92ef-631002b754fe">

While looking for a solution, I stumbled upon [this issue](https://github.com/statamic/cms/issues/2205), which is essentially the same problem, only that I'm sending via AlpineJS.

This is the JS code:

```
document.addEventListener('alpine:initializing', () => {
    Alpine.data('formHandler', () => ({
        processing: false,
        success: false,
        form: null,
        init() {
            this.form = this.$form(
                'post',
                this.$refs.form.getAttribute('action'),
                JSON.parse(this.$refs.form.getAttribute('x-data')).form,
                {
                    headers: {
                        'X-CSRF-Token': {
                            toString: () => this.$refs.form.querySelector('[name="_token"]').value,
                        }
                    }
                }
            )
        },
        submit() {
            this.processing = true;
            this.form.submit()
                .then(response => {
                    {{ if (success_action == 'redirect') }}
                        window.location.replace("{{ success_redirect }}");
                    {{ else }}
                        this.processing = false;
                        this.success = true
                        this.$refs.form.reset()
                    {{ /if }}
                })
                .catch(error => {
                    console.log(error);
                    this.processing = false;
                })
        }
    }))
})
```

This is the rendered field in question:

```
<input type="file" name="dateien[]" multiple="" x-model="form.dateien" @change="form.validate('dateien')" :aria-invalid="form.invalid('dateien')">
```

### How to reproduce

Create a form and enable attachments. Then use the JS from the bug description to try to send the form.

### Environment

```yaml
Environment
Application Name: ABC
Laravel Version: 10.48.10
PHP Version: 8.2.16
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: abc.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: postmark
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.57.3 PRO

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.2.0
mitydigital/sitemapamic: 2.3.9
```

### Installation

Fresh statamic/statamic site via CLI
