### ISSUE TITLE
Glide no longer use defaults from assets.php? [5.0.2]

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#10051]
### Bug description

This is in my template:
```
<img src="{{ glide:image width='1496' height='617' fit='crop_focal' }}" />
```
And this is in my `assets.php`:
```
'defaults' => [
    'format' => 'webp',
    'quality' => 85,
],
```

But it still loads as jpeg when I look at the network tab in Chrome:
![Screenshot 2024-05-13 at 15 19 51](https://github.com/statamic/cms/assets/1135679/bfc9728d-af1b-462f-9dd3-54cdbfaba8f1)

If I add `format='webp'` in the glide tag it works fine.

### How to reproduce

Explained in the bug description.

### Environment

```yaml
Environment
Application Name: Laugstol
Laravel Version: 11.7.0
PHP Version: 8.2.16
Composer Version: 2.7.2
Environment: local
Debug Mode: ENABLED
URL: laugstol.test/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 2 (Norsk, Engelsk)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.0.2 PRO
```

### Installation

Fresh statamic/statamic site via CLI
