### ISSUE TITLE
Glide assets 404 since Statamic V5 upgrade

### ISSUE THREAD

**Issue by atomicjam** [statamic/cms#10053]
### Bug description

Upgraded site from V4 to V5, cleared stash, and glide assets. 

Site produces 404 error on any calls to the glide generated asset urls. 

Assets are viewable in the control panel and directly on the default /assets/ path but the glide /img/assets path throws 404

### How to reproduce

tags used in antlers are like follows but happens on any image

```
<picture>
            {{ default_image:image }}
            <source type="image/webp" media="(min-width: 1919px)" srcset="{{ glide:url width='1919' quality='75' format='webp' }} 1x, {{ glide:url width='1919' quality='75' dpr='2' format='webp' }} 2x">
            <source type="image/webp" media="(max-width: 1600px)" srcset="{{ glide:url width='1600' quality='75' format='webp' }} 1x">
            <source type="image/webp" media="(max-width: 1366px)" srcset="{{ glide:url width='1366' quality='75' format='webp' }} 1x, {{ glide:url width='1366' quality='75' dpr='2' format='webp' }} 2x">
            <source type="image/webp" media="(max-width: 1024px)" srcset="{{ glide:url width='1024' quality='75' format='webp' }} 1x">
            <source type="image/webp" media="(max-width: 640px)" srcset="{{ glide:url width='640' quality='75' format='webp' }}, {{ glide:url width='640' quality='75' dpr='2' format='webp' }} 2x">
            <source type="image/jpg" media="(min-width: 1919px)" srcset="{{ glide:url width='1919' quality='75' }} 1x, {{ glide:url width='1919' quality='75' dpr='2' }} 2x">
            <source type="image/jpg" media="(max-width: 1600px)" srcset="{{ glide:url width='1600' quality='75' }} 1x">
            <source type="image/jpg" media="(max-width: 1366px)" srcset="{{ glide:url width='1366' quality='75' }} 1x, {{ glide:url width='1366' quality='75' dpr='2' }} 2x">
            <source type="image/jpg" media="(max-width: 1024px)" srcset="{{ glide:url width='1024' quality='75' }} 1x">
            <source type="image/jpg" media="(max-width: 640px)" srcset="{{ glide:url width='640' quality='75' }}, {{ glide:url width='640' quality='75' dpr='2' }} 2x">
            <img src="{{ glide:url width='1366' quality='75' }}" class="max-h-screen h-screen w-full object-cover">
            {{ /default_image:image }}
        </picture>
```

### Logs

```shell
Log file empty no errors thrown.
```

### Environment

```yaml
Environment
Application Name: Flourish
Laravel Version: 10.48.10
PHP Version: 8.3.4
Composer Version: 2.3.10
Environment: production
Debug Mode: OFF
URL: flourish.cheltladiescollege.org
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Sites: 1
Stache Watcher: Disabled
Static Caching: half
Version: 5.0.2 PRO

Statamic Addons
mitydigital/feedamic: 2.3.2
mitydigital/sitemapamic: 3.0.1
rias/statamic-redirect: 3.7.1
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Rolling back to v4 and images are generated again fine. 

visiting /assets/new-lc-break-26.jpg for example would display the image fine in v5 

but visiting the url generated by the glide tag /asset/YXNzZXRzL25ldy1sYy1icmVhay0yNi5qcGc=/new-lc-break-26.jpg?w=1919&q=75&fm=webp&s=1099680fd69211e408b15f4d34eaec5a
throws 404 in v5 

glide cache is cleared

[✔] Glide path cache cleared.
[✔] Found 0 images.
[✔] Deleted empty directories.

and /storage/statamic/glide/containers/assets is empty no assets are ever generated in v5 

assets.php config is as follows
```
'image_manipulation' => [
        'route' => 'img',
        'secure' => true,
        'driver' => 'gd',
        'cache' => false,
        'cache_path' => public_path('img'), 
```
