### ISSUE TITLE
Missing form submission config change in upgrade guide

### ISSUE THREAD

**Issue by wiljanslofstra** [statamic/cms#10063]
### Bug description

We upgraded a few sites to Statamic 5. Only in our case we moved the submission directory to another location. The configuration was in forms.php > submissions. But it seems to be changed in version 5:

https://github.com/statamic/cms/commit/22c831fc1f18a9bef038ac80024ede4c4bd27ff4

We changed it, but I couldn't find any reference to the change in the upgrade guide. Maybe useful for people upgrading to version 5 in the future.

### How to reproduce

Upgrade Statamic site from version 4 to 5.

### Environment

```yaml
Environment
Application Name: [redacted]
Laravel Version: 10.48.10
PHP Version: 8.2.8
Composer Version: 2.7.6
Environment: production
Debug Mode: OFF
URL: [redacted]
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Sentry
Enabled: YES
Environment: production
Laravel SDK Version: 3.8.2
PHP SDK Version: 3.22.1
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 10%
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 10
Sites: 4 (NL, BE, UK, DE)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.0.2 PRO

Statamic Addons
orangetalent/statamic-graphql-alternates: dev-dev
orangetalent/statamic-graphql-breadcrumbs: dev-dev
orangetalent/statamic-graphql-lang: 0.0.2
orangetalent/statamic-graphql-search: 0.0.4
orangetalent/statamic-graphql-sitemap: dev-dev
ryanmitchell/statamic-translation-manager: 1.5.0
studio1902/statamic-peak-browser-appearance: 2.0
studio1902/statamic-peak-commands: 2.7.0
studio1902/statamic-peak-seo: 2.6.2
studio1902/statamic-peak-tools: 3.4.3
```

### Installation

Other (please explain)

### Additional details

Upgrade from Statamic 4 to 5 (and also from 3 to 5)
