### ISSUE TITLE
"The given data was invalid" when uploading a GLB file [4.57.0]

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#10069]
### Bug description

I'm having problems uploading GLB-files to the assets container. I've tried to disable the automatic image processing just in case, and I've tried both on my local dev-environment and on the production-environment, but still the same. Uploading other non-image files as PDF or MP4 is not a problem. File size is not the issue, it is well within the configured limits.

This is a screenshot from CP;
![Screenshot 2024-05-14 at 12 50 05](https://github.com/statamic/cms/assets/1135679/488f63cf-7458-47c1-8706-cc6e4c6e5bee)

..and this is what the POST request returns:
![Screenshot 2024-05-14 at 12 50 44](https://github.com/statamic/cms/assets/1135679/9bd0eab7-9c9c-4858-b4ca-163142b42111)

### How to reproduce

In short - try to upload a file with extension .glb to the assets container. It doesn't have to be an actual .glb 3d-model file, I tried to rename a jpg to glb just to check and I get the same error.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.7
PHP Version: 8.2.16
Composer Version: 2.7.2
Environment: local
Debug Mode: ENABLED
URL: cody.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 2 (Norsk, English)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.57.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
