### ISSUE TITLE
419 errors using the nocache tag

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#10068]
### Bug description

On two v5 sites where I use the `nocache` tag I get 419 console errors on the `/!/nocache` route. This leads to the content not being rendered on production sites. 

### How to reproduce

Use nocache with static caching

### Environment

```yaml
Environment
Laravel Version: 11.7.0
PHP Version: 8.2.18
Composer Version: 2.7.6
Environment: staging
Debug Mode: OFF
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Livewire
Livewire: v3.4.12

Statamic
Addons: 8
Sites: 1
Stache Watcher: Disabled
Static Caching: full
Version: 5.0.2 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 2.3.1
jonassiewertsen/statamic-livewire: 3.3.1
rias/statamic-color-swatches: 2.3.0
stillat/relationships: 2.2.0
studio1902/statamic-peak-browser-appearance: 3.4.0
studio1902/statamic-peak-commands: 8.3.0
studio1902/statamic-peak-seo: 8.13.2
studio1902/statamic-peak-tools: 6.0.0
```

### Installation

Starter Kit using via CLI
