### ISSUE TITLE
`Please` references `App\Console\Kernel` which doesn't exist in new (or "shifted") Laravel apps

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#10060]
### Bug description

In new, or shifted Laravel apps there is no `App\Console\Kernel` class, but the Please `Kernel.php` class requires it.

I believe it should extend `Illuminate\Foundation\Console\Kernel` instead.

### How to reproduce

1. Create new Laravel app
2. install Statamic
3. try to run a `please` command.

### Environment

```yaml
Environment
Application Name: Tuckfit
Laravel Version: 11.7.0
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: tuckfit.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: mysql
Logs: stack / daily
Mail: log
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.0.2 PRO

Statamic Addons
citizenadagency/snoozer-choozer: dev-feature/statamic-5-laravel-11
statamic-rad-pack/shopify: 3.3.0
```

### Installation

Existing Laravel app
