### ISSUE TITLE
Mystery 404's on server environment

### ISSUE THREAD

**Issue by vluijkx** [statamic/cms#10067]
### Bug description

After updating to Statamic 5, all our entries result into 404 pages on our staging server. Nothing goes wrong locally though. I find it pretty hard to write this issue as I can't tell you how to replicate this behaviour. I am not even able to replicate the issue locally myself. 

This is what I figured out so far:
* The 404's seem to be rendered by Laravel/Statamic and not by NGINX.
* At first I thought it might have something todo with https://github.com/statamic/cms/issues/9987. However, when I downgraded to `v5.0.0-alpha.1`, the issue persisted.
* I've removed all addons including the `eloquent-driver`. The issue still persisted.
* Clearing the cache doesn't help.

### How to reproduce

So I know this issue is pretty vague 😅. I am not expecting anyone te be able to provide a solution based on these details. I do hope that someone could point me into a better direction so that I will be able to narrow things down and provide better info.

### Environment

```yaml
## Staging environment (results into 404's)

Environment
Application Name: Cell0
Laravel Version: 11.7.0
PHP Version: 8.2.6
Composer Version: -
Environment: staging
Debug Mode: OFF
URL: staging.cell-0.com
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: mailgun
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.0.2 PRO


## Local environment (works fine)

Environment
Application Name: Laravel
Laravel Version: 11.7.0
PHP Version: 8.2.6
Composer Version: -
Environment: local
Debug Mode: OFF
URL: website.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.0.2 PRO
```

### Installation

Existing Laravel app
