### ISSUE TITLE
Entries showing 404's on server with proxies and trust proxies wildcard

### ISSUE THREAD

**Issue by vluijkx** [statamic/cms#10079]
### Bug description

We have been learning more since https://github.com/statamic/cms/issues/10067. The issue happens when loading entries on a server that uses proxies while setting the `TrustProxies` middleware to the wildcard value `*`.

```php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;

return Application::configure(basePath: dirname(__DIR__))
    ->withProviders()
    ->withRouting(
        web: __DIR__.'/../routes/web.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware) {
        $middleware->trustProxies(at: '*'); // This line results into entries showing 404's.
    })
    ->withExceptions(function (Exceptions $exceptions) {
        //
    })->create();
```

The control-panel routes and the regular `web.php` routes work fine.

### How to reproduce

* Start a new Statamic project.
* Create a collection with routing enabled.
* Add an entry.
* Set the `app.php` contents to the file above (set trusted IP's to `*`)
* Deploy the project to a server environment that uses proxies.
* The entry should result into a 404.

### Environment

```yaml
Environment
Application Name: Cell0
Laravel Version: 11.7.0
PHP Version: 8.2.6
Composer Version: -
Environment: staging
Debug Mode: OFF
URL: staging.cell-0.com
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: mailgun
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.1.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
Good catch! Glad to hear you managed to get it sorted.

In our documentation, we [recommend that site URLs are fully-qualified, absolute URLs](https://statamic.dev/multi-site#url) as to ensure server magic (like trusted proxies in your case) don't cause any issues.

**Comment by o1y** [comment]
I have the same problem with Statamic 5 on a production server, which uses a reverse proxy:

sites.yaml:
```yaml
default:
  name: English
  locale: en
  url: /en
de:
  name: Deutsch
  locale: de
  url: /de
```

app/Http/Middleware/TrustProxies.php
```php
// ...
protected $proxies = "*";
// ...
```

**Comment by duncanmcclean** [comment]
In that case, your site URLs will need to be absolute URLS, like this:

```yaml
default:
  name: English
  locale: en
  url: {{ config:app:url }}/en
de:
  name: Deutsch
  locale: de
  url: {{ config:app:url }}/de
```
