### ISSUE TITLE
[5.x] Problem with saving when editing a term if the slug is unique

### ISSUE THREAD

**Issue by yuliia-bondareva-corefy** [statamic/cms#10078]
### Bug description

I created a taxonomy and specified in the slug validation that it should be unique.
created the term, saved it. I edited the term term, I saved it - I got an error

### How to reproduce

I created a taxonomy and specified in the slug validation that it should be unique.
created the term, saved it. I edited the term term, I saved it - I got an error
I have one term in taxonomy 
![image](https://github.com/statamic/cms/assets/119051067/83e5cd98-3b37-4c72-9ee5-10e55bb1f276)
![image](https://github.com/statamic/cms/assets/119051067/5f395187-59ec-4d1d-a67b-49ed406fb589)

### Environment

```yaml
Environment
Application Name: localhost
Laravel Version: 11.7.0
PHP Version: 8.3.6
Composer Version: 2.2.6
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: pgsql
Logs: stack / daily, database
Mail: smtp
Queue: sync
Session: database

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.1.0 PRO

Statamic Addons
osayaweventures/share-links: 1.0.1
statamic/collaboration: 1.0.0
statamic/eloquent-driver: 4.0.0
statamic/seo-pro: 6.0.2

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
```

### Installation

Fresh statamic/statamic site via CLI
