### ISSUE TITLE
Root nav items don't return custom field data

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#10080]
### Bug description

I don't seem to get any navigation blueprint data returned in Antlers for root items. It does seem to work for children (in my case).

```yaml
tree:
  -
    id: c818add2-f657-474b-ae28-fa4cec914bc2
    title: Follow
    data:
      contents: social_media
```

```antlers
{{ nav:footer max_depth="2" select="contents|title|url" }}
   {{ contents | dump }}
```

This dumps nothing. Only the Title and URL are available. The data also isn't available when I remove the `select` attribute. When I dump the whole nav I don't see the data:
<img width="950" alt="Screenshot 2024-05-14 at 08 55 58" src="https://github.com/statamic/cms/assets/69107412/029732a4-1ccb-463b-aa3d-b9b3315f08a2">

### How to reproduce

Create a nav with custom fields
Add root items with custom fields filled in
Request it in Antlers

### Environment

```yaml
Environment
Laravel Version: 11.7.0
PHP Version: 8.2.19
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.4.12

Statamic
Addons: 8
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.1.0 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 2.3.1
jonassiewertsen/statamic-livewire: 3.3.1
rias/statamic-color-swatches: 2.3.0
stillat/relationships: 2.2.0
studio1902/statamic-peak-browser-appearance: 3.4.0
studio1902/statamic-peak-commands: 8.3.0
studio1902/statamic-peak-seo: 8.13.2
studio1902/statamic-peak-tools: 6.0.0
```

### Installation

Starter Kit using via CLI

### Additional details

Possibly related to #10055
