### ISSUE TITLE
"Allow creating" is not saved on the Entries-fieldtype

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#10083]
### Bug description

When I edit a fieldset and toggle "Allow creating" to off and click apply/save it does not actually save. If I go into edit mode on the field again it looks fine, but if I reload the page it is restored.

I did a video do illustrate:
https://github.com/statamic/cms/assets/1135679/b4b536ab-f93e-438a-b91b-903ac8962d56

### How to reproduce

Hopefully the description is sufficient.

### Environment

```yaml
Environment
Application Name: Laugstol
Laravel Version: 11.7.0
PHP Version: 8.2.16
Composer Version: 2.7.2
Environment: local
Debug Mode: ENABLED
URL: laugstol.test/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 2 (Norsk, Engelsk)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.0.2 PRO
```

### Installation

Fresh statamic/statamic site via CLI
