### ISSUE TITLE
Upgrade Statamic from 4.58.2 to 5.x not work 

### ISSUE THREAD

**Issue by emran-alhaddad** [statamic/cms#10082]
### Bug description

I tried to upgrade statamic from the version 4.58.2 to 5.x and its not upgrade anything, I tried everything in the documentation about upgrading from version 4 to 5 , but not works 

### How to reproduce

composer update 
statamic update 

### Environment

```yaml
Environment
Application Name: Alreef
Laravel Version: 10.48.10
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: alreef-cms.brackets-tech.com.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Sites: 2 (English, عربي)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.58.2 PRO

Statamic Addons
spatie/statamic-responsive-images: 4.1.1
statamic/eloquent-driver: 3.4.1
swiftmade/statamic-clear-assets: 2.0.1
teamnovu/statamic-unused-assets: 2.0.2

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
```

### Installation

Fresh statamic/statamic site via CLI
