### ISSUE TITLE
Code mode unstlyed on YAML fieldtype

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#10084]
### Bug description

It appears that the code mode is showing unstyled on the YAML field. This is likely a result of moving the code mode into a toolbar on the Code fieldtype.

<img width="805" alt="Screenshot 2024-05-15 at 10 36 01 pm" src="https://github.com/statamic/cms/assets/414211/78902bc2-f4da-4719-9f4e-60c558d513e3">

<img width="793" alt="Screenshot 2024-05-15 at 10 36 51 pm" src="https://github.com/statamic/cms/assets/414211/18c22362-f025-4a2b-a831-74f055872e70">

### How to reproduce

- Create a yaml field

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.7.0
PHP Version: 8.2.19
Composer Version: 2.7.6
Environment: local
Debug Mode: OFF
URL: scratch.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.1.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
