### ISSUE TITLE
QueriesEntryStatus doesn't check if a collection is dated before applying conditions to the date.

### ISSUE THREAD

**Issue by etcmfa** [statamic/cms#10108]
### Bug description

I'm using the [eloquent driver](https://github.com/statamic/eloquent-driver) and have some collections which are dated and some which are not.

When using `whereStatus('published')` to retrieve entries from a collection which is not dated no results are returned.

Since the entries that belong a non-dated collection have a NULL date value in the database any before or after timestamp comparison fails.

### How to reproduce

Create a non-dated collection and add some published entries.

`Entry::query()->where('collection', {collectionHandle})->whereStatus('published')->get()`

Example of the SQL from `toRawSql` which always fails because the `date` values of the non-dated entries are NULL:

`select * from cp_entries where collection = 'testimonials' and published = 1 and ((collection = 'testimonials' and date < '2024-05-17 15:48:04'))`

### Environment

```yaml
Environment
Laravel Version: 10.48.5
PHP Version: 8.3.1
Composer Version: 2.7.2
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: redis

Filament
Packages: filament, forms, notifications, support, tables
Version: v3.2.63
Views: NOT PUBLISHED

Livewire
Livewire: v3.4.10

Statamic
Addons: 4
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.1.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.0.0
statamic/seo-pro: 6.0.2
teamnovu/statamic-images-missing-alt: 1.0.4
teamnovu/statamic-unused-assets: 2.0.2

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: file
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: file
Revisions: eloquent
Taxonomies: file
Terms: eloquent
```

### Installation

Existing Laravel app
