### ISSUE TITLE
Git autocommitting broken on a fresh install of Statamic

### ISSUE THREAD

**Issue by amadeann** [statamic/cms#10102]
### Bug description

Please see the thread:
https://discord.com/channels/489818810157891584/1240373773279039499/1240374342303350876

for reference.

[Autocommit to git](https://statamic.dev/git-automation) fails with messages like:
```
[2024-05-16 21:39:36] production.ERROR: Process Class: Git
Command:  -c "user.name=Amadeusz Annissimo" -c "user.email=me@example.com" commit -m "Content saved"
Error: sh: 1:
-c: not found  
```

Replacing `config('statamic.git.binary')` to hardcoded `git` fixes the issue. Most likely this bug was introduced here:
https://github.com/statamic/cms/commit/770dc485dd2b330b40816c68727f080e45f18bfc

### How to reproduce

Fresh install of Statamic.
Set up git autocommit as per docs.
Make any changes in the entry.
Check application logs for errors.

### Environment

```yaml
Environment
Application Name: *****
Laravel Version: 10.48.8
PHP Version: 8.3.3-1+ubuntu22.04.1+deb.sury.org+1
Composer Version: 2.7.6
Environment: production
Debug Mode: OFF
URL: *****
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: mailgun
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.56.1 PRO

Statamic Addons
statamic/seo-pro: 5.4.4
stefangalescu/statamic-heroicons: 2.1.1
```

### Installation

Fresh statamic/statamic site via CLI
