### ISSUE TITLE
Replicator Set Picker is clickable even though max_sets is exceeded

### ISSUE THREAD

**Issue by mgschoen** [statamic/cms#10105]
### Bug description

When a replicator field has `max_sets` configured and that number of sets is reached, the set picker button is hidden accordingly. Its container however is still present and clickable. This way, a user can add more sets than the blueprint allows. I'd expect this to be prevented.

![Screenshot 2024-05-17 at 13 00 31](https://github.com/statamic/cms/assets/22660469/0653fba6-2cab-4f1e-bcb9-e2391cc016fa)
![Screenshot 2024-05-17 at 13 00 51](https://github.com/statamic/cms/assets/22660469/23ab0cf7-e90e-4ff6-924b-53e7a718e2f3)

### How to reproduce

- Configure any replicator field with `max_sets` set
- Open entry with new field
- Add `max_sets` number of sets
- Observe how you can still add more sets by clicking on the empty space where the set picker was previously displayed

### Environment

```yaml
Tested in fresh and plain installations of

- Statamic v4.58.2
- Statamic v5.2.0

Support Details for the latter:

Environment
Application Name: Statamic
Laravel Version: 10.47.0
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.2.0 Solo
```

### Installation

Starter Kit using via CLI
