### ISSUE TITLE
Dark mode issues

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#10119]
### Bug description

Two tiny dark mode issues I just noticed:

**Pagination in widgets**
<img width="499" alt="Screenshot 2024-05-20 at 19 59 07" src="https://github.com/statamic/cms/assets/69107412/99727fc0-d461-4e44-adb4-1d4778d5b981">

**Top border on nested entries for structured collections**
<img width="943" alt="Screenshot 2024-05-20 at 19 59 19" src="https://github.com/statamic/cms/assets/69107412/4e3e6cfd-594c-43e2-8349-f10af3a17ee8">

### How to reproduce

Check out dark mode on paginated widgets and structured collections with nested entries.

### Environment

```yaml
Environment
Laravel Version: 11.7.0
PHP Version: 8.2.19
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.4.12

Statamic
Addons: 9
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.3.0 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 2.3.1
jonassiewertsen/statamic-livewire: 3.3.1
rias/statamic-color-swatches: 2.3.0
stillat/relationships: 2.2.0
stoffelio/statamic-404-logger: 1.0.0
studio1902/statamic-peak-browser-appearance: 3.4.0
studio1902/statamic-peak-commands: 8.3.0
studio1902/statamic-peak-seo: 8.13.3
studio1902/statamic-peak-tools: 6.0.0
```

### Installation

Starter Kit using via CLI
