### ISSUE TITLE
New user activation message reads poorly when expiry is anything other than 1 hour.

### ISSUE THREAD

**Issue by martyf** [statamic/cms#10116]
### Bug description

When going through the new user sign up Wizard, the Email Content message reads poorly when the word "hours" should be used.

The current message is:
> Activate your new Statamic account on starter.test to begin managing this website. For your security, the link below expires after **_2 hour_**. After that, please contact the site administrator for a new password.

The issue is bolded and italicised above - it reads `2 hour` instead of `2 hours`.

The issue, however, is that the word "hour" is part of the translation string, and has a merge value for the number of hours - but the string itself will always say "hour". Any changes here become larger as it impacts all translation strings, and I felt it better to have core team input rather than make a change/PR that doesn't align with what the team would have done: but happy to have a chat about how you'd like to approach this and work on a PR to offload this work too.

### How to reproduce

1. Install a new site with `statamic new ...`
2. Make a user, and enable Pro for the CP (`config/statamic/editions.php`)
3. Change the Auth timeout to be anything other than 1 hour (`config/auth.php`)
4. Create a new user via the CP, and progress to the email content screen: you will see the "Email Content" field here with the issue.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.7.0
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: authtest.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.2.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
