### ISSUE TITLE
"Manage publish state" permission not working

### ISSUE THREAD

**Issue by steveooo1** [statamic/cms#1011]
I created a test user with a role that disallows managing publish states. E.g. for authors that only are able to create stuff, but not publish it before a proofreader approves this. I unchecked the "Manage publish state" option but still, I am able as the user to publish entries.

<img width="407" alt="CleanShot 2019-11-27 at 23 46 44@2x" src="https://user-images.githubusercontent.com/58191591/69764396-77ac2080-1170-11ea-93d1-7660a4ace517.png">

<img width="372" alt="CleanShot 2019-11-27 at 23 49 22@2x" src="https://user-images.githubusercontent.com/58191591/69764442-990d0c80-1170-11ea-96f4-3a2c8949b12b.png">

The resources/users/roles.yaml:
```
author:
  title: Author
  permissions:
    - 'access cp'
    - 'view test entries'
    - 'edit test entries'
    - 'create test entries'
```
