### ISSUE TITLE
[Dark] Drag Handle on Entries fieldtype showing dark styles in light mode

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#10127]
### Bug description

<img width="674" alt="Screenshot 2024-05-21 at 2 37 34 pm" src="https://github.com/statamic/cms/assets/414211/c70eb4ef-993e-430c-a34f-086e226e2654">

### How to reproduce

Add entries field

### Environment

```yaml
Environment
Application Name: Pilot Pen Australia
Laravel Version: 10.48.10
PHP Version: 8.2.19
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: pilot.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Locales
Installed
Locales Version: 1.9.0
Protected

Localization
Installed: en
LaravelLang\Attributes\Plugin: 2.10.5
LaravelLang\HttpStatuses\Plugin: 3.8.3
LaravelLang\Lang\Plugin: 13.12.0
Protected Locales: en
Publisher Version: 14.7.1

Livewire
Livewire: v3.4.12

Statamic
Addons: 16
Sites: 1
Stache Watcher: Disabled
Static Caching: full
Version: 5.3.0 PRO

Statamic Addons
aerni/social-links: 3.2.0
aniket-magadum/insta-feeds: 1.0.1
duncanmcclean/static-cache-manager: 4.0.0
fdmind/ignore-query-strings: dev-main
jacksleight/statamic-bard-mutator: 2.3.1
jonassiewertsen/statamic-livewire: 3.3.1
mikemartin/helpscout-beacon: 1.0.4
ncla/statamic-focal-point-fieldtype: dev-main
rias/statamic-color-swatches: 2.3.0
steadfastcollective/statamic-csv-exporter: dev-main
stillat/relationships: 2.2.0
studio1902/statamic-peak-browser-appearance: 3.4.0
studio1902/statamic-peak-commands: 8.3.0
studio1902/statamic-peak-seo: 8.13.3
studio1902/statamic-peak-tools: 6.0.0
swiftmade/statamic-clear-assets: 3.0.0
```

### Installation

Fresh statamic/statamic site via CLI
