### ISSUE TITLE
[Dark] Replicator/Bard set picker missing dark UI

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#10125]
### Bug description

Both the replicator and bard field are missing dark UI in their set pickers.

<img width="380" alt="Screenshot 2024-05-21 at 2 06 22 pm" src="https://github.com/statamic/cms/assets/414211/2368f96a-e497-462e-9b91-a9f9a557485d">

<img width="370" alt="Screenshot 2024-05-21 at 2 09 41 pm" src="https://github.com/statamic/cms/assets/414211/999d479c-1cbf-43cd-9d27-02c604f70e1b">

### How to reproduce

Add a bard field with sets. For example:
```
title: Default
fields:
  -
    handle: content
    field:
      type: bard
      display: Content
      always_show_set_button: true
      buttons:
        - h2
        - h3
        - bold
        - italic
        - unorderedlist
        - orderedlist
        - anchor
      smart_typography: true
      sets:
        '':
          display: null
          sets:
            pull_quote:
              display: 'Pull Quote'
              icon: text-formatting-quotation
              fields:
                -
                  handle: quote
                  field:
                    type: bard
                    display: Quote
                    buttons:
                      - bold
                      - italic
                    toolbar_mode: floating
                -
                  handle: name
                  field:
                    type: text
                    display: Name
            newsletter_callout:
              display: 'Newsletter Callout'
              icon: form-text-field
              fields: {  }
            photo_gallery:
              display: 'Photo Gallery'
              icon: dashboard-layout
              fields: {  }
            video:
              display: 'Video Embed'
              icon: media-webcam-video
              fields:
                -
                  handle: video
                  field:
                    type: video
                    display: Video
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.7.0
PHP Version: 8.2.19
Composer Version: 2.7.6
Environment: local
Debug Mode: OFF
URL: scratch.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.3.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
