### ISSUE TITLE
`{{ if children }}` not working

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#10130]
### Bug description

`{{ if children }}` is always `false`.
`{{ children | dump ))` gives no output.
But there are children and when you show the titles with this
```
{{ children }}
    {{ title }}
{{ /children }}
```
are the titles shown correctly.

### How to reproduce

Use a nested collection to check for children not inside the `nav` tag.

### Environment

```yaml
Environment
Laravel Version: 10.48.10
PHP Version: 8.2.7
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.4.12

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.3.0 PRO

Statamic Addons
ddm-studio/cookie-byte: 1.5.0
jonassiewertsen/statamic-livewire: 3.3.1
mitydigital/statamic-google-fonts: 2.0.0
nineteensquared/instagram: 1.2.0
```

### Installation

Fresh statamic/statamic site via CLI
