### ISSUE TITLE
SubmissionActionController contains 1 abstract method and must therefore be declared abstract or implement the remaining methods

### ISSUE THREAD

**Issue by tats149576** [statamic/cms#10142]
### Bug description

Attempting to delete saved form submission from site's control panel.  (Very simple contact form with four fields)

### How to reproduce

Submit form, then try to delete saved submission and it displays an error popup.

### Logs

```shell
laravel.log

local.ERROR: Class Statamic\Http\Controllers\CP\Forms\SubmissionActionController contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Statamic\Http\Controllers\CP\ActionController::getItemData) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Class Statamic\\Http\\Controllers\\CP\\Forms\\SubmissionActionController contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Statamic\\Http\\Controllers\\CP\\ActionController::getItemData) at /var/www/transamer-weblab.com/vendor/statamic/cms/src/Http/Controllers/CP/Forms/SubmissionActionController.php:7)
[stacktrace]
```

### Environment

```yaml
Environment
Application Name: Trans American
Laravel Version: 10.48.7
PHP Version: 8.1.2-1ubuntu2.17
Composer Version: 2.7.2
Environment: local
Debug Mode: OFF
URL: www.transamer.com
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.2.0 PRO
```

### Installation

Starter Kit using via CLI

### Additional details

Happened after upgrading from 5.2.0 -> 5.3.0.  Seems to have been caused by #6375.  I have reverted back to 5.2.0 in the meantime that's why support details show that version.  Also tested 5.3.0 in lab after running composer update and updating PHP to 8.3 - same error.
