### ISSUE TITLE
Unable to upload image due to validation error

### ISSUE THREAD

**Issue by JaWSnl** [statamic/cms#10158]
### Bug description

Upload an image file causes the error: `Image [some-image.png] does not actually appear to be a valid image.`. (See image attached.)

Mime-type of the asset is empty when using breakpoints. In `vendor/statamic/cms/src/Imaging/ImageGenerator.php:297 = validateImage()`. On line 309 the exception is thrown.

![some-image](https://github.com/statamic/cms/assets/1092708/f4579a89-9277-446b-8dd2-d4a6b3674ca1)

Noticed: Events are encountered in stack trace (which were changed/added in 4.53.0).

### How to reproduce

Checkout statamic version 4.53.0, upload an image in a blueprint that supports it, in our case a global. Clicking "upload" and then selecting an image starts a loading bar, but fails with the above error. Note that we use S3.

Checking out statamic version 4.52.0 does not result in this issue.

### Environment

```yaml
Statamic 4.53.0
Use S3 for filesystem

Details using `php artisan statamic:support:details`:
Environment
Application Name: <removed>
Laravel Version: 10.43.0
PHP Version: 8.3.2
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: localhost:8000
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stdout
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Sites: 2 (<removed>, <removed>)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.53.0 PRO

Statamic Addons
goldnead/statamic-collapse-fieldtype: 1.0.5
jacksleight/statamic-bard-texstyle: 3.1.6
statamic/eloquent-driver: 2.10.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

This issue was recently encountered when trying to upload images via a command. Calling Blink:flush() between each upload fixes this. It seems that the image is not present in the cache.
