### ISSUE TITLE
Multisite: If you delete an entry (not the origin) you see a modal with options (delete or detach) but the option delete won't delete the origin entry.

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#10162]
### Bug description

With this example:

- example.com/en/page-1 (origin)
- example.com/de/page-1

=> If you delete the origin entry you can choose between delete entry or detach. This works as expected.

=> If you delete the other entry you can choose between delete or detach too. But if you choose delete, the origin entry won't delete and is still in the collection view.

<img width="952" alt="Bildschirmfoto 2024-05-22 um 14 22 57" src="https://github.com/statamic/cms/assets/8265902/30743fd2-5b5e-42cb-bdd0-6ec569d88fc7">

### How to reproduce

- Enable multisite
- Create an entry on both locales
- Delete entry on the not origin locale
- Choose Delete in the modal.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.8.0
PHP Version: 8.2.19
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: multisite-test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 2 (Statamic DE, Statamic FR)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.4.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
