### ISSUE TITLE
Order of filter presets not maintained after renaming

### ISSUE THREAD

**Issue by wiebkevogel** [statamic/cms#10176]
### Bug description

When users have many filter presets and they edit or rename an existing preset, the order of the saved filters is not maintained. The preset that is edited or renamed is always moved to the last position in the list.

Expected Behavior:
The edited or renamed filter should retain its original position in the list.

https://github.com/statamic/cms/assets/54707973/9588a62c-f494-4f95-903e-a76f5e105d95

### How to reproduce

1. Open the list view of a collection
2. Save multiple filter presets
3. Edit or rename an existing filter
4. The updated filter is sorted to the end

### Environment

```yaml
Laravel Version: 10.48.4
PHP Version: 8.3.7
Composer Version: 2.7.6

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.5.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
