### ISSUE TITLE
Replicator not displaying field previews

### ISSUE THREAD

**Issue by schwartzmj** [statamic/cms#10198]
### Bug description

Replicator fields are not displaying field previews even with Field Previews toggled on.

Manually adding `replicator_preview: true` to the field's YAML causes it to work, but anytime you re-save the field this goes away.

I'm assuming the default is meant to be `true` (which is why it disappears) but there is some bug in the logic.

### How to reproduce

Make a Replicator field type and use it.

### Environment

```yaml
Environment
Application Name: [redacted]
Laravel Version: 11.7.0
PHP Version: 8.3.1
Composer Version: 2.6.6
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.5.0 PRO

Statamic Addons
jacksleight/statamic-bard-ipsum: 1.0.1
spatie/statamic-responsive-images: 5.0.0
```

### Installation

Fresh statamic/statamic site via CLI
