### ISSUE TITLE
Can't access individual drafts using REST API

### ISSUE THREAD

**Issue by jpmaga** [statamic/cms#10207]
### Bug description

I was trying to use the api to access individual drafts. While it works when using the collection index:

`api/collections/articles/entries?filter[status:is]=draft&fields=id`
```json
{
    "data": [
        {
            "id": "28e138b9-17be-4dc5-a59b-f0dc31cf8c41"
        },
        {
            "id": "8b8359ae-5dbb-48c5-a27e-55288156079d"
        },
        {
            "id": "76987f6f-e29c-4c75-a974-caf21a538686"
        }
    ],
...
}
```

If doesn't work if I try to access them directly:

`/api/collections/articles/entries/8b8359ae-5dbb-48c5-a27e-55288156079d`
```json
{
    "message":"Not found."
}
```
adding `?filter[status:is]=draft` here produces the same result.

Upon further inspection the issue seems to lie here: https://github.com/statamic/cms/blob/5.x/src/Http/Controllers/API/CollectionEntriesController.php#L43

Which then leads us here: 
https://github.com/statamic/cms/blob/5.x/src/Http/Controllers/API/ApiController.php#L28

And this method leaves very little room for interpretation, or a way to circumvent this easily.

For my use case I just needed to use that in preview mode, so adding this bit solved it for me:
```php
throw_if($item->published() === false && !request()->get("live-preview"), new NotFoundHttpException);
```

But a more sturdy solution should be implemented.

### How to reproduce

Please check above

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.11
PHP Version: 8.3.0
Composer Version: 2.6.6
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 2 (English, Deutsch)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.58.1
```

### Installation

Existing Laravel app
