### ISSUE TITLE
GraphQL API does not work in 5.5.0

### ISSUE THREAD

**Issue by thomas4Bitcraft** [statamic/cms#10203]
### Bug description

The GraphQL Api does not work in the latest Statamic Version. No query is possible, the explorer window is empty and there is also an error in the Docs.

![image-1](https://github.com/statamic/cms/assets/44415527/69165296-1df7-4824-87fd-18d56ff2e00d)
![image](https://github.com/statamic/cms/assets/44415527/b3bf3c08-a632-4f8e-bf92-5b94ef7d1e9d)

### How to reproduce

Query:
```
query MyQuery {
  ping
}
```

Result:
{"errors":[{"message":"Cannot query field \"ping\" on type \"Query\".","locations":[{"line":2,"column":3}],"extensions":{"file":"\/home\/vagrant\/code\/xyz\/vendor\/webonyx\/graphql-php\/src\/Validator\/Rules\/FieldsOnCorrectType.php","line":43}}]}

### Environment

```yaml
Environment
Application Name: xyz
Laravel Version: 11.7.0
PHP Version: 8.2.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: xyz.com
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 2 (DE, EN)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.5.0 PRO

Statamic Addons
bitcraft/simple-seo: dev-master
statamic/eloquent-driver: 4.0.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
```

### Installation

Fresh statamic/statamic site via CLI
