### ISSUE TITLE
Control panel page is non-scrollable after opening and closing fullscreen on a code field

### ISSUE THREAD

**Issue by petemolinero** [statamic/cms#10208]
### Bug description

If I toggle fullscreen on a code field, the page becomes non-scrollable.

### How to reproduce

1. Add a code field to an entry's blueprint (or anything else)
2. Navigate to the control panel page containing the code field
3. Turn fullscreen on for the code editor
4. Turn fullscreen off again
5. Try scrolling the page; it will be disabled

### Environment

```yaml
Environment
Laravel Version: 11.9.1
PHP Version: 8.2.15
Composer Version: 2.6.5
Environment: development
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled
Static Caching: full
Version: 5.6.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.0.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: file
Navigation Trees: file
Navigations: eloquent
Revisions: eloquent
Taxonomies: file
Terms: eloquent
```

### Installation

Other (please explain)

### Additional details

I originally installed a previous version of Statamic on Laravel 10, but have recently upgraded to the latest of each.
