### ISSUE TITLE
CP nav customisation inconsistency

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#10213]
### Bug description

When you group items using the CP nav feature you can't set icons, which is an open issue (#9667). However something else that's a bit confusing is that collections and taxonomies you move out of a certain main nav item remain in the overview table.

In this case I made a group that contains two taxonomies and one collection:
<img width="148" alt="Screenshot 2024-05-29 at 11 11 40" src="https://github.com/statamic/cms/assets/69107412/2c65b545-922c-4845-9442-32bfb85b382c">

But in the collection and taxonomy overview tables you still see them listed, when they're removed from the sidebar:
<img width="502" alt="Screenshot 2024-05-29 at 11 12 33" src="https://github.com/statamic/cms/assets/69107412/07579a3d-d64d-4e1a-9b6a-f513908f1746">
<img width="519" alt="Screenshot 2024-05-29 at 11 12 39" src="https://github.com/statamic/cms/assets/69107412/d773e7e7-fafe-4717-bf74-68b5b58d3761">

This is a bit inconsistent and possibly confusing. It might be better for them to be removed from the overview table as well. 

### How to reproduce

1. Move stuff out of collections/taxonomies into its own group using the CP nav feature.
2. See those items still listed in the overview tables.

### Environment

```yaml
Environment
Laravel Version: 11.8.0
PHP Version: 8.2.19
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.0

Statamic
Addons: 9
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.5.0 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 2.3.1
jonassiewertsen/statamic-livewire: 3.3.1
rias/statamic-color-swatches: 2.3.0
stillat/relationships: 2.2.0
stoffelio/statamic-404-logger: 1.1.0
studio1902/statamic-peak-browser-appearance: 3.4.0
studio1902/statamic-peak-commands: 8.3.0
studio1902/statamic-peak-seo: 8.13.3
studio1902/statamic-peak-tools: 6.1.0
```

### Installation

Starter Kit using via CLI
