### ISSUE TITLE
JS errors with replicator fields in v5.6.0

### ISSUE THREAD

**Issue by heidkaemper** [statamic/cms#10210]
### Bug description

After updating to Statamic 5.6.0 replicator fields throw an JavaScript error "Cannot read properties of undefined (reading 'length')"

![image](https://github.com/statamic/cms/assets/10990014/444ddda6-07e9-456f-8dc8-027eb4f05616)

In some cases, this causes the entry not to be saved. The Request fails with error 422 (Unprocessable Content).

Reverting back to v5.5 fixes this.

### How to reproduce

- Add a replicator field with some sets to a blueprint
- Create an entry based on that blueprint
- Add a new set
- Check the JavaScript console for errors

### Environment

```yaml
Environment
Application Name: CHANGE_ME
Laravel Version: 11.9.1
PHP Version: 8.3.7
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: tpl-statamic.heidkaemper.nds-dev.de
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: sqlite
Logs: debug / single
Mail: sendmail
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.6.0 PRO

Statamic Addons
heidkaemper/statamic-toolbar: 1.2.0
ndx/statamic-bard-color-picker: 1.3.0
spatie/statamic-responsive-images: 5.0.0
stillat/antlers-components: 2.2.0
```

### Installation

Other (please explain)
