### ISSUE TITLE
Replicator `add set` label is not localizable

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#10212]
### Bug description

The nice label added in #9806 turns out not to be localizable. 

### How to reproduce

1. Add a label.
2. Add a string to your `locale.json` file translating the label.
3. Change the CP locale to that language.
4. See that the label doesn't translate.

### Environment

```yaml
Environment
Application Name: Statamic Peak Development
Laravel Version: 11.9.1
PHP Version: 8.2.19
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.6.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.4.1
studio1902/statamic-peak-commands: 8.3.0
studio1902/statamic-peak-seo: 8.13.3
studio1902/statamic-peak-tools: 6.1.0
```

### Installation

Fresh statamic/statamic site via CLI
