### ISSUE TITLE
Warming stache during deploy outputs many messages

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#10224]
### Bug description

We call `please stache:refresh` during deployment, and since we upgraded to v5 we see hundreds of these messages on every deploy:

<img width="333" alt="image" src="https://github.com/statamic/cms/assets/6069653/9874f70a-51cd-4a7e-8b27-1593a30a8f31">

(same with `Warming the State`)

### How to reproduce

Use Forge to deploy a v5 and have `please stache:refresh` as part of the deploy.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.9.1
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: transform.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: sqlite
Logs: stack / daily, front
Mail: log
Queue: sync
Session: file

Livewire
Livewire: v3.5.0

Statamic
Addons: 13
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.6.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.11.0
edalzell/forma: 3.0.1
jacksleight/statamic-bard-mutator: 2.3.1
jacksleight/statamic-distill: 0.7.0
jonassiewertsen/statamic-jobs: 1.5.0
jonassiewertsen/statamic-livewire: 3.3.1
statamic/seo-pro: 6.0.3
transformstudios/events: 5.4.3
transformstudios/front: dev-fix/to-data
transformstudios/github: dev-main
transformstudios/review: 5.0
transformstudios/simple: 5.0.0
transformstudios/uptime: dev-fix/front
```

### Installation

Fresh statamic/statamic site via CLI
