### ISSUE TITLE
[Dark] Bold text within `prose` content is unreadable

### ISSUE THREAD

**Issue by aaronbushnell** [statamic/cms#10234]
### Bug description

If a `<strong>` tag is used in any of the areas of Statamic that utilize Tailwind's `prose` class it does not properly swap to a light variant:

![Screenshot 2024-05-30 at 11 31 21 AM](https://github.com/statamic/cms/assets/315202/3424ccad-642b-49e5-a68b-7ce16a6eeead)

### How to reproduce

Add a `<strong>` tag with content in a popup/confirmation window or in the Markdown cheatsheet. Swapping to dark mode keeps the bold text dark and is not readable. 

### Environment

```yaml
Environment
Application Name: Statamic Starter
Laravel Version: 11.9.2
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: statamic-starter.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 8
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.6.2 PRO

Statamic Addons
bencarr/statamic-hyperlink: 3.0.3
rias/statamic-redirect: 3.7.1
statamic/seo-pro: 6.0.3
trendyminds/guide: dev-main
trendyminds/nerf: dev-main
trendyminds/orbit-statamic: 1.1.1
trendyminds/statamic-palette: 1.2.0
trendyminds/tip: dev-main
```

### Installation

Fresh statamic/statamic site via CLI
