### ISSUE TITLE
Config files not being updated

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#10239]
### Bug description

This started off by me configuring like I always do for automatic git commit / push. We started the project with v5.0.

This is the log:
```
[2024-05-31 00:53:25] local.ERROR: Process Class: Git
Command:  -c "user.name=xxx xxxx" -c "user.email=xxx xxxx" commit -m "Content saved [BOT]"
Error: sh: 1: -c: not found
```
(xxx for keeping it not so public)

So I thought ok - maybe this have been fixed so I compared to a project installed from v5.6.2 and yes, the `git.php > commands` file have been changed. So I got this working, but my question is - how come the config files is not updated when doing updates as recommended? Is it a bug, or is it not possible?

### How to reproduce

Explained above.

### Environment

```yaml
Environment
Application Name: Laugstol
Laravel Version: 11.7.0
PHP Version: 8.2.16
Composer Version: 2.7.2
Environment: local
Debug Mode: ENABLED
URL: laugstol.test/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 2 (Norsk, Engelsk)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.6.2 PRO

Statamic Addons
jacksleight/statamic-focal-link: 2.0.2
```

### Installation

Fresh statamic/statamic site via CLI
