### ISSUE TITLE
Query Scope can not overwrite `orderBy('date')` 

### ISSUE THREAD

**Issue by marcorieser** [statamic/cms#10230]
### Bug description
When having a collection with `date` enabled the configured sorting (in the collection in cp) gets applied when fetching the entries via collection tag. I want to overwrite that sorting in a query scope via `$query->orderBy('date', 'asc')` and I expect the entries to be sorted by date (asc) and title (desc). But the default sorting gets appended to the query which results in eg. `select * from entries where collection in ('tours') and published = '1' and redirect is null order by date asc, title desc, date asc` with two `order by date`s.

Querying the entries via the collection facade or the collections tag with the `sort` param works perfectly.

### How to reproduce
Clone the demo repo and read trough it's readme:
https://github.com/marcorieser/statamic-order-scope-bug

or

1. install a fresh Statamic site
2. create a collection
3. enable dates for the collection
4. set the default sorting to `desc`
5. list the entries in antlers via collection tag
6. change the order for `date` to `asc` via a query scope
7. notice that this did not work

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.9.2
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: statamic-order-scope-bug.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.6.1 PRO
```

### Installation

Fresh statamic/statamic site via CLI
