### ISSUE TITLE
Cache Manager/Static Page Cache indicates "Pages: 0"

### ISSUE THREAD

**Issue by tats149576** [statamic/cms#10235]
### Bug description

Site uses full page caching.  Upgraded from 5.5.0 -> 5.6.2.  No issues found, site functions as expected.  Noticed in Cache Manager that Static Page Cache now indicates "Pages: 0".  Cleared Static Page Cache, ran 'php please static:warm' and returns no errors, everything looks good.  Tested site, everything appears fine; forms work, content saves, no change in performance.  Checked cache folder contents and can see freshly cached files with new timestamps.  Static Page Cache still indicates "Pages: 0".  Prod is PHP 8.1; In lab running PHP 8.3 I did not experience this behavior.

### How to reproduce

(From 5.5.0)

composer require "statamic/cms 5.6.2"
php please static:warm

### Logs

```shell
No errors logged.
```

### Environment

```yaml
Environment
Application Name: Trans American
Laravel Version: 10.48.7
PHP Version: 8.1.2-1ubuntu2.17
Composer Version: 2.7.2
Environment: local
Debug Mode: OFF
URL:
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: full
Version: 5.6.2 PRO
```

### Installation

Starter Kit using via CLI

### Additional details

This isn't causing me any trouble and I can't find any errors being logged, just pointing out something odd I noticed.
