### ISSUE TITLE
A published status cannot be added to a widget

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#10256]
### Bug description

I configured a collection widget in the config file cp.php
```
'widgets' => [
        'getting_started',
    [
      'type' => 'collection',
      'collection' => 'articles',
      'fields' => ['date', 'tags'],
      'limit' => 10,
      'width' => 100,
      'sort' => 'date:desc',
  ],
],
```
In the 'fields' array I wanted to add the published status of my entries.
To no avail
I tried with 'status', 'published_status' and even 'default_published_status'

### How to reproduce

Configure a collection widget for the CP in the cp.php config file

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.4
PHP Version: 8.2.11
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: storyteller.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.6.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI
