### ISSUE TITLE
[Dark] Delete entry and navigation item modals show incorrect background against buttons

### ISSUE THREAD

**Issue by aaronbushnell** [statamic/cms#10252]
### Bug description

There's a couple modals that need some dark mode tuning! (via [Discord](https://discord.com/channels/489818810157891584/491735338377805835/1246770697439809586))

![Screenshot 2024-06-03 at 10 05 05 AM](https://github.com/statamic/cms/assets/315202/23d5d7e3-a6af-4155-951d-f4540bb95733)
![Screenshot 2024-06-03 at 10 05 17 AM](https://github.com/statamic/cms/assets/315202/d5f2e2a1-3fa8-4438-b2e7-1fbc5f16f463)

### How to reproduce

- Enable dark mode
- Attempt to delete an entry or a navigation link

### Environment

```yaml
Application Name: Statamic Starter
Laravel Version: 11.9.2
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: statamic-starter.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.6.2 PRO

Statamic Addons
bencarr/statamic-hyperlink: 3.0.3
```

### Installation

Fresh statamic/statamic site via CLI
