### ISSUE TITLE
Collection widget has a tiny top-left border radius in the header row when the “fields” option is activated.

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#10260]
### Bug description

It seems to me that this border radius is not necessary here.

<img width="941" alt="Bildschirmfoto 2024-06-04 um 11 26 00" src="https://github.com/statamic/cms/assets/8265902/60afe962-e648-499c-b2b4-0abc5df75fb8">

### How to reproduce

- Add some fields in a collection widget
```
[
    'type' => 'collection',
    'collection' => 'events',
    'fields' => ['date', 'verfuegbarkeit'],
],
```
- Go to dashboard. The nitpick UI thing with the border-radius is easier to recognize in dark mode.

### Environment

```yaml
Environment
Application Name: Kochort CMS
Laravel Version: 11.9.2
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: /
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.6.2 PRO

Statamic Addons
mitydigital/statamic-sticky-notes: 1.0.0
statamic/seo-pro: 6.0.3
stillat/relationships: 2.2.0
```

### Installation

Fresh statamic/statamic site via CLI
