### ISSUE TITLE
Entry can't be saved if the Slug contains underscore

### ISSUE THREAD

**Issue by o1y** [statamic/cms#10262]
### Bug description

Since Statamic 5 I can't save most of my entries, which contains a slug with underscores.

### How to reproduce

1. Add Entry with slug `foo_bar`
2. Save entry

Error:
```
Must contain only letters and numbers with dashes or underscores as separators.
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.10.0
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: statamic-test-v5.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.6.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI
