### ISSUE TITLE
CMD+S doesn't save when editing fields in the Blueprint / Fieldset builder

### ISSUE THREAD

**Issue by wesort** [statamic/cms#10276]
### Bug description

While editing a Bard fieldtype in the CP with a stack open, making a change and typing `cmd + s` shows "Saved" (green notification bottom left) but nothing is saved to disk.

### Steps
CP > Fieldsets > Select a fieldset > Fields > click into a Bard field (opens a "stack"):
- Make a change to something
- Type `cmd + s` > a green notification with "Saved" appears bottom-left

### Expectation
- For the change made to be saved to disk

### What actually happens
- Nothing is saved
- Workaround: click Apply button (stack closes) > click "Save" OR type `cmd + s`

### Suggestions
That `cmd + s` should either save it or not show the notification.

However, I wonder if there's something more to assess about the primary action button for the stack being "Apply". Maybe either:
- "Apply" could be replaced by something similar to the options available on entry editing:
  - Save: After saving > Continue Editing
  - Save: After saving > Close stack
- `cmd + s` could do nothing if a stack is open?
- `cmd + s` could trigger "Apply" (though ideally not close the stack)?

### Environment

```yaml
Application Name: Peascod
Laravel Version: 11.10.0
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: dev
Debug Mode: ENABLED
URL: dev.peascod.studio
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.7.2 PRO
```

### Installation

Fresh statamic/statamic site via CLI
