### ISSUE TITLE
Livewire "Uncaught Component already registered" since v5.6.0

### ISSUE THREAD

**Issue by lakkes-ra** [statamic/cms#10273]
### Bug description

I am using Mailcoach Self-Hosted with Statamic. Since I updated to `v5.6.0` and beyond the livewire components in the Mailcoach UI can't be used anymore. The console tells me "Uncaught Component already registered" when I use the "+ Add Campaign" Button.

![image](https://github.com/statamic/cms/assets/63732644/f7100f9c-21ff-4572-87c4-0bed08c8ef94)

With downgrading to `v5.5.0` it's not happening anymore. 

I don't know, if this is the right place for this issue, since it may also be an issue with Mailcoach itself, but since it happend with the update to `v5.6.0` you might already now a place or reason why this behavior could happen. I couldn't find it myself when I read through the changelog. I hope we can find some more information together. 

I can provide a repository, but you'll need a Mailcoach licence. 

### How to reproduce

- Install a fresh statamic installation with v5.6.0 or higher.
- Install [laravel-mailcoach](https://mailcoach.app/self-hosted/documentation/v8/getting-started/installation/in-an-existing-laravel-app) (You need authorization for that unfortunately)
- Use eloquent for Statamic Users 
- Use Mysql, since it's a requiremt for Mailcoach

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.10.0
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: livewire-component-already-registered.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Filament
Packages: forms, notifications, support, tables
Version: v3.2.40
Views: NOT PUBLISHED

Livewire
Livewire: v3.5.0

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.7.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI
