### ISSUE TITLE
CP: Update badge on up to date site

### ISSUE THREAD

**Issue by marcorieser** [statamic/cms#10277]
### Bug description

Sometimes the changelog for an addon does not get updated which causes an update badge in cp even if everything is up to date. In my case it's the Translation Manager addon. But found an issue that seems like to underline my case: https://github.com/statamic/cms/issues/6718

<img width="943" alt="Bildschirmfoto_2024-06-07_um_14 11 55" src="https://github.com/statamic/cms/assets/2395800/f96a09fd-8df0-4900-8364-c64e80d6b549">

### How to reproduce

No idea but installing the Translation Manager addon probably reproduces the issue atm.

### Environment

```yaml
Environment
Application Name: Wizard Live
Laravel Version: 11.10.0
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: statamic-wizard-promotions.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Livewire
Livewire: v3.5.0

Statamic
Addons: 5
Sites: 2 (German, English)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.7.2 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.4.0
marcorieser/statamic-vitals: 1.2.0
marcorieser/tailwind-merge-statamic: 1.1.0
ryanmitchell/statamic-translation-manager: 2.0.0
stillat/relationships: 2.2.0
```

### Installation

Fresh statamic/statamic site via CLI
