### ISSUE TITLE
Collection listing filters coming from global preferences can't be deleted

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#10278]
### Bug description

If you set custom filters in `preferences.yaml` like so:

```yaml
collections:
  orders:
    filters:
      betaald:
        display: Betaald
        filters:
          fields:
            order_status:
              operator: like
              value: paid
      verlopen:
        display: Niet betaald
        filters:
          fields:
            order_status:
              operator: '<>'
              value: paid
```
Every user gets those filters. This is neat. However as an individual user you can't delete them from the collection UI. I appreciate this because it's set as a site wide filter for all users, however perhaps the rename/delete options shouldn't be shown in this case because they don't work properly.

<img width="443" alt="Screenshot 2024-06-10 at 08 23 39" src="https://github.com/statamic/cms/assets/69107412/f4a0f8fa-c7b9-4be1-8e46-0ac536e117ac">

1. Rename creates a new view, just like duplicate.
2. Delete doesn't do anything.

### How to reproduce

1. Add a collection filter in the `preferences.yaml`
3. Check the UI and see that it offers options to delete and rename.

### Environment

```yaml
Environment
Application Name: Avond4daagse Baflo
Laravel Version: 11.10.0
PHP Version: 8.2.19
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: avond4daagsebaflo.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.7.2 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.3.1
studio1902/statamic-peak-seo: 8.14.0
studio1902/statamic-peak-summit: 0.2.0
studio1902/statamic-peak-tools: 6.1.0
```

### Installation

Starter Kit using via CLI
