### ISSUE TITLE
CP Nav: Asset container active status not updating when switching container via tabs

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#10285]
### Bug description

If you have a couple of asset containers and you switch form one to another via tabs the active state in the CP nav does not update. In the example below I clicked on the «Projekte» Tab, but in the CP nav «Download» stays active with bold text.

<img width="731" alt="Bildschirmfoto 2024-06-11 um 09 23 03" src="https://github.com/statamic/cms/assets/8265902/30178318-10a3-40c3-8d84-2293b718cb8e">

### How to reproduce

- Click through asset containers in the cp nav → active state (bold text) is updating
- Click on a container in the tab → active state in CP nav is not updating

### Environment

```yaml
Environment
Application Name: Studio Roth
Laravel Version: 11.10.0
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: studioroth.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.7.2 PRO

Statamic Addons
rias/statamic-color-swatches: 2.3.0
statamic/seo-pro: 6.0.3
```

### Installation

Fresh statamic/statamic site via CLI
