### ISSUE TITLE
Variables Inside Tag Parameters don't work for limit param in a collection

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#1029]
For the following setup, I'm getting this error: `Object of class Statamic\Fields\Value could not be converted to int`

```yaml
# home.md

latest_articles_number: '3'
```

```html
<!-- home.antlers.html -->

{{ collection:blog as="posts" :limit="latest_articles_number" }}
<section class="section has-background-black">
    {{ posts }}
    <div class="column">
      {{ partial:blog/card }}
    </div>
    {{ /posts }}
</section>
{{ /collection:blog }}
```

**Comment by edalzell** [comment]
@jimblue are you on the latest version? There was a change in how you update Statamic now.

**Comment by jimblue** [comment]
@edalzell I've use migrator maybe a week ago.
Since I update my project almost everyday: `composer update statamic/cms --with-dependencies`
But I don't know how to check for the actual version number?

**Comment by jimblue** [comment]
BTW here is the update log:

```bash
# > composer update statamic/cms --with-dependencies

Dependency "laravel/framework" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Dependency "laravel/framework" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: intervention/httpauth
Discovered Package: intervention/image
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: statamic/cms
Discovered Package: wilderborn/partyline
Package manifest generated successfully.
> @php artisan statamic:install --ansi
Addon manifest generated successfully.
Copied Directory [/vendor/statamic/cms/resources/users] To [/resources/users]
Publishing complete.
Publishing complete.
Copied Directory [/vendor/statamic/cms/resources/dist] To [/public/vendor/statamic/cp]
Publishing complete.
Publishing complete.
Compiled views cleared!
Application cache cleared!
```

**Comment by jasonvarga** [comment]
Thank you for providing the logs but i don’t think you’ve done anything wrong. What kind of field is latest_articles_number in your blueprint?

**Comment by jimblue** [comment]
Hey @jasonvarga, sure here is the interesting part of my `blueprint`:

```yaml
latest_articles:
    display: 'Latest articles'
    fields:
      -
        handle: latest_articles_enabled
        field:
          type: toggle
          display: Enable
      -
        handle: latest_articles_heading
        field:
          type: text
          display: Heading
          localizable: true
          validate: required
          if:
            latest_articles_enabled: '1'
      -
        handle: latest_articles_number
        field:
          type: text
          display: 'Post(s) to display'
          default: 3
          validate: 'required|min:1|numeric'
          character_limit: 0
          if:
            latest_articles_enabled: '1'
```
