### ISSUE TITLE
Entries sometimes won't publish

### ISSUE THREAD

**Issue by tenmillionteeth** [statamic/cms#10297]
### Bug description

A client site has a collection of events. Since 4.58, sometimes when adding an event, then clicking save + publish, the entry doesn't publish. It seems to go into a draft state, despite not indicating that it's in a draft state. Clicking save + publish a second time then publishes the entry. 

It was not an issue in 4.57.3, but every version since then it's a sometimes issue. 

### How to reproduce

Hard to recreate, because it doesn't happen every time. Nothing in the logs. 

### Environment

```yaml
Environment
Application Name:
Laravel Version: 10.48.12
PHP Version: 8.3.8
Composer Version: 2.7.6
Environment: production
Debug Mode:
URL: 
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: mysql
Logs: stack / single
Mail: postmark
Queue: sync
Session: file

Statamic
Addons: 
Sites: 3 
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.7.2 PRO

Statamic Addons
4rn0/statamic-image-optimizer: 1.1.1
aerni/font-awesome: 2.1.0
anakadote/statamic-recaptcha: 1.0.14
aryehraber/statamic-color-extractor: 1.5.0
jacksleight/statamic-bard-texstyle: 3.2.2
mitydigital/feedamic: 2.3.3
rias/statamic-redirect: 3.7.1
statamic/collaboration: 1.0.0
statamic/seo-pro: 6.0.3
stillat/antlers-layouts: 2.1.0
```

### Installation

Fresh statamic/statamic site via CLI
