### ISSUE TITLE
Updated to 5.8.0, I can't save pages?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#10317]
### Bug description

When I press save I get this error

```
Method Illuminate\Validation\Validator::validateUniqueEntryValue does not exist.
```

### How to reproduce

Updated from 4 to 5.7.3, then 5.8.0. Not sure where it was introduced.

### Logs

```shell
local.ERROR: Method Illuminate\Validation\Validator::validateUniqueEntryValue does not exist. {"userId":"a22581f2-580e-4041-81e2-e343df73d946","exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Validation\\Validator::validateUniqueEntryValue does not exist. at /Users/xxxxxxxxx/Repositories/xxxxxx/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:1638)
```

### Environment

```yaml
Environment
Application Name: xxxxxxxx
Laravel Version: 11.10.0
PHP Version: 8.3.8
Composer Version: 2.6.5
Environment: local
Debug Mode: OFF
URL: xxxxxxxx.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: redis
Database: sqlite
Logs: stack / single
Mail: log
Queue: redis
Session: file

Livewire
Livewire: v3.5.0

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.8.0 PRO

Statamic Addons
jonassiewertsen/statamic-jobs: 1.5.0
jonassiewertsen/statamic-live-search: 2.1.1
jonassiewertsen/statamic-livewire: 3.5.0
statamic/collaboration: 1.0.0
visuellverstehen/statamic-anchor-navigation: 1.0.0
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by ryanmitchell** [comment]
Can you share the blueprint and config for what you are saving (eg if its a collection, share the collection config).

**Comment by stephenmeehanuk** [comment]
Config
```
title: Products
template: "@blueprint"
layout: layouts/triple
revisions: false
route: "/{{ parent_uri }}/{{ slug }}"
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  - label: Entry
    url: "{permalink}"
    refresh: true
structure:
  root: false
  max_depth: 5
  slugs: true
```

**Comment by stephenmeehanuk** [comment]
Blueprint
```
title: Page
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              validate:
                - required
              instructions: 'Used in navigation.'
              listable: true
              input_type: text
              antlers: false
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: product_media_asset
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Page Image'
              icon: assets
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              replicator_preview: true
      -
        display: Body
        fields:
          -
            handle: intro
            field: common.body_bard
            config:
              buttons:
                - anchor
              link_noopener: true
              link_noreferrer: true
              target_blank: true
              fullscreen: false
              allow_source: false
              display: Introduction
              container: assets
              instructions: 'Optional. Example length: Our innovative engineering and product development solutions inspire the safety, reliability, and performance of critical transportation and energy infrastructures.'
              character_limit: 160
          -
            import: bard_sets
            prefix: pages_
  hero:
    display: Hero
    sections:
      -
        display: Hero
        fields:
          -
            handle: hero_style
            field:
              options:
                jumbo_banner: Full
                fifty_banner: 50/50
              default: jumbo_banner
              type: button_group
              display: 'Hero Style'
              icon: button_group
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              width: 50
          -
            handle: toggle_default_banner
            field:
              default: false
              type: toggle
              display: 'Toggle Hero'
              icon: toggle
              width: 50
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            import: banner
            prefix: pages_
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate:
                - required
                - 'unique_entry_value:{collection},{id},{site}'
          -
            handle: parent
            field:
              type: entries
              collections:
                - pages
              max_items: 1
              listable: false
              localizable: true
  seo:
    display: SEO
    sections:
      -
        fields:
          -
            import: meta_data

```

**Comment by ryanmitchell** [comment]
Looks like one of the update scripts hasn't run... 

`unique_entry_value:{collection},{id},{site}`

should be

'new \Statamic\Rules\UniqueEntryValue({collection}, {id}, {site})'

**Comment by stephenmeehanuk** [comment]
Great

Changing this

```
handle: slug
            field:
              type: slug
              localizable: true
              validate:
                - required
                - 'unique_entry_value:{collection},{id},{site}'
```
To this:
```
handle: slug
            field:
              type: slug
              localizable: true
              validate:
                - required
                - 'new \Statamic\Rules\UniqueEntryValue({collection}, {id}, {site})'
```
Worked.

Really appreciate the help, thanks.
