### ISSUE TITLE
Collapsing/expanding a structured collection in a stack selects item

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#10321]
### Bug description

If you have a structured collection and use an entries field to select an item from this collection you are presented with a stack that renders the structured collection. If you expand/collapse an item in this stack it selects the item as opposed to just expanding/collapsing.

https://github.com/statamic/cms/assets/69107412/85e1faca-15a0-4b83-9067-481880aca6ec

### How to reproduce

1. Create a structured collection.
2. Add entries and make sure they're nested.
3. Create an entry field (stack selector) in some blueprint/fieldset (probably with `max_items` set to 1).
4. Try to link to an entry by opening the stack selector. 
5. Click on one of the expand/collapse chevrons.

You'll see the entries collapse/expand but it also selects the current entry. The latter shouldn't happen.

### Environment

```yaml
Environment
Application Name: Connect2id
Laravel Version: 11.10.0
PHP Version: 8.2.20
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: connect2id.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.8.0 PRO

Statamic Addons
rias/statamic-color-swatches: 2.3.0
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.3.2
studio1902/statamic-peak-seo: 8.14.0
studio1902/statamic-peak-tools: 6.1.0
```

### Installation

Fresh statamic/statamic site via CLI
