### ISSUE TITLE
Handles with double underscores invalidate in Statamic 5

### ISSUE THREAD

**Issue by Ben-Kemp-8433** [statamic/cms#10328]
### Bug description

When copying handles for my navigation from a version 4 updated to 5 website into a fresh version 5 website I noticed some of the handles return "The given data was invalid".

Regular handles, such as `some_collection_handle`, do work perfectly fine. But the issue lies in handles that have double underscores, like my footer nav being called `footer_navigation__socials`
Admittedly the way I created these handles isn't usual, but it created some structure within my code. This codebase is shared among several websites that use the same structure, so I can't simply change these handles out.

### How to reproduce

Simply create a new navigation with the handle being anything with a double underscore such as previously mentioned `footer_navigation__socials` and press save.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.12
PHP Version: 8.3.8
Composer Version: 1.10.8
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 8
Sites: 4 (Nederlands, English, Français, Deutsch)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.8.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.12.0
aryehraber/statamic-logbook: 3.3.0
duncanmcclean/cookie-notice: 9.0.0
nineteensquared/instagram: 1.2.0
notonpaper/form-blacklist: dev-AVZ-10
webographen/statamic-admin-log: 1.1.0
withcandour/aardvark-seo: 5.0.0
xndbogdan/statamic-bard-text-color: 5.1.0
```

### Installation

Existing Laravel app

### Additional details

We are building a suite for a customer with several websites on one codebase. The designing process of the websites takes a long time, so while a few websites were already passing into Acceptance, there's still a few that need to be set up. Part way through this process we decided to update to Statamic 5.

Handles created in Statamic 4 with my specific structure get moved over without issue, but creating the same handle through the Control Panel in version 5 leads to not being able to save and thus not able to progress.
