### ISSUE TITLE
Git integration throwing error unnecessarily

### ISSUE THREAD

**Issue by o1y** [statamic/cms#10329]
### Bug description

Getting errors like this.

```bash
[2024-06-19 07:58:48] production.ERROR: Process Class: Git
Command: 'git' 'push' '--porcelain'
Error: remote: . Processing 1 references
remote: Processed 1 references in total
```

However, this seems not to be an actual git error.

### How to reproduce

Use git integration

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.7.0
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: localhost:8080
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: reverb
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 11 (English, Deutsch, Español, and 8 more)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.6.2 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 2.3.1
jacksleight/statamic-bard-texstyle: 3.2.2
statamic/collaboration: 1.0.0
statamic/ssg: 3.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

```bash
git --version
git version 2.39.2
```
