### ISSUE TITLE
Optional labels on Button Group are not optional?

### ISSUE THREAD

**Issue by eminos** [statamic/cms#10323]
### Bug description

It doesn't allow the field to be saved when leaving the label fields empty.
![image](https://github.com/statamic/cms/assets/1682784/0034c169-6065-4059-b143-a8416ebe6d84)
It saves fine with the label fields filled.

### How to reproduce

.

### Environment

```yaml
Laravel Version: 11.10.0
PHP Version: 8.3.6
Version: 5.7.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI
