### ISSUE TITLE
`raw` modifier doesn't seem to do anything

### ISSUE THREAD

**Issue by andymswick** [statamic/cms#1032]
If I have a select `bg_color` with the following options 

```
options:
   bg-transparent: Transparent
   bg-black: Black
   bg-white: White
   bg-gray-100: 'Gray 100 (Lightest)'
   bg-gray-200: 'Gray 200'
 ...
```

When I save the page file has the following:

`bg_color: bg-black`

In my template when I use 

`{{ bg_color | raw }}`

I get:

`Black`

Also the raw modifier does not appear to be mentioned anywhere else in the docs other than: https://statamic.dev/fieldtypes/select
