### ISSUE TITLE
Select field without labels producing nulls

### ISSUE THREAD

**Issue by andymswick** [statamic/cms#1033]
When saving a field (fieldset?) in the CP without labels the result is the following:

```
container:
    options:
      w-1/5: null
      w-1/4: null
      w-1/3: null
      w-2/5: null
      w-1/2: null
      w-3/5: null
      w-2/3: null
      w-4/5: null
      container: null
      w-full: null
    clearable: true
    multiple: false
    searchable: true
    taggable: false
    push_tags: false
    type: select
    localizable: false
    display: 'Container Width'
```

My saved file has the following:

`container: w-1/2`

Template:

```
<div class="md:{{ container }}">...</div>
```

Results in:

```
<div class="md: ">...</div>
```
