### ISSUE TITLE
Revision history panel of unpublished entries loads indefinitely

### ISSUE THREAD

**Issue by faltjo** [statamic/cms#10331]
### Bug description

When clicking on the 'View History' button of an unpublished entry in the CP, the revision history panel loads indefinitely.
The called route `cp/collections/{collection}/entries/{entry}/revisions` fails with error 500 in the background.

Illuminate\Routing\Exceptions\UrlGenerationException
Missing required parameter for [Route: statamic.cp.collections.entries.revisions.show] [URI: cp/collections/{collection}/entries/{entry}/revisions/{revision}] [Missing parameter: revision].

### How to reproduce

Open an unpublished entry in the CP and click on `View History`. The panel `Revision History` opens on the right side, but loads indefinitely.

### Logs

```shell
local.ERROR: Missing required parameter for [Route: statamic.cp.collections.entries.revisions.show] [URI: cp/collections/{collection}/entries/{entry}/revisions/{revision}] [Missing parameter: revision]. 

"exception":"[object] (Illuminate\\Routing\\Exceptions\\UrlGenerationException(code: 0): Missing required parameter for [Route: statamic.cp.collections.entries.revisions.show] [URI: cp/collections/{collection}/entries/{entry}/revisions/{revision}] [Missing parameter: revision]. at vendor/laravel/framework/src/Illuminate/Routing/Exceptions/UrlGenerationException.php:35)
```

### Environment

```yaml
Environment
Laravel Version: 11.8.0
PHP Version: 8.3.7
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: redis
Database: pgsql
Logs: stack / daily, sentry
Mail: ses
Queue: database
Session: file

Livewire
Livewire: v3.4.12

Statamic
Addons: 4
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.5.0 PRO

Statamic Addons
rias/statamic-address-field: 1.3.0
rias/statamic-redirect: 3.7.1
statamic-rad-pack/meilisearch: 3.3.0
statamic/eloquent-driver: 4.0.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: eloquent
Navigations: file
Revisions: eloquent
Taxonomies: file
Terms: file
```

### Installation

Existing Laravel app
