### ISSUE TITLE
Password resetter not defined error

### ISSUE THREAD

**Issue by steveparks** [statamic/cms#10338]
### Bug description

When I submit my email in the password reset process, I get an error "Password resetter [resets] is not defined."

It seems this has come up in the past, and I tried the workarounds from those threads.

1. I checked my auth.php against statamic/statamic version
2. I added this code to the bottom of app/Models/user.php:
```
     public function sendPasswordResetNotification($token)
     {
         $this->notify(new \Statamic\Notifications\PasswordReset($token));
     }
```

I'm on Statamic 5.7.3, Laravel 11.10.0, PHP 8.3.8, running locally under Herd.

I've moved my users to the database, following the docs, and all else works well with users.

I've set up mail sending via SMTP to Mailtrap, and confirmed it works by sending a test email from the cp/utilities/email.

I'm simply using the example code from the documentation on Tags to place the two password reset forms on pages.

The User:Forgot_Password_Form page submits.

Then instead of loading my defined page which the User:Reset_Password_Form tag is on, it goes to /!/auth/password/email and shows the error.

I discussed this issue in Discord in a thread with Erin: https://discord.com/channels/489818810157891584/1252643229715796079

### How to reproduce

1. Migrate users to a relational database, to use the eloquent driver
2. Set up the password reset form tags on pages
3. Go to the first form, enter email and submit

### Environment

```yaml
Environment
Application Name: Convivio
Laravel Version: 11.10.0
PHP Version: 8.3.8
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: convivio2.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.7.3 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.3.1
studio1902/statamic-peak-seo: 8.14.0
studio1902/statamic-peak-tools: 6.1.0
tv2regionerne/statamic-passport: 1.4.1
tv2regionerne/statamic-private-api: 1.14.0
```

### Installation

Fresh statamic/statamic site via CLI
