### ISSUE TITLE
Collection widget pagination overflows

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#10348]
### Bug description

When you have a lot of entries and use a collection widget, the pagination overflows:

<img width="464" alt="Screenshot 2024-06-21 at 10 34 51" src="https://github.com/statamic/cms/assets/69107412/5fb89fa4-19e2-4b13-920b-abd71f708725">
<img width="459" alt="Screenshot 2024-06-21 at 10 53 20" src="https://github.com/statamic/cms/assets/69107412/91a5745b-7d0b-4dcb-a9ea-a049b81bbccd">

### How to reproduce

1. Use a collection widget
2. Generate a lot of entries
3. Check out the pagination

### Environment

```yaml
Environment
Application Name: Connect2id
Laravel Version: 11.11.1
PHP Version: 8.2.20
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: connect2id.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.10.0 PRO

Statamic Addons
rias/statamic-color-swatches: 2.3.0
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.3.2
studio1902/statamic-peak-seo: 8.14.0
studio1902/statamic-peak-tools: 6.1.0
```

### Installation

Starter Kit using via CLI
