### ISSUE TITLE
"Window" in the pagination not working as documented

### ISSUE THREAD

**Issue by ChrisLCarrBF** [statamic/cms#10363]
### Bug description

I have a brand new Statamic installation and am having the **EXACT** same issue as [is described here](https://discord.com/channels/489818810157891584/1245032826185973916).

### How to reproduce

I used the [code here](https://statamic.dev/tags/collection/#pagination-examples) and it appears that inside {{ links:segments }} you have {{ first }} and that outputs the number of collection pages, everything after that appears to do nothing.

### Logs

```shell
I have my collection tag as:
{{ collection :from="mount" paginate="9" on_each_side="1" as="cards" taxonomy:benchmarks="{get:benchmark}" }}

Then, the structure of my {{ paginate }} block is basically what you see at https://statamic.dev/tags/collection/#pagination-examples

Here is a dump of the pagination links:
array:2 [▼ // vendor/statamic/cms/src/Modifiers/CoreModifiers.php:599
  "all" => array:12 [▼
    0 => array:2 [▼
      "page" => 1
      "url" => "http://divosa-benchmark.test/publicaties?page=1"
    ]
    1 => array:2 [▼
      "page" => 2
      "url" => "http://divosa-benchmark.test/publicaties?page=2"
    ]
    2 => array:2 [▼
      "page" => 3
      "url" => "http://divosa-benchmark.test/publicaties?page=3"
    ]
    3 => array:2 [▼
      "page" => 4
      "url" => "http://divosa-benchmark.test/publicaties?page=4"
    ]
    4 => array:2 [▼
      "page" => 5
      "url" => "http://divosa-benchmark.test/publicaties?page=5"
    ]
    5 => array:2 [▼
      "page" => 6
      "url" => "http://divosa-benchmark.test/publicaties?page=6"
    ]
    6 => array:2 [▼
      "page" => 7
      "url" => "http://divosa-benchmark.test/publicaties?page=7"
    ]
    7 => array:2 [▼
      "page" => 8
      "url" => "http://divosa-benchmark.test/publicaties?page=8"
    ]
    8 => array:2 [▼
      "page" => 9
      "url" => "http://divosa-benchmark.test/publicaties?page=9"
    ]
    9 => array:2 [▼
      "page" => 10
      "url" => "http://divosa-benchmark.test/publicaties?page=10"
    ]
    10 => array:2 [▼
      "page" => 11
      "url" => "http://divosa-benchmark.test/publicaties?page=11"
    ]
    11 => array:2 [▼
      "page" => 12
      "url" => "http://divosa-benchmark.test/publicaties?page=12"
    ]
  ]
  "segments" => array:3 [▼
    "first" => array:6 [▼
      0 => array:2 [▼
        "page" => 1
        "url" => "http://divosa-benchmark.test/publicaties?page=1"
      ]
      1 => array:2 [▼
        "page" => 2
        "url" => "http://divosa-benchmark.test/publicaties?page=2"
      ]
      2 => array:2 [▼
        "page" => 3
        "url" => "http://divosa-benchmark.test/publicaties?page=3"
      ]
      3 => array:2 [▼
        "page" => 4
        "url" => "http://divosa-benchmark.test/publicaties?page=4"
      ]
      4 => array:2 [▼
        "page" => 5
        "url" => "http://divosa-benchmark.test/publicaties?page=5"
      ]
      5 => array:2 [▼
        "page" => 6
        "url" => "http://divosa-benchmark.test/publicaties?page=6"
      ]
    ]
    "slider" => []
    "last" => array:2 [▼
      0 => array:2 [▼
        "page" => 11
        "url" => "http://divosa-benchmark.test/publicaties?page=11"
      ]
      1 => array:2 [▼
        "page" => 12
        "url" => "http://divosa-benchmark.test/publicaties?page=12"
      ]
    ]
  ]
]
```

### Environment

```yaml
Environment
Application Name: Divosa Benchmark
Laravel Version: 11.7.0
PHP Version: 8.2.19
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: divosa-benchmark.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.5.0 PRO

Statamic Addons
ryanmitchell/statamic-translation-manager: 2.0.0
studio1902/statamic-peak-browser-appearance: 3.4.0
studio1902/statamic-peak-commands: 8.3.0
studio1902/statamic-peak-seo: 8.13.3
studio1902/statamic-peak-tools: 6.1.0
```

### Installation

Starter Kit using via CLI

### Additional details

Nothing terribly fancy. I used the fabulous Peak starter kit by @robdekort. @edalzell, I opened this issue because you suggested to do so [in your comment](https://discord.com/channels/489818810157891584/1245032826185973916/1245445515760504872). Hopefully we can get the code to match the documentation. Thanks so much, in advance! I really appreciate it!
