### ISSUE TITLE
Moving an asset did not update refs in globals

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#10385]
### Bug description

I haven't tested or investigated this much at all, but I moved an asset to a subfolder and it caused a crash on my website.

The image was included as a subfield within a Grid fieldtype, within my globals. My template code crashed because the image was no longer available. The reference to it was not updated after the move.

I have reinforced my code to handle situations like this but I just wanted to flag the error. You might want to check that there is a system in place within the asset reference updater code to handle any global fields that reference the asset.

Thanks.

### How to reproduce

Move an asset that is referenced in a global grid field.

### Environment

```yaml
Environment
Laravel Version: 11.14.0
PHP Version: 8.3.8
Composer Version: 2.7.7
Environment: production
Debug Mode: OFF
Maintenance Mode: OFF
Timezone: Europe/Dublin
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Livewire
Livewire: v3.5.1

Statamic
Addons: 4
Sites: 1
Stache Watcher: Disabled
Static Caching: half
Version: 5.12.0 Solo

Statamic Addons
pecotamic/sitemap: 1.4.7
spatie/statamic-responsive-images: 5.0.0
stuartcusackie/statamic-cache-requester: 1.2.1
stuartcusackie/statamic-seo: 0.9.1
```

### Installation

Fresh statamic/statamic site via CLI
