### ISSUE TITLE
Search Tag does not contain Supplementing Data

### ISSUE THREAD

**Issue by jbrhel** [statamic/cms#10384]
### Bug description

After upgrading to version 5.8.0 and higher, the tag {{ search:results ...}} does not display Supplementing Data.

In the collection items for Articles, I have associated the taxonomies tags, categories, and the entity users (authors), but it does not return the expected data and falls back in a cascade to the item's title.

The screenshots show the example before and after version 5.8.0.

The problem is likely in the implementation of PR [323](https://github.com/statamic/cms/pull/10301).

### How to reproduce

Upgrade to 5.8.0 or higher.
Have a search template  that refers to related entries or taxonomies."

```
{{ search:results index="articles" }}
  {{ title }}
  {{ tags }}
    {{ title }}
  {{ /tags }}
{{ /search:results }}
```

config/statamic/search.php
```

    'indexes' => [
        'articles' => [
            'driver' => 'local',
            'searchables' => 'collection:articles',
            'fields' => ['title', 'perex', 'article_content'],
        ],
    ]
```

![Cursor-2](https://github.com/statamic/cms/assets/1133430/0b0fd625-503c-47d5-87e6-01ae6e1dd5fc)

![Cursor](https://github.com/statamic/cms/assets/1133430/4f376462-34a8-426a-a4d1-1503badb5b06)

### Environment

```yaml
Environment
Application Name: GDPR.cz
Laravel Version: 11.14.0
PHP Version: 8.2.20
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: gdpr.cz.test/
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.12.0 PRO

Statamic Addons
edalzell/forma: 3.0
jacksleight/statamic-bard-mutator: 2.3.1
pecotamic/sitemap: 1.4.7
statamic-rad-pack/mailchimp: 5.0.1
```

### Installation

Fresh statamic/statamic site via CLI
