### ISSUE TITLE
Collection widget with custom fields miss a border above the table header

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#10396]
### Bug description

Very minor. When you create a collection widget for the dashboard and include a bunch of custom fields, there's a visual border missing above the table header.

<img width="947" alt="Screenshot 2024-07-04 at 16 20 41" src="https://github.com/statamic/cms/assets/69107412/43b16de0-e931-47a0-93b3-341b2d1f3f54">

### How to reproduce

Do the obvious thing, create a collection with some fields, create a widget, include the fields in the widget. You got this.

### Environment

```yaml
Environment
Application Name: Connect2id
Laravel Version: 11.14.0
PHP Version: 8.2.20
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: connect2id.test
Maintenance Mode: OFF
Timezone: Europe/Sofia
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Locales
Installed: en
LaravelLang\Actions\Plugin: 1.8.4
LaravelLang\Attributes\Plugin: 2.10.7
LaravelLang\HttpStatuses\Plugin: 3.8.3
LaravelLang\Lang\Plugin: 15.5.4
Locales Version: 2.9.2
Protected: en
Publisher Version: 16.4.0

Livewire
Livewire: v3.5.2

Statamic
Addons: 7
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.12.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.6.0
mitydigital/statamic-scheduled-cache-invalidator: 2.0.5
rias/statamic-color-swatches: 2.3.0
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.3.2
studio1902/statamic-peak-seo: 8.15.2
studio1902/statamic-peak-tools: 6.1.0
```

### Installation

Starter Kit using via CLI
