### ISSUE TITLE
StaticWarmJob is not unique

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#10404]
### Bug description

If you run `php please static:warm --queue`  the jobs dispatched are not unique. Let's say you have a `warm` command in your deploy script and do multiple deployments, the queue currently gets piled with warm jobs for the same URL's. I'm working on a site with 600+ entries and this has quite an impact. 

### How to reproduce

1. Run `static:warm` on a queue. 
2. Run `static:warm` on a queue again.
3. Notice the amount of jobs on the queue gets doubled. 

### Environment

```yaml
Environment
Application Name: Connect2id
Laravel Version: 11.14.0
PHP Version: 8.2.20
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: connect2id.test
Maintenance Mode: OFF
Timezone: Europe/Sofia
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Locales
Installed: en
LaravelLang\Actions\Plugin: 1.8.4
LaravelLang\Attributes\Plugin: 2.10.7
LaravelLang\HttpStatuses\Plugin: 3.8.3
LaravelLang\Lang\Plugin: 15.5.4
Locales Version: 2.9.2
Protected: en
Publisher Version: 16.4.0

Livewire
Livewire: v3.5.2

Statamic
Addons: 7
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: full
Version: 5.13.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.6.0
mitydigital/statamic-scheduled-cache-invalidator: 2.0.5
rias/statamic-color-swatches: 2.3.0
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.4.0
studio1902/statamic-peak-seo: 8.15.2
studio1902/statamic-peak-tools: 6.3.0
```

### Installation

Starter Kit using via CLI
