### ISSUE TITLE
Asset Relationship Field breaks in antlers after statamic 5 update

### ISSUE THREAD

**Issue by danielml01** [statamic/cms#10411]
### Bug description

in asset relationship fields, asset ids stored as container::filepath generate an error when called to display in antlers after updgrade to statamic 5 (they still work in the control panel) Temporarily can be fixed by going to the entry with the field and saving without changing anything. This changes the stored id from container::filepath to just filepath.

### How to reproduce

create an entry that has an asset relationship field. 
Select an asset and save the entry.
Edit yaml file for the entry and format the stored value to container::filepath (as it was previously) 
save yaml file
in the antler, display any value from the related asset > this will generate an error in statamic 5

### Logs

```shell
Found 1 error while validating the input provided for the GetObject operation: [Key] expected string length to be >= 1, but found string length of 0
```

### Environment

```yaml
Environment
Application Name: REDACTED
Laravel Version: 10.48.12
PHP Version: 8.1.20
Composer Version: 2.5.8
Environment: dev
Debug Mode: OFF
URL: REDACTED
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: errorlog
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 12
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.7.2 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.3.0
jacksleight/statamic-bard-texstyle: 3.2.2
kadegray/statamic-country-and-region-fieldtypes: 1.2.4
rias/statamic-color-swatches: 2.3.0
simonridley/tracking-code-manager: 1.0.2
statamic/eloquent-driver: 4.2.0
stillat/relationships: 2.2.0
teamddm/aws-transcode: dev-main
teamddm/cp-password-expires: dev-main
teamddm/statamic-mixpanel: dev-main
teamddm/statamic-pdf-thumbnailer: dev-main
webographen/statamic-admin-log: 1.1.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Starter Kit using via CLI
