### ISSUE TITLE
Radio buttons in form submission not showing (dark mode)

### ISSUE THREAD

**Issue by geertjanknapen1** [statamic/cms#10427]
### Bug description

So I have a form with radio buttons, that contain 6 options.
Upon submitting the form I can see the correct selected radio option.
When I go to the submission, none of the radio buttons are selected.

The radio button should not be a required field. How would one go about resolving this? See the images below for a better understanding of the issue.

Blueprint:
![image](https://github.com/statamic/cms/assets/33750300/b6b577ed-6976-4ca6-8806-2155e6e87877)

The submission (we use AJAX):
![image](https://github.com/statamic/cms/assets/33750300/e7066783-b345-4cbb-8c24-081f9c40bb9e)

The submission in Control Panel:
![image](https://github.com/statamic/cms/assets/33750300/112138fe-d596-4c21-84f4-fa8d0155ae96)

### How to reproduce

Create a form. 
Add radio buttons with a few options
Select one of the options and submit the form.
Look at the latest form submission in CP.
No radio button selected.

### Environment

```yaml
Environment
Application Name: mysite
Laravel Version: 11.11.0
PHP Version: 8.3.8
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: mysite.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 2 (English, Dutch)
Stache Watcher: Disabled
Static Caching: half
Version: 5.9.0 PRO

Statamic Addons
spatie/statamic-responsive-images: 5.0.0
statamic-rad-pack/meilisearch: 3.3.0
withcandour/aardvark-seo: 5.0.0
```

### Installation

Existing Laravel app
