### ISSUE TITLE
Performance issue when switching between localizations on entry publish form

### ISSUE THREAD

**Issue by JoeriE** [statamic/cms#10429]
### Bug description

I upgraded to the latest version of Statamic and everything in the control panel runs smooth and fast except when I want to switch the sites on a entry. It takes more than 10 seconds to load the site in a different language. Is this a known issue? it doesn't really depend on the amount content, we've tested it with no content and a lot of content on the page. 

Also 'Unsaved changes' is immediately appearing without changing anything. 

### How to reproduce

It mainly happens on production / staging server, locally everything runs fast most of the time. This one specific project is really slow, but it has the same hosting settings as other Statamic projects that run fast. 

### Environment

```yaml
Environment
Application Name:
Laravel Version: 11.15.0
PHP Version: 8.2.21
Composer Version: 2.7.7
Environment: staging
Debug Mode: ENABLED
URL: 
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 4 (Nederlands, English, Français, Portuguese)
Stache Watcher: Disabled
Static Caching: full
Version: 5.13.0 PRO

Statamic Addons
aerni/advanced-seo: 2.6.0
stillat/relationships: 2.2.1
swiftmade/statamic-clear-assets: 3.0.0
```

### Installation

Fresh statamic/statamic site via CLI
