### ISSUE TITLE
Select fieldtype with max items set causes wrong cursor to appear

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/cms#10431]
### Bug description

I created a select field with the max items set, but when the select field is full it shows the do not enter cursor over the whole field (including the items themselves) which is confusing.

Example:
![image](https://github.com/statamic/cms/assets/3847288/d7fa6d0c-4922-4c0b-9f9a-1c560b82bf47)

### How to reproduce

1. Create a select field
2. Set the max items on the select field
3. Save it to a blueprint
4. Fill out an entry with the select field and select the max number of items
5. Cursor shows the do not enter cursor when hovering over items even though you can drag the items and click the x to remove them

### Environment

```yaml
Environment
Application Name: Website
Laravel Version: 11.15.0
PHP Version: 8.3.8
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: website.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.2

Statamic
Addons: 18
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.14.0 PRO

Statamic Addons
aerni/livewire-forms: 9.3.0
aerni/social-links: 3.2.0
aryehraber/statamic-logbook: 3.3.0
edalzell/forma: 3.0.1
godismyjudge95/statamic-embera: 1.1.1
jonassiewertsen/statamic-livewire: 3.6.0
kolaente/statamic-snippet: 1.1.2
mitydigital/statamic-google-fonts: 2.0.0
patrickjunod/image-select: 0.2.1
plugrbase/statamic-maintenance-mode: 1.07
statamic-rad-pack/mailchimp: 5.0.1
statamic-rad-pack/meilisearch: 3.3.0
statamic/seo-pro: 6.0.3
stillat/antlers-components: 2.2.0
stillat/relationships: 2.2.1
thoughtco/statamic-restrict-fields: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI
