### ISSUE TITLE
Wrong sorting in a Collection, when Entries are numbered with single and more digits at the end

### ISSUE THREAD

**Issue by maltemichels** [statamic/cms#10449]
### Bug description

When I create entries which are numbered from single digits (1) to two digits (10), then the sorting looks like this:
<img width="350" alt="Bildschirmfoto 2024-07-13 um 17 49 26" src="https://github.com/user-attachments/assets/bc73003f-8e84-4c45-8914-126aa9f26f24">

Wouldn't it be expected to sort like this? Small problem, but sometimes these are the most frustrating. 😬
```
Heading towards NowHere 1
Heading towards NowHere 2
Heading towards NowHere 3
Heading towards NowHere 4
Heading towards NowHere 5
Heading towards NowHere 6
Heading towards NowHere 7
Heading towards NowHere 8
Heading towards NowHere 9
Heading towards NowHere 10
…
```

### How to reproduce

Creating entries which are numbered at the end. For example from 1 through 10. Then the 10th will follow the first not the 9th.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.15.0
PHP Version: 8.3.7
Composer Version: 2.3.10
Environment: local
Debug Mode: OFF
URL: localhost
Maintenance Mode: OFF
Timezone: CET
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.14.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
