### ISSUE TITLE
Reupload asset broken

### ISSUE THREAD

**Issue by alexthekiwi** [statamic/cms#10440]
### Bug description

I tried to re-upload a file using the asset browser, and nothing happened - showing a Javascript console error.

### How to reproduce

This occurs from a brand new installation of Statamic created with `statamic new`, using Statamic version `"statamic/cms": "^5.0"`.

Example repo: https://github.com/alexthekiwi/file-reupload-statamic

To reproduce:
1. Log into CMS
2. Upload an asset
3. Click the "Reupload" button, from either the modal or the assets index view
4. Select asset
5. See browser console error, and no file populated in the input (can't save)

### Logs

```shell
TypeError: Cannot read properties of null (reading 'push')
    at q.uploadComplete (app-bdb8f92f.js:390:251254)
    at invokeWithErrorHandling (app-bdb8f92f.js:5:37633)
    at q.I (app-bdb8f92f.js:5:14221)
    at invokeWithErrorHandling (app-bdb8f92f.js:5:37633)
    at M.$emit (app-bdb8f92f.js:5:28219)
    at q.handleUploadSuccess (app-bdb8f92f.js:192:5563)
    at app-bdb8f92f.js:192:5468
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.15.0
PHP Version: 8.2.16
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: file-reupload-statamic.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.14.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
