### ISSUE TITLE
Assets Tag doesn't work

### ISSUE THREAD

**Issue by aerni** [statamic/cms#1044]
The `assets` tag doesn't work as expected. The `{{ url }}` outputs `/` instead of the correct path. This might be related to #1043 

**Assets container `main.yaml`:**
```yaml
title: Main
disk: assets
blueprint: asset
allow_uploads: true
allow_downloading: true
allow_renaming: true
allow_moving: true
create_folders: true
```

**Template:**
```html
{{ assets container="main" }}
  <img src="{{ url }}">
{{ /assets }}
```

**Output:**
```html
<img src="/">
```
