### ISSUE TITLE
The `on_each_side` pagination parameter doesn't behave as expected

### ISSUE THREAD

**Issue by aaronbushnell** [statamic/cms#10445]
### Bug description

The [Statamic docs](https://statamic.dev/tags/collection#parameters) for `on_each_side` says:

> When using pagination, this specifies the max number of links each side of the current page. The minimum value is 1.

However, it seems either the behavior is incorrect or the docs need reworded because the number of pages on each side seems quite larger under most circumstances.

### How to reproduce

Say I have 12 blog posts and my Antlers output is the following:

```antlers
{{ collection:blog paginate="1" on_each_side="1" as="posts" }}
  <div>
    {{ posts }}
      <h2>{{ title }}</h2>
    {{ /posts }}
  </div>

  <div>
    {{ paginate:auto_links }}
  </div>
{{ /collection:blog }}
```

I would expect the `auto_links` to look like this on page 5 because I'm only allowing 1 on each side.
![Screenshot 2024-07-12 at 10 36 00 AM](https://github.com/user-attachments/assets/c92888b5-f1fd-4f93-9f26-2156ce8b227b)

However, what it actually looks like is this:
![Screenshot 2024-07-12 at 10 36 38 AM](https://github.com/user-attachments/assets/190ae62b-52e6-43e7-937f-c77afce68730)

If I jump to page 6 it behaves a _bit_ closer to what I expect, but the additions of **2** and **11** seem odd:
![Screenshot 2024-07-12 at 10 37 53 AM](https://github.com/user-attachments/assets/22e06a2c-a6a5-4c6d-be1f-460e47045c0f)

### Environment

```yaml
Environment
Application Name: Statamic Starter
Laravel Version: 11.15.0
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: statamic-starter.test
Maintenance Mode: OFF
Timezone: America/Indiana/Indianapolis
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 9
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.14.0 PRO

Statamic Addons
mitydigital/statamic-scheduled-cache-invalidator: 2.0.5
rias/statamic-redirect: 3.7.1
statamic/seo-pro: 6.0.3
trendyminds/guide: dev-main
trendyminds/link: dev-main
trendyminds/nerf: 1.2.0
trendyminds/orbit-statamic: 1.2.0
trendyminds/statamic-palette: 1.2.1
trendyminds/tip: 1.0.0
```

### Installation

Other (please explain)

### Additional details

This is a templated GitHub project we use for our Statamic projects
