### ISSUE TITLE
Collection ordering via 'Orderable' setting not activating in cp

### ISSUE THREAD

**Issue by jjohnlaw** [statamic/cms#10466]
### Bug description

When i toggle 'Orderable' on in 'Edit Collection' settings nothing happens on the collection listing, no drag an drop interface. This is the same for all collections. 

After activating if i go back into the collection settings 'Orderable' is still active.

### How to reproduce

[mysite].test/cp -> Collections -> Edit Collection -> Orderable

Then click back to Collections, nothing is different

### Logs

```shell
No logs created for issue
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.15.0
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: jrl-statamic.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.13.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
