### ISSUE TITLE
Overwriting EntryPolicy does not correctly process the view() method

### ISSUE THREAD

**Issue by daerentis** [statamic/cms#10475]
### Bug description

When overwriting the EntryPolicy and defining a `view()` method that returns `false` the entry in the Control Panel is still visible.

I asked for a solution on Discord and was in contact with Erin. He mentioned that it could be an outstanding issue.
https://discord.com/channels/489818810157891584/1153390699161587823/1260541818416922725

### How to reproduce

Add a Policy inside the `boot()` method of the `AppServiceProvider`:

`Gate::policy(\Statamic\Eloquent\Entries\Entry::class, \App\Policies\EntryPolicy::class);`

Than create the custom `EntryPolicy` class with a `view()` method that returns `false`

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.16.0
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 2 (International, Canada)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.16.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.10.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```

### Installation

Fresh statamic/statamic site via CLI
