### ISSUE TITLE
Custom template on a taxonomy breaks the collection-taxonomy pages

### ISSUE THREAD

**Issue by steveparks** [statamic/cms#10478]
### Bug description

**Summary**
When custom templates are applied to a taxonomy via its configuration page, the taxonomy pages on the site work fine, but collection-taxonomy pages for any attached collections give a 404 page, even if their default templates are also left in place

**Details**
I've consolidated my various taxonomy templates into common templates at /views/taxonomy and set my taxonomies to use these templates.

Those work fine at the usual paths, eg example.com/tags/term.

But suddenly my collection taxonomy pages, eg example.com/blog/tags/term, have stopped working, giving a 404.

I previously had everything working with no custom template set on the taxonomy, so just using the default settings, and having templates in place at:
/views/blog/tags/index.antlers.html   & show.antlers.html
/views/tags/index.antlers.html  &  show.antlers.html

Now I have added:
/views/taxonomy/index.antlers.html   &  term.antlers.html
and set these as the templates through the UI for the taxonomy.

I left the templates on the default paths in place.

We discussed this issue in this Discord thread: https://discord.com/channels/489818810157891584/1263476458035216476
@andjsch was able to reproduce.

Here are the relevant yaml files:

``` yaml
# /content/collections/blog.yaml

title: Blog
template: blog/show
layout: layout
mount: d11a5ec8-9915-4528-8cfe-e282362ef9ee
taxonomies:
  - series
  - tags
revisions: false
route: '/{mount}/{slug}'
date: true
sort_dir: desc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: false
```

``` yaml
# /content/taxonomies/tags.yaml

title: 'Tags'
preview_targets:
  -
    label: Tag
    url: '{permalink}'
    refresh: true
template: taxonomy/index
term_template: taxonomy/term
layout: layout
```

### How to reproduce

1. Set up a simple blog collection at path /blog
2. Set up a taxonomy 'tags' and attach to the blog collection
3. Add some terms to the taxonomy
4. Set up usual default templates and verify they work at example.com/tags and example.com/blog/tags
5. Now set up custom templates at /views/taxonomy/
6. Edit the taxonomy configuration to use these custom templates
7. Verify that they work at example.com/tags
8. Verify that example.com/blog/tags gives a 404

### Environment

```yaml
Environment
Application Name: Convivio
Laravel Version: 11.16.0
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: convivio.test
Maintenance Mode: OFF
Timezone: Europe/London
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.4

Statamic
Addons: 10
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.16.0 PRO

Statamic Addons
goldnead/statamic-toc: 1.5
jonassiewertsen/statamic-livewire: 3.6.0
statamic/wikilinks: 2.1.0
stillat/relationships: 2.2.1
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.4.0
studio1902/statamic-peak-seo: 8.15.3
studio1902/statamic-peak-tools: 6.3.0
tv2regionerne/statamic-passport: 1.4.1
tv2regionerne/statamic-private-api: 1.15.0
```

### Installation

Existing Laravel app

### Additional details

Installed into existing Laravel app, and then added the Peak Starter Kit
