### ISSUE TITLE
Select dropdown entries showing below field when max_items is 1

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#10474]
### Bug description

Select dropdowns are showing the entries below the field even when max_items are set to 1. 

<img width="803" alt="Screenshot 2024-07-18 at 3 27 19 PM" src="https://github.com/user-attachments/assets/c6f137e0-0952-4ea9-825d-1ff14a985ee3">

### How to reproduce

Add Select Dropdown fields to blueprint:
```
        fields:
          -
            handle: select_dropdown_entries
            field:
              mode: select
              type: entries
              display: 'Select Dropdown Entries'
          -
            handle: select_dropdown_entry
            field:
              max_items: 1
              mode: select
              type: entries
              display: 'Select Dropdown Entry (Max 1)'
```

### Environment

```yaml
Environment
Application Name: Orb
Laravel Version: 11.16.0
PHP Version: 8.2.19
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: orb.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: database
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Livewire
Livewire: v3.5.4

Spatie Permissions
Features Enabled: Default
Version: 6.9.0

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.16.0 PRO

Statamic Addons
addonfoundry/flexible-forms: 1.1.4
doefom/currency-fieldtype: 1.4.0
marcorieser/tailwind-merge-statamic: 1.1.0
statamic-rad-pack/runway: 7.6.0
stillat/antlers-components: 2.2.0
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by mikemartin** [comment]
Hey @jasonvarga 
This is still showing for me on 5.0.17.

<img width="1440" alt="Screenshot 2024-07-23 at 9 19 08 PM" src="https://github.com/user-attachments/assets/ecc4087c-536a-4061-b63a-c2306215a4e5">

Fieldset:
```
-
            handle: entries_field
            field:
              max_items: 1
              collections:
                - articles
              type: entries
              display: 'Entries Field'
              mode: select
```

Here are my support details:
```
Environment
Application Name: Orb
Laravel Version: 11.16.0
PHP Version: 8.2.19
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: orb.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: database
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Livewire
Livewire: v3.5.4

Spatie Permissions
Features Enabled: Default
Version: 6.9.0

Statamic
Addons: 6
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.17.0 PRO

Statamic Addons
addonfoundry/flexible-forms: 1.1.5
doefom/currency-fieldtype: 1.4.0
marcorieser/tailwind-merge-statamic: 1.1.0
mitydigital/statamic-stripe-checkout-fieldtype: 2.0.0
statamic-rad-pack/runway: 7.6.0
stillat/antlers-components: 2.2.0
```
