### ISSUE TITLE
Wrong image path with glide

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#10493]
### Bug description

This tag generates the image:
`{{ glide src="{{ url }}" width='3000' height='1400' fit='crop_focal' quality='70' format="webp" }}`

When the image has the same width, like the original image, glide generates this path, but there is no image. Is shows error 404.
`/img/cache/containers/bilder/landschaft/wm_20180402-1715-_dsc9141_bombachsee-und-wald-bearbeitet_max_3000px.jpg/2b5ba43607f5110b38173a5a34376e9c/wm_20180402-1715-_dsc9141_bombachsee-und-wald-bearbeitet_max_3000px.webp`

When the width is different, the generated path is right and working.
`/img/cache/containers/bilder/landschaft/wm_20180402-1715-_dsc9141_bombachsee-und-wald-bearbeitet_max_3000px.jpg/9785af8fe2fad228b0d060a54e246c58/wm_20180402-1715-_dsc9141_bombachsee-und-wald-bearbeitet_max_3000px.webp`

### How to reproduce

Generate an image with glide with the same width like the original image.

### Environment

```yaml
Environment
Laravel Version: 10.48.16
PHP Version: 8.3.7
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.4

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.17.0 PRO

Statamic Addons
ddm-studio/cookie-byte: 1.5.2
jonassiewertsen/statamic-livewire: 3.6.0
mitydigital/statamic-google-fonts: 2.0.0
mitydigital/statamic-sticky-notes: 1.0.1
nineteensquared/instagram: 1.2.0
```

### Installation

Fresh statamic/statamic site via CLI
