### ISSUE TITLE
Ambiguous validation error when using image dimensions rule

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/cms#10500]
### Bug description

I created an asset field that accepts multiple images.  Then added a dimensions rule to the field.  When I upload an invalid image rather than highlighting which image is invalid it just says "Invalid image dimensions".

### How to reproduce

1. Create an asset field
2. Add a dimensions validation rule to the asset field
3. Upload multiple images to the field
4. See the ambiguous validation error

### Environment

```yaml
Environment
Application Name: Website
Laravel Version: 11.16.0
PHP Version: 8.3.9
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: website.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.4

Statamic
Addons: 18
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.17.0 PRO

Statamic Addons
aerni/livewire-forms: 9.3.0
aerni/social-links: 3.2.0
aryehraber/statamic-logbook: 3.3.0
edalzell/forma: 3.0.1
godismyjudge95/statamic-embera: 1.1.1
jonassiewertsen/statamic-livewire: 3.6.0
kolaente/statamic-snippet: 1.1.2
mitydigital/statamic-google-fonts: 2.0.0
patrickjunod/image-select: 0.2.1
plugrbase/statamic-maintenance-mode: 1.07
statamic-rad-pack/mailchimp: 5.0.1
statamic-rad-pack/meilisearch: 3.3.0
statamic/seo-pro: 6.0.3
stillat/antlers-components: 2.2.0
stillat/relationships: 2.2.1
thoughtco/statamic-restrict-fields: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

I think there could be two solutions here:
- Highlight the image with invalid dimensions
- Add the file name to the validation message

Could implement both eventually, but the 2nd one is probably the simplest.
