### ISSUE TITLE
nav tag ignores select

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/cms#10503]
### Bug description

`select`ing fields for the `nav` tag appears to be ignored and all fields are selected regardless

### How to reproduce

```
{{ nav:main select="title" }}
{{ url }}
{{ /nav:main }}
```

This still outputs the `url`s for each entry in the main nav, it shouldn't as they haven't been selected

### Environment

```yaml
Environment
Laravel Version: 11.10.0
PHP Version: 8.3.8
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.17.0 PRO

Statamic Addons
edalzell/forma: 3.0.1
statamic-rad-pack/mailchimp: 5.0.1
```

### Installation

Fresh statamic/statamic site via CLI
