### ISSUE TITLE
"This URI has already been taken." when saving a new entry again if you use the "Continue Editing" after save option

### ISSUE THREAD

**Issue by bland-industries** [statamic/cms#10504]
### Bug description

When trying to save again, a new entry with a route and slug, you get an error of "This URI has already been taken." if you use the "Continue Editing" after save option. It seems that after you save, the browser is not redirected to the newly saved entry so it thinks the user is trying to save a second new entry.

### How to reproduce

1. Create a collection with a route: `this-is-a-test/{slug}`
2. Create an Entry
3. Set "After Saving" radio option to "Continue Editing"
4. Type in a title like "This is a test. Please ignore this." and hit tab to make sure slug field is set
5. Click "Save & Publish"
6. After entry is saved click "Save & Publish" again.
7. Error "This URI has already been taken." will appear by the slug field
8. url is still "/collections/tests/entries/create/default"

### Logs

```shell
N/A
```

### Environment

```yaml
Environment
Application Name: 
Laravel Version: 10.48.12
PHP Version: 8.1.27
Composer Version: 2.6.6
Environment: local
Debug Mode: ENABLED
URL: 
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: errorlog
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 15
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.7.2 PRO

Statamic Addons
alt-design/alt-redirect: 1.3.2
aryehraber/statamic-logbook: 3.3.0
doefom/statamic-export: 0.4.0
jacksleight/statamic-bard-texstyle: 3.2.2
kadegray/statamic-country-and-region-fieldtypes: 1.2.4
rias/statamic-color-swatches: 2.3.0
simonridley/tracking-code-manager: 1.0.2
statamic/collaboration: 1.0.0
statamic/eloquent-driver: 4.2.0
stillat/relationships: 2.2.0
webographen/statamic-admin-log: 1.1.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
