### ISSUE TITLE
Unauthorized deletion of entries in multi-site setup

### ISSUE THREAD

**Issue by lakkes-ra** [statamic/cms#10519]
### Bug description

A client wants to have a multi-tenant website for his main website and two subdomains that will be exactly the same site but with different look and content. While making a proof of concept, we encountered a supposed bug. 

We're able to delete an entry from "Site B" with a user that only has access to "Site A". That happens because the user was deleting the source entry. (Detailed steps in _How to reproduce_)

We may overlook some setting here that disables that, but couldn't find one yet. 

## Setting up the sites and user
- Create a multi-site with "Site A" and "Site B"
- Create three users:
  - One with permission to access both pages 
  - One with permission to access only "Site A"
  - One with permission to access only "Site B"
- All user must have permission to edit the pages (or any other) collection.

## Handling the entry
- Create a page with the user that can access all pages. 
- Localize the page so that the source entry is from "Site A" and we have that page in "Site A" and "Site B".
- Login with user that can only access "Site A"
- Go to pages collection. The page entry we just created is shown in list view. Click on three dots from this entry and click delete. 
- The entry from "Site B" was also deleted by the "Site A" user even without having permission to access or delete anything from that "Site B", since the source entry was deleted. 

## Notes
When I click on delete in the collection list view, it's only possible to delete straight away. When deleting the entry while at the entry edit page, I can choose between delete and detach, but still shouldnt be able to delete.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.17.0
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: tenant-one.localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 2 (Tenant One, Tenant Two)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.17.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
