### ISSUE TITLE
BulkAugmentor fails to handle iterables that have non-sequential or non-numeric keys

### ISSUE THREAD

**Issue by simonworkhouse** [statamic/cms#10510]
### Bug description

Seeing `Undefined array key ...` errors when the `BulkAugmentor` attempts to augment any iterable that does not have sequential numeric keys.

### How to reproduce

Create a new tag like the following and attempt to use it in a template using `{{ test_bulk_augmentor }}`. This assumes that you have multiple entries.

```php
<?php

namespace App\Tags;

use Statamic\Tags\Tags;

class TestBulkAugmentor extends Tags
{
    /**
     * The {{ test_bulk_augmentor }} tag.
     *
     * @return string|array
     */
    public function index()
    {
        return \Statamic\Facades\Entry::query()->get()->reject(fn($entry, $key) => $key % 2 == 0);
    }
}
```

### Environment

```yaml
Environment
Application Name: Testing Things
Laravel Version: 10.48.17
PHP Version: 8.2.18
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: testing-things.localhost
Maintenance Mode: OFF
```

### Installation

Fresh statamic/statamic site via CLI
