### ISSUE TITLE
Error accessing assets in CP after 5.14.0

### ISSUE THREAD

**Issue by joshuablum** [statamic/cms#10520]
### Bug description

We received two support tickets about this error. Looks like this PR https://github.com/statamic/cms/pull/10392 released with v5.14.0 introduced a bug when trying to access the assets overview in the Control Panel resulting in a `Call to undefined method Closure::first()` error.

```php
$firstContainerInNav = Nav::build()->pluck('items')->flatten()
    ->filter(fn (NavItem $navItem) => $navItem->url() === cp_route('assets.index'))
    ->map(fn (NavItem $navItem) => $navItem->children()?->first())
    ->first();
```
returns a closure which it tries to call `->first()` on resulting in the error.

### How to reproduce

Update to `>=5.14.0` and access the assets page. Seems to behave differently between local and staging environments and might also be related to having more than one asset container.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.18.1
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: sandbox.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 2 (Statamic, German)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.17.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
