### ISSUE TITLE
Live preview refreshing but not affected by template field change

### ISSUE THREAD

**Issue by mehdismekouar** [statamic/cms#10527]
### Bug description

When adding **Template field** in a collection blueprint, the live preview in any entry of that collection doesn't get affected by the **Template field** change

### How to reproduce

Create a collection Articles for example
In the default blueprint or any blueprint of that collection, make sure to have the Template field
Add an entry in that collection
Start populating the fields and make sure to have at least two different antlers templates in /resources/views/
Click on Live preview
Change the template field value
You'll see a page refresh but the template is the same as before

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.16.0
PHP Version: 8.2.12
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.17.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
