### ISSUE TITLE
Height of the spacer fieldtype is too large on small screens

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#10528]
### Bug description

The spacer field type leads to incorrect vertical spacing between fieldtypes on small screens.

- Viewports below 408px are fine
- Between 408px to 535px there is way too much spacing
- Between 536x to 646px there is a little too much spacing
- Form 647px everything is fine again

<img width="922" alt="Bildschirmfoto 2024-07-30 um 10 14 45" src="https://github.com/user-attachments/assets/fc412c3d-6830-4010-916e-77d820082504">

<img width="967" alt="Bildschirmfoto 2024-07-30 um 10 16 01" src="https://github.com/user-attachments/assets/d74bb3a5-978e-47e8-bb9f-d3887a2732c0">

### How to reproduce

Create a blueprint with a spacer fieldtype between some narrow fields, so that the second textfield moves to a new line. For example:
- 33% textfield
- 33% spacer
- 66% textfield

### Environment

```yaml
Environment
Application Name: Kochort CMS
Laravel Version: 11.18.1
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: /
Maintenance Mode: OFF
Timezone: Europe/Zurich
Locale: de_CH

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.17.1 PRO

Statamic Addons
mitydigital/statamic-sticky-notes: 1.0.1
statamic/seo-pro: 6.0.3
stillat/relationships: 2.2.1
swiftmade/statamic-clear-assets: 3.0.0
```

### Installation

Fresh statamic/statamic site via CLI
