### ISSUE TITLE
Dropdown Overflows Page - Configure Global Setting's Sites

### ISSUE THREAD

**Issue by DanielDarrenJones** [statamic/cms#10522]
### Bug description

When you have a long dropdown it can currently overflow the end of the page, and isn't scrollable.

![Screenshot 2024-07-29 at 15 52 46](https://github.com/user-attachments/assets/ed93aa9f-8d98-41c3-9a37-195473237e81)

In the above screenshot there are two additional options Foundation GB and Foundation US which aren't accessible, this is on the configure globals screen.

### How to reproduce

In this specific instance have multiple sites, we have 10, and then on the bottom dropdown of the globals configure sites settings it will overflow the page.

### Environment

```yaml
Environment
Application Name: Pelorus
Laravel Version: 10.48.16
PHP Version: 8.2.21
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: pelorus-travel.test/
Maintenance Mode: OFF
Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED
Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file
Statamic
Addons: 9
Sites: 10 (Travel (GB), Travel (US), Aviation (GB), and 7 more)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.16.0 PRO
Statamic Addons
aryehraber/statamic-captcha: 1.12.0
doefom/currency-fieldtype: 1.4.0
gerttimmerman/statamic-zapier: 1.6
jacksleight/statamic-bard-texstyle: 3.2.2
ndx/statamic-bard-color-picker: 2.0.0
ryanmitchell/statamic-translation-manager: 2.0.0
statamic/eloquent-driver: 4.10.0
thoughtco/statamic-cache-tracker: 0.5.1
withcandour/aardvark-seo: 5.0.0
Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
