### ISSUE TITLE
Laravel Telescope errors when creating user via the `make:user` command

### ISSUE THREAD

**Issue by rrelmy** [statamic/cms#10525]
### Bug description

When accessing `User::editUrl` directly or through other methods like `User::toArray` before the model has been persisted results in a `UrlGenerationException`. This is expected as the urls required the ID.
This breaks the creation of users.

We initially discovered this issue by installing [Laravel Telescope](https://laravel.com/docs/11.x/telescope) which records all events by default and tries to serialise the model in the UserCreating event.

_Not sure if this is something you want to fix, I mainly want to document it for other users any my future self._ 😅 

### Workaround when using telescope
Add the events to the ignore list in `config/telescope.php`

```php
        Watchers\EventWatcher::class => [
            'enabled' => env('TELESCOPE_EVENT_WATCHER', true),
            'ignore' => [
                \Statamic\Events\UserCreating::class,
                \Statamic\Events\UserSaving::class,
            ],
        ],
```

### How to reproduce

1. Add a listener to the UserCreating event
``` php
        Event::listen(UserCreating::class, function (UserCreating $event) {
            dump($event->user->toArray());
        });
```
2. Create a user with `php please make:user`

---

Alternatively you can install Laravel Telescope and enable it

### Logs

```shell
Illuminate\Routing\Exceptions\UrlGenerationException 

  Missing required parameter for [Route: statamic.cp.users.edit] [URI: cp/users/{user}/edit] [Missing parameter: user].

  at vendor/laravel/framework/src/Illuminate/Routing/Exceptions/UrlGenerationException.php:35
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.17.0
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: localhost

Statamic
Addons: 3
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.17.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
