### ISSUE TITLE
Email validation rule not working

### ISSUE THREAD

**Issue by mehdismekouar** [statamic/cms#10558]
### Bug description

I can type an email like this **mehdi@mekouar** without a .tld and get it passed the email validation rule in a form

### How to reproduce

- create a form in the admin panel
- add a text field with **email** as input type
- in the validation tab toggle **required** and add **email** in Rules field
- save and add that field in any form of your choice
- in the form page, type an email like **name@domain** without adding any .com or .net or any td
- submit the form
- your form will be saved and you'll find your email **name@domain** saved which is incorrect

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.16.0
PHP Version: 8.2.12
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.19.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
