### ISSUE TITLE
"Forgot Your Password?" page shows default page title

### ISSUE THREAD

**Issue by tommulroy** [statamic/cms#10554]
### Bug description

The forgot your password page shows the default "Here" page title.

![image](https://github.com/user-attachments/assets/f39a1dac-101d-441c-a2dc-fda4b6cf7d8b)

### How to reproduce

Do a fresh install 

`composer create-project --prefer-dist statamic/statamic cyberspace-place`

Visit `/cp/auth/password/reset`

Alternatively, visit `/cp/auth/password/reset` on any of your current websites. 

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.19.0
PHP Version: 8.2.21
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.19.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
