### ISSUE TITLE
when running local and pro version the licenses banner is getting the way

### ISSUE THREAD

**Issue by rabol** [statamic/cms#10564]
### Bug description

whne you run in local mode, the banner telling you that you need a liceses - which you actually do not need in local mode - is preventing you from selecting the bottom menu item
<img width="1228" alt="Screenshot 2024-08-03 at 21 14 49" src="https://github.com/user-attachments/assets/568654db-03ea-40a2-a842-4a270f52176d">

### How to reproduce

turn on pro edition and run locally

### Environment

```yaml
Environment
Application Name: Sportax
Laravel Version: 11.19.0
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: sportax.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 2 (Español, English)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.19.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
