### ISSUE TITLE
Array fieldtype labels are required despite being shown as optional

### ISSUE THREAD

**Issue by petemolinero** [statamic/cms#10573]
### Bug description

If I create an `Array` field type, choose "Keyed" UI mode, and omit labels, the settings cannot be saved. If I then fill out the labels, I can save it.

![Screenshot 2024-08-05 at 4 14 40 PM](https://github.com/user-attachments/assets/f3e2fa5f-b2a1-4086-a91d-1cb371f6cad7)

### How to reproduce

1. Create an array fieldtype in your blueprint
2. Choose the `Keyed` UI mode
3. Enter keys but not labels
4. Observe the error

### Environment

```yaml
Environment
Application Name: --------
Laravel Version: 11.16.0
PHP Version: 8.2.21
Composer Version: 2.6.5
Environment: development
Debug Mode: ENABLED
URL: --------
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.19.0 PRO

Statamic Addons
jonassiewertsen/statamic-documentation: 2.0.0
statamic/eloquent-driver: 4.9.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Taxonomies: file
Terms: eloquent
Tokens: file
```

### Installation

Existing Laravel app
