### ISSUE TITLE
Form field handle with uppercase character

### ISSUE THREAD

**Issue by mscruse** [statamic/cms#10572]
### Bug description

When creating a form field and it's slug contains an uppercase character it fails validation and will not save.

We have several clients for whom we have built Statamic forms that post to Salesforce and have a real need for field slugs to have uppercase characters.

We can manually edit this via the blueprint yaml file, but cannot create and edit via the CP.

### How to reproduce

Add a field to a form blueprint via the CP and have an uppercase character in the slug.

### Environment

```yaml
Environment
Application Name: 
Laravel Version: 11.19.0
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: 
Maintenance Mode: OFF
Timezone: Australia/Melbourne
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 9
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.19.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.12.1
jacksleight/statamic-bard-ipsum: 1.0.1
mitydigital/feedamic: 2.4.1
mitydigital/iconamic: 2.1.1
mitydigital/sitemapamic: 3.1.0
mitydigital/statamic-google-fonts: 2.0.0
mitydigital/statamic-two-factor: 2.2.1
mitydigital/statamic-variable-number-fieldtype: 2.0.0
mitydigital/supportamic: 1.1.1
```

### Installation

Fresh statamic/statamic site via CLI
