### ISSUE TITLE
Ternary statement in partial evaluates as true for null values

### ISSUE THREAD

**Issue by o1y** [statamic/cms#10589]
### Bug description

When using a ternary statement within a partial to check if a value is set, the ternary expression is evaluated as true even if the value is null.

### How to reproduce

1. Add a select field `select_field` with some random options.
2. Create an entry, but don't select a value from `select_field`
3. Create a partial `container.antlers.html` with the following content

```antlers
{{ select_field ? 'true' : 'false' }}
```

4. In your template add the partial like so:
```antlers
{{ partial:container :select_field="select_field" }}
```

This returns 'true' 🤯

When dumping `select_field` in the partial you'll see that this seems not correct:
```antlers
{{ select_field | dump }}
```

```
Statamic\Fields\LabeledValue {#3116 ▼ // vendor/statamic/cms/src/Modifiers/CoreModifiers.php:613
  #value: null
  #extra: array:1 [▶]
}
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.20.0
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: ternary.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.19.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
