### ISSUE TITLE
Query Filter with `terms` fieldtype causing CP UI problems

### ISSUE THREAD

**Issue by eiiot** [statamic/cms#10581]
### Bug description

When you create a query filter that uses a `terms` field to allow the user to select certain taxonomy terms, there are a bunch of UI issues best described by the video below:

https://github.com/user-attachments/assets/b71cf9a8-e9ab-4653-808e-800c959cdb2a

Notably:

- the term doesn't display correctly when selected
- after I disable the filter by clicking the x on the badge, the term is still selected until I reload the page

### How to reproduce

1. Create a taxonomy `issues` and link it to a collection. Add a field in the collection.

Taxnomy:
```yaml
title: Issues
preview_targets:
  -
    label: Term
    url: '{permalink}'
    refresh: true
layout: layout
```
Blueprint:
```yaml
title: Issue
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
              display: Date
              input_type: date
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              required: true
              validate:
                - required
                - 'max:200'
```

2. Create a query filter that uses the `terms` UI like below:

```php
<?php

namespace App\Scopes;

use Statamic\Query\Scopes\Filter;

class IssueFilter extends Filter
{
    /**
     * Pin the filter.
     *
     * @var bool
     */
    public $pinned = true;

    /**
     * Define the filter's title.
     *
     * @return string
     */
    public static function title()
    {
        return __('Issue');
    }

    /**
     * Define the filter's field items.
     *
     * @return array
     */
    public function fieldItems()
    {
        return [
            'assigned' => [
                'type' => 'terms',
                'mode' => 'select',
                'taxonomies' => ['issues'],
            ],
        ];
    }

    /**
     * Apply the filter.
     *
     * @param  \Statamic\Query\Builder  $query
     * @param  array  $values
     * @return void
     */
    public function apply($query, $values)
    {
        $query->whereIn('issues', $values['assigned']);
    }

    /**
     * Define the applied filter's badge text.
     *
     * @param  array  $values
     * @return string
     */
    public function badge($values)
    {
        return count($values['assigned']) > 1 ? __(count($values['assigned']).' Issues') : __('1 Issue');
    }

    /**
     * Determine when the filter is shown.
     *
     * @param  string  $key
     * @return bool
     */
    public function visibleTo($key)
    {
        // your logic here
    }
}
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.7.0
PHP Version: 8.3.6
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: crimson.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.19.0 PRO

Statamic Addons
statamic/collaboration: 1.0.0
statamic/eloquent-driver: 4.12.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
