### ISSUE TITLE
Entries list view and edit view loading all Taxonomy terms

### ISSUE THREAD

**Issue by danielwashbrook** [statamic/cms#10599]
### Bug description

After importing a large set of content that includes 19k Taxonomy Terms, the Entries list view and edit view becomes very slow as it loads all the terms as "Statamic\Eloquent\Taxonomies\TermModel" for the filters in the list view and the typeahead field selector on the edit view.
![image](https://github.com/user-attachments/assets/37b7e27b-9920-49bb-bb1d-0d6f5d0785bf)
I currently see the following options to solve this:

- Find a way to configure the list view filters in statamic - I didn't manage to find one yet
- Look through statamic frontend or backend code to find a good spot to override one of the default implementations with an improved one

Thanks!

### How to reproduce

Create a collection with a taxonomy term reference. Generate a large body of Terms for that taxonomy and create a few Entries of that collection type. Navigate to the list view of the Collection and subsequently the edit view of one of the entries. 

### Environment

```yaml
Environment
Application Name: Emmys
Laravel Version: 10.48.14
PHP Version: 8.2.19
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.10.0 PRO

Statamic Addons
rias/statamic-redirect: 3.7.1
statamic/eloquent-driver: 4.5.0
statamic/seo-pro: 6.0.3
stefangalescu/statamic-heroicons: 3.0
thoughtco/statamic-blurhash: 1.2.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: file
Revisions: eloquent
Taxonomies: file
Terms: eloquent
Tokens: eloquent
```

### Installation

Fresh statamic/statamic site via CLI
