### ISSUE TITLE
No smart quotes when `smartypants` is `true` in content

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1059]
I have a fieldset with a markdown content field:
```
        handle: content
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: true
          escape_markup: true
          smartypants: true
          type: markdown
          localizable: false
          display: Content
```

When I have content with quotes: 
<img width="190" alt="image" src="https://user-images.githubusercontent.com/6069653/70113375-c55fd780-160d-11ea-906e-e716e2ba281c.png">

No curly quotes are shown: 
<img width="215" alt="image" src="https://user-images.githubusercontent.com/6069653/70113396-dd375b80-160d-11ea-8dd3-39b87ef567f3.png">

Use the `markdown` modifier on the `content` field does not help.
