### ISSUE TITLE
Blueprint/Entry/CP Bugs

### ISSUE THREAD

**Issue by Victor-Miguel1405** [statamic/cms#10598]
### Bug description

Hi guys! I'm having some issues with the CP can someone help me?
First error is happening on the blueprints. When I try to create new fields and edit the blueprint, i get some errors:
1. Infinite loading when adding or editing a field.
2. Error when tryng to save created or edited field;
3 Created fields just not appear.
Infinite loading:
![image_error](https://github.com/user-attachments/assets/92c0c0f8-6d9f-4680-9460-b0794dd6cbb7)
Error in the console:
![image_error2](https://github.com/user-attachments/assets/d5530298-5ea5-436a-b4a7-0245cf7c3708)

So I just close and open again multiple times, and click to save multiple times until it finally works.

Also I'm getting a lot of errors related to saving the field. When creating an Entry for example, I get the error "Couldn't save entry", but it ends up saving it, and when I try to save it again it says that it already exists.

![image_error3](https://github.com/user-attachments/assets/8103c4b9-7e12-4017-a2fd-6e6a7ec0ee07)

Then, I decided to take a peak  in the console and this was the JSON being sent in the request:
 
![image_error4](https://github.com/user-attachments/assets/13645a0b-d43a-4af3-a6f7-7fbc432a40b9)

Is this JSON correct? It looks weird.

Some more console errors:

![image](https://github.com/user-attachments/assets/7f7b4ca3-699c-49d4-a315-ba53631646ce)

Tried to delete and got this:

![image](https://github.com/user-attachments/assets/2c927ffb-1fa4-4349-8063-e437d32a7a40)

Tried again: 

![image](https://github.com/user-attachments/assets/69fd5ff6-868b-44c6-b6ba-001acd790a7e)

It was deleted on the first try, althought presented error.

Also having a little bug when selecting entries to delete. The bar with options just looks like this:

![image_error5](https://github.com/user-attachments/assets/51a67c9a-20b9-4f01-978a-94ec332c093a)

Just some extra details:

-It's happening in more than one browser. Tested it on Edge and Chrome.
- I'm currently using the newest version of Statamic  and plugins;

### How to reproduce

I don't know if everyone is getting these errors, but to reproduce it just act normally, create blueprints, entrys, taxonomies, edit fields in blueprints, try to save entries and blueprints.

### Logs

```shell
Magically, there's nothing in laravel logs. I caught some errors on the console of DevTools related to JS properties as you can see in the description. Reproduced all error with the laravel logs opened and nothing.
```

### Environment

```yaml
Environment
Application Name: houseTI
Laravel Version: 11.17.0
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: production
Debug Mode: ENABLED
URL: www.houseti.com.br
Maintenance Mode: OFF
Timezone: America/Sao_Paulo
Locale: pt_BR

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: database
Session: database

Statamic
Addons: 10
Sites: 1
Stache Watcher: Enabled
Static Caching: half
Version: 5.19.0 Solo

Statamic Addons
aerni/font-awesome: 3.0.1
aryehraber/statamic-captcha: 1.12.1
dryven/faviconator: 1.3.1
eminos/statamic-iconify: 1.3.0
eminos/statamic-tabs: 1.2.0
ndx/statamic-bard-color-picker: 2.0.0
o1y/statamic-flexible-width: 1.0.1
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-seo: 8.15.3
studio1902/statamic-peak-tools: 3.4.3
```

### Installation

Fresh statamic/statamic site via CLI
