### ISSUE TITLE
Slow loading time when loading assets in control panel as a not super user

### ISSUE THREAD

**Issue by motion-work** [statamic/cms#10601]
### Bug description

I am experiencing a performance issue when loading assets in the Control Panel. In my case it takes a very long time (about 10 seconds) to load all the assets in the asset container. 

Strangely, this slow loading time only occurs as a user with no admin role. **As a Super Admin the loading time is fast as it should be.** 

So my guess is that statamic is doing some permisson checks in the background when loading the assets? or some caching related issue.

As a site note, all assets are stored in an S3 bucket. 

Do you have any idea how to solve this problem? 

Statamic v4.36.0

https://github.com/user-attachments/assets/fbc5f69e-e818-4b74-adcb-d3a6eb96195c

### How to reproduce

- Use Statamic v4.36.0
- Have a S3 bucket with lots of files
- with a user without super admin role navigate to the Assets in the control panel.

### Environment

```yaml
Environment
Application Name: Seilbahnen Schweiz
Laravel Version: 9.52.16
PHP Version: 8.2.13
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: seilbahnen-cms.novu.io
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / daily, sentry
Mail: smtp
Queue: sync
Session: redis

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 3.8.2
PHP SDK Version: 3.22.1
Release: 2619600c0
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 100%
Sample Rate Profiling: NOT SET
Send Default PII: ENABLED

Statamic
Addons: 2
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.36.0.1 PRO

Statamic Addons
doublethreedigital/duplicator: 4.0.1
teamnovu/graphql-breadcrumbs: 1.0.1
```

### Installation

Fresh statamic/statamic site via CLI
