### ISSUE TITLE
UniqueEntryValue triggers "Array to string conversion"

### ISSUE THREAD

**Issue by ajnsn** [statamic/cms#10614]
### Bug description

Create an entries relationship field and set max items to 1, apply the UniqueEntryValue rule. Even if there's only one entry related, the value passed to the rule will be an array. This results into a `Array to string conversion` exception wihtin the EntryQueryBuilder, triggerd [here](https://github.com/statamic/cms/blob/bd3f907ca817e3b0c969b4d04bac928b22fc396f/src/Rules/UniqueEntryValue.php#L32).

A simple solution would to support array values within the rule, e.g.
```php
$existing = $query
    ->when(
        is_array($value),
        fn ($query) => $query->whereIn($attribute, $value),
        fn ($query) => $query->where($attribute, $value)
    )
    ->first();
```

Might apply also to the other Unqiue-rules?
Any thoughs on this?

Thank you!

### How to reproduce

See above

### Environment

```yaml
Environment
Application Name: www
Laravel Version: 11.20.0
PHP Version: 8.2.22
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: log
Queue: redis
Session: file

Livewire
Livewire: v3.5.4

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.7.1
PHP SDK Version: 4.9.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 0%
Sample Rate Profiling: 0%
Send Default PII: DISABLED

Statamic
Addons: 0
Sites: 6 (German, English, Spanish and 3 more)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.20.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
