### ISSUE TITLE
Collection Reordering - Not saving correctly and results changing between screens 

### ISSUE THREAD

**Issue by DanielDarrenJones** [statamic/cms#10619]
### Bug description

When re-ordering collections they don't seem to be saving properly and also seem to change between go in and out of the editing screen. Please see the below loom showing the issue:

https://www.loom.com/share/c2296295ac00468cb8df0dacdace3665

### How to reproduce

This happens simply when trying to re-order collections through the UI.

### Environment

```yaml
Environment
Application Name: Pelorus
Laravel Version: 10.48.20
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: pelorus-travel.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: log
Queue: redis
Session: redis

Statamic
Addons: 9
Sites: 10 (Travel (GB), Travel (US), Aviation (GB), and 7 more)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.20.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.12.1
doefom/currency-fieldtype: 1.4.0
gerttimmerman/statamic-zapier: 1.6
jacksleight/statamic-bard-texstyle: 3.2.3
ndx/statamic-bard-color-picker: 2.0.0
ryanmitchell/statamic-translation-manager: 2.0.0
statamic/eloquent-driver: 4.12.3
thoughtco/statamic-cache-tracker: 0.5.1
withcandour/aardvark-seo: 5.0.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
