### ISSUE TITLE
Computed fields look sortable in the blueprint

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#10610]
### Bug description

You can't sort on computed fields, but in the blueprint builder you see this:
<img width="797" alt="image" src="https://github.com/user-attachments/assets/772451ed-2e33-4ff5-8569-04e0e2e1ac60">

That shouldn't show up when you choose `computed`

### How to reproduce

1. create a computed field
2. look at the screen

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.20.0
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: transform.share.silentz.dev
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: sqlite
Logs: stack / daily
Mail: log
Queue: sync
Session: file

Livewire
Livewire: v3.5.4

Statamic
Addons: 13
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.20.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.12.1
edalzell/forma: 3.0.1
jacksleight/statamic-bard-mutator: 2.3.1
jacksleight/statamic-distill: 0.8.0
jonassiewertsen/statamic-livewire: 3.6.0
statamic-rad-pack/runway: dev-feature/resource-actions
statamic/seo-pro: 6.0.3
transformstudios/events: 5.4.3
transformstudios/front: 3.0.1
transformstudios/github: dev-main
transformstudios/review: 5.0
transformstudios/simple: 5.1.14
transformstudios/uptime: dev-feature/billing
```

### Installation

Fresh statamic/statamic site via CLI
