### ISSUE TITLE
Type NavPage_* must define one or more fields error in GraphiQL

### ISSUE THREAD

**Issue by 321zeno** [statamic/cms#10621]
### Bug description

I created a new Statamic project, enabled pro and GraphQL locally and created a super user for the CP.

I created a new Navigation called "Test"

When I open GraphiQL if fails to fetch the schema with the message 

```
Type NavPage_Test must define one or more fields.,
```

### How to reproduce

- `composer create-project --prefer-dist statamic/statamic statamic-nav`
- `php please make:user`
- Enable GraphQL in .env
- enable `resources.navs` in `statamic-nav/config/statamic/graphql.php`
- `php artisan serve`
- Create a new navigation called "Test"
- (optional) Create a new item in the nav
- Visit http://localhost:8000/cp/graphiql and refetch schema

The error message `Type NavPage_Test must define one or more fields.",` shows up
Also the `nav()` query is not visible in the Explorer (only `ping`)

### Logs

```shell
Nothing in the logs
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.20.0
PHP Version: 8.3.6
Composer Version: 2.2.6
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.20.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
