### ISSUE TITLE
E-Mail-Templates: Field value for asset field contains references to all images in Volume and crashes SendMail jobs

### ISSUE THREAD

**Issue by mnlmaier** [statamic/cms#10631]
### Bug description

Hi guys, here's another bug which took me literal days and an accidental variable dumping to figure out. On a production site, we are facing the problem of constant SendMail job crashes because of timeouts. This only happened if asset fields were part of the form.

The assets **will not** be attached directly to the email. Instead, they are placed in an Asset Container `form_uploads` and the links to the respective files will be rendered into the email template.

Now, back to the crash. Locally and in our Staging Environments, everything was working as expected. On live though, no emails were sent. Turns out, when Assets are passed into the mail template, **references to all images which are stored in the asset volume are passed into the template as well**. This very large dataset obviously crashes the job, since we have about 20k assets just happily hanging around in the file system.

I don't know if this is intended, but I would guess (and hope) it's not :) Sure, purging the Volume solves the problem, but it's only masking the problem and not solving the issue itself.

### How to reproduce

- Create a public asset volume for form uploads
- Create a form with an asset field
- Setup an Email Template
- Render links to the uploaded files into the template
- Submit a form
- Check the Mail queue
- See it working fine
- Populate the Asset Container with about 20k images (depending on server power)
- Submit the form again
- See it fail

### Environment

```yaml
Environment
Application Name: ..
Laravel Version: 10.48.11
PHP Version: 8.3.1
Composer Version: 2.7.7
Environment: production
Debug Mode: OFF
URL: ...
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single, flare
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 7
Antlers: runtime
Sites: 4 (...)
Stache Watcher: Enabled
Static Caching: full
Version: 4.58.2 PRO

Statamic Addons
aryehraber/statamic-color-extractor: 1.4.0
aryehraber/statamic-uuid: 2.3.0
ddm-studio/cookie-byte: 1.5.0
handmadeweb/statamic-laravel-packages: 1.0.5
jonassiewertsen/statamic-documentation: 1.10.0
statamic-rad-pack/shopify: 3.3.1
swiftmade/statamic-clear-assets: 2.0.1
```

### Installation

Starter Kit using via CLI
