### ISSUE TITLE
Navigation Element sidebar prevents opening of overlays like editing a site entry for a link in a grid

### ISSUE THREAD

**Issue by fighter3005** [statamic/cms#10630]
### Bug description

When trying to select an entry for the link in the sidebar, the overlay opens and closes instantly.

![Bildschirmfoto 2024-08-14 um 12 27 44](https://github.com/user-attachments/assets/ed245139-7c36-4283-865e-319ca4052413)

### How to reproduce

Use a table (grid) for a navigation element and put a field inside that opens and overlay, like linking a collection entry.

### Environment

```yaml
"php": "^8",
"eminos/statamic-tabs": "v1.2.0",
"laravel/framework": "v11.20.0",
"laravel/tinker": "v2.9.0",
"statamic/cms": "v5.21.0",
"thoughtco/statamic-restrict-fields": "v1.1.0"
```

### Installation

Fresh statamic/statamic site via CLI
