### ISSUE TITLE
After Save dropdown not showing options

### ISSUE THREAD

**Issue by mscruse** [statamic/cms#10632]
### Bug description

The options for After Save when creating / editing entries is blank. Seems to have been introduced in 5.21.0. Experiencing this on all 5.21.0 sites, but not on 5.20.0.

<img width="299" alt="Screenshot 2024-08-15 at 10 31 30" src="https://github.com/user-attachments/assets/44ba05f8-0da7-4ded-8e4c-09f551909ba4">

### How to reproduce

New install of 5.21.0. Create or edit entry. Click arrow next to Save & Publish button - no options are shown.

### Environment

```yaml
PHP Version: 8.3.10
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: 
Maintenance Mode: OFF
Timezone: Australia/Melbourne
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 11
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.21.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.12.1
jacksleight/statamic-bard-ipsum: 1.0.1
jacksleight/statamic-distill: 0.8.0
mitydigital/feedamic: 2.4.2
mitydigital/iconamic: 2.1.1
mitydigital/sitemapamic: 3.1.0
mitydigital/statamic-google-fonts: 2.0.0
mitydigital/statamic-scheduled-cache-invalidator: 2.0.5
mitydigital/statamic-sticky-notes: 1.0.2
mitydigital/statamic-two-factor: 2.2.1
mitydigital/supportamic: 1.1.1
```

### Installation

Fresh statamic/statamic site via CLI
