### ISSUE TITLE
Checkbox and Radio Button Blueprint format changed breaking frontend templates

### ISSUE THREAD

**Issue by DanielDarrenJones** [statamic/cms#10645]
### Bug description

Saving checkbox or radio button fields on a form blueprint changes their format from:
```
options:
  'Norway': 'Norway'
  'Japan': 'Japan'
  'Kenya': 'Kenya'
  ```
  to
  ```
options:
  -
    key: Norway
    value: Norway
  -
    key: Japan
    value: Japan
  -
    key: Kenya
    value: Kenya
  ```
  
  This changes the way the data is returned to the frontend, giving back an array with the key and value defined within for the value rather than directly, as seen below:
  
![image](https://github.com/user-attachments/assets/7f797ac7-27d9-4721-88ae-653db3a2bfbd)

This results in the fields not rendering properly:
![image](https://github.com/user-attachments/assets/5871c68c-ee51-404a-937c-983baaae9367)

### How to reproduce

Create a checkbox or radio button within a form save, I triggered this breaking again by setting instructions on the field, but I don't think that was the exact cause, rather just it triggered the blueprint to re-save that field triggering the update.

Then attempt to render the field by looping over the data:
```
{{ foreach:options as="option|label" }}
    <label class="text-[#66665D] font-montserrat font-medium text-xs inline-flex tracking-wide mr-5">
        <input
            class="form-checkbox text-[#F38B00] focus:ring-[#BCB9AF] flex-none"
            type="checkbox"
            name="{{ handle }}[]"
            value="{{ option }}"
            {{ if js_driver }}{{ js_attributes }}{{ /if }}
            {{ if value|in_array:option }}checked{{ /if }}
            {{ if validate|contains:required }}required{{ /if }}
        >
        <span class="flex-1 min-w-0  {{ inline ? 'ml-2' : 'ml-5' }}">{{ label !== null ? label : option }}</span>
    </label>
    {{ unless inline }}
        <br>
    {{ /unless }}
{{ /foreach:options }}
```
Please not the above slightly varies from the template defaults, but the important part is that the option and label in `{{ foreach:options as="option|label" }}` have their data formats changed.

### Environment

```yaml
Environment
Application Name: Pelorus
Laravel Version: 10.48.20
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: pelorus-travel.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: log
Queue: redis
Session: redis

Statamic
Addons: 9
Sites: 10 (Travel (GB), Travel (US), Aviation (GB), and 7 more)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.21.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.12.1
doefom/currency-fieldtype: 1.4.0
gerttimmerman/statamic-zapier: 1.6
jacksleight/statamic-bard-texstyle: 3.2.3
ndx/statamic-bard-color-picker: 2.0.0
ryanmitchell/statamic-translation-manager: 2.0.0
statamic/eloquent-driver: 4.12.3
thoughtco/statamic-cache-tracker: 0.5.1
withcandour/aardvark-seo: 5.0.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
