### ISSUE TITLE
{{ config:mail:from:address }} doesn't work in some form email fields

### ISSUE THREAD

**Issue by mehdismekouar** [statamic/cms#10647]
### Bug description

**{{ config:mail:from:address }}** doesn't work in **recipient** field nor **cc**, **bcc**, **reply-to** in form emails
but works only in **sender** field

### How to reproduce

- create a form in the admin panel
- in the form configuration page, at the bottom click on **Add Email**
- in the **recipient** field write: **{{ config:mail:from:address }}** to indicate that we want to mail the **laravel default from email**
- in the other fields choose whatever suits you
- navigate to the form link and fill the form then send it
- you should be able to see an error like: `An email must have a "To", "Cc", or "Bcc" header`

### Environment

```yaml
Environment
Application Name: Mehdi Mekouar
Laravel Version: 11.16.0
PHP Version: 8.2.12
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: localhost:8000
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.20.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
