### ISSUE TITLE
Session tag wildcard method could fails when a conflicting variable exists in the current context

### ISSUE THREAD

**Issue by dadaxr** [statamic/cms#10643]
### Bug description

AFAIK Ihe variables created inside {{ nocache tag }} are not accessible to other nocachetag... So my idea was to use the session to share existing data between two {{ nocache tag }}  but it seems that fetching data from session can behave inconsistently according to the variable defined in the current scope (context)

ie : 

```
{{ nocache }}
  {{ variableToShare = { heavy:processing } }}
  {{ session:set :variableToShare="variableToShare" }}
  ... some template stuff using this variableToShare
{{ /nocache }}

... other template stuff 
{{ nocache }}
 {{ myRetrievedVariabled = {session:variableToShare} }} => myRetrievedVariabled is empty, it does not work
 {{ myRetrievedVariabled = {session:value key="variableToShare} }} => myRetrievedVariabled is filled, it's ok.

   ... some other template stuff using this variableToShare
{{ /nocache }}

```

So put simply I could say : if a variable named "xxx" exist in the current context, the tag {{ session:xxx }} would not work as intended (documented). 

Moreover, the {{ session:value key="xxx" }} tag method is not documented (source diving helps ;))

### How to reproduce

{{ my_var = 'value' }}
{{ session:set my_var="another value" }}

{{ session:my_var }} {# output nothing : it's broken }}
{{ session:value key="my_var" }} {# output "another value" : it's working }}

### Environment

```yaml
Environment
Laravel Version: 10.48.13
PHP Version: 8.2.7
Composer Version: 2.6.2
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.20.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
