### ISSUE TITLE
Translations of a set group displayed in a replicator preview at the top level does not work (multiple levels)

### ISSUE THREAD

**Issue by fighter3005** [statamic/cms#10657]
### Bug description

![Bildschirmfoto 2024-08-19 um 17 11 07](https://github.com/user-attachments/assets/c5295d62-39c7-4ec4-9de2-3f2c64311d6b)

The translation of the Set does not show properly at the upper location, but does translate successfully at the bottom red square. This seems to be a bug?

![image](https://github.com/user-attachments/assets/f6854fac-09d6-4aa6-a364-68ba5e8a11f0)

### How to reproduce

Use translation file to translate into different languages.

### Environment

```yaml
"php": "^8",
"eminos/statamic-tabs": "v1.2.0",
"laravel/framework": "v11.20.0",
"laravel/tinker": "v2.9.0",
"statamic/cms": "v5.21.0",
"thoughtco/statamic-restrict-fields": "v1.1.0"
```

### Installation

Fresh statamic/statamic site via CLI
