### ISSUE TITLE
`locale` tag not working inside `taxonomy` tag

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#10655]
### Bug description

After updating a site from 4.28 to 4.57.1 the output of this slug is empty.
```
{{ taxonomy:betriebsart }}
{{ locales:de }}{{ slug }}{{ /locales:de }}
{{ /taxonomy:betriebsart }}
```
This pr broke the output:
https://github.com/statamic/cms/pull/9566/files

After updating to the current version this is still an issue.

### How to reproduce

Try to output a taxonomy slug from a specific site with a multi-site setup.

### Environment

```yaml
Environment
Laravel Version: 10.48.19
PHP Version: 8.3.7
Composer Version: 2.5.8
Environment: production
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Sites: 2 (Deutsch, Englisch)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.19.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
