### ISSUE TITLE
Hiding only blueprint for taxonomy does not hide Create Term button

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/cms#10675]
### Bug description

Similar to this issue https://github.com/statamic/cms/issues/9735

Hiding the only blueprint for a taxonomy does not hide the "Create Term" button and instead the button shows an empty dropdown

### How to reproduce

1. Create a taxonomy
2. Edit the blueprint and check the "Hidden" toggle
3. Go to the taxonomy index page and attempt to create a new term
4. The button is visible still and the dropdown shown is empty

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.20.0
PHP Version: 8.3.10
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: site.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 5
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.22.1 PRO

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.2.3
kolaente/statamic-snippet: 1.1.2
statamic-rad-pack/meilisearch: 3.3.0
```

### Installation

Fresh statamic/statamic site via CLI
