### ISSUE TITLE
Use title instead of handle in selected user roles

### ISSUE THREAD

**Issue by stefankempf** [statamic/cms#10673]
### Bug description

When adding a new user, selected roles get shown below the dropdown. The label of these selected roles (and probably also groups) is the handle instead of the title.

![Screenshot von 2024 08 21 um 16 12 55](https://github.com/user-attachments/assets/e4d2e06e-595b-4dc2-bdb2-34616ae28643)

### How to reproduce

create user role and add new user

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.19.0
PHP Version: 8.3.9

Statamic
Addons: 0
Sites: 1
Static Caching: Disabled
Version: 5.19.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
