### ISSUE TITLE
Select Field - Frontend output - All entities using key value

### ISSUE THREAD

**Issue by palmersoft-uk** [statamic/cms#10696]
### Bug description

![Screenshot 2024-08-23 at 21 10 14](https://github.com/user-attachments/assets/14e9f9ae-7b0b-4345-817f-c821964e01c2)

Select field added to collection, multi select enabled, values as per screenshot above.

I then created an entry in the collection and added three categories.

![Screenshot 2024-08-23 at 21 29 00](https://github.com/user-attachments/assets/b2944108-c862-4a3d-9412-4c3bfe06e004)

The output uses the label value as expected.

On the frontend, the key, value, and label entities are all using the key.

```
{{ dump:categories }}
```

Produces

```
array:3 [▼
  0 => array:3 [▼
    "key" => "employers"
    "value" => "employers"
    "label" => "employers"
  ]
  1 => array:3 [▼
    "key" => "news"
    "value" => "news"
    "label" => "news"
  ]
  2 => array:3 [▼
    "key" => "job-seekers"
    "value" => "job-seekers"
    "label" => "job-seekers"
  ]
]
```
I am expecting the label entity to use the value I specified in the blueprint.

### How to reproduce

Latest version of statamic.

Create a collection.

Edit the blueprint.

Add a select field.

Add some options to the select field, ensuring that the key and label are set, and that the label is different to the key.

Create at least one entity in the collection and ensure you select an option in the select field.

On the frontend, output the collection, for each entity ensure you output the select field, or dump the field.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.20.0
PHP Version: 8.2.22
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: annecorder.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.23.0 PRO

Statamic Addons
aerni/font-awesome: 3.0.1
aryehraber/statamic-captcha: 1.12.1
ndx/statamic-bard-color-picker: 2.0.0
```

### Installation

Fresh statamic/statamic site via CLI
