### ISSUE TITLE
Blueprint → Edit Section: display and instructions not saved on enter

### ISSUE THREAD

**Issue by meyegui** [statamic/cms#10702]
### Bug description

When creating a new section in a blueprint, hitting the `Enter` key has the same effect as clicking "Cancel".

To save the details, I had to reopen the "Edit Section" modal, redo my changes, and click the "Save" button.

### How to reproduce

1. Go to any blueprint.
2. Add a new section or edit an existing one.
3. Hit `Enter` rather than clicking the "Save" button in the "Edit Section" modal.
4. Behold! The section details remain unchanged.

https://github.com/user-attachments/assets/ce570d13-1fc9-4d0a-8b91-0572fd1b7ba6

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.21.0
PHP Version: 8.3.10
Composer Version: 2.7.8
Environment: local
Debug Mode: ENABLED
URL: statamic-cyberspace.ddev.site
Maintenance Mode: OFF
Timezone: Europe/Zurich
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mariadb
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.23.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

I'm using DDEV but I'd be surprised if it was related to this bug, because it looks like a client bug to me, and not a server-side bug.
