### ISSUE TITLE
Statamic Cloudinary asset container not working with folders

### ISSUE THREAD

**Issue by DmitrySidorenkoShim** [statamic/cms#10716]
### Bug description

I understand it is not directly a bug of Statamic itself
but maybe someone can help me with this issue

so, in 'Assets' if you have 'Cloudinary' asset container
and any folders in Cloudinary
like 'auto mapping folder' and other nested folders in it 
loading of a list takes too much time, and at the end id shows 'The container is empty'
![Screenshot 2024-08-28 at 12 06 52](https://github.com/user-attachments/assets/3a482754-60bf-4f1d-9adb-9ddd596acad1)

I thought it is an issue of Cloudinary itself
but it works perfectly without any folders

 - upload, list, preview, destroy, rename, etc.
 
Cloudinary package is only as flysystem disk driver
 and it does return a list of all files and directories from Cloudinary
 I also tried all variants of data in `asset_meta` trying to make it work

### How to reproduce

So, install [yoelpc4/laravel-cloudinary](https://github.com/yoelpc4/laravel-cloudinary)
(I don't know why, but the official package [cloudinary-labs/cloudinary-laravel](https://github.com/cloudinary-community/cloudinary-laravel) is not fully working in this case)
Fill out `.env `credentials:
```
FILESYSTEM_DISK=cloudinary

CLOUDINARY_API_KEY=
CLOUDINARY_API_SECRET=
CLOUDINARY_CLOUD_NAME=
CLOUDINARY_SECURE=true
```
Register cloudinary driver configuration in `config/filesystems.php` at disks section (example in the package readme)
In Cloudinary 'Upload Presets' add 'asset folder', for example: 'some/images'

After all this setup is done goto Statamic Assets, create a new asset container 'Cloudinary' which uses 'cloudinary' disk
and upload some sample.jpg (on this step Statamic will show an error " Hochladen fehlgeschlagen. Die Datei ist möglicherweise größer als von deinem Server erlaubt. " ["Upload failed. The file size may be larger than your server allows."])
the image is successfully uploaded to cloudinary though
check the image is in the folder in Cloudinary
something like:
https://res.cloudinary.com/.../image/upload/v1.../some/images/sample.jpg
and it is in `asset_meta` in database

but after this there is no chance to see it in Statamic

any help on this would be appreciated 🙏 

### Environment

```yaml
Environment
Application Name: Bergwelten Backend
Laravel Version: 10.48.20
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.8.0
PHP SDK Version: 4.9.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 3
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.58.2 PRO

Statamic Addons
rbmh/cdc-user-area: dev-master
rbmh/global-functions: 2.2.0
statamic/eloquent-driver: 3.4.1

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
```

### Installation

Existing Laravel app

### Additional details

I don't know if it is important
but I have tried this:
```
    $rawFlysystemDirectoryListing        = \Illuminate\Support\Facades\Storage::disk('cloudinary')
        ->getDriver()->listContents('/', true);
    $files = collect($rawFlysystemDirectoryListing)
        ->keyBy('path')
        ->map(fn ($file) => \App\Services\TestService::normalizeFlysystemAttributes($file))
        ->pipe(fn ($files) => \App\Services\TestService::ensureMissingDirectoriesExist($files))
        ->sortKeys();
```
  like you have it in \Statamic\Assets\AssetContainerContents::all()
  in $files I have a full list of files and directories from Cloudinary
  
  as I wrote, any help would be greatly appreciated
