### ISSUE TITLE
field handle does not show up on hover in CP

### ISSUE THREAD

**Issue by dadaxr** [statamic/cms#10717]
### Bug description

When editing an entry, we can hover the field label to see the field handle in a tooltip (black box in the belllow picture)

![image](https://github.com/user-attachments/assets/1784880c-fc27-4f11-abbf-c46701d7adf5)

But when fields are in replicator or group, nothing appears on hover.
For instance, on my screenshot, nothing appears when hovering "Hero" or "Slides" or "Image desktop"

It's quite usefull when coding templates (without it we have to go to the blueprint definition to check handles).

If using a nice tooltip is the probleme here... maybe we can just show a native window using the title attribute (shown on the on the screenshot above for the example) ? What do you think ?

### How to reproduce

read the ticket above

### Environment

```yaml
Environment
Application Name: xxx
Laravel Version: 10.48.13
PHP Version: 8.2.7
Composer Version: 2.6.2
Environment: local
Debug Mode: ENABLED
URL: xxx.localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.20.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
