### ISSUE TITLE
When revisions are enabled, after saving and publishing, saving again disables publishing until a refresh is made

### ISSUE THREAD

**Issue by mattmultiplied** [statamic/cms#10723]
### Bug description

After saving and publishing an entry with revisions enabled, saving again disables publishing until a refresh is made.

Please what the video for the bug:

https://www.loom.com/share/506dc00670d84a74b37682cf06b87eac?sid=658ffa02-ef67-42d0-8044-d6be94a6eac3

### How to reproduce

With revision enabled.

- Save entry
- Publish entry
- Save entry again
- It will then highlight the entry has unsaved changes and can't be published until a refresh is made

### Environment

```yaml
Environment
Application Name: Wilson Power Solutions
Laravel Version: 11.21.0
PHP Version: 8.3.7
Composer Version: 2.7.7
Environment: local
Debug Mode: OFF
URL: wilson-power-solutions.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 3 (Wilson Power Solutions, Wilson Power Solutions India, WATTS Rental Dubai)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.23.0 PRO

Statamic Addons
alt-design/alt-redirect: 1.3.2
jacksleight/statamic-bard-texstyle: 3.3.0
statamic/seo-pro: 6.0.3
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

No fancy set-ups, just standard Statamic.
