### ISSUE TITLE
Conditional Field Display Based on Taxonomy Selection Not Working

### ISSUE THREAD

**Issue by emran-alhaddad** [statamic/cms#10722]
### Bug description

I have created a taxonomy called "categories" and added two categories. In the Pages collection, specifically on the Home page, I added two text fields (Field 1 and Field 2) and a taxonomy term field called "Test Categories" linked to the "categories" taxonomy. The "Test Categories" field is configured to display as a select dropdown.

I set up conditions for Field 1 to display if "Test Categories" is set to "category-1" and for Field 2 to display if "Test Categories" is set to "category-2" based on the slug from the "categories" taxonomy.

However, when I save and test the setup, neither Field 1 nor Field 2 appears based on the conditions. I tried all possible conditional show configurations for the fields, but none of them worked. This appears to be a bug.

Attached Screenshots:

Configuration of the taxonomy and categories.
Pages collection setup.
Field conditions setup.
<img width="1439" alt="Screenshot 2024-08-28 at 11 30 50 PM" src="https://github.com/user-attachments/assets/4b233679-843e-42eb-ba74-4c926974231d">
<img width="1440" alt="Screenshot 2024-08-28 at 11 30 42 PM" src="https://github.com/user-attachments/assets/450a8490-7ec7-480c-ab92-7290dd6e7fd2">
<img width="1433" alt="Screenshot 2024-08-28 at 11 30 33 PM" src="https://github.com/user-attachments/assets/5bb1d042-2113-4fdc-9be4-aa41a79e90b0">
<img width="1434" alt="Screenshot 2024-08-28 at 11 30 14 PM" src="https://github.com/user-attachments/assets/9c59692e-9aec-4b7b-a66e-a28e7b4c5ade">
<img width="1439" alt="Screenshot 2024-08-28 at 11 30 04 PM" src="https://github.com/user-attachments/assets/b6301335-ca8b-464c-8724-d093b2975940">
<img width="1440" alt="Screenshot 2024-08-28 at 11 29 52 PM" src="https://github.com/user-attachments/assets/245ddf3d-5ec6-4413-86ef-602ded2c9463">
<img width="1440" alt="Screenshot 2024-08-28 at 11 29 36 PM" src="https://github.com/user-attachments/assets/4071ae68-4e87-4716-8e19-7a8dc5bb8669">
<img width="1439" alt="Screenshot 2024-08-28 at 11 29 19 PM" src="https://github.com/user-attachments/assets/e8285e74-1c64-4ff0-ba22-6bc0e00f0c67">
<img width="1440" alt="Screenshot 2024-08-28 at 11 28 36 PM" src="https://github.com/user-attachments/assets/ec4a4017-0b2d-45a9-a085-18f0a8166c18">

### How to reproduce

1. Create a taxonomy called "categories."
2. Add two categories within this taxonomy.
3. In the Pages collection, on the Home page:
4. Add two text fields (Field 1 and Field 2).
5. Add a taxonomy term field called "Test Categories" linked to the "categories" taxonomy.
6. Set "Test Categories" to display as a select dropdown.
7. Set the condition for Field 1 to display if "Test Categories" is "category-1."
8. Set the condition for Field 2 to display if "Test Categories" is "category-2."
9. Save the setup and try to view the fields based on the condition.

### Logs

```shell
There are no specific logs available as the issue is related to UI behavior.
```

### Environment

```yaml
Statamic Version: 5.23.0

Output of php please support:details:

Environment
Application Name: Sand & Fun
Laravel Version: 11.21.0
PHP Version: 8.2.22
Composer Version: 2.5.5
Environment: production
Debug Mode: ENABLED
URL: sand-fun-cms.brackets-tech.com
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.23.0 PRO

Statamic Addons
statamic-rad-pack/mailchimp: 5.1.1
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

All screenshots related to the issue have been attached for reference. The conditions should have worked as per the configuration, but they failed to trigger the field display.
