### ISSUE TITLE
Parent on Home entry displaying error on field when revisions and multisite are used

### ISSUE THREAD

**Issue by mattmultiplied** [statamic/cms#10724]
### Bug description

After saving the Home entry with revisions and multisite enabled, the parent field turns red with empty contents suggesting there's an error. This only occurs on the Home entry when no parent should be allocated. This is occurring all websites that have been migrated from Statamic 4 to Statamic 5 with revisions and multisite enabled.

### How to reproduce

1. Save the home entry
2. The field will turn red suggesting there is an error

https://www.loom.com/share/ea1d3df19f5547b4a6df3e547b2c544f?sid=2d5b12cc-9bef-4023-9e44-feca197ba90d

### Environment

```yaml
Environment
Application Name: Wilson Power Solutions
Laravel Version: 11.21.0
PHP Version: 8.3.7
Composer Version: 2.7.7
Environment: local
Debug Mode: OFF
URL: wilson-power-solutions.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 3 (Wilson Power Solutions, Wilson Power Solutions India, WATTS Rental Dubai)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.23.0 PRO

Statamic Addons
alt-design/alt-redirect: 1.3.2
jacksleight/statamic-bard-texstyle: 3.3.0
statamic/seo-pro: 6.0.3
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Standard Statamic 5 set-up with multisite and revisions enabled.
