### ISSUE TITLE
Forms: Text fields with `hidden` type are hidden in the control panel

### ISSUE THREAD

**Issue by JonKaric** [statamic/cms#10734]
### Bug description

If you add a text field to a form with the _Input Type_ of `hidden`, it hides that field from form submissions in the control panel. 

If it's intentional, I think a field setting would make it a little more friendly. Sometimes you might wanna include information within the form to be visible in the control panel, but hidden from the frontend. 

### How to reproduce

- Add a text field to your form

```yaml
-
  handle: text_field
  field:
    input_type: hidden
    antlers: true
    type: text
    display: 'Text Field'
    localizable: false
```

2) Submit the form
2) Go to that form submission
3) Behold! a label with nothing under it 

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.20
PHP Version: 8.3.10
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.6

Statamic
Addons: 4
Sites: 2 (en, fr)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.22.1 PRO

Statamic Addons
arrowtide/statamic-payment-icons: 1.1.0
jonassiewertsen/statamic-livewire: 3.6.0
statamic-rad-pack/shopify: 3.4.2
```

### Installation

Fresh statamic/statamic site via CLI
