### ISSUE TITLE
Session start/cookies not needed for all visitors

### ISSUE THREAD

**Issue by 925dk** [statamic/cms#10745]
### Bug description

Seems `laravel_session` and `XSRF-TOKEN` cookies are always set on front-end (for all users). Which I guess means a server side session is always created.

I don't need (or want) any session/state for regular site visitors.

For performance + no need to put cookies when not actually needed (privacy/cookie policy/politeness) + play nicely with any reverse proxy/cache etc.

Of course for cp/signed-in users, things can/should continue to function as-is. This is about normal visitors to the site/front-end.

So I suggest by-pass the session start/cookie stuff for regular site visitors as the default. Or if that is a breaking change, have a config option to disable it.

### How to reproduce

Visit a Statamic site in a private tab. See cookies are placed.

### Environment

```yaml
Environment
Application Name: xxx
Laravel Version: 11.21.0
PHP Version: 8.2.21
Composer Version: 2.5.8
Environment: production
Debug Mode: OFF
URL: dev.xxx.com
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: sqlite
Logs: stack / single
Mail: sendmail
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 2 (xxx (en), xxx (da))
Stache Watcher: Disabled
Static Caching: half
Version: 5.23.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
