### ISSUE TITLE
Delete modal runs action too early

### ISSUE THREAD

**Issue by morhi** [statamic/cms#10754]
### Bug description

When deleting entries and there are entries with descendants the modal would ask if you want to delete or detach the descendants (localizations). However, the modal already sends the request when clicking the button whether to delete or detach the descendants and not when clicking the actual red delete button.

https://github.com/user-attachments/assets/128e3a86-f33f-4c63-aacc-068e60b54306

### How to reproduce

Delete many entries having descendants and press the delete option for descendants. The action will run immediately instead of after clicking the red delete button.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.21.0
PHP Version: 8.2.20
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 19
Sites: 2 (Deutsch, Französisch)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.23.0 PRO

Statamic Addons
doefom/statamic-export: 0.4.0
duncanmcclean/simple-commerce: 7.4.5
jonassiewertsen/statamic-livewire: 3.6.0
rias/statamic-redirect: 3.7.2
thoughtco/statamic-cache-tracker: 0.8.2
...
```

### Installation

Fresh statamic/statamic site via CLI
