### ISSUE TITLE
Static Page Cache number too high?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#10757]
### Bug description

Hi

I've been experiencing issues with my queues not running. 

While looking around, trying to figure out what the issue is, I spotted the static page cache is `9540` pages?

This is way too high, the site isn't that big.

I wonder if this could be the reason why the queue keeps failing?

Do you know of any reason why the static page cache would inflate like this?

<img width="908" alt="Screenshot 2024-09-04 at 10 01 04" src="https://github.com/user-attachments/assets/5c0249b8-3516-477c-8a81-f9e3c6da33c4">

### How to reproduce

Difficult to know how to reproduce, sorry.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.20.0
PHP Version: 8.3.10
Composer Version: 2.7.8
Environment: production
Debug Mode: OFF
URL: website.com
Maintenance Mode: OFF
Timezone: America/New_York
Locale: en

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: redis
Session: redis

Livewire
Livewire: v3.5.4

Statamic
Addons: 5
Sites: 1
Stache Watcher: Disabled
Static Caching: half
Version: 5.22.0 PRO

Statamic Addons
jonassiewertsen/statamic-jobs: 1.5.0
jonassiewertsen/statamic-live-search: 2.1.1
jonassiewertsen/statamic-livewire: 3.6.0
statamic/collaboration: 1.0.0
visuellverstehen/statamic-anchor-navigation: 1.0.0
```

### Installation

Fresh statamic/statamic site via CLI
