### ISSUE TITLE
Non-Statamic tests run slow after Statamic installation

### ISSUE THREAD

**Issue by Fadarrizz** [statamic/cms#10753]
### Bug description

After installing Statamic in an existing Laravel project, all non-Statamic tests take more than a second per test longer.

I've been playing with some config settings, such as stache, but nothing seems to improve it.

### How to reproduce

- Have an existing Laravel project with tests
- Pick a test and see duration after running
- Install Statamic with eloquent-driver addon
- Run test again and notice duration increase

### Environment

```yaml
❯ a statamic:support:details

Environment
Application Name: Laravel
Laravel Version: 11.21.0
PHP Version: 8.3.11
Composer Version: 2.7.8
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: nl

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: null
Cache: file
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: sync
Session: database

Filament
Packages: filament, forms, notifications, support, tables
Version: v3.2.110
Views: PUBLISHED: notifications

Livewire
Livewire: v3.5.6

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.8.0
PHP SDK Version: 4.9.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 0%
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 1
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.23.0 Solo

Statamic Addons
statamic/eloquent-driver: 4.14.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Existing Laravel app
