### ISSUE TITLE
Form submission emails not sent due to SMTP issues; form submissions not saved to database

### ISSUE THREAD

**Issue by emran-alhaddad** [statamic/cms#10761]
### Bug description

When I configure an email to be sent after a form submission using "Email: Configure emails to be sent when new form submissions are received," if there is an issue with the SMTP account linked to Statamic, the email fails to send, and the form submission is not stored in the database.
Expected behavior: Even if the email sending fails, the form submission should still be saved in the database.

What happened?
I set up a form to send emails after submission, but encountered an SMTP error. As a result, the submission was not saved to the database.

What did you expect to happen?
I expected that if the email failed to send, the form submission would still be stored in the database, regardless of the email issue.

### How to reproduce

Set up a form with email notifications enabled.
Link an SMTP account to handle email submissions.
Simulate an SMTP error (e.g., by providing invalid SMTP credentials).
Submit the form and observe that neither the email is sent nor the submission stored in the database.

### Environment

```yaml
Environment
Application Name: ###
Laravel Version: 11.21.0
PHP Version: 8.2.22
Composer Version: 2.5.5
Environment: production
Debug Mode: ENABLED
URL: ###
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.23.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

No other special configurations were made. The issue is linked to SMTP failures, but form data should still be stored even if an email issue occurs.
