### ISSUE TITLE
Table border radius missing

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#10760]
### Bug description

Lately an issue re-appeared regarding the top border radius of table headers:
<img width="936" alt="Screenshot 2024-09-04 at 13 40 56" src="https://github.com/user-attachments/assets/af968683-18fc-45f7-bae8-491675a44b23">
<img width="927" alt="Screenshot 2024-09-04 at 13 40 31" src="https://github.com/user-attachments/assets/1f130559-e351-4b3e-af3b-ce62626e18f9">

### How to reproduce

Check the globals table, or the collection blueprint table.

### Logs

```shell
Environment
Application Name: Statamic Peak Development
Laravel Version: 11.21.0
PHP Version: 8.2.22
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 2 (English, Dutch)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.23.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.4.3
studio1902/statamic-peak-seo: 8.15.3
studio1902/statamic-peak-tools: 6.3.2
```

### Environment

```yaml
Environment
Application Name: Paro
Laravel Version: 11.22.0
PHP Version: 8.2.22
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: paro.test
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.6

Statamic
Addons: 5
Sites: 3 (English, Dutch, German)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.24.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.6.0
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.4.3
studio1902/statamic-peak-seo: 8.16.0
studio1902/statamic-peak-tools: 6.3.2
```

### Installation

Starter Kit using via CLI
