### ISSUE TITLE
[5.x] Letter 'f' cannot be typed in Asset file rename modal in some cases

### ISSUE THREAD

**Issue by steveparks** [statamic/cms#10776]
### Bug description

Sometimes, users are unable to type the letter 'f' in the filename field of the Asset file rename modal. Reports so far are only from users of the Brave browser.

Mitsch reported this issue in Discord: https://discord.com/channels/489818810157891584/489818810157891586/1280881805100056598

> I have a somewhat weird problem. 
> This problem only occurs for SOME of my authors and I don't know why.
> 
> When renaming a file [in the Rename modal's Filename field], the letter 'f' can't be used. -- Nothing happens when that letter is pressed on the keyboard. It can be copied still...
> The uppercase letter 'F' is totally fine
> They can use the letter f everywhere (even on statamic) but not in the input field for renaming files
> they are all using brave
> 
> if I am using brave everything is working fine.
> For my authors it's not. For now I'm unable to further check their settings but they are up to date as well.
> Stock brave installation

I have experienced this exact issue myself a few weeks ago — same letter, same field. I just assumed it was a problem with my keyboard or my laptop needed a PRAM reset. 
I can't reproduce it now. Perhaps it's been resolved by updates I've done to Statamic or Brave in the meantime, or perhaps it's intermittent.

This is the modal that is affected:
![CleanShot 2024-09-06 at 17 23 02@2x](https://github.com/user-attachments/assets/0848e60b-ef46-41ed-84ab-ac1898e3bec8)

In troubleshooting, Mitsch then reported:
> I got an error "Uncaught TypeError: this.handleShowFilters is not a function"

@925dk replied:
> Bet it's https://github.com/statamic/cms/blob/dd4ad041859660a80a96aa9c9145225463336986/resources/js/components/data-list/HasFilters.js#L58. 
> Guess just nuke, left over from filter refactor it seems.

I will submit a PR for consideration with this issue, implementing 925dk's suggestion.

### How to reproduce

Seems difficult to reproduce. Others have tried and not had the same issue.

But if the issue does occur, it's these steps:
1. Use the Brave browser
2. Navigate to an asset, click 'rename'
3. In the filename field type various letters including trying 'f'

### Environment

```yaml
This is my current environment, but I don't have the issue anymore:

Environment
Application Name: Convivio
Laravel Version: 11.21.0
PHP Version: 8.3.10
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: convivio.test
Maintenance Mode: OFF
Timezone: Europe/London
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.6

Statamic
Addons: 12
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.23.0 PRO

Statamic Addons
goldnead/statamic-toc: 1.5
jonassiewertsen/statamic-livewire: 3.6.0
mitydigital/feedamic: 2.5.0
mitydigital/statamic-scheduled-cache-invalidator: 2.1.0
statamic/wikilinks: 2.1.0
stillat/relationships: 2.2.1
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.4.3
studio1902/statamic-peak-seo: 8.16.0
studio1902/statamic-peak-tools: 6.3.2
tv2regionerne/statamic-passport: 1.4.1
tv2regionerne/statamic-private-api: 1.15.0
```

### Installation

Existing Laravel app
