### ISSUE TITLE
Duplicate IDs menu entry icon

### ISSUE THREAD

**Issue by steven-reckless** [statamic/cms#10779]
### Bug description

The icon for the duplicate IDs menu entry in the CMS is not displaying.
It is showing just the text instead
Consistent across local and production.
![re-bug-screenshot](https://github.com/user-attachments/assets/de1f543c-3024-41b9-8828-0ac088d72d13)

### How to reproduce

Standard base Statamic install.
No special steps taken.

### Environment

```yaml
Environment
Application Name: RE
Laravel Version: 11.22.0
PHP Version: 8.2.13
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: relocal.com
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 2 (RE-US, RE-EN)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.24.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
