### ISSUE TITLE
Debug error Static cache loaded multisite

### ISSUE THREAD

**Issue by danielreales7** [statamic/cms#10783]
### Bug description

I'm using the static cache full strategy in my multisite project. I've tried a hundred thousand different configurations and I always get the same error.

production.DEBUG: Static cache loaded If you are seeing this, your server rewrite rules have not been set up correctly.

### How to reproduce

This is my nginx.conf

```php
set $try_location @static;
    
    if ($request_method != GET) {
        set $try_location @not_static;            
    }
    
    if ($args ~* "live-preview=(.*)") {
        set $try_location @not_static;
    }

    location / {
        try_files $uri $try_location;
    }
    
    location @static {
        try_files /static/${host}${uri}_$args.html $uri $uri/ /index.php?$args;
    }
    
    location @not_static {
        try_files $uri /index.php?$args;
    }
```

This is my static_caching:

```php
'full' => [
            'driver' => 'file',
            'path' => [
                'es' => public_path('static') . '/' . env('APP_DOMAIN'),
                'en' => public_path('static') . '/' . env('APP_EN_DOMAIN'),
            ],
            'lock_hold_length' => 0,
            'warm_concurrency' => 10,
        ],
```

APP_DOMAIN = mysite.es
APP_EN_DOMAIN = mysite.es

I have to say that all the Spanish URLs are mysite.es, mysite.es/portfolio, mysite.es/test etc.

In English they are:
mysite.es/en, mysite.es/en/projects, mysite.es/en/test etc.

I have tried countless solutions but I always get the same error and I don't know what to do.

Another detail to keep in mind is that the URL that appears in the logs is https://www.mysite.es/ many times and I don't understand why it adds the slash at the end if in my nginx.conf I have:
```
# REMOVE TRAILING SLASH
rewrite ^/(.*)/$ /$1 permanent;
```

### Environment

```yaml
Environment
Application Name: Statamic Peak
Laravel Version: 9.52.16
PHP Version: 8.2.21
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Sites: 2 (Español, English)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.58.2 PRO
```

### Installation

Starter Kit using via CLI
