### ISSUE TITLE
Erroneous filter after Collection `Reorder`

### ISSUE THREAD

**Issue by sjclark** [statamic/cms#10796]
### Bug description

Cancelling or saving from the Collection **Reorder** function results in an erroneous `Site: Statamic` filter.

https://github.com/user-attachments/assets/2ff61a29-2b87-476b-a16d-8c4359f61882

### How to reproduce

1. Make an **orderable collection**.
2. Use the **reorder** function
3. Gasp in despair at a filter that does nothing!

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.17.0
PHP Version: 8.2.21
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: complaints.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en_AU

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.25.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Note this is **not** a multi-site. As far as I can tell this is just a visual / cosmetic glitch.
