### ISSUE TITLE
Field listing visibility doesn't work in assets containers

### ISSUE THREAD

**Issue by mattmultiplied** [statamic/cms#10799]
### Bug description

In the blueprint editor for Assets Containers the listing visibility fields allow you to set their visibility in the list view. Although, currently in assets containers these don't do anything as you can't edit the fields that are displayed in the list view.

(Not sure if this is a bug or whether it should be posted in the Statamic Ideas Repo, can move over if it's the wrong place!)

<img width="1527" alt="Screenshot 2024-09-13 at 19 04 33" src="https://github.com/user-attachments/assets/159044f9-466d-4b66-8686-a8300c0a3274">

It would be good to have the functionality to display additional fields in the list views for assets, similar to how they display in collections. This would be really helpful for identifying assets with and without alternative text in large folders.

<img width="1496" alt="Screenshot 2024-09-13 at 19 15 34" src="https://github.com/user-attachments/assets/6d316202-d286-47fb-8a4f-107e4221e776">

### How to reproduce

Set a field to have Listable to Shown by default, but it doesn't display in the list view.

### Environment

```yaml
Environment
Application Name: Website
Laravel Version: 11.21.0
PHP Version: 8.3.7
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: website.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: CACHED
Events: CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 3
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.25.0 PRO

Statamic Addons
alt-design/alt-redirect: 1.3.2
jacksleight/statamic-bard-texstyle: 3.3.0
statamic/collaboration: 1.0.0
statamic/seo-pro: 6.1.1
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

The assets container is using an DO S3 Spaces Object to store media.
