### ISSUE TITLE
Slugs are shown in collection tables even with listable set to `Hidden by default`

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#10792]
### Bug description

Slugs are shown in collection tables even with listable set to `Hidden by default`

### How to reproduce

Create a collection
Set slugs to `Hidden by default`
View collection table
See slugs

### Environment

```yaml
Environment
Laravel Version: 11.23.2
PHP Version: 8.2.23
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.6

Statamic
Addons: 5
Sites: 3 (English, Dutch, German)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.25.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.8.0
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.8.0
studio1902/statamic-peak-seo: 8.16.0
studio1902/statamic-peak-tools: 6.3.2
```

### Installation

Fresh statamic/statamic site via CLI
