### ISSUE TITLE
EntrySaved event listener never completes

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#10804]
### Bug description

Below is a very basic listener which is fired on the EntrySaved event. If I use the sync queue then my CP freezes. If I use the redis queue then the listener never completes:

`2024-09-16 12:31:12 App\Listeners\ForceEntryInvalidationTest ................................... RUNNING  `

```
namespace App\Listeners;

use Statamic\Facades\Entry;
use Statamic\Events\EntrySaved;
use Illuminate\Contracts\Queue\ShouldQueue;

class ForceEntryInvalidationTest implements ShouldQueue
{
    public function handle(EntrySaved $event)
    {
        \Illuminate\Support\Facades\Log::info('Invalidating entry', ['entry' => $event->entry]);
    }
}
```

I've tried other events, e.g. NavSaved, and everything works fine.

This is only happening on localhost using Laragon (similar to WAMP).

### How to reproduce

Use a non-queued listener on EntrySaved, e.g.:

```
        \Statamic\Events\EntrySaved::class => [
            ForceEntryInvalidationTest::class
        ],
```

### Logs

None available. It just hangs forever.

### Environment

```yaml
Environment
Application Name: My Site
Laravel Version: 11.23.5
PHP Version: 8.2.13
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: mysite.test
Maintenance Mode: OFF
Timezone: Europe/Dublin
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: single
Mail: smtp
Queue: redis
Session: file

Livewire
Livewire: v3.5.6

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.25.0 PRO

Statamic Addons
jonassiewertsen/statamic-live-search: 2.1.1
jonassiewertsen/statamic-livewire: 3.8.0
rias/statamic-redirect: 3.7.2
spatie/statamic-responsive-images: 5.0.1
statamic/seo-pro: 6.1.2
```

### Installation

Fresh statamic/statamic site via CLI
