### ISSUE TITLE
Image reference removed from .md, if image isn't local.

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#10820]
### Bug description

Admittedly, an edge case (perhaps?)

I use Laravel Sync for my images, this means assets aren't version controlled in Git.

When I pull latest updates from `production` to `local`, sometimes I forget to pull the assets (using Laravel Sync).

Most of the time this isn't really an issue, as I'm not making any changes to entries that are missing images from production. 

The problem arrises when I do make a `local` edit to an entry that contains images I've not pulled from `production`

The entry markdown file still has the reference to the image, `entry_images`

```
type: set
    attrs:
      id: m1aff5vd
      values:
        type: image
        entry_images:
          - slava-auchynnikau-b5ncjc-kpva-unsplash.jpg
```

The bard field shows the image set template, but there's no image. Even though `entry_images` still has a value (at this point).

The problem I've come across is, if I press save `entry_images` is removed.

When I push the update to production the image is no longer shown... I understand why this happens. The image isn't local, I press save and the reference to `entry_images` isn't there.

However, is it possible to leave the reference to `entry_images` in place when pressing save? Even if the image isn't local? Perhaps only replace it when a new image is added or remove it if the image set template is removed.

Hope this makes sense.

### How to reproduce

- Exclude assets from git
- Add an image to production using an image set in bard
- Pull changes to local
- The local version of the site will show an empty image set template
- Make a change to the entry, press save
- The image reference will be removed from .md file

### Environment

```yaml
Application Name: Statamic
Laravel Version: 11.23.4
PHP Version: 8.3.8
Composer Version: 2.6.5
Environment: local
Debug Mode: OFF
URL: demo.test
Maintenance Mode: OFF
Timezone: Europe/London
Locale: en_GB

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: sqlite
Logs: stack / single
Mail: log
Queue: redis
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.25.0 PRO

Statamic Addons
jonassiewertsen/statamic-jobs: 1.5.0
```

### Installation

Fresh statamic/statamic site via CLI
