### ISSUE TITLE
Bard Field with antlers parsing outputs additional Paragraph Tags

### ISSUE THREAD

**Issue by Jubeki** [statamic/cms#10825]
### Bug description

If you use a globals with a Bard Field. And try to output it inside another Bard Field you get one additional paragraph tag before and after the globals output.

I would expect no additional tags before and after.

### How to reproduce

https://github.com/Jubeki/statamic-bug-antlers-and-bard
- User: `test@example.com`
- PW: `password`

Steps for setting up:
1. Setup a fresh Statamic Application
2. Add a Globals with a Bard Field and some content (Globals: `contact`, Bard Field: `details`)
3. Use a Bard Field on the Page Collection, enable Antlers parsing and output the global `{{ contact:details }}`
4. See on the homepage that before and after the global output are each one additional empty paragraph tag. (using the Dev Tools)

Changing the `Remove Empty Nodes` Option from `Don't remove empty nodes` to `Remove empty nodes at start and end` does not change the behaviour.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.23.5
PHP Version: 8.3.11
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: localhost:8000
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.25.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
