### ISSUE TITLE
Static cached pages contain broken HTML

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#10829]
### Bug description

This seems to happen again: https://github.com/statamic/cms/issues/7033. I've seen it on two projects now (both multisite). The first time I noticed it reappear was on September 16th, 2025. But of course, it could've been before that. 

The nasty thing about this issue is that you don't really have a way of knowing and it looks pretty bad.

Downgraded a project to 5.20 because I noticed some lock changes in 5.21 (#10607). Perhaps those a related. Just a guess though. 

<img width="1355" alt="370002635-30cc1d88-597e-4742-b73c-047f23a475a0" src="https://github.com/user-attachments/assets/0e4bab48-eadd-4814-be56-226617e1efd2">

![367690941-c8b2606b-f66c-4855-b72f-a58b0fdc10f3](https://github.com/user-attachments/assets/61cea8eb-b741-4355-9f58-6278bc5f39bf)

### How to reproduce

Wish I knew. Happy to share a repo though from the project where it happens.

### Environment

```yaml
Environment
Laravel Version: 11.23.4
PHP Version: 8.2.23
Composer Version: 2.7.9
Environment: staging
Debug Mode: OFF
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: en

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Livewire
Livewire: v3.5.6

Statamic
Addons: 7
Sites: 3 (English, Dutch, German)
Stache Watcher: Disabled (auto)
Static Caching: full
Version: 5.25.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.8.0
ryanmitchell/statamic-translation-manager: 2.0.0
stillat/relationships: 2.2.1
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.8.1
studio1902/statamic-peak-seo: 8.16.0
studio1902/statamic-peak-tools: 6.3.2
```

### Installation

Starter Kit using via CLI
