### ISSUE TITLE
view var inside partial leak to other partials

### ISSUE THREAD

**Issue by dadaxr** [statamic/cms#10835]
### Bug description

as mentioned in the title, the special "view" var avaible in partial  (which contains frontmatter values and "passed parameter" values) is leaking to other following partial ... which can be problematic (more on that later)

### How to reproduce

just create a template including 2 different partials : 

main template : 
```
{{ partial:test1 name="abc" fake="true" }}
{{ 'template'|dump }}
{{ view|dump }}
{{ partial:test2 id="123" }}

```

partial "test1" : 
```
---
name:
other: "default"
---
{{'test1'|dump}}
{{view|dump}}
```

partial "test2" : 
```
---
id:
---
{{'test2'|dump}}
{{view|dump}}

```

You should see the leak as pictured bellow : 
![image](https://github.com/user-attachments/assets/85f64e5b-2ef6-4e3f-8058-32bb5450808a)

As we can see, the leak only happens between partial but not with the main template.

Why fixing it is important ... if not only for my own mental health ?
It's because it can lead to weird behavior (I stumbled upon this issue while playing with the {{ nocache }} tag and it's "select" parameter ... I wanted the to do something like : {{ nocache select="view" }} but while inspecting the inner working... I discovered the polluted view var... ). it's also annoying while trying to loop over the "view" var inside a partial ... as it not only contains what it should 

I'm sure this one is for @JohnathonKoster ;)

### Environment

```yaml
Environment
Laravel Version: 10.48.22
PHP Version: 8.2.7
Composer Version: 2.6.2
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.25.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
