### ISSUE TITLE
Link Fieldtype does not enforce required on "First Child" option, if there is no first child

### ISSUE THREAD

**Issue by fighter3005** [statamic/cms#10834]
### Bug description

If I set the Link to UR, leave the field empty and try to save the collection, it triggers the required validation.
If I set the Link to First Child and save the collection, the collection is saved successfully and the link is null.
I assume this is not expected, since null is an "empty" value and required means not empty as per your documentation?

![image](https://github.com/user-attachments/assets/6413c167-1874-466b-a33e-8aac72ed8db7)

![image](https://github.com/user-attachments/assets/4be821f8-eaaa-4400-ac89-580ba0c987cb)

![Bildschirmfoto 2024-09-25 um 11 05 09](https://github.com/user-attachments/assets/fd5d0034-63ec-4b52-99e8-21ff40e5ae4c)

### How to reproduce

Use the Link Fieldtype in some Fieldset.
set the Link as required.
Put the link in the last collection at the end, so First Child is null.
save the collection and be surprised, it does not trigger the required validation.

### Environment

```yaml
"php": "^8",
    "eminos/statamic-tabs": "v1.2.0",
    "fuf/asset-glide-url": "*",
    "fuf/n8n-viewer": "*",
    "laravel/framework": "v11.23.5",
    "laravel/tinker": "v2.9.0",
    "statamic/cms": "v5.25.0",
    "thoughtco/statamic-restrict-fields": "v1.1.0"
```

### Installation

Fresh statamic/statamic site via CLI
