### ISSUE TITLE
Antlers: {{ collection:count }} not always working

### ISSUE THREAD

**Issue by AtmoFX** [statamic/cms#10830]
### Bug description

I have a case where, for an existing collection called "events"

 - `{{ collection:events as="entries" }}{{ entries | count }}{{ /collection:events }}` returns 2 (which is the correct number)
 - `{{ collection:count in="events" }}` returns nothing/null (not even 0)

To be precise, `{{ collection:count in="events" }}` works most of the time; the issue seems to occur in 1 very specific case, when a taxonomy is involved.

### How to reproduce

  1. Create a collection (which in my case was called "events" but I do not think this is a name that could send the interpreter haywire) + 1 published entry.
  2. Add `{{ collection:count in="events" }} vs {{ collection:events as="entries" }}{{ entries | count }}{{ /collection:events }}` e.g. in a navbar of the layout file.
  3. Create a taxonomy with some terms in it. For the report, I created something called `Test of taxonomies` (the slug was left to default value) with 1 term inside.
![image](https://github.com/user-attachments/assets/4bc4e05e-37b3-4478-bd1d-926d9fbd788f)
  Make it so the templates are set to some `index` and `show` antlers files like:
![image](https://github.com/user-attachments/assets/eb413d94-736e-451c-bac5-e9b0e7d1680a)
 4. The bug should now appear:
     1. The homepage should display `1 vs 1` (assuming the `events` collection only has 1 published entry).
     2. The 404 page should also display `1 vs 1`.
     3. The page at address `/test-of-taxonomies` should also display `1 vs 1`.
     4. The page at address `/test-of-taxonomies/test` should, in contrast, display the **incorrect** ` vs 1` (the first `1` is missing)
     5. In case you have a collection set to work with taxonomy entries (in my cases, I have one called `research` and `/research/test-of-taxonomies/term1` would be a valid URL), it has the **correct** behavior, i.e. displays `1 vs 1`

### Environment

```yaml
Environment
Application Name: Gaia ESG fintech platform
Laravel Version: 11.23.5
PHP Version: 8.3.11
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: gaia-hub.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.25.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Not enough of an expert to know if that will help but please have a screenshot from the debugbar, tab Antlers:
![image](https://github.com/user-attachments/assets/bdf792de-2684-4bda-8e87-d244063f977b)

Note that apparently no logs are written here (cleared storage/logs/laravel.log + restarted Laravel Herd + refreshed the page; the log file is empty after refreshing).
