### ISSUE TITLE
Handle

### ISSUE THREAD

**Issue by ahmeij** [statamic/cms#10857]
### Bug description

Create a nested fieldset with a prefix to prevent handle clashes, the frontend will complain on adding a conflicting handle to the fieldset tat imports the other fieldset.

### How to reproduce

1. Create a fieldset (lets name it `button`) with text field with handle `title`
2. Create a new fieldset (lets name it `block`)
3. In the `block` fieldset link the `button` fieldset, set the prefix to `button_`
4. Add a new text field to the `block` with handle `title`
5. Save the fieldset

An error appears: `A field with a handle of title already exists.` However wit the 'prefix' set there is no actual problem.

### Environment

```yaml
Environment
Application Name: Website
Laravel Version: 11.21.0
PHP Version: 8.3.12
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: website
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 2 (English, Nederlands)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.27.0 PRO

Statamic Addons
jacksleight/statamic-bonus-routes: 0.3.2
```

### Installation

Fresh statamic/statamic site via CLI
