### ISSUE TITLE
White square boxes when viewing jpeg file in Asset Manager

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#10852]
### Bug description

When viewing a jpg file in the asset manager while in dark mode, 2 white square boxes are displayed in the bottom right corner at any viewport size.

<img width="578" alt="Capture d’écran 2024-09-26 à 21 09 33" src="https://github.com/user-attachments/assets/f777f5d0-271f-4615-9926-e701b9ba7730">

One whitish square box is also visible while in Light mode:

<img width="413" alt="Capture d’écran 2024-09-26 à 21 34 49" src="https://github.com/user-attachments/assets/86458067-50c8-47d5-b5de-0abb1bc5a451">

### How to reproduce

Put your CP in Dark Mode
Go to Assets
Click on a jpg file

Or Put your CP in Light mode (or system mode)
Go to Assets
Click on a jpg file

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.20
PHP Version: 8.3.7
Composer Version: 2.6.5
Environment: local
Debug Mode: OFF
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.26.0 PRO

Statamic Addons
ebeauchamps/multi-taxonomies: 1.1.1
ryanmitchell/statamic-translation-manager: 1.6.0
```

### Installation

Fresh statamic/statamic site via CLI
