### ISSUE TITLE
Modifiers bard_items / raw | bard_items behavior with Antlers

### ISSUE THREAD

**Issue by AtmoFX** [statamic/cms#10862]
### Bug description

I was trying to customize the rendering of a bard field by processing the document's nodes 1 by 1. As per [the documentation](https://statamic.dev/modifiers/bard_items), the `bard_items` modifier "*converts any Bard data to a flat array of ProseMirror nodes and marks*". My idea was to browse through the nodes inside document structure as per [that other documentation](https://prosemirror.net/docs/ref/#model.Node).
The ultimate goal is to change the DOM compared to the default behavior of Statamic e.g. render images inside `<figure>` tags.

It is very possible this exercise is doomed from the start, as bard fields just work fine with native rendering; however, the only purpose I can fathom for the `bard_items` modifier is exactly what I am trying to do.

Hopefully, if nodes can be traversed in a sensible way, with recursivity, the feasibility of such approach would be demonstrated.
I have inferred from the documentation that recursivity, the same way it is done for NAVs (i.e. `{{ *recursive children* }}, may not work (that is why nodes are returned in a flat array) but TBH, I could not reach a point where I could test that very part.

The value I try to render is, for illustration, the below value from a bard field configured **without sets** (I will include what happens with sets below):
```
content:
  -
    type: heading
    attrs:
      level: 2
    content:
      -
        type: text
        text: Title
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Paragraph1 Line1'
      -
        type: hardBreak
      -
        type: text
        text: 'Paragraph1 Line 2'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Paragraph2 Line1'
      -
        type: hardBreak
      -
        type: text
        text: 'Paragraph2 Line 2'
---
```

I fail to get "*a flat array of ProseMirror nodes*" using the `bard_items` / `raw | bard_items` modifiers.
Also, I am getting an error in 1 situation.

### How to reproduce

Render the provided document with each of the following code snippets:

 - `{{ content }}` works to render the whole bard field at once.
 When the bard field is configured with sets, then `{{ content }}{{ text }}{{ content }}` works for the above document (but obviously would need some `{{ type }}` test to correctly render all possible other documents)
 - `{{ content | bard_items }}` fails with a type error:
    ```
    Illuminate\Support\Arr::isAssoc(): Argument #1 ($array) must be of type array, string given, called in C:\Users\fxavi\Herd\gaia-hub\vendor\statamic\cms\src\Support\Arr.php on line 323
    ```
    The complete code for that attempt is:
    ```
    {{ article_content = content | bard_items }}
    {{ article_content }}
    <p>[{{ type }} / {{ text }}]</p>
    {{ /article_content }}
    ```
    When the bard field is configured with sets, the above code renders something but as a single block. I actually do not see any difference between `{{ content }}` and `{{ content | bard_items }}` in that situation.
 - `{{ content | raw | bard_items }}` kind of works but completely breaks down the ProseMirror document structure.
 The code snippet here is very similar to the one above:
     ```
    {{ article_content = content | raw | bard_items }}
    {{ article_content }}
    <p>[{{ type }} / {{ text }}]</p>
    {{ /article_content }}
    ```
    The rendered page shows how the `heading` sub-node has no children; rather, the text `Title` is rendered in the next node. The same goes for the paragraphs for which the following `text`s and `hardBreak` are sibling nodes rather that children nodes.

It can be argued that `raw | bard_items` returns a flat array but it seems that `bard_items` alone does not do that, contrary to the documentation.
As per my tests, I do not think what is returned is ProseMirror nodes. A lot of the documented properties (`{{ type }}`, `{{ text }}`, `{{ attrs }}`, ...) are accessible but not all of them (properties related to nodes children: `{{ content }}`, `{{ childCount }}`, ... + a few more such as `nodeSize`).

### Environment

```yaml
Environment
Application Name: Gaia ESG fintech platform
Laravel Version: 11.23.5
PHP Version: 8.3.12
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: gaia-hub.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.27.0 Solo

Statamic Addons
alt-design/alt-seo: 1.2.1
```

### Installation

Fresh statamic/statamic site via CLI
