### ISSUE TITLE
Autoloading addon commands causes NotBootedException

### ISSUE THREAD

**Issue by heidkaemper** [statamic/cms#10873]
### Bug description

When trying to use (some) addons with Statamic 5.28.0 we get an NotBootedException. This is caused by the new autoload feature: https://github.com/statamic/cms/pull/9270

The problem may be that we're calling $this->getAddon() here:
https://github.com/statamic/cms/blob/4731d577a500f35959bc8bbd4701b67106b1e44d/src/Providers/AddonServiceProvider.php#L707

But $this->app->isBooted() isn't true yet, when commands are registered:
https://github.com/statamic/cms/blob/4731d577a500f35959bc8bbd4701b67106b1e44d/src/Providers/AddonServiceProvider.php#L638

An easy fix would be to disable autoload for commands. But maybe there is a smarter way.

### How to reproduce

1. Install Statamic v5.28.0
2. Try to install an addon that has commands, like Responsive Images:
https://statamic.com/addons/spatie/responsive-images

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.25.0
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.x-dev Solo

Statamic Addons
spatie/statamic-responsive-images: 5.0.1
```

### Installation

Fresh statamic/statamic site via CLI
