### ISSUE TITLE
z-index issue with replicator sets

### ISSUE THREAD

**Issue by RyanRoberts** [statamic/cms#10897]
### Bug description

This video should explain https://media.yep.digital/nsDn8FGR

It's just a CSS z-index issue that causes the cancel/apply nav area to position under the field set content.

### How to reproduce

Create a new replicator with sets and fields within the sets

### Environment

```yaml
Environment
Application Name: ***
Laravel Version: 11.26.0
PHP Version: 8.3.10
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: ***.ddev.site
Maintenance Mode: OFF
Timezone: Europe/London
Locale: en_GB

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mariadb
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.29.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.13.0
marcorieser/tailwind-merge-statamic: 1.1.0
statamic/seo-pro: 6.1.2
```

### Installation

Fresh statamic/statamic site via CLI
