### ISSUE TITLE
statamic new <site> incorrectly saves the superuser password

### ISSUE THREAD

**Issue by AtmoFX** [statamic/cms#10891]
### Bug description

The `statamic new <site name>` command may not save the superuser password correctly, resulting in the impossibility to connect with the password typed during the process, which makes it confusing.

### How to reproduce

 1. Run `statamic new <site name>` with a site name of your choosing. Make it so a superuser will be created in the process.
 2. When asked for the super user password, type anything that contains a `$`, for instance `123$456789`.
 3. Open the site and try to connect to the control panel. Using `123$456789` is not the correct password but `123` is.
 Apparently, `$` and everything to its right is ignored.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.26.0
PHP Version: 8.3.12
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: Test.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.29.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
