### ISSUE TITLE
Default values of global fields are not available in Antlers

### ISSUE THREAD

**Issue by aerni** [statamic/cms#10901]
### Bug description

I noticed that default field values of Globals are not augmented in Antlers.

I've got a `galleries_layout` field with a default value of `offset` in a `settings` global. The value hasn't been saved to file. So the `settings.yaml` global is empty. I'm expecting `{{ settings:galleries_layout }}` to output `offset`. 

This behavior works for default field values of entries. It just doesn't work for globals.

Note, that the default field value gets augmented correctly when accessing the field programmatically:

![CleanShot 2024-10-04 at 12 24 21@2x](https://github.com/user-attachments/assets/7bcf6e9a-dbfc-44e3-aa7a-ab59a47c7694)

### How to reproduce

1. Create a `settings` global
2. Use this blueprint:
```yaml
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: galleries_layout
            field:
              options:
                -
                  key: offset
                  value: Offset
                -
                  key: column
                  value: Column
              default: offset
              type: button_group
              display: 'Galleries Layout'
```

3. Add `{{ settings:galleries_layout }}` to your Antlers template
4. You would expect to see `offset` but don't see anything

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.26.0
PHP Version: 8.3.12
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: photography.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Livewire
Livewire: v3.5.9

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.30.0 Solo

Statamic Addons
aerni/zipper: 2.4.0
jacksleight/statamic-bard-texstyle: 3.3.0
jonassiewertsen/statamic-livewire: 3.8.1
spatie/statamic-responsive-images: 5.0.1
stillat/antlers-components: 2.3.0
```

### Installation

Fresh statamic/statamic site via CLI
