### ISSUE TITLE
`from` parameter doesn't work for `collection` tag in variable assignment

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/cms#10905]
### Bug description

Using the `from` parameter when assigning the result of a collection tag to a variable causes an error.

Assignment:
`{{ $my_variable = { collection from="my_collection" } }}`

Error:
`Modifier [from] not found`

The reason not to use `collection:my_collection` is so the collection name can be a variable `:from="collection_name"`

### How to reproduce

Use code above with a valid collection name

### Environment

```yaml
Environment
Laravel Version: 11.26.0
PHP Version: 8.2.24
Composer Version: 2.7.7

Statamic
Version: 5.30.0
```

### Installation

Fresh statamic/statamic site via CLI
