### ISSUE TITLE
Static cache redirection

### ISSUE THREAD

**Issue by artisanbarista** [statamic/cms#10907]
### Bug description

Static cache is set while redirecting.

### How to reproduce

Lets say i have 2 pages with `STATAMIC_STATIC_CACHING_STRATEGY=half`

https://www.test.com/party
https://www.test.com/eu/party

I have a middleware that in case u visit 
https://www.test.com/party from a european ip
it will redirect to 
https://www.test.com/eu/party

```
return redirect('/eu/party', 302, [
    'X-Redirected-By' => 'Party Redirecion',
    'X-Redirected-From' => '/party',
]);
```

Once this redirection is executed and user lands https://www.test.com/eu/party
there is a button in that page to say this is not available for european users and if you landed here by mistake to
click on a button to go to https://www.test.com/party?mistake=true

Unfortunattely this does not work correctly because statamic static cache allready cached https://www.test.com/eu/party while redirecting
and when the user clicks on the button to go to https://www.test.com/party?mistake=true it continue showing https://www.test.com/eu/party static cached page.

As a fix for this problem I have added this

```
if ($event->response->getStatusCode() === 302) {
    return;
}
```
https://github.com/statamic/cms/blob/3956ab1343eef8b20d89c5281160c05c63f279c0/src/StaticCaching/Cachers/ApplicationCacher.php#L51

```
        Event::listen(ResponsePrepared::class, function (ResponsePrepared $event) use ($key, $value) {
            $headers = collect($event->response->headers->all())
                ->reject(fn ($value, $key) => in_array($key, ['date', 'x-powered-by', 'cache-control', 'expires', 'set-cookie']))
                ->all();

              if ($event->response->getStatusCode() === 302) {
                  return;
              }

            $cacheValue = [
                'content' => $value,
                'headers' => $headers,
                'status' => $event->response->getStatusCode(),
            ];

            $this->getDefaultExpiration()
                ? $this->cache->put($key, $cacheValue, now()->addMinutes($this->getDefaultExpiration()))
                : $this->cache->forever($key, $cacheValue);
        });
```

to prevent any 302 code responses not to be statically cached and it works fine.

I am not sure if this is a bug from my code or statamic itself. but it should be nice if there was an option in the config to exclude certain html status codes from static cache via statamic/static_cache.php configuration.

### Environment

```yaml
Application Name: Party
Laravel Version: 10.48.22
PHP Version: 8.3.11
Composer Version: 2.7.9
Environment: local
Debug Mode: ENABLED
URL: party.com.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single, bugsnag
Mail: log
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 15 (English, Deutsch, 中文简体, and 12 more)
Stache Watcher: Disabled
Static Caching: half
Version: 5.25.0 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 3.0.0
jacksleight/statamic-bard-texstyle: 3.3.0
```

### Installation

Existing Laravel app
