### ISSUE TITLE
Button Group with integer keys doesn't display selected state in the CP

### ISSUE THREAD

**Issue by eminos** [statamic/cms#10915]
### Bug description

When using integers as keys in a Button Group fieldtype it doesn't show the selected state properly in the CP.

### How to reproduce

Have a Button Group fieldtype with simple integers (1, 2, 3) as keys.

### Environment

```yaml
Laravel Version: 11.26.0
PHP Version: 8.3.6
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
Are you able to provide the *full* output of `php please support:details`?

**Comment by eminos** [comment]
Sorry about that. I thought I provided the Statamic version at least, which I assume would be most important in this case, but I didn't. It's Statamic 5.30.0 (latest as of writing).

Anyway I see there's a PR now fixing this issue.

**Comment by andjsch** [comment]
Can confirm. I stumbled upon this a few days ago as well!

**Comment by andjsch** [comment]
for example this:
```yaml
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              width: 50
              localizable: false
              validate:
                - required
              display: Name
          -
            handle: stars
            field:
              options:
                -
                  key: 1
                  value: '1'
                -
                  key: 2
                  value: '2'
                -
                  key: 3
                  value: '3'
                -
                  key: 4
                  value: '4'
                -
                  key: 5
                  value: '5'
              default: s5
              type: button_group
              display: Sterne
              localizable: false
              width: 50
          -
            handle: quote
            field:
              type: textarea
              display: Quote
              localizable: true
          -
            handle: company
            field:
              type: text
              display: Firma
              localizable: false
              width: 50
              listable: true
              validate:
                - required
          -
            handle: position
            field:
              type: text
              display: Position
              localizable: true
              width: 50
title: Testimonial
```
