### ISSUE TITLE
Asset listing sort order has no effect on folders

### ISSUE THREAD

**Issue by daun** [statamic/cms#10919]
### Bug description

When sorting files in the asset listing, the selected sort order has no effect on folders, which are always sorted by name in ascending order. The files themselves are sorted correctly.

### How to reproduce

Create lots of folders. Try sorting by name and reversing sort order. They'll always be sorted in ascending order.

![Screen Recording 2024-10-08 at 22 01 31](https://github.com/user-attachments/assets/af355f92-108b-46db-b3ed-7cbd8f422fa2)

### Environment

```yaml
Environment
Application Name: *****
Laravel Version: 11.25.0
PHP Version: 8.3.3
Composer Version: 2.5.1
Environment: local
Debug Mode: OFF
URL: *****.test
Maintenance Mode: OFF
Timezone: Europe/Vienna
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: redis
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.30.0 PRO

Statamic Addons
daun/statamic-widget-collection-count: 1.2.1
doefom/currency-fieldtype: 1.4.1
jacksleight/statamic-bard-mutator: 3.0.0
jacksleight/statamic-bard-texstyle: 3.3.0
stillat/relationships: 2.2.1
```

### Installation

Fresh statamic/statamic site via CLI
