### ISSUE TITLE
Paginated local search returns incorrect total count

### ISSUE THREAD

**Issue by daun** [statamic/cms#10917]
### Bug description

When paginating a search using the `local` driver, the `total_results` variable doesn't contain the number of total results, but the number of results on the current page. I've stumbled upon [a comment by @jasonvarga](https://github.com/statamic/cms/pull/5812#issuecomment-1099239198) that suggests using `{{ paginate:total_items }}` for that, which works, but the `total_results` variable should still contain the correct value or be renamed to reflect its contents.

### How to reproduce

The following will display `2 Results` on the first page and `1 Result` when 3 products are found across 2 pages.

```antlers
{{ search:results index="products" paginate="2" as="results" }}

  <h1>{{ total_results }} Results</h1>

  {{ results }}
    <h2>{{ title }}</h2>
  {{ /results }}

  {{ paginate:auto_links }}

{{ /search:results }}
```

### Environment

```yaml
Environment
Application Name: ******
Laravel Version: 11.26.0
PHP Version: 8.3.4
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: ******.test
Maintenance Mode: OFF
Timezone: Europe/Vienna
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: database
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.30.0 PRO

Statamic Addons
daun/statamic-widget-collection-count: 1.2.1
doefom/currency-fieldtype: 1.4.1
jacksleight/statamic-bard-mutator: 3.0.1
jacksleight/statamic-bard-texstyle: 3.3.0
stillat/relationships: 2.2.1
```

### Installation

Fresh statamic/statamic site via CLI
