### ISSUE TITLE
SubmissionSaving and SubmissionCreated Event is not triggered

### ISSUE THREAD

**Issue by thomas4Bitcraft** [statamic/cms#10926]
### Bug description

I wanted to use the two Event Listeners, but they are not triggering. 

### How to reproduce

Here is the implementation:
```
class AppServiceProvider extends ServiceProvider
{

    protected $listen = [
        SubmissionSaving::class => [FormSaving::class],
        SubmissionCreated::class => [FormSubmission::class],
    ];
    ...
}
```

```
class FormSaving
{
    /**
     * @param SubmissionSaving $event
     * @return void
     */
    public function handle(SubmissionSaving $event)
    {
        dd("test");
     }
}
```

When I send a POST request to `http://<domain>/!/forms/<form_handle>` this is not triggered

### Environment

```yaml
Environment
Application Name: xxx
Laravel Version: 11.23.5
PHP Version: 8.2.7
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: xxx
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Sentry
Enabled: YES
Environment: local
Laravel SDK Version: 4.8.0
PHP SDK Version: 4.9.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 0%
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 4
Sites: 2 (DE, EN)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.30.0 PRO

Statamic Addons
bitcraft/form-webhook: dev-master
bitcraft/page-generator: dev-master
statamic/eloquent-driver: 4.14.3
stillat/relationships: 2.2.1

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```

### Installation

Fresh statamic/statamic site via CLI
