### ISSUE TITLE
Browser history navigation doesn't work in asset browser

### ISSUE THREAD

**Issue by daun** [statamic/cms#10920]
### Bug description

When using the back button inside the asset browser to return to the previous folder, nothing happens. There's a loading spinner and the url changes to the previous folder url, but then it shows the same folder I was just at. Going forward or backward has no effect here.

### How to reproduce

Open the asset browser, create a folder, double-click it, then click the browser back button.

![Screen Recording 2024-10-08 at 22 24 08](https://github.com/user-attachments/assets/42fa2db4-d5d2-4b6c-ad2c-99ef4340af3e)

### Environment

```yaml
Environment
Application Name: *****
Laravel Version: 11.25.0
PHP Version: 8.3.3
Composer Version: 2.5.1
Environment: local
Debug Mode: OFF
URL: *****.test
Maintenance Mode: OFF
Timezone: Europe/Vienna
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: redis
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.30.0 PRO

Statamic Addons
daun/statamic-widget-collection-count: 1.2.1
doefom/currency-fieldtype: 1.4.1
jacksleight/statamic-bard-mutator: 3.0.0
jacksleight/statamic-bard-texstyle: 3.3.0
stillat/relationships: 2.2.1
```

### Installation

Fresh statamic/statamic site via CLI
