### ISSUE TITLE
Unable to validate dynamic assets field

### ISSUE THREAD

**Issue by aerni** [statamic/cms#10925]
### Bug description

If you use the dynamic assets folder feature with the option set to `id` you won't be able to make the field required. Because you can't add images to a folder that doesn't exist yet.

![CleanShot 2024-10-09 at 14 30 06@2x](https://github.com/user-attachments/assets/73a97398-aca6-4896-b389-283b7385e353)

### How to reproduce

Add this field to your blueprint and try saving the entry:

```yaml
handle: assets
field:
  container: assets
  type: assets
  dynamic: id
  validate:
    - required
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.27.2
PHP Version: 8.3.12
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: photography.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Livewire
Livewire: v3.5.9

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.30.0 Solo

Statamic Addons
aerni/zipper: 2.4.0
jacksleight/statamic-bard-texstyle: 3.3.0
jonassiewertsen/statamic-livewire: 3.8.1
spatie/statamic-responsive-images: 5.0.1
stillat/antlers-components: 2.3.0
```

### Installation

Fresh statamic/statamic site via CLI
