### ISSUE TITLE
Can't browser subfolders when using dynamic folders

### ISSUE THREAD

**Issue by aerni** [statamic/cms#10934]
### Bug description

When using the dynamic folder feature, you are unable to select assets from subfolders. In the example below, I'm expecting to be able to see and navigate the `subfolder` as well. Related to https://github.com/statamic/cms/issues/10904.

**Dynamic folder**

![CleanShot 2024-10-10 at 11 03 10@2x](https://github.com/user-attachments/assets/583a1145-a9b1-4f76-b576-aff06e8de8bf)

**When browsing in the asset fieldtype**

![CleanShot 2024-10-10 at 11 03 33@2x](https://github.com/user-attachments/assets/0868499d-297b-4265-a916-a62cc85d0410)

### How to reproduce

Add this field to your blueprint:

```yaml
handle: assets
field:
  container: assets
  type: assets
  dynamic: id
```

Then create a subfolder in the generated dynamic folder and try browsing it in the fieldtype.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.27.2
PHP Version: 8.3.12
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: starter-kit-photography-dev.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Livewire
Livewire: v3.5.9

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.30.0 Solo

Statamic Addons
aerni/zipper: 2.4.0
jacksleight/statamic-bard-texstyle: 3.3.0
jonassiewertsen/statamic-livewire: 3.8.1
spatie/statamic-responsive-images: 5.0.1
stillat/antlers-components: 2.3.0
```

### Installation

Fresh statamic/statamic site via CLI
