### ISSUE TITLE
Updating term slug creates duplicate instead of updating

### ISSUE THREAD

**Issue by daun** [statamic/cms#10938]
### Bug description

When the stache watcher is disabled, updating a term slug in the control panel creates a duplicate of the term instead of updating the term's slug. Looking at the content folder, the file is correctly renamed, but the control panel shows both the previous as well as the new version of the term.

There's a [workaround](https://github.com/statamic/cms/issues/5449#issuecomment-1396916959) — clearing the stache from an event listener after each term save — but that probably shouldn't be necessary. There's a related PR #9260 but since that marked the issue as solved, I figured this might be something else and opened a new issue.

With stache watcher **disabled**

![Screen Recording 2024-10-11 at 13 16 55](https://github.com/user-attachments/assets/5918d224-03ce-4ca3-866e-0f3fe6978142)

With stache watcher **enabled**

![Screen Recording 2024-10-11 at 13 19 31](https://github.com/user-attachments/assets/2f335b64-b1a0-4e06-865b-5a587a1f2356)

### How to reproduce

- Disable stache watcher
- Create a taxonomy
- Create a term and save
- Edit the term, update the slug, and save
- Return to listing

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.22
PHP Version: 8.3.3
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 2 (DE, EN)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.30.0 PRO

Statamic Addons
daun/statamic-widget-collection-count: 1.2.1
```

### Installation

Fresh statamic/statamic site via CLI
