### ISSUE TITLE
Static cache files include IP address instead of `APP_URL`

### ISSUE THREAD

**Issue by marijoo** [statamic/cms#10932]
### Bug description

I have a site with full measure caching where – since a few days – statically cached html files include asset urls with the server IP (and http~s~ protocol) instead of the app url. Something like:

```html
<link rel="modulepreload" href="http://123.123.123.123/build/assets/_commonjsHelpers-Cpj98o6Y.js" />
```

Instead of what I expect and what’s included in most of the html files:

```html
<link rel="modulepreload" href="https://website.com/build/assets/_commonjsHelpers-Cpj98o6Y.js" />
```

This doesn’t happen on all urls and I’m not even sure if it’s happening when the site is regenerated after being cleared after a content change or if it’s happening by running `php please static:warm` which is done automatically on the server daily.

Maybe this is related to the following PR? This would fit since it’s happening since a week or so.

Any ideas?

### How to reproduce

Rather hard, I wasn’t able to reliably reproduce this. 

### Environment

```yaml
Environment
Application Name: App
Laravel Version: 11.27.2
PHP Version: 8.3.12
Composer Version: 2.5.4
Environment: production
Debug Mode: OFF
URL: website.com
Maintenance Mode: OFF
Timezone: Europe/Berlin
Locale: de

Cache
Config: CACHED
Events: CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Locales
Installed: de, en
LaravelLang\Attributes\Plugin: 2.11.1
LaravelLang\Lang\Plugin: 15.8.1
Locales Version: 2.9.2
Protected: de, en
Publisher Version: 16.4.0

Statamic
Addons: 1
Sites: 2 (Deutsch, English)
Stache Watcher: Disabled
Static Caching: full
Version: 5.30.0 PRO

Statamic Addons
aryehraber/statamic-color-extractor: 1.5.0
```

### Installation

Fresh statamic/statamic site via CLI
