### ISSUE TITLE
Navigation fields synced with origin when no origin is present

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#10930]
### Bug description

When you add fields to navigation blueprint, all field by default are synced with their origin. Even when no origin is present and the field _only_ exists on the navigation blueprint.
<img width="417" alt="Screenshot 2024-10-10 at 13 10 49" src="https://github.com/user-attachments/assets/9b31d3d2-cc85-4064-9f99-16e4a5a2579f">

It's worth noting that it does work as expected. You can edit the field and it get's de-linked. It seems like just a UI issue. 

### How to reproduce

1. Add a unique field to a nav that doesn't exist on the entries blueprint
2. Open the nav entry edit stack
3. See the field greyed out and saying it's synced with its (non existent) origin

### Environment

```yaml
Environment
Laravel Version: 11.26.0
PHP Version: 8.2.24
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.30.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.9.0
studio1902/statamic-peak-seo: 8.16.0
```

### Installation

Starter Kit using via CLI
