### ISSUE TITLE
Issue with dynamic assets folder and renaming

### ISSUE THREAD

**Issue by aerni** [statamic/cms#10943]
### Bug description

I ran into an issue with dynamic assets folder and the rename folder feature. 

Renaming a folder works as expected. However, if you later remove all the assets from the fieldtype, the folder name will be reset to whatever was set in the fieldtype config, like `id` or `slug`. The fieldtype doesn't retain the name of the previously renamed folder. This leads to previously uplouded assets not being selectable anymore.

**Quick demo**

https://github.com/user-attachments/assets/dcbacb1a-2966-4cd0-88c1-05896237bbee

### How to reproduce

1. Add this field to your blueprint:

```yaml
handle: assets
field:
  container: assets
  type: assets
  dynamic: id
```

2. Upload some assets
3. Rename the folder
4. Remove the assets from the fieldtype
5. Try selecting previously uploaded assets

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.27.2
PHP Version: 8.3.12
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: photography.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Livewire
Livewire: v3.5.9

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.30.0 Solo

Statamic Addons
aerni/zipper: 2.4.0
jacksleight/statamic-bard-texstyle: 3.3.0
jonassiewertsen/statamic-livewire: 3.8.1
spatie/statamic-responsive-images: 5.0.1
stillat/antlers-components: 2.3.0
```

### Installation

Fresh statamic/statamic site via CLI
