### ISSUE TITLE
Editing an asset metadata leaves you in an `edit` subfolder

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#10957]
### Bug description

When you edit in asset (alt text) and hit save you end in a weird edit folder.

Step 1:
<img width="1056" alt="Screenshot 2024-10-15 at 13 14 17" src="https://github.com/user-attachments/assets/047355a4-fa31-4247-9808-d2fdf5a80bea">

Step 2:
<img width="1295" alt="Screenshot 2024-10-15 at 13 14 26" src="https://github.com/user-attachments/assets/e3479b45-7149-418b-add0-1fe98196eab6">

Step 3:
<img width="1043" alt="Screenshot 2024-10-15 at 13 14 31" src="https://github.com/user-attachments/assets/f2d7ddc1-234f-4f90-a3f8-41411af8329d">

### How to reproduce

1. Edit asset
2. Hit save

### Environment

```yaml
Environment
Laravel Version: 11.27.2
PHP Version: 8.2.24
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 3 (English, Dutch, German)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.31.0 PRO

Statamic Addons
stillat/relationships: 2.2.1
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.9.0
studio1902/statamic-peak-seo: 8.16.0
studio1902/statamic-peak-tools: 6.3.3
```

### Installation

Starter Kit using via CLI
