### ISSUE TITLE
Taxonomy term template is ALWAYS prefixed with the collection_handle when mounted to page (and, is that right?)

### ISSUE THREAD

**Issue by jeroenimpres** [statamic/cms#10953]
### Bug description

I have:
 * a collection called FAQ
 * a page 'Veelgestelde vragen' with slug 'veelgestelde-vragen'
 * the collection FAQ is mounted onto the entry/page with slug 'veelgestelde-vragen'
 * the collection has a taxonomy called 'faq_categorie'
 * the taxonomy term has its own template which I chose from my the UI (i.e.: `my/own/folder/show`)
 * i have a term with slug 'algmeen'

Statamic allows us to go to https://example.com/veelgestelde-vragen/faq-categorie/algemeen which should show my template `my/own/folder/show`.

However.. I see in the [LocalizedTerm.php:381](https://github.com/statamic/cms/blob/ef4f7d73aead508b521280924d785d30da4acafd/src/Taxonomies/LocalizedTerm.php#L381) that the template is *ALWAYS* prefixed with the collection handle and a dot. 

To me, this isn't a logical decision as the value in the yaml file of the taxonmy isn't honoured (it's prefixed) and also in the Statamic UI where you edit the Taxonomy there isn't a warning about this. Also the dropdown where you can select a template isn't filtering to only begin with the collection handle (which in my case is 'faq'), instead you see every file in the 'views' directory.

I can understand the prefixing of the template path if it was derived from a default value (when not specified in the taxonomy YAML). But when it's explicitly speciried there, I assume it should be honored. 

Bonus: What made this more hard to find for me is that a PageNotFound was raised, so for a while I thoght my routing was messed up or there was something cached that was wrong..

### How to reproduce

* create a page 'Veelgestelde vragen' with slug 'veelgestelde-vragen'
* create a collection called FAQ
* mount in to the entry called 'Veelgestelde vragen'
* create a taxonomy called 'faq_categorie'
* create folder in your views caled 'mooi'
* create a template file in that folder called 'henk'
* edit your taxonomy and assign 'mooi/henk' to the term template
* create a term called 'algemeen'
* create an entry in the FAQ, assign the taxonomy
* go to https://example.com/veelgestelde-vragen/faq-categorie/algemeen and you will find a 404
* create a folder 'faq' in your views (if its not there already)
* move the folder 'mooi' into the FAQ
* now it should work

### Environment

```yaml
Environment
Application Name: Stadspassen
Laravel Version: 11.27.2
PHP Version: 8.3.2-1+0~20240120.16+debian11~1.gbpb43448
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: stadspas.ddev.site
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: nl

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.9

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.19.0 PRO

Statamic Addons
aerni/factory: 1.5.1
jonassiewertsen/statamic-livewire: 3.8.1
statamic-rad-pack/meilisearch: 3.3.0
```

### Installation

Starter Kit using via CLI
