### ISSUE TITLE
`Blueprint::ensureFieldHasConfig` doesn't work as expected when modifying imported fields

### ISSUE THREAD

**Issue by conallcoda** [statamic/cms#10965]
### Bug description

I am trying to modify the visibility of a field on the fly using a UserBlueprintFound event listener. Unfortunately it does not work as internally the field cannot be found.

### How to reproduce

1. Create new fresh installation via CLI "statamic new example"
2. Enable pro mode
3. Create the following fieldset:

resources/fieldsets/custom_fieldset.yaml
```
title: custom_fieldset
fields:
  - handle: a_custom_field
    field:
      type: text
      display: "A Custom Field"
      visibility: hidden
```

4. Import the fieldset to your user blueprint:

resources/blueprints/user.yaml
```
title: User
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: name
            field:
              type: text
              display: Name
          -
            handle: email
            field:
              type: text
              input_type: email
              display: 'Email Address'
              listable: true
              input: email
          -
            handle: roles
            field:
              type: user_roles
              mode: select
              width: 50
              listable: true
              filterable: false
          -
            handle: groups
            field:
              type: user_groups
              mode: select
              width: 50
              listable: true
              filterable: false
          -
            handle: avatar
            field:
              type: assets
              max_files: 1
              container: assets
          -
            import: custom_fieldset

```

5. Add event listener that adapts field config:

/app/Listeners/ModifyUserBlueprint.php
```
<?php

namespace App\Listeners;


use Statamic\Events\UserBlueprintFound;

class ModifyUserBlueprint
{
    public function handle(UserBlueprintFound $event)
    {
        $blueprint = $event->blueprint;
        if ($blueprint->hasField('a_custom_field')) {
            $blueprint->ensureFieldHasConfig('a_custom_field', ['visiblity' => 'visible']);
        }
    }
}

```

6. Try and create a user in the control panel and get the following error message:

![image](https://github.com/user-attachments/assets/655faff7-cd2c-4690-8972-fc5eb02d4247)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.28.0
PHP Version: 8.3.1
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: example.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.31.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
