### ISSUE TITLE
Updates badge sometimes incorrect

### ISSUE THREAD

**Issue by RyanRoberts** [statamic/cms#10970]
### Bug description

Statamic shows an update badge when all adding are up to date. In this case SEO Pro.

![Google Chrome - 2024-10-17--14-09-44@2x](https://github.com/user-attachments/assets/058ece08-38ad-4392-a795-b5b956d779b5)

### How to reproduce

In this case I updated SEO Pro via `composer update`, prior to running that command the badge wasn't showing.

### Environment

```yaml
Environment
Application Name: Site
Laravel Version: 11.28.1
PHP Version: 8.3.12
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: site.test
Maintenance Mode: OFF
Timezone: Europe/London
Locale: en_GB

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mariadb
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.31.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.13.0
marcorieser/tailwind-merge-statamic: 1.1.0
statamic-rad-pack/mailchimp: 5.2.2
statamic-rad-pack/shopify: 4.0.4
statamic/seo-pro: 6.3.0
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

SEO Pro on the marketplace and GitHub have the same version as shown in the Statamic Updates page.

I've cleared caches and everything else I can think of.
