### ISSUE TITLE
Translate default dictionaries

### ISSUE THREAD

**Issue by andjsch** [statamic/cms#10972]
### Bug description

Currently, if you view the CP in another language and use one of the predefined dictionaries, the labels are not translated. I think translating Countries and Currencies would be sufficient enough.

If this is something that would be considered for a merge, I'd be happy to provide a PR.

For the PR, it should be considered where to put the translations.
- Either within the ``{lang}.json`` file, which would be convenient, but messy
- Within a ``dictionaries.php`` file where the translated dictionaries are within an array
  - Countries -> ``countries.{iso2}``
  - Currencies -> ``currencies.{code}``

### How to reproduce

Create a dictionary fieldtype within come blueprint and change the language to anything !English.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.28.1
PHP Version: 8.3.12
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.31.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
