### ISSUE TITLE
Asset edit dialog messes up folder view.

### ISSUE THREAD

**Issue by janoschdigg** [statamic/cms#10974]
### Bug description

When you open an asset and then click on save the url in the browser stays on the edit dialog url. In my case: http://test.test/cp/assets/browse/assets/testfile.mp4/edit
in the file view it looks like you are in the folder testfile.mp4 and edit.

See the process in the attached video:

https://github.com/user-attachments/assets/a63f7307-8670-4133-8b4e-3cb29fb2d5b3

### How to reproduce

- Create Statamic project
- Upload asset
- click on filename
- click "save" or "cancel"

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.28.1
PHP Version: 8.3.12
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: Test.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.31.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
