### ISSUE TITLE
Error on update page after updating to version 5.32.0

### ISSUE THREAD

**Issue by payrequestio** [statamic/cms#10979]
### Bug description

After I updated everything works fine but on the update page I get:
`Call to a member function versionLimit() on null 
`

UPDATE: after some minutes the error was gone, maybe update was still going in the background or caching?

### How to reproduce

1. Update to latest version
2. Visit /cp/updater
3. you see error:   Call to a member function versionLimit() on null 
4.  after some minutes the error was gone, maybe update was still going in the background or caching?

### Logs

```shell
Controller Statamic\Http\Controllers\CP\Updater\UpdaterController@index
Route name statamic.cp.updater
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.28.1
PHP Version: 8.3.6
Composer Version: 2.7.2
Environment: local
Debug Mode: ENABLED
URL: openstartup.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.32.0 Solo

Statamic Addons
eminos/statamic-iconify: 1.3.0
pecotamic/sitemap: 1.4.7
webographen/statamic-widget-cache-controller: 1.1.1
webographen/statamic-widget-continue-editing: 1.3.2
```

### Installation

Fresh statamic/statamic site via CLI
