### ISSUE TITLE
Synced multisite relations not filterable within the content API 

### ISSUE THREAD

**Issue by maartenvanhunsel** [statamic/cms#10983]
### Bug description

Context: We do have a multisite with 3 languages and use the Content API for date fetching. 
Our collection with +350 entries with the name `brands` uses a relational (entry) field. Every brand does have 1 designer, so because of that we linked the `brands` collection with the `designers` collection. Regardless the language, the designer is always the same. Because of that the field is not translatable.

When accessing the API (api/collections/brands/{uuid}) it looks all good, Statamic shows the translated entry ID of the right language. However when filtering the brands based on the brand ID results in zero items. The only language which works is the origin language. (/api/collections/brands/entries?filter[designer]{uuid}

*when changing the field to `translatable` and desync the designer field and re-attach it. It works. But in that case we need to change +350 entries which is not the expected behaviour.

### How to reproduce

**Statamic**
1. create multi-site (EN - NL)
2. create 2 collections: `brands` + `designers`
3. add an entry field with `limit 1` inside the brands collection to link designers (not translatable field)
4. Create multiple entries and link relations
5. Create new entries based on the origin and keep the designer in sync with the origin.

**API**
1. Fetch the current entry: `api/collections/brands/entries/5ec35aa6-e4db-4873-9ad2-9e60db5cc46d`.
2. Copy the designer ID
3.  Fetch all brands based on the designer ID `api/collections/brands/entries?fields=title,url,designer&filter[designer]=4dc99c18-cf52-4bb7-8111-8cb24ed55e36?site=nl`

*important: site should not be the origin site.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.22
PHP Version: 8.2.24
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: cms.borek.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 3 (Nederlands, English, Deutsch)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.32.0 PRO

Statamic Addons
aerni/advanced-seo: 2.9.1
appswithlove/statamic-one-click-content-translation: 5.2.3
rias/statamic-redirect: 3.8.1
```

### Installation

Fresh statamic/statamic site via CLI
