### ISSUE TITLE
Form submissions stored on server when disabled but form contains file upload

### ISSUE THREAD

**Issue by palmersoft-uk** [statamic/cms#10987]
### Bug description

I have a form, where I have set Store Permissions to false, here is the form yaml file

```
title: 'Register with Name Redacted'
email:
  -
    id: m0i6h4jx
    to: email@redacted.co.uk
    subject: 'Name Redacted - Candidate Registration'
    attachments: true
    html: mail/candidate/registration
    markdown: true
store: false
```

There is a file upload field on the form

```
      -
        display: CV
        fields:
          -
            handle: current_cv
            field:
              max_files: 1
              type: files
              display: 'Upload your current C.V.'
              instructions: 'Upload either a .doc, .docx, or .pdf file'
              validate:
                - required
```

If someone submits the form then it is storing the submission on the server - Interestingly, it is not storing the file on the server. 

If I remove the file field, then the submissions are not saved to the server, as expected.

![Screenshot 2024-10-20 at 10 46 01](https://github.com/user-attachments/assets/86421db5-032a-48ae-ad1c-5615d764910a)

### How to reproduce

Fresh statamic install

Add a form with a file upload field and ensure that the 'Store Submissions' option is not enabled.

Display the form on the front end and then submit it.

You should see that the submission is stored on the server.

Form yaml attached if it will help.
[register_with_acr.yaml.txt](https://github.com/user-attachments/files/17465429/register_with_acr.yaml.txt)

### Environment

```yaml
Environment
Application Name: Anne Corder Recruitment
Laravel Version: 11.25.0
PHP Version: 8.2.23
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: annecorder.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.32.0 PRO

Statamic Addons
aerni/font-awesome: 3.0.1
aryehraber/statamic-captcha: 1.13.0
ndx/statamic-bard-color-picker: 2.0.0
```

### Installation

Fresh statamic/statamic site via CLI
