### ISSUE TITLE
Scheduled entries don't display in a listing until a minute after the publish time

### ISSUE THREAD

**Issue by aaronbushnell** [statamic/cms#10994]
### Bug description

Looks like this was a conscious decision in #10966, but if I'm displaying a collection of "blog posts" in a list and have a publish date of 8:00 AM the new entry won't show up in that listing until 8:01 AM. I was hoping that the time the entry is published both the detail page _and_ areas where it is listed would show that post.

### How to reproduce

1. Create a blog detail and listing page
2. Enable full static caching
3. Schedule a new blog post 1 minute from your current time
4. Wait one minute and run `php artisan schedule:run`
5. Refresh the detail page and you'll see the post is available
6. Refresh the listing page and the post is not visible
7. Wait another minute and run `php artisan schedule:run` again
8. The post is now visible on listing view

### Environment

```yaml
Environment
Application Name: Statamic Starter
Laravel Version: 11.29.0
PHP Version: 8.3.12
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: statamic-starter.test
Maintenance Mode: OFF
Timezone: America/Indiana/Indianapolis
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 8
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: full
Version: 5.33.0 PRO

Statamic Addons
rias/statamic-redirect: 3.8.1
statamic/seo-pro: 6.3.0
trendyminds/guide: dev-main
trendyminds/link: dev-main
trendyminds/nerf: 1.2.0
trendyminds/orbit-statamic: 2.0.0
trendyminds/statamic-palette: 1.2.1
trendyminds/tip: 1.0.0
```

### Installation

Other (please explain)

### Additional details

Using a starter kit we built as a GitHub templated repo and cloned
