### ISSUE TITLE
Color Fieldtype: Collapsed state shows plain HTML 

### ISSUE THREAD

**Issue by JorisOrangeStudio** [statamic/cms#10991]
### Bug description

When the color field is used inside a Replicator and collapsed it shows plain html for the Fieldtype index like this:

![image](https://github.com/user-attachments/assets/7a568a54-b6f8-4aaa-b27c-35dfdc4e5e97)

### How to reproduce

Add a color field to a replicator. Above's screenshot is a nested replicator (so replicator inside a replicator) that uses a color field with pre-defined swatches to choose from. 

### Environment

```yaml
Environment
Application Name: Local
Laravel Version: 10.48.22
PHP Version: 8.3.7
Composer Version: 2.5.5
Environment: staging
Debug Mode: ENABLED
URL: localhost/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Cache: file
Database: mysql
Logs: stack / single
Mail: mailgun
Queue: sync
Session: file

Statamic
Addons: 6
Sites: 3 (Dutch, English, German)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.29.0 PRO

Statamic Addons
aerni/advanced-seo: 2.9.1
heidkaemper/statamic-toolbar: 1.2.1
jacksleight/statamic-bard-texstyle: 3.3.0
mattrothenberg/statamic-mapbox-address: 0.9.0
mitydigital/statamic-logger: 2.3.0
statamic/collaboration: 1.0.0
```

### Installation

Existing Laravel app
