### ISSUE TITLE
Image field in asset (blueprint) does not open the image but breaks the flow

### ISSUE THREAD

**Issue by jivanrij** [statamic/cms#11007]
### Bug description

In Statamic, I've created a separate asset container specifically for video files. Each video asset includes a field for attaching a preview image, allowing visitors to see a thumbnail before clicking play. However, there's an issue when attempting to edit this preview image within the asset editing interface.

### How to reproduce

When editing a video asset, the preview image appears correctly in the side panel. Normally, this panel would allow me not only to replace or upload a new image but also to edit it (e.g., adjust the focal point). However, when I try to interact with the image in any way that should open the editing options, the image simply disappears from view instead of opening the editing interface.

This is the asset's yaml:

```
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: image
            field:
              instructions: 'Show this image as a preview for the video.'
              max_files: 1
              min_files: 1
              container: assets
              type: assets
              display: Afbeelding
              localizable: false
              validate:
                - required
```

### Logs

```shell
No log's on the server side of things.

I do get some JS errors, but don't think those are the cause because I get them after the page reloads after the click. I've added a screenshot in the additional details field.
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.15.0
PHP Version: 8.2.24
Composer Version: 2.7.9
Environment: local
Debug Mode: ENABLED
URL: d-backoffice.blijnder.nl
Maintenance Mode: OFF
Timezone: UTC
Locale: nl

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / daily, slack
Mail: postmark
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.14.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

https://github.com/user-attachments/assets/295986f1-2827-44af-8225-af6bfd2599e6

![Screenshot 2024-10-25 at 08 51 56](https://github.com/user-attachments/assets/ec8713b5-a7a1-4565-bbf5-f6cf22e918d0)
