### ISSUE TITLE
Dictionary tag breaks when custom option is not set

### ISSUE THREAD

**Issue by bynicolas** [statamic/cms#11004]
### Bug description

The new dictionary antler tag introduced in v5.31.0 (#10885) throws a not found exception when a custom option is not set.

I have added a custom `multiple` toggle option to my dictionary. When the option is not set, the page with the form using that dictionary throws a not found exception.

### How to reproduce

in the dictionary definition class, add a custom field option item:

```php
protected function fieldItems()
{
    return [
        'multiple' => [
            'type' => 'toggle',
            'value' => false,
            'instructions' => 'Allow multiple selections.'
        ]
    ];
}
```

Use the dictionary tag in your form field. I use a form partial defined in `resources/views/partials/forms/fields/dictionary.antlers.html` dynamically rendered in my form template.

```antlers
<select name="{{ handle }}{{ dictionary:multiple ?= " []" }}"  ...>
...
</select>
```

If multiple is not define because the toggle option on the form field is set to disabled, then the exception is thrown

### Environment

```yaml
Environment
Application Name: Dev site
Laravel Version: 11.28.1
PHP Version: 8.3.12
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: cliniqueia.test
Maintenance Mode: OFF
Timezone: America/Toronto
Locale: fr_CA

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 2 (Dev site - en)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.31.0 PRO

Statamic Addons
alt-design/alt-redirect: 1.3.2
bynicolas/ignite-seo: dev-main
```

### Installation

Fresh statamic/statamic site via CLI
