### ISSUE TITLE
Smartypants not converting double quotes

### ISSUE THREAD

**Issue by efc** [statamic/cms#11013]
### Bug description

My Markdown content field has double quote marks in it, but they are not turned into curly quotes by smartypants. 

### How to reproduce

Put this text into a page's content...

    I'm wondering 'how' well "smartypants" works--is it here... or not?

Then include this in the layout...

    {{ content | smartypants }}

I find that the output is...

    <p>I’m wondering ‘how’ well "smartypants" works—is it here… or not?</p>

Notice that the double quotes around "smartypants" are rendered as straight quotes. It does the right thing with the single quotes, just not with the double quotes.

How can I get smartypants to curl the quotes?

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.27.2
PHP Version: 8.3.12
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: test.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.34.0 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.3.0
rias/statamic-redirect: 3.8.1
statamic/ssg: 3.0.2
```

### Installation

Fresh statamic/statamic site via CLI
