### ISSUE TITLE
Typeahead field shows duplicate terms and corrupts data on save

### ISSUE THREAD

**Issue by daun** [statamic/cms#11019]
### Bug description

I'm seeing an issue where the terms field shows terms twice, allows selecting both and will submit both, leading to possibly corrupt data when deleting one of the duplicates. This only seems to happen for the `typeahead` field.

The real issue seems to happen when selecting both of the duplicates, then removing one of them, and saving. The data is now indexed numerically, but skips an index. The term field refuses to show any data afterwards. See screenshots below.

The examples below are showing a `terms` field in `select` mode with three existing terms A, B, and C.

```yaml
-
  handle: tags
  field:
    mode: select
    taxonomies:
      - tags
    type: terms
    display: Tags
```

## Duplicate options

<img width="540" alt="Screenshot 2024-10-27 at 23 14 25" src="https://github.com/user-attachments/assets/6e253545-48ea-4b02-bc68-d8b508138f40">

## Duplicate selection

<img width="520" alt="Screenshot 2024-10-27 at 23 14 32" src="https://github.com/user-attachments/assets/050f8470-edab-4210-97d5-ed0553229636">

## Duplicate submission payload

<img width="212" alt="Screenshot 2024-10-27 at 23 14 53" src="https://github.com/user-attachments/assets/e01b6709-3603-4dcc-b705-bbd28f7c2587">

## Corrupt data when submitting with one duplicate deleted

<img width="294" alt="Screenshot 2024-10-27 at 23 15 33" src="https://github.com/user-attachments/assets/1b9ed046-3bcb-4a21-86d6-13247e38fb76">

## Broken input after submitting with one duplicate deleted

<img width="421" alt="Screenshot 2024-10-27 at 23 15 27" src="https://github.com/user-attachments/assets/a46309eb-c994-4d84-b82a-0ccf562c5300">

### How to reproduce

- Install from cli
- Create taxonomy `tags`
- Add `terms` field to `pages` collection, limited to `tags` taxonomy, with `typeahead` input
- Create new terms `A`, `B`, and `C`
- Edit page from collection
- Enter `A` into term field
- `A` should appear twice, and should be selectable twice
- Select and add both available `A` options
- Select and add both available `B` options
- Remove the first one of each
- Save
- Reload

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.29.0
PHP Version: 8.3.3
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: statamic-terms-test.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.34.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
