### ISSUE TITLE
Error when updating from 5.32 to 5.33

### ISSUE THREAD

**Issue by tenmillionteeth** [statamic/cms#11012]
### Bug description

We tried updating several sites to 5.33 from 5.32, and consistently get the following error: 

```
   Error

  Call to undefined method ReflectionUnionType::getName()

  at vendor/statamic/cms/src/Providers/AddonServiceProvider.php:240
    236▕                 ) {
    237▕                     return [];
    238▕                 }
    239▕
  ➜ 240▕                 $event = $reflection->getMethod('handle')->getParameters()[0]->getType()->getName();
    241▕
    242▕                 return [$event => $class];
    243▕             })
    244▕             ->filter()

      +12 vendor frames

  13  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

All sites are using multi-site. 

### How to reproduce

Update from 5.32 to 5.33 via command line. 

### Environment

```yaml
Environment
Application Name: --
Laravel Version: 10.48.22
PHP Version: 8.3.8
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: --
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: file
Database: mysql
Logs: stack / single
Mail: ses
Queue: sync
Session: file

Statamic
Addons: 8
Sites: 2 (English, Español)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.32.0 PRO

Statamic Addons
4rn0/statamic-image-optimizer: 1.1.1
aryehraber/statamic-color-extractor: 1.5.0
doefom/statamic-browser-detect: 0.1.1
jacksleight/statamic-bard-texstyle: 3.3.1
rias/statamic-redirect: 3.8.1
statamic/collaboration: 1.0.0
stillat/antlers-layouts: 2.1.0
teamnovu/statamic-images-missing-alt: 1.0.4
```

### Installation

Fresh statamic/statamic site via CLI
