### ISSUE TITLE
Creating S3 Assets container keeps loading

### ISSUE THREAD

**Issue by maarten-mald-digital** [statamic/cms#11022]
### Bug description

In the CP i go to Assets > Create container > File driver s3. Popup says container created success, but keeps loading

![Screenshot 2024-10-28 at 12 25 07](https://github.com/user-attachments/assets/76763067-d9e6-43d9-a51b-53b41a8be453)

### How to reproduce

1. I have created a clean project
```
composer create-project statamic/statamic your-project-name
```

2. Added correct credentials in my .env
```
AWS_ACCESS_KEY_ID=***
AWS_SECRET_ACCESS_KEY=***
AWS_DEFAULT_REGION=***
AWS_BUCKET=***
```

3. Installed required Laravel package
```
composer require league/flysystem-aws-s3-v3 "^3.0" --with-all-dependencies
```

4. I go to cp > assets > create container
title: test
handle: test
disk: s3

Results in loading foreva.

### Logs

```shell
In console i get the following error. Its coming from: vendor/statamic/cp/build/assets

app-aceaa728.js:194 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
```

### Environment

```yaml
Environment
Application Name: LiviSense
Laravel Version: 11.28.0
PHP Version: 8.3.13
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.34.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

- Using tinker i can Storage::disk('s3')->put('test.txt', 'Testing connection'); to store a file
- In my other project looking in Storage > statamic > glide i see a folder "containers" with the created container. This does not show in this project
- Have tried alot of cache/stache clearing
- php 8.3
- node 18 (tried 18 and 21)
