### ISSUE TITLE
Bard Toolbar not staying fixed to top on scroll when used inside Replicator

### ISSUE THREAD

**Issue by fixr-austin** [statamic/cms#11028]
### Bug description

When using a Bard inside a Replicator, the Bard's Toolbar is not staying fixed (sticky) to the top of the screen when scrolling.
Tested on latest Firefox and Chrome browsers, and both have the same issue.

### How to reproduce

- Add Replicator to a collection's Blueprint
- Inside the Replicator, Link an Existing Fieldset that contains a Bard fieldtype. (Or create a new set with a Bard fieldtype)
- Add content to the bard so it extends enough to need to scroll to see more
- Bard toolbar is not staying fixed to the top.

### Environment

```yaml
Environment
Application Name: SR
Laravel Version: 11.26.0
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: OFF
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: pgsql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.9.0
PHP SDK Version: 4.9.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 3
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.35.0 PRO

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.3.1
ndx/statamic-bard-color-picker: 2.0.0
statamic/eloquent-driver: 4.15.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: eloquent
Collection Trees: file
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: file
Navigation Trees: file
Navigations: eloquent
Revisions: eloquent
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
