### ISSUE TITLE
Bug: You can no longer see which option is selected in the 'Button Groups' type in the CP

### ISSUE THREAD

**Issue by nunoc66** [statamic/cms#11029]
### Bug description

If you select an option in a button group, it gets saved and shows up in the DB, but the styles on the screen don't show which option is selected. This happens in light and dark modes.

### How to reproduce

Create a blueprint that uses a button group with multiple choices. Choose an option and notice that the unselected buttons look the same as the selected one.

### Environment

```yaml
Cache
Config: CACHED
Events: CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: postmark
Queue: sync
Session: database

Statamic
Addons: 1
Sites: 2 (Not a Tesla App, Rivian Wave)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.35.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.15.2

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: eloquent
Collection Trees: file
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: file
Navigation Trees: file
Navigations: eloquent
Revisions: eloquent
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
