### ISSUE TITLE
Updating term slug twice results in server error

### ISSUE THREAD

**Issue by daun** [statamic/cms#11020]
### Bug description

When updating a term's slug in the control panel and saving, the first save goes okay and updates the term. However, when updating the slug again, saving now results in a `404` as the edit form is trying to post the data to the previous slug's route.

Only applies when the `Continue Editing` option is selected on the `Save` button.

Looks like the slug is part of the post/patch route and doesn't get updated when changing the slug.

`https://statamic.test/cp/taxonomies/tags/terms/{slug}/default`

### How to reproduce

- Create taxonomy `tags`
- Add new term `A` and publish
- Return to listing
- Click on `A`
- Select `Continue Editing` on the `Save` button
- Change slug to `b`
- Save
- Change slug to `c`
- Should result in `Server error` toast and `404` network request to old patch route

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.29.0
PHP Version: 8.3.3
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: statamic-terms-test.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.34.0 Solo
```
```


### Installation

Fresh statamic/statamic site via CLI

### Additional details

_No response_
