### ISSUE TITLE
Updating term slug does not update references in entries

### ISSUE THREAD

**Issue by daun** [statamic/cms#11021]
### Bug description

When changing a term's slug, it should in theory update any references to that term across all entries. That's what the `UpdateTermReferences` subscriber looks to be doing, but it never happens.

The reason seems to be that `$term->getOriginal('slug')` always returns `null` and no listener can relate old to new slug on a term to do the updating. Unfortunately, this also makes it impossible to fix in user land.

This issue is related to #10938 but not quite the same issue, as the other one can be solved with a custom event listener and this one can't, at least not without touching vendor files.

### How to reproduce

- Create taxonomy `tags`
- Create tags A, B, and C
- Add `terms` field limited to `tags` to `pages` entry blueprint
- Create an entry
- Add tag `C` to entry
- Save
- Edit tag `C`
- Change title to `D` and slug to `d`
- Save
- Check `content/collections/pages/*.yaml`
- See that the `tags` field wasn't updated and is still pointing to `c` instead of `d`

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.29.0
PHP Version: 8.3.3
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: statamic-terms-test.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.34.0 Solo
```
```


### Installation

Fresh statamic/statamic site via CLI

### Additional details

_No response_
