### ISSUE TITLE
Range Date field is missing time field

### ISSUE THREAD

**Issue by marcorieser** [statamic/cms#11024]
### Bug description

I just discovered that a date field with `mode: range` and `time_enabled: true` does not show the time inputs. 

<img width="871" alt="Bildschirmfoto 2024-10-29 um 08 53 20" src="https://github.com/user-attachments/assets/26405491-f278-46b7-9088-2946fc1edace">

Not sure if that's a bug or a feature request.

### How to reproduce

Add a date field to a blueprint like below and visit the entry edit form.
```yaml
handle: booked_from_to
field:
  mode: range
  time_enabled: true
  type: date
  display: 'Booked from to'
  validate:
    - required
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.29.0
PHP Version: 8.3.13
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: statamic-gebetskalender.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.35.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
