### ISSUE TITLE
Bard field inline mode deletes content when there are breaks above

### ISSUE THREAD

**Issue by Bahbv** [statamic/cms#11037]
### Bug description

I've configured a bard field without sets as followed:
- `Enabled with line break`
- `Don't remove empty nodes`

When content is placed in the bard field and a line break is placed above. All content will be removed after saving the page. 
I expected the `<br>` to just be there.

### How to reproduce

1) Start up a new Statamic site.
2) Create a new Bard fieldtype in for example the Page blueprint.
3) Configure the Bard fieltype like this:
```
    -
      handle: bard_field
      field:
        inline: break
        remove_empty_nodes: false
        type: bard
        display: 'Bard Field'
        buttons:
          - bold
        toolbar_mode: floating
```
4) Go to the page and add some content in the bard field.
5) Place linebreaks above the content and save the page.
6) The content will be removed after saving.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.30.0
PHP Version: 8.3.13
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: redis
Session: file

Livewire
Livewire: v3.5.12

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.36.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

I'm getting the same behaviour on different sites.
