### ISSUE TITLE
Unable to use globals in form mail settings

### ISSUE THREAD

**Issue by 925dk** [statamic/cms#11039]
### Bug description

Trying to use `{{ my_global_set:some_email }}` as "Recipient(s)" (`to`) in form mail settings dosen't work. Errors on mail send with invalid to address.

On the other hand, using `{{ email }}` as dynamic reply-to works fine (as per docs).

### How to reproduce

See above.

### Environment

```yaml
Environment
Application Name: xxx
Laravel Version: 11.29.0
PHP Version: 8.2.23
Composer Version: 2.5.8
Environment: production
Debug Mode: OFF
URL: dev.xxx.com
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: sqlite
Logs: stack / single
Mail: sendmail
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.35.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
