### ISSUE TITLE
Statamic API shows incorrect time when using the 'Now' button

### ISSUE THREAD

**Issue by nunoc66** [statamic/cms#11030]
### Bug description

When you're publishing an entry and set the publish date/time to Now, the UI shows the time in the user's timezone, for example Pacific time, however, in the Statamic API, it shows the same time, but in the UTC timezone.

### How to reproduce

If you set the time to Now in an entry, or simply create a new entry which defaults to the publish time being the current time, it'll show your current time in your timezone, for example, 1:50 pm. However, when this entry is published, the Statamic API will show the same time (13:50), but it'll say the timezone is UTC, ruining the correct time of the entry.

### Environment

```yaml
Cache
Config: CACHED
Events: CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: postmark
Queue: sync
Session: database

Statamic
Addons: 1
Sites: 2 (...)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.35.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.15.2

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: eloquent
Collection Trees: file
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: file
Navigation Trees: file
Navigations: eloquent
Revisions: eloquent
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
