### ISSUE TITLE
"Localizable" button shouldn't show on user blueprints

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#11048]
### Bug description

When editing a user blueprint in a multisite, the "Localizable" button is shown on fields. Since users can't be localized, the button shouldn't be shown.

![CleanShot 2024-11-04 at 09 39 46](https://github.com/user-attachments/assets/5895bb24-cc84-45cc-8ddc-9ee8d06f16cd)

### How to reproduce

1. Setup a multi-site
2. Edit the Users blueprint
3. See the "Localizable" buttons showing

### Environment

```yaml
Environment
Application Name: xxx
Laravel Version: 11.29.0
PHP Version: 8.3.13
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: xxx.test
Maintenance Mode: OFF
Timezone: Europe/London
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.12

Statamic
Addons: 5
Sites: 6 (xx, xx, xx, ...)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.34.0 PRO

Statamic Addons
duncanmcclean/static-cache-manager: 4.0.0
edalzell/forma: 3.0.1
jonassiewertsen/statamic-livewire: 3.8.1
mitydigital/statamic-form-submission-cleaner: 1.0.0
silentz/akismet: 5.0
```

### Installation

Fresh statamic/statamic site via CLI
