### ISSUE TITLE
HandleEntrySchedule has timed out

### ISSUE THREAD

**Issue by jbrhel** [statamic/cms#11051]
### Bug description

After updating to version **5.36.0**, my Laravel Horizon started unexpectedly reporting unfinished tasks with the message HandleEntrySchedule has timed out. Additionally, I noticed a significant increase in system resource (CPU) usage in the ```artisan horizon:work process```.

I suspect the origin of this issue might be related to PR: https://github.com/statamic/cms/pull/10966.

### How to reproduce

1. running ```artisan horizon```
2. updating content using Statamic CP
3. **Exception**

```
Illuminate\Queue\TimeoutExceededException: Statamic\Jobs\HandleEntrySchedule has timed out. in /laravel/framework/src/Illuminate/Queue/TimeoutExceededException.php:15
--
Stack trace:
#0 /Illuminate/Queue/Worker.php(803): Illuminate\Queue\TimeoutExceededException::forJob()
#1 /Illuminate/Queue/Worker.php(218): Illuminate\Queue\Worker->timeoutExceededException()
#2 /Illuminate/Cache/MemcachedStore.php(59): Illuminate\Queue\Worker->Illuminate\Queue\{closure}()
```

3. **Exception Context**
```
null
```

4. **Data**
```

{
  "job": null,
  "connection": null,
  "queue": null,
  "delay": null,
  "afterCommit": null,
  "middleware": [],
  "chained": [],
  "chainConnection": null,
  "chainQueue": null,
  "chainCatchCallbacks": null
}
```

### Environment

```yaml
Environment
Application Name: project
Laravel Version: 11.26.0
PHP Version: 8.3.7
Composer Version: 2.8.2
Environment: production
Debug Mode: OFF
URL: project.cz/
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: memcached
Database: mysql
Logs: stack / rollbar, single
Mail: mailgun
Queue: redis
Session: file

Statamic
Addons: 2
Sites: 4 (cs, en, sk, pl)
Stache Watcher: Disabled
Static Caching: full
Version: 5.36.0 PRO

Statamic Addons
appswithlove/statamic-one-click-content-translation: 5.2.3
jacksleight/statamic-bard-mutator: 3.0.3
```

### Installation

Fresh statamic/statamic site via CLI
