### ISSUE TITLE
Form checkboxes with required

### ISSUE THREAD

**Issue by AtmoFX** [statamic/cms#11062]
### Bug description

Continuation to the recent, unanswered discussion: https://github.com/statamic/cms/discussions/10984

When adding the validation `required` to a `Checkboxes` field, the form cannot be submitted unless all the options are ticked. I cannot find a way to validate a checkboxes field so that the submission is accepted so long as I check at least 1 entry but not all of them.
The important thing pointed out by @stephenmeehanuk is that the behavior disappears when the hidden field is removed.

The reason I classify this issue as bug is because the behavior was apparently introduced by: https://github.com/statamic/cms/pull/7180. It must have worked before.

### How to reproduce

Create a form with checkboxes containing more than 1 option.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.30.0
PHP Version: 8.3.13
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: gaia-hub.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.36.0 PRO

Statamic Addons
alt-design/alt-seo: 1.2.1
jacksleight/statamic-bard-mutator: 3.0.3
statamic/eloquent-driver: 4.16.1

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
