### ISSUE TITLE
Conditional field in nav_group not working?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#11077]
### Bug description

I've added a `menu_columns` button group to my  `nav_group` blueprint. 

I've set it to be conditional. I only want the button group to show if the `depth = 1`

The conditional hides it everywhere, regardless of depth?

This is the blueprint

```
       handle: menu_columns
            field:
              options:
                -
                  key: one
                  value: '1'
                -
                  key: two
                  value: '2'
                -
                  key: three
                  value: '3'
                -
                  key: four
                  value: '4'
              default: one
              type: button_group
              display: 'Menu Columns'
              always_save: true
              if:
                depth: 'equals 1'
```

### How to reproduce

40 Second video shows the issue and setup.
https://github.com/user-attachments/assets/44566d23-a608-4997-8658-3ea019fac254

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.29.0
PHP Version: 8.3.8
Composer Version: 2.6.5
Environment: local
Debug Mode: OFF
URL: website.test
Maintenance Mode: OFF
Timezone: America/New_York
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: sqlite
Logs: stack / single
Mail: log
Queue: redis
Session: file

Livewire
Livewire: v3.5.12

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.34.0 PRO

Statamic Addons
jonassiewertsen/statamic-jobs: 1.5.0
jonassiewertsen/statamic-live-search: 2.1.1
jonassiewertsen/statamic-livewire: 3.8.1
statamic/collaboration: 1.0.0
visuellverstehen/statamic-anchor-navigation: 1.0.0
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Field conditions require referencing other fields. `depth` isn't a field.

However `depth` has now been made available in #11080. Upgrade to 5.37.

**Comment by stephenmeehanuk** [comment]
Thanks, I've updated but I'm still seeing the same issue. `menu_columns` doesn't show at all when I add the conditional
```
if:
                depth: 'equals 1'
```
Full nav blueprint below.
```
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: menu_columns
            field:
              options:
                -
                  key: 1
                  value: null
                -
                  key: 2
                  value: null
                -
                  key: 3
                  value: null
                -
                  key: 4
                  value: null
              default: '4'
              type: button_group
              display: 'Menu Columns'
              always_save: true
              if:
                depth: 'equals 1'
          -
            handle: hide_link
            field:
              type: toggle
              display: Hide
```

```
Environment
Application Name: Statamic
Laravel Version: 11.30.0
PHP Version: 8.3.8
Composer Version: 2.6.5
Environment: local
Debug Mode: OFF
URL: website.test
Maintenance Mode: OFF
Timezone: America/New_York
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: sqlite
Logs: stack / single
Mail: log
Queue: redis
Session: file

Livewire
Livewire: v3.5.12

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.37.0 PRO

Statamic Addons
jonassiewertsen/statamic-jobs: 1.5.0
jonassiewertsen/statamic-live-search: 2.1.1
jonassiewertsen/statamic-livewire: 3.8.1
statamic/collaboration: 1.0.0
visuellverstehen/statamic-anchor-navigation: 1.0.0
```
