### ISSUE TITLE
Dictionary Field - Custom Labels show raw HTML on Listing page

### ISSUE THREAD

**Issue by joshtaylordev** [statamic/cms#11084]
### Bug description

I created a new Dictionary class and added a custom label so that I could include a small svg before the text. It displays really nicely on the field itself but on the Collection Listing page it outputs the raw HTML:

Field:
![Screenshot 2024-11-07 at 10 43 07](https://github.com/user-attachments/assets/10cb367b-ae0d-4fac-8504-612289e32eb2)

Listing page:
![Screenshot 2024-11-07 at 10 42 21](https://github.com/user-attachments/assets/6c5e2e26-0812-4dd8-bad9-452f15a9558b)

### How to reproduce

Create a New Dictionary class and add a some HTML into `getItemLabel()`. Then add to a collection and entry and view the listing page.

### Environment

```yaml
Environment
Application Name: Shorefield
Laravel Version: 11.30.0
PHP Version: 8.3.13
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: shorefield.test
Maintenance Mode: OFF
Timezone: Europe/London
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.36.0 PRO

Statamic Addons
statamic-rad-pack/runway: 7.12.0
statamic/eloquent-driver: 4.16.1
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-seo: 8.16.0
studio1902/statamic-peak-tools: 6.3.3

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: file
Revisions: eloquent
Sites: file
Taxonomies: file
Terms: eloquent
Tokens: eloquent
```

### Installation

Starter Kit using via CLI
