### ISSUE TITLE
Collections no longer appears in one category

### ISSUE THREAD

**Issue by JohnnyWalkerDigital** [statamic/cms#11090]
### Bug description

This might not be a bug, but I can't explain what I'm seeing.

Our FAQs are individual items in our `content/collections/faqs` folder. I was doing some testing and I renamed the folders to `-faqs` for a second, loading the site to ensure they didn't appear, and then renamed it back to `faqs`... except they didn't reappear.

They no longer appear in our CP (except you can see the **pagination** sees them -- four pages of questions that are invisible). I can add a new FAQ, and it will appear (and affect the pagination, too). I can delete the new FAQ... but none of the other FAQ files in the folder (which are still there) appear in statamic anymore.

<img width="870" alt="Screenshot 2024-11-07 at 18 50 57" src="https://github.com/user-attachments/assets/fcd7cf20-4a88-4003-9aff-79b24cf36c27">

### How to reproduce

Rename a collections folder, visit the site, and then rename it back to what it was.

### Environment

```yaml
Environment
Application Name: XXX
Laravel Version: 11.26.0
PHP Version: 8.3.13
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: www.xxx.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.30.0 PRO

Statamic Addons
visuellverstehen/statamic-classify: 3.0.0
```

### Installation

Fresh statamic/statamic site via CLI
