### ISSUE TITLE
404 error on direct links to Asset entries

### ISSUE THREAD

**Issue by RyanDrewniak** [statamic/cms#11091]
### Bug description

If I navigate to the asset browser in the CP and click on an entry in the list, it loads the modal with the target edit URL with no problems. However, when trying to link directly to an asset in the CP like this (i.e. either linking directly to this URL or loading that exact URL in a browser window):

https://my-site-url.com/cp/assets/browse/assets/1dsc09534.jpg/edit

it throws a basic nginx 404 error. The site in question is running php 8.2 on an nginx server.

### How to reproduce

1. Select an asset from the assets section of the admin panel, loading the "edit" url.
2. Copy that url targeting that specific asset and open it in a new browser tab.

### Environment

```yaml
Environment
Application Name: TestSite
Laravel Version: 10.48.22
PHP Version: 8.2.24
Composer Version: 2.2.6
Environment: development
Debug Mode: ENABLED
URL: testsite.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single, slack
Mail: mailgun
Queue: sync
Session: redis

Livewire
Livewire: v3.5.12

Sentry
Enabled: YES
Environment: development
Laravel SDK Version: 4.9.0
PHP SDK Version: 4.9.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 7
Sites: 5 (Main, Edmonton - Kids, Calgary - Kids, Edmonton - Adult, Calgary - Adult)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.33.1 PRO

Statamic Addons
alt-design/alt-redirect: 1.3.2
jacksleight/statamic-bard-mutator: 3.0.3
jacksleight/statamic-bard-texstyle: 3.3.1
mitydigital/sitemapamic: 3.2.0
statamic/eloquent-driver: 4.15.2
stillat/antlers-components: 2.2.0
teamnovu/statamic-unused-assets: 2.0.2

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: file
```

### Installation

Starter Kit using via CLI
