### ISSUE TITLE
Lang files are not loaded

### ISSUE THREAD

**Issue by kazak71** [statamic/cms#11101]
### Bug description

I made bulgarian translations of lang files (bg folder with message files and bg.json) and place them in lang/vendor/statamic folder. By changing locale to 'bg' nothing happens, but when I place these files in statamic/cms package (vendor/statamic/cms/resources/lang) everithing works fine.

### How to reproduce

Publish translations, make a copy of en.json to bg.json, change any strings, change locale in .env to 'bg' and you will not see any changes. 

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.30.0
PHP Version: 8.2.20
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF
Timezone: UTC
Locale: bg

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.37.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
