### ISSUE TITLE
Error when setting an option field on a Dictionary field

### ISSUE THREAD

**Issue by CedsTrash** [statamic/cms#11124]
### Bug description

Dictionary field edition screen gives an error when adding a config field of type "select".

### How to reproduce

```
<?php

namespace App\Dictionaries;

use Statamic\Dictionaries\Dictionary;
use Statamic\Dictionaries\Item;

class Artists extends Dictionary
{
    public function options(?string $search = null): array
    {
        return [
            1 => '1',
            2 => '2',
            3 => '3',
        ];
    }

    public function get(string $key): ?Item
    {
        return new Item($key, 'name-' . $key, [
            'name' => 'name-' . $key,
        ]);
    }

    protected function fieldItems()
    {
        return [
            'category' => [
                'display' => 'Category',
                'instructions' => 'Choose a category',
                'type' => 'select',
                'default' => 'rock',
                'options' => [
                    'rock' => 'Rock',
                    'blues' => 'Blues'
                ]
            ]
        ];
    }
}
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.31.0
PHP Version: 8.3.12
Composer Version: 2.6.6
Environment: local
Debug Mode: ENABLED
URL: StatamicNova.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.38.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

![image](https://github.com/user-attachments/assets/c85a337c-5c1e-46be-9cc6-4dc631f3eb31)
