### ISSUE TITLE
Spaces are removed for inline formatting (italics and bold)

### ISSUE THREAD

**Issue by christophstockinger** [statamic/cms#11125]
### Bug description

We have an existing customer project that we updated to Statamic v5 some time ago and is currently running on v5.38.0.

We have been shown a strange behavior by our customer that we cannot understand, that it only occurs isolated in the project. The problem does not occur in one of our sandbox projects with the same Statamic version and the same bard field settings.

The problem is as follows: 
If one or more words in a paragraph are marked in italics or bold, the space before and after the marking is deleted after saving and also displayed as such. Interestingly, however, the space character is also sent in the payload of the request. 

During debugging, however, we noticed that these are then removed all at once when the fields are added.

https://github.com/user-attachments/assets/c5deec38-ee82-43ed-8f2b-8874c0b0b09c

I have attached a video that shows the issue again so that you can reproduce it. 

We are also happy to provide the test environment of the customer project, but unfortunately we have to refrain from linking it publicly here in Github. Unfortunately, this can only be done privately (via e-mail or Discord).

### How to reproduce

The attached video shows the steps to reproduce the problem.

As described, it is possible that this does not occur in another project. We therefore offer to provide access to the test environment. The problem is present on all environments that we operate (local, test and production)

### Environment

```yaml
Environment
Application Name: [DEV] Konkav & K16
Laravel Version: 11.31.0
PHP Version: 8.2.9
Composer Version: 2.8.2
Environment: development
Debug Mode: OFF
URL: cms-konkav.morethings.dev
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Sites: 5 (Konkav - DE, Konkav - EN, K16 - DE, K16 - EN, K16 - PL)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.38.0 PRO

Statamic Addons
aryehraber/statamic-uuid: 2.3.0
jonassiewertsen/statamic-documentation: 2.0.0
morethingsdigital/personio: dev-main
morethingsdigital/statamic-nextjs: 1.0.2
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-seo: 8.17.0
studio1902/statamic-peak-tools: 6.4.0
```

### Installation

Existing Laravel app
