### ISSUE TITLE
Asset container validation - Unable to upload files of type .gpx

### ISSUE THREAD

**Issue by motion-work** [statamic/cms#11131]
### Bug description

Trying to upload a .gpx file and getting this 422 validation error:

![CleanShot 2024-11-18 at 12 33 27@2x](https://github.com/user-attachments/assets/aa182591-3b9e-4b7c-a049-08591773b3d7)

![CleanShot 2024-11-18 at 12 33 33@2x](https://github.com/user-attachments/assets/3e07b04a-68eb-4909-a511-6ab248236d90)

Example GPX-File can be downloaded here: [GPX File](https://www.topografix.com/gpx_sample_files.asp)

Also tried to explicitly allow gpx files as a validation rule in the assets blueprint like so
![CleanShot 2024-11-18 at 12 37 05@2x](https://github.com/user-attachments/assets/57b218a8-e7da-46b1-afed-e75f1a567101)

### How to reproduce

Upload any .gpx file.

Example GPX-File can be downloaded here: [GPX File](https://www.topografix.com/gpx_sample_files.asp)

### Environment

```yaml
Statamic
Addons: 5
Sites: 3 (🇩🇪 Deutsch, 🇫🇷 Français, 🇮🇹 Italiano)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.38.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
