### ISSUE TITLE
str_replace() Deprecation Warnings in PerformanceCollector

### ISSUE THREAD

**Issue by jarridb** [statamic/cms#11147]
### Bug description

This was originally logged in a previous bug that was closed off https://github.com/statamic/cms/issues/6579, 

It appears that it is present in the debugger in the latest version.
We have has resurfaced in version 5.38, when running the debugbar with PHP 8.3, we see multiple warnings being logged related to null parameters being passed to `str_replace()`.

### How to reproduce

Installed a local version following https://statamic.dev/installing/local

### Logs

```shell
Not seeing anything in the logs.
```

### Environment

```yaml
Environment
Application Name: TestingCMS
Laravel Version: 11.31.0
PHP Version: 8.3.10
Composer Version: 2.8.2
Environment: local
Debug Mode: ENABLED
URL: opusdns-cms.ddev.site
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mariadb
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 2 (English, Deutsch)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.38.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

LOG.warning: str_replace(): Passing null to parameter #1 ($search) of type array|string is deprecated in /var/www/html/vendor/statamic/cms/src/View/Debugbar/AntlersProfiler/PerformanceCollector.php on line 78

LOG.warning: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /var/www/html/vendor/statamic/cms/src/View/Debugbar/AntlersProfiler/PerformanceCollector.php on line 78
