### ISSUE TITLE
Too many requests to statamic.com. Try again in xx seconds - happens after a few clicks in cp

### ISSUE THREAD

**Issue by toxsick** [statamic/cms#11154]
### Bug description

Hey Guys,

in our production environment we are getting these messages all the time after a few clicks:

![Monosnap Pages ‹ Collections ‹ Statamic 2024-11-21 23-43-27](https://github.com/user-attachments/assets/4f9ed855-859c-456d-8497-398f92a97f17)

What can we do about this. Kind of confusing for our customers.

Thanks a lot and regards, Hannes

### How to reproduce

Click through 3 - 4 views in the cp.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.33.2
PHP Version: 8.3.8
Composer Version: 2.5.8
Environment: production
Debug Mode: OFF
URL: <live-domain>
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.38.1 PRO

Statamic Addons
eminos/statamic-tabs: 1.2.0
thoughtco/statamic-restrict-fields: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI
