### ISSUE TITLE
Group fieldtype doesn't work correctly in a Navigation blueprint

### ISSUE THREAD

**Issue by eminos** [statamic/cms#11160]
### Bug description

Adding a Group fieldtype to a Navigation blueprint works, but two things happen:
- It's not displayed correctly in the sidebar when opening up a Navigation item (should be grouped?).
- The data is not saved in a nested matter (the group object).

![image](https://github.com/user-attachments/assets/edb22a63-7a39-4e2b-bffe-995f81efc6b0)
![image](https://github.com/user-attachments/assets/31770d55-f43b-4d85-ad0d-1ed75ba7fc9f)

### How to reproduce

Add Group fieldtype to a Navigation blueprint.
Add a few fields inside it.
Try to use it.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.33.2
PHP Version: 8.3.11
Composer Version: 2.2.22
Environment: local
Debug Mode: ENABLED
URL: 
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.39.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
