### ISSUE TITLE
Moving an image doesn't update refs on all globals

### ISSUE THREAD

**Issue by planeer** [statamic/cms#11177]
### Bug description

When moving an image that is linked to more than one globals, doesn't update the reference on all of them. You can see this in the video below.

https://github.com/user-attachments/assets/3e40cead-0199-4c6c-9da7-09b2a474ff42

### How to reproduce

Here is the repository from the video: https://github.com/planeer/statamic-globals-image-move-bug

Login credentials are:
- email: admin@example.com
- password: admin

To reproduce:
1. Link the same image to both globals Test and Test1
2. Go to assets and move that image to the different folder
3. When checking both globals now, the image should be updated on only one, and the other should be without the linked image, because the reference didn't update

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.31.0
PHP Version: 8.3.12
Composer Version: 2.7.8
Environment: local
Debug Mode: ENABLED
URL: statamic-globals-image-move-bug.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.25.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

I updated statamic to latest version after creating new site via CLI.
