### ISSUE TITLE
Hidden fields show up in publish form

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#11170]
### Bug description

Hidden fields are currently hidden in the publish form but their labels do show, which leads to an experience that looks a bit broken:
<img width="939" alt="Screenshot 2024-11-26 at 09 30 09" src="https://github.com/user-attachments/assets/11fd2815-4242-4c02-941d-9421157f0349">

Personally I think hidden fields _should_ show up on this form, but they should only be hidden if `visibility` is set to hidden. As the instructions there state: "Control field visibility on publish forms.". But I guess this is debatable. 

### How to reproduce

1. Make a form
2. Use a hidden field
3. Submit the form
4. Check the publish view

### Environment

```yaml
Environment
Laravel Version: 11.33.2
PHP Version: 8.2.26
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Locales
Installed: en, nl
LaravelLang\Actions\Plugin: 1.8.8
LaravelLang\Attributes\Plugin: 2.11.1
LaravelLang\HttpStatuses\Plugin: 3.8.5
LaravelLang\Lang\Plugin: 15.9.4
Locales Version: 2.9.2
Protected: en
Publisher Version: 16.4.0

Livewire
Livewire: v3.5.12

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.39.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.8.1
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.11.2
studio1902/statamic-peak-seo: 8.17.0
studio1902/statamic-peak-tools: 6.4.0
```

### Installation

Starter Kit using via CLI
