### ISSUE TITLE
Stataic Cache and Livewire - multiple instances running

### ISSUE THREAD

**Issue by HannesEURESA** [statamic/cms#11173]
### Bug description

If we activate half measure Static Caching and on the Statamic Sites are Livewire Components included, even with the nocache Tag the Components aren´t rendering good. And the console show the Error Detected multiple instances of Livewire and Alpine running.

So the Components can´t be rendered well and they be broken. It works on Lokal Environment, but on Production it´s not working.

We don´t want to exclude the whole Page/URL , because it´s the HomePage. (example.com/) So it should be very fast to reach. 

### How to reproduce

Livewire Component included into antlers.html and show on Statamic Website URL which is cached half Static. 
<img width="387" alt="image" src="https://github.com/user-attachments/assets/a1c8a1c7-85ba-403d-b0f0-8d6163c3c52b">

### Environment

```yaml
Environment
Application Name: EURESAreisen
Laravel Version: 11.33.2
PHP Version: 8.3.4
Composer Version: 2.7.2
Environment: production
Debug Mode: ENABLED
URL: euresa-reisen.app.test
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: NOT CACHED
Events: CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: database
Database: mysql
Logs: stack / single
Mail: ses
Queue: database
Session: database

Livewire
Livewire: v3.5.12

Statamic
Addons: 8
Sites: 1
Stache Watcher: Disabled (auto)
Static Caching: half
Version: 5.39.0 PRO

Statamic Addons
jonassiewertsen/statamic-live-search: 2.1.1
jonassiewertsen/statamic-livewire: 3.8.1
rias/statamic-redirect: 3.8.2
statamic/eloquent-driver: 4.18.0
stillat/antlers-components: 2.3.0
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-seo: 8.17.0
studio1902/statamic-peak-tools: 6.4.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: file
Global Variables: file
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
