### ISSUE TITLE
Can't upload assets using the `user:profile_form`

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#11172]
### Bug description

I have an asset field in my user blueprint, but I can't seem to upload assets currently using the `user:profile_form`. There's nothing in the docs that suggest this ain't possible, but it seems this might be an oversight. 

### How to reproduce

Create a user account form
Add an assets field
Fail to make it work

### Environment

```yaml
Environment
Laravel Version: 11.33.2
PHP Version: 8.2.26
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: nl

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Locales
Installed: en, nl
LaravelLang\Actions\Plugin: 1.8.8
LaravelLang\Attributes\Plugin: 2.11.1
LaravelLang\HttpStatuses\Plugin: 3.8.5
LaravelLang\Lang\Plugin: 15.9.4
Locales Version: 2.9.2
Protected: en, nl
Publisher Version: 16.4.0

Statamic
Addons: 11
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.39.0 PRO

Statamic Addons
doefom/statamic-export: 0.4.0
duncanmcclean/guest-entries: 4.0.1
mitydigital/statamic-two-factor: 2.3.0
roorda-ict/statamic-entries-export: 2.1.1
ryanmitchell/statamic-translation-manager: 2.0.0
statamic/eloquent-driver: 4.18.0
stillat/relationships: 2.2.1
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.11.2
studio1902/statamic-peak-seo: 8.17.0
studio1902/statamic-peak-tools: 6.4.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: eloquent
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Starter Kit using via CLI
