### ISSUE TITLE
FrontendFormRequest always gets default locale.

### ISSUE THREAD

**Issue by geertjanknapen1** [statamic/cms#11179]
### Bug description

My form submissions broke, always returning the error messages in our default language (English) even when on the German site.

I traced it to the following change > https://github.com/statamic/cms/commit/ec9e5c51dc5237846385c48a5e7bb519d3c506cf 

In my case `$previousUrl` is a storage link (`myurl.test/storage/images/downloads/hobby/SDS_thumbnail_mobile.jpg`), which does not contain a locale, which means `Site::findByUrl()` does not return an actual site.

This means it will fall back to the default language, causing the frontend errors to be in the wrong language.

### How to reproduce

Setup a multisite with at least two languages. A form with multiple fields, and make sure you have the appropriate translation files.

Submit the form, using AJAX, and observer error messages returned in the default language, instead of the currently active language.

### Environment

```yaml
Environment
Application Name: myapp
Laravel Version: 11.33.2
PHP Version: 8.3.13
Composer Version: 2.8.2
Environment: local
Debug Mode: ENABLED
URL: myapp.test
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / daily, stderr
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 4
Sites: 8 (English, Dutch, Spanish, and 5 more)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.39.0 PRO

Statamic Addons
appswithlove/statamic-one-click-content-translation: 5.2.3
spatie/statamic-responsive-images: 5.2.1
statamic-rad-pack/meilisearch: 3.3.0
withcandour/aardvark-seo: 5.0.0
```

### Installation

Existing Laravel app
