### ISSUE TITLE
Infinite loop when stache indexes are being freshly loaded by a worker

### ISSUE THREAD

**Issue by simonworkhouse** [statamic/cms#11187]
### Bug description

The `Statamic\Stache\Indexes\Index::load()` method can cause infinite loops when being executed by a worker when there's an empty stache.

### How to reproduce

The following set of commands will either cause an infinite loop or segfault:

```bash
php artisan cache:clear && \
php artisan tinker --execute="\Request::swap(request()->duplicate(server: ['argv' => [ 'artisan', 'queue:work', ], 'argc' => 2])); tap(\Statamic\Entries\Collection::make('test'))->save(); \Statamic\Facades\Entry::make()->id('alfa-id')->collection('test')->slug('alfa')->data(['title' => 'Alfa'])->save();"
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.34.2
PHP Version: 8.2.26
Composer Version: 2.8.2
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.41.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
