### ISSUE TITLE
Unable to get entries from other sites

### ISSUE THREAD

**Issue by thomas4Bitcraft** [statamic/cms#11183]
### Bug description

We utilize the multisite feature in Statamic for our website, managing a default locale (e.g., de) and additional sites for various countries (de-at, de-de, de-ch). This setup allows us to customize entries for specific countries while maintaining a default version for the language. However, certain collections don’t require country-specific sites and are therefore not linked to them.

The problem arises when we have a specific entry for a site like de-at. Entries that don’t exist for this site are not linked correctly.

For example, our collections are structured as follows:

pages: de, de-at, de-de, de-ch, it, it-it, ch-id
products: de, it
In the pages collection, we have an entries form field to link products. However, if the entries are not published across all sites, they do not display correctly.

Another maybe quicker solution would be to set a default origin for specific sites. With this we could use the auto propagate feature and the locales would be correctly linked. For example:
de-at has default origin de
it-it has default origin it

### How to reproduce

-

### Logs

```shell
-
```

### Environment

```yaml
Environment
Laravel Version: 11.34.2
PHP Version: 8.2.7
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF
Timezone: Europe/Vienna
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.10.1
PHP SDK Version: 4.10.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 0%
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 5
Sites: 12 (de, it, en, and 9 more)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.41.0 PRO

Statamic Addons
bitcraft/form-webhook: dev-production
bitcraft/page-generator: dev-production
bitcraft/simple-seo: dev-production
ndx/statamic-bard-color-picker: 2.0.0
statamic/eloquent-driver: 4.18.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```

### Installation

Fresh statamic/statamic site via CLI
