### ISSUE TITLE
Validation fails when dynamic folder is set to id and min_files >= 1

### ISSUE THREAD

**Issue by nopticon** [statamic/cms#11181]
### Bug description

If you create an assets field with dynamic folder set to `id` and min_files = 1 or more, it shows an error message when creating a new entry.

![Screenshot 2024-11-27 at 16 15 30](https://github.com/user-attachments/assets/f3fd5bc5-1bf4-46f0-8747-426f001e4e7a)

### How to reproduce

Add this field to your blueprint and try saving the entry:

```yaml
handle: assets_field
field:
  max_files: 1
  min_files: 1
  container: assets
  dynamic: id
``` 

![Screenshot 2024-11-27 at 16 04 28](https://github.com/user-attachments/assets/ae4cf4a4-b896-413a-9a7d-e66d29c46c4e)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.34.2
PHP Version: 8.3.14
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.41.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

I suggest if Statamic could create a temporary folder to store assets. After the entry is created, the system moves those files to the dynamic id destination folder.
