### ISSUE TITLE
Issue with Model based Dictionary Field for Multiple Selections in User Blueprint

### ISSUE THREAD

**Issue by chano195** [statamic/cms#11195]
### Bug description

I am encountering an issue with a dictionary (modules) that is based on a model in my database, configured as described in the Statamic documentation [here](https://statamic.dev/extending/dictionaries#item-data).

In my user blueprint, I have a field of type dictionary associated with the modules dictionary for multiple selections. Everything works fine when saving, and it stores the selected modules in the users table under the modules field as an array, like this: ["1","2"], where 1 and 2 are the IDs of the selected modules based on the modules model.

However, when I return to edit the user, the labels of the selected modules do not appear, and the saved format (["1","2"]) is not recognized correctly. The options do not appear as selected, and the saved data does not show up as expected in the user interface.

I've also tested using a pivot table between the module and user models, but it not works for me

Questions/Clarifications:

Is this the best approach for implementing this feature, or are there better ways to associate users with multiple modules?
Do you have any suggestions or corrections to ensure that the selected module labels display correctly when editing the user?
I would appreciate any guidance on how to resolve this. Thank you in advance!

Model based Dictionary: 
![image](https://github.com/user-attachments/assets/284bec20-050d-4a93-8718-e34db8cc6b7d)

User BluePrint:
![image](https://github.com/user-attachments/assets/bd51950d-3741-4e00-aff5-9d9dc855eb0a)

User Model

![image](https://github.com/user-attachments/assets/26637da2-20bb-498f-9c94-71dda33fc5dc)

Editor selector (working):
![image](https://github.com/user-attachments/assets/63c1335b-b9a1-43ac-981f-ed9a742e574d)

Editor bug
![image](https://github.com/user-attachments/assets/9466cb07-4811-4458-a5c3-acce3dbe0c4b)

### How to reproduce

Create a Dictionary:

Create a dictionary (modules) based on a model as described in the [Statamic documentation](https://statamic.dev/extending/dictionaries#item-data).
The dictionary should use a model where the id is the key and nombre (or another attribute) is the value. Example fields could include:
id (primary key)
nombre (name of the module)
Create a User Field for Module Association:

In your user model (or the relevant model), create a field called modulo_id to store the associated module IDs. This will act as the foreign key to your modules dictionary.
Create a Blueprint for Users:

Create a blueprint for the user model of type dictionary that references the modules dictionary. Make sure the field type is set for multiple selection, with no selection limit.
Create or Edit a User:

Create a new user or edit an existing one in the Statamic control panel.
In the modulo_id field, select one or more modules from the available options. This should work fine and save the selected module(s) as an array (e.g., ["1","2"]) in the user’s modulo_id field.
Exit and Re-enter the User Edit View:

Save the user and exit the edit view.
Return to the user edit screen for the same user.
Expected Behavior:

When re-editing the user, the previously selected modules should be displayed as selected options with their labels.
Actual Behavior:

The selected modules now appear as ["1","2"] in the modulo_id field, marked in red. It appears as if the user can only select a single option, instead of multiple options being properly displayed.

As seen in the provided screenshots, the field behaves as if it’s a single selection, which causes confusion.

### Environment

```yaml
Environment
Application Name: Centro-de-Recursos-GSL
Laravel Version: 11.23.4
PHP Version: 8.3.11
Composer Version: 2.7.9
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: America/Santiago
Locale: es

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Locales
Installed: en, es
LaravelLang\Actions\Plugin: 1.8.8
LaravelLang\Attributes\Plugin: 2.11.1
LaravelLang\HttpStatuses\Plugin: 3.8.5
LaravelLang\Lang\Plugin: 15.9.5
Locales Version: 2.9.2
Protected: es
Publisher Version: 16.4.0

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.40.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.18.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: eloquent
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Please let me know if you need anything else, I'll be on the lookout
