### ISSUE TITLE
AWS.SimpleQueueService.NonExistentQueue CollectionTreeControler

### ISSUE THREAD

**Issue by HannesEURESA** [statamic/cms#11208]
### Bug description

I am on the Tree View of an Collection. If I want to move an Entry and want to save the Tree I get the Server Error Message.
In the log there is the Error: 

Error executing "SendMessage" on "https://sqs.eu-central-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://sqs.eu-central-1.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"com.amazonaws.sqs#QueueDoesNotExist","message":"The specified queue does not exist."}
 AWS.SimpleQueueService.NonExistentQueue (Sender): The specified queue does not exist. - {"__type":"com.amazonaws.sqs#QueueDoesNotExist","message":"The specified queue does not exist."}

 
The Error comes from 
EntriesController@store
CollectionTreeController@update
so far. 

On the Local it´s working. Production I get the Error Message. So I think it has to to something with AWS configuration or queue. 

![image](https://github.com/user-attachments/assets/8c676286-fc39-47b5-808d-45cf3f4d50f5)

![image](https://github.com/user-attachments/assets/836d6cb6-38fd-4c33-84d4-fd97c80e50fd)

### How to reproduce

Go to Collection, move an entry in the Tree view and save

### Environment

```yaml
Environment
Application Name: xxx
Laravel Version: 11.34.2
PHP Version: 8.3.4
Composer Version: 2.7.2
Environment: production
Debug Mode: ENABLED
URL: xxx
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: NOT CACHED
Events: CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: database
Database: mysql
Logs: stack / single
Mail: ses
Queue: database
Session: database

Livewire
Livewire: v3.5.15

Statamic
Addons: 8
Sites: 1
Stache Watcher: Disabled (auto)
Static Caching: half
Version: 5.41.0 PRO

Statamic Addons
jonassiewertsen/statamic-live-search: 2.1.1
jonassiewertsen/statamic-livewire: 3.8.1
rias/statamic-redirect: 3.8.2
statamic/eloquent-driver: 4.19.0
stillat/antlers-components: 2.4.0
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-seo: 8.17.0
studio1902/statamic-peak-tools: 6.5.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: file
Global Variables: file
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Statamic built with Vapor on AWS.
