### ISSUE TITLE
500 error from duplicate ID in collection tree following reorder of entries

### ISSUE THREAD

**Issue by wesort** [statamic/cms#11209]
### Bug description

Reordering a new entry causes a duplicate ID in the collection _tree_.

Similar to #2662 (closed) and #9531 (open).

### How to reproduce

_NB: I'm struggling to recreate this in my dev env. The client has managed to cause the issue a couple of times but not entirely sure what is triggering it._

### Steps:
- Create a new entry in an orderable collection and publish it.
- Reorder the entries and save.
- Result: 500 error on front-end that doesn't use custom error template

### Only certain users seem to cause this issue: 
- Their preferences & permissions are the same apart from collection listing columns being displayed
- Users on Windows 11 using Chrome.
- Workaround seems to be: refresh the collection listing (ie: `cmd + r` in the browser) _after_ publishing the new entry but _before_ reordering.

### Environment

```yaml
Environment
Application Name: Red + White
Laravel Version: 11.34.1
PHP Version: 8.3.13
Composer Version: 2.8.3
Environment: production
Debug Mode: OFF
URL: redandwhite.co
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: CACHED
Events: CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.40.0 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 3.0.3
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Further context:
- List of entries in the _tree_ includes a duplicate ID at the end after using `Reorder` button in the CP.
- Results in `500` error on the front-end (see below) 
  - NB: `APP_DEBUG=false` so I presume the custom error template `/resources/views/errors/500.blade.php` should be presented instead?
- Results in _Server error_ in CP listing for that collection but no further info
- The duplicate ID CP page doesn't appear. I presume as it's not a duplicate entry in the _collection_, but a duplicate entry in the _tree_.
- The position of the newly created entry seems random. Sometimes it's at the top of the listing (desired) and sometimes at the bottom. 

<details>
<summary>

### front-end error screenshot
</summary>

![Screenshot 2024-12-02 14 10 33](https://github.com/user-attachments/assets/9f0e907a-9f18-4fe2-ae30-8fa444993946)

</details>

<details>
<summary>

### CP error screenshot
</summary>

![Screenshot 2024-12-02 14 09 17](https://github.com/user-attachments/assets/6a0d53df-9731-4cc9-b62c-02c2bd57b1a9)

</details>

**Comment by wesort** [comment]
**Update:** I _think_ this is due to the user's choice with the number of entries to include in the pagination in the CP. Users that cause the issue have this set to `50` (default) and there are more than 50 entries in the collection. Changing `100` fixes it.

```
preferences:
  collections:
    projects:
      per_page: 100

```

![image](https://github.com/user-attachments/assets/ac553f33-8f36-46dc-92b1-60dbb14e78c3)
