### ISSUE TITLE
php please support:details not working with PHP 8.3

### ISSUE THREAD

**Issue by christophstockinger** [statamic/cms#11205]
### Bug description

```
Fatal error: Uncaught Error: Class "App\Console\Kernel" not found in /Users/cstockinger/Code/morethingsdigital/k16-konkav-cms/vendor/statamic/cms/src/Console/Please/Kernel.php:11
Stack trace:
#0 phar:///Applications/Herd.app/Contents/Resources/valet/dump.phar/vendor/composer/ClassLoader.php(576): include()
#1 phar:///Applications/Herd.app/Contents/Resources/valet/dump.phar/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/Users/cstockin...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Statamic\\Consol...')
#3 /Users/cstockinger/Code/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(940): ReflectionClass->__construct('Statamic\\Consol...')
#4 /Users/cstockinger/Code/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(815): Illuminate\Container\Container->build('Statamic\\Consol...')
#5 /Users/cstockinger/Code/project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1048): Illuminate\Container\Container->resolve('Statamic\\Consol...', Array, true)
#6 /Users/cstockinger/Code/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(751): Illuminate\Foundation\Application->resolve('Statamic\\Consol...', Array)
#7 /Users/cstockinger/Code/project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1030): Illuminate\Container\Container->make('Statamic\\Consol...', Array)
#8 /Users/cstockinger/Code/project/please(33): Illuminate\Foundation\Application->make('Statamic\\Consol...')
#9 {main}
  thrown in /Users/cstockinger/Code/project/vendor/statamic/cms/src/Console/Please/Kernel.php on line 11
```

### How to reproduce

Use Herd with PHP-Version 8.3

Go in a statamic projekt and runs `php please support:details`

But `php artisan statamic:support:details` works!

### Environment

```yaml
Environment
Application Name: project
Laravel Version: 11.33.2
PHP Version: 8.3.14
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: project.test
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Sites: 2 (DE, EN)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.38.1 PRO

Statamic Addons
aryehraber/statamic-uuid: 2.3.0
jonassiewertsen/statamic-documentation: 2.0.0
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-seo: 8.17.0
studio1902/statamic-peak-tools: 6.4.0
```

### Installation

Existing Laravel app
