### ISSUE TITLE
Link in Bard Fieldset have wrong url

### ISSUE THREAD

**Issue by christophstockinger** [statamic/cms#11206]
### Bug description

We have a site with a multisite setup (de and en). On the English page, we set a link to another entry in a bard field. 

Now, however, a link is created on the English page that links to the German page

### How to reproduce

Create a multisite with German and English. German is Origin. Then create a bard field and link it in a blueprint. Create an entry and insert a link in the bard field that points to an entry that is available in both languages. 

Then call the API and see what is output. 

### Environment

```yaml
Environment
Application Name: project
Laravel Version: 11.33.2
PHP Version: 8.3.14
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: project.test
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Sites: 2 (DE, EN)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.38.1 PRO

Statamic Addons
aryehraber/statamic-uuid: 2.3.0
jonassiewertsen/statamic-documentation: 2.0.0
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-seo: 8.17.0
studio1902/statamic-peak-tools: 6.4.0
```

### Installation

Existing Laravel app
