### ISSUE TITLE
Ordering search results by `order` doesn't work

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#11200]
### Bug description

I have a structured collection that I query using its search index for a Livewire component. The results returned don't seem to respect `orderBy('order')`, however I can sort it on other fields.

```php
$query = Search::index('case_studies')
    ->ensureExists()
    ->search($this->search)
    ->where('status', 'published')
    ->orderBy('order');
```

The `order` property is added to the search index and is correctly visible in the search index.

```json
{"entry::c7fe40a3-6acc-4e49-8009-56de948c7b26":{"title":"Association of Independent Music","hero_heading":"Rebranding the UK's biggest independent music association","verticals":["brand"],"order":68}
```

### How to reproduce

1. Create an ordered collection.
2. Query it using the above code.
3. See that the order is not respected.

### Environment

```yaml
Environment
Application Name: Paradise
Laravel Version: 10.48.25
PHP Version: 8.2.26
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: paradise.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.14

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.41.0 PRO

Statamic Addons
jaygeorge/admin-styler: dev-main
jonassiewertsen/statamic-live-search: 2.1.1
jonassiewertsen/statamic-livewire: 3.8.1
statamic/collaboration: 1.0.0
statamic/seo-pro: 6.3.0
```

### Installation

Fresh statamic/statamic site via CLI
