### ISSUE TITLE
Images too large for thumbnail generation look like failed uploads

### ISSUE THREAD

**Issue by daun** [statamic/cms#11228]
### Bug description

Images larger than `assets.thumbnails.max_width` won't generate thumbnails, which is fine, but to non-technical editors that don't know this limitation, it looks like the image is broken or there was an error uploading it. The thumbnail url resolves to a 404 and will prompt the browser to show an icon for broken/missing images.

### Example

<img width="641" alt="Screenshot 2024-12-06 at 21 18 04" src="https://github.com/user-attachments/assets/75862233-a810-43fb-89dd-25ad9241ec8b">

### Suggested solution

I'd suggest showing a generic "image" icon instead of linking to the thumbnail here, similar to how non-image assets are displayed, e.g. PDFs that have their own icon.

<img width="487" alt="Screenshot 2024-12-06 at 21 25 19" src="https://github.com/user-attachments/assets/9e96a9fb-bd52-47db-9164-9c8f1eebcac8">

### How to reproduce

Upload than image larger than 10.000 x 10.000px

### Environment

```yaml
Environment
Application Name: *****
Laravel Version: 11.30.0
PHP Version: 8.3.14
Composer Version: 2.8.3
Environment: development
Debug Mode: ENABLED
URL: *****.test
Maintenance Mode: OFF
Timezone: Europe/Vienna
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.37.0 PRO

Statamic Addons
daun/statamic-widget-collection-count: 1.3.0
doefom/statamic-export: 0.4.0
jacksleight/statamic-bard-mutator: 3.0.3
jacksleight/statamic-bard-texstyle: 3.3.2
```

### Installation

Fresh statamic/statamic site via CLI
