### ISSUE TITLE
Custom Slug Rules Not Being Applied

### ISSUE THREAD

**Issue by xyNNN** [statamic/cms#11220]
### Bug description

I want to modify the slug validation for a collection. Specifically, I’d like to allow slashes (/) in the slug field. However, when I try to save an entry, I receive the error message: 'This URI has already been assigned.

### How to reproduce

1. Overwrite the EntryRepository with a custom implementation.
2. Override the repository methods: createRules, updateRules, and bindings.
3. Modify the slug method to prevent slugifying the provided value for the collection slug.

![image](https://github.com/user-attachments/assets/58fd410c-841e-445b-9c49-87202ac5055f)
![image](https://github.com/user-attachments/assets/24e7c283-0212-40a8-bd35-a8caab21c222)
![image](https://github.com/user-attachments/assets/04f8c18f-2c51-426d-9ec9-41ac74627743)

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 11.25.0
PHP Version: 8.2.25
Composer Version: 2.8.2
Environment: local
Debug Mode: ENABLED
URL: domain.development
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: CACHED
Events: CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: redis
Database: pgsql
Logs: stack / single
Mail: smtp
Queue: sync
Session: redis

Pulse
Enabled: OFF
Version: v1.2.5

Livewire
Livewire: v3.5.8

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.9.0
PHP SDK Version: 4.9.0
Release: 60e416e9
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.40.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.18.0
statamic/seo-pro: 6.3.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Existing Laravel app
