### ISSUE TITLE
Augmentation not working on markdown fields in navigation

### ISSUE THREAD

**Issue by wnschroeder** [statamic/cms#11223]
### Bug description

A Markdown field in the navigation is ignored by the augmentation process and passed through to the frontend in Markdown syntax. Even the Markdown modifier does not resolve this issue.

![image](https://github.com/user-attachments/assets/01297dd0-1a74-44e1-b1ef-071a3cc752d7)

![image](https://github.com/user-attachments/assets/fde8cbbe-011e-49f8-a857-4ed82a9c2819)

![image](https://github.com/user-attachments/assets/e67cbca7-95d3-4ba7-954c-d7fe89466da7)

![image](https://github.com/user-attachments/assets/06852083-76b0-424a-a9b0-7289444befc2)

### How to reproduce

Place a markdown field within a navigation blueprint. In my case it's part of a group fieldtype.

### Environment

```yaml
Environment
Laravel Version: 11.31.0
PHP Version: 8.3.8
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: localhost:24600
Maintenance Mode: OFF
Timezone: Europe/Berlin
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.12

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.40.0 PRO

Statamic Addons
aerni/livewire-forms: 9.4.0
eminos/statamic-tabs: 1.2.0
jonassiewertsen/statamic-livewire: 3.8.1
statamic/seo-pro: 6.3.0
```

### Installation

Fresh statamic/statamic site via CLI
