### ISSUE TITLE
Broken app extension registration

### ISSUE THREAD

**Issue by caseydwyer** [statamic/cms#11231]
### Bug description

I believe there was a regression in #11046, that broke "standard" extension registration. I would expect this to have broken other file types inside the `App/*` directories, but have confirmed it on Dictionaries. Specifically, see [this commit](https://github.com/statamic/cms/commit/a345e00f535e76f485b2e0a40f27551b990b5519#diff-3c0edc65740baada07e6b672b968db1a105e30a228299601956ed67ecb48cf2bL338).

When reverting that code (ie, before that PR was merged), DD'ing the `$fqcn` inside `registerAppExtensions` yields something valid and expected, like:
```
App\Dictionaries\SpecialMap
```

But with that PR, it breaks the fully-qualified name and returns an invalid path:
```
App\C:\www\my-website\app\Dictionaries\SpecialMap
```

### How to reproduce

1. Install latest Statamic
2. Setup a Dictionary _(or presumably any of the standard extension classes)_
3. Append the field as a config on any fieldtype:
```php
Text::appendConfigFields([
    'external_field' => [
        'type' => 'dictionary',
        'dictionary' => 'special_map',
        'instructions' => 'Corresponding field, as labeled on the associated object.',
        'max_items' => 1,
    ],
]);
```
4. Try to open a blueprint field of that type, inspect request for error _(exception thrown in `DictionaryFields.php` around line 57)_

### Environment

```yaml
Environment
Application Name: My Website
Laravel Version: 11.34.2
PHP Version: 8.2.5
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: my-website.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.17

Statamic
Addons: 6
Sites: 3 (One, Tow, Three)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.42.0 PRO

Statamic Addons
caseydwyer/statamic-long-range: dev-main
eminos/statamic-tabs: 1.2.0
jacksleight/statamic-miniset: 1.2.0
jonassiewertsen/statamic-livewire: 3.8.1
statamic-rad-pack/runway: 7.13.1
statamic/seo-pro: 6.4.0
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

On Windows 10, using Herd.
