### ISSUE TITLE
Replicator and Group: Preview option not working as expected

### ISSUE THREAD

**Issue by carstenjaksch** [statamic/cms#11235]
### Bug description

I have a Replicator as Page Builder (from Peak). It contains a set that uses a fieldset, which uses another fieldset (a group). That group fieldset has preview activated. It contains three fields, one of them is a Bard field also with preview enabled. The other two have preview disabled.

Issues:

1. The bard field preview returns [object Object].
2. The other fields are displayed as preview, even though they have preview disabled.

Without a group, the Bard field preview works as expected.

<img width="892" alt="Replicator Preview" src="https://github.com/user-attachments/assets/376f7b0a-a8a0-4772-83d2-dfe1e5e064bd">

<img width="888" alt="Replicator" src="https://github.com/user-attachments/assets/47eb3239-7e98-4c20-96f6-1bf292cfb3ba">

### How to reproduce

https://github.com/gutacht/statamic

The group field is currently in use on the home page.

### Environment

```yaml
Environment
Application Name: Gutachterix
Laravel Version: 11.34.2
PHP Version: 8.3.14
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: gutachterix.test
Maintenance Mode: OFF
Timezone: Europe/Berlin
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: reverb
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Sites: 2 (Gutachterix, Clever-Immo)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.42.0 PRO

Statamic Addons
ryanmitchell/statamic-translation-manager: 2.0.0
statamic/collaboration: 1.0.0
studio1902/statamic-peak-browser-appearance: 3.6.0
studio1902/statamic-peak-commands: 8.12.0
studio1902/statamic-peak-seo: 8.18.0
studio1902/statamic-peak-tools: 6.6.0
```

### Installation

Starter Kit using via CLI
