### ISSUE TITLE
Memory Leak on publish

### ISSUE THREAD

**Issue by waldemar-p** [statamic/cms#11245]
### Bug description

I Upgraded from statamic 4 to 5 and after that I couldnt publish on production anymore. Weirdly it works on my local machine.

I am unsure how much influence it has, but I also have the revisions enabled.

### How to reproduce

Sadly I don't know that. I am sorry, but maybe you can help me anyway.

### Environment

```yaml
Environment
Application Name: Actiware
Laravel Version: 10.48.25
PHP Version: 8.2.26
Composer Version: 2.2.6
Environment: local
Debug Mode: ENABLED
URL: 127.0.0.1:8000
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 3 (Deutsch, Schweizer Hochdeutsch, English)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.42.0 PRO

Statamic Addons
aerni/font-awesome: 3.0.2
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

I use statamic headless, but I think that's of no importance.
