### ISSUE TITLE
Entry slug URI not updating on save

### ISSUE THREAD

**Issue by kram-dyoll** [statamic/cms#11240]
### Bug description

I'm using the Eloquent driver for entries and it seems to be an issue when using the Eloquent driver as the file based driver woirks as expected.

When I update the slug for an entry, the change saves but checking the new URL results in a 404 page (old URL is still valid). If I save the page again, the new URL work.

It looks like the first save updates the `slug` field in the table. The second save then updates the `uri` field in the table.

### How to reproduce

- Use the Eloquent driver for entries.
- Update a slug of an entry and visit the new page. This will be a 404 page. You can also check the DB table and see the `slug` has been updated , but the `uri` has not.
- Save the entry again and visit the new page. This will now work as expected. You can also check the DB table and see the `uri` has now been updated.

### Environment

```yaml
Environment
Application Name: Test Website
Laravel Version: 11.34.2
PHP Version: 8.3.14
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: test-website.ddev.site
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.42.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.19.0
statamic/seo-pro: 6.4.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: file
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: file
Revisions: file
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
