### ISSUE TITLE
`validate: sometimes` not working when used in Nav blueprint

### ISSUE THREAD

**Issue by o1y** [statamic/cms#11249]
### Bug description

When using `validate: sometimes` in a Nav blueprint, validation rules are triggered even when the associated field is not visible.

### How to reproduce

Use the following Blueprint for a Navigation:

```yaml
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: has_image
            field:
              inline_label: 'Show Image'
              inline_label_when_true: 'Hide Image'
              type: toggle
              display: 'Add Image'
          -
            handle: image
            field:
              container: assets
              type: assets
              display: Image
              validate:
                - sometimes
                - required
              if:
                has_image: 'equals true'

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.35.0
PHP Version: 8.3.14
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: statamic-validation-check.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.42.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI
