### ISSUE TITLE
locales and locales:count does not work with Fluent Tags

### ISSUE THREAD

**Issue by isaackearl** [statamic/cms#11247]
### Bug description

In my project, I had localizations for english and spanish.  I attempted to use the locales:count to get the number of localizations on a given page.  In blade, I could not get any of the methods working for getting the count or the locales other then using this method: `<s:locales:count />`

I ran the example in the docs:
`{{-- Using Antlers Blade Components --}}
<s:locales:count />
<s:locales:count self="false" />
 
{{-- Using Fluent Tags --}}
{{ Statamic::tag('locales:count') }}
{{ Statamic::tag('locales:count')->self(false) }}`

returns 
2
1

and then for the fluent tags
0
0

other methods such as @tags('locales'), does not seem to work either.

In the end I had to use @antlers @endantlers in order to get the functionality I needed.

### How to reproduce

Setup a multisite page with a blade template.  Test this:

I ran the example in the docs:
`{{-- Using Antlers Blade Components --}}
<s:locales:count />
<s:locales:count self="false" />
 
{{-- Using Fluent Tags --}}
{{ Statamic::tag('locales:count') }}
{{ Statamic::tag('locales:count')->self(false) }}`

notice that the FluentTags always just return 0.  also if you do 'locales' it will always be an empty result when fetching.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.35.0
PHP Version: 8.3.14
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Livewire
Livewire: v3.5.17

Statamic
Addons: 2
Sites: 2 (English, Español)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.42.0 PRO

Statamic Addons
aerni/livewire-forms: 9.4.1
jonassiewertsen/statamic-livewire: 3.8.1
```

### Installation

Fresh statamic/statamic site via CLI
