### ISSUE TITLE
Published entry time is updated on save

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#11255]
### Bug description

When modifying a published entry, it will have its created time replaced by the edited time.

### How to reproduce

- Create a new collection.
- In the entry blueprint of this collection, add a date field with the option `time_enabled`.
- Create and publish 3 entries, all with the date of yesterday, but different times.
- Memories the order of your entries in the control panel list.
- Now edit the first created entry without changing the date or time and save it.

You will see that the date of this entry is still yesterday, but the created time has been replaced by the edited time.

As a result, the order of the collection entries has changed, which is a problem.

### Environment

```yaml
Environment
Application Name: photos
Laravel Version: 11.35.1
PHP Version: 8.3.14
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: photos.test
Maintenance Mode: OFF
Timezone: Europe/Paris
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.42.1 PRO

Statamic Addons
spatie/statamic-responsive-images: 5.2.1
statamic/seo-pro: 6.5.0
```

### Installation

Fresh statamic/statamic site via CLI
