### ISSUE TITLE
buggy {{ collection:previous|next }} in collection with date and time enabled

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#11263]
### Bug description

The `{{ collection:previous}}` and `{{ collection:next }}` don’t return the correct entry.
It appends to the collection with time and date enabled.

### How to reproduce

It's a really weird problem. My guess is a problem with collection sorting that is mixing date and title, but I'm not sure.
To make it easier to understand, I've created a reproduction repo : https://github.com/jimblue/statamic-buggy-nav

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.35.1
PHP Version: 8.3.14
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.42.1 PRO
```

### Installation

Fresh statamic/statamic site via CLI
