### ISSUE TITLE
When filtering by a taxonomy in the collection entries table view, it displays incorrect entries when filtered

### ISSUE THREAD

**Issue by mattmultiplied** [statamic/cms#11262]
### Bug description

When filtering by a taxonomy (in this case sectors) in the entries table view it is displaying entries that don't have the assigned taxonomy. 

### How to reproduce

https://www.loom.com/share/c6800143fbca44a292fbfc419cdf3d23

### Environment

```yaml
Environment
Application Name: <concealed by 1Password>
Laravel Version: 11.34.2
PHP Version: 8.3.12
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: <concealed by 1Password>.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: CACHED
Events: CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Qu<concealed by 1Password>e: sync
Session: file

Statamic
Addons: 5
Sites: 3 (<concealed by 1Password>, <concealed by 1Password>, <concealed by 1Password>)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.42.1 PRO

Statamic Addons
alt-design/alt-redirect: 1.3.2
jacksleight/statamic-bard-texstyle: 3.4.1
statamic/collaboration: 1.0.0
statamic/seo-pro: 6.5.0
teamnovu/statamic-images-missing-alt: 1.0.4
```

### Installation

Fresh statamic/statamic site via CLI
