### ISSUE TITLE
When replacing an asset and setting alt, it closes the window

### ISSUE THREAD

**Issue by mattmultiplied** [statamic/cms#11260]
### Bug description

When replacing an asset and clicking 'Set Alt' after upload, it closes the asset window completely.

### How to reproduce

https://www.loom.com/share/a8c524fd105441c3b1de89188a62e932?sid=b1d1854f-4c89-4371-a159-8d1d82034191

### Environment

```yaml
Environment
Application Name: <concealed by 1Password>
Laravel Version: 10.48.25
PHP Version: 8.3.12
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: <concealed by 1Password>.test
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.42.1 PRO

Statamic Addons
alt-design/alt-redirect: 1.3.2
jacksleight/statamic-bard-texstyle: 3.4.1
statamic/seo-pro: 6.5.0
```

### Installation

Fresh statamic/statamic site via CLI
