### ISSUE TITLE
Different date format between collection and entry in control panel

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#11266]
### Bug description

In collection list view it's in 24h format 👍
![image](https://github.com/user-attachments/assets/efac1651-4e20-4655-b124-f681f3e759c1)

But in entry it's not 👎
![image](https://github.com/user-attachments/assets/dd899690-504b-4e35-a244-0c7dd7d06533)

### How to reproduce

Create a collection with date enabled.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.35.1
PHP Version: 8.3.14
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.42.1 PRO
```

### Installation

Fresh statamic/statamic site via CLI
