### ISSUE TITLE
GraphQL Forbidden Error When Using _or Condition in Entries Query

### ISSUE THREAD

**Issue by emran-alhaddad** [statamic/cms#11271]
### Bug description

What happened? What did you expect to happen?

When using an _or condition in a GraphQL query to filter entries, the query returns a "Forbidden" error. I expected the query to return entries matching either of the conditions specified.

Error Message:
`Forbidden for _or condition.`

### How to reproduce

1. Create a collection named articles with fields title and short_description.
2. Run the following GraphQL query:

```
query Entries {
    entries(
        collection: "articles"
        filter: {
            _or: {
                title: { matches: ".*emran.*" }
                short_description: { matches: ".*emran1.*" }
            }
        }
    ) {
        data {
            ... on Entry_Articles_Article {
                title
                short_description
                date(format: "D-M-Y")
            }
        }
    }
}
```

3. The query fails with the error message: 

```
{
    "errors": [
        {
            "message": "validation",
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "entries"
            ],
            "extensions": {
                "category": "validation",
                "validation": {
                    "filter": [
                        "Forbidden: _or"
                    ]
                }
            }
        }
    ],
    "data": {
        "entries": null
    }
}
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.35.0
PHP Version: 8.2.22
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: ####
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 2 (English, Arabic)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.42.0 PRO

Statamic Addons
isaadsalman/headless-refresh: 1.0.0
mitydigital/statamic-tinymce-cloud: 3.1.0
ndx/statamic-bard-color-picker: 2.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Is there any current way to use _or conditions in GraphQL? If not, is there an alternative or a planned fix for this issue?

Thank you for your help!
