### ISSUE TITLE
Validation errors trickle down replicator

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#11286]
### Bug description

In this page builder, you can see there's a validation error in a certain set. When I delete that set, the error trickles down to the next set in the replicator field. 
![2024-12-19 10 12 39](https://github.com/user-attachments/assets/8772fd74-1ecb-417f-9fa4-92f72e0d5f47)

### How to reproduce

1. Create a replicator
2. Cause a validation error in set 1
3. Remove set 1
4. See the validation error trickle down to set 2
5. And so forth

### Environment

```yaml
Environment
Application Name: Care About IT
Laravel Version: 10.48.25
PHP Version: 8.2.26
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: careaboutit.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Locales
Installed
Locales Version: 1.9.0
Protected

Localization
Installed: en, nl
LaravelLang\Attributes\Plugin: 2.11.2
LaravelLang\HttpStatuses\Plugin: 3.8.5
LaravelLang\Lang\Plugin: 13.12.0
Protected Locales: en
Publisher Version: 14.7.1

Livewire
Livewire: v3.5.17

Statamic
Addons: 5
Sites: 3 (English, Finnish, Dutch)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.44.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.8.1
studio1902/statamic-peak-browser-appearance: 3.6.0
studio1902/statamic-peak-commands: 2.7.0
studio1902/statamic-peak-seo: 7.5.0
studio1902/statamic-peak-tools: 3.4.3
```

### Installation

Fresh statamic/statamic site via CLI
