### ISSUE TITLE
Upgrade to 5.43.2 errors with "Target class [statamic.booted-addons] does not exist."

### ISSUE THREAD

**Issue by martyf** [statamic/cms#11284]
### Bug description

When running `composer update` from 5.43.0 to 5.43.2, the error occurred.

```bash
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Illuminate\Contracts\Container\BindingResolutionException 

  Target class [statamic.booted-addons] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:946
    942▕ 
    943▕         try {
    944▕             $reflector = new ReflectionClass($concrete);
    945▕         } catch (ReflectionException $e) {
  ➜ 946▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    947▕         }
    948▕ 
    949▕         // If the type is not instantiable, the developer is attempting to resolve
    950▕         // an abstract type such as an Interface or Abstract Class and there is

  1   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(MityDigital\StatamicGoogleFonts\ServiceProvider), "MityDigital\StatamicGoogleFonts\ServiceProvider")
      +14 vendor frames 

  16  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(MityDigital\StatamicGoogleFonts\ServiceProvider), "MityDigital\StatamicGoogleFonts\ServiceProvider")

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

It is not selective of what addon is used - I've tried on a clean install with our own addons, as well as those made by others. 

### How to reproduce

1. Do a clean install on 5.43.0
2. Install any addon
3. Run `composer update`

This also happens if you:
1. Do a clean install through `statamic new` (installs 5.43.2)
2. Try to install any addon

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.36.1
PHP Version: 8.3.14
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: fresh.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.43.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI
