### ISSUE TITLE
UI bugs in Safari 18.2 

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#11287]
### Bug description

In some update recently the select field and button group styling got degraded, at least in Safari.

**Select field**
<img width="171" alt="Screenshot 2024-12-19 at 10 23 04" src="https://github.com/user-attachments/assets/a43fb881-7029-4bac-866d-742ab22da687" />
The arrow part misses a border

**Button group**
<img width="238" alt="Screenshot 2024-12-19 at 10 23 18" src="https://github.com/user-attachments/assets/fedcc648-2667-451e-aea7-e16324a2a64a" />
There's hardly any contrast left for unselected items.

### How to reproduce

Check those fields.

### Environment

```yaml
Environment
Application Name: Statamic Peak Development
Laravel Version: 11.34.2
PHP Version: 8.2.26
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.42.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.6.0
studio1902/statamic-peak-commands: 8.12.0
studio1902/statamic-peak-seo: 8.18.0
studio1902/statamic-peak-tools: 6.6.0
```

### Installation

Fresh statamic/statamic site via CLI
