### ISSUE TITLE
Laravel Version: 11.34.2 mail send bug

### ISSUE THREAD

**Issue by dascwf** [statamic/cms#11296]
### Bug description

My other project ( **without Statamic** ) encountered an error when sending emails using Laravel Version: 11.34.2:
> [!WARNING]
> "The "" scheme is not supported; supported schemes for mailer 'smtp' are: 'smtp', 'smtps'." 

The sending code is similar to:

```php
Mail::to($recipientEmail)->send(function ($message) use ($data) {
``` 

This issue might have been caused by a dependency. **Later, I upgraded to Laravel Framework 11.36.1, and the problem was resolved.**

I am now facing the same issue when sending emails in Statamic 5.45.0.
Is it possible to upgrade the Laravel version, or can you tell me how to resolve this issue?

Thankyou

### How to reproduce

```php
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Mail;

Mail::to($recipientEmail)->send(function ($message) use ($data) {
  $message->subject('title');
  $message->from(config('mail.from.address'), config('mail.from.name'));
  $message->view('email.collaboration-inquiry', ['data' => $data]);
});
```

### Logs

```shell
[2024-12-21 09:38:44] dev.ERROR: The "" scheme is not supported; supported schemes for mailer "smtp" are: "smtp", "smtps". {"userId":1,"exception":"[object] (Symfony\\Component\\Mailer\\Exception\\UnsupportedSchemeException(code: 0): The \"\" scheme is not supported; supported schemes for mailer \"smtp\" are: \"smtp\", \"smtps\". at /home/git/app/page/vendor/symfony/mailer/Transport/Smtp/EsmtpTransportFactory.php:28)
```

### Environment

```yaml
Environment
Application Name: Page
Laravel Version: 11.34.2
PHP Version: 8.4.2
Composer Version: 2.8.4
Environment: dev
Debug Mode: ENABLED
URL: page.xx.com
Maintenance Mode: OFF
Timezone: *
Locale: *

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: page-mariadb-docker
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Disabled (auto)
Static Caching: Disabled
Version: 5.45.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
