### ISSUE TITLE
Only the default {{ template_content }} template will be parsed.

### ISSUE THREAD

**Issue by dascwf** [statamic/cms#11292]
### Bug description

As a result of my multiple attempts, including clearing the cache ( commands + rm files ) and other operations, I found that.
**Only the default {{ template_content }} template will be parsed**.

![1](https://github.com/user-attachments/assets/1d35c6f7-22df-4fc0-aaa8-ebd6026058ae)

![2](https://github.com/user-attachments/assets/2325a7a5-b822-4b40-a1a3-b6b68a1a8a0c)

![3](https://github.com/user-attachments/assets/5f38379a-9b4c-4c76-ac79-76c3cead38f8)

![4](https://github.com/user-attachments/assets/d64f431d-c4d6-4e0e-abe1-dcc29fceb0a9)

![5](https://github.com/user-attachments/assets/d62f0d3b-d384-4520-b30b-80be7d82a61d)

### How to reproduce

blueprints > add new Template > Handle: template_start
Create Entry > set template_start: body-collaborate.antlers.html

web page output: **body-collaborate**  ( tpl name )

### Logs
```
//content/collections/pages/collaborate.md
---
id: b6c89a36-b0bd-4b7d-be9d-7688bfe3a095
blueprint: page
title: collaborate
author: 1
updated_by: 1
updated_at: 1734705046
bg_header_mark: tech-1
duplicated_from: 3265b6ce-6c89-4338-bc57-447b2acf2e8b
body: body-collaborate
---
``` 
```
//content/collections/pages.yaml
title: Page
layout: separate
revisions: false
route: '{parent_uri}/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
```
### Environment

```yaml
Environment
Application Name: Page
Laravel Version: 11.34.2
PHP Version: 8.4.2
Composer Version: 2.8.4
Environment: dev
Debug Mode: ENABLED
URL: ********
Maintenance Mode: OFF
Timezone: ********
Locale: ********

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: page-mariadb-docker
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Disabled (auto)
Static Caching: Disabled
Version: 5.44.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
