### ISSUE TITLE
Group by date stuck in UTC

### ISSUE THREAD

**Issue by efc** [statamic/cms#11301]
### Bug description

The `group_by` parameter of `collection` seems to be stuck in UTC time when using `date`. This is evident if you include `e` time zone in your date format. The `since` and `until` parameters do use the proper time zone, only `group_by` seems to be stuck in UTC.

### How to reproduce

1. Set your `APP_TIMEZONE` to a non-UTC timezone.
2. Create a blog collection with dates.
3. Add a few entries who's date/time in the overlap that would make it a different month in UTC and the time zone you have selected. This would probably be something like 0:30am UTC time on the first or last day of a month.
4. Create a template that shows the collection grouped by month (`group_by="date|F Y e"`), filtered to show only one month (using `since` and `until`).
5. Observe that the group names will include the UTC timezone (thanks to the `e` in the `group_by` format) and that some of those entries that fall on the boundary between months will be displayed in the wrong month.

### Environment

```yaml
Environment
Application Name: Tensegrities
Laravel Version: 11.36.1
PHP Version: 8.3.14
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: mary.test/web
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 7
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.45.0 Solo

Statamic Addons
alt-design/alt-redirect: 1.3.3
heidkaemper/statamic-toolbar: 1.3.0
jacksleight/statamic-bonus-routes: 0.3.2
mitydigital/feedamic: 2.5.0
statamic/importer: 1.6.0
statamic/ssg: 3.1.0
trendyminds/statamic-palette: 1.2.1
```

### Installation

Fresh statamic/statamic site via CLI
