### ISSUE TITLE
Multisite (Collection Fieldtype): The deactivated field “Select Across Sites” is not always respected.

### ISSUE THREAD

**Issue by MitschF** [statamic/cms#11307]
### Bug description

Since english is not my first language, I need an example to explain the bug.

I have an Authors collection and an Articles collection in a multisite setup.

The authors are automatically created on all sites, but the articles are not. There is a relationship via an "Entries" field from authors to articles (With "Select Across Sites" disabled). If an author has an article in one language but not in another, this article is still displayed if the fields are in sync.

As far as I understand it, this behavior is incorrect if the “Select Across Sites” field is deactivated.

Because of this issue the following filter `articles:exists="true"` does not work properly. 
Authors with articles on any of the other sites are still displayed, even if the author does not have any article on the current site.

```
 {{ collection:authors paginate="60" articles:exists="true" as="authors" }}
        {{ partial:authors/list }}
 {{ /collection:authors }}
```

<img width="1650" alt="SCR-20250102-mssu" src="https://github.com/user-attachments/assets/6dfbe93b-c373-45d2-b9d1-7950392e7608" />
<img width="380" alt="SCR-20250102-mtds" src="https://github.com/user-attachments/assets/2858480b-6719-4218-816d-978066c894e6" />

### How to reproduce

1. You need a multisite-setup with at least two sites / languages
2. Create two collections (Ex. authors with _Propagate equals true_ and articles)
3. Create a relation (Entry-Field on authors-collection with "articles" as selected collection)
4. Make sure "Select Across Sites" is disabled
5. Create an author and an article
6. Add article to authors "article" field (see step 3)
7. Change site and visit authors page
8. The article is there but it should not

### Environment

```yaml
Environment
Application Name: OJC Web
Laravel Version: 11.35.1
PHP Version: 8.3.14
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: sendmail
Queue: sync
Session: file

Statamic
Addons: 11
Sites: 4 (OJC (ojc.de), DIJG (dijg.de), Salzkorn (ojc-salzkorn.de), hOffen (hoffen-magazin.de))
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.42.1 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.3.0
daun/statamic-placeholders: 3.0.1
eminos/statamic-iconify: 1.3.0
michaelmannucci/shades: 1.0.0
mitydigital/feedamic: 2.5.0
mitydigital/statamic-sticky-notes: 1.0.2
pecotamic/sitemap: 1.4.7
stillat/relationships: 2.2.1
swiftmade/statamic-clear-assets: 3.1.0
takepart-media/statamic-oreos: 1.3.0
webographen/statamic-admin-l
```

### Installation

Fresh statamic/statamic site via CLI
