### ISSUE TITLE
Custom indexes not used by all entry fields

### ISSUE THREAD

**Issue by efc** [statamic/cms#11308]
### Bug description

If I use the "select" or "typeahead" UI Mode for an Entry Field, then custom indexes don't seem to be consulted when selecting entries. Note that custom indexes _are_ consulted when using the "stack" UI Mode. 
This is probably a limitation of the kind of UI element being used for "select" and "typeahead" presentations, both of which seem to use variations of a dropdown select field. These usually only allow selection by the text shown in the field, which seems to be the "title" field.
It would be great if the custom indexes would work, or if, alternatively, a way were provided to define fields to be used for the text of these select fields so that they could be more flexible than simple titles.
At a minimum, it would help to have a warning on the UI Mode option that lets users know that only titles will be shown for anything other than "stack" presentations.

### How to reproduce

For example, in my case I have Courses that are linked from Student Projects.
In `/content/collections/courses.yaml` I have...
```yaml
search_index: courses
```
To keep this simple, in `/config/statamic/search.php` I am just trying a transform of the `title` field
```php
        'courses' => [
            'driver' => 'local',
            'searchables' => 'collection:courses',
            'fields' => ['title'],
            'transformers' => [
                'title' => function ($value, $searchable) {
                    if ($course = $searchable->value('course')) {
                        $value .= ' ' . $course['title'] . ' ' . $course['identifier'];
                    }
                    return $value;
                },
            ],
        ],
```
And, of course, I have done `php please search:update courses` to update the index.
But still, when I type one of the identifiers into the a course entry field in a related student projects entry, I get no hits, it just appears to search the titles that are visible in the dropdown.
<img width="378" alt="Screenshot 2025-01-02 at 1 53 04 PM" src="https://github.com/user-attachments/assets/4cb7dfd2-8bf9-4f92-ab18-4d34f3e706ef" />
However, in the list of course entries, I think this search is working, since I can now get hits from text that is not in the course title or slug.
<img width="384" alt="Screenshot 2025-01-02 at 1 53 35 PM" src="https://github.com/user-attachments/assets/4f8ba69e-7d81-4458-9fe9-6a1970fb83f6" />
I'd be happy to do something similar to the index transform or to create an alternative calculated field to be used in the select dropdown, but I don't see any way to do that.

### Environment

```yaml
Environment
Application Name: Tensegrities
Laravel Version: 11.36.1
PHP Version: 8.3.15
Composer Version: 2.8.3
Environment: local
Debug Mode: OFF
URL: mary.test
Maintenance Mode: OFF
Timezone: America/Chicago
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 6
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.45.0 Solo

Statamic Addons
alt-design/alt-redirect: 1.3.3
heidkaemper/statamic-toolbar: 1.3.0
statamic/importer: 1.6.0
statamic/ssg: 3.1.0
stillat/relationships: 2.2.1
trendyminds/statamic-palette: 1.2.1
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by efc** [comment]
By the way, I found a work-around, which is to make `title` computed and add to it the values I need there. I've created a `page_title` to hold what used to be in `title`. I don't know if there are some hidden side effects to computing the `title`, but it seems to be working for me. I still think some warning in the UI Mode instructions on Entry fields would be helpful.

**Comment by jasonvarga** [comment]
I would expect `select` to only filter by titles because your search doesn't go back up to the server.

But `typeahead` should be using the search index.

Can you show the configuration of that field?

**Comment by efc** [comment]
@jasonvarga, here is another example...

This is the definition of the entry field:
```yaml
            handle: course_entry
            field:
              max_items: 1
              collections:
                - courses
              type: entries
              display: Course
              search_index: courses
              width: 50
              mode: typeahead
```
Here is what it looks like as I type a word:
![Screenshot 2025-01-09 at 12 26 18 PM](https://github.com/user-attachments/assets/2a666607-81b3-4793-a760-33b545b01aa3)

And here is what a search for the same word looks like when I look at the collection in question:
![Screenshot 2025-01-09 at 12 25 48 PM](https://github.com/user-attachments/assets/4a8a067e-0faa-4082-8723-7956a288ca70)

So, yes, the entry field is set up with `typeahead` and, no, it is not benefiting from the custom search.
