### ISSUE TITLE
Can not order search results by origin value in multisite

### ISSUE THREAD

**Issue by marcorieser** [statamic/cms#11314]
### Bug description

Given a multisite with two sites: `de` (origin) and `en`.  

I'm using the search facade and I want to order the `posts` collection entries by `order_number` and `title`. None of the values are localized. The ordering works for the `de` site because all values are present in the `yaml` but the order is wrong for `en`. The order gets correct when I localize the values (the values are written to the `en` `yaml`).

My conclusion is that `orderBy()` does not work for inherited/origin values.

### How to reproduce

- Clone this repo: https://github.com/marcorieser/statamic-search-orderby
- Visit `routes/web.php` for the search logic
- Visit `/de` or `/en` for the result

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.37.0
PHP Version: 8.3.15
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: statamic-search-orderby.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 2 (German, English)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.45.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
