### ISSUE TITLE
Vite sources using hot reload in production instead of build

### ISSUE THREAD

**Issue by breizhwave** [statamic/cms#11317]
### Bug description

EVEN THOUGH I have build with npm run build, published, my online install suddenly renders as it was indebug mode with npm run dev which is not the case, how can I force use of build ? asking for  php please ssg:generate does not change anything
--
  | <script type="module" src="http://localhost:5173/@vite/client"></script><script type="module" src="http://localhost:5173/resources/js/site.js"></script><link rel="stylesheet" href="http://localhost:5173/resources/css/site.css" />
  | <script type="module" src="http://localhost:5173/@vite/client"></script><link rel="stylesheet" href="http://localhost:5173/resources/css/waveswiper.css" />

### How to reproduce

just copied resource, content via FTP and suddenly behaves as local with npm run dev

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.37.0
PHP Version: 8.2.20
Composer Version: 2.7.7
Environment: production
Debug Mode: OFF
URL: wave2025.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 6
Sites: 1
Stache Watcher: Disabled (auto)
Static Caching: Disabled
Version: 5.45.0 Solo

Statamic Addons
alt-design/alt-redirect: 1.3.3
alt-design/alt-seo: 1.2.2
heidkaemper/statamic-toolbar: 1.3.0
jacksleight/statamic-bard-texstyle: 3.4.1
krakero/tailwind-fieldtype: dev-main
statamic/ssg: 3.1.0
```

### Installation

Starter Kit using via CLI
