### ISSUE TITLE
Unable to Use Headings, Lists, or Formatting Options in Bard content element

### ISSUE THREAD

**Issue by xyNNN** [statamic/cms#11312]
### Bug description

In the Bard content element, I cannot use headings, lists, or any other elements. Clicking on the corresponding icons has no effect, and there are no JavaScript error messages. The only functionality that works is marking text as bold or italic. Attached is a video demonstrating the issue.

### How to reproduce

https://github.com/user-attachments/assets/7fd28150-3b64-41dd-aaf7-66de4a2de75d

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 11.35.1
PHP Version: 8.2.26
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: dev-mi-boda.com
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: NOT CACHED
Events: CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: redis
Database: pgsql
Logs: stack / single
Mail: smtp
Queue: sync
Session: redis

Pulse
Enabled: OFF
Version: v1.2.5

Livewire
Livewire: v3.5.8

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.9.0
PHP SDK Version: 4.9.0
Release: 25882060
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.45.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.18.0
statamic/seo-pro: 6.3.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Existing Laravel app
