### ISSUE TITLE
Commit via php artisan does not work with Laravel scheduler or Cronjob

### ISSUE THREAD

**Issue by sparmin** [statamic/cms#11318]
### Bug description

The [docs](https://statamic.dev/git-automation#scheduling-commits) offer a way to use Git Automation with Laravel Scheduler to consolidate changes. Unfortunately the php artisan command `php artisan statamic:git:commit` does not work via the Laravel Scheduler or Cronjob **_but_** it works when executing it manually via terminal.

I've set up two scheduler tasks in `console.php`: one for committing, one for pushing.

```
Schedule::command('statamic:git:commit')->everyTenMinutes()->appendOutputTo(storage_path('logs/git.log'));
Schedule::exec('git push')->everyTenMinutes()->appendOutputTo(storage_path('logs/git.log'));
```

The log file shows the success message saying "Content committed", but a `git status` proves that nothing has been committed. When executing `php artisan statamic:git:commit` manually in the terminal, it commits correctly and the second scheduled task of pushing also works.

To test it without the usage of schedulers, I've set up the two tasks as cronjobs:

```
* * * * * cd /home/ohostudi/public_html/laravel/firalux.ohodesign.ch/src && php artisan statamic:git:commit >> storage/logs/git.log
* * * * * cd /home/ohostudi/public_html/laravel/firalux.ohodesign.ch/src && git push >> storage/logs/git.log
```

The behaviour was the same: first one only returned a success message without actual commit, but after manual committing the push was successful.

When nothing is to be committed, the log message also says so accordingly. So it seems like the command is indeed executed, and also kinda works but not really.

I also don't think it's a git issue, since the commit and push work per se. 

### How to reproduce

Set up Git Automation. Use these settings in the `.env`:
```
STATAMIC_GIT_ENABLED=true
STATAMIC_GIT_AUTOMATIC=false
STATAMIC_GIT_PUSH=false
STATAMIC_GIT_DISPATCH_DELAY=
```
Set up the two scheduler tasks as shown above or the two cronjobs. Make a change in a tracked file. Track if the commit command was successful with `git status`.

### Environment

```yaml
Environment
Application Name: Firalux
Laravel Version: 11.34.2
PHP Version: 8.3.10
Composer Version: 2.8.3
Environment: production
Debug Mode: ENABLED
URL: firalux.ohodesign.ch
Maintenance Mode: OFF
Timezone: Europe/Zurich
Locale: de_CH

Cache
Config: NOT CACHED
Events: CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Sentry
Enabled: MISSING DSN
Environment: production
Laravel SDK Version: 4.10.1
PHP SDK Version: 4.10.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 4
Sites: 4 (Firalux - DE, Firalux - EN, Firalux - FR, Firalux - IT)
Stache Watcher: Disabled (auto)
Static Caching: half
Version: 5.41.0 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.3.0
mitydigital/statamic-two-factor: 2.4.1
statamic/eloquent-driver: 4.18.0
webographen/statamic-admin-log: 1.1.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Our host provider has several php functions disabled for security reason, for example exec(), shell_exec(), system(), dl() and passthru(). I've enabled them for testing purposes, but that didn't change anything. There might be possibly some other similar setting responsible, although I doubt it personally.
