### ISSUE TITLE
Content files are overwritten blank when added manually

### ISSUE THREAD

**Issue by tao** [statamic/cms#1132]
I've tried manually copying over some markdown files into the collections folder, as I've done with Statamic v2 before. I usually expect Statamic to add a new ID field to the meta data when a new file is detected. 

With v3 the entire file is wiped and only the new meta data ID remains.

For example all my files are in this format (filenames `1.1981-01-15.md`, `2.1981-01-17.md`, ...)
```
---
title: 'January 15th, 1981'
session: 1
---

Lorem ipsum dolor sit amet, consectetur adipiscing elit...

(Two-minute pause.)

Lorem ipsum dolor sit amet, consectetur adipiscing elit...

...
```

If I copy a couple of those files and reload Statamic then the files are overwritten like this and the content is gone, and the file names also change to `1981-01-15.md` and the order numbering removed.

```
---
id: f55d7ac5-44a4-4353-b36d-4708de9d7c16
---
```

**Comment by jasonvarga** [comment]
The order prefix isn't a thing anymore. The combination of that plus dates for slugs is probably confusing it.

The entry order is defined in the collection's yaml file under `entry_order`

```
entry_order:
  - this-entry-id
  - that-entry-id
```

**Comment by tao** [comment]
I'm using the numbers because I have some files that took place on the same date, so they need unique filenames.

For example 98 and 99 are the same date
```
97.1982-09-15.md
98.1982-09-24.md
99.1982-09-24.md
100.1982-11-18.md
```

I don't specifically care about the ordering in Statamic because I can use the `session` variable in the metadata, but I don't think I have a better way to name the files... I want to keep them in order on my filesystem too as I have a large amount.

I could change it like this but that looks strange to me...
```
1982-09-15.md
1982-09-24-01.md
1982-09-24-02.md
1982-11-18.md
```

What do you suggest?

**Comment by tao** [comment]
I could always use an underscore like `98__1982-09-24.md` if I need too, but clearing the files content is quite destructive so I thought I would raise the issue anyway.

**Comment by jasonvarga** [comment]
What did the site/content/collections/collection-name/folder.yaml look like in v2?

**Comment by tao** [comment]
previous folder.yaml
```
title: 'My Content Title'
order: number
template: mytemplatename
columns:
  -
    value: order
    header: Session
    width: 10
  -
    value: title
    link: true
  - slug
searchable:
  - title
  - content
fieldset: myfieldsetname
```

This is what the new collection yaml is like:
```
title: 'My Content Title'
route: 'session/{session}'
template: session/page
blueprints:
  - session
revisions: false
entry_order:
  - 2dd3b60f-b5ef-493d-8992-8106fb827ec8
  - c5888e0e-827a-4d11-8ffb-e6e299f59d16
  - f6522c13-375e-455d-90dc-3fed248ce797
  - e78c9203-e838-4567-98f9-531bb928a0ad
  - ca92330c-1043-4cc0-afad-701c43ce33f1
  - 3d06c76a-ca86-4429-8835-26f1fe417e39
  - 0cf42e2a-ecdb-4335-a128-d6daa0176d37
sort_dir: asc
date_behavior:
  past: public
  future: private
sites:
  - en
  - fr
```
I set up v3 for testing and made a couple of sessions in the control panel, then tried copying over the rest of my files manually (instead of using the migration tool) and I found it started clearing the file contents.
