### ISSUE TITLE
Git "auto-packing" errors

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#11325]
### Bug description

Seeing a non-error showing up as an actual error.

### How to reproduce

Use git feature, it'll show up eventually.

### Logs

```shell
Error: {"message":"Process Class: Git\nCommand: git -c "user.name=Navera Rehimtoola" -c "user.email=n.sabir@tarbiya.org" commit -m "Content saved"\nError: Auto packing the repository in background for optimum performance.\nSee "git help gc" for manual housekeeping.","context":[],"level":400,"level_name":"ERROR","channel":"production","datetime":"2025-01-07T12:08:42.113369-08:00","extra":[]}
```

### Environment

```yaml
Environment
Application Name: Zakat Foundation of America
Laravel Version: 11.37.0
PHP Version: 8.3.15
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: zakat.test
Maintenance Mode: OFF
Timezone: America/Los_Angeles
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: null
Cache: file
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.18

Statamic
Addons: 13
Sites: 4 (zakat.org (EN), zakat.org (AR), zfinstitute.com (ZFI), zakat.org (TR))
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.45.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.14.0
edalzell/forma: 3.0.1
jacksleight/statamic-bard-mutator: 2.3.1
jacksleight/statamic-distill: 0.8.2
jonassiewertsen/statamic-livewire: 3.8.1
statamic-rad-pack/runway: 7.13.4
statamic/seo-pro: 6.5.0
transformstudios/events: 5.4.4
transformstudios/front: 3.0.1
transformstudios/github: dev-main
transformstudios/neon: dev-main
transformstudios/review: 5.0
transformstudios/simple: 5.10.2
```

### Installation

Fresh statamic/statamic site via CLI
