### ISSUE TITLE
A Stache index file with wrong filename gets created on Stache:warm()

### ISSUE THREAD

**Issue by Krzemo** [statamic/cms#11323]
### Bug description

When running `Stache:warm()` a file `storage/framework/cache/data/stache/indexes/entries/{{ collection_handle }}/collection` gets created.

That file seems to be never used.

When making a first request to the site after `stache:refresh`, file `storage/framework/cache/data/stache/indexes/entries/{{ collection_handle }}/collectionHandle` is created. This is the correct file.

This can significantly add to response time depending on collection(s) size.

### How to reproduce

1. Run `stache:refresh`
2. Go to `storage/framework/cache/data/stache/indexes/entries/{{ collection_handle }}/` folder and list the files
3. Make a request to a page iterating through collection entries (`{{ collection }}` tag)
4. Check stache folder from point 2 again - `collectionHandle` file should be there now

### Environment

```yaml
Environment
Application Name: ainews
Laravel Version: 11.34.2
PHP Version: 8.3.15
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: ainews-v5.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en_US

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Cache: file
Database: pgsql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Disabled
Static Caching: half
Version: 5.45.0 PRO

Statamic Addons
statamic/collaboration: 1.0.0
statamic/seo-pro: 6.4.0
```

### Installation

Fresh statamic/statamic site via CLI
