### ISSUE TITLE
Dropdown Select Field (Vue Select) crashes when searching 'ui'

### ISSUE THREAD

**Issue by pixelastronauts** [statamic/cms#11330]
### Bug description

The Select field component in Statamic CP crashes when entering 'ui' in search, due to Vue Select attempting toLowerCase() on UI object.

## Status
✅ Fix submitted: sagalbot/vue-select#1861

## Technical Details
- Occurs in Vue Select component used by Statamic's Select field
- Caused by filterBy receiving UI object instead of string for 'ui' search
- Fixed by ensuring string conversion before toLowerCase()

## Impact
Affects search functionality in Select fields when entering specific string 'ui'

## Steps to reproduce
1. Open any Select field in Statamic CP
2. Type 'ui' in search box
3. Field crashes with TypeError

### Logs

```shell
## Error
TypeError: (be || "").toLocaleLowerCase is not a function
```

### Environment

```yaml
Environment
Application Name: Pixel Astronauts
Laravel Version: 11.37.0
PHP Version: 8.3.15
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: formyfoodies.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.18

Statamic
Addons: 10
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.45.0 PRO

Statamic Addons
jacksleight/statamic-memberbox: 2.1.3
joetannenbaum/antlers-stack-tags: 0.1.0
jonassiewertsen/statamic-livewire: 3.8.1
reachweb/statamic-livewire-filters: dev-main
statamic/eloquent-driver: 4.19.1
statamic/importer: 1.6.0
studio1902/statamic-peak-browser-appearance: 3.6.0
studio1902/statamic-peak-commands: 8.13.0
studio1902/statamic-peak-seo: 8.18.0
studio1902/statamic-peak-tools: 6.6.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
