### ISSUE TITLE
UX: Indicate the prefix value for fieldsets used in blueprints. 

### ISSUE THREAD

**Issue by adampatterson** [statamic/cms#11340]
### Bug description

When a field set is used multiple times, customize columns shows the field name as duplicates or as many times as the field set has been used.

### How to reproduce

* Create a fieldset called Base Contact, Add fields.
* In Blueprints, Create a CRM and B2B section.
* link the Base contact to CRM, and then to B2B this time adding a prefix of `b2b_`

A saved Entry will look something like this.

* name - Name
* phone - Phone
* email - Email
* b2b_name - Name
* b2b_phone - Phone
* b2b_email - Email

If you were to display this information in the table, you'd have `Name | Phone | Email | Name | Phone | Email`

![image](https://github.com/user-attachments/assets/1265d95a-c0fa-40c6-b758-968386e7ec9d)

![image](https://github.com/user-attachments/assets/6b130d09-16d4-4e42-a4d7-f97d91bf6067)

![image](https://github.com/user-attachments/assets/03e32480-64ea-45b5-9ec1-efd93f44f860)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.37.0
PHP Version: 8.2.24
Composer Version: 2.8.1
Environment: adam
Debug Mode: ENABLED
URL: tourism-calgary.adam.paperleaf.dev
Maintenance Mode: OFF
Timezone: America/Edmonton
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Sentry
Enabled: MISSING DSN
Environment: adam
Laravel SDK Version: 4.10.2
PHP SDK Version: 4.10.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 2
Sites: 1
Stache Watcher: Disabled (auto)
Static Caching: Disabled
Version: 5.45.1 PRO

Statamic Addons
goldnead/statamic-collapse-fieldtype: 1.1
statamic/eloquent-driver: 4.19.1

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

As a really crude example, showing a small indication of the prefix name would go a long way to clarify the labels. 
![image](https://github.com/user-attachments/assets/12b1f73a-de97-4cc0-95f7-9b8fbad4633f)
