### ISSUE TITLE
Default values not working after saving

### ISSUE THREAD

**Issue by andjsch** [statamic/cms#11355]
### Bug description

https://github.com/user-attachments/assets/0cee4020-c518-409e-9f87-8da8aeb4005e

When having a grid fieldtype that only shows on some condition (e.g. a toggle set to true) and having set ``Always save`` to false, the Stache behaves weird after saving an entry when it comes to default values.

The default value is not shown after editing and saving an entry and setting the toggle to ``true`` again, even though the grid field hasn't been saved to the file. I would expect the default value to show once the field is shown again.

### How to reproduce

Create a blueprint with the following example:
```yaml
  -
    handle: has_nutrition_table
    field:
      type: toggle
      display: 'Show nutrition table'
  -
    handle: nutrition_table
    field:
      type: grid
      display: 'Nutrition table'
      default:
        -
          name: Sugar
        -
          name: Salt
      always_save: false
      if:
        has_nutrition_table: 'equals true'
      fields:
        -
          handle: name
          field:
            type: text
            display: Name
            width: 33
        -
          handle: detail
          field:
            type: text
            display: Detail
            width: 66
```

Create an entry and see the field showing/hiding depending on the toggle state. Now save the entry with the grid being hidden. Reload the tab and set the toggle to true. You get an empty grid, instead of the prepopulated one. I would expect it to have the default values.

Once the stache has been cleared, everything works again as expected.

### Environment

```yaml
Environment
Application Name: Steiermarkt
Laravel Version: 11.34.2
PHP Version: 8.3.15
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: steiermarkt.test
Maintenance Mode: OFF
Timezone: Europe/Vienna
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.15

Statamic
Addons: 5
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.41.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.8.1
schantldev/shop: dev-main
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-seo: 8.17.0
studio1902/statamic-peak-tools: 6.5.0
```

### Installation

Fresh statamic/statamic site via CLI
