### ISSUE TITLE
Nav blueprint sections should hide when empty

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#11359]
### Bug description

If you use conditions on navigation blueprint fields, you'd probably expect blueprint sections to auto-hide whenever there's no fields in it, just like in collection blueprints (#9137).

<img width="390" alt="Screenshot 2025-01-15 at 15 57 28" src="https://github.com/user-attachments/assets/55f22dee-e88d-4bd2-9f8a-bb0dfd9a5d4b" />

### How to reproduce

1. Create a section in a nav blueprint.
2. Make a conditional field.
3. See the empty section when the condition doesn't pass.

### Environment

```yaml
Environment
Application Name: De Kinderacademie
Laravel Version: 11.37.0
PHP Version: 8.2.27
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: dekinderacademie.test
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.45.1 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.6.0
studio1902/statamic-peak-commands: 8.15.1
studio1902/statamic-peak-seo: 8.19.0
studio1902/statamic-peak-tools: 6.6.0
```

### Installation

Starter Kit using via CLI

**Comment by robdekort** [comment]
Ah gotcha, this makes me realize my setup is a bit different as the field is hidden initially based on depth. This is the blueprint:

```yaml
tabs:
  main:
    display: Main
    sections:
      -
        display: General
      -
        display: Styling
        fields:
          -
            handle: render_as_button
            field:
              type: toggle
              display: 'Render as button'
              if:
                depth: '< 2'
```
