### ISSUE TITLE
Inconsistent Filename Behavior on duplicated entries in Collections with Publish Date and Multisite

### ISSUE THREAD

**Issue by ansovi** [statamic/cms#11360]
### Bug description

In a multisite setup with three languages (German, French, English), there is inconsistent behavior when using the duplication functionality in a collection where the publish date is enabled.

### How to reproduce

1. Set up a multisite installation with German as the default language and French and English as additional languages.
2. Create a collection where the publish date is enabled.
3. Create a new entry in this collection:

- The file in the default language (German in my case) includes the date in the filename (e.g., 2025-01-15.new-entry.md).
- The files for other languages (French, English) do not include the date in the filename (e.g., new-entry.md).

6. Duplicate the entry within the collection:

- For each language, a file with the full filename, including the date, is created (e.g., 2025-01-15.new-entry-1.md).

8. Change the publish date (It's not localized so just in the default language)

**Expected Behavior:**
When changing the publish date in the default language, the filenames in all languages should be updated consistently.

**Actual Behavior:**
Only the filename of the default language (German in my case) is updated. The filenames of the other languages 
remain unchanged, leading to different publish dates across languages.

![Bildschirmfoto 2025-01-15 um 15 31 20](https://github.com/user-attachments/assets/ab1656ac-cad5-446a-a12f-269091519323)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.38.2
PHP Version: 8.4.2
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: Europe/Zurich
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 3 (Deutsch, Französisch, Englisch)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.45.1 PRO
Statamic Version: 5.45.1
```

### Installation

Existing Laravel app
