### ISSUE TITLE
"type" attribute is unnecessary for javascript resources #11366

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#11370]
### Bug description

"type" attribute is unnecessary for javascript resources since HTML5. 

Reference: https://html.spec.whatwg.org/multipage/scripting.html#attr-script-type

### How to reproduce

Use the `{{ nocache }} ` tag whith static caching.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Website
Laravel Version: 11.38.2
PHP Version: 8.3.14
Composer Version: 2.8.4
Environment: development
Debug Mode: ENABLED
URL: website.test
Maintenance Mode: OFF
Timezone: Europe/Paris
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Disabled (auto)
Static Caching: Disabled
Version: 5.45.1 PRO

Statamic Addons
rias/statamic-redirect: 3.9.2
spatie/statamic-responsive-images: 5.2.1
statamic/seo-pro: 6.5.0
```

### Installation

Fresh statamic/statamic site via CLI
