### ISSUE TITLE
The `depth` value in nav blueprint isn't being live updated

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#11378]
### Bug description

When you add/reorder nav items in the nav blueprint editor, the `depth` value isn't being live updated but only updated after a save + reload.

### How to reproduce

1. Add a field to your nav blueprint with the following condition:

```yaml
-
  handle: render_as_button
  field:
    type: toggle
    display: 'Render as button'
    if:
      depth: 'equals 1'
```

2. Add an item to your nav on the first level.
3. See the toggle.
4. Move the item to a second level.
5. See the toggle
6. Save
7. Reload
8. See the toggle is properly hidden.

### Environment

```yaml
Environment
Application Name: De Kinderacademie
Laravel Version: 11.38.2
PHP Version: 8.2.27
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: dekinderacademie.test
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.45.2 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.6.0
studio1902/statamic-peak-commands: 8.15.1
studio1902/statamic-peak-seo: 8.19.0
studio1902/statamic-peak-tools: 6.7.1
```

### Installation

Starter Kit using via CLI
