### ISSUE TITLE
Inconsistent behavior when using custom nav field conditions based on `depth`

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#11379]
### Bug description

Possibly related to #11359?

In a nav blueprint, the following condition using `< 2` works. The field is only visible on level 1:

```yaml
tabs:
  main:
    display: Main
    sections:
      -
        display: General
      -
        display: Styling
        fields:
          -
            handle: render_as_button
            field:
              type: toggle
              display: 'Render as button'
              if:
                depth: '< 2'
```

The following condition using `equals 1` doesn't work. The field is not visible on any level:

```yaml
tabs:
  main:
    display: Main
    sections:
      -
        display: General
      -
        display: Styling
        fields:
          -
            handle: render_as_button
            field:
              type: toggle
              display: 'Render as button'
              if:
                depth: 'equals 1'
```

When we don't use a section, either of these blueprints and conditions will work as expected:

```yaml
tabs:
  main:
    display: Main
    sections:
      -
        display: General
        fields:
          -
            handle: render_as_button
            field:
              type: toggle
              display: 'Render as button'
              if:
                depth: '< 2'
```

```yaml
tabs:
  main:
    display: Main
    sections:
      -
        display: General
        fields:
          -
            handle: render_as_button
            field:
              type: toggle
              display: 'Render as button'
              if:
                depth: 'equals 1'
```

### How to reproduce

Play with the blueprints above.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: De Kinderacademie
Laravel Version: 11.38.2
PHP Version: 8.2.27
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: dekinderacademie.test
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.45.2 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.6.0
studio1902/statamic-peak-commands: 8.15.1
studio1902/statamic-peak-seo: 8.19.0
studio1902/statamic-peak-tools: 6.7.1
```

### Installation

Starter Kit using via CLI
