### ISSUE TITLE
{{ search:results offset="1" paginate="10" }} returns an error

### ISSUE THREAD

**Issue by nopticon** [statamic/cms#11382]
### Bug description

Using this search tag {{ search:results as="results" offset="1" paginate="10" }} displays an error.

`Call to undefined method Statamic\Search\Result::id()`

If I remove `paginate` or `offset`, it displays the search results correctly.

### How to reproduce

Stack trace at https://flareapp.io/share/47qjLp35

Create a simple view file with this content:

```
{{ search:results as="results" offset="1" paginate="10" }}
    {{ if results }}
    <ul>
        {{ results }}
        <li>{{ title }}</li>
        {{ /results }}
    </ul>
    {{ /if }}
{{ /search:results }}

```

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.39.1
PHP Version: 8.3.15
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: a.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.46.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
