### ISSUE TITLE
Incorrectly rendered 404 page (URL encoding problem)

### ISSUE THREAD

**Issue by Jubeki** [statamic/cms#11387]
### Bug description

Visiting the URL with the path `/%c0` results in the rendering engine not working properly and the page is not displayed correctly (with the blade engine it can even result in an 500 error).

I expected a normal 404 page to be rendered.

(I used the blade engine and got a 500 error reported via sentry, that is why I began investigating)

### How to reproduce

1. Create a new statamic application.
2. Update the `404.antlers.html` to the following: `<p>404 Page not found. {{ site:short_locale }}</p>`
3. Serve the Application (`php artisan serve`)
4. Visit http://localhost:8000/awd and see a correctly rendered 404 page
5. Visit http://localhost:8000/%c0 and see an incorrectly rendered 404 page (no site short locale rendered and the 404 is on the top left and not in the middle.

If you rename the file `404.antlers.html` to `404.blade.php` and set the content to `<p>404 Page not found. {{ $site->short_locale }}</p>` you receive a 500 error with `Undefined variable $site`.
It works correctly on the URL http://localhost:8000/awd

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.39.1
PHP Version: 8.3.16
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: statamic-bug.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.46.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
