### ISSUE TITLE
Search results missing "search_snippets"

### ISSUE THREAD

**Issue by ivang76** [statamic/cms#11398]
### Bug description

I noticed that if I search for two words, the **search_snippets** array is populated only when the item found contains both words (even if they aren't on the same line). However, if the search result contains only one of the searched words, the search_snippets array remains empty.
I'm using the the native local driver, not algolia.

Is this some kind of limitation, a bug, or could I be missing some configuration parameters in the indexes?

Thanks!

### How to reproduce

Simply create an index, for example my _pages_ below, on the collection of static pages, and then run a search using two or more words to find (choosing them knowing that only one is present on a specific target page).

`'pages' => [
    'driver' => 'local',
    'searchables' => 'collection:*',
    'fields' => ['title','main_body','description_block'],
],`

Then dump the results and look into the structure, checking the search_snippets array, you will find an empty one.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: BAAM
Laravel Version: 11.34.2
PHP Version: 8.3.9
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: localhost:8000
Maintenance Mode: OFF
Timezone: Europe/Zurich
Locale: it

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.16

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.10.1
PHP SDK Version: 4.10.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 7
Sites: 2 (it, en)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.46.0 PRO

Statamic Addons
alt-design/alt-redirect: 1.6.1
anakadote/statamic-recaptcha: 1.0.16
eminos/statamic-tabs: 1.2.0
jacksleight/statamic-bard-texstyle: 3.4.1
ryanmitchell/statamic-translation-manager: 1.6.0
sortarad/extraextra: 1.0.1
statamic-rad-pack/runway: 7.13.4
```

### Installation

Fresh statamic/statamic site via CLI
