### ISSUE TITLE
Form field with handle `url` as displayed column breaks CP form listing

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#11394]
### Bug description

When you have a field called `url` in your form blueprint and you enable the field as a displayed column in the CP listing, like this:
<img width="613" alt="Image" src="https://github.com/user-attachments/assets/2749919e-9d16-4d07-925b-7c74589a7ab2" />

The link in the listing breaks, it uses the value of the `url` field. 
<img width="441" alt="Image" src="https://github.com/user-attachments/assets/0530593b-22dd-4fcf-b15f-a2c906d6f0de" />

The link will either take you to the website that has been used as a value if it is a website, or it causes a 404 in the CP.
<img width="1499" alt="Image" src="https://github.com/user-attachments/assets/e96cf3c7-38f3-4520-a268-5e1482e16d0b" />

### How to reproduce

1. Add a field called `url` to your form blueprint
2. Enable the field as a displayed column
3. Fill in a form
4. Try to reach the form details from the listing view
5. Chuckle

### Environment

```yaml
Environment
Application Name: Statamic Peak Development
Laravel Version: 11.39.1
PHP Version: 8.2.27
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test/
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.45.2 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.6.0
studio1902/statamic-peak-commands: dev-main
studio1902/statamic-peak-seo: 8.19.0
studio1902/statamic-peak-tools: 6.7.1
```

### Installation

Starter Kit using via CLI
