### ISSUE TITLE
Deleting a form record successfully but get "Item could not be deleted" flash message

### ISSUE THREAD

**Issue by alantucker** [statamic/cms#11406]
### Bug description

When deleting an entry from my contact form (successfully deleted), I get a flash message at the bottom left corner of my browser window: "Item could not be deleted."

### How to reproduce

Specific to a form created on my local machine. I have not tested with a second form, but I can do it if you can not replicate the problem. Please note that I am storing everything in the database, e.g. forms and blueprints.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.41.0
PHP Version: 8.3.16
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: untitleddigital.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.46.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.19.1
statamic/ssg: 3.1.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

No errors were thrown in the log file.
