### ISSUE TITLE
"Array to string conversion" in CP if a translation file exists with the same name as a breadcrumb

### ISSUE THREAD

**Issue by SanderFlooris** [statamic/cms#11418]
### Bug description

We are currently migrating an existing application from Statamic 3 to Statamic 5 and while testing everything, we discovered that the control panel no longer seems to work properly when trying to open any item from the Pages collection.

After a bit of digging inside the source code it seems like it's caused because the breadcrumbs are translated, but because the breadcrumb "Pages" also matches our `pages.php` translation file, it returns an array of translations, which is something the code is not expecting when trying to implode it.

**Relevant files**
- `vendor/statamic/cms/src/CP/Breadcrumbs.php`
- `vendor/statamic/cms/resources/views/entries/edit.blade.php`

### How to reproduce

1. Create the translation file `lang/en/pages.php`
2. Fill the translations file with something, ours is as follows
    ```php
    <?php
    
    return [
        'opening-hours' => [
            'opening_hours' => 'Opening hours',
            'show_garden' => 'Show garden',
            'phone' => 'Phone',
            'this_week' => 'This week',
            'next_week' => 'Next week',
            'currently_open' => 'Currently open',
            'currently_closed' => 'Currently closed',
        ],
        'homepage' => [
            'featured_products' => 'Featured products',
            'knowledge_base' => 'Knowledge base',
            'brands' => 'Featured brands',
            'categories' => 'Categories',
        ],
    ];
    ```
4. Open the CP and try to open an item inside the `pages` collection
5. You should now get a HTTP 500 from the `vendor/statamic/cms/resources/views/entries/edit.blade.php`

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: REDACTED
Laravel Version: 11.35.1
PHP Version: 8.3.15
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: REDACTED.localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: nl

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Scout: algolia
Session: file

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.10.0
PHP SDK Version: 4.10.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.46.1 PRO

Statamic Addons
flooris/REDACTED-frontend-routes: dev-update/TT-1116-major-updates
flooris/REDACTED-model-management: dev-update/TT-1116-major-updates
statamic/seo-pro: 6.3.0
```

### Installation

Existing Laravel app

### Additional details

Discovered during a migration from Statamic 3 to 5.

I also removed the name of the project inside the environment section, which is most likely not relevant to the issue.
