### ISSUE TITLE
Separate guard for Statamic with database sessions does not function

### ISSUE THREAD

**Issue by Jamesking56** [statamic/cms#11411]
### Bug description

If you add Statamic to an existing Laravel app and want your Statamic users to be flat-file but use a separate guard (so you can separate Statamic login access vs. your app users), you cannot login to CP when `SESSION_DRIVER` is set to `database`. The CP login screen just refreshes when given correct credentials.

I followed this guide to setup the separate Statamic guard:

https://statamic.dev/tips/using-an-independent-authentication-guard

But it appears not to work correctly.

### How to reproduce

Reproduction Steps:

1. Install Laravel 11 and set `SESSION_DRIVER` to `database` in `.env`
2. Add Statamic to Laravel 11 install
3. Change user storage to `file` instead of `eloquent` and create a test user
4. Configure separate guard for Statamic following this guide: https://statamic.dev/tips/using-an-independent-authentication-guard
5. Attempt to login to CP with your test user account and you should see that the login screen just refreshes.

I've already followed these on a fresh Laravel install and provided a repo with separate commits so you can step through the changes I've made:

https://github.com/Jamesking56/statamic-session-bug

(You can use `john.doe@example.com` and `password` to attempt login to CP)

Set `SESSION_DRIVER` to `database` in your `.env` and you can replicate the issue, the bug does not occur when `SESSION_DRIVER` is set to `file`.

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 11.41.3
PHP Version: 8.3.16
Composer Version: 2.8.5
Environment: local
Debug Mode: ENABLED
URL: test.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: database
Database: mariadb
Logs: stack / single
Mail: log
Queue: database
Session: database

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.46.0 PRO
```

### Installation

Existing Laravel app
