### ISSUE TITLE
user tag is null when use Independent auth guard

### ISSUE THREAD

**Issue by danielreales7** [statamic/cms#11438]
### Bug description

I'm using: independent auth guards with Laravel 11. Instead of using the default user:login_form I created a custom one using Livewire. User login works perfectly in the frontend with database users and CP with flatfile. The problem occurs when I need to get the data of the logged in user from the frontend.

```php
{{ if logged_in }}
    {{ user }}
        Welcome back! {{ name }}.
    {{ /user }}
{{ /if }}
```

It's really funny how it goes into user and shows me Welcome back! but without the name. If y try {{ user | dump }} It doesn't show anything either. User::current() is null and I don't know what could be wrong.

### How to reproduce

[https://github.com/danielreales7/guard-statamic](https://github.com/danielreales7/guard-statamic)

In this repository if you go to /register page and create a new user after registration redirect to profile page.

I think the problem is related to the fact that the variable {{ user }} comes from the UserRepository of statamic. Is this how it works? Can it be changed if I use the UserRepository for the database data?

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Test
Laravel Version: 11.41.3
PHP Version: 8.3.13
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: guard-statamic.test
Maintenance Mode: OFF
Timezone: UTC
Locale: es

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Livewire
Livewire: v3.5.19

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.46.1 PRO

Statamic Addons
marcorieser/statamic-livewire: 4.0.0
studio1902/statamic-peak-browser-appearance: 3.6.0
studio1902/statamic-peak-commands: 8.16.1
studio1902/statamic-peak-seo: 8.19.0
studio1902/statamic-peak-tools: 7.1.0
```

### Installation

Starter Kit using via CLI
