### ISSUE TITLE
Asset field loses upload text when 50% width on smaller viewports

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#11436]
### Bug description

If you have an asset field that's 50% width and you make the viewport smaller you lose the "Upload file or drop..." text.

### How to reproduce

1. Add 2 asset fields side by side, each 50% width
2. Decrease the window size

![Image](https://github.com/user-attachments/assets/5985c98f-6add-43e4-90fd-f97070b4d518)

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.41.3
PHP Version: 8.3.16
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: asset-field.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.46.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI
