### ISSUE TITLE
Database cache is used prior to database cache tables existence on composer install

### ISSUE THREAD

**Issue by Jamesking56** [statamic/cms#11449]
### Bug description

When running `composer install` on a Statamic site which uses database as a cache, it errors because Statamic is running a cache lookup before Laravel's cache tables exist (since we haven't migrated yet)

### How to reproduce

1. Create a new Laravel project, completing the usual Laravel installation
2. Install Statamic as normal
3. Install a marketplace package (we used SEO Pro but I don't think it matters which package)
4. Change `CACHE_STORE` to `database` in `.env`
5. Remove `vendor` directory
6. Run `composer install`
7. 🔥 Exception occurs during installation

### Logs

```shell
Illuminate\Database\QueryException 

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.cache' doesn't exist (Connection: mysql, SQL: select * from `cache` where `key` in (marketplace-packages/statamic/seo-pro/6.5.0))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:825
    821▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    822▕                 );
    823▕             }
    824▕ 
  ➜ 825▕             throw new QueryException(
    826▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    827▕             );
    828▕         }
    829▕     }

  1   [internal]:0
      Statamic\Extend\Manifest::Statamic\Extend\{closure}()

  2   vendor/laravel/framework/src/Illuminate/Database/Connection.php:407
      PDOException::("SQLSTATE[42S02]: Base table or view not found: 1146 Table 'core.cache' doesn't exist")

  3   vendor/laravel/framework/src/Illuminate/Database/Connection.php:407
      PDO::prepare()

  4   vendor/laravel/framework/src/Illuminate/Database/Connection.php:812
      Illuminate\Database\Connection::Illuminate\Database\{closure}()

  5   vendor/laravel/framework/src/Illuminate/Database/Connection.php:779
      Illuminate\Database\Connection::runQueryCallback()

  6   vendor/laravel/framework/src/Illuminate/Database/Connection.php:398
      Illuminate\Database\Connection::run()

  7   vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:3106
      Illuminate\Database\Connection::select()

  8   vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:3091
      Illuminate\Database\Query\Builder::runSelect()

  9   vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:3676
      Illuminate\Database\Query\Builder::Illuminate\Database\Query\{closure}()

  10  vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:3090
      Illuminate\Database\Query\Builder::onceWithColumns()

  11  vendor/laravel/framework/src/Illuminate/Cache/DatabaseStore.php:130
      Illuminate\Database\Query\Builder::get()

  12  vendor/laravel/framework/src/Illuminate/Cache/DatabaseStore.php:105
      Illuminate\Cache\DatabaseStore::many()

  13  vendor/laravel/framework/src/Illuminate/Cache/Repository.php:117
      Illuminate\Cache\DatabaseStore::get()

  14  vendor/laravel/framework/src/Illuminate/Cache/Repository.php:88
      Illuminate\Cache\Repository::get()

  15  vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php:453
      Illuminate\Cache\Repository::has()

  16  vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:361
      Illuminate\Cache\CacheManager::__call()

  17  vendor/statamic/cms/src/Providers/CacheServiceProvider.php:73
      Illuminate\Support\Facades\Facade::__callStatic()

  18  vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:126
      Illuminate\Cache\Repository::Statamic\Providers\{closure}()

  19  vendor/laravel/framework/src/Illuminate/Cache/Repository.php:789
      Illuminate\Cache\Repository::macroCall()

  20  vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php:453
      Illuminate\Cache\Repository::__call()

  21  vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:361
      Illuminate\Cache\CacheManager::__call()

  22  vendor/statamic/cms/src/Marketplace/Marketplace.php:22
      Illuminate\Support\Facades\Facade::__callStatic()

  23  vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:361
      Statamic\Marketplace\Marketplace::package()

  24  vendor/statamic/cms/src/Extend/Manifest.php:53
      Illuminate\Support\Facades\Facade::__callStatic()

  25  vendor/statamic/cms/src/Extend/Manifest.php:28
      Statamic\Extend\Manifest::formatPackage()

  26  [internal]:0
      Statamic\Extend\Manifest::Statamic\Extend\{closure}()
  27  vendor/laravel/framework/src/Illuminate/Collections/Arr.php:609

  28  vendor/laravel/framework/src/Illuminate/Collections/Collection.php:799
      Illuminate\Support\Arr::map()

  29  vendor/statamic/cms/src/Extend/Manifest.php:27
      Illuminate\Support\Collection::map()

  30  vendor/statamic/cms/src/Console/Commands/AddonsDiscover.php:35
      Statamic\Extend\Manifest::build()

  31  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
      Statamic\Console\Commands\AddonsDiscover::handle()

  32  vendor/laravel/framework/src/Illuminate/Container/Util.php:43
      Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()

  33  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:95
      Illuminate\Container\Util::unwrapIfClosure()

  34  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:35
      Illuminate\Container\BoundMethod::callBoundMethod()

  35  vendor/laravel/framework/src/Illuminate/Container/Container.php:696
      Illuminate\Container\BoundMethod::call()

  36  vendor/laravel/framework/src/Illuminate/Console/Command.php:213
      Illuminate\Container\Container::call()

  37  vendor/symfony/console/Command/Command.php:279
      Illuminate\Console\Command::execute()

  38  vendor/laravel/framework/src/Illuminate/Console/Command.php:182
      Symfony\Component\Console\Command\Command::run()

  39  vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php:68
      Illuminate\Console\Command::run()

  40  vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php:29
      Illuminate\Console\Command::runCommand()

  41  vendor/statamic/cms/src/Console/Commands/Install.php:49
      Illuminate\Console\Command::call()

  42  vendor/statamic/cms/src/Console/Commands/Install.php:38
      Statamic\Console\Commands\Install::addons()

  43  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
      Statamic\Console\Commands\Install::handle()

  44  vendor/laravel/framework/src/Illuminate/Container/Util.php:43
      Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()

  45  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:95
      Illuminate\Container\Util::unwrapIfClosure()

  46  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:35
      Illuminate\Container\BoundMethod::callBoundMethod()

  47  vendor/laravel/framework/src/Illuminate/Container/Container.php:696
      Illuminate\Container\BoundMethod::call()

  48  vendor/laravel/framework/src/Illuminate/Console/Command.php:213
      Illuminate\Container\Container::call()

  49  vendor/symfony/console/Command/Command.php:279
      Illuminate\Console\Command::execute()

  50  vendor/laravel/framework/src/Illuminate/Console/Command.php:182
      Symfony\Component\Console\Command\Command::run()

  51  vendor/symfony/console/Application.php:1094
      Illuminate\Console\Command::run()

  52  vendor/symfony/console/Application.php:342
      Symfony\Component\Console\Application::doRunCommand()

  53  vendor/symfony/console/Application.php:193
      Symfony\Component\Console\Application::doRun()

  54  vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:198
      Symfony\Component\Console\Application::run()

  55  vendor/laravel/framework/src/Illuminate/Foundation/Application.php:1235
      Illuminate\Foundation\Console\Kernel::handle()

  56  artisan:13
      Illuminate\Foundation\Application::handleCommand()

Script @php artisan statamic:install --ansi handling the post-autoload-dump event returned with error code 1
```

### Environment

```yaml
Environment
Application Name: --snip--
Laravel Version: 11.42.0
PHP Version: 8.3.16
Composer Version: 2.8.5
Environment: local
Debug Mode: ENABLED
URL: --snip--
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: database
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: database

Pulse
Enabled: ENABLED
Version: v1.4.0

Livewire
Livewire: v3.5.19

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.12.0
PHP SDK Version: 4.10.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Spatie Permissions
Features Enabled: Teams
Version: 6.13.0

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.46.1 PRO

Statamic Addons
statamic/seo-pro: 6.5.0
visuellverstehen/statamic-classify: 3.0.0
```

### Installation

Existing Laravel app

### Additional details

To workaround this, we are having to set `CACHE_STORE` to `file` just for the initial install, then changing to `database` prior to running Laravel's migrations.
