### ISSUE TITLE
parent_uri is not useful in some cases

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#11445]
### Bug description

parent_uri works fine when have a simple top-level route for the collection, e.g.:
Route:
`{parent_uri}/{slug}`

However, if the route contains a prefixed segment (e.g. products) then `parent_uri` is not useful at all.
`products/{parent_uri}/{slug}`

The above produces urls like so:
/products/products/product1/product2

Note that /products/ is duplicated in the abovewhen it should just be:
/products/product1/product2

It doesn't seem possible to just use the slug of the parent? e.g.
`products/{parent:slug}/{slug}`

### How to reproduce

Set up parent child routing structure with a url segment prefixed.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: mysite
Laravel Version: 11.41.3
PHP Version: 8.3.15
Composer Version: 2.7.4
Environment: local
Debug Mode: ENABLED
URL: mysite.test
Maintenance Mode: OFF
Timezone: Europe/Dublin
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Livewire
Livewire: v3.5.19

Statamic
Addons: 8
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.46.1 Solo

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.4.1
jonassiewertsen/statamic-live-search: 2.1.1
jonassiewertsen/statamic-livewire: 3.8.1
rias/statamic-redirect: 3.9.3
spatie/statamic-responsive-images: 5.2.1
statamic/seo-pro: 6.5.0
stuartcusackie/statamic-cache-requester: 1.2.7
```

### Installation

Fresh statamic/statamic site via CLI
