### ISSUE TITLE
Parent listable not working on some collections

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#11444]
### Bug description

One my 'pages' collection I have a parent field like so:

```
-
  handle: parent
  field:
    type: entries
    collections:
      - pages
     max_items: 1
     listable: true
     localizable: true
```

And this works fine as being a listable column:
<img width="620" alt="Image" src="https://github.com/user-attachments/assets/67f3b481-da96-4796-8b97-1022b02493b2" />

However, on my 'product_categories' collection I have a parent field like so:

```
-
  handle: parent
  field:
    type: entries
    collections:
      - product_categories
    max_items: 1
   listable: true
   localizable: true
```

And none of the 'parent' colums are filled
<img width="647" alt="Image" src="https://github.com/user-attachments/assets/dbc736bb-006b-48fe-8831-67f42e5cc880" />

### How to reproduce

No idea

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: mysite
Laravel Version: 11.41.3
PHP Version: 8.3.15
Composer Version: 2.7.4
Environment: local
Debug Mode: ENABLED
URL: mysite.test
Maintenance Mode: OFF
Timezone: Europe/Dublin
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Livewire
Livewire: v3.5.19

Statamic
Addons: 8
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.46.1 Solo

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.4.1
jonassiewertsen/statamic-live-search: 2.1.1
jonassiewertsen/statamic-livewire: 3.8.1
rias/statamic-redirect: 3.9.3
spatie/statamic-responsive-images: 5.2.1
statamic/seo-pro: 6.5.0
stuartcusackie/statamic-cache-requester: 1.2.7
```

### Installation

Fresh statamic/statamic site via CLI
