### ISSUE TITLE
Error when calling `toArray` on revisions of an entry

### ISSUE THREAD

**Issue by lostgeek** [statamic/cms#11454]
### Bug description

Calling `$entry->revisions()->toArray()` causes an Error:
```pathinfo(): Argument #1 ($path) must be of type string, Statamic\Revisions\Revision given```

Raying the result of `$entry->revisions()` yields: 
<img width="404" alt="Image" src="https://github.com/user-attachments/assets/2c55c78f-9143-4b67-a236-4469b01b2d26" />

### How to reproduce

Calling `$entry->revisions()->toArray()` on any revision-enabled entry with revisions.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: desitin-cms
Laravel Version: 11.42.1
PHP Version: 8.3.15
Composer Version: 2.8.1
Environment: local
Debug Mode: ENABLED
URL: desitin-cms.novu.io
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: pgsql
Logs: stack / daily
Mail: smtp
Queue: redis
Scout: algolia
Session: redis

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.12.0
PHP SDK Version: 4.10.0
Release: 144b52b
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 1%
Sample Rate Profiling: 1%
Send Default PII: ENABLED

Statamic
Addons: 4
Sites: 2 (🇩🇪 Deutsch, 🇫🇷 Français)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.46.1 PRO

Statamic Addons
cnj/seotamic: 5.0.0
teamnovu/graphql-breadcrumbs: 1.0.7
teamnovu/localize: 1.1.3
teamnovu/statamic-gql-swr-cache: 1.0.0
```

### Installation

Fresh statamic/statamic site via CLI
