### ISSUE TITLE
Duplicating entries with propagate=true results in too many duplicates

### ISSUE THREAD

**Issue by JorisOrangeStudio** [statamic/cms#11467]
### Bug description

When duplicating an Entry that has localisations in a collection with `propagate=true` it duplicates the non-default languages (Deutsch & English) twice. See screenshot below:

![Image](https://github.com/user-attachments/assets/2983b828-4368-4be3-8a95-c273492c9336)
![Image](https://github.com/user-attachments/assets/e536f6c9-76b4-4b83-b1c3-66118cd5465e)

Is this normal behaviour for duplicating with propagate set to true? When `propagate=false` it only duplicates the entry 3 times (once per locale). This is tested on 2 different installs within different collections. 

### How to reproduce

1. Make a Collection with Propagate set to True
2. Make a Entry with at least one localised version in that Collection
3. Duplicate the entry 

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: XXX
Laravel Version: 10.48.22
PHP Version: 8.3.9
Composer Version: 2.8.5
Environment: production
Debug Mode: OFF
URL: www.example.com/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: redis
Database: mysql
Logs: stack / daily, slack
Mail: mailgun
Queue: redis
Session: redis

Statamic
Addons: 6
Sites: 3 (Nederlands, English, Deutsch)
Stache Watcher: Enabled
Static Caching: half
Version: 5.29.0 PRO

Statamic Addons
aerni/advanced-seo: 2.9.3
heidkaemper/statamic-toolbar: 1.2.1
jacksleight/statamic-bard-texstyle: 3.3.1
mattrothenberg/statamic-mapbox-address: 0.9.0
mitydigital/statamic-logger: 2.3.0
statamic/collaboration: 1.0.0
```

### Installation

Existing Laravel app
