### ISSUE TITLE
Wrong taxonomies count

### ISSUE THREAD

**Issue by peimn** [statamic/cms#11472]
### Bug description

Terms count are wrong in taxonomies when multisite enebaled.

### How to reproduce

Create a taxonomy and assign it to multiple sites. When you add a term to that taxonomy, the total count of terms will be multiplied by the number of sites it’s applied to. For example, if you create a term in a taxonomy shared across 3 sites, the term count will reflect 3 instances (one for each site).
### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 11.42.1
PHP Version: 8.3.13
Composer Version: 2.8.2
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: fa

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Octane: frankenphp
Queue: sync
Session: file

Locales
Installed: az, en, fa
LaravelLang\Actions\Plugin: 1.8.10
LaravelLang\Attributes\Plugin: 2.11.4
LaravelLang\HttpStatuses\Plugin: 3.8.5
LaravelLang\Lang\Plugin: 15.14.0
LaravelLang\MoonShine\Plugin: INCORRECT
Locales Version: 2.9.2
Protected: en, fa
Publisher Version: 16.4.1

Statamic
Addons: 6
Sites: 5 (فارسی, English, עִברִית, عربي, Turkçe)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.x-dev PRO

Statamic Addons
aryehraber/statamic-logbook: dev-main
doefom/restrict: dev-main
octoper/statamic-html-minify: dev-main
statamic/seo-pro: dev-main
tresdstudioweb/dynamic-select: dev-main
webographen/statamic-admin-log: dev-main
```

### Installation

Existing Laravel app
