### ISSUE TITLE
`rawurlencode` does not encode forward slashes

### ISSUE THREAD

**Issue by miicah** [statamic/cms#11470]
### Bug description

The documentation for [urlrawencode](https://statamic.dev/modifiers/rawurlencode) indicates it should take a string and encode it as per RFC 3986 and all characters except -_.~ should be encoded with their % equivalent.  Mentioned here statamic/docs#1603 originally.

I'd consider this a bug as it doesn't match how the function is supposed to work. Maybe a simple fix would be to change it to simply be a wrapper for `rawurlencode` without any additional processing of the input string?

### How to reproduce

```yaml
url_encode_array:
  test: 'http://test.com/it's coming home'
  test2: 'pronouns are he\him'
  test3: 'please and thank you/Mommy'
```

```antlers
{{ foreach:url_encode_array }}
    <p>{{ value | rawurlencode }}</p>
{{ /foreach:url_encode_array }}
```

Expected output

```html
<p>http%3A//test.com/its%20coming%20home</p>
<p>pronouns%20are%20he%5Chim</p>
<p>please%20and%thank&20you%2FMommy</p>
```

Actual output:

```html
<p>http%3A//test.com/its%20coming%20home</p>
<p>pronouns%20are%20he%5Chim</p>
<p>please%20and%20thank%20you/Mommy</p>
```

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.38.2
PHP Version: 8.3.17
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: cyberspace-place.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.45.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI
