### ISSUE TITLE
Scope for an Entry field is only applied in List View, not in Tree View

### ISSUE THREAD

**Issue by jensolafkoch** [statamic/cms#11477]
### Bug description

I have a scope:

```
<?php

namespace App\Scopes;

use Statamic\Query\Scopes\Scope;

class RequestSegmentFormatInstructions extends Scope
{
    public function apply($query, $values): void
    {
        $query->whereJsonContains('applicable_types', ['request_segment_format_instructions']);
    }
```

applied to an Entry field:

![Image](https://github.com/user-attachments/assets/f2b0912d-6935-4394-86f2-b6391f0810ee)

when called in an entry in the CP, here with `Link existing item`:

![Image](https://github.com/user-attachments/assets/075a69c9-e0aa-4ea8-9756-040cfeaa63cf)

I get the correct scoped EntryCollection in List View:

![Image](https://github.com/user-attachments/assets/6d364670-0619-4a48-959a-ec5ba9cadaf3)

but not in Tree View:

![Image](https://github.com/user-attachments/assets/3d1c5041-e7cd-4a26-8845-729f8c382b2e)I 

### How to reproduce

See above.

### Logs

```shell

```

### Environment

```yaml
nvironment
Application Name: Tradivi
Laravel Version: 11.43.0
PHP Version: 8.3.3
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: jok-tradivi.test
Maintenance Mode: OFF
Timezone: Europe/Berlin
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: database
Database: sqlite
Logs: daily
Mail: log
Queue: database
Session: database

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.47.0 Solo

Statamic Addons
marcorieser/statamic-livewire: 4.0.0
```

### Installation

Fresh statamic/statamic site via CLI
