### ISSUE TITLE
To upload assets in profile you need access to at least one site in multisites

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#11474]
### Bug description

Some of our users can change their profile page only in the CP.

To show the upload file button for assets fields (e.g. an avatar field), the user role needs to have at least access to one site, even if the profile or the asset container are not even using any connections (as far as I know) to the different sites.

![Image](https://github.com/user-attachments/assets/21bee6f2-78eb-435c-b00b-cbf866d26c28)

![Image](https://github.com/user-attachments/assets/7a0076f7-a607-4442-8a46-c34c7afc2896)

![Image](https://github.com/user-attachments/assets/b95bca7c-fb63-4732-afc6-772d1799ab44)

### How to reproduce

1. Make Multisite
2. Add asset field to user blueprint
3. Create Role
4. Allow access to asset container
5. Add / Remove access to site and check the visibility of the file upload button. (logout and login after changing the site accesses)

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Schweiz
Laravel Version: 11.41.3
PHP Version: 8.3.14
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: Europe/Zurich
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 4 (Schweiz, Aargau, St. Gallen, Baselland)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.46.1 PRO
```

### Installation

Fresh statamic/statamic site via CLI
