### ISSUE TITLE
[5.48] Found double string in fr.php translation file after running the translator command

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#11489]
### Bug description

I ran 'php translator generate fr'  after upgrading to 5.48 and the translator did not picked a key that was already translated in 'fr.json':
You can see below that the same translation key was added again when I ran this command.

"If you're having trouble clicking the \":actionText\" button, copy and paste the URL below\ninto your web browser:": "",
 "If you’re having trouble clicking the \":actionText\" button, copy and paste the URL below\ninto your web browser:": "Si vous ne parvenez pas à cliquer sur le bouton \":actionText\", copiez et collez l'URL ci-dessous dans votre navigateur Web :",

### How to reproduce

Locally upgrade statamic to 5.48
Download the zip for statamic/cms from Github and replace the content of the "resources" folder on your dedicated translation repo with the content of the "resources" folder downloaded
Run 'php translator generate fr' in your dedicated translation repo
Compare the updated 'fr.json' in this repo with the same file located in statamic 5.48 / vendor / resources / lang /

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.36.1
PHP Version: 8.3.7
Composer Version: 2.6.5
Environment: local
Debug Mode: OFF
URL: statamic.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.48.0 PRO

Statamic Addons
ebeauchamps/multi-taxonomies: 1.1.1
ryanmitchell/statamic-translation-manager: 2.0.0
```

### Installation

Fresh statamic/statamic site via CLI
