### ISSUE TITLE
Video dimensions of rotated videos

### ISSUE THREAD

**Issue by grischaerbe** [statamic/cms#11480]
### Bug description

The dimensions fields `width` and `height` are swapped for videos with rotated video streams.

PR is up: #11479 

### How to reproduce

Upload a video with a rotated video stream.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.38.2
PHP Version: 8.3.17
Composer Version: 2.8.4
Environment: production
Debug Mode: ENABLED
URL: freelingwaters-cms-new.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Sites: 1
Stache Watcher: Disabled (auto)
Static Caching: Disabled
Version: 5.x-dev PRO
```

### Installation

Fresh statamic/statamic site via CLI
