### ISSUE TITLE
Live Preview CSP rule does not include port number

### ISSUE THREAD

**Issue by dmxmo** [statamic/cms#11497]
### Bug description

After enabling multisite, the Content Security Policy (CSP) for Live Preview does not include the port number in the frame-ancestors directive when determining allowed origins. This issue affects configurations where the control panel is served on a custom port (e.g., http://127.0.0.1:8000/ or http://localhost:8080/). Since CSP treats http://127.0.0.1/ and http://127.0.0.1:8000/ as distinct origins, the live preview fails to load within an iframe.

This generates the following error in the console log: "This issue affects setups where the control panel is served on a custom port (e.g., http://127.0.0.1:8000/ or http://localhost:8080/). Since CSP treats http://127.0.0.1/ and http://127.0.0.1:8000/ as separate origins, Live Preview fails to load in an iframe."

### How to reproduce

1. Create a new statamic website
2. Enable multisite (php please multisite)
3. Serve using "php artisan serve"
4. Edit a Page entry and click preview
5. Check the console log for error: Refused to frame 'http://127.0.0.1:8000/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors http://127.0.0.1"

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.44.0
PHP Version: 8.3.4
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: 127.0.0.1:8000
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 2 (Statamic EN, Statamic FR)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.48.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Set up:
LAMP using "php artisan serve" to spin it up
