### ISSUE TITLE
Carbon error from REST API cacher

### ISSUE THREAD

**Issue by CedsTrash** [statamic/cms#11492]
### Bug description

I just updated to 4.48.0 and I receive this error message when accessing API routes:
`Carbon\Carbon::rawAddUnit(): Argument #3 ($value) must be of type int|float, string given, called in /home/forge/{DOMAIN}/vendor/nesbot/carbon/src/Carbon/Traits/Units.php on line 356`

Sentry also notified me:
![Image](https://github.com/user-attachments/assets/c0d762e4-8a63-4d3c-8535-d380ecbdaaee)

### How to reproduce

Simply upgrade to Statamic 5.48.0

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: App
Laravel Version: 11.43.2
PHP Version: 8.3.12
Composer Version: 2.6.6
Environment: local
Debug Mode: ENABLED
URL: localhost:8000
Maintenance Mode: OFF
Timezone: America/Toronto
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: reverb
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.13.0
PHP SDK Version: 4.10.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 100%
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 5
Sites: 2 (App - EN, App - FR)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.48.0 PRO

Statamic Addons
itiden/statamic-backup: 0.5.2
ndx/statamic-bard-color-picker: 2.0.1
nxstar/pages-without-seo: dev-staging
statamic/collaboration: 1.0.0
swiftmade/statamic-clear-assets: 3.1.0
```

### Installation

Fresh statamic/statamic site via CLI
