### ISSUE TITLE
Error at installing a new project in Windows because of the `ext-pcntl` missing extension.

### ISSUE THREAD

**Issue by LTroya** [statamic/cms#11490]
### Bug description

Hi guys,

I am getting this error when creating a new statamic project in Windows 11 because of `spatie/fork` which uses the `ext-pcntl` which cannot be install on Linux ([source](https://stackoverflow.com/questions/30045085/how-can-i-install-the-pcntl-extension-on-windows)):

`There was a problem installing the Static Site Generator addon!`

Environment info:

I executed the following command:

```bash
C:\Users\<User>\AppData\Roaming\Composer\vendor\bin\statamic.bat new

# I also tried non-bat executable. Same error
```

<img width="1910" alt="Image" src="https://github.com/user-attachments/assets/796b494a-a029-4cd9-9513-1bca3a64dd26" />

### How to reproduce

Use Herd on Windows 11 and create a new statamic project.

### Logs

```shell

```

### Environment

```yaml
- Windows 11
- Laravel Herd 1.14.0 
- PHP 8.3

Output of `php artisan statamic:support:details`:

Environment
Application Name: Statamic
Laravel Version: 11.43.2
PHP Version: 8.3.17
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: blog.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.48.0 Solo

Statamic Addons
statamic/ssg: 3.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Is there something I can do to about this error? 

Thanks in advance!
