### ISSUE TITLE
Handle validation doesn't allow handles starting with numbers

### ISSUE THREAD

**Issue by atomicjam** [statamic/cms#11503]
### Bug description

![Image](https://github.com/user-attachments/assets/9acca1ed-bcad-4ec3-9da8-e3400252f685)

Validation prevents pages with handle beginning with numbers yet validation message suggests should be fine and we have used this handle format in the past appears to be new in 5.48.1

### How to reproduce

Statamic 5.48.1 create page starting with numbers as per screenshot. 

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: cheltladiescollege.org
Laravel Version: 11.44.0
PHP Version: 8.3.16
Composer Version: 2.3.10
Environment: production
Debug Mode: OFF
URL: www.cheltladiescollege.org
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Disabled
Static Caching: half
Version: 5.48.0 PRO

Statamic Addons
mitydigital/feedamic: 2.5.0
mitydigital/sitemapamic: 3.2.0
rias/statamic-redirect: 3.9.3
```

### Installation

Fresh statamic/statamic site via CLI
