### ISSUE TITLE
Bard Field '+' Icon jumps when trying to select text underneath it

### ISSUE THREAD

**Issue by JorisOrangeStudio** [statamic/cms#11521]
### Bug description

When using a Bard field and selecting texts the UI bugs once you reach the '+' icon, see attached video. This makes it almost impossible to select the first character of a line with your cursor and can be quite frustrating if you are copying/pasting a lot of content. 

Possible solution is maybe to move the plus icon to the next/previous line instead of the active one? 
Or hide the plus icon when text is being selected (if that is possible)? 

https://github.com/user-attachments/assets/015e2876-ea02-4b36-9caa-9d7950fd22e5

### How to reproduce

Use a Bard field with the + icon set to always visible and select a text (see video)

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: xxx
Laravel Version: 10.48.28
PHP Version: 8.3.16
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: localhost/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Cache: file
Database: mysql
Logs: stack / single
Mail: mailgun
Queue: sync
Session: file

Statamic
Addons: 6
Sites: 4 (Dutch, English, German, French)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.46.1 PRO

Statamic Addons
aerni/advanced-seo: 2.9.3
heidkaemper/statamic-toolbar: 1.3.0
jacksleight/statamic-bard-texstyle: 3.4.1
mattrothenberg/statamic-mapbox-address: 0.9.0
mitydigital/statamic-logger: 2.4.0
statamic/collaboration: 1.0.0
```

### Installation

Fresh statamic/statamic site via CLI
