### ISSUE TITLE
Term filter on entry listing not working when limiting to 1 term per entry

### ISSUE THREAD

**Issue by dryven-lukas** [statamic/cms#11527]
### Bug description

It seems that recently the term filtering of entries is somewhat broken. When filtering for certain terms the result remains "no results" eventhough there should be. The problem is fixed when not limiting binded terms to 1 at maximum in the blueprint. I guess there is an issue when the binded term is not saved as an array.

### How to reproduce

1. Bind a taxonomy to a collection
2. Restrict number of connected terms to 1 through the collections blueprint
3. After binding a taxonomy term to some entries of this collection, filter for a certain term in the collections entry list.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: dryven Project
Laravel Version: 11.44.0
PHP Version: 8.3.8
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: Europe/Vienna
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.49.1 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.3.0
ddm-studio/cookie-byte: 1.5.4
spatie/statamic-responsive-images: 5.2.2
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

I rolled back the versions and the problem seems to persist since version 5.43.0. I guess it may have something to do with #11268.
