### ISSUE TITLE
Error "Statamic\Auth\Protect\Protectors\Password\Guard" not found

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#11524]
### Bug description

After updating from 5.23.0 to 5.49.1 this code ` {{ if {has_entered_password} }}` causes this error:

`Class "Statamic\Auth\Protect\Protectors\Password\Guard" not found`

After downgrading back the error is gone.

### How to reproduce

I use a password secured area and checked with `{{ if {has_entered_password} }}`, if the user is logged in.

### Logs

```shell

```

### Environment

```yaml
Environment
Laravel Version: 10.48.28
PHP Version: 8.3.7
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.23.0 PRO

Statamic Addons
ddm-studio/cookie-byte: 1.5.4
mitydigital/statamic-google-fonts: 2.0.0
visuellverstehen/statamic-anchor-navigation: 1.0.0
```

### Installation

Fresh statamic/statamic site via CLI
