### ISSUE TITLE
Fallback config does not respect `APP_LOCALE`

### ISSUE THREAD

**Issue by marcorieser** [statamic/cms#11548]
### Bug description

I assumed the frontend would take `locale` in `config/app.php` into account if I don't have a `sites.yaml` created. This is mostly the case when I don't need multisite.

### How to reproduce

- Install a new project
- Set `APP_LOCALE` to e.g. `de` in `.env`
- Inspect the locale of the default site that is set to `en_US`

### Environment

```yaml
Environment
Application Name: Stiftung Birkenhof Berg
Laravel Version: 12.1.1
PHP Version: 8.3.17
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: statamic-birkenhof.test
Maintenance Mode: OFF
Timezone: Europe/Zurich
Locale: de_CH

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Livewire
Livewire: v3.6.1

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.49.1 PRO

Statamic Addons
marcorieser/statamic-livewire: 4.1.0
marcorieser/statamic-vitals: 1.2.0
marcorieser/tailwind-merge-statamic: 1.1.0
ryanmitchell/statamic-translation-manager: 2.1.0
stillat/antlers-components: 2.5.0
```

### Installation

Fresh statamic/statamic site via CLI
