### ISSUE TITLE
container-type: inline-size

### ISSUE THREAD

**Issue by carstenjaksch** [statamic/cms#11547]
### Bug description

In a Grid field I noticed that the Link field doesn't take up the entire space in all it's states:

<img width="881" alt="Image" src="https://github.com/user-attachments/assets/8416a806-06b2-45c1-abb2-1d1b7e8d1b92" />
<img width="879" alt="Image" src="https://github.com/user-attachments/assets/fe1a57b6-fa96-4e28-92fd-2941a3efe94e" />
<img width="882" alt="Image" src="https://github.com/user-attachments/assets/01827089-1767-4ef3-b2bd-93f1bfe8d833" />

Disabling `container-type: inline-size` solves this issue:

<img width="956" alt="Image" src="https://github.com/user-attachments/assets/19e79942-2754-4d58-a560-6df4dad962e5" />
<img width="891" alt="Image" src="https://github.com/user-attachments/assets/522b9f9d-f22b-4100-8a55-33ad0d1798ca" />
<img width="888" alt="Image" src="https://github.com/user-attachments/assets/4c7d5d8f-0804-49d7-9152-5d4050b4caa3" />
<img width="886" alt="Image" src="https://github.com/user-attachments/assets/41690c4f-7308-40dc-bdf5-a0021a7b0d6a" />

But that looks like a pretty important class – there could be possible side effects with other field combinations.

### How to reproduce

Create a Grid field (UI mode "table") with a Link field inside and some other fields after the Link field.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 12.1.1
PHP Version: 8.3.17
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: statamic-starter.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.49.1 Solo

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.4.1
```

### Installation

Fresh statamic/statamic site via CLI
