### ISSUE TITLE
Password Reset Action ignores custom notification template

### ISSUE THREAD

**Issue by Jepyhaja** [statamic/cms#11554]
### Bug description

When using custom notification template for password resets, the correct template is not used when sending password reset throud Control Panel action from Users page. Correct template is used on the "forgot password form" on route cp/auth/password/reset.

### How to reproduce

Install statamic, in my case I installed to two different existing projects. Follow the docs so that we have following files:
```php
// config/auth.php
'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_reset_tokens',
            'expire' => 60,
            'throttle' => 60,
        ],
        'activations' => [
          'provider' => 'users',
          'table' => 'password_activation_tokens',
          'expire' => 4320,
          'throttle' => 60,
        ],
  ],
```
```php
// config/statamic/users.php
'passwords' => [
    'resets' => 'users',
    'activations' => 'activations',
  ],
```
Create migrations with `php please auth:migration`
Run migrations and add super user to database.

Configure User model
```php
// /models/User.php

public function sendPasswordResetNotification($token)
{
    $this->notify(new \Statamic\Notifications\PasswordReset($token));
}
```

Create custom notification, for example:
```php 
// Notifications/PasswordResetNotification
<?php

namespace App\Notifications;

use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class PasswordResetNotification extends Notification
{
  public function __construct()
  {
  }

  public function via($notifiable): array
  {
    return ['mail'];
  }

  public function toMail($notifiable): MailMessage
  {
    return (new MailMessage)
        ->line('Test');
  }

  public function toArray($notifiable): array
  {
    return [];
  }
}

```

Replace the previous sendPasswordNotification on User model with this:
```php
// /Models/User.php
public function sendPasswordResetNotification($token): void
{
  $this->notify(new PasswordResetNotification($token));
}
```

Clear routes, cache and config just to be sure.

Go to statamic login and open forgot password form. Submit and receive the correct template with "test" content.

Log in and navigate to Users, select user and "Send Password Reset" action. Receive statamic default notification instead of the custom notification.

### Logs

```shell
No log entries.
```

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 10.48.28
PHP Version: 8.3.15
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: laravel.test
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.58.3 PRO

Statamic Addons
eminos/statamic-tabs: 1.2.0

AND

Environment
Application Name: laraveltest
Laravel Version: 11.30.0
PHP Version: 8.3.15
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: laraveltest.test
Maintenance Mode: OFF
Timezone: UTC
Locale: fi

Cache
Config: CACHED
Events: CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Spatie Permissions
Features Enabled: Default
Version: 6.10.0

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.40.0 PRO

Statamic Addons
eminos/statamic-tabs: 1.2.0
```

### Installation

Existing Laravel app
