### ISSUE TITLE
Icon fieldtype in replicator broken

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#11558]
### Bug description

Possibly due to: https://github.com/statamic/cms/pull/11523

Update: it seems the wrong set of icons is being loaded here. The names don't correspond with the icons we had there pre 5.50.

Icons don't load properly in the fieldset editor (replicator):

<img width="1584" alt="Image" src="https://github.com/user-attachments/assets/2918d63f-0da3-4968-9a16-7fa6e68af1fd" />

### How to reproduce

Create a replicator
Pick an icon for your set

### Logs

```shell

```

### Environment

```yaml
Environment
Laravel Version: 12.1.1
PHP Version: 8.2.27
Composer Version: 2.8.5
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF
Timezone: America/Edmonton
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.50.0 PRO

Statamic Addons
rias/statamic-color-swatches: 2.3.0
studio1902/statamic-peak-browser-appearance: 3.6.1
studio1902/statamic-peak-commands: 8.16.1
studio1902/statamic-peak-seo: 8.19.1
studio1902/statamic-peak-tools: 7.1.0
```

### Installation

Fresh statamic/statamic site via CLI
