### ISSUE TITLE
Active language does not update in collection table view when switching via the global header

### ISSUE THREAD

**Issue by kungphung** [statamic/cms#11557]
### Bug description

We recently updated from Statamic v4.45 to v5.49 and noticed an issue when switching languages using the global header in the CMS.

In a collection (e.g., "News"), we have entries in multiple languages. When switching to another language via the global header, the collection table view does not update to reflect the newly selected language. Instead, it remains on the previously active language.

Expected behavior: The table view should update to match the selected language, as it did in v4.45.

This issue affects content editors who need to manage multilingual content efficiently.

### How to reproduce

1. Ensure you have a collection (e.g., "News") with entries in multiple languages.
2. In the CMS, set the active language to English.
3. Navigate to the "News" collection and view the table with English entries.
4. Use the global header to switch the language to German.
5. Observe the collection table view: it still displays the English entries instead of updating to German.

Expected Behavior:

The table view should update to display the entries in the newly selected language, as it did in v4.45.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: ###
Laravel Version: 11.44.0
PHP Version: 8.2.27
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: ###
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: nl

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.6.0

Statamic
Addons: 5
Sites: 3 (nl, en, de)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.49.1 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.8.1
stillat/relationships: 2.2.1
studio1902/statamic-peak-browser-appearance: 3.6.1
studio1902/statamic-peak-seo: 8.19.1
studio1902/statamic-peak-tools: 3.4.3
```

### Installation

Fresh statamic/statamic site via CLI
