### ISSUE TITLE
Carbon deprecation warning triggered in date fieldtypes `parseSaved` function

### ISSUE THREAD

**Issue by simonerd** [statamic/cms#11553]
### Bug description

I've got a date field in a blueprint which logs the following warning every time I open the index of the containing collection, where the date field is shown as a column.

```
createFromFormat() $time parameter will only accept string or integer for 1-letter format representing a numeric unit in the next version in /[…]/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 653
```

This leads to [the `parseSaved` function of the date fieldtype](https://github.com/statamic/cms/blob/1bb28a16b3e312c47e1723c1019bc77a6582add8/src/Fieldtypes/Date.php#L349-L356):

```php
private function parseSaved($value)
{
    try {
        return Carbon::createFromFormat($this->saveFormat(), $value);
    } catch (InvalidFormatException|InvalidArgumentException $e) {
        return Carbon::parse($value);
    }
}
```

The `$value` param is a Carbon instance, which the `createFromFormat()` function doesn't seem to like in the future. If I simply cast it to a string, the warning disappears.

```php
return Carbon::createFromFormat($this->saveFormat(), (string) $value);
```

While this fixes the issue, this might not be the best idea, as the value would be cast to Carbon when read from data, then cast back to string, only to be used to create a new Carbon instance again 🤷🏻 

Don't know if you're on this for v6 already. Happy to contribute if you can give a bit of input on which direction to go.

### How to reproduce

- configure your app to log deprecation warnings (e. g. `LOG_DEPRECATIONS_CHANNEL=daily` in .env)
- create a dated collection
- add the date field to the visible columns in index
- create an entry, open collection index

### Logs

```shell
[2025-03-10 18:05:15] local.WARNING: createFromFormat() $time parameter will only accept string or integer for 1-letter format representing a numeric unit in the next version in /[…]/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 653
```

### Environment

```yaml
Environment
Application Name: myapp
Laravel Version: 11.44.0
PHP Version: 8.3.17
Composer Version: 2.8.5
Environment: local
Debug Mode: ENABLED
URL: localhost:8001
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: pgsql
Logs: daily
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.49.1 PRO

Statamic Addons
statamic/eloquent-driver: 4.20.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: eloquent
Navigations: file
Revisions: eloquent
Sites: file
Taxonomies: file
Terms: eloquent
Tokens: eloquent
```

### Installation

Fresh statamic/statamic site via CLI
