### ISSUE TITLE
Collection Filter not working for "Taxonomy Terms" with "Max Items = 1"

### ISSUE THREAD

**Issue by wuifdesign** [statamic/cms#11562]
### Bug description

When adding a taxonomy terms field to a collection blueprint and selection "max items = 1" the filter in the list view isn't working.

You still get a "contains" type select, which seams to be wrong as it should be "is/isn't" and may result in the error.

<img width="297" alt="Image" src="https://github.com/user-attachments/assets/b96287e5-4acc-4c88-98e3-49fd1dfbced2" />

if you use "contains" and select any value it will show an empty list, even if collections have the taxonomy term applied.

### How to reproduce

- add a taxonomy terms field to a collection blueprint and select "max items = 1"
- create a new entry in this collection and select any taxonomy
- try to filter the list for the taxonomy

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.44.1
PHP Version: 8.2.27
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: 127.0.0.1:8000
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 2 (English, German)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.50.0 PRO

Statamic Addons
jacksleight/statamic-distill: 0.8.2
ndx/statamic-bard-color-picker: 2.0.1
teamnovu/statamic-images-missing-alt: 1.0.5
webographen/statamic-widget-continue-editing: 1.3.2
```

### Installation

Fresh statamic/statamic site via CLI
