### ISSUE TITLE
Slug still being generated, even when field is hidden

### ISSUE THREAD

**Issue by ssyberg** [statamic/cms#11564]
### Bug description

I'm trying to disable slugs on a subset of entries in a collection but new entires appear to still have slugs generated.

### How to reproduce

1. Create blueprint with a slug field, slug field is set to auto generate based on title, but conditionally visible based on a "has profile" boolean, if `slug` is hidden I expect it to be empty and remain empty
1. Create collection with slugs set to _not required_
1. Create a new entry with "has profile" false
1. New entry is created and has slug set

Stranger still, and this is probably just something I don't understand about revisions, but I don't see a slug value set on the content record at all, but I do see it on the revision record

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: <redacted>
Laravel Version: 10.48.27
PHP Version: 8.3.17
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: <redacted>
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.46.0 PRO

Statamic Addons
alt-design/alt-redirect: 1.3.3
aryehraber/statamic-logbook: 3.3.0
jacksleight/statamic-bard-texstyle: 3.4.1
stillat/relationships: 2.2.1
```

### Installation

Fresh statamic/statamic site via CLI
