### ISSUE TITLE
Link field entry titles too wide

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#11563]
### Bug description

The Link fieldtype is currently showing the full title of the linked entry. If it's a long title then it can cause layout issues. Here are some examples: 

50% width Link field in bard:
<img width="840" alt="Image" src="https://github.com/user-attachments/assets/e2f22f1a-f685-4c3b-a750-0d0fbe4e271a" />

Grid field: table layout
<img width="619" alt="Image" src="https://github.com/user-attachments/assets/1a4f5b50-438e-49db-80bc-31235fd4bd0f" />

Grid field: stacked layout
<img width="620" alt="Image" src="https://github.com/user-attachments/assets/b8d4aa9e-8a7a-4f4f-b0a8-19d8bd85f501" />

Can link titles be truncated to maybe 15 or 20 characters?

Thanks.

### How to reproduce

- Add a link field to a row of other fields.
- Link to an entry with a long title.

### Logs

```shell

```

### Environment

```yaml
Environment
Laravel Version: 11.44.1
PHP Version: 8.3.15
Composer Version: 2.7.4
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF
Timezone: Europe/Dublin
Locale: en

Cache
Config: NOT CACHED
Events: CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Livewire
Livewire: v3.6.1

Statamic
Addons: 8
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.49.1 PRO

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.4.1
jonassiewertsen/statamic-live-search: 2.1.1
jonassiewertsen/statamic-livewire: 3.8.1
pecotamic/sitemap: 1.4.8
rias/statamic-redirect: 3.9.3
spatie/statamic-responsive-images: 5.2.2
```

### Installation

Fresh statamic/statamic site via CLI
