### ISSUE TITLE
glide:url no longer crops images correctly as of 5.49

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#11567]
### Bug description

I do have this code in my template view:

```
{{ bilder limit="2" }}

        {{ if seitenverhaeltnis === "16x10" }}

            …other size

        {{ elseif seitenverhaeltnis === "4x5" }}

            <img class="object-cover w-full"

                srcset="
                    {{ glide:url width="856" height="1070" sharpen="10" format="webp" }} 856w,
                    {{ glide:url width="1280" height="1600" sharpen="10" format="webp" }} 1280w,
                    {{ glide:url width="1440" height="1800" sharpen="10" format="webp" }} 1440w,
                    {{ glide:url width="1600" height="2000" sharpen="10" format="webp" quality="80" }} 1600w,
                    {{ glide:url width="2000" height="2500" sharpen="10" format="webp" quality="80" }} 2000w"

                sizes="
                    (min-width: 1024px) 50vw,
                    100vw"

                src="{{ glide:url width="1600" height="2000" sharpen="10" quality="70" }}"

                decoding="async"
                width="1600" height="2000"
                alt="{{ alt }}"
                style="background-color: {{ url | color:average }};">

        {{ else }}

           …other size

{{ /bilder }}
```

Version 5.49 introduces a few issues (maybe because of [11372 ](https://github.com/statamic/cms/pull/11372)?):

- First the images are no longer cropped and displayed the intended size (see screenshot with one example)
- Second the generated HTML has different path outputs: `/img/paths/assets` instead of `/img/containers/assets`. I don't know, what this means in case of this issue

<img width="1481" alt="Image" src="https://github.com/user-attachments/assets/75d086d0-014b-4ab5-af2f-be7014cdc2e7" />

5.49
```
<img class="object-cover w-full" 

srcset="
    /img/paths/assets/lehrwerkstatt/praktische-ausbildung/elias2.jpg/3a6102101f00a5fd5c189331eb06e427/elias2.webp 856w,
    /img/paths/assets/lehrwerkstatt/praktische-ausbildung/elias2.jpg/ec01f1d857fddf8f1ccd08d36a7c8ba7/elias2.webp 1280w,
    /img/paths/assets/lehrwerkstatt/praktische-ausbildung/elias2.jpg/3e36eeae58693c929277a9a427e40131/elias2.webp 1440w,
    /img/paths/assets/lehrwerkstatt/praktische-ausbildung/elias2.jpg/0172f88ce938dc3885d708f095e799a8/elias2.webp 1600w,
    /img/paths/assets/lehrwerkstatt/praktische-ausbildung/elias2.jpg/f6cde124b3040e0418b65eacb80e0b3d/elias2.webp 2000w" 

sizes="
    (min-width: 1024px) 50vw,
    100vw" 

src="/img/paths/assets/lehrwerkstatt/praktische-ausbildung/elias2.jpg/8dda656d66216f68cfaf5e03b0ce1c7d/elias2.jpg" 

decoding="async" width="1600" height="2000" alt="" style="background-color: #9E4331;">
```

5.48.1
```
<img class="object-cover w-full" 

srcset="
    /img/containers/assets/lehrwerkstatt/praktische-ausbildung/elias2.jpg/c17fdf8704c565d4efd914d62b3bbe36/elias2.webp 856w,
    /img/containers/assets/lehrwerkstatt/praktische-ausbildung/elias2.jpg/ded9c512e1a648727b7c71d6516eb829/elias2.webp 1280w,
    /img/containers/assets/lehrwerkstatt/praktische-ausbildung/elias2.jpg/cfd443dc883d6e3724e5e8f83ac5bb62/elias2.webp 1440w,
    /img/containers/assets/lehrwerkstatt/praktische-ausbildung/elias2.jpg/b65baf4036fd8492af937f4a0bf24eba/elias2.webp 1600w,
    /img/containers/assets/lehrwerkstatt/praktische-ausbildung/elias2.jpg/fe700386a16612e9816f1791ad30349d/elias2.webp 2000w" 

sizes="
    (min-width: 1024px) 50vw,
    100vw" 

src="/img/containers/assets/lehrwerkstatt/praktische-ausbildung/elias2.jpg/7213d78f62c93619698a4b64809b2de1/elias2.jpg" 

decoding="async" width="1600" height="2000" alt="" style="background-color: #9E4331;">
```

### How to reproduce

composer update from 5.48.1 to 5.49 and use the code above in a template.

On other parts on the site I use this code, which still seems to work fine:

```
src="{{ glide:teaser_bild width="1680" height="840" sharpen="10"  quality="70" }}"
```

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Schnätzi CMS
Laravel Version: 11.44.2
PHP Version: 8.3.17
Composer Version: 2.8.5
Environment: local
Debug Mode: ENABLED
URL: /
Maintenance Mode: OFF
Timezone: Europe/Zurich
Locale: de_CH

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.49.0 PRO

Statamic Addons
aryehraber/statamic-color-extractor: 1.5.0
mitydigital/statamic-sticky-notes: 1.0.2
rias/statamic-color-swatches: 2.3.0
rias/statamic-redirect: 3.9.3
statamic/seo-pro: 6.6.0
```

### Installation

Fresh statamic/statamic site via CLI
