### ISSUE TITLE
TypeError in `internalFieldActions` for RelationshipFieldtype

### ISSUE THREAD

**Issue by TommyFinetic** [statamic/cms#11572]
### Issue Summary
In the latest version of Statamic, a Vue function called `internalFieldActions` has been added in the following file:  

**File Path:**  
`vendor/statamic/cms/resources/js/components/fieldtypes/relationship/RelationshipFieldtype.vue`  

During execution, a **TypeError** occurs when checking the visibility of a specific action. The error message is as follows:  _TypeError: Cannot read properties of null (reading 'length')_

### Cause of the Error
The issue arises from the following line of code:  

```js
internalFieldActions() {
            return [
                {
                    title: __('Unlink All'),
                    dangerous: true,
                    run: this.unlinkAll,
                    visible: this.value.length > 0,
                },
            ];
        },
```

### 1. Create a Blueprint  
Create a blueprint that includes a **taxonomy-term relation** field with the **mode set to `select`**.

### 2. Add the Blueprint to a `<publish-form>`  
Include this blueprint in a `<publish-form>` component to generate the form in the Statamic Control Panel.

### 3. Attempt to Select a Taxonomy Term  
Try selecting a taxonomy term from the dropdown field.  

### Expected Behavior  
The dropdown should display the available taxonomy terms for selection.

### Actual Behavior  
- The dropdown doesn't set the selected value.  
- The previously mentioned **TypeError** occurs in the console.  

This issue prevents users from properly selecting taxonomy terms when using the `select` mode in the relationship field.

### Logs

```shell

```

### Environment

```yaml
Environment
Laravel Version: 11.44.0
PHP Version: 8.3.14
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: pgsql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Simple Commerce
Currencies: EUR
Gateways: Mollie
Repository: Customer: DuncanMcClean\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DuncanMcClean\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DuncanMcClean\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Free Shipping
Tax Engine: DuncanMcClean\SimpleCommerce\Tax\Standard\TaxEngine

Livewire
Livewire: v3.5.20

Statamic
Addons: 15
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.48.0 PRO

Statamic Addons
addonfoundry/flexible-forms: 1.2.7
aerni/font-awesome: 3.0.2
doefom/statamic-export: 0.4.2
duncanmcclean/simple-commerce: 7.7.0
jacksleight/statamic-bard-texstyle: 3.4.1
jonassiewertsen/statamic-live-search: 2.1.1
jonassiewertsen/statamic-livewire: 3.8.1
marcorieser/statamic-livewire: 4.0.0
mitydigital/statamic-logger: 2.4.0
reachweb/statamic-livewire-filters: 2.4.0
rias/statamic-redirect: 3.9.3
statamic/seo-pro: 6.5.0
```

### Installation

Fresh statamic/statamic site via CLI
