### ISSUE TITLE
Control panel crashes if a translation file exists with the same name as a collection blueprint

### ISSUE THREAD

**Issue by daun** [statamic/cms#11577]
### Bug description

The collection edit screen crashes if there is a translation file named like the blueprint handle.

Seems to have the same root cause as #11418, resulting in a `Array to string conversion` exception.

### How to reproduce

- Create a new blueprint `pages/search.yaml`
- Create a new translation file `lang/en/search.php` containing a translation array
- Navigate to the `Pages` collection and try to edit the collection
- Should result in a 500 server error

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: *****
Laravel Version: 11.41.3
PHP Version: 8.3.16
Composer Version: 2.8.4
Environment: local
Debug Mode: OFF
URL: *****.test
Maintenance Mode: OFF
Timezone: Europe/Berlin
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 7
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.48.1 PRO

Statamic Addons
daun/statamic-placeholders: 3.0.1
daun/statamic-widget-collection-count: 1.3.1
jacksleight/statamic-bard-mutator: 3.0.3
jacksleight/statamic-bonus-routes: 0.3.2
stillat/relationships: 2.2.1
thoughtco/statamic-cache-tracker: 0.9.3
```

### Installation

Fresh statamic/statamic site via CLI
