### ISSUE TITLE
Entries Fieldtype with UI Mode Typeahead Field broken

### ISSUE THREAD

**Issue by eminos** [statamic/cms#11589]
### Bug description

When using the Entries Fieldtype with UI Mode Typeahead Field I get "No options to choose from..." in the field itself. If I switch to an other UI Mode it works fine and I can see the entries as expected.

### How to reproduce

Set up a Entries Fieldtype Field with UI Mode Typeahead Field. Make sure to select a collection with entries!
Now when viewing that field on an edit page it doesn't list the entries as expected and instead just shows "No options to choose from...".

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: 
Laravel Version: 11.44.2
PHP Version: 8.3.14
Composer Version: 2.2.22
Environment: local
Debug Mode: ENABLED
URL: test.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.51.0 PRO

Statamic Addons
eminos/statamic-set-header-toggle: 1.1.0
statamic/collaboration: 1.0.0
statamic/importer: 1.7.5
```

### Installation

Fresh statamic/statamic site via CLI
