### ISSUE TITLE
Asset URL is null with an S3 bucket asset container

### ISSUE THREAD

**Issue by JohnnyWalkerDigital** [statamic/cms#11584]
### Bug description

I don't understand how this has happened, but since I switched to using an S3 bucket for my assets, my image galleries are not loading.

Here's an example output. You can see `permalink` and `url` fields are null. Yet the images are visible in the control panel in their assets field in the Collection. 

```
{
    "id": "assets::web_1st_floor_bar.webp",
    "title": "web_1st_floor_bar.webp",
    "path": "web_1st_floor_bar.webp",
    "filename": "web_1st_floor_bar",
    "basename": "web_1st_floor_bar.webp",
    "extension": "webp",
    "is_asset": true,
    "is_audio": false,
    "is_previewable": false,
    "is_image": true,
    "is_svg": false,
    "is_video": false,
    "blueprint": {
      "title": "Asset",
      "handle": "assets"
    },
    "edit_url": "http://www.hidden.com/cp/assets/browse/assets/web_1st_floor_bar.webp/edit",
    "container": {
      "id": "assets",
      "title": "Assets",
      "handle": "assets",
      "disk": "s3",
      "blueprint": {
        "title": "Asset",
        "handle": "assets"
      },
      "search_index": null,
      "api_url": null
    },
    "folder": "/",
    "url": null,
    "permalink": null,
    "api_url": null,
    "size": "108.59 KB",
    "size_bytes": 111194,
    "size_kilobytes": 108.59,
    "size_megabytes": 0.11,
    "size_gigabytes": 0,
    "size_b": 111194,
    "size_kb": 108.59,
    "size_mb": 0.11,
    "size_gb": 0,
    "last_modified": "2025-03-14T15:36:26.000000Z",
    "last_modified_timestamp": 1741966586,
    "last_modified_instance": "2025-03-14T15:36:26.000000Z",
    "focus": "50-50-1",
    "has_focus": false,
    "focus_css": "50% 50%",
    "height": 960,
    "width": 1399,
    "orientation": "landscape",
    "ratio": 1.4572916666666667,
    "mime_type": "image/webp",
    "duration": null,
    "duration_seconds": null,
    "duration_minutes": null,
    "duration_sec": null,
    "duration_min": null,
    "playtime": "16:41",
    "label": null,
    "alt": null,
    "location": null
  },
```

I have tried clearing all the caches.

### How to reproduce

1. Use an S3 bucket for your assets container
2. Create a field in a Blueprint to allow multiple images
3. Add multiple images to the field
4. Output the gallery images one-by-one

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Hidden
Laravel Version: 11.44.2
PHP Version: 8.4.3
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: www.hidden.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single, slack
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.50.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.20.2
statamic/ssg: 3.1.1
stillat/antlers-layouts: 2.1.0
visuellverstehen/statamic-classify: 3.0.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```

### Installation

Fresh statamic/statamic site via CLI
