### ISSUE TITLE
File field in navigation blueprint resets preview when sidepanel closes

### ISSUE THREAD

**Issue by mawalu** [statamic/cms#11588]
### Bug description

We have a file field to upload images in our navigation blueprint. When a user sets an image, saves the navigation item and reopens the navigation item side panel without reloading, the file field is no longer populated but defaults to the empty state.

After the tree is saved and the page reloaded the field is populated correctly but this behavior causes confusion to users.

### How to reproduce

* Add a file field to a navigation blueprint
* Choose a file for a navigation item and save the item
* Click again on the same navigation item opening the side panel, without saving the tree or reloading first
* See that the file field is not showing your selected file as value

Happens both with newly uploaded files and existing files

### Logs

```shell

```

### Environment

```yaml
$ php please support:details

Environment
Application Name: xxx
Laravel Version: 10.48.28
PHP Version: 8.2.24
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: xxx.ddev.site
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.19

Statamic
Addons: 2
Sites: 6 (xxx - DE, xxx - EN, xxx - DK, and 3 more)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.51.0 PRO

Statamic Addons
appswithlove/statamic-one-click-content-translation: 5.2.3
thoughtco/statamic-restrict-fields: 1.1.0
```

### Installation

Existing Laravel app

### Additional details

This issue already existed on previous versions, I just updated to verify it still affects the latest one

**Comment by duncanmcclean** [comment]
The "Files" fieldtype is only really intended to be used on forms and by addon developers. Is there any reason you're not using the "Assets" field type instead?

**Comment by mawalu** [comment]
Thank you for your response and sorry for the inaccuracy, but we are using a `type: assets` field for this. At least in the translated version of the CP the Fieldtype is called "Files" in the ui, thats why I referred to it that way.

```yaml
-
  handle: headerimage
  field:
    max_files: 1
    container: images
    type: assets
    display: 'Headerbild'
    localizable: false
```

Can this be reopened?

**Comment by duncanmcclean** [comment]
This looks like the same underlying issue as #10630.

**Comment by o1y** [comment]
The issue affects all fields in the nav blueprint not just asset fields :/ 

![Image](https://github.com/user-attachments/assets/27b6a341-ee14-4ae1-88cb-584387026179)

`nav_test.yaml`
```yaml
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: replicator_field
            field:
              type: replicator
              display: 'Replicator Field'
              sets:
                new_set_group:
                  display: 'New Set Group'
                  sets:
                    new_set:
                      display: 'New Set'
                      fields:
                        -
                          handle: text_field_two
                          field:
                            type: text
                            display: 'Text Field'
```
