### ISSUE TITLE
Entry is invalidated in all sites, not just the edited one

### ISSUE THREAD

**Issue by wautersj** [statamic/cms#11580]
### Bug description

**What happened:**
Entry is invalidated in every site it is published to; not just in the site i'm editing.
- Our statamic is a multisite for English (EN) and German (DE).
- Our statamic has full static caching enabled

Many thanks in advance for your input!

### How to reproduce

**Steps I took:**
- Visited the homepage in EN; first visit takes 2-3sec.
- Visited the homepage in DE; first visit takes 2-3sec.
- Revisited the homepage in EN; now takes 100ms. (The page comes from static cache)
- Revisited the homepage in DE; now takes 100ms. (The page comes from static cache)
- Open the homepage entry in the cp under pages.
- Currently selected Site for the entry is EN.
- Make a change in the content.
- Save the entry (for the entry in EN site)
- Visited the homepage in EN; now the visit takes 2-3sec. (obviously, since i changed some content and the entry for the EN site was invalidated)
- Visited the homepage in DE; now this visit also takes 2-3sec. (not obviously, since i didn't change anything for the entry in the DE site)

**What I found during debugging:**
When I put logs in the DefaultInvalidator, it seems that when saving an entry, it handles the entry for both sites, and thus passing 2 entries (they are handled one by one) through this mechanism to be invalidated.

**What I would have expected:**
That only the entry in the site that I edited is invalidated.
So in my example; when saving the change for the homepage in EN:
- The Homepage in EN should be invalidated.
- The Homepage in DE should not be invalidated.

**Question:**
Is this intended normal behaviour? or doesn't this seem right?
If not; what is intended behaviour?
(I was also building a CustomInvalidator that would invalidate other entries in a smart (custom) way; but since both entries from the 2 sites EN + DE are passing through; it becomes complex and heavy.)

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Xeikon
Laravel Version: 10.48.28
PHP Version: 8.2.28
Composer Version: 2.8.6
Environment: staging
Debug Mode: ENABLED
URL: staging.xeikon.com
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: redis

Livewire
Livewire: v3.6.0

Sentry
Enabled: YES
Environment: staging
Laravel SDK Version: 3.8.2
PHP SDK Version: 3.22.1
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 100%
Sample Rate Profiling: 100%
Send Default PII: DISABLED

Statamic
Addons: 3
Sites: 2 (English, Deutsch)
Stache Watcher: Disabled
Static Caching: full
Version: 5.49.0 PRO

Statamic Addons
digiti/statamic-crow: 1.1.2
marcorieser/statamic-livewire: 4.1.0
statamic/seo-pro: 6.6.0
```

### Installation

Statamic site originally created in Statamic 3 in 2021. 
=> statamic/cms": "3.2.*"
And recently upgraded to 4.x and now 5.X (latest version)

**Comment by duncanmcclean** [comment]
What does your `resources/sites.yaml` file look like?

It might be fixed by #10669.

**Comment by wautersj** [comment]
The pull you mentioned; It sounds very relatable!

My sites.yaml looks like this:
```
en:
  name: English
  locale: en_US
  url: /en
de:
  name: Deutsch
  locale: de_DE
  url: /de
```
