### ISSUE TITLE
Nav tag performance issues due to parent object

### ISSUE THREAD

**Issue by DwainsWorld** [statamic/cms#11595]
### Bug description

A few of our sites utilise flyout menus using Vue's Headless UI (Disclosures) for site navigation. In Statamic 4 we could use `select=@shallow` to improve performance, now we use the `select=specific keys`.

Example:
```
<public-left-navigation
    :items="{{ nav:main_navigation as='entry' select="id|title|url"  }}{{ entry | to_json | entities }}{{ /nav:main_navigation }}"
/>
```

Without the `select` parameter our page size was ~3MB, with it ~1.3MB. If I remove the navigation component above it drops to ~21KB.

I originally thought, the issue was relating to no longer using `@shallow` or the paginated like behaviour, prev / next keys within the nav items. However, after a deeper investigation the significant increase in size is due to the parent object (and recursive parents if deep enough) being included in the Nav toArray output:

https://github.com/statamic/cms/blob/4f835e27d02e529f4f1ac4e7151c2f280e5ffd87/src/Tags/Structure.php#L139

If I comment this line out, the page size drops significantly (in my case ~143KB)  and my navigation menus continue to function as expected. 

Is there any way for this to become a configurable option to exclude the parent object? Possibly the pagination like values prev / next too? The entire page object is being shown in these properties. Excluding these would drastically increase the performance on page load.

![Image](https://github.com/user-attachments/assets/ecb8eba8-a989-4fdb-b950-6c9717607154)

This didn't become prevalent until it made it way to our staging environment. We use the half measure caching strategy and 1.3MB page responses were getting dropped into our Redis cache - resulting in OOM exceptions.

### How to reproduce

Example Nav structure:
![Image](https://github.com/user-attachments/assets/9f55c6e6-bc3a-42b0-ae31-3ba880695dd2)

Example Page structure:
![Image](https://github.com/user-attachments/assets/7fb74995-63ad-48fb-bce9-0b67c1c35efd)

Inject navigation data as JSON into JS component:
```
<public-left-navigation
    :items="{{ nav:main_navigation as='entry' select="id|title|url"  }}{{ entry | to_json | entities }}{{ /nav:main_navigation }}"
/>
```

Inspect page size....

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Example
Laravel Version: 11.35.0
PHP Version: 8.2.26
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: localhost:3334
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Sentry
Enabled: YES
Environment: local
Laravel SDK Version: 4.11.0
PHP SDK Version: 4.10.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 5
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.48.1 PRO

Statamic Addons
edalzell/forma: 3.0.1
rias/statamic-link-it: 2.4.0
statamic/eloquent-driver: 4.19.1
statamic/seo-pro: 6.5.0
transformstudios/events: 5.4.3

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```

### Installation

Existing Laravel app
