### ISSUE TITLE
404 Not Found on valid pages during static:warm

### ISSUE THREAD

**Issue by ELowry** [statamic/cms#11599]
### Bug description

I have recently deployed my site on a server, and am getting `404 Not Found` errors on valid pages (that both I an the server can visit, tested using tinker) during the static warm process (see below logs)

The affected pages are always the same, and are effectively all pages belonging to collections (`pages` for most, and `programs` for the /workshops/{slug} ones).

I have a similarly set up website on another server (same starter kit, same general `pages` config, but using NGINX instead of Apache) that doesn't have this issue.

### How to reproduce

Unsure.

### Logs

```shell
Visiting 24 URLs...
  /blog/medium .............................................................................................. ✓ Cached
  /blog ..................................................................................................... ✓ Cached
  / ......................................................................................................... ✓ Cached
  /faq/technical ....................................................................................... 404 Not Found
  /contact ............................................................................................. 404 Not Found
  /faq ................................................................................................. 404 Not Found
  /coaching ............................................................................................ 404 Not Found
  /page-not-found ........................................................................................... ✓ Cached
  /lab ................................................................................................. 404 Not Found
  /pedagogy ............................................................................................ 404 Not Found
  /platform ............................................................................................ 404 Not Found
  /privacy-compliance .................................................................................. 404 Not Found
  /privacy-compliance/accessibility .................................................................... 404 Not Found
  /privacy-compliance/data ............................................................................. 404 Not Found
  /privacy-compliance/cinq-eula ........................................................................ 404 Not Found
  /privacy-compliance/terms ............................................................................ 404 Not Found
  /technical-checklist ................................................................................. 404 Not Found
  /test ................................................................................................ 404 Not Found
  /workshops/explorer .................................................................................. 404 Not Found
  /workshops ........................................................................................... 404 Not Found
  /workshops/pathfinder ................................................................................ 404 Not Found
  /workshops/rob-a-bank ................................................................................ 404 Not Found
  /workshops/trailblazer ............................................................................... 404 Not Found
  /workshops/vanguard .................................................................................. 404 Not Found
```

### Environment

```yaml
Environment
Application Name: CinQ Leadership & Teamwork Lab
Laravel Version: 11.44.2
PHP Version: 8.3.6
Composer Version: 2.8.6
Environment: production
Debug Mode: OFF
URL: futurelearning.group
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: gmail
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Disabled (auto)
Static Caching: full
Version: 5.51.0 Solo

Statamic Addons
rias/statamic-collection-groups: 1.1.0
spatie/statamic-responsive-images: 5.2.2
studio1902/statamic-peak-browser-appearance: 3.6.1
studio1902/statamic-peak-seo: 8.20.1
studio1902/statamic-peak-tools: 7.1.0
```

### Installation

Starter Kit using via CLI

### Additional details

I am using Statamic Peak.

I first set up the website locally using Laravel Herd, configured it, and then synced it to my server using git. Here is the `.gitignore` config:

```gitignore
# Node modules directory
node_modules/

# Vite build output
public/build/

# Environment files
.env
.env.*

# Log files
*.log

# Laravel storage (excluding necessary files)
storage/*.key
storage/*.log
storage/framework/sessions/*
storage/framework/views/*
storage/framework/cache/*
storage/debugbar/*
storage/app/private/*
storage/app/public/*
public/storage
public/hot

# Statamic cache
bootstrap/cache/*
public/static/*

# Unite testing cache
/.phpunit.cache

# User uploads (if not versioned)
public/uploads/

# Composer dependencies
/vendor/
/lang/vendor/

# IDE specific files
.idea/
.vscode/

# Local dev files
.antlers.json
Homestead.json
Homestead.yaml

# MacOS specific files
.DS_Store

# Thumbnails
thumbs.php

# Static assets
/public/vendor/statamic
/public/vendor/statamic-peak-tools

# Sensitive user information
/users
/storage/forms
app/Console/Commands/ImportArticlesHtml.php
app/Console/Commands/UpdatePremiumEntries.php
app/Console/Commands/FindMissingPremiumCodes.php

# Root htaccess containing specific server config
.htaccess

# Eventbrite events don't need to be automatically synced
/content/collections/eventbrite_events
```
