### ISSUE TITLE
Conditional rules missing in forms queried via GraphQL

### ISSUE THREAD

**Issue by MSchmidt** [statamic/cms#11600]
### Bug description

When querying forms via GraphQL, there is no way to get the given field conditions from the blueprint. The same is available on the REST-API via a `if` array that is part of the response JSON.

### How to reproduce

1) Set e.g. conditional visibility on any field of a form blueprint.

2) Query via GraphQL with all available fields.

```graphql
{
  forms {
    handle
    rules
    fields {
      config
      display
      handle
      instructions
      type
      width
    }
    honeypot
    title
  }
}
```

### Logs

```shell

```

### Environment

```yaml
Application Name: Statamic
Laravel Version: 11.34.2
PHP Version: 8.3.19
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF
Timezone: UTC
Locale: de
```

### Installation

Fresh statamic/statamic site via CLI
