### ISSUE TITLE
CP Nav Icon selector does not work

### ISSUE THREAD

**Issue by nopticon** [statamic/cms#11623]
### Bug description

If I try to change the icon of any CP Nav, nothing happens.

![Image](https://github.com/user-attachments/assets/6c6d80b0-fd1c-4d1f-b604-3df2c4489abd)

### How to reproduce

- Go to CP Nav
- Edit any Nav Item
- On the Icon field, open the dropdown and select any option or click X
- Nothing happens

_Expected result is to update to the selected icon_

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 12.3.0
PHP Version: 8.3.19
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: sta.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.52.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
