### ISSUE TITLE
Date localization bug in Revisions panel (displays as previous day in GMT minus timezones)

### ISSUE THREAD

**Issue by cjefferies** [statamic/cms#11629]
### Bug description

Groups of revisions share a `day` value where `day` is a unix timestamp of the day at midnight GMT (probably a substring of the ISO date string or something). When this value gets localized (for instance in js/components/revision-history/History.vue; in this.revisions[i].day as rendered in h6.revision-date) it uses the browser's timezone by default. 

Consider adding `timeZone: "UTC",` to the options argument of `toLocaleDateString` method (in this case). I have verified that this works on a local copy. In theory, localization would have already been taken into account when the revisions were grouped and the `day` timestamp got generated (I am inferring this from its behavior, I haven't verified).

### How to reproduce

- Clean install, enable Revisions
- Be in America
- Do something that shows up in the Revisions panel
- Observe that day grouping shows yesterday's date

### Logs

```shell

```

### Environment

```yaml
$ php please support:details

Environment
Application Name: datebug
Laravel Version: 12.3.0
PHP Version: 8.3.13
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: date-bug.vm
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.52.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
