### ISSUE TITLE
Password reset issue with independent authentication guard

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#11639]
### Bug description

After following the changes needed for the [Independent Authentication Guard](https://statamic.dev/tips/using-an-independent-authentication-guard), I'm getting the following exception:

`Base table or view not found: 1146 Table 'project.password_resets' doesn't exist`

Why is Statamic trying to access the database table here? And how can I fix this? I'm quite sure this has worked before (another installation).

### How to reproduce

Just follow the guide on how to use an independent authentication guard, create a user, then try to reset the password via the regular "Reset password" function.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Demo
Laravel Version: 11.44.2
PHP Version: 8.3.19
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: demo.test
Maintenance Mode: OFF
Timezone: Europe/Berlin
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: postmark
Queue: sync
Session: file

Livewire
Livewire: v3.6.2

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.52.0 PRO

Statamic Addons
marcorieser/statamic-livewire: 3.9.0
stillat/antlers-components: 2.6.0
```

### Installation

Existing Laravel app
