### ISSUE TITLE
Nested field inside form field

### ISSUE THREAD

**Issue by Rmkrs13** [statamic/cms#11631]
### Bug description

<img width="2560" alt="Image" src="https://github.com/user-attachments/assets/9462b6d2-029b-46a7-9728-14e16dababc2" />

### How to reproduce

How can I add a custom field to this view?

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: VP capital
Laravel Version: 11.37.0
PHP Version: 8.3.19
Composer Version: 2.8.6
Environment: staging
Debug Mode: ENABLED
URL: vp-capital.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Locales
Installed: en
LaravelLang\Actions\Plugin: 1.8.10
LaravelLang\Attributes\Plugin: 2.11.4
LaravelLang\HttpStatuses\Plugin: 3.8.5
LaravelLang\Lang\Plugin: 15.11.6
Locales Version: 2.9.2
Protected: en
Publisher Version: 16.4.0

Statamic
Addons: 4
Sites: 1
Stache Watcher: Disabled
Static Caching: full
Version: 5.45.1 PRO

Statamic Addons
aerni/advanced-seo: 2.9.3
ndx/statamic-bard-color-picker: 2.0.0
swiftmade/statamic-clear-assets: 3.1.0
thoughtco/statamic-cache-tracker: 0.9.3
```

### Installation

Existing Laravel app
