### ISSUE TITLE
statamic:nocache.replaced event not fired when page is not yet cached.

### ISSUE THREAD

**Issue by Burans** [statamic/cms#11644]
### Bug description

When using full measure static cache the `statamic:nocache.replaced` event is not fired on the first page load (when the page is not yet cached).

Also, Chrome outputs `Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.` on the first page load.

### How to reproduce

1. Fresh Statamic install.
2. Turn on full measure static cache in .env.
3. Replace home template with:

```
<div>Cached content</div>

{{ nocache }}
	<div>Dynamic content</div>
{{ /nocache }}

<script>
	document.addEventListener('statamic:nocache.replaced', (event) => {
		console.log('dynamic content loaded'); // does not fire on the first load.
	});
</script>
```
4. Open the page and see how the "dynamic content loaded" is not logged on the first page load but is logged on the subsequent loads.
5. Clear static cache and test again. 

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 12.4.1
PHP Version: 8.4.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: cachetest.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: full
Version: 5.52.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
