### ISSUE TITLE
Taxonomy terms do not delete, they reappear in slug format, if connected to a draft item

### ISSUE THREAD

**Issue by curiousways** [statamic/cms#11640]
### Bug description

When a taxonomy term is attached to an item, and that item is set to Draft status, and that taxonomy term is deleted, it will come back later in slug format in the taxonomy terms list. The term can only be deleted when it has been removed from the draft item.

### How to reproduce

- Create a taxonomy term
- Attach it to an item
- Set the item to Draft status
- Delete the taxonomy term

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Side
Laravel Version: 11.44.0
PHP Version: 8.2.28
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: side-gallery.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: mailgun
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.49.0 PRO

Statamic Addons
statamic/importer: 1.7.5
statamic/seo-pro: 6.6.2
```

### Installation

Fresh statamic/statamic site via CLI
