### ISSUE TITLE
The use whereTaxonomy method makes a really big check inside a query which makes the query take very long.

### ISSUE THREAD

**Issue by SuperHydroman** [statamic/cms#11645]
### Bug description

Hi, another question regarding statamic performance.

I have a custom query scope, being used in the CP as well as in my templates
```php
$query->whereTaxonomy('resource_type::customer-cases')
    ->where('status', 'published')
    ->whereNotNull('logo')
    ->whereNotNull('logo_asset_exists');
```

I have noticed that the `->whereTaxonomy()` method, adds a check against all entries from a given collection/taxonomy (not really sure), I've attached a screenshot in where you can see the query that is being run. This makes the query very big and takes a while to complete. Having multiple checks like this on a single page makes the load time increase significantly for *obvious* reasons. 

I want to ask why this adds so much to the query and how there is a better method of doing this.

**FYI:** The big query is **WITH** the `->whereTaxonomy()` method and the second (small query) is **WITHOUT** the `->whereTaxonomy()` method.

### How to reproduce

1. Make a collection
2. Make a taxonomy, in which you make some entries
3. Add a taxonomy select to the collection
4. Link a taxonomy to the collection
5. Try to retrieve only a specific set of entries from the collection using the whereTaxonomy method. (See snippet above)
6. Enable Laravel DEBUGBAR and see the big query (large if you have a lot of entries inside the collection).

![Image](https://github.com/user-attachments/assets/8865f4c3-8391-4c85-9686-7fd7e3809f62)
![Image](https://github.com/user-attachments/assets/182bab23-c68a-4370-8bf4-bcf93159a361)

### Logs

```shell

```

### Environment

```yaml
Warning: Module "sqlsrv" is already loaded in Unknown on line 0

Warning: Module "pdo_sqlsrv" is already loaded in Unknown on line 0

Environment
Application Name: IFS Ultimo
Laravel Version: 11.44.2
PHP Version: 8.3.19
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: ultimo-statamic.test
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 6 (English, Deutsch, Español, and 3 more)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.52.0 PRO

Statamic Addons
thoughtco/statamic-cache-tracker: 0.9.3
withcandour/aardvark-seo: 5.0.2
```

### Installation

Other (please explain)

### Additional details

On going project, created from Statamic version 5.28.0, with the use of our custom Starter kit, upgraded in the meantime multiple times till the latest version, speaking as of now. Project has been on-going for 5-6 months. Now that the website is live, we noticed the extremely slow loading speeds, which made us investigate, stumbling upon this bug.
