### ISSUE TITLE
"Add Set" button inside Bard not working

### ISSUE THREAD

**Issue by wuifdesign** [statamic/cms#11653]
### Bug description

When I click the "Add Set" button inside Bard, it sometimes doesn’t work. It appears to close immediately after opening, without giving me a chance to select anything. This issue seems to occur more frequently when many sets have already been added to the page. (no errors are shown in the console)

https://github.com/user-attachments/assets/cbcd2780-7f15-438b-a07c-d360a92be09b

### How to reproduce

Create a Bard element and add many Sets to it, save it and try to add a new set.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: ---
Laravel Version: 11.44.2
PHP Version: 8.2.28
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: 127.0.0.1:8000
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Sentry
Enabled: YES
Environment: local
Laravel SDK Version: 4.13.0
PHP SDK Version: 4.10.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 10%
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 4
Sites: 2 (English, German)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.52.0 PRO

Statamic Addons
jacksleight/statamic-distill: 0.8.2
ndx/statamic-bard-color-picker: 2.0.1
teamnovu/statamic-images-missing-alt: 1.0.5
webographen/statamic-widget-continue-editing: 1.3.2
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

This happens local and on production environment. It may seam to be a problem with focus state of button and editor.
