### ISSUE TITLE
Falsy values are not saved as part of extra form configuration

### ISSUE THREAD

**Issue by Azelen** [statamic/cms#11669]
### Bug description

Hello.

Recently I tried adding a toggle fieldtype as part of my forms' extra configuration with a default value of true. Then wanted to turn it off for some forms. But what I noticed is that "my_toggle_field: false" state is not saved in the form's YAML file.

I dig a bit in the source code and noticed that `$data` variable is filtered before it's saved. This removes all falsy values (empty strings, false, null etc). I am not sure why, haven't digged deeper.

### How to reproduce

1. Install fresh Statamic.
2. Add custom configuration for forms via `\Statamic\Facades\Form::appendConfigFields('*', ...)`
3. The custom configuration must include a Toggle fieldtype with a default value of true.
4. Create a form, go to edit form page, turn the toggle off and save the form.
5. Refresh the page and see the toggle is back on.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.44.2
PHP Version: 8.3.7
Composer Version: 2.5.3
Environment: local
Debug Mode: ENABLED
URL: 127.0.0.1
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 2 (NL, EN)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.51.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.14.0
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

I have only tested this with a toggle field, but as I understand it rejects all falsy values because that's how Laravel's collection filter method works.
