### ISSUE TITLE
Replacing an asset is only executed for the first occurrence

### ISSUE THREAD

**Issue by rmxmr** [statamic/cms#11662]
### Bug description

If you link one asset (e.g. image) to more than one of your pages and replace the image afterwards using the asset-explorer, only the first occurrence (e.g. entry) will be updated. On the other pages the original image stays.

### How to reproduce

- Link the same asset on multiple pages using the asset-fieldset
- Replace the asset in the asset-explorer with another one (either upload a new or select a different one)
- `AssetReplaced` event will be dispatched. Start the queue-worker to handle it
- After handling the event, the asset was replaced only on one of the pages you linked the asset to

### Logs

```shell
-
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 12.7.2
PHP Version: 8.4.5
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mariadb
Logs: stack / single
Mail: smtp
Queue: database
Session: database

Storage
public/storage: NOT LINKED

Locales
Installed: de, en
LaravelLang\Lang\Plugin: 15.19.9
Locales Version: 2.10.0
Protected: en
Publisher Version: 16.6.0

Livewire
Livewire: v3.6.2

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.52.0 PRO

Statamic Addons
pecotamic/sitemap: 1.4.9
```

### Installation

Fresh statamic/statamic site via CLI
