### ISSUE TITLE
min_count parameter not filtering taxonomy terms based on published entries count

### ISSUE THREAD

**Issue by klickreflex** [statamic/cms#11678]
### Bug description

The min_count parameter on taxonomy tags is not correctly filtering terms based on the number of published entries, even though entries_count correctly returns the count of published entries only (as implemented in PR #10727).

For example, when using:
```antlers
{{ taxonomy:offer_focus sort="sort_order" min_count="1" }}
```

Terms with zero published entries are still included in the output. Here's the debug output showing the issue:

```
<!-- Debug: meditation (0) -->
{ id: 'meditation', name: 'Meditation', disabled: false }
```
The term 'meditation' is included in the results despite having 0 published entries, when it should be filtered out by min_count="1".

### How to reproduce

1. Create a taxonomy with multiple terms
2. Create some entries and assign them to different taxonomy terms
3. Ensure some entries are published and others are draft
4. In a template, use a taxonomy tag with min_count="1"
5. Add debug output to show entries_count for each term:
```antlers
{{ taxonomy:your_taxonomy min_count="1" }}
    <!-- Debug: {{ slug }} ({{ entries_count }}) -->
    { id: '{{ slug }}', name: '{{ title }}' }
{{ /taxonomy:your_taxonomy }}
```
6. Observe that terms with entries_count of 0 are still included in the output, despite min_count="1"

### Environment

```yaml
Environment
Application Name: privaate
Laravel Version: 11.44.2
PHP Version: 8.3.19
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: private.test
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Sites: 2 (Deutsch, English)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.52.0 PRO

Statamic Addons
ademti-software/form-protection: 1.0.1
croox/statamic-auto-translator: dev-main
croox/statamic-form-stats: dev-main
duncanmcclean/static-cache-manager: 4.0.1
goldnead/statamic-toc: 1.7
rias/statamic-redirect: 3.10.3
studio1902/statamic-peak-seo: 8.21.1
```

### Installation

Starter Kit using via CLI

### Additional details

**Current workaround:**

As a temporary workaround, you can manually filter the terms using an if condition:
```antlers
{{ taxonomy:your_taxonomy }}
    {{ if entries_count > 0 }}
        { id: '{{ slug }}', name: '{{ title }}' }
    {{ /if }}
{{ /taxonomy:your_taxonomy }}
```
