### ISSUE TITLE
Unable to navigate through assets folders when replacing images

### ISSUE THREAD

**Issue by mattmultiplied** [statamic/cms#11676]
### Bug description

When replacing image, I am unable to navigate through folders.

https://www.loom.com/share/cc770348a9db490bb7c382bc038fefcf?sid=a06f4931-51c1-4cee-9ddc-1bfa9030f830

### How to reproduce

https://www.loom.com/share/cc770348a9db490bb7c382bc038fefcf?sid=a06f4931-51c1-4cee-9ddc-1bfa9030f830

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Wilson Power Solutions
Laravel Version: 11.44.2
PHP Version: 8.3.12
Composer Version: 2.8.5
Environment: local
Debug Mode: ENABLED
URL: wilson-power-solutions.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: CACHED
Events: CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 3 (Wilson Power Solutions, Wilson Power Solutions India, WATTS Rental Dubai)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.52.0 PRO

Statamic Addons
alt-design/alt-redirect: 1.6.3
jacksleight/statamic-bard-texstyle: 3.5.2
statamic/collaboration: 1.0.0
statamic/seo-pro: 6.6.3
teamnovu/statamic-images-missing-alt: 1.0.5
```

### Installation

Fresh statamic/statamic site via CLI
