### ISSUE TITLE
Data too long for column 'url' when using nocache on query parameter urls

### ISSUE THREAD

**Issue by mattmultiplied** [statamic/cms#11684]
### Bug description

We've recently built a site which has a filtering mechanism using query parameters, we also use query parameters for pagination. 

When filtering through products, eventually the URL becomes too long for the 'url' column in the nocache_regions table. This also sometimes occurs when using some marketing platforms which can add a lot of query parameters.

As our pagination uses query strings we can't set 'ignore_query_strings' => true' as we will have incorrect pagination.

### How to reproduce

https://www.loom.com/share/60d5ffeb1c46427da1aecefa5d3b8a92?sid=16e7faa6-e732-4211-bf08-baf7ffdef3e8

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: BBP
Laravel Version: 10.48.28
PHP Version: 8.3.12
Composer Version: 2.8.5
Environment: local
Debug Mode: ENABLED
URL: bbp.test
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: file
Database: mysql
Logs: stack / single, sentry
Mail: smtp
Queue: sync
Session: file

Sentry
Enabled: YES
Environment: local
Laravel SDK Version: 4.13.0
PHP SDK Version: 4.10.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 100%
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.49.1 PRO

Statamic Addons
alt-design/alt-redirect: 1.6.2
jacksleight/statamic-bard-texstyle: 3.4.1
statamic/importer: 1.7.5
```

### Installation

Fresh statamic/statamic site via CLI
