### ISSUE TITLE
CP login url redirect is encoded; fails to render cp route

### ISSUE THREAD

**Issue by wautersj** [statamic/cms#11685]
### Bug description

Since shortly, I'm experiencing that when i login to the CP; and am redirected to pages collection, i'm redirected to url: /cp/collections%2Fpages instead of /cp/collections/pages. This results in a 404 Not Found - The requested URL was not found on this server.

### How to reproduce

- Go to the login url as configured (by default /cp)
- Login with the user details
- I am now redirected to /cp/collections%2Fpages
- I see server feedback: 404 Not Found

<img width="694" alt="Image" src="https://github.com/user-attachments/assets/f170b6fa-810c-4f7f-97a6-00b6bc2a4702" />

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Xeikon
Laravel Version: 10.48.29
PHP Version: 8.2.27
Composer Version: 2.5.4
Environment: production
Debug Mode: ENABLED
URL: xeikon-statamic.valet/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: sendmail
Queue: sync
Session: file

Livewire
Livewire: v3.6.2

Sentry
Enabled: MISSING DSN
Environment: production
Laravel SDK Version: 3.8.2
PHP SDK Version: 3.22.1
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 3
Sites: 2 (English, Deutsch)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.52.0 PRO

Statamic Addons
digiti/statamic-crow: 1.1.2
marcorieser/statamic-livewire: 4.4.0
statamic/seo-pro: 6.6.3
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

I have this issue on 4 different sites.
