### ISSUE TITLE
Unpublish multisite taxonomy term

### ISSUE THREAD

**Issue by tobinski** [statamic/cms#11694]
### Bug description

I have a multisite page with two languages. I setup a taxonomy, with some terms. Now, I need a term just in one language, and not in another. This is not possible at the moment. If you have a term in one language, there is no option to hide it from the other one.

### How to reproduce

1. Setup a new statamic multisite with two languages
2. Add a taxonomy
3. Make taxonomy available in both languages
4. Try to hide a term in one language

![Image](https://github.com/user-attachments/assets/82fc4db1-bcd3-481a-b8e0-3253cad5bebd)

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: ------
Laravel Version: 11.44.2
PHP Version: 8.2.6
Composer Version: 2.5.7
Environment: production
Debug Mode: OFF
URL: ---------
Maintenance Mode: OFF
Timezone: Europe/Zurich
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / daily, flare
Mail: smtp
Queue: sync
Session: file

Locales
Installed: de, de_CH, en, fr
LaravelLang\Actions\Plugin: 1.10.1
LaravelLang\Attributes\Plugin: 2.13.4
LaravelLang\HttpStatuses\Plugin: 3.10.3
LaravelLang\Lang\Plugin: 15.19.9
LaravelLang\MoonShine\Plugin: INCORRECT
LaravelLang\StarterKits\Plugin: 1.3.6
Locales Version: 2.10.0
Protected: de, en
Publisher Version: 16.6.0

Statamic
Addons: 3
Sites: 3 (Frieda Deutsch, Frieda Französisch, Frieda Englisch)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.52.0 PRO

Statamic Addons
appswithlove/statamic-one-click-content-translation: 5.2.3
martyfriedel/les-mills-class-types: dev-captns
spatie/statamic-responsive-images: 5.2.2
```

### Installation

Fresh statamic/statamic site via CLI
