### ISSUE TITLE
Moving assets breaks references

### ISSUE THREAD

**Issue by 925dk** [statamic/cms#11690]
### Bug description

I moved a bunch of assets (images) into a new folder.... like half of the content referencing those images weren't updated.

CP -> Assets. Checked like 20 and clicked Move.

### How to reproduce

Move some assets.

### Environment

```yaml
Environment
Application Name: xxx
Laravel Version: 11.44.2
PHP Version: 8.3.16
Composer Version: 2.5.8
Environment: production
Debug Mode: OFF
URL: xxx
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: sqlite
Logs: stack / single
Mail: sendmail
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.53.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
