### ISSUE TITLE
Multisite Flat Collection Routing – Secondary Site Always 404

### ISSUE THREAD

**Issue by oldinosor** [statamic/cms#11709]
### Bug description

In a Statamic 5.x multisite setup with two sites (English default and French secondary), flat collection entries are routed correctly on the main site (e.g. `/demo`), but the same entry on the secondary site (e.g. `/fr/demo`) always returns a 404.

Both entries exist, have the same `id` and `slug`, are published, and use the same template. The issue persists after clearing all caches, deleting and recreating entries, changing locale codes, and even after downgrading/upgrading Statamic.

No custom routes are defined. The bug occurs even with a brand new collection and a minimal setup.

### How to reproduce

1. Set up a Statamic 5.x multisite with two sites:
   - `default` (English, `en_US`, `/`)
   - `french` (French, `fr`, `/fr/`)
2. Create a flat collection (no structure) called `demo`, with `route: '{slug}'` and `sites: [default, french]`.
3. Add an entry with the same `id` and `slug` (`demo`) in both `default` and `french` subfolders, both published and using the same template.
4. Clear all caches (`php please cache:clear && php please stache:refresh`), and manually delete `storage/statamic/*` and `storage/framework/cache/*`.
5. Visit `/demo` (works) and `/fr/demo` (404).
6. Try all troubleshooting steps (recreating entries, changing locale from `fr_FR` to `fr`, testing on a new collection, updating/downgrading Statamic) – the 404 persists on the secondary site.

### Logs

```shell
No error messages are shown in `storage/logs/laravel.log` when accessing `/fr/demo`.
Only unrelated warnings (e.g. deprecated CLI commands) are present.
```

### Environment

```yaml
Statamic version: 5.x (also tested on previous release)
Laravel version: 12.x
PHP version: 8.2+
OS: macOS
Herd
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

- demo.yaml:
  title: Demo
  revisions: false
  route: '{slug}'
  sites:
    - default
    - french

- default/demo.md:
  ---
  id: demo-multi
  slug: demo
  title: Demo EN
  published: true
  template: test
  ---
  Demo content EN

- french/demo.md:
  ---
  id: demo-multi
  slug: demo
  title: Démo FR
  published: true
  template: test
  ---
  Contenu démo FR

All standard troubleshooting steps have been attempted. The issue occurs even in a minimal, clean project.

**Comment by duncanmcclean** [comment]
What does your `resources/sites.yaml` file look like?

**Comment by oldinosor** [comment]
@duncanmcclean 

> What does your `resources/sites.yaml` file look like?

Here is the content of my resources/sites.yaml file:

default:
  name: Anglais
  url: /
  locale: en_US
  lang: en_US
francais:
  name: Français
  url: /fr/
  locale: fr_FR
  lang: fr_FR

Please note that my main site configuration is also in config/statamic/sites.php (as posted above).

**Comment by duncanmcclean** [comment]
The `config/statamic/sites.php` config file was [removed in Statamic 5](https://statamic.dev/upgrade-guide/4-to-5#site-configuration-changes). What does it look like?

Also, can you please provide the full output of `php please support:details`?

**Comment by oldinosor** [comment]
@duncanmcclean

> The `config/statamic/sites.php` config file was [removed in Statamic 5](https://statamic.dev/upgrade-guide/4-to-5#site-configuration-changes). What does it look like?
> 
> Also, can you please provide the full output of `php please support:details`?

In my project, I still have a config/statamic/sites.php file.

Here is its content:

<?php

return [
    'default' => 'default',
    'sites' => [
        'default' => [
            'name' => 'English',
            'locale' => 'en_US',
            'url' => '/',
            'direction' => 'ltr',
        ],
        'french' => [
            'name' => 'Français',
            'locale' => 'fr',
            'url' => '/fr/',
            'direction' => 'ltr',
        ],
    ],
];

Here is the full output of php please support:details:

Environment
Application Name: Statamic
Laravel Version: 12.9.1
PHP Version: 8.4.5
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: stawtd.test
Maintenance Mode: OFF
Timezone: UTC
Locale: fr

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 0
Sites: 2 (Anglais, Français)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.53.0 PRO

**Comment by duncanmcclean** [comment]
> In my project, I still have a config/statamic/sites.php file.

You can delete it now. It's no longer used.

---

Can you try making them absolute URLs, instead of relative URLs (eg. include the `APP_URL` in it). Like this:

```yaml
default:
  name: Anglais
  url: '{{ config:app:url }}'
  locale: en_US
  lang: en_US
francais:
  name: Français
  url: '{{ config:app:url }}/fr/'
  locale: fr_FR
  lang: fr_FR
```

**Comment by oldinosor** [comment]
I have deleted the obsolete config/statamic/sites.php file as recommended.

I have also updated my resources/sites.yaml file with absolute URLs as follows:

```yaml
default:
  name: Anglais
  url: '{{ config:app:url }}'
  locale: en_US
  lang: en_US
francais:
  name: Français
  url: '{{ config:app:url }}/fr/'
  locale: fr_FR
  lang: fr_FR
```

After clearing all caches (php please cache:clear && php please stache:refresh), both /demo and /fr/demo still return a 404.
Is there anything else I should try ?

Thank you for your continued help!

**Comment by oldinosor** [comment]
@jasonvarga 

> > Both entries exist, have the same id and slug
> 
> Both have the same`id`? They shouldn't.

I have followed all the latest suggestions:

I deleted the old config/statamic/sites.php file.
I updated my resources/sites.yaml to use absolute URLs and changed the secondary site key from francais to french:

```yaml
default:
  name: Anglais
  url: '{{ config:app:url }}'
  locale: en_US
  lang: en_US
french:
  name: Français
  url: '{{ config:app:url }}/fr/'
  locale: fr_FR
  lang: fr_FR
```

Both entry files now have different id values but the same slug: content/collections/demo/default/demo.md

```yaml
---
id: demo-en
slug: demo
title: Demo EN
published: true
template: test
---
Demo content EN
```

content/collections/demo/french/demo.md

```yaml
---
id: demo-fr
slug: demo
title: Démo FR
published: true
template: test
---
Contenu démo FR
```

I cleared all caches and refreshed the Stache after every change.
Both /demo and /fr/demo still return a 404 error.
