### ISSUE TITLE
When a taxonomy field is set to max items one, filtering on the taxonomy field in the CMS returns no items

### ISSUE THREAD

**Issue by mattmultiplied** [statamic/cms#11707]
### Bug description

When a taxonomy field is set to max items one, filtering on the taxonomy field in the CMS returns no items

### How to reproduce

https://www.loom.com/share/efde170e5857416cadda159c053eab1f?sid=96a5eb5c-282a-4d59-966c-9140e92dfabb

Create a blueprint with a taxonomy field with max items set to one, when attempting to filter on the taxonomy it will always return no items.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: XXX
Laravel Version: 11.44.2
PHP Version: 8.3.12
Composer Version: 2.8.5
Environment: local
Debug Mode: ENABLED
URL: wilson-power-solutions.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: CACHED
Events: CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 3
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.53.0 PRO

Statamic Addons
alt-design/alt-redirect: 1.6.3
jacksleight/statamic-bard-texstyle: 3.5.2
statamic/seo-pro: 6.6.3
teamnovu/statamic-images-missing-alt: 1.0.5
```

### Installation

Fresh statamic/statamic site via CLI
