### ISSUE TITLE
`shuffle` (and `first`) modifiers do not work for collections

### ISSUE THREAD

**Issue by AtmoFX** [statamic/cms#11719]
### Bug description

I am trying to shuffle the entries of a collection, and I always get them in the same order.

It must have broken down some time after https://github.com/statamic/cms/pull/2709

### How to reproduce

Add the below snippet on a page, choosing a collection with several entries (ideally 4 or more).

You will see the entries printed side by side are in the same order, and that order will not change if you refresh.
This is to be compared with the shuffled string and array that are not returned in the same order, be it within the same page or after refreshing.

```
<div class="py-2 w-160 flex flex-row justify-between">
    <ol>
        {{ collection use="<your chosen collection>" | shuffle }}
            <li>{{ id }}</li>
        {{ /collection }}
    </ol>
    <ol>
        {{ collection use="<your chosen collection>" | shuffle }}
            <li>{{ id }}</li>
        {{ /collection }}
    </ol>
</div>

<div class="py-2">
    {{ my_string = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" }}
    {{ my_string | shuffle }}<br/>
    {{ my_string | shuffle }}<br/>
</div>

<div class="py-2 w-160 flex flex-row justify-between">
    {{ places = "Scotland, England, Switzerland, Italy" }}
    {{ places | explode(',') | shuffle | ol }}
    {{ places | explode(',') | shuffle | ol }}
</div>
```

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: GaiaMine UAT
Laravel Version: 11.44.2
PHP Version: 8.3.20
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: gaiamine.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: database

Pulse
Enabled: ENABLED
Version: v1.4.1

Livewire
Livewire: v3.6.3

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.53.0 PRO

Statamic Addons
alt-design/alt-seo: 1.3.0
jacksleight/statamic-bard-mutator: 3.0.3
statamic/eloquent-driver: 4.21.0
stillat/antlers-components: 2.6.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Not exactly a problem for me but the `first` modifier does not work for collections either.

My assumption here is that collections were treated as "regular" arrays of entries when https://github.com/statamic/cms/pull/2709 was implemented, and it is no more the case now.
