### ISSUE TITLE
"Edit" option is visible on relationship fieldtypes, even when user is missing relevant permissions

### ISSUE THREAD

**Issue by hailwood** [statamic/cms#11718]
### Bug description

When a user does not have the permissions to edit a taxonomy, the "Edit" option is still visible when using the "Taxonomy Terms" field.

![Image](https://github.com/user-attachments/assets/d22f1636-4fd5-43ed-9020-7aacda2c8959)

It appears that even though we have the data to say whether the individual taxonomy is editable, we are simply checking if the entire field is editable, and if so we show the edit button on the term.

Selecting the Edit button gives a page flash and then 
![Image](https://github.com/user-attachments/assets/3d0e3848-a533-461e-94a8-063bd07ee1e8)

### How to reproduce

1. Create a taxonomy
2. Create a non super-user user without permissions to edit taxonomies
3. Grant the user permissions to edit the entries
4. Add a Taxonomy Terms field to the blueprint of your entry

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: My Statamic Site
Laravel Version: 12.9.2
PHP Version: 8.4.2
Composer Version: -
Environment: local
Debug Mode: ENABLED
URL: example.lndo.site
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.53.1 PRO

Statamic Addons
statamic/eloquent-driver: 4.21.1

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```

### Installation

Fresh statamic/statamic site via CLI
