### ISSUE TITLE
Search in collection index returns non-collection items

### ISSUE THREAD

**Issue by simonerd** [statamic/cms#11710]
### Bug description

Consider a collection which has a specified search index, which does not only include the collections own entries. Let's say I specified `search_index: default` for my collection `articles`, but the `default` index is set to `'searchables' => 'all'`. Using the search bar in the `articles` collection index can now show entries from e. g. the `pages` collection, if the search term matches.

Looking into `Http/Controllers/CP/Collections/EntriesController` I realised that there's no "where" that's limiting to the current collection in the `indexQuery` function (or anywhere else). 

### How to reproduce

Fresh install, add `search_index: default` to pages collection config. Create a second collection and create an entry with title "Foo". Go to Pages collection, list view and type in "Foo" into the search bar. The entry from the other collection will be listed.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: my_app
Laravel Version: 11.44.2
PHP Version: 8.3.19
Composer Version: 2.8.5
Environment: local
Debug Mode: ENABLED
URL: localhost:8001
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: pgsql
Logs: daily
Mail: log
Queue: database
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.53.0 PRO

Statamic Addons
statamic-rad-pack/typesense: 2.1.1
statamic/eloquent-driver: 4.21.1

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: eloquent
Navigations: file
Revisions: eloquent
Sites: file
Taxonomies: file
Terms: eloquent
Tokens: eloquent
```

### Installation

Fresh statamic/statamic site via CLI
