### ISSUE TITLE
Error 500 when creating an entry

### ISSUE THREAD

**Issue by AtmoFX** [statamic/cms#11728]
### Bug description

One of my CP users cannot create an entry, the error is:

![Image](https://github.com/user-attachments/assets/50d7cfab-5972-4af7-87a4-64c9bbfbdb8b)

![Image](https://github.com/user-attachments/assets/8a37e730-8d96-41eb-a1c7-36e878ee2ba2)

![Image](https://github.com/user-attachments/assets/02d0571f-ce13-47e6-bed2-0d7115bae41b)

As suggested by the second picture, the error seems to occur because the user has no privilege to edit other authors' entries (though it should not be triggered here since they are trying to create a new entry, with their name as the author). Sure enough, if I grant the privilege to the user, the error disappears.

### How to reproduce

1. Create a role with the ability to create/edit entries in some collection. Importantly, make sure the role does not grant the "Edit other authors' entries" privilege.
2. Create an entry, you should encounter an Error 500 reply.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: GaiaMine Ltd
Laravel Version: 11.44.2
PHP Version: 8.3.16
Composer Version: 1.10.26
Environment: production
Debug Mode: OFF
URL: gaiamine.com
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: database

Pulse
Enabled: ENABLED
Version: v1.4.1

Livewire
Livewire: v3.6.3

Statamic
Addons: 5
Sites: 1
Stache Watcher: Disabled (auto)
Static Caching: Disabled
Version: 5.53.1 PRO

Statamic Addons
alt-design/alt-seo: 1.3.0
jacksleight/statamic-bard-mutator: 3.0.3
marcorieser/statamic-livewire: 4.4.3
statamic/eloquent-driver: 4.21.1
stillat/antlers-components: 2.6.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
