### ISSUE TITLE
Error creating term in a multi-site when taxonomy has sites in different order than default

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#11733]
### Bug description

In a multi-site, tried to create a taxonomy term.

### How to reproduce

1. Create a site
2. Make it multi-site, giving the second site the handle `second`
3. Create a taxonomy and assign to both sites but make sure `second` is the first one listed.
4. Make sure you're in the default (first) site
5. try to create a Categories term.

### Logs

```shell
[2025-04-24 17:53:14] local.ERROR: Call to a member function all() on null {"userId":"d443f122-c7bc-474b-bdea-cc5ca52024b4","exception":"[object] (Error(code: 0): Call to a member function all() on null at /Users/erin/Sites/multi-term/vendor/statamic/cms/src/Taxonomies/Term.php:113)
[stacktrace]
#0 /Users/erin/Sites/multi-term/vendor/statamic/cms/src/Data/ExistsAsFile.php(45): Statamic\\Taxonomies\\Term->fileData()
#1 /Users/erin/Sites/multi-term/vendor/statamic/cms/src/Data/ExistsAsFile.php(94): Statamic\\Taxonomies\\Term->fileContents()
#2 /Users/erin/Sites/multi-term/vendor/statamic/cms/src/Stache/Stores/BasicStore.php(142): Statamic\\Taxonomies\\Term->writeFile()
#3 /Users/erin/Sites/multi-term/vendor/statamic/cms/src/Stache/Stores/TaxonomyTermsStore.php(196): Statamic\\Stache\\Stores\\BasicStore->writeItemToDisk(Object(Statamic\\Taxonomies\\Term))
#4 /Users/erin/Sites/multi-term/vendor/statamic/cms/src/Stache/Repositories/TermRepository.php(127): Statamic\\Stache\\Stores\\TaxonomyTermsStore->save(Object(Statamic\\Taxonomies\\Term))
#5 /Users/erin/Sites/multi-term/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(361): Statamic\\Stache\\Repositories\\TermRepository->save(Object(Statamic\\Taxonomies\\Term))
#6 /Users/erin/Sites/multi-term/vendor/statamic/cms/src/Taxonomies/Term.php(224): Illuminate\\Support\\Facades\\Facade::__callStatic('save', Array)
#7 /Users/erin/Sites/multi-term/vendor/statamic/cms/src/Taxonomies/LocalizedTerm.php(439): Statamic\\Taxonomies\\Term->save()
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 12.10.2
PHP Version: 8.3.20
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: multi-term.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 0
Sites: 2 (First, Second)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.53.1 PRO
```

### Installation

Fresh statamic/statamic site via CLI
