### ISSUE TITLE
Form Files fieldtype frontend component bug when displaying a single file

### ISSUE THREAD

**Issue by Azelen** [statamic/cms#11734]
### Bug description

I tried creating a form with a Files field and noticed this bug when viewing form submission in the CP when field has `max_files` set to 1:

![Image](https://github.com/user-attachments/assets/7f39f0c2-b9a0-426d-9909-a5456e08705e)

The frontend component always expects an array of items as I understand, otherwise it splits the file name into individual characters.

### How to reproduce

1. Create a form with a Files fieldtype and set Max Files config to 1.
2. Submit a form with a file.
3. View submission in CP.

### Logs

```shell

```

### Environment

```yaml
Application Name: Statamic
Laravel Version: 11.44.2
PHP Version: 8.3.7
Composer Version: 2.5.3
Environment: local
Debug Mode: ENABLED
URL: http://127.0.0.1:8000
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Sites: 2 (NL, EN)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.53.1 PRO

Statamic Addons
aerni/advanced-seo: 2.13.0
aryehraber/statamic-captcha: 1.14.0
eminos/statamic-tabs: 1.2.0
jacksleight/statamic-bard-texstyle: 3.5.2
rias/statamic-redirect: 3.10.6
teamnovu/statamic-images-missing-alt: 1.0.5
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

I solved this by overriding Files fieldtype in my app and changing the `process` method to always return an array, this solved the issue, but I am not sure it's the right way to fix this.
