### ISSUE TITLE
Addon editions are not being retrieved from the composer.json file as expected.

### ISSUE THREAD

**Issue by jpgorman** [statamic/cms#11759]
### Bug description

When setting a list of editions in an addons composer file e.g.

myaddon composer.json
```json
{
    "extra": {
        "statamic": {
            "editions": ["free", "pro"]
        }
    }
}
```
Then in a project that consumes myaddon, add the following to the `config/statamic/editions.php`

```php
'addons' => ['vendor/myaddon' => 'free'];
```

The statamic app will through an error e.g `Invalid edition [free] for addon myaddon`.

According to the [documentation](https://statamic.dev/extending/addons#defining-editions) this is the method that should be used to define editions for an addon.

### How to reproduce

Create an addon. Add the following to the composer.json
```json
{
    "extra": {
        "statamic": {
            "editions": ["free", "pro"]
        }
    }
}
```

Then in a project that consumes myaddon, add the following to the `config/statamic/editions.php`

```php
'addons' => ['vendor/myaddon' => 'free'];
```

Access and control panel i.e. uncached route.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.21.0
PHP Version: 8.3.13
Composer Version: 2.8.2
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single, stderr, stdout, json
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.23.0 PRO

Statamic Addons
jpgorman/cloudinary: dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

I was able to mitigate this issue by adding the following to my addons ServiceProvider's boot sequence:

```php
protected function bootEditions() {
  Addon::get('vendor/myaddon')->editions(['free', 'pro]);
  return $this;
}
```

I saw in the Extend\Addon.php tests that this is method that would work : https://github.com/statamic/cms/blob/c3751a170a7102fa32da885ed3e4104c8313de3a/tests/Extend/AddonTest.php#L85
