### ISSUE TITLE
Sync with Origin erroneous when using date field as publication date

### ISSUE THREAD

**Issue by lostgeek** [statamic/cms#11752]
### Bug description

On a multisite setup, when creating a new localised entry, that entry can have a different publication date. This can be entered correctly and also saves correctly.

When opening the entry, the 🔗 symbol for "sync with origin" is erroneously set, which leads to saving the origin date overriding the data visible to the user.

Wondering whether this is connected to https://github.com/statamic/cms/issues/10688

### How to reproduce

https://github.com/user-attachments/assets/53a067c2-49f5-472b-bfdb-908bf682cafc

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: statamic-skeleton
Laravel Version: 11.41.0
PHP Version: 8.3.19
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: statamic-skeleton.novu.io
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: redis

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.10.1
PHP SDK Version: 4.10.0
Release: da3a453
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 1%
Sample Rate Profiling: 1%
Send Default PII: ENABLED

Statamic
Addons: 4
Sites: 2 (🇩🇪 Deutsch, 🇫🇷 Français)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.53.1 PRO

Statamic Addons
cnj/seotamic: 5.0.0
teamnovu/graphql-breadcrumbs: 1.0.7
teamnovu/localize: 5.0.0
teamnovu/statamic-gql-swr-cache: 1.0.0
```

### Installation

Other (please explain)
