### ISSUE TITLE
Replaced asset does not relink to asset fields in entries

### ISSUE THREAD

**Issue by mkwia** [statamic/cms#11769]
### Bug description

When using the [Replace Asset function](https://statamic.dev/assets#replace) the original asset is correctly deleted (when the option is toggled on) and the new asset is correctly uploaded, however the new asset is not relinked to asset fields in entries where the original asset was being used in accordance with the documentation "Replaced assets with the replace action will update any references to it throughout your content".

### How to reproduce

1. Create a new entry which has an asset field.
2. Upload an image
![Image](https://github.com/user-attachments/assets/b102f7d0-6bf1-4bf9-a8a2-691c1a923f20)
3. In the asset area replace the image with another one (of a different filename - this report is not the same as #11229  )
![Image](https://github.com/user-attachments/assets/3a817f1b-9e8e-44cc-ad73-943de1836914)
4. The asset field in the entry is now empty since the original asset is deleted and relinking did not occur
![Image](https://github.com/user-attachments/assets/b41a155e-8e09-436e-b080-e05851d0a539)
![Image](https://github.com/user-attachments/assets/1be2dbba-2332-48f4-93f8-d793e1df7a61)

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: #############################
Laravel Version: 11.44.7
PHP Version: 8.2.27
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: #############################
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 8
Sites: 12 (Global (English), Germany (German), UK (English), and 9 more)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.53.1 PRO

Statamic Addons
edalzell/forma: 3.1.1
robole/advanced-table: 0.0.0
silentz/akismet: 5.1
statamic-rad-pack/runway: 8.3.1
statamic/eloquent-driver: 4.21.1
thoughtco/statamic-cache-tracker: 0.9.3
withcandour/aardvark-seo: 5.0.3
withcandour/statamic-markdown-table: 1.0.0-beta

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
