### ISSUE TITLE
Bard field's set replication uses same object for multiple sets

### ISSUE THREAD

**Issue by faltjo** [statamic/cms#11765]
### Bug description

When using the bard field type, one can define custom sets. If the used set includes fields which rely on objects (e.g. address field), adding additional sets of this type to the bard field does not work correctly.

The new sets use a shallow copy of the previous set and therefore the same objects are used in the background. If the data of one set is changed, the same changes are reflected to the other sets.

It is expected that all those sets can hold their data individually and independently from the other sets of the same type.

This bug is very similar to: https://github.com/statamic/cms/issues/11619

### How to reproduce

1. Clone https://github.com/faltjo/fix-bard-field-set-bug
2. Duplicate .env.example and rename it to .env
3. `composer install`
4. `npm install`
5. `herd php artisan key:generate`
6. Create a new user and open the CP
7. Create a new entry in the collection 'Articles'
8. Go to the 'Bard Content' field and add two sets by clicking '+', which shows when clicking into text-area of the field.
9. Edit the Street of the first set, see that the second set also changes its value and vice-versa. You can add additional sets and see the same behaviour.

In the screenshot the first set was changed actively and the changes got reflected to the second one, which should be independent from the first.

<img width="1233" alt="Image" src="https://github.com/user-attachments/assets/38261a7a-ceff-437e-af8c-d3aeb1f6af69" />

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 12.12.0
PHP Version: 8.3.20
Composer Version: 2.8.8
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.54.0 PRO

Statamic Addons
rias/statamic-address-field: 1.4.0
```

### Installation

Starter Kit using via CLI

### Additional details

The address-field addon is used (https://statamic.com/addons/rias/address-field).
