### ISSUE TITLE
Route tag not working with Statamic route

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#11762]
### Bug description

I'm trying to use the [Statamic route tag](https://statamic.dev/tags/route) to create a link to my search page definined in `routes/web.php` but I'm getting an error:

```bash
Symfony \ Component \ Routing \ Exception \ RouteNotFoundException
PHP 8.4.6
12.12.0
Route [search] not defined.
```

### How to reproduce

**routes/web.php** content:
```php
<?php

use Illuminate\Support\Facades\Route;

Route::statamic('search', 'search/index', [
    'title' => __('theme.search.title'),
    'description' => __('theme.search.description'),
]);
```

trying to get **search route** in Antlers:
```twig
<a href="{{ route:search }}">Search</a>
```
I've tried to clear route cache, but it doesn't help.

### Environment

```yaml
Environment
Application Name: Website
Laravel Version: 12.12.0
PHP Version: 8.4.6
Composer Version: 2.8.8
Environment: local
Debug Mode: ENABLED
URL: website.test
Maintenance Mode: OFF
Timezone: Europe/Paris
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: redis
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.54.0 PRO

Statamic Addons
rias/statamic-redirect: 3.10.7
spatie/statamic-responsive-images: 5.2.2
statamic/seo-pro: 6.6.4
```

### Installation

Fresh statamic/statamic site via CLI
