### ISSUE TITLE
trying to login after first install

### ISSUE THREAD

**Issue by ZachBacon** [statamic/cms#11761]
### Bug description

So I've tried to search to see if this was an issue, and off hand I have not seen it yet, but when I go to mysite.com/cp the elements that disappear when the page finished loading. I've tried in a few chromium based browser, firefox on a variety of devices, from android, macos, linux and even windows and the elements containing the login field just disappears.

### How to reproduce

I honestly don't know how to reproduce it since I'm sure this might just be localized to my setup

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 12.12.0
PHP Version: 8.4.6
Composer Version: 2.8.8
Environment: local
Debug Mode: ENABLED
URL: thatzachbacon.com.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.54.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
