### ISSUE TITLE
Entries Fieldtype: Setting UI mode to other than default disables the "create" option

### ISSUE THREAD

**Issue by StevenRiot** [statamic/cms#11789]
### Bug description

In an Entries fieldset, if you pick "select" or "typeahead" as mode instead of the default (Stack Selector), the create buttons aren't visible, even if the "create" option is set to true.

### How to reproduce

In a collection's blueprint, create three fieldsets. 
Set the UI mode of :

- the first one as "Stack Selector" (default)
- the second one as "Dropdown"
- the third one as "Typehead Field"

Make sure the "Allow creating" toggle is on for all three of them.

Then go to an entry's edit page. Only the first field will show the "Create & Link Item" and "Link Existing Item" buttons.

You can then try typing stuff in the last 2 fields to search in the collection, and if there are no results, you just see "No options to choose from" (no "Create & link" button there either.)

### Logs

```shell

```

### Environment

```yaml
Application Name: Secret stuff
Laravel Version: 11.30.0
PHP Version: 8.3.8
Composer Version: 2.8.2
Environment: local
Debug Mode: ENABLED
URL
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 10
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.40.0 Solo

Statamic Addons
edalzell/forma: 3.0.1
goldnead/statamic-collapse-fieldtype: 1.1
jonassiewertsen/statamic-jobs: 1.5.0
rias/statamic-collection-groups: 1.1.0
stillat/relationships: 2.2.1
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.9.0
studio1902/statamic-peak-seo: 8.16.0
studio1902/statamic-peak-tools: 6.3.3
transformstudios/events: 5.4.3
```

### Installation

Fresh statamic/statamic site via CLI
