### ISSUE TITLE
Using Eloquent driver triggers error

### ISSUE THREAD

**Issue by SteveEdson** [statamic/cms#11795]
### Bug description

I installed the eloquent driver, but immediately got an issue when the entries were imported to the database:

![Image](https://github.com/user-attachments/assets/7fadd5d3-863e-415c-9067-981df23a3e74)

I've spent some time diving into this and I've found the issue, but i'm not quite sure why.

In `src/Structures/CollectionStructure.php`, line 78, the following breaks:
```php
$thisCollectionsEntries = $this->collection()->queryEntries()
            ->where('site', $locale)
            ->pluck('id');
```

However changing it to:
```php
$thisCollectionsEntries = $this->collection()->queryEntries()
            ->where('site', '=', $locale)
            ->pluck('id');
```

Resolves the issue. It seems to think the `$locale` is the operator, which doesn't work. Is this a bug in the core, or something in my config? If it was truly broken, everyone would be having this issue, so i'm not sure why it's just me?

### How to reproduce

I just installed the eloquent driver and imported collections and entries.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: XXXX
Laravel Version: 11.44.7
PHP Version: 8.3.20
Composer Version: 2.8.8
Environment: local
Debug Mode: ENABLED
URL: XXXX.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 26 (Belgium / Dutch, Belgium / French, Denmark / Danish, and 23 more)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.55.0 PRO

Statamic Addons
alt-design/alt-redirect: 1.6.3
mitydigital/sitemapamic: 3.2.0
statamic/eloquent-driver: 4.21.1
statamic/ssg: 3.1.1

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
