### ISSUE TITLE
Scheduled publish times ignore APP_TIMEZONE and use system time zone

### ISSUE THREAD

**Issue by woerndl** [statamic/cms#11803]
### Bug description

When a collection has “Publish dates” enabled, entries scheduled with a specific date + time stay in Scheduled until the corresponding UTC time passes (system time zone). Even though the “Now” button sets the correct app time zone timestamp in the UI, so entries publish late by exactly the zone offset.

<img width="772" alt="Image" src="https://github.com/user-attachments/assets/c47d2ee4-2012-4b97-8a45-18e749a7b60e" />

Screenshot taken at 10:22 in UTC/GMT +2 hours time zone

### How to reproduce

1. Set APP_TIMEZONE to any non-UTC zone in .env, clear caches.
2. In a collection, enable Publish dates (date + time).
3. Create an entry, click Now, set the time a few minutes ahead, and save.
4. Wait until the scheduled local time passes; the entry remains Scheduled until the matching UTC time, showing a delay equal to the zone offset.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: 
Laravel Version: 12.14.1
PHP Version: 8.4.6
Composer Version: 2.8.8
Environment: local
Debug Mode: ENABLED
URL: 
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.55.0 PRO

Statamic Addons
statamic/ssg: 3.1.1
studio1902/statamic-peak-browser-appearance: 3.6.1
studio1902/statamic-peak-commands: 9.0.1
studio1902/statamic-peak-seo: 8.23.0
studio1902/statamic-peak-tools: 7.2.0
```

### Installation

Starter Kit using via CLI

### Additional details

Maybe the "Now" button uses browser time, because I just tried setting the app timezone to `UTC` but that didn't apply.
