### ISSUE TITLE
Edge case when using blade view helpers within antler blade component default slot

### ISSUE THREAD

**Issue by dadaxr** [statamic/cms#11806]
### Bug description

It's more a question than an error I guess : 

within a template,  I have :

```
@php
    use function Statamic\View\Blade\{value};
    use function Statamic\View\Blade\{modify};
@endphp

<ul class="menu ">

    {{value($title)}} {{-- this works as expected --}}
    {{modify($title)->stripTags() }} {{-- this works as expected --}}

    <s:nav:burger >

        {{ value($title) }} {{-- this does not call the Statamic\View\Blade\{value} function but the value() function defined in  src/vendor/laravel/framework/src/Illuminate/Collections/helpers.php which is totally different --}}

        {{ Statamic\View\Blade\value($title) }} {{-- this works as expected but is quite  verbose ... --}}

        {{ modify($title)->stripTags() }} {{-- this does not work (throw an :  undefined function "modify"  --}}
        {{ Statamic::modify($title)->stripTags() }} {{-- this works as expected --}}

    </s:nav:burger>
    <li>
</ul>

```
Using the <s:tag> syntax is powerfull and ellegant, and using the inner default slot is more than frequent. So what would be the solution if we want to use the elleganly the value() and or the modify ( or tag ) statamic blade helper ? 

Using the `Statamic::modify` is short and ok to me, but there is not equivalent for the value() function... Maybe it would be better to add a Statamic::value static function also ? 

And of course ... I think there is room for improvement in the statamic blade doc page on that particular topic because nothing is mentioned.

### How to reproduce

just try to use the Statamic\View\Blade\value() helper function within any <s:tag> </s:tag> 

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.29
PHP Version: 8.2.7
Composer Version: 2.6.2
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.54.0 Solo

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.5.3
```

### Installation

Fresh statamic/statamic site via CLI
