### ISSUE TITLE
Navigation items without title are not editable

### ISSUE THREAD

**Issue by AtmoFX** [statamic/cms#11818]
### Bug description

Nav items can be saved with a title, a url, or both.
In the event you want a nav item with only url (which in my case is relevant: I edited the blueprint to add an icon field to it, which I show instead of the title), after 1. saving and 2. refreshing the page, there is no way to open it again.

### How to reproduce

 1. Create an element with only a URL, `Submit`.<br/>At this stage, the url will be displayed.
![Image](https://github.com/user-attachments/assets/17935559-08b3-4a06-b184-5b618cd71478)
 2. Click `Save changes`.
 3. Refresh the page.<br/>You will see the text has disappeared and with it, the only way to show the edit panel to change the nav item; about this, it does not seem to matter whether the nav item is at the 1st level in the tree or a child of another nav item.<br/>Checked the 3-dot menu, it only allows to remove the element, not to edit it.
![Image](https://github.com/user-attachments/assets/2f95e318-f543-477b-a56c-8f91c223473e)

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: GaiaMine UAT
Laravel Version: 11.45.0
PHP Version: 8.3.21
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: design.test/
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: database

Pulse
Enabled: ENABLED
Version: v1.4.1

Livewire
Livewire: v3.6.3

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.56.0 PRO

Statamic Addons
alt-design/alt-seo: 1.3.0
jacksleight/statamic-bard-mutator: 3.0.3
marcorieser/statamic-livewire: 4.4.3
statamic/eloquent-driver: 4.21.2
stillat/antlers-components: 2.6.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
