### ISSUE TITLE
Issue on Nav Edit when Editing

### ISSUE THREAD

**Issue by fajriyan** [statamic/cms#11813]
### Bug description

I always encounter problems when editing the “nav edit” section, I usually change the order, I also change the structure, usually I change the pages by creating my own section. the problem occurs when I save the sequence file and sometimes the icon that I have selected becomes messy, the order that I have previously set is broken and I have to repeat it 2-3 times before it works.

I have to do this because the request from the user side menu is like that.
<img width="1035" alt="Image" src="https://github.com/user-attachments/assets/9eabfe27-982f-4b70-a1a5-de85cf7fa693" />

I thank you very much and that's my input. 🙏

### How to reproduce

My usual steps are as follows:
1. Open the Nav edit menu
2. Edit Menu (Create New Section)
3. Remove Pages from Collection then Insert into New Section (like “CMS”)
4. Save Nav Edit

### Logs

```shell

```

### Environment

```yaml
fajriyan@fajriyann NAMC % php please support:details

Environment
Application Name: Statamic
Laravel Version: 12.12.0
PHP Version: 8.3.20
Composer Version: 2.8.8
Environment: local
Debug Mode: ENABLED
URL: 127.0.0.1:8000
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Livewire
Livewire: v3.6.3

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.54.0 Solo

Statamic Addons
marcorieser/statamic-livewire: 4.4.3
statamic/eloquent-driver: 4.21.1

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

in some statamic installations this problem does not occur and in some others this happens, I have tried updating to the latest version if the previous problem it remains problematic.
