### ISSUE TITLE
CMS Password Reset flow Broken with Eloquent driver

### ISSUE THREAD

**Issue by SuryaWebfox** [statamic/cms#11819]
### Bug description

I migrated my users in Statamic 5 to use the eloquent driver, as described in the docs.
When using the "Forgot Password" form on the CMS login form, I got an error after submitting

`Route [password.reset] not defined.`

### How to reproduce

- Use the eloquent driver for your users and follow the documentation on https://statamic.dev/tips/storing-users-in-a-database
- Go to `/cp` and click "Forgot password?"
- Fill out the form and submit

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Kwetta
Laravel Version: 12.15.0
PHP Version: 8.4.3
Composer Version: 2.8.5
Environment: staging
Debug Mode: ENABLED
URL: kwetta.gil.testsite.kiwi.nz
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: LINKED

Statamic
Addons: 2
Sites: 1
Stache Watcher: Disabled (auto)
Static Caching: Disabled
Version: 5.56.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.21.2
statamic/ssg: 3.1.1

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```

### Installation

Fresh statamic/statamic site via CLI
