### ISSUE TITLE
Collections: publish by default setting not working with revisions

### ISSUE THREAD

**Issue by JoeriE** [statamic/cms#11815]
### Bug description

I'm experiencing an issue with a collection where "Enable Revisions" is turned on. I also want to enable the "Publish by Default" option. While it appears to save correctly initially, after refreshing the page, the "Publish by Default" setting is reverted and appears disabled again.

Through testing, we found that if revisions are disabled, the "Publish by Default" setting works as expected and persists after saving and refreshing. It seems the issue is specifically tied to having revisions enabled.

### How to reproduce

1. Enable revisions on your collection
2. Enable Publish by default on your collection
3. After a save, the Publish by default is disabled

### Logs

```shell

```

### Environment

```yaml
Application Name: 
Laravel Version: 11.44.2
PHP Version: 8.2.24
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: 
Maintenance Mode: OFF
Timezone: Europe/Brussels
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Octane: frankenphp
Queue: database
Session: file

Locales
Installed: en
LaravelLang\Actions\Plugin: 1.10.1
LaravelLang\Attributes\Plugin: 2.13.4
LaravelLang\HttpStatuses\Plugin: 3.10.3
LaravelLang\Lang\Plugin: 15.19.9
LaravelLang\MoonShine\Plugin: INCORRECT
LaravelLang\StarterKits\Plugin: 1.3.6
Locales Version: 2.10.0
Protected: en
Publisher Version: 16.6.0

Statamic
Addons: 3
Sites: 2 (Nederlands, English)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.53.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.21.1
swiftmade/statamic-clear-assets: 3.1.0
thoughtco/statamic-cache-tracker: 0.9.3

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
