### ISSUE TITLE
Impossible to set custom markdown renderers

### ISSUE THREAD

**Issue by CapitaineToinon** [statamic/cms#11825]
### Bug description

Hey,

I was following [the doc](https://statamic.dev/extending/markdown#custom-parsers) on custom parsers and wanted to hook into there to also set a custom renderer for a given node. However this seems to be impossible as the parser instance seems to be created on the fly, removing anything that was done to the commonmark environment.

This is unfortunate as being able to set custom renderes would be very powerful. I believe it would be easy to add as there already is an option to add extensions. Or maybe I'm doing something wrong. I've opened a thread on the discord server and haven't got any answer so far but based on the digging I've done I believe it to be currently impossible.

### How to reproduce

Firstly, I created a custom renderer for the Link node:

```php
<?php

namespace App\CommonMark;

use League\CommonMark\Extension\CommonMark\Node\Inline\Link as InlineLink;
use League\CommonMark\Node\Node;
use League\CommonMark\Renderer\ChildNodeRendererInterface;
use League\CommonMark\Renderer\NodeRendererInterface;

class LinkRenderer implements NodeRendererInterface
{
    public function render(Node $node, ChildNodeRendererInterface $childRenderer)
    {
        if (! ($node instanceof InlineLink)) {
            throw new \InvalidArgumentException('Incompatible node type: '.get_class($node));
        }

        return view('markdown.link', [
            'url' => $node->getUrl(),
            'title' => $node->getTitle(),
            'text' => $childRenderer->renderNodes($node->children()),
        ])->render();
    }
}
```

Then I extend the default parser to use my renderer:

```php
Markdown::extend('default', function (Parser $parser) {
    $parser->environment()->addRenderer(Link::class, new LinkRenderer);
                                                                        
    return $parser;
});
```

Worth noting that at this point, it works (note the data-custom attribute):

```php
Markdown::extend('default', function (Parser $parser) {
    $parser->environment()->addRenderer(Link::class, new LinkRenderer);
                                                                            
    dd($parser->parse('[Statamic](https://statamic.com) is a great CMS!'));
                                                                            
    return $parser;
});
```

```html
<p><a href="https://statamic.com" title="" data-custom class="bg-red-500">Statamic</a>
 is a great CMS!</p>
```

Then I have a markdown field setup as so:

```yaml
          -
            handle: content
            field:
              type: markdown
              display: Content
              localizable: true
              automatic_links: true
              heading_anchors: true
              table_of_contents: true
              buttons:
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - quote
                - link
                - image
                - table
                - strikethrough
                - asset
                - code
                - codeblock
```

And simply rendered using antlers:

```antlers
{{ content }}
```

But the outputed html has nothing.

```html
<a href="//darksouls.wikidot.com/fall-control">Fall Control</a>
```

I tried to find where the parser was used and I concluded it was in `Statamic\Fieldtypes\Markdown`:

https://github.com/statamic/cms/blob/5.x/src/Fieldtypes/Markdown.php#L130-L169

And if I dd the parser there, I can see the converter is null, and therefore will have to be instantiated again, creating a new environment without my custom renderer.

```
Statamic\Markdown\Parser {#3264 ▼ // vendor/statamic/cms/src/Fieldtypes/Markdown.php:167
  #converter: null
  #extensions: array:3 [▶]
  #config: array:4 [▶]
}
```

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 12.15.0
PHP Version: 8.4.7
Composer Version: 2.8.8
Environment: local
Debug Mode: ENABLED
URL: localhost:8000
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Livewire
Livewire: v3.6.3

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.56.0 PRO

Statamic Addons
statamic/ssg: 3.1.1
```

### Installation

Fresh statamic/statamic site via CLI
