### ISSUE TITLE
Live Preview visible for collections when no route is defined

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1183]
The Live Preview is visible and can be used for collections, even when no route has been defined. Opening the live preview does show an 500 error and cant find the view.

My collection does look like this.

```
title: Events
blueprints:
  - events
revisions: false
date: true
sort_dir: desc
date_behavior:
  past: private
  future: public
``` 

The expected behavior would be to hide the live preview button, in case a route is not defined.
