### ISSUE TITLE
The shallowAugmentedArrayKeys method does not work

### ISSUE THREAD

**Issue by itsserbin** [statamic/cms#11831]
### Bug description

I'm trying to extend the API response to get the required fields instead of additional sampling on the frontend.
I have 2 versions of Statamic:

1. Version 4 on the file system
2. Version 5 with posgtres

The problem occurs on the 5th version which is connected to postgres. Just after adding a CustomEntry and registering it with the AppServiceProvider, nothing happens, no changes, absolutely nothing. Although at the same time, version 4 with file system handles this extension

### How to reproduce

app/Http/CustomEntry.php
```
<?php

namespace App\Http;

use Statamic\Entries\Entry;

class CustomEntry extends Entry
{
    public function shallowAugmentedArrayKeys()
    {
        dd('asdasd');
        $shallowAugmentedArrayKeys = ['id', 'title', 'url', 'permalink', 'api_url'];

        if ($this->collection()->handle() == 'reviews') {
            return array_merge($shallowAugmentedArrayKeys, ['company', 'company_logo', 'client_page_logo', 'photo', 'position', 'text', 'video_link']);
        }
        return $shallowAugmentedArrayKeys;
    }
}
```

app/Providers/AppServiceProvider.php
```
 public function boot(): void
    {
        if ($this->app->environment('HTTPS')) {
            URL::forceScheme('https');
        }

        // 1
        $this->app->bind(\Statamic\Entries\Entry::class, function () {
            return new \App\Http\CustomEntry;
        });

        // 2
        $this->app->bind(
            \Statamic\Contracts\Entries\Entry::class,
            \App\Http\CustomEntry::class
        );

        // 3
        $this->app->bind(
            \Statamic\Entries\Entry::class,
            \App\Http\CustomEntry::class
        );
    }
```

### Logs

```shell
Nothing
```

### Environment

```yaml
php please support:details

Environment
Application Name: Laravel
Laravel Version: 12.15.0
PHP Version: 8.3.21
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: database
Database: pgsql
Logs: google
Mail: smtp
Queue: database
Session: database

Storage
public/storage: NOT LINKED

Statamic
Addons: 3
Sites: 5 (English, Spanish, Ukrainian, Portuguese, kz)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.56.0 PRO

Statamic Addons
appswithlove/statamic-one-click-content-translation: 5.2.3
mitydigital/statamic-two-factor: 2.5.0
statamic/eloquent-driver: 4.21.2

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```

### Installation

Existing Laravel app
