### ISSUE TITLE
Non-existent Socialite driver causes 500

### ISSUE THREAD

**Issue by martinoak** [statamic/cms#11842]
### Bug description

When using OAuth login, but providing a non-existent Socialite provider in the URl, the web throws a 500 error with InvalidArgumentException

`Driver [foo] not supported.`

### How to reproduce

1. Set up OAuth login method.
2. when signing via oauth, take the URL and replace the driver handle for any other that does not exist (/oauth/my-provider/... for /oauth/foobar/...)
3. Voila

### Logs

```shell

```

### Environment

```yaml
Environment
Laravel Version: 11.44.2
PHP Version: 8.3.20
Composer Version: 2.7.9
Environment: devel
Debug Mode: ENABLED
Maintenance Mode: OFF
Timezone: Europe/Prague
Locale: cz

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: mariadb
Logs: stack / single
Mail: smtp
Queue: sync
Session: redis

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.52.0 PRO

Statamic Addons
dek-statamic/dev-tools: 1.5.2
pecotamic/sitemap: 1.4.8
statamic/eloquent-driver: 4.20.2

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
