### ISSUE TITLE
Cannot create new globals collection even with permission set

### ISSUE THREAD

**Issue by miicah** [statamic/cms#11849]
### Bug description

Setting the `Configure globals` setting in Permissions does not actually grant that permission.

### How to reproduce

1. Start a fresh Statamic site
2. Create a super user and log in
3. Create a role and assign it `Configure globals`
4. Create a new user and assign it that role
5. Log in as new user and try to create a new global set
6. Get permission denied (403)

### Logs

```shell
Nothing in logs (at least at default reporting level?). I did try and use Telescope, but couldn't understand the stack trace.
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 12.17.0
PHP Version: 8.4.7
Composer Version: 2.8.9
Environment: local
Debug Mode: ENABLED
URL: globals2.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.57.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

All the other general permissions work (collections, assets, navs, taxonomies).
