### ISSUE TITLE
Can't reference augmented fields in a computed value

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#11853]
### Bug description

If you create a computed field but reference an augmented value, you get recursion/timeouts when you try to retrieve the entry in tinker (and elsewhere you get nginx 503, seg faults)

### How to reproduce

On a brand new site, put the following in the `AppServiceProvider`:

```php
        Collection::computed(
            'pages',
            'custom',
            fn (Entry $entry) => $entry->permalink
        );
```

Then open tinker and try `\Statamic\Facades\Entry::find("home")`. You'll see tinker immediately quit. If you remove the call to ->permalink and return a string instead, everything is fine

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 12.17.0
PHP Version: 8.3.22
Composer Version: 2.8.9
Environment: local
Debug Mode: ENABLED
URL: computed.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.57.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
