### ISSUE TITLE
Uploading a file with a single quote causes errors.

### ISSUE THREAD

**Issue by adampatterson** [statamic/cms#11857]
### Bug description

A client uploaded an image `arts-culture_public-art_internal_mural-'sohkatisiwin'-downtown.jpg` that contained single quotes.  

The file worked fine in the admin, but when it came to rendering in the template errored. 

> lluminate\View\ViewException
Statamic\Assets\AssetRepository::find():
Argument #1 ($asset) must be of type string, null given, called in...

Odly, it works fine on my mac, but was upset on Ubuntu.

### How to reproduce

Upload an asset with single quotes in the file name. Attach it to an image field, Render the image field in blade,

```blade
<statamic:glide src="{{ $image }}" :preset="$preset">
    <img src="{{ $url }}" width="{{ $width }}" height="{{ $height }}" alt="{{ $column->image->alt }}"@if ($column->force_full_width_image) class="w-full"@endif/>
</statamic:glide>
```

I am using Object storage with Glide, so the image isn't local, but I don't think that's a factor.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Tourism Calgary
Laravel Version: 11.44.7
PHP Version: 8.4.7
Composer Version: 2.8.9
Environment: production
Debug Mode: OFF
URL: tourism-calgary.paperleaf.dev
Maintenance Mode: OFF
Timezone: America/Edmonton
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: log
Queue: database
Scout: algolia
Session: redis

Sentry
Enabled: YES
Environment: production
Laravel SDK Version: 4.13.0
PHP SDK Version: 4.11.1
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 6
Sites: 1
Stache Watcher: Disabled (auto)
Static Caching: Disabled
Version: 5.57.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.14.0
eminos/statamic-tabs: 1.2.0
jacksleight/statamic-bard-texstyle: 3.5.5
statamic/eloquent-driver: 4.23.1
statamic/seo-pro: 6.7.0
thoughtco/statamic-restrict-fields: 1.1.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```

### Installation

Fresh statamic/statamic site via CLI
