### ISSUE TITLE
Reordering Collections in Control panel is not working

### ISSUE THREAD

**Issue by leon-fablr** [statamic/cms#11859]
### Bug description

When changing the order in the control panel on a collection that has been set to be orderable, the order in the database field seems to be getting set wrong despite the success response. My setup has entities and collections stored in mysql via eloquent and my blueprints stored in yaml files in git.

Collections that have been changed to be orderable have sql NULL on their existing entities and these will continue to have nulls after reordering. Entities created after setting the collection as orderable always have '1' as their sort order.

I've run `artisan optimize:clear` at various points throughout this in case there's something stored in cache. 

If the order field on the entries table is manually updated, the ordering works correctly.

### How to reproduce

1. Create a collection.
2. In its options, toggle the Orderable field on
3. Set the Max depth field to 1
4. Create 3-4 entries
5. Click the Reorder button
6. Re-order entries
7. Click the save button

Check the order column in database via:
```
SELECT id, JSON_EXTRACT(data, '$.title') AS title, `order` FROM entries where collection = 'my_test_collection';
```

### Logs

```shell
SQL result from: 

SELECT id, JSON_EXTRACT(data, '$.title') AS title, `order` FROM entries where collection = 'my_test_collection';

+--------------------------------------+---------+-------+
| id                                   | title   | order |
+--------------------------------------+---------+-------+
| 3a258d06-9773-42c0-bf89-e677d411692f | "Test1" |     1 |
| 85271a8e-2538-4b09-8aab-03c5761d67b6 | "Test3" |     1 |
| f408bebf-53ee-4ac6-8a24-37053fe09ec9 | "Test2" |     1 |
+--------------------------------------+---------+-------+
```

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 11.45.1
PHP Version: 8.3.13
Composer Version: 2.8.2
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: database
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: database

Simple Commerce
Currencies: GBP
Gateways: Stripe
Repository: Customer: DuncanMcClean\SimpleCommerce\Customers\UserCustomerRepository
Repository: Order: App\Repository\EloquentOrderRepository
Repository: Product: DuncanMcClean\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Standard shipping
Tax Engine: DuncanMcClean\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 6
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.57.0 PRO

Statamic Addons
alt-design/alt-google-2fa: dev-fablr
duncanmcclean/simple-commerce: 7.8.5
rias/statamic-redirect: 3.10.9
statamic-rad-pack/runway: 8.5.0
statamic/eloquent-driver: 4.23.0
statamic/seo-pro: 6.7.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: file
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```

### Installation

Fresh statamic/statamic site via CLI
