### ISSUE TITLE
Custom Set Icons not working

### ISSUE THREAD

**Issue by andjsch** [statamic/cms#11864]
### Bug description

In my local environment, the icons are showing. On the staging and production server, I do not get them, it falls back to the default icon.

I am using ``schantldev/statamic-phosphoricons``.

This is the ``svg-icon``-component in my local environment:

![Image](https://github.com/user-attachments/assets/ca26645c-ed0e-4dba-a119-9d5eeb9a2b2a)

This in my prod env:

![Image](https://github.com/user-attachments/assets/7b9ddf51-efca-48ec-a932-8a4739531787)

Besides the directory of course being different, I don't see any difference. I also tried to retrieve the icons via ``Icon::getCustomSvgIcons()`` which works fine. Getting a fine JSON response. I also see that output within the HTML when I expect the source before the JS loads. What could I be overseeing?

<img width="1398" alt="Image" src="https://github.com/user-attachments/assets/f318a59f-bd60-4b42-803b-b33a50565c9d" />

### How to reproduce

Really not sure in this case.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: "Statamic"
Laravel Version: 12.18.0
PHP Version: 8.4.7
Composer Version: 2.8.8
Environment: local
Debug Mode: ENABLED
URL: reiserei.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.57.0 PRO

Statamic Addons
schantldev/statamic-phosphoricons: 1.0.1
studio1902/statamic-peak-browser-appearance: 3.6.1
studio1902/statamic-peak-seo: 8.23.0
studio1902/statamic-peak-tools: 7.3.1
```

### Installation

Starter Kit using via CLI
