### ISSUE TITLE
Added key in case of import field

### ISSUE THREAD

**Issue by kevinmeijer97** [statamic/cms#11878]
### Bug description

I've run into a problem when using the `statamic/importer` addon.

When importing data into a collection that includes fieldsets imported onto the blueprint, the process goes through the `getTabFields()` method in `src/Fields/Blueprint.php`. This can result in the following array:
![Image](https://github.com/user-attachments/assets/bfa98b89-fed5-49b3-8510-12b21afbcc16)

As you can see, the last item in the array is a fieldset being imported into the blueprint. However, since an imported fieldset doesn't have a `handle`, this results in an empty key, which can cause errors when using the import addon.

A possible solution would be to adjust the `keyBy` method to also check for `$field['import']` as a fallback when the handle is missing.

### How to reproduce

- Install the `statamic/importer` addon.
- Create a collection with a blueprint, also create a new fieldset with a text field and import the fieldset onto the blueprint.
- Try and import some data onto this collection

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Trucks Statamic
Laravel Version: 11.45.0
PHP Version: 8.3.16
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: trucks-statamic.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 8
Sites: 12 (Trucks Nederland, Trucks België | Nederlands, Trucks International | English, and 9 more)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.56.0 PRO

Statamic Addons
appswithlove/statamic-one-click-content-translation: 5.2.3
just-better/translations-overview: dev-feature/deepl-translate-addon
just-better/url-reference-updater: dev-feature/deepl-translate-addon
justbetter/statamic-content-translation: dev-feature/deepl-translate-addon
justbetter/statamic-structured-data: 1.2.2
markkravchuk/statamic-activity-book: 1.0.1
statamic/eloquent-driver: 4.22.0
statamic/importer: 1.8.1

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: file
Revisions: eloquent
Sites: file
Taxonomies: file
Terms: eloquent
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
