### ISSUE TITLE
Can't create new taxonomy term in non-active site via stack selector

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#11884]
### Bug description

If you have a multi-site (A & B) and you're in site B (in the CP), and an entry has a stack selector terms field, you can't pick site A to create the new term in.

Confusing I know, sorry, hopefully the video is clear

https://github.com/user-attachments/assets/53faf3e2-068e-4748-8340-0c2d0a723de1

### How to reproduce

1. create site
2. make multisite
3. make taxonomy, `Categories` that's in both site
4. change the pages blueprint and set the categories field to Stack Selector
5. Set the site to the second site
6. open home page in the cp
7. click create on the categories field
8. click the first site

See error 

![Image](https://github.com/user-attachments/assets/94403151-f139-4986-aa84-0b59e370f09d)

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 12.19.3
PHP Version: 8.3.22
Composer Version: 2.8.9
Environment: local
Debug Mode: ENABLED
URL: terms.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 0
Sites: 2 (Statamic, Second)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.57.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
