### ISSUE TITLE
resolvingValues returned as member variable from __sleep() but does not exist

### ISSUE THREAD

**Issue by vitalijalbu** [statamic/cms#11887]
### Bug description

`serialize(): resolvingValues returned as member variable from __sleep() but does not exist`

I'm gettin this error when revisions is enabled and publish dates too.

https://github.com/user-attachments/assets/bbf1afa4-47a9-4c8a-9cea-c4b10931b79f

### How to reproduce

- activate revisions
- activate publush date on articles collection

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: TDPost
Laravel Version: 12.19.3
PHP Version: 8.4.8
Composer Version: 2.8.9
Environment: development
Debug Mode: ENABLED
URL: tp-news-api.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled
Static Caching: full
Version: 5.58.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.25.2

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: file
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```

### Installation

Fresh statamic/statamic site via CLI
