### ISSUE TITLE
`image` validation on `files` fieldtype failing

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/cms#11893]
### Bug description

Adding validation of `- image` to a form field of `type: files` always returns and error of _"The Assets Field field must be an image."_

An `asset` fieldtype with this validation works fine.

### How to reproduce

Make a form with the following fields:
```
-
  handle: assets_field
  field:
    max_files: 1
    container: assets
    folder: /
    type: assets
    display: 'Assets Field'
    validate:
      - image
-
  handle: files_field
  field:
    max_files: 1
    type: files
    display: 'Files Field'
    validate:
      - image
```
Add images to both fields and submit.

### Environment

```yaml
Environment
Application Name: Testweb
Laravel Version: 12.15.0
PHP Version: 8.3.22
Composer Version: 2.8.9
Environment: local
Debug Mode: ENABLED
URL: testweb.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.56.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI
