### ISSUE TITLE
Recursion error

### ISSUE THREAD

**Issue by saltenasbenas** [statamic/cms#11892]
### Bug description

Hello, after latest update, when i clean cache i get: Recursion detected while augmenting [Statamic\Entries\Entry] with ID [45694750-f312-495e-97d9-1502458566cd]. This ID is copy of original collection post

I have multisite, with propagate, before update it worked fine. I do not use any special fields. I propagate fields and do not edit them in other languages. Shouldn't it work fine even if i do not edit them in other languages? Because it seems, what this causes error

### How to reproduce

Set up a multisite Statamic project  with at least two locales.

Create a collection with propagation enabled for all sites.

Create an entry in the primary site

Let the entry auto-propagate to the other site

Do not modify the propagated entry manually in the secondary locale.

Clear the cache using admin panel

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 12.19.3
PHP Version: 8.2.0
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: test.local/
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Locales
Installed: en, et, lt, lv
LaravelLang\Actions\Plugin: 1.10.1
LaravelLang\Attributes\Plugin: 2.13.4
LaravelLang\HttpStatuses\Plugin: 3.10.3
LaravelLang\Lang\Plugin: 15.22.0
LaravelLang\MoonShine\Plugin: INCORRECT
LaravelLang\StarterKits\Plugin: 1.3.9
Locales Version: 2.10.0
Protected: en
Publisher Version: 16.6.0

Statamic
Addons: 6
Sites: 4 (Lithuanian, Latvian, Estonian, English)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.58.0 PRO

Statamic Addons
alt-design/alt-redirect: 1.6.3
lucapon/statamic-content-backup: 3.0.3
pixelastronauts/statamic-autocomplete-address-field: 1.0.0
ryanmitchell/statamic-translation-manager: 2.2.0
statamic/seo-pro: 6.7.0
thoughtco/statamic-cache-tracker: 0.9.3
```

### Installation

Fresh statamic/statamic site via CLI
