### ISSUE TITLE
Collection search is case sensitive for special characters

### ISSUE THREAD

**Issue by SG-fabian** [statamic/cms#11902]
### Bug description

Hello!

We have encountered a  strange but with the backend search for collections. If the different cases for "Umlaut" characters are handled differently (for example "ä" and "Ä"). I guess this also includes other "non-standard" characters.

### How to reproduce

Set the title of a entry for example to "Mieträder". The following search terms can find the entry: "Mieträder", "mieträder", "mietRäder", "räder". But you can't find the entry with this: "mietrÄder".

Another example: "ÖPNV". You can find it with: "ÖPNV", "PNV", "Öpnv" but not with "öpnv".

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.45.1
PHP Version: 8.2.28
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: sdd-marburg-cms.test/
Maintenance Mode: OFF
Timezone: Europe/Berlin
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.58.0 PRO

Statamic Addons
itiden/statamic-backup: 1.0.2
```

### Installation

Fresh statamic/statamic site via CLI
