### ISSUE TITLE
Issues when passing in grid field type data into PublishForm

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1206]
Hey,

I’ve been building an add-on recently that uses the publish form component. I’m loading in a blueprint to that component which has a Grid field type in it, for variants (in my use case).

Creating variants work fine, I get the data back to my controller and they are stored in my database. However, I get issues when I try to load variants back into my edit form.

This is how I’m loading the product variables and the variant stuff for my controller:

```php
	$product = Product::where('uid', $product)->first();
  $variants = Variant::where('product_id', $product->id)->get();
        
	$values = array_merge($product->toArray(), [
            'variants' => $variants->map(function (Variant $variant, $key) {
                return [
                    '_id' => 'row-'.$key,
                    'description' => $variant->description,
                    'max_quantity' => $variant->max_quantity,
                    'name' => $variant->name,
                    'price' => $variant->price,
                    'sku' => $variant->sku,
                    'stock_number' => $variant->stock_number,
                    'unlimited_stock' => $variant->unlimited_stock,
                    'variant_attributes' => collect($variant->variant_attributes)->map(function ($attribute, $key) {
                        return [
                            '_id' => 'row-'.$key,
                            'key' => $attribute['key'],
                            'value' => $attribute['value'],
                        ];
                    })->toArray(),
                ];
            })->toArray()
        ]);
```

I’ve found that I need to load exactly the stuff that’s in my blueprint and I need to generate some `_id` field for the index.

So now that I’ve got that working, there’s still one weird thing. The grid field type will only display the amount of variants that are in the `min_rows` column in the blueprint.

For example, if I have 6 variants, and my `min_rows` for the grid in my blueprint is `1`, only 1 of the variants will be displayed. However, the other variants are still being passed into the component as props (I can tell using Vue dev tools)

**Comment by jasonvarga** [comment]
Please include the grid field from your blueprint too.

**Comment by damcclean** [comment]
Oops, sorry forgot to include that 🤦‍♂ 

```yaml
      -
        handle: variants
        field:
          fields:
            -
              handle: name
              field:
                character_limit: 0
                type: text
                localizable: false
                width: 50
                display: Name
            -
              handle: price
              field:
                type: money
                localizable: false
                width: 25
                display: Price
            -
              handle: sku
              field:
                generate: true
                type: slug
                localizable: false
                width: 25
                display: SKU
            -
              handle: max_quantity
              field:
                type: integer
                instructions: 'How many of these can a customer buy at once?'
                localizable: false
                width: 33
                display: 'Max Quantity'
            -
              handle: stock_number
              field:
                type: integer
                localizable: false
                width: 33
                display: 'Stock Number'
                unless:
                  unlimited_stock: 'equals true'
                instructions: 'After every purchase, this number will be deducted from.'
            -
              handle: unlimited_stock
              field:
                type: toggle
                localizable: false
                width: 33
                display: 'Unlimited stock?'
            -
              handle: description
              field:
                type: textarea
                localizable: false
                display: Description
            -
              handle: variant_attributes
              field:
                fields:
                  -
                    handle: key
                    field:
                      character_limit: 0
                      type: text
                      localizable: false
                      display: Key
                  -
                    handle: value
                    field:
                      character_limit: 0
                      type: text
                      localizable: false
                      display: Value
                mode: table
                max_rows: 0
                min_rows: 4
                reorderable: true
                type: grid
                localizable: false
                display: Attributes
          mode: stacked
          max_rows: 0
          min_rows: 2
          add_row: 'New Variant'
          reorderable: true
          type: grid
          localizable: false
          display: Variants
```

**Comment by damcclean** [comment]
Just to give a quick update.

I've changed around some of the Blueprint

```
title: 'Simple Commerce: Product'
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Title
      -
        handle: description
        field:
          type: textarea
          localizable: false
          display: Description
      -
        handle: variants
        field:
          fields:
            -
              handle: name
              field:
                character_limit: 0
                type: text
                localizable: false
                width: 50
                display: Name
            -
              handle: price
              field:
                type: money
                localizable: false
                width: 25
                display: Price
            -
              handle: sku
              field:
                generate: false
                type: slug
                localizable: false
                width: 25
                display: SKU
            -
              handle: max_quantity
              field:
                type: integer
                instructions: 'How many of these can a customer buy at once?'
                localizable: false
                width: 33
                display: 'Max Quantity'
            -
              handle: stock_number
              field:
                type: integer
                localizable: false
                width: 33
                display: 'Stock Number'
                unless:
                  unlimited_stock: 'equals true'
                instructions: 'After every purchase, this number will be deducted from.'
            -
              handle: unlimited_stock
              field:
                type: toggle
                localizable: false
                width: 33
                display: 'Unlimited stock?'
            -
              handle: description
              field:
                type: textarea
                localizable: false
                display: Description
            -
              handle: variant_attributes
              field:
                fields:
                  -
                    handle: uuid
                    field:
                      character_limit: 0
                      type: hidden
                      localization: false
                      display: UUID
                  -
                    handle: key
                    field:
                      character_limit: 0
                      type: text
                      localizable: false
                      display: Key
                  -
                    handle: value
                    field:
                      character_limit: 0
                      type: text
                      localizable: false
                      display: Value
                mode: table
                reorderable: false
                type: grid
                localizable: false
                display: Attributes
                listable: true
                add_row: 'Add Attribute'
          mode: stacked
          max_rows: 0
          min_rows: 2
          add_row: 'New Variant'
          reorderable: false
          type: grid
          localizable: false
          display: Variants
          listable: hidden
  attributes:
    display: Attributes
    fields:
      -
        handle: product_attributes
        field:
          fields:
            -
              handle: uuid
              field:
                type: hidden
                localizable: false
                listable: hidden
                display: UUID
            -
              handle: key
              field:
                html_type: text
                type: text
                localizable: false
                listable: hidden
                display: Key
            -
              handle: value
              field:
                html_type: text
                type: text
                localizable: false
                listable: hidden
                display: Value
          mode: table
          add_row: 'Add Attribute'
          reorderable: false
          type: grid
          localizable: false
          listable: true
          display: Attributes
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          generate: true
          type: slug
          localizable: false
          display: Slug
      -
        handle: category
        field:
          max_items: 1
          mode: default
          type: product_category
          localizable: false
          display: 'Product Category'
      -
        handle: is_enabled
        field:
          type: toggle
          localizable: false
          display: 'Is Enabled?'
```

And I've changed the controller that pushed the data to the publish form view.

```php
$product = Product::with('variants', 'attributes')
            ->where('uuid', $product)
            ->first();

        $values = array_merge($product->toArray(), [
            'category' => $product->product_category_id,
            'variants' => $product->variants->map(function (Variant $variant, $key) {
                return array_merge($variant->toArray(), [
                    '_id' => 'row-'.$key,
                    'stock_number' => $variant->stock,
                    'variant_attributes' => collect($variant->attributes)
                        ->map(function (Attribute $attribute, $key) {
                            return [
                                '_id' => 'row-'.$key,
                                'uuid' => $attribute->uuid,
                                'key' => $attribute->key,
                                'value' => $attribute->value,
                            ];
                        })
                        ->toArray(),
                ]);
            }),
            'product_attributes' => collect($product->attributes)
                ->map(function (Attribute $attribute, $key) {
                    return [
                        '_id' => 'row-'.$key,
                        'uuid' => $attribute->uuid,
                        'key' => $attribute->key,
                        'value' => $attribute->value,
                    ];
                })
                ->toArray(),
        ]);

        $blueprint = (new Product())->blueprint();
        $fields = $blueprint->fields();
        $fields = $fields->preProcess();

        return view('simple-commerce::cp.products.edit', [
            'crumbs'    => $crumbs,
            'blueprint' => $blueprint->toPublishArray(),
            'values'    => $values,
            'meta'      => $fields->meta(),
            'action'    => $product->updateUrl(),
        ]);
```

It's a pretty big bug in my addon so hopefully it's an easy fix 😄 . Let me know if you need any other information.
