### ISSUE TITLE
Required validations do not work in Bard

### ISSUE THREAD

**Issue by lightbringer93** [statamic/cms#1225]
I created a fieldset Button which I implemented in the Bard text block. When I set certain fields as required, than I can not save anymore, because the fields still seem to be empty, even though I have set some value. 
![Screenshot](https://user-images.githubusercontent.com/27002677/72665327-9065e380-3a07-11ea-86fa-edef158329e1.png)
I also tried it with required_if and required_without and experience the same problem with those validations.

**Comment by goellner** [comment]
Experienced the same thing today. I had an asset field with "validation: required" and got the same error as in your screenshot

**Comment by studio1902** [comment]
Same here. And in replicator sets required validations don't do anything. They pass even if fields are empty.

**Comment by benfurfie** [comment]
Likely related to #1702

**Comment by studio1902** [comment]
Yeah, maybe. I've encountered a few different issues regarding validation and conditional logic in replicator and bard or in a combination. The end results differ in each case. Not sure if this is all related or not. I'd be happy to test/provide info about this. Don't want to add duplicate issues.

**Comment by benfurfie** [comment]
Yeah. I think it's because Jason and co are struggling to target nested arrays with Vue. It seems like almost rule issue is down to this pain point. He'll be able to confirm more than I will.

**Comment by studio1902** [comment]
Yeah, also DM'ed Jason in case he needs more info. Ha, this was the #1 thing I was missing in v2, let's hope they'll figure it out :-).

**Comment by jonassiewertsen** [comment]
We just ran into this issue today as well. I can confirm that it's still present.

**Comment by arthurperton** [comment]
Hi guys, I am currently on v3.1.9 and it al works like a charm when I use the fields below. Should anything else be added to reproduce, or is this issue solved maybe?

Cheers

```
      -
        handle: bard
        field:
          always_show_set_button: false
          sets:
            must_haves:
              display: 'Must haves'
              fields:
                -
                  handle: obligatory
                  field:
                    input_type: text
                    antlers: false
                    display: Obligatory
                    type: text
                    icon: text
                    listable: hidden
                    validate:
                      - required
                -
                  handle: important_asset
                  field:
                    mode: grid
                    container: assets
                    restrict: false
                    allow_uploads: true
                    max_files: 1
                    display: 'Important asset'
                    type: assets
                    icon: assets
                    listable: hidden
                    validate:
                      - required
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
          container: assets
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          display: Bard
          type: bard
          icon: bard
          listable: hidden
      -
        handle: see_the_asterix
        field:
          input_type: text
          antlers: false
          display: 'See the asterix?'
          type: text
          icon: text
          listable: hidden
          validate:
            - required
      -
        handle: replicator
        field:
          collapse: false
          sets:
            new_set:
              display: 'New Set'
              fields:
                -
                  handle: must_be_filled
                  field:
                    input_type: text
                    antlers: false
                    display: 'Must be filled'
                    type: text
                    icon: text
                    listable: hidden
                    validate:
                      - required
          display: Replicator
          type: replicator
          icon: replicator
          listable: hidden
```
