### ISSUE TITLE
Get first text set from Bard field

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1243]
I'm migrating one of my personal sites from v2 to v3. However I've noticed that one bit of code that I use to get the first bit of the first text block in a Bard field for an article excerpt no longer works. `builder` is the name of the Bard field in my sample below.

```
{{ builder where="type:text" limit="1" }}{{ text | safe_truncate:240 | striptags }}{{ /builder }}
```

You might also want to try it with my Blueprint to check its not me being stupid.

```yaml
title: Article
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          display: Title
          localizable: true
          width: 50
      -
        handle: seo_description
        field:
          type: text
          display: 'SEO Description'
          width: 50
      -
        handle: seo_image
        field:
          type: assets
          container: main
          folder: /
          restrict: false
          max_files: 1
          display: 'SEO Image'
      -
        handle: builder
        field:
          type: bard
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - anchor
            - assets
          style: sans
          spellcheck: true
          allow_source: true
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          semantic_elements: true
          restrict_assets: true
          sets:
            image:
              display: Image
              fields:
                -
                  handle: image
                  field:
                    mode: grid
                    restrict: false
                    allow_uploads: true
                    max_files: 1
                    type: assets
                    localizable: false
                    listable: hidden
                    display: Image
                    container: main
                -
                  handle: caption
                  field:
                    type: text
                    localizable: false
                    listable: hidden
                    display: Caption
          display: 'Page Builder'
          allow_internal_links: true
          folder: /
          container: main
          listable: false
          save_html: false
          toolbar_mode: fixed
          reading_time: true
          fullscreen: true
  sidebar:
    display: Sidebar
    fields:
      -
        handle: date
        field:
          type: date
          display: 'Publish Date'
          allow_blank: false
          allow_time: true
          require_time: false
          earliest_date: 'January 1, 1900'
      -
        handle: slug
        field:
          type: text
          display: Slug
```
