### ISSUE TITLE
Site variables as an array

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1257]
We have a handful of global/system variables that get injected into templates.

Things like `environment`, `xml_header`, `csrf_token`, `logged_in`, `now`, etc.

We have a bunch of site/locale related ones too:

- `site` that outputs the current site's handle
- `site_name` for the defined `name`
- `site_url` for the defined `url`

How about instead of `site_x` we just have a `site` array with those things?

```
site:
  name: Default
  locale: en_US
  short_locale: en
  url: /
  permalink: http://site.com/
```

Then you can reference `site:locale`, `site:url`, etc.
