### ISSUE TITLE
Revealer inside a grid inside a Bard doesn't hide fields

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#1260]
I have an "Add overlay" revealer, with 2 text fields that I want to show when "add_overlay" is true:

![image](https://user-images.githubusercontent.com/3626559/73059768-b4597700-3e96-11ea-9faa-ea19ce1d8b32.png)

This is the Yaml:

```yaml
                -
                  handle: add_overlay
                  field:
                    type: revealer
                    localizable: false
                    listable: false
                    display: 'Add overlay'
                -
                  handle: overlay_image
                  field:
                    container: assets
                    mode: list
                    restrict: false
                    allow_uploads: true
                    max_files: 1
                    type: assets
                    localizable: false
                    width: 50
                    listable: hidden
                    display: 'Overlay image'
                    show_when:
                      add_overlay: true
                -
                  handle: overlayText
                  field:
                    type: textarea
                    localizable: false
                    listable: false
                    display: 'Overlay Text'
                    show_when:
                      add_overlay: true
```

All this is inside a Grid, inside a Set of a Bard field
