### ISSUE TITLE
Fields not augmented when in a replicator

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1306]
I have a markdown field and an asset field inside a replicator and neither are being augmented. I had to use the `markdown` modifier and the `asset` tag to make things work.

On beta 14.

**Comment by edalzell** [comment]
Blueprint:
```yaml
title: Content
sections:
  main:
    display: Main
    fields:
      - handle: title
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Title
          width: 25
      - handle: slug
        field:
          generate: true
          type: slug
          localizable: false
          display: Slug
          width: 25
      - handle: tags
        field:
          max_items: 0
          mode: typeahead
          type: taxonomy
          localizable: false
          width: 25
          display: Tags
      - handle: link
        field:
          character_limit: 0
          type: text
          localizable: false
          width: 25
          display: Link
          validate: url
      - handle: content_block
        field:
          sets:
            text:
              display: Text
              fields:
                - handle: text
                  field:
                    restrict: false
                    automatic_line_breaks: true
                    automatic_links: false
                    escape_markup: false
                    smartypants: false
                    type: markdown
                    localizable: false
                    listable: hidden
                    display: Text
            image:
              display: Image
              fields:
                - handle: image
                  field:
                    container: assets
                    mode: grid
                    restrict: false
                    allow_uploads: true
                    type: assets
                    localizable: false
                    listable: hidden
                    display: Image
                    max_files: 1
          type: replicator
          localizable: false
          listable: hidden
          display: Content
```
