### ISSUE TITLE
Slug field twice

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#1308]
Create a collection sorted by date => Add a section as sidebar and create a slug field and a date-field with the name "date" => The slug field is shown twice. 
![image](https://user-images.githubusercontent.com/3351449/73875460-a112b800-4855-11ea-9767-6ebcb2ba1ba4.png)

**Comment by jackmcdade** [comment]
There's _already_ a slug field automatically. All you need to do is remove your duplicate slug field. 👍

**Comment by Pfeifakopf** [comment]
I've added the slug field to order the position of it.  This works on all templates. The slug is just shown once on my favorite position. 
That's the sidebar fieldset, including the slug to order it:
```
title: Sidebar
fields:
  menuetitle:
    type: text
    instructions: 'Optional, anstatt Titel'
    localizable: false
    display: Menütitel
  slug:
    generate: true
    type: slug
    localizable: false
    display: Slug
  nav__hidden:
    type: toggle
    instructions: 'In Navigation nicht anzeigen'
    localizable: false
    display: Verbergen
```

Now I have two templates, with the sidebar sections:
Template 1:
```
  sidebar:
    display: Sidebar
    fields:
      -
        handle: date
        field:
          mode: single
          time_enabled: true
          time_required: false
          earliest_date: '2020-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          type: date
          localizable: false
          listable: hidden
          display: Datum
      -
        import: sidebar
```
Template 2:
```
  sidebar:
    display: Sidebar
    fields:
      -
        handle: date
        field:
          time_enabled: true
          time_required: false
          earliest_date: '2020-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          mode: single
          type: date
          localizable: false
          listable: hidden
          display: Beginn
      -
        handle: end
        field:
          time_enabled: true
          time_required: false
          earliest_date: '2020-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          mode: single
          type: date
          localizable: false
          listable: true
          display: Ende
      -
        import: sidebar
        prefix: Seitenleiste

```
The first template shows the slug once, the second template twice.
![image](https://user-images.githubusercontent.com/3351449/74835808-6c573400-531e-11ea-9640-625f85e79fce.png)
![image](https://user-images.githubusercontent.com/3351449/74835844-7f6a0400-531e-11ea-86dd-4fd9d01d5622.png)
