### ISSUE TITLE
Type is not beeing recongnized

### ISSUE THREAD

**Issue by lightbringer93** [statamic/cms#1320]
Since the last upgrade all my type conditions are not being recongnized anymore. For example in my bard text block. But when I dump the type, I am getting all the types. 
```
{{ text_block }}
    {{ if type == 'text' }}
        {{ text }}
    {{ elseif type == 'button' }}
        {{ if !border_left }}
            {{ partial:partials/button }}
        {{ /if }}
    {{ elseif type == 'icons' }}
        {{ if !border_left }}
            <div class="flex flex-wrap ">
                {{ icons }}
                    {{ partial:partials/icon }}
                {{ /icons }}
            </div>
        {{ /if }}
    {{ elseif type == 'image' }}
        <img src="{{ glide:text_img width="720" }}"
             srcset="{{ glide:text_img width="720" }} 780w,
                     {{ glide:text_img width="1024" }} 1024w,
                     {{ glide:text_img width="1440" }} 1440w"
             alt="{{ text_img | get:alt }}" />
    {{ /if }}
{{ /text_block }}
```
I have the same issue with my contact form types. Also in my contact form it is displaying the success message, even though the success variable is empty. 
```
{{ form:create in="contact" }}
    <input class="hidden" name="honeypot" value="">
    {{ if errors || success }}
        {{ partial:partials/alert }}
    {{ /if }}
    {{ fields }}
        {{ if type == 'text' }}
            <div class="mb-4 max-w-md relative text-secondary-500">
                <input class="input font-light bg-gray-100 border border-l-3 border-{{ error ? 'red' : 'gray' }}-400 appearance-none rounded w-full px-3 py-3 pt-5 pb-2 focus:border-primary-600 focus:outline-none active:outline-none active:border-primary-600"
                       id="{{ handle }}"
                       name="{{ handle }}"
                       type="{{ handle == 'email' ? 'email' : 'text' }}"
                       value="{{ old }}"
                       autofocus
                       {{ validate | contains:'required' ? 'required' : '' }}>
                <label for="{{ handle }}"
                       class="label absolute mb-0 -mt-1 pt-2 leading-tighter text-gray-800 text-base cursor-text"
                       style="padding-left:18px">
                    {{ display }}{{ validate | contains:'required' ? '*' : '' }}:
                </label>
            </div>
        {{ elseif type == 'textarea' }}
            <div class="mb-4 max-w-lg relative text-secondary-500">
                <textarea class="input font-light bg-gray-100 border border-l-3 border-{{ error ? 'red' : 'gray' }}-400 appearance-none rounded w-full px-3 py-3 pt-5 pb-2 focus:border-primary-600 focus:outline-none active:outline-none active:border-primary-600"
                          id="{{ handle }}"
                          type="{{ handle == 'email' ? 'email' : 'text' }}"
                          rows="2"
                          autofocus
                          {{ validate | contains:'required' ? 'required' : '' }}>{{ old }}</textarea>
                <label for="{{ handle }}"
                       class="label absolute mb-0 -mt-1 pt-2 leading-tighter text-gray-800 text-base cursor-text"
                       style="padding-left:18px">
                    {{ display }}{{ validate | contains:'required' ? '*' : '' }}:
                </label>
            </div>
        {{ elseif type == 'checkboxes' }}
            {{ options }}
                <div class="flex flex-wrap max-w-lg -mt-1 mb-4 text-secondary-500">
                    <label class="label-checkbox w-full flex" for="{{ handle }}">
                        <input id="{{ handle }}" name="{{ handle }}" type="checkbox" class="hidden" value="1" {{ validate | contains:'required' ? 'required' : '' }}>
                        <span class="checkbox"></span>
                        <span class="select-none text-sm md:text-base pr-2">
                            {{ gdpr }}
                        </span>
                    </label>
                </div>
            {{ /options }}
        {{ /if }}
    {{ /fields }}
    <button class="btn btn-primary btn-triangle">{{ general:submit }}</button>
{{ /form:create }}
```

**Comment by jasonvarga** [comment]
The first text_block snippet in your issue, is that the entire template?

Can you please post the corresponding blueprint, as well as the content file? I can't duplicate this issue, I think there must be something else getting involved.

**Comment by lightbringer93** [comment]
This is my blueprint for my pages. But I have the same problem in my contact form...
```
title: Page
sections:
  main:
    display: Main
    fields:
      -
        handle: template
        field:
          type: template
          display: Template
          localizable: true
          validate: required
      -
        handle: slider
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          max_files: 0
          type: assets
          localizable: false
          display: Slider
          container: assets
          folder: slider
          if:
            template: 'equals templates/home'
      -
        handle: banner_image
        field:
          container: assets
          mode: list
          folder: banners
          restrict: false
          allow_uploads: true
          max_files: 1
          type: assets
          localizable: false
          display: 'Banner image'
          listable: hidden
          if:
            template: 'equals templates/default'
      -
        handle: employees
        field:
          collections:
            - employees
          type: entries
          localizable: false
          listable: hidden
          display: Employees
          if:
            template: 'equals templates/team'
      -
        handle: testimonials
        field:
          type: entries
          localizable: false
          listable: hidden
          display: Testimonials
          collections:
            - testimonials
          if:
            template: 'equals templates/testimonials'
      -
        handle: investments
        field:
          sets:
            investment_block:
              display: 'Investment block'
              fields:
                -
                  import: icon
                  prefix: investment_
          type: replicator
          localizable: false
          listable: hidden
          display: Investments
          if:
            template: 'equals templates/investment'
      -
        handle: content_wrapper
        field:
          type: replicator
          localizable: false
          display: 'Content wrapper'
          sets:
            content_block:
              display: 'Content block'
              fields:
                -
                  handle: content_block
                  field:
                    sets:
                      text:
                        display: Text
                        fields:
                          -
                            import: title
                          -
                            import: block_width
                            prefix: text_
                          -
                            handle: border_left
                            field:
                              type: toggle
                              localizable: false
                              width: 25
                              display: 'Border left'
                          -
                            handle: main
                            field:
                              type: toggle
                              localizable: false
                              width: 25
                              display: 'Main block'
                          -
                            handle: text_block
                            field:
                              buttons:
                                - h2
                                - h3
                                - bold
                                - italic
                                - unorderedlist
                                - orderedlist
                                - removeformat
                                - quote
                                - anchor
                                - image
                                - table
                              save_html: false
                              toolbar_mode: fixed
                              link_noopener: false
                              link_noreferrer: false
                              target_blank: false
                              reading_time: false
                              fullscreen: true
                              allow_source: true
                              type: bard
                              localizable: false
                              display: 'Text block'
                              sets:
                                button:
                                  display: Button
                                  fields:
                                    -
                                      import: button
                                icons:
                                  display: Icons
                                  fields:
                                    -
                                      handle: icons
                                      field:
                                        sets:
                                          icon:
                                            display: Icon
                                            fields:
                                              -
                                                import: icon
                                                prefix: icon_
                                              -
                                                import: block_width
                                                prefix: icon_
                                        type: replicator
                                        localizable: false
                                        listable: hidden
                                        display: Icons
                                image:
                                  display: Image
                                  fields:
                                    -
                                      handle: text_img
                                      field:
                                        container: assets
                                        mode: list
                                        folder: content
                                        restrict: false
                                        allow_uploads: true
                                        max_files: 1
                                        type: assets
                                        localizable: false
                                        listable: hidden
                                        display: Image
                              container: assets
                              listable: hidden
                      image:
                        display: Image
                        fields:
                          -
                            import: title
                          -
                            import: block_width
                            prefix: img_
                          -
                            handle: image
                            field:
                              container: assets
                              mode: list
                              restrict: false
                              allow_uploads: true
                              max_files: 1
                              type: assets
                              localizable: false
                              display: Image
                              folder: content
                              width: 50
                          -
                            handle: img_absolute
                            field:
                              type: toggle
                              localizable: false
                              width: 50
                              listable: hidden
                              display: Absolute
                          -
                            handle: img_offset_top
                            field:
                              type: text
                              instructions: 'In pixel'
                              localizable: false
                              width: 25
                              listable: hidden
                              display: 'Offset top'
                          -
                            handle: img_offset_right
                            field:
                              type: text
                              instructions: 'In pixel'
                              localizable: false
                              width: 25
                              listable: hidden
                              display: 'Offset right'
                          -
                            handle: img_offset_bottom
                            field:
                              type: text
                              instructions: 'In pixel'
                              localizable: false
                              width: 25
                              listable: hidden
                              display: 'Offset bottom'
                          -
                            handle: img_offset_left
                            field:
                              type: text
                              instructions: 'In pixel'
                              localizable: false
                              width: 25
                              listable: hidden
                              display: 'Offset left'
                      progress:
                        display: Progress
                        fields:
                          -
                            import: title
                          -
                            import: block_width
                            prefix: progress_
                          -
                            handle: progress
                            field:
                              sets:
                                progress_step:
                                  display: 'Progress step'
                                  fields:
                                    -
                                      handle: step_title
                                      field:
                                        type: text
                                        localizable: false
                                        listable: hidden
                                        display: 'Step title'
                                    -
                                      handle: step_desc
                                      field:
                                        buttons:
                                          - h2
                                          - h3
                                          - bold
                                          - italic
                                          - unorderedlist
                                          - orderedlist
                                          - removeformat
                                          - quote
                                          - anchor
                                          - image
                                          - table
                                        save_html: false
                                        toolbar_mode: fixed
                                        link_noopener: false
                                        link_noreferrer: false
                                        target_blank: false
                                        reading_time: false
                                        fullscreen: true
                                        allow_source: true
                                        type: bard
                                        localizable: false
                                        listable: hidden
                                        display: 'Step description'
                                    -
                                      handle: step_img
                                      field:
                                        container: assets
                                        mode: list
                                        folder: content
                                        restrict: false
                                        allow_uploads: true
                                        max_files: 1
                                        type: assets
                                        localizable: false
                                        listable: hidden
                                        display: 'Step image'
                              type: replicator
                              localizable: false
                              listable: hidden
                              display: Progress
                    type: replicator
                    localizable: false
                    display: 'Content block'
                    listable: hidden
            partial_block:
              display: 'Partial block'
              fields:
                -
                  handle: partial_block
                  field:
                    options:
                      services: Services
                      testimonials: Testimonials
                      investment: Investment
                    clearable: false
                    multiple: false
                    searchable: true
                    taggable: false
                    push_tags: false
                    cast_booleans: false
                    type: select
                    localizable: false
                    listable: hidden
                    display: 'Partial block'
                -
                  handle: testimonials
                  field:
                    type: entries
                    localizable: false
                    listable: hidden
                    display: Testimonials
                    collections:
                      - testimonials
                    if:
                      partial_block: 'equals testimonials'
          listable: hidden
  sidebar:
    display: Sidebar
    fields:
      -
        handle: navigation
        field:
          type: section
          localizable: false
          display: Navigation
      -
        handle: menu_text
        field:
          character_limit: 0
          type: text
          localizable: false
          display: 'Menu text'
          validate: required
      -
        handle: slug
        field:
          generate: true
          type: slug
          localizable: false
          display: Slug
          validate: required
      -
        handle: is_hidden
        field:
          type: toggle
          localizable: false
          display: 'Hide from navigation'
      -
        handle: nav_icon
        field:
          container: assets
          mode: list
          folder: icon
          restrict: false
          allow_uploads: true
          max_files: 1
          type: assets
          localizable: false
          display: 'Nav icon'
          listable: hidden
      -
        handle: settings
        field:
          type: section
          localizable: false
          display: Settings
      -
        handle: author
        field:
          type: users
          display: Author
          localizable: true
          max_items: 1
  seo_og_tags:
    display: 'SEO / OG Tags'
    fields:
      -
        handle: document_title
        field:
          character_limit: 0
          type: text
          localizable: false
          display: 'Document title / OG Title'
      -
        handle: meta_desc
        field:
          type: textarea
          localizable: false
          display: 'Meta description'
      -
        handle: open_graph
        field:
          type: section
          localizable: false
          display: 'Open Graph'
      -
        handle: og_img
        field:
          container: assets
          mode: grid
          folder: og
          restrict: false
          allow_uploads: true
          max_files: 1
          type: assets
          localizable: false
          display: 'OG image'
```
This is my contact form blue print:
```
title: 'Contact form'
sections:
  main:
    display: Main
    fields:
      -
        handle: firstname
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Vorname
      -
        handle: lastname
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Nachname
          validate: required
      -
        handle: email
        field:
          character_limit: 0
          type: text
          localizable: false
          display: E-Mail
          validate: required|email
      -
        handle: message
        field:
          type: textarea
          localizable: false
          display: Nachricht
      -
        handle: gdpr
        field:
          options:
            gdpr: 'Ich habe die <a href="/datenschutzerklaerung.html" target="_blank">Datenschutzerklärung</a> zur Kenntnis genommen. Ich stimme zu, dass meine Angaben und Daten zur Beantwortung meiner Anfrage elektronisch erhoben und gespeichert werden.'
          inline: false
          type: checkboxes
          localizable: false
          display: DSGVO
          validate: required

```

**Comment by jasonvarga** [comment]
Thanks :)

**Comment by jasonvarga** [comment]
It seems to work fine here. 

You said:

>Since the last upgrade all my type conditions are not being recongnized anymore. 

What does not being recognized mean? In the first snippet, what gets output? Nothing?

**Comment by lightbringer93** [comment]
It depends of course on which site I dump the type. But when i dump it, it shows me the correct type, for example:
![Screenshot](https://user-images.githubusercontent.com/27002677/74219988-9a010500-4cae-11ea-94a3-b82ac423e9a5.png)
It is only not being recongnized in the if statement. Here is my complete content wrapper template. I created a _page builder_, where I can create multiply versions of layouts. At the moment it is quite messy, but I intend to create more partials in the future for text block, image block etc. 
```
{{ content_wrapper }}
    {{ if type == 'content_block' }}
        <!-- Content wrapper
        ============================================= -->
        <div class="container content">
            <div class="flex flex-wrap lg:mb-14 -mx-2 lg:-mx-3 xl:py-3">
                {{ if template == 'templates/contact' }}
                    <div class="w-full md:w-1/2 md:pl-6 xl:pr-6" data-aos="fade-right">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2702.7834670131997!2d8.547682016238026!3d47.35762531313604!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x479aa74dde979329%3A0xc741d15a90f6daa5!2sToweb%20GmbH!5e0!3m2!1sde!2sch!4v1579712774121!5m2!1sde!2sch" width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                    </div>
                {{ /if }}
                {{ content_block }}
                    {{ if type == 'text' }}
                        <!-- Text block
                        ============================================= -->
                        <{{ main ? 'main' : 'div' }} class="px-2 lg:px-3 w-full{{ if text_width == '3/4' }} md:w-3/4{{ elseif text_width == '2/3' }} md:w-2/3{{ elseif text_width == '1/2' }} md:w-1/2{{ elseif text_width == '1/3' }} md:w-1/3{{ elseif text_width == '1/4' }} md:w-1/4{{ /if }}"
                                                     data-aos="{{ text_animation ?? 'fade' }}">
                            <div class="{{ border_left ? 'md:border-l-3 md:border-primary-400 md:pl-6 xl:pr-6' : '' }}">
                                {{ if title }}
                                    {{ partial:partials/title }}
                                {{ /if }}
                                {{ text_block }}
                                    {{ type | dump }}
                                    {{ if type == 'text' }}
                                        {{ text }}
                                    {{ elseif type == 'button' }}
                                        {{ if !border_left }}
                                            {{ partial:partials/button }}
                                        {{ /if }}
                                    {{ elseif type == 'icons' }}
                                        {{ if !border_left }}
                                            <div class="flex flex-wrap ">
                                                {{ icons }}
                                                    {{ partial:partials/icon }}
                                                {{ /icons }}
                                            </div>
                                        {{ /if }}
                                    {{ elseif type == 'image' }}
                                        <img src="{{ glide:text_img width='720' }}"
                                             srcset="{{ glide:text_img width='720' }} 780w,
                                                     {{ glide:text_img width='1024' }} 1024w,
                                                     {{ glide:text_img width='1440' }} 1440w"
                                             alt="{{ text_img | get:alt }}" />
                                    {{ /if }}
                                {{ /text_block }}
                            </div>
                            {{ if border_left }}
                                {{ text_block }}
                                    {{ if type == 'button' }}
                                        {{ partial:partials/button }}
                                    {{ elseif type == 'icons' }}
                                        <div class="flex flex-wrap -mx-2 lg:-mx-3">
                                            {{ icons }}
                                                {{ partial:partials/icon }}
                                            {{ /icons }}
                                        </div>
                                    {{ elseif type == 'image' }}
                                        <img src="{{ glide:text_img width='720' }}"
                                             srcset="{{ glide:text_img width='720' }} 780w,
                                                     {{ glide:text_img width='1024' }} 1024w,
                                                     {{ glide:text_img width='1440' }} 1440w"
                                             alt="{{ text_img | get:atlt }}" />
                                    {{ /if }}
                                {{ /text_block }}
                            {{ /if }}
                        </{{ main ? 'main' : 'div' }}>
                    {{ elseif type == 'image' }}
                        <!-- Image block
                        ============================================= -->
                        <div class="{{ img_absolute ? 'relative z-1 ' : '' }}px-2 lg:px-3 w-full{{ if img_width == '3/4' }} md:w-3/4{{ elseif img_width == '2/3' }} md:w-2/3{{ elseif img_width == '1/2' }} md:w-1/2{{ elseif img_width == '1/3' }} md:w-1/3{{ elseif img_width == '1/4' }} md:w-1/4{{ /if }}"
                             data-aos="{{ img_animation ?? 'fade' }}">
                            <div class="{{ border_left ? 'md:border-l-3 md:border-primary-400 md:pl-6' : '' }}">
                                {{ if title }}
                                    {{ partial:partials/title }}
                                {{ /if }}
                                {{ if image }}
                                    <img class="{{ img_absolute ? 'absolute top-0 left-0' : '' }}"
                                         src="{{ glide:image width='720' }}"
                                         srcset="{{ glide:image width='720' }} 780w,
                                                 {{ glide:image width='1024' }} 1024w,
                                                 {{ glide:image width='1440' }} 1440w"
                                         alt="{{ image | get:alt }}"
                                         style="{{ if img_offset_top }}top:{{ img_offset_top }};{{ /if }}
                                                {{ if img_offset_right }}right:{{ img_offset_right }};{{ /if }}
                                                {{ if img_offset_bottom }}bottom:{{ img_offset_bottom }};{{ /if }}
                                                {{ if img_offset_left }}left:{{ img_offset_left }};{{ /if }}" />
                                {{ /if }}
                            </div>
                        </div>
                    {{ elseif type == 'progress' }}
                        <!-- Progress block
                        ============================================= -->
                        <div class="px-2 lg:px-3 w-full{{ if progress_width == '3/4' }} md:w-3/4{{ elseif progress_width == '2/3' }} md:w-2/3{{ elseif progress_width == '1/2' }} md:w-1/2{{ elseif progress_width == '1/3' }} md:w-1/3{{ elseif progress_width == '1/4' }} md:w-1/4{{ /if }}"
                             data-aos="{{ progress_animation ?? 'fade' }}">
                            {{ if title }}
                                {{ partial:partials/title }}
                            {{ /if }}
                            {{ if progress }}
                                <!-- Progress bar
                                ============================================= -->
                                <div class="flex flex-wrap justify-around relative text-center mb-7">
                                    <div class="absolute z-below h-3 w-full bg-primary-400 border-2 border-b-0 border-gray-300 rounded-full" style="margin-top:42px"></div>
                                    {{ progress }}
                                        <!-- Progress step
                                        ============================================= -->
                                        <div class="progress-step flex flex-col flex-1 items-center cursor-pointer{{ first ? ' active' : '' }}"
                                             tabindex="0" role="button" data-progress-step="{{ index | add:1 }}">
                                            <div class="flex items-center justify-center relative">
                                                <span class="absolute text-3xl {{ first ? 'text-white' : 'text-primary-500' }} font-extrabold leading-none mt-px pt-px -ml-px">
                                                    {{ index | add:1 }}
                                                </span>
                                                <img class="{{ first ? 'hidden' : '' }}"
                                                     src="{{ glide src='/assets/layout/progress-step-bg.png' width='85' }}"
                                                     srcset="{{ glide src='/assets/layout/progress-step-bg.png' width='85' }} 1x,
                                                             {{ glide src='/assets/layout/progress-step-bg.png' width='170' }} 2x"
                                                     alt="Progress step background" />
                                                <img class="{{ !first ? 'hidden' : '' }}"
                                                     src="{{ glide src='/assets/layout/progress-step-active-bg.png' width='85' }}"
                                                     srcset="{{ glide src='/assets/layout/progress-step-active-bg.png' width='85' }} 1x,
                                                             {{ glide src='/assets/layout/progress-step-active-bg.png' width='170' }} 2x"
                                                     alt="Progress step active background" />
                                            </div>
                                            <h4 class="text-primary-500">{{ step_title }}</h4>
                                        </div>
                                    {{ /progress }}
                                </div>
                                {{ progress }}
                                    <!-- Progress content
                                    ============================================= -->
                                    <div class="{{ !first ? 'hidden ' : 'active ' }} flex flex-wrap w-full border-3 border-primary-500 rounded"
                                         id="progressContent{{ index | add:1 }}">
                                        {{ if step_desc }}
                                            <div class="px-5 py-4 w-2/3">
                                                {{ step_desc }}
                                                    {{ if type == 'text' }}
                                                        {{ text }}
                                                    {{ /if }}
                                                {{ /step_desc }}
                                            </div>
                                        {{ /if }}
                                        {{ if step_img }}
                                            <img src="{{ glide:step_img width='350' }}"
                                                 srcset="{{ glide:step_img width='350' }} 780w,
                                                         {{ glide:step_img width='500' }} 1024w,
                                                         {{ glide:step_img width='700' }} 1440w"
                                                 alt="{{ step_img | get:alt }}">
                                        {{ /if }}
                                    </div>
                                {{ /progress }}
                            {{ /if }}
                        </div>
                    {{ /if }}
                {{ /content_block }}
            </div>
        </div>
    {{ elseif type == 'partial_block' }}
        {{ partial src="partials/{ partial_block | underscored }" }}
    {{ /if }}
{{ /content_wrapper }}
```
This is my pages content of the example dump.
```
---
title: 'Wir machen Webseiten'
template: templates/home
is_hidden: false
updated_by: 65b940e9-bfb0-40b6-81bd-5df49a2123bd
updated_at: 1580828095
menu_text: Home
content_wrapper:
  -
    content_block:
      -
        text_width: 2/3
        border_left: false
        main: true
        title: 'Wir machen Webseiten'
        subtitle: 'und Sie machen das, was Sie am besten können'
        title_size: h1
        title_icon: logo/toweb-brand.png
        text_block:
          -
            type: paragraph
            content:
              -
                type: text
                text: 'Unsere Erfahrung in den Bereichen Webdesign, Webseiten, Webshops sammeln wir seit 2007 mit unzähligen ausgeführten Projekten. Ihr Erfolg ist unser Ansporn. Gemeinsam legen wir fest, welches die optimalen Webdienstleistungen sind, um Ihre Sichtbarkeit im digitalen Zeitalter zu gewährleisten.'
        type: text
        enabled: true
        title_align: null
        text_animation: fade-right
    type: content_block
    enabled: true
  -
    partial_block: services
    type: partial_block
    enabled: true
    testimonials: null
  -
    content_block:
      -
        title: 'Einfach - Transparent - Sicher'
        subtitle: null
        title_size: h2
        title_icon: null
        text_width: 1/2
        border_left: true
        main: false
        text_block:
          -
            type: paragraph
            content:
              -
                type: text
                text: 'Wir sind der Meinung, Webdienstleistungen können durchaus bezahlbar sein. Wir bieten Ihnen ein günstiges Preis- Leistungsangebot. Sie wählen aus unseren variablen Angeboten das passende für Sich aus. Unser modularer Aufbau ermöglicht es Ihnen Ihr Packet so zusammen zu stellen, wie es Ihren Bedürfnissen gerade entspricht.'
          -
            type: set
            attrs:
              values:
                type: icons
                icons:
                  -
                    icon_name: 'Flexible Finanzierung'
                    icon_icon: icon/custom/icon-calculator.png
                    icon_link: null
                    icon_internal_link: null
                    icon_desc: null
                    type: icon
                    enabled: true
                    icon_width: 1/3
                    icon_animation: null
                  -
                    icon_name: 'Kluge Strategie'
                    icon_icon: icon/custom/icon-chart.png
                    icon_link: null
                    icon_internal_link: null
                    icon_desc: null
                    type: icon
                    enabled: true
                    icon_width: 1/3
                    icon_animation: null
                  -
                    icon_name: 'Grösste Sicherheit'
                    icon_icon: icon/custom/icon-safety.png
                    icon_link: null
                    icon_internal_link: null
                    icon_desc: null
                    type: icon
                    enabled: true
                    icon_width: 1/3
                    icon_animation: null
          -
            type: set
            attrs:
              values:
                type: button
                btn_text: 'Jetzt mehr erfahren'
                btn_class: primary-outline
                btn_internal_link: 7bdd0ba7-f546-42c1-b57f-125592fb8775
                btn_external_link: null
                btn_triangle: true
                alignment: null
          -
            type: set
            attrs:
              values:
                type: button
                btn_text: 'Kontakt aufnehmen'
                btn_class: primary
                btn_internal_link: 75c0c3f6-da5e-46b6-8414-9f003aa95e0b
                btn_external_link: null
                btn_triangle: false
                alignment: null
        type: text
        enabled: true
        title_align: null
        text_animation: fade-left
      -
        title: null
        subtitle: null
        title_size: null
        title_icon: null
        img_width: 1/2
        image: content/home/home-1-content.png
        type: image
        enabled: true
        title_align: null
        img_animation: fade-right
        img_absolute: true
        img_offset_top: '-65px'
        img_offset_right: null
        img_offset_bottom: null
        img_offset_left: null
    type: content_block
    enabled: true
  -
    content_block:
      -
        title: null
        subtitle: null
        title_size: null
        title_icon: null
        text_width: 2/3
        border_left: true
        main: false
        text_block:
          -
            type: paragraph
          -
            type: set
            attrs:
              values:
                type: image
                text_img: content/home/home-2-content.png
          -
            type: set
            attrs:
              values:
                type: icons
                icons:
                  -
                    icon_name: '13'
                    icon_icon: icon/custom/icon-toweb.png
                    icon_link: null
                    icon_internal_link: null
                    icon_desc: 'Jahre toweb'
                    icon_width: 1/4
                    icon_animation: null
                    type: icon
                    enabled: true
                  -
                    icon_name: '1''218'
                    icon_icon: icon/custom/icon-customer.png
                    icon_link: null
                    icon_internal_link: null
                    icon_desc: Kunden
                    icon_width: 1/4
                    icon_animation: null
                    type: icon
                    enabled: true
                  -
                    icon_name: '2''164'
                    icon_icon: icon/custom/icon-project.png
                    icon_link: null
                    icon_internal_link: null
                    icon_desc: Projekte
                    icon_width: 1/4
                    icon_animation: null
                    type: icon
                    enabled: true
                  -
                    icon_name: '115'
                    icon_icon: icon/custom/icon-coffee.png
                    icon_link: null
                    icon_internal_link: null
                    icon_desc: 'Kaffee pro Woche'
                    icon_width: 1/4
                    icon_animation: null
                    type: icon
                    enabled: true
          -
            type: paragraph
            content:
              -
                type: text
                text: 'Wir entlasten Sie von der Komplexität der Digitalisierung. Auch sorgen wir dafür, dass Sie von Anfang an wissen, was Sie Ihr Webauftritt kosten wird.'
              -
                type: hard_break
              -
                type: text
                text: 'Damit Sie sich um das kümmern können, was Ihnen wichtig ist: Ihr Kerngeschäft bzw. Ihre Kunden. Mit uns als Partner gehen Sie keinerlei Abhängigkeiten ein, da wir auf die Open Source Partner MadeSimple und PrestaShop setzten. Somit haben Sie jederzeit die Möglichkeit bzw. Option, dass Sie bei Bedarf auch mit anderen Partner zusammen zu arbeiten, ohne gleich alles wieder neu erstellen zu müssen.'
          -
            type: set
            attrs:
              values:
                type: button
                btn_text: 'Jetzt unverbindlich beraten lassen'
                btn_class: primary-outline
                btn_internal_link: 75c0c3f6-da5e-46b6-8414-9f003aa95e0b
                btn_external_link: null
                btn_triangle: true
                alignment: null
        type: text
        enabled: true
        title_align: null
        text_animation: fade-left
      -
        title: null
        subtitle: null
        title_size: null
        title_icon: null
        img_width: 1/3
        image: content/home/home-3-content.png
        type: image
        enabled: true
        title_align: null
        img_animation: fade-right
        img_absolute: true
        img_offset_top: null
        img_offset_right: null
        img_offset_bottom: null
        img_offset_left: null
    type: content_block
    enabled: true
  -
    partial_block: testimonials
    type: partial_block
    enabled: true
    testimonials:
      - d0738cd7-425a-4393-a0d7-36d51ea43079
      - 4dab9cdf-d0c0-4045-aa67-3b3bf3554c14
      - 2a228cef-7513-4aa1-bea7-cdf6dd8b52ec
      - 49927a02-ec53-4293-8280-c356bbed6534
      - 6d6607b8-1b4d-422d-bd99-f5594d1ec675
      - 2c8ed715-cbd5-4434-acfe-e594e30f7d16
      - ea1ff5c7-0b93-42c0-88d4-af509b3061fc
      - 91857e75-8763-47b4-afd9-5f0d2a6bf68b
  -
    content_block:
      -
        title: null
        subtitle: null
        title_size: null
        title_align: null
        title_icon: null
        text_width: null
        text_animation: fade-right
        border_left: false
        main: false
        text_block:
          -
            type: set
            attrs:
              values:
                type: button
                btn_text: 'Kontakt aufnehmen'
                btn_class: primary
                btn_internal_link: 75c0c3f6-da5e-46b6-8414-9f003aa95e0b
                btn_external_link: null
                btn_triangle: false
                alignment: right
          -
            type: set
            attrs:
              values:
                type: button
                btn_text: 'Weitere Referenzen'
                btn_class: primary-outline
                btn_internal_link: 7d4ed903-75de-4487-b3dc-c26cc10747c4
                btn_external_link: null
                btn_triangle: true
                alignment: right
        type: text
        enabled: true
    type: content_block
    enabled: true
author: 65b940e9-bfb0-40b6-81bd-5df49a2123bd
id: home
---
```
