### ISSUE TITLE
toAugmentedArray() doesn't return all values

### ISSUE THREAD

**Issue by goellner** [statamic/cms#1322]
When using toAugmentedArray() not all fields are returned. It looks like all fields, which are some sort of array return an empty object instead of the data.

Example:

This markdown:
```
-
        type: set
        attrs:
          values:
            type: card
            image: fern.jpg
            aspect_ratio: 16-9
            section_headline: null
            headline: 'Card Headline'
```

output from toAugmentedArray():

```
image: { },
aspect_ratio: { },
section_headline: null,
headline: "Card Headline",
type: "card"
```
