### ISSUE TITLE
A taxonomy can't be null, even when checking if it exists

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1350]
```
Call to a member function collection() on null
```

Even when checking if the taxonomy is defined

From my blueprint
```
-
    handle: course_type
    field:
       mode: select
       type: taxonomy
       localizable: false
       listable: hidden
       display: Kursart
       max_items: 1
-
```

Saved data
```
course_type: null
```

In my view
```
{{ if course_type }}
     <tr>
           <td class="font-bold">Kurszeit</td>
           <td>{{ course_type }}</td>
     </tr>
{{ /if }}
```
