### ISSUE TITLE
Cannot access Bard field elements in template 

### ISSUE THREAD

**Issue by tobiaseichert** [statamic/cms#1377]
For some reason, I'm not able to access the various parts of my Bard field content using the approach described here:

https://statamic.dev/fieldtypes/bard#templating

Here's the field configuration:

```yaml
article_body:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'This is just an example text for testing purposes.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Anyway, here's another paragraph you can have a look at.'
```

Current template code in default.antlers.html:
```
    {{ article_body }}
      {{ type }}
    {{ /article_body }}
```

I used {{ type }} to check if I could access all the parts, but there's no output as if the field wasn't there at all. Am I doing something wrong here? If I dump the {{ article_body }} variable using

```
{{ article_body | dump }}
```

there's just HTML (the combined paragraphs from above) in it which explains why I cannot access the individual parts. The "Save HTML instead of structured data." option in my Bard field config is disabled:

```yaml
handle: article_body
field:
  buttons:
    - h2
    - h3
    - bold
    - italic
    - unorderedlist
    - orderedlist
    - removeformat
    - quote
    - anchor
    - image
    - table
  container: assets
  save_html: false
  toolbar_mode: fixed
  link_noopener: false
  link_noreferrer: false
  target_blank: false
  reading_time: false
  fullscreen: true
  allow_source: true
  type: bard
  localizable: false
  listable: hidden
  display: 'Article Body'
```
