### ISSUE TITLE
If toggle not working in replicator inside another replicator

### ISSUE THREAD

**Issue by AndersMFJ** [statamic/cms#1383]
I have a blueprint with a replicator with a number of sets, one of these sets is a replicator (cards) for displaying cards with text/image/video/whatever. In the template I'm using the following code to pick the appropriate partial. rep_content is the handle of the first replicator field in the blueprint: 

```
{{ rep_content }}
    {{ partial src="replicator/{type}" }}
{{ /rep_content }}
```
The partial template looks like this (with some stuff removed for brevity):
```
 {{ cards }}
      <div>
            {{ if image }}<img src="{{ glide:image preset='50' }}" />{{ /if }}
            {{ if header }}<h2>{{ header }}</h2>{{ /if }}
            {{ if copy }}<p>{{ copy }}</p>{{ /if }}
            {{ if link }}<p>{{ partial:partials/button url = "{{ link }}" text = "{{ if link_text }}{{ link_text }}{{ else }}{{ trans:frontend.read_more }}{{ /if }}" }}</p>{{ /if }}
            {{ if form }}{{ partial:partials/form }}{{ /if }}
      </div>
{{ /cards }}
``` 
The cards part of the blueprint looks like this: 
```
      cards:
        display: Cards
        fields:
          -
            handle: header
            field:
              type: text
              localizable: false
              listable: hidden
              display: Header
          -
            import: text_color
          -
            handle: background_color
            field:
              theme: classic
              color_modes:
                - HEXA
              default_color_mode: HEXA
              type: color
              localizable: false
              listable: hidden
              display: 'Background color'
          -
            handle: cards
            field:
              sets:
                card:
                  display: Card
                  fields:
                    -
                      import: image_and_caption
                    -
                      import: video_with_preview_and_settings
                    -
                      handle: header
                      field:
                        type: text
                        localizable: false
                        listable: hidden
                        display: Header
                    -
                      handle: copy
                      field:
                        type: textarea
                        localizable: false
                        listable: hidden
                        display: Copy
                    -
                      handle: large_text
                      field:
                        type: toggle
                        localizable: false
                        listable: hidden
                        display: 'Large text'
                    -
                      import: link
                    -
                      import: form
              type: replicator
              localizable: false
              listable: hidden
              display: Cards
```
I would expect that filling the copy field in a card (inside an entry) would mean that the field is enabled in the template and the content in the copy field is displayed. This doesn't work. Weirdly though, if I just use the variable directly it is shown. 

So this outputs the content of the copy field
```
{{ copy }}
```
But this outputs nothing:
```
{{ if copy }}{{ copy }}{{ /if }}
```

Beta 16 and multi-site
