### ISSUE TITLE
Textarea field in a stacked grid has no height

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#1395]
![image](https://user-images.githubusercontent.com/3626559/74720085-7a7d5580-5235-11ea-9163-0c1e6a2b2460.png)

Field config:
```
-
    handle: address
    field:
        type: textarea
        localizable: false
        listable: hidden
        display: Address
        rows: 20
```

**Comment by jackmcdade** [comment]
I can't recreate this. Do you have any other clues? What browser is it in? Is the grid inside another field?

**Comment by riasvdv** [comment]
It's happening in both Firefox and Chrome for me

This is the full Global config:

```
title: Globals
sections:
  main:
    display: Main
    fields:
      -
        handle: logos
        field:
          type: section
          localizable: false
          display: 'Logo''s'
      -
        handle: logo
        field:
          type: assets
          max_files: 1
          width: 50
          mode: list
          restrict: false
          allow_uploads: true
          display: Logo
          instructions: 'Logo for light backgrounds'
      -
        handle: favicon
        field:
          type: assets
          max_files: 1
          width: 50
          mode: list
          instructions: 'Displayed in the browser tab'
      -
        handle: links
        field:
          type: section
          localizable: false
          display: Links
      -
        handle: facebook
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Facebook
          validate: url
          width: 33
      -
        handle: twitter
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Twitter
          validate: url
          width: 33
      -
        handle: linkedIn
        field:
          character_limit: 0
          type: text
          localizable: false
          display: LinkedIn
          validate: url
          width: 33
  offices:
    display: Offices
    fields:
      -
        handle: offices
        field:
          fields:
            -
              handle: flag
              field:
                type: text
                localizable: false
                listable: hidden
                display: Flag
                width: 33
            -
              handle: name
              field:
                type: text
                localizable: false
                listable: hidden
                display: Name
                width: 33
            -
              handle: mapLink
              field:
                type: text
                localizable: false
                listable: hidden
                display: 'Map link'
                width: 33
            -
              handle: address
              field:
                type: textarea
                localizable: false
                listable: hidden
                display: Address
                rows: 20
          mode: stacked
          reorderable: true
          type: grid
          localizable: false
          listable: hidden
          display: Offices
          add_row: Add office
```

So the textareas are inside the grid in the second tab of the globals
