### ISSUE TITLE
group_by modifier throws query builder error

### ISSUE THREAD

**Issue by alexharrell** [statamic/cms#1406]
When I want to use the group_by modifier I get the following error:

strtolower() expects parameter 1 to be string, object given

and highlights the following section of vendor/statamic/cms/src/Query/Builder.php

```
    protected function invalidOperator($operator)
    {
        return ! in_array(strtolower($operator), array_keys($this->operators), true);
    }
```

This is what will break it:
`{{ fd_fair_date_items group_by="fdi_audience" }}{{ /fd_fair_date_items }}`

This is in a partial -> data is stored in a replicator inside a replicator

**Comment by jasonvarga** [comment]
What fieldtype is `fdi_audience`? Text?

**Comment by alexharrell** [comment]
Single select

**Comment by jasonvarga** [comment]
Are you on the latest version?

**Comment by alexharrell** [comment]
Yes, but started earlier than 17. I can't say when as this is a complicated partial and I'm new to Statamic so keep trying to do lots of different things (thinking it is my lack of skills). But ultimately, what I'm doing is pulling a list from a globals file, iterating through things and if a toggle for grouping is turned on, I use the group by. In it's simplest form:

```
{{ site_preferences:fair_dates }}
    {{ if fd_group_by_audience }}
        {{ fd_fair_date_items group_by="fdi_audience" }}

        {{ /fd_fair_date_items }}
    {{ /if }}
{{ /site_preferences:fair_dates }}
```

**Comment by alexharrell** [comment]
Here is part of the YAML from the globals file:

```
fair_dates:
    -
      fd_date: '2020-03-14 18:21'
      fd_title_for_day: 'Project Check-in'
      fd_subtitle_for_day: 'Students check-in with their boards and completed forms.'
      fd_fair_date_items:
        -
          fdi_start_time: '14:00'
          fdi_end_time: null
          fdi_item_title: 'Volunteers Arrive'
          fdi_item_description: null
          type: fair_date_item
          enabled: true
          fdi_audience: volunteers
        -
          fdi_start_time: '14:00'
          fdi_end_time: '17:00'
          fdi_item_title: 'STEM Fair Project Check-in'
          fdi_item_description: null
          type: fair_date_item
          enabled: true
          fdi_audience: students-parents
      type: fair_date
      enabled: true
      fd_location_title: 'SMC Event Center - Fiesta Hall'
      fd_location_link: null
      fd_date_tbd: false
      fd_group_by_audience: false
```
