### ISSUE TITLE
Setting multiple: true on a select creates "strtolower() expects parameter 1 to be string, object given" error

### ISSUE THREAD

**Issue by twd3** [statamic/cms#1421]
I have this in my blueprint:
```
      -
        handle: case_type
        field:
          type: select
          display: 'Case Type'
          validation: required
          multiple: true
          options:
            car: 'Automobile Accident'
            truck: 'Commercial Truck Accident'
            work: 'Construction Accident'
            bad: 'Insurance Bad Faith'
            legal: 'Legal Malpractice'
            med: 'Medical Malpractice'
            death: 'Wrongful Death'
            moto: 'Motorcycle Accident'
            ped: 'Pedestrian Accident'
            bic: 'Bicycle Accident'
          listable: true
          clearable: false
          searchable: false
          taggable: false
          push_tags: false
          cast_booleans: false
```
When I select multiple case_types I get this data:
```
case_type:
  - bad
  - legal
```
All looks right but then I get this error: https://flareapp.io/share/NPG0xk7G Hopefully this is not a dupe issue...
