### ISSUE TITLE
reply_to not working for Forms

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1438]
When I try and use `reply_to` in my form's yaml file and submit the form, the email is sent but not with a reply_to header and just wants to reply to the sending address (in my case an email which doesn't accept receiving emails)

```yaml
  -
    to: contact@somecompany.co.uk
    reply_to: "{{ email }}"
    subject: 'Appointment Booking Form'
```

Also, when you try and set `{{ email }}` as the reply to thing in the Control Panel, I hit a validation error complaining that it's not an email.

![image](https://user-images.githubusercontent.com/19637309/75279437-8653b380-5803-11ea-964c-dfe7feba5138.png)
