### ISSUE TITLE
Includes/Contains conditional not working

### ISSUE THREAD

**Issue by goellner** [statamic/cms#1462]
I have the following fieldset configuration and the `hero_poster` field is not showing up.

```
  hero_media:
    container: assets
    mode: grid
    restrict: false
    allow_uploads: true
    max_files: 1
    type: assets
    localizable: false
    listable: hidden
    width: 50
    display: Image/Video
  hero_poster:
    container: assets
    mode: grid
    restrict: false
    allow_uploads: true
    max_files: 1
    type: assets
    localizable: false
    listable: hidden
    display: Poster
    width: 50
    if:
      hero_media: includes mp4
```

I tried all of the following, but no luck:

```
    if:
      hero_media: includes mp4

    if:
      hero_media: 'includes mp4'

    if:
      hero_media: contains mp4

    if:
      hero_media: 'contains mp4'

```
