### ISSUE TITLE
Cannot output grid field value using shorthand variable

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#1474]
I've run into this issue a few times, where outputting a value with a tag pair works:
`{{ hero_button }} {{ label }} {{ /hero_button }}`

But using the shorthand has no output or error.
`{{ hero_button:label }}`

blueprint:
```
title: Home
sections:
  main:
    display: Main
    fields:
      -
        import: button
        prefix: hero_
```

fieldset:
```
title: Button
fields:
  button:
    fields:
      -
        handle: label
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Label
      -
        handle: link
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Link
    mode: table
    max_rows: 1
    min_rows: 0
    add_row: 'Add Button'
    reorderable: true
    type: grid
    localizable: false
    width: 100
    display: Button
```

content:
```
hero_button:
  -
    label: 'Request Demo'
    link: /demo
    icon: true
```
