### ISSUE TITLE
Field condition params

### ISSUE THREAD

**Issue by jesseleite** [statamic/cms#1490]
Right now you can write custom JS conditions by referencing your custom function like:

```
if: heroMediaIsVideo
```

It might also be nice to make a more reusable JS condition, and pass param(s) to it like:

```
if: 'isVideo:hero_media'
```

Also, the ability to run custom conditions on specific fields, so that multiple conditions can be used:

```
if_any:
  hero_media: 'custom isType:mp4'
  hero_image: 'custom isType:jpg'
  hero_text: 'not empty'
```

Also also, object destructuring on the JS side, so that we can pass even more useful things without enforcing param order:

```
Statamic.$conditions.add('isType', function ({ target, value, root }) {
    //
});
```
