### ISSUE TITLE
Cannot render variables injected in collection YAML file

### ISSUE THREAD

**Issue by fourstacks** [statamic/cms#1517]
I'm running into the exact issue specified in #1103 but the problem seems to be more broadly applicable to any attempt to use `inject` to add data at a collection level.  

My setup is:

`content/collections/articles.yaml`

```
title: Articles
route: '/{slug}'
template: articles/show
blueprints: articles
orderable: true
structure: sections
revisions: false
inject:
  foo: 'bar'
date: true
sort_dir: asc
default_status: draft
date_behavior:
  past: public
  future: private
entry_order:
  - 90cb9bc3-4c92-425d-be3a-71ffbf3081c9
  - 05f17c8a-17ad-43dd-87d7-29ef317e2e4f
  - 334b4be3-bc61-4a02-a94b-db21822cc9fb
```

In `resources/views/articles/show.antlers.html`

```
{{ foo }}
```

This should result in `bar` being printed but nothing is printed.
