### ISSUE TITLE
PHP gets commented out in Antlers

### ISSUE THREAD

**Issue by lbattaglioli2000** [statamic/cms#1519]
So I have one of them fancy fangled Bard field types in my periodical blueprint. The bard itself has several sets associated with it, one of them being a set called `php_code` which is nothing more than a Code field type. 

In my template, when I go to iterate through the sets in my bard field variable (`article_body` is the actual variable name), I can access the `type` totally fine (that being `php_code`). I know the type is being accessed because I do get the gray span where the code should be when I load the page.  

When I go to actually print the `code` itself, (`{{ code }}`) however, nothing shows up. I tried dumping the value and it *does* show that the code is there.

# My Template

```
{{ article_body }}
    {{ if type == "text" }}
        {{ text }}
    {{ elseif type == "php_code" }}
        <div>
            <pre class="rounded bg-gray-100 my-4 p-4 overflow-scroll shadow-inner"><code>{{ code }}</code></pre>
        </div>
    {{ /if }}
{{ /article_body }}
```

# My Markdown

```
---
title: 'Lorem is good stuff'
publish_date: '2020-03-17 02:52'
author: 1
summary: 'This is just a sample article. Read on for more information.'
article_photo: luigi.jpg
updated_by: 1
updated_at: 1584640502
id: 1cf26fdb-7850-409d-b761-59d04efc5a38
article_body:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet consequatur doloremque ipsa maxime nisi quasi repudiandae saepe sint vitae? Corporis labore maiores minus praesentium quae, quibusdam quidem sequi veniam.'
  -
    type: set
    attrs:
      values:
        type: php_code
        code: |
          <?php
              echo "Hi";
          ?>
---
```

I looked at the source code and nothing was showing there. My thought was that the PHP was some how being run but I'm really not sure.

**Comment by lbattaglioli2000** [comment]
# Update!

I just cleared my stache and it caused something else to happen. The code still doesn't show up on the page, however now there is an *HTML comment* containing the code. But obviously since it's a comment, it doesn't show up on the page itself. I have no clue why it's rendering as a comment 🙁

**Comment by jasonvarga** [comment]
can you try `{{ php_code | noparse }}` ?

**Comment by lbattaglioli2000** [comment]
`{{ php_code | noparse }}` shows __lex_no_value__ on my template.

Also, `php_code` is the name of the set and `code` is the key that contains the code. I also tried {{ code | noparse }} and that didn't output anything except the code as an HTML comment 😕 

![Screen Shot 2020-03-19 at 3 05 31 PM](https://user-images.githubusercontent.com/13672801/77104859-121bc280-69f3-11ea-9a11-4119e915325c.png)

**Comment by lbattaglioli2000** [comment]
Not sure if it helps, but here is my periodical blueprint too if you want to take a peek at it.

```
title: Periodical
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          input_type: text
          type: text
          instructions: 'give er'' a good title'
          localizable: false
          listable: true
          display: Title
      -
        handle: publish_date
        field:
          mode: single
          time_enabled: false
          time_required: false
          earliest_date: '1900-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          type: date
          localizable: false
          width: 50
          listable: true
          display: 'Publish Date'
      -
        handle: author
        field:
          max_items: 1
          mode: typeahead
          type: users
          localizable: false
          width: 50
          listable: hidden
          display: Author
      -
        handle: summary
        field:
          type: textarea
          localizable: false
          width: 50
          listable: true
          display: Summary
      -
        handle: article_photo
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          max_files: 1
          type: assets
          instructions: 'Give the article an eye catching photo.'
          localizable: false
          listable: true
          display: 'Article Photo'
          width: 50
      -
        handle: article_body
        field:
          buttons:
            - h1
            - h2
            - h3
            - h4
            - h5
            - h6
            - bold
            - italic
            - underline
            - strikethrough
            - unorderedlist
            - orderedlist
            - removeformat
            - anchor
            - image
            - table
            - code
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: true
          fullscreen: true
          allow_source: true
          type: bard
          localizable: false
          listable: true
          display: Content
          sets:
            playlist:
              display: Playlist
              fields:
                -
                  handle: playlist_embed_code
                  field:
                    restrict: false
                    automatic_line_breaks: true
                    automatic_links: false
                    escape_markup: false
                    smartypants: false
                    type: markdown
                    instructions: 'Add your playlist iFrame embed code.'
                    localizable: false
                    listable: true
                    display: 'Playlist Embed Code'
            quote:
              display: Quote
              fields:
                -
                  handle: quote
                  field:
                    type: textarea
                    localizable: false
                    listable: hidden
                    display: Quote
                -
                  handle: author
                  field:
                    input_type: text
                    type: text
                    localizable: false
                    listable: hidden
                    display: Author
            php_code:
              display: 'PHP Code'
              fields:
                -
                  handle: code
                  field:
                    theme: material
                    mode: php
                    indent_type: tabs
                    indent_size: 4
                    line_numbers: true
                    line_wrapping: true
                    key_map: default
                    type: code
                    localizable: false
                    listable: hidden
                    display: Code
```
