### ISSUE TITLE
Bard List Items add nested content with paragraphs

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/cms#1522]
```
content:
      -
        type: list_item
        content:
          -
            type: paragraph
            content:
              -
                type: text
                text: 'To foster and stimulate improvements in all aspects of healthcare of infants, children, and adolescents;'
```

Because of the extra paragraph info it is harder to style properly.
