### ISSUE TITLE
Assets not augmented inside grid field

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#1527]
```
downloads:
  -
    category: Unternehmen
    files:
      - path/filename.pdf
      - path/filename.pdf
  -
    category: Kataloge
    files:
      - path/filename.pdf
      - path/filename.pdf
  -
    category: Flyer
    files:
      - path/filename.pdf
      - path/filename.pdf
      - path/filename.pdf

```

```
{{ downloads}}
{{ files }}
{{ alt }} // No output
{{ filename }} // No output
{{ url }} // No output
{{ /files }}
{{ /downloads}}
```
