### ISSUE TITLE
A collection without a route takes over the homepage since beta 20

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#1537]
If I have a collection "A" without a route and a collection "Pages" with a route of `{parent_uri}/{slug}`, going to the homepage will try to load the first entry from "A" (because it's alphabetically first)

Hope this explains it well

**Comment by mikemartin** [comment]
Yep! Also happening to me. The `Analyze` entry from my `How it works` collection (the first collection without a route) is loading as the homepage.

**Pages** collection
`/collections/pages.yaml`
```
title: Pages
template: default
layout: layout
blueprints:
  - default
revisions: false
route: '{parent_uri}/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
```

**How it works** collection
`/collections/how-it-works.yaml`

```
title: 'How it works'
template: how-it-works.index
blueprints:
  - how_it_works
mount: 040322da-43d5-4e8e-8183-260bce79c1a4
revisions: false
date_behavior:
  past: public
  future: private
structure:
  max_depth: 1
  tree:
    -
      entry: dcf416a3-4612-40c9-b822-5450c143b479
    -
      entry: 0f7441c1-8bac-4d42-b36e-00d51d96fe40
    -
      entry: 87a60d06-7858-4094-a38b-323a37d0e720
```

**Comment by jasonvarga** [comment]
Ooh good one. Thanks!

**Comment by jasonvarga** [comment]
@riasvdv What's in your content/collections/pages.yaml?

**Comment by riasvdv** [comment]
```yaml
title: Pages
template: page
layout: layouts/main
blueprints:
  - page
revisions: false
route: '{parent_uri}/{slug}'
structure:
  root: true
  tree:
    -
      entry: d1cc3004-fd1e-44b4-9ec8-d1614b9ee19d
    -
      entry: f6ffcda5-0f65-4e5d-a163-df73250e1cb9
    -
      entry: 0451b734-1934-46a3-98b5-78e68a567302
    -
      entry: 3082a70a-032e-4323-a5e2-50f3142709fc

```
