### ISSUE TITLE
Scoped content doesn't have access to parent scope

### ISSUE THREAD

**Issue by aryehraber** [statamic/cms#1550]
A common pattern that I followed in V2 was to use the Replicator fieldtype to add "page builder" functionality to pages using a simple template that dynamically called the correct partial based on its `type`.

Data:
```yaml
---
title: Lorem Ipsum Title
logo: partners/lorem-ipsum-logo.svg
page_content:
  -
    type: hero
    title: Lorem Ipsum
    byline: Lorem ipsum vitae elit libero, a pharetra augue.
---
```

Template:
```
{{ page_content scope="set" }}
  {{ partial src="sets/{type}" }}
{{ /page_content }}
```

This technically still works, however one major difference seems to be that inside the loop (if `scope="whatever"` is used) we no longer have access to the parent scope. This means that shared data that was saved outside of `page_content` can't be accessed.

Hero Set:
```html
<section>
  <h1>{{ set:title }}</h1> <!-- works -->
  <p>{{ set:byline }}</p> <!-- works -->
  {{ logo }}
    <img src="{{ url }}" alt="{{ alt }}"> <!-- doesn't work -->
  {{ /logo }}
</section>
```

Hopefully I'm just missing something?
