### ISSUE TITLE
Select fieldtype doesn't show in the data-table listing

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#1551]
![image](https://user-images.githubusercontent.com/44739/77771827-9981bb00-701d-11ea-8f98-cfee0a7b3a08.png)

**Comment by jasonvarga** [comment]
It tries to show the label but you didn't add any:

![image](https://user-images.githubusercontent.com/105211/77772363-61c74300-701e-11ea-8e6e-bd07d61098d0.png)

``` yaml
        field:
          type: select
          options:
            Bench: null
            Chair: null
            Couch: null
            Hammock: null
            Stool: null
            Swing: null
```
