### ISSUE TITLE
Select fields in taggable mode don't save the values

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1555]
Defeats the purpose if you can't create.

Also applies to relationship fields in select or typeahead modes.

**Comment by damcclean** [comment]
Looks like this issue has been resolved by the looks of it... I created a new `select` field in one of my blueprints (field config as below). I created an entry with some select options, also created a new option. Looking at the entry, all of the options were saved correctly.

```yaml
-
        handle: select
        field:
          options:
            test: test
            wip: WIP
          multiple: true
          clearable: false
          searchable: true
          taggable: true
          push_tags: true
          cast_booleans: false
          display: Select
          type: select
          icon: select
          listable: hidden
```
