### ISSUE TITLE
if condition breaks output

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#1580]
```
preise:
  -
    einheit: VVK
    preis: '15'
  -
    einheit: AK
    preis: '17'
  -
    einheit: 'Alle 3 Veranstaltungen'
    preis: '39'`
```
With condition:
```
{{ if preise }}
{{ preise limit="1" }}
<span class="value">ab {{ preis }} €</span> <span class="label">/ {{ einheit }}</span>
{{ /preise }}
{{ /if }}
```
Output
```
<div class="price">
 [{"einheit":"VVK","preis":"15"}]
<span class="value">ab  €</span> <span class="label">/ </span>
{{ /preise }}
</div>
```
Without condition:
```
<div class="price">
{{ preise limit="1" }}
<span class="value">ab {{ preis }} €</span> <span class="label">/ {{ einheit }}</span>
{{ /preise }}
</div>
```
Output
```
<div class="price">
<span class="value">ab 15 €</span> <span class="label">/ VVK</span>
</div>
```
