### ISSUE TITLE
Call to Undefined when calling collection entries endpoint

### ISSUE THREAD

**Issue by aamood** [statamic/cms#1586]
When calling the `/api/collections/{collection}/entries` endpoint I am getting the error: 
Call to undefined method Statamic\Structures\Tree::id()

Here's my call in vue:
```
window.axios({
      method: 'get',
      url: `${window.ps.appUrl}api/collections/${this.collection}/entries`,
}).then((response) => {
      this.posts = response.data;
});
```

Here's the formatted URL on my local: `https://website.localhost.com/api/collections/blog/entries`

Here's my collection:
```
title: Blog
template: blog/standard
layout: layout
blueprints:
  - default
  - home
taxonomies:
  - tags
revisions: false
route: '/blog/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
structure:
  root: true
  tree:
    -
      entry: db161ef5-d891-48d6-8b09-50166c868a4d
    -
      entry: 8cb67ce5-05e9-4465-80ea-54aa08d22795
    -
      entry: 90917140-85a1-43fe-a787-f180d0ef4291
    -
      entry: 1f2c749b-c0a7-4b2c-ac02-12540588c4d7
```
