### ISSUE TITLE
Converting single to multisite error : Undefined index: name  [site.php#26]

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#1611]
**Describe the bug**
When trying to convert a single site to a multisite following the documentation here, i get an error saying : **Undefined index: name (View: /Users/pixney/Development/Web/mysite/vendor/statamic/cms/resources/views/layout.blade.php)**

![image](https://user-images.githubusercontent.com/31292231/78301290-260a0d00-7539-11ea-9705-4d1ec7c7c80f.png)

**To Reproduce**
1) Create a website on v3.23. My website has only one page: home.
2) My home.md looks like this:
```
---
title: Home
page_content:
  -
    image: park-view.jpg
    type: header_image
    enabled: true
    headline_small: 'sasassas'
    headline: Asasasas
    image_alt_text: 'A beautiful park with swimming pools'
  -
    space_top: none
    editor:
      -
        type: heading
        attrs:
          level: 2
        content:
          -
            type: text
            text: 'What Good Life Is Made of'
      -
        type: paragraph
        content:
          -
            type: text
            text: 'sasasas'
      -
        type: paragraph
        content:
          -
            type: text
            text: 'dadadd'
    image: main_01.jpg
    type: section_with_image_and_editor
    enabled: true
    background_color: bg-wind
    editor_placement: order-1
  -
    editor:
      -
        type: heading
        attrs:
          level: 2
        content:
          -
            type: text
            text: 'dadadada'
      -
        type: paragraph
        content:
          -
            type: text
            text: 'dadadadadaddadadad'
      -
        type: paragraph
        content:
          -
            type: text
            text: 'ddaddadadddadadad'
    image: breakfast_01.jpg
    type: section_with_image_and_editor
    enabled: true
    space_top: none
    background_color: bg-wind
    editor_placement: order-1
pagetitle: 'A title tag is an HTML element that specifies the title of a web page.'
page_description: 'A title tag is an HTML element that specifies the title of a web page.'
updated_by: 4268f7ef-8d1a-44cd-a8af-0b64272c83df
updated_at: 1585845937
template: home
id: home
---

```

3) My page blueprint:
```
title: Page
sections:
  main:
    display: Main
    fields:
      -
        import: default
  seo:
    display: SEO
    fields:
      -
        import: seo
  settings:
    display: Settings
    fields:
      -
        handle: template
        field:
          hide_partials: true
          type: template
          localizable: false
          listable: hidden
          display: Template

```

4 One of the fieldsets:
```
title: Default
fields:
  page_content:
    sets:
      header_image:
        display: 'Header Image'
        fields:
          -
            handle: headline_small
            field:
              input_type: text
              type: text
              instructions: 'Small uppercase headline above main headline'
              localizable: false
              listable: hidden
              display: 'Headline small'
              width: 50
          -
            handle: headline
            field:
              input_type: text
              type: text
              instructions: 'Main headline in the page header'
              localizable: false
              listable: hidden
              display: Headline
              width: 50
          -
            handle: image
            field:
              container: assets
              mode: grid
              folder: /
              restrict: false
              allow_uploads: true
              max_files: 1
              type: assets
              localizable: false
              listable: hidden
              display: Image
              width: 33
          -
            handle: image_alt_text
            field:
              input_type: text
              type: text
              instructions: 'Alt text for those that can not see, describe the image with words.'
              localizable: false
              listable: hidden
              display: 'Image Alt Text'
              width: 66
      section_with_image_and_editor:
        display: 'Section with image and editor'
        fields:
          -
            handle: editor
            field:
              buttons:
                - h2
                - h3
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - removeformat
                - quote
                - anchor
              save_html: false
              toolbar_mode: fixed
              link_noopener: true
              link_noreferrer: true
              target_blank: false
              reading_time: false
              fullscreen: true
              allow_source: true
              type: bard
              localizable: false
              width: 66
              listable: hidden
              display: editor
          -
            handle: image
            field:
              container: assets
              mode: grid
              folder: /
              restrict: false
              allow_uploads: true
              max_files: 1
              type: assets
              localizable: false
              listable: hidden
              display: image
              width: 33
          -
            handle: background_color
            field:
              options:
                bg-wind: Wind
                bg-water: Water
                bg-sun: Sun
              clearable: false
              multiple: false
              searchable: true
              taggable: false
              push_tags: false
              cast_booleans: false
              type: select
              instructions: 'Select a background color for the text area'
              localizable: false
              width: 33
              listable: hidden
              display: 'Background Color'
          -
            handle: space_top
            field:
              options:
                none: None
                tight: Tight
                normal: Normal
              clearable: false
              multiple: false
              searchable: true
              taggable: false
              push_tags: false
              cast_booleans: false
              type: select
              instructions: 'Select the spacing you would like to use toward the top.'
              localizable: false
              listable: hidden
              display: 'Space Top'
              width: 33
          -
            handle: editor_placement
            field:
              options:
                order-1: Left
                order-2: Right
              clearable: false
              multiple: false
              searchable: true
              taggable: false
              push_tags: false
              cast_booleans: false
              type: select
              instructions: 'Do you want to place the editor to the left or to the right'
              localizable: false
              listable: hidden
              display: 'Editor Placement'
              width: 33
    type: replicator
    localizable: false
    listable: hidden
    display: Content

```

5) My seo fieldset:

```
title: Seo
fields:
  pagetitle:
    character_limit: 70
    type: text
    localizable: false
    display: Pagetitle
    instructions: 'A title tag is an HTML element that specifies the title of a web page. Title tags are displayed on search engine results pages (SERPs) as the clickable headline for a given result, and are important for usability, SEO, and social sharing. The title tag of a web page is meant to be an accurate and concise description of a page''s content. **[Keep it to around max 60 chars]**'
    listable: hidden
    placeholder: placeholder
    input_type: text
    validate: required
  page_description:
    type: textarea
    localizable: false
    display: 'Page Description'
    instructions: 'The meta description is an HTML attribute that provides a brief summary of a web page. Search engines such as Google often display the meta description in search results, which can influence click-through rates. **[Keep it to around max 50–160 chars]**'
    validate: required
    listable: hidden
    character_limit: '300'
  page_image:
    mode: grid
    restrict: false
    allow_uploads: true
    max_files: 1
    type: assets
    localizable: false
    display: 'Page Image'
    instructions: 'The page image represents this page when you share it on different social media networks together with the page description and page title. For best visual effect it is important you follow the ratio guidelines:  **[Ratio: 1.91:1 - 1200x630 pixels**'
    listable: hidden
    folder: og
    container: assets

```

6) Run `php please multisite` accept that your first site is default, then enter something for the second site. Add it to config, clear cache and if you now visit the dashboard you should get the same error.

**Screenshots**
![image](https://user-images.githubusercontent.com/31292231/78301581-9add4700-7539-11ea-9137-d77126b20840.png)

**Environment (please complete the following information):**
 - Statamic version:
    Statamic 3.0.0-beta.23
 - Install method: 
    Fresh install from statamic/statamic
 - PHP version:
   PHP 7.3.16
 - Operating System:
    MacOS
 - Browser:
    Brave
