### ISSUE TITLE
[fieldtypes] Cannot set Options in the CP for some fieldtypes (beta24)

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1665]
## Bug Description
When creating either an ARRAY, a SELECT, a RADIO or a CHECKBOXES fieldtypes, there is no way to define their OPTIONS in the CP.

Am I missing something?

## How to Reproduce
Add one of those fieldtype to a Blueprint

## Extra Detail
![Capture d'écran 2020-04-11 23 05 23](https://user-images.githubusercontent.com/1823359/79054968-986da200-7c49-11ea-98c3-cb2069697828.png)

```html
<div class="form-group publish-field array-fieldtype field-w-full">
<div class="field-inner">
<label class="publish-field-label">
<span class="">Options</span> 
<!----> <!----> <!----> <!----> 
<button class="outline-none" style="display: none;">
<div class="h-4 ml-sm w-4 text-grey-60 svg-icon using-svg has-tooltip" data-original-title="null">
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M10.082 9.5A4.47 4.47 0 0 0 6.75 8h-1.5a4.5 4.5 0 0 0 0 9h1.5a4.474 4.474 0 0 0 3.332-1.5M13.918 9.5A4.469 4.469 0 0 1 17.25 8h1.5a4.5 4.5 0 1 1 0 9h-1.5a4.472 4.472 0 0 1-3.332-1.5M6.75 12.499h10.5" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></path></svg></div></button> 
<button class="outline-none" style="display: none;">
<div class="h-4 ml-sm w-4 text-grey-60 svg-icon using-svg has-tooltip" data-original-title="null"><svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs" viewBox="0 0 24 24"><g transform="matrix(1,0,0,1,0,0)"><path d="M 16.5,15.749h1.875c2.17,0.092,4.01-1.58,4.125-3.749l0,0c-0.114-2.17-1.954-3.842-4.125-3.75H16.5 " stroke="currentColor" fill="none" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path><path d="M 7.5,15.749H5.625C3.455,15.841,1.615,14.169,1.5,12l0,0c0.115-2.169,1.955-3.842,4.125-3.75H7.5 " stroke="currentColor" fill="none" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path><path d="M 12,5.249v-4.5 " stroke="currentColor" fill="none" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path><path d="M 9,5.249 l-1.5-1.5 " stroke="currentColor" fill="none" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path><path d="M 15,5.249l1.5-1.5 " stroke="currentColor" fill="none" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path><path d="M 12,18.749v4.5 " stroke="currentColor" fill="none" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path><path d="M 9,18.749l-1.5,1.5 " stroke="currentColor" fill="none" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path><path d="M 15,18.749l1.5,1.5" stroke="currentColor" fill="none" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path></g></svg></div></button></label> <div class="help-block -mt-1"><p>Set the array keys and their optional labels.</p>
</div></div> <!----> <!----> <!----></div>
```

## Environment

**Statamic version:** 3.0.0.-beta-24

**PHP version:** 7.2.20

**MAC OS 10.12.6
Chrome 81 or Safari 12.1.2

**Install method (choose one):**
I tried with:
- Fresh install from `statamic/statamic`
- Updated beta23 install with composer update up to Beta24 now
- Starter kit (Cool Writings)

**Comment by ramimassoud** [comment]
I ran into this too, this is the error I noticed in the Chrome dev console

```
vue.common.prod.js:6 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at a.isKeyed (ArrayFieldtype.vue:109)
    at fn.get (vue.common.prod.js:6)
    at fn.evaluate (vue.common.prod.js:6)
    at a.isKeyed (vue.common.prod.js:6)
    at a.<anonymous> (ArrayFieldtype.vue?a802:1)
    at a.e._render (vue.common.prod.js:6)
    at a.r (vue.common.prod.js:6)
    at fn.get (vue.common.prod.js:6)
    at new fn (vue.common.prod.js:6)
```

I even have options set in the yaml file and the error still happens

**Comment by ebeauchamps** [comment]
ok. Did not see this, but I can confirm that manually adding the OPTIONS in the Blueprint give access to those Options in the Entry, but they are still not displayed when viewing the Blueprint in the CP

My Blueprint:
```
        handle: selector
        field:
          clearable: true
          multiple: true
          searchable: true
          taggable: true
          push_tags: true
          cast_booleans: true
          type: select
          localizable: false
          listable: hidden
          display: Selector
          instructions: 'just a selector test'
          placeholder: 'select me'
          options:
            donuts: Donuts
            icecream: 'Ice Cream'
            brownies: Brownies
      -
        handle: radio
        field:
          inline: false
          type: radio
          localizable: false
          listable: hidden
          display: Radio
          options:
            donuts: Donuts
            icecream: 'Ice Cream'
            brownies: Brownies
      -
        handle: checkboxes
        field:
          inline: false
          type: checkboxes
          options:
            donuts: Donuts
            icecream: 'Ice Cream'
            brownies: Brownies
          localizable: false
          listable: hidden
          display: Checkboxes
```

My entry:
![Capture d'écran 2020-04-12 23 41 33](https://user-images.githubusercontent.com/1823359/79080670-324f5080-7d17-11ea-88b8-9b517c123aed.png)
