### ISSUE TITLE
Exception Root page cannot have children

### ISSUE THREAD

**Issue by peimann** [statamic/cms#1666]
## Bug Description
I've added a child to the root item in navigation then I can't see the navigations because of 500 error.
## How to Reproduce
Add a child to root item in navigation. You may need to enable root item in nav configurations.
## Extra Detail

<img width="827" alt="image" src="https://user-images.githubusercontent.com/40042952/79064896-cd1d4000-7cc1-11ea-99a5-55c85b91ccd0.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/40042952/79064909-e6be8780-7cc1-11ea-9e62-78769ce354dd.png">

## Environment

**Statamic version:** 3.0.0.-beta-24

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Did the CP let you do that?

Move it manually in the YAML to fix it.

``` yaml
tree:
  -
    entry: the root
    children:
      -
        entry: a-child
```

change to 

``` yaml
tree:
  -
    entry: the root
  -
    entry: a-child
```
```

**Comment by stuartcusackie** [comment]
Same exception here. I can't remember exactly what I did but I just installed Statamic, created a super user, the messed about with the sidebar in Preview mode of the default Home page.

Now I'm having trouble fixing things and have a new error after following your advice:
**Call to a member function selectedQueryColumns() on null**

Here's how the pages.yaml file looks:

```
title: Pages
revisions: false
route: '{parent_uri}/{slug}'
structure:
  root: true
  tree:
    -
      entry: 4deede67-8e61-4a9d-b7e6-beae95db3fa1
    -
      entry: home
```
