### ISSUE TITLE
Email templates not working

### ISSUE THREAD

**Issue by icemancast** [statamic/cms#1681]
## Bug Description

I created a new form and set an email template in the control panel. It still still uses the default system email template.

## How to Reproduce

Create a form in control panel, select an email template that you have in your views folder. When the email gets sent you will see the default template still being used.

## Extra Detail

`resources/forms/request.yaml`

```
title: 'Request'
blueprint: request
email:
  -
    to: email@domain.com
    subject: 'New Request'
    template: emails/request
```

`resources/views/emails/request.antlers.html`

```
----------------------------------------------
Please keep all requests confidential.
----------------------------------------------

Name: {{ name }}
Email: {{ email }}

{{ request }}

Date: {{ date }}
```

## Environment

**Statamic version:** 3.0.0.-beta-25

**PHP version:** 7.2

**Install method (choose one):**
- Fresh install from `statamic/statamic`
