### ISSUE TITLE
Taxonomy listing with collection param returns all terms

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#1684]
## Bug Description

We have a collection with one entry that is tagged with a single term. When I pass the collection param, I would expect to only have that single term return however it returns all terms.

```
{{ taxonomy:levels collection="math-zone" }}
      <a href="{{ url }}">{{ title }}</a>
{{ /taxonomy:levels }}
```

It looks like the collection parameter is queried here but then it returns all terms. https://github.com/statamic/cms/blob/master/src/Tags/Taxonomy/Terms.php#L36

**Statamic version:** 3.0.0.-beta-26

**PHP version:** 7.{?}

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Starter kit
- Existing Laravel app
- Other (please explain this magic!)

**Comment by jasonvarga** [comment]
How many terms are in that taxonomy? Are they all being output?

**Comment by edalzell** [comment]
2 terms

**Comment by edalzell** [comment]
@mikemartin I'm not sure this is true. I see the filtering working https://challengeteacher.online/word-play/levels/primary & https://challengeteacher.online/word-play/levels/intermediate

**Comment by edalzell** [comment]
What I DO see is that when are NO terms, all are shown, like here: https://challengeteacher.online/math-zone/levels/primary there should be nothing shown.

The code we're using is:
```
      {{ collection :from="segment_1" }}
        <li class="flex flex-1">
          {{ partial:activities/card }}
        </li>
      {{ /collection }}
```

**Comment by jasonvarga** [comment]
The code in the initial issue description is a taxonomy tag. Now you're showing me a collection tag. I'm confused. 🤔

**Comment by edalzell** [comment]
Ya sorry I'm confused too, let me regroup and report, feel free to delete my comments. I gotta understand how we're using the taxonomies.

**Comment by mikemartin** [comment]
Hey @jasonvarga,
If you visit @edalzell site at http://challengeteacher.online/math-zone you'll see that the Math Zone collection has one entry, yet both terms are listed. 

Levels Taxonomy
/taxonomies/level.yaml
```
title: Levels
blueprints:
  - level
```

Taxonomy terms in /taxonomies/levels:
`intermediate.yaml`
`primary.yaml`

Collection entry in `/collections/math-zone/`:
`2020-04-13.a-problem-4-you.md`
```
---
title: 'A Problem 4 You'
summary: 'Come up with the numbers from 1 to 15 using four fours'
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Did you know you can make a lot of numbers with exactly four fours?'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Using addition, subtraction, multiplication, division, parentheses (to show what to do first) and square roots, see if you can make equations that use four fours to come up with the numbers from 1 to 15.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'For example 4÷4+4-4=1 '
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Llama''s hint: remember that the square root of 4 is 2. '
levels:
  - intermediate
updated_by: 4385e51a-052c-4af4-a564-3a9690f4003b
updated_at: 1586804054
id: 6f400cb2-5999-45fe-bd14-000ab8379c21
---
```
