### ISSUE TITLE
Array validation syntax doesn't work inside Replicator etc

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1702]
## Bug Description

There's no great way to validate against fields in the same context/set inside replicator.

## How to Reproduce

```yaml
-
  handle: replicator
  field:
    type: replicator
    sets:
      intro:
        fields:
          -
            handle: add_cta
            field:
              type: toggle
          -
            handle: cta_text
            field:
              type: text
              validate: make this required if add_cta in the same set is true        
```

You might try `validate: 'require_if:replicator.*.add_cta,true'` but the `*` doesn't get replaced as expected.

## Extra Detail

Replicator already duplicates the validation rules for all the sets.
If you have `validate: somerule` on a `foo` field, it actually duplicates it for as many times as that set was used in the submitted data.

Lets say you submitted a replicator field and the first and fourth sets had that `foo` field, it would generate these rules:

```
replicator.0.foo => 'somerule',
replicator.3.foo => 'somerule',
```

I think the solution should be to allow an asterisk to represent "this field and this index".

```
validate: 'require_if:*.add_cta,true'
```
or maybe leave the asterisk to mean the index, and have a separate thing as a placeholder for the field:
```
validate: 'require_if:{parent}.*.add_cta,true'
```

Should generate something like:

```
replicator.0.foo => 'required_if:replicator.0.add_cta',
replicator.3.foo => 'required_if:replicator.3.add_cta',
```

You shouldn't need to put the name of the field you're in. It may cause issues if you're using importing that field from a fieldset etc.

## Environment

**Statamic version:** 3.0.0.-beta.26
