### ISSUE TITLE
Index variable inside of loop starts at zero instead of one

### ISSUE THREAD

**Issue by nerdroid23** [statamic/cms#1729]
## Bug Description
In the documentation, it says that to get the current index of a loop, we can use the `index` which starts at 1 and `zero_index` which starts at 0. 

## How to Reproduce
Create a loop and output the `index` variable

## Extra Detail
![image](https://user-images.githubusercontent.com/21242932/80180975-8dabf900-85c9-11ea-8e27-216e02f393f1.png)

`antlers file`
```html
{{ benefits_list }}
  <div class="numbered-block__item{{ if last }} mb-4{{ /if }}" data-aos="slide-up">
    <div class="numbered-block__num">{{ index }}</div>
      <div class="numbered-block__text">
        <h5 class="text-primary font-weight-bold">{{ title }}</h5>
        <p class="small">{{ subtitle }}</p>
    </div>
  </div>
{{ /benefits_list }}
```

`md file`
```yaml
benefits_list:
      -
        title: 'Sin costo para tu empresa.'
        subtitle: 'Nosotros ponemos el capital.'
        type: benefit
        enabled: true
      -
        title: 'Bajo costo, seguro e inmediato para tu colaborador.'
        subtitle: 'Tu colaborador puede acceder a su nómina y decidir cuando y cuanto quiere adelantarse las 24 x 7 x 365.'
        type: benefit
        enabled: true
      -
        title: 'Fácil Administración.'
        subtitle: 'Solo dedícale 10 minutos por ciclo de nómina. Funciona con cualquier sistema de nómina.'
        type: benefit
        enabled: true
```

## Environment

**Statamic version:** 3.0.0-beta.27

**PHP version:** 7.4.2

**Install method (choose one):**
- [x] Fresh install from `statamic/statamic`
