### ISSUE TITLE
Can't save a link in a Bard

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1738]
## Bug Description
I have a bard and when I try to save content with a link in it (by using the Bard link button), I get an "invalid data" error
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/6069653/80293630-a7f2ed80-8715-11ea-8dc9-763eff9d5b55.png">

## How to Reproduce

1. Create a Bard field
2. Go into the CP for that content
3. Select some text, add an URL
4. Save

## Extra Detail

```
        handle: description
        field:
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          type: bard
          localizable: false
          listable: hidden
          display: Description
          sets:
            times_table:
              display: 'Times table'
              fields:
                -
                  handle: table
                  field:
                    type: table
                    localizable: false
                    listable: true
                    display: 'Times table'
          container: assets
```

## Environment

**Statamic version:** 3.0.0.-beta-27

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`
