### ISSUE TITLE
Join modifier doesn't work on a select fieldtype

### ISSUE THREAD

**Issue by huladesign** [statamic/cms#1753]
## Bug Description
I've set up a select fieldtype with the option to select multiple options enabled. When looping through the selected options, commas aren't being inserted.

## How to Reproduce
For my exact scenario, the template code may be more specific. However, it was just done by creating a select field type, enabling the option for multiple selections and looping through the options using in the antlers fashion. The select field was pulling through keywords saved in a collection entry if that matters.

## Extra Detail
**Blueprint snippet**
```yaml
      -
        handle: project_tag
        field:
          options:
            branding: Branding
            content: Content
            design: Design
          clearable: false
          multiple: true
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          type: select
          localizable: false
          width: 50
          listable: hidden
          display: 'Project Tag'
      -
```

**page.md**
```yaml
project_tag:
  - branding
  - content
```

**index.antlers.html**
I tried the below ways
```html
{{ collection :from="work" }}
    {{ project_tag | join }}
        {{ value }}
    {{ /project_tag }}
{{ /collection }}

{{ collection:work }}
    {{ project_tag | join }}
        {{ value }}
    {{ /project_tag }}
{{ /collection:work }}

{{ collection:work }}
    {{ project_tag join=', ' }}
        {{ value }}
    {{ /project_tag }}
{{ /collection:work }}
```

## Environment

**Statamic version:** 3.0.0.-beta-26

**PHP version:** 7.4.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`
