### ISSUE TITLE
Error message when collection is missing is not clear

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1788]
## Bug Description

If you have an `entries` fieldtype referencing a non-existent collection and you reference the fieldset in the CP, the error is not very clear.

## How to Reproduce

Make a fieldset (by hand) that has an entries fieldtype w/ a non-existent collection:
```
                    field:
                      type: entries
                      max_items: 1
                      width: 50
                      display: Entry
                      collections:
                        - i-dont-exist
                        - blog
```

## Extra Detail

https://flareapp.io/share/o7Aeqd7p

## Environment

**Statamic version:** 3.0.0-beta-27

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic` (with migrator)
