### ISSUE TITLE
`get_content` fails when using `:` and `id`

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1791]
## Bug Description

When you use `:id` in the `get_content` tag you get an array offset error

## How to Reproduce
Blueprint:
```yaml
      -
        handle: reference
        field:
          collections:
            - posts
          type: entries
          localizable: false
          listable: hidden
          display: Reference
          max_items: 1
```

Content:
```yaml
---
title: Home
template: home
reference: 2ecd287f-2c01-45ab-bc29-b48be746ad3a
updated_by: e8982d24-f8f9-4e2f-9286-062f9d98aa4a
updated_at: 1588704828
id: home
---
Welcome to your new Statamic website.
```

Template:
```html
{{ get_content :id="reference" }}
{{ /get_content }}
```

## Extra Detail
![image](https://user-images.githubusercontent.com/6069653/81105029-37439200-8ec8-11ea-9e9b-b7624b70b0a3.png)

## Environment

**Statamic version:** 3.0.0.-beta-27

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`
