### ISSUE TITLE
User Groups

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#18]
In v2, users are tracked within the user groups yaml.

With #9 it would be nice to move user groups into a config file. However, we don't want to track the users in there.

The idea is to flip it, and put the groups within the user's yaml.

v2:

``` yaml
# groups.yaml
admin:
  title: Admin
  roles:
    - admin
  users:
    - john
```

v3:

``` php
# config/auth.php
return [
  'groups' => [
    'admin' => [
      'title' => 'Admin',
      'roles' => ['admin'],
    ]
];
```

``` yaml
# users/john.yaml
name: John
groups:
  - admin
```
