### ISSUE TITLE
Bard field adds unwanted paragraphs to list items

### ISSUE THREAD

**Issue by jmartsch** [statamic/cms#1805]
## Bug Description
I have an unordered list in a bard field which looks like this:
![image](https://user-images.githubusercontent.com/551551/81279486-810eb280-9057-11ea-8132-49ea8324f31b.png)

When I output the list, there are <p> tags in the unordered list, which are unwanted:
`<ul><li><p><a href="https://processwire.com/">ProcessWire</a> 3</p></li><li><p><a href="https://foundation.zurb.com/">Foundation for sites</a> 6 framework</p></li><li><p>SASS</p></li><li><p><a href="https://webpack.js.org/">Webpack</a></p></li><li><p>Gulp</p></li><li><p>Git</p></li></ul>`

The markdown file also seems to be not correct:
```
   type: bullet_list
    content:
      -
        type: list_item
        content:
          -
            type: paragraph
            content:
              -
                type: text
                marks:
                  -
                    type: link
                    attrs:
                      href: 'https://processwire.com/'
                      target: null
                      rel: null
                text: ProcessWire
              -
                type: text
                text: ' 3'
      -
```
The type of the list item should be text and not paragraph. This problem also affects ordered lists.

I think the problem is not the output, but the input, as it adds a paragraph in a list, when you press "Enter".

## Environment

**Statamic version:** 3.0.0.-beta-26
