### ISSUE TITLE
API Routes all return 404

### ISSUE THREAD

**Issue by repomaa** [statamic/cms#1818]
## Bug Description

Any request to `/api/...` routes result in 404 html responses.

## How to Reproduce

1. Set STATAMIC_API_ENABLED=true
2. Optionally set STATAMIC_API_ROUTE=api
3. restart php-fpm
4. `curl https://<local_statamic>/api/globals

## Extra Detail

I've set up statamic to run in a php-fpm docker container.

``` Dockerfile
# Dockerfile

FROM composer:1.10 AS composer
WORKDIR /app
RUN composer create-project statamic/statamic . --prefer-dist --stability=dev
RUN composer install --optimize-autoloader --no-dev
RUN php artisan config:cache
RUN php artisan route:cache
RUN php artisan view:cache

FROM php:7.3-fpm-alpine AS php-fpm
RUN apk add --update freetype-dev libjpeg-turbo-dev libpng-dev \
	&& docker-php-ext-configure gd \
	&& docker-php-ext-install -j$(nproc) gd \
	&& docker-php-ext-configure exif \
	&& docker-php-ext-install -j$(nproc) exif
COPY --from=composer --chown=1000:1000 /app /app
USER 1000:1000
WORKDIR /app

FROM nginx:latest AS nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
```

``` yaml
# docker-compose.yml
version: '3.7'
services:
  nginx:
    build:
      context: .
      target: nginx
    ports:
      - 3000:80
    volumes:
      - ./public:/app/public:ro
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      target: php-fpm
    environment:
      STATAMIC_API_ENABLED: 'true'
    volumes:
      - storage:/app/storage
      - ./public:/app/public
      - ./config:/app/config
      - ./addons:/app/addons
      - ./content:/app/content
      - ./users:/app/users
      - ./resources:/app/resources

volumes:
  storage:
```

``` nginx
# nginx.conf
server {
        listen 80 default_server;
        root /app/public;

        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";

        index index.html index.htm index.php;

        charset utf-8;

        location / {
                try_files $uri $uri/ /index.php?$query_string;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        error_page 404 /index.php;

        location ~ \.php$ {
                fastcgi_pass php-fpm:9000;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
                include fastcgi_params;
        }

        location ~ /\.(?!well-known).* {
                deny all;
        }
}
```

`/cp/utilities/phpinfo` shows `STATAMIC_API_ENABLED    true` under Environment. 

## Environment

**Statamic version:** 3.0.0.-beta.28

**PHP version:** 7.3.17

**Install method (choose one):**
- Fresh install from `statamic/statamic`
