### ISSUE TITLE
Partial not recognising on-the-fly params

### ISSUE THREAD

**Issue by tobiaseichert** [statamic/cms#1824]
## Bug Description
I've created a partial for picture markup so I can include it in various templates:
```html
{{ image }}
<div class="ratio bg-gray-300" style="padding-bottom: calc({{ height }} / {{ width }} * 100%);">
  <picture>
    <source data-srcset="{{ glide:url width='1024' fm='webp' q='75' dpr='2' }}" type="image/webp">
    <source data-srcset="{{ glide:url width='1024' fm='jpg' q='75' dpr='2' }}" type="image/jpeg">
    <img data-src="{{ glide:url width='1024' fm='jpg' q='75' dpr='2' }}"
         data-action="zoom"
         alt="{{ alt }}" title="{{ alt }}"
         class="opacity-0 lazyload" />
  </picture>
</div>
{{ /image }}
```

If the handle of the image field is called "image", it simply works with the partial above.

```html
{{ partial src="partials/picture"}}
```

However, not all of my image fields are called "image" and have a maximum number of assets. For example, there's an image field called "feature_image", as well as an image field inside a Bard set called "gallery" which can house more than one image at a time. This is where things become tricky. I simply cannot get this partial to work in those cases.

I have the following data structures:

Simple image field with handle "feature_image" with max number of assets = 1:
```yaml
feature_image: 2020/03/10/firefox.png
```
Image field with handle "image" inside Bard set with max number of assets = 1:
```yaml
  -
    type: set
    attrs:
      values:
        type: image
        image: IMG_0692.JPG
```
Image field with handle "gallery" inside Bard set with unlimited number of assets:
```yaml
  -
    type: set
    attrs:
      values:
        type: gallery
        gallery:
          - 2020/02/29/IMG_0331.JPG
          - 2020/02/29/IMG_0342.JPG
          - 2020/02/29/IMG_0516.JPG
          - 2020/02/29/IMG_0536.JPG
          - 2020/02/29/IMG_0553.JPG
          - 2020/02/29/IMG_0554.JPG
```

How can I invoke the partial for "feature_image" and "gallery"?

There's a hint on https://statamic.dev/tags/partial regarding the use of on-the-fly params:

> Note that the :items parameter is prefixed by a colon, meaning it will pass the value of a flavors variable, if it exists.

I've tried to map the handle of those fields with an on-the-fly param called "image" which didn't work.

{{ partial src="partials/picture" :image="feature_image" }}

I'm not sure if this is a bug or some misconfiguration on my part. In addition, if I pass a variable "foo" with a value of "bar" to the partial, it's simply not there (null).

## How to Reproduce

Try to access on-the-fly params inside your partial. They're null (at least with my setup). 

## Extra Detail
Here's the article blueprint containing the various image fields:
```yaml
title: Article
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          localizable: false
          listable: hidden
          display: Title
      -
        handle: feature_image
        field:
          container: assets
          mode: grid
          restrict: false
          allow_uploads: true
          max_files: 1
          type: assets
          localizable: false
          listable: hidden
          display: 'Feature Image'
      -
        handle: main_content
        field:
          sets:
            image:
              display: Image
              fields:
                -
                  handle: image
                  field:
                    container: assets
                    mode: grid
                    restrict: false
                    allow_uploads: true
                    max_files: 1
                    type: assets
                    localizable: false
                    listable: hidden
                    display: Asset
                -
                  handle: caption
                  field:
                    type: textarea
                    localizable: false
                    listable: hidden
                    display: Caption
            gallery:
              display: Gallery
              fields:
                -
                  handle: gallery
                  field:
                    container: assets
                    mode: grid
                    restrict: false
                    allow_uploads: true
                    type: assets
                    localizable: false
                    listable: hidden
                    display: Gallery
                -
                  handle: caption
                  field:
                    type: textarea
                    localizable: false
                    listable: hidden
                    display: Caption
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - table
            - code
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          type: bard
          localizable: false
          listable: hidden
          display: 'Main content'
```

## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`
