### ISSUE TITLE
List modifier showing array to string conversion error when used with multi-select.

### ISSUE THREAD

**Issue by twd3** [statamic/cms#1832]
List modifier is popping a view exception. Says "Array to string conversion".

Reproduce by having a collection entry that uses a select with multiple true then in your template use that select tag and include the modifier "list". Will error on the front.

I'm on Windows using valet.

Statamic 3.0.0.-beta-28

**PHP version:** 7.3.6

Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Please include your template snippet.

**Comment by twd3** [comment]
View:
```
{{ collection:verdicts }}
      <p>{{ case_type | list }}</p>
{{ /collection:verdicts }}
```
Field:
```
      -
        handle: case_type
        field:
          type: select
          display: 'Case Type'
          validation: required
          multiple: true
          options:
            car: 'Automobile Accident'
            truck: 'Commercial Truck Accident'
            work: 'Construction Accident'
            bad: 'Insurance Bad Faith'
            legal: 'Legal Malpractice'
            med: 'Medical Malpractice'
            death: 'Wrongful Death'
            moto: 'Motorcycle Accident'
            ped: 'Pedestrian Accident'
            bic: 'Bicycle Accident'
          listable: true
          clearable: true
          searchable: false
          taggable: true
          push_tags: true
          cast_booleans: false
```
Data:
```
case_type:
  - car
  - death
```
