### ISSUE TITLE
Select Fieldtype augmentation to return label is not working

### ISSUE THREAD

**Issue by andrewcgregory** [statamic/cms#1833]
## Bug Description
I have a Select Fieldtype for assigning a category to a collection, but am unable to output the Label for this field in an antlers template. According to [the docs](https://statamic.dev/fieldtypes/select#templating) I would use `{{ category }}` for the label and `{{ category | raw }}` for the raw value, but both are exporting the raw value.

## How to Reproduce
**Blueprint Field:**
```
-
        handle: category
        field:
          options:
            web-design: 'Web Design'
            paid-search-advertising: 'Paid Search Advertising'
          clearable: false
          multiple: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          type: select
          localizable: false
          listable: hidden
          display: Category
```

**Collection:**
`category: paid-search-advertising`

**Antlers Template:**
` <p class="section-heading">{{ category }}</p>`

**Output:**
`<p class="section-heading">paid-search-advertising</p>`

## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`
