### ISSUE TITLE
Navigation variable is_parent not working as intended

### ISSUE THREAD

**Issue by FlorianMoser** [statamic/cms#1839]
The navigation/structure variable `is_parent` doesn't seem to work. It is always false for root node, and only true on deeper nodes, when `is_current` is also true.

Template:

```
<ul>
    {{ nav:main_nav }}
    <li class="current-{{ if is_current }}yes{{ else }}no{{ endif }} has-children-{{ if children }}yes{{ else }}no{{ endif }} is-parent-{{ if is_parent }}yes{{ else }}no{{ endif }}">
        <a href="{{ url }}">{{ title }}</a>
        {{ if children }}
            <ul>{{ *recursive children* }}</ul>
        {{ /if }}
    </li>
    {{ /nav:main_nav }}
</ul>
```

Data:
```
title: Main
collections:
  - pages
tree:
  -
    entry: 07e22957-6530-41ad-b71c-01b14592e066
    children:
      -
        entry: 903a6ccb-fe52-415f-92d4-d7484697c52f
        children:
          -
            entry: 08d8bca9-2307-414b-ba00-dbe5e33cbc4b
```

I'm on beta.28
