### ISSUE TITLE
Custom publish form with custom relationship field saves as array

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1857]
## Bug Description

I have a custom publish form and the blueprint has a custom relationship field in a grid, set to `max_items: 1`. However when the data is saved, the relationship field is saved as an array.

## How to Reproduce

Blueprint:
```
title: Charge
sections:
  main:
    display: Main
    fields:
      -
        handle: subscription
        field:
          type: section
          localizable: false
          listable: hidden
          display: Subscription
      -
        handle: roles-and-plans
        field:
          fields:
            -
              handle: role
              field:
                input_type: text
                type: text
                localizable: false
                width: 50
                listable: hidden
                display: Role
            -
              handle: plan
              field:
                max_items: 1
                mode: select
                type: plans
                localizable: false
                width: 50
                listable: hidden
                display: Plan
          mode: table
          reorderable: false
          type: grid
          localizable: false
          listable: hidden
          display: 'Roles and Plans'
      -
```

When saved I get:
```
        'roles-and-plans' => [
            [
                'role' => 'asdf',
                'plan' => [
                    'charge-test-monthly-10-FtOuYKqH7A',
                ],
                '_id' => 'kaj5696h',
            ],
        ],
```

Note the extra `_id` as well.
## Environment

**Statamic version:** 3.0.0-beta-28

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`
