### ISSUE TITLE
Publish Form saves Sections

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1860]
## Bug Description

Publish form is saving sections in the data.

## How to Reproduce

Create a blueprint with a section (or two)
Create a publish form that uses that data.
Save the data

## Extra Detail

Blueprint:
```
title: Charge
sections:
  main:
    display: Main
    fields:
      -
        handle: subscription
        field:
          type: section
          localizable: false
          listable: hidden
          display: Subscription
      -
        handle: roles-and-plans
        field:
          fields:
            -
              handle: role
              field:
                input_type: text
                type: text
                localizable: false
                width: 50
                listable: hidden
                display: Role
            -
              handle: plan
              field:
                max_items: 1
                mode: select
                type: plans
                localizable: false
                width: 50
                listable: hidden
                display: Plan
          mode: table
          reorderable: false
          type: grid
          localizable: false
          listable: hidden
          display: 'Roles and Plans'
      -
        handle: email
        field:
          type: section
          localizable: false
          listable: hidden
          display: EMAIL
      -
        handle: from
        field:
          input_type: text
          type: text
          localizable: false
          listable: hidden
          display: 'From Email'
      -
        handle: one_time
        field:
          type: section
          localizable: false
          listable: hidden
          display: 'One Time'
      -
        handle: payment_template
        field:
          hide_partials: true
          type: template
          localizable: false
          listable: hidden
          display: 'Payment Template'
      -
        handle: payment_subject
        field:
          input_type: text
          type: text
          localizable: false
          listable: hidden
          display: 'Payment Subject'
```

Data saved:
```
    "subscription": null,
    "roles-and-plans": [
        {
            "role": "asdf",
            "plan": "charge-test-monthly-10-FtOuYKqH7A"
        }
    ],
    "email": null,
    "from": "test@email.com",
    "one_time": null,
    "payment_template": "auth\/login",
    "payment_subject": "kjh"
```

## Environment

**Statamic version:** 3.0.0-beta-28

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Starter kit
- Existing Laravel app
- Other (please explain this magic!)
