### ISSUE TITLE
Custom relationship not getting loaded into Publish Form

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1862]
**This very well might be user error, but I believe I've followed the instructions.**

## Bug Description

I have a custom publish form, that uses a custom relationship field. The data saves down correctly but does not reload properly.

## How to Reproduce

View custom publish form (below).
Set a Role/Plan combination.
Save
Reload page.

## Extra Detail

Blueprint:
```
title: Charge
sections:
  main:
    display: Main
    fields:
      -
        handle: subscription
        field:
          type: section
          localizable: false
          listable: hidden
          display: Subscription
      -
        handle: roles-and-plans
        field:
          fields:
            -
              handle: role
              field:
                input_type: text
                type: text
                localizable: false
                width: 50
                listable: hidden
                display: Role
            -
              handle: plan
              field:
                max_items: 1
                mode: select
                type: plans
                localizable: false
                width: 50
                listable: hidden
                display: Plan
          mode: table
          reorderable: false
          type: grid
          localizable: false
          listable: hidden
          display: 'Roles and Plans'
      -
        handle: email
        field:
          type: section
          localizable: false
          listable: hidden
          display: EMAIL
      -
        handle: from
        field:
          input_type: text
          type: text
          localizable: false
          listable: hidden
          display: 'From Email'
      -
        handle: one_time
        field:
          type: section
          localizable: false
          listable: hidden
          display: 'One Time'
      -
        handle: payment_template
        field:
          hide_partials: true
          type: template
          localizable: false
          listable: hidden
          display: 'Payment Template'
      -
        handle: payment_subject
        field:
          input_type: text
          type: text
          localizable: false
          listable: hidden
          display: 'Payment Subject'
```

Relationship:
```
<?php

namespace Silentz\Charge\Fieldtypes;

use Statamic\Fieldtypes\Relationship;
use Statamic\Support\Arr;
use Stripe\Plan;
use Stripe\Stripe;

class Plans extends Relationship
{
    protected $canCreate = false;
    protected $canSearch = false;

    public function __construct()
    {
        Stripe::setApiKey(config('cashier.secret'));
    }

    public function getIndexItems($request)
    {
        return collect(Arr::get(Plan::all(), 'data', []))->map(function ($plan, $ignored) {
            return [
                'id' => $plan->id,
                'title' => $plan->nickname,
            ];
        })->all();
    }

    protected function toItemArray($id)
    {
        return Plan::retrieve($id)->toArray();
    }
}
```

Saved data:

```
return [
    'subscription' => [
        'roles-and-plans' => [
            [
                'role' => 'asdf',
                'plan' => 'charge-test-monthly-10-FtOuYKqH7A',
            ],
        ],
    ],
```

Loading/saving the data:
```
    public function edit(Request $request)
    {
        // Get an array of values from the item that you want to be populated
        // in the form. eg. ['title' => 'My Product', 'slug' => 'my-product']
        $values = $this->formatConfigIntoBlueprint(config('charge'));

        // Get a blueprint. This might come from an actual blueprint yaml file
        // or even defined in this class. Read more about blueprints below.

        /** @var Blueprint */
        $blueprint = BlueprintAPI::find('charge');

        // Get a Fields object, a representation of the fields in a blueprint
        // that factors in imported fieldsets, config overrides, etc.
        $fields = $blueprint->fields();

        // Add the values to the object. This will let you do things like
        // validation, and processing, which is about to happen.
        $fields = $fields->addValues($values);

        // Pre-process the values. This will convert the raw values into values
        // that the corresponding fieldtype vue components will be expecting.
        $fields = $fields->preProcess();

        // You'll probably prefer chaining all of that.
        // $fields = $blueprint->fields()->addValues($values)->preProcess();

        // The vue component will need these three values at a minimum.
        return view('charge::cp.settings', [
            'blueprint' => $blueprint->toPublishArray(),
            'values'    => $fields->values(),
            'meta'      => $fields->meta(),
        ]);
    }

    public function update(Request $request)
    {
        /** @var Blueprint */
        $blueprint = BlueprintAPI::find('charge');

        // Get a Fields object, and populate it with the submitted values.
        $fields = $blueprint->fields()->addValues($request->all());

        // Perform validation. Like Laravel's standard validation, if it fails,
        // a 422 response will be sent back with all the validation errors.
        $fields->validate();

        // Perform post-processing. This will convert values the Vue components
        // were using into values suitable for putting into storage.
        $values = $fields->process()->values();

        Log::info(json_encode($values, JSON_PRETTY_PRINT));
        $this->configurator->set(
            'subscription',
            [
                'roles-and-plans' => Arr::get($values, 'roles-and-plans', []),
            ]
        );
        $this->configurator->set('email', Arr::except($values, 'roles-and-plans'));
        $this->configurator->refresh();

        return back();
    }

    private function formatConfigIntoBlueprint(array $config)
    {
        $rolesAndPlans = collect(Arr::get($config, 'subscription.roles-and-plans'))
            ->map(function ($rolePlan, $key) {
                return [
                    'role' => $rolePlan['role'],
                    'plan'=> Arr::wrap($rolePlan['plan']),
                ];
            });

        return ['roles-and-plans'=> $rolesAndPlans];
    }
```

## Environment

**Statamic version:** 3.0.0-beta-28

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`
