### ISSUE TITLE
Date Field Not Saving

### ISSUE THREAD

**Issue by johncarter-** [statamic/cms#1867]
## Bug Description
When you save a date using the date field type the date is not saved to the entry.

## How to Reproduce
- Install a fresh Statamic site
- Add a date field to the default blueprint with the following settings
```yaml
      -
        handle: date
        field:
          mode: single
          time_enabled: false
          time_required: false
          earliest_date: '1900-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          type: date
          localizable: false
          listable: hidden
          display: Date
```
- Edit an entry and update the date to a date in the future. 
- Save the entry
- Check the content `.md` file and see the data not present

## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.2

**OS:** Windows 10

**Install method:** Fresh install from `statamic/statamic`
