### ISSUE TITLE
Asset Tag not working

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1906]
The Asset tag seems not to work as written in the docs: 

https://statamic.dev/tags/asset

```html
{{ asset url="/img/brand/logo.png" }}
  <img src="{{ url }}" alt="{{ alt }}">
{{ /asset }}
```

The output is just empty. I wanted to use it as the equivalent to the blade asset. 

**Statamic version:** 3.0.0.-beta-29

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by Konafets** [comment]
Do you want to use the asset tag inside a Blade template?

**Comment by jonassiewertsen** [comment]
No. I did try to use it inside an antlers template. 

This is how it's often done in blade `{{ asset('path/image.jpg' }}`

Inside Antlers I did try to use `{{ asset url="path/image.jpg' }} ``

But I am not sure if those are expected to work the same way ...

**Comment by jackmcdade** [comment]
Is the asset in an asset container?

**Comment by mikemartin** [comment]
I'm experiencing a related asset tag issue. This shorthand for glide is no longer working:

```
<img class="rounded-full h-20 xl:h-24 w-20 xl:w-24" src="{{ glide:avatar square='200' fit='crop_focal' }}"/>
```

But this still works:
```
{{ asset:avatar }}
    <img class="rounded-full h-20 xl:h-24 w-20 xl:w-24" src="{{ glide:url square='200' fit='crop_focal' }}"/>
{{ /asset:avatar}}
```

Fieldset:
```
handle: avatar
        field:
          type: assets
          max_files: 1
          container: assets
          folder: avatars
          display: Avatar
          listable: hidden
          mode: grid
          restrict: false
          allow_uploads: true
```

Content:
```
avatar: brand/jason-resnick-rezzz-psw.jpg
```
