### ISSUE TITLE
Upload file field allows multiple files to upload when set to max_files: 1

### ISSUE THREAD

**Issue by jeremydouglas** [statamic/cms#1955]
## Bug Description

By clicking on the 'Upload file' link on an asset field, multiple files can be uploaded, even when the field is set to `max_files: 1`

## How to Reproduce
Create a field such as:
```
handle: hero_image
field:
  type: assets
  display: Image
  container: assets
  folder: gallery
  max_files: 1
```
In the cp, click on 'Upload file' and select multiple files.

## Extra Detail
<img width="334" alt="Screen Shot 2020-06-19 at 3 55 51 PM" src="https://user-images.githubusercontent.com/113216/85175580-c244d580-b245-11ea-914b-a22ded36ef05.png">

## Environment

**Statamic version:** 3.0.0.-beta-31

**PHP version:** 7.4

**Install method (choose one):**
- Existing Laravel app
