### ISSUE TITLE
Image validation fails

### ISSUE THREAD

**Issue by jdsimcoe** [statamic/cms#1956]
## Bug Description
I have an asset field called `image` that has `validate: image` set. When I go to create a blog entry and try to save, I get an invalidation error even though the image is a valid `.jpg` image.

## How to Reproduce
- Create a Blog Collection
- Create a Blog Blueprint with an Image and Bard Field (see below)
- Mount the Blog Blueprint to Blog Collection
- Create new Blog entry
- Add an valid `.jpg` image to a valid `Assets` container
- Watch image invalidate

```yaml
title: Blog
sections:
  main:
    display: Main
    fields:
      -
        handle: image
        field:
          mode: grid
          container: assets
          restrict: false
          allow_uploads: true
          max_files: 1
          type: assets
          localizable: false
          listable: hidden
          display: Image
          validate: image
      -
        handle: bard
        field:
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
          container: assets
          save_html: false
          toolbar_mode: fixed
          link_noopener: true
          link_noreferrer: true
          target_blank: true
          reading_time: true
          fullscreen: true
          allow_source: true
          type: bard
          localizable: false
          listable: hidden
          display: Bard

```

## Extra Detail
![image](https://user-images.githubusercontent.com/275617/85178243-ddf2b080-b232-11ea-8749-829bdf21c895.png)

## Environment

**Statamic version:** 3.0.0.-beta.31
**PHP version:** 7.4.6
**Install method (choose one):** Fresh install from `statamic/statamic`
