### ISSUE TITLE
Can't limit a taxonomy field's choices to a single taxonomy via CP

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/cms#1980]
## Bug Description
When creating a blueprint in the CP, if you limit choices to a taxonomy, the saved YAML looks like:

```yaml
-
  handle: ingredient
  field:
    type: taxonomy
    taxonomy:
      - ingredients
    max_items: 1
    mode: select
    localizable: false
    listable: hidden
    display: Ingredient
```

instead of:

```yaml
-
  handle: ingredient
  field:
    type: taxonomy
    taxonomy: ingredients
    max_items: 1
    mode: select
    localizable: false
    listable: hidden
    display: Ingredient
```

## Extra Detail
![image](https://user-images.githubusercontent.com/468029/85638371-56021180-b64b-11ea-9571-34e6e484f255.png)

## Environment

**Statamic version:** v3.0.0-beta.31

**PHP version:** 7.4.6

**Install method (choose one):**
- Fresh install from `statamic/statamic`
