### ISSUE TITLE
Setting 'enabled: false' on the first set in a replicator causes error 

### ISSUE THREAD

**Issue by studio1902** [statamic/cms#2006]
## Bug Description
Setting enabled: false on the first set in a replicator with multiple sets causes an error `View ... not found`.

## How to Reproduce
1. Add a replicator to your current fieldset. 
2. Give the replicator at least one set of fields.
3. Edit the page the replicator is on and add at least two sets to the replicator.
4. Switch off the output toggle of the first set so that `enabled` get's set to `false`.

## Extra Detail
The front matter for your replicator should look something like this:
```
replicator:
  -
    bard: null
    type: article
    enabled: false
  -
    bard: null
    type: article
    enabled: true
```

The error:
<img width="1563" alt="Screenshot 2020-06-30 at 12 27 13" src="https://user-images.githubusercontent.com/4067523/86116007-0d27de00-bacd-11ea-89c0-f900713e0ec2.png">

## Environment

**Statamic version:** 3.0.0.-beta-33

**PHP version:** 7.4.6

**Install method (choose one):**
- Fresh install from `statamic/statamic`
