### ISSUE TITLE
Templating issue - Asset isn't outputted correctly

### ISSUE THREAD

**Issue by padders** [statamic/cms#2060]
#1740  Bug Description
I have a partial template, that when I add it to a bard section works as expected. It has an asset tag and using that tag outputs the image location correctly. 

The partial html is:
`<img src="{{image}}" alt="{{leading_caption}}" class="mb-0">`

and it's associated field in the yaml is
```
title: 'Image - Centered with caption'
fields:
  -
    handle: image
    field:
      mode: grid
      container: assets
      restrict: false
      allow_uploads: true
      max_files: 1
      type: assets
      localizable: false
      listable: hidden
      display: image
```

I have another partial, with 2 columns. The second column has a replicator in it that we can add sets to. I have an almost identical partial to the one above that allows us to put an image with a caption into a column, however the asset tag in this one doesn't work. I wonder if it's something to do with folder locations for my partials

The partial html is the same
`<img src="{{ image }}" alt="{{ leading_caption }}" class="mb-0">`

and the yaml is very similar
```
title: 'Column - Image with caption'
fields:
  -
    handle: image
    field:
      mode: grid
      container: assets
      folder: img
      restrict: true
      allow_uploads: true
      max_files: 1
      type: assets
      localizable: false
      listable: hidden
      display: image
```

The partial that loads the column looks like this
```
{{ 2nd_column_content }}
      {{ partial src="partials/columns/{type}" }}
{{ /2nd_column_content}}
```

The other fields in the partial output correctly, but the asset tag doesn't work. I have noticed it's saving it slightly differently in the page.md file

In the working partial when added to a bard it saves this
```
-
    type: set
    attrs:
      values:
        type: image_-_centered_with_caption
        image: img/avocado.png
        leading_caption: 'Mr Avocado'
        handwritten_caption: 'He''s Shocked. SHOCKED I TELL YOU!'
```

in the partial in the replicator column it saves like this. The image is saved as an array in this one
```
2nd_column_content:
          -
            image:
              - 'assets::img/avocado.png'
            leading_caption: 'Mr Avocado'
            handwritten_caption: 'He''s Shocked. SHOCKED I TELL YOU!'
            type: column_image_caption
            enabled: true
```
the broken partial just outputs the following html `<img src="" alt="Mr Avocado" class="mb-0">`

If I use `{{ image:0 }}` in the template i get the following outputted as the src field `assets::img/avocado.png` 

The working partial outputs `<img src="/assets/img/avocado.png" alt="Avocado" class="mb-0">`

My partials for the column are in a subfolder partials/columns but the containing replicator field points them at that. The working partial is in the partials folder.

## Environment

**Statamic version:** v3.0.0-beta.35

**PHP version:** 7.4.4

**Install method (choose one):**
- Starter kit - cool writings
