### ISSUE TITLE
Bard input outputting an empty text value 

### ISSUE THREAD

**Issue by timdonaldson** [statamic/cms#2077]
I'm running into a bug with a bard input that is outputting an empty text value which is breaking the site:

The output value (error is at line 22):

```
project_description:
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: link
            attrs:
              href: 'http://canvas.ws/about?page=about-ci'
              target: _blank
              rel: null
        text: 'NPO法人 CANVAS'
      -
        type: text
        text: 'のCIリニューアルをプロデュースしました。「未来をつくるお道具箱」というコンセプトのもと、道具としてデザインされた様々なエレメントで構成されたCI システムです。お道具箱に収められた道具や素材モチーフは、丸・三角・四角の基本図形と、赤・青・黄の三原色で構成されています。それらを組み合わせることで、様々なロゴタイプやイメージをつくることができます。使い手の創造力に委ねた自由で遊び心のあるCIシステムが生まれました。'
      -
        type: hard_break
      -
        type: text
        text: 　<====== ERROR IS HERE
      -
        type: hard_break
      -
        type: text
        marks:
          -
            type: link
            attrs:
              href: 'https://youtu.be/jiGjtOMF84I'
              target: _blank
              rel: null
        text: 'CANVAS New CI コンセプトムービー'
---------------------------
```

The error reads: 

**Invalid YAML
Correct any syntax errors. You may have used YAML 1.0 syntax, but 1.2 is expected.**

And my client only runs into this error when inputing Japanese content it seems
