### ISSUE TITLE
Collection column madness!

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2116]
## Bug Description
The columns in the collection overview are going crazy! Didn't notice this before beta-38.

## How to Reproduce
Create a new collection and add a huge blueprint to it.

## Extra Detail
<img width="1917" alt="Bildschirmfoto 2020-07-21 um 21 43 20" src="https://user-images.githubusercontent.com/23167701/88099420-6ef2d980-cb9b-11ea-83dd-e1843e3e7cbc.png">

## Environment

**Statamic version:** 3.0.0.-beta-38

**PHP version:** 7.4.6

**Install method:** Upgrade from beta-37

**Comment by aerni** [comment]
Oh, forgot to mention the `Customize Columns` dropdown. All the columns that are showing are not even in the `Displayed Columns` section. And even when adding columns, the setting will soon disappear again and the madness is back.

<img width="304" alt="Bildschirmfoto 2020-07-21 um 21 46 32" src="https://user-images.githubusercontent.com/23167701/88099656-c2652780-cb9b-11ea-981c-7711e1ac213b.png">

**Comment by jasonvarga** [comment]
What does the blueprint look like?

**Comment by aerni** [comment]
```yaml
title: 'Product New'
sections:
  basic:
    display: Basic
    fields:
      -
        handle: basic_information_section
        field:
          type: section
          instructions: 'Add the basic product information. <a href="https://docs.snipcart.com/v3/setup/products">Learn more</a>'
          localizable: false
          listable: hidden
          display: 'Basic Information'
      -
        handle: title
        field:
          type: text
          localizable: false
          listable: hidden
          display: Name
          instructions: 'The name of the product.'
          validate: required|string
          width: 33
      -
        handle: sku
        field:
          input_type: text
          type: text
          localizable: false
          listable: hidden
          display: SKU
          instructions: 'A unique product identifier.'
          validate: required
          width: 33
      -
        handle: price
        field:
          type: currency
          localizable: false
          listable: hidden
          display: Price
          instructions: 'Rounded to two decimal places.'
          validate: required|numeric
          width: 33
      -
        handle: description
        field:
          type: textarea
          localizable: false
          listable: hidden
          instructions: 'A short product description that will show in the cart.'
          display: Description
      -
        handle: images
        field:
          mode: grid
          container: assets
          restrict: false
          allow_uploads: true
          type: assets
          localizable: false
          listable: hidden
          display: Images
          instructions: 'One or more product images. The first image will show in the cart.'
  advanced:
    display: Advanced
    fields:
      -
        handle: additional_information_section
        field:
          type: section
          localizable: false
          listable: hidden
          display: 'Additional Information'
          instructions: 'Add additional product information. <a href="https://docs.snipcart.com/v3/setup/products#advanced-product-attributes">Learn more</a>'
      -
        handle: categories_new
        field:
          type: taxonomy
          taxonomy: categories_new
          display: Categories
          instructions: 'The categories of this product.'
          mode: select
      -
        handle: metadata
        field:
          type: yaml
          localizable: false
          listable: hidden
          display: Metadata
          instructions: 'Additional metadata for this product.'
      -
        handle: shipping_section
        field:
          type: section
          instructions: 'Customize the shipping behavior of the cart for this product. <a href="https://docs.snipcart.com/v3/setup/products#product-shipping">Learn more</a>'
          localizable: false
          listable: hidden
          display: Shipping
      -
        handle: shippable
        field:
          type: toggle
          instructions: 'Mark this product as `shippable`. Turn this off, if you do not ship this product.'
          localizable: false
          listable: hidden
          display: Shippable
          default: true
      -
        handle: weight_and_dimensions_section
        field:
          type: section
          instructions: 'Use these attributes if you need to offer different shipping prices depending on product dimensions. <a href="https://docs.snipcart.com/v3/setup/products#product-dimensions">Learn more</a>'
          localizable: false
          listable: hidden
          display: 'Weight & Dimensions'
      -
        handle: weight
        field:
          type: weight
          localizable: false
          listable: hidden
          display: Weight
          instructions: 'This is `mandatory` if you use any integrated shipping provider.'
      -
        handle: length
        field:
          type: length
          localizable: false
          listable: hidden
          display: Length
          instructions: 'This is `optional` if you enabled an integrated shipping provider.'
          width: 33
      -
        handle: width
        field:
          type: length
          localizable: false
          listable: hidden
          display: Width
          instructions: 'This is `optional` if you enabled an integrated shipping provider.'
          width: 33
      -
        handle: height
        field:
          type: length
          localizable: false
          listable: hidden
          display: Height
          instructions: 'This is `optional` if you enabled an integrated shipping provider.'
          width: 33
      -
        handle: taxes_section
        field:
          type: section
          localizable: false
          listable: hidden
          display: Taxes
          instructions: 'Customize how taxes will be handled for this product. <a href="https://docs.snipcart.com/v3/setup/products#product-taxes">Learn more</a>'
      -
        handle: taxable
        field:
          type: toggle
          instructions: 'Mark this product as `taxable`. Turn this off, if you want to exclude the product from the taxes calculation.'
          localizable: false
          listable: hidden
          display: Taxable
          default: true
      -
        handle: has_taxes_included
        field:
          type: toggle
          instructions: 'Turn this on, if the taxes are included in the product''s price.'
          localizable: false
          listable: hidden
          display: 'Taxes included'
      -
        handle: taxes
        field:
          type: tags
          instructions: 'Specifically define the taxes to be applied on this product.'
          localizable: false
          listable: hidden
          display: Taxes
      -
        handle: quantity_section
        field:
          type: section
          instructions: 'Customize how the product quantity can be updated. <a href="https://docs.snipcart.com/v3/setup/products#product-quantity">Learn more</a>'
          localizable: false
          listable: hidden
          display: Quantity
      -
        handle: quantity
        field:
          type: integer
          instructions: 'The default product quantity.'
          localizable: false
          listable: hidden
          display: 'Default Quantity'
          width: 33
          default: 1
      -
        handle: min_quantity
        field:
          type: integer
          instructions: 'The minimum allowed product quantity.'
          localizable: false
          listable: hidden
          display: 'Minimum Quantity'
          width: 33
      -
        handle: max_quantity
        field:
          type: integer
          instructions: 'The maximum allowed product quantity.'
          localizable: false
          listable: hidden
          display: 'Maximum Quantity'
          width: 33
      -
        handle: quantity_step
        field:
          type: integer
          instructions: 'The quantity will change by this number when using the `+` and `-` buttons in the cart.'
          localizable: false
          listable: hidden
          display: 'Quantity Step'
          default: 1
      -
        handle: stackable
        field:
          options:
            auto: Auto
            never: Never
            always: Always
          default: auto
          clearable: false
          multiple: false
          searchable: false
          taggable: false
          push_tags: false
          cast_booleans: false
          type: select
          instructions: 'Customize the cart''s behaviour when adding multiple items of the same product.'
          localizable: false
          listable: hidden
          display: Stackable
      -
        handle: digital_section
        field:
          type: section
          localizable: false
          listable: hidden
          display: 'Digital Goods'
          instructions: 'Sell a link to a digital good. Remember to upload the file in Snipcart''s dashboard. <a href="https://docs.snipcart.com/v3/setup/products#digital-goods">Learn more</a>'
      -
        handle: file_guid
        field:
          input_type: text
          type: text
          instructions: 'The file GUID of the digital good.'
          localizable: false
          listable: hidden
          display: 'File GUID'
  custom_fields:
    display: Custom
    fields:
      -
        handle: custom_fields
        field:
          sets:
            dropdown:
              display: Dropdown
              fields:
                -
                  handle: name
                  field:
                    input_type: text
                    type: text
                    instructions: 'Name the dropdown, e.g. `Color` or `Size`.'
                    localizable: false
                    listable: hidden
                    display: Name
                    validate: required
                -
                  handle: options
                  field:
                    fields:
                      -
                        handle: name
                        field:
                          input_type: text
                          type: text
                          instructions: 'The name of this option, e.g. `Black` or `White`.'
                          localizable: false
                          listable: hidden
                          display: Name
                          validate: required
                      -
                        handle: price
                        field:
                          type: currency
                          instructions: 'You may define a different price for this product option.'
                          localizable: false
                          listable: hidden
                          display: Price
                          validate: numeric
                    mode: table
                    reorderable: true
                    type: grid
                    localizable: false
                    listable: hidden
                    display: Options
                    instructions: 'The first option will be the default.'
                    add_row: 'Add Option'
                    replicator_preview: false
                    validate: required
                    min_rows: 2
            checkbox:
              display: Checkbox
              fields:
                -
                  handle: name
                  field:
                    input_type: text
                    type: text
                    instructions: 'Name the checkbox, e.g. `Gift`.'
                    localizable: false
                    listable: hidden
                    display: Name
                    validate: required
            text:
              display: 'Text / Textarea'
              fields:
                -
                  handle: field_type
                  field:
                    options:
                      text: Text
                      textarea: Textarea
                    type: button_group
                    localizable: false
                    listable: hidden
                    display: Type
                    instructions: 'Choose the type of the text field. A `textarea` is great for longer messages.'
                    validate: required
                    replicator_preview: false
                    default: text
                -
                  handle: name
                  field:
                    input_type: text
                    type: text
                    instructions: 'Name the text field, e.g. `Gift note` or `Message`.'
                    localizable: false
                    listable: hidden
                    display: Name
                    validate: required
                -
                  handle: placeholder
                  field:
                    input_type: text
                    type: text
                    instructions: 'Define an optional placeholder.'
                    localizable: false
                    listable: hidden
                    display: Placeholder
                    replicator_preview: false
                -
                  handle: default
                  field:
                    input_type: text
                    type: text
                    instructions: 'Define an optional default value.'
                    localizable: false
                    listable: hidden
                    display: Default
                    replicator_preview: false
                -
                  handle: required
                  field:
                    type: toggle
                    instructions: 'Make this field required.'
                    localizable: false
                    listable: hidden
                    display: Required
                    replicator_preview: false
          type: replicator
          localizable: false
          listable: hidden
          display: 'CUSTOM FIELDS'
          instructions: 'Define product variations for things like `color` and `size` or collect additional information like a `gift note`. <a href="https://docs.snipcart.com/v3/setup/products#custom-fields">Learn more</a>'
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          generate: true
          type: slug
          instructions: 'The slug of the product.'
          localizable: false
          listable: hidden
          display: Slug
      -
        handle: is_snipcart_product
        field:
          type: hidden

```
