### ISSUE TITLE
HTML Email setting on contact form causing an error

### ISSUE THREAD

**Issue by MikeHarrison** [statamic/cms#2131]
## Bug Description
When I set an HTML View for an email generated by a contact form, I see an "Invalid View" error when the form is submitted, and the email is not sent

## How to Reproduce

1. Create a new html email template at `resources/views/emails/contact.antlers.html`
2. Select this as the HTML email view in the CP
3. Submit the form

## Extra Detail
This is my `contact_form.yaml`, the view appears in there ok when updated in the cp:

```
title: Contact
email:
  -
    to: '{{ email_address }}'
    from: stay@shelveholidays.co.uk
    reply_to: stay@shelveholidays.co.uk
    subject: 'Thank you for your message'
    automagic: true
    html: emails/contact
  -
    to: stay@shelveholidays.co.uk
    from: noreply@shelveholidays.co.uk
    reply_to: '{{ email_address }}'
    subject: 'New Contact Form Submission from Shelve Holidays Website'
    automagic: true
    html: emails/contact
```
This is the error I see on form submission:

![Screenshot_2020-07-25 🧨 Invalid view ](https://user-images.githubusercontent.com/6464063/88457051-401a8300-ce7b-11ea-9a25-01d16f470ef4.png)

## Environment

**Statamic version:**  3.0.0-beta.40

**PHP version:** 7.2.1

**Install method (choose one):**
Fresh install from `statamic/statamic`
