### ISSUE TITLE
Noparse issue with markdown fields

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#2161]
## Bug Description

I have a markdown field with the following contents:

```
{{ color.label }}
```

This is what gets output when I dump the field in my templates:

```
<p>noparse_56c56f2a2936bb9da06452fbd043aec8</p>
```

The final html however is just

```
<p></p>
```

Seems like the `{{ color.label }}` is somehow being parsed.

## Environment

**Statamic version:** 3.0.0.-beta-41

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Are you using vue or something similar on the frontend?

Is that <p> empty in the actual rendered source?

**Comment by riasvdv** [comment]
So this is the field:

![image](https://user-images.githubusercontent.com/3626559/89040464-20380300-d344-11ea-88c1-8ce061d37b74.png)

This is what's rendered

![image](https://user-images.githubusercontent.com/3626559/89040526-35149680-d344-11ea-9ab1-caf091b50f02.png)


When I `| dump` the markdown, this is shown

![image](https://user-images.githubusercontent.com/3626559/89040559-4493df80-d344-11ea-96c2-f1ce803ff094.png)

Just using a normal antlers partial

**Comment by riasvdv** [comment]
It's a set inside a Bard though, if that maybe helps

**Comment by jasonvarga** [comment]
Can you confirm that you are looking at the rendered html output (using "view source") rather than devtools?

**Comment by riasvdv** [comment]
View source also has an empty <p>

![image](https://user-images.githubusercontent.com/3626559/89041369-87a28280-d345-11ea-94d5-2eba3d133f2d.png)

**Comment by riasvdv** [comment]
Ah no, sorry, it's just an empty div

![image](https://user-images.githubusercontent.com/3626559/89041514-cafcf100-d345-11ea-8ab7-3f03d439997e.png)

The `<p></p>` is from Bard

**Comment by jasonvarga** [comment]
So it's correct?

**Comment by riasvdv** [comment]
No, when I type `{{ color.label }}` inside a markdown field, I expect to see this html:

```
<div class="max-w-3xl mx-auto my-8">
    {{ color.label }}
</div>
```

It shouldn't try to parse what I type inside the markdown field

**Comment by jasonvarga** [comment]
Yeah ok sorry haven't finished my coffee. 😅 

If you have some other text in the markdown field, you see that, right? Just not the `{{ color.label }}` part?

**Comment by riasvdv** [comment]
Yes

![image](https://user-images.githubusercontent.com/3626559/89042747-b4579980-d347-11ea-9c93-a1ffcc829ee3.png)

Result:

![image](https://user-images.githubusercontent.com/3626559/89042756-b91c4d80-d347-11ea-9aa7-5f8717aabecb.png)

**Comment by jasonvarga** [comment]
Can you paste the yaml for that field in your blueprint?

**Comment by riasvdv** [comment]
Sure, it's just the default Markdown one inside a Bard set

```
markdown:
              display: Markdown
              fields:
                -
                  handle: markdown
                  field:
                    restrict: false
                    automatic_line_breaks: true
                    automatic_links: false
                    escape_markup: false
                    smartypants: false
                    type: markdown
                    localizable: false
                    listable: hidden
                    display: Markdown
```
