### ISSUE TITLE
Taxonomy content field only works in the yaml header.

### ISSUE THREAD

**Issue by tao** [statamic/cms#2164]
## Bug Description
I would like to know if there's any specific reason, or if this is a bug, or if by design that the markdown content field in taxonomies only works as a yaml header. It seems inconsistent with how collections are designed to work.

For example, in my project I want to include content on each taxonomy that could even be an article explaining the taxonomy tag in depth, so when they click on the taxonomy they can see the full taxonomy tag description/article plus any collection entries associated with it.

The normal way I've been working with collections has been:
``` yaml
title: "Lorem Ipsum"
updated_at: "123456"
updated_by: author-id
---
Lorem ipsum dolor sit amet, consectetur adipiscing elit...
```

In taxonomies it doesn't work the same way?

``` yaml
title: "Lorem Ipsum"
updated_at: "123456"
updated_by: author-id
content: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit...
```

This seems a bit strange and I'd prefer my content not to be in the yaml header so that it's easier to edit and read in the future, or edit on GitHub. Is this by design?

If I want to link content or an article to a taxonomy would I need to create a new collection type with a 1:1 relationship to my taxonomy? It seems messy if I have 100+ tags.

```taxonomy:kenya <-> collection:article:kenya```

## Environment

**Statamic version:** 3.0.0.-beta-41
