### ISSUE TITLE
Ampersand_list modifier no longer works with taxonomy tags

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#2177]
## Bug Description

I'm migrating a v2 site where I had been using `{{ tags|ampersand_list }}` a lot. It seems to no longer work and outputs `[{},{},{},{},{}]` instead.

Blueprint field:
```
-
        handle: tags
        field:
          type: taxonomy
          taxonomy: tags
          display: Tags
          mode: select
```

Template:
```
      <div class="w-full md:w-1/2 pb-10 sm:pb-0 px-3">
        <h1 class="text-4xl mb-3"><a href="{{ url }}" class="text-white">{{ title }}</a></h1>
        <p class="text-lg sm:text-xl uppercase font-bold text-gold-600 tracking-wider leading-normal mb-4">{{ tags|ampersand_list }}</p>
        <div class="text-xl leading-normal sm:text-2xl mb-6">{{ content }}</div>
        <a href="{{ url }}" class="border-b border-gold-600 text-gold-600 hover:border-white uppercase font-bold inline-block py-1 mb-3">See Project</a>
      </div>
```

Content:

```
---
title: Chameleon
subtitle: 'Helping teams build better user-onboarding'
website: 'http://www.trychameleon.com'
tags:
  - design
  - user-experience
  - css
  - statamic
```
