### ISSUE TITLE
Fieldset Fields not kept in sync

### ISSUE THREAD

**Issue by davidwarrington** [statamic/cms#2183]
## Bug Description
It looks like this is probably related to #2157.

When applying a fieldset field to a blueprint, updates to the field are not kept in sync. The settings for the field are copied into the blueprint `yaml` file, like so:

```yaml
sections:
  main:
    display: Main
    fields:
      -
        handle: colour
        field: colours.colour
        config:
          options:
            red: Red
            blue: Blue
            yellow: Yellow
``` 

Getting rid of the `config` key, so I'm just left with the following appears to fix the issue for now:
```yaml
sections:
  main:
    display: Main
    fields:
      -
        handle: colour
        field: colours.colour
```

## How to Reproduce
1. Create a fieldset with a `select` field and three options
2. Create a blueprint which references the field you've just created with `Link Existing > Link a single field`
3. Create an entry in a collection that uses the blueprint you created in step 2
4. Update the field you created in step 1 by adding an extra option
5. Edit the entry you created in step 3 and you should see that the options haven't updated

## Environment

**Statamic version:** 3.0.0-beta-43

**PHP version:** 7.4.8

**Install method:**
- Fresh install from `statamic/statamic`
