### ISSUE TITLE
Multiple fieldset imports in a single blueprint broke somewhere between beta.34 and beta.43

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/cms#2194]
## Bug Description
Importing the same fieldset multiple times in a blueprint (with prefixes) no longer works. Only the first will appear.

It appears that b/c Statamic no longer recognizes the fields, augmentation doesn't work with my existing content, which means, even though my image fields' values are still in the content, the images no longer render.

## How to Reproduce
Create a fieldset, and import it multiple times into the same blueprint with unique prefixes.

## Extra Detail
Blueprint excerpt:

```yaml
-
  import: featured_case_study
  prefix: featured_research_case_study_
-
  import: featured_case_study
  prefix: featured_design_case_study_
-
  import: featured_case_study
  prefix: featured_build_case_study_
```

Fieldset:

```yaml
title: 'Featured Case Study'
fields:
  -
    handle: heading
    field:
      input_type: text
      type: text
      localizable: false
      listable: hidden
      display: Heading
      width: 50
  -
    handle: description
    field:
      type: textarea
      localizable: false
      listable: hidden
      display: Description
      width: 50
  -
    handle: image
    field:
      mode: grid
      container: images
      folder: work-samples
      restrict: true
      allow_uploads: true
      max_files: 1
      type: assets
      localizable: false
      listable: hidden
      display: Image
      width: 50
  -
    handle: link
    field:
      max_items: 1
      mode: default
      collections:
        - case_studies
      type: entries
      localizable: false
      listable: hidden
      display: Link
      width: 50
```

## Environment

**Statamic version:** 3.0.0.-beta.43

**PHP version:** 7.4.7

**Install method (choose one):**
- Fresh install from `statamic/statamic`
