### ISSUE TITLE
Blueprints not synced with fieldset updates

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#2198]
## Bug Description
Blueprints not synced with fieldset updates

## How to Reproduce
Create collection A and B
Create a blueprint X
Create a replicator fieldset (Y) , attach some fields.
Import this fieldset Y into blueprint X.
Attach blueprint X to collection A and B. These now have access to all fields in the replicator fieldset.
Go to the fieldset, add a new set to the replicator.
That set is **not** available unless you first go to each collection blueprint for A and B, remove the fieldset you have shared and then attach it again. When sharing among many different blueprints, this becomes problematic rather quickly.

## Environment

**Statamic version:** 3.0.0.-beta-43

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Please provide the contents of the blueprint’s yaml file.

**Comment by Pixney-William** [comment]
will do, just have to verify its still an issue on 43. just became unsure.

**Comment by davidwarrington** [comment]
Sounds like #2183 might be related to this issue?

**Comment by edalzell** [comment]
I'm encountering this, here are my blueprint and fieldsets:

Blueprint:
```
title: Post
sections:
  main:
    display: Main
    fields:
      -
        import: post_content
```

`post_content.yaml`:
```
title: 'Post Content'
fields:
  -
    handle: post_content
    field:
      sets:
        carousel:
          display: Carousel
          fields:
            -
              import: block_carousel
              replicator_preview: false
```
