### ISSUE TITLE
Confusing syntax for where modifier with a true/false value

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/cms#2208]
# Bug Description
When using the where modifier searching for a value created by a toggle (true or false) does not work as a condition.

## How to Reproduce
For Example, this does not work:
```
{{ grid_field where="enabled:true" }}
```

However, this does:
```
{{ grid_field }} {{ if enabled }}
```

And so does this:
```
{{ grid_field where="title:Title" }}
```

The data looks like:

```
title: Title
data:
  grid_field:
    -
      title: Title
      enabled: true
      ...
```

## Environment

**Statamic version:** 3.0.0.-beta-43

**PHP version:** 7.2.30

**Install method (choose one):**
- Fresh install from `statamic/statamic`
