### ISSUE TITLE
Keys on Select Field Not Saved when a Key is `0`

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/cms#2215]
## Bug Description
Labeled value (from select fieldtype inside a grid) has no key value.

I would expect that the key would be accessible as `{{ field:key }}`

```
Statamic\Fields\LabeledValue {#2317 ▼
  #value: "Thursday"
  #label: "Thursday"
}
```

## How to Reproduce
Try to get the key value from a select fieldtype.

## Environment

**Statamic version:** 3.0.0.-beta-43

**PHP version:** 7.2.30

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by twd3** [comment]
Might be duplicate of : https://github.com/statamic/cms/issues/2066

**Comment by jasonvarga** [comment]
Did you try `{{ field }}`?

**Comment by jcohlmeyer** [comment]
That also prints the label, not the key.

**Comment by jasonvarga** [comment]
Looks like your label and key are the same though. What's in the blueprint file?

**Comment by jcohlmeyer** [comment]
My blueprint looks like this:
```
            -
              handle: day_to_show
              field:
                options:
                  - Sunday
                  - Monday
                  - Tuesday
                  - Thursday
                  - Friday
                  - Saturday
                  - Sunday
                clearable: true
                multiple: false
                searchable: true
                taggable: false
                push_tags: false
                cast_booleans: false
                type: select
                localizable: false
                listable: hidden
                display: 'Day To Show'
                width: 50
```

In the CP it looks like this:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/1778271/90150039-2fab4900-dd53-11ea-83c3-3e2b4270e649.png">

In the content file it looks like this:

```
title: Site
data:
  logo: logos/TrinityLife-Logo-Complete-Yellow.svg
  notices:
    -
      title: Live
      background_colour: bg-red-600
      enabled: true
      notice: 'Gather online & watch the live stream service!'
      link: 'https://live.trinitylife.ca'
      day_to_show: Thursday
```

**Comment by jasonvarga** [comment]
Okay it's working as expected, except that options field in the CP is a bit weird.

When your values are zero indexed like that, it just saves a simple array - like you have in your YAML file.

Did you create the field through the CP or in the file?

**Comment by jcohlmeyer** [comment]
Ah. That makes sense. I created via the CP.

**Comment by jasonvarga** [comment]
Do you actually want those numbers to be the values?

I think if you start from `1` instead of `0`, it'll actually save numbers.

**Comment by jcohlmeyer** [comment]
I do as I want to compare to `{{ now | format:w }}` and not make the user enter the day of the week as 0-6...

**Comment by jcohlmeyer** [comment]
Please keep this open. Also @robdekort I do consider this a bug.

**Comment by jcohlmeyer** [comment]
> This issue has not had recent activity and has been marked as stale — by me, a robot. Simply reply to keep it open and send me away. If you do nothing, I will close it in a week. I have no feelings, so whatever you do is fine by me.

Please keep this open. Also @robdekort I do consider this a bug.

**Comment by arthurperton** [comment]
I think the only way to solve these issues (see #3179 too) is to make both the keys and the labels mandatory. Then there will be no confusion about what the user meant. 

Would that be an acceptable solution for 3.1?

**Comment by jasonvarga** [comment]
I don't think that would solve anything. In this comment https://github.com/statamic/cms/issues/2215#issuecomment-673526515 you can see that the values are all being defined anyway.

I think what might need to happen is to support an additional longer syntax for defining your options.

```yaml
options:
  - 
    label: Sunday
    value: 0
  - 
    label: Monday
    value: 1
  - 
    label: Tuesday
    value: 2
  - 
    label: Wednesday
    value: 3
  - 
    label: Thursday
    value: 4
  - 
    label: Friday
    value: 5
  - 
    label: Saturday
    value: 6
```
