### ISSUE TITLE
Getting error accessing pages collection due to Taxonomy field

### ISSUE THREAD

**Issue by sg-modlab** [statamic/cms#2235]
## Bug Description

Getting  an error when accessing my `Pages` collection. From log it is related to the following field in my home page's blueprint. Removing this from the blueprint no longer gives an error. The field was added to the blueprint via CP.

```
      -
        handle: our_services
        field:
          type: taxonomy
          max_items: 4
          taxonomy: services
          mode: default
          display: Services
          listable: true
          taxonomies:
            - services
```

## How to Reproduce

The above field definition for a taxonomy field seems to be at heart of error.

## Extra Detail
[Error Message](https://flareapp.io/share/lm2bnOmx)

Note the taxonomy field used in this blueprint for my homepage is not associated with the pages collection that my homepage is part of. It is associated with "Projects" and "Blog" collections. The terms of this taxonomy power the "Services" landing page of our studio's portfolio. We use the taxonomy field above on our home page to curate and showcase our services and offer links to their detail pages. 

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/529067/90311253-ff84b700-dec6-11ea-8561-384152edf195.png">

## Environment

* Statamic 3.0.0-beta.44 Pro
* Laravel 7.25.0
* PHP 7.3.4
* SEO Pro 2.0.5

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Recently updated via `composer update`
