### ISSUE TITLE
Unpublished entries not 404-ing

### ISSUE THREAD

**Issue by johncarter-** [statamic/cms#2239]
## Bug Description
An unpublished entry is still accessible when you are not logged in.

## How to Reproduce
Create an unpublished entry, visit the url in incognito. See the page.

## Extra Detail
Discord chat: https://discordapp.com/channels/489818810157891584/489819906540568593/744866559394316318

## Environment

Windows 10

**Statamic version:** 3.0.0-beta.44

**PHP version:** 7.4

**Install method (choose one):** Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
What does your collection yaml file look like?

**Comment by johncarter-** [comment]
I deleted my `statamic/statamic` install. But here is one from another similarly fresh install:

```yaml
title: Pages
revisions: false
route: '{parent_uri}/{slug}'
structure:
  root: true
  tree:
    -
      entry: home
    -
      entry: 81975e6c-c239-47ae-ac99-026bcff22c70
```

**Comment by damcclean** [comment]
Hmm okay. I think there's an option somewhere in the Collection's settings to choose when/if to show entries on the frontend. (I could be speaking rubbish though). I'll try to remember to have a look later on.

**Comment by ReneWeCode** [comment]
Check #2070. They are pretty much related.

**Comment by johncarter-** [comment]
> Hmm okay. I think there's an option somewhere in the Collection's settings to choose when/if to show entries on the frontend. (I could be speaking rubbish though). I'll try to remember to have a look later on.

Even if there is, this shouldn't be default behaviour right?

**Comment by ReneWeCode** [comment]
I would say this, and the related issues are qualifying for a 3.0.0-final label 🤔

**Comment by jasonvarga** [comment]
I can't reproduce this. Any other details you can provide? What does the collection's yaml file look like? What's the filename of the unpublished entry? What's inside the md file?

**Comment by johncarter-** [comment]
Give me a minute. I'll spin up a statamic/statamic again.

**Comment by jasonvarga** [comment]
Ah looks like its when its a collection with a structure, like `pages`.

**Comment by johncarter-** [comment]
- Fresh `git clone https://github.com/statamic/statamic` and `composer install`.
- Create a super user from CLI.
- Login to /cp
- Create new page entry with whatever content 
- Toggle "Published" to off and Save.
- Open "Visit URL" in incognito
- See page content 

Using **Windows 10** locally, but happens on my Forge deployed sites too.

`content/collections/pages.yaml`:  
```yaml
title: Pages
revisions: false
route: '{parent_uri}/{slug}'
structure:
  root: true
  tree:
    -
      entry: home
    -
      entry: 6a6a13ae-d394-4fe8-9247-612b28cba473
````
And `content/collections/pages/whatever.md`:   
```
---
title: Whatever
author: c4a5cef7-5ae3-4fbf-9839-300496f2f03f
updated_by: c4a5cef7-5ae3-4fbf-9839-300496f2f03f
updated_at: 1597671339
id: 6a6a13ae-d394-4fe8-9247-612b28cba473
published: false
---
hello there.
```
