### ISSUE TITLE
E-mail templates not parsing data (tags and variables)

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2240]
## Bug Description
When using contact forms the html templates for e-mails are not parsed. Neither Antlers tags or e-mail variables get rendered:

## How to Reproduce
* Make a form
* Make an email template that contains tags and e-mail variables.

## Extra Detail
<img width="462" alt="Screenshot 2020-08-17 at 15 48 53" src="https://user-images.githubusercontent.com/69107412/90403370-2d255800-e0a1-11ea-8c4c-1bd2954f86c7.png">

## Environment

Statamic 3.0.0-beta.44 Pro
Laravel 7.25.0
PHP 7.4.6
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Can you confirm that you are using `.antlers.html` and not just `.html` files?

**Comment by robdekort** [comment]
I've tried using .antlers.html but then the form won't send. Let me try without using the Ajax method.

**Comment by jasonvarga** [comment]
You don't need to include `antlers` in the form config, if that's what you're doing. Just make sure that the file extension has it.

**Comment by robdekort** [comment]
Ok, that was indeed it it. I got a 500 error using the AJAX sending method. Without I could see that the error was regarding a modifier in the mail template. When I removed it stuff started working.

**Comment by robdekort** [comment]
Everything works except {{ message }} doesn't render anything. 

This is the forms blueprint:

```
sections:
  main:
    display: Main
    fields:
      -
        handle: name
        field:
          display: Name
          type: text
          validate: required
      -
        handle: email
        field:
          display: "E-mail address"
          type: text
          validate: required|email
      -
        handle: message
        field:
          display: Message
          type: textarea
          validate: required
```
