### ISSUE TITLE
Error when using "values" handle for grid field

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#2251]
## Bug Description

It seems that the term "values" is conflicting and cannot currently be used as a handle for the grid field.

## How to Reproduce

Template:

```
{{ values }}
...
{{ /values }}
```

Fieldset:
```
-
    handle: values
    field:
      type: grid
      display: Values
      mode: table
      fields:
        -
          handle: title
          field:
            type: text
            display: Title
        -
          handle: icon
          field:
            type: assets
            display: Icon
            container: main
            folder: parakeet
            max_files: 1
```

## Extra Detail

```
 Argument 1 passed to Statamic\Fields\Fields::addValues() must be of the type array, string given, called in /Users/mike/Sites/trychameleon/vendor/statamic/cms/src/Fieldtypes/Grid.php on line 163

  at vendor/statamic/cms/src/Fields/Fields.php:107
    103|     {
    104|         return $this->fields->values()->map->toPublishArray()->all();
    105|     }
    106| 
  > 107|     public function addValues(array $values)
    108|     {
    109|         $fields = $this->fields->map(function ($field) use ($values) {
    110|             return $field->newInstance()->setValue(array_get($values, $field->handle()));
    111|         });
```
## Environment

Statamic 3.0.0-beta.46 Pro
Laravel 7.25.0
PHP 7.4.9
statamic/migrator dev-master
statamic/ssg 0.1.0
