### ISSUE TITLE
Range field in Bard-Set not draggable

### ISSUE THREAD

**Issue by HellPat** [statamic/cms#2283]
## Bug Description

When you place a Range field into a Bard-Set Drag&Drop of the "knob" is not possible but instead the whole "set" is beeing marked active with a blue border.

## How to Reproduce

Place this in a bard and try to change the values via "knob".

![image](https://user-images.githubusercontent.com/1016798/91058399-ae906380-e628-11ea-9ba4-abd773e4f286.png)

```
title: Bilder
fields:
  -
    handle: custom_settings
    field:
      type: toggle
      instructions: 'Wenn der Standart nicht passt: (Small: 2, Medium: 4, Large: 4)'
      localizable: false
      listable: false
      display: 'Abweichendes Responsive-Verhalten'
  -
    handle: sm
    field:
      step: 1
      min: 0
      max: 2
      type: range
      localizable: false
      listable: hidden
      display: 'Kleine Geräte'
      if:
        custom_settings: 'equals true'
      width: 33
  -
    handle: md
    field:
      step: 1
      min: 0
      max: 4
      type: range
      localizable: false
      listable: hidden
      display: 'Mittlere Geräte'
      if:
        custom_settings: 'equals true'
      width: 33
  -
    handle: lg
    field:
      step: 1
      min: 0
      max: 8
      type: range
      localizable: false
      listable: hidden
      display: 'Große Geräte'
      if:
        custom_settings: 'equals true'
      width: 33
  -
    handle: images
    field:
      mode: grid
      container: assets
      folder: galerien
      restrict: true
      allow_uploads: true
      type: assets
      localizable: false
      listable: hidden
      display: Bilder
``` 

## Extra Detail

![image](https://user-images.githubusercontent.com/1016798/91058108-5f4a3300-e628-11ea-858f-36f11c443d5b.png)

## Environment

**Statamic version:** 3.0.0 @ `b9a41ffab70664c88656b2c497bf2991d1d42cec`

**PHP version:** 7.4
**Install method (choose one):**
- Starter kit
