### ISSUE TITLE
Select field not displaying in CP after upgrading to 3.0.1

### ISSUE THREAD

**Issue by johncarter-** [statamic/cms#2302]
## Bug Description
Select field type is throwing a JS error and not displaying after upgrading to 3.0.1

![image](https://user-images.githubusercontent.com/3776888/91319554-6bfb9200-e7b4-11ea-8de1-5ac132a3555a.png)

![image](https://user-images.githubusercontent.com/3776888/91319381-39519980-e7b4-11ea-85d7-df46ef9d8f05.png)

```yaml
handle: images_per_row
field:
  options:
    - 2
    - 3
    - 4
    - 5
  clearable: false
  multiple: false
  searchable: false
  taggable: false
  push_tags: false
  cast_booleans: false
  default: 4
  type: select
  listable: hidden
  display: 'Images Per Row'
```

## Environment

Statamic 3.0.1 Solo
Laravel 7.26.0
PHP 7.4.6
No addons installed
