### ISSUE TITLE
Radio-Field: Cannot read property 'fields' of undefined

### ISSUE THREAD

**Issue by psren** [statamic/cms#2312]
## Bug Description

When I add Fieldset with a `radio`-Field to a `bard` it does not work and Errors in the JS-Console with

```js
Cannot read property 'fields' of undefined
```

## How to Reproduce

When I add a `button` including an options field to a `bard`

## Extra Detail

![image](https://user-images.githubusercontent.com/1016798/91546429-b6028600-e922-11ea-814f-850047d3e727.png)

It **works** with this Fielset (`button.yaml`):

```yaml
title: Button
fields:
  -
    handle: title
    field:
      input_type: text
      type: text
      localizable: false
      listable: hidden
      display: Titel
  -
    handle: link
    field:
      type: link
      localizable: false
      listable: hidden
      display: Link
```

It does **not work** with this one:

```yaml
title: Button
fields:
  -
    handle: type
    field:
      options:
        default: weiß
        primary: rot
      inline: true
      type: radio
      localizable: false
      width: 50
      listable: hidden
      display: Darstellung
  -
    handle: title
    field:
      input_type: text
      type: text
      localizable: false
      listable: hidden
      display: Titel
  -
    handle: link
    field:
      type: link
      localizable: false
      listable: hidden
      display: Link
```

## Environment

**Statamic version:** `3.0.2@4e8f45ade7f0c70ab3bbad4f62ac3563728568e5`

**PHP version:** 7.4.9

**Install method (choose one):**
- Fresh install from `statamic/statamic`
