### ISSUE TITLE
Image metadata not created when file in .meta already exists, even if empty.

### ISSUE THREAD

**Issue by fitzage** [statamic/cms#2338]
## Bug Description
If an image already has a yaml file in .meta for a specific image, statamic will not generate the metadata for the file, even if the existing file is empty.

Where this is particularly problematic is for images that have custom fields filled in with content from a migration from v2.

## How to Reproduce
1. Empty the content from one of the yaml files in .meta for an asset container.
2. Try to load the asset container in the control panel that shows this image, and you’ll get the error. This is true whether you have custom content fields in the yaml file or if it’s just empty. If the file exists, statamic won’t generate the metadata.

Note: If you delete the file completely and then access the list, this will prompt the file to be re-created with the correct metadata.

## Extra Detail
The yaml file for one image looked like this:

```
data:
  title: Seamster.io
  link: 'https://seamster.io'
  description: 'Welcome to Seamster, a new global edge computing initiative, and learn how leading enterprises are solving for edge-enabled experiences.'
```

This particular image was the only one in a specific asset container that had custom content, so all the other meta yaml files looked like this:

```
data: {  }
size: 21189
last_modified: 1597876992
width: 800
height: 800
```

So statamic generated all the metadata for the files that don’t have custom fields, but not the ones that do.

On a whim, I tested with a completely empty file, and discovered it had the same problem. Statamic wouldn’t add the metadata if the file already exists.

## Environment
Statamic 3.0.2 Pro
Laravel 7.25.0
PHP 7.3.17
No addons installed
Fresh install from `statamic/statamic`, then migrated from v2 with official tool.
