### ISSUE TITLE
Ranged date field ranged saves dates minus one

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2349]
## Bug Description
The date field (ranged in this case) always saves the dates a day before.

## How to Reproduce
```
field:
          mode: range
          time_enabled: false
          time_required: false
          earliest_date: '2020-01-01'
          full_width: true
          inline: true
          columns: 1
          rows: 1
          type: date
          listable: hidden
          instructions: 'When is the climate adaptation week?'
          display: 'Climate adaptation week'
```

## Extra Detail
<img width="322" alt="Screenshot 2020-09-02 at 11 05 51" src="https://user-images.githubusercontent.com/69107412/91962015-44ed1500-ed0c-11ea-896c-dc2746104317.png">

## Environment
Statamic 3.0.2 Pro
Laravel 7.26.1
PHP 7.4.6
No addons installed

**Install method (choose one):**
- Starter Kit Peak
