### ISSUE TITLE
Ranged date formatting only works when used as tag pair

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2350]
## Bug Description
This doesn't work:
```
{{ configuration:climate_adaptation_week:start format_localized="%e" }}
```
But this does:
```
{{ configuration:climate_adaptation_week }}
    {{ start format_localized="%e"  }}
{{ /configuration:climate_adaptation_week }}
```

This is very inflexible to use when templating.

## How to Reproduce
```
-
  handle: climate_adaptation_week
  field:
    mode: range
    time_enabled: false
    time_required: false
    earliest_date: '2020-01-01'
    full_width: true
    inline: true
    columns: 1
    rows: 1
    type: date
    listable: hidden
    instructions: 'When is the climate adaptation week?'
    display: 'Climate adaptation week'
    width: 50
```

## Environment

Statamic 3.0.2 Pro
Laravel 7.26.1
PHP 7.4.6
No addons installed

**Install method (choose one):**
- Starter kit Peak
