### ISSUE TITLE
Error when showing a field named the same in multiple collections, using different fieldtypes.

### ISSUE THREAD

**Issue by cbautista103** [statamic/cms#2361]
## Bug Description

In an entry with an **Entries** fieldtype, an error will be thrown when attempting to assign an Entry if the field is connected to multiple Collection types. For instance, if there is an entry for "Life of Pi," an error will be thrown if there is an Entries field connected to both Movies and Books collections.

## How to Reproduce

1. Create 3 collections—A, B, and Z.
2. Create an Entries fieldtype on Collection Z that is linked to Collection A and Collection B
3. Attempt to link field in the control panel

handle: appears_in
        field:
          mode: default
          collections:
            - collection_a
            - collection_b
          type: entries
          instructions: 'Select which organizations should display the album'
          listable: hidden
          display: 'Appears In'

4. An error will be thrown as indicated below

## Extra Detail

`Argument 1 passed to Statamic\Markdown\Parser::parse() must be of the type string, array given, called in /Users/{user}/Sites/jesuit-statamic/vendor/statamic/cms/src/Markdown/Manager.php on line 15`

## Environment

Statamic 3.0.3 Pro
Laravel 7.26.1
PHP 7.4.4
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
What's the error? What's the entries field in your blueprint?

**Comment by cbautista103** [comment]
Accidentally submitted before finalizing details, it should now be clarified.

**Comment by jasonvarga** [comment]
Please post the field from your blueprint.

**Comment by cbautista103** [comment]
```
handle: appears_in
        field:
          mode: default
          collections:
            - athletics
            - cocurriculars
          type: entries
          instructions: 'Select which organizations should display the album'
          listable: hidden
          display: 'Appears In'
```
