### ISSUE TITLE
A read only user select field can have a user removed

### ISSUE THREAD

**Issue by johncarter-** [statamic/cms#2415]
Create a blueprint with a field like this.
```
handle: owners
field:
  mode: select
  type: users
  listable: hidden
  display: Owners
```

Add a user to that field and save the entry
```
owners:
  - 7c3d4e68-4718-456f-a757-c63358474baa
```

Go back to the blueprint and make it `read_only: true`.

Then go to the back to the entry and you can remove the assigned user and save the entry.
