### ISSUE TITLE
Can't set view_model for specific blueprint

### ISSUE THREAD

**Issue by RobertCordes** [statamic/cms#2438]
## Bug Description
No matter how I try to set a view model for a specific blueprint, I can't get it to work. I've searched all over the place but I can't find a solution. There only seem to be two ways: in the collection (via `inject`) or directly in the markdown file of a specific page.

## How to Reproduce and extra details
The documentation only gives one example of where to specifiy your view model — inside a collection by using `inject`:

```yaml
# content/collections/pages.yaml
title: Pages
...
inject:
  view_model: App\ViewModels\Page
```
And that works as expected. In my pages collection I have different blueprints, for example `homepage.yaml`, `about.yaml`, etc. I’m expecting that I can just as well define view models inside those files:

```yaml
# resources/blueprints/collections/pages/homepage.yaml
title: Homepage
inject:
  view_model: App\ViewModels\Home

# or

title: Homepage
view_model: App\ViewModels\Home
```
Reading the [documentation on view models](https://statamic.dev/view-models), I didn't expect this to be a problem. I also tried using [YAML front matter](https://statamic.dev/variables#view-frontmatter) inside the template:

```yaml
# resources/views/home.antlers.html
---
view_model: App\ViewModels\Home
---
<div>...</div>
```

What **does work** however is defining the view model inside the markdown files:
```yaml
# content/collections/pages/de/home.md
---
title: Homepage
template: home
view_model: App\ViewModels\Home
...
```

I don't know if this is a bug or not, but it's definitely not very intuitive. If it it expected behaviour this can obviously be closed. 😇

## Environment
Statamic 3.0.8 Pro
Laravel 7.25.0
PHP 7.4.2
rias/statamic-color-swatches 2.0.5

**Install method:** Fresh install from `statamic/statamic`
