### ISSUE TITLE
Date Ranger Picker doesn't allow for sorting by start/end dates

### ISSUE THREAD

**Issue by mnlmaier** [statamic/cms#2441]
## Bug Description
When adding dates by date ranger picker, I am unable to sort by date values in Antlers templates.

## How to Reproduce
Add a date ranger picker, try to sort the collection in the Antlers loop.

## Environment

Statamic 3.0.8 Solo
Laravel 6.18.40
PHP 7.4.2
statamic/ssg dev-master

**Install method (choose one):**
- Starter kit

**Comment by jasonvarga** [comment]
Please provide the template code and an example of the data of an entry.

**Comment by jasonvarga** [comment]
Hey there, we haven’t heard back on this for a while so I’m going to need to close the issue to help us stay organized. You can always reply with more info so we can reopen it or feel free start a fresh one anytime. Either is fine by us!

**Comment by krsilas** [comment]
I'm experiencing the same issue. This is my blueprint:
```yaml
sidebar:
    display: Sidebar
    fields:
      -
        handle: date_range
        field:
          mode: range
          time_enabled: false
          time_required: false
          earliest_date: '2016-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: Date
          type: date
          icon: date
          listable: hidden
```
That creates entries like this:
```yaml
date_range:
  start: '2018-04-22'
  end: '2018-05-13'
```

And that's the template:
```html
{{ taxonomy use="topics" as="item" date_range:exists="true" sort="date_range" }} // or date_range.end
  <ul>
    {{item}}
     <li>{{title}}</li>
    {{/item}}
  </ul>
{{ /taxonomy}}

```

**Comment by j3ll3yfi5h** [comment]
Can confirm, that this doesn't work:

`{{ collection from="events" sort="event_date:start" as="events" }}`

**Comment by arthurperton** [comment]
PR #4967 improves this, at least it'll sort by the first date in date_range, which will normally be the start date.

**Comment by arthurperton** [comment]
Note to devs: I tried supporting the dot notation here, e.g. `sort="event_date.end"`. 

The DataCollection can easily be made to sort in this way, just by replacing `return $this->normalizeSortableValue($item[$sort] ?? null);` with `return $this->normalizeSortableValue(Arr::get($item, $sort));` in the`getSortableValue()` method.

It's just that when the query builders try getting the index by a name with a dot in it, that fails:
`file_put_contents(.../storage/framework/cache/data/stache/indexes/terms/topics/date_range/start): Failed to open stream: No such file or directory`
The dot apparently has a different meaning in index names.

**Comment by austriker27** [comment]
Hello, 

So I was thinking Jason fixed this issue in https://github.com/statamic/cms/pull/5030

However its not working for me. Either sorting by `study_date:end` or just `study_date`. 

content example: 
```md
---
id: 38c09600-720f-43ca-b20e-7ac77ddfbcc1
blueprint: education
title: 'Economics, BA'
study_date:
  start: '2008-09-01'
  end: '2011-09-01'
```

blueprint:
```yaml
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: study_date
        field:
          mode: range
          time_enabled: false
          time_seconds_enabled: false
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: Date
          type: date
          icon: date
          listable: hidden
          instructions_position: above
          read_only: false
          validate:
            - required
          instructions: 'If you are currently studying use your expected completion date'
title: Education
```

template:
```handlebars
{{ collection:education sort="study_date:end" }}
<p>
{{ study_date:start format="Y" }} - {{ study_date:end format="Y" }}
</p>
{{ /collection:education }}
```
