### ISSUE TITLE
Sort modifier causes no output

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#2450]
## Bug Description
After upgrading from 3.0.0 there is no output for arrays, when you add the sort param. Before this was working. When you remove the param, the entries are shown.

## How to Reproduce

```
history:
  -
    jahr: '1920'
    title: 'title'
    text: 'text'
    is_hidden: false
  -
    jahr: '1925'
    title: 'title'
    text: 'text'
    is_hidden: false
```

```
{{ history sort="jahr:desc" }} // no putput
{{ history }} // putput
```

## Environment

**Statamic version:** 3.0.9

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`
