### ISSUE TITLE
Taxonomy Terms doesn't respect 'create: false'

### ISSUE THREAD

**Issue by ReneWeCode** [statamic/cms#2453]
## Bug Description
The documentation (https://statamic.dev/fieldtypes/terms#config-options) tells to add `create: false` , to "only allow selecting from existing terms." This doesn't work - It doesn't do anything.

## Extra Detail
```      
-
  handle: article_categories
  field:
    type: terms
    taxonomies:
      - article_categories
    display: 'Kategorier'
    mode: select
    create: false
    listable: hidden
```

## Environment

**Statamic version:** 3.0.9

**PHP version:** 7.4.10

**Install method (choose one):**
- Fresh install from `statamic/statamic`
