### ISSUE TITLE
Blueprint Field Conditions not working / breaking panel when used on 'parent'

### ISSUE THREAD

**Issue by SirNovi** [statamic/cms#2496]
## Bug Description / How to reproduce
Add a condition to a field that is related to 'parent' and it won't work. It get's worse if you use `equals` then the field is always hidden no matter the actual parent or the value of the condition. It get's worse if the field is in the sidebar as well, then the 'parent' and 'slug' fields vanish as well. 

## Extra Detail
<img width="325" alt="CleanShot 2020-09-22 at 12 45 17@2x" src="https://user-images.githubusercontent.com/1991072/93876877-d2060700-fcd7-11ea-80ec-df750367faa2.png">

[produkt.txt](https://github.com/statamic/cms/files/5261059/produkt.txt)

## Environment

Statamic 3.0.11 Solo
Laravel 7.8.1
PHP 7.3.21
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by sjclark** [comment]
Can verify this, tested it on my own local test copy while talking on the discord to @SirNovi . I was getting un-intelligible (to me at least) Vue errors logged in console when `equals` was used. Other operators (such as `contains`) don't result in the fields disappearing, but also don't result in proper validation. Seems to be a specific issue with **conditional validation not working correctly when referencing the parent variable**.

The shortest path to validating this (as an example) is to append the following to a sidebar blueprint:
```
      - handle: text
        field:
          input_type: text
          display: Text
          type: text
          listable: hidden
          unless:
            parent: "equals cheese"
```
This will result in both the slug and parent fields disappearing (likely due to the aforementioned Vue errors?)
