### ISSUE TITLE
Can't display section above entry title

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2506]
## Bug Description
You can add a section above your entry title in Yaml, but it won't render above the page title in the CP.

## How to Reproduce
```yaml
title: 'Page'
sections:
  main:
    display: Main
    fields:
      -
        handle: section_title
        field:
          type: section
          instructions: 'A section.'
          localizable: false
          display: Section
      -
        handle: title
        field:
          input_type: text
          type: text
          localizable: true
          listable: true
          display: Title
```

## Extra Detail

<img width="354" alt="Screenshot 2020-09-23 at 11 29 53" src="https://user-images.githubusercontent.com/69107412/93994492-3be1e780-fd90-11ea-864e-94e3646b4e63.png">
<img width="970" alt="Screenshot 2020-09-23 at 11 29 57" src="https://user-images.githubusercontent.com/69107412/93994497-3c7a7e00-fd90-11ea-8b61-d2131d1d3dbc.png">

## Environment

Statamic 3.0.12 Pro
Laravel 7.28.3
PHP 7.4.6
