### ISSUE TITLE
Vertical alignment for stack selector in grid table

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2518]
## Bug Description
The vertical alignment for a stack selector in a grid mode table is a little off.

## How to Reproduce
```yaml
-
    handle: pins
    field:
      fields:
        -
          handle: title
          field:
            input_type: text
            type: text
            localizable: true
            listable: hidden
            display: Title
            instructions: 'Leave blank to use the entry title'
        -
          handle: pins
          field:
            type: entries
            localizable: true
            display: Pins
            instructions: 'The pins you want to place.'
            listable: hidden
            mode: default
            collections:
              - pages
            max_items: 1
      mode: table
      min_rows: 1
      add_row: 'Add pin'
      reorderable: true
      type: grid
      instructions: 'Add one or more pins.'
      listable: hidden
      validate: required
      display: Pins
      replicator_preview: false
```

## Extra Detail
<img width="790" alt="Screenshot 2020-09-23 at 14 51 24" src="https://user-images.githubusercontent.com/69107412/94014886-72c5f680-fdac-11ea-99cb-6633589a5c52.png">
