### ISSUE TITLE
[Blueprints] Conditional field breaks section

### ISSUE THREAD

**Issue by jelleroorda** [statamic/cms#2534]
## Bug Description
Conditional field doesn't work as expected; it breaks the `Subsection` tab in the control panel.

## How to Reproduce

I have the following blueprint for a collection:

```yaml
title: Building
sections:
  main:
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
          display: Name
          listable: true
          input_type: text
      -
        handle: content
        field:
          type: markdown
          localizable: true
  subsection:
    fields:
      -
        handle: crew_member_id
        field:
          mode: typeahead
          collections:
            - crew_members
          display: 'Crew member'
          max_items: 1
          type: entries
          listable: hidden
          width: 50
          if:
            root.type_id: 'not building_types::flat'
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: type_id
        field:
          type: terms
          taxonomies:
            - building_types
          display: 'Type'
          default: 'building_types::flat'
          mode: select
          listable: hidden
          max_items: 1
          validate:
            - required
```

If I remove this part, it works like expected:

```yaml
if:
  root.type_id: 'not building_types::flat'
```
## Extra Detail
The tab that doesn't display anymore:
![Screenshot 2020-09-25 at 10 55 17](https://user-images.githubusercontent.com/9193686/94247977-25699680-ff1e-11ea-97fb-d404e1631f22.png)

The JS error:
![Screenshot 2020-09-25 at 11 00 32](https://user-images.githubusercontent.com/9193686/94248144-58138f00-ff1e-11ea-8a3f-2f2678831131.png)

(Line 209 from JS error above)
![Screenshot 2020-09-25 at 11 02 12](https://user-images.githubusercontent.com/9193686/94248296-91e49580-ff1e-11ea-8c3c-f02e6c05123a.png)

## Environment
Statamic 3.0.12 Pro
Laravel 7.28.3
PHP 7.4.9

**Install method (choose one):**
- Fresh install from `statamic/statamic`
