### ISSUE TITLE
No way to have a single checkbox on a form

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#2541]
## Bug Description

In the forms feature, when you're building the blueprint we're showing a subset of the available fieldtypes.
We have a `checkboxes` field but not a single checkbox field. We don't actually have a single checkbox field, but the `toggle` field would be the equivalent.

In addition to adding the toggle to the allow list, we'd need to:

- Write the Antlers view so it could be rendered on the frontend (as a checkbox)
- Use the preProcess method to convert a 0 or 1 (which is what the checkbox would naturally submit) to a true or false.

**Statamic version:** 3.0.13

**Comment by robdekort** [comment]
Hey Jason, I used this a while back to validate consent before adding an e-mail to Mailchimp:
```
-
        handle: consent
        field:
          inline: false
          type: checkboxes
          listable: hidden
          display: Consent
          validate:
            - required
```
