### ISSUE TITLE
Multi-site: Grid within Grid doesn't respect localizable on single fields

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2551]
## Bug Description
Single fields of a Grid within a Grid don't respect `localizable`. They are localizable even when `localizable: true` isn't set.

## How to Reproduce
Add this to the blueprint to reproduce. The field with the handle `name` shouldn't be localizable.

```yaml
     -
        handle: variants
        field:
          fields:
            -
              handle: type
              field:
                type: text
            -
              handle: options
              field:
                fields:
                  -
                    handle: name
                    field:
                      type: text
                  -
                    handle: price
                    field:
                      type: text
                      localizable: true
                mode: table
                reorderable: true
                type: grid
                listable: false
                localizable: true
          mode: stacked
          reorderable: true
          type: grid
          listable: false
          localizable: true
```

## Environment
Statamic 3.0.12 Pro
Laravel 7.28.3
PHP 7.4.9
aerni/snipcart dev-master
