### ISSUE TITLE
in_array and contains modifiers don't work on array's without first flattening

### ISSUE THREAD

**Issue by that0n3guy** [statamic/cms#2580]
## Bug Description
I'm using a "select" fieldtype in a fieldset like this:
```
  -
    handle: options
    field:
      options:
        icon_above: 'Icon on top'
        text-center: 'Horizontal Center Text'
        vertical_center_icon: 'Vertical Center Text & Icon'
      multiple: true
      clearable: false
      searchable: false
      taggable: false
      push_tags: false
      cast_booleans: false
      display: Options
      type: select
      icon: select
      listable: hidden
```

My content looks like:
```
                options:
                  - icon_above
                  - vertical_center_icon
```

In my view I would expect this to work
```
{{ if (options |in_array:icon_above) }}this should show {{/if}}
{{ if (options |contains:icon_above) }}so should this {{/if}}
{{ if options | contains:icon_above }}so should this {{/if}}

```
Neither one works.

This DOES work though:
```
{{ if (options | flatten | in_array:icon_above) }}this should show {{/if}}
{{ if (options | flatten | contains:icon_above) }}so should this {{/if}}

```

## Environment
Statamic 3.0.14 Solo
Laravel 6.18.3
PHP 7.4.9
statamic/migrator dev-master

**Install method (choose one):**
- Fresh install from `statamic/statamic` (Technically I used the migrator from back in beta)
