### ISSUE TITLE
Editing a Blueprint with imported fieldset breaks the sets in entry edit window

### ISSUE THREAD

**Issue by aadind** [statamic/cms#2585]
## Bug Description
I have a `fieldset` for `bard content` and imported into a `standard posts fieldset`. 

The `standard posts fieldset`  is again imported into different collections. 

If i import another fieldset to the existing blueprint while the associated collection entry is being edited, after saving the blueprint the edit page shows all sets of bard fieldset broken and contents are uneditable. 

## How to Reproduce

1. Import a fieldset X into another fieldset Y and map it to H collection blueprint. 
2. Import a new fieldset  Z to  H Collection Blueprint. 
3. WHile doing above, An entry in H collection was being edited and it has many sets from the bard field.
4. in order to see the new imported fieldset Z i will be refreshing the editing window of my entry. 
5. The Sets are now broken and no more editable. - But the rendered content while viewing the entry is intact. 

## Extra Detail

![image](https://user-images.githubusercontent.com/13034288/95007261-47a09a00-062b-11eb-91d5-5199678183ec.png)

## Environment
Developement

**Statamic version:** 3.0.14

**PHP version:** 7.4

**Install method :**
- Migrated from V2

**Comment by damcclean** [comment]
Would you mind providing the YAML files for each of the three fieldsets you're having issues with so we can replicate with the same configuration?

**Comment by aadind** [comment]
Hello there, sharing my complete blueprint for a collection plus blueprints + fieldsets involved. 

```
order: 1
title: Pages
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        import: standard_post
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: date
        field:
          type: date
          required: true
          validate:
            - required
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
      -
        handle: tags
        field:
          type: terms
          taxonomies:
            - tags
          display: Tags
          mode: select
      -
        import: archive_selection
  SEO:
    display: SEO
    fields:
      -
        handle: seotamic_meta
        field:
          display: Meta
          listable: hidden
          type: section
          localizable: false
      -
        handle: seotamic_title
        field:
          options:
            title: Title
            custom: Custom
          clearable: false
          multiple: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          type: select
          localizable: false
          listable: hidden
          default: title
          display: Title
          instructions: 'It can be used to determine the title used on search engine results pages.'
      -
        handle: seotamic_custom_title
        field:
          input_type: text
          character_limit: 100
          type: text
          localizable: false
          listable: hidden
          display: 'Custom Meta Title'
          if:
            seotamic_title: 'equals custom'
      -
        handle: seotamic_title_prepend
        field:
          type: toggle
          instructions: 'Prepends to title the text set in General SEO settings'
          localizable: false
          default: true
          width: 50
          listable: hidden
          display: 'Title prepend'
      -
        handle: seotamic_title_append
        field:
          type: toggle
          localizable: false
          instructions: 'Appends to title the text set in General SEO settings'
          width: 50
          listable: hidden
          default: true
          display: 'Title append'
      -
        handle: seotamic_meta_description
        field:
          options:
            empty: Empty
            general: General
            custom: Custom
          clearable: false
          default: empty
          multiple: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          type: select
          instructions: 'It can be used to determine the text used under the title on search engine results pages. If empty, search engines will automatically generate this text.'
          localizable: false
          listable: hidden
          display: 'Meta description'
      -
        handle: seotamic_custom_meta_description
        field:
          input_type: text
          character_limit: 200
          type: textarea
          localizable: false
          listable: hidden
          display: 'Custom Meta description'
          if:
            seotamic_meta_description: 'equals custom'
      -
        handle: seotamic_canonical
        field:
          type: link
          instructions: 'By default it will be set to the page url'
          localizable: false
          listable: hidden
          display: Canonical
      -
        handle: seotamic_social
        field:
          type: section
          localizable: false
          listable: hidden
          display: Social
      -
        handle: seotamic_open_graph_title
        field:
          options:
            title: Title
            general: General
            custom: Custom
          clearable: false
          default: title
          multiple: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          type: select
          localizable: false
          listable: hidden
          display: 'Open Graph title'
      -
        handle: seotamic_custom_open_graph_title
        field:
          input_type: text
          character_limit: 100
          type: text
          localizable: false
          listable: hidden
          display: 'Custom Open Graph title'
          if:
            seotamic_open_graph_title: 'equals custom'
      -
        handle: seotamic_open_graph_description
        field:
          options:
            meta: 'Meta description'
            general: 'General description'
            custom: Custom
          clearable: false
          default: general
          multiple: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          type: select
          localizable: false
          listable: hidden
          display: 'Open Graph description'
      -
        handle: seotamic_custom_open_graph_description
        field:
          input_type: text
          character_limit: 200
          type: textarea
          localizable: false
          listable: hidden
          display: 'Custom Open Graph description'
          if:
            seotamic_open_graph_description: 'equals custom'
      -
        handle: seotamic_twitter_title
        field:
          options:
            title: Title
            general: General
            custom: Custom
          clearable: false
          default: title
          multiple: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          type: select
          localizable: false
          listable: hidden
          display: 'Twitter title'
      -
        handle: seotamic_custom_twitter_title
        field:
          input_type: text
          character_limit: 100
          type: text
          localizable: false
          listable: hidden
          display: 'Custom Twitter title'
          if:
            seotamic_twitter_title: 'equals custom'
      -
        handle: seotamic_twitter_description
        field:
          options:
            meta: 'Meta description'
            general: 'General description'
            custom: Custom
          clearable: false
          default: general
          multiple: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          type: select
          localizable: false
          listable: hidden
          display: 'Twitter description'
      -
        handle: seotamic_custom_twitter_description
        field:
          input_type: text
          character_limit: 200
          type: textarea
          localizable: false
          listable: hidden
          display: 'Custom Twitter description'
          if:
            seotamic_twitter_description: 'equals custom'
      -
        handle: seotamic_image
        field:
          container: assets
          mode: grid
          restrict: false
          allow_uploads: true
          max_files: 1
          type: assets
          instructions: 'If not set, the general image will be used. It''s best to use an image with a 1.91:1 aspect ratio that is at least 1200px wide for universal support. The image will be resized to 1200 width.'
          localizable: false
          listable: hidden
          display: Image

```
Above is pages collection blueprint. It has imports as Standard Post fieldset.

further  Standard post fieldset has another set of imports inside it as default_bard_content , Archive Selection, hero Banner fieldsets. 

The standard Post Fieldset: 

```
title: 'Standard Post'
fields:
  -
    handle: hero_slider_block
    field:
      display: 'Hero Slider Block'
      type: section
      icon: section
      instructions: 'Inserts an Image + Captions Slider from the Hero Banners Collection.'
      listable: hidden
  -
    import: hero_banner_block
  -
    handle: featured_image_block
    field:
      display: 'Featured Image Block'
      type: section
      icon: section
      instructions: 'An Image which is showed in archives, Homepage etc. Adviced to have an image all the time for making better impressions.'
      listable: hidden
  -
    handle: featured_in_content
    field:
      display: 'Show Featured Image In Content Page?'
      type: toggle
      icon: toggle
      listable: hidden
      width: 50
  -
    handle: featured_image_size
    field:
      options:
        - '200'
        - '300'
        - '400'
        - '500'
        - '600'
        - '700'
      multiple: false
      clearable: true
      searchable: true
      taggable: true
      push_tags: false
      cast_booleans: false
      display: 'Featured Image Height'
      type: select
      icon: select
      listable: hidden
      instructions: 'Select the maximum height of the image - numbers are in pixels'
      placeholder: '300'
      if:
        featured_in_content: 'equals true'
      width: 50
  -
    handle: featured_image
    field:
      mode: grid
      container: main
      restrict: false
      allow_uploads: true
      max_files: 1
      type: assets
      listable: hidden
      display: 'Featured Image'
      width: 66
  -
    handle: content_area
    field:
      display: 'Content Area'
      type: section
      icon: section
      instructions: 'All page contents go into this section'
      listable: hidden
  -
    import: default_bard_content
  -
    handle: excerpt
    field:
      restrict: false
      automatic_line_breaks: true
      automatic_links: true
      escape_markup: false
      smartypants: false
      type: markdown
      listable: hidden
      display: Excerpt
      instructions: 'Write a brief note if necessary'
```

the default_bard_content fieldset:

```title: 'Default Bard Content'
fields:
  -
    handle: bard_content
    field:
      type: bard
      buttons:
        - h2
        - h3
        - h4
        - h1
        - h5
        - h6
        - bold
        - italic
        - underline
        - strikethrough
        - unorderedlist
        - orderedlist
        - removeformat
        - quote
        - superscript
        - subscript
        - anchor
        - assets
        - code
        - codeblock
      style: sans
      spellcheck: true
      allow_source: true
      allow_internal_links: true
      link_noopener: false
      link_noreferrer: false
      target_blank: true
      semantic_elements: false
      container: main
      folder: /
      restrict_assets: false
      sets:
        table:
          display: Table
          fields:
            -
              handle: bard_table
              field:
                type: table
                display: Table
        video:
          display: Video
          fields:
            -
              handle: bard_video
              field:
                type: video
                display: Video
                listable: hidden
        images:
          display: Images
          fields:
            -
              handle: bard_image
              field:
                type: assets
                container: main
                folder: /
                restrict: false
                display: Images
                mode: grid
                listable: hidden
                allow_uploads: true
            -
              handle: image_size
              field:
                placeholder: '300'
                options:
                  - '200'
                  - '300'
                  - '400'
                  - '500'
                  - '600'
                  - '700'
                multiple: false
                clearable: true
                searchable: false
                taggable: true
                push_tags: false
                cast_booleans: false
                display: 'Image Max Height'
                type: select
                icon: select
                instructions: 'Select the max height for image in pixels.'
                listable: hidden
        lists:
          display: Lists
          fields:
            -
              handle: bard_list
              field:
                display: List
                type: list
                icon: list
                listable: hidden
        icons:
          display: Icons
          fields:
            -
              handle: font_awesome
              field:
                display: 'Font Awesome Icons'
                type: font_awesome
                icon: text
                listable: hidden
                instructions: 'start typing to get icon suggestions..'
        bard_forms:
          display: Forms
          fields:
            -
              handle: insert_form
              field:
                max_items: 1
                display: Form
                type: form
                icon: form
                listable: hidden
        html:
          display: HTML
          fields:
            -
              handle: insert_html
              field:
                display: 'Insert Plain HTML'
                type: textarea
                icon: textarea
                instructions: 'Insert Pure HTML or Iframe OR Buttons etc. avoid using variables'
                listable: hidden
        insert_entries:
          display: 'Insert Entries'
          fields:
            -
              handle: bard_entries
              field:
                mode: default
                collections:
                  - pages
                  - photos_gallery
                  - results
                  - testimonials
                  - publications
                  - updates
                  - wisdom_leadership
                display: 'Insert Entries'
                type: entries
                icon: entries
                listable: hidden
      display: 'Flexible Page Content'
      listable: hidden
      always_show_set_button: false
      save_html: false
      toolbar_mode: fixed
      reading_time: true
      fullscreen: true
```


the archive_selection fieldset: 

```
title: 'Archive Selection'
fields:
  -
    handle: template
    field:
      hide_partials: true
      type: template
      listable: hidden
      display: Template
  -
    handle: archive_collections
    field:
      max_items: 1
      mode: select
      display: 'Select Collections'
      type: collections
      icon: collections
      listable: true
  -
    handle: layout
    field:
      hide_partials: false
      display: Layout
      type: template
      icon: template
      listable: hidden
```

the hero_banner fieldset: 

```
title: 'Hero Banner Block'
fields:
  -
    handle: hero_layout
    field:
      options:
        - 'Caption Background Right'
        - 'Caption Background Left'
        - 'Caption Background Dusted Right'
      display: 'Hero Banner Layout'
      type: button_group
      icon: button_group
      listable: hidden
      instructions: 'MUST SELECT if you are adding a slide.'
  -
    handle: hero_slides
    field:
      max_items: 5
      mode: default
      collections:
        - home_banner
      display: 'Select Slides'
      type: entries
      icon: entries
      listable: hidden
      instructions: 'Select Slides from below:'
```
