### ISSUE TITLE
'is_future' and 'is_past' modifiers acting weird

### ISSUE THREAD

**Issue by ramondrent** [statamic/cms#2596]
## Bug Description
**Important:** i'm using European dates, so today for example isn't 10-06-2020 (m-d-Y) but 06-10-2020 (d-m-Y)

I have a 'events' collection with entries including two dates: start_date and end_date.
When I want to output past events, it doesn't seem to output events that have a later day of the month than today.
For example: My code does output an event where the end_date is 05-09-2019, but it doesn't output an event where the end_date is 07-09-2019 (which has a later day of the month than today, the 6th)

## How to Reproduce

My code on the frontend:
`{{ collection:events as="events" }
{{ events date_end | is_past }}
{{ title}}
{{ /events }}
{{ /collection:events }}`

My event in Markdown:

`title: 'My first event'
date_start: 26-08-2019
date_end: 07-09-2019`

## Environment

Laravel 8.8.0
spatie/statamic-responsive-images 1.3.0

**Statamic version:** 3.0.15 Solo

**PHP version:** 7.4.10

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Did you customize the `format` config option of the date field?

**Comment by ramondrent** [comment]
Hi Jason, thanks for taking the time to answer!
I did customize the config option to the d-m-Y format:
```
title: Events
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: start_date
        field:
          mode: single
          time_enabled: false
          time_required: false
          earliest_date: '1900-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: Begindatum
          type: date
          icon: date
          listable: true
          format: d-m-Y
          width: 50
      -
        handle: end_date
        field:
          mode: single
          time_enabled: false
          time_required: false
          earliest_date: '1900-01-01'
          format: d-m-Y
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: Einddatum
          type: date
          icon: date
          listable: true
          width: 50
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required

```
