### ISSUE TITLE
Global variables not available on {{ *recursive children* }}

### ISSUE THREAD

**Issue by jeremydouglas** [statamic/cms#2609]
## Bug Description
When using the `{{ nav }}` tag, and `{{ *recursive children* }}`, the page variables are available on a parent, but not a child.

## How to Reproduce
An example collection structure:
```
structure:
  root: false
  max_depth: 3
  tree:
    -
      entry: c53823d7-c375-4a8c-902e-d799828f3679
      children:
        -
          entry: 5685c3ca-5a54-4fc9-82e3-088c72ceeb7b
          children:
            -
              entry: 07c38551-8e3c-43ab-a140-0af2b8e4d893
            -
              entry: 13f96b3b-0bb2-4a01-85ae-8f18223ef758
```

Template file:
```
{{ nav:collection:catalog }}
<li>current_url: {{ current_url or 'nada' }}</li>
{{ /nav:collection:catalog }}
```

Rendered Output:
```
current_url: //localhost:3000/catalog/bakery
current_url: nada
current_url: nada
current_url: nada
```

## Environment

**Statamic version:** 3.0.16

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`
