### ISSUE TITLE
Select-Field: Options can be deleted on non-primary sites when set to read-only

### ISSUE THREAD

**Issue by schmidtflo** [statamic/cms#2646]
## Bug Description

When using Multisite, and building a blueprint containing a select field, I'm able to delete the selected elements in the non-primary site-versions, when set to non-localizable (=> read-only). However, I cannot add an element.

## How to Reproduce

This is the field yaml definition: 

```yaml
      -
        handle: industry
        field:
          options:
            option1: label1
            option2: label2
            option3: 'Label number 3'
          multiple: true
          max_items: 3
          clearable: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          display: Industrie
          type: select
          icon: select
          instructions: 'In welchen Bereichen ist der Kunde aktiv?'
          listable: hidden
          validate:
            - required
```

## Extra Detail

![Bildschirmfoto 2020-10-13 um 14 28 04](https://user-images.githubusercontent.com/4164150/95860488-63f5b280-0d60-11eb-8a54-1f4a31ed881f.png)
This is the primary site, everything working fine.

![Bildschirmfoto 2020-10-13 um 14 28 19](https://user-images.githubusercontent.com/4164150/95860555-7cfe6380-0d60-11eb-8106-60ca5d8d322a.png)
This is the secondary site, but I'm able to delete the selected options.

## Environment

**Statamic version:** 3.0.16
