### ISSUE TITLE
Sorting by a toggle field type with missing values has unexpected results 

### ISSUE THREAD

**Issue by jelleroorda** [statamic/cms#2679]
## Bug Description
When sorting by two fields the results seem to be incorrect.

## How to Reproduce

1. Create a default collection, with an additional 'featured' field with the following blueprint:

```yaml
      -
        handle: featured
        field:
          type: toggle
          listable: false
          default: false
          validate:
            - required
            - boolean
```

2. Then add a few entries to the collection, with some titles, and mark one or two as featured.

3. Try to display the entries with the following `sort`:

```php
{{ collection from="gemeenten" sort="featured:asc|title:asc" limit="8" }}
    {{ title }}, featured: {{ featured ? 'true' : 'false' }}<br>
{{ /collection }}
```

I would expect the collection to be sorted like this:
- first get the featured articles (sort these by title if necessary)
- then get the rest of the non-featured articels (sort these by title if necessary as well)

Which would mean something like this:
```
Aagtekerke, featured: true
Pijnacker, featured: true
's-Gravenpolder, featured: false
's-Gravenzande, featured: false
Aalburg, featured: false
Aalst, featured: false
Akkrum, featured: false
Alblasserdam, featured: false
```

The result however is like this:
```
's-Gravenpolder, featured: false
's-Gravenzande, featured: false
Aalburg, featured: false
Aalst, featured: false
Akkrum, featured: false
Alblasserdam, featured: false
Aagtekerke, featured: true
Pijnacker, featured: true
```

## Environment
Statamic 3.0.19 Pro
Laravel 7.28.4
PHP 7.4.9

**Install method (choose one):**
- Fresh install from `statamic/statamic`
