### ISSUE TITLE
Bard field not saving start attribute on ordered lists

### ISSUE THREAD

**Issue by fitzage** [statamic/cms#2713]
## Bug Description

- When creating an ordered list in a bard field that ends up getting split by a set or something, it displays as expected, which is to say that the number continues after the split instead of starting over at 1.
- When viewing the source in the control panel, it shows that the `<ol>` tags include a `start` attribute in order to enable this behavior. i.e., `<ol start="7”>`
- This attribute doesn’t get saved in the content file, so on the front end, the `<ol>` tags start over at 1.

## How to Reproduce

1. Inside a bard field, create an ordered list
2. Separate two of the list items with a set
3. Save the page
4. View the page

## Environment

Statamic 3.0.20 Pro (migrated from v2)
Laravel 7.28.3
PHP 7.3.17
cnj/seotamic 2.0.2

**Comment by fitzage** [comment]
This is kind of a show stopper for a site we’re trying to take live.

**Comment by fitzage** [comment]
Obviously this will need more than just saving the attribute, as the system also needs to display that correctly.

**Comment by fitzage** [comment]
Sorry for the rapid-fire updates, but I may have initially misdiagnosed this.

This appears to actually be saved in content, but it’s an `order` attribute instead of `start`.  In theory, if I knew how to manually modify the output, I could dig in and apply that.

**Comment by isratrade** [comment]
I'm also having this problem. ```order: 4``` is **not** outputting as ```<ol start=4```


```
    type: ordered_list
    attrs:
      order: 4
    content:
      -
        type: list_item
        content:
          -
            type: paragraph
            content:
```
