### ISSUE TITLE
Re-selecting an image not possible

### ISSUE THREAD

**Issue by freshface** [statamic/cms#2774]
## Bug Description

After choosing an image to an asset field and closing the image browser i want to select another image.
The image browser opens but the images and folder are not loading.

## How to Reproduce

Se above.

## Extra Detail

The error in the console:

<img width="700" alt="Screenshot 2020-10-30 at 13 50 15" src="https://user-images.githubusercontent.com/103913/97707365-7ccbcb00-1ab7-11eb-9346-4ca098a5f969.png">

## Environment

**Statamic version:** 3.0.21

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
What does the asset field look like in your blueprint?

**Comment by freshface** [comment]
```
 handle: afbeeldingen
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          display: Afbeeldingen
          type: assets
          icon: assets
          listable: hidden
```

**Comment by damcclean** [comment]
Does the issue still happen if you add a container key to the field somewhere, like this:

```yaml
handle: afbeeldingen
field:
  mode: grid
  restrict: false
  allow_uploads: true
  display: Afbeeldingen
  type: assets
  icon: assets
  listable: hidden
  container: assets
```

Obviously replace `assets` with the handle of your asset container.
