### ISSUE TITLE
Can't add a default value to taxonomy terms field if its handle isn't a single word

### ISSUE THREAD

**Issue by lovrokalan** [statamic/cms#2798]
## Bug Description
Adding a default value to taxonomy terms field in blueprints yaml file doesn't work if fields handle includes multiple words separated by underscores.

## How to Reproduce
Add a default value to an existing terms field in yaml file and see that it won't appear in the editor.

## Environment

Statamic 3.0.22 Pro
Laravel 7.28.4
PHP 7.3.11
spatie/statamic-responsive-images 1.3.0

Install method: Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
To confirm, do you mean adding `default: some thing` to a `type: terms` blueprint field?

**Comment by lovrokalan** [comment]
Yes.

**Comment by damcclean** [comment]
This issue seems to have been resolved. I'm can't seem to re-create the issue on the latest version (v3.0.26), here's what I did:

1. Cloned the [Cool Writings](https://github.com/statamic/starter-kit-cool-writings) starter kit
2. Saved the article blueprint, with the `terms` field.
3. In my `resources/blueprints/articles/article.yaml` file, I added a default key to my field configuration:
```yaml
-
        handle: topics
        field:
          type: terms
          taxonomies:
            - topics
          display: Topics
          mode: select
          default: soda
```
4. Went to create a new entry and `Soda` is selected as the default taxonomy.

![image](https://user-images.githubusercontent.com/19637309/98855123-6a587680-2453-11eb-8a8b-8b68a622bbda.png)

If you're still having this issue on v3.0.26, please comment on this issue with the field from your blueprint and I can re-open this issue.
