### ISSUE TITLE
Adding `entries` field type to user blueprint breaks CP

### ISSUE THREAD

**Issue by jelleroorda** [statamic/cms#2855]
## Bug Description
After I add the following field to my `blueprints/user.yaml`, the whole CP is broken.

```yaml
      -
        handle: allowed_buildings
        field:
          type: entries
          collections:
            - buildings
          listable: hidden
```

## How to Reproduce

Add an entries field to your user blueprint, then try to load any page.

## Extra Detail

![Screenshot 2020-11-17 at 18 32 01](https://user-images.githubusercontent.com/9193686/99425492-32de4400-2903-11eb-9176-f7d121883d9e.png)

## Environment

Statamic 3.0.20 Pro
Laravel 7.29.3
PHP 7.4.9
No addons installed
Fresh install from `statamic/statamic`
