### ISSUE TITLE
Broken UI with Array Fieldtype

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2858]
## Bug Description
The UI of the Array Fieldtype breaks in `mode:keyed` when you don't provide labels to the keys.

## How to Reproduce
Use this blueprint to reproduce:

```yaml
sections:
  address:
    display: Address
    fields:
      -
        handle: address
        field:
          mode: keyed
          keys:
            company: Company
            street: 'Street + Nr.'
            zip: 'ZIP Code'
            city: City
            country: Country
          display: Address
          type: array
          icon: array
          instructions: 'The address of your company'
          listable: hidden
          validate:
            - required
      -
        handle: contact
        field:
          mode: keyed
          keys:
            email: null
            phone: null
          display: Contact
          type: array
          icon: array
          instructions: 'The contact information of your company'
          listable: hidden
          validate:
            - required
```

## Extra Detail
<img width="932" alt="Bildschirmfoto 2020-11-18 um 14 30 06" src="https://user-images.githubusercontent.com/23167701/99536454-adae6a00-29aa-11eb-9787-c208edf71289.png">

## Environment
Statamic 3.0.28 Pro
Laravel 8.15.0
PHP 7.4.12
aerni/social-links 2.1.0
aerni/zipper 1.2.0
jonassiewertsen/statamic-livewire 2.1.2
spatie/statamic-responsive-images 1.4.0
visuellverstehen/statamic-classify 2.0.0

**Comment by damcclean** [comment]
I can confirm this is a bug. Thanks for the YAML.

**Comment by damcclean** [comment]
Is there any reason why you're not providing labels for the `email` and `phone` fields?

**Comment by aerni** [comment]
Nope. Just ran to into this by accident. I'm fine having to provide labels. But then the blueprint builder should require the labels.

**Comment by damcclean** [comment]
Yeah, that's probably the best solution (to require them in the blueprint builder)

**Comment by aerni** [comment]
Still an issue.

**Comment by mikemartin** [comment]
Definitely still an issue.

**Comment by mikemartin** [comment]
@aerni I'm experiencing a similar issue when using the Array Fieldtype inside a grid.

<img width="598" alt="Screen Shot 2021-02-02 at 11 15 25 am" src="https://user-images.githubusercontent.com/414211/106534369-091edb80-6548-11eb-814f-97d9603dccb2.png">



```
-
    handle: hero_buttons
    field:
      type: grid
      display: 'Hero Button'
      fields:
        -
          handle: hero_button
          field:
            type: array
            display: Button
            keys:
              label: Label
              link: Link
            listable: hidden
            mode: keyed
      max_rows: 2
      add_row: 'Add Button'
      listable: hidden
      mode: table
      reorderable: true
```
