### ISSUE TITLE
Broken table header in a Grid-Fieldtype that is open in a stack

### ISSUE THREAD

**Issue by wiebkevogel** [statamic/cms#2897]
## Bug Description
The table header of a grid fieldtype is visible with wrong top position and z-index. Happens when an entry is edited via the Relationship-Fieldtype and opened in a stack.

## Extra Detail

https://www.dropbox.com/s/pbp7bc512rtq1q2/Bildschirmvideo%20aufnehmen%202020-11-23%20um%2011.12.28.mov?dl=0

## Environment

**Statamic version:** 3.0.26

**PHP version:** 7.3.14

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Starter kit
- Existing Laravel app
- Other (please explain this magic!)

**Comment by robdekort** [comment]
Can you share your fieldset to make it easier for the developers to replicate this?

**Comment by WiebkeVog** [comment]
Of course. We use a custom fieldtype for the asset and bard, but that should not matter here.

```yaml
        handle: elements
        field:
          type: grid
          fields:
            -
              handle: image
              field:
                type: elvis_assets
                display: 'Bild'
                container: image
                allow_uploads: false
            -
              handle: caption
              field:
                type: bard
                save_html: true
                allow_source: false
                link_noopener: true
                link_noreferrer: true
                target_blank: true
                show_text_count: false
                spellcheck: false
                fullscreen: true
                listable: false
                sortable: false
                display: Bildunterschrift
                buttons:
                - bold
                - italic
                - underline
                - removeFormat
                - anchor
                - entrylink
          mode: table
          display: Bilder
          reorderable: true
          max_rows: 0
          min_rows: 0
          max_files: 100
```
