### ISSUE TITLE
Text only value in field type bard not available in frontend

### ISSUE THREAD

**Issue by dave-maatwebsite** [statamic/cms#2915]
## Bug Description
After migrating from version 2 to version 3, pages that have only text in the bard field and no sets don't show that content in the frontend.

## How to Reproduce
The pages collection has a bard type field in its setup with the following settings:
```
handle: body
    field:
      type: bard
      buttons:
        - h1
        - h2
        - h3
        - bold
        - italic
        - unorderedlist
        - orderedlist
        - removeformat
        - quote
        - anchor
        - assets
        - uppercase
        - bootstrapButton
      style: sans
      spellcheck: true
      allow_source: true
      allow_internal_links: true
      link_noopener: false
      link_noreferrer: false
      target_blank: false
      semantic_elements: false
      restrict_assets: false
      localizable: true
      save_html: true
      display: Body
      sets:
        list-of-sets
```

This results in this field in the control panel:
![statamic-body](https://user-images.githubusercontent.com/61797810/100204126-c5827280-2f03-11eb-937f-2718f43f073d.PNG)

And the saved content of the page looks like this:

```
---
title: Pers
template: default
page_width_class: container-small
summary: Description
slug: pers
blueprint: default
footer_size: default
updated_by: 09926cd0-0572-4fe4-8cd6-f05d348e815e
updated_at: 1606294151
body:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'This is the content'
id: a4ae77b1-68fe-4fc2-ae3a-2e82bc57da57
---
```

The default blueprint contains `{{ partial:bard }}`, which loads the correct partial for the bard elements. But no matter how we try, we can't get the content of the body displayed in the front end of the site.  It does load the file `resources/views/partials/bards/text.antlers.html` as you'd expect, but the `text` variable is an empty string at that point instead of the content we'd expect. 

When selecting a set in this field and adding content to that, this works as expected, but text only still isn't displayed.

For instance, this content setup in the control panel:
![statamic-body-set](https://user-images.githubusercontent.com/61797810/100205726-c4eadb80-2f05-11eb-9e29-9253f52cdb87.PNG)

Produces this content:
```
body:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'This is the content'
  -
    type: paragraph
  -
    type: set
    attrs:
      values:
        type: text
        text:
          -
            type: paragraph
            content:
              -
                type: text
                text: 'This is a text field inside the bard element'
```

In the frontend, this only prints `This is a text field inside the bard element` and not `This is the content`.

Possibly this is an issue with migrating the content and setup from V2 to V3, because this setup worked fine in V2.

## Environment

**Statamic version:** 3.0.30

**Laravel version:** 7.28.4

**PHP version:** 7.4.3

**Install method (choose one):**
- Fresh install from `statamic/statamic` and running the migrator to migrate the content from v2 to v3.
