### ISSUE TITLE
Emails only getting delivered to one person on list in YAML and getting multiple times

### ISSUE THREAD

**Issue by twd3** [statamic/cms#2918]
## Bug Description

Email submissions only going to the first person in the forms yaml config and getting delivered the amount of people you have configured. So I have something like this with five people getting the form submission in the forms yaml config:
```
title: 'Contact'
honeypot: contact_fax
email:
  -
    to: tom@blah.com
    from: admin@blah.com
    reply_to: '{{ email }}'
    subject: 'New Contact'
    html: email/contact-us
    text: email/contact-us-text
  -
    to: joe@blah.com
    from: admin@blah.com
    reply_to: '{{ email }}'
    subject: 'New Contact'
    html: email/contact-us
    text: email/contact-us-text
  -
    to: jerry@blah.com
    from: admin@blah.com
    reply_to: '{{ email }}'
    subject: 'New Contact'
    html: email/contact-us
    text: email/contact-us-text
  -
    to: beth@blah.com
    from: admin@blah.com
    reply_to: '{{ email }}'
    subject: 'New Contact'
    html: email/contact-us
    text: email/contact-us-text
  -
    to: dude@blah.com
    from: admin@blah.com
    reply_to: '{{ email }}'
    subject: 'New Contact'
    html: email/contact-us
    text: email/contact-us-text
```
**What happens is only tom@blah.com gets the form submission and he gets it 5 times in a row because there is five people configured.** I have not tried rolling back the version to see if it fixes it. Also, there is nothing in the logs.

## How to Reproduce

Make a simple form then make sure to have both html and text version templates as I have above then add 5 people to get the submissions. Only the topmost person should get the submission in their email and they should get it 5 times.

## Extra Detail

I've tested this on a few forms and it's happening on all. I've also tested with Akismet turned off because I thought that could be it...

## Environment

Statamic 3.0.31 Pro
Laravel 8.15.0
PHP 7.4.6
silentz/akismet 2.2.3

Fresh install from `statamic/statamic`
