### ISSUE TITLE
Reordering bard sets does break bard content

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#2922]
## Bug Description
On the bard settings page, it's very easy to reorder sets. Unfortunately this breaks the content sometimes, because it regenerates the set handles from the display name with reordering. (this happens only, if you rename the automatic set handles to your own fits)

## How to Reproduce

1. Add a bard field to your blueprint with at least two sets.
2. Change the set handle (not display name) to something you like.
3. Add entries and content inside these two sets.
4. Go back to the bard settings page and reorder the sets.
5. Reopen the previously edited page and have a look at the broken bard set output.

## Environment
Statamic 3.0.30 Pro
Laravel 8.15.0
PHP 7.4.12
No addons installed

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by j3ll3yfi5h** [comment]
Found out that it had to do with my custom set handles. Anyway, this should not happen...

**Comment by damcclean** [comment]
@j3ll3yfi5h Did you manage to resolve the issue? Just wondering as you closed and re-opened the issue.

**Comment by j3ll3yfi5h** [comment]
@damcclean Not really, but I found out that it has to do with my custom set handles... If I reorder sets, the handles are regenerated (from the set title) and this causes the broken content...

**Comment by damcclean** [comment]
Would you be able to share the broken set handles?

**Comment by j3ll3yfi5h** [comment]
@damcclean for example these three sets:
before reordering:
```
       c_map:
          display: Map
          fields:
            -
              handle: map_latitude
              field:
                input_type: text
                display: Breitengrad
                type: text
                icon: text
                listable: hidden
            -
              handle: map_longitude
              field:
                input_type: text
                display: Längengrad
                type: text
                icon: text
                listable: hidden
        c_form:
          display: Formular
          fields:
            -
              import: blocktitle
            -
              handle: c_form
              field:
                max_items: 1
                display: Formular
                type: form
                icon: form
                listable: hidden
            -
              handle: submit_txt
              field:
                input_type: text
                display: Button-Beschriftung
                type: text
                icon: text
                instructions: 'Fallback: «Absenden»'
                listable: hidden
        c_code:
          display: Code
          fields:
            -
              handle: c_code
              field:
                theme: material
                mode: htmlmixed
                indent_type: tabs
                indent_size: 4
                key_map: sublime
                line_numbers: true
                line_wrapping: true
                display: HTML
                type: code
                icon: code
                listable: hidden
```

after reordering:

```
        code:
          display: Code
          fields:
            -
              handle: c_code
              field:
                theme: material
                mode: htmlmixed
                indent_type: tabs
                indent_size: 4
                key_map: sublime
                line_numbers: true
                line_wrapping: true
                display: HTML
                type: code
                icon: code
                listable: hidden
        formular:
          display: Formular
          fields:
            -
              import: blocktitle
            -
              handle: c_form
              field:
                max_items: 1
                display: Formular
                type: form
                icon: form
                listable: hidden
            -
              handle: submit_txt
              field:
                input_type: text
                display: Button-Beschriftung
                type: text
                icon: text
                instructions: 'Fallback: «Absenden»'
                listable: hidden
        map:
          display: Map
          fields:
            -
              handle: map_latitude
              field:
                input_type: text
                display: Breitengrad
                type: text
                icon: text
                listable: hidden
            -
              handle: map_longitude
              field:
                input_type: text
                display: Längengrad
                type: text
                icon: text
                listable: hidden
```
