### ISSUE TITLE
No allowed to save in asset fieldtype with validation rule 'image'

### ISSUE THREAD

**Issue by felixstoessel** [statamic/cms#2933]
## Bug Description
When saving an `asset` fieldtype and using the validation rule `image` to only allow the client to select images, you are not allowed to save the entry and it say's `Must be an image.`.

## How to Reproduce
Use this and try to save without adding an image to the field:

```
  -
    handle: images
    field:
      mode: grid
      container: assets
      restrict: false
      allow_uploads: true
      display: Bilder
      type: assets
      icon: assets
      listable: hidden
      validate:
        - nullable
        - image
```

I also tried to add a `nullable` validation rule before the `image` after a suggestion by a community member, but this still doesn't work.

## Environment

Statamic 3.0.30 Solo
Laravel 8.14.0
PHP 7.4.10

**Comment by damcclean** [comment]
Hmm, does this issue occur for you when you upload a single or multiple images?

**Comment by felixstoessel** [comment]
Yeah, this message also appears when I select 1 or multiple images. So with this validation rule, I can not save, even if I fulfill the rule requirements.

**Comment by jasonvarga** [comment]
`image` doesn't work as a validation rule because what's being submitted is just a list of IDs. The assets themselves would have already been uploaded.

What you can do instead is use `'mimes:jpg,png'`

**Comment by felixstoessel** [comment]
@jasonvarga Hey Jason. I tried your suggestion, but still the same error: `Must be a file of type: jpg, jpeg, png, gif, webp, svg.`

Here is my code:
```
  -
    handle: image
    field:
      mode: grid
      container: assets
      restrict: false
      allow_uploads: true
      max_files: 1
      display: Bild
      type: assets
      icon: assets
      listable: hidden
      validate:
        - 'mimes:jpg,jpeg,png,gif,webp,svg'
  -
    handle: images
    field:
      mode: grid
      container: assets
      restrict: false
      allow_uploads: true
      display: Bilder
      type: assets
      icon: assets
      listable: hidden
      validate:
        - 'mimes:jpg,jpeg,png,gif,webp,svg'
```

What am I doing wrong?
