### ISSUE TITLE
Incorrect alignment of fields in CP form when using the prepend option

### ISSUE THREAD

**Issue by jelleroorda** [statamic/cms#2935]
##  Bug Description
When prepending to an input, the input is not aligned correctly (at least when you have 4 next to eachother, did not test with less inputs).

## How to Reproduce
Create a new collection with the following snippet as part of the fields:

```yaml
      -
        handle: correctie_vermindering
        field:
          display: 'Correctie vermindering'
          type: section
          listable: hidden
      -
        handle: leden_m_correctie_vermind
        field:
          input_type: text
          display: 'Leden (m)'
          prepend: '-'
          width: 25
          listable: hidden
          validate:
            - numeric
      -
        handle: leden_v_correctie_vermind
        field:
          input_type: text
          display: 'Leden (v)'
          prepend: '-'
          width: 25
          listable: hidden
          validate:
            - numeric
      -
        handle: doopleden_m_correctie_vermind
        field:
          input_type: text
          display: 'Doopleden (m)'
          prepend: '-'
          width: 25
          listable: hidden
          validate:
            - numeric
      -
        handle: doopleden_v_correctie_vermind
        field:
          input_type: text
          display: 'Doopleden (v)'
          prepend: '-'
          width: 25
          listable: hidden
          validate:
            - numeric
      -
        handle: totaal_correctie
        field:
          display: 'Totaal aantal leden na correctie'
          type: section
          listable: hidden
      -
        handle: leden_m_totaal_na_vermind
        field:
          display: 'Leden (m)'
          type: text
          read_only: true
          width: 25
          listable: hidden
      -
        handle: leden_v_totaal_na_vermind
        field:
          display: 'Leden (v)'
          type: text
          read_only: true
          width: 25
          listable: hidden
      -
        handle: doopleden_m_totaal_na_vermind
        field:
          display: 'Doopleden (m)'
          type: text
          read_only: true
          width: 25
          listable: hidden
      -
        handle: doopleden_v_totaal_na_vermind
        field:
          display: 'Doopleden (v)'
          type: text
          read_only: true
          width: 25
          listable: hidden
```

## Extra Detail
As you can see, the read-only inputs align properly, but the ones with prepended string do not.
![Screenshot 2020-11-28 at 10 07 56](https://user-images.githubusercontent.com/9193686/100498445-93228080-3162-11eb-87d7-3ebc7fde7c2e.png)

## Environment
Statamic 3.0.30 Pro
Laravel 7.29.3
PHP 7.4.9
**Fresh install from `statamic/statamic`**
