### ISSUE TITLE
Form submissions columns: date preference being ignored

### ISSUE THREAD

**Issue by JonKaric** [statamic/cms#2948]
## Bug Description
Form submissions columns: datestamp preference being ignored

## How to Reproduce

1) Go to form submissions
2) Amend columns (include date)
3) Refresh 

## Extra Detail

No console errors logged.

**User config file after saving column preferences**

```yaml
preferences:
  forms:
    contact:
      columns:
        - datestamp
        - name
        - email
```

**Form blueprint**
```yaml
title: Contact
fields:
  -
    handle: name
    field:
      type: text
      display: Name
      validate: ''
  -
    handle: email
    field:
      type: text
      display: 'Email Address'
      validate: required|email
  -
    handle: message
    field:
      type: text
      display: Message
      validate: required

```

## Environment
Statamic 3.0.31 Pro
Laravel 8.14.0
PHP 7.3.7
aryehraber/statamic-captcha 1.0.3
edalzell/variable 1.0.1
statamic/migrator dev-master
statamic/seo-pro 2.0.14

**Install method (choose one):**
- Existing statamic v3 site
