### ISSUE TITLE
Control Panel "crashes" with nested structure

### ISSUE THREAD

**Issue by philippgrimm** [statamic/cms#2959]
Hey I contacted the support with this and they said I should create an issue
## Bug Description
In my specific use case with Nested replicators and sets (relations) in a bard field the cp crashes when adding content to the bard field.

I checked the vue events in dev tools an there is an ifinite loop of meta-update and replicator-preview-updated
![vue dev tools](https://user-images.githubusercontent.com/9745579/101042834-e12dee80-357d-11eb-8f45-777a1c4914df.png)

## How to Reproduce
My Structure:

Pages Blueprint -> rows field (replicator of row fieldset) -> colums field (replicator of colums fieldset) -> content (bard with sets. eg teaser, button, slider,etc)

So lets say I have a page with "row 1" and "row 2" both with one column ("col 1.1", "col 2.1").

If I add a relational field (entry field of teaser collection) to the bard comntent of "col1.1" everything works fine. If I add the a relational field (entry field of teaser collection) to the bard comntent of "col2.1" and hit select the CP crashes (out of memory) and nothing happens.

## Extra Detail
[content+resources.zip](https://github.com/statamic/cms/files/5636725/content%2Bresources.zip)

## Environment
Statamic 3.0.31 Solo
Laravel 8.16.1
PHP 7.4.9
spatie/statamic-responsive-images 1.4.0

**Install method (choose one):**
Fresh install from `statamic/statamic`

**Comment by snavebelac** [comment]
I think I have hit this bug recently as well and was able to reproduce with a basic example on a fresh install.

Statamic 3.0.32 Solo
Laravel 8.17.2
PHP 7.4.13
No addons installed

Browser tab crashes when selecting an Entry on the second instance of a nested Bard field.

- Add 2 Nested Bard fields to the root Bard field
- Add Button fields to both
- Link to existing Entry on one of them works fine (order does not seem to matter)
- Link to existing Entry on the other one and tab crashes

### Basic Blueprint
```yaml
title: Pages
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: bard
        field:
          always_show_set_button: false
          sets:
            nested_bard:
              display: 'Nested Bard'
              fields:
                -
                  handle: bard
                  field:
                    always_show_set_button: false
                    buttons:
                      - h2
                      - h3
                      - bold
                      - italic
                      - unorderedlist
                      - orderedlist
                      - removeformat
                      - quote
                      - anchor
                      - image
                      - table
                    save_html: false
                    toolbar_mode: fixed
                    link_noopener: false
                    link_noreferrer: false
                    target_blank: false
                    reading_time: false
                    fullscreen: true
                    allow_source: true
                    display: Bard
                    type: bard
                    icon: bard
                    listable: hidden
                    sets:
                      button:
                        display: Button
                        fields:
                          -
                            handle: entries
                            field:
                              mode: default
                              collections:
                                - pages
                              display: Entries
                              type: entries
                              icon: entries
                              listable: hidden
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          display: Bard
          type: bard
          icon: bard
          listable: hidden
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
```

<img width="692" alt="Screenshot 2020-12-04 at 10 11 36" src="https://user-images.githubusercontent.com/4972511/101151211-3b2fc200-3619-11eb-8740-975724ba3280.png">
