### ISSUE TITLE
Section fieldtype saves as null

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2970]
## Bug Description
The `Section` fieldtype saves `null` to the entry's markdown file.

**Example**
The fieldtype's handle is `image_section` and it saves `image_section: null` to the entry.

## How to Reproduce
- Add a `Section` fieldtype to a blueprint
- Save an entry with that blueprint
- See the fieldtype save with null

## Environment
Statamic 3.0.32 Pro
Laravel 8.17.2
PHP 7.4.13
aerni/social-links 2.1.0
aerni/zipper 1.2.0
aryehraber/statamic-impersonator 2.0.0
jonassiewertsen/statamic-livewire 2.2.0
spatie/statamic-responsive-images 1.4.0
visuellverstehen/statamic-classify 2.0.0
withcandour/aardvark-seo 2.0.2

**Comment by damcclean** [comment]
I can't seem to replicate. The section fieldtype doesn't save anything to my entry's markdown file, as intended. 

Do you have any more information you could share, like if you're saving the entry outside of the CP? Could you also share your blueprint where the section is?

**Comment by aerni** [comment]
Ah got it. This issue only happens with section fieldtypes within a replicator set.

**In your blueprint:**
```yaml
handle: replicator
field:
  collapse: false
  sets:
    new_set:
      display: 'New Set'
      fields:
        -
          handle: section
          field:
            display: Section
            type: section
            icon: section
            listable: hidden
  display: Replicator
  type: replicator
  icon: replicator
  listable: hidden
```

**The data that gets saved:**
```md
replicator:
  -
    section: null
    type: new_set
    enabled: true
```
