### ISSUE TITLE
Empty field is saving as `''`

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#2986]
## Bug Description

Empty text fields save as `''` 

## How to Reproduce

```yaml
    handle: link_text
    field:
      type: text
      display: 'Link Text'
      default: 'Learn More'
      antlers: true
```

Then in the template:

`{{ link_text ?? title }}`

The `title` never gets shown if the text is `''`.

## Environment

Statamic 3.0.33 Pro
Laravel 8.18.1
PHP 7.4.13
aryehraber/statamic-captcha 1.1.0
edalzell/forma 0.7.2
serieseight/statamic-uuid 2.0.0
silentz/mailchimp 2.4.2
statamic/seo-pro 2.0.14
transformstudios/front dev-main
