### ISSUE TITLE
Date field should not show time when not needed

### ISSUE THREAD

**Issue by aerni** [statamic/cms#3004]
## Bug Description
I've got a blueprint where the default date field has the time enabled. If an entry doesn't need the time, you can discard the input. On reload, the time is back at `00:00`. I expect it to show the `Add time` button instead.

## How to Reproduce
Add this to your blueprint and try yourself:
```yaml
field:
  type: date
  required: true
  validate:
    - required
  display: Date
  listable: true
  mode: single
  time_enabled: true
  time_required: false
  earliest_date: '2020-01-01'
  full_width: false
  inline: false
  columns: 1
  rows: 1
  instructions: 'The date of this article'
  width: 50
```

## Extra Detail
![date](https://user-images.githubusercontent.com/23167701/101909940-8d935480-3bbe-11eb-858d-e04cebfc5bca.gif)

## Environment
Statamic 3.0.34 Pro
Laravel 8.18.1
PHP 7.4.13
aerni/social-links 2.1.0
aerni/zipper 1.2.0
aryehraber/statamic-impersonator 2.0.0
jonassiewertsen/statamic-livewire 2.2.0
spatie/statamic-responsive-images 1.4.0
visuellverstehen/statamic-classify 2.0.0
withcandour/aardvark-seo 2.0.3
