### ISSUE TITLE
Error in sidebar when using conditions to show/hide field

### ISSUE THREAD

**Issue by JoeriE** [statamic/cms#3054]
## Bug Description
I've a collection with two linked taxonomies. One taxonomy should only be visible if the other collection has a certain value, example:
Expertise categories has entries: expertise, news and projects
Expertise tags should only be visible if expertise categories has value expertise. 

I've added this as a condition in the cp:

![image](https://user-images.githubusercontent.com/11161180/103213595-77033200-490e-11eb-9114-91c4aec9834d.png)

But then the sidebar breaks because of an javascript error:
**Sidebar before**
![image](https://user-images.githubusercontent.com/11161180/103213701-c0538180-490e-11eb-8147-4576cf3a1980.png)

**Sidebar after** 
![image](https://user-images.githubusercontent.com/11161180/103213664-99954b00-490e-11eb-8381-3911edf39464.png)

**Javascript error**
`SyntaxError: Unexpected token ':'
    at _default.passesCondition (Validator.js:209)
    at Validator.js:62
    at underscore.js:926
    at underscore.js:255
    at Function.v.each.v.forEach (underscore.js:186)
    at Function.v.filter.v.select (underscore.js:254)
    at Function.v.reject (underscore.js:262)
    at v.each.v.<computed> [as reject] (underscore.js:1639)
    at _default.value (Validator.js:62)
    at _default.value (Validator.js:33)`

## Environment
Statamic 3.0.36 Pro
PHP 7.4.12

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Hi there! I've just attempted to re-produce this issue and I don't seem to get the console error or the fields hiding from my sidebar. For reference, here's the two fields I tested with in my blueprint.

```yaml
      -
        handle: show_hello
        field:
          options:
            'yes': 'Yes'
            'no': 'No'
          multiple: false
          clearable: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          display: 'Show Hello'
          type: select
          icon: select
          listable: hidden
      -
        handle: hello
        field:
          input_type: text
          antlers: false
          display: Hello
          type: text
          icon: text
          listable: hidden
          if:
            show_hello: 'equals yes'
```

Would you be able to share the two fields from your blueprint that are causing issues so I can see if I can reproduce with the same field names etc?

**Comment by JoeriE** [comment]
@damcclean Here's the blueprint of the two fields:
```yaml
      -
        handle: expertise_categories
        field:
          type: terms
          taxonomies:
            - expertise_categories
          display: 'Expertise categories'
          mode: select
          max_items: 1
      -
        handle: expertise_tags
        field:
          type: terms
          taxonomies:
            - expertise_tags
          display: 'Expertise tags'
          mode: select
          listable: hidden
          if:
            expertise_categories: 'equals expertise'
``` 

Thanks!
