### ISSUE TITLE
Read only terms select input with overflow shows UI oddity

### ISSUE THREAD

**Issue by johncarter-** [statamic/cms#3073]
This is a low priority issue.

I have a field with the following config:

```
        handle: product_type
        field:
          type: terms
          taxonomies:
            - product_type
          display: Type
          mode: typeahead
          max_items: 1
          read_only: true
          icon: taxonomy
          listable: hidden
          width: 25
```

When the option in that terms select is **too long for the container** and it is set to `read_only`, there is a weird grey box that overlaps the container:

![Untitled](https://user-images.githubusercontent.com/3776888/103755242-69803300-5005-11eb-9c5e-01fa99059418.png)
