### ISSUE TITLE
Live Preview Renders 404 Page for Drafts/Posts Scheduled in the Future

### ISSUE THREAD

**Issue by ramimassoud** [statamic/cms#3113]
## Bug Description
If a post is in the draft state or published and scheduled for a future date, then Live Preview renders the 404 error page instead of the post.
## How to Reproduce
1. Set future posts to be private
2. Create a new post in a collection, saved or unsaved, published or draft
3. Change date to the future
4. Click "Live Preview"
5. Live preview page will render, but instead of the post, you'll see the 404 page

Looking in the network tab, Live Preview is still fetching `cp/collections/articles/entries/<uuid>/<slug>/preview`
## Extra Detail

`content/collections/articles.yaml`
```yaml
title: Articles
template: articles.show
layout: layout
mount: <UUID>
taxonomies:
  - topics
revisions: false
route: '{year}/{month}/{day}/{slug}'
date: true
sort_dir: desc
default_status: draft
date_behavior:
  past: public
  future: private
```

## Environment

```
Statamic 3.0.38 Pro
Laravel 8.21.0
PHP 7.4.13
No addons installed
```

**Install method:**
- Starter kit
