### ISSUE TITLE
Bard Breaks Control Panel Styling With Long Lines

### ISSUE THREAD

**Issue by ramimassoud** [statamic/cms#3115]
## Bug Description

When typing in a bard field text wrapping does not occur soon enough and causes the styling in admin to break with an unexpected side scroll and when scrolling the editing area will move into the left sidebar.

I've tested this both with normal text and text in a code block.

## How to Reproduce

Use a smaller window size, then in a bard field type characters until there should be a line wrap.

## Extra Detail

![statamic-admin-bug](https://user-images.githubusercontent.com/374033/104822707-83debb80-5812-11eb-902a-1b9c3463968c.gif)

`/resources/blueprints/collections/articles/article.yaml`
```yaml
title: Article
sections:
  main:
    display: Main
    fields:
      -
        handle: hero_image
        field:
          container: assets
          mode: list
          restrict: false
          allow_uploads: true
          max_files: 1
          type: assets
          localizable: false
          listable: false
          display: 'Hero Image'
          folder: articles
      -
        handle: title
        field:
          type: text
          display: Title
      -
        handle: article_body
        field:
          buttons:
            - h1
            - h2
            - h3
            - h4
            - bold
            - italic
            - underline
            - strikethrough
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - code
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: true
          reading_time: true
          fullscreen: true
          allow_source: false
          type: bard
          localizable: false
          listable: true
          display: 'Article Body'
          container: assets
          sets:
            image:
              display: Image
              fields:
                -
                  handle: image
                  field:
                    container: assets
                    mode: grid
                    restrict: false
                    allow_uploads: true
                    type: assets
                    localizable: false
                    listable: hidden
                    display: Image
                    folder: articles
                    max_files: 1
                -
                  handle: caption
                  field:
                    restrict: false
                    automatic_line_breaks: false
                    automatic_links: true
                    escape_markup: false
                    smartypants: true
                    type: markdown
                    localizable: false
                    listable: hidden
                    display: Caption
            code_block:
              display: 'Code Block'
              fields:
                -
                  handle: language_select
                  field:
                    options:
                      ruby: Ruby
                      php: PHP
                      shell: Shell
                      nginx: Nginx
                    placeholder: 'Select Language'
                    clearable: false
                    multiple: false
                    searchable: true
                    taggable: false
                    push_tags: false
                    cast_booleans: false
                    type: select
                    localizable: false
                    listable: true
                    display: 'Language Select'
                -
                  handle: ruby
                  field:
                    theme: light
                    mode: ruby
                    indent_type: spaces
                    indent_size: 2
                    line_numbers: true
                    line_wrapping: true
                    key_map: default
                    type: code
                    localizable: false
                    listable: hidden
                    display: Ruby
                    if:
                      language_select: 'equals ruby'
                -
                  handle: php
                  field:
                    theme: light
                    mode: php
                    indent_type: spaces
                    indent_size: 4
                    line_numbers: true
                    line_wrapping: true
                    key_map: default
                    type: code
                    localizable: false
                    listable: hidden
                    display: PHP
                    if:
                      language_select: 'equals php'
                -
                  handle: shell
                  field:
                    theme: light
                    mode: shell
                    indent_type: tabs
                    indent_size: 4
                    key_map: default
                    line_numbers: true
                    line_wrapping: true
                    type: code
                    localizable: false
                    listable: hidden
                    display: Shell
                    if:
                      language_select: 'equals shell'
                -
                  handle: nginx
                  field:
                    theme: light
                    mode: nginx
                    indent_type: tabs
                    indent_size: 4
                    key_map: default
                    line_numbers: true
                    line_wrapping: true
                    type: code
                    localizable: false
                    listable: hidden
                    display: Nginx
                    if:
                      language_select: 'equals nginx'
            video:
              display: Video
              fields:
                -
                  handle: video_embed
                  field:
                    type: video
                    localizable: false
                    listable: false
                    display: 'Video Embed'
            gallery:
              display: Gallery
              fields:
                -
                  handle: gallery_images
                  field:
                    container: assets
                    mode: grid
                    folder: articles
                    restrict: false
                    allow_uploads: true
                    type: assets
                    localizable: false
                    listable: hidden
                    display: 'Gallery Images'
            twitter_embed:
              display: 'Twitter Embed'
              fields:
                -
                  handle: twitter_url
                  field:
                    input_type: url
                    type: text
                    localizable: false
                    listable: hidden
                    display: 'Twitter URL'
      -
        handle: author
        field:
          type: users
          display: Author
          default: current
  metadata:
    display: Metadata
    fields:
      -
        handle: excerpt
        field:
          type: textarea
          display: Excerpt
          character_limit: 160
      -
        handle: tags
        field:
          type: taggable
          localizable: false
          listable: hidden
          display: Tags
```

## Environment
```
Statamic 3.0.38 Pro
Laravel 8.21.0
PHP 7.4.13
No addons installed
```
**Install method:**
- Starter kit
