### ISSUE TITLE
Fieldset conditions not working properly

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#3153]
## Bug Description
Lot's of time they do seem to work now, but I came across a use case where it doesn't seem to work for me.

## How to Reproduce
```
title: Hero
fields:
  -
    handle: hero_type
    field:
      options:
        illustration: Illustration
        photo: Photo
        empty: Empty
      default: photo
      validate:
        - required
      display: Type
      type: button_group
      listable: hidden
  -
    handle: title
    field: common.title
    config:
      width: 50
      validate:
        - required
  -
    handle: image
    field: common.image
    config:
      width: 50
      unless:
        hero_type: 'equals empty'
```

Put it in a replicator as a set. The image field should hide when you select the `empty` `hero_type`. It doesn't.

## Environment

Statamic 3.0.40 Pro
Laravel 8.24.0
PHP 7.4.13
edalzell/forma 0.8.5
nineteensquared/instagram 1.0.4
silentz/mailchimp 2.5.4

**Install method (choose one):**
- Starter kit: peak

**Comment by jasonvarga** [comment]
Can you provide the replicator blueprint field?

**Comment by robdekort** [comment]
Sure, I'll rip out all the sets you don't have:

```
title: 'Page builder'
fields:
  -
    handle: page_builder
    field:
      type: replicator
      localizable: true
      collapse: true
      listable: false
      display: 'Page builder'
      instructions: 'Build your page by using various predefined content models.'
      sets:
        hero:
          display: Hero
          instructions: 'Show a hero.'
          fields:
            -
              import: hero
```

**Comment by damcclean** [comment]
Do you get any console errors?

**Comment by robdekort** [comment]
Nope

**Comment by robdekort** [comment]
So it could all be me still ;). Anyways. I added some more logic in the template to prevent issues. Good enough for now.

**Comment by robdekort** [comment]
This just sprung to my mind. I don't know why as this is from 11 days ago, but I never shared my relevant common fields.
```
title: 'Common reusable fields'
fields:
  -
    handle: image
    field:
      mode: list
      container: assets
      restrict: false
      allow_uploads: true
      max_files: 1
      type: assets
      localizable: true
      listable: hidden
      display: Image
  -
    handle: title
    field:
      input_type: text
      type: list
      localizable: true
      listable: hidden
      display: Title
      instructions: 'Use a new line for the differences in title styling.'
```
