### ISSUE TITLE
Terms only associated to entries in the non-default site ignore the title defined in the file

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#3154]
## Bug Description

If an entry in site 2 has a term on it, and the same term isn't used by any entries in site 1, then if you attempt to give a title to the term (by editing it in the cp or adding to the yaml file), it is ignored. The slug gets shown.

## How to Reproduce

- Create taxonomy
- Create collection
- Add taxonomy to collection
- Create entry in second site
- Enter a term in entry
- Edit the term, give it a title
- See that the slug is shown in the term listing, not the title.

## Environment

**Statamic version:** 3.0.40

**Comment by richarderoche** [comment]
I'm seeing this issue even if the tags are used in entries on both sites.

**Comment by arthurperton** [comment]
I'm having trouble reproducing this one. Let's take it from step 3, "Add taxonomy to collection":

* I use "Edit Collection" to connect the Taxonomy.
* A field for that taxonomy automatically shows up when editing an Entry, but says "Read Only" in the secondary site.
* So I add a "Taxonomy Terms" field in the blueprint editor and make it localisable.
* Enter a term in entry
* Edit the term, give it a title
* The term listing *does* show the new title.

@jasonvarga What should I do differently?

**Comment by edalzell** [comment]
I'm the original reporter of this @arthurperton, let me revisit this one. We are using entries-in-the-db perhaps that's something to do with it.

I'll update the repro steps, if I can

**Comment by edalzell** [comment]
We're also not on 3.1, maybe it's resolved there as well, I'll try.

**Comment by arthurperton** [comment]
Sure, thank you

**Comment by edalzell** [comment]
Waiting to hear back from the client on this, but ran into this one again: https://github.com/statamic/cms/issues/3091#issuecomment-773158873.

**Comment by edalzell** [comment]
@arthurperton here is our issue: https://cln.sh/cbrSRZ

Note that this was on 3.1.10 but we are using Eloquent (in a Postgres db) for the entries.

I'm happy to walk you through our setup or send you what we have, if that helps.

**Comment by edalzell** [comment]
More info, looks like the collection does NOT have that taxonomy "assigned"

```
title: 'Non-Art Venues'
sites:
  - detroit
  - beholdr
  - boston
  - denver
template: pages/non-art-venues/show
layout: layout
taxonomies:
  - non_art_venue_types
revisions: false
route: '/non-art-venues/{slug}'
sort_dir: asc
search_index: non_art_venues
```

**Comment by edalzell** [comment]
Blueprint:
```
title: 'Non-Art Venue'
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: subtitle
        field:
          input_type: text
          antlers: false
          display: Subtitle
          type: text
          icon: text
          listable: hidden
      -
        handle: hero_image
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          max_files: 1
          display: 'Hero Image'
          type: assets
          icon: assets
          container: editorial
          listable: hidden
          validate:
            - required
      -
        import: intro
        prefix: intro_
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: non_art_venue_types
        field:
          type: terms
          taxonomies:
            - non_art_venue_types
          display: 'Non-art Venue Types'
          mode: select
          icon: taxonomy
          listable: hidden
          validate:
            - required
      -
        handle: non_art_venue_subtypes
        field:
          type: terms
          taxonomies:
            - non-art_venue_subtype
          display: 'Non-Art Venue Subtypes'
          mode: select
          listable: hidden
  maps:
    display: Maps
    fields:
      -
        import: nearby
        prefix: nearby_
  location:
    display: Location
    fields:
      -
        handle: neighborhoods
        field:
          mode: select
          collections:
            - neighborhoods
          display: Neighborhoods
          type: entries
          icon: entries
          listable: hidden
      -
        import: address
      -
        handle: phone
        field:
          input_type: text
          antlers: false
          display: Telephone
          type: text
          icon: text
          listable: hidden
      -
        handle: email
        field:
          input_type: text
          antlers: false
          display: Email
          type: text
          icon: text
          listable: hidden
          validate:
            - email
      -
        import: social
      -
        import: geo_location
      -
        handle: neighborhood_temp
        field:
          input_type: text
          antlers: false
          display: 'Neighborhood (temp)'
          type: text
          icon: text
          listable: hidden
```
