### ISSUE TITLE
Search not performed on new fields created with transformers

### ISSUE THREAD

**Issue by radovanobal** [statamic/cms#3181]
## Bug Description
When you add additional data to the index by the means of transformers it stores the additional fields in the index, but when you search for those values it does not return any results. 

## How to Reproduce
- create multisite
- create collection A
- create collection B referencing collection A with entities
- create search config for transformers getting the referenced collection entity data
- link collection index
- try searching by collection relation 

## Extra Detail
search.php collection index settings
```
'events' => [
            'driver' => 'local',
            'searchables' => ['collection:events'],
            'fields' => ['title', 'movie', 'type'],
            'transformers' => [
                'movie' => function ($movieId) {
                    $movies = Collection::find('movies')
                        ->queryEntries()
                        ->where('id', $movieId)
                        ->first();

                    return [
                        'movie_type' => 'igrani',
                        'actors' => 'Maximiliano',
                        'movie' => ''
                    ];
                }
            ]
        ],
```
        
events.yaml
```
title: Events
search_index: events
sites:
  - default
  - en
template: event
layout: layout
revisions: false
route: '{parent_uri}/event/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
```

## Environment

Statamic version: 3.0.40 Pro
PHP version: 7.4.9
Fresh install from `statamic/statamic`
