### ISSUE TITLE
Store collection and taxonomy routes in their files

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#32]
If you programmatically modify a collection's route, it will actually re-save the config file.
This was okay when we used YAML files, but now that we're using PHP files, all the comments and formatting will be lost. It will be quite sad.

So, I think the route should be moved into the folder.yaml

``` yaml
# content/collections/blog/folder.yaml
title: Blog
template: blog/post
route: /blog/{slug}  # here
```

I think it makes more sense to be there anyway.
