### ISSUE TITLE
Replicator content dissapears from collection entity when replicator set has a link with condition

### ISSUE THREAD

**Issue by radovanobal** [statamic/cms#3226]
## Bug Description
Content of replicator disappears when you create a condition to hide a link field when a entity field is not null. 
The same rule works fine on a text field.  

## How to Reproduce
- create fieldset
- create replicator field
- create replicator set
- create fields (must contain entity field) except for link field
- save the fieldset
- create a bard field inside a collection entity that contains the above fieldset as a set of it's own 
- create a bunch of content inside a entities bard with the current fieldset and save the entity
- go back to the fieldset
- open replicator
- add link field
- add condition to the link field to be hidden when entity is not null
- save fieldset
- return to the entity you have content entered with this fieldset in a bard
- find that the content is empty

## Extra Detail
https://user-images.githubusercontent.com/60649057/107571992-f3668180-6beb-11eb-8c4a-8b1b4e6d042b.mp4

## Environment
Statamic version: 3.0.42 Pro
PHP version: 7.4.9
Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Do you get any console errors?

**Comment by radovanobal** [comment]
No console errors.

Here is the headers and the payload on save:
```
###General
Request URL: http://laravel.local:8080/cp/fields/fieldsets/cards
Request Method: PATCH
Status Code: 204 No Content
Remote Address: 127.0.0.1:8080
Referrer Policy: strict-origin-when-cross-origin

###Response Headers
Cache-Control: no-cache, private
Connection: keep-alive
Date: Wed, 10 Feb 2021 23:04:05 GMT
Server: nginx/1.19.2
Set-Cookie: XSRF-TOKEN=****; expires=Thu, 11-Feb-2021 01:04:05 GMT; Max-Age=7200; path=/; samesite=lax
Set-Cookie: festival_of_tolerance_session=****; expires=Thu, 11-Feb-2021 01:04:05 GMT; Max-Age=7200; path=/; httponly; samesite=lax
X-Powered-By: PHP/7.4.11
X-Powered-By: Statamic

###Request Headers
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 1823
Content-Type: application/json;charset=UTF-8
Cookie: _ga=GA1.1.1794044943.1600172357; _ga_SW0WBPTDW3=GS1.1.1612992467.46.1.1612992828.0; XSRF-TOKEN=****; festival_of_tolerance_session=*****
Host: laravel.local:8080
Origin: http://laravel.local:8080
Pragma: no-cache
Referer: http://laravel.local:8080/cp/fields/fieldsets/cards/edit
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
X-CSRF-TOKEN: *****
X-Requested-With: XMLHttpRequest
X-XSRF-TOKEN: *****

###Request Payload
{title: "Cards", handle: "cards", fields: [{handle: "cards", type: "inline",…}]}
  fields: [{handle: "cards", type: "inline",…}]
    0: {handle: "cards", type: "inline",…}
      config: {collapse: false, sets: {cards: {display: "Cards",…}}, display: "Cards", type: "replicator",…}
        collapse: false
        display: "Cards"
        icon: "replicator"
        instructions: null
        listable: "hidden"
        localizable: true
        max_sets: null
        sets: {cards: {display: "Cards",…}}
          cards: {display: "Cards",…}
            display: "Cards"
            fields: [{handle: "program",…}, {handle: "grid",…}, {handle: "thumbnail",…}, {handle: "description",…},…]
              0: {handle: "program",…}
                field: {max_items: 1, mode: "default", collections: ["programs", "pages"], display: "Content",…}
                  collections: ["programs", "pages"]
                  display: "Content"
                  icon: "entries"
                  listable: "hidden"
                  max_items: 1
                  mode: "default"
                  type: "entries"
                  unless: {external_link: "not null"}
                  handle: "program"
              1: {handle: "grid",…}
              2: {handle: "thumbnail",…}
              3: {handle: "description",…}
              4: {handle: "cta",…}
              5: {handle: "external_link",…}
                field: {display: "External Link", type: "link", icon: "link", listable: "hidden",…}
                  display: "External Link"
                  icon: "link"
                  listable: "hidden"
                  type: "link"
                  unless: {program: "not null"}
                  handle: "external_link"
              6: {handle: "title",…}
        type: "replicator"
        validate: []
        width: 100
      fieldtype: "replicator"
      handle: "cards"
      icon: "replicator"
      type: "inline"
      _id: 0
    handle: "cards"
    title: "Cards"
```

**Comment by duncanmcclean** [comment]
Does your issue sound like the same thing as #3153?

**Comment by radovanobal** [comment]
No this issue is something else entirely. There is a error output on the entity side however. 
Was late yesterday and I didn't check the editor side just the rules side.

![Screenshot from 2021-02-11 08-36-42](https://user-images.githubusercontent.com/60649057/107611536-816e5680-6c44-11eb-8dcd-842282234bfd.png)

**Comment by duncanmcclean** [comment]
Would you mind sharing your the replicator field from your blueprint file so we can attempt to replicate?

**Comment by radovanobal** [comment]
the fieldset yaml with the replicator;
```
title: Cards
fields:
  -
    handle: cards
    field:
      collapse: false
      sets:
        cards:
          display: Cards
          fields:
            -
              handle: program
              field:
                max_items: 1
                mode: default
                collections:
                  - programs
                  - pages
                display: Content
                type: entries
                icon: entries
                listable: hidden
                unless:
                  external_link: 'not null'
            -
              handle: grid
              field:
                options:
                  col-12: 1/1
                  col-6: 1/2
                  col-4: 1/3
                  col-3: 1/4
                multiple: false
                max_items: 3
                clearable: false
                searchable: false
                taggable: false
                push_tags: false
                cast_booleans: false
                display: Grid
                type: select
                icon: select
                listable: hidden
            -
              handle: thumbnail
              field:
                mode: grid
                container: assets
                restrict: false
                allow_uploads: true
                max_files: 1
                display: Thumbnail
                type: assets
                icon: assets
                instructions: '(optional) if left empty, the content display image will be used'
                listable: hidden
            -
              handle: description
              field:
                character_limit: '300'
                antlers: false
                display: Description
                type: textarea
                icon: textarea
                instructions: '(optional) if left empty the content 1st text field will be used'
                listable: hidden
            -
              handle: cta
              field:
                input_type: text
                antlers: false
                display: CTA
                type: text
                icon: text
                listable: hidden
            -
              handle: external_link
              field:
                display: 'External Link'
                type: link
                icon: link
                listable: hidden
                unless:
                  program: 'not null'
            -
              handle: title
              field:
                input_type: text
                antlers: false
                display: Title
                type: text
                icon: text
                listable: hidden
                unless:
                  external_link: 'equals null'
      display: Cards
      type: replicator
      icon: replicator
      localizable: true
      listable: hidden
```
