### ISSUE TITLE
Widont modifier only affecting last paragraph with Bard

### ISSUE THREAD

**Issue by wesort** [statamic/cms#3241]
## Bug Description
A `&nbsp;` should be inserted between the final two words of _every_ paragraph. It is only functioning on the _last_ paragraph

## How to Reproduce
**1.** Bard field within a replicator with the following config:
```
-
  handle: block_text
  field:
    type: bard
    display: Text
    save_html: true
    buttons:
      - bold
      - italic
      - unorderedlist
      - orderedlist
      - html
      - anchor
      - h2
      - h3
      - removeformat
    listable: hidden
    always_show_set_button: false
    toolbar_mode: fixed
    link_noopener: false
    link_noreferrer: false
    target_blank: false
    reading_time: false
    fullscreen: true
    allow_source: true
```

2. Used within a partial view with: 
`{{ block_text | widont }}`

3. When two or more paragraphs are saved in the field, only the final paragraph receives the `&nbsp;`.
 
## Environment
**Statamic** 3.0.43 Pro
**Laravel** 6.20.16
**PHP** 7.4.9
**Addon** doublethreedigital/cookie-notice 3.0.5

**Install method**
Clone of previous site which originated from Cool Writings starter kit
