### ISSUE TITLE
Select field: selected options can still be deleted in readonly mode

### ISSUE THREAD

**Issue by arthurperton** [statamic/cms#3282]
## Bug Description

When a select field has multiple options selected and is set to read_only, you can still delete the selected options.

## How to Reproduce

1 Add a select field to a blueprint and allow multiple selections
1 In an entry, select a few options and save
1 Set the select field to read_only
1 In the entry you can still delete the selected options

## Extra Detail

You can use this in your blueprint:
```
      -
        handle: select
        field:
          options:
            option-1: 'Option 1'
            option-2: 'Option 2'
            option-3: 'Option 3'
          multiple: true
          clearable: true
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          display: Select
          type: select
          icon: select
          width: 25
          listable: hidden
          # read_only: true
```

## Environment

Statamic 3.0.43
Laravel 8.27.0
PHP 8.0.2

**Install method (choose one):**
- Fresh install from `statamic/statamic`
