### ISSUE TITLE
YAML converts arrays to short syntax too early

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#33]
eg.

``` yaml
fields:
  name: { display: Name, validate: 'required|min:2' }
```

This should be

``` yaml
fields:
  name:
    display: Name
    validate: 'required|min:2'
```

The short syntax shouldn't happen until several levels in. Maybe never?
