### ISSUE TITLE
Mounted collection items do not inherit parent_uri

### ISSUE THREAD

**Issue by codedge** [statamic/cms#3312]
## Bug Description

I mounted a collection `Colors` onto a page entry `Colors`. I expected that the items inside the `Colors` collection would inherit the parent uri from the `Colors` collection.

Expectation for routes:

* Color1: `/colors/color1`
* Color1: `/colors/color2`

**Collections:**

* Pages
  * Colors, route `/colors`
  * Legal, route `/legal`
  * Contact, ..
  * ...
* Colors
  * Color1 item
  * Color2 item
  * ...

Configurations `Colors1` collection:

```yml
title: Colors
template: default
layout: layout
mount: d9c8d503-4187-47ae-9aa6-c4a7ba55686d
revisions: false
sort_dir: asc
route: '{parent_uri}/{slug}'
date_behavior:
  past: public
  future: private
```

When I loop through the collection with `{{ collection:colors }}`, the `{{ url }}` variable only show `/color1` instead of `/colors/color1`.

## Environment

Statamic 3.0.45 Pro
Laravel 8.29.0
PHP 7.4.15

**Install method:**
- Fresh install from `statamic/statamic`
