### ISSUE TITLE
Generating image url does not work with S3 asset

### ISSUE THREAD

**Issue by codedge** [statamic/cms#3346]
## Bug Description

Rendering a single image from an asset fieldtype does not work without using Glide.

**Blueprint**

```yaml
media:
    display: Media
    fields:
      -
        handle: overview_images
        field:
          collapse: false
          sets:
            image:
              display: Bild
              fields:
                -
                  handle: image
                  field:
                    mode: grid
                    container: product_images
                    restrict: false
                    allow_uploads: true
                    max_files: 1
                    display: Bild
                    type: assets
                    icon: assets
                    listable: hidden
          display: Übersichtsbilder
          type: replicator
          icon: replicator
          listable: hidden
```

**Template**
```html
{{ overview_images }}
        <div class="mx-auto">
            <a href="{{ image }}" class="glightbox" data-gallery="gallery1">
            {{ glide:image width="135" height="135" }}
                <img class="rounded"
                     src="{{ url }}"
                     width="{{ width }}"
                     height="{{ height }}"
                     alt="{{ label }}"
                     title="{{ label }}"
                />
                <div class="mt-4 text-center w-full">
                    {{ label }}
                </div>
            {{ /glide:image }}
            </a>
        </div>
{{ /overview_images }}
```

The different outputs are:

* `<a href="{{ image }}">` outputs to `<a href="product_images::color_catalog/alle-farben-1.jpg>` which results in a `404 Not Found`
* `{{ glide:image width="135" height="135" }}` outputs a proper url `src="/img/asset/cHJvZHVjdF9pbWFnZXMvY29sb3JfY2F0YWxvZy9hbGxlLWZhcmJlbi0xLmpwZw==?w=135&h=135&s=5ce27c4c595dfb935ae946f32a0666d9"` by using `{{ url }}`

The url to the image in `<img src"..."` is correct, while the url inside the `a href="..."` leads to a 404. So the same image is properly outputted when using glide, but not when just using the `field` name, which should result in a proper url.

Am I using the field `{{ image }}` wrongly?

## Environment

Statamic 3.0.46 Pro
Laravel 8.31.0
PHP 8.0.2
joetannenbaum/antlers-stack-tags 0.1.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`
