### ISSUE TITLE
Assets meta data not available if blueprint is edited

### ISSUE THREAD

**Issue by delz-dev** [statamic/cms#3367]
## Bug Description
-> Title

## How to Reproduce
-> Edit assets blueprint, add custom text-field "text"

## Extra Detail
**.meta/B0002040_2.jpg.yaml**
```yaml
data:
  text: "Image description"
  alt: "Alt text"
size: 15246105
 ```

**Antlers**
```html
{{ images }}
    <img src="{{ url }}" alt="{{ alt }}" />
    <div>{{ text }}</div>
{{ /images }}
```

**Output**
```html
<img src="/img/B0002040_2.jpg" alt="">
<div></div>
````

## Environment
Statamic 3.0.46 Pro
Laravel 8.32.1
PHP 7.4.15

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
This seems to be working fine for me, using both `alt` and a custom text field. What does your assets blueprint look like?

**Comment by delz-dev** [comment]
Yes, `images` is a assets fieldtype …

**Comment by duncanmcclean** [comment]
I've just had a look at this again and I'm still unable to reproduce this issue.

Here's my templating code:

```
{{ big_image }}
    <img src="{{ url }}" alt="{{ alt }}">
{{ /big_image }}
```

Here's what it outputs:

```
<img src="/assets/content/lagoa.jpg" alt="Alt for lagoa">
```

And here's my image field:

```
-
        handle: big_image
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          display: 'Big Image'
          type: assets
          icon: assets
          listable: hidden
```
