### ISSUE TITLE
Collection Error upon upgrading to 3.0.47 | Error Call to a member function columns() on null 

### ISSUE THREAD

**Issue by andrew-ireland** [statamic/cms#3380]
## Bug Description

When I upgrade my Statamic version to 3.0.47, I get the error 
`Error
Call to a member function columns() on null
http://operata-2021.test/cp/collections/blog`

## How to Reproduce

Upgraded site to 3.0.47, downgrading site to previous version (3.0.46) resolves the issue.

## Extra Detail
<img width="1223" alt="Screen Shot 2021-03-16 at 4 45 08 pm" src="https://user-images.githubusercontent.com/18650897/111261718-05b65e00-8677-11eb-8bdb-c680ee61d7c8.png">

## Environment

Statamic 3.0.47 Pro
Laravel 8.32.1
PHP 8.0.2
spatie/statamic-responsive-images 2.5.2

**Install method (choose one):**
- PEAK
- Other (please explain this magic!)

**Comment by duncanmcclean** [comment]
Could you take a screenshot of the folder structure of your `resources/blueprints` directory?

**Comment by andrew-ireland** [comment]
Hey Duncan, here you go 🙂

<img width="852" alt="Screen Shot 2021-03-22 at 9 51 39 am" src="https://user-images.githubusercontent.com/18650897/111923647-43dad400-8af4-11eb-93bf-7bb58425c7b0.png">

**Comment by duncanmcclean** [comment]
Okay, the file structure looks fine to me, would you mind also sharing the `blog_post.yaml` blueprint as well, please?

**Comment by andrew-ireland** [comment]
Sure: 

```
hide: false
title: 'Blog Post'
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          display: Title
          validate:
            - required
      -
        handle: subtitle
        field:
          type: text
          display: Subtitle
      -
        handle: excerpt
        field:
          type: text
          display: Excerpt
          validate: required
      -
        handle: cover_image
        field:
          type: assets
          display: 'Cover Image'
          folder: blog
          max_files: 1
          listable: hidden
          mode: grid
          restrict: false
          allow_uploads: true
          validate:
            - required
      -
        handle: long_form
        field:
          type: bard
          display: 'Long Form Content'
          buttons:
            - h3
            - h4
            - uppercase
            - bold
            - italic
            - underline
            - removeformat
            - unorderedlist
            - orderedlist
            - quote
            - code
            - anchor
          sets:
            heading:
              display: Heading
              field:
                heading:
                  display: 'The Heading'
                  type: text
              fields: {  }
            image:
              display: Image
              fields:
                -
                  handle: photo
                  field:
                    type: assets
                    display: Photo
                    folder: blog
                    max_files: 1
                -
                  handle: caption
                  field:
                    type: text
                -
                  handle: image_type
                  field:
                    type: radio
                    default: Normal
                    options:
                      - Normal
                      - Oversized
            quote:
              display: 'Pull Quote'
              fields:
                -
                  handle: quote
                  field:
                    type: markdown
                    display: 'The Quote'
                -
                  handle: cite
                  field:
                    type: text
                    display: Cite
            button:
              display: 'CTA Button'
              fields:
                -
                  handle: button_label
                  field:
                    type: text
                    display: 'Button Label'
                    width: 50
                -
                  handle: button_link
                  field:
                    type: text
                    display: 'Button Link'
                    width: 50
            video-embed:
              display: 'Video (iframe)'
              fields:
                -
                  handle: video_embed
                  field:
                    type: textarea
                    instructions: 'Paste iframe embed code from Vimeo here to display a video'
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: author
        field:
          type: users
          display: Author
          max_items: 1
          validate: required
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
      -
        handle: date
        field:
          type: date
          required: true
          validate:
            - required
      -
        handle: categories
        field:
          type: terms
          taxonomies:
            - categories
          display: 'Blog Categories'
          mode: select
  seo:
    display: SEO
    fields:
      -
        import: seo
```

**Comment by duncanmcclean** [comment]
Out of curiosity, if you remove `hide: true` from that and you try again, is the problem resolved? I have a suspicion it's because of #3251, which was fixed recently.

**Comment by pryley** [comment]
I got this error immediately after hiding the blueprint.

![image](https://user-images.githubusercontent.com/134939/112685862-c3410e00-8e3a-11eb-8a3a-4608c764a38b.png)

**Comment by andrew-ireland** [comment]
Hwy @damcclean, sorry for the delay in getting back to you — I didn't have the blueprint hidden initially so I'm not sure if that was the issue.

Upgrading to 3.1 seems to resolve the `Call to a member function columns() on null` issue with no changes on my part, so you may have caught the issue!

**Comment by duncanmcclean** [comment]
Yeah, i imagine that'll be the issue. You'll need at least one nice non-hidden blueprint for each collection. Although, there should probably be some better error handling around it.

**Comment by jasonvarga** [comment]
So to confirm, you're seeing this issue if you hide all the blueprints?

**Comment by pryley** [comment]
@jasonvarga Yes.

Here is a screen recording where the product collection has only one blueprint:

https://user-images.githubusercontent.com/134939/112860828-6bd8b300-9071-11eb-9e80-3a0439da1ee7.mp4

**Comment by jasonvarga** [comment]
Okay, understood.

Do you want to hide it though?

You need to have one non-hidden one, or you won't be able to create any entries.

I know that weird error isn't ideal. We'll have to improve the UX. But the solution will be the same whether its a nice or ugly error. You need a non-hidden blueprint.

**Comment by pryley** [comment]
No, I don't want to hide it. However, since I was testing to see what would happen when hidden, I think some UX to handle that situation would be more ideal than just throwing an error.

**Comment by jasonvarga** [comment]
I agree. Just checking.

**Comment by nouce** [comment]
Hi there,

I'm getting the same error when i try to edit the collection!

When iI click on 'Configure collection', i get the error immediately.
 
<img width="1919" alt="Schermafbeelding 2021-11-08 om 15 43 14" src="https://user-images.githubusercontent.com/45368779/140762343-70d6f0dc-9613-43ef-8b5b-db1bfe2c12be.png">

The only blueprint active for this collection is very simple:

```
title: pages
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
            - 'unique_entry_value:{collection},{id},{site}'
      -
        handle: template
        field:
          hide_partials: true
          display: Template
          type: template
          icon: template
          listable: hidden
```


Statamic version: 3.2.20

Someone know what i'm doing wrong?
