### ISSUE TITLE
Save date as timestamp

### ISSUE THREAD

**Issue by aerni** [statamic/cms#3413]
## Bug Description
I have a `Date` fieldtype in my blueprint. The data looks like this when saving the entry: `created_at: '2021-03-24 20:39'`. I would like to save the date as a timestamp instead of a string. The same way Statamic does here:  `updated_at: 1616528480`.

## Environment
Statamic 3.0.48 Pro
Laravel 8.34.0
PHP 7.4.16

**Comment by jasonvarga** [comment]
Add `format: U` to your date field in the blueprint.

**Comment by edalzell** [comment]
@jasonvarga in the docs that looks like its for how the date appears in the CP, NOT how it's saved? 
<img width="595" alt="CleanShot 2021-03-23 at 14 12 14@2x" src="https://user-images.githubusercontent.com/6069653/112219128-d6a56c80-8be1-11eb-8cd2-256e5096cc2a.png">

**Comment by jasonvarga** [comment]
Yeah the docs are wrong. See https://github.com/statamic/docs/issues/417

**Comment by aerni** [comment]
Ah, I see. I suppose this in the blueprint builder is wrong too then:

<img width="1136" alt="Screenshot 2021-03-24 at 8 27 35 AM" src="https://user-images.githubusercontent.com/23167701/112271094-cc837c80-8c7a-11eb-977d-0194739fc3bb.png">

Also, the timestamps get saved as a string rather than an integer:

```md
updated_at: 1616570745
created_at: '1616574300'
```

**Comment by edalzell** [comment]
@aerni can you update the title to reflect the bug (saved as string)?

**Comment by jasonvarga** [comment]
It works fine even if it's a string. Does it cause a problem somewhere?

**Comment by aerni** [comment]
I didn't encounter any problems except my OCD 🤪

**Comment by 1stevengrant** [comment]
@jasonvarga @aerni  I've ran into it causing a problem as it happens.

I have a Bard field has a set that allows the selection of an entry from an `events` collection. 

The event blueprint has a date field `event_start_date` and the is formatted to `U`.

When I try to select an event from my Bard set field, it hit this 

```
Could not parse '1616716800': DateTime::__construct(): Failed to parse time string (1616716800) at position 8 (0): Unexpected character
```

and can't load any entries from the `events` collection as a result. Changing `event_start_date: '1616716800'` to `event_start_date: 1616716800` and order is restored and I can select freely.

**Comment by 1stevengrant** [comment]
for the record, this worked fine in v2

**Comment by aerni** [comment]
I'm actually running into the same error now too. Not with a bard though. Just a regular field. 

This is in my blueprint:
```yaml
handle: created_at
  field:
    mode: single
    time_enabled: true
    time_required: true
    earliest_date: '2021-01-01'
    full_width: false
    inline: false
    columns: 1
    rows: 1
    display: 'Created at'
    type: date
    icon: date
    listable: true
    read_only: true
    format: U
    width: 50
    instructions: 'The time this order was created'
```

And this in the entry's data:
```md
created_at: 1617117360
```

Changing the data to a string fixes the error.
