### ISSUE TITLE
Antlers parse issue with array in related entry

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#3415]
## Bug Description
This is the data of an entry in `books`:
```yaml
reviews:
  -
    stars: '4'
    review: 'Some text.'
  -
    stars: '5'
    review: 'Some text.'
```

This is the data of a page with a replicator where I linked the above book:

```yaml
-
  type: book_highlight
  enabled: true
  book: 63d9511c-a01b-4ba0-8bee-d83d6eaac58c
```

On the template of that page I tried the following two snippets which I'd expect to work:

```html
{{ book:reviews limit="2" }}
    {{ stars }}
    {{ review }}
{{ /book:reviews }}
```

```html
{{ book:reviews as="reviews" }}
    {{ reviews limit="2" }}
        {{ stars }}
        {{ review }}
    {{ /reviews }}
{{ /book:reviews }}
```

They don't return anything. This syntax however does work:
```html
{{ book }}
    {{ reviews limit="2" }}
        {{ stars }}
        {{ review }}
    {{ /reviews }}
{{ /book }}
```

_Thanks to Jason and Erin for identifying this bug on Discord and coming up with a solution._

## How to Reproduce
1. Add a replicator to a page where you can select a set that references another entry (`book`).
2. Give that other entry a grid field called `reviews` with some fields.
3. Try to display the reviews on the page.

## Environment
Statamic 3.1.0-beta.2 Pro
Laravel 8.33.1
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Starter kit
