### ISSUE TITLE
Bard won't display assets if "Display HTML" mode is selected

### ISSUE THREAD

**Issue by joseph-d** [statamic/cms#3436]
## Bug Description

If the "Display HTML" mode toggle is enabled (`save_html: true`) in the blueprint for a Bard field then although an asset (an image) will display when the user first selects it, it will no longer display in the Bard field on subsequent loads. However, it does display on the frontend template correctly.

## How to Reproduce

1. Create a simple collection:
```
title: Stuff
revisions: false
date_behavior:
  past: public
  future: private
```

2. Create a blueprint like this - (minimal example shown)

```
title: Stuff
sections:
  main:
    display: Main
    fields:
      -
        handle: bard
        field:
          always_show_set_button: false
          buttons:
            - image
          save_html: true
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          display: Bard
          type: bard
          icon: bard
          listable: hidden
          container: assets
```

3. Add an image from the asset browser - image will display
4. Save the entry
5. View in front end template - image displays
6. View again in CP, image does not display, only a small image browser control displays

### When image is selected initially, it shows correctly:

![working](https://user-images.githubusercontent.com/1070155/112724508-ad4f4e00-8f0b-11eb-8bb5-1f9e7aaa91c5.png)

### After image is saved and the entry is reloaded in the CP, the image no longer shows:

![not_working](https://user-images.githubusercontent.com/1070155/112724536-c657ff00-8f0b-11eb-9993-656edebebee3.png)

### Notes: 

1. If the "Display HTML" toggle is turned off (`save_html: false`) then the image displays properly in both cases.
2. The image always displays properly in the frontend template no matter which Bard option is selected
3. Entry data looks like this:

```
---
title: test
bard: '<p><img src="/assets/articles/1111.jpeg" alt=""></p>'
updated_by: 5fc6dbd1-5b18-4616-8cad-78199707c2c6
updated_at: 1616856490
id: 9040eea6-cea8-4432-a9e7-8613099b8075
---
test
```

## Environment

```
**Statamic** 3.1.1 Pro
**Laravel** 8.34.0
**PHP** 7.4.16
statamic/seo-pro 2.2.0
```

**Install method (choose one):**
- Fresh install from `statamic/statamic`
