### ISSUE TITLE
Validation required issue in replicator -> grid due to empty ghost rows

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#3481]
## Bug Description
If I fill all required fields in the attached blueprint the data won't validate and the entry won't save. I can only get it to work without `validation: required` on those required nested fields.

> This could very well be a duplicate, I'm not sure, if so please remove. 

## How to Reproduce
Make an entry with attached blueprint. Fill in all (required) fields and hit `cmd+s`.

Originally all those fields below are imported via other fieldsets. At least we now know that's not the issue here as this is all flattened.

## Extra Detail
```yaml
title: Test
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          input_type: text
          localizable: true
          listable: true
          display: Title
          validate:
            - required
      -
        handle: page_builder
        field:
          type: replicator
          localizable: true
          collapse: true
          listable: false
          display: 'Page builder'
          sets:
            link_blocks:
              display: 'Link blocks'
              fields:
                -
                  handle: link_blocks
                  field:
                    fields:
                      -
                        handle: image
                        field: common.image
                        config:
                          width: 50
                          validate: required
                      -
                        handle: title
                        field:
                          input_type: text
                          type: text
                          localizable: true
                          listable: hidden
                          display: Title
                          antlers: false
                          validate: required
                      -
                        handle: text
                        field: common.text_basic
                        config:
                          validate: required
                      -
                        handle: label
                        field:
                          input_type: text
                          type: text
                          localizable: true
                          listable: false
                          display: Label
                          instructions: 'The text inside the button.'
                          width: 66
                          replicator_preview: false
                          validate: required
                      -
                        handle: target_blank
                        field:
                          type: toggle
                          localizable: false
                          width: 33
                          listable: false
                          display: 'Open in new window?'
                          instructions: 'Open link in new tab or window.'
                          replicator_preview: false
                      -
                        handle: link_type
                        field:
                          options:
                            entry: Entry
                            url: URL
                            email: E-mail
                            tel: Telephone
                            asset: Asset
                          type: button_group
                          instructions: 'What type of link do you want to add?'
                          localizable: false
                          default: entry
                          listable: false
                          display: 'Link type'
                          replicator_preview: false
                      -
                        handle: entry
                        field:
                          max_items: 1
                          mode: default
                          type: entries
                          instructions: 'Choose the collection entry you want to link.'
                          localizable: false
                          listable: false
                          display: Entry
                          width: 50
                          replicator_preview: false
                          validate:
                            - 'required_if:{this}.link_type,entry'
                          if:
                            link_type: 'entry'
                      -
                        handle: url
                        field:
                          placeholder: 'https://site.com'
                          input_type: url
                          type: text
                          instructions: 'The URL you want to link.'
                          localizable: false
                          listable: false
                          display: URL
                          width: 50
                          validate:
                            - 'required_if:{this}.link_type,url'
                          if:
                            link_type: 'url'
                      -
                        handle: email
                        field:
                          placeholder: info@site.com
                          input_type: email
                          type: text
                          instructions: 'The e-mail address you want to link.'
                          localizable: false
                          listable: false
                          display: E-mail
                          width: 50
                          replicator_preview: false
                          validate:
                            - 'required_if:{this}.link_type,email'
                          if:
                            link_type: 'email'
                      -
                        handle: tel
                        field:
                          placeholder: '+0 (0)12 345678'
                          input_type: tel
                          type: text
                          instructions: 'The telephone number you want to link.'
                          localizable: false
                          listable: false
                          display: Telephone
                          width: 50
                          replicator_preview: false
                          validate:
                            - 'required_if:{this}.link_type,tel'
                          if:
                            link_type: 'tel'
                      -
                        handle: asset
                        field: common.image
                        config:
                          instructions: 'The asset you want to link.'
                          width: 50
                          display: Asset
                          if:
                            link_type: 'asset'
                      -
                        handle: button_type
                        field:
                          options:
                            button: Button
                            inline: Inline
                          type: button_group
                          instructions: 'How should the button be displayed?'
                          localizable: false
                          default: button
                          listable: false
                          width: 50
                          display: 'Button type'
                          replicator_preview: false
                      -
                        handle: attr_title
                        field:
                          placeholder: 'Learn more'
                          input_type: text
                          type: text
                          localizable: true
                          listable: false
                          display: Title
                          instructions: 'Optional tooltip on mouse hover.'
                          width: 50
                          replicator_preview: false
                      -
                        handle: attr_aria
                        field:
                          placeholder: 'Download the PDF'
                          input_type: text
                          type: text
                          localizable: true
                          listable: false
                          display: 'Aria label'
                          instructions: 'Optional aria label for accessibility.'
                          width: 50
                          replicator_preview: false

                    mode: stacked
                    min_rows: 1
                    add_row: 'Add link block'
                    reorderable: true
                    type: grid
                    instructions: 'Add one or more link blocks with a title, text and a button.'
                    listable: hidden
                    display: 'Link blocks'
                    replicator_preview: false
  sidebar:
    display: Sidebar
    fields:
      -
        handle: meta
        field:
          type: section
          instructions: 'This entry''s meta data.'
          display: Meta
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          generate: true
          listable: hidden
          display: Slug
          validate:
            - required
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
```

<img width="1742" alt="Screenshot 2021-04-06 at 16 02 16" src="https://user-images.githubusercontent.com/69107412/113723299-80601f80-96f1-11eb-846a-02fa3945de25.png">

## Environment
Statamic 3.1.3 Pro
Laravel 8.35.1
PHP 7.4.13
edalzell/forma 0.8.9
silentz/mailchimp 2.5.4

**Install method (choose one):**
- Starter kit

**Comment by jelleroorda** [comment]
Hi Rob,

I was able to replicate your bug. I had to change the blueprint a little since you imported a few fieldsets still.

<details>
  <summary>Used blueprint</summary>
  
```yaml
title: Test
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          input_type: text
          localizable: true
          listable: true
          display: Title
          validate:
            - required
      -
        handle: page_builder
        field:
          type: replicator
          localizable: true
          collapse: true
          listable: false
          display: 'Page builder'
          sets:
            link_blocks:
              display: 'Link blocks'
              fields:
                -
                  handle: link_blocks
                  field:
                    fields:
                      -
                        handle: image
                        field:
                          mode: grid
                          restrict: false
                          allow_uploads: true
                          display: Image
                          type: assets
                          icon: assets
                          container: assets
                          listable: hidden
                          validate:
                            - required
                          max_files: 1
                      -
                        handle: title
                        field:
                          input_type: text
                          type: text
                          localizable: true
                          listable: hidden
                          display: Title
                          antlers: false
                          validate: required
                      -
                        handle: text
                        field:
                          always_show_set_button: false
                          buttons:
                            - h2
                            - h3
                            - bold
                            - italic
                            - unorderedlist
                            - orderedlist
                            - removeformat
                            - quote
                            - anchor
                            - image
                            - table
                          save_html: false
                          toolbar_mode: fixed
                          link_noopener: false
                          link_noreferrer: false
                          target_blank: false
                          reading_time: false
                          fullscreen: true
                          allow_source: true
                          enable_input_rules: true
                          enable_paste_rules: true
                          container: assets
                          display: Text
                          type: bard
                          icon: bard
                          listable: hidden
                          validate:
                            - required
                      -
                        handle: label
                        field:
                          input_type: text
                          type: text
                          localizable: true
                          listable: false
                          display: Label
                          instructions: 'The text inside the button.'
                          width: 66
                          replicator_preview: false
                          validate: required
                      -
                        handle: target_blank
                        field:
                          type: toggle
                          width: 33
                          listable: false
                          display: 'Open in new window?'
                          instructions: 'Open link in new tab or window.'
                          replicator_preview: false
                      -
                        handle: link_type
                        field:
                          options:
                            entry: Entry
                            url: URL
                            email: E-mail
                            tel: Telephone
                            asset: Asset
                          type: button_group
                          instructions: 'What type of link do you want to add?'
                          default: entry
                          listable: false
                          display: 'Link type'
                          replicator_preview: false
                      -
                        handle: entry
                        field:
                          max_items: 1
                          mode: default
                          type: entries
                          instructions: 'Choose the collection entry you want to link.'
                          localizable: false
                          listable: false
                          display: Entry
                          width: 50
                          replicator_preview: false
                          validate:
                            - 'required_if:{this}.link_type,entry'
                          if:
                            link_type: 'entry'
                      -
                        handle: url
                        field:
                          placeholder: 'https://site.com'
                          input_type: url
                          type: text
                          instructions: 'The URL you want to link.'
                          listable: false
                          display: URL
                          width: 50
                          validate:
                            - 'required_if:{this}.link_type,url'
                          if:
                            link_type: url
                      -
                        handle: email
                        field:
                          placeholder: info@site.com
                          input_type: email
                          type: text
                          instructions: 'The e-mail address you want to link.'
                          listable: false
                          display: E-mail
                          width: 50
                          replicator_preview: false
                          validate:
                            - 'required_if:{this}.link_type,email'
                          if:
                            link_type: email
                      -
                        handle: tel
                        field:
                          placeholder: '+0 (0)12 345678'
                          input_type: tel
                          type: text
                          instructions: 'The telephone number you want to link.'
                          listable: false
                          display: Telephone
                          width: 50
                          replicator_preview: false
                          validate:
                            - 'required_if:{this}.link_type,tel'
                          if:
                            link_type: tel
                      -
                        handle: asset
                        field:
                          mode: grid
                          restrict: false
                          allow_uploads: true
                          type: assets
                          icon: assets
                          container: assets
                          listable: hidden
                          validate:
                            - required
                          max_files: 1
                          display: Asset
                          instructions: 'The asset you want to link.'
                          width: 50
                          if:
                            link_type: 'asset'
                      -
                        handle: button_type
                        field:
                          options:
                            button: Button
                            inline: Inline
                          type: button_group
                          instructions: 'How should the button be displayed?'
                          default: button
                          listable: false
                          width: 50
                          display: 'Button type'
                          replicator_preview: false
                      -
                        handle: attr_title
                        field:
                          placeholder: 'Learn more'
                          input_type: text
                          type: text
                          localizable: true
                          listable: false
                          display: Title
                          instructions: 'Optional tooltip on mouse hover.'
                          width: 50
                          replicator_preview: false
                      -
                        handle: attr_aria
                        field:
                          placeholder: 'Download the PDF'
                          input_type: text
                          type: text
                          localizable: true
                          listable: false
                          display: 'Aria label'
                          instructions: 'Optional aria label for accessibility.'
                          width: 50
                          replicator_preview: false
                    mode: stacked
                    min_rows: 1
                    add_row: 'Add link block'
                    reorderable: true
                    type: grid
                    instructions: 'Add one or more link blocks with a title, text and a button.'
                    listable: hidden
                    display: 'Link blocks'
                    replicator_preview: false
```
</details>

The issue seems to lie in the fact that the grid has a ghost row that is failing validation.

<details>
  <summary>Request body</summary>
  
```json
{
    "title": "title",
    "page_builder": [{
        "link_blocks": [{
            "image": [],
            "title": null,
            "text": "[]",
            "label": null,
            "target_blank": false,
            "link_type": "entry",
            "entry": [],
            "url": null,
            "email": null,
            "tel": null,
            "asset": [],
            "button_type": "button",
            "attr_title": null,
            "attr_aria": null,
            "_id": "row-0"
        }, {
            "image": ["assets::placeholder.jpg"],
            "title": "Title",
            "text": "[{\"type\":\"paragraph\",\"content\":[{\"type\":\"text\",\"text\":\"test text\"}]}]",
            "label": "jlabel",
            "target_blank": false,
            "link_type": "entry",
            "entry": [],
            "url": null,
            "email": null,
            "tel": null,
            "asset": [],
            "button_type": "button",
            "attr_title": null,
            "attr_aria": null,
            "_id": "knouk83r"
        }],
        "_id": "set-knouk7m8",
        "type": "link_blocks",
        "enabled": true
    }],
    "meta": null,
    "slug": "title",
    "parent": [],
    "seo": {
        "enabled": true,
        "title": {
            "source": "inherit",
            "value": null
        },
        "description": {
            "source": "inherit",
            "value": null
        },
        "site_name": {
            "source": "inherit",
            "value": null
        },
        "site_name_position": {
            "source": "inherit",
            "value": null
        },
        "site_name_separator": {
            "source": "inherit",
            "value": null
        },
        "canonical_url": {
            "source": "inherit",
            "value": null
        },
        "robots": {
            "source": "inherit",
            "value": null
        },
        "image": {
            "source": "inherit",
            "value": null
        },
        "twitter_handle": {
            "source": "inherit",
            "value": null
        },
        "sitemap": {
            "source": "inherit",
            "value": null
        },
        "priority": {
            "source": "inherit",
            "value": null
        },
        "change_frequency": {
            "source": "inherit",
            "value": null
        }
    },
    "published": true,
    "_blueprint": "testen"
}
```
</details>

I'll try to look into it later if I find some more time.
