### ISSUE TITLE
Grid fields with localization enabled still have read-only on fields inside when using stacked mode

### ISSUE THREAD

**Issue by jesperlindstrom** [statamic/cms#3498]
## Bug Description
It's not possible to translate fields that are inside a grid, even if the grid have the "localize" globe enabled. 

## How to Reproduce
Create a grid with a text field inside. Make the grid localizable. Create a translation of a page and you'll find the fields as "read only".

## Extra Detail

We have set up the grid field like this:
<img width="444" alt="Skärmavbild 2021-04-08 kl  15 12 56" src="https://user-images.githubusercontent.com/1730738/114032933-1d9b8f00-987d-11eb-9857-fdc4cbd3f13e.png">
<img width="1038" alt="Skärmavbild 2021-04-08 kl  15 15 31" src="https://user-images.githubusercontent.com/1730738/114033137-4754b600-987d-11eb-9d3c-83d4574dca3a.png">

The field code looks like this in the blueprint (as generated by the GUI, not hand coded)
```yaml
- handle: independent_bullets
field:
  fields:
    - handle: title
      field:
        input_type: text
        antlers: false
        display: Title
        type: text
        icon: text
        listable: hidden
    - handle: text
      field:
        input_type: text
        antlers: false
        display: Text
        type: text
        icon: text
        listable: hidden
  mode: stacked
  reorderable: true
  display: "Independent bullets"
  type: grid
  icon: grid
  localizable: true
  listable: hidden
```

We have Swedish as base language and English as a translation. In English, the field gets displayed as "read only": 
<img width="339" alt="Skärmavbild 2021-04-08 kl  15 12 18" src="https://user-images.githubusercontent.com/1730738/114032941-1eccbc00-987d-11eb-9763-fc42efcfa7f2.png">

We found a workaround by manually adding `localizable: true` to the actual fields inside the grid (which can only be done in code, there are no "globes" to click in the GUI on the fields inside the grid).
```yaml
- handle: independent_bullets
field:
  fields:
    - handle: title
      field:
        input_type: text
        antlers: false
        display: Title
        type: text
        icon: text
        listable: hidden
        localizable: true
    - handle: text
      field:
        input_type: text
        antlers: false
        display: Text
        type: text
        icon: text
        listable: hidden
        localizable: true
  mode: stacked
  reorderable: true
  display: "Independent bullets"
  type: grid
  icon: grid
  localizable: true
  listable: hidden
```

That made it work properly:
<img width="268" alt="Skärmavbild 2021-04-08 kl  15 12 40" src="https://user-images.githubusercontent.com/1730738/114032981-28eeba80-987d-11eb-867a-302858de54e1.png">

## Environment
Statamic 3.1.5 Pro
Laravel 6.20.22
PHP 7.4.15
statamic/seo-pro 2.2.0
statamic/ssg dev-master

**Install method (choose one):**
Starter kit
