### ISSUE TITLE
"Changes you made may not be saved."

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#3500]
## Bug Description

What I know so far:
- Saving again doesn't help
- It happens on random entries
- They stay the "broken ones", no changes here
- It happens on blueprints with bard, but also with the default link blueprint or even on the collection configuration page
- Nothing to see in the logs or in the console
- It doesn't matter, if it is a multisite or not

## How to Reproduce
No idea.

## Extra Detail
![Bildschirmfoto 2021-04-08 um 17 28 52](https://user-images.githubusercontent.com/6337411/114054724-66107800-9890-11eb-9845-f8fa6b8d615e.png)
![Bildschirmfoto 2021-04-08 um 16 50 55](https://user-images.githubusercontent.com/6337411/114054025-c357f980-988f-11eb-937d-be3ec1a6df2f.png)
![Bildschirmfoto 2021-04-08 um 17 28 15](https://user-images.githubusercontent.com/6337411/114054830-7c1e3880-9890-11eb-81f6-454aecdb03ef.png)

## Environment
Statamic 3.1.5 Pro
Laravel 8.35.1
PHP 7.4.15
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by j3ll3yfi5h** [comment]
@jackmcdade Can only confirm, that #3605 fixed my settings page. The other two are still "dirty".

**Comment by j3ll3yfi5h** [comment]
@jackmcdade Should I open a new issue?

**Comment by jackmcdade** [comment]
What fields are on the page(s) that show that message?

**Comment by j3ll3yfi5h** [comment]
First: The strangest one with just a redirect...

![Bildschirmfoto 2021-07-06 um 08 28 29](https://user-images.githubusercontent.com/6337411/124552695-2c6def80-de34-11eb-94db-eeb7c670df06.png)

**Blueprint:**
```
title: Verknüpfen
sections:
  main:
    display: Hauptteil
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          localizable: true
          validate:
            - required
      -
        handle: redirect
        field:
          type: link
          localizable: true
          validate:
            - required
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
            - 'unique_entry_value:{collection},{id},{site}'
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true

```

**Content:**
```
---
title: Reparatur
redirect: '@child'
updated_by: 473a9b9b-d9af-4434-a3a0-73828851bca6
updated_at: 1613549462
id: 37112be7-1c2e-485b-858c-a11a83092a82
blueprint: link
---

```
