### ISSUE TITLE
Taxonomy URLs on collections don't work

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#3554]
## Bug Description
Taxonomy URLs aren't registered. Result in 404.

## How to Reproduce
Mount a collection and assign taxonomies to it. Create a ``show.antlers.html`` and/or ``index.antlers.html`` in the ``views/{collection}/{taxonomy}`` folder. 

Usually, this should trigger the CMS to register the URLs, somehow though, these 404.

## Environment
Laravel Valet

**Statamic version:** 3.1.9

**PHP version:** 7.4

**Install method (choose one):**
- Used Laravel installation

**Comment by jasonvarga** [comment]
- Whats the collection's handle?
- What's inside the `content/collection/{handle}.yaml` file?
- What's the taxonomy handle?

**Comment by AndreasSchantl** [comment]
> * Whats the collection's handle?

The collection's handle is ``blog``


> * What's inside the `content/collection/{handle}.yaml` file?

```yaml
title: Blog
template: blog/show
layout: layout
mount: 1664ffef-6815-4365-a13f-7ff6238e0f08
taxonomies:
  - tags
  - categories
revisions: false
route: '{mount}/{slug}'
date: true
sort_dir: desc
date_behavior:
  past: public
  future: private
```

> * What's the taxonomy handle?

The handles are ``tags`` and ``categories``
