### ISSUE TITLE
Fieldtype date range does not respect formatting

### ISSUE THREAD

**Issue by grischaerbe** [statamic/cms#3635]
## Bug Description

When a field of type date with the option "range" is added to a blueprint, the formatting options are not respected and the field is saved in the standard formatting of Carbon: `Y-m-d` or if a time is set: `Y-m-d H:i:s`.

## How to Reproduce

- fresh install of `statamic/statamic`
- Add a date field to any blueprint, be careful to change the handle to something different than "date"
- Enable the range option and change the formatting to something different like "c" for the ISO8601 string formatting
- Add an entry, set some date range, save the entry and find the corresponding .md file, it will contain a date like this: 

```yaml
duration:
  start: '2021-05-02'
  end: '2021-05-28'
```

## Environment

- Statamic 3.1.11 Solo
- Laravel 8.40.0
- PHP 8.0.3
- No addons installed

**Statamic version:** 3.1.11

**PHP version:** 8.0.3

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Can you show the blueprint containing this date field?

**Comment by grischaerbe** [comment]
This is the blueprint:

```yaml
title: Pages
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: content
        field:
          type: markdown
          display: Content
          localizable: true
      -
        handle: author
        field:
          type: users
          display: Author
          default: current
          localizable: true
          max_items: 1
      -
        handle: template
        field:
          type: template
          display: Template
          localizable: true
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
      -
        handle: duration
        field:
          mode: range
          time_enabled: false
          time_required: false
          earliest_date: '1900-01-01'
          format: c
          full_width: false
          inline: true
          columns: 1
          rows: 1
          display: Duration
          type: date
          icon: date
          listable: hidden

```

This is the output .md:

```yaml
---
id: home
title: Home
template: home
author: e3b0be0e-d073-469f-b4c0-9377fb1a8001
updated_by: e3b0be0e-d073-469f-b4c0-9377fb1a8001
updated_at: 1620083384
duration:
  start: '2021-05-01'
  end: '2021-05-31'
---
Welcome to your new Statamic website.
```
