### ISSUE TITLE
Internal links and title attribute are getting stripped out in GraphQL queries

### ISSUE THREAD

**Issue by el-schneider** [statamic/cms#3686]
## Bug Description
an internal link created with bard like this:

```yaml
-
  type: text
  marks:
    -
      type: link
      attrs:
        href: 'statamic://entry::f9250d29-35f8-41e8-a30a-b21f43d93871'
        rel: null
        target: null
        title: Netflix
  text: Netflix
```
produces this:
```html
<a href=\"/\">Netflix</a>
```

## How to Reproduce
query a bard `link` with GraphQL

## Environment

Statamic 3.1.12 Pro
Laravel 8.39.0
PHP 7.4.19

**Install method (choose one):**
- Fresh install from `statamic/statamic`
