### ISSUE TITLE
Entries are not translated inside partial

### ISSUE THREAD

**Issue by tobiasdierich** [statamic/cms#3723]
## Bug Description

Entries of a `entries` field are not translated. I have a multisite running with two locales, `english` and `german` and a collection of frequently asked questions, the content of which is translatable. If I loop over the entries using the collection tag `{{ faqs }}`, translation works fine. However, if I wrap this loop inside another partial, in order to render the faqs into the slot of that partial, translation no longer works and I always get the english translation. The rest of the page, however, is still correctly translated.

## How to Reproduce

Render entries as a partial inside the slot of another partial. See below for example code snippets.

## Extra Detail
Blueprint of the FAQ collection
```YAML
title: FAQ
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          display: Frage
          validate:
            - required
          localizable: true
      -
        handle: content
        field:
          type: markdown
          display: Antwort
          localizable: true
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
```

FAQs collection
```YAML
title: FAQs
sites:
  - german
  - english
revisions: false
date_behavior:
  past: public
  future: private
```

Page template (translation works)
```HTML
<div class="py-32">
    <div class="container">
        <div class="lg:px-32">
                {{ faqs }}
                    {{ partial:partials/faq-details }}
                {{ /faqs }}
        </div>
    </div>
</div>
```

Page template (translation not working)
```HTML
<div class="py-32">
    <div class="container">
        <div class="lg:px-32">
            {{ partial:partials/faqs-container }}
                {{ faqs }}
                    {{ partial:partials/faq-details }}
                {{ /faqs }}
            {{ /partial:partials/faqs-container }}
        </div>
    </div>
</div>
```

## Environment

Statamic 3.1.14 Pro
Laravel 8.41.0
PHP 7.4.16
No addons installed

**Statamic version:** 3.1.14

**PHP version:** 7.4.16

**Install method (choose one):**
- Fresh install from `statamic/statamic`
