### ISSUE TITLE
Modifiers not working on dynamically called global collection

### ISSUE THREAD

**Issue by hmalaud** [statamic/cms#3724]
## Bug Description
When accessing a global set dynamically (`my_global[var]`), adding a modifier causes the collection to output nothing.

## How to Reproduce

1. Create global set file. E.g. `dev.yaml`
```
title: Dev
data:
  full_images:
    -
      image_width: 1600
      media_query: '(orientation: landscape) and (min-width: 1600px)'
      default_size: false
      type: size
      is_portrait: false
      enabled: true
    -
      image_width: 1920
      media_query: '(orientation: landscape) and (min-width: 1920px)'
      default_size: false
      type: size
      is_portrait: false
      enabled: true
    -
      image_width: 1440
      media_query: '(orientation: landscape) and (min-width: 1440px)'
      default_size: false
      type: size
      is_portrait: false
      enabled: true
    -
      image_width: 1280
      media_query: '(orientation: landscape) and (min-width: 1280px)'
      default_size: true
      type: size
      is_portrait: false
      enabled: true
    -
      image_width: 1152
      image_height: 2050
      media_query: '(orientation: portrait) and (min-width: 1152px)'
      default_size: false
      type: size
      is_portrait: false
      enabled: true
```
3. Create partial. E.g. `picture.antlers.html` 
``` 
   {{ dev:full_images where="default_size:1" }} // or sort/group_by/...
      Not dynamic, this shows in template
   {{ /dev:full_images }}

   {{ dev[gset] }}
      Dynamic, shows in template
   {{ /dev[gset] }}

   {{ dev[gset] where="default_size:1" }} // or sort/group_by/...
      Dynamic, this doesn't show in template
   {{ /dev[gset] }}
```
4. Call partial from template. E.g. `{{ partial:partials/picture gset="full_images" }}`

## Environment
**Statamic version:** 3.1.14
**PHP version:** 8.0.2
**Laravel version:** 8.41.0

**Install method:**
- Fresh install from `statamic/statamic` 
(Statamic's CLI (`statamic new ...`))
