### ISSUE TITLE
Where modifier not working with exists (Antlers)

### ISSUE THREAD

**Issue by hmalaud** [statamic/cms#3733]
## Bug Description
After [discussing](https://discordapp.com/channels/489818810157891584/489819906540568593/843894307492593664) it on Discord, it seems there is no working Antlers way to use `exists` in the `where` modifier with Antlers. 
(Sorry guys for bothering you around these similar problems lately!)

## How to Reproduce
Create array of objects. E.g.
```
  full_images:
    -
      image_width: 1600
      media_query: '(orientation: landscape) and (min-width: 1600px)'
      default_size: false
      type: size
      enabled: true
    -
      image_width: 1920
      media_query: '(orientation: landscape) and (min-width: 1920px)'
      default_size: false
      type: size
      image_height: 2500
      enabled: true
    -
      image_width: 1440
      media_query: '(orientation: landscape) and (min-width: 1440px)'
      default_size: false
      type: size
      enabled: true
    -
      image_width: 1280
      media_query: '(orientation: landscape) and (min-width: 1280px)'
      default_size: true
      type: size
      enabled: true
```
Loop in template with `where` modifier to check existence:
```
{{ full_images where="image_height|exists" }}
  No output
{{ /full_images }}
```
But this works:
```
{{ full_images where="image_height:2500" }} {{# not` image_height|2500` btw #}}
  Output OK
{{ /full_images }}
```

## Environment
**Statamic version:** 3.1.14
**PHP version:** 8.0.2
**Laravel version:** 8.41.0

**Install method:**
- Fresh install from `statamic/statamic` 
(Statamic's CLI (`statamic new ...`))
