### ISSUE TITLE
Date field shows wrong date and time

### ISSUE THREAD

**Issue by aerni** [statamic/cms#3748]
## Bug Description
I just came across a really weird date bug I didn't notice before. It seems like the date field is living in the past. It shows the wrong day, month, and year. And the time is always the current time. I took this screenshot at `19:52` on my machine:

<img width="433" alt="Bildschirmfoto 2021-05-20 um 7 56 11 PM" src="https://user-images.githubusercontent.com/23167701/119026416-6fb7f000-b9a5-11eb-9f5f-92264215434f.png">

The data is saved as a timestamp. The timestamp is `1621525900`. If you format the same timestamp with Carbon it returns the correct date and time:

```php
Carbon::createFromTimestamp('1621525900')->toDateTimeString();

// Output: "2021-05-20 15:51:40"
```

## How to Reproduce
1. Add this field to your blueprint:

```yaml
handle: pledge_date
  field:
    type: date
    required: true
    validate:
        - required
    display: Date
    listable: true
    mode: single
    time_enabled: true
    time_required: true
    earliest_date: '2021-01-01'
    full_width: false
    inline: false
    columns: 1
    rows: 1
    read_only: true
    format: U
    instructions: 'The time this pledge was made'
    width: 50
```

2. Add this data to your content file:

```md
pledge_date: 1621525900
```

3. Check your entry in the CP.

## Environment
Statamic 3.1.14 Pro
Laravel 8.42.1
PHP 7.4.16
aerni/social-links 2.2.0
jonassiewertsen/statamic-livewire 2.5.0
visuellverstehen/statamic-classify 2.1.1
