### ISSUE TITLE
Date in entry listing is not localized

### ISSUE THREAD

**Issue by aerni** [statamic/cms#3787]
## Bug Description
The date is not localized in the entry listing. It displays `18. May 2021 13:17`. It should be `18. Mai 2021 13:17` instead. The date is localized correctly in the fieldtype itself.

## How to Reproduce
1. Set `'date_format' => 'j. F Y'` in the `cp.php` config

2. Create a user and add a locale setting:

```yaml
preferences:
  locale: de
```

3. Add this field to your blueprint:

```yaml
handle: pledge_date
field:
  type: date
  required: true
  validate:
    - required
  display: Date
  listable: true
  mode: single
  time_enabled: true
  time_required: true
  earliest_date: '2021-01-01'
  full_width: false
  inline: false
  columns: 1
  rows: 1
  read_only: true
  format: U
  instructions: 'The time this pledge was made'
  width: 50
```

4. Create an entry and set a date
5. Look at the date in the entry listing

## Extra Detail
<img width="1652" alt="Bildschirmfoto 2021-05-29 um 12 07 29 PM" src="https://user-images.githubusercontent.com/23167701/120066403-74039d80-c076-11eb-8dce-84e6eb32c181.png">

## Environment
Statamic 3.1.18 Pro
Laravel 8.44.0
PHP 7.4.16
aerni/social-links 2.2.0
jonassiewertsen/statamic-livewire 2.5.0
visuellverstehen/statamic-classify 2.1.1
