### ISSUE TITLE
Nested field within bard > replicator > bard does not validate properly as required

### ISSUE THREAD

**Issue by claasjansen** [statamic/cms#3789]
## Bug Description
I have the following setup: Page Blueprint > Bard Field > Bard set containing a replicator > Replicator set containing a bard field > Bard set containing a required text field. Text fieldtype in this case but others don't seem to work either. In this setup the field at the bottom of the hierarchy does not validate properly. Even when the field is filled it is still marked as required when validated.

## How to Reproduce
Page blueprint below. Fill out 'required_text_in_replicator' field and it should not validate correctly.

## Extra Detail
```
title: 'Replicator Test'
sections:
  main:
    display: Hauptteil
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: bard
        field:
          always_show_set_button: false
          sets:
            replicator:
              display: Replicator
              fields:
                -
                  handle: replicator
                  field:
                    collapse: false
                    sets:
                      bard_in_replicator:
                        display: 'Bard in Replicator Set'
                        fields:
                          -
                            handle: replicator_title
                            field:
                              input_type: text
                              antlers: false
                              display: 'Replicator title'
                              type: text
                              icon: text
                              listable: hidden
                              validate:
                                - required
                          -
                            handle: bard_in_replicator
                            field:
                              always_show_set_button: false
                              sets:
                                required_text_set:
                                  display: 'Required Text Set'
                                  fields:
                                    -
                                      handle: required_text_in_replicator
                                      field:
                                        input_type: text
                                        antlers: false
                                        display: 'Required Text in Replicator'
                                        type: text
                                        icon: text
                                        listable: hidden
                                        validate:
                                          - required
                              buttons:
                                - h2
                                - h3
                                - bold
                                - italic
                                - unorderedlist
                                - orderedlist
                                - removeformat
                                - quote
                                - anchor
                                - image
                                - table
                              save_html: false
                              toolbar_mode: fixed
                              link_noopener: false
                              link_noreferrer: false
                              target_blank: false
                              reading_time: false
                              fullscreen: true
                              allow_source: true
                              enable_input_rules: true
                              enable_paste_rules: true
                              display: 'Bard in replicator'
                              type: bard
                              icon: bard
                              listable: hidden
                    display: Replicator
                    type: replicator
                    icon: replicator
                    listable: hidden
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          display: Bard
          type: bard
          icon: bard
          listable: hidden
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
```

## Environment
Statamic 3.1.18 Pro
Laravel 8.44.0
PHP 7.4.16
edalzell/blade-directives 3.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`
