### ISSUE TITLE
Exception: "Root page cannot have children" in pages collection

### ISSUE THREAD

**Issue by rrelmy** [statamic/cms#3791]
## Bug Description
I believe it is related to multi-site setups

We have a site in development where we got the exception after the customer localized some sub-pages, they did not touch the home page.

In the tree files for the non-primary locales the `home` was missing and another page was the first in the tree. The `home` pages have already some translations in all languages.

What we had

``` yaml
tree:
  -
    entry: 84c597d7-52a9-4ab7-b06b-97fc492252b2
    children:
      -
        entry: b635d8ab-6a06-44ab-b3fe-67929f03b2a4
      -
        entry: e9788ce7-407d-409c-a7d2-10bd7cc07591
```

I just added the `entry: home` to fix it

``` yaml
tree:
  -
    entry: home
  -
    entry: 84c597d7-52a9-4ab7-b06b-97fc492252b2
    children:
      -
        entry: b635d8ab-6a06-44ab-b3fe-67929f03b2a4
      -
        entry: e9788ce7-407d-409c-a7d2-10bd7cc07591
```

## How to Reproduce

Starting from a fresh clone of statamic/statamic and after running following commands

```
composer update
cp .env.example .env
php artisan key:generate
```

1. Create a multi-site setup `php please multisite`
2. Add another page in the pages collection
3. Add sub-pages to this page
4. Localize and publish the page created in step 2
5. (Try to) Localize the page created in step 3 (It shows a loader but never ends)
6. Clear the cache

## Extra Detail
Might relate to #1666 

## Environment

Statamic 3.1.18 Pro
Laravel 8.44.0
PHP 8.0.6
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`
