### ISSUE TITLE
fields in blueprint that reference a fieldset slow down the index listing

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#381]
I have a `fieldsets/bard.yaml` like this:

```
title: Bard Configs
fields:
  basic:
    type: bard
    allow_source: false
    fullscreen: false # waiting for statamic to add this
    save_html: true
    restrict_assets: true
    buttons: [ bold, italic, underline ]
  basic+:
    type: bard
    allow_source: false
    fullscreen: false # waiting for statamic to add this
    save_html: true
    restrict_assets: true
    buttons: [ bold, italic, underline, link ]
```

I define a field in `blueprints/article.yaml` that references one of the bard fields:

```
title: Article
taxonomies: false
sections:
  main:
    fields:
      -
        handle: title
        field:
          type: text
          localizable: true
      -
        handle: intro
        field: bard.basic
        config:
          display: Teaser
          link_noopener: true
          link_noreferrer: true
          target_blank: true
          show_text_count: true
          spellcheck: false
          listable: false
```

This makes the article listing load super slow, if at all. Removing the references to the fieldset speeds the listing up to expected performance.
