### ISSUE TITLE
Multisite blueprint regression 3.1.19

### ISSUE THREAD

**Issue by rrelmy** [statamic/cms#3814]
## Bug Description
3.1.19 introduced a regression with multisite localisations.
Creating a localised entry adds a wrong blueprint to the entry.

## How to Reproduce

1. Create a multisite setup
2. Define 2 different blueprints
3. Create a page with the second blueprint
4. Localise the page

## Extra Detail
Prior to 3.1.19 the localised entry looked like this
``` yaml
id: d5d3047a-c27b-4665-95d8-723f9b9a5186
origin: d42bbc2e-fbd5-4287-b8a7-5256f5927acc
published: false
updated_by: 28dd9fd9-b7b1-4703-aa38-ecdbe038372e
updated_at: 1623232119
```

using 3.1.19 or 3.1.20 will create this
``` yaml
id: d61b1873-dc06-45b0-99dc-371052828acf
origin: d42bbc2e-fbd5-4287-b8a7-5256f5927acc
published: false
blueprint: asset # <------- This one is new and wrong
updated_by: 28dd9fd9-b7b1-4703-aa38-ecdbe038372e
updated_at: 1623232161
```

The origin entry looks like this
``` yaml
---
id: d42bbc2e-fbd5-4287-b8a7-5256f5927acc
blueprint: other_pages
title: Foo
template: default
parent: 7be9fb0f-16cf-406b-9b45-0bb05564c83e
updated_by: 85c18159-3ea4-4a80-80b6-bd72c558211b
updated_at: 1622789532
---

```

## Environment
**Statamic version:** 3.1.19, 3.1.20

**PHP version:** 8.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`
