### ISSUE TITLE
In the Assets fieldtype, with the option 'restrict: true', it is still possible to go up one folder in the asset browser

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#3824]
## Bug Description

1. Edit a blueprint with an asset fieldtype and switch the toggle option 'Restrict: Prevent users from navigating to other folders.' on.

```
-
  handle: portrait
  field:
    mode: grid
    container: assets
    folder: mitarbeiter_innen
    restrict: true
    allow_uploads: true
    max_files: 1
    display: Portrait
    type: assets
    icon: assets
    instructions: 'Don't forget to set the focus point.'
    listable: true
    validate:
      - 'mimes:jpg,jpeg,png'
```

2. Edit an entry with this blueprint. The navigation within the asset browser won't be fully disabled and is still possible (1). Although then no more folders are displayed on the upper level. Neither the originally defined nor others (2).

<img width="264" alt="Bildschirmfoto 2021-06-10 um 10 08 41" src="https://user-images.githubusercontent.com/8265902/121489786-b614d380-c9d4-11eb-9079-ac852a1652ae.png">

<img width="399" alt="Bildschirmfoto 2021-06-10 um 10 09 55" src="https://user-images.githubusercontent.com/8265902/121489952-e0669100-c9d4-11eb-8470-becbd6d2dbb1.png">

## Environment

Statamic 3.1.21 Pro
Laravel 8.46.0
PHP 7.4.20
rias/statamic-color-swatches 2.0.5
rias/statamic-redirect 1.4.6
statamic/seo-pro 2.2.1

- Fresh install from `statamic/statamic`
