### ISSUE TITLE
multisite: collection with inherited 'date' property doesn't update 

### ISSUE THREAD

**Issue by verybigelephants** [statamic/cms#3826]
## Bug Description
When you run a multilingual site and use "date" property (which tells when the item should be published) that is not localizable but inherited from the main language: creating an entry works fine and the translated collection item has the "date" correctly, creating a yaml file like _2021-05-03.slug.md_, but when the original item's date is updated, the change on the translated articles doesn't happen and the item keeps the old date. 

probably because the date property is not stored in the .yaml file like the rest of the data but right in the filename

## How to Reproduce
on a multisite-enabled instance:

 * create a collection that has a 'date' property and make it non-translatable
 * create an entry, set the date
 * create a translated instance of the article
 * update original article's date
 * observe that the translated .yaml filename doesn't change and hence the item has the old date, that is not updatable

## Extra Detail
here's a blueprint for a simple collection that has this property:

```
title: News
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
          localizable: true
      -
        handle: perex
        field:
          always_show_set_button: false
          buttons:
            - bold
            - italic
            - removeformat
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: false
          allow_source: false
          enable_input_rules: true
          enable_paste_rules: true
          display: Perex
          type: bard
          icon: bard
          localizable: true
          listable: hidden
          validate:
            - required
      -
        handle: body
        field:
          always_show_set_button: false
          buttons:
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: false
          enable_input_rules: true
          enable_paste_rules: true
          display: Body
          type: bard
          icon: bard
          localizable: true
          listable: hidden
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: date
        field:
          type: date
          required: true
          validate:
            - required
          display: 'Publish at'
          listable: hidden
          mode: single
          time_enabled: true
          time_required: false
          earliest_date: '2000-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
      -
        handle: image
        field:
          mode: grid
          container: assets
          folder: news
          restrict: false
          allow_uploads: true
          max_files: 1
          display: Image
          type: assets
          icon: assets
          listable: hidden

```

## Environment

```
Statamic 3.1.21 Pro     
Laravel 8.38.0          
PHP 8.0.3               
No addons installed 
```

**Statamic version:** 
3.1.21 Pro

**PHP version:** 
8.0.0

**Install method (choose one):**
Fresh install from `statamic/statamic`
