### ISSUE TITLE
Error when deleting entries in the CP

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#3839]
## Bug Description

When deleting an entry, this error message appears. After reloading the page, however, the entry is deleted. It could be related with https://github.com/statamic/cms/issues/3600. But this one is already closed. 

<img width="1821" alt="error message" src="https://user-images.githubusercontent.com/8265902/121801028-74cf2e80-cc35-11eb-97fb-a6190dd847b0.png">

## How to Reproduce

- fresh install from statamic/statamic
- create a new collection in the CP with following settings (please note: date_behavior ist not used, but added in the yaml-file when configure the collection in the CP).

```
title: Test
template: test/show
layout: layout
revisions: false
route: 'test/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
structure:
  root: false
  max_depth: 1
```

- add a new page
- try to delete it

It doesn't make a difference if the `/conten/tree/collections/test.yaml` file is empty 

`{  }` 

or has entries listed after reordering the pages in the CP.

```
tree:
  -
    entry: df730002-eec2-42f4-8d64-41a04e4ce9be
  -
    entry: 185aaac6-f8b5-490e-941e-2af2dee2dafe
  -
    entry: 59d6af47-b87c-4c9f-a44b-0bebf7160c3c

```

## Environment

Statamic 3.1.22 Solo
Laravel 8.46.0
PHP 7.4.20
No addons installed

- fresh install from `statamic/statamic`
