### ISSUE TITLE
Date field UI fiasco

### ISSUE THREAD

**Issue by aerni** [statamic/cms#3897]
## Bug Description
The Date field with time enabled looks super funky in a Grid in Table mode.

## How to Reproduce
Add this field to your blueprint:
```yaml
handle: exceptions
  field:
    fields:
      -
        handle: from
        field:
          mode: single
          time_enabled: true
          time_required: false
          earliest_date: '1900-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: From
          type: date
          icon: date
          listable: hidden
          validate:
            - required
      -
        handle: from
        field:
          mode: single
          time_enabled: true
          time_required: false
          earliest_date: '1900-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: From
          type: date
          icon: date
          listable: hidden
          validate:
            - required 
    mode: table
    add_row: 'Add Exception'
    reorderable: true
    display: Exceptions
    type: grid
    icon: grid
    listable: hidden
```

## Extra Detail
<img width="989" alt="Bildschirmfoto 2021-06-23 um 11 45 10 AM" src="https://user-images.githubusercontent.com/23167701/123075373-790b0100-d418-11eb-8299-ca87667eeb5c.png">

## Environment
Statamic 3.1.26 Pro
Laravel 8.48.0
PHP 7.4.20
spatie/statamic-responsive-images 2.5.4
