### ISSUE TITLE
Form Submissions Overview: datestamp column not shown when other columns are selected

### ISSUE THREAD

**Issue by RafaelKr** [statamic/cms#3966]
## Bug Description
I created a form with multiple columns. On the form submissions overview page (`/cp/forms/competition`) I toggled the visibility of some columns. Now my date column is not visible when reloading the page, although the user preferences are looking correct:

```yaml
preferences:
  forms:
    competition:
      columns:
        - datestamp
        - firstname
        - lastname
        - file
```

I can enable "Date" and click save, then it's shown, but after reloading the column is missing again.
The other 3 columns are shown.

In the network panel it does a request to the following URL: `/cp/forms/competition/submissions?sort=datestamp&order=desc&page=1&perPage=50&search=&filters=e30=&columns=firstname,lastname,file`

Notice the columns parameter is also missing the `datestamp`. The result of this request looks like this:

![image](https://user-images.githubusercontent.com/14234815/124758164-979bec80-df2e-11eb-901e-5597640884a0.png)

## How to Reproduce
1. Create a form with some columns.
2. Make at least 1 submission.
3. Go to your form submissions overview.
4. Enable some more columns (keep "Date" enabled!) with the settings icon (![image](https://user-images.githubusercontent.com/14234815/124758773-36284d80-df2f-11eb-880d-bbf44e8648eb.png))
5. Reload the page
6. Date column should be missing although it wasn't disabled

## Additional notes
I have an image upload column which I have enabled. There is a small preview of the images. It would be great if it would open that file in a new tab on click! (Currently I can only right-click and "Open image in New Tab)
I can create an own issue for that if you like me to.

## Environment

Statamic 3.1.27 Solo
Laravel 8.48.0
PHP 7.4.16
octoper/statamic-blade-components 1.0.1

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
What does your form blueprint look like?

**Comment by RafaelKr** [comment]
I can also give access to the private GitLab Repo if that would help.

That's my blueprint:

<details>
<summary>resources/blueprints/forms/competition.yaml</summary>

```yaml
sections:
  main:
    display: Main
    fields:
      -
        handle: firstname
        field:
          input_type: text
          antlers: false
          display: Firstname
          type: text
          icon: text
          listable: hidden
          validate:
            - required
      -
        handle: lastname
        field:
          input_type: text
          antlers: false
          display: Lastname
          type: text
          icon: text
          listable: hidden
          validate:
            - required
      -
        handle: street
        field:
          input_type: text
          antlers: false
          display: Street
          type: text
          icon: text
          width: 66
          listable: hidden
          validate:
            - required
      -
        handle: housenumber
        field:
          input_type: text
          antlers: false
          display: Housenumber
          type: text
          icon: text
          width: 33
          listable: hidden
          validate:
            - required
      -
        handle: city
        field:
          input_type: text
          antlers: false
          display: City
          type: text
          icon: text
          width: 66
          listable: hidden
          validate:
            - required
      -
        handle: zip
        field:
          input_type: text
          antlers: false
          display: Zip
          type: text
          icon: text
          width: 33
          listable: hidden
      -
        handle: state
        field:
          input_type: text
          antlers: false
          display: State
          type: text
          icon: text
          listable: hidden
          validate:
            - required
      -
        handle: country
        field:
          input_type: text
          antlers: false
          display: Country
          type: text
          icon: text
          listable: hidden
          validate:
            - required
      -
        handle: company_name
        field:
          input_type: text
          antlers: false
          display: 'Company Name'
          type: text
          icon: text
          listable: hidden
          validate:
            - required
      -
        handle: email
        field:
          input_type: text
          antlers: false
          display: 'Mail Address'
          type: text
          icon: text
          listable: hidden
          validate:
            - required
            - email
      -
        handle: creator_consent
        field:
          inline: false
          display: 'Creator Consent'
          type: checkboxes
          icon: checkboxes
          listable: hidden
          validate:
            - required
            - accepted
      -
        handle: majority_age_consent
        field:
          inline: false
          display: 'Majority Age Consent'
          type: checkboxes
          icon: checkboxes
          listable: hidden
          validate:
            - required
            - accepted
      -
        handle: copyright_holder_consent
        field:
          inline: false
          display: 'Copyright Holder Consent'
          type: checkboxes
          icon: checkboxes
          listable: hidden
          validate:
            - required
            - accepted
      -
        handle: file
        field:
          mode: grid
          restrict: true
          allow_uploads: true
          max_files: 1
          display: File
          type: assets
          icon: assets
          listable: hidden
          validate:
            - required
          container: competition
          folder: competition
```

</details>
