### ISSUE TITLE
Date picker field not displaying value

### ISSUE THREAD

**Issue by byron-roots** [statamic/cms#3986]
## Bug Description
Datepickers are no longer showing the value of the field, but still save the selected value. Opening the datepicker and selecting a date updates the value of the field, but doesn't visually display the date. Error in the console is as follows. 

```
v-calendar.umd.min.js:formatted:12217 TypeError: t.DoFn is not a function
    at Object.Do (v-calendar.umd.min.js:formatted:12217)
    at v-calendar.umd.min.js:formatted:12217
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at v-calendar.umd.min.js:formatted:12217
    at _.format (v-calendar.umd.min.js:formatted:12217)
    at pe.format [as _format] (v-calendar.umd.min.js:formatted:12217)
    at pe.format (v-calendar.umd.min.js:formatted:12217)
    at a.<anonymous> (v-calendar.umd.min.js:formatted:12217)
    at Array.<anonymous> (v-calendar.umd.min.js:formatted:12217)
```

## How to Reproduce

Not sure when the issue started occurring but think it aligns with  #3730. I do have some custom. I remember being able to set a moment time format before, and since that has been removed the issue has been happening. Is there a way to rebuild the vendor assets for statamic?

## Extra Detail
Here's the the Vue debug of the date field, as you can see there is a value set but nothing is shown to the user
<img width="569" alt="Screenshot 2021-07-13 at 11 19 33" src="https://user-images.githubusercontent.com/38127763/125437476-75d8ca6e-6910-461b-8641-a35084d69d41.png">
<img width="328" alt="Screenshot 2021-07-13 at 11 19 00" src="https://user-images.githubusercontent.com/38127763/125437477-44f0b354-c2c6-4643-85ab-0b1dadc9dbb5.png">

## Environment
Statamic 3.1.27 Pro
Laravel 8.48.0
PHP 7.4.12
aryehraber/statamic-logbook 2.0.2
aryehraber/statamic-splash 1.0.5
mattrothenberg/statamic-mapbox-address 0.6.0
rias/statamic-color-swatches 2.0.5
statamic/collaboration 0.1.0

**Statamic version:** 3.2.7

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Whats the `date_format` in `config/statamic/cp.php`?

**Comment by byron-roots** [comment]
Date format is set to ` 'date_format' => 'jS F Y',`

and here is one of the date fields
```
handle: date
        field:
          type: date
          required: true
          validate:
            - required
          display: 'Start date'
          listable: hidden
          mode: single
          time_enabled: false
          time_required: false
          earliest_date: '1900-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          format: Y-m-d
```
