### ISSUE TITLE
Bard allows saving with empty code blocks, but won't load with them.

### ISSUE THREAD

**Issue by fitzage** [statamic/cms#4037]
## Bug Description

I had a user save a page in progress that had an empty code block in a Bard field. When reloading the page, the entire Bard field was empty with the following console error:

![image](https://user-images.githubusercontent.com/1958/126566304-ef1860f1-e0d1-41ac-abd4-c8c3b7dd0797.png)

The easiest solution would seem to me for Statamic not to allow saving the page with this empty code block so that it won't result in the error on load.

## How to Reproduce

1. Add a code block to a bard field.
2. Don't insert any content into the code block.
3. Save the page.
4. Reload

## Environment

Statamic 3.1.29 Pro
Laravel 8.51.0
PHP 7.4.20
statamic/migrator dev-master
statamic/seo-pro 2.2.1
statamic/ssg 0.7.0
transformstudios/review 3.1

- Fresh install from `statamic/statamic`, migrated, upgraded myriad times

**Comment by arthurperton** [comment]
Hi @fitzage, I am not able to reproduce this. I tried your steps in Chrome and Safari and Bard just shows the empty code block (and any other content) after the reload. Without any errors or warnings. I am currently on v3.1.32.

Can you try this in the latest version and / or elaborate on the steps to reproduce?

**Comment by fitzage** [comment]
I have not installed any updates, but I also can no longer duplicate this. I wonder if it's related to the specific page in question or something. I will poke around more, but I guess this can probably be closed.

**Comment by arthurperton** [comment]
Thanks, I'll close the issue for now. For future reference, if this one pops up again: 

<details>
  <summary>I was able to cause the error by manually editing the content file.</summary>

A code block is saved like this:
```yaml
 -
    type: paragraph
    content:
      -
        type: text
        text: 'Content before code block'
  -
    type: code_block
    content:
      -
        type: text
        text: 'some brilliant code'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Content after code block'
```

An empty code block in the editor is saved (and successfully loaded and displayed) like this, without the `content` part:
```yaml
 -
    type: paragraph
    content:
      -
        type: text
        text: 'Content before code block'
  -
    type: code_block
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Content after code block'
```

If however you leave the `content` bit with an empty string for `text`, you'll get the exact error described in this issue:
```yaml
 -
    type: paragraph
    content:
      -
        type: text
        text: 'Content before code block'
  -
    type: code_block
    content:
      -
        type: text
        text: ''
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Content after code block'
```

But it seems like you have to manually edit the file to create this invalid data. Bard (in our tests) saves an empty code block correctly like in the second code snippet above.

</details>
