### ISSUE TITLE
Missing create option in terms fieldtype editor

### ISSUE THREAD

**Issue by rrelmy** [statamic/cms#4040]
## Bug Description
In the fieldset editor when editing a terms fieldtype there is no option to disable the [creation feature](https://statamic.dev/fieldtypes/terms#config-options) of the terms fieldtype.

One has to manually edit the YAML file to disable it
``` yaml
fields:
  -
    handle: room
    field:
      max_items: 1
      mode: select
      taxonomies:
        - rooms
      display: Raum
      type: terms
      icon: taxonomy
      width: 50
      listable: hidden
      create: false # I would like to be an UI option too 😢 
```

## How to Reproduce
1. Add a terms field to a fieldset
2. Search the UI option to disable the creation feature

## Environment

Statamic 3.1.29 Pro
Laravel 8.51.0
PHP 7.4.3
4rn0/statamic-v3-image-optimizer 1.0.8
kind-work/two-fa 1.3.0
statamic/seo-pro 2.2.1
