### ISSUE TITLE
Taxonomy slug in URL not localized (Multisite)

### ISSUE THREAD

**Issue by timojokinen** [statamic/cms#4061]
## Bug Description
When having a localized taxonomy term assigned to a localized entry in a collection that is using the terms slug in its url schema, statamic generates the same url for each version of the entry.

## How to Reproduce
Enable multisite and create a new taxonomy with localizable title and slug. Then create a localized entry with a term field and assign the taxonomy term to the entry. Then edit the collections url schema so it uses the term field in the url:

Entry Blueprint:
```
title: Products
sections:
  main:
    display: Main
    fields:
      - handle: title
        field:
          type: readonly_text
          required: true
          input_type: text
          antlers: false
          display: Title
          icon: lock
          localizable: true
          listable: true
          validate:
            - required
      - handle: category
        field:
          type: terms
          taxonomies:
            - category
          display: Category
          mode: select
          max_items: 1
          icon: taxonomy
          listable: hidden

```

Taxonomy Blueprint:
```
title: Category
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          localizable: true
          validate:
            - required
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required

```

URL Schema of our collection:
```{category}/{slug}```

Say the taxonomy term we assigned to the entry has slug "_products_" in the english site (default) and "_produkte_" in german site.
And the entry has slug "_entry-en_" in english and "_entry-de_" in german.
Statamic will generate the following two URLS:

- /products/entry-en for english site
- /products/entry-de for german site

Instead of 
- /products/entry-en
- /produkte/entry-de

## Environment
Statamic 3.1.26.3 Pro
Laravel 8.49.0
PHP 8.0.8

**Statamic version:** 3.1.26.3

**PHP version:** 8.0.8

**Install method (choose one):**
- Fresh install from `statamic/statamic`
