### ISSUE TITLE
Date Fieldtype: earliest_date has no effect

### ISSUE THREAD

**Issue by helloiamlukas** [statamic/cms#4080]
## Bug Description

When configuring `earliest_date` in the Date fieldtype, it is still possible to select (& save) dates earlier than the defined value. I would expect earlier dates to be disabled.

## How to Reproduce

```yaml
    - handle: sendout_date
      field:
          mode: single
          time_enabled: true
          time_required: true
          earliest_date: '2021-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          type: date
          icon: date
          listable: true
```

## Extra Detail
<img width="294" alt="statamic" src="https://user-images.githubusercontent.com/15997450/127855175-2fc9cc1d-f8f1-416a-8057-4f9136ffbd4f.png">

## Environment

```
Statamic 3.1.32 Pro
Laravel 8.40.0
PHP 7.4.19
statamic/collaboration 0.1.0
statamic/eloquent-driver dev-custom-entry-data-class
```
`config/statamic/cp.php`
```php
    /*
    |--------------------------------------------------------------------------
    | Date Format
    |--------------------------------------------------------------------------
    |
    | When a date is encountered throughout the Control Panel, it will be
    | rendered in the following format. Any PHP date variables are permitted.
    |
    */

    'date_format' => 'Y-m-d',

```
**Install method (choose one):**
- Fresh install from `statamic/statamic`
