### ISSUE TITLE
Nav Blueprint: Link field is desynced by default

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#4133]
## Bug Description
Thanks for the amazing work with Nav blueprints. I had no idea that I would ever want the syncing feature and you guys knocked it out of the park. The only field that seems to be treated differently is the `link` field when using the slug `redirect`. This probably works as expect but I wanted to flag just in case. I'll share this repo with you for testing, as it's a pretty good use case for nav blueprints. https://ozdesign.dev (repo: https://github.com/jamshop/ozdesign)

## Extra Detail
<img width="1194" alt="Screen Shot 2021-08-18 at 11 59 14 am" src="https://user-images.githubusercontent.com/414211/129824588-140495cb-21a1-406e-86d9-cefc106f6659.png">

<details>
<summary>Nav blueprint</summary>
<pre>
```
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: redirect
        field:
          display: Redirect
          type: link
          icon: link
          listable: hidden
          validate:
            - required
      -
        handle: featured
        field:
          fields:
            -
              handle: image
              field:
                mode: grid
                container: assets
                folder: /
                restrict: false
                allow_uploads: true
                max_files: 1
                display: Image
                type: assets
                icon: assets
                listable: hidden
            -
              handle: title
              field:
                input_type: text
                antlers: false
                display: Title
                type: text
                icon: text
                listable: hidden
            -
              handle: url
              field:
                input_type: text
                antlers: false
                display: URL
                type: text
                icon: text
                listable: hidden
          mode: stacked
          max_rows: 1
          add_row: 'Add Feature'
          reorderable: false
          display: Featured
          type: grid
          icon: grid
          listable: hidden
      -
        handle: summary
        field:
          antlers: false
          display: Summary
          type: textarea
          icon: textarea
          listable: hidden
      -
        handle: button_label
        field:
          input_type: text
          antlers: false
          display: 'Button Label'
          type: text
          icon: text
          instructions: 'Shown when a button is required'
          listable: hidden
      -
        handle: image
        field:
          mode: grid
          container: assets
          folder: /
          restrict: false
          allow_uploads: true
          max_files: 1
          display: Image
          type: assets
          icon: assets
          listable: hidden
```
</pre>
</details>

<details>
  <summary>Entry blueprint</summary>
<pre>```
order: 1
title: Page
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: redirect
        field:
          display: Redirect
          type: link
          icon: link
          listable: hidden
          validate:
            - required
      -
        handle: featured
        field:
          fields:
            -
              handle: image
              field:
                mode: grid
                container: assets
                folder: /
                restrict: false
                allow_uploads: true
                max_files: 1
                display: Image
                type: assets
                icon: assets
                listable: hidden
            -
              handle: title
              field:
                input_type: text
                antlers: false
                display: Title
                type: text
                icon: text
                listable: hidden
            -
              handle: url
              field:
                input_type: text
                antlers: false
                display: URL
                type: text
                icon: text
                listable: hidden
          mode: stacked
          max_rows: 1
          add_row: 'Add Feature'
          reorderable: false
          display: Featured
          type: grid
          icon: grid
          listable: hidden
      -
        handle: summary
        field:
          antlers: false
          display: Summary
          type: textarea
          icon: textarea
          listable: hidden
      -
        handle: button_label
        field:
          input_type: text
          antlers: false
          display: 'Button Label'
          type: text
          icon: text
          instructions: 'Shown when a button is required'
          listable: hidden
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
            - 'unique_entry_value:{collection},{id},{site}'
      -
        handle: image
        field:
          mode: grid
          container: assets
          folder: /
          restrict: false
          allow_uploads: true
          max_files: 1
          display: Image
          type: assets
          icon: assets
          listable: hidden
 ```      
</pre></details>

## Environment

Statamic 3.2.0-beta.1 Pro
Laravel 8.55.0
PHP 7.4.21
mikemartin/helpscout-beacon 1.0.2
