### ISSUE TITLE
Template error on empty bard field (3.2)

### ISSUE THREAD

**Issue by smcyr** [statamic/cms#4167]
## Bug Description

I upgraded an existing website from 3.1 to 3.2 and I now have an error when I output a bard field which is empty.

## How to Reproduce
Add a bard field to an entry. Save the entry without content in the bard field. Output the field in the antlers template. Visit the page.

## Extra Detail

Error message:
```
TypeError
Argument 1 passed to Statamic\Fieldtypes\Bard::resolveStatamicUrls() must be of the type string, null given, called in ___\vendor\statamic\cms\src\Fieldtypes\Bard.php on line 160
```

## Environment

Statamic 3.2.0 Pro
Laravel 8.54.0
PHP 7.3.25
No addons installed

**Comment by smcyr** [comment]
If I save the entry with some content in the bard field and I return to then entry and erase the content, it works after saving. In the markdown file of the entry, the field was not there, but after saving without content, it added the field with this value:
```
results__body: '<p></p>'
```

**Comment by jasonvarga** [comment]
Thanks we'll sort that out soon.

**Comment by jasonvarga** [comment]
Can you provide the bard field inside your blueprint's yaml file?
Also, the template code for how you're trying to output the bard field.

**Comment by smcyr** [comment]
Here:
```
-
    handle: results__body
    field:
        type: bard
        display: Body
        localizable: true
        save_html: true
        buttons:
        - bold
        - italic
        - unorderedlist
        - orderedlist
        - html
        - quote
        - codeblock
        - h1
        - h2
        - h3
        - h4
        - h5
        - h6
        - anchor
```
```
{{ if results__body }}
    <div>{{ results__body }}</div>
{{ /if }}
```
