### ISSUE TITLE
Author Relation causes blank screen / JS error

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#4183]
## Bug Description
I have created a collection called "Authors". The Blueprint allows an author (Statamic User) to be assigned (via Users fieldset) to entries. On vice versa, within my Users Blueprint, those "Author"-Entries can be assigned (one at most). After creating the fields, everything works fine. But after saving an entry, the backend remains blank with an error in the console, see below.

From the "Authors" Blueprint:

```
handle: assigned_author
  field:
    max_items: 1
    mode: select
    display: Autor
    type: users
    icon: users
    listable: hidden
```

From the Users Blueprint (user.yaml):

```
field:
  max_items: 1
  mode: select
  create: false
  collections:
    - autoren
  display: Infoseite
  type: entries
  icon: entries
  listable: hidden
```

If I delete either of these codes directly from the yaml files, the backend loads fine again. Also, deleting the relation (eg: `assigned_author: 6bb75e4d-a280-4287-9b7d-c75782c654a8`) from the entry, the backend loads fine as well.

## How to Reproduce
Do what is described in the bug description. I could make a video if the description is unclear.

## Extra Detail
<img width="694" alt="Screenshot 2021-08-26 at 17 27 17" src="https://user-images.githubusercontent.com/3603346/130992317-f0092912-6b4a-48d3-90ee-4d7b41776ebd.png">

## Environment
Statamic 3.2.0 Pro
Laravel 8.56.0
PHP 8.0.9
jacksleight/bard-paragraph-style 1.0.0
jonassiewertsen/statamic-livewire 2.7.0
octoper/statamic-blade-components 1.0.1

**Install method**
- Existing Laravel app
