### ISSUE TITLE
UI Issue with Date + Time picker in sidebar

### ISSUE THREAD

**Issue by SteveEdson** [statamic/cms#4188]
## Bug Description
With a date picker in the sidebar, the time selector overflows the container

## How to Reproduce

Add a date field to the sidebar, with the following config (inline mode enabled, and time enabled)

```yaml
sidebar:
    display: Sidebar
    fields:
      -
        handle: date
        field:
          type: date
          required: true
          validate:
            - required
          listable: hidden
          mode: single
          time_enabled: true
          time_required: true
          earliest_date: '1900-01-01'
          full_width: false
          inline: true
          columns: 1
          rows: 1
```

## Extra Detail

<img width="416" alt="Screenshot 2021-08-27 at 08 53 33" src="https://user-images.githubusercontent.com/1201960/131093249-5da01d8b-b64d-4b80-a623-a7f41d7f6006.png">

## Environment

```
Statamic 3.1.34 Solo
Laravel 8.55.0
PHP 8.0.9
No addons installed
```

**Install method (choose one):**
- Fresh install from `statamic/statamic`
