### ISSUE TITLE
GraphQL: Title not showing as common field in NavPage implementation

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#4203]
## Bug Description
When querying a nav blueprint, it appears that `Title` does not appear as a common field in `NavPage` unless you explicitly add a `title` field in the nav blueprint.

## How to Reproduce

Nav blueprint:
```
sections:
  main:
    display: Main
    fields:
      -
        handle: description
        field: common.description
      -
        handle: plans
        field:
          type: terms
          taxonomies: plans
          display: Plans
          mode: select
      -
        handle: amounts
        field:
          fields:
            -
              handle: plan
              field:
                max_items: 1
                mode: select
                display: Plan
                type: terms
                icon: taxonomy
                listable: hidden
                taxonomies:
                  - plans
            -
              handle: value
              field:
                input_type: text
                antlers: false
                display: Value
                type: text
                icon: text
                listable: hidden
          mode: table
          reorderable: true
          display: 'Plan Amount'
          type: grid
          icon: grid
          listable: hidden
          add_row: 'Add Amount'
      -
        handle: info_tip
        field:
          type: toggle
          display: 'Info Tip'
      -
        handle: new
        field:
          type: toggle
```

Query:
```
{
  nav(handle: "comparison") {
    tree {
      depth
      page {
        ...on NavPage_Comparison {
          title
        }
      }
    }
  }
}
```

## Extra Detail

<img width="1172" alt="Screen Shot 2021-09-01 at 3 18 25 pm" src="https://user-images.githubusercontent.com/414211/131615992-1123b0d0-d192-4dc3-a733-eb8f894de3d3.png">

Error:
````
Cannot query field \"title\" on type \"NavPage_Comparison\". Did you mean to use an inline fragment on \"PageInterface\", \"EntryInterface\", \"NavBasicPage_Comparison\", or \"NavEntryPage_Comparison_Features_Features\"?"
```



## Environment

Statamic 3.2.1 Pro
Laravel 8.58.0
PHP 7.4.22
mikemartin/helpscout-beacon 1.0.2
rias/statamic-color-swatches 2.0.5
rias/statamic-redirect 1.4.7
spatie/statamic-responsive-images 2.8.0
withcandour/aardvark-seo 2.0.15
