### ISSUE TITLE
Migrating v2 pages with false values for selects results in an error exception

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/cms#4204]
## Bug Description
Trying to get our migrated site running, we're running into some speedbumps due to caveats in v2.
If you added a new select field to an existing fieldset, and save the entry without selecting a value, v2 will save that field as `false` instead of `null`.
This check will then result in an `array_key_exists(): The first argument should be either a string or an integer` error exception.

## How to Reproduce
1. Manually edit any entry containing a select field using your favorite editor, and save that field with the value `false`
2. Clear Stache/cache to get the updates
3. Try and view the entry outside CP
4. Experience the beautiful error page from Ignition

## Extra Detail

![image](https://user-images.githubusercontent.com/1186125/131668904-862b1183-99e8-4d54-b879-c44ec58a495e.png)

This can be fixed by adding a special check for `false`:
```php
$label = is_null($value) || $value === false ? null : array_get($this->config('options'), $value, $value);
```

## Environment

Statamic 3.2.1 Pro
Laravel 8.57.0
PHP 7.4.14
statamic/migrator dev-master

**Install method (choose one):**
Migrated from v2

**Comment by jasonvarga** [comment]
What are the `options` in the field?

**Comment by jasonvarga** [comment]
On the v2 site, and on the v3 site.

**Comment by FrittenKeeZ** [comment]
In v2:
```yaml
menu_placement:
  type: select
  display: 'Menu placement'
  options:
    none: '-- Select --'
    dynamic: Dynamic
    global: Global
  default: false
```
In v3:
```yaml
handle: menu_placement
field:
  type: select
  display: 'Menu placement'
  options:
    none: '-- Select --'
    dynamic: Dynamic
    global: Global
  default: false
```
The field was added later on, but I can't remember why I opted for `default: false` instead of `default: none`.
