### ISSUE TITLE
Same Fieldset in Fieldset breaks backend entries (502 Bad Gateway)

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#4206]
## Bug Description
I just updated to the latest version and everything was running fine. But some entries in the backend throw an error "502 Bad Gateway". I thought it was my local setup so I tried to fix that but it turns out, Statamic causes this. I did the same update on my production server and to my surprise, the error occurs are well. Going back to v3.2.1 "fixes" that error.

**Update:** The problem occurs when I reference the same fieldset within a fieldset. I my example an Accordion within an Accordion. Although it was a mistake on my end (there should be not child accordion in a parent accordion), it should technically by possible to do that. I think. But it throws an error 502 as of now.

## Environment

Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 8.0.10
jacksleight/bard-paragraph-style 1.0.0
jonassiewertsen/statamic-livewire 2.7.0
octoper/statamic-blade-components 1.0.1
optimoapps/statamic-bard-text-align 1.0.2

**Install method:**
- Existing Laravel app

**Comment by MrMooky** [comment]
Hmmm... the error seems to come from one of the fields in my Replicator:

```
handle: contents
field:
  collapse: accordion
  sets:
    text:
      display: Text
      fields:
        -
          import: text
    image:
      display: Bild
      fields:
        -
          import: image
    accordion:
        display: Accordion
        fields:
            -
                import: accordion
    slideshow:
        display: Slideshow
        fields:
            -
                import: slideshow
  display: Inhalte
  type: replicator
  icon: replicator
  listable: hidden
```

When I remove the following block, the backend loads just fine:

```
accordion:
  display: Accordion
  fields:
    -
      import: accordion
```
