### ISSUE TITLE
Incorrect validation error message

### ISSUE THREAD

**Issue by SteveEdson** [statamic/cms#4208]
## Bug Description
When setting a rule of `min:3` on a repeater field type, the validation error message says "Must be at least 3 characters", would be better to be "must be at least 3 items".

## How to Reproduce
```yaml
-
    handle: icon_blocks
    field:
      collapse: false
      sets:
        icon_block:
          display: 'Icon Block'
          fields:
            -
              handle: title
              field:
                input_type: text
                antlers: false
                display: Title
                type: text
                icon: text
                listable: hidden
      display: 'Icon Blocks'
      type: replicator
      icon: replicator
      listable: hidden
      max_sets: 4
      validate:
        - 'min:3'
```

## Extra Detail

![image](https://user-images.githubusercontent.com/1201960/131822758-3b5521a8-709c-4610-8190-70d488092821.png)

## Environment

Statamic 3.2.1 Pro
Laravel 8.57.0
PHP 8.0.10
