### ISSUE TITLE
Slug fieldtype missing option to set a field to make a slug from

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#4218]
## Bug Description
Slug fieldtype doesn't have an option to tell it what handle to make a slug from. It's possible to manually add a `from: handle_name_to_make_slug_from` in `resources/blueprints/user.yaml` but it's buggy.

## How to Reproduce
In the CP add a `Slug fieldtype` to the `user` blueprint. Try to associate the `Slug fieldtype` with the `name` field. There doesn't seem to be a way to do this via the CP.

I can edit `resources/blueprints/user.yaml` manually . I added `from: name` and saved the `user.yaml` file

```
  handle: slug
        field:
          generate: true
          display: Slug
          type: slug
          icon: slug
          listable: hidden
          from: name
 ```

With the `user.yaml` still open, went back to the `user` blueprint and pressed save.  `from: name` is removed. 

I add it again to `user.yaml` this time I navigate away from the `user` blueprint without saving. When I navigate back to it and press save `from: name` is not removed.

Only then does the Slug fieldtype work as expected.

## Environment
Statamic 3.2.2 Pro
Laravel 8.52.0
PHP 8.0.8
simonhamp/statamic-heroicons 1.0.1

**Install method (choose one):**
- Fresh install from `statamic/statamic`
