### ISSUE TITLE
Weird spacing in a Grid fieldtype

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#4224]
## Bug Description
Weird spacing in a Grid fieldtype, drag handles are massive...

## Extra Detail
<img width="886" alt="Screenshot 2021-09-06 at 21 24 14" src="https://user-images.githubusercontent.com/72254741/132258806-e0832f47-69a1-4f10-873c-230381025906.png">

## Environment
Statamic 3.2.2 Pro
Laravel 8.52.0
PHP 8.0.8

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Have you given all the fields a width?

**Comment by stephenmeehanuk** [comment]
Yes, see below.

![Screenshot 2021-09-07 at 08 12 42](https://user-images.githubusercontent.com/72254741/132300750-7d81c3ff-c331-4a4f-b7ea-e8cba31d4386.png)

```
 handle: opening_times
        field:
          fields:
            -
              handle: day
              field: common.text
              config:
                display: Day
                width: 50
            -
              handle: opening_time
              field:
                display: 'Opening Time'
                type: time
                icon: time
                width: 25
                listable: hidden
                default: '09:00'
            -
              handle: closing_time
              field:
                display: 'Closing Time'
                type: time
                icon: time
                width: 25
                listable: hidden
                default: '17:00'
          mode: table
          max_rows: 7
          add_row: 'Add day'
          reorderable: true
          display: 'Opening Times'
          type: grid
          icon: grid
          listable: hidden
```
