### ISSUE TITLE
[3.2.3] Bard won't validate

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#4240]
## Bug Description
In the most recent update (3.2.3) a bard field I use doesn't validate. I get the error 'Must be an array' and can't save the entry. Downgrading to 3.2.2 solves the issue for me.

## Extra Detail
The field (used in a replicator set):
```yaml
-
  handle: title_bottom
  field: common.text_bold
  config:
    display: Text bottom
```

The common field:
```yaml
  -
    handle: text_bold
    field:
      buttons:
        - bold
      save_html: false
      toolbar_mode: floating
      link_noopener: false
      link_noreferrer: false
      target_blank: false
      reading_time: false
      fullscreen: false
      allow_source: false
      type: bard
      replicator_preview: false
      localizable: true
      listable: hidden
      display: Text
```

## Environment
Statamic 3.2.2 Pro
Laravel 8.60.0
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Starter kit
