### ISSUE TITLE
Asset meta data gets lost when an asset is moved

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#4253]
## Bug Description

When you move an asset, the value of the meta file's `data` key is copied into a new meta file in the new location. However none of the standard meta values are (`width` etc.) This causes two issues:

1. If you try to load the asset on the frontend the standard values aren't available
2. When you browse to the destination folder in the asset browser the standard metadata is re-generated, but in doing this the `data` key gets overwritten, so you then lose any additional data like captions, alt text etc.

## How to Reproduce

1. Upload an asset and add some meta data such as a caption
2. Move the asset
3. Try to read one of the assets standard meta values, eg. `width`, it's no longer set
4. Browse to the destination folder (standard meta values now get re-generated)
5. Check the caption, it's no longer set

## Extra Detail

Meta file before move:

```yaml
data:
  alt: 'Some Alt Text'
  caption: 'Example Caption'
size: 70220
last_modified: 1631542181
width: 820
height: 768
mime_type: image/jpeg
```

Meta file after move:

```yaml
data:
  alt: 'Some Alt Text'
  caption: 'Example Caption'
```

Meta file after browsing to destination folder:

```yaml
data: {  }
size: 70220
last_modified: 1631542181
width: 820
height: 768
mime_type: image/jpeg
```

## Environment

Statamic 3.2.4 Pro
Laravel 8.60.0
PHP 7.4.21
