### ISSUE TITLE
Nav extra fields not displayed for the home item

### ISSUE THREAD

**Issue by MarceauKa** [statamic/cms#4258]
## Bug Description

I have a navigation with extra fields (see below). All entries are from the same collection called "Pages". I can display my navigation with the `{{ nav:main }}` tag but for the first entry my custom `nav_icon` field is not rendered (but data is saved). If I reorder my nav, it's always the first item that comes with empty extra fields.

For now, I __fixed__ the issue by duplicating my first entry (my homepage). Each have the same `nav_icon` field and I set my antlers tag with `include_home=false`.

## Extra Detail

**Antlers code**

```antlers
{{ nav:main max_depth="2" include_home="true" }}
<li class="w-full">
    <a class="flex items-center px-3 py-2 bg-white font-bold text-md uppercase shadow-lg hover:text-primary" href="{{ url }}">
        {{ if nav_icon }}
             {{ svg :src="nav_icon" class="w-6 h-6 mr-3 text-white" aria-hidden="true" }}
        {{ /if }}

        {{ title }}
    </a>
</li>
{{ /nav:main }}
```

**Nav blueprint**

```yaml
sections:
  main:
    display: Principale
    fields:
      -
        handle: nav_icon
        field:
          options:
            home: 'Accueil'
            music: 'Musique'
            cog: 'Engrenage'
            ticket: 'Ticket'
            calendar: 'Agenda'
            about: 'A propos'
            online: 'En ligne'
            shop: 'Panier'
          multiple: false
          max_items: 1
          clearable: true
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          display: 'Icône'
          type: select
          icon: select
          listable: hidden
```

**Nav content**

```yaml
tree:
  -
    id: 1318f6bd-5cfb-4e64-8db0-80973439b8b8
    entry: home
    data:
      nav_icon: home
  -
    id: 422e42ea-0a0d-4e05-ab56-841eda921827
    entry: badf5771-c207-48fa-b979-544be7053092
    data:
      nav_icon: music
  -
    id: 5d3cbf36-f10c-46f8-bf77-e26d45ab5a78
    entry: e9d7195c-0bd0-4ed2-b11e-19f8fd81a0b9
    data:
      nav_icon: cog
  -
    id: 222f24a2-53f1-4b87-b26a-fd112479d4cc
    entry: 2b072263-2118-41a2-bf02-8ede2e837ddd
    data:
      nav_icon: ticket
```
## Environment

**Statamic version:** 3.2.4

**PHP version:** 8.0.10

**Install method (choose one):**
- Starter kit (Peak)
