### ISSUE TITLE
Error when saving entry in CP

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#426]
Log:
```
[2019-05-25 03:59:56] local.ERROR: Call to a member function format() on null {"userId":"b84d1156-8c84-4779-9db6-9df20c5bb092","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function format() on null at /Users/erin/Documents/Development/three-cms/app/Data/Content/UrlBuilder.php:128)
[stacktrace]
#0 /Users/erin/Documents/Development/three-cms/app/Data/Content/UrlBuilder.php(106): Statamic\\Data\\Content\\UrlBuilder->getSpecialValue('year')
#1 /Users/erin/Documents/Development/three-cms/app/Data/Content/UrlBuilder.php(54): Statamic\\Data\\Content\\UrlBuilder->getValue('year')
#2 /Users/erin/Documents/Development/three-cms/app/Data/Routable.php(29): Statamic\\Data\\Content\\UrlBuilder->build('/blog/{year}/{m...')
#3 /Users/erin/Documents/Development/three-cms/app/Stache/Stores/BasicStore.php(371): Statamic\\Data\\Entries\\Entry->uri()
#4 /Users/erin/Documents/Development/three-cms/app/Stache/Repositories/EntryRepository.php(76): Statamic\\Stache\\Stores\\BasicStore->insert(Object(Statamic\\Data\\Entries\\Entry))
#5 /Users/erin/Sites/dl3/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Statamic\\Stache\\Repositories\\EntryRepository->save(Object(Statamic\\Data\\Entries\\Entry))
```

Blueprint:
```
title: Blog Post
author: true
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          localizable: true
          display: Title
          type: text
          width: 25
      -
        handle: slug
        field:
          type: text
          width: 25
          display: Slug
      -
        handle: author
        field:
          type: users
          display: Author
          width: 25
          max_items: 1
          default: current
      -
        handle: date
        field:
          allow_blank: false
          allow_time: true
          require_time: true
          earliest_date: January 1, 1900
          type: date
          width: 25
          display: Date/Time
      -
        handle: link
        field:
          display: Link
          type: text
          validate: url
          width: 50
```

Collection:
```
title: Blog
route: '/blog/{year}/{month}/{day}/{slug}'
dated: true
blueprints:
  - post
template: post
date_behavior:
  past: public
  future: private
```
