### ISSUE TITLE
Error when creating a Structure

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#427]
Collection:
```
title: Page
route: '/{slug}'
blueprints:
  - page
orderable: true
```

Blueprint

```
title: 'Page'
sections:
  main:
    fields:
      -
        handle: title
        field:
          type: text
      -
        handle: content
        field:
          type: markdown
      -
        handle: template
        field:
          type: template
```

Error: https://cl.ly/f52913880252
