### ISSUE TITLE
Error when trying to Link Existing Item for Multi Taxonomy Term field.

### ISSUE THREAD

**Issue by michaelr0** [statamic/cms#4317]
## Bug Description
Error when trying to Link Existing Item for Multi Taxonomy Term field.

Call to a member function visible() on null
![image](https://user-images.githubusercontent.com/54159303/134855027-b84f0e98-19c8-4e82-9082-ed0c2140cfc2.png)

This looks like it is related to the Taxonomy column, which can be confirmed by trying to access the link used during the XHR request.
`http://localhost:8000/cp/fieldtypes/relationship?...&columns=title,taxonomy&search=`

Which then also errors.
![image](https://user-images.githubusercontent.com/54159303/134856155-f5a46283-df93-4026-b27d-70e5f2026fc4.png)
![image](https://user-images.githubusercontent.com/54159303/134856204-2127df9a-8a30-4e6c-ae0d-4ef06537d941.png)

The error goes away, when accessing the api and removing taxonomy from the columns.
What is odd is that we have only just started seeing this error pop up now, it wasn't an issue previously.

The taxonomy column appears to be getting added to the api url from the below code.
`Statamic\Fieldtypes\Terms`
```php
    protected function getColumns()
    {
        $columns = [Column::make('title')];

        if (! $this->usingSingleTaxonomy()) {
            $columns[] = Column::make('taxonomy');
        }

        return $columns;
    }
```

## Extra Detail
`taxonomies/test.yml`
```yml
title: Test
```

`taxonomies/test2.yml`
```yml
title: Test2
```

`taxonomies/test/test.yml`
```yml
title: test
content: test
updated_by: 90ad7de2-8e7e-4dae-81a0-7b1a91d10091
updated_at: 1632723240
blueprint: test
```

`taxonomies/test2/test2.yml`
```yml
title: test2
content: test2
updated_by: 90ad7de2-8e7e-4dae-81a0-7b1a91d10091
updated_at: 1632723253
blueprint: test2
```

`resources/blueprints/collections/pages/pages.yml`
```yml
title: Pages
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: content
        field:
          type: markdown
          display: Content
          localizable: true
          listable: hidden
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: true
      -
        handle: taxonomy_terms
        field:
          mode: default
          create: false
          taxonomies:
            - test
            - test2
          display: 'Taxonomy Terms'
          type: terms
          icon: taxonomy
          listable: hidden
          instructions_position: above
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
```

Then go into a page and try to link a taxonomy term.

## Environment

Statamic 3.2.8 Pro
Laravel 8.61.0
PHP 8.0.10

**Install method:**
Fresh install from statamic cli
