### ISSUE TITLE
Bard: some set configurations are not translated to ProseMirror node types

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#454]
Somehow, not all of our configured Bard sets are available in the underlying ProseMirror instance as node types, which leads to the following exception:

```
[tiptap warn]: Invalid content. Passed value: 
Object { type: Getter & Setter, content: Getter & Setter, … }
 Error: RangeError: "Unknown node type: slideshow"
    nodeType index.js:2442
    fromJSON index.js:1392
    nodeFromJSON index.js:2430
    fromJSON index.js:306
    fromJSON index.js:1391
    nodeFromJSON index.js:2430
    value tiptap.esm.js:986
    value tiptap.esm.js:951
    value tiptap.esm.js:859
    t tiptap.esm.js:840
    mounted BardFieldtype.vue:189
    VueJS 14
    start Statamic.js:51
    <anonymous> shift-in-balance-of-power-for-rebels-in-wartorn-syria:283
tiptap.esm.js:988
```

No content is rendered in the Bard editor field.

Bard config:

```
-
  handle: body
  field:
    type: bard
    display: Inhalt
    buttons:
      - convertToParagraph
      - h3
      - orderedlist
      - unorderedlist
      - bold
      - italic
      - underline
      - removeFormat
      - anchor
      - linkToContentStore
    allow_source: false
    link_noopener: true
    link_noreferrer: true
    target_blank: true
    show_text_count: true
    spellcheck: false
    sets:
      image:
        display: Bild
        fields:
          -
            handle: image
            field:
              type: polygon_assets
              display: Bild
              container: image
              max_files: 1
              allow_uploads: false
          -
            handle: caption
            field:
              type: bard
              save_html: true
              display: Bildunterschrift
              buttons:
                - bold
                - italic
                - underline
                - anchor
                - linkToContentStore
              allow_source: false
              link_noopener: true
              link_noreferrer: true
              target_blank: true
              instructions: |
                Überschreibt die Bildbeschreibung.

          -
            handle: placement
            field:
              type: select
              display: Ausrichtung
              options:
                center: Mitte
                big: Maxi
                left: Links
                right: Rechts
              default: center
          -
            handle: link
            field:
              type: text
              display: Link
              instructions: |
                Komplette URL (inklusive https:// bzw. http://) oder für interne Seiten relativen Pfad

      slideshow:
        display: Slideshow
        fields:
          -
            handle: slideshow
            field:
              type: polygon_relationship
              display: Slideshow
              max_items: 1
              collections: [ slideshow ]
          # -
          #   handle: caption
          #   field: bard.basic+
          #   config:
          #     display: Caption
```

The `image` set works fine (when loading an entry with an image but no slideshow in the body field).
