### ISSUE TITLE
Validation - `required` seems to be default?

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#456]
I have a field:
```
      -
        handle: link
        field:
          display: Link
          type: text
          validate: url
          width: 50
```

When I try to fill in the entry via the CP, I can't get it to save unless I fill in that field, even though I don't have have `required` in the validation.
