### ISSUE TITLE
Bard Fieldtype does not properly focus, requiring interaction to see (+)

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#458]
My fieldset:
```
      -
        handle: bard
        field:
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
          save_html: null
          toolbar_mode: fixed
          link_noopener: null
          link_noreferrer: null
          target_blank: null
          reading_time: null
          fullscreen: true
          allow_source: true
          type: bard
          instructions: null
          localizable: false
          width: 100
          display: Content
          sets:
            images:
              display: Image
              fields:
                -
                  handle: images
                  field:
                    type: assets
                    container: main
            text:
              display: Text
              fields:
                -
                  handle: text
                  field:
                    type: markdown
```

I have to hit enter to get the first +. This is on Safari. https://cl.ly/b945790cb847
