### ISSUE TITLE
Add Bard hit areas between sets

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#460]
The first time I did bard content via the CP, it created all these empty sets. I removed them so my content was clean:
```
bard:
  -
    type: set
    attrs:
      values:
        type: text
        text: 'testing the *markdown* stuff'
```

When I got back to the CP, I cannot add any more sets: https://cl.ly/13af7d350b27, unless I hit the enter key (and I don't know where the cursor is)
