### ISSUE TITLE
Bard: extra sets are saved

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#461]
This time I just started typing, then hit enter and saw the +, then added a text set and put some text in it. It looked like this: https://cl.ly/05cf49ff6e13.

When it saved the content had extra sets in it:
```
bard:
  -
    type: paragraph
    content:
      -
        type: text
        text: asdfadsf
  -
    type: paragraph
  -
    type: set
    attrs:
      values:
        type: text
        text: lkjlkjlkj
  -
    type: paragraph
```
