### ISSUE TITLE
HtmlToProseMirror\Renderer::render(): Argument #1 ($value) must be of type string, array given

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#4634]
### Bug description

When I try to link to another entry from within the CP, I get the following error:

> HtmlToProseMirror\Renderer::render(): Argument #1 ($value) must be of type string, array given, called in /Users/mooky/Code/yyy/vendor/statamic/cms/src/Fieldtypes/Bard.php on line 330

I found some similar errors / issues, but those were related to the content handle being actually named `content`. I had this problem a few months ago as well, but was able to solve it by naming it `contents`.

Anyway, the bug seems to have a different cause. Oddly enough, the error only happens locally, this works just fine on the production server with the same setup.

### How to reproduce

I actually don't really know. I just created a few entries and tried to interlink them.

### Logs

```shell
[2021-11-02 08:44:55] local.ERROR: HtmlToProseMirror\Renderer::render(): Argument #1 ($value) must be of type string, array given, called in /Users/mooky/Code/yyy/vendor/statamic/cms/src/Fieldtypes/Bard.php on line 330 {"userId":"6bb75e4d-a280-4287-9b7d-c75782c654a8","exception":"[object] (TypeError(code: 0): HtmlToProseMirror\\Renderer::render(): Argument #1 ($value) must be of type string, array given, called in /Users/mooky/Code/yyy/vendor/statamic/cms/src/Fieldtypes/Bard.php on line 330 at /Users/mooky/Code/yyy/vendor/ueberdosis/html-to-prosemirror/src/Renderer.php:118)
[stacktrace]
#0 /Users/mooky/Code/yyy/vendor/statamic/cms/src/Fieldtypes/Bard.php(330): HtmlToProseMirror\\Renderer->render(Array)
#1 [internal function]: Statamic\\Fieldtypes\\Bard->Statamic\\Fieldtypes\\{closure}(Array, 0)
#2 /Users/mooky/Code/yyy/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(664): array_map(Object(Closure), Array, Array)
#3 /Users/mooky/Code/yyy/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(351): Illuminate\\Support\\Collection->map(Object(Closure))
#4 /Users/mooky/Code/yyy/vendor/statamic/cms/src/Fieldtypes/Bard.php(344): Illuminate\\Support\\Collection->flatMap(Object(Closure))
#5 /Users/mooky/Code/yyy/vendor/statamic/cms/src/Fieldtypes/Bard.php(269): Statamic\\Fieldtypes\\Bard->convertLegacyData(Array)
#6 /Users/mooky/Code/yyy/vendor/statamic/cms/src/Fields/Field.php(262): Statamic\\Fieldtypes\\Bard->preProcessIndex(Array)
#7 /Users/mooky/Code/yyy/vendor/statamic/cms/src/Http/Resources/CP/Entries/ListedEntry.php(66): Statamic\\Fields\\Field->preProcessIndex()
#8 /Users/mooky/Code/yyy/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(711): Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry->Statamic\\Http\\Resources\\CP\\Entries\\{closure}(Object(Statamic\\CP\\Column), 1)
#9 /Users/mooky/Code/yyy/vendor/statamic/cms/src/Http/Resources/CP/Entries/ListedEntry.php(70): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))
#10 /Users/mooky/Code/yyy/vendor/statamic/cms/src/Http/Resources/CP/Entries/ListedEntry.php(41): Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry->values(Array)
#11 /Users/mooky/Code/yyy/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(95): Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry->toArray(Object(Illuminate\\Http\\Request))
#12 /Users/mooky/Code/yyy/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(232): Illuminate\\Http\\Resources\\Json\\JsonResource->resolve(Object(Illuminate\\Http\\Request))
#13 /Users/mooky/Code/yyy/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(870): Illuminate\\Http\\Resources\\Json\\JsonResource->jsonSerialize()
#14 [internal function]: Illuminate\\Support\\Collection->Illuminate\\Support\\Traits\\{closure}(Object(Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry))
#15 /Users/mooky/Code/yyy/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(878): array_map(Object(Closure), Array)
```

### Versions

Statamic 3.2.19 Pro
Laravel 8.68.1
PHP 8.0.11
jacksleight/bard-paragraph-style 1.2.2
jonassiewertsen/statamic-livewire 2.7.0
octoper/statamic-blade-components 1.0.1
optimoapps/statamic-bard-text-align 1.0.2

### Installation

Existing Laravel app

**Comment by duncanmcclean** [comment]
Do you have any Bard fields called `content`?

**Comment by MrMooky** [comment]
Not anymore. As I said in my bug description, I had a similar issue before and renamed my content fields (handle) `contents`, so with an 's' at the end and that fixed that prior problem.

I just checked my few local entries (the .md files) and the content is always located under `contents`:

```
contents:
  -
```

**Comment by duncanmcclean** [comment]
Ah sorry, didn't see that in the initial description.

**Comment by jasonvarga** [comment]
Where exactly are you seeing this error?

**Comment by MrMooky** [comment]
Directly in the CP in the lower left corner right after clicking the "Entry" field folder icon. So the "Page Explorer" (what is it called?) appears blank and the errors pops up.

<img width="356" alt="Screenshot 2021-11-02 at 15 06 04" src="https://user-images.githubusercontent.com/3603346/139862975-52c0f9b6-3132-4f6d-ac39-1e43964d9903.png">

<img width="1713" alt="Screenshot 2021-11-02 at 15 04 28" src="https://user-images.githubusercontent.com/3603346/139862722-e85da7b0-2c0c-4d07-ae05-1b3f3df7f365.png">

**Comment by jasonvarga** [comment]
Cool. In Bard. You didn't mention that. 👍 
Do you have `link_collections` defined for your bard field?

**Comment by MrMooky** [comment]
The same error is mentioned in the error description at the very top.
I have no `link_collections` defined, at least not that I'm aware of.

Here is a blueprint example of one of the collections. Most of them are almost identical.

```
title: Checklisten
sections:
  main:
    display: Hauptteil
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: contents
        field:
          collapse: true
          sets:
            text:
              display: Text
              fields:
                -
                  import: text
            image:
              display: Bild
              fields:
                -
                  import: image
            textimage:
              display: TextBild
              fields:
                -
                  import: text_image
            checklist-download:
              display: 'Checklist Download'
              fields:
                -
                  import: checklist_download
            infobox:
              display: Infobox
              fields:
                -
                  import: infobox
          display: Inhalte
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: tags
        field:
          type: terms
          taxonomies:
            - tags
          display: Tags
          mode: select
      -
        handle: creator
        field:
          max_items: 1
          mode: select
          create: false
          collections:
            - autoren
          display: Autor
          type: entries
          icon: entries
          listable: hidden
      -
        handle: kategorien
        field:
          type: terms
          taxonomies:
            - kategorien
          display: Kategorien
          mode: select
      -
        handle: allow_comments
        field:
          default: true
          display: 'Kommentare erlauben'
          type: toggle
          icon: toggle
          listable: hidden
      -
        handle: show_toc
        field:
          default: false
          display: 'Inhaltsverzeichnis anzeigen'
          type: toggle
          icon: toggle
          listable: hidden
          instructions_position: above
      -
        handle: preview_image
        field:
          mode: grid
          container: dokumente
          restrict: false
          allow_uploads: true
          max_files: 1
          display: Vorschaubild
          type: assets
          icon: assets
          listable: hidden
  seo_settings:
    display: SEO
    fields:
      -
        handle: seo_title
        field:
          input_type: text
          character_limit: 65
          antlers: false
          display: SEO-Titel
          type: text
          icon: text
          instructions: 'Überschreibt den Standard-Titel, gewöhnlich der Titel des Artikel.'
          listable: hidden
          instructions_position: above
      -
        handle: seo_description
        field:
          character_limit: '160'
          antlers: false
          display: SEO-Beschreibung
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above

```
