### ISSUE TITLE
Date field not saving

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#464]
I have a date field in my collection blueprint:
```
title: 'Blog Post'
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          localizable: true
          display: Title
          type: text
          width: 25
      -
        handle: slug
        field:
          type: text
          width: 25
          display: Slug
      -
        handle: author
        field:
          type: users
          display: Author
          width: 25
          max_items: 1
          default: current
      -
        handle: date
        field:
          allow_blank: false
          allow_time: true
          require_time: true
          earliest_date: 'January 1, 1900'
          type: date
          width: 25
          display: Date/Time
      -
        handle: link
        field:
          display: Link
          type: text
          validate: url
          width: 50
      -
        handle: bard
        field:
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
          save_html: null
          toolbar_mode: fixed
          link_noopener: null
          link_noreferrer: null
          target_blank: null
          reading_time: null
          fullscreen: true
          allow_source: true
          type: bard
          instructions: null
          localizable: false
          width: 100
          display: Content
          sets:
            images:
              display: Image
              fields:
                -
                  handle: images
                  field:
                    type: assets
                    container: main
            text:
              display: Text
              fields:
                -
                  handle: text
                  field:
                    type: markdown
```

I can choose a date: https://cl.ly/0c1c9dff6854, but if I reload the entry, there's nothing shown: https://cl.ly/e31e58b12e57 and nothing is saved:
```
title: 'bard test'
author: b84d1156-8c84-4779-9db6-9df20c5bb092
bard:
  -
    type: paragraph
    content:
      -
        type: text
        text: asdfadsf
  -
    type: set
    attrs:
      values:
        type: text
        text: lkjlkjlkj
  -
    type: paragraph
updated_by: b84d1156-8c84-4779-9db6-9df20c5bb092
updated_at: 1559956219
id: eef65878-7c8f-4f9d-b92f-e021c7867a19
published: false
```
