### ISSUE TITLE
Can't add time to an entry

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#465]
I have a date/time field:
```
        handle: date
        field:
          allow_blank: false
          allow_time: true
          require_time: true
          earliest_date: 'January 1, 1900'
          type: date
          width: 25
          display: Date/Time
```

But in the entry there's no time: https://cl.ly/ec061881bdea
