### ISSUE TITLE
Blueprint default values get ignored when using the API

### ISSUE THREAD

**Issue by St3Ko** [statamic/cms#4658]
### Bug description

When you use the API to create an Entry for example like this:
```php
Entry::make()
    ->collection('pages')
    ->slug('created-with-api')
    ->data([
        'title' => 'Created Via API',
    ])
    ->save();
```
fields with a default value like this:
```yaml
handle: select
field:
  options:
    test: Test
    anotherone: 'Another One'
  multiple: false
  max_items: 1
  clearable: false
  searchable: true
  taggable: false
  push_tags: false
  cast_booleans: false
  default: test
  display: Select
  type: select
  icon: select
  listable: hidden
  instructions_position: above
```
will get ignored and are only stored, after you manually save them again inside the CP

repo link at the bottom, if needed

### How to reproduce

* create a field inside a blueprint with a default value
* use the API to create and save an entry

### Versions

Statamic 3.2.20 Solo
Laravel 8.69.0
PHP 7.3.27
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Additional details

repo:
https://github.com/St3Ko/entry-blueprint-bug

use `php artisan command:name` to create an entry via API
