### ISSUE TITLE
Making time required isn't showing the time field

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#466]
Blueprint:
```
        handle: date
        field:
          time_enabled: true
          time_required: true
          earliest_date: 'January 1, 1900'
          type: date
          width: 33
          display: Date/Time
```

But in the entry, the time is not included: https://cl.ly/4e4c1c599a42
