### ISSUE TITLE
Relationship fieldtype is not getting augmented

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#4670]
### Bug description

I have created a custom relationship fieldtype, `Invoice`:

```php
class Invoice extends StripeField
{
    protected static $handle = 'stripe_invoice';

    protected function augmentValue($value)
    {
        dd($value);
    }
...
}
```

I have put the field in a grid in a blueprint:

```yaml
...
      -
        handle: milestones
        field:
          type: grid
          mode: stacked
          min_rows: 1
          add_row: 'Add Milestone'
          fields:
            -
              handle: invoice
              field:
                mode: select
                display: Invoice
                type: stripe_invoice
                icon: stripe_invoice
                listable: hidden
                instructions_position: above
                max_items: 1
...
```

It works, data is saved properly.

When I use it in a template via `{{ invoice }}` the `augmentValue` is not called, and instead the base value is returned.

### How to reproduce

See my description above.

### Versions

Statamic 3.2.20 Pro
Laravel 8.69.0
PHP 8.0.12
aryehraber/statamic-captcha 1.5.2
aryehraber/statamic-uuid 2.0.3
doublethreedigital/duplicator 2.0.1
edalzell/forma 1.0
jonassiewertsen/statamic-livewire 2.7.0
statamic/seo-pro 2.3.2
transformstudios/events 2.2.3
transformstudios/front 1.7.1
transformstudios/gated dev-main
transformstudios/magic-link dev-main
transformstudios/review 3.1
transformstudios/simple dev-main
transformstudios/stripe dev-main
transformstudios/takeover-redirects dev-main
transformstudios/uptime dev-main

### Installation

Starter Kit using via CLI
