### ISSUE TITLE
Email variables not working in Subject of Forms

### ISSUE THREAD

**Issue by danystad** [statamic/cms#4736]
### Bug description

I'm trying to use email variables described here https://statamic.dev/forms#email-variables in the Subject of the email, but there is no output for that email variable in the sent email's subject line.

### How to reproduce

Add an email variable to the subject line like this:

```
title: 'Contact Form'
email:
  -
    to: email@domain.com
    reply_to: '{{ email }}'
    subject: 'Website Contact Form - sent {{ now }}'
    template: contact-form
```

### Versions

Statamic version: 3.2.21

### Installation

Fresh statamic/statamic site via CLI

### Additional details

This used to work in Statamic 2. 

Our use case for this is to keep email subjects unique, by including a date and time stamp, and so that they are not grouped together as a conversation in email platforms like Gmail.
