### ISSUE TITLE
Table cells don't update properly within replicators

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#4774]
### Bug description

Table data is not updated in Live Preview, and when the live preview is closed, some data is lost.

### How to reproduce

➡️ **I have a table field in a replicator in a bard:** ⬅️ 

```
title: Pages
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: bard_content
        field:
          always_show_set_button: false
          sets:
            one:
              display: One
              fields:
                -
                  handle: blocks
                  field:
                    collapse: false
                    sets:
                      table:
                        display: Table
                        fields:
                          -
                            handle: table
                            field:
                              display: Table
                              type: table
                              icon: table
                              listable: hidden
                              instructions_position: above
                    display: Blocks
                    type: replicator
                    icon: replicator
                    listable: hidden
                    instructions_position: above
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          display: 'Bard Content'
          type: bard
          icon: bard
          listable: hidden
          instructions_position: above
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
      -
        handle: template
        field:
          type: template
          display: Template
          localizable: true
```

I have a template:

```html
    {{ bard_content }}
        {{ partial :src="type" }}
    {{ /bard_content }}
```

```html
{{ blocks }}
    {{ partial :src="type" }}
{{ /blocks }}
```

```html
<table>
    {{ table }}
      <tr>
        {{ cells }}
          <td>{{ value | markdown }}</td>
        {{ /cells }}
      </tr>
    {{ /table }}
</table>
```

When I use Live Preview the data is not updated in the live preview, and when you close the live preview you lose the data you put in a cell. Video here:
https://user-images.githubusercontent.com/6069653/142472601-c288b83e-4a60-485d-a82c-eff6870d92bf.mp4

### Versions

Statamic 3.2.22 Solo
Laravel 8.72.0
PHP 8.0.12
No addons installed

### Installation

Fresh statamic/statamic site via CLI
