### ISSUE TITLE
preProcess() and preProcessIndex() of custom fieldtype are never called

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#479]
We have `app/Fieldtypes/ChannelSelect.php`

```php
<?php

namespace App\Fieldtypes;

use Statamic\Fields\Fieldtype;

class ChannelSelect extends Fieldtype
{
    protected $defaultValue = null;

    public function preProcess($data)
    {
        dump('preProcess called', $data);
        return $data;
    }

    public function preProcessIndex($data)
    {
        dump('preProcessIndex called', $data);
        $cTitle = $data['title'];
        $scTitle = $data['sub_channel']['title'];
        return $scTitle == 'default' ? $cTitle : $cTitle . ' › ' . $scTitle;
    }

    public function process($data)
    {
        return $data;
    }
}
```

and `resources/blueprints/article.yaml` (shortened quite a bit)

```yaml
taxonomies: false
sections:
  main:
    display: Inhalt
    fields:
      -
        handle: title
        field:
          type: text
          display: Titel
          localizable: true
          width: 66
      -
        handle: heading
        field:
          type: text
          display: Dachzeile
          width: 33
      -
        handle: seo_title
        field:
          type: seo_title
          display: SEO-Titel
          validate: required
      -
        handle: channel
        field:
          type: channel_select
          display: Channel
          width: 50
          sortable: false
title: Article
```

and in the article listing, the `channel` column renders its contents as a string even though it's a JSON object. Our `preProcessIndex()` never runs.
