### ISSUE TITLE
Asset field of `mode: grid` doesn't respect `read_only`

### ISSUE THREAD

**Issue by aerni** [statamic/cms#4844]
### Bug description

An asset field with `mode: grid` and `read_only: true`, is in fact not read-only at all. You can still delete the asset. Read-only works for `mode: list` though.

### How to reproduce

1. Add this field to your blueprint:

```yaml
handle: asset
field:
  mode: grid
  container: assets
  restrict: false
  allow_uploads: true
  show_filename: true
  max_files: 1
  display: Asset
  type: assets
  icon: assets
  listable: hidden
  instructions_position: above
```

2. Add an asset to that field.
3. Now add `read_only: true` to the field's config.
4. Go to the entry in the CP and see that you can still delete the asset.

### Versions

Statamic 3.2.24 Pro
Laravel 8.73.2
PHP 8.0.13

### Installation

Fresh statamic/statamic site via CLI

### Additional details

https://user-images.githubusercontent.com/23167701/144194936-d88ecd53-264c-40fd-b5a1-aaccf7a3e197.mov
