### ISSUE TITLE
Conditional fields don't work inside a set

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#491]
Example:

```yaml
sets:
  my_set:
    display: My own set
    fields:
      -
        handle: bla
        field:
          type: toggle
          default: false
          display: Bla
      -
        handle: foo
        field:
          type: text
          display: Foo
          if:
            bla: true
```
