### ISSUE TITLE
Page freezes on save - Introduced in v3.2.28

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#5025]
### Bug description

The page you are editing freezes when using replicator in a nested scenario.  Issue introduced in Statamic version 3.2.28, working fine in 3.2.27

### How to reproduce

- [ ] Create a new page
- [ ] Create a replicator "Page Builder" (IMAGE 1)
- [ ] Add the benefits field type below as a set (IMAGE 2)
- [ ] Add a new replicator additional benefits, which should have a set called benefits_additionals (snippet 2)
- [ ] The fieldset should now look like IMAGE 3
- [ ] In the page, if you know try to do anything within this section, statamic freezes. See video 1

**IMAGE 1**
![image](https://user-images.githubusercontent.com/31292231/148375556-812d7403-3757-4809-959e-14674c1889af.png)

**IMAGE 2**
![image](https://user-images.githubusercontent.com/31292231/148375674-9bb6af2b-1ff4-48f9-ad4e-80c97fa404b1.png)

**IMAGE 3**
![image](https://user-images.githubusercontent.com/31292231/148375794-eced32db-bfbc-42cf-99a0-473d0a68657d.png)

**VIDEO 1**

https://user-images.githubusercontent.com/31292231/148376322-47081cf1-d1e5-4c0e-acae-f850b6a0ac88.mov

**Benefits field type**
```
title: Benefits
fields:
  -
    handle: benefits_intro
    field:
      always_show_set_button: false
      buttons:
        - h3
        - bold
      save_html: false
      toolbar_mode: fixed
      link_noopener: false
      link_noreferrer: false
      target_blank: false
      reading_time: false
      fullscreen: true
      allow_source: true
      enable_input_rules: true
      enable_paste_rules: true
      antlers: false
      display: 'Benefits Intro'
      type: bard
      icon: bard
      listable: hidden
      instructions_position: above
  -
    handle: benefit_sections
    field:
      collapse: false
      sets:
        benefit_section:
          display: 'Benefit Section'
          fields:
            -
              handle: benefit_section_content
              field:
                always_show_set_button: false
                buttons:
                  - h3
                  - bold
                save_html: false
                toolbar_mode: fixed
                link_noopener: false
                link_noreferrer: false
                target_blank: false
                reading_time: false
                fullscreen: true
                allow_source: true
                enable_input_rules: true
                enable_paste_rules: true
                antlers: false
                display: 'Benefit Section Content'
                type: bard
                icon: bard
                listable: hidden
                instructions_position: above
            -
              handle: benefit_section_image
              field:
                mode: list
                container: do
                restrict: false
                allow_uploads: true
                show_filename: true
                max_files: 1
                display: 'Benefit Section Image'
                type: assets
                icon: assets
                listable: hidden
                instructions_position: above
      display: 'Benefit Sections'
      type: replicator
      icon: replicator
      listable: hidden
      instructions_position: above
  -
    handle: benefits_additionals
    field:
      collapse: false
      sets:
        additional_benefit:
          display: 'Additional Benefit'
          fields:
            -
              import: benefits_additionals
      display: 'Additional Benefits'
      type: replicator
      icon: replicator
      listable: hidden
      instructions_position: above
```
**Benefits Additional**
```
title: 'Benefits Additionals'
fields:
  -
    handle: section_title
    field:
      input_type: text
      antlers: false
      display: 'Section Title'
      type: text
      icon: text
      listable: hidden
      instructions_position: above
  -
    handle: list
    field:
      display: List
      type: list
      icon: list
      listable: hidden
      instructions_position: above
```

### Versions

Works fine in 3.2.27 , issue introduced in 3.2.28

```
Statamic 3.2.28 Pro
Laravel 8.78.1
PHP 8.0.12
No addons installed
```

### Installation

Fresh statamic/statamic site via CLI
