### ISSUE TITLE
Asset fields left empty fail fatally

### ISSUE THREAD

**Issue by wesort** [statamic/cms#5043]
### Bug description

Blueprint has an asset field which is optional. If left blank by the author, frontend throws `500` error.

```
TypeError
array_merge(): Argument #1 must be of type array, null given
```

### Expected
To reference an asset variable and if it doesn’t exist for it to gracefully fail (eg: show nothing).

### Blueprint
```
fields:
  -
    handle: portrait
    field:
      type: assets
      container: main
      folder: /
      restrict: false
      max_files: 1
      width: 50
      display: 'Portrait'
```
_NB: Also tested with adding `required: false`

### Template
```
{{ assets:portrait }}
  <img ... >
{{ /assets:portrait }}
```

### Content
Field not used and therefore `portrait` isn’t present with a value.

### Versions

Statamic 3.2.30 Solo
Laravel 7.30.6
PHP 8.0.10
statamic/migrator dev-master

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Caused by augmentation? Regression from the Antlers rewrite?

### Workaround
Wrap `{{ assets }}` tag in a `{{ if }}` statement
