### ISSUE TITLE
Bard in collapsed set causes 'TypeError: this.editor is null'

### ISSUE THREAD

**Issue by stoffelio** [statamic/cms#5061]
### Bug description

Not sure how helpful this will be, but figured I'd report it anyways:

On multiple websites our page content is structured as follows:
- the page blueprint contains a grid named 'sections' which pulls in a fieldset 'section'
- the 'section' fieldset contains a replicator which pulls in a bunch of other fieldsets including 'textblock'
- the 'textblock' contains a bard field (and other fields)

Now whenever I add a 'textblock' to a 'section' I get a couple of the errors ('TypeError: this.editor is null' in vendor.js:2:1186069) in the browser console. This happens only with fieldsets that contain a bard field.

This doesn't seem to cause any major issues besides the error messages in the console, at least not that I can see. I can save the pages and the data persists, but opening the page in the CP seems very sluggish with the error.

### How to reproduce

Create the above content structure, I've been able to reproduce it on multiple sites we run.

### Versions

At least 3.2.19 - 3.2.30, probably earlier

### Installation

Fresh statamic/statamic site via CLI

**Comment by stoffelio** [comment]
It would appear that I have found the culprit: in the section replicator I had _all sets collapsed by default_ set since we work this some pretty long content pages. When I set it to _all sets expanded by default_ instead, the error does not occur. So I guess with the sets being collapsed, the tiptap editor is not created properly on page load, creating the error message described above.

**Comment by leonchris** [comment]
This happens to me as well when you have bard field within replicator and set collapse to accordion it crashes the javascript as described above.

Here is an example that will cause the crash:
```
     -
        handle: test
        field:
          type: replicator
          sets:
            item:
              display: item
              fields:
                -
                  handle: title
                  field:
                    type: text
                    display: Title
                    width: 50
                -
                  handle: text
                  field:
                    type: bard
                    restrict_assets: false
                    display: Text
                    save_html: true
                    buttons:
                      - bold
                      - italic
                      - underline
                      - h1
                      - h2
                      - h3
                      - h4
                      - h5
                      - h6
                      - anchor
          localizable: true
          display: Test
          instructions_position: above
          listable: hidden
          read_only: false
          collapse: accordion
```

Without the collapse it will not crash:
```
      -
        handle: test
        field:
          type: replicator
          sets:
            item:
              display: item
              fields:
                -
                  handle: title
                  field:
                    type: text
                    display: Title
                    width: 50
                -
                  handle: text
                  field:
                    type: bard
                    restrict_assets: false
                    display: Text
                    save_html: true
                    buttons:
                      - bold
                      - italic
                      - underline
                      - h1
                      - h2
                      - h3
                      - h4
                      - h5
                      - h6
                      - anchor
          localizable: true
          display: Test
```
