### ISSUE TITLE
Grid with date/time looks a bit off

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#5073]
### Bug description

<img width="891" alt="CleanShot 2022-01-14 at 10 25 42@2x" src="https://user-images.githubusercontent.com/6069653/149566380-446ded8d-aef2-438d-ac4e-443d25988708.png">

### How to reproduce

Fieldset:

```
    handle: days
    field:
      type: grid
      mode: table
      fields:
        -
          handle: date
          field:
            type: date
            allow_blank: false
            allow_time: false
            require_time: false
            input_format: M/D/YYYY
            width: 33
            display: Date
        -
          handle: start_time
          field:
            type: time
            width: 33
            display: 'Start Time'
        -
          handle: end_time
          field:
            type: time
            width: 33
            display: 'End Time'
      display: Days
      min_rows: 2
      add_row: 'Add Day'
      instructions_position: above
      listable: hidden
      reorderable: true
      if:
        multi_day: 'equals true'
```

### Versions

```
Statamic 3.2.30 Pro
Laravel 8.79.0
PHP 8.0.14
aryehraber/statamic-captcha 1.7.0
aryehraber/statamic-uuid 2.0.3
edalzell/forma 1.0
edalzell/private-eye dev-main
jonassiewertsen/statamic-livewire 2.7.1
statamic/seo-pro 2.3.2
transformstudios/events 3.3
transformstudios/front 1.7.1
transformstudios/gated dev-main
transformstudios/magic-link dev-main
transformstudios/review 3.1.1
transformstudios/shopify dev-main
transformstudios/simple dev-main
transformstudios/stripe dev-main
transformstudios/takeover-redirects dev-main
```

### Installation

Starter Kit using via CLI
