### ISSUE TITLE
Fieldset field handles causing errors in Bard

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#5087]
### Bug description

I have a Button field set with the fields:
- type
- url
- document
- entry
- form

If I add this fieldset to a Bard field then I get the following errors after hitting the Add Set button:
```
vue.common.prod.js:6 TypeError: Cannot read properties of undefined (reading 'display')
vue.common.prod.js:6 TypeError: f.hasAttribute is not a function
```

I can solve this by prefixing each field width btn_, so they become:
- btn_type
- btn_url
- btn_document
- btn_entry
- btn_form

This is fine but I don't understand the problem. Should fieldset fields always be prefixed or am I using a reserved name for a field?

I've seen some comments stating that custom validation rules for fields that are nested in fieldsets should be defined like so:
`button.entry` or `button.btn_entry`
So I'm finding the naming of fields a little confusing.

### How to reproduce

Set up a fieldset with this YAML then link it as a set in a Bard field.

```
title: Button
fields:
  -
    handle: type
    field:
      options:
        document: Document
        entry: Entry
        url: Url
      multiple: false
      clearable: false
      searchable: true
      taggable: false
      push_tags: false
      cast_booleans: false
      default: url
      display: 'Button Type'
      type: select
      icon: select
      width: 50
      listable: hidden
      instructions_position: above
      validate:
        - required
  -
    handle: entry
    field:
      max_items: 1
      mode: default
      create: true
      collections:
        - articles
        - pages
        - posts
      display: Entry
      type: entries
      icon: entries
      width: 50
      listable: hidden
      instructions_position: above
      validate:
        - 'required_if:button.type,entry'
      if:
        type: 'equals entry'
  -
    handle: document
    field:
      mode: list
      restrict: false
      allow_uploads: true
      show_filename: true
      max_files: 1
      display: Document
      type: assets
      icon: assets
      width: 50
      listable: hidden
      instructions_position: above
      container: documents
      validate:
        - 'required_if:button.type,document'
      if:
        type: 'equals document'
  -
    handle: url
    field:
      input_type: url
      antlers: false
      display: URL
      type: text
      icon: text
      width: 50
      listable: hidden
      instructions_position: above
      validate:
        - 'required_if:button.type,url'
      if:
        type: 'equals url'
  -
    handle: label
    field:
      input_type: text
      antlers: false
      display: Label
      type: text
      icon: text
      width: 50
      listable: hidden
      instructions_position: above
      validate:
        - required

```

### Versions

Statamic 3.2.29 Pro
Laravel 8.78.0
PHP 8.1.1
edalzell/blade-directives 3.5.1

### Installation

Fresh statamic/statamic site via CLI
