### ISSUE TITLE
sort="order|title" does not work

### ISSUE THREAD

**Issue by michaelmannucci** [statamic/cms#5098]
### Bug description

Coming from [here](https://github.com/statamic/ideas/issues/740)

Seems like sorting by more than one param does not work for me.

### How to reproduce

My tags are:

```
{{ collection:people speaker:is="true" sort="order|title" }}
    <li onClick="filters('{{ slug }}','speaker')" class="py-2 px-4 hover:text-white hover:bg-color transition duration-200 cursor-pointer">
        {{ title }}
    </li>
{{ /collection:people }}
```
I have instead tried `sort_by="order|title"`, `sort="order, title"`, `sort="order title"` and nothing has worked.

### Logs

```shell
There is no error and no logs regarding this issue
```

### Versions

Statamic 3.2.31 Pro
Laravel 8.79.0
PHP 8.1.1
michaelmannucci/verseoftheday 1.1.0     
spatie/statamic-responsive-images 2.8.5 
visuellverstehen/statamic-classify 2.3.1

### Installation

Fresh statamic/statamic site via CLI

**Comment by jackmcdade** [comment]
Is your collection an ordered collection with a `max_depth` of 1?

**Comment by michaelmannucci** [comment]
Looks like yes:

```
title: '3. People'
template: people/show
layout: layout
revisions: false
route: 'people/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
structure:
  root: false
  max_depth: 1
  ```
