### ISSUE TITLE
Button-Group / Radios / Checkboxes saving numbers as string 

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#5103]
### Bug description

If your keys are numbers, the content will saved as string, like `size: '300'`. If you want to use now modifiers like subtract, multiply, etc. you will see an error, because the modifiers can't work with strings.

### How to reproduce

```
        handle: buttons
        field:
          options:
            200: 200px
            300: 300px
            400: 400px
          type: button_group
          listable: true
          display: Buttons
          default: 200
          instructions_position: above
```

### Versions

Statamic 3.2.28 Pro
Laravel 7.30.6
PHP 8.0.12

### Installation

Fresh statamic/statamic site via CLI
