### ISSUE TITLE
Range fieldtype does not save as integer

### ISSUE THREAD

**Issue by mmuro** [statamic/cms#5180]
### Bug description

According to the documentation a Range fieldtype saves as an integer. However, it saves the value as a string.

In the screenshot below you can see how an Integer fieldtype saves the value compared to the Range fieldtype.

<img width="292" alt="range-integer" src="https://user-images.githubusercontent.com/999324/151878853-40d1cd53-72b3-4183-a672-c9980abd0d02.png">

I discovered this by trying to use a Range value as part of the mod modifier and getting a type conversion error.

### How to reproduce

1. Add a Range fieldtype
2. Save the page
3. Check the value type

### Versions

Statamic 3.2.32 Pro
Laravel 8.81.0
PHP 8.1.1
aryehraber/statamic-uuid 2.0.3
cnj/seotamic 2.0.5

### Installation

Fresh statamic/statamic site via CLI

**Comment by Konafets** [comment]
Hey @mmuro, 

your screenshot does not looks like the YAML for the Range fieldtype. A newly created Range ft looks like this:

```yaml
handle: range
field:
  step: 1
  min: 0
  max: 100
  default: 42
  prepend: prepend
  append: append
  display: Range
  type: range
  icon: range
  listable: hidden
  instructions_position: above
```

**Comment by jasonvarga** [comment]
His screenshot seems like the data for the range field, not the blueprint.

I can confirm it does save a string.

**Comment by mmuro** [comment]
I have a Fieldset with these fields, so I'm not sure if that makes a difference. Here is the blueprint for each field:
```yaml
handle: rows
field:
  default: '3'
  display: Rows
  type: integer
  icon: integer
  width: 50
  listable: hidden
  instructions_position: above
```

```yaml
handle: rows_range
field:
  min: 1
  max: 10
  step: 1
  default: '3'
  display: 'Rows Range'
  type: range
  icon: range
  listable: hidden
  instructions_position: above
```

I notice that my default value in the Range field is a string whereas yours is an integer.
