### ISSUE TITLE
`sort` modifier fails in combination with `list` modifier

### ISSUE THREAD

**Issue by Konafets** [statamic/cms#5253]
### Bug description

The [docs](https://statamic.dev/modifiers/sort) showing an example about the how to pipe a sorted array to the `list` modifier:  `{{ primitive | sort | list }}`

When I tried this, I get this error:

```
TypeError
implode(): Argument #2 ($array) must be of type ?array, Illuminate\Support\Collection given
```

It breaks in `Modifiers/CoreModifiers.php:885` where the `$value` is a Collection instead of an array.

### How to reproduce

I recreated this very example from the docs:

Blueprint.yaml
```yaml
      -
        handle: primitive
        field:
          mode: dynamic
          display: 'Sorting Test'
          type: array
          icon: array
          listable: hidden
          instructions_position: above
```

Content.md (Frontmatter)
```yaml
primitive:
  - Zulu
  - Tango
  - Alpha
  - Bravo
```

show.antlers.html
```handlebars
{{ primitive | sort | list }}
```

### Versions

3.2

### Installation

Fresh statamic/statamic site via CLI
