### ISSUE TITLE
`flip` modifier produces broken output.

### ISSUE THREAD

**Issue by Konafets** [statamic/cms#5259]
### Bug description

It seems to me that this is a bug in the Docs and in the CMS.

I used essentially this example from the docs about the `flip` modifier: https://statamic.dev/modifiers/flip

When I just loop through the array like so:

```handlebars
{{ favorites }}
    My favorite {{ key }} is {{ value }}.
{{ /favorites }}
```

I got no output at all.

When I add the `flip` modifier like:

```handlebars
{{ favorites | flip }}
    My favorite {{ key }} is {{ value }}.
{{ /favorites }}
```

I get this output:

> My favorite is . {{ /favorites }}

### How to reproduce

Blueprint:

```yaml
        handle: favorites
        field:
          mode: keyed
          display: favs
          type: array
          icon: array
          listable: hidden
          instructions_position: above
```

I created the same structure like in the docs:

Frontmatter:

```yaml
favorites:
  chicken: nuggets
  nuggets: Denver
```

(First difference to the docs is the missing dash `-` between "favorites" and the content of the array.

### Versions

3.2

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
The `flip` modifier is working correctly.

However, yes, that docs page is wrong in multiple ways, we can fix it.

Use the parameter syntax on a tag pair, like this: `flip="true"`

Flipping it would result in this:

```yaml
favorites:
  nuggets: chicken
  Denver: nuggets
```

Then you can do `{{ nuggets }}` and `{{ Denver }}`.

There's no `{{ value }}` or `{{ key }}`.
