### ISSUE TITLE
Grid within grid doesn't work correctly with min_row

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/cms#5301]
### Bug description

As the title says, something goes wrong when adding a second element to a grid which has a nested grid with `min_row:1`
There seems to be added a "ghost" row for times that can't be edited.

![image](https://user-images.githubusercontent.com/1186125/154507494-d9519d51-3714-40db-9882-f8f685312fd9.png)

![image](https://user-images.githubusercontent.com/1186125/154507342-8bc3926b-0bfa-4b76-922d-466230960476.png)

### How to reproduce

Add this field to any blueprint:
```yaml
-
  handle: dates
  field:
    type: grid
    display: Dates
    add_row: Date
    min_rows: 1
    mode: stacked
    fields:
      -
        handle: date
        field:
          type: date
          display: Date
          validate:
            - required
          width: 50
      -
        handle: doors_open
        field:
          display: 'Doors Open'
          type: time
          width: 50
      -
        handle: times
        field:
          type: grid
          display: Times
          add_row: Times
          min_rows: 1
          fields:
            -
              handle: start
              field:
                type: time
                display: Start
                validate:
                  - required
            -
              handle: end
              field:
                type: time
                display: End
                validate:
                  - 'after:start'
          validate:
            - required
```

### Logs

```shell
{
    "message":"The given data was invalid.",
    "errors":{
        "dates.1.times.0.start":["This field is required."]
    }
}
```

### Versions

Statamic 3.2.33 Pro
Laravel 8.83.0
PHP 8.0.15
jacksleight/statamic-bard-mutator 1.0.3

### Installation

Fresh statamic/statamic site via CLI

### Additional details

We have added a custom style override, since time fields weren't displayed properly (see #5073)
```css
.grid-table td.time-fieldtype {
    width: auto;
}
```
