### ISSUE TITLE
Form Submit redirects to `http://domain.test/!/forms/form_handle`

### ISSUE THREAD

**Issue by sjclark** [statamic/cms#5355]
### Bug description

I've made an absolute boilerplate setup based on completely fresh Statamic install to try and resolve an issue I'm having across multiple sites. Most code below is copy-pasted directly from the docs due to me trying to strip it back to the most basic setup.

Submitting a form **saves the data, sends an email; and then redirects to a 404 Not found to** `http://domain.test/!/forms/form_handle`

Here is my `home.antlers.html`:
```
{{ content }}

{{ form:test_form }}
 
    // First let's check if this is after a submission, and if so, was it successful.
    // If it was, just show the success message. After all, we don't want them submitting again once they've gotten in touch!
    {{ if success }}
        <div class="bg-green-300 text-white p-2">
            {{ success }}
        </div>
    {{ else }}
        // If we weren't successful, show any errors. If a fresh page load, there's no errors, so do nothing.
        {{ if errors }}
            <div class="bg-red-300 text-white p-2">
                {{ errors }}
                    {{ value }}<br>
                {{ /errors }}
            </div>
        {{ /if }}
 
        // Loop through and render the form inputs
        {{ fields }}
            <div class="p-2">
                <label>{{ display }}</label>
                <div class="p-1">{{ field }}</div>
                {{ if error }}
                    <p class="text-gray-500">{{ error }}</p>
                {{ /if }}
            </div>
        {{ /fields }}
 
        // This is just a submit button.
        <button type="submit">Submit</button>
    {{ /if }}
 
{{ /form:test_form }}
```
Here is `resources/blueprints/forms/test_form.yaml`
```
sections:
  main:
    display: Main
    fields:
      -
        handle: name
        field:
          input_type: text
          antlers: false
          display: Name
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: phone_number
        field:
          input_type: text
          antlers: false
          display: 'Phone Number'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: email
        field:
          input_type: text
          antlers: false
          display: Email
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: enquiry
        field:
          antlers: false
          display: Enquiry
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
```
Here is `resources/forms/test_form.yaml`
```
title: 'Test Form'
email:
  -
    to: sam@test.nz
    from: sam@test.nz
    reply_to: sam@test.nz
    subject: 'TMR Website Form Submission'
```
Exerpt from `.env`
```
MAIL_MAILER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=xx
MAIL_PASSWORD=yy
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=sam@test.nz
```

### How to reproduce

Create a basic form with a few basic fields.
Add to front-end.
Have data saved, email sent, but form 404 redirect.

### Logs

```shell
Nothing is logged.
```

### Versions

Statamic 3.2.33 Solo
Laravel 8.83.2
PHP 8.0.13
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Additional details

I created the above after having issues with a slightly more complex setup (Captcha, and Postmark). But removed absolutely everything to strip it back to the most basic install, and still can't get it to work.

Don't have static caching, or anything like that on, literally the above on a fresh Statamic project. Have tried both secured and unsecured.

More than happy to provide the entire project.

Having this issue both locally and in production (Ubuntu 20 via Ploi @ Vultr)
