### ISSUE TITLE
3.3 beta - Short glide tags throw error in new runtime parser

### ISSUE THREAD

**Issue by ryanmitchell** [statamic/cms#5356]
### Bug description

Using an assets field with a max number of 1 allowed you to do something like the following in the regex parser:

`{{ glide:thumbnail width="189" height="114" dpr="2" format='webp' }}`

However in the new runtime parser it throws an error:

`pathinfo(): Argument #1 ($path) must be of type string, array given`

Changing the tag as follows works:

`{{ glide:thumbnail:0 width="189" height="114" dpr="2" format='webp' }}`

Will this change be required?

### How to reproduce

Have a blueprint field as follows:

```yaml
      -
        handle: thumbnail
        field:
          mode: list
          container: assets
          restrict: true
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Thumbnail
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          instructions: ''
          folder: news
```

### Versions

3.3.0 beta 2

### Installation

Fresh statamic/statamic site via CLI
