### ISSUE TITLE
Can't re-order the entries in a structure

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#539]
I have a Structure connected to an orderable collection:
```yaml
title: Pages
collections:
  - pages
expects_root: true
root: 543dbb36-42dc-47c9-bcc7-c611fd96da9a
```

Collection

```yaml
title: Page
route: '/{slug}'
dated: false
blueprints:
  - page
orderable: true
structure: pages
entry_order:
  - 543dbb36-42dc-47c9-bcc7-c611fd96da9a
  - 674dc18b-693e-4c80-9314-994a239cf86e
  - 0833e122-af36-4d03-8735-04d2fe8b7377
```

In the Structure config page, there's no place to re-order the "pages" (entries). I had to set that order manually.
