### ISSUE TITLE
3.3 beta – Undefined variable when accessing any entry

### ISSUE THREAD

**Issue by devingray** [statamic/cms#5395]
### Bug description

Undefined variable when accessing any entry

### How to reproduce

When editing my page I wanted to make use of the live preview feature and when clicking it it gave me a weird 

`[object object]`  

![livepreview@2x](https://user-images.githubusercontent.com/11573528/156548986-89a41f6c-ff47-4ebf-a6cc-b0e270c0299c.png)

So I looked at my composer and noticed that I am on the `v3.3.0-beta.3` version, as this is beta I decided to fix to a specific version `3.2.35` as this is lates release

However now when I try to access any entry I get the following error

![screenshot@2x](https://user-images.githubusercontent.com/11573528/156549330-46ca2143-5ecf-4e6c-a42f-d5ef4b16c419.png)

### Versions

PHP 8.1
Laravel 8.83.2

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
What's the output when you run `php please support:details`? It looks like you're running the Statamic 3.3 beta.

**Comment by devingray** [comment]
Statamic 3.3.0-beta.3 Pro
Laravel 8.83.2
PHP 8.1.3
edalzell/blade-directives 3.5.2

**Comment by jasonvarga** [comment]
Just to be clear, you're only seeing `Undefined variable $previewTargets` when you downgrade back to 3.2?
Run `php artisan view:clear` and see if you still get it.

As for the Live Preview issue on 3.3, what does your template look like?

**Comment by devingray** [comment]
@jasonvarga Thank you, I fee dumb for not clearing the view to solve this, it happens. 

However when on 3.3.0-beta.3 the live preview thing still persists. The template file does not matter as even if I replace my entire rendered file with 
```
<p>Hello World</p>
```
I still only see the white screen with `[object Object]`

**Comment by jasonvarga** [comment]
Can you share your `content/collections/{handle}.yaml` file?

**Comment by devingray** [comment]
```
title: Ratgeber
sites:
  - default
  - {company-redacted}-germany
  - {company-redacted}-austria
  - {company-redacted}-switzerland
  - {company-redacted}-luxemburg
template: ratgeber/show
layout: layouts/blog
mount: e099a0a7-4bfa-426f-9c46-f49ef2cced33
taxonomies:
  - category
revisions: false
route: "/ratgeber/{category}/{slug}"
date: true
sort_dir: asc
date_behavior:
  past: public
  future: private

```
