### ISSUE TITLE
Users fieldtype/data can't be related/retrieved

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#541]
With this blueprint:
```yaml
      -
        handle: author
        field:
          type: users
          display: Author
          width: 50
          max_items: 1
          default: current
```

And this data:
```yaml
author: 950f647a-7fff-49f9-9904-87be70619d26
```

Neither of these Antlers calls work:
```html
{{ author }} {{ first_name }} {{ /author }} {{ relate:author }}{{ first_name }}{{ /relate:author }}
```
