### ISSUE TITLE
Asset focal point not stored in meta data

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#543]
I used the CP to move a focal point, but I don't see it in the asset's meta data:
```yaml
data:
  text: 'DLs @ Canada Day'
size: 1313126
last_modified: 1550786540
width: 1937
height: 2437
```
