### ISSUE TITLE
Asset fieldtype in collection causes error

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#544]
When I am on a CP entry url (http://dl3.test/cp/collections/blog/entries/4057d2c0-e1c9-46c8-a283-438ea920d204/my-ev-one-year-in), I get an error: https://cl.ly/05f8263b0385.

blueprint:
```yaml
title: 'Blog Post'
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          localizable: true
          display: Title
          type: text
          width: 33
      -
        handle: slug
        field:
          type: slug
          width: 33
          display: Slug
      -
        handle: date
        field:
          time_enabled: true
          time_required: true
          earliest_date: 'January 1, 1900'
          type: date
          width: 33
          display: Date/Time
      -
        handle: author
        field:
          type: users
          display: Author
          width: 50
          max_items: 1
          default: current
      -
        handle: link
        field:
          display: Link
          type: text
          validate: url
          width: 50
      -
        handle: content_block
        field:
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
          save_html: null
          toolbar_mode: fixed
          link_noopener: null
          link_noreferrer: null
          target_blank: null
          reading_time: null
          fullscreen: true
          allow_source: true
          type: replicator
          instructions: null
          localizable: false
          width: 100
          display: Content
          sets:
            media:
              display: Media
              fields:
                -
                  handle: media
                  field:
                    type: assets
                    container: main
            text:
              display: Text
              fields:
                -
                  handle: text
                  field:
                    type: markdown
```

Entry:
```yams
title: 'My EV - One Year In'
author: 950f647a-7fff-49f9-9904-87be70619d26
content_block:
  - 
    type: text
    text: |
      We've owned our Nissan Leaf for almost a full year, and it is, without a doubt, the best car I've ever owned (note, I've only owned 5 cars and this is the first truly new car). Note we "only" got the old $5k provincial credit, not the new, additional $5k federal one nor the $6k Scrap It one.
      
      It now has 25K kms on it. If that had been my previous car (a 2005 Kia Spectra), it would have cost ~$3,500 on gas (~9.4L/100K @ $1.5/L) and ~$3000 in maintenance.
      
      Instead it's cost ~$700 in energay costs and $100 in maintenance (annual check up), for gross savings of $6,500. My payments are around $6000/year, so I'm up around $500 over the year.
      
      Naturally, as the gas prices go up, these numbers get better. And of course, my payments will stop in a few years, making an even better deal.
      
      My only real complaint is that the Bluetooth module is not super reliable and I we often have to restart the car to get it to connect (which only takes about 15 secs).
      
      Only once have I ever been really low in battery; when I left my house with only 75% charge then drove to Cypress Mountain and back. Arrived home, with some aggressive battery safe driving, with 8% charge, about 20kms left.
id: 4057d2c0-e1c9-46c8-a283-438ea920d204
tags:
  - ev
```

Container:
```yaml
title: Main
disk: local
blueprint: image
```
