### ISSUE TITLE
Bard produces invalid HTML on some tag combinations

### ISSUE THREAD

**Issue by goldnead** [statamic/cms#5481]
### Bug description

Especially, when combining links with other tags, like **bold**, bard seems to mess up the order of tag closings, leading to issues like:
```html
<a href="https://custom-link-tag.com" target="_blank"><strong>Link that should be bold</a></strong>
```

Since modern browsers handle wrong tag-pair closings quite verbose it might just stay undetected until one experiences some weird css-issues or uses a HTML-Syntax validator.

I also noticed, that the issue occurs when marks are stored with links first, like:
```yaml
-
  type: text
  marks:
    -
      type: link
      attrs:
        href: 'https://custom-link-tag.com'
        rel: null
        target: null
        title: null
      text: 'https://custom-link-tag.com'
    -
      type: bold
```

When the order inside `marks` is reversed, it seems to render without issues.

The produced yaml-files seem to be all right, that's why I suspect an issue on somewhere the rendering-front, probably something regarding the package `ueberdosis/prosemirror-to-php` as it seems to be discontinued?

### How to reproduce

1. Create a Bard fiel in a blueprint with at least `link` and `bold` tags enabled.
2. Write something into the field, combining both tags.
3. Create a template that renders given bard field and check the html-source

### Versions

Statamic 3.2.37 Pro
Laravel 8.83.4
PHP 8.0.8

### Installation

Fresh statamic/statamic site via CLI

**Comment by sjclark** [comment]
I've experienced this same issue on multiple sites and could not figure out how it had occurred
```html
<a href="https://domain.co.nz/agreement"><strong>Agreement</a> </strong>
```
While it's not show-stopping, it's also clearly not correct

**Comment by arthurperton** [comment]
This looks like an issue that was [fixed](https://github.com/ueberdosis/prosemirror-to-html/commit/52136fbe65466e2b2788d2593fee9a1f7688f7dc) in `ueberdosis/prosemirror-to-html` [v2.6.0](https://github.com/ueberdosis/prosemirror-to-html/releases/tag/2.6.0).

Could you check your installed version by running `composer show ueberdosis/prosemirror-to-html` on you command line?

**Comment by sjclark** [comment]
The two sites I've noticed this on (recently) are both running 2.7.0
```
keywords : prosemirror
versions : * 2.7.0
```

For reference in terms of current versions of the two sites:
```
Statamic 3.2.28 Pro (Site 1) / Statamic 3.2.33 Pro (Site 2)
Laravel 8.77.1 (Site 1) / Laravel 8.80.0 (Site 2)
PHP 8.0.13
aryehraber/statamic-captcha 1.7.0
spatie/statamic-responsive-images 2.8.5
```
It's possible the malformation has persisted through from a previous revision so I'll try test some point soon, although @goldnead will likely get to it before me 😂

**Comment by goldnead** [comment]
The sites, on which I'm experiencing the error also run the same version:

```
keywords : prosemirror
versions : * 2.7.0
```

**Comment by vonox7** [comment]
@arthurperton I also have the same issue. Steps to reproduce (Statamic 3.3.58):

1. write this HTML: ```<p><span style="text-align: center; display: block">this is centered<br></span><strong><span style="text-align: center; display: block">and this line below is bold</span></strong></p>```
<img width="868" alt="image" src="https://user-images.githubusercontent.com/621501/203856151-abd671a4-3a0f-437b-9695-d81a4f1765b4.png">
2. the saved .md file has the following content:
```
---
id: xxx
blueprint: xxx
title: 'xxxt'
updated_by: xxx
updated_at: xxx
content:
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: textAlign
            attrs:
              align: center
        text: 'this is centered'
      -
        type: hard_break
        marks:
          -
            type: textAlign
            attrs:
              align: center
      -
        type: text
        marks:
          -
            type: bold
          -
            type: textAlign
            attrs:
              align: center
        text: 'and this line below is bold'
---
```
3. the resulting HTML (fetched via REST API) is invalid HTML:
```<p><span style="text-align:center;display :block">this is centered<br><strong>and this line below is bold</span></strong></p>```
