### ISSUE TITLE
Path not resolving for inline images coming from an external container (GCS)

### ISSUE THREAD

**Issue by djmenkveld** [statamic/cms#5482]
### Bug description

The problem is that images are not being displayed inline, when my images are loaded from an external container, in this case GCS.

Problem 1: image not shown in preview mode
Problem 2: image src not set in API (example: https://content.yosokugames.com/api/collections/www_tournamentfootball_co_uk/entries/48)

This is my setup:

Configuration:

**filesystems.php**
```
 'gcs' => [
            'driver' => 'gcs',
            'project_id' => env('GOOGLE_CLOUD_PROJECT_ID', 'yosoku-games'),
            'key_file' => env('GOOGLE_CLOUD_KEY_FILE', null),
            'bucket' => env('GOOGLE_CLOUD_STORAGE_BUCKET', 'assets.yosokugames.com'),
            'path_prefix' => env('GOOGLE_CLOUD_STORAGE_PATH_PREFIX', null),
            'storage_api_uri' => env('GOOGLE_CLOUD_STORAGE_API_URI', null),
            'url' => env('GOOGLE_CLOUD_ASSETS_URL', '/assets'),
            'visibility' => 'public',
        ],
```

**.env**
```
GOOGLE_CLOUD_PROJECT_ID=yosoku-games
GOOGLE_CLOUD_KEY_FILE=/var/www/html/config/gcs-user.json
GOOGLE_CLOUD_STORAGE_BUCKET=assets.yosokugames.com
GOOGLE_CLOUD_STORAGE_PATH_PREFIX=content
GOOGLE_CLOUD_STORAGE_API_URI=https://storage.googleapis.com
GOOGLE_CLOUD_ASSETS_URL=https://assets.yosokugames.com/content
```

**GoogleStorageService.php**
```
    \Storage::extend('gcs', function($app, $config) {
            $storageClient = new StorageClient([
                'projectId' => $config['project_id'],
                'keyFilePath' => $config['key_file'],
            ]);

            $bucket = $storageClient->bucket($config['bucket']);
            $storageApiUri = $config['storage_api_uri'];

            $adapter = new GoogleStorageAdapter($storageClient, $bucket, 'content', $storageApiUri);

            return new Filesystem($adapter);
        });
```

**gcs.yaml** located in src/content/assets
```
title: GCS
disk: gcs
allow_uploads: true
allow_downloading: true
allow_renaming: true
allow_moving: true
create_folders: true
```

Fieldset config:
**content_item.yaml** located in src/resources/fieldsets
```
title: 'Content Item'
...
-
    handle: content
    field:
      restrict: false
      automatic_line_breaks: true
      automatic_links: false
      escape_markup: false
      smartypants: false
      antlers: false
      container: gcs
      display: Content (use Markdown, no HTML)
      type: markdown
      icon: markdown
      listable: hidden
      validate:
        - required
```

Collection config:
**www_tournamentsoccer_us.yaml** located in src/resources/blueprints/collections/www_tournamentsoccer_us
```
title: www.tournamentsoccer.us
sections:
  main:
    display: Main
    fields:
      -
        import: content_item
        config:
          title:
            required: true
```

### How to reproduce

1. Composer require superbalist/laravel-google-cloud-storage
2. Setup configuration for a bucket
3. Try adding images inline
4. Try the api endpoint for the collection and see that the permalink and url are not set. Also in the content <img src="">

### Versions

Statamic 3.2.37 Pro
Laravel 8.83.4
PHP 8.0.16
statamic/eloquent-driver 0.1.2

### Installation

Fresh statamic/statamic site via CLI
