### ISSUE TITLE
Problem with depth in nested navigation with new Antlers parser

### ISSUE THREAD

**Issue by speercy** [statamic/cms#5554]
### Bug description

The new `runtime` Antlers parsers seems to trip up when using `{{ depth }}` in `{{ nav }}` tags.

### How to reproduce

On a fresh installation of Statamic into an existing Laravel app, create navigation that has nested levels:

```
tree:
  -
    id: 7c15e122-9057-483f-82d9-2e481431c5bf
    title: Home
    url: /
  -
    id: d5e0312d-2c9d-4746-aeed-ace069a6331a
    title: About
    url: /about
    children:
      -
        id: 52486fc9-b997-48af-b57f-ecdd56cd840e
        title: Team
        url: /about/team
        children:
          -
            id: 73f82f54-78df-4987-90e6-d5ded3020a45
            title: Leadership
            url: /about/team/leadership
  -
    id: 94f69c31-237b-4237-ba55-177ef0929449
    title: Projects
    url: /projects
    children:
      -
        id: 9b3a4919-40b0-4a3b-9b8b-44a427d16c07
        title: Supernova
        url: /projects/supernova
      -
        id: c5ab4d57-d53b-429b-ae50-7b1086cc8ab0
        title: Meadow
        url: /projects/meadow
        children:
          -
            id: e602b108-701d-403b-a206-ce86449995c7
            title: Discussion
            url: /projects/meadow/discussion
  -
    id: 9ca8bf85-089c-4f97-b449-2230eb21fc5d
    title: Contact
    url: /contact
```

Now set up the following in a view:

```
{{ nav:main include_home="true" }}
    <div>{{ depth }} {{ title }}</div>
    {{ if children }}
        {{ *recursive children* }}
    {{ /if }}
{{ /nav:main }}
```

Using the old `regex` Antlers parser, the output is what you would expect:

```
1 - Home
1 - About
2 - Team
3 - Leadership
1 - Projects
2 - Supernova
2 - Meadow
3 - Discussion
1 - Contact
```

But under the new `runtime` parser:

```
1 - Home
1 - About
2 - Team
3 - Leadership
1 - Projects
1 - Supernova
1 - Meadow
2 - Discussion
1 - Contact
```

### Versions

Statamic 3.3.1 Solo
Laravel 9.5.1
PHP 8.1.3
No addons installed

### Installation

Existing Laravel app
