### ISSUE TITLE
Aliasing entries of collection in runtime antlers throws an exception

### ISSUE THREAD

**Issue by jbrhel** [statamic/cms#5566]
### Bug description

I have an entries fieldset "contacts" of the collection Contacts:

```
  -
    handle: contacts
    field:
      mode: typeahead
      create: true
      collections:
        - contacts
      display: Contacts
      type: entries
      icon: entries
```

When entries is alised I'm getting "**_Call to a member function all() on array_**" in runtime mode. Regex mode works as expected.

```
{{ contacts as="contact_items" }}
    {{ if !no_results }}
        <div class="block">
            <div class="block__container">
                {{ contact_items }}
                    {{ partial:partials/contact_locket }}
                {{ /contact_items }}
            </div>
        </div>
    {{ /if }}
{{ /contacts }}
```

### How to reproduce

- runtime mode version set in antlers config
- use entries pair tag with an aliasing inside the antlers template (see above)

### Versions

Statamic 3.3.x-dev Pro
Laravel 8.83.5
PHP 8.1.1
jacksleight/bard-mutator 0.1.4
octoper/statamic-html-minify 0.0.5

### Installation

Starter Kit using via CLI
