### ISSUE TITLE
Can't add rows to second grid in a replicator set

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#564]
We have a replicator field with a set which in turn has two grid fields (in table mode). Clicking 'Add Row' on one of them only works if I didn't click 'Add Row' on the other grid field before. When I click the button for the grid field I didn't use before, the page freezes until I let Firefox kill the script. After that, no JS works on the page (no surprise there).

This blueprints recreates the bug:

```yaml
title: Test
sections:
  main:
    fields:
      -
        handle: title
        field:
          type: text
      -
        handle: blocks
        field:
          type: replicator
          sets:
            opinion:
              fields:
                -
                  handle: teasers
                  field:
                    type: grid
                    mode: table
                    fields:
                      -
                        handle: article
                        field:
                          type: relationship
                          collections: [ article ]
                          max_items: 1
                          width: 75
                          create: false
                      -
                        handle: layout
                        field:
                          type: select
                          options:
                            xxl: 'XXL'
                            xl: 'XL'
                            xl-compact: 'XL-Compact'
                            l: 'L'
                            l-compact: 'L-Compact'
                            m: 'M'
                            m-compact: 'M-Compact'
                            m-wide: 'M-Wide'
                            s: 'S'
                            s-wide: 'S-Wide'
                          width: 25
                          default: m
                -
                  handle: columnists
                  field:
                    type: grid
                    mode: table
                    fields:
                      -
                        handle: author
                        field:
                          type: relationship
                          collections: [ author ]
                          max_items: 1
                          width: 50
                          create: false
                          validate: required
                      -
                        handle: topic
                        field:
                          type: relationship
                          collections: [ topic ]
                          max_items: 1
                          width: 50
                          create: false
```
