### ISSUE TITLE
Multi-site: Navigation blueprint fields are not filtered by site

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#5643]
### Bug description

When viewing a navigation entry, the "entries" fields are not filtered by site.
<img width="1271" alt="Screen Shot 2022-03-25 at 11 43 31 am" src="https://user-images.githubusercontent.com/414211/160033063-8875e7b2-ecb1-4b30-93d7-3a11cf2c0db4.png">

### How to reproduce

- Create multi-site
- Add navigation with blueprint with entries field
- Edit Navigation in CP
- View navigation entry

### Versions

Statamic 3.3.3 Pro
Laravel 9.5.1
PHP 8.0.13
aerni/advanced-seo 1.0.2
doublethreedigital/duplicator 2.1.1
mattrothenberg/statamic-mapbox-address 0.7.2
mikemartin/helpscout-beacon 1.0.2
reachweb/multisite-propagator 1.0.0
rias/statamic-color-swatches 2.0.5
rias/statamic-redirect 2.1.1
spatie/statamic-responsive-images 2.11.0
webographen/statamic-widget-continue-editing 1.0.1

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

### Additional details

Navigation blueprint:
```
sections:
  main:
    display: Main
    fields:
      -
        handle: description
        field: common.description
      -
        handle: plans
        field:
          type: entries
          collections:
            - plans
          display: Plans
          mode: select
          localizable: true
      -
        handle: amounts
        field:
          fields:
            -
              handle: plan
              field:
                max_items: 1
                mode: select
                display: Plan
                type: entries
                listable: hidden
                localizable: true
                collections:
                  - plans
            -
              handle: value
              field:
                localizable: true
                input_type: text
                antlers: false
                display: Value
                type: text
                icon: text
                listable: hidden
          mode: table
          reorderable: true
          display: 'Plan Amount'
          type: grid
          icon: grid
          listable: hidden
          add_row: 'Add Amount'
          localizable: true
      -
        handle: info_tip
        field:
          type: toggle
          display: 'Info Tip'
          localizable: true
      -
        handle: new
        field:
          type: toggle
          localizable: true

```
