### ISSUE TITLE
Relationship field with ö in display name breaks the select stack

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#566]
For example, this field will make the query that's sent when opening the select stack fail:

```yaml
-
  handle: authors
  field:
    type: polygon_relationship
    display: Autör/en
    collections: [ author ]
    create: false
    sortable: false
    width: 50
```

This is the content of the decoded config parameter:

```json
{"type":"polygon_relationship","display":"Autr/en","collections":["author"],"create":false,"sortable":false,"width":50,"max_items":0,"mode":null,"component":"relationship","handle":"authors","instructions":null,"required":false}
```

Note how the ö is missing in there.
