### ISSUE TITLE
Links to home inside replicator fields using slots work just once

### ISSUE THREAD

**Issue by potentweb** [statamic/cms#5667]
### Bug description

When using the new runtime parser there were times when content was rendering fine but then disappearing on the next load. If you used `php artisan cache:clear` it would show again but again disappear on subsequent loads.

I narrowed it down to:

1. having a link to the homepage (`statamic://entry::home` in the page yaml) in a replicator field. This is how a bard field with a link to the homepage saves.
2. Using a slot in a partial to help render the content.

Please note:

- The bug does **not** happen on the home page
- Links to any other pages worked fine (saved like `statamic://entry::{guid}`)
- The link needs to be in a replicator field
- Using a partial with a slot is required to trigger the bug

### How to reproduce

Starting from a brand new repo, change to use the new runtime parser:

1. Add a replicator field to the page blueprint. Create a bard field in the set.
2. Create a new page (the bug will **not** trigger on the home page).
3. On that new page create a new set / new bard field and create a link to the home page using the editor. In the page markdown it will look  something like this:

```
replicator_field:
  -
    bard_field:
      -
        type: paragraph
        content:
          -
            type: text
            marks:
              -
                type: link
                attrs:
                  href: 'statamic://entry::home'
                  rel: null
                  target: null
                  title: null
            text: 'Link to home'
    type: new_set
    enabled: true
```

4. On your view add code something like this:

```
    {{ replicator_field }}
        {{ partial src="wrap" }}
            {{ bard_field }}
        {{ /partial }}
    {{ /replicator_field}}
```

The wrap partial simply includes `{{ slot }}`. If you don't have this partial the bug does not trigger. If `bard_field` is not inside a replicator the bug does not trigger.

5. Go to your page (not home). The bard_field should be rendered. Hit refresh and nothing is rendered.

### Logs

```shell
Nothing comes through on the logs.
```

### Versions

Statamic 3.3.3 Solo
Laravel 9.5.1
PHP 8.0.17
No addons installed

### Installation

Other (please explain)

### Antlers Parser

runtime (new)

### Additional details

Intalled using composer create
