### ISSUE TITLE
Taxonomy data leaks into custom collection loop when taxonomy slug is used in route

### ISSUE THREAD

**Issue by FlorianMoser** [statamic/cms#5698]
### Bug description

The taxonomy details provided to the entry seem to leak into loops, when the taxonomy slug is used in the collections route `{taxonomy_slug}/{slug}`.

When viewing the page for such an entry, and looping over items of the same collection on that page, an error "Cannot render an object variable as a string: {{ taxonomy_slug }}" is shown in the logs.

In the loop the logic probably fetches the taxonomy_slug for each entry to generate its URL/permalink but somehow uses the parent taxonomy_slug data provided to the entry/page.

### How to reproduce

1. Create a new project
2. in `config/statamic/antlers.html` set the `version` to "runtime"
3. Create a collection (ie "news)
4. Create a taxonomy (ie "topic") and assign it to the collection
5. In the collection blueprint make sure to limit the number of taxonomies to 1 (max_items: 1)
6. In the collection setting set the route to `{topic}/{slug}`
7. Create an entry in the taxonomy, for example "test"
8. Create an entry in the news collection, "news-1". Don't assign a taxonomy
9. Create a second entry, "news-2" and assign the "test" taxonomy
10. Add `{{ collection:news }}{{ /collection:news }}` to the default.antlers.html template
11. Now open `/news-1`. Everything is fine.
12. Now open `/test/news-2` and visit the logs. You should see the error below.

### Logs

```shell
[2022-03-30 10:45:23] local.DEBUG: Cannot render an object variable as a string: {{ topic }}
```

### Versions

Statamic 3.3.3 Solo
Laravel 9.6.0
PHP 8.0.16
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

resources/blueprints/collections/news/news.yaml
```
title: news
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
      -
        handle: topic
        field:
          type: terms
          taxonomies:
            - topic
          display: topic
          mode: select
          instructions_position: above
          listable: hidden
          read_only: false
          max_items: 1
          create: true
```

content/collections/news.yaml
```
title: news
template: default
layout: layout
taxonomies:
  - topic
revisions: false
route: '{topic}/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
```
