### ISSUE TITLE
Select field push tag issue

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#5713]
### Bug description

`push_tags` don't appear to work? 

I've set `Allow additions` and `Push Tags` in a `select_field` but when adding new tags they don't get saved?

### How to reproduce

Add this to a blueprint, then try to add a new option. It'll allow a new option to be created, but it doesn't save it so it can be selected again in another entry?

```
 handle: country_code_select_field
        field:
          options:
            '+44': null
            '+1': null
          multiple: false
          max_items: 1
          clearable: true
          searchable: true
          taggable: true
          push_tags: true
          cast_booleans: false
          display: 'Country Code'
          type: select
          icon: select
          width: 25
          listable: true
          instructions_position: above
          read_only: false
          instructions: 'Add or pick a code'
```

### Versions

```
Statamic 3.3.4 Pro
Laravel 9.5.1
PHP 8.0.8
simonhamp/statamic-heroicons 1.0.1
statamic/collaboration 0.4.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
