### ISSUE TITLE
Select field value not listable?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#5714]
### Bug description

I've set the `select_field` to have a `listable: true` but it's value isn't shown in a collection listing?

![Screenshot 2022-03-31 at 16 26 49](https://user-images.githubusercontent.com/72254741/161092901-0ef76a18-5bfb-4850-b4ce-fc775ffdebcf.png)

### How to reproduce

Add this to a blueprint
```
handle: country_code_select_field
        field:
          options:
            '+44': null
            '+1': null
          multiple: false
          max_items: 1
          clearable: true
          searchable: true
          taggable: true
          push_tags: true
          cast_booleans: false
          display: 'Country Code'
          type: select
          icon: select
          width: 25
          listable: true
          instructions_position: above
          read_only: false
          instructions: 'Add or pick a code'
```
- Pick an option from the select field
- Add `country_code_select_field` to collection list
- It's blank?

### Versions

```
Statamic 3.3.4 Pro
Laravel 9.5.1
PHP 8.0.8
simonhamp/statamic-heroicons 1.0.
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
