### ISSUE TITLE
Missing ›save‹ button on assets editing popup

### ISSUE THREAD

**Issue by maltemichels** [statamic/cms#5720]
### Bug description

The ›save‹ button isn't visible on the editing popup for an asset.
![statamic-missing_save_button](https://user-images.githubusercontent.com/24814661/161258598-82117e13-c2ee-42b4-b568-b5e53d66845b.jpg)

### How to reproduce

When the size/ratio of an image is e.g. square and 3000px wide it pushes the ›save‹ button out of the viewport, when it’s height is larger then the viewports. Mostly the case for 16:9 screens, if you drag the window smaller you can see the buttons coming back in.

### Versions

Statamic 3.3.4 Pro
Laravel 8.83.5
PHP 7.4.28
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by arthurperton** [comment]
Hi @maltemichels, thanks for your report. I was not able to reproduce the issue just by using a 3000x3000 pixel image. However, I see that you have several custom fields in you asset blueprint that may be relevant to the issue. So can you please share the following:

- Your asset blueprint YAML file
- Also just to be sure, please tell us which browser you are using

**Comment by maltemichels** [comment]
Hi @arthurperton, thanks for digging into this.
Sure, here is the YAML file for my assets container.
I experienced this issue in Safari (v15.4), Firefox (v98.0) and Vivaldi (5.0).

```
title: Fotografien
sections:
  main:
    display: Hauptteil
    fields:
      -
        handle: alt
        field:
          display: 'Kurzbeschreibung (optional)'
          type: text
          instructions: 'Beschreibung des Motivs (u.a. für Screen-Reader)'
          instructions_position: above
          listable: hidden
          read_only: false
          input_type: text
          antlers: false
          width: 50
      -
        handle: fotografie_kategorien
        field:
          mode: default
          create: true
          taxonomies:
            - fotografie_kategorien
          display: 'Fotografie Kategorien'
          type: terms
          icon: taxonomy
          width: 50
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: fotografie_mit_filmrand
        field:
          mode: list
          container: fotografien
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: 'Fotografie mit Filmrand'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          read_only: false
          validate:
            - image
      -
        handle: beschreibung
        field:
          always_show_set_button: false
          buttons:
            - anchor
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          antlers: false
          display: Beschreibung
          type: bard
          icon: bard
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: audio_datei
        field:
          mode: list
          container: fotografien
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: 'Audio Datei'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          read_only: false
```

**Comment by arthurperton** [comment]
That's weird, I am consistently seeing this in Chrome, Safari and Firefox, all buttons stay visible regardless of how I resize the window 🤔

<img width="1944" alt="Screenshot 2022-04-04 at 12 23 05" src="https://user-images.githubusercontent.com/4067531/161524942-4dcc4053-4709-4312-9d18-9ed6e4b04edf.png">

I tried it when editing an asset from the asset page, and when editing an asset from an asset field in an entry. Is there anything you can think of that I should do differently to reproduce your issue?

**Comment by arthurperton** [comment]
This is the image I am using. I also just changed the Control Panel language to German, but there's no difference.

![3000x3000](https://user-images.githubusercontent.com/4067531/161525824-1a3a483e-8db8-463f-acde-4401b21b7efb.jpg)

**Comment by maltemichels** [comment]
Hm, I just found another project, where I'm not having this issue and I've looked into the styles:

**Installation with issue:**
cp.scss:99
vendor/statamic/cp/css/cp.css?v=3.3.4
```
.asset-editor .editor-preview .image-wrapper {
  display: flex;
  align-items: center;
  height: 100%;
  width: 100%;
  justify-content: center;
  position: relative;
}

.asset-editor .editor-preview .image-wrapper>* {
  max-width: 100%;
  max-height: 100%;
  width: 100%;
  box-shadow: 0 0 32px rgba(0,0,0,.35);
}
```

**The one, which works fine:**
assets.scss:311
vendor/statamic/cp/css/cp.css?v=3.3.2
```
.asset-editor .editor-preview .image-wrapper {
  flex: 1 1 auto;
  position: relative;
}
```
cp:scss:99
```
.asset-editor .editor-preview .image-wrapper>* {
  position: absolute;
  width: auto;
  height: auto;
  max-width: 100%;
  max-height: 100%;
  box-shadow: 0 0 32px rgba(0,0,0,.35);
  left: 50%;
  top: 50%;
  transform: translate(-50%,-50%);
}
```

When I exchange these two blocks of CSS it seems fixed, but I'm not quite sure why the styles are different.
I've no addons installed or adjusted an styles concerning the control panel.

And even if I updated the working installation to 3.3.4 the issue didn't appeared. Is there a smart way to reinstall statamic with the existing templates etc.? Maybe something got messed up in the process.

**Comment by maltemichels** [comment]
But also I'm wondering what's happening, because I've got the same issue in my two most recent projects.
What could I've done? 🤔

**Comment by arthurperton** [comment]
Well that is weird. The second version you're showing (repeated below) is the latest and correct css, which [fixes an overflow issue](https://github.com/statamic/cms/pull/5689) since v3.3.4.

I don't know how the old css could have ended up in your v3.3.4 install. Perhaps just a simple `composer install` might help, as it also copies the latest Statamic resources to the public folder. And be sure to do a 'hard refresh' in your browser afterwards of course. Good luck!

```css
.asset-editor .editor-preview .image-wrapper {
  flex: 1 1 auto;
  position: relative;
}

.asset-editor .editor-preview .image-wrapper > * {
  position: absolute;
  width: auto;
  height: auto;
  max-width: 100%;
  max-height: 100%;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
  box-shadow: 0 0 32px rgba(0, 0, 0, 0.35);
}
```
