### ISSUE TITLE
nl2br rendering additional </br> at end of string

### ISSUE THREAD

**Issue by benfurfie** [statamic/cms#5743]
### Bug description

I have a text field within a fieldset, called text. This fieldset is called hero.

When I call the text using the _nl2br_ modifier, it renders an additional `<br>` tag.

### How to reproduce

**hero.yaml fieldset**
```yaml
title: Hero
fields:
  -
    handle: heading
    field:
      input_type: text
      antlers: false
      display: 'Page Heading'
      type: text
      icon: text
      instructions: 'Optional. You can use this field to overwrite what appears at the top of the page if the title isn''t appropriate.'
      listable: hidden
      instructions_position: above
      read_only: false
  -
    handle: text
    field:
      antlers: false
      display: Text
      type: textarea
      icon: textarea
      listable: hidden
      instructions_position: above
      read_only: false
  -
    handle: links
    field:
      fields:
        -
          handle: label
          field:
            input_type: text
            antlers: false
            display: Label
            type: text
            icon: text
            width: 50
            listable: hidden
            instructions_position: above
            read_only: false
        -
          handle: link
          field:
            collections:
              - pages
              - legal
            display: Link
            type: link
            icon: link
            width: 50
            listable: hidden
            instructions_position: above
            read_only: false
      mode: stacked
      max_rows: 2
      min_rows: 0
      add_row: 'Add Link'
      reorderable: true
      display: Links
      type: grid
      icon: grid
      listable: hidden
      instructions_position: above
      read_only: false
```

**MD file**
```markdown
hero.text: |-
  Say goodbye to _work from home_, without the commute.
  Embrace the _work from anywhere_ revolution!
```

**Antlers**
```antlers
<div class="mt-4 leading-7 text-gray-500 font-cursive text-5 md:text-10 md:leading-12 em-wavy">{{ hero.text | markdown | strip_tags:p,em,br | nl2br }}</div>
```

### Versions

3.3.4

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
