### ISSUE TITLE
"Upload" button not showing in assets field

### ISSUE THREAD

**Issue by wautersj** [statamic/cms#5751]
### Bug description

When you have an assets field with the capability of uploading new assets, and the field has already previously selected assets, and the assets pane opens, there is no upload button in the top bar.

However, the upload still works by dragging the assets into the window.

Not critical, but inconvenient.

### How to reproduce

- Click 'browse' on the assets field (not limited to a count, upload enabled, ...)
- The assets pane opens.
- Select a few assets
- Click 'select'
- Click 'browse' again
- The assets pane opens.
- Now the upload button is gone.

![Screenshot 2022-04-05 at 13 13 25](https://user-images.githubusercontent.com/4070167/161741926-7a26ca17-3256-46b0-8e71-0a5fe5f1ed52.png)

![Screenshot 2022-04-05 at 13 13 34](https://user-images.githubusercontent.com/4070167/161741943-534a30bb-732a-4ce1-b72e-0ce6d0c7b603.png)

### Versions

PHP Version | 7.4.28
Statamic Pro | 3.2.32

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
What does the asset field look like in your blueprint? I just created one in a site I'm working on and it shows for me - might have to do with how the field is configured.

Also, as a workaround, you can also click the 'Upload file' link, next to 'Browse'.

**Comment by wautersj** [comment]
@duncanmcclean yes, if you click the 'upload file' you get the file prompt, but then it just uploads the file in the root of the container. Which with quite robust sites, it not very useful.

The fieldset of the field: 

```
handle: logo_assets
    field:
      mode: grid
      container: assets
      restrict: false
      allow_uploads: true
      show_filename: true
      display: 'Logo assets'
      type: assets
      icon: assets
      instructions: 'Will be rendered 80px in height, so best uploaded as retina in 160px. De width can be variable; make sure the logo is edge to edge to the bounding-box horizontally.'
      listable: hidden
      instructions_position: above
```
