### ISSUE TITLE
Replicator causes 'unsaved changes' on publish form loading

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#578]
This works fine, no unsaved changes when you load the entry edit page:

```yaml
taxonomies: false
title: Homepage
sections:
  main:
    display: Nachrichtenblöcke
    fields:
      -
        handle: title
        field:
          type: text
          display: Titel
```

This shows unsaved changes as soon as the page loads:

```yaml
taxonomies: false
title: Homepage
sections:
  main:
    display: Nachrichtenblöcke
    fields:
      -
        handle: title
        field:
          type: text
          display: Titel
      -
        handle: blocks_news
        field:
          type: replicator
          display: Nachrichtenblöcke
```
