### ISSUE TITLE
No output if taxonomy referenced in a taxonomy terms fieldtype has the same spelling as the fieldtype handle.

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#5827]
### Bug description

Using the same slug for a taxonomy terms fieldtype as the handle for the taxonomy prevents you from then listing your taxonomies in the view.

This worked earlier but was introduces in one of the last versions.

It is the same issue no matter if i use the regex or runtime parser

### Create taxonomy
- Create a taxonomy called `discipline`, and similar blueprint as image shows.

<img width="274" alt="image" src="https://user-images.githubusercontent.com/31292231/163031876-4ee0098a-5166-40fa-9813-67ee9d238eba.png">

<img width="936" alt="image" src="https://user-images.githubusercontent.com/31292231/163031935-56df8301-8389-4f55-a2ba-d00266b726bd.png">

### Use the taxonomy terms fieldtype on your page and make sure you name this field discipline and then add some tags.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/31292231/163032030-3c944682-d8e3-438b-8a7b-0fa1c3c16f5d.png">

```
      -
        handle: discipline
        field:
          mode: default
          create: true
          taxonomies:
            - discipline
          display: Discipline
          type: terms
          icon: taxonomy
          listable: false
          instructions_position: above
          read_only: false
```

### Add code to your view to list them
```
{{ discipline }}
    {{ title }}
{{ /discipline }}
```

As you will notice, there are no titles displaying. The issue as it seems is in the naming. When the field handle is the same as the taxonomy used in the fieldtype.

If you simply change the handle in the snippet above to `discipline_alt_name` and do 

```
{{ discipline_alt_name }}
    {{ title }}
{{ /discipline_alt_name }}
```

It works as intended

### Versions

Statamic 3.3.6 Pro
Laravel 8.83.8
PHP 8.0.12
doublethreedigital/duplicator 2.1.1
jonassiewertsen/statamic-livewire 2.9.0
transformstudios/review 3.2.1

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
