### ISSUE TITLE
The `to_json` modifier doesn't handle nested query builders

### ISSUE THREAD

**Issue by ottz0** [statamic/cms#5866]
### Bug description

I've added an Assets field inside of a replicator. I've uploaded 1 or multiple images which adds the image/s to the .md file. I can view and change the images in the CP, however when I view the object it is empty.

### How to reproduce

Create a Replicator, add images to the set. Show the image

```
imageset:
  -
    title: test
    logos:
      - logos/logo1.svg
      - logos/logo1.svg
      - logos/logo1.svg
    type: test1
    enabled: true
```

`{{imageset | to_json | entities }}`

Logos shows an empty object, I can view title

`[{"title”:”test”,”logos":{},"type”:”test1”},{“title”:”another,”logos":{},"type”:”test”2}]
`

### Versions

php 8.1

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Laravel Sail
