### ISSUE TITLE
SyntaxError: missing name after . operator after updating to 3.3.7

### ISSUE THREAD

**Issue by jannejava** [statamic/cms#5907]
### Bug description

After updating to Statamic 3.3.7 I cannot save on certain collections. However, if I roll back to Statamic 3.3.6 it's working again.

### How to reproduce

<img width="1086" alt="CleanShot 2022-04-25 at 11 06 35@2x" src="https://user-images.githubusercontent.com/543616/165057479-9b88bf7a-80be-42c7-afef-ccefd5352308.png">

* Update to Static 3.3.7
* Have multi site enabled
* Create a collection as below with a Replicator Field

### Logs

```shell
I cannot see anything in the logs. It seems to be a JavaScript-only problem.
```

### Versions

Statamic 3.3.7 Pro
Laravel 8.83.9
PHP 7.4.28
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

I am happy to provide more info. If I remove the entries on the replicator fields it seems to work again. The site has multisite enabled.

```yaml

hide: true
title: 'Region Index'
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
          localizable: true
      -
        handle: hero
        field:
          collapse: false
          sets:
            hero:
              display: Hero
              fields:
                -
                  handle: headline
                  field:
                    input_type: text
                    antlers: false
                    display: Rubrik
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                -
                  handle: sub_headline
                  field:
                    input_type: text
                    antlers: false
                    display: Underrubrik
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    read_only: false
                -
                  handle: content
                  field:
                    always_show_set_button: false
                    buttons:
                      - h2
                      - h3
                      - bold
                      - italic
                      - unorderedlist
                      - orderedlist
                      - removeformat
                      - quote
                      - anchor
                      - image
                      - table
                    save_html: false
                    toolbar_mode: fixed
                    link_noopener: false
                    link_noreferrer: false
                    target_blank: false
                    reading_time: false
                    fullscreen: true
                    allow_source: true
                    enable_input_rules: true
                    enable_paste_rules: true
                    antlers: false
                    display: Innehåll
                    type: bard
                    icon: bard
                    listable: hidden
                    instructions_position: above
                    read_only: false
                -
                  handle: button_1_text
                  field:
                    input_type: text
                    antlers: false
                    display: 'Knapp 1 – text'
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                -
                  handle: button_1_href
                  field:
                    display: 'Knapp 1 – länk'
                    type: link
                    icon: link
                    listable: hidden
                    instructions_position: above
                -
                  handle: button_2_text
                  field:
                    input_type: text
                    antlers: false
                    display: 'Knapp 2 – text'
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                -
                  handle: button_2_href
                  field:
                    display: 'Knapp 2 – länk'
                    type: link
                    icon: link
                    listable: hidden
                    instructions_position: above
          display: Hero
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above
          read_only: false
          localizable: true
      -
        handle: call_to_action_1
        field:
          collapse: false
          sets:
            call_to_action_1:
              display: 'Call to action'
              fields:
                -
                  handle: subheading
                  field:
                    input_type: text
                    antlers: false
                    display: Överskrift
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    validate:
                      - required
                -
                  handle: headline
                  field:
                    input_type: text
                    antlers: false
                    display: Rubrik
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    validate:
                      - required
                -
                  handle: content
                  field:
                    always_show_set_button: false
                    buttons:
                      - h2
                      - h3
                      - bold
                      - italic
                      - unorderedlist
                      - orderedlist
                      - removeformat
                      - quote
                      - anchor
                      - image
                      - table
                    save_html: false
                    toolbar_mode: fixed
                    link_noopener: false
                    link_noreferrer: false
                    target_blank: false
                    reading_time: false
                    fullscreen: true
                    allow_source: true
                    enable_input_rules: true
                    enable_paste_rules: true
                    antlers: false
                    display: Text
                    type: bard
                    icon: bard
                    listable: hidden
                    instructions_position: above
                    read_only: false
                -
                  handle: button_text
                  field:
                    input_type: text
                    antlers: false
                    display: 'Knapp – text'
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                -
                  handle: button_link
                  field:
                    display: 'Knapp – länk'
                    type: link
                    icon: link
                    listable: hidden
                    instructions_position: above
          display: 'Call to action'
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above
          read_only: false
          localizable: true
      -
        handle: call_to_action_2
        field:
          collapse: false
          sets:
            call_to_action_1:
              display: 'Call to action'
              fields:
                -
                  handle: subheading
                  field:
                    input_type: text
                    antlers: false
                    display: Överskrift
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    validate:
                      - required
                -
                  handle: headline
                  field:
                    input_type: text
                    antlers: false
                    display: Rubrik
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    validate:
                      - required
                -
                  handle: content
                  field:
                    always_show_set_button: false
                    buttons:
                      - h2
                      - h3
                      - bold
                      - italic
                      - unorderedlist
                      - orderedlist
                      - removeformat
                      - quote
                      - anchor
                      - image
                      - table
                    save_html: false
                    toolbar_mode: fixed
                    link_noopener: false
                    link_noreferrer: false
                    target_blank: false
                    reading_time: false
                    fullscreen: true
                    allow_source: true
                    enable_input_rules: true
                    enable_paste_rules: true
                    antlers: false
                    display: Text
                    type: bard
                    icon: bard
                    listable: hidden
                    instructions_position: above
                    read_only: false
                -
                  handle: button_text
                  field:
                    input_type: text
                    antlers: false
                    display: 'Knapp – text'
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                -
                  handle: button_link
                  field:
                    display: 'Knapp – länk'
                    type: link
                    icon: link
                    listable: hidden
                    instructions_position: above
          display: 'Call to action'
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above
          read_only: false
          localizable: true
  sidebar:
    display: Sidebar
    fields:
      -
        handle: language
        field:
          options:
            sv: Svenska
            en: Engelska
          multiple: false
          max_items: 1
          clearable: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          default: sv
          display: Språk
          type: select
          icon: select
          listable: hidden
          instructions_position: above
          validate:
            - required
          localizable: true
      -
        handle: template
        field:
          default: region_index
          display: Template
          type: hidden
          icon: hidden
          listable: hidden
          instructions_position: above
          validate:
            - required
      -
        handle: slug
        field:
          type: slug
          localizable: true
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
  seo:
    display: SEO
    fields:
      -
        handle: seo_title
        field:
          input_type: text
          antlers: false
          display: Titel
          type: text
          icon: text
          instructions: 'Visas vid sökresultat och delningar på sociala medier'
          listable: hidden
          instructions_position: above
          read_only: false
          localizable: true
      -
        handle: seo_description
        field:
          antlers: false
          display: Beskrivning
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          read_only: false
          localizable: true
      -
        handle: og_image
        field:
          mode: list
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Bild
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          read_only: false
          localizable: true

```

```yaml

---
id: 113c6249-6c9d-4038-bf78-ac06e27f8b78
blueprint: region_index
title: Hem
language: sv
hero:
  -
    headline: 'asdfasdfa!'
    content:
      -
        type: paragraph
        content:
          -
            type: text
            text: 'asdfasdfasdf'
    button_1_text: asdf'
    button_1_href: '#'
    button_2_text: 'asdf'
    button_2_href: '#'
    type: hero
    enabled: true
    sub_headline: "asdfasdfasdf"
template: region_index
updated_at: 1650878246
call_to_action_1:
  -
    subheading: 'asdfasdfasf?'
    headline: 'asdfasdf'
    content:
      -
        type: paragraph
        content:
          -
            type: text
            text: 'asdfasdfasdf.'
      -
        type: paragraph
        content:
          -
            type: text
            text: 'asdfasdfasdf.'
    button_text: 'asdfasdfasd'
    button_link: 'entry::4b43fae3-7767-40c1-a4ff-c55f711b2b08'
    type: call_to_action_1
    enabled: true
call_to_action_2:
  -
    subheading: 'Om asdfasdf'
    headline: 'asdfasdfasdf!'
    content:
      -
        type: paragraph
        content:
          -
            type: text
            text: 'asdfasdfasdfasdfasdfasdf '
      -
        type: paragraph
        content:
          -
            type: text
            text: 'asdfasdfasdf'
    type: call_to_action_1
    enabled: true
    button_link: 'entry::4a0c839d-8dfe-4e84-8430-60c63f6b17ad'
seo_title: Page
seo_description: 'En beskrivning av sidan'
---


```
