### ISSUE TITLE
Setting the `blueprint` in the create collection wizard doesn't actually set the blueprint

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#593]
I used the wizard to create a collection, and chose and existing blueprint.

No `blueprint`s were saved in the yams:
```yaml
title: Gallery
route: 'gallery/{slug}'
default_status: published
orderable: true
revisions: false
date: false
```
