### ISSUE TITLE
Content gets deleted in replicator fields after reordering

### ISSUE THREAD

**Issue by JoeriE** [statamic/cms#6034]
### Bug description

Hi,

When reordering items in my replicator field some of their content gets deleted and I've no idea why. It only happens with the fields with handle image, internal_video or external_video.

### How to reproduce

I've made a video to explain the issue a bit more: https://option5.studio/issue.mov
As you can see, after the content is reordered the 'internal_video' and 'image' data are deleted.

This is the replicator field:
```      
      -
        handle: items_replicator
        field:
          collapse: true
          sets:
            item:
              display: item
              fields:
                -
                  handle: text
                  field: default.text_simple
                  config:
                    buttons:
                      - bold
                    display: Text
                -
                  import: media
          display: Items
          type: replicator
          icon: replicator
          localizable: true
          listable: hidden
          instructions_position: above
          read_only: false
```

### Versions

Statamic 3.3.11 Pro
Laravel 8.83.8
PHP 8.0.17

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
