### ISSUE TITLE
Sets with Bard and Replicator fields clash causing `Unexpected end of JSON input` errors in Omitter.js

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#6176]
### Bug description

I'm running into a `SyntaxError: Unexpected end of JSON input` error when saving entries. This error is being thrown by JavaScript before the request is sent. I've tracked it down to the `jsonDecodeValue` method in `Omitter.js`, which appears to be trying to parse an actual array to `JSON.parse` instead of a JSON string.

This is happening with a replicator field and seems to occur with a set configuration like this:

- Replicator Field
    - Set A
        - Bard Field
    - Set B
        - Replicator Field

If you use this configuration, and the two inner fields have the same handle, the error will occur when inserting a new B set between two existing A sets and then saving.

I've tried to figure out what's going on, and I _think_ I know roughly what's happening:

When the Bard fields inside the A sets are mounted they call `setFieldSubmitsJson` with their field path. But, when a new B set is added between the two A sets the path change of the Bard inside the second A set doesn't seem to be getting updated correctly in `jsonSubmittingFields`. Because of this `Omitter.js` fetches the wrong value (the Replicator's value), and as the Replicator value is an actual array and not a JSON string the error is thrown.

At least, that's what I _think_ is going on. I could be wrong.

The same issue occurs if you move a B set into the position of an existing A set.

### How to reproduce

1. Create a new collection using the blueprint below
2. Create a new entry in that collection, add two Set A to the replicator field, save and reload
3. Insert a new B set between the two A sets
4. Save
5. Error is thrown

### Versions

Statamic 3.3.13 Pro
Laravel 9.17.0
PHP 8.1.2

### Installation

Fresh statamic/statamic site via CLI

### Additional details

```yaml
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: builder
        field:
          collapse: false
          sets:
            a:
              display: A
              fields:
                -
                  handle: content
                  field:
                    always_show_set_button: false
                    buttons:
                      - h2
                      - h3
                      - bold
                      - italic
                      - unorderedlist
                      - orderedlist
                      - removeformat
                      - quote
                      - anchor
                      - image
                      - table
                    save_html: false
                    toolbar_mode: fixed
                    link_noopener: false
                    link_noreferrer: false
                    target_blank: false
                    reading_time: false
                    fullscreen: true
                    allow_source: true
                    enable_input_rules: true
                    enable_paste_rules: true
                    antlers: false
                    display: 'Bard Field'
                    type: bard
                    icon: bard
                    listable: hidden
                    instructions_position: above
                    read_only: false
            b:
              display: B
              fields:
                -
                  handle: content
                  field:
                    collapse: false
                    sets:
                      new_set:
                        display: 'New Set'
                        fields: {}
                    display: 'Replicator Field'
                    type: replicator
                    icon: replicator
                    listable: hidden
                    instructions_position: above
                    read_only: false
          display: 'Replicator Field'
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above
          read_only: false
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
title: Test
```

**Comment by jesseleite** [comment]
@jacksleight Can you also test to see if #6261 resolves your Omitter JS error here? I can't reproduce this one atm.

**Comment by jacksleight** [comment]
@jesseleite That PR doesn't fix this issue for me, however based your fix for the other issue I think I've found a solution to to this one.

In `BardFieldtype.vue` I added:

```js
watch: {

    // ...

    fieldPathPrefix(fieldPathPrefix, oldFieldPathPrefix) {
        this.$store.commit(`publish/${this.storeName}/setFieldSubmitsJson`, fieldPathPrefix);
        this.$store.commit(`publish/${this.storeName}/unsetFieldSubmitsJson`, oldFieldPathPrefix);
    },

},
```
```js
beforeDestroy() {
    // ...

    this.$store.commit(`publish/${this.storeName}/unsetFieldSubmitsJson`, this.fieldPathPrefix || this.handle);
},
```

Then in `Container.vue` I added:

```js
unsetFieldSubmitsJson(state, dottedKey) {
    const index = state.jsonSubmittingFields.indexOf(dottedKey);
    if (index !== -1) {
        state.jsonSubmittingFields.splice(index, 1);
    }
},
```

In re-testing I found another case of this happening, when you remove a Set A and replace it with a Set B, which is the reason for the `beforeDestroy()` addition as well.

**A bit more info if it might help reproduce this:**

Using the blueprint above, the entry below, and the https://github.com/statamic/cms/pull/6261 PR, here is a video of what I'm seeing:

https://user-images.githubusercontent.com/126740/176398399-3e4715a2-9462-40dc-9b3f-bef63c77c5d3.mp4

```yaml
---
id: 99cad6f7-2f52-4a95-b42f-a85478310e1e
blueprint: test
title: 'Test JSON Error'
updated_by: 32ce8ba0-181b-49ff-853d-1e6b52e1a27e
updated_at: 1656493201
builder:
  -
    type: a
    enabled: true
  -
    type: a
    enabled: true
---
```
