### ISSUE TITLE
Empty Grid row action when min/max equal

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#6245]
### Bug description

If you have a grid with `min_items` and `max_items` set the same, you get an empty action menu

<img width="891" alt="CleanShot 2022-06-23 at 10 23 50@2x" src="https://user-images.githubusercontent.com/6069653/175358310-222bba08-7762-4a3d-9b1a-fcb8741d3206.png">

### How to reproduce

Have this field in a blueprint:

```yaml
      -
        handle: grid_field
        field:
          mode: table
          max_rows: 2
          min_rows: 2
          reorderable: true
          display: 'Grid Field'
          type: grid
          icon: grid
          listable: hidden
          instructions_position: above
          read_only: false
          fields:
            -
              handle: text_field
              field:
                input_type: text
                antlers: false
                display: 'Text Field'
                type: text
                icon: text
                listable: hidden
                instructions_position: above
                read_only: false
```

### Versions

```
Statamic 3.3.16 Solo
Laravel 9.18.0
PHP 8.1.7
No addons installed
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
