### ISSUE TITLE
Data is lost when moving a Bard/Replicator set containing hidden fields

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#6257]
### Bug description

Running into an issue where data is lost if you move a Bard set that contains a Revealer/hidden field without opening the revealer. Any values in the hidden fields are removed from the markdown file on save.

The same issue happens with replicators as well, if you move a set into the position of a different set that doesn't contain the hidden field.

Not sure if it could be related to https://github.com/statamic/cms/issues/6018 or  https://github.com/statamic/cms/issues/6034

Although it's a very different problem it feels like it could even be related to https://github.com/statamic/cms/issues/6176, where the Omitter data isn't being updated when things move around.

### How to reproduce

1. Create a collection and blueprint with a Bard field that contains a set that contains hidden fields (sample below)
2. Create a new entry, add some text and a set to the Bard field
3. Open the revealer and add a value to the hidden field
4. Save
5. Check the markdown, everything looks good
6. Reload the page
7. Move the set to another position within the Bard field
8. *Dont open the revealer*
9. Save
10. Check the markdown, the hidden field's value has gone

The value is still in the field in the CP if you open the revealer, and actually reappears in the markdown if you then save. But if you leave the page without opening the revealer it's gone forever.

### Versions

Statamic 3.3.16 Solo
Laravel 9.18.0
PHP 8.1.7

### Installation

Starter Kit using via CLI

### Additional details

Test Blueprint:

```yaml
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: bard_field
        field:
          always_show_set_button: false
          sets:
            new_set:
              display: 'New Set'
              fields:
                -
                  handle: text_field_1
                  field:
                    input_type: text
                    antlers: false
                    display: 'Text Field 1'
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    read_only: false
                -
                  handle: text_field_2
                  field:
                    input_type: text
                    antlers: false
                    display: 'Text Field 2'
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    read_only: false
                    if:
                      revealer_field: 'equals true'
                -
                  handle: revealer_field
                  field:
                    mode: button
                    display: 'Revealer Field'
                    type: revealer
                    icon: revealer
                    listable: hidden
                    instructions_position: above
                    read_only: false
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          antlers: false
          display: 'Bard Field'
          type: bard
          icon: bard
          listable: hidden
          instructions_position: above
          read_only: false
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
title: Test
```
