### ISSUE TITLE
Grouping a Collection is not working as expected

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#6303]
### Bug description

I follow the [docs](https://statamic.dev/tags/collection#grouping) to implement a simple category / tag grouping for a collection. It is just not working as expected.

The following snippet gives me an empty string `" "` on both `key` and `group`.

```
{{ collection:videos as="posts" }}
    {{ posts :group_by="video_categories" }}
        {{ groups }}
            <h3>{{ group }}</h3>

            {{ items }}
                {{ title }} <br>
            {{ /items }}
        {{ /groups }}
    {{ /posts }}
{{ /collection:videos }}
```

<img width="368" alt="Screenshot 2022-07-05 at 10 10 12" src="https://user-images.githubusercontent.com/3603346/177281404-4b2c6673-0b86-4b1e-ad2b-baf7d304397f.png">

### How to reproduce

I created a Taxonomy and assigned it to a single collection. Then I used the mentioned code from the docs to get a first glimpse of the output...

This is the `video_categories.yaml` blueprint:

```
sections:
  main:
    display: Hauptteil
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
title: 'Video Kategorien'
```

### Versions

Statamic 3.3.17 Pro
Laravel 8.83.16
PHP 8.0.17
jacksleight/bard-paragraph-style 1.2.3
jonassiewertsen/statamic-livewire 2.9.0
octoper/statamic-blade-components 1.0.1
optimoapps/statamic-bard-text-align 1.0.2

### Installation

Existing Laravel app

### Antlers Parser

regex (default)
