### ISSUE TITLE
"Array to string conversion" error when opening (empty) Collection

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#6326]
### Bug description

When opening a collection overview, I suddenly get the following error:

> Array to string conversion (View: /x/y/vendor/statamic/cms/resources/views/collections/empty.blade.php).

 I had the same error when there were entries in the collection, but only with `show.blade.php` instead of `empty.blade.php`. 

Cleared all caches, dumped autoload... error is still there. 

### How to reproduce

Not really sure. The collection is empty now and there is nothing I can think of. This is the config for the collection:

```
title: News
sites:
  - default
  - en
propagate: false
template: cms/news/show
layout: layout
revisions: false
route: 'news/{slug}'
date: true
sort_dir: asc
date_behavior:
  past: public
  future: private
```

### Logs

```shell
https://flareapp.io/share/V7jLaKJm#F80
```

### Versions

Statamic 3.3.18 Pro
Laravel 9.19.0
PHP 8.1.4
jonassiewertsen/statamic-livewire 2.9.0
octoper/statamic-blade-components 2.0.0

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)
