### ISSUE TITLE
Required_if recently stopped working: Fieldset inside replicator

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#6328]
### Bug description

As the title implies, one of my websites is ignoring a 'required_if' validation on a field within a fieldset, within a replicator.

Fieldset field 'btn_entry' should be required when 'btn_type' is entry.
```
  -
    handle: btn_type
    field:
      options:
        none: None
        asset: Document
        form_popup: 'Form Popup'
        entry: 'Page or Article'
        url: Url
      default: none
      multiple: false
      clearable: false
      searchable: false
      taggable: false
      push_tags: false
      cast_booleans: false
      display: 'Button Type'
      type: select
      icon: select
      listable: hidden
  -
    handle: btn_entry
    field:
      max_items: 1
      mode: default
      display: Entry
      type: entries
      icon: entries
      listable: hidden
      validate:
        - 'required_if:btn_type,entry'
      if:
        btn_type: 'equals entry'
```

As mentioned, this fieldset is used on multiple blocks within a replicator, a sort of page builder.

The validation used to work but now users are able to save empty 'btn_entry' fields, and I have to reinforce my code to prevent this from breaking my logic.

Thanks.

### How to reproduce

Try setting up a fieldset with:
- Select field
- Entry field (required_if select == 'xxx')

Add this fieldset to a replicator.

### Versions

Statamic 3.3.18 Pro
Laravel 9.19.0
PHP 8.1.1

### Installation

Fresh statamic/statamic site via CLI
