### ISSUE TITLE
Conditionals on Toggle-Fieldtype save wrong default value

### ISSUE THREAD

**Issue by wiebkevogel** [statamic/cms#6347]
### Bug description

When saving the Toggle-Fieldtype, `false` is always set, even if the condition does not apply. We would have expected that the value is not saved at all or with its originally specified default value `true`

``` yaml
  -
    handle: hide_image_top
    field:
      type: toggle
      display: 'Hide Image'
      default: true
      filterable: false
      instructions_position: above
      listable: hidden
      visibility: visible
      if:
        type: 'equals highlight'
```

### How to reproduce

Create a Toggle-Fieldtype with `default: true` and a condition that hides the field for example: `id: 'not empty'` and save

### Versions

Statamic 3.3.20
Laravel 9.20.0
PHP 8.1.8

### Installation

Existing Laravel app
