### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#6352]
### Bug description

test

### How to reproduce

test

### Logs

```shell
test
```

### Versions

```yaml


Environment
Application Name: Statamic
Composer Version: 2.3.6
Debug Mode: ENABLED
Environment: local
Laravel Version: 9.21.0
Maintenance Mode: OFF
PHP Version: 8.1.6
URL: statamic3.test

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: mysql
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Version: 3.3.x-dev PRO

Statamic Addons
andymnewhouse/radnight: dev-master
doublethreedigital/blaze: 1.2.5


```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

test
