### ISSUE TITLE
Propagated Entries of a collection are always published if default status is draft

### ISSUE THREAD

**Issue by christophstockinger** [statamic/cms#6357]
### Bug description

I have a Statamic website with multisite setup (German & English). Is now created in a Collection on the english site and is the automatic German page published, although I have defined the default status in the collection as `draft`. 

### How to reproduce

Have a Statamic with Multisite-Setup and create a collection like the following setup: 
```
title: Downloads
sites:
  - en
  - de
propagate: true
template: default
layout: layout
taxonomies:
  0: tags
  2: categories
revisions: false
slugs: false
sort_dir: asc
default_status: draft
date_behavior:
  past: public
  future: private
```

Now create a collection on one site an save the draft. 

Proposed result: both sites are saved as a draft.
Current result: the created entry in the selected site is saved as a draft, the other site is published

### Environment

```yaml
Statamic 3.2.39 Pro
Laravel 8.83.6
PHP 8.0.20
```

### Installation

Fresh statamic/statamic site via CLI
