### ISSUE TITLE
Stack selector search index not affected by search config

### ISSUE THREAD

**Issue by StudioNautilus** [statamic/cms#6376]
### Bug description

When changing the search.php settings for a collection, this only affects the search functionality within the main collection listing (for the cp).

Searching within the stack selector for a relationship field however, keeps searching by the default settings (title field only).

### How to reproduce

- Create collection A
- Create a search index for that collection and add an entry
- Add a searchable for a field that is not 'title'
- Connect the index in the configuration yaml for that collection
- Do a search in that collection on that field in the cp, it finds the entry,

- Create collection B with an entries field to collection A (with stack selector).
- Create an entry in collection B and go to that entries field.
- Do the same search within the stack selector , it does not find the entry.

### Environment

```yaml
Environment
Application Name: Tapp Company Shop
Laravel Version: 9.21.6
PHP Version: 8.1.7
Composer Version: 2.3.7
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: postmark
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Version: 3.3.23 PRO

Statamic Addons
aryehraber/statamic-uuid: 2.1.0
jonassiewertsen/statamic-livewire: 2.9.0
rias/statamic-data-import: 1.2.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
