### ISSUE TITLE
Minify field HTML is too aggressive

### ISSUE THREAD

**Issue by mynetx** [statamic/cms#6390]
### Bug description

We’re using HTML inside a checkbox option value. Spaces after tags are removed. This causes words to stick together.

Rendered:

```html
<label for="accept_privacy[]-62e2482cd8cea" class="text-base text-current leading-tight text-left select-none">Ich akzeptiere die <a href='/datenschutz' class='underline hover:no-underline'>Datenschutzbestimmungen</a>und bin mit der Verarbeitung meiner Daten gemäß DSGVO einverstanden.
```

Note the missing space between “Datenschutzbestimmungen” and “und”.

The problem is caused by the regex in `RendersForms::minifyFieldHtml()`, introduced in #4949 (https://github.com/statamic/cms/commit/9ba5e2df349d26d06787f3ec0dc55a17e26673c7).

### How to reproduce

Prepare a form with a checkbox:

```yaml
      -
        handle: accept_privacy
        field:
          inline: false
          options:
            'yes': 'Ich akzeptiere die <a href=''/datenschutz'' class=''underline hover:no-underline''>Datenschutzbestimmungen</a> und bin mit der Verarbeitung meiner Daten gemäß DSGVO einverstanden.'
          display: Datenschutzbestimmungen
          type: checkboxes
          icon: checkboxes
          listable: hidden
          instructions_position: above
          validate:
            - required
```

Render the form and see the minified result (see above).

### Environment

```yaml
Statamic 3.3.24 Pro
Laravel 8.83.23
PHP 8.0.21
webographen/statamic-dynamic-token 1.0.0
withcandour/aardvark-seo 2.0.28
```

### Installation

Fresh statamic/statamic site via CLI
