### ISSUE TITLE
Hidden fields don't show in the form submission

### ISSUE THREAD

**Issue by aerni** [statamic/cms#6393]
### Bug description

Fields that have `visibility: hidden` don't show up in the form submission view. I'm expecting all fields to show and be `read_only` in the form submission view, regardless of their visibility setting. Currently, fields are only visible when they have either `visibility: visible` or `visibility: read_only`.

### How to reproduce

1. Create a form
2. Add three fields, each with a different visibility setting
3. Create a form submission
4. Recognize that the field with `visibility: hidden` is not showing in the CP

### Environment

```yaml
Environment
Application Name: TDS Aarau
Laravel Version: 9.22.0
PHP Version: 8.1.6
Composer Version: 2.3.5
Environment: local
Debug Mode: ENABLED
URL: tdsaarau.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 8
Antlers: runtime
Version: 3.3.23 PRO

Statamic Addons
aerni/livewire-forms: 6.0.0
aryehraber/statamic-impersonator: 2.4.1
doublethreedigital/duplicator: 2.3.1
jacksleight/statamic-bard-mutator: 1.1.1
jacksleight/statamic-bard-texstyle: 1.0.3
jonassiewertsen/statamic-livewire: 2.9.0
spatie/statamic-responsive-images: 2.13.0
visuellverstehen/statamic-classify: 2.4.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
