### ISSUE TITLE
Incorrect locale url rendered for taxonomy collection routes

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#6418]
### Bug description

When a taxonomy route is used with a specific collection (ie: /events/tag/term) the `{{ locales }}` tag is missing the collection segment from the url (ie. /tag/term).

### How to reproduce

1. Clone test repo at https://github.com/mikemartin/taxonomy-test
2. Visit `/events/tag/feast`
3. Confirm the url of the locale switch is `/tag/feast`

<img width="1189" alt="Screen Shot 2022-08-02 at 4 33 43 pm" src="https://user-images.githubusercontent.com/414211/182307754-49b8657f-17f0-428e-94f3-c2470ea33bb9.png">

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.22.1
PHP Version: 8.0.21
Composer Version: 2.1.9
Environment: local
Debug Mode: ENABLED
URL: taxonomy-test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.25 PRO

Statamic Addons
aerni/advanced-seo: 1.2.0
```

### Installation

Starter Kit using via CLI
