### ISSUE TITLE
Non-translatable date field not updated when origin changes

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#6419]
### Bug description

> **Note**: This is _may_ be related to https://github.com/statamic/cms/issues/6397, although I don't use any specific cache invalidation rules.

When using the date field in a multisite setup and changing the origin date (publish date), the translated field is not updated. A workaround would be to make the translated field editable, but that might cause confusion in the long run.

I made a short video to demonstrate it:
https://www.loom.com/share/a9aa2762a0a242ab948c160ed405d4ad

The same issue appeared when changing any other field that was non-translatable, but clearing the cache "fixed" it. But the issue with the date field is not cache related, it seems.

### How to reproduce

Set up a multisite, in my case DE and EN, with publish dates on entries. Don't make the publish date translatable. Create an entry and translate it. Change the publish date on the origin. The translated record will keep the date it had before.

### Environment

```yaml
Environment
Laravel Version: 9.22.1
PHP Version: 8.1.4
Composer Version: 2.2.0
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Version: 3.3.25 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 2.9.0
octoper/statamic-blade-components: 2.0.0
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)
