### ISSUE TITLE
Runtime antlers engine reports incorrect nav depth when using a partial multiple times

### ISSUE THREAD

**Issue by martyf** [statamic/cms#6439]
### Bug description

For the nav tag, it may need to be used in multiple places for desktop and mobile layouts. For easier code readability, this could be moved to a partial.

With **runtime**, the first time the partial is called, it is correct.

The second time, the depths are incremented by 1.

If the partial's contents are wrapped in a `{{ cache }}` tag, the issue is not present.

Changing to the **regex** engine, the issue disappears.

### How to reproduce

- Create a new install (no starter kit)
- Create a few more pages
- Create a nested nav
- Output the nav in a partial
- Include the partial multiple times

Hey, look over there: https://github.com/martyf/statamic-nav-depth-test

This issue only occurs if the `{{ nav }}` is within a partial: using the nav tag multiple times in the same file does not exhibit the issue.

The demo repo includes:
- nav in partial, with the issue
- nav in a partial with cache, no issue
- nav twice in the main layout, no issue

Change the demo config to **regex** and the issue disappears.

### Environment

```yaml
Application Name: Statamic
Laravel Version: 9.23.0
PHP Version: 8.1.2
Composer Version: 2.2.3
Environment: local
Debug Mode: ENABLED
URL: nav-depth.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Version: 3.3.25 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
