### ISSUE TITLE
toAugmentedArray with nested EntryCollection breaks in v3.3.x

### ISSUE THREAD

**Issue by sheggi** [statamic/cms#6467]
### Bug description

Augmentation of `EntryCollection` behaves different in v3.3.x compared to v3.2.x.

When augmenting the page with `toAugmentedArray` and returning as JSON either an empty object or only a list of entry IDs is returned.

Expected a return value of list of objects (with all augmented data from entry).

If I run `toAugmentedArray()` directly on the `EntryCollection` it works just fine, so the error happens when it's nested within another field or page.

### How to reproduce

Case: 1️⃣  **only list of entry IDs**
- make blueprint with Entries field
- call `json_encode($page->toAugmentedArray())` on a `Statamic\Structures\Page`
- get list of IDs

Case: 2️⃣  **empty Object**
This is a bit more difficult to reproduce because the entries field in other fields
- make blueprint with nested fields
- Page > Bard > BardSet > Replicator > ReplicatorSet > Entries

### Environment

```yaml
Environment
Laravel Version: 9.23.0
PHP Version: 8.1.8
Composer Version: 2.3.10
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Statamic
Addons: 0
Antlers: regex
Version: 3.3.25 PRO

Also tested with Laravel 8 - no difference
```

### Installation

Fresh statamic/statamic site via CLI
