### ISSUE TITLE
StaticCaching\Replacers breaks Inertia Links

### ISSUE THREAD

**Issue by tobiasthaden** [statamic/cms#6475]
### Bug description

This PR [#6231](https://github.com/statamic/cms/pull/6231) breaks our Inertia adapter, we use on multiple websites.

**Statamic\StaticCaching\Replacers\CsrfTokenReplacer::prepareResponseToCache():Argument 1 ($response) must be of type Illuminate\Http\Response, Illuminate\Http\JsonResponse given, called in /var/www/html/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php on line 62**

### How to reproduce

I'll provide an example repo - if necessary.

### Environment

```yaml
Laravel Version: 9.24.0
PHP Version: 8.1.6
Composer Version: 2.3.5
Addons: 0
Version: 3.3.27 PRO
```

### Installation

Existing Laravel app

### Antlers Parser

regex (default)
