### ISSUE TITLE
Recursive navigation part2

### ISSUE THREAD

**Issue by danijelk** [statamic/cms#6485]
### Bug description

This is extension of https://github.com/statamic/cms/issues/6319

Currently the last node doesn't seem to understand it's a child

### How to reproduce

![screenshot 3](https://user-images.githubusercontent.com/580753/184330535-b0107b3e-f566-410b-a24f-b513a20f8213.png)
![screenshot 1](https://user-images.githubusercontent.com/580753/184330543-01f7b789-4c29-492c-a5ad-e7b7ec34d596.png)

Moving things around:

![screenshot 4](https://user-images.githubusercontent.com/580753/184330541-3259febd-eefb-4923-bdb8-40b687b486a4.png)

![screenshot 5](https://user-images.githubusercontent.com/580753/184330544-cc91f57a-22e2-46e3-97fa-6d448ec825f8.png)

Code snippet for @JohnathonKoster 

```
            {{ nav:footer }}
                {{ if depth == 1 }}
                <div class="">
                    <div>
                        <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
                            {{ title }} - {{ depth }} - {{ children_depth }}
                        </h3>
                        {{ if children }}
                        <ul role="list" class="mt-4 space-y-4">
                            {{ *recursive children* }}
                        </ul>
                        {{ /if }}
                    </div>
                </div>
                {{ elseif depth == 2 }}
                <li>
                    <a href="{{ url }}" class="text-base text-gray-300 hover:text-white">{{ title }}</a>
                </li>
                {{ /if }}
            {{ /nav:footer }}


```

### Environment

```yaml
Environment
Application Name: VG
Laravel Version: 9.24.0
PHP Version: 8.1.9
Composer Version: 2.3.10
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Version: 3.3.28 PRO

Statamic Addons
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
