### ISSUE TITLE
Slow page loading and asset metadata

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#6495]
### Bug description

I've tried just about everything to improve the slow page loading on this site (disabling the watcher, selecting nav fields, etc) and I seem to have narrowed the problem down to the high number of assets. The assets folder on this project has exactly 14464 asset files and as a result, some of my pages take as long as 8 seconds to load. When I turn off `catch_meta` the page takes 40 seconds to load.

Typically this isn't a problem with static caching but I've recently introduced Livewire on this project and every Livewire query is taking 2 to 3 seconds. 

I understand that I should reduce the number of assets but this still seems like a major performance issue. Would it make any difference if I moved the assets to external storage like DO spaces or S3?

### How to reproduce

You can see it in action here as a demonstration of the slow page loading:
https://staging.burlingameproperties.com/properties

### Environment

```yaml
aerni/livewire-forms: 4.0.0
jonassiewertsen/statamic-livewire: 2.9.0
mikemartin/helpscout-beacon: 1.0.2
spatie/statamic-responsive-images: 2.13.0
swiftmade/statamic-clear-assets: 1.1.0
webographen/statamic-widget-continue-editing: 1.0.1
withcandour/aardvark-seo: 2.0.28
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
