### ISSUE TITLE
File uploads can't be opened in form submissions

### ISSUE THREAD

**Issue by stvnthomas** [statamic/cms#6501]
### Bug description

All fields are set to readonly in form submissions. This includes the files for the assets fieldtype so you can't click and open them from the submission.

https://user-images.githubusercontent.com/2236267/184684602-1bfcbe60-2651-41f9-9027-852c5f385d8a.mp4

### How to reproduce

Create a form with an assets field.
Render the form on the frontend and submit a file.
Review the submission in Statamic. Click the uploaded file. Nothing happens.

### Environment

```yaml
Environment
Application Name: Bear Valley Electric Service, Inc
Laravel Version: 9.24.0
PHP Version: 8.0.14
Composer Version: -
Environment: local
Debug Mode: OFF
URL: bvesinc.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Version: 3.3.28 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
