### ISSUE TITLE
FluentTag camelCased parameters do not work

### ISSUE THREAD

**Issue by ajnsn** [statamic/cms#6503]
### Bug description

```
When using multi-word parameters, like query_scope, you must use the camelCased version (queryScope).
```
https://statamic.dev/blade

This does not seem to work. At least I encounter a lot of issues when using `Statamic::tag` and the recommended camelCase version of the parameter, e.g.

```php
Statamic::tag('collection:news')->show_past(false)->fetch(); // works
Statamic::tag('collection:news')->showPast(false)->fetch(); // does not work

Statamic::tag('nav:breadcrumbs')->include_home(false)->fetch(); // works
Statamic::tag('nav:breadcrumbs')->includeHome(false)->fetch(); // does not work
```

### How to reproduce

Try snake_case vs camelCased fluently.

### Environment

```yaml
Environment
Application Name: statamic
Laravel Version: 9.24.0
PHP Version: 8.1.9
Composer Version: 2.3.10
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: daily
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 0
Antlers: runtime
Version: 3.3.28 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

If I am not totally interpreting this wrong, this could be solved by changing the `FluentTag`'s `__call` method to this:

```diff
public function __call($param, $args)
{
-    $this->param($param, $args[0] ?? true);
+    $this->param(Str::snake($param), $args[0] ?? true);

    return $this;
}
```

After the change e.g. `->show_past(false)` and `->showPast(false)` work for me.
