### ISSUE TITLE
GraphQL hide menu item with permissions

### ISSUE THREAD

**Issue by andreasbergqvist** [statamic/cms#6529]
### Bug description

When GraphQL is enabled, it will show for all users. There should be a permission to set if it is showed or not. Being able to only show relevant menu items (most content editors we work with have no idea what GraphQL is) is a real winner for Statamic vs other more "bloated" CMS (none mentioned).

### How to reproduce

Enable GraphQL, create a user with minumum permissions (only "Access the Control Panel").
Still, when that user logs in, the "Tools" / "GraphQL" menu item still shows.

### Environment

```yaml
**Environment**
Application Name: -
Laravel Version: 9.25.1
PHP Version: 8.1.5
Composer Version: 2.4.0
Environment: production
Debug Mode: OFF
URL: -
Maintenance Mode: OFF

**Cache**
Config: CACHED
Events: CACHED
Routes: CACHED
Views: CACHED

**Drivers**
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: mailgun
Queue: sync
Session: file

**Statamic**
Addons: 3
Antlers: regex
Version: 3.3.30 PRO

**Statamic Addons**
goldnead/statamic-toc: 1.2.0
jacksleight/statamic-bard-mutator: 1.1.2
jacksleight/statamic-bard-texstyle: 1.0.3
```

### Installation

Fresh statamic/statamic site via CLI
