### ISSUE TITLE
Select field - Listable: Shown by default - Not showing value

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#6533]
### Bug description

I have just set a select field to 'Shown by default' but the column values are blank on the listing.

I have cleared all caches. I am not using labels for my options.

### How to reproduce

Set up a select field and set 'Listable' to 'Shown By Default'
Note that values are not shown in listing

### Environment

```yaml
Version: 3.3.30 PRO
Laravel Version: 9.25.1
PHP Version: 8.1.1
```

### Installation

Existing Laravel app
