### ISSUE TITLE
Live Preview doesn't work when site domains are different

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#6536]
### Bug description

Trying to Live Preview site 2 content from site 1 CP, shows a blank screen with this error: 
![](https://user-images.githubusercontent.com/6069653/185681846-972127df-fccb-4f29-87cf-d8405cb3bb5e.png)

Not sure if this is an actual bug. To fix, we'd have to update the DataResponse to add a header when `live-preview` is in the query string:

```
Content-Security-Policy "frame-src https://site1.com https://site2.com;"
```

### How to reproduce

Steps:

- two (multi)sites, with different domains
- default Forge/Ploi nginx configuration
- accessing CP on site1.com
- try to Live Preview content ONLY on site2.com

### Environment

```yaml
Environment
Application Name: Alaska PAC
Laravel Version: 9.25.1
PHP Version: 8.1.9
Composer Version: 2.4.0
Environment: local
Debug Mode: ENABLED
URL: alaskapac.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / daily, front
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 17
Antlers: runtime
Version: 3.3.29 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.8.0
aryehraber/statamic-uuid: 2.1.0
doublethreedigital/duplicator: 2.3.1
edalzell/forma: 1.2
jacksleight/statamic-bard-mutator: 1.1.1
jacksleight/statamic-bard-texstyle: 1.0.3
jonassiewertsen/statamic-external-link: 1.6.0
jonassiewertsen/statamic-livewire: 2.9.0
statamic/seo-pro: 3.1.0
swiftmade/statamic-clear-assets: 1.1.0
transformstudios/events: 4.0.6
transformstudios/front: 1.10
transformstudios/gated: dev-main
transformstudios/magic-link: dev-main
transformstudios/review: 3.3.2
transformstudios/simple: dev-main
transformstudios/takeover-redirects: dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
