### ISSUE TITLE
1st published version of an entry is unpublished when revisions is on and the stache is cleared

### ISSUE THREAD

**Issue by sunscreem** [statamic/cms#6557]
### Bug description

This took a bit of working out. 

We noticed that after deploying a site a recently published entry was becoming un-published.

I'm not sure if it's relevant but all recommended laravel caching methods are on (config, events, etc)

### How to reproduce

1. Install Statamic
2. Enable revisions
3. Create a collection
4. Enable revisions in that collection.
5. Create an entry in the collection, save entry and publish entry.
5. Clear the Stache.

Entry will now be unpublished.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.25.1
PHP Version: 8.0.10
Composer Version: 2.4.1
Environment: production
Debug Mode: OFF
Maintenance Mode: OFF

Cache
Config: CACHED
Events: CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Version: 3.3.31 PRO

Statamic Addons
statamic/collaboration: 0.4.0
```

### Installation

Fresh statamic/statamic site via CLI
