### ISSUE TITLE
HTML entities in Bard don't work

### ISSUE THREAD

**Issue by aerni** [statamic/cms#6572]
### Bug description

When using HTML Entities like `&shy;` in a Bard field, the entity is actually visible on the frontend without taking effect.

**Control Panel**

<img width="895" alt="Bildschirmfoto 2022-08-25 um 11 29 16" src="https://user-images.githubusercontent.com/23167701/186707102-c5d317c7-da9b-44b5-8f28-0550d2102128.png">

**Frontend**

<img width="774" alt="Bildschirmfoto 2022-08-25 um 11 29 27" src="https://user-images.githubusercontent.com/23167701/186707143-9df6c487-f3d6-4a27-922d-8c8773b5f21b.png">

### How to reproduce

1. Create a bard field
2. Use `&shy;` in a long German word like `Rindfleisch&shy;etikettierungsüberwachungsaufgabenübertragungsgesetz`
3. See it render on the frontend

### Environment

```yaml
Environment
Application Name: TDS Aarau
Laravel Version: 9.26.1
PHP Version: 8.1.6
Composer Version: 2.3.5
Environment: local
Debug Mode: ENABLED
URL: tdsaarau.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 9
Antlers: runtime
Version: 3.3.32 PRO

Statamic Addons
aerni/advanced-seo: 1.3.2
aerni/livewire-forms: 6.2.0
aryehraber/statamic-impersonator: 2.4.1
doublethreedigital/duplicator: 2.3.2
jacksleight/statamic-bard-mutator: 1.1.2
jacksleight/statamic-bard-texstyle: 1.0.3
jonassiewertsen/statamic-livewire: 2.9.0
spatie/statamic-responsive-images: 2.13.0
visuellverstehen/statamic-classify: 2.4.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
