### ISSUE TITLE
ENV variable in form email throws error

### ISSUE THREAD

**Issue by ewhicher** [statamic/cms#6573]
### Bug description

I always put email addresses for my forms in my `.env` file as they are different for each environment and it feels slightly more secure. I just went to do it and got this error when submitting the form:

```
Symfony \ Component \ Mime \ Exception \ RfcComplianceException
Email "{env:MAIL_TO_ADDRESS}" does not comply with addr-spec of RFC 2822.
```
![Screenshot 2022-08-25 at 16 39 42](https://user-images.githubusercontent.com/8192603/186709690-8d7f78de-cc3a-4db5-9169-1d276e36f6b7.png)

I've got multiple sites using this same method and it works just fine, might this be related to a new version of one of the packages?

### How to reproduce

Add this to your form.yaml
```
title: Contact
honeypot: sticky
email:
  -
    to: '{env:MAIL_TO_ADDRESS}'
    subject: 'A new message from the website'
store: false
```

and add to your `.env` file:
```
MAIL_TO_ADDRESS="example@email.com"
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.26.1
PHP Version: 8.1.4
Composer Version: 2.2.9
Environment: local
Debug Mode: ENABLED
URL: macmill.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Version: 3.3.32 Solo

Statamic Addons
visuellverstehen/statamic-classify: 2.4.0
```

### Installation

Fresh statamic/statamic site via CLI
