### ISSUE TITLE
str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in processReplacement function

### ISSUE THREAD

**Issue by sebabal** [statamic/cms#6579]
### Bug description

I am getting lots of warnings on PHP 8.1.9 like this one using the **runtime** parser

`str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /vendor/statamic/cms/src/View/Antlers/Language/Runtime/LiteralReplacementManager.php on line 111`

I am using the Peak starter kit (latest version 5.5), brand new installation.

Seems to be related to when trying to use the yield/section combo.

I checked the function and indeed $defaultContent is indeed null.

I quickly fixed the issue by simple using the null coalescing operator and default to an empty string.

Eg: 

`content = str_replace($regionName, $defaultContent ?? '', $content);`

### How to reproduce

Install default Peak starter kit, check debugbar log.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.26.1
PHP Version: 8.1.9
Composer Version: 2.1.6
Environment: local
Debug Mode: ENABLED
URL: starter-kit.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Version: 3.3.32 PRO
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
