### ISSUE TITLE
Control Panel not loading and throwing JavaScript errors

### ISSUE THREAD

**Issue by K3CK** [statamic/cms#6583]
### Bug description

After upgrading to Statamic 3.3.32 the control panel does not load anymore. Logging in works, but the page stays empty. 

Debug console shows JavaScript errors (in vue.common.prod.js):

```
vue.common.prod.js:6 ReferenceError: stacks is not defined
    at kn.eval (eval at qa (vue.common.prod.js:6:91553), <anonymous>:7:32465)
    at e._render (vue.common.prod.js:6:35309)
    at kn.r (vue.common.prod.js:6:67998)
    at fn.get (vue.common.prod.js:6:26596)
    at new fn (vue.common.prod.js:6:26514)
    at vue.common.prod.js:6:68012
    at kn.$mount (vue.common.prod.js:6:67874)
    at kn.$mount (vue.common.prod.js:6:93370)
    at e._init (vue.common.prod.js:6:32866)
    at new kn (vue.common.prod.js:6:30196)
```

and

```
ReferenceError: stacks is not defined
    at kn.eval (eval at qa (vue.common.prod.js:6:91553), <anonymous>:7:32465)
    at e._render (vue.common.prod.js:6:35309)
    at kn.r (vue.common.prod.js:6:67998)
    at fn.get (vue.common.prod.js:6:26596)
    at fn.run (vue.common.prod.js:6:27480)
    at cn (vue.common.prod.js:6:25588)
    at Array.<anonymous> (vue.common.prod.js:6:12294)
    at Ge (vue.common.prod.js:6:11693)
```

Note: After the update I also did run "npm install" and "npm run production".

### How to reproduce

Run `composer update` or start the update in the Control Panel.

### Environment

```yaml
Environment
Application Name: Codetopia
Laravel Version: 9.26.1
PHP Version: 8.1.9
Composer Version: 2.4.1
Environment: production
Debug Mode: OFF
URL: codetopia.de
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.32 PRO

Statamic Addons
spatie/statamic-responsive-images: 2.13.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
