### ISSUE TITLE
Editing entry from Nav discards unsaved changes

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#6589]
### Bug description

Making a navigation, and I accidentally hit the 'Edit Entry' menu item from the 3 dots menu. When I clicked the `< Page` link I went back to the pages (of course), but all my unsaved nav changes were lost.

Would be great if it either auto-saved when you went to the edit entry page, or didn't allow you to continue until you have no  unsaved changes (likely the easiest fix)/

### How to reproduce

1. Make a nav
2. save
3. add a few more nav items, at least one of them an entry
4. click on the `Edit Entry` from the pop up menu
5. click the `< Pages` link in the nav
6. navigate back to Nav
7. see none of the previous added items

### Environment

```yaml
Environment
Application Name: Groundlings
Laravel Version: 9.26.1
PHP Version: 8.1.9
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: groundlings-new.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Version: 3.3.32 PRO

Statamic Addons
aerni/font-awesome: 1.2.0
statamic/migrator: dev-master
```
```


### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

_No response_
