### ISSUE TITLE
Entry Facade perform unstably on jobs running in Horizon

### ISSUE THREAD

**Issue by jbrhel** [statamic/cms#6592]
### Bug description

I have a job (delayed) that is managed through Horizon. This job is dispatched with an Entry instance. This job failing randomly with "Call to a member function value() on null". There is `fresh()` method called on given entry instance, which is implementation of Entry Facade find method.  And this is failing point. It almost everytime return null instead of "fresh" entry instance.

**Running this job via "php artisan:queue:listen" works just fine.** 

`App\Jobs\CheckPaymentStatus`

```
<?php

namespace App\Jobs;

use Statamic\Entries\Entry;
use Illuminate\Bus\Queueable;
use Illuminate\Support\Facades\Log;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class CheckPaymentStatus implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $entry;

    public function __construct(Entry $entry)
    {
        $this->entry = $entry;
    }

    public function handle()
    {
       if (!$this->entry->fresh()->value('paid')) {
           $this->entry->set('paid', true);
           $this->entry->save();
        }
    }
}

```

`App\Http\Controllers\Api\v1\OrderController`

```
<?php

namespace App\Http\Controllers\Api\v1;

use Statamic\Facades\Entry;
use Illuminate\Http\Request;
use App\Jobs\CheckPaymentStatus;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
    
    public function store(Request $request) {
        $entry = Entry::make()
            ->collection('orders')
            ->data($request->all())
            ->date(now());

        $entry->save();

        CheckPaymentStatus::dispatch($entry)->delay(now()->addSeconds(30));
    }
}

```

### How to reproduce

- run horizon with delayed job. 
- It happens randomly (but almost every second and next job is FAILS)
- I haven't any clue, what is going on. Maybee it's somehow related to:  #2993

### Environment

```yaml
Environment
Laravel Version: 9.27.0
PHP Version: 8.1.1
Composer Version: 2.2.6
Environment: production

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.32 PRO

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / rollbar, single
Mail: smtp
Queue: redis
Session: file
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
