### ISSUE TITLE
Trans tag in mail templates don't use site language

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#6602]
### Bug description

This used to work. But the trans tag in mail templates (from a form submission) use English and not the current locale.

### How to reproduce

1. Make a site with a non english locale
2. Add a form
3. Use a translatable string in the form
4. Translate that string in your strings file
5. Submit the form

DM me for a repo with example

### Environment

```yaml
Environment
Application Name: Zoschke
Laravel Version: 9.26.1
PHP Version: 8.1.7
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: zoschke.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Version: 3.3.32 PRO

Statamic Addons
edalzell/forma: 1.2
jonassiewertsen/statamic-livewire: 2.9.0
silentz/mailchimp: 2.9.1
zoschke/csv-product-import: dev-develop
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
