### ISSUE TITLE
Saving globals is taking a very long time or wont save at all

### ISSUE THREAD

**Issue by Oleafeon** [statamic/cms#6611]
### Bug description

When i edit the globals i cant save cause it takes a really long time and when i refresh the page the settings are not saved i saw that i got an error in console
![unknown](https://user-images.githubusercontent.com/20043831/187844532-7e41082d-bcdc-4330-95f0-bb318aaa4c67.png)

### How to reproduce

1. Create a settings file in the globals
2. Try to save the globals
3. Get error

### Environment

```yaml
Environment
Application Name: Playground
Laravel Version: 9.27.0
PHP Version: 8.1.6
Composer Version: 2.3.5
Environment: local
Debug Mode: ENABLED
URL: playground.test/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 10
Antlers: regex
Version: 3.3.32 PRO

Statamic Addons
4rn0/statamic-v3-image-optimizer: 1.0.15
aerni/font-awesome: 1.2.0
appart/bard-classes: 1.5
aryehraber/statamic-captcha: 1.8.0
doublethreedigital/duplicator: 2.3.2
jacksleight/statamic-bard-mutator: 1.1.2
pecotamic/sitemap: 1.4.0
rias/statamic-link-it: 2.2.3
rias/statamic-redirect: 2.4.0
statamic/seo-pro: 3.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by Oleafeon** [comment]
Continuation from github:
![image](https://user-images.githubusercontent.com/20043831/187845457-f12da2ed-2403-4bde-a668-40020a9f54ff.png)
yes i have an bard field in my globals

**Comment by jesseleite** [comment]
@Oleafeon Having trouble reproducing with a bard field in my globals blueprint. Can you share your blueprint maybe? Also curious which fields need to be filled to trigger the error? Thanks!

**Comment by Oleafeon** [comment]
```
sections:
  logos:
    display: "Logo's"
    fields:
      -
        handle: logo
        field: image.image
        config:
          restrict: true
          display: Logo
          folder: logo
          max_files: 1
  social_media:
    display: 'Social media'
    fields:
      -
        handle: social_media_title
        field:
          input_type: text
          antlers: false
          display: 'Social media titel'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: social_media
        field:
          fields:
            -
              handle: icon
              field:
                styles:
                  - brands
                display: Icoon
                type: font_awesome
                icon: select
                listable: hidden
                instructions_position: above
                read_only: false
                validate:
                  - required
            -
              handle: name
              field:
                input_type: text
                antlers: false
                display: Naam
                type: text
                icon: text
                instructions: 'De naam van het social media platform'
                listable: hidden
                instructions_position: above
                read_only: false
            -
              handle: url
              field:
                input_type: text
                antlers: false
                display: URL
                type: text
                icon: text
                instructions: 'De URL van de social media pagina'
                listable: hidden
                instructions_position: above
                read_only: false
                validate:
                  - required
                  - url
          mode: stacked
          add_row: 'Add new social media item'
          reorderable: true
          display: 'Social media'
          type: grid
          icon: grid
          listable: hidden
          instructions_position: above
          read_only: false
  various:
    display: Diverse
    fields:
      -
        handle: navigation_title
        field:
          input_type: text
          antlers: false
          display: 'Navigatie titel'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: contact_title
        field:
          input_type: text
          antlers: false
          display: 'Contact titel'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: contact_details
        field: text.text
        config:
          buttons:
            - h2
            - h3
            - bold
            - italic
            - underline
            - anchor
            - unorderedlist
            - orderedlist
            - removeformat
            - horizontalrule
          display: 'Contact details'
      -
        handle: copyright_footer_links
        field:
          fields:
            -
              import: button
          mode: stacked
          max_rows: 5
          add_row: 'Nieuwe link toevoegen'
          reorderable: true
          display: 'Copyright footer links'
          type: grid
          icon: grid
          listable: hidden
          instructions_position: above
          read_only: false
  404_page:
    display: '404 pagina'
    fields:
      -
        handle: 404_text
        field: text.text
        config:
          buttons:
            - h1
            - h2
            - h3
            - bold
            - italic
            - underline
            - anchor
            - unorderedlist
            - orderedlist
            - removeformat
            - horizontalrule
      -
        import: button
  contact_pop_up:
    display: 'Contact pop-up'
    fields:
      -
        handle: pop_up_success_message
        field:
          input_type: text
          antlers: false
          display: 'Succes melding'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: pop_up_failed_message
        field:
          input_type: text
          antlers: false
          display: 'Mislukt melding'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: pop_up_button_text
        field:
          input_type: text
          antlers: false
          display: 'Knop tekst'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          read_only: false
```

maybe the jump ins are a bit weird thats because of github

**Comment by Oleafeon** [comment]
here are the fieldsets that we import
text
```
title: Tekst
fields:
  -
    handle: text
    field:
      always_show_set_button: false
      buttons:
        - h2
        - h3
        - bold
        - italic
        - underline
        - anchor
        - unorderedlist
        - orderedlist
        - removeformat
        - horizontalrule
        - bardclassesclass
      container: docs
      save_html: false
      toolbar_mode: fixed
      link_noopener: true
      link_noreferrer: true
      target_blank: true
      reading_time: false
      fullscreen: false
      allow_source: false
      enable_input_rules: false
      enable_paste_rules: false
      antlers: false
      display: Tekst
      type: bard
      icon: bard
      listable: hidden
      instructions_position: above
      read_only: false
```

button
```
title: Knop
fields:
  -
    handle: button
    field:
      types:
        - asset
        - entry
        - custom
        - email
        - url
        - tel
      newWindow: true
      text: true
      aria: false
      append: false
      collections:
        - pages
      containers:
        - images
        - docs
        - videos
      display: Knop
      type: link_it
      icon: external-link
      listable: hidden
      instructions_position: above
      read_only: false
  -
    handle: button_id
    field:
      input_type: text
      antlers: false
      display: 'knop ID'
      type: text
      icon: text
      listable: hidden
      instructions_position: above
      read_only: false
```
image
```
title: Afbeelding
fields:
  -
    handle: image
    field:
      mode: list
      container: images
      restrict: false
      allow_uploads: false
      show_filename: true
      display: Afbeelding
      type: assets
      icon: assets
      listable: hidden
      instructions_position: above
      read_only: false
```

**Comment by Oleafeon** [comment]
this is what we have filled using the yaml file in the content map that way it works but when we want to save in the cp even without editing the page i get the error
```
title: Instellingen
data:
    logo: favicon/mstile-144x144.png
    navigation_title: Sitemap
    contact_title: Contact
    social_media_title: 'Social media'
    copyright_footer_links:
      -
        button:
          type: url
          url: 'https://example.com/'
          newWindow: true
          text: 'Privacy policy'
        button_id: test-button-id-hoi-1
      -
        button:
          type: url
          url: 'https://example.com/'
          newWindow: true
          text: 'Algemene voorwaarden'
        button_id: test-button-id-hoi-2
      -
        button:
          type: url
          url: 'https://example.com/'
          newWindow: true
          text: 'Cookiebeleid'
        button_id: test-button-id-hoi-3
```
