### ISSUE TITLE
Reorder images in asset fieldtype

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#6649]
### Bug description

Reorder images in the asset fieldtype shows you a big white frame, when dragging the image around. The green scribble stands for the cursor. Tried in Safari and Chrome. 

<img width="1142" alt="Bildschirmfoto 2022-09-07 um 08 45 32" src="https://user-images.githubusercontent.com/8265902/188809100-33900ca2-1b08-4684-b6a1-4a489ff6b4dd.png">

### How to reproduce

Select two images in an asset fieldtype and try to reorder them

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.28.0
PHP Version: 8.1.5
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: test-img.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.34 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
