### ISSUE TITLE
Blade @nocache shows NOCACHE_PLACEHOLDER

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#6682]
### Bug description

Just experimenting with the @nocache directive for a new project.

I have a header that contains auth-based items (e.g. settings / profile) so I am using the nocache directive like so:
`@nocache('partials.nav-main')`

But all I am seeing is:
`NOCACHE_PLACEHOLDER`

The layout is a blade component but I have also tried it with a layout that uses template inheritance. Same results either way.

### How to reproduce

Try the @nocache directive in blade.

### Environment

```yaml
Version: 3.3.34 PRO
Laravel Version: 9.28.0
PHP Version: 8.1.1
```

### Installation

Fresh statamic/statamic site via CLI
