### ISSUE TITLE
Visual spacing issue with new plus button above replicators

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#6686]
### Bug description

If you have instructions for your replicator the newly added plus button in #6586 causes some visual overlap.
<img width="698" alt="189337315-d5a7fb44-d561-47b1-86e7-44fa639c1801" src="https://user-images.githubusercontent.com/69107412/189381306-dea77dab-46cc-4ce5-9edf-c26a66ae3ffe.png">

### How to reproduce

Add instructions to a replicator fieldtype.

### Environment

```yaml
Application Name: Is het al veilig
Laravel Version: 9.28.0
PHP Version: 8.1.7
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: ishetalveilig.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Version: 3.3.34 PRO
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
