### ISSUE TITLE
Asset fieldtype in list mode limited to one asset still shows add button

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#6687]
### Bug description

The asset fieldtype in list mode limited to one asset still shows add button since #6639.
<img width="831" alt="Screenshot_2022-09-09_at_12 58 45" src="https://user-images.githubusercontent.com/69107412/189382317-92e6690b-48c8-49b7-8c5e-a0d6fd0fe7ae.png">

### How to reproduce

Add an asset field in list mode with a 1 asset limit. 

### Environment

```yaml
Application Name: Is het al veilig
Laravel Version: 9.28.0
PHP Version: 8.1.7
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: ishetalveilig.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Version: 3.3.34 PRO
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
