### ISSUE TITLE
CMS User Role permissions do not allow for renaming of Asset Folder

### ISSUE THREAD

**Issue by ChrisWorkhouse** [statamic/cms#6696]
### Bug description

When a Role is granted all of the Asset permissions; an individual asset can be edited, renamed or deleted. But asset folders still only allow for deletion - and not rename.

For example, below are my permissions configured in the CMS:

![image](https://user-images.githubusercontent.com/23635988/189635292-43ece382-b9be-4dfe-8ae9-5501c980d2e7.png)

But an asset folder still only allows Delete:

![image](https://user-images.githubusercontent.com/23635988/189635435-6a1b4260-7847-4d1b-9dc4-87832b0f7b0f.png)

### How to reproduce

Create a new role in the Statamic CMS.

Ensure Super User is unticked. Set all permissions to True / Enabled.

Log in as a user with this role applied and attempt to rename an Asset Folder

### Environment

```yaml
Environment
Application Name: Site
Laravel Version: 9.27.0
PHP Version: 8.0.23
Composer Version: 2.1.12
Environment: local
Debug Mode: ENABLED
URL: 
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: regex
Version: 3.3.35 PRO

Statamic Addons
rias/statamic-address-field: 1.0.2
statamic/seo-pro: 3.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
