### ISSUE TITLE
CP links with hash - tab is not set active

### ISSUE THREAD

**Issue by mmodler** [statamic/cms#6706]
### Bug description

When you open or reload a cp link with a hash, the corresponding tab is no longer set active. Console logs a js error:

```
ReferenceError: visibleTabs is not defined
    setActiveTabFromHash Sections.vue:213
    mounted Sections.vue:173
    VueJS 14
    start Statamic.js:87
    <anonymous> settings:430
```

### How to reproduce

In CP, navigate to a collection entry or global with tabs, select a tab and reload your browser.

### Environment

```yaml
Laravel Version: 9.29.0
PHP Version: 8.0.19
Antlers: runtime
Version: 3.3.35 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
