### ISSUE TITLE
Multisite entry fields not synced with origin without clearing the stache

### ISSUE THREAD

**Issue by Kylewalow** [statamic/cms#6714]
### Bug description

Entry fields are not synced with origin page until the stache gets cleared.
After clearing the stache one times it works as it should for all further changes.

### How to reproduce

1. Create a new Statamic project including a superuser. (STATAMIC_STACHE_WATCHER=false)
2. Configure multisite with eg. three different languages.
3. Create a new collection.
4. Create a entry for the new collection.
5. Create the new entry in another language by clicking on the corresponding site in the sidebar on the right and save & publish. The Field `content` is displayed as synced.
![image](https://user-images.githubusercontent.com/48148789/189934023-6e8e0d30-aaa1-45ae-b633-174f2656daca.png)

6. Return to the origin page and edit the value of the `content` field. Save & Publish.
![image](https://user-images.githubusercontent.com/48148789/189934178-93a74741-b2a1-4592-9e5a-b5814b91af4b.png)

8. The page from the other language does not update its value.
![image](https://user-images.githubusercontent.com/48148789/189934304-3d3ab010-2c2c-48c9-a182-a70ce544d481.png)

10. run a `php please stache:clear`.
11. The value is updated.
![image](https://user-images.githubusercontent.com/48148789/189935200-3e032dcc-91a1-41df-9af5-144375c3258a.png)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.29.0
PHP Version: 8.1.8
Composer Version: 2.2.7
Environment: production
Debug Mode: OFF
URL: statamic_test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.35 PRO
```

### Installation

Fresh statamic/statamic site via CLI
