### ISSUE TITLE
CP: Update badge on updated site

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#6718]
### Bug description

I keep getting an update badge in the CP while the project is up2date (afaik). 

### How to reproduce

It happens on this repo: https://github.com/studio1902/1902

1. Clone
2. `composer install`
3. `npm i && npm run build`
5. `php please make:user`
6. login

### Environment

```yaml
Environment
Application Name: Studio 1902
Laravel Version: 9.30.0
PHP Version: 8.1.10
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: 1902.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Version: 3.3.36 PRO

Statamic Addons
jonassiewertsen/statamic-jobs: 1.1.0
jonassiewertsen/statamic-livewire: 2.9.0
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
