### ISSUE TITLE
Folders not visible inside asset containers via Digital Ocean Spaces

### ISSUE THREAD

**Issue by taylorcammack** [statamic/cms#6755]
### Bug description

I'm transferring assets from local to Digital Ocean Spaces. If it helps, I used [s3cmd](https://docs.digitalocean.com/products/spaces/reference/s3cmd-usage/) to upload them in bulk, not sure if it's different than uploading them directly. The site itself runs completely fine, but when I go to view the assets, the folders are not visible.

**Spaces interface showing folders**
![Screen Shot 2022-09-20 at 3 01 08 PM](https://user-images.githubusercontent.com/2514935/191353988-90333a14-1d93-41d7-bc8c-152804cba34e.png)

**Local cp interface just showing assets**
![Screen Shot 2022-09-20 at 3 01 12 PM](https://user-images.githubusercontent.com/2514935/191354055-f119c190-40f6-4dbc-ace4-b7335aeed30c.png)

If I go to an assets field on an entry where the field is restricted to a single folder, I can view assets within that folder. So everything else seems to work, it just doesn't show the folders in the UI.

BTW, for the main asset container, I have the root set to a subfolder at `/main`. However, it doesn't seem to matter what the root is set to, none of the folders are visible.

```
    'do_spaces_assets' => [
      'driver' => 's3',
      'key' => env('DO_SPACES_KEY'),
      'secret' => env('DO_SPACES_SECRET'),
      'endpoint' => env('DO_SPACES_ENDPOINT'),
      'region' => env('DO_SPACES_REGION'),
      'bucket' => env('DO_SPACES_BUCKET'),
      'root' => 'main',
      'url' => env('DO_SPACES_URL'),
      'visibility' => 'public',
    ],
```

### How to reproduce

- Create Digital Ocean space and upload files
- Hook up asset container
- View Assets in CP

### Environment

```yaml
Environment
Laravel Version: 9.31.0
PHP Version: 8.1.10
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: regex
Version: 3.3.37 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.8.0
simonhamp/statamic-heroicons: 1.0.1
spatie/statamic-responsive-images: 2.13.1
```

### Installation

Other (please explain)

### Antlers Parser

regex (default)

### Additional details

Custom starter kit
