### ISSUE TITLE
Collapse/Duplicate/Delete toggle in Bard Sets not working in v3.3.39

### ISSUE THREAD

**Issue by manogi** [statamic/cms#6778]
### Bug description

The Collapse/Duplicate/Delete toggles on any Bard set stopped doing anything after upgrading to v.3.3.39.
![CleanShot 2022-09-24 at 16 36 55](https://user-images.githubusercontent.com/1419634/192103902-42fa2304-9ecc-4415-bffc-6daa88ab8908.gif)

### How to reproduce

Install a complete fresh version of Statamic (v3.3.39), make a Bard fieldset with some sets and use it in a blueprint, try to collapse/delete/duplicate a set in the Bard field.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.31.0
PHP Version: 8.1.9
Composer Version: 2.3.10
Environment: local
Debug Mode: ENABLED
URL: test-collapse.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.39 Solo
```

### Installation

Fresh statamic/statamic site via CLI
