### ISSUE TITLE
title modifer does not handle abbreviations properly

### ISSUE THREAD

**Issue by architchandra** [statamic/cms#6782]
### Bug description

Running something like {{ 'How to use PR Firms at Startups'|title }} results in 'How to Use Pr Firms at Startups'.

### How to reproduce

Output a string that contains an abbreviation with the title modifier added after it.

### Environment

```yaml
Environment
Application Name: <redacted>
Laravel Version: 9.26.1
PHP Version: 8.1.9
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: <redacted>
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.32 Solo

Statamic Addons
mitydigital/sitemapamic: 2.3.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
