### ISSUE TITLE
Asset picker inside Link fieldtype shows browse button

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#6786]
### Bug description

A bit like https://github.com/statamic/cms/issues/6687, the asset picker inside the Link fieldtype doesn't really look right with the browse button included:

![Screenshot 2022-09-26 at 12 46 45](https://user-images.githubusercontent.com/126740/192268820-c5b41633-879b-4daf-aa58-e82e7d0565ab.png)

### How to reproduce

Create link field and select the asset option

### Environment

```yaml
Statamic
Addons: 13
Antlers: runtime
Version: 3.3.39 PRO
```

### Installation

Fresh statamic/statamic site via CLI
