### ISSUE TITLE
Cannot read properties of undefined (reading 'type') in AssetsFieldtype.vue

### ISSUE THREAD

**Issue by htulibacki** [statamic/cms#6798]
### Bug description

I think that #6788 introduced a bug in AssetsFieldtype.vue resulting in TypeError.

### How to reproduce

I have Asset field direct in my collection. When I upgraded to 3.3.40 I noticed, that the asset preview is not showing.

### Logs

```shell
vue.common.prod.js:6 TypeError: Cannot read properties of undefined (reading 'type')
    at a.isInLinkField (AssetsFieldtype.vue:327:1)
    at fn.get (vue.common.prod.js:6:26596)
    at fn.evaluate (vue.common.prod.js:6:27746)
    at a.isInLinkField (vue.common.prod.js:6:29650)
    at a.showPicker (AssetsFieldtype.vue:346:1)
    at fn.get (vue.common.prod.js:6:26596)
    at fn.evaluate (vue.common.prod.js:6:27746)
    at a.showPicker (vue.common.prod.js:6:29650)
    at fn (AssetsFieldtype.vue?d862:3:446)
    at Object.r [as default] (vue.common.prod.js:6:15520)
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.32.0
PHP Version: 8.1.5
Composer Version: 2.2.9
Environment: local
Debug Mode: ENABLED
URL: remivision.com.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Version: 3.3.40 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
