### ISSUE TITLE
Creating Fieldset with the same handle as existing results in error

### ISSUE THREAD

**Issue by stuartpearman** [statamic/cms#6826]
### Bug description

If you attempt to create a fieldset with a handle that already exists, it results in the error:

```
Method Statamic\Http\Controllers\CP\Fields\FieldsetController::show does not exist.
```

Seems like it sees that the fieldset already exists, and attempts to redirect it to the `show` method for the resource class, which is not defined for Fieldsets.

In my case, I'm redirected to `http://localhost:8000/cp/fields/fieldsets/undefined`, which suggests the fieldset handle also isn't being passed through.

### How to reproduce

In the Control Panel, create a new fieldset via `/cp/fields/fieldsets/create` route. Give it a handle of one that already exists.

### Logs

```shell
cloudwatch: ERROR: Method Statamic\Http\Controllers\CP\Fields\FieldsetController::show does not exist. 
{
    "userId": 1,
    "exception": "[object] (BadMethodCallException(code: 0): Method Statamic\\Http\\Controllers\\CP\\Fields\\FieldsetController::show does not exist. at (project-root)/api/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:68)"
}
```

### Environment

```yaml
Environment
Application Name: 
Laravel Version: 9.24.0
PHP Version: 8.1.10
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: cloudwatch
Mail: ses
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.27 PRO
```

### Installation

Fresh statamic/statamic site via CLI
