### ISSUE TITLE
Image Metadata

### ISSUE THREAD

**Issue by crackAT** [statamic/cms#6837]
### Bug description

since version 3.3.40 Image meta datas were stored in database but when editing the image in an entry, meta data fields are empty
![image](https://user-images.githubusercontent.com/6299060/194295561-4c2b4241-f5c8-4724-8719-dcf3174fe576.png)
![image](https://user-images.githubusercontent.com/6299060/194295600-f28f027a-e4cf-436c-9032-c7cfd239092e.png)

### How to reproduce

update to version 3.3.40 or higher
add image to entry, 
edit metadatas
reload page
edit metadatas again

### Environment

```yaml
Laravel Version: 9.34.0
PHP Version: 8.0.23
Version: 3.3.39 PRO
statamic/eloquent-driver: 1.0.1
```

### Installation

Fresh statamic/statamic site via CLI
