### ISSUE TITLE
Asset browser performance regression on >3.3.41

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#6846]
### Bug description

After the Glide focal PR got merged in, we're seeing timeouts in the asset browser when using S3 and a bucket with 1000s of assets.

### How to reproduce

1. install 3.3.41
2. have an s3 buckets with >3k assets
3. try to view that asset container in asset browser

<img width="1361" alt="CleanShot 2022-10-07 at 13 23 10@2x" src="https://user-images.githubusercontent.com/6069653/194651786-e6ce7380-3eff-4b7a-a24d-508dff8bfd32.png">

### Environment

```yaml
Application Name: Statamic
Laravel Version: 9.34.0
PHP Version: 8.1.11
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
URL: zakat.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 20
Antlers: runtime
Version: 3.3.41 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.0
aryehraber/statamic-impersonator: 2.4.1
aryehraber/statamic-uuid: 2.1.0
doublethreedigital/duplicator: 2.3.2
doublethreedigital/runway: 2.5.3
edalzell/forma: 1.2
jacksleight/statamic-bard-mutator: 1.1.2
jacksleight/statamic-bard-texstyle: 1.0.3
jonassiewertsen/statamic-livewire: 2.9.0
statamic/seo-pro: 3.1.0
swiftmade/statamic-clear-assets: 1.1.0
transformstudios/events: 4.0.6
transformstudios/front: 1.11.0
transformstudios/gated: dev-main
transformstudios/github: dev-main
transformstudios/magic-link: dev-main
transformstudios/memorial: dev-fix/statamic-simple-update
transformstudios/review: 3.6.0
transformstudios/simple: 2.9.1
transformstudios/takeover-redirects: dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
