### ISSUE TITLE
Rename label "Display HTML" to "Save as HTML" in Blueprints > Bard fieldtype

### ISSUE THREAD

**Issue by schwemmer** [statamic/cms#6847]
### Bug description

The current label "Display HTML" is confusing. Enabling the option causes the field's content to be SAVED as HTML. Therefore, the label should say "Save as HTML".

<img width="1233" alt="Bildschirmfoto 2022-10-08 um 10 56 09" src="https://user-images.githubusercontent.com/725398/194699313-e7b5d036-5d01-4bef-b4a1-7ea178cd0035.png">

### How to reproduce

Edit the Blueprint for a Collection. Create a new field of type "Bard". You will see the label "Display HTML".

### Environment

```yaml
Environment
Laravel Version: 9.32.0
PHP Version: 8.1.10
Composer Version: -
Environment: local
Debug Mode: ENABLED
URL: localhost:8001
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: regex
Version: 3.3.43 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 1.1.2
jacksleight/statamic-bard-texstyle: 1.0.3
textandbytes/footnotes: dev-main
```

### Installation

Existing Laravel app

### Antlers Parser

regex (default)
