### ISSUE TITLE
Contact form created invalid UTF-8 data in YAML which broke control panel

### ISSUE THREAD

**Issue by brendanfalkowski** [statamic/cms#6860]
### Bug description

A client reported they couldn't login to their control panel. Just getting 500 error on `/cp/dashboard`.

I updated my local repo + updated Statamic + re-deployed. Same thing.

Found this in logs:

```
[2022-10-11 01:05:34] production.ERROR: The YAML value does not appear to be valid UTF-8. {"userId":"ffae2ce4-c4a1-43a3-a58e-ee417c84fdbe","exception":"[object] (Statamic\\Yaml\\ParseException(code: 0): The YAML value does not appear to be valid UTF-8. at /home/forge/savoirfaireacappela.com.com/storage/statamic/tmp/yaml/9e81f4fe098a5ade56f8d6752592bd93:-1)
```

Checked all the recent changes, and didn't see anything wrong in content. Happened to manually try `/cp/login` and it rendered a 404. Realized only `/cp/dashboard` was failing, and it's because I included the "contact form" widget.

There were 680 junky form submissions, and one of them introduced invalid UTF-8 content somehow. Deleted them all on the server, and that resolved it.

I have a backup if you want to figure out what the invalid entry was. No idea how long ago this started happening. I didn't see anything visibly wrong in the last 20 submissions, and I stopped there.

### How to reproduce

In theory, submit non-UTF-8 content in a form.
Include the form submissions widget on the CP dashboard.

Note: I also couldn't access the "forms" CP area while this data existed on the server.

### Environment

```yaml
Environment
Application Name: Savoir Faire A Cappella
Laravel Version: 9.23.0
PHP Version: 8.1.8
Composer Version: 2.4.2
Environment: production
Debug Mode: OFF
URL: savoirfaireacappella.com
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: postmark
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.43 Solo
```

### Installation

Fresh statamic/statamic site via CLI
