### ISSUE TITLE
In Bard, strikethrough renders the deprecated <strike> element

### ISSUE THREAD

**Issue by architchandra** [statamic/cms#6864]
### Bug description

Using the _Strikethrough_ button in a Bard field renders the `<strike>` element in the markup, which has been [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strike). It should instead use the `<s>` element.

### How to reproduce

Add some text in a Bard field and then strike some text off. Save the entry and view the corresponding front-end interface's HTML source. A `<strike>` element would be seen around the text that was struck off.

### Environment

```yaml
Environment
Application Name: <redacted>
Laravel Version: 9.33.0
PHP Version: 8.0.22
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: <redacted>
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Version: 3.3.42 Solo

Statamic Addons
mitydigital/sitemapamic: 2.3.1
statamic/ssg: 1.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
