### ISSUE TITLE
Collection not rendering when running on Vapor

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/cms#6868]
### Bug description

I've configured Statamic to use the Eloquent driver deployed on Vapor.

Works well so far but my articles collection view craps out on me (can publish entries just fine).

Error is

```
{
"userId": 1,
"exception": {
"class": "TypeError",
"message": "explode(): Argument #2 ($string) must be of type string, array given",
"code": 0,
"file": "/var/task/vendor/statamic/cms/src/Http/Resources/CP/Concerns/HasRequestedColumns.php:39"
}
}
```

### How to reproduce

https://github.com/1stevengrant/serverless-statamic

Create a Vapor database, deploy to Vapor

Create a Statamic user in the db. Configure a collection like `Articles`. Create a test entry, see that the collection view errors out.

### Environment

```yaml
Application Name: Statamic
Laravel Version: 9.35.0
PHP Version: 8.1.8
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.43 Solo

Statamic Addons
statamic/eloquent-driver: 1.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
