### ISSUE TITLE
Content fields from globals unexpected returned as arrays

### ISSUE THREAD

**Issue by Jeroen-G** [statamic/cms#6876]
### Bug description

I used a content replicator and some fieldsets inside a globals to define some 'site-wide' content. However, in the output when I fetch the data from the globals these are arrays instead of the Statamic fields and values classes.
Since my sections and bard components expect those classes but get an array instead the site crashes.

### How to reproduce

Configure a globals blueprint that contains a Bard field for example, and render (I am using Blade) that globals variable in a template.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.33.0
PHP Version: 8.1.9
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
URL: statamic.local
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: pgsql
Logs: stack / single, stderr
Mail: smtp
Queue: sync
Scout: database
Session: file

Statamic
Addons: 4
Antlers: regex
Version: 3.3.25 PRO

Statamic Addons
mitydigital/sitemapamic: 2.3.1
rias/statamic-button-box: 2.0.3
rias/statamic-redirect: 2.4.0
```

### Installation

Fresh statamic/statamic site via CLI
