### ISSUE TITLE
Asset field not outputting custom title field

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#6882]
### Bug description

I've got an asset field called `downloads` which I want to loop. The asset has a blueprint with one field called `title`. I've tried the following to get the `{{ title }}` to render, but it returns the URL in every case.

At first I tried this cuz that made most sense to me:

```antlers
{{ downloads }}
    <li>
        <a href="{{ url }}" download>{{ title }}</a>
    </li>
{{ /downloads }}
```

Then I figured let's add the `asset` tag:

```antlers
{{ downloads }}
    <li>
        {{ asset :url="url"}}
            <a href="{{ url }}" download>{{ title }}</a>
        {{ /asset }}
    </li>
{{ /downloads }}
```

Unfortunately that doesn't work either. But then I thought of the query builder stuff that [recently bit me](https://github.com/statamic/cms/discussions/6793) so I tried this:

```antlers
{{ downloads as="items" }}
    {{ items }}
        <li>
            <a href="{{ url }}" download>{{ title }}</a>
        </li>
    {{ /items }}
{{ /downloads }}
```

Nope, not working. Well why not combine ALL THOSE TRICKS?

```antlers
{{ downloads as="items" }}
    {{ items }}
        <li>
            {{ asset :url="url"}}
                <a href="{{ url }}" download>{{ title }}</a>
            {{ /asset }}
        </li>
    {{ /items }}
{{ /downloads }}
```

Still returning the URL. So now I think this might be a bug and here we are.

### How to reproduce

- Give an asset blueprint one `text` field called `title`
- Add a field called `downloads` to a collection blueprint.
- Add some downloads to an entry.
- Loop `{{ downloads }}` in the `show` template.

### Environment

```yaml
Environment
Application Name: TWA Architecten
Laravel Version: 9.35.1
PHP Version: 8.1.10
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: twa-architecten.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.44 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 2.9.0
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
