### ISSUE TITLE
User Field select list default order should be alphabetical

### ISSUE THREAD

**Issue by binoclard** [statamic/cms#6883]
### Bug description

By default, it seems that a User Field, in select list mode, displays the users by "last created/modified".

I am sure there are good valid reasons for that, but for me is it a bit counter-intuitive, especially when the users list gets long.

I think the default should be alphabetical.

### How to reproduce

Have a long list of users
Create a User Field with `mode: select`
Take note of the seemingly random order.
Change a thing in a user file, save. Now this user is at the top of the list.

### Environment

```yaml
Environment
Laravel Version: 9.33.0
PHP Version: 8.1.4
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Version: 3.3.43 PRO

Statamic Addons
aryehraber/statamic-impersonator: 2.4.1
raynl/generate-slug: 1.1.1
rias/statamic-data-import: 1.2.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
