### ISSUE TITLE
Asset field limited to one image should have different styling

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#6892]
### Bug description

After the recent changes to the asset field in the CP I ran into an issue where you have the `mode` set to `grid` and `max_files` to `1`.

The field looks like it can hold more than one images. I think the single image should be displayed a lot bigger as it did in earlier versions so it communicates to the user that the field is 'filled'.
<img width="822" alt="Screenshot 2022-10-16 at 16 09 55" src="https://user-images.githubusercontent.com/69107412/196040086-a313c212-ffde-4759-973f-dd7c4230ef96.png">

The new design causes issues on smaller sizes:
<img width="830" alt="Screenshot 2022-10-16 at 16 06 38" src="https://user-images.githubusercontent.com/69107412/196040106-cd9b784c-db58-43a9-a605-096c5af0f3e5.png">

For reference. This is how it used to look:
<img width="820" alt="Screenshot 2022-10-16 at 16 15 36" src="https://user-images.githubusercontent.com/69107412/196040415-a5fbf1d4-9dfc-4ea1-bd7e-2f524656ea0c.png">
<img width="831" alt="Screenshot 2022-10-16 at 16 15 20" src="https://user-images.githubusercontent.com/69107412/196040421-5eaa34a0-a0b8-4ec4-b151-5efbdcce8cbb.png">

### How to reproduce

1. Make an asset field with `max_files` set to `1` and `mode` to `grid`. 
2. Put it in a blueprint.
3. Play with the widths.

### Environment

```yaml
Environment
Application Name: TWA Architecten
Laravel Version: 9.35.1
PHP Version: 8.1.10
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: twa-architecten.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.45 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 2.9.0
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
