### ISSUE TITLE
Conditionally hidden required fields always throw a validation error after reordering inside a replicator field

### ISSUE THREAD

**Issue by moritzlang** [statamic/cms#6897]
### Bug description

Conditionally hidden required fields (using the [Validating Nested Fields](https://statamic.dev/validation#validating-nestable-fields) syntax with `sometimes` and `required` but also when using the Laravel validation syntax e.g. `required_if`) always throw a validation error after reordering using the **collapsed** state in a `replicator_field`.

[Video showcasing the issue](https://imgur.com/a/suE4Zyp)

### How to reproduce

1. Create a replicator field with a set that uses the [Validating Nested Fields](https://statamic.dev/validation#validating-nestable-fields) syntax with `sometimes` and `required`

e.g.

```yaml
-
  handle: replicator_field
  field:
    collapse: false
    previews: true
    sets:
      validation_set:
        display: 'Validation Set'
        fields:
          -
            handle: foo
            field:
              mode: default
              create: true
              collections:
                - pages
              display: Foo
              type: entries
              icon: entries
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: bar
            field:
              input_type: text
              antlers: false
              display: Bar
              type: text
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              validate:
                - required
                - sometimes
              always_save: false
              if:
                foo: 'equals empty'
              instructions: 'Should be only required when visible'
```

2. Go to the entry that uses this replicator field and add at least two sets to that field
3. Save the entry and Reload the page
4. Click "Collapse All" on the "Replicator Field"
5. Reorder the "Validation Set"
6. Save the page
7. A validation error for the field `bar` is thrown

## Demo Repository

I also created a repo thats showcases the issue: https://github.com/moritzlang/statamic-nested-fields-validation

### Setup for the demo

1. `composer install` in the root of the project
2. `cp .env.example .env && php artisan key:generate`
3. Make a new user `php please make:user`
4. `cd public`
5. `valet link statamic-nested-fields-validation`
6. Open `http://statamic-nested-fields-validation.test`

### Reproduction steps

1. Open the "Home" page `http://statamic-nested-fields-validation.test/cp/collections/pages/entries/home`
2. Click "Collapse All" on the "Replicator Field"
3. Reorder the "Validation Set"
4. Save the page
5. A validation error for the field `bar` is thrown

Error Response:

```json
{
    "message": "The given data was invalid.",
    "errors": {
        "replicator_field.0.bar": ["This field is required."]
    }
}
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.35.1
PHP Version: 8.0.23
Composer Version: 2.0.8
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.45 Solo
```

### Installation

Starter Kit using via CLI
