### ISSUE TITLE
Taxonomy term field filters don't work in the CP

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#6898]
### Bug description

When trying to filter taxonomy terms in the CP nothing is filtered and no filter badge is displayed (the page does shift slightly so it is doing something).

https://user-images.githubusercontent.com/126740/196199756-bfea7ce6-e4bf-4e84-ac51-e49262418bc4.mp4

### How to reproduce

Go to a term listing and try to apply a field filter.

### Environment

```yaml
Statamic
Addons: 1
Antlers: runtime
Version: 3.3.45 PRO
```

### Installation

Starter Kit using via CLI
