### ISSUE TITLE
Can't add multiple conditions to field

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#6901]
### Bug description

Trying to set up a conditional field on a simple entry:

Show when: All of the conditions pass
field - not - test-value
field - not - text-value-2

When I save this entry the second condition disappears and does not get saved.

### How to reproduce

Set up a conditional field as described.

### Environment

```yaml
Version: 3.3.45 PRO
Laravel Version: 9.35.1
PHP Version: 8.1.1
```

### Installation

Fresh statamic/statamic site via CLI
