### ISSUE TITLE
Cannot upload files without encoding as multipart form data when submitting a form with files upload

### ISSUE THREAD

**Issue by maxi032** [statamic/cms#6914]
### Bug description

I created a form in Blade using
<code>
{!!  Form::open(['class'=>'form-inputs',
                'id'=>'site-form',
                'autocomplete'=>'off',
                'files'=>true,
                'url' => $contactForm['attrs']['action'],
                'method' => $contactForm['attrs']['method']]) !!}
</code>

This will add a form tag like:

```<form method="POST" action="https://site.test/!/forms/contact_form_homepage" accept-charset="UTF-8" class="form-inputs" id="site-form" autocomplete="off" enctype="multipart/form-data">```

However, when I attach a file and submit the form I get the message:

```Cannot upload files without encoding as multipart form data when submitting a form with files upload``` 

### How to reproduce

Try to create a form with  'files'=>true,

### Environment

```yaml
I am using 

Environment
Application Name: Laravel
Laravel Version: 9.35.1
PHP Version: 8.1.11
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Version: 3.3.45 PRO
```
```


### Installation

Existing Laravel app

### Antlers Parser

_No response_

### Additional details

_No response_
