### ISSUE TITLE
Blade @nocache recursive dependency error when a global set is in view context

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#6924]
### Bug description

If you use the `@nocache` directive while you have a global set in the view context (`$__data` array) it errors with:

```
Nesting level too deep - recursive dependency?
vendor/statamic/cms/src/StaticCaching/NoCache/Region.php: 55
```

This happens with all static caching strategies including null. This happens even if the global set is empty.

### How to reproduce

Create a blade template that uses `@nocache` while you have a global set in the view context:

```blade
@php
$__data['settings'] = Statamic\Facades\GlobalSet::find('settings')->inCurrentSite();
@endphp
@nocache('test')
```

Obviously you wouldn't normally set `$__data` directly, but this situation can easily occur if you've used a global set further up the view hierachy or added with `View::share()`.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.36.3
PHP Version: 8.1.10
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: sandbox-issue.test
Maintenance Mode: OFF

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.47 PRO
```

### Installation

Fresh statamic/statamic site via CLI
