### ISSUE TITLE
Assets in submitted form are not accesible

### ISSUE THREAD

**Issue by maxi032** [statamic/cms#6926]
### Bug description

I've made a Form with a few text fields and an asset file input.
The files are getting uploaded in storage but when I click the pdf icon from the Form overview, nothing happens. I would expect that the link points to the file from storage. 

### How to reproduce

Add a file in a form blueprint.
Set the validation to required, mime:pdf 
Make a new assets container and set the files to be uploaded there

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 9.35.1
PHP Version: 8.1.11
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
URL: bertels.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Version: 3.3.45 PRO

Statamic Addons
withcandour/aardvark-seo: 2.0.29
```

### Installation

Existing Laravel app
