### ISSUE TITLE
Drag and drop fields in Fieldset editor with a Bard field can glitch out and prevent saving

### ISSUE THREAD

**Issue by martyf** [statamic/cms#6960]
### Bug description

When creating or editing a fieldset, adding a new Bard field has a tendency to create a glitch when dragging and dropping fields.

It seems that adding a Bard field causes the issue: if non-Bard fields are added, it tends to work more reliably.

On Save:
```Statamic\Fields\FieldTransformer::fromVue(): Argument #1 ($submitted) must be of type array, null given, called in [path]/vendor/statamic/cms/src/HttpControllers/CP/Fields/FieldsetController.php on line 69```

### How to reproduce

1. Create a new Fieldset
2. Add a Bard field
3. Add a Text field
4. Drag and drop them around to see the issue
5. Save shows a funky error

### Workaround
1. Add your fields, including Bard, etc
2. Save the Fieldset
3. Reload screen, then drag and drop

### Environment

```yaml
Environment
Application Name: Site Name
Laravel Version: 9.36.4
PHP Version: 8.1.11
Composer Version: 2.2.3
Environment: local
Debug Mode: ENABLED
URL: nhi.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Version: 3.3.48 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.0
mitydigital/feedamic: 2.2.2
mitydigital/iconamic: 1.1.0
mitydigital/sitemapamic: 2.3.3
mitydigital/statamic-google-fonts: 1.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

Videos are fun, so here's one:

https://user-images.githubusercontent.com/1491079/198039094-70d38ddd-5401-4446-b203-090867006f43.mov
