### ISSUE TITLE
wrong date translation when iso_format modifier is used in title format and a user locale is set

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#6966]
### Bug description

In a collection setting I use this string in the title format field:

<img width="867" alt="Bildschirmfoto 2022-10-28 um 10 55 47" src="https://user-images.githubusercontent.com/8265902/198549726-f56f23b6-8fca-4e7f-b923-a525c8888c19.png">

In the collection overview the title is shown in english or german. It depends on what I've set in the users.yaml preference.

<img width="580" alt="en" src="https://user-images.githubusercontent.com/8265902/198551055-dcfd1bb4-aa5d-4d2a-8563-9315d91760b6.png">
<img width="493" alt="de" src="https://user-images.githubusercontent.com/8265902/198551063-8451f858-5138-489b-abc2-64a2e761305f.png">

The [docs](https://statamic.dev/modifiers/iso_format) says that «the language that will be used for translations depends on what you configured in your config/statamic/sites.php file. The locale and fallback_locale settings from the config/app.php file have no influence on this modifier.»

It looks like the user settings override the setting in `config/statamic/sites.php`. Here I have only one locale:
<img width="369" alt="Bildschirmfoto 2022-10-28 um 11 17 17" src="https://user-images.githubusercontent.com/8265902/198551959-44ae00f2-9bed-4201-b390-7110b69129e2.png">

The title field is used in the front end views. Therefore I think it's a bug, when the users preferences is used instead?

### How to reproduce

- Define a title format in the collection settings with an iso_format modifier
- Create a new entry
- Check the translation showed in the title column in the collection list
- Change the locale in the users preferences
- Save the entry again
- The translation should now have changed in the title column in the collection list

### Environment

```yaml
Application Name: Essort
Laravel Version: 9.35.1
PHP Version: 8.1.11
Composer Version: 2.4.3
Environment: local
Debug Mode: ENABLED
URL: /
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Version: 3.3.49 PRO

Statamic Addons
rias/statamic-redirect: 2.4.0
statamic/seo-pro: 3.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
