### ISSUE TITLE
Antlers Runtime: Regression `recursive children` unpredictable

### ISSUE THREAD

**Issue by o1y** [statamic/cms#6967]
### Bug description

I'm printing a navigation multiple times on my site using the new Antlers runtime. When using `{{ *recursive children* }}` in combination with a condition around the `{{ nav }}`, it returns the children from a wrong {{ nav }} scope. Maybe this is a regression of #2712, a bug with the new runtime or I'm doing something completly wrong.

### How to reproduce

In the following example the second navigation will print the recursive children from the _first_ navigation.

_Workarounds_:
- remove the block `{{ if true }} ... {{ /if }}` 
- Add another inline condition inside, see comment below
- Change Antlers parser back to `regex`

```antlers {.lineNo}
 {{ nav handle="main_navigation" }}
  {{ if depth == 1 }}
    <div class="{{ if is_current || is_parent }}active{{ /if }}">
     <a href="{{ url }}">First: {{ title }}</a>
        {{ if children }}
      <ul>
        {{ *recursive children* }}
      </ul>
      {{ /if }}
    </div>
  {{ /if }}

  {{ if depth == 2 }}
    <li><a class="{{ if is_current }}active{{ /if }}" href="{{ url }}">First: {{ title }}</a></li>
  {{ /if }}
{{ /nav }}

{{ if true }} // this is just an example condition. removing it results in a correct recursive children return
  {{ nav handle="main_navigation" }}
    {{ if depth == 1 }}
      <div> // adding another inline if condition here results in returning the correct recursive children
        <a href="{{ url }}">Second: {{ title }}</a>
          {{ if children }}
        <ul>
          {{ *recursive children* }}
        </ul>
        {{ /if }}
      </div>
    {{ /if }}

    {{ if depth == 2 }}
      <li><a class="{{ if is_current }}active{{ /if }}" href="{{ url }}">Second: {{ title }}</a></li>
    {{ /if }}
  {{ /nav }}
{{ /if }}
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.30.1
PHP Version: 8.1.11
Composer Version: 2.4.3
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.49 PRO

Statamic Addons
statamic/ssg: 1.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
