### ISSUE TITLE
`group_by="date|F"` combined with `{{ group iso_format="MMMM" }}`: outputs "December" twice

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#6972]
### Bug description

I'm trying to output an event list grouped by the month name. Without the `iso_format="MMMM"`on the `group` it's working correctly; adding the above modifier, it ends in two "December" outputs.

Maybe this bug only exists today, 31-10?

### How to reproduce

1. Create a dated collection.
2. Add entries in October, November and December.
3. Output them like here:
```
{{ collection:events sort="date:asc" since="yesterday" as="entries" }}
	{{ entries group_by="date|F" }}
		
		{{ groups }}
			<div>
				<h1>{{ group iso_format="MMMM" }}</h1>
				<div class="u-grid u-grid--small">
				{{ items scope="event" }}
					{{ title|wrap:h2 }}
				{{ /items }}
				</div>
			</div>
		{{ /groups }}
		
	{{ /entries }}
{{ /collection:events }}
```

### Environment

```yaml
Environment
Laravel Version: 9.37.0
PHP Version: 8.0.16

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.49 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Switching between the two parsers does not make any difference.
