### ISSUE TITLE
Umlaute in slugs do not convert as usual when using automatic titles

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#6985]
### Bug description

If I generate the title of a collection entry automatically with a configuration set in the collection settings…

<img width="933" alt="Configure Collection" src="https://user-images.githubusercontent.com/8265902/199458904-410de33b-e05a-4d96-9d87-2f688bb5641c.png">

…and use this title afterwards for my slug slug in the blueprint
<img width="1495" alt="Edit Blueprint" src="https://user-images.githubusercontent.com/8265902/199458909-06b00821-04f3-45ca-ad2f-c24f235d7c33.png">

…the slug converts german Umlaute not as usual. a ö ü becomes a o u instead of ae ou ue.

But if I dispense with automatic titles and use a single title field in my blueprint, the characters ä ö ü in the slug converts to ae oe ue, which is intentional and good.

**You can see the difference in the two screenshots:**

<img width="1260" alt="with automatic title" src="https://user-images.githubusercontent.com/8265902/199464932-51a5e06b-9285-4e31-b33e-b60a8e0dce9b.png">

<img width="1264" alt="single title field" src="https://user-images.githubusercontent.com/8265902/199464939-f1a2160e-6c69-41fd-b8ca-baf2302637f2.png">

(In my usecase I would hide the slug field in the blueprint, but I would like to use the readable slug in the entry filename instead of the ID.)

### How to reproduce

- Create a collection and a blueprint with some text fields (like pre- and surname)
- Use the pre- and surname fields in your title format in the collection settings
- Add a new entry with Umlaute Ä Ö Ü
- Compare the spelling of the generated slug with the slug of an entry from an other collection, where you enter the same name, but directly in the title field of the entry.

### Environment

```yaml
Application Name: Statamic
Laravel Version: 9.38.0
PHP Version: 8.1.11
Composer Version: 2.4.3
Environment: local
Debug Mode: ENABLED
URL: test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.50 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
