### ISSUE TITLE
Debug error "Cannot loop over non-loopable variable" when using slot in partial

### ISSUE THREAD

**Issue by Sm1lEE** [statamic/cms#6986]
### Bug description

When using the slot-feature of partials, the following debug-message is written to the logs: 

`local.DEBUG: Cannot loop over non-loopable variable: {{ slot:modal_contents }}`

Depending on the number of usages of this feature, the log file fills up really quickly.

The error comes from this line: https://github.com/statamic/cms/blob/dcf00549e0a2d418b605431c6816dbfb99e31548/src/View/Antlers/Language/Runtime/NodeProcessor.php#L723
I don't know the internals of the antlers runtime engine, but probably an additional check for a slot tag could work.

Please let me know if you need any further information.

### How to reproduce

Use [this demo github repo](https://github.com/Sm1lEE/statamic-slot-looping-error) or follow the steps below.

#### 1. Install new, blank statamic page via cli

`statamic new my-site`

#### 2. Use antlers runtime version:
```php
// config/statamic/antlers.php
'version' => 'runtime',
```

#### 3. Create a partial using the slot feature, e. g.:

```html
<!-- partials/_modal.antlers.html -->
<div id="modal">
    {{ slot:modal_contents }}
</div>
```

#### 4. Use the partial and provide contents to the slot

```html
<!-- home.antlers.html -->
{{ partial:modal }}
    {{ slot:modal_contents }}
        <h1>I am the modal content.</h1>
    {{ /slot:modal_contents }}
{{ /partial:modal }}
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.38.0
PHP Version: 8.1.9
Composer Version: 2.2.18
Environment: local
Debug Mode: ENABLED
URL: statamic-looping-error.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Version: 3.3.50 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
