### ISSUE TITLE
Full static cache randomly misses cache hit

### ISSUE THREAD

**Issue by ahinkle** [statamic/cms#6990]
### Bug description

Hey folks 👋  

I'm having an issue with the full-page cache. I've read through the documentation, asked on Discord, and researched online, and the issue persists. 

Most of the time the caching works, and randomly at different points throughout the day, it will stop working for random expected cached pages. I will see in my error log:

```
Static cache loaded [https://(domain).com/] If you are seeing this, your server rewrite rules have not been set up correctly.
```

This site has high traffic, and it happens sometimes but not all the time and at random intervals (nothing during deployment).

### How to reproduce

1. Enable Full Page Cache (env: `STATAMIC_STATIC_CACHING_STRATEGY="full"`)
2. Set config for static page cache:

Static Cache Strategies: 
```php
        'full' => [
            'driver' => 'file',
            'path' => public_path('static'),
            'lock_hold_length' => 0,
            'warm_concurrency' => 10,
        ],
```

Static Cache Excludes:
```php
    'exclude' => [
        '/sitemap.xml',
    ],
``` 

Statatic Cache Ignore Query Strings:
```php
 'ignore_query_strings' => true,
```

3. Update NGINX Config:
```yml
    location / {
        try_files /static${uri}_${args}.html $uri /index.php?$args;
    }
```

4. Update Forge Deployment Script:
```bash
if [[ $FORGE_DEPLOY_MESSAGE =~ "[Autosave]" ]]; then
    echo "Automatically committed on production. Nothing to deploy."
    exit 0
fi

( flock -w 10 9 || exit 1
    echo 'Restarting FPM...'; sudo -S service $FORGE_PHP_FPM reload ) 9>/tmp/fpmlock

cd /home/forge/(domain).com
git pull origin $FORGE_SITE_BRANCH
$FORGE_COMPOSER install --no-interaction --prefer-dist --optimize-autoloader

npm ci
npm run build
$FORGE_PHP artisan cache:clear
$FORGE_PHP artisan config:cache
$FORGE_PHP artisan route:cache
$FORGE_PHP artisan ratings:refresh
$FORGE_PHP artisan queue:restart
$FORGE_PHP artisan statamic:search:update --all
$FORGE_PHP artisan statamic:static:clear
$FORGE_PHP artisan statamic:assets:generate-presets --queue
$FORGE_PHP artisan statamic:static:warm
```

### Logs

```shell
Static cache loaded [https://(domain).com/premium-features] If you are seeing this, your server rewrite rules have not been set up correctly.

Static cache loaded [https://(domain).com/] If you are seeing this, your server rewrite rules have not been set up correctly.

Static cache loaded [https://(domain).com/blog] If you are seeing this, your server rewrite rules have not been set up correctly.
```

### Environment

```yaml
Environment
Application Name: (redacted)
Laravel Version: 9.38.0
PHP Version: 8.1.8
Composer Version: 2.4.4
Environment: production
Debug Mode: OFF
URL: (redacted).com
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: production / single, slack
Mail: ses
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Version: 3.3.50 PRO

Statamic Addons
optimoapps/statamic-bard-text-align: 1.0.2
```

Someone recommended turning off OpCache; this is disabled, and the issue still persists. 

### Installation

Fresh statamic/statamic site via CLI
