### ISSUE TITLE
Since 3.3.50, replicator loses fields on save

### ISSUE THREAD

**Issue by martyf** [statamic/cms#6993]
### Bug description

This issue presents itself when editing an entry that uses a replicator, and the "save" button is set to "Continue Editing".

Adding a row to the replicator, and then clicking Save, causes the replicator to lose its config and the rows that you just added, and a JS error is thrown to the console:

```
TypeError: can't access property "text_field", t.meta is undefined
    h Set.vue:1
    vt VueJS
    h Set.vue:1
    VueJS 27
    runAfterSaveHook PublishForm.vue:540
    promise callback*runAfterSaveHook PublishForm.vue:473
    performSaveRequest PublishForm.vue:519
    promise callback*performSaveRequest PublishForm.vue:509
    promise callback*runBeforeSaveHook PublishForm.vue:493
    save PublishForm.vue:476
    setTimeout handler*save PublishForm.vue:473
    click PublishForm.vue:1
    VueJS 27
vue.common.prod.js:6:11579
```

Refreshing the page adds fields back, but they may not be correctly aligned with what the Save button had set them as. i.e. if you have complicated sets that have different configuration, it can save the wrong parts with the wrong set.

Demonstration of issue:

https://user-images.githubusercontent.com/1491079/199600114-1c90bcf0-feb9-473c-83be-f80cf88d7ab1.mov

Example repo at https://github.com/martyf/statamic-replicator-issue

This issue was introduced with 3.3.50. Rolling back to 3.3.49 does not exhibit the issue.

### How to reproduce

1. Clone this repo:
https://github.com/martyf/statamic-replicator-issue
2. Run `php please make:user`
3. Log in, and go to make a new Page
4. Check "Save" is set to "Save and Continue"
5. Using the Replicator Field that is set up, add a field
6. Click Save

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.38.0
PHP Version: 8.1.11
Composer Version: 2.2.3
Environment: local
Debug Mode: ENABLED
URL: replicatortest.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.51 Solo
```

### Installation

Fresh statamic/statamic site via CLI
