### ISSUE TITLE
Contact form does not display content in CP 

### ISSUE THREAD

**Issue by terryosayawe** [statamic/cms#6994]
### Bug description

The contact form is submitted and the data is saved to the MySQL database but an attempt to view the submission leads to a blank page with an error about missing date, upon checking the database table the `created_at` field is not populated, manually adding a value fixes the issues until there is a new entry with `created_at NULL`. 
<img width="1756" alt="Screenshot 2022-11-02 at 23 06 58" src="https://user-images.githubusercontent.com/115593420/199612539-a8454aac-d24d-48ed-91ba-a246a32149ea.png">

### How to reproduce

Create and contact form, submit it and try to view the submission. I am using eloquent driver so a database is needed 

### Environment

```yaml
Environment
Application Name: 10Guru Solutions
Laravel Version: 9.36.4
PHP Version: 8.0.14
Composer Version: 2.1.10
Environment: local
Debug Mode: ENABLED
URL: oss-website.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: regex
Version: 3.3.51 PRO

Statamic Addons
statamic/eloquent-driver: 1.0.1
statamic/seo-pro: 3.1.0
```

### Installation

Fresh statamic/statamic site via CLI
