### ISSUE TITLE
Entries from all sites shown in Entries fieldtype

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#6998]
### Bug description

If you have a multi-site and use an Entries fieldtype, the drop has entries from all sites, which can make it very difficult to choose the correct one, if the titles are the same across sites.

<img width="243" alt="CleanShot 2022-11-03 at 09 37 09@2x" src="https://user-images.githubusercontent.com/6069653/199780441-4063567b-d792-4799-8887-bffe14481183.png">

### How to reproduce

1. Make a multi-site
2. localize a collection
3. make 1 entry that's localized in both sites, with the same title (but different content)
4. Add an Entries fieldtype to a blueprint
5. try to figure out which one is which.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.37.0
PHP Version: 8.1.12
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: zakat.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 20
Antlers: runtime
Version: 3.3.49 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.0
aryehraber/statamic-impersonator: 2.4.1
aryehraber/statamic-uuid: 2.1.0
doublethreedigital/duplicator: 2.3.2
doublethreedigital/runway: 2.5.4
edalzell/forma: 1.2
jacksleight/statamic-bard-mutator: 1.1.2
jacksleight/statamic-bard-texstyle: 1.0.3
jonassiewertsen/statamic-livewire: 2.9.0
statamic/seo-pro: 3.1.0
swiftmade/statamic-clear-assets: 1.1.0
transformstudios/events: 4.0.6
transformstudios/front: 1.11.0
transformstudios/gated: dev-main
transformstudios/github: dev-main
transformstudios/magic-link: dev-main
transformstudios/memorial: dev-main
transformstudios/review: 3.6.0
transformstudios/simple: 2.12.1
transformstudios/takeover-redirects: dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
