### ISSUE TITLE
Fresh install on server - Can't locate path dist and dist-frontend

### ISSUE THREAD

**Issue by ryatkins** [statamic/cms#7023]
### Bug description

Cannot publish assets as they don't exist in the vendor folder.  We are updating to 3.3 from 3.1.   This works locally, but not on our Forge Ubuntu (Digital Ocean) server. 

```
 INFO  Publishing [statamic-cp] assets.  
 ERROR  Can't locate path: <vendor/statamic/cms/src/Providers/../../resources/dist>.  

 INFO  Publishing [statamic-frontend] assets.  
 ERROR  Can't locate path: <vendor/statamic/cms/src/Providers/../../resources/dist-frontend>.  
```

### How to reproduce

Fresh install:

1. Clone the project
2. Run composer install 
3. Run php artisan statamic:install 

### Logs

```shell
{
    "name": "studio1902/statamic-peak",
    "description": "Statamic Peak",
    "keywords": [
        "statamic",
        "cms",
        "flat file",
        "laravel"
    ],
    "type": "project",
    "require": {
        "php": "^8.1",
        "ext-json": "*",
        "aerni/imagekit": "^2.2",
        "barryvdh/laravel-snappy": "^1.0",
        "bashy/laravel-campaignmonitor": "^6.0",
        "doublethreedigital/duplicator": "^2.3",
        "gabrielbull/ups-api": "^2.0",
        "guzzlehttp/guzzle": "^7.3",
        "jonassiewertsen/statamic-livewire": "^2.9",
        "laravel/framework": "^9.36",
        "laravel/horizon": "^5.8",
        "laravel/tinker": "^2.7",
        "league/flysystem-aws-s3-v3": "^3.0",
        "predis/predis": "^1.1",
        "sentry/sentry-laravel": "^2.11",
        "statamic/cms": "^3.3",
        "statamic/seo-pro": "^3.1",
        "xndbogdan/statamic-bard-text-color": "^1.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.6",
        "fakerphp/faker": "^1.13.0",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.3",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.4"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pixelfear/composer-dist-plugin": false
        }
    },
```

### Environment

```yaml
Forge Ubuntu (Digital Ocean) server

Laravel Version: 9.39.0
PHP Version: 8.1.11
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: --- redacted
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 5
Antlers: regex
Version: 3.3.52 PRO

Statamic Addons
aerni/imagekit: 2.2.0
doublethreedigital/duplicator: 2.3.3
jonassiewertsen/statamic-livewire: 2.9.0
statamic/seo-pro: 3.1.1
xndbogdan/statamic-bard-text-color: 1.0.2
```

### Installation

Existing Laravel app

### Antlers Parser

regex (default)
