### ISSUE TITLE
Safari: Images in listable columns only load after a refresh

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7024]
### Bug description

When you have a listing table with a blueprint containing a listable image field, the image in Safari only loads after a refresh.

**Initial state**
<img width="985" alt="Screenshot 2022-11-08 at 20 03 26" src="https://user-images.githubusercontent.com/69107412/200652717-96cd3878-2c49-48d2-886a-aad1541e5cc8.png">

**Refreshed state**
<img width="998" alt="Screenshot 2022-11-08 at 20 03 33" src="https://user-images.githubusercontent.com/69107412/200652754-5fc028cc-9284-4672-8244-34773be89046.png">

### How to reproduce

1. Add an `image` field (limit = 1) to your collection blueprint.
2. Set the field to `listable: true`.
3. View the listing table in the CP in Safari. 
4. See no images.
5. Refresh.
6. See images.

### Environment

```yaml
Environment
Application Name: SDG House Groningen
Laravel Version: 9.39.0
PHP Version: 8.1.10
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: sdghousegroningen.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.52 PRO
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

### Additional details

This has been an issue for a long time, but I never got around to submitting it :-).
