### ISSUE TITLE
CP saving of entry timeouts

### ISSUE THREAD

**Issue by ryatkins** [statamic/cms#7029]
### Bug description

When saving an entry in CP the file saves, but the UI loading indicator does not complete.  The network tab continues to show processing when trying to save the entry
`https://.../cp/collections/countries/entries/ecb4f452-85e0-482f-894d-36ad43175330`

We've tried 
- with caching on or off.  
- Debugging disabled.
- Fresh install of existing app

### How to reproduce

Save an entry.

### Environment

```yaml
Laravel Version: 9.37.0
PHP Version: 8.1.11
Composer Version: 2.4.4
Environment: local
Debug Mode: OFF
URL: ...
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 5
Antlers: regex
Version: 3.3.53 PRO

Statamic Addons
aerni/imagekit: 2.2.0
doublethreedigital/duplicator: 2.3.2
jonassiewertsen/statamic-livewire: 2.9.0
statamic/seo-pro: 3.1.0
xndbogdan/statamic-bard-text-color: 1.0.2
```

### Installation

Existing Laravel app

### Antlers Parser

regex (default)
