### ISSUE TITLE
Root page children bug introduced in 3.3.53 when nav contains nested item

### ISSUE THREAD

**Issue by taylorcammack** [statamic/cms#7031]
### Bug description

Seeing "This would cause the root page to have children." errors when trying to update any pages on the top level. Can create a page without issues. Downgraded to 3.3.52 and everything works as expected.

### How to reproduce

1. Assuming a fresh collection, create an unnested page. Should be able to update all pages without issues.
2. Create a nested page. Now unable to make any updates.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.39.0
PHP Version: 8.1.11
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.53 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
