### ISSUE TITLE
Focus point value doesn't save in .meta yaml-file when editing other fields at the same time

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#7032]
### Bug description

If you edit an image in the control panel, select a focus point and edit other fields (like the alt field) at the same time, you will lose the values of the focus point after saving.

Currently, in order to save the values of the focus point to the .meta yaml-file, you have to click on the "Save" button directly after selecting the focus point.

Then you can reopen the edit screen for edit the alt text.

### How to reproduce

- Upload a image in the CP
- Set a focus point and edit the alt-text at the same time
- Click save
- Check the .meta yaml-file → **Only the alt-text was saved**
- Set the focus point again without touching the alt field
- Click save again → Now the focus-point values are present in the yaml-file
- After that you can edit the alt-Text. As long as you don't edit the focus point at the same time you are fine.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.39.0
PHP Version: 8.1.11
Composer Version: 2.4.3
Environment: local
Debug Mode: ENABLED
URL: test-focus.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.54 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
