### ISSUE TITLE
The "All" tab in the Collection Filters won't translate yet

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#7035]
### Bug description

If you save Collection Filters in the CP, the "All" Tab won't translate yet. The string is already present in the json translation files though. 

I guess the line in `resources/js/components/data-list/FilterPresets.vue` needs some tweaks?

```
<button class="data-list-filter-link" :class="{ active: ! activePreset }" @click="viewAll">All</button>
```

<img width="292" alt="Bildschirmfoto 2022-11-10 um 22 37 58" src="https://user-images.githubusercontent.com/8265902/201212696-bb185060-dafd-42d8-8a40-97b8d9732276.png">

### How to reproduce

Save a filter in a collection listings.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.39.0
PHP Version: 8.1.11
Composer Version: 2.4.3
Environment: local
Debug Mode: ENABLED
URL: test-focus.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.54 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
