### ISSUE TITLE
Adding an asset: must be an array, may not have more than 1 items

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#704]
![image](https://user-images.githubusercontent.com/3626559/65491382-3cab1980-deaf-11e9-9850-5f6895ec722b.png)

This is the set configuration (within a Bard field):
```yaml
        image:
              display: Image
              fields:
                -
                  handle: image
                  field:
                    container: assets
                    restrict: false
                    max_files: 1
                    allow_uploads: true
                    mode: grid
                    type: assets
                    localizable: false
                    display: Image
```
