### ISSUE TITLE
Deleting assets in subfolders via CP doesn't delete the corresponding .meta yaml files.

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#7042]
### Bug description

Deleting assets in your local assets container via CP won't delete the corresponding .meta yaml files **if the assets are stored in subfolders.** Only .meta files form assets in your root will be deleted. Take a look at this example with one subfolder and two images.

before deleting:
<img width="313" alt="before deleting" src="https://user-images.githubusercontent.com/8265902/201484249-fe0026a9-bb5e-4e01-aa0e-dd8187ce5f70.png">

after deleting
<img width="274" alt="after deleting" src="https://user-images.githubusercontent.com/8265902/201484250-a92ec6a4-6e51-4b6c-9f51-e71f1a9b11f5.png">

The meta yaml from the asset in the subfolder gets some changes though. It's no difference if you delete the asset with or without an alt-text set. Without alt text you just would have the line `data: {  }` left after deleting. 
<img width="296" alt="Bildschirmfoto 2022-11-12 um 17 35 00" src="https://user-images.githubusercontent.com/8265902/201484488-29e05eda-a45f-434b-8a97-6655bd7499f9.png">

### How to reproduce

- fresh install via cli
- the next steps are all done via CP…
- create a subfolder in your assets container
- upload one image each in the root and one in the subfolder
- delete both images
- .meta yaml from image in root is gone, the one from the subfolder still extists.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.39.0
PHP Version: 8.1.11
Composer Version: 2.4.3
Environment: local
Debug Mode: ENABLED
URL: delete.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.54 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by marcorieser** [comment]
I can confirm that this issue still exists:

```yaml
Environment
Application Name: MAN | CTS
Laravel Version: 10.28.0
PHP Version: 8.2.11
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: statamic-man-cts.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.0.8

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.28.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.0.0
marcorieser/statamic-vitals: 1.1.0
```
