### ISSUE TITLE
Bard Fieldtype: Single Text node not selectable

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7050]
### Bug description

I'm migrating plain html content with [https://github.com/ueberdosis/html-to-prosemirror](html-to-prosemirror) into the Prosemirror format. When the html contains text nodes, which are not wrapped inside a paragraph, the user cannot select the text node in Bard:

The cursor randomly jumps to the next node.

![2022-11-14 16 14 16](https://user-images.githubusercontent.com/1102712/201696156-46a7cb4b-0d1e-4313-b306-684006b77873.gif)

I've tested this with #6043, but the issue is the same with tiptap 2.

### How to reproduce

The issue can be reproduced if the source html contains a text node which is not wrapped within a paragraph. Use the following source .md to reproduce:

```html
---
id: 5e1552b5-45a8-42af-8369-3df7a79125fc
title: 'Lorem Ipsum'
---
<p>
    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
</p>
Edit me :)
<h4>About us</h4>
```

_Prosemirror/YAML format:_

```
content:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
  -
    type: text
    text: 'Edit me :)'
  -
    type: heading
    attrs:
      level: '4'
    content:
      -
        type: text
        text: 'About us'
```

### Environment

```yaml
Application Name: Statamic
Laravel Version: 9.30.1
PHP Version: 8.1.11
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Version: 3.3.52 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
