### ISSUE TITLE
SVG-Icon not shown in collection listing

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#7058]
### Bug description

The icon is shown in the file browser, in the entry, but not in the listing.

### How to reproduce

![image](https://user-images.githubusercontent.com/3351449/201937669-6d6f3b92-00ed-4b9c-aa53-b2cc5bfbf942.png)
![image](https://user-images.githubusercontent.com/3351449/201937756-5d1e01b8-339a-4f5a-9bd1-10c1d357ff67.png)

![image](https://user-images.githubusercontent.com/3351449/201937832-cb915aab-4e54-4d72-9244-d21f32d89c7b.png)

Example file:
[icon_pulverbeschichtung.zip](https://github.com/statamic/cms/files/10013272/icon_pulverbeschichtung.zip)

### Environment

```yaml
Environment
Laravel Version: 9.39.0
PHP Version: 8.0.12
Composer Version: 2.1.3
Environment: local
Debug Mode: ENABLED      
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED    

Drivers
Broadcasting: log
Cache: statamic  
Database: mysql  
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Version: 3.3.55 PRO

Statamic Addons
doublethreedigital/duplicator: 2.3.4
nineteensquared/instagram: 1.1.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
