### ISSUE TITLE
Invalid slug validation when using `max_depth: 1`

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7066]
### Bug description

Validation of a valid entry fails with `This URI has already been taken` when collection nesting is configured with `max_depth: 1`. I'm not sure if this is intended behavior, but it feels quite weird. 🤔

![2022-11-16 15 18 16](https://user-images.githubusercontent.com/1102712/202205124-49d2eb26-2ca1-45e0-a632-8a9ca5a4a499.gif)

### How to reproduce

I'm using the following collection configuration:

```
title: News
template: news/index
layout: layout
revisions: false
route: '/news/{slug}'
sort_dir: asc
default_status: draft
preview_targets:
  -
    label: Entry
    url: '{permalink}'
structure:
  root: false
  max_depth: 1
  slugs: true
```

Scenario a)
1. Create & _Publish_ a new entry with slug `test`.
2. Create another entry and save as draft with same slug `test`.
3. Publish the second entry. Result: Validation error `This URI has already been taken`, which is correct.
4. Change the slug from `test` to `test123` and Save. Result: Validation error `This URI has already been taken`, which is not correct.

Scenario b)
1. Create & _Publish_ a new entry with slug `test`.
2. Create & _Publish_ a new entry with slug `test`. _Result_: No validation error.
3. Change the slug from `test` to `test123` and Save. Result: Validation error `This URI has already been taken`, which is not correct.

_Workaround_: remove `max_depth: 1` from collection configuration or disable ordering.

### Environment

```yaml
Environment
Application Name: Test
Laravel Version: 9.39.0
PHP Version: 8.1.10
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Version: 3.3.53 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
