### ISSUE TITLE
@nocache blade directive causes fatal error

### ISSUE THREAD

**Issue by jolora** [statamic/cms#7067]
### Bug description

I'm trying to use the `@nocache` Blade directive but whenever I do I get the following PHP error:

> Nesting level too deep - recursive dependency?

Stack trace points to vendor/statamic/cms/src/StaticCaching/NoCache/Region.php:55

### How to reproduce

Use the `@nocache` Blade directive. Here's an example from my code:

```
<nav>
  <x-nav-mobile />
  <div class="-ml-4 hidden lg:block">
    @foreach (Statamic::tag('nav:main') as $item)
      <a href="{{ $item["url"] }}" class="mx-4 nav__link">{{ $item['title'] }}</a>
    @endforeach
  </div>
  @nocache('components/header-auth')
</nav>
```

### Logs

```shell
[2022-11-16 15:19:55] local.ERROR: Nesting level too deep - recursive dependency? {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Nesting level too deep - recursive dependency? at /Users/jolora/Code/theoffsiteguide/vendor/statamic/cms/src/StaticCaching/NoCache/Region.php:55)
[stacktrace]
#0 {main}
"}
```

### Environment

```yaml
Environment
Application Name: The Offsite Guide
Laravel Version: 9.38.0
PHP Version: 8.1.11
Composer Version: 2.2.3
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Scout: algolia
Session: redis

Statamic
Addons: 2
Antlers: runtime
Version: 3.3.52 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.0
stuartcusackie/statamic-blade-view-data: 1.1.13
```

### Installation

Existing Laravel app
