### ISSUE TITLE
Using `JsonResource::withoutWrapping()` in Laravel breaks Statamic CP

### ISSUE THREAD

**Issue by jhhazelaar** [statamic/cms#7068]
### Bug description

When using `JsonResource::withoutWrapping()` in a Laravel application breaks Statamic CP. Listing is empty and can't create entry.

There already 2 issues with this error https://github.com/statamic/cms/issues/4431 and https://github.com/statamic/cms/issues/1365. The comments on this tickets are saying that you can't use `JsonResource::withoutWrapping()`, but I think that isn't the solution.

### How to reproduce

- Install fresh Laravel installation.
- Install Statamic into the Laravel installation.
- Add `JsonResource::withoutWrapping()` to AppServiceProvider (https://laravel.com/docs/9.x/eloquent-resources#data-wrapping)
- In CP goto Users and see empty listing.

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 9.40.1
PHP Version: 8.1.12
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: laravel-statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.55 PRO
```

### Installation

Existing Laravel app

### Additional details

I think the solution is to change the return values in the ResourceCollection `toArray` and correct implement the `meta` key return according to the Laravel docs: https://laravel.com/docs/9.x/eloquent-resources#adding-meta-data
