### ISSUE TITLE
Multi-Site broken: Wrongly cached data of localizations leads to lost content in control panel and multiple (wrong) .md files for the same entry

### ISSUE THREAD

**Issue by wanze** [statamic/cms#7077]
### Bug description

https://user-images.githubusercontent.com/2118742/211855859-d642eb45-40bf-43d8-b9f3-b490423e0fe0.mp4

### Preconditions

* 3 sites (at least)
* `STATAMIC_STACHE_WATCHER` is set to `false`

### How to reproduce

1. Create a new entry in the default site. Save it **unpublished** (Save draft)
2. Create a new entry in the second site. Save it **unpublished** (Save draft)
3. Publish both entries (Save & Publish)
4. Create a new entry for the third site, save and publish it.
5. In the sidebar, navigate back to the entry of the second site.

Notice that the just created entry for the third site is not existing anymore (red/crossed). If you know click again on it, Statamic will create a new file on the disk and the previous content is no longer visible in the control panel. 🙀You can repeat this over and over again and create multiple files for the same entry. Clearing the Stache does not fix it, you have to manually remove the "wrong" files from the disk.

### How to fix

I think that this issue is caused by serving wrongly cached data of the localizations to the frontend. More information: https://github.com/statamic/cms/issues/7077#issuecomment-1379034698

### Environment

```yaml
Environment
Application Name: Statamic-Sandbox
Laravel Version: 9.45.1
PHP Version: 8.1.13
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: statamic-sandbox.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.3.64
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
