### ISSUE TITLE
Live Preview not working with static cache and ignore_query_strings 

### ISSUE THREAD

**Issue by naabster** [statamic/cms#7079]
### Bug description

Live Preview is not working if you enable static caching with the ignore_query_strings option:

Changes made are not updated.

### How to reproduce

- enable static caching (either half or full)
- set config `statamic.static_caching.ignore_query_strings` to `true`
- edit some entry in live preview

### Environment

```yaml
Environment
Application Name: Statamic Demo
Laravel Version: 9.40.1
PHP Version: 8.1.12
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Version: 3.3.56 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
