### ISSUE TITLE
Entry always creates a date on a localized file, even when the collection has no dates.

### ISSUE THREAD

**Issue by tao** [statamic/cms#7085]
### Bug description

When you create a localization on Multisite, it creates a date in the filename even if the collection itself does not use dates.

For example I have a Wiki collection with an Entry on "compassion". The filename is:

```
content/collections/wiki/en
└── compassion.md
```

If I create a new localization for French, the new filename includes a date:

```
content/collections/wiki/fr
└── 2021-08-12-2309.compassion.md
```

This happens because the [makeLocalization](https://github.com/statamic/cms/blob/3.3/src/Entries/Entry.php#L639) function doesn't check if the collection uses dates or not, and automatically adds dates:

```php
    public function makeLocalization($site)
    {
        return Facades\Entry::make()
            ->collection($this->collection)
            ->origin($this)
            ->locale($site)
            ->published($this->published)
            ->slug($this->slug())
            ->date($this->date());
    }
```

### How to reproduce

Create a collection without dates and try add a new entry.

### Environment

```yaml
Environment
Laravel Version: 9.24.0
PHP Version: 8.0.24
Composer Version: 2.0.11
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Scout: elasticsearch
Session: file

Statamic
Addons: 3
Antlers: runtime
Version: 3.3.28 PRO

Statamic Addons
statamic/collaboration: 0.4.0
statamic/ssg: 1.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

Related to [Make multisite great again](https://github.com/statamic/ideas/issues/880).
