### ISSUE TITLE
Home icon jumps to the alphabetically first entry in list mode

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#7094]
### Bug description

If you have a collection with max_depth more than one, the home icon jumps to the first entry when you change the view from tree to list. Because list view is sorted alphabetical, it's most likely that this won't be the homepage.

<img width="898" alt="Bildschirmfoto 2022-11-21 um 18 26 38" src="https://user-images.githubusercontent.com/8265902/203122079-c7355982-5fcc-4d00-a1e4-a94352e090ef.png">
<img width="896" alt="Bildschirmfoto 2022-11-21 um 18 26 44" src="https://user-images.githubusercontent.com/8265902/203122089-27b1ccea-f358-4ccc-9bf3-a2c4d189b3a1.png">

Here's the pages.yaml

```
title: Pages
template: default
layout: layout
revisions: false
route: '{parent_uri}/{slug}'
sort_dir: asc
preview_targets:
  -
    label: Entry
    url: '{permalink}'
structure:
  root: true
  max_depth: 2
```

### How to reproduce

- fresh install via cli
- change max_depth in pages collection to something else than 1
- add some entries
- rearrange them in tree view
- switch to list view

### Environment

```yaml
Application Name: Statamic
Laravel Version: 9.40.1
PHP Version: 8.1.11
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: startseite.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.57 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
