### ISSUE TITLE
CP Thumbnails timing out with 524 - High CPU

### ISSUE THREAD

**Issue by ryatkins** [statamic/cms#7096]
### Bug description

CP Thumbnails keep timing out upon loading of an entry and they don't look to be cached.

I have run `php artisan statamic:assets:generate-presets` and it has completed without errors.

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/1211767/203146701-ea55b659-6066-4d84-8d74-e0cd2eee5e52.png">

### How to reproduce

Load an entry with images.

Images are stored on Digital Ocean Spaces.

Thumbnails are being stored on the filesystem. 

### Environment

```yaml
Environment
Laravel Version: 9.37.0
PHP Version: 8.1.12
Composer Version: 2.4.4
Environment: production
Debug Mode: ENABLED
URL: staging...
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: array
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: regex
Version: 3.3.49 PRO

Statamic Addons
aerni/imagekit: 2.2.0
doublethreedigital/duplicator: 2.3.2
jonassiewertsen/statamic-livewire: 2.9.0
statamic/seo-pro: 3.1.0
xndbogdan/statamic-bard-text-color: 1.0.2
```

### Installation

Existing Laravel app

### Antlers Parser

regex (default)

### Additional details

This started happening after update from 3.1 to 3.3.
