### ISSUE TITLE
Not possible to translate the Assets Page title

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#7098]
### Bug description

I've been working on the Norwegian translation, and I see the same in the Danish translation. When clicking on Assets -> Assets in the menu the title reads "Assets" over the list.

![Screenshot 2022-11-22 at 01 45 51](https://user-images.githubusercontent.com/1135679/203187959-18ab2ab7-9c51-43e3-9a6d-a76491ec2bfe.png)

And while I'm at it - the string "File" in xx.json, is this used in several places? I would like to call it "Name" instead as it is more like what I would expect if comparing to the MacOS finder or Windows Explorer. That is if it is only used above the file-/foldername list.

### How to reproduce

Try to use another language in CP and go to the Assets menu.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.40.1
PHP Version: 8.0.23
Composer Version: 2.2.6
Environment: local
Debug Mode: ENABLED
URL: properti-master.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Version: 3.3.58 PRO

Statamic Addons
r8edge/imagemap: dev-espenlg/nov3
r8edge/welcome-widget: dev-main
statamic/eloquent-driver: 1.1.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
