### ISSUE TITLE
Date based filtering doesn't work with date ranges

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7099]
### Bug description

I have a collection with a date range field. I tried filtering the collection like this:

`event_date.end:is_after="{ today }"` 

Unfortunately this doesn't return any results while there are entries with the following data:

```yaml
event_date:
  start: '2022-11-26'
  end: '2022-11-30'
```

### How to reproduce

1. Create a collection with a date range field.
2. Enter some entries (doesn't matter what dates you use for the date field).
3. Filter the collection using: `your_date_field.end:is_after="{ today }"` 
4. See no results

Workaround: use two single date fields.

### Environment

```yaml
Environment
Application Name: SDG House Groningen
Laravel Version: 9.40.1
PHP Version: 8.1.10
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: sdghousegroningen.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Version: 3.3.58 PRO

Statamic Addons
doublethreedigital/duplicator: 2.3.4
jonassiewertsen/statamic-livewire: 2.9.0
rias/statamic-color-swatches: 2.1.9
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
