### ISSUE TITLE
Using 'skip' operator with assets fieldtype does not 'reset' indices of items

### ISSUE THREAD

**Issue by St3Ko** [statamic/cms#7120]
### Bug description

When using the `skip` operator with an `assets` fieldtype (in this case with four elements) like this:
```antlers
{{ assets_field = assets_field skip (1) }}
```
the output of
```antlers
{{ dump:assets_field }}
```
will be:
```
array:3 [▼
  1 => array:44 [▶]
  2 => array:44 [▶]
  3 => array:44 [▶]
]
```

with `skip (2)` for example it becomes:
```
array:2 [▼
  2 => array:44 [▶]
  3 => array:44 [▶]
]
```

This becomes a problem when you now loop over these elements and you need to dereference them by using the index of the loop, the indexing of the elements will fail because `index` inside the loop will start from `0`.

for example like this:
```antlers
{{ _assets_field = assets_field skip (1) }}
    {{ partial:components/image :image="_assets_field[index]" }}
{{ /_assets_field }}
```

### How to reproduce

* create a assets field
* add some items
* use the `skip` operator to get a 'slice' of the elements
* 'slice' will not start on index `0`

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.41.0
PHP Version: 8.1.10
Composer Version: 2.3.8
Environment: local
Debug Mode: ENABLED
URL: index-problem.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Version: 3.3.58 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
