### ISSUE TITLE
'Simple' loop syntax with 'skip' operator does not work with assets fieldtype

### ISSUE THREAD

**Issue by St3Ko** [statamic/cms#7121]
### Bug description

This syntax
```antlers
{{ assets_field skip (1) }}
    ..do stuff
{{ /assets_field }}
```
and using it like this
```antlers
{{ assets_field = assets_field skip (1) }}
    ..do stuff
{{ /assets_field }}
```
does not apply the skip operator on `assets` fieldtypes and will loop over every element.

Assigning it to a different name however works:
```antlers
{{ _assets_field = assets_field skip (2) }}
    ..do stuff
{{ /_assets_field }}
```

### How to reproduce

see bug description

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.41.0
PHP Version: 8.1.10
Composer Version: 2.3.8
Environment: local
Debug Mode: ENABLED
URL: index-problem.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Version: 3.3.58 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
