### ISSUE TITLE
Multi-Site: New Child Entry propagates localized entry to wrong parent

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7127]
### Bug description

Adding a new Child Entry to a nested Collection results in a localized entry which gets saved as a parent.

![2022-11-27 18 53 14](https://user-images.githubusercontent.com/1102712/204152432-f2049965-7479-44fc-87e8-7e989a17b490.gif)

### How to reproduce

1. Enable Multi-Site.
2. Configure collection with `propagate: true`.
3. Add a new Child Entry to a nested collection.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.41.0
PHP Version: 8.1.10
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.58 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

_Possible way to resolve this issue:_
* Add a proper Test Case.
* Use `addToStructure()` from [LocalizeEntryController](https://github.com/statamic/cms/blob/3.3/src/Http/Controllers/CP/Collections/LocalizeEntryController.php#L27-L51) when [Entry propagates](https://github.com/statamic/cms/blob/3.3/src/Entries/Entry.php#L631-L645).
