### ISSUE TITLE
CP Exception when editing an image / asset

### ISSUE THREAD

**Issue by flolanger** [statamic/cms#7129]
### Bug description
When editing an image / asset inside a collection entry and save it, the following exception occurs in the CP:
![Bildschirmfoto 2022-11-27 um 23 18 51](https://user-images.githubusercontent.com/21835310/204163975-c13908b3-f607-4698-a291-d03a7fa1ffc4.png)

### How to reproduce

On any collection with an asset field type:

1. Open entry with asset field type
2. Edit existing asset and click "Save".
3. -> Asset-Preview is missing now
4. Save the entry
5. -> CP Exception occurs (see screenshot above)

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 9.41.0
PHP Version: 8.1.12
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.58 PRO

Statamic Addons
pecotamic/sitemap: 1.4.0
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)
