### ISSUE TITLE
Statamic Pro is required.

### ISSUE THREAD

**Issue by gausoft** [statamic/cms#7137]
### Bug description

After adding Statamic 3.3 as Laravel package in existing projet, I'am unable to create root user in order to connect to control panel.

### How to reproduce

Folowing [this guide](https://statamic.dev/installing/laravel)

I've successfully added statamic but when trying to create Statamic user with: `php please:make user`, 

I got : Statamic Pro is required.

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 9.38.0
PHP Version: 8.1.11
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.58 Solo
```

### Installation

Existing Laravel app
