### ISSUE TITLE
Frontend TypeError: this.localizations.find(...) is undefined

### ISSUE THREAD

**Issue by tao** [statamic/cms#7141]
### Bug description

I believe this bug was introduced by the localization modal in v3.3.51, the modal and the ability to bypass localization confirmation modal works great if you're translation an Entry that already exists. However, I found it you try create a new Entry we run into a Javascript error.

The error exists with both `origin_behavior: select` or `origin_behavior: root`.

![Screenshot 2022-11-29 at 16 17 19](https://user-images.githubusercontent.com/1446331/204553062-df8d6593-0f57-4553-b4a1-da8e53e17636.png)

I tried to investigate and debug this more but unfortunately I can't figure out how to compile and run the Javascript code.

This line is causing the issue, PublishForm.vue#756

```js
    created() {
        window.history.replaceState({}, document.title, document.location.href.replace('created=true', ''));

        this.selectedOrigin = this.originBehavior === 'active'
            ? this.localizations.find(l => l.active).handle
            : this.localizations.find(l => l.root).handle;
    },
```

### How to reproduce

Try create a new entry in Multisite and check the console.

### Environment

```yaml
Environment
Laravel Version: 9.41.0
PHP Version: 8.1.12
Composer Version: 2.0.11
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Version: 3.3.58 PRO

Statamic Addons
statamic/collaboration: 0.4.0
statamic/ssg: 1.2.0
stillat/relationships: 1.2.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
