### ISSUE TITLE
Incorrect partial src when Antlers variable collides with bard set handle

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7155]
### Bug description

I'm assining an unaugmented bard field with the `raw` Modifier to a variable in my Antlers View. The view also contains a `partial` tag with a dynamic `src="set/{type}"` to include a bard set. The dynamic partial source cannot be resolved when my variable name collides with a bard set handle.

I have no idea if I'm doing something wrong within my Antlers, but I was not expecting this. 😅

### How to reproduce

_View:_
```antlers
{{ news = {collection:news sort="date:desc"} }}
  {{ article = bard_field | raw }}
  {{# ... doing something with my variable article ... #}}

  {{ bard_field }}
    {{ if type == 'article' }} {{# not required, just for better understanding #}}
      {{ partial src="set/{type}" }} {{# Expected src path = "set/article" #}}
      {{# 
           Results in: "View [components.article] not found"
           I was expecting View: set.article
           Workaround: Rename the previous declared variable
       #}}
    {{ /if }}
  {{ /bard_field }}
{{ /news }}

```
_Blueprint:_
```yaml
# ... 
-
  handle: bard_field
  field:
    sets:
      article:
        display: Article
        fields:
          -
            # ... 
```

_Content:_
```yaml
# ... 
bard_field:
  -
    id: pADmSHXR
    type: article
    enabled: true
    article:
      -
        # ...
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.30.1
PHP Version: 8.1.11
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Version: 3.3.59 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
