### ISSUE TITLE
API pagination size

### ISSUE THREAD

**Issue by tomhelmer** [statamic/cms#7160]
### Bug description

In the api.php config file there's a pagination_size setting:

`     'pagination_size' => 50,`

but the paginate function has a hardcoded page size :

```
protected function paginate($query)
    {
        $columns = explode(',', request()->input('fields', '*'));

        return $query
            ->paginate(request()->input('limit', 25), $columns)
            ->appends(request()->only(['filter', 'limit', 'page', 'sort']));
    }
```

### Environment

```yaml
Environment
Laravel Version: 9.42.2
PHP Version: 8.1.12
Composer Version: 2.4.4
Environment: staging
Debug Mode: ENABLED
Maintenance Mode: OFF
```
