### ISSUE TITLE
Duplicated entries with slugs: false should have id as filename

### ISSUE THREAD

**Issue by wesort** [statamic/cms#7166]
### Bug description

Duplication actions in core (#6307) ignores the expected behaviour when a collection is set to `slugs: false`.  

_Ref: Expected via Hot Tip mentioned in [statamic.dev/collections#slugs](https://statamic.dev/collections#slugs)._ 

The newly duplicated filename is `1.md` rather than the newly generated `id` - ie: `ce1068d8-704e-4bdc-82d9-94d5f45d093a.md`

Screenshot:
- left: filename not `id`
- right: collection .yaml with `slugs: false`
-
![statamic-filename-not-id](https://user-images.githubusercontent.com/3920126/205615772-ed92ec68-905a-4ef9-98a5-a63913ee59e8.png)

### How to reproduce

CP `>` visit a collection listing `>` select "Duplicate" from "Actions menu" on an entry `>` "Run action"

Viewing the newly created content file shows the `.md` filename is not the `{id}` that is generated and set within the new content.

### Environment

```yaml
Environment
Application Name: Villon Films
Laravel Version: 9.42.2
PHP Version: 8.1.12
Composer Version: 2.4.4
Environment: dev
Debug Mode: ENABLED
URL: dev.villonfilms.ca
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Version: 3.3.60 PRO

Statamic Addons
aryehraber/statamic-uuid: 2.1.0
rias/statamic-data-import: 1.2.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

### Additional details

FWIW: Is the "Antlers Parser question necessary still considering `php please support:details` provides this?
