### ISSUE TITLE
Images in CP listings are huge

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7192]
### Bug description

When you use an `asset` field in a a blueprint and make the field `listable` you get a nice preview in the entry listings (this [doesn't work](https://github.com/statamic/cms/issues/7024) well in Safari however).

Statamic generates thumbnails for those listings however something is broken here. The thumbnails are actually huge images which results in a slow CP experience. 
![Screenshot_2022-12-09_at_10 47 28](https://user-images.githubusercontent.com/69107412/206852056-f1ebcbec-c49b-4e75-afe4-5e05add5f1e0.png)

### How to reproduce

1. Add an asset field to a collection blueprint
2. Make the asset field listable
3. Upload BIG images
4. Create entries and select a BIG image
5. Check the entry listing

### Environment

```yaml
Environment
Laravel Version: 9.42.2
PHP Version: 8.1.10
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Version: 3.3.60 PRO
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
