### ISSUE TITLE
Cloudflare R2 disk setup with S3 resulting in "unable to copy file from source to cache" error

### ISSUE THREAD

**Issue by el-schneider** [statamic/cms#7193]
### Bug description

Assets are not being shown in filebrowser, but files can be uploaded and show in the respective Cloudflare R2 Bucket

Issue might be related to https://github.com/statamic/cms/pull/5996

<img width="1295" alt="grafik" src="https://user-images.githubusercontent.com/26460248/206854809-0e73cc89-fb7e-4334-8bb8-35723e1244d3.png">

### How to reproduce

Here is a demo repo:
https://github.com/el-schneider/statamic-r2

### Logs

```shell
[2022-12-10 12:17:11] local.ERROR: Unable to copy file from source://aaf123d29f3f6403ee9ab5a5d21fe733-3.jpg to cache://aaf123d29f3f6403ee9ab5a5d21fe733-3.jpg {"userId":"bd612549-77ed-486b-86cf-579d1990ef4c","exception":"[object] (League\\Flysystem\\UnableToCopyFile(code: 0): Unable to copy file from source://aaf123d29f3f6403ee9ab5a5d21fe733-3.jpg to cache://aaf123d29f3f6403ee9ab5a5d21fe733-3.jpg at /Users/jonas/dev/playground/statamic-r2/vendor/league/flysystem/src/UnableToCopyFile.php:37)
[stacktrace]
#0 /Users/jonas/dev/playground/statamic-r2/vendor/league/flysystem/src/MountManager.php(371): League\\Flysystem\\UnableToCopyFile::fromLocationTo('source://aaf123...', 'cache://aaf123d...', Object(League\\Flysystem\\UnableToRetrieveMetadata))
#1 /Users/jonas/dev/playground/statamic-r2/vendor/league/flysystem/src/MountManager.php(245): League\\Flysystem\\MountManager->copyAcrossFilesystem(NULL, Object(League\\Flysystem\\Filesystem), 'aaf123d29f3f640...', Object(League\\Flysystem\\Filesystem), 'aaf123d29f3f640...', 'source://aaf123...', 'cache://aaf123d...')
#2 /Users/jonas/dev/playground/statamic-r2/vendor/statamic/cms/src/Imaging/Attributes.php(20): League\\Flysystem\\MountManager->copy('source://aaf123...', 'cache://aaf123d...')
#3 /Users/jonas/dev/playground/statamic-r2/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Statamic\\Imaging\\Attributes->from(Object(League\\Flysystem\\Filesystem), 'aaf123d29f3f640...')
#4 /Users/jonas/dev/playground/statamic-r2/vendor/statamic/cms/src/Assets/Attributes.php(78): Illuminate\\Support\\Facades\\Facade::__callStatic('from', Array)
#5 /Users/jonas/dev/playground/statamic-r2/vendor/statamic/cms/src/Assets/Attributes.php(43): Statamic\\Assets\\Attributes->getImageAttributes()
#6 /Users/jonas/dev/playground/statamic-r2/vendor/statamic/cms/src/Assets/Asset.php(264): Statamic\\Assets\\Attributes->get()
#7 /Users/jonas/dev/playground/statamic-r2/vendor/statamic/cms/src/Assets/Asset.php(238): Statamic\\Assets\\Asset->generateMeta()
#8 /Users/jonas/dev/playground/statamic-r2/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(426): Statamic\\Assets\\Asset->Statamic\\Assets\\{closure}()
#9 /Users/jonas/dev/playground/statamic-r2/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(418): Illuminate\\Cache\\Repository->rememberForever('asset-meta-asse...', Object(Closure))
#10 /Users/jonas/dev/playground/statamic-r2/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\\Cache\\CacheManager->__call('rememberForever', Array)
#11 /Users/jonas/dev/playground/statamic-r2/vendor/statamic/cms/src/Assets/Asset.php(241): Illuminate\\Support\\Facades\\Facade::__callStatic('rememberForever', Array)
#12 /Users/jonas/dev/playground/statamic-r2/vendor/statamic/cms/src/Assets/Asset.php(246): Statamic\\Assets\\Asset->meta()
#13 /Users/jonas/dev/playground/statamic-r2/vendor/statamic/cms/src/Assets/Asset.php(215): Statamic\\Assets\\Asset->metaValue('size')
#14 /Users/jonas/dev/playground/statamic-r2/vendor/statamic/cms/src/Assets/Asset.php(823): Statamic\\Assets\\Asset->meta('size')
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.43.0
PHP Version: 8.1.13
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: statamic-r2.test
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.60 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
