### ISSUE TITLE
Default category cache cannot be created

### ISSUE THREAD

**Issue by hlorofos** [statamic/cms#7199]
### Bug description

Blog collection view is broken in CP:

file_put_contents(***/storage/framework/cache/data/stache/items/terms/categories/default/): Failed to open stream: Is a directory (View: /***/vendor/statamic/cms/resources/views/collections/show.blade.php)

### How to reproduce

Create a blog entity with empty Categories (Taxonomy)
```yaml
---
id: dd6aaf10-31ab-412b-8db9-12729b698a8d
blueprint: blog
title: 'This is a title'
author: 5d4ffd4f-f4f6-429e-8717-196699291931
categories:
  - null
hero_image: 2022-12/post_image_lorem.jpeg
---
Here is the content
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.43.0
PHP Version: 8.1.13
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: cmska2.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.60 PRO

Statamic Addons
raynl/generate-slug: 1.1.1
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
