### ISSUE TITLE
Term creation through fieldtype doesn't respect locale for slug

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/cms#7200]
### Bug description

Creating a term normally through its taxonomy page will generate the correct slug, however creating the term through the fieldtype will result in the slug being generated with English.

The term `Kødpålæg` in Danish should generate the slug `koedpaalaeg`, but in English it's generated as `kodpalaeg`.

### How to reproduce

1. Create a site with Danish locale `da_DK`
2. Create a `tags` taxonomy
3. Create the term `Kødpålæg` in Danish and verify the slug is as stated above
4. Delete the term again
5. Create an entry with the taxonomy associated in Danish
6. Add `Kødpålæg` in the terms field without it existing
7. Save the entry and go to the tags taxonomy
8. Verify that the slug is wrongly generated as `kodpalaeg`

### Environment

```yaml
Environment
Application Name: Comwell
Laravel Version: 9.42.2
PHP Version: 8.0.19
Composer Version: 2.1.5
Environment: local
Debug Mode: ENABLED
URL: comwell-v2.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: daily
Mail: mailgun
Queue: sync
Session: redis

Statamic
Addons: 3
Antlers: runtime
Version: 3.3.60 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 1.1.2
pecotamic/sitemap: 1.4.0
statamic/eloquent-driver: 1.1.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
