### ISSUE TITLE
Replacing an asset trashes meta data (alt)

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7215]
### Bug description

When you replace an asset (amazing feature btw), you loose any data entered in the blueprint fields like `alt` text.

_Note:_ This does not happen when reuploading an asset.

### How to reproduce

1. Upload an asset.
2. Set an alt text.
3. Replace the asset with another file.
4. Open the asset.
5. Be like: "Hey! Where's my alt text?"

### Environment

```yaml
Environment
Application Name: Statamic Peak
Laravel Version: 9.43.0
PHP Version: 8.1.10
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: statamic-peak-dev.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.60 PRO

Statamic Addons
studio1902/statamic-peak-commands: 1.1
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
