### ISSUE TITLE
Unable to use custom validation rule in backend

### ISSUE THREAD

**Issue by maxi032** [statamic/cms#7225]
### Bug description

I need to check if a record is unique in it's collection but not only by id. I need to check the uniqueness in combination with the value from another field too.
For that I made a custom rule with

```php artisan make:rule MyRule```

Basically I followed this example: https://benfurfie.co.uk/articles/adding-custom-validation-rules-to-statamic-3
but the rule is not visible in the dropdown.

### How to reproduce

Try to add a new rule with: ```php artisan make:rule MyRule```

### Environment

```yaml
Environment
Application Name: Test
Laravel Version: 9.42.2
PHP Version: 8.2.0
Composer Version: 2.4.4
Environment: production
Debug Mode: ENABLED
URL: webdev.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / daily
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: regex
Version: 3.3.59 PRO

Statamic Addons
spatie/statamic-responsive-images: 2.14.4
withcandour/aardvark-seo: 2.0.30
```

### Installation

Existing Laravel app

### Antlers Parser

None
