### ISSUE TITLE
Collection tag with multiple collections not working predictably

### ISSUE THREAD

**Issue by taylorcammack** [statamic/cms#7227]
### Bug description

I'm using a collection tag to group multiple collections, in this case, news and events. I can get them individually `from='news'` AND I can get them in a larger group `from='schools|events|news'`, but when I try just `from='events|news'`, it only renders whichever collection comes first. 

Can provide a ZIP of the repo

https://user-images.githubusercontent.com/2514935/207981755-76513ea0-2812-42b2-90d5-da578ade9966.mov

### How to reproduce

Can't reproduce in latest core.

### Environment

```yaml
Environment
Application Name: Wiley College
Laravel Version: 9.43.0
PHP Version: 8.1.11
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: wiley.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 9
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.61 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
doublethreedigital/duplicator: 2.3.4
encore/app: dev-main
goldnead/statamic-collapse-fieldtype: 1.0.4
jonassiewertsen/statamic-livewire: 2.9.0
rias/statamic-data-import: 1.2.2
simonhamp/statamic-heroicons: 1.1.0
spatie/statamic-responsive-images: 2.14.4
webographen/statamic-dynamic-token: 1.0.0
```

### Installation

Other (please explain)

### Antlers Parser

runtime (new)
