### ISSUE TITLE
Not able to save a Entry using the "Publishing date" configuration and the mode "range"

### ISSUE THREAD

**Issue by FR6** [statamic/cms#7234]
### Bug description

When trying to save en Entry having a date "range" field I get the error:
`DateTime::__construct(): Argument #1 ($datetime) must be of type string, array given...`.

The Entry gets saved when the mode is "Single" but not "Range".

Tested on 3.3.60 and 3.3.61.

### How to reproduce

- Create a Collection
- Add a date field with a mode to "range"
- Create en Entry
- Specify two dates 
- Click "Save & Publish"

It should give an error.

### Logs

```shell
local.ERROR: DateTime::__construct(): Argument #1 ($datetime) must be of type string, array given {"userId":"0bacd04f-2352-486f-8fc3-3aceb4479604","exception":"[object] (TypeError(code: 0): DateTime::__construct(): Argument #1 ($datetime) must be of type string, array given at /vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:87)
[stacktrace]
#0 /vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(87): DateTime->__construct()
#1 /vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(185): Carbon\\Carbon->__construct()
#2 /vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(216): Carbon\\Carbon::rawParse()
#3 /vendor/statamic/cms/src/Http/Controllers/CP/Collections/EntriesController.php(485): Carbon\\Carbon::parse()
#4 /vendor/statamic/cms/src/Http/Controllers/CP/Collections/EntriesController.php(366): Statamic\\Http\\Controllers\\CP\\Collections\\EntriesController->toCarbonInstanceForSaving()
#5 /vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\Collections\\EntriesController->store()
#6 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#7 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#8 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#9 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(727): Illuminate\\Routing\\Route->run()
#10 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /vendor/statamic/cms/src/Http/Middleware/DeleteTemporaryFileUploads.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DeleteTemporaryFileUploads->handle()
#13 /vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\CountUsers->handle()
#15 /vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
...
```

### Environment

```yaml
Environment
Application Name: xxx
Laravel Version: 9.41.0
PHP Version: 8.1.4
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
URL: localhost:8000
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.61 Solo

Statamic Addons
aerni/livewire-forms: 6.3.0
jonassiewertsen/statamic-live-search: 1.5.1
jonassiewertsen/statamic-livewire: 2.9.0
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)
