### ISSUE TITLE
How to duplicate a collection entry

### ISSUE THREAD

**Issue by maxi032** [statamic/cms#7237]
### Bug description

I have v3.3.61 and from what I understood the duplicate Addon is part of the core since v3.59 but I don't see the Duplicate link when I click on the 3 dots corresponding to the entry.

### How to reproduce

Make a collection and test duplication in a multisite environment.

### Environment

```yaml
Environment
Application Name: Test
Laravel Version: 9.42.2
PHP Version: 8.2.0
Composer Version: 2.4.4
Environment: production
Debug Mode: ENABLED
URL: webdev.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / daily
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.61 PRO

Statamic Addons
spatie/statamic-responsive-images: 2.14.4
withcandour/aardvark-seo: 2.0.30
```

### Installation

Existing Laravel app

### Antlers Parser

regex (default)
