### ISSUE TITLE
Fields from linked fieldsets can't be removed in event

### ISSUE THREAD

**Issue by aerni** [statamic/cms#7256]
### Bug description

You can't remove a blueprint field in an `EntryBlueprintFound` event if the field in question is part of a linked fieldset. You can remove it however if you link a single field from a fieldset.

I'm expecting `$event->blueprint->removeField($handle)` to remove fields no matter how they are imported.

### How to reproduce

Add this simple fieldset:

```yaml
title: Fieldset
fields:
  -
    handle: text
    field:
      input_type: text
      antlers: false
      display: Text
      type: text
      icon: text
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
```

Import it in a blueprint:

```yaml
title: Pages
sections:
  main:
    display: Main
    fields:
      -
        import: fieldset
```

Add this event listener:

```php
public function handle(EntryBlueprintFound $event)
{
    $event->blueprint->removeField('text');
}
```

This should remove the `text` field from the blueprint, but it doesn't.

Now link the field directly:

```yaml
title: Pages
sections:
  main:
    display: Main
    fields:
      -
        handle: text
        field: fieldset.text
```

The field will now be removed as expected.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.41.0
PHP Version: 8.1.11
Composer Version: 2.4.3
Environment: local
Debug Mode: ENABLED
URL: statamic-advanced-seo.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Version: 3.3.58 PRO

Statamic Addons
aerni/advanced-seo: dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
