### ISSUE TITLE
Cannot select asset container

### ISSUE THREAD

**Issue by zsoltjanes** [statamic/cms#7262]
### Bug description

After a fresh Statamic install I want to make a blueprint with assets and in Container I can not select existing containers.
![Screenshot_5](https://user-images.githubusercontent.com/7995436/208897450-d05f3663-a799-4873-ad4f-c7eab05ecee4.png)

### How to reproduce

Just install a new fresh Statamic site and try to make a blueprint with asset.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.45.0   
PHP Version: 8.1.0        
Composer Version: 2.5.0   
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.62 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
