### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by justkidding96** [statamic/cms#7263]
### Bug description

When trying to links a form within replicator field I get the inifinite loading screen with a 500 error: 

```{
    "message": "Trying to access array offset on value of type null",
    "exception": "ErrorException",
    "file": ".../vendor/statamic/cms/src/Http/Controllers/CP/Fieldtypes/RelationshipFieldtypeController.php",
    "line": 49,
    "trace": [
```

### How to reproduce

Create a replicator field within a collection with a form field type. Then try to select a form.

### Environment

```yaml
Environment
Application Name: *******
Laravel Version: 9.42.2
PHP Version: 8.1.0
Composer Version: 2.0.9
Environment: local
Debug Mode: ENABLED
URL: site.lcl
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: regex
Version: 3.3.62 PRO

Statamic Addons
doublethreedigital/duplicator: 2.3.4
rias/statamic-link-it: 2.2.3
statamic/seo-pro: 3.1.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
