### ISSUE TITLE
Stache isn't getting updated when changing a slug on a taxonomy when STATAMIC_STACHE_WATCHER is false.

### ISSUE THREAD

**Issue by sunscreem** [statamic/cms#7265]
### Bug description

When the STATAMIC_STACHE_WATCHER is set to false, changing a slug on a taxonomy term means you will see the "old" and "new" term in the control panel until you manually clear the stache.

### How to reproduce

Fresh install Statamic.
Set `STATAMIC_STACHE_WATCHER=false`
Create a taxonomy, and a term. 
Change the slug on the term.

The taxonomy page will now show two terms.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.45.1
PHP Version: 8.0.21
Composer Version: 2.5.0
Environment: local
Debug Mode: ENABLED
URL: temp.sunscreem.xyz.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.63 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
