### ISSUE TITLE
Page from Controller does not cached

### ISSUE THREAD

**Issue by hlorofos** [statamic/cms#7272]
### Bug description

View from Controller doesn't cached as expected in full caching mode

### How to reproduce

Enable  in .env
`STATAMIC_STATIC_CACHING_STRATEGY=full`

Add the Route
`Route::get('p/{q}', [ProductPage::class, 'index']);`

and ProductPage with 
```
    public function index()
    {
        return (new View)->template('catch_all')->with([
                'main_keyword' => str_replace('-', ' ', request()->path()),
            ]);
   }
```

navigate to yoursite.test/p/test-product and check your public/static folder.
it expected the page being cached as .html file there.
No file is observed.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.43.0
PHP Version: 8.1.13
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: cmska2.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.63 PRO

Statamic Addons
raynl/generate-slug: 1.1.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
