### ISSUE TITLE
Adding multiple field conditions to a form field doesn't work

### ISSUE THREAD

**Issue by jmartsch** [statamic/cms#7280]
### Bug description

If I add multiple conditions for a field and then click on "Finish" and then re-open the field conditions, only the last option is saved and the others are gone. I tested this behaviour with a fresh installation (blank) of Statamic 3.3.63 and in an existing site.

### How to reproduce

Create a new form.
Go to "edit form"
Go to Fields > Blueprint > Edit
add two fields
in the second field go to "Conditions" > Show when
enter multiple conditions
click on "Finish"
re-open the field and then go to "Conditions"
Your options are gone :(

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.45.1
PHP Version: 8.1.12
Composer Version: 2.4.0
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.63 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
