### ISSUE TITLE
Creation of dynamic property Statamic\Extensions\Translation\Translator::$files is deprecated

### ISSUE THREAD

**Issue by nbeerten** [statamic/cms#7282]
### Bug description

On seemingly any request a warning get's spit out, visible in monitoring tools like Laravel Telescope. The warning is about the creation of dynamic properties, deprecated in PHP 8.2.
The warning is *not* stored in any log in `storage/logs`.
Happens both in Production and Development environment, logs are from Development env.

### How to reproduce

As far as I know:
1. Use PHP 8.2
2. Make a request to the website

### Logs

```shell
Creation of dynamic property Statamic\Extensions\Translation\Translator::$files is deprecated in /var/www/vendor/statamic/cms/src/Extensions/Translation/Translator.php on line 14
```

### Environment

```yaml
Environment
Application Name: *************
Laravel Version: 9.45.1
PHP Version: 8.2.0
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: localhost 
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.63 Solo

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
statamic/eloquent-driver: 1.1.2
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)
