### ISSUE TITLE
Auto propagation on collections de-syncs fields

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7286]
### Bug description

If you have an auto propagating collection on a multisite environment with fields that have `localizable` set to `false` fields only sync on initial creation. After that the fields stop syncing and CP users are stuck with values that were initially set. 

This behaviour doesn't happen when auto propagation is disabled. It then works as intended.

### How to reproduce

1. Create a multisite with two sites at minimum.
3. Create a collection 
4. Set the collection to be available in both sites
5. Enable auto propagation
6. Add a field to the collection blueprint (don't make it localizable) 
7. Create an entry for the main site
8. Fill in the fields
9. Check the auto propagated entry for the second site
10. See the fields are locked and filled in with the origin values (good)
11. Change the fields on the main site
12. Go back to the localised entry and see the initially saved values (bad)

This behaviour doesn't happen when auto propagation is false. The values continue to updated for all other sites when they are changed on the origin entry.  This how it also work on globals for example. You often want fields to be only set in one locale and have them available on all translated versions. 

### Environment

```yaml
Environment
Application Name: Studio 1902
Laravel Version: 9.45.0
PHP Version: 8.1.13
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: 1902.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.62 PRO

Statamic Addons
jonassiewertsen/statamic-jobs: 1.1.0
jonassiewertsen/statamic-livewire: 2.9.0
studio1902/statamic-peak-commands: 1.9
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
