### ISSUE TITLE
Image uploads from website times out

### ISSUE THREAD

**Issue by ryatkins** [statamic/cms#7288]
### Bug description

When a user uploads an image from one of our forms, the image path is not properly saved to the form's yaml file.  The job times out.

File does get successfully uploaded to server and Digital Ocean spaces.

Suspecting more image generation issues.   Is there a way to disable image generation on file uploads?

Uploading images via the CMS does produce preset images.

### How to reproduce

Submit form as a job using `QUEUE_CONNECTION=redis`, upload an image.    Submitting as `QUEUE_CONNECTION=sync` works, but not via a job.   Works without the image as well.

Times out in save() method in `vendor/statamic/cms/src/Assets/Asset.php`
```
    public function save()
    {
        $withEvents = $this->withEvents;
        $this->withEvents = true;

        Facades\Asset::save($this);

        $this->clearCaches();

        if ($withEvents) {
            AssetSaved::dispatch($this);
        }

        $this->syncOriginal();

        return true;
    }
```

Removing this preset does not work either
```
        'presets' => [
            'small' => ['w' => 200, 'h' => 200, 'q' => 75, 'fit' => 'crop'],
        ],
```

### Logs

```shell
yaml

quantity: '1'
returnReason: worn-needs-refurbishment
details: details text
attachments: null
```

### Environment

```yaml
Environment
Laravel Version: 9.43.0
PHP Version: 8.1.12
Composer Version: 2.5.1
Environment: production
Debug Mode: OFF
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 5
Antlers: regex
Version: 3.3.60 PRO

Statamic Addons
aerni/imagekit: 2.2.0
doublethreedigital/duplicator: 2.3.4
jonassiewertsen/statamic-livewire: 2.9.0
statamic/seo-pro: 3.1.2
xndbogdan/statamic-bard-text-color: 2.4.1
```

### Installation

Existing Laravel app

### Antlers Parser

regex (default)
