### ISSUE TITLE
Custom CP favicon does not work

### ISSUE THREAD

**Issue by michaelmannucci** [statamic/cms#7290]
### Bug description

I've tried to replace the favicon in `cp.php`... here's what I have:

`'custom_favicon_url' => env('STATAMIC_CUSTOM_FAVICON_URL', '/assets/site/cp_favicon.png'),`

It still loads the Statamic one. I have PRO enabled. I've tried clearing cache and clearing config cache.

I do get a log error that I pasted in the _Logs_ section.

I confirmed with someone in Discord that they are experiencing the same issue.

### How to reproduce

Update the `custom_favicon_url` line in `cp.php` and open the CP

### Logs

```shell
[2023-01-03 23:20:19] development.ERROR: Found 1 error while validating the input provided for the GetObject operation:
[Key] expected string length to be >= 1, but found string length of 0
```

### Environment

```yaml
Environment
Application Name: Name
Laravel Version: 9.45.1
PHP Version: 8.1.13
Composer Version: 2.4.4
Environment: development
Debug Mode: ENABLED
URL: covenant.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.63 PRO

Statamic Addons
aryehraber/statamic-logbook: 2.1.0
eklektos/cp: dev-main
michaelmannucci/coolor: 1.0.0
michaelmannucci/shades: 1.0.0
spatie/statamic-responsive-images: 2.14.4
visuellverstehen/statamic-classify: 2.4.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
