### ISSUE TITLE
Live preview gets stuck while switching with multi site

### ISSUE THREAD

**Issue by GioChocolateBro** [statamic/cms#7300]
### Bug description

When I'm using live preview editing a page I'll get errors when I'm switching between (multi)sites. Important to note that these sites have different domain names. 

### How to reproduce

When I'm accessing the CP using domain1.com and switching to domain2.com or domain3.com there are no issues. But switching back to domain1.com It'll error give an error on some code in the UpdatesIframe.js.

When I'm accessing the CP using domain2.com I can switch to domain1.com or domain3.com but the same problem arises switching back to the site with the same domain name as what's used accessing the CP.  Inside the `UpdatesIFrame.js` I do see some code concerning if this is 'the same origin'. But it doesn't seem to catch this.

After hardcoding the variable `isSameOrigin` to false this seems fixed. Currently, it evaluates true when I switch back to the site that matches the CP URL. Logically so, if I read the code preserving the scroll state. But in this case with multi-site using different domains, there is no scroll to preserve.

![](https://media.discordapp.net/attachments/489818810157891586/1060355356552876133/image.png)

### Environment

```yaml
Environment
Application Name: TNNA
Laravel Version: 9.43.0
PHP Version: 8.1.8
Composer Version: 2.3.10
Environment: local
Debug Mode: ENABLED
URL: topnotch.ddev.site
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / daily, flare
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Version: 3.3.60 PRO

Statamic Addons
statamic/eloquent-driver: 1.1.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
