### ISSUE TITLE
Missing custom create label

### ISSUE THREAD

**Issue by aerni** [statamic/cms#7315]
### Bug description

The customized create labels as [described in the docs](https://statamic.dev/collections#labels) are not displayed in the overview when the collection doesn't have any entries yet.

<img width="962" alt="Bildschirmfoto 2023-01-06 um 12 35 14" src="https://user-images.githubusercontent.com/23167701/211066805-1f5b3215-df3b-40bd-b589-1fac556758c0.png">

<img width="1267" alt="Bildschirmfoto 2023-01-06 um 12 35 22" src="https://user-images.githubusercontent.com/23167701/211066802-ed656998-c541-4099-aa19-726c8ca0bfcd.png">

### How to reproduce

- Create a new collection
- Add a custom label for that collection
- Visit the collection route

### Environment

```yaml
Environment
Application Name: site
Laravel Version: 9.46.0
PHP Version: 8.1.13
Composer Version: 2.5.0
Environment: local
Debug Mode: ENABLED
URL: site.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 10
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.63 PRO

Statamic Addons
aerni/advanced-seo: 1.3.3
aerni/livewire-forms: 6.3.0
aerni/social-links: 3.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
