### ISSUE TITLE
unpublished entries you get from taxonomies are not filtered out

### ISSUE THREAD

**Issue by Oleafeon** [statamic/cms#7322]
### Bug description

When i connect entries to a taxonomie and unpublish a couple entries like this
![image](https://user-images.githubusercontent.com/20043831/211270465-309b2910-bcc7-4aef-b506-33d27ddec41f.png)

it wont remove the entries from the site
![image](https://user-images.githubusercontent.com/20043831/211270714-c9dc9dae-7af7-4374-93b2-a6ed68fd61e0.png)

I did this to the code
![image](https://user-images.githubusercontent.com/20043831/211270902-0fea3c06-916f-49f2-8b4a-5789beea72ee.png)

### How to reproduce

Create a taxonomie
Create a collection
Connect collection to taxonomie
Create a couple entries and taxonomies
Unpublish a couple entries in the collection
Show entries via taxonomie fieldtype

### Environment

```yaml
Environment                     
Application Name: Tracks & Trade
Laravel Version: 9.40.1         
PHP Version: 8.1.6              
Composer Version: 2.3.5         
Environment: local              
Debug Mode: ENABLED             
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 10
Antlers: runtime
Version: 3.3.58 PRO

Statamic Addons
aerni/font-awesome: 1.2.0
aryehraber/statamic-captcha: 1.9.1
ddm-studio/cookie-byte: 1.0.16
doublethreedigital/duplicator: 2.3.4
jacksleight/statamic-bard-mutator: 1.1.2
pecotamic/sitemap: 1.4.0
rias/statamic-link-it: 2.2.3
rias/statamic-redirect: 2.5.0
statamic/seo-pro: 3.1.1
xndbogdan/statamic-bard-text-color: 2.4.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

### Additional details

```
{{ archive }}
<div class="{{ if !last }}mb-20 lg:mb-40{{ /if }}">
    <div class="mb-4 grid grid-cols-1 lg:mb-7">
        <div id="{{ slug }}" class="border-1 border-normal-600 col-span-full border-b pb-4">{{ title }}</div>
    </div>
    <div class="hidden lg:grid lg:grid-cols-3 lg:gap-x-4 lg:gap-y-16">
        {{ entries sort="order" published="true" }}
        <div class="archive group relative overflow-hidden rounded-2xl">
            {{ partial:components/picture cover="true" class="relative z-0" }}
            <div class="archive__overlay"></div>
            <h3 class="archive__title">{{ title }}</h3>
            <div class="archive__content">
                <h3 class="archive__title--content">{{ title }}</h3>
                <p class="archive__text--content">lot number {{ lot_number }}</p>

                {{ if sold }}
                <div class="archive__sold">Sold</div>
                {{ else }} {{ if button }} {{ button }}
                <a href="{{ url }}" class="archive__button">{{text}}</a>
                {{ /button }} {{ /if }} {{ /if }}
            </div>
        </div>
        {{ /entries }}
    </div>
</div>
{{ /archive }}
```
