### ISSUE TITLE
Routing is broken when using `parent_uri`

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7324]
### Bug description

Collection Routing is not behaving [as expected](https://statamic.dev/collections#for-when-you-care-too-much-about-seo) when using `parent_uri` as a path segment.
 
![2023-01-09 15 57 30](https://user-images.githubusercontent.com/1102712/211339487-1c362b53-26cf-4092-9b3c-b2bd8ca7b020.gif)

### How to reproduce

The following route configuration returns `/parent.html/test.html`.

```yaml
route: /{parent_uri}/{slug}.html
```
I am expecting `/parent/test.html`.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.46.0
PHP Version: 8.1.10
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.64 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
