### ISSUE TITLE
Live Preview not compatible with `array` cache driver

### ISSUE THREAD

**Issue by jakubjo** [statamic/cms#7330]
### Bug description

The live preview is not compatible with the `array` cache driver. The error message is rather ambiguous, but makes perfect sense:

`Call to a member function repository() on null`

<img width="730" alt="image" src="https://user-images.githubusercontent.com/2873852/211547773-96fe3914-28d0-4550-90cf-5775c4fb53c4.png">

There should be an appropriate exception thrown. Something like: "Live Preview not supported using array cache driver" -- I can create a PR if desired.

I've also created a PR to add that info to the docs: https://github.com/statamic/docs/pull/977

### How to reproduce

Use array cache driver.

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 9.46.0
PHP Version: 8.1.14
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: array
Database: mysql
Logs: stack / single
Mail: postmark
Queue: sync
Session: redis

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.64 PRO

Statamic Addons
mitydigital/statamic-google-fonts: 1.0.1
spatie/statamic-responsive-images: 2.15.0
swiftmade/statamic-clear-assets: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
