### ISSUE TITLE
`$loop->last` not working when looping `Statamic::tag('collection')`

### ISSUE THREAD

**Issue by johncarter-** [statamic/cms#7331]
### Bug description

I am using Blade for my front end. I am trying to use the `$loop` variable in a foreach.

When I use `range(1,2)` the last item is correctly detected, using the `Statamic::tag` doesn't work.

```blade
@foreach (Statamic::tag('collection:articles')->param('taxonomy:categories', 'pscs')->limit(2)->sort('date:desc') as $article)
    {{-- @foreach (range(1, 2) as $article) --}} 
    @if (!$loop->last)
        <hr class="mt-6">
    @endif
@endforeach
```

### How to reproduce

Make a Blade template looping a collection using this code:
```blade
@foreach (Statamic::tag('collection:articles')->param('taxonomy:categories', 'pscs')->limit(2)->sort('date:desc') as $article)
    {{-- @foreach (range(1, 2) as $article) --}} 
    @if (!$loop->last)
        <hr class="mt-6">
    @endif
@endforeach
```

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 9.46.0
PHP Version: 8.1.12
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: dev.arweave.news.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.63 PRO

Statamic Addons
spatie/statamic-responsive-images: 2.14.4
```
```


### Installation

Other (please explain)

### Antlers Parser

None

### Additional details

_No response_
