### ISSUE TITLE
Taxonomy Value Customizations Are Sometimes Overwritten

### ISSUE THREAD

**Issue by warkior** [statamic/cms#7332]
### Bug description

I have created a taxonomy called Tags and adjusted it's blueprint to allow adding additional information to each tag. I have then created a collection called Articles and am attempting to attach tags to articles. 

In specific situations, when I link an existing tag to an article, all custom data attached to that tag is removed. The custom tag with custom data is replaced with a new empty tag.

NOTE:
I have narrowed the issue down to being caused when I type in the tag name and press Return to add it to the article, rather than typing part of the tag and then selecting it from the dropdown list of available tags.

### How to reproduce

1. Create a new Tags taxonomy.
2. Add fields to the Tags taxonomy blueprint to allow customizing additional Tag data.
3. Create a new Collection (Articles)
4. Configure Articles to allow tags to be added. (mode: select)
5. Create a custom tag with some custom data. (ie. tag: breakfast)
6. Create a new article and attach it to the custom tag with the following steps:

a. Start typing the tag name.
b. You should see the available matching tags show up in a dropdown
c. Continue typing the tag name (even though it appears in the dropdown) and press Return/Enter.
d. Save your article.

When you do this, all your custom data in the tag will be removed and it will be replaced by a default empty tag with the name you typed in.

To get around the problem:

a. Start typing the tag name.
b. See the dropdown list of matching tags.
c. Select the appropriate matching tag from the list by clicking on it.
d. Save.

When you choose the pre-existing tag by clicking it, rather than continuing to type it out, the custom data in the tag is preserved.

### Environment

```yaml
Running on my local mac Valet, however I've seen the same issue on our live server.

Environment
Application Name: Multisite Local
Laravel Version: 9.46.0
PHP Version: 8.1.13
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: 127.0.0.1:8000
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single, bugsnag
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.64 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
edalzell/forma: 1.2
silentz/akismet: 3.1.3
statamic/migrator: dev-master
statamic/seo-pro: 3.1.3
```

### Installation

Other (please explain)

### Antlers Parser

None

### Additional details

Other installation: Upgraded from statamic v2 and then installed multisite.
