### ISSUE TITLE
Static Cache not invalidating correctly

### ISSUE THREAD

**Issue by robbanl** [statamic/cms#7333]
### Bug description

When enabling full page cache, `STATAMIC_STATIC_CACHING_STRATEGY=full` the pages doesn't invalidate correctly if the cache is cleared (php artisan cache:clear).

### How to reproduce

1. Enable FPC
2. Visit some pages and make sure they stay static
3. Update an entry that is cached
4. See how the page actually changes in frontend
5. Clear the static cache and then the normal cache (php please static:clear ; sail artisan cache:clear)
6. Repeat step 2-3 above, and notice how the pages AREN'T invalidated
7. Clear cache and static (sail artisan cache:clear ; php please static:clear) (notice how I switched place on the commands)
8. Repeat step 2-3 above, and notice how the pages are invalidated

I'm guessing this is due to that we destroy the urls cache-key when clearing the cache, causing entries to stay stuck in cache.

### Environment

```yaml
Environment
Application Name: SiteName
Laravel Version: 9.43.0
PHP Version: 8.1.11
Composer Version: 2.5.1
Environment: production
Debug Mode: OFF
URL: the-client-domain.se
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: redis
Cache: redis
Database: mysql
Logs: daily
Mail: smtp
Queue: redis
Session: redis

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.3.64 PRO

Statamic Addons
aryehraber/statamic-logbook: 2.1.0
codepeak/private: 1.0.11
edalzell/forma: 1.2
jezzdk/statamic-wp-import: 1.6.0
pecotamic/sitemap: 1.4.0
rias/statamic-data-import: 1.2.2
silentz/akismet: 3.1.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
