### ISSUE TITLE
`{{ parent:title }}` not working as expected inside `{{ get_content }}`

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#7336]
### Bug description

I want to show the parent title inside a get_content tag, but it shows the parent title from the current page, instead of the title from the parent of the get_content entry.

### How to reproduce

I link from a entry to another site with `?ref={{ id }}`

On this site I generate a link like this:
```
{{ get_content :from="get:ref" }}
{{ partial src="elements/btn"  :url="url" name="Zurück: {{ parent:title }} - {{ title }}" }}
{{ /get_content }}
```
The output is the parent title from the current page, not from the parent of the get_content entry.

The parent title from the current page is possible with `{{ page:parent:title }}`, so {{ parent:title }} inside a `get_content` tag should output the parent from the get_content entry.

### Environment

```yaml
Laravel Version: 9.40.1
PHP Version: 8.0.12
Composer Version: 2.1.3
Environment: local
Debug Mode: ENABLED   
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Statamic
Addons: 2
Antlers: runtime
Version: 3.3.56 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
