### ISSUE TITLE
Publish form breaks when you have multiple nested replicator/grid fields

### ISSUE THREAD

**Issue by notnek** [statamic/cms#7342]
### Bug description

We have built a dynamic page builder using a top-level Replicator fieldtype which has some sets that include either another Replicator fieldtype or a Grid fieldtype, which may also include another nested Grid fieldtype.  Once you get to the 3rd level, a Javascript error is thrown from the StackedRow.vue component and the field doesn't render, only the label. 

Here's a screenshot, in which Nested Grid Field should have a text fieldtype available (see included blueprint):

<img width="641" alt="Screen Shot 2023-01-11 at 3 31 39 PM" src="https://user-images.githubusercontent.com/114763/211911919-74c85dc6-5d5a-40e5-8125-9e45e03d1a63.png">
<img width="514" alt="Screen Shot 2023-01-11 at 3 33 39 PM" src="https://user-images.githubusercontent.com/114763/211911929-ccbecf73-ee99-4c7b-bc98-d417867059fd.png">

### How to reproduce

Here's a blueprint that will create the attached screenshot and JS error:

```yaml
title: 'Grids with more grids'
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: replicator_field
        field:
          collapse: false
          previews: true
          sets:
            grid:
              display: Grid
              fields:
                -
                  handle: grid_field
                  field:
                    fields:
                      -
                        handle: title
                        field:
                          input_type: text
                          antlers: false
                          display: Title
                          type: text
                          icon: text
                          listable: hidden
                          instructions_position: above
                          visibility: visible
                          always_save: false
                      -
                        handle: nested_grid_field
                        field:
                          mode: stacked
                          max_rows: 1
                          min_rows: 1
                          reorderable: true
                          display: 'Nested Grid Field'
                          type: grid
                          icon: grid
                          listable: hidden
                          instructions_position: above
                          visibility: visible
                          always_save: false
                          fields:
                            -
                              handle: nested_title
                              field:
                                input_type: text
                                antlers: false
                                display: 'Nested Title'
                                type: text
                                icon: text
                                listable: hidden
                                instructions_position: above
                                visibility: visible
                                always_save: false
                    mode: stacked
                    reorderable: true
                    display: 'Grid Field'
                    type: grid
                    icon: grid
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    always_save: false
          display: 'Replicator Field'
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
```

### Environment

```yaml
Environment
Application Name: App
Laravel Version: 9.39.0
PHP Version: 8.1.8
Composer Version: 2.3.5
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: none (content api only)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.3.64 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

In our specific use case, the deepest grid field is imported via a fieldset, but it happens in either case.
