### ISSUE TITLE
FieldType picker not loading

### ISSUE THREAD

**Issue by codrin-axinte** [statamic/cms#7346]
### Bug description

Hello, I have this issue when I open the FieldType modal it never loads and throws this exception. This happens on a fresh Statamic installation using the statamic-cli. It happens 90% of the time, after I refresh the website a few times it loads the modal 1-2 times and then again throws error. Here is a [link to a recording](https://discord.com/channels/489818810157891584/489819906540568593/1063047068412813418)

![image](https://user-images.githubusercontent.com/6564791/212056697-793177f5-0213-4c6c-a9f5-595294655403.png)

And it also has another weird issue. Whenever I delete something (it can be an entry or global set or whateverr) the modal doesn't close upon completion, even tho the action was successful.

### How to reproduce

1. Install a new statamic app using the statamic-cli.
2. Create a new Collection and edit the blueprint
3. Click on the Create FieldType.
4. Observe issue.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.47.0
PHP Version: 8.1.13
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.64 PRO

Statamic Addons
spatie/statamic-health: 1.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
