### ISSUE TITLE
Runtime Parser: UrlBuilder uses incorrect scope when building routes

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7347]
### Bug description

Collection Routes with Antlers variables do not behave like the Regex parser when using the runtime parser. When a Antlers variable is used in the route definition that is not present in the context of [$this->routeData()](https://github.com/statamic/cms/blob/3.3/src/Routing/UrlBuilder.php#L53), variables from the global context are being used instead. This leads to wrong routes.

### How to reproduce

Here you can find a reproduction repo: https://github.com/o1y/statamic-runtime-routing-bug or follow these steps:

1. Use the following `pages.yaml` collection config:

```yaml
title: Pages
template: default
layout: layout
revisions: false
route: '/{{slug}}{{ if deprecated == "true" }}-old{{ /if }}'
sort_dir: asc
preview_targets:
  -
    label: Entry
    url: '{permalink}'
structure:
  root: true
  slugs: true
```
3. Add a `deprecated` field to your pages.yaml Blueprint, e.g.
```yaml
  -
  handle: deprecated
  field:
    default: false
    display: Deprecated
    type: toggle
    icon: toggle
    listable: hidden
    instructions_position: above
    visibility: visible
    always_save: false
```
5. Add a Home Site and two Pages "Deprecated" and "Not Deprecated". Make sure to enable the "Deprecated" Setting on the first one. Remove any `deprecated: false` values from `not-deprecated.md` and `home.md`.

6. Add a navigation with handle `test` which contains all previous pages. Add the following nav to your `layout.antlers.yaml`:
```antlers
{{ nav:test }}
     <a href="{{ url }}">{{ title }} -> {{ url }}</a>
{{ /nav:test }}
```

### Result
On the home site the following _correct_ navigation is rendered:
```
Home -> /
Deprecated -> /deprecated-old
Not deprecated -> /not-deprecated
```

On the deprecated site the following _wrong_ navigation is rendered:
```
Home -> /-old
Deprecated -> /deprecated-old
Not deprecated -> /not-deprecated-old
```

I'm expecting on all pages the same navigation. When using `regex` Parser there are no issues.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.46.0
PHP Version: 8.1.10
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.64 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
