### ISSUE TITLE
Model accessors do not work without appending in Antlers

### ISSUE THREAD

**Issue by royvanv** [statamic/cms#7356]
### Bug description

[Accessors on models](https://laravel.com/docs/9.x/eloquent-mutators#defining-an-accessor) do not work in Antlers without being appended (either add it to `$appends` in the model or call the `append` method on the model instance)

## 1. Define additional attributes

Add the following to a model (e.g. `App\Models\User`):

```php
    protected $appends = [
        'favorite_color',
    ];

    public function favoriteColor(): Attribute
    {
        return Attribute::make(
            get: fn() => 'Black',
        );
    }

    public function favoriteBand(): Attribute
    {
        return Attribute::make(
            get: fn() => 'Nickelback',
        );
    }

    public function getFavoriteIceCreamFlavorAttribute(): string {
        return 'Vanilla';
    }

    public function getFavoriteCarBrandAttribute(): string {
        return 'Tesla';
    }
```

## 2. Create a new controller

For example `App\Http\Controllers\FavoriteController`:

```php
<?php

namespace App\Http\Controllers;

use App\Models\User;

class FavoriteController extends Controller
{
    public function __invoke()
    {
        $user = User::first()->append('favorite_ice_cream_flavor');

        return view('favorite.index', ['user' => $user]);
    }
}
```

## 3. Create a view

Create a new view (e.g. `resources/views/favorites/index.antlers.html`):

```antlers
Color: {{ user.favorite_color }}<br>
Band: {{ user.favorite_band }}<br>
Ice cream flavor: {{ user.favorite_ice_cream_flavor }}<br>
Car brand: {{ user.favorite_car_brand }}
```

## 4. Define a route

E.g. `favorites`.

```php
Route::get('favorites', FavoriteController::class);
```

## 5. View the output

Go the route (e.g. `/favorites`).

```html
Color: Black
Band:
Ice cream flavor: Vanilla
Car brand:
```
Band and car brand are missing here.

### Environment

```yaml
Application Name: Statamic
Laravel Version: 9.47.0
PHP Version: 8.1.4
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: sandbox.statamic.local
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.64 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

This works in Blade. Of course the template should be renamed and replaced with the following content:
```blade
Color: {{ $user->favorite_color }}<br>
Band: {{ $user->favorite_band }}<br>
Ice cream flavor: {{ $user->favorite_ice_cream_flavor }}<br>
Car brand: {{ $user->favorite_car_brand }}
```
