### ISSUE TITLE
Runtime Parser: Using the runtime parser for Static Site generation results in decreased performance

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7360]
### Bug description

Enabling the `runtime` parser significantly increases the time required for static site generation with each page being generated. For sites with many entries and more complex templates, the rendering for all entries can take several hours to complete.

Since this is an issue related to the `runtime` Parser and not related to the [ssg](https://github.com/statamic/ssg) code, I'm creating the bug report in this repo. Hope this is okay :)

### `ssg` with `runtime` Parser:
```
php please ssg:generate
[✔] Gathered content to be generated
Generating 3001 content files...
[1] Generate /fr/90fc2d83-2314-4e07-9ab7-bc662afc6fdc    (71ms)
[2] Generate /it/a4669cf3-d1ef-4e31-be7d-23f39a3fd63b    (39ms)
[3] Generate /pt/e14d12cc-62c4-4b41-a825-b7d70508d3ee    (37ms)
[4] Generate /12859be1-0053-4d84-92bc-b929cd67276b    (36ms)
[5] Generate /pt/c4cd2123-454c-40ac-ad1f-b7d2b745642c    (42ms)
[6] Generate /de/729ba0b0-6c22-4a57-9444-8b43b84da116    (41ms)
[7] Generate /b3f2627c-abd9-49ba-a584-1fe2733fc3f8    (40ms)
[8] Generate /pt/481877d0-ac0d-4123-a4f8-c90642110b44    (42ms)
[9] Generate /de/27d38cfc-df4d-4842-a29c-85daf7dbf47c    (40ms)
[10] Generate /pt/de11555f-4ac5-4948-a29a-e82f27a4fe1c    (38ms)
[11] Generate /de/3cb99a2a-b6b2-4379-ae73-6728352b175e    (40ms)
...
[2432] Generate /ar/5289b604-f67e-4ef9-83cc-d35ecc88938e    (224ms)
[2433] Generate /3c15938a-fcda-4364-b852-d2c5d8abac58    (222ms)
[2434] Generate /de/5c98565c-9f60-4d19-8213-0a73568478f3    (339ms)
[2435] Generate /1abaa4cd-cd89-4af4-a184-a30f0a213d87    (222ms)
[2436] Generate /fr/65bf8dfd-4c3d-4122-a83b-20ae7a47b433    (332ms)
```

* Here you can see that the renderings for the first few pages are okay (~40ms).
* Rendering time increases the more pages being generated. I stopped the command because it took so long :)

These times are only examples. In my project with real content and more complex templates, a single page can take a few minutes to render.

### `ssg` with `regex` Parser:

```
php please ssg:generate
[✔] Gathered content to be generated
Generating 3001 content files...
[1] Generate /ar/13387981-9ea7-40f2-ba5c-a9166550f63a    (71ms)
[2] Generate /fr/51358a6c-6f67-48c3-a532-f06679e2f461    (41ms)
[3] Generate /it/f27de003-3774-461a-8161-86dcd7d05356    (40ms)
[4] Generate /ar/a361cf01-f3a7-45dd-ab72-1798e5955ecc    (41ms)
[5] Generate /de/be8f8011-f743-4845-82af-b4032d1164fd    (43ms)
[6] Generate /de/37f6be3e-9df4-4274-98ce-7fee87e41511    (41ms)
[7] Generate /ar/f306c9a9-1c5f-4b14-8102-bc0ab0b83dd6    (43ms)
[8] Generate /624d75d0-4b6e-45d0-8806-bcdc0e32b7e8    (39ms)
[9] Generate /de/d6a3c943-a7b9-452c-9967-b9189af0e8e4    (41ms)
[10] Generate /c19d513c-e593-4fb0-bf07-a0ffbf253a49    (39ms)
[11] Generate /de/f6796bdb-71a2-489f-9da0-5460c13e5d3f    (41ms)
[12] Generate /fr/a73e35ab-c77f-4eb4-8093-ae7b0e46ef5b    (40ms)
[13] Generate /d694885f-31a3-4bf7-bd68-2309f0eb4d1a    (38ms)
[14] Generate /fr/2727aae0-5da1-434e-8d7c-1173f6b94fae    (39ms)
[15] Generate /ar/c2a3ba38-ff11-4b33-81f3-2eada678bed0    (38ms)
...
[2997] Generate /ar/aed0857b-6f26-4733-a584-5436081e1327    (43ms)
[2998] Generate /pt/7a8432b1-4e47-48db-a7a1-8159f5785bd5    (45ms)
[2999] Generate /abc18742-9db6-4873-b31e-1a9f3b89e0be    (43ms)
[3000] Generate /it/8be5059b-7d81-4f06-9c4a-262560add8b3    (45ms)
```
* Always around ~43ms

### Reproduction Repo

I have created a reproduction repo with the following content:
* Added `statamic/ssg` package.
* Enabled Multi-Site with six locales.
* Added 500 dummy entries per locale.
* Enabled `runtime` Parser.
* Added a patch from @tao for `statamic/ssg` to see the time each page takes during the `php please ssg:generate` command.

Repo: https://github.com/o1y/statamic-runtime-memory-issue

### Environment

```yaml
Application Name: Statamic
Laravel Version: 9.47.0
PHP Version: 8.2.0
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.64 PRO

Statamic Addons
statamic/ssg: 1.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
