### ISSUE TITLE
Option fields blank in submission emails if labels aren't set

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#7364]
### Bug description

If you add an option based field (select, radio etc.) to a form and don't set the labels (which are optional), the submission email will show the fields as blank. The values are included in the form HTML correctly and saved to the submission yaml, so this just appears to be an issue with the default email template not falling back to the `key` if no `label` is set.

### How to reproduce

Use the blueprint below to create a new form, complete the form and set the field, send a submission email. The email will render like this with a blank value:

```
Select Field:
```

```yaml
sections:
  main:
    display: Main
    fields:
      -
        handle: select_field
        field:
          options:
            One: null
            Two: null
          multiple: false
          clearable: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          display: 'Select Field'
          type: select
          icon: select
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
```

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.64 Solo
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
