### ISSUE TITLE
Configure Asset Containers doesn't assign all permissions

### ISSUE THREAD

**Issue by Rovaski** [statamic/cms#7382]
### Bug description

A non-super user with the Configure Asset Containers permission tried to upload an image to an asset container. Was greeted with a 'Action not authorized' error. 

As per the Configure Asset Containers description, I expected it to grant all permissions for assets. 

### How to reproduce

Have a user with just the "configure asset containers" permission checked. (Can't be super-user obviously.)
Try to upload an image to a container. 

### Environment

```yaml
Environment
Application Name: COM:Rebirth
Laravel Version: 9.24.0
PHP Version: 8.1.14
Composer Version: 1.10.26
Environment: local
Debug Mode: ENABLED
URL: staging.thechroniclesofman.com
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Version: 3.3.65 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
