### ISSUE TITLE
Runtime Antlers doesn't handle multiple entries with the same `id`

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#7389]
### Bug description

If you have a collection of entries with the same id, but set different supplements on them, the supplements are not displayed properly.

### How to reproduce

1. `git clone https://github.com/edalzell/antlers`
2. `composer install`
3. `php artisan key:generate`
4. Visit the homepage

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.48.0
PHP Version: 8.1.14
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: antlers.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.65 Solo
```
```


### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

_No response_
