### ISSUE TITLE
Setting a user password as super admin

### ISSUE THREAD

**Issue by ksullivanlw** [statamic/cms#7395]
### Bug description

I noticed a change in behavior when changing user passwords in the control panel.  In the past when using the control panel as a Super Admin I was able to choose a user and click "change password".

Previous Behavior: It asked for a password and a confirmation.
New Behavior: It is asking for the current password first and then a new password and a confirmation.

The issue with this is as a super admin, I would quickly create a password without having to send reset links.  Is this change intended or is there a reason behind it?  As change password isn't very beneficial if I have to enter the current users password which I don't know for good reason.

### How to reproduce

Login to control panel
Create additional User
Go to that users profile 
Click Change Password

### Environment

```yaml
Application Name
Laravel Version: 9.34.0
PHP Version: 8.1.13
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: lwb2023.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.65 PRO

Statamic Addons
transformstudios/events: 4.0.7
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
