### ISSUE TITLE
Replicator sets disappear when saved

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#7400]
### Bug description

We have replicators in a bard set and whenever we add a new replicator set and save (cmd-s), the newly added set IS saved but disappears on screen. If you reload the page it's there.

### How to reproduce

I have a private site I can share that shows the issue, please reach out for the link.

1. Login (Erin@silentz.co/password)
2. Go to Home page
3. Add a Jumbotron 1 set to the only Bard set
4. Cmd-s
5. Note the newly added set disappears.

### Logs

Browser console errors:
<img width="567" alt="CleanShot 2023-01-23 at 15 37 42@2x" src="https://user-images.githubusercontent.com/6069653/214176500-34b4ee01-3e30-458f-a67c-c17e8fb0800f.png">

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.48.0
PHP Version: 8.2.1
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: broken.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / daily, front
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 16
Antlers: runtime
Stache Watcher: Enabled
Static Caching: half
Version: 3.3.65 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
doublethreedigital/duplicator: 2.3.4
edalzell/forma: 1.2
jacksleight/statamic-bard-mutator: 1.1.3
jacksleight/statamic-bard-texstyle: 1.0.3
jonassiewertsen/statamic-livewire: 2.9.0
statamic/seo-pro: 3.1.3
swiftmade/statamic-clear-assets: 1.1.0
transformstudios/events: 4.1.1
transformstudios/front: 1.11.0
transformstudios/gated: dev-main
transformstudios/github: dev-main
transformstudios/magic-link: dev-main
transformstudios/review: 3.7.2
transformstudios/simple: 2.21.3
transformstudios/takeover-redirects: dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

Happens in Safari and Firefox.

Video: 

https://user-images.githubusercontent.com/6069653/214178269-1e69860c-c913-4e62-b9bf-8372a4e9dc41.mp4
