### ISSUE TITLE
Long loading times (>= 20 seconds) 

### ISSUE THREAD

**Issue by jurnskie** [statamic/cms#7401]
### Bug description

After adding al the content (100+ collection items) for a new website in Statamic(3.3.64) i'm experiencing very long loading times.  I'm able to reproduce it in 3 seperate environements with different php versions (8.1,8.2). I've also tried it in a production environment with similar results.

From the looks of it it is mostly on pages with lots of html/content, and only on first load.

As a starter kit i'm using Statamic Peak.

I tried the following to resolve the issue: 

- enabling stache (full & half)
- disabling my css/javascript (no results)
- disabling debugbar
- disabled file watcher

### How to reproduce

1. Go to a blog item for example: https://hwoh.jurnspijksma.nl/12-meridianen-van-het-lichaam 

Video of bug:https://youtu.be/6DXKTMlLrT4

### Environment

```yaml
Environment
Application Name: holisticwayofhealing
Laravel Version: 9.48.0
PHP Version: 8.2.1
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: holisticwayofhealing.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.3.64 Solo

Statamic Addons
jonassiewertsen/statamic-livewire: 2.9.0
xndbogdan/statamic-bard-text-color: 2.4.1
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
