### ISSUE TITLE
Asset field using container without alt field shows 'Set Alt' button

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7406]
### Bug description

When you use an asset field and set it to a container where the blueprint doesn't contain an alt field, for example with icon containers, the asset field still shows the `Set Alt` button:

<img width="394" alt="Screenshot 2023-01-26 at 10 52 05" src="https://user-images.githubusercontent.com/69107412/214806778-b010c40d-4d73-4262-b9b2-d997a41cd756.png">

### How to reproduce

1. Remove the alt field from an asset containers' blueprint.
2. Use an asset field pointed to that container.
3. See the Set Alt button.

### Environment

```yaml
Environment
Application Name: Corus Advies
Laravel Version: 9.48.0
PHP Version: 8.1.13
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: corusadvies.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.65 PRO

Statamic Addons
edalzell/forma: 1.2
jonassiewertsen/statamic-livewire: 2.9.0
silentz/mailchimp: 2.9.1
studio1902/statamic-peak-commands: 1.15
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
