### ISSUE TITLE
[Error] Undefined array key "en" in FileCacher:155 when invalidating static cache of 2nd site with path /en

### ISSUE THREAD

**Issue by jlmmns** [statamic/cms#7411]
### Bug description

I have a Multi-Site configuration running with Full Static Caching.
But the invalidation rules don't seem to work for my 2nd site.
Only the 1st site gets invalidated when saving an entry.

It might have to do with the path `/en` of the 2nd site. (#7403)

Error in the logs:
```
[2023-01-26 20:54:27] production.ERROR: Undefined array key "en" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"en\" at /home/forge/site/vendor/statamic/cms/src/StaticCaching/Cachers/FileCacher.php:155
```

### How to reproduce

`/config/statamic/sites.php`
```
'sites' => [

    'nl' => [
        'name' => "Nederlands",
        'locale' => 'nl_BE',
        'url' => env('APP_URL'),
    ],

    'en' => [
        'name' => "English",
        'locale' => 'en_US',
        'url' => env('APP_URL') . '/en',
    ],

],
```

`/config/statamic/static_caching.php`
```
'invalidation' => [

    'class' => null,

    'rules' => [
        'collections' => [
            'news' => [
                'urls' => [
                    '/nieuws',    // works
                    '/nieuws/*',  // works
                    '/en/news',   // not working
                    '/en/news/*', // not working
                    '/news',      // not working
                    '/news/*'     // not working
                ]
            ],
            ...
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.45.1
PHP Version: 8.1.10
Composer Version: 2.5.1
Environment: production
Debug Mode: OFF
URL: example.com
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Disabled
Static Caching: full
Version: 3.3.63 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
