### ISSUE TITLE
Linking popup not having focus on search field

### ISSUE THREAD

**Issue by mscruse** [statamic/cms#7413]
### Bug description

When in a bard field and linking to either an asset or another entry the popup that appears does not set the focus on the search field so you can start typing - you need to click into the search field.

<img width="1650" alt="Screenshot_2023-01-27_at_13 11 18" src="https://user-images.githubusercontent.com/22737928/215015936-1bfc1367-66dc-4257-9740-c6a1299200b1.png">

### How to reproduce

In a bard field click the link button - select either entry or asset. Note in the popup to find your entry or asset the search field does not have focus, you need to click into it then start typing.

### Environment

```yaml
Environment
Application Name: Pool Spa Life
Laravel Version: 9.48.0
PHP Version: 8.1.14
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: poolspalife.com.au.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.65 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
mitydigital/feedamic: 2.2.3
mitydigital/iconamic: 1.1.2
mitydigital/sitemapamic: 2.3.5
mitydigital/statamic-google-fonts: 1.0.1
rias/statamic-data-import: 1.2.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
