### ISSUE TITLE
Live preview include cp if entry is not saved

### ISSUE THREAD

**Issue by rabol** [statamic/cms#7415]
### Bug description

When you try to preview a page before it's saved the first time, then CP is embedded in the preview

### How to reproduce

open CP, create a new page and press 'live preview' before saving the page

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.48.0
PHP Version: 8.1.14
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: clean.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.66 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
