### ISSUE TITLE
Breaking change: tags in tags doesn't work anymore

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#7419]
### Bug description

If you have a tag in an antlers tag `{{ {some:tag} | dump }}`, you get an error:

![image](https://user-images.githubusercontent.com/6069653/215224224-a41f6b0c-0ea8-4d6d-a2f8-047389d931c7.png)

@JohnathonKoster says it's the new dynamic feature.

To work around it do `{{ ; {some:tag} | dump }}` (spaces important)

### How to reproduce

1. make a tag that returns a value
2. use a modifier on it

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.48.0
PHP Version: 8.2.1
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: zakat.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 19
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.3.66 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
aryehraber/statamic-impersonator: 2.4.1
doublethreedigital/duplicator: 2.3.4
doublethreedigital/runway: 2.6.4
edalzell/forma: 1.2
jacksleight/statamic-bard-mutator: 1.1.3
jacksleight/statamic-bard-texstyle: 1.0.3
jonassiewertsen/statamic-livewire: 2.9.0
statamic/seo-pro: 3.1.3
swiftmade/statamic-clear-assets: 1.1.0
transformstudios/events: 4.1.1
transformstudios/front: 1.11.0
transformstudios/gated: dev-main
transformstudios/github: dev-main
transformstudios/magic-link: dev-main
transformstudios/memorial: dev-staging
transformstudios/review: 3.7.2
transformstudios/simple: 2.21.3
transformstudios/takeover-redirects: dev-main
```
```


### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

_No response_
