### ISSUE TITLE
Bard v1 -> v2 snake_case to camelCase issue for content files?

### ISSUE THREAD

**Issue by davebarrau** [statamic/cms#7421]
### Bug description

After upgrading to Statamic 3.4, some pages were broken ("Invalid content" when attempting to edit the page). SSG also failed to render these correctly.

After investigating, the cause seems to be the use of camelCase instead of snake_case for certain YAML properties in Bard?

This doesn't work:

```
content:
  -
    type: table
    content:
      -
        type: table_row
        content:
          -
            type: table_cell
            attrs:
              colspan: 1
              rowspan: 1
              colwidth: null
              background: null
            content:
<snip>
```

After replacing `table_row` with `tableRow` and `table_cell` with `tableCell`, the page was able to render.

### How to reproduce

Save a table in a Bard field in Statamic 3.3, then try to edit the table in Statamic 3.4.

### Environment

```yaml
Environment
Laravel Version: 9.48.0
PHP Version: 8.2.1
Composer Version: 2.5.1
Environment: local
Debug Mode: OFF
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.0 PRO

Statamic Addons
goldnead/statamic-toc: 1.3.1
simonhamp/statamic-heroicons: 1.1.0
statamic/ssg: 1.3.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

My workaround (on MacOS at least) was:

```sh
find content -name '*.md' -exec echo sed -i \'\' \'s/table_row/tableRow/g\' {} \;|/bin/sh
find content -name '*.md' -exec echo sed -i \'\' \'s/table_cell/tableCell/g\' {} \;|/bin/sh
find content -name '*.md' -exec echo sed -i \'\' \'s/bullet_list/bulletList/g\' {} \;|/bin/sh
find content -name '*.md' -exec echo sed -i \'\' \'s/list_item/listItem/g\' {} \;|/bin/sh
find content -name '*.md' -exec echo sed -i \'\' \'s/hard_break/hardBreak/g\' {} \;|/bin/sh
```

**Comment by robdekort** [comment]
Ah yeah, I just ran into this as well using lists. Had to manually update my content as follows in my case (get it?):

`list_item` -> `listItem`
`ordered_list` -> `orderedList`
`unordered_list` -> `unorderedList`

**Comment by robdekort** [comment]
I took the liberty to wield some of my red label powers here.

**Comment by jonassiewertsen** [comment]
As a reference, why this is kind of expected:
https://github.com/statamic/cms/pull/6043#pullrequestreview-992083202

Aliases have not been allowed by TipTap https://github.com/ueberdosis/tiptap/discussions/2839, even if there seems a high interest in it.

**Comment by Rusya13** [comment]
After renaming **code_block** to **codeBlock** I got an error in CP:
```
vue.common.prod.js:6 TypeError: Cannot read properties of undefined (reading 'localsInner')
    at Be.locals (index.js:3956:42)
    at index.js:1890:23
    at st.updateChildren (index.js:1253:9)
    at new st (index.js:1158:18)
    at at (index.js:1385:12)
    at on.updateStateInner (index.js:5035:36)
    at on.updateState (index.js:4986:14)
    at st.createView (tiptap-core.esm.js:3505:19)
    at new ge (tiptap-core.esm.js:3337:14)
    at new st (tiptap-vue-2.esm.js:56:9)
```

**Comment by MrMooky** [comment]
Just ran into this as well.

<img width="417" alt="Screenshot 2023-01-29 at 20 53 17" src="https://user-images.githubusercontent.com/3603346/215352364-5de36306-9c7a-4015-9c6d-ea0f16af8b9e.png">

**Comment by davebarrau** [comment]
Thanks for fixing that so quickly, @jasonvarga! 🙇

**Comment by MrMooky** [comment]
Not sure if I'm missing something, but re-saving does not solve it for me. In some cases it even removed the content! I re-saved the entry, refreshed the CP and the content was gone completely. Fortunately, this happened locally but wow, this is really bad. 😨 I can't be the only one experiencing this huge problem after upgrading.

I followed the [upgrade guide](https://statamic.dev/upgrade-guide/3-3-to-3-4) and don't know where to go next. I'm really afraid to "try" this live, as the client has 17 collections with lots of entries.

**Comment by jasonvarga** [comment]
Go ahead and open a support request giving us access to your site and we'll see what's up. Maybe it's something specific to your project. I haven't really heard of anyone else with this issue since releasing this PR.

**Comment by jasonvarga** [comment]
Actually, the text align addon you used would add stuff to the prosemirror schema. Since you removed it, when you load the content into the Bard field, it doesn't know what to do with it, which is why you get the error.

If Bard can't read the content, then you save it, that explains why it saves nothing.

You'll need to keep that addon installed, or convert to the built in alignment feature.

```yaml
-
  type: paragraph
  attrs:
    textAlign: justify
```

If you search for `textAlign` throughout `md` files, are there a lot of them?
