### ISSUE TITLE
Stache Performance: Slow page response time with growing collection size

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7424]
### Bug description

As the number of entries in a Statamic collection increases, page response time using the `Stache` driver degrades, resulting in longer build times with `statamic/ssg` and a poor user experience for pages that cannot be served with full or half-measure cache.

## Reproduction Repository
https://github.com/o1y/statamic-stache-performance

I've created a reproduction repo with the following additions:
 
* Added a seeder to seed `pages` collection.
  * Added 5000 dummy entries.
  * You can also use the seeder with `php please db:seed`. Adjust the number of entries to be generated in `database/seeders/DatabaseSeeder.php`
* Added `statamic/ssg` and a patch to output build time per generated site. You can measure the response time directly in the Browser. For a better reproduction I'm using `php please ssg:generate`.

_Environment:_
```bash
STATAMIC_STACHE_WATCHER=false
STATAMIC_STATIC_CACHING_STRATEGY=null
DEBUGBAR_ENABLED=false
```

## Results
Most of the following results are from a MacBook Pro M1 with 10 CPU Cores, 16GB RAM, Laravel Valet and `php artisan serve`. This hardware is very fast compared to regular servers, like a Digital Ocean Droplet. The results are therefore much worse in reality.

### ~10 entries
* Browser Response time: ~45ms
* `ssg:generate`: ~5ms per file:
```
[7] Generate /3d32a6ca-7e20-49f5-82ed-373bd9f2ca86    (4ms)
[8] Generate /1f05ef51-ac5d-4496-8b3d-71977d77fec4    (4ms)
[9] Generate /dbe77740-1413-4b2b-a623-151ec4aa66dc    (5ms)
[10] Generate /353b2108-9fea-4b75-a417-7638313c8fc2    (5ms)
```

### ~100 entries
* Browser Response time: ~60ms
* `ssg:generate`: ~10ms per file:
```
[51] Generate /04e73b27-fa2b-4589-adbb-47338a6dfc00    (8ms)
[52] Generate /e9ae3a72-16b3-47c6-ac48-597176f680e3    (7ms)
[53] Generate /e6133b4e-2873-43ac-869f-ce14f037836a    (9ms)
[54] Generate /d5e74f0c-c9fc-4757-9643-e705f40f71d1    (8ms)
```

### ~1000 entries
* Browser Response time: ~900ms 🐌🐌 
* `ssg:generate`: ~50ms per file:
```
[20] Generate /ac23511c-2e3b-40b0-aec3-7bb2d2d862c4    (50ms)
[21] Generate /b926683e-39d0-4efd-99bd-793e16533f0e    (46ms)
[22] Generate /bfbe4938-c54b-48c3-9c73-5e3d82f475ec    (48ms)
[23] Generate /76d711ae-3d72-46a1-a280-b6125b764d94    (48ms)
```

### ~5000 entries
* Browser Response time: ~1410ms 🐌🐌🐌
* `ssg:generate`: ~300ms per file.
```
[662] Generate /08a2f4b6-1189-452a-8169-b9a6bef3ec7e    (299ms)
[663] Generate /ccfb9613-815a-4919-8dd8-5f8e611a0c76    (294ms)
[664] Generate /d4187263-ae11-4c48-bee7-601c60caa8d3    (301ms)
[665] Generate /78fbdcff-0dcb-4ef6-983d-37ef48efac32    (309ms)
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.48.0
PHP Version: 8.2.1
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: statamic-ssg-performance.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.4.0 Solo

Statamic Addons
statamic/ssg: 1.3.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
