### ISSUE TITLE
Terms within a scoped collection don't augment

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7426]
### Bug description

When you're looping a bunch of entries from a collection with attached terms, the terms don't augment when you scope the collection.

**This works**
```antlers
{{ posts }}
    <li>{{ title }}: {{ tags }}{{ title }} {{ /tags }}</li>
{{ /posts }}
```

**This doesn't work**
```antlers
{{ posts scope="post" }}
    <li>{{ post:title }}: {{ post:tags }}{{ title }} {{ /post:tags }}</li>
    {{ post:tags | dump }}
{{ /posts }}
```

You can see the difference in output here:
<img width="1345" alt="Screenshot 2023-01-30 at 11 06 11" src="https://user-images.githubusercontent.com/69107412/215447786-fbe2a3d1-1e79-402c-abbe-39db2c2b0a17.png">

This what you get when you dump the tags:
<img width="1394" alt="Screenshot 2023-01-30 at 11 06 30" src="https://user-images.githubusercontent.com/69107412/215447842-1b35ad44-8f5b-46c3-8f90-feeae818983d.png">

### How to reproduce

1. Download this Statamic install: [test.zip](https://github.com/statamic/cms/files/10534645/test.zip)
2. Run `composer install`
3. Visit the homepage
4. Check `default.antlers.html` 

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.48.0
PHP Version: 8.1.13
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
