### ISSUE TITLE
Bards Section Three Dots Dropdown

### ISSUE THREAD

**Issue by StephenThink** [statamic/cms#7427]
### Bug description

![Screenshot 2023-01-30 at 10 38 22](https://user-images.githubusercontent.com/86749311/215457167-f616fb4e-c739-42b3-ac79-f736014c3613.png)

By clicking on the three dots button, the button rotated.  But no dropdown menu, however opening in Inspector it appears.

![Screenshot 2023-01-30 at 10 38 37](https://user-images.githubusercontent.com/86749311/215457354-5746ff05-92d4-4a48-86c2-fdb35e953e94.png)

There was also a closing issue with it flickering.

![CleanShot_2023-01-30_at_10 44 23](https://user-images.githubusercontent.com/86749311/215457578-b1d352b1-060f-4709-8c10-e3d0a93adf9d.gif)

### How to reproduce

Create a Bard, with a section.

Then in the page, add a section and just click on the three dots.  I found this out when I tried to delete a section I didn't need.s

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.48.0
PHP Version: 8.1.14
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: thinktemplate.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.0 PRO

Statamic Addons
takepart-media/statamic-oreos: 1.3.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
