### ISSUE TITLE
Class "Vite" not found (View: /var/www/html/vendor/statamic/cms/resources/views/partials/scripts.blade.php)

### ISSUE THREAD

**Issue by johncarter-** [statamic/cms#7428]
### Bug description

I'm trying to use Vite in the CP. I followed the instructions here: https://github.com/statamic/cms/pull/6869

When I load the CP after doing so, I get the following exception. https://flareapp.io/share/bP98Dz8m#F80

`Class "Vite" not found (View: /var/www/html/vendor/statamic/cms/resources/views/partials/scripts.blade.php)`

### How to reproduce

- Install Statamic 3.3.
- Follow instructions for Vite CP assets, https://github.com/statamic/cms/pull/6869
- `npm run dev`
- Load CP.

### Environment

```yaml
Environment
Application Name: Arweave News
Laravel Version: 9.48.0
PHP Version: 8.1.14
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: dev.arweave.news.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.3.66 PRO

Statamic Addons
spatie/statamic-responsive-images: 2.15.2
```
```


### Installation

Existing Laravel app

### Antlers Parser

None

### Additional details

_No response_
