### ISSUE TITLE
Missing asset attribute throws error, frequently

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#7437]
### Bug description

We get this error regularly (like every 15 mins) on only one of our sites. Is is always the same missing data but always a different request url.

Happy to pay to figure out why this happens or how to resolve.

### How to reproduce

Sorry, no clue.

### Logs

```shell
Request URL: https://centertix.com/img/asset/cHVibGljL2V2ZW50cy0yMi9hY3MtMjIyMy1jaHJpc3RtYXMtMTI4MC52Mi5qcGc=?p=seo_pro_og&s=080d9ca103f87196984ce7ea4317e33b
Request data: {"p":"seo_pro_og","s":"080d9ca103f87196984ce7ea4317e33b"}
Unable to delete file located at: cache://containers/public/assets/2022/02/alaskapac-building.jpg/9db90dcd2209764bc01967284a2d0588.jpg.

/home/forge/alaskapac.org/vendor/league/flysystem/src/UnableToDeleteFile.php (24)
/home/forge/alaskapac.org/vendor/league/flysystem/src/MountManager.php (187)
/home/forge/alaskapac.org/vendor/statamic/cms/src/Imaging/Attributes.php (29)
/home/forge/alaskapac.org/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php (338)
/home/forge/alaskapac.org/vendor/statamic/cms/src/Tags/Glide.php (138)
{"function":"Statamic\Tags\{closure}","class":"Statamic\Tags\Glide","type":"->"}
/home/forge/alaskapac.org/vendor/laravel/framework/src/Illuminate/Collections/Arr.php (560)
/home/forge/alaskapac.org/vendor/laravel/framework/src/Illuminate/Collections/Collection.php (739)
/home/forge/alaskapac.org/vendor/statamic/cms/src/Tags/Glide.php (147)
{"function":"generate","class":"Statamic\Tags\Glide","type":"->"}
```

### Environment

```yaml
Environment
Application Name: Alaska PAC
Laravel Version: 9.48.0
PHP Version: 8.2.1
Composer Version: 2.5.1
Environment: production
Debug Mode: ENABLED
URL: alaskapac.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / daily, front
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 17
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.65 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
doublethreedigital/duplicator: 2.3.4
edalzell/forma: 1.2
jacksleight/statamic-bard-mutator: 1.1.3
jacksleight/statamic-bard-texstyle: 1.0.3
jonassiewertsen/statamic-external-link: 1.6.0
jonassiewertsen/statamic-livewire: 2.9.0
statamic/seo-pro: 3.1.3
swiftmade/statamic-clear-assets: 1.1.0
transformstudios/events: 4.1.1
transformstudios/front: 1.11.0
transformstudios/gated: dev-main
transformstudios/github: dev-main
transformstudios/magic-link: dev-main
transformstudios/review: 3.7.2
transformstudios/simple: 2.21.3
transformstudios/takeover-redirects: dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

Happy to share site if it helps, or walk through site.
