### ISSUE TITLE
Relationships cannot be reordered

### ISSUE THREAD

**Issue by HellPat** [statamic/cms#744]
I have two collections which have a relation.

`posts` are sorted by date.
Then there is `teams` where each `team` has a relation to multiple `posts`.

The `posts` are related properly, but they are not sortable.
I don't know the intended behavior, but the default one seems wrong to me.

There _is_ a sorting-handle. But the handle is not usable.

![Bildschirmaufnahme](https://user-images.githubusercontent.com/1016798/65989890-d7e15780-e48a-11e9-889a-f947cfb36544.gif)

This brings me to the following options:

- Do not show the handle if not sortable
- Allow for manual sorting
- Allow to inherit sorting from the related collection

This is most likely related to #391 

Here my config:

```yaml
# blueprint/teams.yaml
title: Team
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Title
      -
        handle: relationship
        field:
          max_items: 0
          collections:
            - posts
          mode: default
          type: relationship
          localizable: false
          display: relationship
```

```yaml
# the entry with relationships
---
title: 'Herren 1'
updated_by: 9cc04642-f1ee-474a-9400-47413c8ec24f
updated_at: 1569873398
team_categories:
  - aktiv
relationship:
  - 672b0232-53df-4414-a6af-f50a666813ce
  - 46bb36f5-57b8-4e9b-ac71-f1588411d0be
  - 7d1a9461-b03b-405d-b8a0-4ae3fc5444d2
id: a9a14c40-a595-4de7-89d5-053bdb09a318
---
```

```yaml
# collecions/posts.yaml
title: Posts
route: 'posts/{slug}'
default_status: published
blueprints:
  - post
taxonomies:
  - tags
revisions: false
date: true
date_behavior:
  past: public
  future: private
```
