### ISSUE TITLE
Saving with cmd + s creates a new entry each time 

### ISSUE THREAD

**Issue by freshface** [statamic/cms#7441]
### Bug description

In 3.4 when creating a new entry and saving thru cmd+s it creates a new entry each time you save via the cmd+s shortcut.
It does not redirect to the listing

### How to reproduce

In 3.4 when creating a new entry and saving thru cmd+s it creates a new entry each time you save via the cmd+s shortcut.
It does not redirect to the listing

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.48.0
PHP Version: 8.1.5
Composer Version: 2.2.18
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
