### ISSUE TITLE
Text in bard set unselectable on firefox

### ISSUE THREAD

**Issue by esensgit** [statamic/cms#7447]
### Bug description

When adding sets to my bard field I noticed the text in sets isn't selectable. Which means I have to select the text with my shift+arrow keys if I want to add any formatting. I found this bug in Firefox and Firefox Development edition. Chrome works fine.

![bard-text-selecting](https://user-images.githubusercontent.com/103586317/215996603-2581456c-cf9a-4dc6-815a-6dfce21dd6c6.png)

### How to reproduce

Add a bard content field to a blueprint, add a set containing a text field / textarea or another bard field.
Go to the page in the backend and add the set to the bard field. The text you type here isn't selectable with your mouse while using Firefox.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.49.0
PHP Version: 8.0.18
Composer Version: 2.0.12
Environment: local
Debug Mode: ENABLED
URL: test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

Firefox 109.0 (64-bit) on Windows
