### ISSUE TITLE
The time input field is unusable on mobile

### ISSUE THREAD

**Issue by sunscreem** [statamic/cms#7449]
### Bug description

I'm using an android device and trying to input a time into a standard control panel time fields. 

You can set the hours, but the minutes default to `59` or `NaN`.

It seems there's some JavaScript formatting happening on blur that causing the issue.

### How to reproduce

This happens in any stand alone time input field. 

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.47.0
PHP Version: 8.2.0
Composer Version: 2.5.1
```

Device:
```
Chrome 109.0.5414.188 running on Android 13 on a Google Pixel 5.
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

Happy to help diagnose this further if someone can point me in the right direction.
