### ISSUE TITLE
The container option in the asset fieldtype should only be a requirement if multiple containers exist

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#745]
This should be in enough in the blueprint:

```
-
  handle: images
  field:
    type: assets
```

Right now (and in v2) you _had_ to include `container:`. If there's only one container configured, we can just assume that's it.
