### ISSUE TITLE
Exclude home from static caching

### ISSUE THREAD

**Issue by JoeriE** [statamic/cms#7451]
### Bug description

My site is running on full static caching and I want to exclude only the homepage.
So I added the page to the exclude in static_caching.php

    'exclude' => [
        '/',
    ],

But this doesn't seem to work. When I go the website, there's still a `_.html` file in `public/static`.
Although, when running `php please static:warm` the homepage is ignored and not included in the caching. So that's correct.

### How to reproduce

1. Enable full static caching
2. Add homepage to exclude array
3. Refresh home page and check if page is cached in `public/static`

### Environment

```yaml
Environment
Application Name: ***
Laravel Version: 9.50.0
PHP Version: 8.0.27
Composer Version: 2.5.1
Environment: staging
Debug Mode: ENABLED
URL: louisblockx.option5.studio
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: full
Version: 3.3.67 PRO

Statamic Addons
aerni/advanced-seo: 1.3.3
swiftmade/statamic-clear-assets: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
