### ISSUE TITLE
Homepage static cache not cleared

### ISSUE THREAD

**Issue by axeloz** [statamic/cms#7452]
### Bug description

Hello, 

My issue looks very much like #6749 
I have a static cache strategy on "half". 

I added some invalidation rules: 
```
    'invalidation' => [

        'class' => null,

        'rules' => [
            'collections' => [
                'publications' => [
                    'urls' => [
                        '/publications',
                        '/',
                    ]
                ],
                'solutions' => [
                    'urls' => [
                        '/solutions',
                        '/',
                    ]
                ],
            ]
        ]
    ],
```

When adding or updating a publication, the /publications page is refreshed. But homepage is **not**. 
However, this issue is supposed to be fixed so I don't get it.

Thanks

### How to reproduce

* activate cache strategy
* create new content
* check supposed-to-be-refreshed URLS

### Environment

```yaml
Environment
Application Name: <undisclosed>
Laravel Version: 9.42.2
PHP Version: 8.1.13
Composer Version: 2.1.14
Environment: local
Debug Mode: ENABLED
URL: <undisclosed>.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / daily
Mail: mailjet
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.59 PRO

Statamic Addons
aryehraber/statamic-logbook: 2.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
