### ISSUE TITLE
Static caching and calling an URL different from APP_URL

### ISSUE THREAD

**Issue by andreas-eisenmann** [statamic/cms#7456]
### Bug description

We accidentally had no default vhost on a machine so when a weird robot called the public ip of the host, a statamic project has been served. When calling `/sitemap.xml` (with the correct domain) we got a list of URLs with the public ip instead of the domain of the project. We found out that this page has been served by the static cache, although it is excluded from caching in `statamic.static_caching.exclude`.

So two things to debug:

- Why is the sitemap.xml being served by the static cache although it has been excluded?
- Why do we have URLs with wrong domains?

Found out that we have a possible incorrect behaviour in `\Statamic\StaticCaching\DefaultUrlExcluder::isExcluded`:

![image](https://user-images.githubusercontent.com/93596193/216322036-77296f02-b7a5-4b58-a8e7-1bbfdea478ff.png)

What's happening there:

- `APP_URL` is `http://localhost`
- The app is called via `http://127.0.0.1`
- The Base-URL `http://localhost` is being trimmed from the called URL (or let's say: there's a try but nothing happens), assuming that we can now compare the exclusions (only defined as Paths and **not** as absolute URLs) in `statamic.static_caching.exclude` with the called URL
- Our excluded URL (or rather path) is falsely declared as not excluded

In my opinion the root cause of this behaviour is implemented in `\Statamic\StaticCaching\Cachers\AbstractCacher::getBaseUrl`. Why is the URL of the request not being defined as base URL?

By the way, the documentation says about `app.url`:

```
/*
|--------------------------------------------------------------------------
| Application URL
|--------------------------------------------------------------------------
|
| This URL is used by the console to properly generate URLs when using
| the Artisan command line tool. You should set this to the root of
| your application so that it is used when running Artisan tasks.
|
*/
```

But in this case this config is being used in context of an http request?

There's a comment in the code of `getBaseURL` that says:

```
// This could potentially just be Site::current()->absoluteUrl() but at the
// moment that method gets the URL based on the request. For now, we will
// manually get it from the config, as to not break any existing sites.
```

What's the reason for not using the URL based on the request?

Maybe defining a multisite environment with absolute URLs and all possible domains (leading to different cache directories) could be a workaround, but that feels wrong to me...

So we have two issues caused by the wrong base URL:

- Exclusion of URLs from static caching does not work
- When stored with a different domain, the static cache serves all URLs with the wrong domain

And last but not least a personal comment: when working with URLs, why do you work with raw strings and not with URL parts from [parse_url](https://www.php.net/manual/de/function.parse-url.php) or even better (if there's no care about dependencies) an oop library like [spatie/url](https://packagist.org/packages/spatie/url)? Seems like sometimes you mess up with "scheme + host", "path" and a full (absolute) url when "talking" about "url" (e.g. in a variable)? 😊

### How to reproduce

In a local dev environment:

- Set `APP_URL` to `http://localhost`
- Set `STATAMIC_STATIC_CACHING_STRATEGY` to `full`
- Ensure that `statamic.static_caching.exclude` contains `/sitemap.xml`
- Call `http://127.0.0.1/sitemap.xml`
- Call `http://localhost/sitemap.xml`

The second call will:

- Serve content from static cache 
- And all URLs will have `127.0.0.1` as domain instead of `localhost` as defined per Request AND per `APP_URL`

### Environment

```yaml
Environment
Application Name: **************
Laravel Version: 9.35.1
PHP Version: 8.1.14
Composer Version: -
Environment: production
Debug Mode: OFF
URL: **************
Maintenance Mode: OFF

Cache
Config: CACHED
Events: CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: full
Version: 3.3.61 PRO

Statamic Addons
anakadote/statamic-recaptcha: 1.0.7
optimoapps/statamic-bard-text-align: 1.0.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
