### ISSUE TITLE
Three Dots within User Permissions

### ISSUE THREAD

**Issue by StephenThink** [statamic/cms#7458]
### Bug description

I'm not sure if this is a bug or something that has cropped up.

When you give some permission to access a collection, but not configure the collection they still have the three dots but no options.  Basically its a blank dropdown.

### How to reproduce

Create a Role, and stop them from configuring the Collections, but give them access to the individual collections.

![Screenshot 2023-02-02 at 15 06 12](https://user-images.githubusercontent.com/86749311/216362782-f88a2ea7-dd60-48e9-a7d5-f3fe8a8b3389.png)

Then if you log in as the user, you can click on the three dots but no options.  Im guessing the three dots should be hidden or is there some information that should drop down?

<img width="754" alt="Screenshot 2023-02-02 at 15 06 35" src="https://user-images.githubusercontent.com/86749311/216362995-ecace0c9-f24c-47f5-8bd7-2649a69be922.png">

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.50.1
PHP Version: 8.1.14
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: thinktemplate.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.1 PRO

Statamic Addons
takepart-media/statamic-oreos: 1.3.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
