### ISSUE TITLE
Contents in code snippet in bard set only shows after focus

### ISSUE THREAD

**Issue by Bahbv** [statamic/cms#7459]
### Bug description

After adding a Code field to my bard set I found it only show its content after being focused.

Before focus:
![no-focus](https://user-images.githubusercontent.com/12693117/216389030-ecf0a9e8-0a16-467d-98c7-9d781cc743f6.png)

After focussing the field:
![with-focus](https://user-images.githubusercontent.com/12693117/216389063-97703094-e3e9-4011-a003-7edea596dfd6.png)

Both in Chrome and Firefox

### How to reproduce

Make a bard field and add a set to it containing a Code field.
Add the set to a page, typesomething in the code field and save.
After refreshing the bug occurs.

### Environment

```yaml
Environment                                          
Application Name: Boiler                             
Laravel Version: 9.48.0                              
PHP Version: 8.0.18                                  
Composer Version: 2.0.12                             
Environment: local                                   
Debug Mode: ENABLED                                  
URL: boiler.test                                     
Maintenance Mode: OFF                                
                                                     
Cache                                                
Config: NOT CACHED                                   
Events: NOT CACHED                                   
Routes: NOT CACHED                                   
Views: CACHED                                        
                                                     
Drivers                                              
Broadcasting: log                                    
Cache: statamic                                      
Database: mysql                                      
Logs: stack / single                                 
Mail: smtp                                           
Queue: sync                                          
Session: file                                        
                                                     
Statamic                                             
Addons: 6                                            
Antlers: runtime                                     
Stache Watcher: Enabled                              
Static Caching: Disabled                             
Version: 3.4.1 PRO                                   
                                                     
Statamic Addons                                      
aryehraber/statamic-logbook: 2.1.0                   
goldnead/statamic-collapse-fieldtype: 1.0.4          
octoper/statamic-html-minify: 1.0.0                  
studio1902/statamic-peak-commands: 1.17              
webographen/statamic-admin-log: 1.0.6                
webographen/statamic-widget-cache-controller: 1.0.1
```

### Installation

Other (please explain)

### Antlers Parser

runtime (new)

### Additional details

The statamic install is an modifed PEAK boilerplate i'm working on.
The only changes are on the front end and some addons.
