### ISSUE TITLE
Entry parent is not updated in entry's data

### ISSUE THREAD

**Issue by ItsYogSothoth** [statamic/cms#7464]
### Bug description

When creating entries in collections that allow creation of child entries parent attribute of created entry is only populated on entry creation time. Moving entry to another parent doesn't update it in entry data, only in tree entity.

While entry list for collection displays properly in control panel using information from tree entity (same goes for the attribute itself inside entry properties) this behavior can cause unexpected effects when querying for collections using GraphQL.

Here is the collection with child entries inside:
![Screenshot_20230203_143433](https://user-images.githubusercontent.com/14014806/216631320-bbbaf868-0ce2-4037-ba74-5492586ce2b9.png)

And properties of entry moved after creation time:
![Screenshot_20230203_143745](https://user-images.githubusercontent.com/14014806/216631423-81aa3195-ee1f-491d-b5b5-2dc05ede4c89.png)

When querying for collection entries using collections interface and applying filter to only display parent entries this is the result I'm getting:
![Screenshot_20230203_143620](https://user-images.githubusercontent.com/14014806/216631691-26e9796a-7dd9-4ca0-8b2a-798eeda6c7d2.png)

Data inside database for entry and tree:
![Screenshot_20230203_143523](https://user-images.githubusercontent.com/14014806/216631858-7f751a52-40a3-4526-a6a9-740ed5d551a1.png)
![Screenshot_20230203_143545](https://user-images.githubusercontent.com/14014806/216631872-fb7717a8-17fd-415e-95af-57461010a064.png)

### How to reproduce

1. Create new collection
2. Configure collection, enable manual ordering, optionally set maximum depth to 2 or larger
3. Create first entry
4. Create second entry
5. Move second entry as a child of first entry

### Environment

```yaml
Environment
Application Name: laravel
Laravel Version: 9.48.0
PHP Version: 8.2.2
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: cms.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Scout: database_index
Session: file

Filament
Packages: filament, forms, notifications, support, tables
Version: v2.16.62
Views: PUBLISHED: filament

Statamic
Addons: 1
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.2 PRO

Statamic Addons
statamic/eloquent-driver: 1.1.2
```

### Installation

Existing Laravel app

### Antlers Parser

regex (default)
