### ISSUE TITLE
Block nocache with multiple url params not working

### ISSUE THREAD

**Issue by jbrhel** [statamic/cms#7465]
### Bug description

{{ nocache }} block {{ /nocache }} return an empty results when url contains more than one parameter and that page is already cached.

Cached page is created and loded but nocache block remains empty.

### How to reproduce

1. fresh instalation of Statamic 3.4.2
2. place ```{{ nocache }}<h1>The Test</h1>{{ /nocache }}``` to home.antlers.html
3. enable static cache full measure ```STATAMIC_STATIC_CACHING_STRATEGY="full"```
4. visit page with url: ```http://test.cache.test/?foo=bar&bar=foo```
5. heading "The Test"  is visible, page is successfully cached
6. visit page again with same url: ```http://test.cache.test/?foo=bar&bar=foo```
7. heading "The Test" is not present, nocache fetch returns an empty regions

![Cursor_and_Home](https://user-images.githubusercontent.com/1133430/216645372-1059b319-d09c-4a16-a753-7a63c0bfcf4f.jpg)

![Home](https://user-images.githubusercontent.com/1133430/216645379-fb1f1379-945f-4088-ac2e-8088e82f72e3.jpg)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.50.2
PHP Version: 8.1.12
Composer Version: 2.2.6
Environment: local
Debug Mode: ENABLED
URL: test.cache.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Disabled
Static Caching: full
Version: 3.4.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
