### ISSUE TITLE
Can't get a cursor to show between bard sets right next to each other

### ISSUE THREAD

**Issue by twd3** [statamic/cms#7468]
### Bug description

Before 3.4 I could click between two bard sets that were right next to each other and a cursor would show up so I could add stuff. I can't get that cursor to show. This happens with or without sets collapsed also in Firefox and Chrome. 

### How to reproduce

Make a bard. Make two sets and use two sets right next to each other then try to place new content between.

### Logs

```shell
None
```

### Environment

```yaml
Environment
Application Name: Skeeter
Laravel Version: 9.50.2
PHP Version: 8.0.10
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
URL: v-34.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: mailgun
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.2 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
aryehraber/statamic-logbook: 2.1.0
jacksleight/statamic-bard-mutator: 2.0.1
jacksleight/statamic-bard-texstyle: 2.0.1
spatie/statamic-responsive-images: 2.15.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
