### ISSUE TITLE
        {{ collection from="referenzen" not_listed:is="false" taxonomy:branchen="{selected:branches}" services:contains="{selected:services|option_list}" }}

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#7484]
### Bug description

I've tried to filter a references collection with livewire.
I get this error:
`foreach() argument must be of type array|object, null given`

### How to reproduce

The references entries have a field with related services entries:
```
selected:
  - 87fd29f0-dff9-4aad-b8a6-35fba2de3530
  - be6439fd-ed8e-4928-8ada-69cecc670a8b
  - e79d1c7b-913f-49f4-ab2e-e3d603856fca
```
From livewire I get the selected services:
```
selected:services
  - be6439fd-ed8e-4928-8ada-69cecc670a8b
  - e79d1c7b-913f-49f4-ab2e-e3d603856fca
```
Now I want to show the entries with this tag:
`{{ collection 
from="references" 
not_listed:is="false" 
taxonomy:branchen="{selected:branches}" 
services:in="{selected:services|option_list}" 
}}`

I've tried multiple versions, but nothing worked:
```
{{ collection from="references" services:in="{selected:services}" }}
{{ collection from="references" services:in="{selected:services|option_list}" }}
{{ collection from="references" services:contains="{selected:services}" }}
{{ collection from="references" services:contains="{selected:services|option_list}" }}
```

This error is shown:
`foreach() argument must be of type array|object, null given`

I think this should work, like it is explained in the docs:
https://statamic.dev/conditions#passing-multiple-values 

The filter for branches with taxonomies working fine without an error.

### Environment

```yaml
Environment
Application Name: test
Laravel Version: 9.48.0
PHP Version: 8.0.12
Composer Version: 2.1.3
Environment: local
Debug Mode: ENABLED
URL: domain.tld
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 10
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.67 PRO

Statamic Addons
anakadote/statamic-recaptcha: 1.0.8
aryehraber/statamic-logbook: 2.1.0
doublethreedigital/duplicator: 2.3.4
heidkaemper/statamic-toolbar: 1.0.3
jezzdk/statamic-google-maps: 1.2.1
jonassiewertsen/statamic-live-search: 1.6.0
jonassiewertsen/statamic-livewire: 2.11.0
weareframework/pinpoint-image: 0.0.10
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
