### ISSUE TITLE
The `nocache` tag shows blank content when `ignore_query_strings` is true

### ISSUE THREAD

**Issue by arthurperton** [statamic/cms#7487]
### Bug description

The code that is responsible for writing and restoring the `NoCache\Session`s does not respect the `ignore_query_strings = true` setting. It just always includes the query string. So if you revisit a cached page with a different query string, it won't be able to find a matching `Session`.

### How to reproduce

* Fresh install
* In the `static_caching.php` config set `'strategy' => 'full',` and `'ignore_query_strings' => true,`
* Add `{{ nocache }} some content {{ /nocache }}` to `home.antlers.html`
* Visit `/?var=1` and see the nocache block rendered
* Visit `/?var=2` and see the nocache block missing

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.50.2
PHP Version: 8.1.8
Composer Version: 2.3.10
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: full
Version: 3.4.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
