### ISSUE TITLE
{{ text }} doesn't render inside a Bard field unless it has some sets assigned

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/cms#7500]
### Bug description

I have a Bard field that works fine in the control panel as expected, however, when rendering the field in the template

```
{{ bard_field }}
  {{ text }}
{{ /bard_field }}
```

no text appears.

### How to reproduce

Create a Bard field with no sets.

See that the text doesn't render.

### Environment

```yaml
Application Name: Statamic
Laravel Version: 9.51.0
PHP Version: 8.1.15
Composer Version: 2.5.2
Environment: local
Debug Mode: ENABLED
URL: sandbox.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.3 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
