### ISSUE TITLE
"locales" Laravel-style fluent tag doesn't fetch locales

### ISSUE THREAD

**Issue by piljac1** [statamic/cms#7502]
### Bug description

In both Blade files and Tinker, if I try to iterate over `Statamic::tag('locales')`, it throws an exception: `ArrayIterator::__construct(): Argument #1 ($array) must be of type array, string given`.

### How to reproduce

Blade example:
```php
@foreach (Statamic::tag('locales') as $locale)
    @dump($locale)
@endforeach
```

If I call `->fetch()` explicitely on the fluent tag, it returns an empty string.

Things to consider:
1. Using the `{{ locales }}` tag in Antlers works as expected
2. In the above example, If I replace `'locales'` by either `'collection:pages'` or `'nav:secondary_navigation'`, it iterates and dumps the value properly.

### Environment

```yaml
Environment
Application Name: Test App
Laravel Version: 9.48.0
PHP Version: 8.1.12
Composer Version: 2.1.6
Environment: local
Debug Mode: ENABLED
URL: statamic-app.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.65 PRO

Statamic Addons
doublethreedigital/runway: 2.6.5
statamic/eloquent-driver: 1.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
