### ISSUE TITLE
Code Block button in Bard

### ISSUE THREAD

**Issue by ottz0** [statamic/cms#7505]
### Bug description

I've just updated to statamic 3.4.3 and am trying to use the `code block` button inside of the bard. The older version worked fine but when I paste code like this `<LogonDatabase Hostname = “127.0.0.1”Username = “root”Password = “ascent”Name = “logon”Port = “3306”Type = “1”>`, either nothing happens when I press the `code block button` or it does not wrap anything in the code and pre tag nor gives it any formatting. 

When I type normal text and then wrap it it works. It seems to have issues with encoding or escaping or not seeing code as text or it's not ending closing it's tag.

### How to reproduce

Add code such as this `<LogonDatabase Hostname = “127.0.0.1”Username = “root”Password = “ascent”Name = “logon”Port = “3306”Type = “1”>` to the `code block button` inside the bard to see if it wraps and formats code as text.

### Environment

```yaml
Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.3 PRO

Statamic Addons
aerni/font-awesome: 1.3.1
simonridley/tracking-code-manager: 1.0.0
withcandour/aardvark-seo: 2.0.30
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
