### ISSUE TITLE
Links in Bard lacking URL path when copied from external sources

### ISSUE THREAD

**Issue by elmanvebs** [statamic/cms#7507]
### Bug description

When content with links is added to Bard, the links are not transferred. The links appear as blue and underlined, but there is no URL path.

### How to reproduce

Simply copy and paste content with links from an external source such as a webpage or Google Document.

### Environment

```yaml
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.3 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
