### ISSUE TITLE
Type exception with custom search driver on 3.4.x

### ISSUE THREAD

**Issue by ffoerster** [statamic/cms#7508]
### Bug description

I am currently trying to update my site (running a custom search driver) to 3.4, but keep running into an issue with the IndexManager. Every index action produces the following exception:

`Statamic\\Search\\IndexManager::callLocalizedCustomCreator(): Argument #3 ($locale) must be of type string, null given, called in /var/www/html/vendor/statamic/cms/src/Search/IndexManager.php on line 88"`

My driver has been updated according to the upgrade docs and passes the $locale along:

```
        Search::extend('meilisearch', function ($app, array $config, $name, $locale) {
            $credentials = $config['credentials'];
            $url = $credentials['url'];
            $masterKey = $credentials['secret'];

            $client = new Client($url, $masterKey);

            return new MeiliSearch\Index($client, $name, $config, $locale);
        });
```

I am not sure, if it is due to my implementation or if it's the typing here:

https://github.com/statamic/cms/blob/91279c900221a52c82b4f7770804a15c9d912abe/src/Search/IndexManager.php#L124

### How to reproduce

Create a custom search driver
Update index with any record
Exception appears

### Environment

```yaml
Environment
Application Name: DevLocal
Laravel Version: 9.41.0
PHP Version: 8.1.12
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: localhost/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: rabbitmq
Session: cookie

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.2 PRO

Statamic Addons
doublethreedigital/runway: 4.0.0
parfaitementweb/statamic-country-fieldtype: 1.0.0
stillat/relationships: 1.2.1
```

### Installation

Existing Laravel app

### Antlers Parser

None
