### ISSUE TITLE
Bard Field: Table extension does not save cleared data from focused cells

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7512]
### Bug description

When selecting cells in a _Bard Field_ table and clearing the data within, after reloading the saved entry, the cleared data reappears. This is an issue since Statamic 3.4.

![2023-02-10 18 31 34](https://user-images.githubusercontent.com/1102712/218158135-95337d12-e6d4-4e76-9adc-f716345dba4a.gif)

### How to reproduce

1. Focus one or more _cells_ with text in a Bard table (Select the cell, not the text)
2. Clear the data within the selected cells
3. Save & reopen the same entry

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.51.0
PHP Version: 8.2.1
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.3 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
