### ISSUE TITLE
Adding an email to a form throws a "required field" error

### ISSUE THREAD

**Issue by bartrylant** [statamic/cms#7524]
### Bug description

When using the Dutch translation of the control pannel. If you add an email to a form, and fill in the recipient email address, the form won't save and says that the recipient field is required. Even if it is filled with a valid email address.

### How to reproduce

Forms > click "add email" > fill in recipient email (and other required fields) > save. The form will not save but will show a "the recipient email field is required" error (in Dutch: Dit veld is verplicht.).

### Environment

```yaml
Environment
Application Name: xxxxx
Laravel Version: 9.51.0
PHP Version: 8.0.8
Composer Version: -
Environment: local
Debug Mode: ENABLED
URL: xxxxx:8890/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.3 PRO

Statamic Addons
aerni/imagekit: 2.2.0
ddm-studio/cookie-byte: 1.1.1
statamic/seo-pro: 4.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
