### ISSUE TITLE
Unable to add Text after Link in Bard Field

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7526]
### Bug description

When placing the cursor at end of a link mark in Bard Field, the link itself gets selected which makes it unable to add any further text after the link. Workaround is using the arrow key. Before `3.4` text could be added by clicking at the end of a link.

## 3.4.x
![2023-02-12 20 14 04](https://user-images.githubusercontent.com/1102712/218333613-d471fc0b-b116-48a7-bdc2-099c02d20787.gif)

## 3.3.x
![2023-02-12 20 53 28](https://user-images.githubusercontent.com/1102712/218333800-574629e3-ed1d-4b20-adbd-6fceddd2b78a.gif)

### How to reproduce

Add a Link to a Bard Field :)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.51.0
PHP Version: 8.2.1
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.3 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
