### ISSUE TITLE
using "scope" modifier with taxo terms can be very slow

### ISSUE THREAD

**Issue by dadaxr** [statamic/cms#7532]
### Bug description

I know the "scope" modifier is mentioned only with collection tags in the doc... but It's actually a very useful modifier to prevent variable conflict... And it appears to (kinda) "work" not only with collections... 

### How to reproduce

Some examples : 
```
{{ taxonomy:budget scope="test" }}
  {{ test.slug }}
{{ /taxonomy:budget }}
```
this works as expected and display my slugs with no performance issue.

```
{{ myTerms = {taxonomy:budget} }}
{{ myTerms scope="test" }}
  {{ test.slug }}
{{ /myTerms }}
```
this also works but there is a huge performance issue. After investigating, it appears the "scope" params here is handled by the "scope" (core) modifier... which do a toArray() on the taxo  terms and retrieve all entries using that taxo... 

In the first example the "scope" parameters was handled by the "parseLoop" function of the "Tags.php" 

### Environment

```yaml
Environment
Application Name: Statamic leporc
Laravel Version: 9.51.0
PHP Version: 8.1.14
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: leporc.localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.3 PRO

Statamic Addons
statamic/seo-pro: 4.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

The second example notation is useful when I want to pass some generic data to a partial (IE a partial iterating over taxonomy terms without knowing how those were retrieve)

Maybe there is a better way to achieve that ? let me know :)
