### ISSUE TITLE
Processing source images breaks SVG's

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7541]
### Bug description

When you have a Glide preset in place to process source images, it will break SVG's. 

### How to reproduce

- Use a preset to process source images: `'replacement' => ['w' => 4500, 'q' => 100, 'fit' => 'max']`
- Enable it on the asset container
- Upload an svg

or
- Install Peak
- Upload an SVG to the `Images` container.

### Environment

```yaml
Environment
Application Name: Statamic Peak Development
Laravel Version: 9.51.0
PHP Version: 8.1.13
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.3 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 1.0
studio1902/statamic-peak-commands: 1.21
studio1902/statamic-peak-seo: 1.2.1
studio1902/statamic-peak-tools: 1.1
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
