### ISSUE TITLE
Cannot add text above or between Bard sets

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#7542]
### Bug description

When adding multiple bard sets, you used to be able to add text above the first set and between adjacent sets. In the screenshot below, you can only enter text below the sets.

<img width="932" alt="Screen Shot 2023-02-15 at 10 47 15 pm" src="https://user-images.githubusercontent.com/414211/219019879-adc05301-4b68-4bdc-801b-5819e970fb09.png">

### How to reproduce

Create a bard field, add 3 sets and attempt to enter text above the first set and between the adjacent sets.

### Environment

```yaml
Environment
Application Name: Momentum Development Support
Laravel Version: 9.52.0
PHP Version: 8.0.21
Composer Version: 2.4.0
Environment: local
Debug Mode: ENABLED
URL: momentum.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: regex
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.4.3 PRO

Statamic Addons
mikemartin/helpscout-beacon: 1.0.2
rias/statamic-color-swatches: 2.1.9
spatie/statamic-responsive-images: 3.1.3
statamic/seo-pro: 4.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
