### ISSUE TITLE
Renaming assets Error: foreach() argument must be of type array|object, string given

### ISSUE THREAD

**Issue by krautgortna** [statamic/cms#7547]
### Bug description

When renaming any asset, the error "foreach() argument must be of type array|object, string given" is being displayed. The renaming works basically, though I have to reload the page to show the asset's new name.

### How to reproduce

Go to an asset container, either 

- click on an asset and click button "Rename" OR
- click on the 3-dot-menu at the far right in the row of the asset and click "Rename"

Choose a new name, click "Rename Asset", the error is shown. 

### Logs

```shell
Request Payload:

{action: "rename_asset", context: {container: "assets", folder: "/"},…}
action: "rename_asset"
context: {container: "assets", folder: "/"}
selections: ["assets::testimage.jpg"]
values: {filename: "pexels-testimage"}




Response:

"message": "foreach() argument must be of type array|object, string given",
"exception": "ErrorException",
"file": "/home/vagrant/tintjournal/vendor/laravel/framework/src/Illuminate/Collections/Arr.php",
"line": 114,
"trace": ...
```

### Environment

```yaml
Both on Shared Hosting as well as in local Homestead environment
Statamic 3.3.68

shared hosting: PHP 8.1.14
homestead: PHP 8.0.16
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
