### ISSUE TITLE
Hide section tabs if no fields are visible

### ISSUE THREAD

**Issue by aerni** [statamic/cms#7554]
### Bug description

This is not a bug per se but it feels like one from a UX perspective.

If a blueprint section (tab) has no visible fields, the tab is still visible. It would be nice if the tab would be hidden as well.

This can happen in two scenarios:

1. All the fields in the section are set to `visibility: hidden`. I usually like to move all hidden fields into their own section to organize my blueprint.
2. The section contains conditional fields, which all are hidden. The tab has to be reactive. If a conditional field should be shown, the tab has to show up again. E.g. when toggling a toggle in another section.

### How to reproduce

Create a blueprint section and add a hidden field and a conditionally hidden field. The tab should be empty now.

<img width="942" alt="Bildschirmfoto 2023-02-16 um 09 15 39" src="https://user-images.githubusercontent.com/23167701/219388984-0b6eeab3-475a-4843-99b1-ece2d9c86b1f.png">

### Environment

```yaml
Environment
Application Name: gomagazin
Laravel Version: 9.52.0
PHP Version: 8.1.13
Composer Version: 2.5.0
Environment: local
Debug Mode: ENABLED
URL: gomagazin.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single, sentry
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 8
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.4 PRO

Statamic Addons
aerni/advanced-seo: 1.4.0
aerni/livewire-forms: 7.0.1
aerni/social-links: 3.0.3
aryehraber/statamic-impersonator: 2.4.1
jacksleight/statamic-bard-texstyle: 2.1.0
jonassiewertsen/statamic-livewire: 2.11.0
spatie/statamic-responsive-images: 3.1.3
stillat/relationships: 1.2.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
