### ISSUE TITLE
Field context not working for conditional fields in control panel

### ISSUE THREAD

**Issue by twd3** [statamic/cms#7564]
### Bug description

I am trying to compare against a field outside of a grid and I can't get it to work. Here is my fieldset trimmed down:
```
        media_object_list:
          display: 'Media Object List'
          fields:
            -
              handle: list_type
              field:
                options:
                  ol: Numbered
                  ul: Icons
                multiple: false
                push_tags: false
                cast_booleans: false
                display: 'List Type'
                type: select
            -
              handle: list_content
              field:
                fields:
                  -
                    handle: list_item_icon
                    field:
                      path_helper: default
                      recursive: default
                      display: 'List Item Icon'
                      type: iconamic
                      if:
                        root.list_type: 'equals ul'
                mode: stacked
                reorderable: true
                display: 'List Content'
                type: grid
```

### How to reproduce

Create a fieldset with a select field that has two options. In that same fieldset make a grid field and within that grid, make field then try to conditionally show it comparing to one of the options in the select field that is outside of the grid.

### Logs

```shell
Nothing in logs regarding this.
```

### Environment

```yaml
Environment
Application Name: 3.4
Laravel Version: 9.52.0
PHP Version: 8.0.10
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
URL: simp.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: mailgun
Queue: sync
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.4 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
aryehraber/statamic-logbook: 2.1.0
jacksleight/statamic-bard-mutator: 2.0.1
jacksleight/statamic-bard-texstyle: 2.1.1
mitydigital/iconamic: 1.1.2
ndx/statamic-bard-color-picker: 1.1.1
spatie/statamic-responsive-images: 3.1.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

Thank you for looking over my issue!
