### ISSUE TITLE
CP navigation preference is not applied to group roles

### ISSUE THREAD

**Issue by aerni** [statamic/cms#7565]
### Bug description

The CP Navigation preference is not applied if a user is part of a group that has that role assigned. The preference is only applied if you directly assign the role to a user.

### How to reproduce

1. Create a user
2. Create a role
3. Create a group
4. Assign the role to the group
5. Assign the group to a user
6. Customize the CP Navigation for the role
7. Login with the user
8. You will see the uncustomized CP navigation

### Environment

```yaml
Environment
Application Name: gomagazin
Laravel Version: 9.52.0
PHP Version: 8.1.13
Composer Version: 2.5.0
Environment: local
Debug Mode: ENABLED
URL: gomagazin.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single, sentry
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 8
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.4 PRO

Statamic Addons
aerni/advanced-seo: 1.4.0
aerni/livewire-forms: 7.0.1
aerni/social-links: 3.0.3
aryehraber/statamic-impersonator: 2.4.1
jacksleight/statamic-bard-texstyle: 2.1.0
jonassiewertsen/statamic-livewire: 2.11.0
spatie/statamic-responsive-ima
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
