### ISSUE TITLE
Vite tag does not support images

### ISSUE THREAD

**Issue by sasa-b** [statamic/cms#7571]
### Bug description

The docs say the following:

>The vite tag is a wrapper around [Laravel's Vite integration](https://laravel.com/docs/vite). It is essentially an Antlers version of the @vite Blade directive.

But the blade `@vite` tag supports images as well, whereas the antlers always assumes it's going to be a css/scss or js file.

### How to reproduce

{{ vite src='resources/img/logo.svg' }}

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 9.52.0
PHP Version: 8.2.3
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: laravel.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: sendmail
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.4 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
