### ISSUE TITLE
Listing users with a group filter isn't showing any results

### ISSUE THREAD

**Issue by danielfowler** [statamic/cms#7578]
### Bug description

https://statamic.dev/tags/users#parameters This page says that there's a group parameter to filter a users list. But when I use it the tag pair returns no results even though I have 7 such users in the group.

My code:

```
{{ users group="team" }}
    {{ name | wrap:h2.font-bold }}
    {{ groups | list }}
{{ /users }}
```

### How to reproduce

Use the `group="foo|bar"` parameter on a `{{ users }}` tag pair.

### Environment

```yaml
Environment
Application Name: Precision Landscape Management LLC
Laravel Version: 9.52.0
PHP Version: 8.1.12
Composer Version: 2.5.2
Environment: local
Debug Mode: ENABLED
URL: precision.localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.4 PRO

Statamic Addons
andrew-l/page-button: 1.0.0
swiftmade/statamic-clear-assets: 1.1.0
webographen/statamic-admin-log: 1.0.6
```

### Installation

Starter Kit using via CLI

### Antlers Parser

regex (default)
