### ISSUE TITLE
Antlers : Cannot create new index on an array

### ISSUE THREAD

**Issue by dadaxr** [statamic/cms#7593]
### Bug description

we can update an array specific index but cannot create new index.
Maybe it's a feature request, but the actual implementation looks bugy to me (see bellow) :

### How to reproduce

update an array specific index : 
```
{{ myArr = ['foo','bar'] }}
{{ myArr.1 = 'updated' }}
{{ myArr|dump }} 

output : 
array:2 [
  0 => "foo"
  1 => "updated"
]

```

trying to create new index : 

```
{{ myArr = ['foo','bar'] }}
{{ myArr.1 = 'updated' }}
{{ myArr.2 = 'new' }}
{{ myArr|dump }}

output : 
"new"
```
(the whole array is overwritten)

### Environment

```yaml
php please supp:det

Environment
Application Name: Statamic leporc
Laravel Version: 9.52.0
PHP Version: 8.1.14
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: leporc.localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.4.4 PRO

Statamic Addons
statamic/seo-pro: 4.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
