### ISSUE TITLE
Antlers : calling tag reset any updated array to their initial value 

### ISSUE THREAD

**Issue by dadaxr** [statamic/cms#7595]
### Bug description

Super weird bug here : 

If you updated the value of an array (created in current or outer scope) and then call some tag (I have tested "loop" and "glide" tag so far but my guess is this bug is not specific to those tags), your updated value is lost and the initial value defined when creating the array is restored.

Simple or associative arrays are impacted, but Local simple (scalar) variable, and front matter array are not. 

more details bellow : 

### How to reproduce

```
---
frontMatterArray:
    key: "default frontmatter array"
---
    {{ simpleVar = "simple val" }}
    {{ simpleVar|dump }} {{#output "simple val" : OK #}}
    {{ simpleVar = "updated simple val" }}
    {{ simpleVar|dump }} {{#output "updated simple val" : OK #}}
    {{ loop from="0" to="3" }}{{ index }}{{ /loop }}
    {{ simpleVar|dump }} {{#output "updated simple val" : OK #}}

    {{ myArray = ['flat array default val'] }}
    {{ myArray|dump }} {{#output "['flat array default val']" : OK #}}
    {{ myArray.0 = "flat array updated val" }}
    {{ myArray|dump }} {{#output "['flat array updated val']" : OK #}}
    {{ loop from="0" to="3" }}{{ index }}{{ /loop }}
    {{ myArray|dump }} {{#output "['flat array default val']" : NOT OK #}}

    {{ myKeyedArray = ['key' => 'keyed array default value'] #}}
    {{ myKeyedArray|dump }} {{#output "['keyed array default value']" : OK #}}
    {{ myKeyedArray.key = "keyed array updated value" }}
    {{ myKeyedArray|dump }} {{#output "['keyed array updated value']" : OK #}}
    {{ loop from="0" to="3" }}{{ index }}{{ /loop }}
    {{ myKeyedArray|dump }} {{#output "['keyed array default value']" : NOT OK #}}

    {{ view.frontMatterArray|dump }} {{# output "default frontmatter array" : OK #}}
    {{ view.frontMatterArray.key = "front matter keyed array updated value" }}
    {{ view.frontMatterArray|dump }} {{# output "front matter keyed array updated value" : OK #}}
    {{ loop from="0" to="3" }}{{ index }}{{ /loop }}
    {{ view.frontMatterArray|dump }} {{# output "front matter keyed array updated value" : OK #}}

    {{ parentArray = ['parent default value'] }}
    {{ partial:partials/_test }}
    
    
    Within "_test" partial : 
    {{ parentArray|dump }} {{# output "parent default value" : OK #}}
    {{ parentArray.0 = 'updated inside partial' }}
    {{ parentArray|dump }} {{# output "updated inside partial" : OK #}}
    {{ loop from="0" to="3" }}{{ index }}{{ /loop }}
    {{ parentArray|dump }} {{# output "parent default value" : NOT OK #}}
```

as mentioned earlier, using {{ glide }} tag (with or without parameter) also trigger the bug !

### Environment

```yaml
php please supp:det

Environment
Application Name: Statamic leporc
Laravel Version: 9.52.0
PHP Version: 8.1.14
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: leporc.localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.4.4 PRO

Statamic Addons
statamic/seo-pro: 4.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
