### ISSUE TITLE
Bard "Invalid Content" after 3.4 update

### ISSUE THREAD

**Issue by spaceageliving** [statamic/cms#7601]
### Bug description

Since updating to vers 3.4, I am getting an "Invalid Content" message on bard fields in the control panel for some items. The content is rendering ok when viewed on the site.

<img width="701" alt="Screenshot 2023-02-23 at 12 44 35 PM" src="https://user-images.githubusercontent.com/874600/221013605-480defe8-a907-4acb-90e1-2d8c42e045f4.png">

I'm thinking this may be due to using the Bard Text Align Extension previously (I removed it with the 3.4 update thinking I would no longer need it).

I am noticing that text items that were previously aligned center are no longer centered, but they do render (as left aligned).

WIth the extension previously enabled, centered text was stored like this:

```
        type: text
        marks:
          -
            type: italic
          -
            type: textAlign
            attrs:
              align: center
        text: 'Robert Pattinson as Bruce Wayne/The Batman'
```

which is different from how centered text is stored as of the 3.4 update.

Is this causing the "Invalid Content" issue? If so, what would be the best way to resolve this?

### How to reproduce

Go to Control Panel and edit content entered prior to 3.4 update.

### Environment

```yaml
Statamic 3.4.4 Pro
Laravel 8.83.27
PHP 8.1.7
Stache Watcher Disabled
Static Caching Disabled
aerni/social-links 2.3.1
mitydigital/feedamic 2.2.3
stillat/meerkat 2.6.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

Was previously using:

optimoapps/statamic-bard-text-align

**Comment by jasonvarga** [comment]
Keep the text align addon installed. That's what's causing the issue.

**Comment by spaceageliving** [comment]
@jasonvarga I was less than pleased with the add-on because it was causing strange line-breaking issues when editing in the bard field. I'd prefer to use the updated alignment controls in 3.4. Would I need to search/replace occurrences in exiting files to "repair" the old formatting?

**Comment by spaceageliving** [comment]
@jasonvarga Thanks very much, I'll review the info provided.

**Comment by spaceageliving** [comment]
@jasonvarga OK I got the updated 1.0.3 text-align add-on reinstalled. Content is editing again for the bard field in the editor. 

However, the 3.4 alignment buttons don't work, so I edited the blueprint to remove/disable them, and added back in the left/center/right options that (I believe) are for the add-on. When I try to edit content in bard field now, the alignment options are not visible (but they do appear in the blueprint editor).

**Comment by spaceageliving** [comment]
Editor:
<img width="909" alt="Screenshot 2023-02-23 at 2 13 04 PM" src="https://user-images.githubusercontent.com/874600/221031594-cb9e9b34-67db-4328-8c02-091b234f2085.png">

Blueprint:
<img width="1219" alt="Screenshot 2023-02-23 at 2 13 20 PM" src="https://user-images.githubusercontent.com/874600/221031633-ef9e2a86-9d3b-486c-9253-73ffa2b6821d.png">

**Comment by spaceageliving** [comment]
Blueprint:
```
-
        handle: content
        field:
          always_show_set_button: true
          buttons:
            - h1
            - h2
            - h3
            - h4
            - bold
            - italic
            - underline
            - left
            - center
            - right
            - small
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - horizontalrule
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          antlers: false
          display: Content
          type: bard
          icon: bard
          listable: hidden
          instructions_position: above
          container: assets
          visibility: visible
          previews: true
          validate:
            - required
          always_save: false
          sets:
            video:
              display: 'Add Video'
              fields:
                -
                  handle: video
                  field:
                    display: Video
                    type: video
                    icon: video
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    always_save: false
          remove_empty_nodes: false
          collapse: false
          smart_typography: false
          inline: false
      -
```
