### ISSUE TITLE
CP thumbnails loading takes more than 10 seconds

### ISSUE THREAD

**Issue by JoeriE** [statamic/cms#7605]
### Bug description

I have an assets type field where a lot of images are uploaded. The loading of the CP thumbnails always take more than 10 seconds (even 30 seconds for some). It's the same after every refresh of the page. Is there a way to cache these thumbnails?

<img width="672" alt="image" src="https://user-images.githubusercontent.com/11161180/221122307-e8769709-31d9-4ea2-ad4f-6c8c788b2dc5.png">

### How to reproduce

The original images are stored in an S3 bucket. This is my filesystems.php settings:

```
'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL') . '/storage',
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'visibility' => 'public',
            'disable_asserts' => true,
            'cache' => true,
        ],

        'assets' => [
            'driver' => 'local',
            'root' => public_path('uploads'),
            'url' => '/uploads',
            'visibility' => 'public',
        ],

    ],
```

### Environment

```yaml
Environment
Application Name:
Laravel Version: 9.44.0
PHP Version: 8.1.16
Composer Version: 2.5.4
Environment: production
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: full
Version: 3.3.61 PRO

Statamic Addons
aerni/advanced-seo: 1.3.3
swiftmade/statamic-clear-assets: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
