### ISSUE TITLE
No options to choose from Collections even there are existing one

### ISSUE THREAD

**Issue by FlickofDarise04** [statamic/cms#7611]
### Bug description

I can't pick an existing collection when configuring Navigation and Taxonomies. You should see the list of collections in the dropdown.
![image](https://user-images.githubusercontent.com/25291157/221402312-8d8fd0f8-7024-4226-b610-a0beb78a173b.png)

### How to reproduce

- Create a statamic project
- add collections
- create a navigation
- configure, in the options
- click the collections dropdown

### Environment

```yaml
Application Name: Statamic
Laravel Version: 9.50.1
PHP Version: 8.1.7
Composer Version: 2.3.10
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
