### ISSUE TITLE
Section defined inside partial slot results in "Call to a member function sections() on null"

### ISSUE THREAD

**Issue by xuneXTW** [statamic/cms#7612]
### Bug description

If i define a section-tag inside a partial tag i always receive the following error "Call to a member function sections() on null"

### How to reproduce

Define a partial tag inside a template with a section tag inside it.

{{ partial:test }}
        {{ section:test }}
            {{ content | widont }}
        {{ /section:test }}
{{ /partial:test }}

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.1.6
Composer Version: 2.3.7
Environment: local
Debug Mode: ENABLED
URL: bug-test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.4 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

This error has something to do with the changes made to 3.6.66. I have tried to downgrade the CMS-Version step by step. On 3.3.35 the error will not show.

BUT this case would not work as expected on 3.3.65 either. In 3.3.65 the yield tag would only be renderet properly if it is placed inside the same template. Placing the yield tag for example in the layout.antlers.html file and the partial/section tag inside a template will result in an empty output.
