### ISSUE TITLE
Error when linking to internal tab inside preferences.yaml

### ISSUE THREAD

**Issue by taylorcammack** [statamic/cms#7614]
### Bug description

Get a `preg_match(): Unknown modifier 'd'` error when trying to add a link to an internal tab in the CP Nav:

In this case, the `#docs` at the end of `globals/documentation`

```
'content_entry::edit_docs':
   action: '@create'
   display: 'Edit Docs'
   url: 'globals/documentation#docs'
   icon: cog
```

### How to reproduce

Add a link to an internal tab

### Environment

```yaml
Environment
Laravel Version: 9.52.4
PHP Version: 8.1.11
Composer Version: 2.5-dev+50cded331ced9acb4e926be3dda1f74b86af2a3b
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 9
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.4 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
encore/encore: dev-main
goldnead/statamic-collapse-fieldtype: 1.0.4
jonassiewertsen/statamic-livewire: 2.11.0
mitydigital/iconamic: 1.1.2
rias/statamic-data-import: 1.2.2
simonhamp/statamic-heroicons: 1.1.0
spatie/statamic-responsive-images: 3.1.3
webographen/statamic-dynamic-token: 1.0.0
```

### Installation

Other (please explain)

### Antlers Parser

runtime (new)
