### ISSUE TITLE
ReferenceError on saving if field name contains a - for some fieldtypes

### ISSUE THREAD

**Issue by rrelmy** [statamic/cms#7619]
### Bug description

Saving an entry shows a toasty with an error message of «ReferenceError: text is not defined» (_text_ depends on the fieldname)

---

Error happens on this line
https://github.com/statamic/cms/blob/24aca57a243abe8d1f7d78ac4c64666c8efbeb11/resources/js/components/publish/Values.js#L77
as `jsPath` reassembles something like `values.breaking-text`.

### How to reproduce

1. Create a blueprint with a Bard field having a handle `breaking-text`.
2. Create an entry
3. Click save

---

Better don't ask what happens when handle is `bard_field;alert("hacked")`.
This is a stored XSS issue as you can put any JS code in the handle!

### Logs

```shell
ReferenceError: text is not defined


This started to happen somewhere around statamic 3.3.40 I would say and is still valid in 3.4.
In earlier versions (incl. v2) this was not an issue.
```

### Environment

```yaml
Environment
Application Name: Foo
Laravel Version: 9.52.4
PHP Version: 8.1.15
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: foo.localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: mysql
Logs: stack / daily
Mail: log
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: half
Version: 3.4.4 PRO

Statamic Addons
statamic/migrator: dev-master
statamic/seo-pro: 4.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
