### ISSUE TITLE
Entries fieldtype - major performance issue when not using stack mode

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/cms#7631]
### Bug description

Using the Entries fieldtype with either `select` or `typeahead` mode will cause relationship endpoints requests to be extremely performance heavy, as they will return fully augmented entries instead of only necessary `id` and `title`.
This is especially painful when an entry has a lot of terms attached.

### How to reproduce

Attach an Entries fieldtype to any blueprint and use `select` mode, then see that the relationship request returns fully augmented entries.

### Environment

```yaml
Environment
Application Name: Comwell
Laravel Version: 9.52.4
PHP Version: 8.0.19
Composer Version: 2.1.5
Environment: local
Debug Mode: ENABLED
URL: comwell-v2.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: daily
Mail: mailgun
Queue: sync
Session: redis

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 PRO

Statamic Addons
dwarfdk/statamic-redirects: dev-master
jacksleight/statamic-bard-mutator: 2.0.1
pecotamic/sitemap: 1.4.1
statamic/eloquent-driver: 1.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
