### ISSUE TITLE
Duplicate button is missing after 3.4

### ISSUE THREAD

**Issue by tenmillionteeth** [statamic/cms#7638]
### Bug description

In versions later than 3.4.0, the duplicate button is missing in all collections. 
<img width="640" alt="Screen Shot 2023-03-01 at 3 06 00 PM" src="https://user-images.githubusercontent.com/119847334/222275766-caad2a93-43c6-4426-8793-f9fec7ef768d.png">

### How to reproduce

Update to 3.4, and the button is missing. 

### Environment

```yaml
Environment
Application Name: --
Laravel Version: 9.51.0
PHP Version: 8.2.1
Composer Version: 2.5.4
Environment: production
Debug Mode: OFF
URL: --
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: NOT CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: mysql
Logs: stack / single
Mail: postmark
Queue: sync
Session: file

Statamic
Addons: 10
Antlers: runtime
Stache Watcher: Disabled
Static Caching: half
Version: 3.4.5 PRO

Statamic Addons
4rn0/statamic-v3-image-optimizer: 1.0.20
aryehraber/statamic-color-extractor: 1.3.0
aryehraber/statamic-impersonator: 2.4.1
codedge/statamic-move-entries: 1.1
ddm-studio/cookie-byte: 1.1.4
jonassiewertsen/statamic-external-link: 1.7.0
rias/statamic-redirect: 2.6.0
statamic/collaboration: 0.5.0
statamic/seo-pro: 4.0.1
swiftmade/statamic-clear-assets: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
