### ISSUE TITLE
'Request failed' when throwing ValidationException in entrySaving with revisions

### ISSUE THREAD

**Issue by simonolog** [statamic/cms#7642]
### Bug description

Throwing a ValidationException in an event listener (e. g. attached to `entrySaving`) like shown below usually allows to attach an error message to a field:

```
public function handle()
{
    throw ValidationException::withMessages(['title' => 'Some error message']);
}
```

Expected behaviour:
![Screenshot_2023-03-02_10-41-46](https://user-images.githubusercontent.com/7941370/222391288-0cb7fbf8-467a-4962-bf95-4ab0745abbeb.png)

However, when publishing an entry with activated revisions this currently results in an error message within the error-toast, "Error: Request failed with status code 422", and the page is stuck.

![Screenshot_2023-03-02_10-36-09](https://user-images.githubusercontent.com/7941370/222391471-e8fad80f-83fc-4b26-ad83-17ef4fa040e5.png)

Without revisions (as well as simply saving the page) this does not happen.

### How to reproduce

- install fresh statamic
- activate pro, revisions and enable revisions for pages collection
- create a new event and attach it to `entrySaving`

```
php artisan make:event TestEvent
```

```
// TestEvent.php

use Illuminate\Validation\ValidationException;

class TestEvent
{
    public function handle()
    {
        throw ValidationException::withMessages(['title' => 'Some error message']);
    }
}
```

```
// EventServiceProvider.php

protected $listen = [
    EntrySaving::class => [
        TestEvent::class,
    ],
];
```

Then simply try to publish (not just save) an entry.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.1.15
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: statamic-validation.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
