### ISSUE TITLE
Partials with `src` attributes have to be closed before a partial with `src` and slot

### ISSUE THREAD

**Issue by marcorieser** [statamic/cms#7644]
### Bug description

> Notice:
In the real setup the partials live in an addon. Because of that the partial tags are used with the `src` attribute instead of `{{ partial:partials/the_partial }}` / `{{ partial:the-addon::partials/the_partial }}` .

When using a partial tag with `src` and a slot all previous partial tags (with the `src` attribute) need a closing `{{ /partial }}` tag at the end. Otherwise the slot does not get rendered.

This seems like a bug because only partials with a slot need a closing tag. 
Further it would be nice to have the ability to use partials from an addon without the `src` attribute (https://github.com/statamic/cms/issues/7645).

### How to reproduce

1. Use the following templates in a fresh installation or clone https://github.com/marcorieser/statamic-partial-slot-src-demo:

```antlers
{{# resources/views/default.antlers.html #}}
{{ partial src="partials/without_slot" }}{{# {{ /partial }} #}}

{{ partial src="partials/with_slot" }}
  {{ loop times="10" }}
    <div>{{ value }}</div>
  {{ /loop }}
 {{ /partial }}
```

```antlers
{{# resources/views/partials/_with_slot.antlers.html #}}
<div>{{ slot }}</div>
```

```antlers
{{# resources/views/partials/_without_slot.antlers.html #}}
<div>Partial without a slot</div>
```

2. Open the home page and see that the slot content (numbers from 1 to 10) is missing.
3. Uncomment the closing `{{ /partial }}` tag in `resources/views/default.antlers.html`.
4. Visit the home page again and notice that the slot content is rendered.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.2.3
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: statamic-partial-slot-src-demo.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 Solo

Statamic Addons
marcorieser/dummy: dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
