### ISSUE TITLE
`{{ user:profile_form }}` save to replicator field not possible

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#7648]
### Bug description

My user blueprint contains a nested replicator field. The users should be possible to edit these Information in their profile. 

 

### How to reproduce

I use the form tag `{{ user:profile_form }}`.

These are the fields, which should be saved ( and a lot more ).
```
    <input class="hidden" type="text" name="datenschutz[][inhalte][][type]" value="inhalt" readonly="">                              
    <input class="hidden" type="text" name="datenschutz[][inhalte][][hl]" value="Datenschutzinformationen" readonly="">                    
    <input class="hidden" type="text" name="datenschutz[][inhalte][][paragraphen][][type]" value="paragraph" readonly="">
    <input class="hidden" type="text" name="datenschutz[][inhalte][][paragraphen][][hl]" value="Verantwortlicher" readonly="">
```
When I try to save the information, I get an error, that the `type` is missing.

So I've added an array field to save the data for testing.

This was saved into the array field:
```
datenschutz:
  -
    inhalte:
      -
        type: inhalt
  -
    inhalte:
      -
        hl: Datenschutzinformationen
  -
    inhalte:
      -
        paragraphen:
          -
            type: paragraph
  -
    inhalte:
      -
        paragraphen:
          -
            hl: Verantwortlicher
```

But it should look like this:

```
datenschutz:
  -
    inhalte:
      -
        hl: 'Datenschutzinformationen'
        paragraphen:
          -
            hl: 'Verantwortlicher'
            type: paragraph
        type: inhalt
```
I think every input is saved separately, that's why the type field is missing.

### Environment

```yaml
Environment
Laravel Version: 9.52.0
PHP Version: 8.0.12
Composer Version: 2.1.3
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 8
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.4 PRO

Statamic Addons
aryehraber/statamic-logbook: 2.1.0
austenc/statamic-instagram-feed: 2.2.0
heidkaemper/statamic-toolbar: 1.0.7
jezzdk/statamic-google-maps: 1.2.2
jonassiewertsen/statamic-live-search: 1.6.0
jonassiewertsen/statamic-livewire: 2.11.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
Your field names should contain the appropriate indexes.

```diff
-name="datenschutz[][...]"
+name="datenschutz[0][...]"
```

By using just `[]`, it is essentially _pushing_ new values onto the array.

**Comment by wm-simon** [comment]
Hey @jasonvarga , thanks for your help. Width your solution `datenschutz[0][...]` the first values are saved correctly.  

When I save the second time values are the first values overwritten. 

After saving the first time I have this:
```
datenschutz:
  -
    inhalte:
      -
        type: inhalt
        hl: Datenschutzinformationen
        paragraphen:
          -
            type: paragraph
            hl: Verantwortlicher
```
After saving the second time, the first values are replaced by this:
```
datenschutz:
  1:
    inhalte:
      -
        type: inhalt
        hl: Datenschutzinformationen
        paragraphen:
          -
            type: paragraph
            hl: Verantwortlicher
```
I've tried it with `datenschutz[0][...]` , `datenschutz[1][...]` after the first time, but the new values are not pushed.
