### ISSUE TITLE
Change permissions on Fieldtypes/Terms.php

### ISSUE THREAD

**Issue by marceli-to** [statamic/cms#7661]
### Bug description

I have a site running on 3.4.5 and I get an error about once a week:

`.../vendor/statamic/cms/src/Fieldtypes/Terms.php): Failed to open stream: Permission denied`

and the site (including cp) stops working. The file is there but it has no permissions set. With a "composer install" I can get rid of the error and bring the site up again.

Any ideas?

### How to reproduce

Can not be reproduced

### Logs

```shell
[2023-03-06 15:33:46] production.ERROR: include(/httpdocs/vendor/statamic/cms/src/Fieldtypes/Terms.php): Failed to open stream: Permission denied {"exception":"[object] (ErrorException(code: 0): include(/httpdocs/vendor/statamic/cms/src/Fieldtypes/Terms.php): Failed to open stream: Permission denied at /httpdocs/vendor/composer/ClassLoader.php:571)
[stacktrace]
#0 /httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'include(/var/ww...', '/var/www/vhosts...', 571)
#1 /httpdocs/vendor/composer/ClassLoader.php(571): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'include(/var/ww...', '/var/www/vhosts...', 571)
#2 /httpdocs/vendor/composer/ClassLoader.php(571): include('/var/www/vhosts...')
#3 /httpdocs/vendor/composer/ClassLoader.php(428): Composer\\Autoload\\includeFile('/var/www/vhosts...')
#4 /httpdocs/vendor/statamic/cms/src/Providers/ExtensionServiceProvider.php(295): Composer\\Autoload\\ClassLoader->loadClass('Statamic\\\\Fieldt...')
#5 /httpdocs/vendor/statamic/cms/src/Providers/ExtensionServiceProvider.php(278): Statamic\\Providers\\ExtensionServiceProvider->registerCoreExtensions(Array)
#6 /httpdocs/vendor/statamic/cms/src/Providers/ExtensionServiceProvider.php(225): Statamic\\Providers\\ExtensionServiceProvider->registerExtensions()
#7 /httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(687): Statamic\\Providers\\ExtensionServiceProvider->register()
#8 /httpdocs/vendor/laravel/framework/src/Illuminate/Support/AggregateServiceProvider.php(31): Illuminate\\Foundation\\Application->register(Object(Statamic\\Providers\\ExtensionServiceProvider))
#9 /httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(687): Illuminate\\Support\\AggregateServiceProvider->register()
#10 /httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register(Object(Statamic\\Providers\\StatamicServiceProvider))
#11 /httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(664): Illuminate\\Foundation\\ProviderRepository->load(Array)
#12 /httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#13 /httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(242): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#14 /httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#15 /httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(160): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#16 /httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#17 /httpdocs/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#18 {main}
"}
```

### Environment

```yaml
Environment
Application Name: Rebobau AG
Laravel Version: 9.52.4
PHP Version: 8.1.13
Composer Version: 2.4.4
Environment: production
Debug Mode: OFF
URL: rebobau.ch
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single, slack
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 PRO

Statamic Addons
jacksleight/statamic-bard-texstyle: 2.1.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
