### ISSUE TITLE
404 page is still accessible with site-wide protection

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#7670]
### Bug description

With site-wide protection activate, we can still access 404 pages which is a problem when using custom 404 page with menu etc...

### How to reproduce

Activate any site-wide protection and try to navigate to a page that doesn't exist.

### Environment

```yaml
Environment
Application Name: Immersion-Pictures
Laravel Version: 9.52.4
PHP Version: 8.2.3
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: immersion-pictures.test
Maintenance Mode: OFF

Cache
Config: CACHED
Events: CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: half
Version: 3.4.5 PRO

Statamic Addons
4rn0/statamic-v3-image-optimizer: 1.0.20
handmadeweb/statamic-cloudflare: 1.0.7
statamic/seo-pro: 4.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
