### ISSUE TITLE
Custom Field in GraphQL API is not filterable

### ISSUE THREAD

**Issue by marvinhuebner** [statamic/cms#7671]
### Bug description

If I add a custom field to the GraphQL API as described [here](https://statamic.dev/graphql#custom-fields), I cannot filter by the custom field.

### How to reproduce

This is a simplified example, of course there should be logic in the resolve method.

Add custom field:
```php
GraphQL::addField('EntryInterface', 'customField', function () {
    return [
        'type' => GraphQL::string(),
        'resolve' => function () {
            return 'customField';
        }
    ];
});
```

GraphQL query with filter:
```gql
query MyQuery {
  entries(filter: {customField: {is: "customField"}}, limit: 5) {
    data {
      id
      customField
    }
  }
}
```

And then I get an empty response:
```json
{
  "data": {
    "entries": {
      "data": []
    }
  }
}
```

___

If I remove the filter, then I also get the value in my custom field, but I would like to filter according to it.

```gql
query MyQuery {
  entries(limit: 5) {
    data {
      id
      customField
    }
  }
}
```

```json
{
  "data": {
    "entries": {
      "data": [
        {
          "id": "00b12fc5-862d-4e9f-9f93-e54b21d6bb94",
          "customField": "customField"
        },
        {
          "id": "0109c5b5-e974-450f-afeb-655a103d2228",
          "customField": "customField"
        },
        {
          "id": "02cdd5d0-6f56-4a70-9c01-b0bcde8fbd7a",
          "customField": "customField"
        },
        {
          "id": "02e47463-380e-4a16-8e2a-87b2fbc60f99",
          "customField": "customField"
        },
        {
          "id": "03845bde-6261-4362-86ca-fd94a3fe4f28",
          "customField": "customField"
        }
      ]
    }
  }
}
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.1.13
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: euregio-backend.local
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
