### ISSUE TITLE
Lang file causing an error

### ISSUE THREAD

**Issue by elmanvebs** [statamic/cms#7672]
### Bug description

When you add a language file with the filename `forms` at `/resources/lang/{lang}` it throws an error when viewing the blueprints page `cp/fields/blueprints` in CP.

Error:
```
htmlspecialchars(): Argument #1 ($string) must be of type string, array given (View: /vendor/statamic/cms/resources/views/blueprints/index.blade.php)
```

<img width="216" alt="image" src="https://user-images.githubusercontent.com/5169878/223692487-aca3533f-0d64-4622-a151-017037b1cfcf.png">

### How to reproduce

Create a file with the name `forms` in lang folder. 

### Environment

```yaml
Statamic
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 PRO
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)
