### ISSUE TITLE
Join modifier should ignore empty key

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#7678]
### Bug description

Actually, the [join modifier](https://statamic.dev/modifiers/join) can not handle properly array with null key. 

### How to reproduce

The following:
```twig
{{ meta = [country, topic] }}
{{ meta | join(" | ") }}
```
with:
```twig
{{ meta = [Italy, Pasta] }}
```
will return `Italy | Pasta`, which is exactly what is expected !
but with :
```twig
{{ meta = [null, Pasta] }}
```
it will return `| Pasta`, which is not good.

This kind of simple check should be done in the backend by default.

### Environment

```yaml
Environment
Application Name: Immersion-Pictures
Laravel Version: 9.52.4
PHP Version: 8.2.3
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: immersion-pictures.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 PRO

Statamic Addons
4rn0/statamic-v3-image-optimizer: 1.0.20
handmadeweb/statamic-cloudflare: 1.0.7
statamic/seo-pro: 4.0.1
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
