### ISSUE TITLE
Using octane + user eloquent driver  does not work

### ISSUE THREAD

**Issue by phyroslam** [statamic/cms#7683]
### Bug description

When serving statamic using octane and configuring it to use the user eloquent driver it gives the following error:

Target [Statamic\Contracts\Auth\User] is not instantiable.

I am also using the eloquent driver for other repositories but I haven't being able to see if those will be impacted to

### How to reproduce

Serve statamic using octane 
change the configuration setting to use user eloquent driver

### Environment

```yaml
Environment
Application Name: ProjectsBox
Laravel Version: 9.52.4
PHP Version: 8.0.12
Composer Version: 2.1.11
Environment: local
Debug Mode: ENABLED
URL: 
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Octane: roadrunner
Queue: redis
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.4 PRO

Statamic Addons
joetannenbaum/antlers-stack-tags: 0.1.0
statamic/eloquent-driver: 1.2.0
```

### Installation

Existing Laravel app

### Antlers Parser

None
