### ISSUE TITLE
Multisite view overrides not working with statmic ssg

### ISSUE THREAD

**Issue by michaelr0** [statamic/cms#7693]
### Bug description

It looks like there is an issue with generating multisite pages with the SSG package, when trying to use view overrides for particular sites/pages.

The below PR's might be related as those appeared to have removed the viewPath's in favour of moving it into a middleware and solving a SSG performance issue.

https://github.com/statamic/cms/pull/7030
https://github.com/statamic/ssg/pull/120

### How to reproduce

- Create a new Statamic Multisite with SSG
- Create different `resources/views/<site1>/home.antlers.html` and `resources/views/<site2>/home.antlers.html` files
- Run `php artisan view:clear`
- Run SSG generate and see that `site1` and `site2` `will` use the override of `site1`
- Run SSG generate again and you may see that the overrides aren't used, both `site1` and `site2` will fallback to `resources/views/home.antlers.html` instead of the site override

### Environment

```yaml
php please support:details

Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.1.16
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: mysite.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 PRO

Statamic Addons
statamic/ssg: 1.3.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
