### ISSUE TITLE
Deleting a set from the replicator that includes a revealer leaves an empty error set on deletion.

### ISSUE THREAD

**Issue by kobe-f8** [statamic/cms#7695]
### Bug description

When deleting a set from the replicator that had revealer in it leaves behind an _"empty error set"_

### How to reproduce

![Screenshot 2023-03-14 at 13 26 10](https://user-images.githubusercontent.com/102222824/225000604-7685248a-3d97-4356-8398-82f061002dd1.png)

No custom settings applied to the revealer

https://user-images.githubusercontent.com/102222824/224999745-e2f86cb1-3499-4294-9a39-758f95b642a1.mov

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.1.13
Composer Version: 2.4.3
Environment: local
Debug Mode: ENABLED
URL: revealertest.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
