### ISSUE TITLE
Moving a set containing a nested revealer creates invalid data

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#7696]
### Bug description

If you have a set that contains a nested revealer, move the sets, hit save and then hit save again, other sets end up inheriting data from the set that contains the revealer:

https://user-images.githubusercontent.com/126740/225006209-15dce564-8723-4f2d-8270-e5e1d4cb6c01.mp4

As you can see at the end, the `divider` set ends up with a `replicator_field` value:

```yaml
  -
    id: lf88q5d9
    type: divider
    enabled: true
    replicator_field:
      - {  }
```

Feels like this could be related to https://github.com/statamic/cms/issues/7695, and could be caused by the same thing, but this is a different issue.

### How to reproduce

Using the blueprint and entry below:

- Open the entry
- Swap the two sets around
- Hit CTRL+S
- Hit CTRL+S again
- Check the entry data and the `divider` will have a `replicator_field` value

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 Solo
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None

### Additional details

```yaml
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: replicator_field
        field:
          collapse: false
          previews: true
          sets:
            items:
              display: Item
              fields:
                -
                  handle: replicator_field
                  field:
                    collapse: false
                    previews: true
                    sets:
                      set:
                        display: Set
                        fields:
                          -
                            handle: text_field
                            field:
                              input_type: text
                              antlers: false
                              display: 'Text Field'
                              type: text
                              icon: text
                              listable: hidden
                              instructions_position: above
                              visibility: visible
                          -
                            handle: revealer_field
                            field:
                              mode: button
                              display: 'Revealer Field'
                              type: revealer
                              icon: revealer
                              listable: hidden
                              instructions_position: above
                              visibility: visible
                    display: 'Replicator Field'
                    type: replicator
                    icon: replicator
                    listable: hidden
                    instructions_position: above
                    visibility: visible
            divider:
              display: Divider
              fields: {  }
          display: 'Replicator Field'
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above
          visibility: visible
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
title: Test
```

```yaml
---
id: b4e2338b-8294-4faa-a980-1cb442f93372
blueprint: test
title: 'Items Test'
updated_by: f35721f8-8c4c-4e40-a119-10a6ac6e1447
updated_at: 1678797989
replicator_field:
  -
    id: lf88q5d9
    type: divider
    enabled: true
  -
    id: lf88xp13
    type: items
    enabled: true
    replicator_field:
      -
        id: lf88ycik
        type: set
        enabled: true
---
```
