### ISSUE TITLE
Deleting a set from a bard field that contains a revealer and saving the page breaks the bard field causing every other set to disappear until refresh 

### ISSUE THREAD

**Issue by kobe-f8** [statamic/cms#7699]
### Bug description

https://user-images.githubusercontent.com/102222824/225073572-c70273b5-fd22-487e-b398-8d21764e087d.mov

Take this video as an example, I have multiple bard sets that have a "advanced options" revealer. When deleting one of these sets and saving the page; all of the other sets disappear until page refresh.

I am certain the revealer is the culprit because when I remove it on every bard set, the other sets don't disappear when saving the page

### How to reproduce

- Step 1. Add a multiple sets to a bard fieldtype each containing a revealer.
- Step 2. Delete one of these sets and save the page and notice how every other set disappears until page refresh
- Step 3. Delete every revealer from the bard field sets and notice that now when you delete a set the other sets don't disappear.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.1.13
Composer Version: 2.4.3
Environment: local
Debug Mode: ENABLED
URL: revealertest.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
