### ISSUE TITLE
Replacing an asset threw an error

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#7702]
### Bug description

Client replaced an asset and said "it threw an error for a second, but worked".

### How to reproduce

Not sure, we only got this error once in our error tool.

### Logs

```shell
Request URL: https://www.zakat.org/cp/assets/actions
Request data: {"new_asset":["public::2023/03/ramadan-2023-background-texture-blue-1678832795.jpg"],"delete_original":true}
Statamic\Assets\Asset::replace(): Argument #1 ($originalAsset) must be of type Statamic\Assets\Asset, null given, called in /home/forge/www.zakat.org/vendor/statamic/cms/src/Actions/ReplaceAsset.php on line 48

/home/forge/www.zakat.org/vendor/statamic/cms/src/Assets/Asset.php (715)
/home/forge/www.zakat.org/vendor/statamic/cms/src/Actions/ReplaceAsset.php (48)
/home/forge/www.zakat.org/vendor/statamic/cms/src/Http/Controllers/CP/ActionController.php (38)
/home/forge/www.zakat.org/vendor/laravel/framework/src/Illuminate/Routing/Controller.php (54)
/home/forge/www.zakat.org/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php (43)
/home/forge/www.zakat.org/vendor/laravel/framework/src/Illuminate/Routing/Route.php (259)
/home/forge/www.zakat.org/vendor/laravel/framework/src/Illuminate/Routing/Route.php (205)
/home/forge/www.zakat.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php (798)
/home/forge/www.zakat.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php (141)
/home/forge/www.zakat.org/vendor/statamic/cms/src/Http/Middleware/DeleteTemporaryFileUploads.php (18)
/home/forge/www.zakat.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php (180)
```

### Environment

```yaml
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.2.3
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: zakat.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 13
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.4.5 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
aryehraber/statamic-impersonator: 2.4.1
doublethreedigital/runway: 4.2.2
edalzell/forma: 1.3.0
jacksleight/statamic-bard-texstyle: 2.1.1
jonassiewertsen/statamic-livewire: 2.11.0
statamic/seo-pro: 4.0.1
transformstudios/events: 4.1.3
transformstudios/front: 1.11.0
transformstudios/github: dev-main
transformstudios/memorial: dev-feature/custom-neon-block
transformstudios/review: 3.8.1
transformstudios/simple: 3.2.0
```
```


### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

_No response_
