### ISSUE TITLE
[4.x] Published tooltip not very useful when using a non-dated collection

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#7705]
### Bug description

The tooltip you see when hovering over the new 'Published' status pill isn't very useful when you're using a non-dated collection.

The tooltip goes and grabs the `date` field from the entry. Usually, that's not set without the collection being "dated".

<img width="671" alt="image" src="https://user-images.githubusercontent.com/19637309/225238073-9b9279ce-69d9-4544-9882-7fcfef6d3be2.png">

### How to reproduce

1. Setup a v4 site, based on Peak
2. Clone down the master branch
3. Run `npm run dev`
4. Try to use Replicator & Bard fields

### Environment

```yaml
Environment
Application Name: Statamic 4 Test
Laravel Version: 9.52.4
PHP Version: 8.2.3
Composer Version: 2.2.6
Environment: local
Debug Mode: ENABLED
URL: statamic-4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: dev-master PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 1.0
studio1902/statamic-peak-commands: 1.24
studio1902/statamic-peak-seo: 1.6.1
studio1902/statamic-peak-tools: 2.1
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
