### ISSUE TITLE
A form without "save answers" still saves the file uploads

### ISSUE THREAD

**Issue by SG-fabian** [statamic/cms#7711]
### Bug description

Even with "save answers" unchecked the file uploads remain inside the selected folder.

We have a form on our website where the user can upload sensitive content - including up to three images. We don't want that on the server and only send it by mail.

### How to reproduce

Create a form with file upload, uncheck "save answers", select a mail address instead.

### Environment

```yaml
Environment
Application Name:
Laravel Version: 9.52.4
PHP Version: 8.2.2
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL:
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 2.11.0
statamic/seo-pro: 4.0.1
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
