### ISSUE TITLE
Bard doesn't add sets when cursor is horizontal

### ISSUE THREAD

**Issue by wesort** [statamic/cms#7712]
### Bug description

The "Add set" (+) button does not insert a new set if the cursor "horizontal".

The cursor is "horizontal" when there are sets in the field but the cursor isn't positioned at an empty paragraph. This works just fine if the cursor is "vertical" in the position of a new paragraph.

![bard-horizontal-cursor-01](https://user-images.githubusercontent.com/3920126/225636126-51578271-b3e9-41f8-acbe-3086313c483a.png)

https://user-images.githubusercontent.com/3920126/225638621-67f3da19-7d5d-4fc0-b286-164bd1fbe77f.mp4

### How to reproduce

- Have a Bard field with at least one set
- Place the cursor before, after or between sets such that it flashes as a horizontal cursor
- Click the "Add set" (+) button
- Nothing happens, except console error: `TypeError: Cannot read properties of undefined (reading 'pos')`

### Logs

```shell
TypeError: Cannot read properties of undefined (reading 'pos')
    at Set.js:57:69
    at Object.set (index.js:60:34)
    at a.<anonymous> (BardFieldtype.vue:398:1)
    at Array.<anonymous> (vue.common.prod.js:6:12294)
    at Ge (vue.common.prod.js:6:11693)
```

### Environment

```yaml
Environment
Application Name: [redacted]
Laravel Version: 9.52.4
PHP Version: 8.2.1
Composer Version: 2.5.4
Environment: dev
Debug Mode: ENABLED
URL: [redacted]
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 Solo
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
