### ISSUE TITLE
Changing "Per page" value for tables generates a 404 error

### ISSUE THREAD

**Issue by malle-pietje** [statamic/cms#7727]
### Bug description

When viewing a multi-page table (for example Akismet spam messages, assets) in the cp, I change the per-page value and nothing happens. In the browser console this error is thrown:
![image](https://user-images.githubusercontent.com/12016131/226304982-b2ed4f0f-32b3-4d87-bb07-637fe6bf6afb.png)

### How to reproduce

See above

### Logs

Here's the full console output after selecting a new per-page value:

```shell
xhr.js:187 
 POST https://zzzzzzz.net/cp/preferences/js 404
(anonymous) @   xhr.js:187
e.exports   @   xhr.js:13
e.exports   @   dispatchRequest.js:51
c.request   @   Axios.js:108
r.forEach.c.<computed>  @   Axios.js:140
(anonymous) @   bind.js:9
value   @   Preference.js:19
setPreference   @   HasPreferences.js:28
changePerPage   @   HasPagination.js:37
Be  @   vue.common.prod.js:6
n   @   vue.common.prod.js:6
Be  @   vue.common.prod.js:6
e.$emit @   vue.common.prod.js:6
input   @   Pagination.vue?b825:1
Be  @   vue.common.prod.js:6
n   @   vue.common.prod.js:6
Be  @   vue.common.prod.js:6
e.$emit @   vue.common.prod.js:6
change  @   Select.vue:78
Be  @   vue.common.prod.js:6
n   @   vue.common.prod.js:6
Kr.o._wrapper   @   vue.common.prod.js:6
handleMouseUp_  @   unknown
createError.js:16 Uncaught (in promise) Error: Request failed with status code 404
    at e.exports (createError.js:16:15)
    at e.exports (settle.js:17:12)
    at XMLHttpRequest.y (xhr.js:54:7)
e.exports   @   createError.js:16
e.exports   @   settle.js:17
y   @   xhr.js:54
Promise.then (async)        
value   @   Preference.js:40
value   @   Preference.js:18
setPreference   @   HasPreferences.js:28
changePerPage   @   HasPagination.js:37
Be  @   vue.common.prod.js:6
n   @   vue.common.prod.js:6
Be  @   vue.common.prod.js:6
e.$emit @   vue.common.prod.js:6
input   @   Pagination.vue?b825:1
Be  @   vue.common.prod.js:6
n   @   vue.common.prod.js:6
Be  @   vue.common.prod.js:6
e.$emit @   vue.common.prod.js:6
change  @   Select.vue:78
Be  @   vue.common.prod.js:6
n   @   vue.common.prod.js:6
Kr.o._wrapper   @   vue.common.prod.js:6
handleMouseUp_  @   unknown
```

### Environment

```yaml
Environment
Application Name: ZZZZZZZ
Laravel Version: 9.52.4
PHP Version: 8.2.3
Composer Version: 2.5.4
Environment: production
Debug Mode: OFF
URL: zzzzzzz.net
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 15
Antlers: regex
Stache Watcher: Disabled
Static Caching: half
Version: 3.4.6 PRO

Statamic Addons
aryehraber/statamic-logbook: 2.2.0
cnj/seotamic: 3.0.5
ddm-studio/cookie-byte: 1.1.5
edalzell/forma: 1.3.0
jackabox/statamic-plausible-analytics: 1.2.1
jacksleight/statamic-bard-texstyle: 2.1.1
jonassiewertsen/statamic-live-search: 1.6.0
jonassiewertsen/statamic-livewire: 2.11.0
rias/statamic-redirect: 2.6.0
silentz/akismet: 3.1.3
sortarad/extraextra: 1.0.1
spatie/statamic-health: 1.0.0
teamnovu/statamic-images-missing-alt: 0.4.0
teamnovu/statamic-unused-assets: 1.0.1
webographen/statamic-admin-log: 1.0.6

```

This error also occurs on our staging server, same PHP version but using Apache 2.5.52.

### Installation

Starter Kit using via CLI

### Antlers Parser

regex (default)
