### ISSUE TITLE
Call to a member function whereAnyStatus()

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#7728]
### Bug description

Tried to add a 'link to entry' and see a `Call to a member function whereAnyStatus()` error

### How to reproduce

This 11 second video shows how to reproduce
https://www.youtube.com/embed/FHQffsamSU0?rel=0

### Logs

```shell
local.ERROR: Call to a member function whereAnyStatus() on null {"userId":"c140131f-c375-40c2-b2b1-b1e0303f6b45","exception":"[object] (Error(code: 0): Call to a member function whereAnyStatus() on null at /Repositories/bones-starter/vendor/statamic/cms/src/Fieldtypes/Entries.php:300)
```

### Environment

```yaml
Environment
Application Name: ABC Widgets Co
Laravel Version: 9.52.4
PHP Version: 8.2.2
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: bones-starter.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.6 PRO

Statamic Addons
simonhamp/statamic-heroicons: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
