### ISSUE TITLE
Using filters in "entries" field clears selection && cannot search for anything but "title" field

### ISSUE THREAD

**Issue by Jade-GG** [statamic/cms#7733]
### Bug description

We are using an `entries` field linking to a collection that consists of 10k+ entries that have a `title` and a `sku` (and more but that's not relevant here). There are two issues that are giving us trouble:

- The search bar will *only* search for the `title` field. This appears to [be hardcoded](https://github.com/statamic/cms/blob/3.4/src/Fieldtypes/Entries.php#LL153C9-L153C9).
- Using the filters to search will clear the selected entries that do not match the filter.

With both of these issues together it makes it pretty much impossible to select entries by `sku` in our scenario, because you cannot search for them at all.

### How to reproduce

1. Create a collection with a bunch of entries (10k+ if you decide you really want to _feel_ our pain) and---aside from the `title` field---another field by which you might want to search, let's say we call it `sku`.
2. Make sure to change the "Listable" setting to "Shown by default" on the `sku` field so that it appears in the listing
3. Create some other blueprint with the `entries` field, linked to the above collection
4. Save and try to select multiple entries in this field by way of searching for the secondary field (that we called `sku`)
5. Observe that you cannot search by `sku` in the search bar, and trying to use the filters on the left will clear any already selected entries

### Environment

```yaml
(I just installed a fresh updated statamic install to test on, and the same issue happens)

Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.1.16
Composer Version: 2.2.9
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
