### ISSUE TITLE
3.4.6+ breaks sorting by order in an entries field.

### ISSUE THREAD

**Issue by tenmillionteeth** [statamic/cms#7739]
### Bug description

Updated to 3.4.6, and entries fields will only sort by title, when previously they could also be sorted by order and other fields. 

### How to reproduce

Have an entries field with a sort option that includes order. Update statamic beyond 3.4.5. The entries on the front end will no longer sort by order if that is selected. 

### Environment

```yaml
Environment
Application Name: --
Laravel Version: 9.51.0
PHP Version: 8.1.13
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: 127.0.0.1
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: mysql
Logs: stack / single
Mail: postmark
Queue: sync
Session: file

Statamic
Addons: 9
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 PRO

Statamic Addons
4rn0/statamic-v3-image-optimizer: 1.0.20
aryehraber/statamic-impersonator: 2.4.1
ddm-studio/cookie-byte: 1.1.4
doublethreedigital/duplicator: 3.0.0
jonassiewertsen/statamic-external-link: 1.7.0
rias/statamic-redirect: 2.6.0
sortarad/lol: 1.0.3
statamic/collaboration: 0.5.0
statamic/seo-pro: 4.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
