### ISSUE TITLE
Bard field with entry link linking itself breaks whole site

### ISSUE THREAD

**Issue by mmodler** [statamic/cms#7742]
### Bug description

If you have a bard field with a text link in it, linking the entry itself, you get an infinite loop while populating the stache.

### How to reproduce

```
---
id: f9ceef91-769f-4238-83af-38836a6027ac
blueprint: foo
title: 'Test'
bard:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Foo '
      -
        type: text
        marks:
          -
            type: link
            attrs:
              href: 'statamic://entry::f9ceef91-769f-4238-83af-38836a6027ac'
              rel: null
              target: null
              title: null
        text: bar
      -
        type: text
        text: '!'
---
```

### Environment

```yaml
Laravel Version: 9.52.0
PHP Version: 8.0.27
Version: 3.3.68 PRO
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)
