### ISSUE TITLE
Error `XXX is not defined` when saving. 

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#7752]
### Bug description

When I want to save an entry this error shows up:
`ReferenceError file is not defined`
`ReferenceError url is not defined`

### How to reproduce

The laravel log is empty.

I could find out, that the conditions here causing the error.

// fieldset video
```
title: Video
fields:
  -
    handle: video_type
    field:
      options:
        'null': Keins
        file: Datei
        youtube: Youtube
        vimeo: Vimeo
      default: 'null'
      display: Video
      type: button_group
      icon: button_group
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
  -
    handle: video-file
    field:
      mode: list
      restrict: false
      allow_uploads: false
      show_filename: true
      max_files: 1
      display: MP4-Datei
      type: assets
      icon: assets
      listable: hidden
      instructions_position: above
      validate:
        - 'mimes:mp4'
      container: vid
      folder: /
      visibility: visible
      if:
        video_type: 'equals file'
  -
    handle: youtube-url
    field:
      display: Youtube-URL
      type: video
      icon: video
      listable: hidden
      instructions_position: above
      placeholder: 'https://www.youtube.com/watch?v=123456789'
      visibility: visible
      if:
        video_type: 'equals youtube'
  -
    handle: vimeo-url
    field:
      placeholder: 'https://vimeo.com/123456789'
      display: Vimeo-URL
      type: video
      icon: video
      listable: hidden
      instructions_position: above
      visibility: visible
      if:
        video_type: 'equals vimeo'

```

When I remove all 
```
      if:
        video_type: 'equals XXX'
```
all works fine.

In the past that worked. Must be caused by an update.

### Environment

```yaml
Statamic 3.4.7 Pro
Laravel 8.83.27
PHP 8.0.12
Stache Watcher Enabled
Static Caching Disabled
jezzdk/statamic-google-maps 1.2.2      
mitydigital/statamic-google-fonts 1.0.2
nineteensquared/instagram 1.1.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
