### ISSUE TITLE
Can't replace and update asset meta data

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#7754]
### Bug description

Replacing the asset AND updating the meta data (in this case the alt text) before saving doesn't persist the new meta data.

### How to reproduce

1. replaced an asset (do NOT save)
2. set the alt text
3. save
 
It uploaded the new replaced asset without the saved info.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.2.4
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: zakat.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 12
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.4.6 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
aryehraber/statamic-impersonator: 2.4.1
doublethreedigital/runway: 4.2.2
edalzell/forma: 1.3.0
jonassiewertsen/statamic-livewire: 2.11.0
statamic/seo-pro: 4.0.1
transformstudios/events: 4.1.4
transformstudios/front: 1.11.0
transformstudios/github: dev-main
transformstudios/memorial: dev-fix/remove-texstyle
transformstudios/review: 3.8.1
transformstudios/simple: 3.3.1
```
```


### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

_No response_
