### ISSUE TITLE
Slug for entries doesn't autogenerate in sites locale

### ISSUE THREAD

**Issue by flolanger** [statamic/cms#7756]
### Bug description

When the slug is generated via Vue, the current site locale is respected, but if the slug gets autogenerated by PHP the slug will always be generated in english.

### How to reproduce

1. Open a existing entry in a site other than english (e.g. german)
2. Have a title that contains language specific characters (like ä, ö, ü)
3. Clear slug field
4. Save entry
5. -> Slug is now generated in english and not in e.g. german.

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 9.52.4
PHP Version: 8.1.13
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
