### ISSUE TITLE
[4.x] Replicator after section header looks off

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7762]
### Bug description

When you have a section header followed by a replicator you get a double border which looks a bit off.

<img width="934" alt="Screenshot 2023-03-24 at 19 55 16" src="https://user-images.githubusercontent.com/69107412/227615160-c51db09f-1830-45e0-aad4-7c8148920d7a.png">

### How to reproduce

Try this global fieldset for example:

```yaml
tabs:
  social_media:
    display: 'Social Media'
    sections:
      -
        display: 'Social media'
        instructions: 'Configure social media links.'
        fields:
          -
            handle: social_media
            field:
              sets:
                email:
                  display: Email
                  fields:
                    -
                      handle: handle
                      field:
                        input_type: text
                        type: text
                        localizable: true
                        listable: hidden
                        display: Email
                        validate: required
                    -
                      handle: prefix
                      field:
                        type: hidden
                        default: 'mailto:'
                facebook:
                  display: Facebook
                  fields:
                    -
                      handle: handle
                      field:
                        input_type: text
                        type: text
                        localizable: true
                        listable: hidden
                        prepend: 'https://www.facebook.com/'
                        display: Handle
                        validate: required
                    -
                      handle: prefix
                      field:
                        type: hidden
                        default: 'https://www.facebook.com/'
                github:
                  display: GitHub
                  fields:
                    -
                      handle: handle
                      field:
                        input_type: text
                        type: text
                        localizable: true
                        listable: hidden
                        prepend: 'https://www.github.com/'
                        display: Handle
                        validate: required
                    -
                      handle: prefix
                      field:
                        type: hidden
                        default: 'https://www.github.com/'
                instagram:
                  display: Instagram
                  fields:
                    -
                      handle: handle
                      field:
                        input_type: text
                        type: text
                        localizable: true
                        listable: hidden
                        prepend: 'https://www.instagram.com/'
                        display: Handle
                        validate: required
                    -
                      handle: prefix
                      field:
                        type: hidden
                        default: 'https://www.instagram.com/'
                linkedin:
                  display: LinkedIn
                  fields:
                    -
                      handle: handle
                      field:
                        input_type: text
                        type: text
                        localizable: true
                        listable: hidden
                        prepend: 'https://www.linkedin.com/'
                        display: Handle
                        validate: required
                    -
                      handle: prefix
                      field:
                        type: hidden
                        default: 'https://www.linkedin.com/'
                mastodon:
                  display: Mastodon
                  fields:
                    -
                      handle: handle
                      field:
                        input_type: text
                        type: text
                        localizable: true
                        listable: hidden
                        display: URL
                        validate: required
                pinterest:
                  display: Pinterest
                  fields:
                    -
                      handle: handle
                      field:
                        input_type: text
                        type: text
                        localizable: true
                        listable: hidden
                        prepend: 'https://www.pinterest.com/'
                        display: URL
                        validate: required
                    -
                      handle: prefix
                      field:
                        type: hidden
                        default: 'https://www.pinterest.com/'
                twitter:
                  display: Twitter
                  fields:
                    -
                      handle: handle
                      field:
                        input_type: text
                        type: text
                        localizable: true
                        listable: hidden
                        prepend: 'https://www.twitter.com/'
                        display: Handle
                        validate: required
                    -
                      handle: prefix
                      field:
                        type: hidden
                        default: 'https://www.twitter.com/'
                vimeo:
                  display: Vimeo
                  fields:
                    -
                      handle: handle
                      field:
                        input_type: text
                        type: text
                        localizable: true
                        listable: hidden
                        prepend: 'https://www.vimeo.com/'
                        display: Handle
                        validate: required
                    -
                      handle: prefix
                      field:
                        type: hidden
                        default: 'https://www.vimeo.com/'
                youtube:
                  display: YouTube
                  fields:
                    -
                      handle: handle
                      field:
                        input_type: text
                        type: text
                        localizable: true
                        listable: hidden
                        prepend: 'https://www.youtube.com/'
                        display: Handle
                        validate: required
                    -
                      handle: prefix
                      field:
                        type: hidden
                        default: 'https://www.youtube.com/'
              type: replicator
              listable: hidden
              localizable: true
              display: 'Social media'
```

### Environment

```yaml
Environment
Application Name: V4
Laravel Version: 9.52.4
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: dev-master PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 1.0
studio1902/statamic-peak-commands: 1.26
studio1902/statamic-peak-seo: 1.7
studio1902/statamic-peak-tools: 2.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
