### ISSUE TITLE
[4.x] Hover state red buttons

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7764]
### Bug description

The hover state of red buttons is missing styling:

<img width="283" alt="Screenshot 2023-03-25 at 14 26 21" src="https://user-images.githubusercontent.com/69107412/227719952-c5dddfd8-63d4-4edb-8d0d-a098252deec4.png">
<img width="194" alt="Screenshot 2023-03-25 at 14 26 13" src="https://user-images.githubusercontent.com/69107412/227719955-90d13357-9522-49ef-adb5-547e8bd0e65f.png">

### How to reproduce

Hover a red button.

### Environment

```yaml
Environment
Application Name: V4
Laravel Version: 9.52.4
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: dev-master PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 1.0
studio1902/statamic-peak-commands: 1.26
studio1902/statamic-peak-seo: 1.7
studio1902/statamic-peak-tools: 2.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
