### ISSUE TITLE
[4.x] New replicator errors

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7766]
### Bug description

When you update to v4 and already have a replicator in place with data and want to save an entry you get an error:

<img width="618" alt="Screenshot_2023-03-25_at_14 22 14" src="https://user-images.githubusercontent.com/69107412/227721255-b3f7909e-33f0-439a-add5-988048b8c352.png">

There's nothing in the laravel.log. As soon as I moved replicator sets into groups I could save existing entries again. 

UPDATE:
I'm still getting the error. Not sure why. 

### How to reproduce

Easiest might be to install Peak, upgrade it to v4 and try to save the homepage.

### Environment

```yaml
Environment
Application Name: V4
Laravel Version: 9.52.4
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: dev-master PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 1.0
studio1902/statamic-peak-commands: 1.26
studio1902/statamic-peak-seo: 1.7
studio1902/statamic-peak-tools: 2.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
