### ISSUE TITLE
[4.x] Replicator set back button shows title of current set

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7767]
### Bug description

When you use groups in the new (awesome) replicator picker and navigate into a group, the back button shows the title of the current group you're in. This implies the back button takes you back to where you already are.

These are groups.
<img width="357" alt="Screenshot 2023-03-25 at 14 52 32" src="https://user-images.githubusercontent.com/69107412/227721476-c247af14-f494-4019-89be-9bafd506cd14.png">

Let's go into the interactive group. The back button includes the label 'Interactive'.
<img width="370" alt="Screenshot 2023-03-25 at 14 52 37" src="https://user-images.githubusercontent.com/69107412/227721484-ef20db69-dfbf-44c0-9f7d-5d40023c0f62.png">

It might be an idea to show 'Back' instead of the current group name. And show the current group name next to the back button.

### How to reproduce

1. Make a group
2. Go into the group
3. Look at the back button

### Environment

```yaml
Environment
Application Name: V4
Laravel Version: 9.52.4
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: dev-master PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 1.0
studio1902/statamic-peak-commands: 1.26
studio1902/statamic-peak-seo: 1.7
studio1902/statamic-peak-tools: 2.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
