### ISSUE TITLE
GraphQL doesn't load set from replicator field

### ISSUE THREAD

**Issue by lotarbo** [statamic/cms#7772]
### Bug description

I have collection Pages with two blueprints: Page and Home.
In both blueprints, i have replicator field `blocks` with sets. So it works like page builder.
In Home blueprint i have 4 sets: 
<img width="1461" alt="image" src="https://user-images.githubusercontent.com/1766890/227923107-1557cbc4-cede-4340-9f8b-5f5f3ceaab06.png">
in Page only 3 
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/1766890/227923251-d3952672-4d11-4588-bd26-d2e31599d9fc.png">
Reason: i need different blocks in different page types.

So in graphiql i see this:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/1766890/227923541-5778c322-5ef7-4ae9-905f-dc7b73840919.png">
<img width="258" alt="image" src="https://user-images.githubusercontent.com/1766890/227923600-40136a64-99ad-4c19-97d5-42fa98a0e8dc.png">

But if i add Brands Set to Page blueprint - i can see what i need in Home type
<img width="241" alt="image" src="https://user-images.githubusercontent.com/1766890/227923895-4f857653-ced0-4bf5-81e7-6ee64f63b949.png">

### How to reproduce

Create different blueprints in one collection with same replicator field name but different sets

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.2.3
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: some-site.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
