### ISSUE TITLE
[4.x] Bard allow fullscreen option gone

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7779]
### Bug description

It seems the `Allow fullscreen` config option is gone from the Bard field configuration in Fieldsets. Or maybe it works differently in v4 but I couldn't find a similar option. Or am blind. Who knows.

### How to reproduce

Add a bard field and look for the `Allow fullscreen` option.

### Environment

```yaml
Environment
Application Name: V4
Laravel Version: 9.52.4
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: dev-master PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 1.0
studio1902/statamic-peak-commands: 1.26
studio1902/statamic-peak-seo: 1.7
studio1902/statamic-peak-tools: 2.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
