### ISSUE TITLE
Bard add set button positioned incorrectly after an image

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#7780]
### Bug description

The add set button is positioned incorrectly when the Bard field contains an image and the cursor is placed after the image:

![Screenshot 2023-03-28 at 09 56 19](https://user-images.githubusercontent.com/126740/228185581-4cb54652-a787-446f-a336-0783cf25fb5c.png)

### How to reproduce

Add an image to a Bard field and place the cursor after the image.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.1.16
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: mysite-v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
