### ISSUE TITLE
[4.x] Replicator set picker positioned incorrectly when adding between sets

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#7781]
### Bug description

The replicator set picker is positioned incorrectly when adding sets between existing ones:

![Screenshot 2023-03-28 at 09 57 16](https://user-images.githubusercontent.com/126740/228186177-71576ebe-0d23-4933-8705-dbb236443216.png)

### How to reproduce

Add a set to a replicator between existing sets.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.1.16
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: mysite-v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
