### ISSUE TITLE
[4.x] Unable to scroll page after adding an image to a Bard field

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#7782]
### Bug description

After adding an image to a Bard field the page is no longer scrollable, looks like the `overflow: hidden` isn't being removed from the body when the overlay closes. I've only noticed this with Bard images, it doesn't seem to happen when picking with the assets field.

### How to reproduce

Add an image to a Bard field, try to scroll.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.1.16
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: mysite-v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
