### ISSUE TITLE
[4.x] Blueprint Builder: handle not autocompleted

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#7783]
### Bug description

It seems autocompleting the ``handle`` input stops after you pause typing for too long. I would expect autocompletion to work as long as I focus the title input for the first time.

<img width="1692" alt="image" src="https://user-images.githubusercontent.com/9936988/228188958-00862210-da52-489f-ad8c-fd81fbadfb60.png">

### How to reproduce

Go into a blueprint and try adding any field. Type a bit slower or pause for a second in between when filling the title field. Autocompleting the handle stops.

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 9.52.4
PHP Version: 8.1.17
Composer Version: 2.2.21
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.1 Solo
```

### Installation

Existing Laravel app

### Antlers Parser

None
