### ISSUE TITLE
[4.x] Set Group: Confirm button not overflown by icon dropdown

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#7784]
### Bug description

<img width="647" alt="image" src="https://user-images.githubusercontent.com/9936988/228191099-4850bc2f-bd14-4bb4-880b-ab8e7bd7c8d3.png">

### How to reproduce

Try adding a set to a bard or replicator.

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 9.52.4
PHP Version: 8.1.17
Composer Version: 2.2.21
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
