### ISSUE TITLE
[4.x] Bard content saving incorrectly and not rendering

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7785]
### Bug description

I have a Bard in a Replicator. Content from Bard saves in a different way to the Markdown file then in 3.x. Therefor it also doesn't render in the frontend. 

This is the how the `article` (Bard) data is saved in a replicator called `page_builder`.

```yaml
page_builder:
  -
    id: lfs1rtym
    article: '[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Test entry"}]},{"type":"paragraph","content":[{"type":"text","text":"This is a Bard in a replicator."}]}]'
    type: article
    enabled: true
```

### How to reproduce

1. Install peak.
2. Create new entry and add a Bard to the page builder.
3. Add some content

### Environment

```yaml
Environment
Application Name: Statamic Peak Development
Laravel Version: 9.52.4
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: dev-master PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: dev-feature/v4-support
studio1902/statamic-peak-commands: dev-feature/v4-support
studio1902/statamic-peak-seo: dev-feature/v4-support
studio1902/statamic-peak-tools: 2.3
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
