### ISSUE TITLE
[4.x] Clicking the Bard add link button scrolls to top of page

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#7787]
### Bug description

If you're scrolled down the page and click the Bard add link button the scroll position moves to the top of the page.

### How to reproduce

Add a link to a Bard field

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.1.16
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: mysite-v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
