### ISSUE TITLE
Remove Collections collections config field

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#779]
``` yaml
field:
  collections:
    - diary
    - pages
  mode: select
  type: collections
```

With this config, I still see all the collections in the site as selectable.

![image](https://user-images.githubusercontent.com/44739/66582318-94a07c00-eb4f-11e9-9768-14d62e0e2ce2.png)
