### ISSUE TITLE
Antlers: Updating a variable inside the user loop isn't available outside the user loop

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#7796]
### Bug description

I've just discovered an issue with Antlers where if you update a custom variable instead a user loop, it's only updated within that loop.

Once I try and use it outside the user loop, it's as if it was never updated.

### How to reproduce

```antlers
{{ userHasAccessToCourse = false }}

{{ if logged_in }}
    {{ user }}
        {{ if courses | pluck:id | contains(page:id) }}
            {{ userHasAccessToCourse = true }}
            {{ userHasAccessToCourse | dump }} -- This is returning true
        {{ /if }}
    {{ /user }}
{{ /if }}

{{ userHasAccessToCourse | dump }} -- This is returning false
```

In my case, `courses` is an entries field on my user blueprint. 

@JohnathonKoster has provided me with a workaround which is to set the user to a variable, then do the if statements on that user.

```antlers
{{ userHasAccessToCourse = false }}

{{ if logged_in }}
    {{ _currentUser = {user}; }}
    {{ if _currentUser.courses | pluck:id | contains(page:id) }}
        {{ userHasAccessToCourse = true }}
        {{ userHasAccessToCourse | dump }}
    {{ /if }}
{{ /if }}

{{ userHasAccessToCourse | dump }}
```

### Environment

```yaml
Environment
Application Name: SiteName
Laravel Version: 9.51.0
PHP Version: 8.2.3
Composer Version: -
Environment: local
Debug Mode: ENABLED
URL: sitename.com.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: USD
Gateways: Stripe, PayPal
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\UserCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.3 PRO

Statamic Addons
doublethreedigital/simple-commerce: 4.5.7
jezzdk/statamic-wp-import: 1.6.0
studio1902/statamic-peak-browser-appearance: 1.0
studio1902/statamic-peak-commands: 1.20
studio1902/statamic-peak-seo: 1.2.1
studio1902/statamic-peak-tools: 1.1
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
