### ISSUE TITLE
Toogle Feild Type wiping data

### ISSUE THREAD

**Issue by ottz0** [statamic/cms#7798]
### Bug description

I use the toggle field type to show either an image or a video, so If the toggle on on (true) it shows the video input or if it's false it will show the user to input an image asset.

Older versions of statamic would keep the data when toggling between 2 states but now the data is wiped out and you have to input the data again to display
### How to reproduce

Create a toggle in the blueprint and add 2 text areas with data inside to toggle between. Between each on off will lose data between each state.

### Environment

```yaml
Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
