### ISSUE TITLE
[4.x] Can't drag Fields when adding Bard or Replicator to Edit Form

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7800]
### Bug description

When adding a field that contains other draggable fields (such as Bard or Replicator), the draggable state of the Edit Form Fields is overridden, preventing the fields from being dragged.

![2023-03-29 12 27 09](https://user-images.githubusercontent.com/1102712/228506510-ab346073-4324-43d9-b7b8-0be16675dde8.gif)

### How to reproduce

Add a Bard or Replicator Field to a Fieldset or Blueprint.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.2.1
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: statamic-v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

Fix from PR #7799 seems related, but cannot be used for V4.
