### ISSUE TITLE
[4.0] Adding view on the collection page is misleading 

### ISSUE THREAD

**Issue by palmiak** [statamic/cms#7807]
### Bug description

If you create a view and then, while having it active, press "+" - the add view behaves as a rename, not add.

Also, creating a second view with the same parameters as the previous one sometimes gets overwritten. It's a bit random and I couldn't catch the exact rule here.

### How to reproduce

Here is the video showing the behavior.
https://user-images.githubusercontent.com/2342458/228995814-5fc0eaa8-eb31-4574-a677-f3c0dc5fefb8.mp4

### Environment

```yaml
Environment
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.1 Solo
```

### Installation

Existing Laravel app

### Antlers Parser

regex (default)
