### ISSUE TITLE
Replacing an Asset with an existing filename appends timestamp to new filename

### ISSUE THREAD

**Issue by motion-work** [statamic/cms#7808]
### Bug description

The problem occurs when I want to replace a file with a new one (with the identical file name). The filename is always supplemented with a sequence of numbers after the replacement and I have to rename the documents in a 2nd step (see screenshots).

Since I want to replace this file, I find it an unnecessary extra step. Especially when I want to replace multiple files.

The file name should remain unchanged.
![example_filename](https://user-images.githubusercontent.com/11538632/229087016-61574690-920c-40a4-8058-7aa405b169ca.png)

### How to reproduce

Replace an existing file with the same exact filename.

### Environment

```yaml
Environment
Laravel Version: 9.51.0
PHP Version: 8.1.13
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Statamic
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.4.1 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
