### ISSUE TITLE
Bard removes domain

### ISSUE THREAD

**Issue by Sukrams** [statamic/cms#7813]
### Bug description

When a URL is pasted into a Bard editor via Copy & Paste, the domain is removed, leaving only the path. This fragment is then also correctly linked.

So in the example I wanted to paste https://statamic.com/blog/statamic-3.4 as URL and /blog/statamic-3.4 is finally displayed in the editor (and correctly linked).

![statamic](https://user-images.githubusercontent.com/15678176/229281177-e522286e-0358-45e6-89d3-627d344cd137.gif)

This occurs in my existing Statamic installation (3.4.7), as well as in a fresh installation.

### How to reproduce

Copy an URL and paste it into a bard editor.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.5
PHP Version: 8.2.4
Composer Version: 2.1.14
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
