### ISSUE TITLE
Entries field without entries still renders once

### ISSUE THREAD

**Issue by mmodler** [statamic/cms#7815]
### Bug description

We have an entries field without any entries attached to it, but the frontend loop still runs once instead of never.

Seems like other loops might be affected, too (assets...).

### How to reproduce

Add an simple entries field to a blueprint:

```
-
  handle: entries_test
  field:
    mode: default
    create: true
    display: 'entries test'
    type: entries
    icon: entries
    listable: hidden
    instructions_position: above
    visibility: visible
    always_save: false
```

And add it to your template:
```
{{ entries_test }}
    {{ dump }}
{{ /entries_test }}
```

Dump should not be executed, but it does!

### Environment

```yaml
Laravel Version: 9.52.0
PHP Version: 8.0.27
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.68 PRO
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)
