### ISSUE TITLE
Select Fieldtype - Options ordering

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#7817]
### Bug description

As long as I'm allowed to order the Options in a Select fieldtype I would expect them to not be reordered when saving. As it is now it is reordered alphabetically after saving, and forces me to add something to the key to keep the order I want.

![Screenshot 2023-04-03 at 15 12 39](https://user-images.githubusercontent.com/1135679/229520860-44b9eba1-0b40-4e8d-aa08-af20921c9878.png)

### How to reproduce

Create a Select fieldtype, add two options (in this order)
- Anchor
- Baloon

and press Finish and save the fieldset. Log out and in, and try to edit the fieldtype, you will se the order is:

- Baloon
- Anchor

### Environment

```yaml
*Environment*
Application Name: Properti Stage
Laravel Version: 9.52.5
PHP Version: 8.0.28
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: properti-stage.test
Maintenance Mode: OFF

*Cache*
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

*Drivers*
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

*Statamic*
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 PRO

*Statamic Addons*
aryehraber/statamic-captcha: 1.9.1
r8edge/imagemap: dev-main
r8edge/properti-dashboard: dev-main
r8edge/welcome-widget: dev-main
statamic/eloquent-driver: 1.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
