### ISSUE TITLE
Blade Directive `@nocache` shows NOCACHE_PLACEHOLDER

### ISSUE THREAD

**Issue by jhhazelaar** [statamic/cms#7820]
### Bug description

I'm using `@nocahe` blade directive for excluding auth dropdown. This give a `NOCACHE_PLACEHOLDER` text in non statamic routes. In the comments of issue #6682 the tip is to add `statamic.web` middleware to the custom route.

With that middleware the nocache placeholder is gone, but then the auth in other section of the page get cached. This is a problem with route that display user data.

User data on the frontend are laravel eloquent users.

### How to reproduce

Example repo: https://github.com/jhhazelaar/laravel-statamic-nocache-placeholder

Set `STATAMIC_STATIC_CACHING_STRATEGY` to `half`.

Register two users in the application. Login and go to dashboard. Login second user and go to dashboard. See username of first user in dashboard.

### Environment

```yaml
Environment
Application Name: Laravel Statamic Nocache Placeholder
Laravel Version: 9.52.5
PHP Version: 8.2.4
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: laravel-statamic-nocache-placeholder.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: half
Version: 3.4.7 Solo
```

### Installation

Existing Laravel app

### Antlers Parser

None
