### ISSUE TITLE
Two small styling issue in v4.0.0-alpha.2

### ISSUE THREAD

**Issue by aerni** [statamic/cms#7832]
### Bug description

I came across these two little styling issues in [v4.0.0-alpha.2](https://github.com/statamic/cms/releases/tag/v4.0.0-alpha.2).

Whenever a modal is opened in the blueprint editor:

![CleanShot 2023-04-05 at 10 16 54@2x](https://user-images.githubusercontent.com/23167701/230023199-7a03bfed-9327-4c80-bc29-a0df3e1f83a1.png)

Whenever the fieldtype selector is open:

![CleanShot 2023-04-05 at 10 15 00@2x](https://user-images.githubusercontent.com/23167701/230022747-0c947086-4157-4103-be48-a71bc01c3aef.png)

### How to reproduce

Install v4.0.0-alpha.2 and follow the description above.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.5
PHP Version: 8.1.13
Composer Version: 2.5.0
Environment: local
Debug Mode: ENABLED
URL: statamic-v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
