### ISSUE TITLE
Improvements of default displayed columns

### ISSUE THREAD

**Issue by aerni** [statamic/cms#7834]
### Bug description

Not a bug but related to [v4.0.0-alpha.2](https://github.com/statamic/cms/releases/tag/v4.0.0-alpha.2).

Can we move the title to the front in the listing view by default? The title is the only clickable field that opens the entry. And it's a little off that it's not the first item. Also, I'd probably move the status to the back by default too.

<img width="1483" alt="CleanShot 2023-04-05 at 10 36 16@2x" src="https://user-images.githubusercontent.com/23167701/230027527-13d60675-bdcb-40b8-a7bc-590ba174675c.png">

### How to reproduce

Nothing to reproduce.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.5
PHP Version: 8.1.13
Composer Version: 2.5.0
Environment: local
Debug Mode: ENABLED
URL: statamic-v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
