### ISSUE TITLE
Missing spacing in imported fieldsets

### ISSUE THREAD

**Issue by aerni** [statamic/cms#7836]
### Bug description

A tiny little UI improvement. There is no spacing:

![CleanShot 2023-04-05 at 12 01 10@2x](https://user-images.githubusercontent.com/23167701/230048921-77d7a1a5-8c59-46d5-acfa-e4334b165a7d.png)

### How to reproduce

Import a fieldset.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.5
PHP Version: 8.1.13
Composer Version: 2.5.0
Environment: local
Debug Mode: ENABLED
URL: statamic-advanced-seo-v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.2 Solo

Statamic Addons
aerni/advanced-seo: dev-feature/statamic-v4
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
