### ISSUE TITLE
[4.x] Assets can only be selected when clicking the thumbnail

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#7840]
### Bug description

When selecting assets clicking on the label or white space doesn't select them, it only works if you click the thumbnail or icon:

https://user-images.githubusercontent.com/126740/230051805-2a35b2b4-09ed-4da4-9d11-309eb34d0b4a.mp4

### How to reproduce

Try to select an asset by clicking on it's label.

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
