### ISSUE TITLE
[4.x] Replicator/bard icon picker modal overflow hidden

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7850]
### Bug description

When you use the icon picker on a Bard or Replicator in the blueprint editor the select box isn't completely visible.
<img width="862" alt="Screenshot 2023-04-05 at 09 22 25" src="https://user-images.githubusercontent.com/69107412/230158511-41051983-fe98-4bf6-abb5-79b3d1eb96ca.png">

### How to reproduce

Try to set an icon in a replicator/bard set group.

### Environment

```yaml
Application Name: Statamic Peak Development
Laravel Version: 9.52.5
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.2 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: dev-feature/v4-support
studio1902/statamic-peak-commands: dev-feature/v4-support
studio1902/statamic-peak-seo: dev-feature/v4-support
studio1902/statamic-peak-tools: dev-feature/v4-support
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
