### ISSUE TITLE
`[ANTLR_008]: Unclosed "if" control structure` on partial with named slot

### ISSUE THREAD

**Issue by johncarter-** [statamic/cms#7851]
### Bug description

`home.antlers.html`:
```
{{ collection:articles taxonomy:categories="{right_category:slug}" limit="3" sort="date:desc" }}
    {{ partial:article-link class="py-6" showImage="true" }}
        {{ slot:footer }}
            <hr class="hidden md:block max-w-[14rem] mt-6">
        {{ /slot:footer }}
    {{ /partial:article-link }}
{{ /collection:articles }}
```

`article-link.antlers.html`:
```
<a href="{{ url }}" class="block {{ class }}">
    {{ if showImage }}
        <div class="{{ image169 ? 'aspect-w-16 aspect-h-9' : 'aspect-w-3 aspect-h-1' }} mb-4">
            {{ if featured_image }}
                {{ responsive src="{featured_image}" class="object-cover w-full h-full" style="object-position: '{featured_image:focus | background_position}'" glide:width="800" }}
            {{ else }}
                <div class="bg-app-light-grey w-full h-full"></div>
            {{ /if }}
        </div>
    {{ /if }}
    <h4 class="mb-2 font-extrabold {{ textLg ? 'text-xl' : '' }}">{{ title }}</h4>

    <p class="text-xxs">{{ date | format('F j, Y') }}</p>
    {{ if showExcerpt }}
        <div class="mt-4 text-sm">
            {{ excerpt = legacy_content_html ?? content | raw | bard_text }}
            {{ excerpt | raw | stripTags | safe_truncate(150) }}...
        </div>
    {{ /if }}
    {{ slot:footer }}
</a>
```

### How to reproduce

Try running the code above

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 9.52.4
PHP Version: 8.1.14
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.4.5 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 2.11.0
rias/statamic-redirect: 2.6.0
spatie/statamic-responsive-images: 2.15.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
