### ISSUE TITLE
Hide sections with no visible fields

### ISSUE THREAD

**Issue by aerni** [statamic/cms#7855]
### Bug description

If all fields of a blueprint section are conditionally hidden, the section is empty and looks super weird. It's probably best to hide a section when no fields are visible.

<img width="948" alt="CleanShot 2023-04-05 at 21 41 21@2x" src="https://user-images.githubusercontent.com/23167701/230187656-33cb6449-ce21-4b49-9f4a-598a8906fd2a.png">

### How to reproduce

1. Add a section with a conditional field
2. Make sure the field is conditionally hidden

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.5
PHP Version: 8.1.13
Composer Version: 2.5.0
Environment: local
Debug Mode: ENABLED
URL: statamic-advanced-seo-v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.2 Solo

Statamic Addons
aerni/advanced-seo: dev-feature/statamic-v4
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
