### ISSUE TITLE
Toggle field UI bug

### ISSUE THREAD

**Issue by aerni** [statamic/cms#7856]
### Bug description

The UI of a read-only toggle field is a little off:

<img width="197" alt="CleanShot 2023-04-05 at 22 20 51@2x" src="https://user-images.githubusercontent.com/23167701/230201349-ba33a537-0de4-4384-bbad-c7a623f52001.png">

### How to reproduce

Add a toggle field

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.5
PHP Version: 8.1.13
Composer Version: 2.5.0
Environment: local
Debug Mode: ENABLED
URL: statamic-advanced-seo-v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.2 Solo

Statamic Addons
aerni/advanced-seo: dev-feature/statamic-v4
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
