### ISSUE TITLE
Bard "Add set" moves cursor one character to the left before inserting.

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#7858]
### Bug description

If I set the cursor at the end of the line, press + and add a set, then the set is inserted before the last character on the line.

https://user-images.githubusercontent.com/1135679/230217301-b82d8567-6aba-400b-a286-b2aad4336255.mov

### How to reproduce

Explained above and illustrated with video.

### Environment

```yaml
Environment
Application Name: Properti Stage
Laravel Version: 9.52.5
PHP Version: 8.0.28
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: properti-stage.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
r8edge/imagemap: dev-main
r8edge/properti-dashboard: dev-main
r8edge/welcome-widget: dev-main
statamic/eloquent-driver: 1.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
