### ISSUE TITLE
Filtering collections using `is_after` not working properly on multisite

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7860]
### Bug description

Possibly related to: https://github.com/statamic/cms/issues/2688

On a multisite environment I use the following code:

```antlers
{{ collection:vacancies sort="date:desc" paginate="true" limit="12" as="items" expires:is_after="{today}" }}
    {{ unless no_results }}
        {{ items }}
            {{ partial src="volt-core::partials/components/vacancies_item" class="md:col-span-6" }}
        {{ /items }}
    {{ else }}
        <div class="md:col-span-6">
            {{ trans:strings.no_results }}
        </div>
    {{ /unless }}
    {{ partial src="statamic-peak-tools::components/pagination" class="md:col-span-12" }}
{{ /collection:vacancies }}
```

This only returns one result which is incorrect. On other locales this code returns zero results which is also incorrect.

When I change the filter to `expires:gt="{today format='Y-m-d'}"` the correct posts start to show up. So that's a nice workaround.

I wasn't able to reproduce this on a non multisite environment. 

### How to reproduce

DM me for repo access. 

### Environment

```yaml
Environment
Application Name: Volt Europa
Laravel Version: 9.52.5
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: volteuropa.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 1.0
studio1902/statamic-peak-commands: 1.27
studio1902/statamic-peak-seo: 1.7
studio1902/statamic-peak-tools: 2.5
volt/volt-core: dev-main
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
