### ISSUE TITLE
[4.x] Overlapping replicator popovers 

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7861]
### Bug description

On `dev-master` you can open multiple replicator popovers by clicking on the various plus buttons.
<img width="849" alt="Screenshot 2023-04-06 at 19 42 38" src="https://user-images.githubusercontent.com/69107412/230455364-d2132c07-b5f0-44d5-97bc-1cb6c6a6430e.png">

### How to reproduce

Click on the big replicator plus button
Click on an inbetween sets replicator plus button

### Environment

```yaml
Environment
Application Name: Statamic Peak Development
Laravel Version: 9.52.5
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: dev-master PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: dev-feature/v4-support
studio1902/statamic-peak-commands: dev-feature/v4-support
studio1902/statamic-peak-seo: dev-feature/v4-support
studio1902/statamic-peak-tools: dev-feature/v4-support
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
