### ISSUE TITLE
Alignment of errors on Replicator fields

### ISSUE THREAD

**Issue by geertjanknapen1** [statamic/cms#7865]
### Bug description

So I wrote a custom validation that checks if all the items in the Replicator set are unique.

It works fine, but when the validation does not pass, the error message is misaligned, can I edit the styling for these myself somewhere?

<img width="181" alt="image" src="https://user-images.githubusercontent.com/33750300/229087275-fe21c350-e44c-4998-9361-ec17dbbf3547.png">

<img width="449" alt="image" src="https://user-images.githubusercontent.com/33750300/229086998-85586a2a-e5a5-4067-a120-5fd277a5b548.png">

### How to reproduce

Make a Replicator field fail any kind of validation.

! Has to be on the replicator fields, not one of its sets.

### Environment

```yaml
Environment
Application Name: <my_url>
Laravel Version: 9.52.5
PHP Version: 8.2.4
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: <my_url>.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: array
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.4.3 PRO

Statamic Addons
spatie/statamic-responsive-images: 2.15.2
statamic/eloquent-driver: 1.2.0
withcandour/aardvark-seo: 2.0.30
```

### Installation

Existing Laravel app

### Antlers Parser

regex (default)

### Additional details

Using a database setup, shouldn't matter though.
