### ISSUE TITLE
Various UI bugs

### ISSUE THREAD

**Issue by aerni** [statamic/cms#7866]
### Bug description

Missing utility icons:

<img width="979" alt="CleanShot 2023-04-06 at 17 14 22@2x" src="https://user-images.githubusercontent.com/23167701/230616638-0a1c4bc4-17fc-4c00-8d2d-ebc56e69d107.png">

A lonely border in the sidebar of a term:

![CleanShot 2023-04-06 at 17 14 42@2x](https://user-images.githubusercontent.com/23167701/230616728-da5f6a37-24d6-4c75-8277-61cd77f4d1c9.png)

Site switcher not centered:

![CleanShot 2023-04-06 at 17 19 25@2x](https://user-images.githubusercontent.com/23167701/230616914-0234e06d-50e1-43c6-8e14-b3a8227d9339.png)

The padding of section fields is larger than the padding of the section title and instructions above:

![CleanShot 2023-04-06 at 17 51 44@2x](https://user-images.githubusercontent.com/23167701/230617041-0fdac910-e561-470c-bf68-98c1b485baa3.png) 

### How to reproduce

Should be self-explanatory

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.5
PHP Version: 8.1.13
Composer Version: 2.5.0
Environment: local
Debug Mode: ENABLED
URL: statamic-v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
