### ISSUE TITLE
Git 'resolving deltas' being reported as errors.

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#7874]
### Bug description

We have git integration turned on and whenever a push is done we get an error in our log.

### How to reproduce

1. Turn on git integration
2. Push something?

Sorry not sure the actual steps, except that's it's now occurring on all our updated (to 3.4.x) sites.

### Logs

```shell
Error: {"message":"Git Process: remote: Resolving deltas: 0% (0/5) \rremote: Resolving deltas: 20% (1/5) \rremote: Resolving deltas: 40% (2/5) \rremote: Resolving deltas: 60% (3/5) \rremote: Resolving deltas: 80% (4/5) \rremote: Resolving deltas: 100% (5/5) \rremote: Resolving deltas: 100% (5/5), completed with 5 local objects.","context":[],"level":400,"level_name":"ERROR","channel":"production","datetime":"2023-04-07T13:52:25.827186-08:00","extra":[],"formatted":"[2023-04-07T13:52:25.827186-08:00] production.ERROR: Git Process: remote: Resolving deltas: 0% (0/5) remote: Resolving deltas: 20% (1/5) remote: Resolving deltas: 40% (2/5) remote: Resolving deltas: 60% (3/5) remote: Resolving deltas: 80% (4/5) remote: Resolving deltas: 100% (5/5) remote: Resolving deltas: 100% (5/5), completed with 5 local objects. [] []\n"}
```

### Environment

```yaml
Application Name: Statamic
Laravel Version: 9.52.5
PHP Version: 8.2.4
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: zakat.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 12
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.4.7 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
aryehraber/statamic-impersonator: 2.4.1
doublethreedigital/runway: 4.2.2
edalzell/forma: 1.3.0
jonassiewertsen/statamic-livewire: 2.11.0
statamic/seo-pro: 4.0.1
transformstudios/events: 4.2.0
transformstudios/front: 1.11.0
transformstudios/github: dev-main
transformstudios/memorial: dev-main
transformstudios/review: 3.8.1
transformstudios/simple: dev-feature/new-commerce-report
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7h0sv)
