### ISSUE TITLE
Error: collection does not have any visible blueprints. At least one must not be hidden.

### ISSUE THREAD

**Issue by hlorofos** [statamic/cms#7879]
### Bug description

Admin user creates one blueprint and then set it as the "Hidden"
(Hides the blueprint from the create buttons in the CP)

Afterwards there will be no way to create an entity for the collection. There will be exception
`The *** collection does not have any visible blueprints. At least one must not be hidden.`

Additionally you cannot un-hide the collection from the Blueprints editor. Although the save button doesn't display any error, in the result `hide: true` will be still in the collection yaml file.

### How to reproduce

- go to Collections
- press Create collection
- Create Collection with any data
- press Configure Blueprints
- select the blueprint
- Edit Blueprint, set Hidden toggle, press Save
- Navigate to the collections menu and click on the collection you just created

### Environment

```yaml
Environment
Application Name: kapusta
Laravel Version: 9.52.4
PHP Version: 8.2.2
Composer Version: 2.5.2
Environment: local
Debug Mode: ENABLED
URL: kapusta.test/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 PRO
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
