### ISSUE TITLE
If a user is found via OAuth ID, its attributes aren't updated

### ISSUE THREAD

**Issue by grantholle** [statamic/cms#7882]
### Bug description

After the initial relationship with the oauth provider and subsequent logins, if a user is found via `findByOAuthId`, it just [returns the user](https://github.com/statamic/cms/blob/3.4/src/OAuth/Provider.php#L37) without updating its attributes.

### How to reproduce

Log in using an oauth provider. After the initial login, add a callback for updating user data using a `withUserData` for the provider. The callback will not be called.

### Environment

```yaml
Application Name: Statamic
Laravel Version: 9.52.5
PHP Version: 8.2.3
Composer Version: 2.6-dev+4e1774518002b0be4365fe62ce220b2011c2b4bf
Environment: local
Debug Mode: ENABLED
URL: tws-rak.test
Maintenance Mode: OFF
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
