### ISSUE TITLE
Can't preview / download assets from Control Panel Form Submissions when using "List" Mode

### ISSUE THREAD

**Issue by ChrisWorkhouse** [statamic/cms#7884]
### Bug description

When you have a form with a file upload, you cannot download of view the asset from the Form Submission page in the Control Panel. You can still preview and download the assets from the Asset section in the Control Panel.

This issue exists when using the List Mode in the upload field.

![image](https://user-images.githubusercontent.com/23635988/231138989-5c8b521c-63bf-4c54-88d4-cfebf9a8ac44.png)

### How to reproduce

1. Create a new form and blueprint with an asset upload and use "List" mode (which is default)
2. Submit an example form submission with a file
3. Log in to the CP as a Super User or equivalent admin
4. Go to the form submission in the CP and try and access the file

Note:

- You can still go to Assets and download the file successfully from there.
- I have tried with different file types, in the example above is a PDF - but the same applies if I upload an image such as a JPG (although you do get the correct thumbnail image).
- I have also tried using both the default Assets container and custom continers

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.5
PHP Version: 8.0.7
Composer Version: 2.1.9
Environment: local
Debug Mode: ENABLED
URL: statamic34.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

I did find a previous issue https://github.com/statamic/cms/issues/4514 which seems to be this issue exactly, and while it is marked as fixed this issue still persists on the latest Stamatic version.

I have found that this bug only persists when using the "List" Mode in the File Upload field, so believe the above only fixed the issue for the "Grid" mode.
