### ISSUE TITLE
Can't localise login:form errror/succes messages

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7890]
### Bug description

I'm trying to localise the error and success message in `{{ user:login_form }}` but they remain English. I've tried to add the strings to my `nl.json` file but that doesn't seem to work. 

My _sites.php_:
```php
'sites' => [
    'default' => [
        'name' => config('app.name'),
        'locale' => 'nl_NL',
        'url' => '/',
    ],
],
```

Marco Rieser suggested to rename `nl.json` to `nl_NL.json` and add `'lang' => 'nl_NL'` to my default site. But that also doesn't work and it breaks all other localisable template strings.

### How to reproduce

Use `nl_NL` as a locale
Add a user login form
Add those strings to the nl.json file:

```json
"Invalid credentials.": "Ongeldige inloggegevens.",
"Login successful.": "Ingelogd.",
```

_Note:_ the field does get translated when I add it to `en.json` (but obviously it shouldn't pick up that one).

Or DM me for repo access.

### Environment

```yaml
Environment
Application Name: Stichting Lutje Geluk
Laravel Version: 9.52.5
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: lutjegeluk.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 PRO

Statamic Addons
statamic/eloquent-driver: 1.2.0
studio1902/statamic-peak-browser-appearance: 1.0
studio1902/statamic-peak-commands: 1.27
studio1902/statamic-peak-seo: 1.7
studio1902/statamic-peak-tools: 2.5
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
