### ISSUE TITLE
[4.x] Set handle does not sync with set name when creating

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#7891]
### Bug description

When creating a new set the handle does not sync with the display name:

https://user-images.githubusercontent.com/126740/231434610-c02bfc51-4dde-4568-931c-30741b0308ef.mp4

### How to reproduce

Create a new set and type in a display name.

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.3 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
