### ISSUE TITLE
Nocache tag not playing nice with trans tag

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7893]
### Bug description

I'm using the `nocache` tag for the first time and whenever I add a `trans` tag within it I get the wrong language returned  or no string at all but just the string reference when there isn't a translation available in English:
![Screenshot_2023-04-12_at_15 31 32](https://user-images.githubusercontent.com/69107412/231500353-a2800a16-2376-4a04-a107-b5767caf0e9a.png)

When I remove the nocache tag everything works fine.

### How to reproduce

1. Create a site.
2. Make sure you're using full static caching.
3. You just need one site, set the locale to `'locale' => 'nl_NL'`.
4. Add a string to your layout, like: `{{ trans:strings.my_string }}`.
5. Create a strings file called `strings` and add and translate `my_string`.
6. Visit the page once: see the translated string.
7. Visite the page a second time: see the English string or none if not available.

### Environment

```yaml
Environment
Application Name: Stichting Lutje Geluk
Laravel Version: 9.52.5
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: lutjegeluk.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 PRO

Statamic Addons
statamic/eloquent-driver: 1.2.0
studio1902/statamic-peak-browser-appearance: 1.0
studio1902/statamic-peak-commands: 1.27
studio1902/statamic-peak-seo: 1.7
studio1902/statamic-peak-tools: 2.5
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
