### ISSUE TITLE
Modifiers with arguments result in Statamic\Modifiers\ModifierNotFoundException

### ISSUE THREAD

**Issue by mstratman** [statamic/cms#7895]
### Bug description

Testing exclusively with `{{ title }}` on both the home page and a collection-show page, it seems that any modifier having arguments throws a `Statamic\Modifiers\ModifierNotFoundException`

Modifiers without arguments work fine.

Switching to 'runtime' version in `config//statamic/antlers.php` seems to work (I haven't yet tested extensively - only discovered this was even a thing by the dropdown in this bug report form.

### How to reproduce

`{{ title | regex_replace(' ', '&nbsp;') }}`

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.39.0
PHP Version: 8.0.8
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: diypedals.net.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 Solo

Statamic Addons
rias/statamic-redirect: 2.5.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
