### ISSUE TITLE
Term sidebar UI bug

### ISSUE THREAD

**Issue by aerni** [statamic/cms#7913]
### Bug description

Following Jason's wish in https://github.com/statamic/cms/issues/7866; here's a separate issue for the lonely border in the sidebar of a term:

![image](https://user-images.githubusercontent.com/23167701/232125626-aac961ba-09d4-4bf4-8f1c-9e15e172cbf1.png)

### How to reproduce

Should be self-explanatory

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.5
PHP Version: 8.1.13
Composer Version: 2.5.0
Environment: local
Debug Mode: ENABLED
URL: statamic-v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
