### ISSUE TITLE
[4.x] Bard Fullscreen Mode regression

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7920]
### Bug description

I got some regression issues when testing Bard fullscreen mode, seems coming from PR #7818:

* When toggling Fullscreen Mode, I'm getting an error on error console coming from [FloatingMenu.js](https://github.com/statamic/cms/blob/master/resources/js/components/fieldtypes/bard/FloatingMenu.js#L69)

```
[Vue warn]: Error in beforeDestroy hook: "TypeError: nameOrPluginKey is undefined"
```
* I'm not able to add any Bard Sets in Fullscreen Mode.
* Editor is missing, when closing Fullscreen mode.

![2023-04-16 13 30 31](https://user-images.githubusercontent.com/1102712/232306975-da241226-9945-4ade-8427-18e0346ac319.gif)

### How to reproduce

1. Add a Bard field.
2. Click on "Toggle Fullscreen Mode"

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.2.1
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: statamic-v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
