### ISSUE TITLE
[4.x] Bard Toolbar is not sticky anymore in default fixed mode 

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7921]
### Bug description

![2023-04-16 14 25 09](https://user-images.githubusercontent.com/1102712/232315896-1bf86c3f-0bfb-4603-bd5c-ab84ebf8dcf9.gif)

### How to reproduce

* Add a Bard Field

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.2.1
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: statamic-v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
