### ISSUE TITLE
Make user creation wizard optional

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#7925]
### Bug description

It would be neat to be able to make the user creation wizard optional. It works fine with the default setup, but as soon as you add additional required fields to the User Blueprint, the creation with the wizard will fail.

Another valid option for me would be to make the wizard smarter and make it ask for the required fields as well. Currently, the default fields are hard-coded.

### How to reproduce

Add required fields to the user blueprint and try to create a user with the wizard.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.5
PHP Version: 8.1.17
Composer Version: 2.2.21
Environment: local
Debug Mode: ENABLED
URL: signature.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
