### ISSUE TITLE
Perf issue with computed values 

### ISSUE THREAD

**Issue by dadaxr** [statamic/cms#7931]
### Bug description

First off : I know computed value should be cached to limit performance issue but still I think there is space for optimization in the way they are handled. 

I have a receipt collection with around 20 fields (whose 1 is a computed field), when displaying a blank page with only the title field of a receipt entry (no header, no footer, no meta or whatsoever)  I can see the computed callback for my field has been called 20 around times.  (to test it, I've made my callback increment a value in session and I've checked its value just before laravel terminate the request)

After a little code digging I've found  the reason, you can look at the call stack bellow : 

![image](https://user-images.githubusercontent.com/1267495/232672894-b1eed9e4-7197-4697-9981-43246daa219e.png)

We can see to hydrate the content, we iterate over the entry keys... 

![image](https://user-images.githubusercontent.com/1267495/232673035-00187848-a15e-47bc-b8cd-c334029ace9c.png)

But to get the keys, the code actually fetch all the values (look at the "data->values()" call bellow : 

![image](https://user-images.githubusercontent.com/1267495/232673260-c449922f-f8e9-450b-ae07-ed4e17f15677.png)

That "values()" call trigger the computed value callback later...

That means calling the "AugmentedEntry::keys()" method can be an "heavy" process...  I guess this would be OK if that call was done once (or can be cached some way) 

**BUT** the keys() method is actually called for each field of a collection !

We can see in src/vendor/statamic/cms/src/Data/AbstractAugmented.php

```
public function select($keys = null)
{
        $arr = [];

        $keys = $this->filterKeys(Arr::wrap($keys ?: $this->keys()));

        foreach ($keys as $key) {
            $arr[$key] = $this->get($key);
        }

        return (new AugmentedCollection($arr))->withRelations($this->relations);
}
```

here "$this->keys()" is called only once... good, but then in the foreach loop, we call the $this->get($key) 

```
public function get($handle): Value
{
        $method = Str::camel($handle);

       ...

        if (method_exists($this->data, $method) && collect($this->keys())->contains(Str::snake($handle))) {
            return $this->wrapValue($this->data->$method(), $handle);
        }

        ...
}
```

And we can see the same "keys()" function calls here !  ( `collect($this->keys())` )

That explain why for an entry with around 20 fields ... we call each computed values around 20 times.

Just to add some context, I have a receipt listing page, showing around 25 receipts, to render the page, the computed values is called more that 500 hundred times ... perf goes down quickly... with the actual behavior caching the computed values is not an option it's mandatory... 

One way to improve the perf here would be to cache the entry keys but I guess it could have some side effects... 
Or maybe register the "computed key" somewhere when registering computed values 

` Collection::computed('myCollection', 'myComputedFieldKeyToRegisterSomewhere', function ($entry, $value) {...})`

I'm sure you can figure out other way to improve the logic here.

### How to reproduce

just read the bug desc above

### Environment

```yaml
Environment
Application Name: Statamic leporc
Laravel Version: 9.52.4
PHP Version: 8.1.14
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: leporc.localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.4.5 PRO

Statamic Addons
statamic/seo-pro: 4.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
