### ISSUE TITLE
[4.x] Nested bard fields are a bit broken in fullscreen mode

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#7934]
### Bug description

![Screenshot 2023-04-18 at 12 22 29](https://user-images.githubusercontent.com/126740/232762235-0c8b2343-dfd1-4ca8-9fa7-fe975447303f.png)

### How to reproduce

Nest some Bard fields and open fullscreen mode.

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.4 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
