### ISSUE TITLE
[4.x] Asset grid view is broken

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#7936]
### Bug description

![Screenshot 2023-04-18 at 14 52 03](https://user-images.githubusercontent.com/126740/232799312-53257fd2-174a-49cd-8b86-99b7bb79f45f.png)

### How to reproduce

Check asset grid view

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.4 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
