### ISSUE TITLE
Replicator expand / collapse / fullscreen buttons don't work properly

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7937]
### Bug description

I can only click on their top half because of the plus button winning z-index wise probably.

### How to reproduce

Add a replicator
Click on the buttons

### Environment

```yaml
Environment
Application Name: Statamic Peak Development
Laravel Version: 9.52.5
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.3 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: dev-feature/v4-support
studio1902/statamic-peak-commands: dev-feature/v4-support
studio1902/statamic-peak-seo: dev-feature/v4-support
studio1902/statamic-peak-tools: dev-feature/v4-support
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
