### ISSUE TITLE
How to display validation error under the slug?

### ISSUE THREAD

**Issue by maxi032** [statamic/cms#7946]
### Bug description

If I set the slug of a collection entry as required or even if I add a custom validation rule to it, the validation message should display in red under the input.
How can I do that?

### How to reproduce

add a validation rule 

### Environment

```yaml
Environment
Application Name: statamic
Laravel Version: 9.51.0
PHP Version: 8.2.4
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: array
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.4.3 PRO

Statamic Addons
spatie/statamic-responsive-images: 2.15.2
statamic/eloquent-driver: 1.2.0
withcandour/aardvark-seo: 2.0.30
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
