### ISSUE TITLE
Empty select fieldtypes not returning null when passed through partial

### ISSUE THREAD

**Issue by taylorcammack** [statamic/cms#7952]
### Bug description

I have a `select` fieldtype that doesn't have a value set. The field doesn't appear in the entry markdown file.

```
  -
    handle: site_type
    field:
      options:
        Airport: null
        Commercial: null
        Greenfield: null
        Industrial: null
        Office: null
      clearable: true
      multiple: false
      searchable: true
      taggable: false
      push_tags: false
      cast_booleans: false
      type: select
      listable: hidden
      display: 'Site Type'
      if:
        property_type: 'equals Site'
      width: 50
      instructions_position: above
      visibility: visible
```

I'm passing that value into a partial

```
{{ partial:property/components/item label="Site Type" :item="site_type" }}
```
And inside that partial, checking for a value:

```
{{ if item }}
    {{ label }} - {{ item }}
{{ /if }}
```

Rather than show nothing (the expected behavior) because the value isn't set, it shows the label that I passed in with no item value.

However, if I do this, it works as expected.

```
{{ if site_type }}
  {{ partial:property/components/item label="Site Type" :item="site_type" }}
{{ /if }}
```

When I checked what is being returned, this is what I get:

![Screenshot 2023-04-19 at 11 37 03 AM](https://user-images.githubusercontent.com/2514935/233147822-66ea5381-b934-4186-bd60-2a2b8feee547.jpg)

By contrast, an empty text fieldtype simply returns `null`. It seems that this should be the expected behavior for empty fields. 

### How to reproduce

1. Create a `select` fieldtype.
2. Don't set a value on it.
3. Pass it into a partial with a check to see if the item is set

### Environment

```yaml
Environment
Application Name: Statamic Core
Laravel Version: 9.52.4
PHP Version: 8.1.16
Composer Version: 2.6-dev+4e1774518002b0be4365fe62ce220b2011c2b4bf
Environment: local
Debug Mode: ENABLED
URL: core.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 9
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
encore/encore: dev-main
goldnead/statamic-collapse-fieldtype: 1.0.4
jonassiewertsen/statamic-livewire: 2.11.0
mitydigital/iconamic: 1.1.2
rias/statamic-data-import: 1.2.2
simonhamp/statamic-heroicons: 1.1.0
spatie/statamic-responsive-images: 3.1.3
webographen/statamic-dynamic-token: 1.0.0
```

### Installation

Other (please explain)

### Antlers Parser

runtime (new)
