### ISSUE TITLE
[Search] Changes in config/statamic/search.php have no effect

### ISSUE THREAD

**Issue by baxterandbailey-dan** [statamic/cms#7954]
### Bug description

Changes I'm making to config/statamic/search.php are being ignored.

I've tried adding a new index:

```
'pages' => [
            'driver' => 'local',
            'searchables' => ['collection:pages'],
            'fields' => ['title'],
        ],
```
And have also added `search_index: pages` to `pages.yaml` and run `php please search:update`. The new index does not show in the list of indexes available to update. I've cleared caches, staches and stopped and restarted the dev server but nothing works.

I then also tested the situation by changing the default index to:

```
'default' => [
            'driver' => 'local',
            'searchables' => ['collection:pages'],
            'fields' => ['title'],
        ],
```
And again running `php please search:update`. Checking the `storage/statamic/search/default.json` shows that it still includes content as if set to `'all'`. This is confirmed by looking at the Search Index status within the CP and Default is still listed with `all` under the Searchables column.

### How to reproduce

Either add a new index as outlined above, or change the values for the default index. Run `php please search:update`

### Logs

```shell
local.ERROR: Search index [pages] is not defined. {"exception":"[object] (InvalidArgumentException(code: 0): Search index [pages] is not defined. at /Users/xxxx/Sites/xxxx/vendor/statamic/cms/src/Search/IndexManager.php:70)
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.6
PHP Version: 8.2.3
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 Solo

Statamic Addons
spatie/statamic-responsive-images: 3.1.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

I'm new to Statamic so I really hope I haven't missed something very obvious, but after plenty of searching for answers I concluded that it's just not working as expected.

Thanks in advance for your help!
