### ISSUE TITLE
Conditions field UI bug

### ISSUE THREAD

**Issue by aerni** [statamic/cms#7956]
### Bug description

The conditions field selector is awkwardly small and doesn't have a placeholder anymore compared to Statamic v3.

**Statamic v4**

![CleanShot 2023-04-19 at 16 10 53@2x](https://user-images.githubusercontent.com/23167701/233189036-1b112aa0-5264-4a1f-b488-4c505f819597.png)

**Statamic v3**

![CleanShot 2023-04-19 at 16 12 52@2x](https://user-images.githubusercontent.com/23167701/233189297-03c8b112-530b-4924-bb7d-243f9ccf253b.png)

### How to reproduce

Go to the conditions of a field in the blueprint editor.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.6
PHP Version: 8.1.13
Composer Version: 2.5.0
Environment: local
Debug Mode: ENABLED
URL: statamic-v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.4 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
