### ISSUE TITLE
Fieldset/blueprint editor issue regarding selectbox

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7958]
### Bug description

If a field on your blueprint or fieldset ends with a selectbox, like the entries field here, the user can't select all options as they disappear outside the view.

Searching is a workaround for now.

<img width="1525" alt="Screenshot 2023-04-20 at 10 06 26" src="https://user-images.githubusercontent.com/69107412/233301557-f11b8813-7571-4825-9039-0429beb8f1e4.png">

### How to reproduce

1. Add a few collections
2. Add an `entries` field to your blueprint or fieldset
3. Edit it
4. Scroll down and try to select the collections

### Environment

```yaml
Environment
Application Name: Stichting Lutje Geluk
Laravel Version: 10.8.0
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: lutjegeluk.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: dev-master PRO

Statamic Addons
doublethreedigital/guest-entries: 2.1.2
statamic/eloquent-driver: 1.2.0
studio1902/statamic-peak-browser-appearance: 2.0-beta.2
studio1902/statamic-peak-commands: 2.0-beta.3
studio1902/statamic-peak-seo: 2.0-beta.2
studio1902/statamic-peak-tools: 3.0-beta.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
