### ISSUE TITLE
Cannot set date on non-dated collection entry for each collection

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7959]
### Bug description

Since #7955 I get the `Cannot set date on non-dated collection entry for each collection` for each collection I have. However I don't seem to be doing anything like mentioned in the breaking change list for that PR.

<img width="1384" alt="Screenshot 2023-04-20 at 10 15 09" src="https://user-images.githubusercontent.com/69107412/233304230-19e328ba-b3bb-4671-b897-8833f80cf39a.png">

<img width="1386" alt="Screenshot 2023-04-20 at 10 15 15" src="https://user-images.githubusercontent.com/69107412/233304216-81bf4fe6-f321-44af-a161-41737500afa8.png">

I have seven collections, two of them are dated with time enabled set to false.

I'm using the eloquent driver for entries. 

### How to reproduce

I don't know. But you can DM for repo access. 

### Environment

```yaml
Environment
Application Name: Stichting Lutje Geluk
Laravel Version: 10.8.0
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: lutjegeluk.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: dev-master PRO

Statamic Addons
doublethreedigital/guest-entries: 2.1.2
statamic/eloquent-driver: 1.2.0
studio1902/statamic-peak-browser-appearance: 2.0-beta.2
studio1902/statamic-peak-commands: 2.0-beta.3
studio1902/statamic-peak-seo: 2.0-beta.2
studio1902/statamic-peak-tools: 3.0-beta.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
