### ISSUE TITLE
[4.x] Sections in live preview sidebar look a little off

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#7960]
### Bug description

The rounded corners on the sections look a little off when displayed in the live preview sidebar, as they run right up to the container edges:

![Screenshot 2023-04-20 at 09 50 17](https://user-images.githubusercontent.com/126740/233312905-23031a6b-c2f7-4e46-9cf5-1b8507a221c9.png)

Maybe a bit of padding would help, or just no rounded corners at all since space is already tight?

### How to reproduce

-

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.4 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
