### ISSUE TITLE
Bard field is empty (!) sometimes after saving …

### ISSUE THREAD

**Issue by delz-dev** [statamic/cms#7963]
### Bug description

https://user-images.githubusercontent.com/54885840/233354391-a4412dd7-efa4-4a6e-9a0e-bf547e2bd4cf.mp4

After adding or deleting text in a bard-field and saving the page, the bard field is empty! But just sometimes … tested on local and on dev-server.

Chrome console output *after* this behaviour

```
[iptap warn]: Invalid content. Passed value: {type: 'doc', content: Array(12)} Error: RangeError: Unknown node type: undefined
    at U.nodeType (index.js:2445:19)
    at S.fromJSON (index.js:1522:23)
    at U.nodeFromJSON (index.js:2430:21)
    at Array.map (<anonymous>)
    at s.fromJSON (index.js:319:35)
    at S.fromJSON (index.js:1521:32)
    at U.nodeFromJSON (index.js:2430:21)
    at At (index.js:1577:27)
    at jt (index.js:1919:12)
    at index.js:1924:22
```

### How to reproduce

… add or delete text inside a bard field, save the page … repeat until it happens.

### Logs

```shell
… nothing changes in the log
```

### Environment

```yaml
Environment
Application Name: Stohler Bett Pratteln
Laravel Version: 9.52.6
PHP Version: 8.2.4
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: stohler-bett.ch.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: sendinblue
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 PRO

Statamic Addons
jacksleight/statamic-bard-texstyle: 2.1.1
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
