### ISSUE TITLE
z-index date field

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7964]
### Bug description

Just like https://github.com/statamic/cms/issues/7950 and https://github.com/statamic/cms/issues/7924 the date field suffers from some layering issues:

<img width="438" alt="Screenshot 2023-04-20 at 15 13 30" src="https://user-images.githubusercontent.com/69107412/233377430-1f287373-755e-47ca-8d75-408ad3c36bdd.png">

### How to reproduce

Add a date field at the end of a section followed by a new section.

### Environment

```yaml
Environment
Application Name: Stichting Lutje Geluk
Laravel Version: 10.8.0
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: lutjegeluk.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: database

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: dev-master PRO

Statamic Addons
doublethreedigital/guest-entries: 2.1.2
statamic/eloquent-driver: 1.2.0
studio1902/statamic-peak-browser-appearance: 2.0-beta.2
studio1902/statamic-peak-commands: 2.0-beta.3
studio1902/statamic-peak-seo: 2.0-beta.2
studio1902/statamic-peak-tools: 3.0-beta.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
