### ISSUE TITLE
Minor listing pill ui thingy

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7965]
### Bug description

The last pill in the user table that shows the role looks different as it has no margin buttom.

<img width="1024" alt="Screenshot 2023-04-20 at 15 12 24" src="https://user-images.githubusercontent.com/69107412/233378675-6332c678-22fe-4d6e-b59e-86d1642f80d0.png">

### How to reproduce

Self explanatory

### Environment

```yaml
Environment
Application Name: Stichting Lutje Geluk
Laravel Version: 10.8.0
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: lutjegeluk.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: database

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: dev-master PRO

Statamic Addons
doublethreedigital/guest-entries: 2.1.2
statamic/eloquent-driver: 1.2.0
studio1902/statamic-peak-browser-appearance: 2.0-beta.2
studio1902/statamic-peak-commands: 2.0-beta.3
studio1902/statamic-peak-seo: 2.0-beta.2
studio1902/statamic-peak-tools: 3.0-beta.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
