### ISSUE TITLE
[4.x] Minor data-table UI issues on Firefox

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7966]
### Bug description

There appears to be an issue with the data-table UI on Firefox. Specifically, when hovering over a table row, the border-radius is not visible. Additionally, there is a border glitch above the actions-column and checkbox-column.

<img width="1148" alt="Bildschirmfoto 2023-04-20 um 15 32 04" src="https://user-images.githubusercontent.com/1102712/233382998-91f4f6bf-7a88-469c-b2b9-36ebb32f9a61.png">

<img width="1260" alt="Bildschirmfoto 2023-04-20 um 15 42 21" src="https://user-images.githubusercontent.com/1102712/233385240-5e9d0b64-b4bc-4086-aea9-55c6e78117c0.png">

### How to reproduce

- Use Firefox
- Check out the data-tables in the control panel

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.4 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
