### ISSUE TITLE
[4.x] Navigation publishing form is not showing more than one section

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7968]
### Bug description

It is possible to add multiple sections to a navigation blueprint. However, on the publish form of the navigation, only the first section is visible. It would be probably not an issue just disabling the option to configure more than one section in the nav blueprint editor.

### How to reproduce

- Add more than one section to a navigation Blueprint

_Nav Blueprint_

<img width="929" alt="Bildschirmfoto 2023-04-20 um 16 03 10" src="https://user-images.githubusercontent.com/1102712/233390790-305781e8-2362-4581-804d-6b14759ebbb4.png">

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.4 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
