### ISSUE TITLE
[4.x] Minor UI issues when having Bard inside a nav form

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7969]
### Bug description

Bard needs more padding and some tweaks on the "Add Set (+)" Button:

<img width="391" alt="Bildschirmfoto 2023-04-20 um 16 08 27" src="https://user-images.githubusercontent.com/1102712/233392842-370c11b6-6cdf-403a-a35c-0a82b8e2afd0.png">

### How to reproduce

- Add a Bard Field to a navigation Blueprint

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.4 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
