### ISSUE TITLE
[4.x] Bard `Show HTML Source` is not working when bard contains a set

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7971]
### Bug description

When clicking `Show HTML Source` in a Bard editor with configured sets, no HTML source is shown.

![2023-04-20 16 48 51](https://user-images.githubusercontent.com/1102712/233403670-8d6ac7c6-bff3-4ca4-aa4e-944e0bdebe1f.gif)

### How to reproduce

- Add a Bard field with a Bard set
- Add set to Bard
- Click Show HTML Source

### Logs

```shell
TypeError: set is undefined
    setDisplay Source.vue:52
    render Source.vue:39
    renderList VueJS
    render Source.vue:39
    VueJS 33
    click BardFieldtype.vue:636
    VueJS 3
vue.esm.js:3767:16
    VueJS 36
    click BardFieldtype.vue:636
    VueJS 3
```

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.4 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
