### ISSUE TITLE
GraphQL doesn't work correctly when you have multiple Bard/Replicator fields with the same handle across Blueprints

### ISSUE THREAD

**Issue by notnek** [statamic/cms#7983]
### Bug description

If you have multiple blueprints with the same handle for a Bard or Replicator field, you cannot query that field for any entries but one of the Blueprints. For example, if you have a Blog Posts and Pages collection that both have a Bard field named `content` but with different sets, only the sets on a Blog Post entry are available and you'll get a spread error on Page entries: _Fragment cannot be spread here as objects of type "Sets_Content" can never be of type "Set_Content_SetHandle"_.

### How to reproduce

I've created a repo where this is reproduced here: https://github.com/notnek/statamic-graphql-issue

This is using v4 alpha but it happens on v3.4 as well. There is a query in the README you can run to see the error. To see it resolved, rename the handle in one of the blueprints and run an updated query and it will work as expected.

You can see the commit of setting everything up here: https://github.com/notnek/statamic-graphql-issue/commit/54866ec9ad78b108f1d1cb10f09c97dfbd951161

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.6
PHP Version: 8.1.8
Composer Version: 2.3.5
Environment: local
Debug Mode: ENABLED
URL: statamic4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.4 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

My example repo is v4 but I first discovered this when moving a v3 app from the Rest API to the GraphQL API.
