### ISSUE TITLE
v4.0.0-alpha.4 Statamic User edit on CP

### ISSUE THREAD

**Issue by mkael1** [statamic/cms#7985]
### Bug description

When I click on a user to try and edit it crashes me.

![image](https://user-images.githubusercontent.com/92281368/234073317-4b7d9d0c-968f-48c0-b036-2fcfa3e703ff.png)
![image](https://user-images.githubusercontent.com/92281368/234073442-699a2393-72b8-460a-8bf9-2c0021970cdd.png)

### How to reproduce

Create a user through php please.
Go onto the Control Panel and click on the user to edit it.

### Environment

```yaml
Environment
Application Name: Lauzon
Laravel Version: 10.8.0
PHP Version: 8.1.10
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Scout: meilisearch
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.4 PRO

Statamic Addons
statamic/eloquent-driver: dev-master
```

### Installation

Existing Laravel app

### Antlers Parser

None

### Additional details

I am using a custom user model (StatamicUser) model through the config and I store the StatamicUsers in my database.
Note: I am using Statamic on another project on version 3.3.65 and this setup currently works fine.
