### ISSUE TITLE
Form validation rules for Asset fieldtypes show incorrectly in GraphQL

### ISSUE THREAD

**Issue by notnek** [statamic/cms#7986]
### Bug description

If you add one of [these validation rules](https://github.com/statamic/cms/blob/3.4/src/Fieldtypes/Assets/Assets.php#L198) to an Asset Fieldtype in a Form, the GraphQL response for that field's validation rules is an empty object instead of the original rule:

- `dimensions`
- `image`
- `max_filesize:foo`
- `mimes:foo,bar`
- `mimetypes:foo,bar`
- `min_filesize:foo`

### How to reproduce

**Blueprint**

```yaml
sections:
  main:
    display: Main
    fields:
      -
        handle: asset_field
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          display: 'Asset Field'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          validate:
            - 'mimetypes:application/pdf'
```

**GraphQL Query**

```graphql
{
  form(handle: "asset_form_example") {
    rules
  }
}
```

**GraphQL Response**

```json
{
  "data": {
    "form": {
      "rules": {
        "asset_field": [
          {},
          "array",
          "nullable"
        ]
      }
    }
  }
}
```

### Environment

```yaml
Environment
Application Name: Sample Site
Laravel Version: 9.48.0
PHP Version: 8.1.8
Composer Version: 2.3.5
Environment: local
Debug Mode: ENABLED
URL: sample-site.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: null
Cache: redis
Database: mysql
Logs: stack / daily,
Mail: log
Queue: redis
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.4.5 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
