### ISSUE TITLE
[4.x] Filters UI not rendered for navigation entries

### ISSUE THREAD

**Issue by SylvesterDamgaard** [statamic/cms#7996]
### Bug description

When adding a collection entry in a navigation, the filters UI is not rendered.
The DataListFilters vue component is present in vue debugger.
![image](https://user-images.githubusercontent.com/2431914/234261277-7495cfb6-b72b-46c2-a2d8-66573c0b43c1.png)

A js error is thrown in the console ```caught (in promise) TypeError: Cannot read properties of undefined (reading 'focus')```
![image](https://user-images.githubusercontent.com/2431914/234261132-d62b0b0c-0cf3-47e9-8aed-aab4d8b66ad9.png)

### How to reproduce

1. Create a navigation
2. Edit the navigation configuration and add a collection for entry selection
3. Under the navigation, Click the _Link to entry_ button. 
![image](https://user-images.githubusercontent.com/2431914/234261510-fd45e367-bf1d-4dd6-84af-be5edaf536bd.png)
4. The popover is missing the filter/search UI

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.6
PHP Version: 8.2.4
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: statamic-v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.4 PRO

Statamic Addons
tv2regionerne/statamic-curated-collection: dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
