### ISSUE TITLE
Breaking change in v3.4.6

### ISSUE THREAD

**Issue by aerni** [statamic/cms#8010]
### Bug description

There seems to be a breaking change introduced in `v3.4.6`. I've got a tag where I'm checking if a value from the context is `$value instanceof OrderedQueryBuilder`. This worked in `v3.4.5`. But in `v3.4.6` the `$value` is an instance of `StatusQueryBuilder`.

This might be connected to PR https://github.com/statamic/cms/pull/7334 that was merged in `v3.4.6`.

### How to reproduce

Add this entries field to your blueprint. Set the `collection` to any collection you want. This is the config I used:

```yaml
handle: protagonists
field:
  mode: default
  create: true
  collections:
    - people
  display: Protagonisten
  type: entries
  icon: entries
  instructions: 'Wähle die Protagonisten dieses Artikels'
  width: 50
  listable: true
  instructions_position: above
  visibility: visible
  always_save: false
  validate:
    - required
```

Add some entries to that field.

Create this tag:

```php
<?php

namespace App\Tags;

use Statamic\Query\OrderedQueryBuilder;
use Statamic\Support\Str;
use Statamic\Tags\Tags;

class Join extends Tags
{
    public function wildcard(): ?string
    {
        $field = Str::before($this->method, ':');
        $value = $this->context->value($field);

        if ($value instanceof OrderedQueryBuilder) {
            $field = Str::contains($this->method, ':')
                ? Str::after($this->method, ':')
                : 'title';

            $value = $value->get()->map->$field;
        }

        $glue = $this->params->get('separator') ?? __('and');
        $oxfordComma = $this->params->get('oxford_comma') ?? false;

        $value = collect($value)->filter()->all();

        return Str::makeSentenceList($value, $glue, $oxfordComma);
    }
}
```

Use it in your template:

```antlers
{{ join:protagonists separator='&' }}
```

This works on `v3.4.5` but breaks on `v3.4.6+`.

### Environment

```yaml
Environment
Application Name: gomagazin
Laravel Version: 9.52.7
PHP Version: 8.1.13
Composer Version: 2.5.0
Environment: local
Debug Mode: ENABLED
URL: gomagazin.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single, sentry, flare
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 10
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.6 PRO

Statamic Addons
aerni/advanced-seo: 2.0.4
aerni/livewire-forms: 7.1.0
aerni/social-links: 3.0.3
aryehraber/statamic-impersonator: 2.4.1
jacksleight/statamic-bard-texstyle: 2.1.1
jonassiewertsen/statamic-jobs: 1.3.0
jonassiewertsen/statamic-livewire: 2.12.0
rias/statamic-redirect: 2.7.0
spatie/statamic-responsive-images: 3.1.3
stillat/relationships: 1.2.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
