### ISSUE TITLE
[4.x] Different Line-Heights (and font-size) in Bard, Bard-Inline and Textarea fields

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#8016]
### Bug description

When you use a bard-field on an entry, you see a different line-height when the bard field is set to inline. The line-height feels a little too tight from a typographical point of view.

The line height should be slightly higher. Probably the same height as for a bard-field with sets.

The different in margin makes sense though, because a bard-inline-field is more oriented to a text/textarea-field.
Speaking of text/textarea-field: They have a bigger font-size than bard fields. The font-size of a bard-inline-field could be the same as in text and textarea-fields maybe? I am not sure. But for a calmer CP, this might be worth checking.

<img width="922" alt="Bildschirmfoto 2023-04-28 um 10 52 20" src="https://user-images.githubusercontent.com/8265902/235104502-51ecaa57-cd26-467a-9194-c6bf392c1e75.png">

### How to reproduce

- Add two bard sets to a blueprint. One of them ist set to inline.
- Edit a entry in CP

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.7
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: v4-test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-beta.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
