### ISSUE TITLE
[4.x] Textarea Fields have a different :focus-border than other fields

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#8017]
### Bug description

Just a little detail. The :focus-border of a textarea field is darker than for a bard- or text field, for example.

<img width="883" alt="Bildschirmfoto 2023-04-28 um 11 27 28" src="https://user-images.githubusercontent.com/8265902/235110606-24d26921-e12f-44e5-b744-cad495f61797.png">
<img width="880" alt="Bildschirmfoto 2023-04-28 um 11 31 55" src="https://user-images.githubusercontent.com/8265902/235111632-69f0b79a-c97e-4b9d-b30d-ae1140894899.png">
<img width="876" alt="Bildschirmfoto 2023-04-28 um 11 32 00" src="https://user-images.githubusercontent.com/8265902/235111634-3c8f3f4e-1bed-4050-b3a8-3a5f739d113a.png">

### How to reproduce

Edit an entry in the CP with different text-fieldtypes.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.7
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: v4-test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-beta.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
