### ISSUE TITLE
4.0 Beta: Bard Fieldtype Table

### ISSUE THREAD

**Issue by thepalk** [statamic/cms#8020]
### Bug description

Within the Bard Field type, the table is expandable over the border of the field type.

### How to reproduce

Go Bard, click table, pull border on the right.
https://user-images.githubusercontent.com/69767296/235168780-f9a8bc26-5be6-49e1-bae0-e67b258d2ade.mp4

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.7
PHP Version: 8.2.1
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: my-v4-test-site-beta.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-beta.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
