### ISSUE TITLE
I got this error TypeError: _.findWhere is not a function  

### ISSUE THREAD

**Issue by yaser2490** [statamic/cms#8030]
### Bug description

Sometimes the admin panel has an error
This usually happens a lot

![Screenshot 2023-05-01 200420](https://user-images.githubusercontent.com/70744366/235479361-4bd3ba48-7347-453e-a651-3992f4f5a9dd.png)

### How to reproduce

I get this error only on Google Chrome
There is no problem on Mozilla and Edge

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.2.4
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: USD
Gateways: PayPal
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\UserCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Free Delivery
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 PRO

Statamic Addons
bencarr/statamic-hyperlink: 1.1.0
doublethreedigital/guest-entries: 2.1.1
doublethreedigital/simple-commerce: 4.5.8
statamic/eloquent-driver: 1.2.0
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
