### ISSUE TITLE
CP parent column: incorrect parent and inability to sort the entries by parent

### ISSUE THREAD

**Issue by johncarter-** [statamic/cms#8037]
### Bug description

See video: https://vimeo.com/823262403/ba1d41a2d6

### How to reproduce

Create a hierarchical collection.
Add a few entries some with parents.
Add "Parent" to the CP columns.
See incorrect parent entries and inability to sort the entries by parent.

### Environment

```yaml
Environment
Application Name: AC1 Electrical Services
Laravel Version: 10.9.0
PHP Version: 8.1.14
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: dev.ac1electricalservices.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-beta.2 PRO

Statamic Addons
spatie/statamic-responsive-images: 3.1.3
```

### Installation

Other (please explain)

### Antlers Parser

None

### Additional details

Upgraded by adding the following to composer.json to: `"statamic/cms": "v4.0.0-beta.2 as 3.4.999"`
