### ISSUE TITLE
[4.x] Text cursor after adding a table is on top right.

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#8038]
**Update:** 

According to this https://github.com/statamic/cms/issues/8038#issuecomment-1532671596 comment this is not a bug. 

There is still a issue with the cursor after adding a table. https://github.com/statamic/cms/issues/8038#issuecomment-1532660339 
I've changed the title of the issue accordingly.

### Bug description

If you move the cursor up or down in a bard field and have two sets in a row with no text between them, you will see a horizontal text cursor.

This seems a bit unusual to me. But since there is no text in between, a normal vertical text cursor wouldn't be quite right either. 🤔

<img width="873" alt="Bildschirmfoto 2023-05-03 um 10 06 32" src="https://user-images.githubusercontent.com/8265902/235867576-0e7bb8f3-c256-4112-8cb4-bd252e696995.png">

### How to reproduce

Add two sets in a bard field and use your arrow up/down keys on your keyboard or click between two sets.

### Environment

```yaml
Application Name: Statamic
Laravel Version: 9.52.7
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: v4-test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-beta.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
