### ISSUE TITLE
[4.x] Array field: reorder rows with drag and drop shows grabbed row with too much offset

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#8039]
### Bug description

When you reorder a row from an array field, the grabbed row gets a bit too much offset. I've tested with Safari 16.4.1 and Chrome 112.0.5615.137

<img width="1258" alt="Bildschirmfoto 2023-05-03 um 11 10 40" src="https://user-images.githubusercontent.com/8265902/235878917-79bf313c-4960-49b1-873b-ae453c9f5f1c.png">

### How to reproduce

Create a array field (with dynamic ui mode), add a few rows and try to reorder them. 

### Environment

```yaml
Application Name: Statamic
Laravel Version: 9.52.7
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: v4-test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-beta.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
