### ISSUE TITLE
[4.x] Unable to reorder Bard toolbar buttons through UI

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#8041]
### Bug description

It's not possible to reorder the Bard toolbar buttons though the blueprint editor. Clicking and dragging does nothing.

### How to reproduce

Try to reorder the Bard buttons.

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-beta.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
