### ISSUE TITLE
Uncached blueprint creations and found events decrease performance

### ISSUE THREAD

**Issue by morhi** [statamic/cms#8047]
### Bug description

I noticed through investigating Clockwork that in my project thousands (2k-5k) of `...BlueprintFound` events have been dispatched, so I thought maybe this would impact my sites performance, because it was getting rather slow with growing content.

Looking in the code it might be helpful to 

1) blink methods that create a new blueprint for entries, taxonomies/terms and asset containers 
2) blink `...BlueprintFound` events so that they would only be dispatched once for the same blueprint.

I will add a PR, that will hopefully improve this issue.

### How to reproduce

1. Install Clockwork to any Statamic install
2. Go to /clockwork/app and investigate the number of events thrown

The number of events depends on how much content is on that page, so the number might vary a lot.

### Environment

```yaml
Environment
Laravel Version: 9.52.4
PHP Version: 8.1.18
Composer Version: 2.2.5
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 13
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
