### ISSUE TITLE
Date picker in collection filter not getting applied

### ISSUE THREAD

**Issue by SirNovi** [statamic/cms#8055]
### Bug description

Trying to filter a collection by the date field does not work. After picking a date the date picker disappears but no filter gets applied.

https://user-images.githubusercontent.com/1991072/236235826-ca6fe016-1565-438d-b3c5-18ce777a3447.mp4

### How to reproduce

- Go to a collection
- try to filter by date field

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.7
PHP Version: 8.2.4
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: statamic-4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-beta.2 PRO
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None

### Additional details

I used the cool writings starter kit
