### ISSUE TITLE
Button label when saving Navigation item

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#8060]
### Bug description

Not a bug, but when looking at the norwegian translation on this button it's just wrong. I could change the translation, but the reason it is wrong is related to the word "Submit".  Should/could this be changed to "Save" instead?

![Screenshot 2023-05-04 at 23 58 24](https://user-images.githubusercontent.com/1135679/236339065-4d88dc69-4167-45ef-b26a-17f167009b54.png)

### How to reproduce

Edit a navigation item.

### Environment

```yaml
Environment
Application Name: Properti Stage
Laravel Version: 9.52.5
PHP Version: 8.0.28
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: properti-stage.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.8 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
properti/estate-items-import: dev-main
properti/properti-dashboard: dev-main
r8edge/imagemap: dev-main
r8edge/welcome-widget: dev-main
statamic/eloquent-driver: 1.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
