### ISSUE TITLE
Yield in layout causes no HTML to be returned

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#8066]
### Bug description

I've just setup Statamic 4 & Peak locally for a project but I was having issues where the homepage didn't get any HTML returned.

I've done some digging and it seems to be related to `{{ yield:seo_body }}` in Peak's layout. If I remove it from my layout, it works fine. If I call the yield something else, still broken.

### How to reproduce

Use this layout with the latest Statamic 4 beta:

```antlers
{{#
    @name Layout
    @desc The default layout file.
#}}

<!-- /layout.antlers.html -->
<!doctype html>
<html lang="{{ site:short_locale }}" class="antialiased">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
        {{ vite src="resources/css/site.css|resources/js/site.js" }}
        {{ partial:statamic-peak-seo::snippets/seo }}
        {{ partial:statamic-peak-browser-appearance::snippets/browser_appearance }}
        {{ partial:statamic-peak-tools::snippets/live_preview }}
    </head>
    <body class="flex flex-col min-h-screen bg-white selection:bg-primary selection:text-white">
        {{ partial:statamic-peak-tools::snippets/noscript }}
        {{ partial:statamic-peak-tools::navigation/skip_to_content }}
        {{ partial:statamic-peak-tools::components/toolbar }}
        {{ yield:seo_body }}

        {{ partial:layout/header }}
        {{ template_content }}
        {{ partial:layout/footer }}
    </body>
</html>
<!-- End: /layout.antlers.html -->
```

### Environment

```yaml
Environment
Application Name: BrandNewProject
Laravel Version: 10.9.0
PHP Version: 8.2.3
Composer Version: 2.2.6
Environment: local
Debug Mode: ENABLED
URL: brandnewproject.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-beta.3 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 2.0-beta.2
studio1902/statamic-peak-commands: 2.0-beta.4
studio1902/statamic-peak-seo: 2.0-beta.2
studio1902/statamic-peak-tools: 3.0-beta.3
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
