### ISSUE TITLE
Regression: Date field always saves time

### ISSUE THREAD

**Issue by aerni** [statamic/cms#8075]
### Bug description

I'm not sure if I'm missing something super obvious here, but the date picker in a collection with publish dates seems to be broken. This seems to be a regression, as [this old issue](https://github.com/statamic/cms/issues/3157) describes the exact same problem and was fixed a long time ago.

I set `time_enabled: true` on the date field. But the time is always required and saved as `00:00`. Even if I set `time_required` to false. 

Also, the `time_required` toggle is missing in the blueprint editor. I thought it might have been removed, but I still found it [mentioned in the docs](https://statamic.dev/fieldtypes/date) (all the way at the bottom).

### How to reproduce

1. Enable publish dates on a collection
2. Set `time_enabled: true` and `time_required: false` on the `date` field
3. Create an entry and see that you can't remove the time

### Environment

```yaml
Environment
Application Name: Bärenmatte
Laravel Version: 9.52.7
PHP Version: 8.1.13
Composer Version: 2.5.0
Environment: local
Debug Mode: ENABLED
URL: baerenmatte.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.11 PRO

Statamic Addons
aerni/advanced-seo: 2.0.6
aryehraber/statamic-impersonator: 2.4.1
jonassiewertsen/statamic-jobs: 1.3.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
