### ISSUE TITLE
Entries/tags field in typeahead mode shows no options initially

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8077]
### Bug description

Whenever I use an `entries` or `taxonomy terms` field in typeahead mode it initially shows no options in the dropdown. You have to type `space` and then `backspace` to get the select to fill. 

I'd expect it to show the options straight away, especially since the fields' placeholder is 'Choose...'. In reality there's nothing to choose from initially.

Maybe this is intended behaviour but I've always found the UX off here.

The `select` mode however seems to work like I'd expect the `typeahead` mode to work. It shows options initially plus you can search. What is supposed to be the difference between those modes? Is `typeahead` redundant maybe?

### How to reproduce

Add an `entries` or `taxonomy terms` field in `typeahead` mode.
Make sure there are entries or terms.
Use the field

### Environment

```yaml
Environment
Application Name: Studio 1902
Laravel Version: 10.9.0
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: 1902.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-beta.4 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 2.12.0
studio1902/statamic-peak-browser-appearance: 2.0-beta.2
studio1902/statamic-peak-commands: 2.0-beta.4
studio1902/statamic-peak-seo: 2.0-beta.2
studio1902/statamic-peak-tools: 3.0-beta.3
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
