### ISSUE TITLE
Stack picker entry listing could be improved

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8079]
### Bug description

When you invoke a collection stack picker the listing view could be improved. In this case the stack is invoked from the navigation builder. It looks the same when you link to an entry from a bard field and probably in other places as well.

The first column is the status which isn't ideal. Ideally it would be the title. Also I would expect the status to have the same design as in the collection table overviews (where it's also the last column). 

<img width="1436" alt="Screenshot 2023-05-09 at 13 20 20" src="https://github.com/statamic/cms/assets/69107412/00c33ce7-ea0b-4ca4-8314-33cf67e2b02d">

### How to reproduce

Add some pages
Add a nav
Add a page to a nav

### Environment

```yaml
Laravel Version: 9.52.7
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-beta.4 PRO

Statamic Addons
rias/statamic-color-swatches: 2.1.9
studio1902/statamic-peak-browser-appearance: 2.0-beta.2
studio1902/statamic-peak-commands: 2.0-beta.4
studio1902/statamic-peak-seo: 2.0-beta.2
studio1902/statamic-peak-tools: 3.0-beta.3
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
