### ISSUE TITLE
Asset focal point preview not showing

### ISSUE THREAD

**Issue by freshface** [statamic/cms#8082]
### Bug description

See video https://cln.sh/8g6SZRtBQQjKtttQFPd5

### How to reproduce

1. Install v4
2. Upload an asset
3. Set focal point

### Environment

```yaml
Environment
Application Name: Vraag het aan Cindy - Haelewyck verzekeren & beleggen
Laravel Version: 9.52.7
PHP Version: 8.1.17
Composer Version: 2.2.18
Environment: local
Debug Mode: ENABLED
URL: cindy.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0 Solo

Statamic Addons
studio1902/statamic-peak-browser-appearance: 2.0
studio1902/statamic-peak-commands: 2.0
studio1902/statamic-peak-seo: 2.0
studio1902/statamic-peak-tools: 3.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
