### ISSUE TITLE
Grid fieldtype (Table UI mode) poor formating of fields

### ISSUE THREAD

**Issue by univers-andrew** [statamic/cms#8086]
### Bug description

When using the grid fieldtype with the table UI mode, the formatting of the field withs looks pretty wonky (time fieldtypes overlap), and widths aren't respected generally. Issue doesn't present in stacked mode, but stacked mode is the inferior choice in this instance!

Small issue, but thought it was worth flagging for future versions...

<img width="2329" alt="Screenshot 2023-05-10 at 5 10 06 pm" src="https://github.com/statamic/cms/assets/122848318/3846320d-6468-4dac-9770-03f2fb6fbe19">

<img width="993" alt="Screenshot 2023-05-10 at 5 11 20 pm" src="https://github.com/statamic/cms/assets/122848318/b61b5f6c-1ffb-49b6-b88e-8818b696dce6">

### How to reproduce

Copy the screenshot settings prevoiusly provided

### Environment

```yaml
Environment
Application Name: Alchemy Cryotherapy Centre
Laravel Version: 10.10.0
PHP Version: 8.1.10
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
URL: alchemy-2023.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: mailgun
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

Nice work on the v4 UI overall. Top work 🥂
