### ISSUE TITLE
Navigation filters broken

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8087]
### Bug description

Filters in the Navigation Add Entry Stack. Clicking on them doesn't do anything (tested in Chrome and Safari).
<img width="1309" alt="Screenshot 2023-05-10 at 09 55 44" src="https://github.com/statamic/cms/assets/69107412/ca155fad-cdc0-4d3a-8a4a-0bfc17086c34">

### How to reproduce

Create a navigation
Add an entry to the navigation
Try the filters

### Environment

```yaml
Environment
Laravel Version: 9.52.7
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0 PRO

Statamic Addons
rias/statamic-color-swatches: 2.2.0
studio1902/statamic-peak-browser-appearance: 2.0
studio1902/statamic-peak-commands: 2.0
studio1902/statamic-peak-seo: 2.0
studio1902/statamic-peak-tools: 3.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
