### ISSUE TITLE
Bard: Invalid HTML

### ISSUE THREAD

**Issue by helloiamlukas** [statamic/cms#8088]
### Bug description

If you have a Bard field and format text which has already been formatted, you will get an invalid HTML output.

https://github.com/statamic/cms/assets/15997450/a8e7a723-cdfe-4f5a-9a79-c93f4dc21a2a

The HTML output of the text in the video will be this:

```html
<p><strong><em>The Macarena</strong> by Los Del Rio (Remixed by the Bayside Boys) has been #1 on the charts for 14 weeks in a&nbsp;row.</em></p>
```

### How to reproduce

This bug can be reproduced with any Bard field in Statamic v4/v3. Just format the text like in the video above.

When inspecting the HTML, do not use Chrome Dev Tools. Chrome automatically tries to fix the (not closing) tags and therefore will not show the invalid HTML.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.10.0
PHP Version: 8.1.18
Composer Version: 2.4.0
Environment: local
Debug Mode: ENABLED
URL: bard-formatting-bug.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0 Solo
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
