### ISSUE TITLE
Asset grid thumbnails are full width

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#8090]
### Bug description

Asset grid view thumbnails seem to have lost their grid layout:

![Screenshot 2023-05-10 at 10 44 38](https://github.com/statamic/cms/assets/126740/a99e8276-4119-4b1f-8494-171a36635ae5)

### How to reproduce

View the asset grid

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
