### ISSUE TITLE
Required asterisk is still visible when hiding a display label

### ISSUE THREAD

**Issue by CjRootStudio** [statamic/cms#8091]
### Bug description

When hiding the Display Label for a required field, the red required asterisk is still visible.

It's possible this is intended behaviour to alert users to a required field but I thought I'd just flag it anyway!

<img width="850" alt="Screenshot 2023-05-10 at 12 07 12" src="https://github.com/statamic/cms/assets/108793851/25eb4e1b-2aa5-4e65-bfa1-f94556fd4004">

### How to reproduce

- Create or edit a blueprint
- Add a text field and give it a Display Label
- Set the field to required in the 'Validation' tab
- Toggle the Display Label as 'Hidden'
- View the field on a page and see the red asterisk still visible

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.7
PHP Version: 8.1.12
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: statamic-starter.test/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.0.0 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.0.0
jacksleight/statamic-bard-texstyle: 3.0.2
jonassiewertsen/statamic-livewire: 2.12.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
