### ISSUE TITLE
Blueprint function errors after update from 3.3.* to 3.4.* or 4.0.0

### ISSUE THREAD

**Issue by colinupgraders** [statamic/cms#8093]
### Bug description

After I updated Statamic 3.3.* to 3.4. or 4.0.0* I got following errors on multiple blueprints. Some blueprints are working fine.

**Collections**
Call to a member function entryBlueprints() on string

**Navigation**
No errors

**Taxonomies**
Call to a member function termBlueprints() on string

**Assets**
Call to a member function id() on string

**Globals**
No errors

**Forms**
Call to a member function blueprint() on string

### How to reproduce

Update from 3.3.* to 3.4.*

### Environment

```yaml
Statamic 3.3.6 Pro
Laravel Version: 9.52.7
PHP Version: 8.2.4
No addons installed
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
