### ISSUE TITLE
Unexpected generated title behavior on multi-sites

### ISSUE THREAD

**Issue by aerni** [statamic/cms#8099]
### Bug description

I've got a collection that uses the `title_format` and is configured for multiple `sites`. Currently, the title is saved for all entries, regardless if it is the same as the title of the entry's origin. I'm expecting the generated title to only be saved to file if it is _different_ to the entry's origin. This would adhere to the origin behavior that's used everywhere else.

**Origin:**
```md
---
id: 546b6c42-c7f6-46ae-9ec6-b91941e6417f
title: 'Jack McDade'
first_name: 'Jack'
last_name: 'McDade'
---
```

**Localization:**
```diff
---
id: 146fab66-33ab-4cb6-a389-161e70cae88d
origin: 546b6c42-c7f6-46ae-9ec6-b91941e6417f
- title: 'Jack McDade'
---
```

### How to reproduce

1. Add a `title_format` to a collection, e.g. `title_format: '{{ first_name }} {{ last_name }}'`
2. Configure the collection for multiple sites
3. Create an entry and localize it (don't localize any values)
4. See the title being saved on the localization, even though it is the same as the origin's title

### Environment

```yaml
Environment
Application Name: autonomiesuisse
Laravel Version: 9.52.7
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: autonomiesuisse.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Localization
Installed: de, en, fr, it
LaravelLang\Attributes\Plugin: v2.3.3
LaravelLang\HttpStatuses\Plugin: v3.3.1
LaravelLang\Lang\Plugin: 12.21.5
Protected Locales: de, en
Publisher Version: v14.6.4

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.11 PRO

Statamic Addons
aerni/advanced-seo: 2.0.6
aerni/livewire-forms: 7.1.1
aerni/social-links: 3.0.3
jonassiewertsen/statamic-livewire: 2.12.0
statamic/migrator: dev-master
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
