### ISSUE TITLE
[4.x] Missing translation

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#8110]
### Bug description

When creating a new Set Group or a new Set when configuring a Bard field, the validation button still is in English: "Confirm"

### How to reproduce

Set the default user language as French, German or Dutch
Create a new Bard field
Click on Add Set Group (in French: Ajouter un groupe d'ensembles)
In the modal, the validation button still is "Confirm"

or

inside a Set Group
Click on New Set (in French: Nouvel ensemble)
In the modal, the validation button still is "Confirm"

(other issue, FWIW: the slug for both the Set group and the Set doesn't update when changing the Title...)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.7
PHP Version: 8.2.0
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

<img width="638" alt="Capture d’écran 2023-05-11 à 00 00 34" src="https://github.com/statamic/cms/assets/1823359/068a17c8-97d3-4e33-a3df-aca0c1d535f1">

<img width="632" alt="Capture d’écran 2023-05-11 à 00 01 07" src="https://github.com/statamic/cms/assets/1823359/16071d4d-d1a8-4917-bbd9-94870b0596dd">
