### ISSUE TITLE
[4.x] When color white is predefined in color selector it not easy to see/select

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#8116]
### Bug description

I defined two colors in the Color Selector; `#0C479D` and `#FFFFFF`. But it is somewhat difficult to see the white color as it has no border around showing there is another color available.

![Screenshot 2023-05-11 at 12 02 06](https://github.com/statamic/cms/assets/1135679/9d5d6ad5-cb1c-49e9-bb51-41111942eeed)

### How to reproduce

Like the description says - create a color selector with the color white and try to use it.

### Environment

```yaml
Application Name: Statamic
Laravel Version: 10.10.0
PHP Version: 8.1.17
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
