### ISSUE TITLE
Set header instructions text inconsistency

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#8120]
### Bug description

The set header instructions text works/displays differently between Replicator and Bard:

Replicator: 
![Screenshot 2023-05-11 at 15 30 42](https://github.com/statamic/cms/assets/126740/dee6dc38-eb29-4145-81f8-915633c9f66c)

Bard:
![Screenshot 2023-05-11 at 15 30 09](https://github.com/statamic/cms/assets/126740/a69d4260-ab80-4342-b516-8f5520ae897d)

### How to reproduce

Add instructions to a Replicator and Bard set.

### Environment

```yaml
Statamic
Addons: 10
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
