### ISSUE TITLE
[4.x] Link field type dropdown z-index lower than section header

### ISSUE THREAD

**Issue by x7ryan** [statamic/cms#8123]
### Bug description

I have a link field at the bottom of a section. When I open up the dropdown to select the link type the header for the next section blocks part of the dropdown.

![Screenshot 2023-05-11 105741](https://github.com/statamic/cms/assets/1036407/3cbb7cf8-1dc7-45c8-949b-6bcc33875619)

### How to reproduce

1. Create a blueprint with 2 sections
2. Add a link field as the last field in the top section
3. Create or edit an entry.
4. Open the link type drop down 

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 10.9.0
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.1.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
