### ISSUE TITLE
Sortable items become unsortable sometimes

### ISSUE THREAD

**Issue by o1y** [statamic/cms#8124]
### Bug description

When I click too fast in the fieldsets/blueprints sortable lists to reorder some items, sometimes it happens that the previously moved item is no longer sortable. I also noticed this when monkey testing #8121.

### How to reproduce

![2023-05-11 20 51 41](https://github.com/statamic/cms/assets/1102712/6a57f2f9-31d4-488b-bfa9-d67e81dc38a0)
![2023-05-11 21 13 33](https://github.com/statamic/cms/assets/1102712/d8573fa1-6131-4e3f-9ae8-54ab3a802de0)

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.1.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
