### ISSUE TITLE
Source image processing does not update extension

### ISSUE THREAD

**Issue by fjahn** [statamic/cms#8127]
### Bug description

If you configure [Source Image Processing](https://statamic.dev/image-manipulation#process-source-images), in an asset container to convert uploaded images to another format, the filename extension does not get updated.

This was just strange before, but since Statamic 4, generating a Glide URL of these images causes an exception. This did not occur in previous versions of Statamic.

### How to reproduce

- Set up a preset in `config/assets.php`, e.g.
```php
'presets' => [
    'default' => [
        'format' => 'webp',
    ],
],
```
- Configure this preset to be used on the default asset container:
```php
// add this to content/assets/assets.yaml
source_preset: default
```
- Via control panel, upload a file that is different from the configured file type, e.g. `test.jpg`
- *When uploading is done, the file will still be named `test.jpg` both in the control panel and on the file system*
- Using `file`, you can check the image format of the actual file content, which is webp:
```bash
▶ file storage/app/public/assets/test.jpg
storage/app/public/assets/test.jpg: RIFF (little-endian) data, Web/P image, VP8 encoding, 3000x2000, Scaling: [none]x[none], YUV color, decoders should clamp
```
- *The thumbnail in the asset container in control panel is missing*
- Set up a view that tries to render the image using a glide tag:
```antlers
{{ glide:image format="webp" }}
```
- Open the view in browser
- An `\Exception` is thrown (see logs for details)

### Logs

```shell
Message: Image [test.jpg] does not actually appear to be a valid image.

Stacktrace:

Statamic \ Imaging \ ImageGenerator : 314
validateImage
Statamic \ Imaging \ ImageGenerator : 260
generate
Statamic \ Imaging \ ImageGenerator : 172
doGenerateByAsset
Statamic \ Imaging \ ImageGenerator : 155
Statamic\Imaging\{closure}
Illuminate \ Cache \ Repository : 438
rememberForever
Statamic \ Imaging \ ImageGenerator : 153
generateByAsset
Statamic \ Tags \ Glide : 168
generateImage
Statamic \ Tags \ Glide : 138
Statamic\Tags\{closure}
.unknown0
array_map
Illuminate \ Support \ Arr : 560
map
Illuminate \ Support \ Collection : 768
map
Statamic \ Tags \ Glide : 134
generate

[ ... app specific calls ]
```

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 9.52.7
PHP Version: 8.2.5
Composer Version: -
Environment: local
Debug Mode: ENABLED
URL: localhost:8000
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: file
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Localization
Installed: de, en
LaravelLang\Lang\Plugin: 11.0.19
Protected Locales: de, en
Publisher Version: v14.6.4

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.1.0 PRO

Statamic Addons
aryehraber/statamic-impersonator: 2.5.0
jacksleight/statamic-bard-mutator: 2.2.0
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)
