### ISSUE TITLE
Live Preview panel not appearing

### ISSUE THREAD

**Issue by theutz** [statamic/cms#8128]
### Bug description

The whole panel with the Live Preview buttons don't seem to be appearing.

![CleanShot 2023-05-12 at 14 00 08@2x](https://github.com/statamic/cms/assets/756348/2d469fbc-2fac-403a-a49d-cf42793daf8d)

Furthermore, it seems there's a `<style>` tag in the header rendering the following CSS rule:

```html
<style>.publish-tab-actions{display:none}</style>
```

If I deactivate the rule, then I can, in fact, use the Live Preview just fine.

### How to reproduce

I'm using the Collaboration plugin and I have revisions enabled. Not sure if those are factors in this, but they seem somewhat related to how that panel is rendered.

### Environment

```yaml
Environment
Application Name: Delegator
Laravel Version: 9.52.4
PHP Version: 8.2.6
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: delegator.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: redis
Database: mysql
Logs: stack / single, flare
Mail: smtp
Queue: redis
Session: redis

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.1.0 PRO

Statamic Addons
aerni/font-awesome: dev-main
rias/statamic-redirect: 3.0.0
statamic/collaboration: 0.6.0
statamic/seo-pro: 5.0.1
stillat/antlers-components: 2.0.0
visuellverstehen/statamic-classify: 2.6.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
