### ISSUE TITLE
First install error 403 on `https://outpost.statamic.com/v3/query` api

### ISSUE THREAD

**Issue by kaozaza2** [statamic/cms#8132]
### Bug description

After install usinc statamic cli with `statamic new app` then serve an app, cannot access control panel page

### How to reproduce

* Install fresh app using `statamic new app`
* serving app using `php artisan serve`
* then access homepage is work, but cannot access control panel page:

![Outpost api error 403](https://github.com/statamic/cms/assets/11665930/45ec2aa8-67d3-4f32-b152-f818795b823d)

### Logs

```shell
[2023-05-13 06:31:28] local.ERROR: Client error: `POST https://outpost.statamic.com/v3/query` resulted in a `403 Forbidden` response:
<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" conte (truncated...)
 {"exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 403): Client error: `POST https://outpost.statamic.com/v3/query` resulted in a `403 Forbidden` response:
<!DOCTYPE html>
<html lang=\"en-US\">
<head>
    <title>Just a moment...</title>
    <meta http-equiv=\"Content-Type\" conte (truncated...)
 at /home/work/workspace/app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.10.1
PHP Version: 8.1.18
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: marano.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.1.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
