### ISSUE TITLE
Collaboration addon thumbnails appear broken when mixing local and production users

### ISSUE THREAD

**Issue by paradise-london** [statamic/cms#8136]
### Bug description

# The Issue

If you run the Collaboration addon on both local environment production environments, a local user's avatar will appear as a broken thumbnail to the production user.

Here are a couple of screenshots from different Statamic installations

![Screenshot 2023-05-15 at 12 16 08](https://github.com/statamic/cms/assets/86011907/ea2b3608-0d3f-47b4-9c43-631d4e9bd6f8)
![Screenshot 2023-05-15 at 12 18 34](https://github.com/statamic/cms/assets/86011907/a79a52ff-d80e-4227-9c52-f9df037ac2eb)

## More information
This happens on both v3 and v4

I suppose you could just say "Don't run the addon locally" but since I work locally 90% of the time, including making edits, using Collaboration is really handy to see if a user is editing the same page I'm on, so I know to avoid conflicts.
It works great between local/production apart from this thumbnail issue.

### How to reproduce

1. Set up Collaboration locally
2. Set up Collaboration on a production environment
3. Log in as user1 on a particular entry on the local environment
4. Log in as user2 on the same entry on the production environment
5. On the production environment, observe user1's avatar appears as a broken thumbnail

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.5
PHP Version: 8.1.5
Composer Version: 2.3.3
Environment: local
Debug Mode: ENABLED
URL: thelens.wip
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.9 PRO

Statamic Addons
jaygeorge/admin-styler: dev-main
statamic/collaboration: 0.6.0
statamic/seo-pro: 4.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
