### ISSUE TITLE
`fullscreen: false` doesn't work on nested grids/replicators

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8137]
### Bug description

When you nest a replicator/grid in a replicator the `fullscreen: false` option doesn't work. The fullscreen button is always available.

### How to reproduce

1. Add a replicator
2. Add a grid or replicator to the replicator
3. Set `fullscreen` to `false`

### Environment

```yaml
Environment
Laravel Version: 9.52.7
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.1.0 PRO

Statamic Addons
rias/statamic-color-swatches: 2.2.0
studio1902/statamic-peak-browser-appearance: 2.0
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.0
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
