### ISSUE TITLE
[4.x] Set Alt Link is visible in grid view even with the setting disabled

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#8144]
### Bug description

If you have an asset field with **grid view** and you turn off the 'set alt' link in the fieldtype settings, the link still shows up in the CP when you edit an entry. The link is hidden in list view only.

<img width="1216" alt="Bildschirmfoto 2023-05-16 um 10 29 31" src="https://github.com/statamic/cms/assets/8265902/22579980-c936-4802-a62f-c249fac9ac65">

<img width="577" alt="Bildschirmfoto 2023-05-16 um 10 29 06" src="https://github.com/statamic/cms/assets/8265902/87d800c1-475d-40c1-af46-4a390181db82">

### How to reproduce

Create an asset fieldtype with grid view and set alt link turned off.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.10.1
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: v4-test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.1.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
