### ISSUE TITLE
[4.x] `min_files` on asset fieldtype does not validate 

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#8145]
### Bug description

If you add a value in the 'Mini Files' setting on an asset field type, you are also able to save the entry in the CP if there are fewer images placed. It seems to me that this setting doesn't make any difference. It does not make any difference whether a `max_files` value is set or not.

<img width="865" alt="Bildschirmfoto 2023-05-16 um 11 16 14" src="https://github.com/statamic/cms/assets/8265902/e2655f52-8549-44c3-8b32-761b833471b4">

<img width="661" alt="Bildschirmfoto 2023-05-16 um 10 58 44" src="https://github.com/statamic/cms/assets/8265902/b3354231-47cc-4ce7-b539-bff1c1de46d6">

### How to reproduce

- Create an asset field type. Choose 2 in the Min-Files settings.
- Create an entry, add only 1 image and save the entry.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.10.1
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: v4-test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.1.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
