### ISSUE TITLE
[4.x] GraphQL incorrect types for replicator field

### ISSUE THREAD

**Issue by lotarbo** [statamic/cms#8146]
### Bug description

GraphQL generates replicator set types only for last blueprint in order for same field

### How to reproduce

Create two blueprints in Pages:
Page and About
Each has hero replicator field
Hero in Page has `hero_image` set
Hero in About has `hero_video` set

when i have this order 
<img width="1027" alt="image" src="https://github.com/statamic/cms/assets/1766890/f3728b82-eee4-4a28-9f29-d13b5c7b87d8">
graphql generates only `Set_Hero_Image` type

when change order to this
<img width="983" alt="image" src="https://github.com/statamic/cms/assets/1766890/55470477-835d-4fc0-9df7-337767137a79">
graphql generates only `Set_Hero_Video` type

so, generated types depends on last blueprint in order

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.10.1
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: statamic-graphql-issue.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.1.2 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
