### ISSUE TITLE
Static cache is not warmed when using Basic Auth

### ISSUE THREAD

**Issue by mynetx** [statamic/cms#8149]
### Bug description

The static cache cannot be warmed when the website is configured to use HTTP Basic Auth.

### How to reproduce

* Set HTTP Basic Auth, for example with Laravel Forge.
* Enable static caching by setting your caching strategy to full in your `.env`:

```env
STATAMIC_STATIC_CACHING_STRATEGY=full
```

* Go to your terminal and call `php please static:warm`.

### Logs

```shell
Visiting 50 URLs...
[✗] /.../... → 401 Unauthorized
[✗] /.../... → 401 Unauthorized
[✗] /.../... → 401 Unauthorized
[✗] /.../... → 401 Unauthorized
[✗] /... → 401 Unauthorized
[✗] / → 401 Unauthorized

etc.
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.7
PHP Version: 8.2.5
Composer Version: 2.4.3
Environment: local
Debug Mode: ENABLED
URL: website.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Enabled
Version: 3.4.11 PRO

Statamic Addons
aerni/advanced-seo: 2.0.6
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
