### ISSUE TITLE
Make bookmarks/favorites URL relative

### ISSUE THREAD

**Issue by luizboaretto** [statamic/cms#815]
The URLs bookmarks URLs are full saved. This can be a problem when changing later.

```yaml
  favorites:
    -
      name: 'Blueprints ‹ Statamic'
      url: 'http://my-blank-site.test/cp/fields/blueprints'
    -
      name: 'Fieldsets ‹ Statamic'
      url: 'http://my-blank-site.test/cp/fields/fieldsets'
```

Suggestion: use CP_ROUTE here to not break if admin prefix changes.
