### ISSUE TITLE
Asset reupload not working for non-super users

### ISSUE THREAD

**Issue by joshuablum** [statamic/cms#8162]
### Bug description

This bug came up in support. A user with all the appropriate permissions (non-super) wasn't able to use the reupload feature while the replace feature worked fine.
Following permissions were set (all available asset permissions):
```
'configure asset containers'
'view [asset_container] assets'
'upload [asset_container] assets'
'edit [asset_container] assets'
'move [asset_container] assets'
'rename [asset_container] assets'
'delete [asset_container] assets'
```

![CleanShot 2023-05-17 at 8 30 01@2x](https://github.com/statamic/cms/assets/3824203/f47cb60e-6fe3-4ab8-ac16-f72df24e6b2d)

### How to reproduce

Create user, set permissions, and try to reupload an asset.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.7
PHP Version: 8.2.6
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: v4-playground.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.1.2 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
