### ISSUE TITLE
Icon dropdown sits behind other fields

### ISSUE THREAD

**Issue by CjRootStudio** [statamic/cms#8165]
### Bug description

When nested inside of a Grid or Replicator field, the new Icon fieldtype seems to have a z-index issue and sits behind other fields below it. I'm unable to select an option from the dropdown as a result.

A temporary workaround is using my arrow keys to cycle through the dropdown and using enter to select the icon.

<img width="893" alt="Screenshot 2023-05-18 at 09 33 58" src="https://github.com/statamic/cms/assets/108793851/cd07d37f-3563-46a3-9c70-878cecf7e348">

### How to reproduce

Add an Icon fieldtype into a Grid or Replicator field with more than 1 Icon available to select. View the template and try to select an icon from the dropdown.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.7
PHP Version: 8.1.12
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: statamic.test/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.1.3 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.1.0
jacksleight/statamic-bard-texstyle: 3.1.0
jonassiewertsen/statamic-livewire: 2.12.0
rootstudio/monitor: 0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
