### ISSUE TITLE
Validation between two date fieldtypes does not work

### ISSUE THREAD

**Issue by Kuldas** [statamic/cms#8172]
### Bug description

There is a validation problem between two date fieldtypes. I have created `start_date` and `end_date`. For `end_date` I have set the validation `after_or_equal:{this}.start_date`. 

For example, I enter today's date in `start_date` and tomorrow's date in `end_date` and I want to save the changes, I get an error that the condition was not met. 

![statamic-error](https://github.com/statamic/cms/assets/15139047/a53d6a31-e9ab-4a9f-8804-c3372ca2fcd8)

### How to reproduce

The easiest reproduction is by using the Peak starter kit and installing the `Business Hours` preset.

1. Install Peak starter kit via CLI
2. Install Business Hours preset via CLI - `php please peak:install-preset`
3. Insert exception in `exceptions` section

### Environment

```yaml
Environment
Application Name: Testovací Statamic
Laravel Version: 10.11.0
PHP Version: 8.1.17
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.1.3 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 2.0
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.0
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
