### ISSUE TITLE
Set picker positioning switches between groups

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8173]
### Bug description

When you have replicator/bard set picker with a few groups the picker can switch above/below the plus button.
![gif](https://github.com/statamic/cms/assets/69107412/9a580a14-3738-498a-a447-c237351cdb48)

Perhaps the picker should always open where it opened on first click.

### How to reproduce

Add a set picker with a bunch of groups and items. Click around. 

### Environment

```yaml
Environment
Laravel Version: 9.52.7
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.1.3 PRO

Statamic Addons
rias/statamic-color-swatches: 2.2.0
studio1902/statamic-peak-browser-appearance: 2.0
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.0
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
