### ISSUE TITLE
Live Preview not working when using NGINX reverse-proxy [Updated Title]

### ISSUE THREAD

**Issue by Cabbidachi** [statamic/cms#8180]
### Bug description

I have a setup where Statamic is running on a random port while i am accessing it with the help of proxy_pass in NGINX. Statamic itself is also running with NGINX but simply with another port.
The entire website remains functional except for the Statamic control panel. For some reason that one causes the proxy to basically be disabled and it trying to access the address in the proxy_pass directly. Which does not really work when its written down as localhost. But even with it being a proper IP address or domain it can't connect.

### How to reproduce

Make two NGINX configs
one for Statamic and one for proxy_pass
The Statamic one you can setup like listed in the Installation Guide (i used the one for Ubuntu)
For the proxy_pass simply do something like this:
`server {`
`listen 443 ssl;`
`# certificates`
`server_name yourdomain.com;`
`location / { `
`proxy_pass http://localhost:12345; `
`# Here you put the port that you gave your Statamic instance`
`}`
`}`
This should also work with a HTTP config (aka. Port 80) but i am doing it with the help of HTTPS while there is technically a third config that converts all http requests to https.

### Environment

```yaml
Environment
Application Name: LunarEngine
Laravel Version: 9.50.0
PHP Version: 8.2.6
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: cabbidachi.gay
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.2.0 Solo
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

### Additional details

i should add that this likely has something to do with the proxy,
since the website works completly fine without any problems if i just run Statamic on the 443 Port.
The only reason i am trying this out is because i want a single config for location setup and also feel more save when the website itself isnt hosted on a known port.
