### ISSUE TITLE
Entries cannot be saved if a date field is conditionally displayed.

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#8185]
### Bug description

I have a collection with two date fields: 
- The first is used for `date`. 
- The second date field is optional and will only be displayed conditionally, depending on a radio fieldtype. 

<img width="1148" alt="Bildschirmfoto 2023-05-22 um 14 41 04" src="https://github.com/statamic/cms/assets/8265902/495538f6-88c8-4f9f-80a8-5fa2d107131f">

I do not have any validations set in the blueprint. But when I create a new entry and don't save a value for the second date field, I get an error, when trying to save the entry in the CP. The error is not obvious, I have to choose option B to see the info in the second date field.

<img width="869" alt="Bildschirmfoto 2023-05-22 um 14 34 33" src="https://github.com/statamic/cms/assets/8265902/24c95195-2250-46af-b81d-ed8262eba441">
<img width="832" alt="Bildschirmfoto 2023-05-22 um 14 34 45" src="https://github.com/statamic/cms/assets/8265902/8da2fbf1-5067-4d4f-b8c0-659f046dcf33">

  
If I delete the condition I can save the entry with a blank second date.
<img width="781" alt="Bildschirmfoto 2023-05-22 um 14 37 03" src="https://github.com/statamic/cms/assets/8265902/635f252f-3340-4aad-b522-df0937277f51">

### How to reproduce

- Create a date based collection
- Add a second date fieldtype in the blueprint
- Add a radio fieldtype with option A and B
- Add a condition on the second date field: Show when radio_field equals B

- Create a new entry: Choose option A (and don't add a second date)
- Save entry → Error appears.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.11.0
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: v4-test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.2.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
