### ISSUE TITLE
Date field validation fails for date ranges

### ISSUE THREAD

**Issue by marijoo** [statamic/cms#8187]
### Bug description

After upgrading to Statamic 4.2 from 3.x saving an entry with a date range field fails [here](https://github.com/statamic/cms/blob/bbdb937a31bc281dd639209e584aa00d716caac4/src/Validation/DateFieldtype.php#L40).

It seems that the validation looks for an array key of `date` but dumping `$value` gives only `start` and `end` each with `Carbon` instances when the date field is in range mode:

```
array:2 [▼
  "start" => Illuminate\Support\Carbon @1693519200 {#4062 ▶}
  "end" => Illuminate\Support\Carbon @1693519200 {#4082 ▶}
]
```

### How to reproduce

Define a date with the following setup:

```md
handle: date
field:
  mode: range
  time_enabled: false
  time_seconds_enabled: false
  full_width: false
  inline: false
  columns: 1
  rows: 1
  display: Datum
  type: date
  icon: date
  localizable: false
  listable: hidden
  instructions_position: above
  visibility: visible
  always_save: false
  validate:
    - required
  format: Y-m-d
```

### Logs

```shell
Undefined array key "date" {"userId":"919795b3-9a28-4cc4-8744-f6dd8844fde8","exception":"[object] (ErrorException(code: 0): Undefined array key \"date\" at /vendor/statamic/cms/src/Validation/DateFieldtype.php:40)
[stacktrace]
#0 /vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Undefined array...', '/Users/marijan/...', 40)
#1 /vendor/statamic/cms/src/Validation/DateFieldtype.php(40): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'Undefined array...', '/Users/marijan/...', 40)
#2 /vendor/statamic/cms/src/Fieldtypes/Date.php(362): Statamic\\Validation\\DateFieldtype->__invoke(Array)
…
```

### Environment

```yaml
Environment
Application Name: Sauerlandpark Hemer
Laravel Version: 10.11.0
PHP Version: 8.2.3
Composer Version: 2.5.4
Environment: development
Debug Mode: ENABLED
URL: sauerlandpark-hemer.de.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: single
Mail: log
Queue: sync
Session: file

Localization
Installed: de, en
LaravelLang\Attributes\Plugin: v2.3.3
LaravelLang\Lang\Plugin: 12.21.5
Protected Locales: de, en
Publisher Version: v14.6.4

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.2.0 PRO

Statamic Addons
aryehraber/statamic-color-extractor: 1.3.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by marijoo** [comment]
@duncanmcclean Will this be fixed by #8205? We would like to roll out 4.x but this one is holding us back.

**Comment by jasonvarga** [comment]
@marijoo Is that date field inside a replicator/grid/bard?

**Comment by marijoo** [comment]
> @marijoo Is that date field inside a replicator/grid/bard?

Yes, the fields where this problem occurred are part of a replicator set. Will test as soon as the release lands. Thanks!

**Comment by marijoo** [comment]
@jasonvarga Unfortunately the problem still persists even though the error changed a bit. The `date` field mentioned above is located inside a `grid` field.

I’m getting `Trying to access array offset on value of type null` at [this location](https://github.com/statamic/cms/blob/600ae223bd900879b712b845c421b40622cd5467/src/Fieldtypes/Date.php#L377) when I try to save an entry. This even happens when I remove the `required` validation rule. Saving works fine if I remove the date range field from the `grid`.

Here is an example what the data looks like – `dates` is the mentioned `grid` field:

```md
…
dates:
  -
    id: ldeff0p5
    date:
      start: '2023-09-01'
      end: '2023-09-01'
    start_time: '20:00'
  -
    id: ZvZQ50Zg
    date:
      start: '2023-10-01'
      end: '2023-10-03'
    start_time: '20:00'
…
```

**Comment by mscruse** [comment]
I'm seeing the same error, not used in a replicator, but the date range is conditionally shown/hidden (and not required).

Drop this blueprint in your "pages" blueprints folder for a bare-bones example. 

When "Show Date Range" is set to "no", the error appears.

```yaml
title: DateTest
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: show_date_range
            field:
              options:
                'yes': 'Yes'
                'no': 'No'
              default: 'no'
              type: button_group
              display: 'Show Date Range'
              icon: button_group
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: date_range
            field:
              mode: range
              inline: false
              full_width: false
              columns: 1
              rows: 1
              time_enabled: false
              time_seconds_enabled: false
              type: date
              display: 'Date Range'
              icon: date
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              if:
                show_date_range: 'equals yes'
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
          -
            handle: parent
            field:
              type: entries
              collections:
                - pages
              max_items: 1
              listable: false
              localizable: true
```
