### ISSUE TITLE
Support modifiers (like chunk, group) on query builder variable instances

### ISSUE THREAD

**Issue by tobimori** [statamic/cms#8195]
### Bug description

See issue #6082

### How to reproduce

1. Create an asset field in a blueprint.
2. Assign some assets to that field.
3. Loop over the field with the chunk modifier.

```
{{ images chunk='2' }}
    {{ chunk }}
        {{ url }}<br>
    {{ /chunk }}
    <br>
{{ /images }}
```
4. Nothing is printed. The loop is never processed.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.7
PHP Version: 8.2.6
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: enfore.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.2.0 PRO

Statamic Addons
aerni/advanced-seo: 2.1.1
ncla/statamic-focal-point-fieldtype: 3.0.0
rias/statamic-color-swatches: 2.2.0
rias/statamic-redirect: 3.0.1
thoughtco/statamic-blurhash: 1.0.4
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
