### ISSUE TITLE
[4.x] Small UI glitch in Safari when expanding entries in collection list

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#8201]
### Bug description

If you display an entries column in an collection list and have more than two entries linked, you see a «View :count more» link. If you expand this link, the last entry has a little more whitespace around the border. Even in a row without a «View :count more» link in Safari. In Chrome, the rendering is correct.

Before expanding:
<img width="415" alt="Bildschirmfoto 2023-05-26 um 08 46 10" src="https://github.com/statamic/cms/assets/8265902/1bf6b260-fb41-4c8b-8b6d-e232b73efde7">

After expanding:
<img width="458" alt="Bildschirmfoto 2023-05-26 um 08 46 17" src="https://github.com/statamic/cms/assets/8265902/ced9a8ad-4027-48be-941b-1913a7fe6233">

### How to reproduce

- Add a entry fieldtype to a blueprint.
- Create an entry and link a least 3 entries from an other collections.
- Show the entry fieldtype in the collection list in Safari.

### Environment

```yaml
Environment
Application Name: Schnätzi
Laravel Version: 10.12.0
PHP Version: 8.1.11
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: /
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.3.0 PRO

Statamic Addons
aryehraber/statamic-color-extractor: 1.3.0
rias/statamic-color-swatches: 2.2.0
rias/statamic-redirect: 3.0.1
statamic/seo-pro: 5.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
