### ISSUE TITLE
Serialization of Closure is not allowed - Blade layout component

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#8203]
### Bug description

Related to: https://github.com/statamic/cms/pull/6935

I am experiencing a 'Serialization of 'Closure' is not allowed' error in a blade layout component.

Simply defining a custom method in my component causes the error. If I remove all custom methods then the error goes away. 

Calling existing Blade Component functions, such as __construct(), data() or render() is fine. It's custom functions that are a problem. It seems these functions need to be excluded from NoCache as the related pull request above did for other functions.

I have verified this by adding my custom function names to the exclusions list in src/StaticCaching/NoCache/Region.php@filterContext()
It works!

```
<?php

namespace App\View\Components;

class SiteLayout extends Component
{
    public function custom() {
        return 'whatever';
    } 
}
```

Then in my sitelayout.blade.php:
`@nocache('partials.toolbar')`

### How to reproduce

- Make a blade layout component
- Use it in your entry view
- Use the nocache tag within the layout template
- Add a custom method to the component class.

### Environment

```yaml
Environment
Laravel Version: 9.52.7
PHP Version: 8.1.12
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED

Statamic
Addons: 6
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.2.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
