### ISSUE TITLE
When selecting a lot of assets (50+) the query string is too long and throws an error in the browser

### ISSUE THREAD

**Issue by ryanmitchell** [statamic/cms#8208]
### Bug description

We are building a site with a lot of assets. A LOT.

When selecting lots of assets in the asset field type, it builds a URL as follows to handle the selection:

```
/cp/assets-fieldtype?assets[]=assets::artists%2Fpip-cowley%2Flife%2Fimage-1685014173.jpeg&assets[]=assets::artists%2Fpip-cowley%2Flife%2Fimage-1685017366.jpeg
```

However, when you start to get in the the 60+ asset region this URL string becomes too large for the browser (Safari) to send and you get a CF_URL error in the developer console and the request is never attempted.

Could you switch to sending this data by POST instead of GET as it would prevent this from happening?

### How to reproduce

See description above, more information can be provided if required.

### Environment

```yaml
Environment
Application Name: levineleavitt
Laravel Version: 9.52.7
PHP Version: 8.1.18
Composer Version: 2.5.7
Environment: staging
Debug Mode: ENABLED
URL: levine.servers.tc
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: postmark
Queue: sync
Session: file

Statamic
Addons: 9
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.3.0 PRO

Statamic Addons
aerni/social-links: 3.1.0
aryehraber/statamic-captcha: 1.10.0
mitydigital/iconamic: 1.1.4
statamic/seo-pro: 5.1.0
steadfast-collective/statamic-cp-resources: 2.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
