### ISSUE TITLE
Not able to create texonomy entries in second site of multisite

### ISSUE THREAD

**Issue by 1986webdeveloper** [statamic/cms#8216]
### Bug description

Not able to create texonomy entries in multisite. showing blank page when click on create entry in second site.

![image](https://github.com/statamic/cms/assets/6542302/eaf7b524-0694-4f8b-8b2b-c0a0ffd54996)

In console showing error

```
app-3beb22f3.js:5 TypeError: Cannot read properties of undefined (reading 'url')
    at q.livePreviewUrl (app-3beb22f3.js:188:93602)
    at M.get (app-3beb22f3.js:5:42279)
    at M.evaluate (app-3beb22f3.js:5:43343)
    at q.livePreviewUrl (app-3beb22f3.js:5:45757)
    at fn (app-3beb22f3.js:188:100809)
    at Object.B [as default] (app-3beb22f3.js:5:21685)
    at q.render (app-3beb22f3.js:188:27456)
    at M._render (app-3beb22f3.js:5:24987)
    at q.N (app-3beb22f3.js:5:29723)
    at M.get (app-3beb22f3.js:5:42279)
logError @ app-3beb22f3.js:5
```

### How to reproduce

1. Create texonomy with some entries
2. Create multisite 
3. Create texonomy in second site. 

### Environment

```yaml
Environment
Application Name: Statamic Peak
Laravel Version: 9.52.7
PHP Version: 8.1.18
Composer Version: 2.5.5
Environment: production
Debug Mode: OFF
URL: 127.0.0.1:8000/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.3.0 PRO

Statamic Addons
acquaintsoft/radiofield: dev-master
aerni/social-links: 3.1.0
studio1902/statamic-peak-commands: 1.27
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
