### ISSUE TITLE
Statamic::tag('user:can'): incorrect results

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#8217]
### Bug description

I've been trying this in Blade and PHP on a user who does not have permission to edit pages:
`Statamic::tag('user:can')->param('do', 'edit pages entries')->fetch()`

Dumping the result shows an empty array.
Using print_r on the result shows (bool) true.

I get the same result no matter what I pass in the param chain, even if I pass a collection that doesn't exist.

### How to reproduce

Try to use the tag in Blade / PHP (not antlers)

### Environment

```yaml
Laravel Version: 9.52.7
PHP Version: 8.1.12
Composer Version: 2.5.5
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.3.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
