### ISSUE TITLE
Pinned CP nav items are missing icon

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#8220]
### Bug description

![Screenshot 2023-05-30 at 16 13 10](https://github.com/statamic/cms/assets/126740/1057ea92-1065-4ea0-a002-19601d0dcbf4)

### How to reproduce

Pin an item to the CP nav

### Environment

```yaml
Statamic
Addons: 11
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.1.2 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
