### ISSUE TITLE
class btn-group behaves different than expected

### ISSUE THREAD

**Issue by manogi** [statamic/cms#8222]
### Bug description

In my addons, I try to use as little custom styles as possible. So I saw that a class "btn-group" exists, and wanted to use this for a "group of buttons" in my addon:

<img width="304" alt="CleanShot 2023-05-30 at 17 38 50@2x" src="https://github.com/statamic/cms/assets/1419634/0391b3ed-f61e-4477-bc3b-3faf3039c1c5">

As you can see the last button behaves differently (less horizontal padding), and I know exactly why you did it this way - you use this button for example as the "Enter" Button next to the "save" buttons:

<img width="296" alt="CleanShot 2023-05-30 at 17 42 25@2x" src="https://github.com/statamic/cms/assets/1419634/d16355e9-a290-401d-a739-157f1b1344dc">

So my questions is - should I write my own little Button Group class (no problem for me), or would you go over the styles somewhere in the next months and change them so that in a "Button Group" class all the button actually have the same horizontal padding?

Thanks, cheers, have a nice day!

### How to reproduce

Use a "btn-group" class in a fieldset addon.

### Environment

```yaml
Environment
Application Name: ******
Laravel Version: 10.13.0
PHP Version: 8.2.3
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: ******
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.3.0 PRO

Statamic Addons
doublethreedigital/runway: 5.0.6
kraenkvisuell/shop: 1.0.0
kraenkvisuell/statamic-helpers: 0.24.0
kraenkvisuell/translatable: 1.0.0
statamic/eloquent-driver: 2.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
