### ISSUE TITLE
[4.x] Live Preview does not change viewport size back to responsive

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#8224]
### Bug description

If you change the viewport size from laptop, tablet or any other fixed size back to responsive, the preview no longer adjusts. It stucks on the last fixed viewport size.

### How to reproduce

1. Open Live Preview
2. Change viewport size to Laptop, Tablet or anything else. 
3. Change viewport size back to Responsive → The live view does not get responsive capabilities any more. 

### Environment

```yaml
Application Name: Statamic
Laravel Version: 10.13.0
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: v4-test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.4.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
