### ISSUE TITLE
[4.x] Bard "Add set" button is always visible and there is no option to deactivate in Control Panel

### ISSUE THREAD

**Issue by rgbfreak** [statamic/cms#8226]
### Bug description

Bard "Add set" button is always visible, and the only way to disable is in the fieldset.yaml file.

If you delete this row, it disappears
`always_show_set_button: true`

### How to reproduce

If you enabled the option in Statamic 3.x in a Bard element and you upgrade the Statamic Version to 4.x you wont be able to disable this funtion in the Control Panel anymore

At least it should mention in the upgrade docs: https://statamic.dev/upgrade-guide/3-4-to-4-0

Statamic 3.x Bard Settings
![grafik](https://github.com/statamic/cms/assets/5921023/c3ade61b-7140-4dbe-a027-35041f1c04c0)

Statamic 4.x Bard Settings
![grafik](https://github.com/statamic/cms/assets/5921023/619751aa-9a78-4627-b380-fec478e2e185)

### Environment

```yaml
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.3.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 2.0
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.1
studio1902/statamic-peak-tools: 3.2
```

### Installation

Existing Laravel app

### Antlers Parser

None
