### ISSUE TITLE
403 forbidden on save 

### ISSUE THREAD

**Issue by JoeriE** [statamic/cms#8229]
### Bug description

When saving any entry, global, .. I get the error 403 forbidden

<img width="424" alt="image" src="https://github.com/statamic/cms/assets/11161180/73009f8f-0142-4dce-beeb-e807a3719b76">

### How to reproduce

This mostly happens on production environments, didn't have this issue on local environment (Laravel Valet)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.13.0
PHP Version: 8.1.16
Composer Version: 1.10.17
Environment: dev
Debug Mode: OFF
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.4.0 PRO

Statamic Addons
aerni/advanced-seo: 2.1.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
