### ISSUE TITLE
Statamic magic routes not injecting $page variable in blade layout

### ISSUE THREAD

**Issue by ilicmarko** [statamic/cms#8235]
### Bug description

When using Statamic magic routes (`Route::statamic`) and the layout is set to a blade file the `$page` variable won't be injected, [like in the docs](https://statamic.dev/blade#current-page).

If that same layout is used inside the collection/blueprint the `$page` variable works.

Based on the debugger my guess is there is a difference between `FrontendController@index` and `FrontendController@route` as they resolve the blade differently.

### How to reproduce

1. Create a blade layout `debug.blade.php` and print out the `$page` variable.
```blade
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Debug</title>
    </head>
    <body class="bg-gray-100 font-sans leading-normal text-gray-800">
        {{ dd($page) }}
    </body>
</html>
```
2. Create a new collection and set the `Template` to `debug` (file from above) inside that collection's blueprint.
3. Create a new entry inside that collection `Test`
4. Open `yoursite/test` and you will see the page printed.
5. Now in `web.php` add a magic route
```php
Route::statamic('blade', 'default', [
    'layout' => 'debug'
]);
```
6. Open `yoursite/blade`, you will see an error `Undefined variable $page`

### Environment

```yaml
Application Name: Statamic
Laravel Version: 10.10.1
PHP Version: 8.2.0RC3
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.4.0 PRO

Statamic Addons
statamic/eloquent-driver: 2.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
