### ISSUE TITLE
User tags not working

### ISSUE THREAD

**Issue by maxi032** [statamic/cms#8238]
### Bug description

I am using Blade but if I want to check if a user is logged in or to get the user permissions by using the user tag, I get back an empty array.
This is related to https://github.com/statamic/cms/issues/8217 which fixes the user:can problem but tags like user:profile or user:is are still not working

### How to reproduce

Try to call Statamic::tag('user:profile')->fetch();
        

### Environment

```yaml
Environment
Application Name: statamic
Laravel Version: 9.52.6
PHP Version: 8.2.4
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: array
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.4.11 PRO

Statamic Addons
aryehraber/statamic-impersonator: 2.4.1
spatie/statamic-responsive-images: 3.1.3
statamic/eloquent-driver: 1.2.0
withcandour/aardvark-seo: 2.0.30
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
