### ISSUE TITLE
Forms listing table visual issues

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8244]
### Bug description

The listing table has wonky corners and probably needs some v4 treatment:
<img width="992" alt="Screenshot 2023-06-01 at 09 53 33" src="https://github.com/statamic/cms/assets/69107412/cefa033e-0e82-463e-80e4-627596d7b4ee">

Actions also don't seem to appear. I'd expect 'Delete' and 'Duplicate' as an option there.
<img width="967" alt="Screenshot 2023-06-01 at 09 55 18" src="https://github.com/statamic/cms/assets/69107412/dea1d395-0961-4fd6-a3d0-a4777cfc7720">

### How to reproduce

Check the forms listing table.
Try actions

### Environment

```yaml
Environment
Laravel Version: 9.52.8
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.4.0 PRO

Statamic Addons
rias/statamic-color-swatches: 2.2.0
studio1902/statamic-peak-browser-appearance: 2.0
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.1.1
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
