### ISSUE TITLE
`embed_url` modifier doesn't support YouTube links anymore

### ISSUE THREAD

**Issue by axelferdinand** [statamic/cms#8249]
### Bug description

Have anyone of you struggled with the `embed_url` modifier?

Here's the value of `video_embed`:
https://www.youtube.com/watch?v=hyJ7CBs_2RQ&t=2s

Here's my markup:
```
{{ if video_embed | is_embeddable }}
    <div class="video__embed">
        <iframe class="video__embed__iframe" data-gesture="media" data-allow="encrypted-media" allowfullscreen src="{{ video_embed | embed_url }}"></iframe>
    </div>
{{ /if }}
```

Here's the output:
```
<div class="video__embed">
        <iframe class="video__embed__iframe" data-gesture="media" data-allow="encrypted-media" allowfullscreen="" src="https://www.youtube-nocookie.com/embed/hyJ7CBs_2RQ&amp;t=2s"></iframe>
    </div>
```

...and here's how it looks like when hitting play (see attached screenshot)

![image](https://github.com/statamic/cms/assets/10460870/73fe0fec-b9c9-4b0b-b4ae-586ea6c44cfc)

Have YouTube changed their logic, so the `embed_url` modifier doesn't work longer?

### How to reproduce

Just try to embed a youtube-link and use the `embed_url` modifier

### Environment

```yaml
Environment
Application Name: Virke
Laravel Version: 10.13.0
PHP Version: 8.1.17
Composer Version: 2.5.5
Environment: development
Debug Mode: ENABLED
URL: virke.proto
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: sendmail
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.4.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
