### ISSUE TITLE
Licence banner blocks asset editor save button

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#8252]
### Bug description

I know you can just click dismiss, but it would be great if it was easier to get to the asset save button when in Pro demo mode:

![Screenshot 2023-06-01 at 17 13 33](https://github.com/statamic/cms/assets/126740/70468857-ea0f-4e26-b1d4-87bedead48c2)

Maybe the editor could render on top of the banner? 

It blocks other things as well:

![Screenshot 2023-06-01 at 17 17 53](https://github.com/statamic/cms/assets/126740/0b12ee21-43e3-4cb9-9919-1c6687d4dbfb)

### How to reproduce

Edit an asset in Pro demo mode.

### Environment

```yaml
Statamic
Addons: 9
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.4.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
