### ISSUE TITLE
Grid hints show HTML tags

### ISSUE THREAD

**Issue by aerni** [statamic/cms#8256]
### Bug description

The hints in a Grid show HTML tags.

<img width="845" alt="CleanShot 2023-06-02 at 12 01 02@2x" src="https://github.com/statamic/cms/assets/23167701/1f2e6803-e1b1-4234-bcf6-327e4a7762ee">

### How to reproduce

Create a Grid in table mode and add a field with instructions.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.13.1
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: statamic-snipcart.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.5.0 PRO

Statamic Addons
aerni/snipcart: dev-feature/statamic-4
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
