### ISSUE TITLE
`user:profile_form` doesn't save when a field in the blueprint is of type `date`

### ISSUE THREAD

**Issue by danielfowler** [statamic/cms#8257]
### Bug description

I have a `birthdate` field in `settings/fieldsets/user.yaml` configured as a `date` fieldtype. I am testing `{{ user:profile_form }}` and found that when that HTML input gets submitted, none of the form data saves. If I change that fieldtype to `text` and submit again, all of it saves as expected. I encountered no error messages or errors in the log file.

### How to reproduce

1. Add a `date` field called `birthdate` to User blueprint.
2. Add HTML input to template inside `{{ user:profile_form }}` tag pair. e.g. `<input name="birthdate" type="date"/>`
3. Edit any other input values.
4. Save form.
5. Check user file - no changes to data.
6. Change fieldtype to `text` within User blueprint and save form again.

### Environment

```yaml
Environment
Application Name: Brella Studio
Laravel Version: 10.13.0
PHP Version: 8.2.3
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: brella.localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.4.0 PRO

Statamic Addons
duncanmcclean/guest-entries: 3.1.0
statamic/migrator: dev-master
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
