### ISSUE TITLE
Cannot add multiple field conditions using the same field for comparison

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/cms#8260]
### Bug description

Recently discovered it is impossible or very difficult if you attempt to compare the same field to multiple values.  If you add multiple conditions using the same field the last one will overwrite all the previous ones (due to the conditions being yaml keyed based on the field name).

### How to reproduce

1. Add a text field to a blueprint
2. Add another text field and add two conditions - for the field, select the field from step 1 and anything else for the operator and value
3. Save the field and blueprint

The result will be only the last field condition being saved as only one condition can be created per field.

### Environment

```yaml
Environment
Application Name: Infomedia
Laravel Version: 9.52.8
PHP Version: 8.0.28
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
URL: infomedia.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.5.0 Solo

Statamic Addons
rias/statamic-color-swatches: 2.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

There are sometimes ways around this bug as you can negate the conditions or use the "hide when" instead of the "show when" but these limitations are not clear from the UI allowing you to select the same field for two conditions.  In my opinion it would be nice to be able to use multiple conditions rather than just adding a disclaimer saying you can't.
