### ISSUE TITLE
Copy function not working in update dialog

### ISSUE THREAD

**Issue by christophstockinger** [statamic/cms#8266]
### Bug description

I have updated an existing Statamic 3 project to Statamic 4. I would update the addons. I used the user interface to get the new commands for updated the dependencies.
But the copy function not set some content to the clipboard. The follow screenshot shows the right command but in my clipboard are old stuff.

![Screenshot 2023-06-05 at 20 38 56](https://github.com/statamic/cms/assets/24808473/037e26bb-fa9a-406f-abcd-7055df48a6f7)

### How to reproduce

After the update I got infos to update other addons. After the klick on the "Update"-Button on the detail page and the dialog is open and shows the update command with an Copy-Icon. On click on the copy icon nothing will be set to the clipboard.

### Environment

```yaml
Environment
Application Name: Konkav & K16
Laravel Version: 9.52.5
PHP Version: 8.2.5
Composer Version: 2.5.7
Environment: local
Debug Mode: ENABLED
URL: k16-konkav-cms.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.5.0 PRO

Statamic Addons
aryehraber/statamic-uuid: 2.2.0
studio1902/statamic-peak-browser-appearance: 1.0
studio1902/statamic-peak-commands: 1.27
studio1902/statamic-peak-seo: 1.7
studio1902/statamic-peak-tools: 2.5
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
