### ISSUE TITLE
Blueprint visibility inside a Taxonomy blueprint cannot be changed

### ISSUE THREAD

**Issue by benammiswift** [statamic/cms#8270]
### Bug description

When creating a taxonomy, I created a blueprint as the only blueprint for this taxonomy and accidentally set the "Hidden" slider, which hides the BP from the create buttons in the CP, to enabled. Hiding the Blueprint.

This caused me to be unable to create a new taxonomy term. 

On realising my error, I attempted to change the "Hidden" slider on the BP back to disabled but every time time I saved and went back to the taxonomy there was no change and upon editting the BP again, the slider was re-enabled hiding the BP.

There was no error messages when saving and Statamic gave the regular "Saved!" popup when saving.

### How to reproduce

- In the CP, go to Taxonomies
- Click the "Create Taxonomy" button
- Name the Taxonomy and again click the "Create Taxonomy" button
- Click "Configure Taxonomy"
- Then under "Content Model" -> Blueprints, press the "Edit" button next the BP matching your Taxonomy name
- Open up the BP matching the taxonomy name from the list
- Enable the "Hidden" slider and save
- Go back out to Blueprints
- Go back into the Taxonomy name BP
- Toggle the "hidden" slider off again and save
- Go back out to blueprints
- Go back into the Taxonomy name BP
- Observe the "Hidden" slider has been re-enabled (No amount of resaving will fix this, it can only be fixed by deleting the BP to get a fresh one and not enabling the "Hidden" slider)

### Environment

```yaml
Environment
Application Name: FPS
Laravel Version: 9.52.8
PHP Version: 8.1.18
Composer Version: 2.6-dev+595559f68d8c01715a2be33a54247898f9fbc34e
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.2.0 PRO

Statamic Addons
alt-design/o-cart: dev-benammi
jonassiewertsen/statamic-livewire: 2.12.0
statamic/eloquent-driver: 2.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
