### ISSUE TITLE
Collection filtering intersection between two arrays

### ISSUE THREAD

**Issue by JoeriE** [statamic/cms#8275]
### Bug description

I want to filter a collection if the value in an array is also in another array. 
I have two collections:
1. Services
2. Projects

The services are linked to a project (can be multiple sevices project).
So one project had the field services with multiple services:
```
services:
  - ef6d7b79-7d0f-423d-ae05-cedfeabeafd8
  - cbb3c216-dca4-4f29-9ee0-1c712756cf2a
```
Now I want to show all related projects that also contain one of those services.

I understand that that's not possible by default in Statamic, so I created a custom scope:

```
<?php

namespace App\Scopes;

use Statamic\Query\Scopes\Scope;

class Intersect extends Scope
{
    public function apply($query, $values)
    {
        $query->whereJsonContains(
            $values->get('intersect_field'),
            $values->explode('intersect_value'),
        );
    }
}
```

And in my template it looks like this:
```
{{ ids = ef6d7b79-7d0f-423d-ae05-cedfeabeafd8|cbb3c216-dca4-4f29-9ee0-1c712756cf2a }}
{{ collection:projects as="results" :id:not="page:id" query_scope="intersect" intersect_field="services" :intersect_value="ids" }}
Results here 
{{ /collection:projects }}
```

So right now it only returns the projects that have both services.
Is there any way to show the projects that have on of the services listed?

I know this would be easier by making services a taxonomy but because of various reasons that is not possible in this case..

Thanks!

### Environment

```yaml
Environment
Application Name:
Laravel Version: 10.11.0
PHP Version: 8.1.15
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.1.2 PRO

Statamic Addons
aerni/advanced-seo: 2.1.1
stillat/relationships: 2.1.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
