### ISSUE TITLE
"Always Save" toggle resets back to original state on linked fields

### ISSUE THREAD

**Issue by generator85** [statamic/cms#8277]
### Bug description

On a linked field, when enabling the "Always Save" option and saving the blueprint. The next time (or after a refresh), the setting is turned off again.

### How to reproduce

1. Create a fieldset and add a bard fieldtype (in my case it was a bard field).
2. Link the field in blueprint and edit it.
3. Enable the "Always Save" option.
4. Save the form and the blueprint.
5. Refresh the page, now when you open the linked field in the blueprint the setting is reset again.

### Environment

```yaml
Environment
Application Name: My Project
Laravel Version: 10.13.2
PHP Version: 8.2.6
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: myproject.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: ses
Queue: sync
Session: file

Localization
Installed: en, nl
LaravelLang\Attributes\Plugin: v2.3.3
LaravelLang\HttpStatuses\Plugin: v3.3.1
LaravelLang\Lang\Plugin: 12.21.9
Protected Locales: nl
Publisher Version: v14.6.4

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.5.0 Solo

Statamic Addons
aerni/livewire-forms: 8.0.1
aerni/social-links: 3.1.0
dryven/faviconator: 1.2.1
jonassiewertsen/statamic-livewire: 2.12.0
statamic/seo-pro: 5.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
