### ISSUE TITLE
Toggle field UI bug

### ISSUE THREAD

**Issue by aerni** [statamic/cms#8279]
### Bug description

A toggle field inside a grid in table mode collapses way too much. And changing the width of the field in the blueprint editor doesn't make a difference either. Removing `width: 1%` in the CSS fixes it.

![CleanShot 2023-06-07 at 14 01 55@2x](https://github.com/statamic/cms/assets/23167701/41a32590-ce0d-453c-907b-6cc5fe4f8e57)

### How to reproduce

Use this blueprint and check for yourself:

```yaml
title: Product
tabs:
  new_tab:
    display: 'New Tab'
    sections:
      -
        display: 'New Section'
        fields:
          -
            handle: grid_field
            field:
              fields:
                -
                  handle: text_field_1
                  field:
                    input_type: text
                    antlers: false
                    type: text
                    display: 'Text Field 1'
                    icon: text
                    localizable: false
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    hide_display: false
                -
                  handle: text_field_2
                  field:
                    input_type: text
                    antlers: false
                    type: text
                    display: 'Text Field 2'
                    icon: text
                    localizable: false
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    hide_display: false
                -
                  handle: toggle_field
                  field:
                    default: false
                    type: toggle
                    display: 'Toggle Field'
                    icon: toggle
                    localizable: false
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    hide_display: false
              mode: table
              reorderable: true
              fullscreen: true
              type: grid
              display: 'Grid Field'
              icon: grid
              localizable: false
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.13.1
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: statamic-snipcart.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.5.0 PRO

Statamic Addons
aerni/snipcart: dev-feature/statamic-4
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
