### ISSUE TITLE
Collection column reset not working properly

### ISSUE THREAD

**Issue by lakkes-ra** [statamic/cms#8285]
### Bug description

Since v4 the collection overview shows the published-sate field on the far right side. I usally want to have it on the left side. If I press the costumize columns button and than click on Reset, the published-state column moves to the left but after a refresh it's back on the right.  

When I click on Reset, then re-open the costumize columns options and then press on save, it stays on the left.  

Here's a video:  

https://github.com/statamic/cms/assets/63732644/f995401c-aee3-46ec-8b62-8104798bb610

### How to reproduce

- Install a fresh statamic project
- Create a new collection
- Add some entries
- Open the collection 
- Do the steps from the video above

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.13.2
PHP Version: 8.1.19
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: column-bug.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.6.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
