### ISSUE TITLE
Toggle UI in sidebar

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#8289]
### Bug description

When adding a Toggle to the sidebar, and set the instructions to "Below" it places the instructions to the right. When setting the instructions to "Above" it is better.

![Screenshot 2023-06-09 at 12 46 29](https://github.com/statamic/cms/assets/1135679/0e6315a5-1fed-45ff-a199-b1e098b1436f)

### How to reproduce

Described above.

### Environment

```yaml
Environment
Application Name: Esso Energi
Laravel Version: 10.10.0
PHP Version: 8.1.17
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.6.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
