### ISSUE TITLE
A page saved in another language should have the same parent than the original page

### ISSUE THREAD

**Issue by GuyVervillePerso** [statamic/cms#8291]
### Bug description

When saving an entry. When saving the default language (en) and going to the French version, the parent is automatically set to Home (Accueil in French) rather than staying under the English parent set.
![CleanShot 2023-06-10 at 09 54 58](https://github.com/statamic/cms/assets/69694028/637ca264-014e-424a-9a96-769502e6934f)

### How to reproduce

1. Create a page in a multisite under an existing page (it has to be a child).
2. After saving, change to the other language.
3. The page has the Home page as a parent rather than staying where it should.
4. The consequence is misleading the user and can be cumbersome if we have a lot of pages to search through.

### Environment

```yaml
Environment
Application Name: Harmonic Studies
Laravel Version: 9.52.7
PHP Version: 8.2.3
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: harmonicstudies.ddev.site
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.6.0 PRO

Statamic Addons
aerni/advanced-seo: 2.1.1
jonassiewertsen/statamic-live-search: 1.7.0
jonassiewertsen/statamic-livewire: 2.12.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
