### ISSUE TITLE
Core filters are missing if custom scopes/filters have same handle/class name

### ISSUE THREAD

**Issue by conradfuhrman** [statamic/cms#8295]
### Bug description

The `Fields` filtering capability is missing from the list view of collections. On a custom collection the only available filter is `Status`. I believe this is related to that we have the Eloquent Driver installed. 

Here is what we see with our collection:
<img width="1800" alt="Screenshot_2023-06-12_at_9 18 27_AM" src="https://github.com/statamic/cms/assets/455824/4405c022-700c-4208-949d-9abd94dc528b">

Even on the default Pages collection we only see status and blueprints as filterable items instead of the fields option:
<img width="1814" alt="Screenshot 2023-06-12 at 12 56 47 PM" src="https://github.com/statamic/cms/assets/455824/d1014101-3530-42dd-aa55-31ffc737d078">

### How to reproduce

Install the eloquent driver add-on and create a new collection. Add additional fields to the blueprint. Check the list view of the collection to see if they are available via a fields dropdown for filtering. Fields will most likely not be present.

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 9.52.8
PHP Version: 8.2.6
Composer Version: 2.5.7
Environment: local
Debug Mode: ENABLED
URL: allygarage.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Octane: swoole (this has been disabled on our content environment where we are actively working)
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.6.0 PRO

Statamic Addons
doublethreedigital/runway: 5.0.6
rias/statamic-collection-groups: 1.1.0
statamic/eloquent-driver: 2.1.0
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

### Additional details

Runs on Laravel Vapor so removing the Eloquent Driver is not an option.
