### ISSUE TITLE
Video Fieldtype: Preview Video is overflowing …

### ISSUE THREAD

**Issue by thepalk** [statamic/cms#8298]
### Bug description

The Preview Video is overflowing.
<img width="1151" alt="Bildschirmfoto 2023-06-13 um 12 25 23" src="https://github.com/statamic/cms/assets/69767296/71f9c6d3-29fb-4dac-b268-4cdcc2293df6">

### How to reproduce

Go Video Fieldtype, paste video url with aspect ratio 9:16 (story format), see overflow

### Environment

```yaml
Environment
Application Name: Records
Laravel Version: 9.52.7
PHP Version: 8.2.6
Composer Version: 2.5.7
Environment: local
Debug Mode: ENABLED
URL: records.test/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.2.0 PRO

Statamic Addons
o1y/statamic-flexible-width: 1.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
