### ISSUE TITLE
Can't save in nested stack selector when creating new terms

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8308]
### Bug description

I have a collection with a taxonomy in a stack selector. The taxonomy blueprint itself has another taxonomy linked, also in a stack selector.

When creating an entry and both terms you want to attach aren't available you can't save the terms. When the deepest taxonomy has already been created you _can_ save.

https://github.com/statamic/cms/assets/69107412/38b75240-57b4-43ae-b4df-b2fb238035bc

### How to reproduce

1. Create a collection
2. Create a taxonomy
3. Link taxonomy to collection blueprint with a stack selector
4. Create another taxonomy
5. Link this taxonomy to the first taxonomy with a stack selector
6. Create a new entry and attach two new terms.

### Environment

```yaml
Environment
Laravel Version: 10.13.5
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.6.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 2.0
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.2
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
