### ISSUE TITLE
Chrome Issue: Stacks on Stacks on Stacks

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#8315]
### Bug description

In Chrome, there are currently rendering problems as soon as there are multiple stacks (getting buggy around 3 and not workable at 5).

https://github.com/statamic/cms/assets/9936988/015db65f-6a66-49a7-8a86-b6d75665cde2

### How to reproduce

Create some nested blueprint leading to multiple steps

### Environment

```yaml
Environment
Application Name: Perlacherhof
Laravel Version: 10.13.5
PHP Version: 8.2.6
Composer Version: 2.2.21
Environment: local
Debug Mode: ENABLED
URL: perlacherhof.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.6.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 2.0
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.3
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
