### ISSUE TITLE
Typeahead dropdown on wrong position when in replicator

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8316]
### Bug description

I have taxonomy terms field in typeahead mode in a replicator set. The dropdown (when searching) is in the wrong position. It's relative to the top of the dropdown instead of the bottom. Note that the initial dropdown appears above the select field.

<img width="728" alt="Screenshot 2023-06-16 at 09 36 28" src="https://github.com/statamic/cms/assets/69107412/61b6cb73-aa61-4ea8-bb8f-88b9050f9a0d">

This might also be the case for a select field. 

### How to reproduce

Add replicator
Add sets
Add typeahead field to set
Search in the typeahead field

### Environment

```yaml
Environment
Laravel Version: 10.13.5
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.6.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 2.0
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.2
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
