### ISSUE TITLE
Multisite generated slug from generated title

### ISSUE THREAD

**Issue by lakkes-ra** [statamic/cms#8317]
### Bug description

We have a `headline` field as Bard, because we need superscript and subscript numbers in our titles. We switched the title field from a text field to a hidden field since Statamic always requires a field with the handle `title`. We created a Bard field `headline` and told the collection config to generate the `title` based on the `{headline}`. In our source language, if I click save, the slug gets generated properly. When I switch to the other language and type in another title and hit save, the slug doesnt get updated. 

May be better to understand in this video:

https://github.com/statamic/cms/assets/63732644/db81b1f3-6869-4224-9cf0-f1807216ab61

Sometimes, when I use [cmd]+[s] on first creation it actually works, but I cant figure out any patterns behind it. 

Do you have any ideas or maybe workarounds?

Best regards!

### How to reproduce

- Create a multisite statamic
- Create a Bard field `headline` in your collection. 
- Tell your collection to generate the `title` from `{headline}.`
- Hide the title Field in your blueprint
- Create an entry and type in the headline -> the slug should be generated after clicking save.
- Localize this entry and type in another headline -> the slug stays the same after clicking save.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.10.0
PHP Version: 8.2.6
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: isasev.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: redis
Database: mysql
Logs: stack / single, slack
Mail: log
Queue: redis
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.6.0 PRO

Statamic Addons
elvenstar/statamic-meilisearch: dev-main
visuellverstehen/statamic-classify: 2.6.1
visuellverstehen/statamic-content-renderer: 0.1.1-beta
visuellverstehen/statamic-picturesque: 1.2.0
```

### Installation

Other (please explain)

### Antlers Parser

runtime (new)
