### ISSUE TITLE
Password forgotten option removed from CP login screen with oAuth enabled

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8329]
### Bug description

When you have set `STATAMIC_OAUTH_ENABLED` to `true` the Password forgotten link gets removed from the CP login screen.

### How to reproduce

Enable oAuth
Go the the CP login page
Click 'Login with email'

### Environment

```yaml
Environment
Application Name: Stichting Lutje Geluk
Laravel Version: 10.13.5
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: lutjegeluk.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: database

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.6.0 PRO

Statamic Addons
doublethreedigital/guest-entries: 3.1.0
statamic/eloquent-driver: 2.1.0
studio1902/statamic-peak-browser-appearance: 3.1.1
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.3
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
