### ISSUE TITLE
Field instructions in grid in table mode don't get parsed.

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8333]
### Bug description

Field instructions in a grid in table mode don't get parsed. It shows the raw html in de popper floaty thingy.
<img width="925" alt="Screenshot 2023-06-21 at 14 15 11" src="https://github.com/statamic/cms/assets/69107412/a1f98b06-7fd7-4e98-9939-45d26d5584d5">

### How to reproduce

1. Add a grid in table mode
2. Add fields and give them instructions
3. Hover over the `i` in the grid table head.

### Environment

```yaml
Environment
Application Name: Stichting Lutje Geluk
Laravel Version: 10.13.5
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: lutjegeluk.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: database

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.7.0 PRO

Statamic Addons
doublethreedigital/guest-entries: 3.1.0
statamic/eloquent-driver: 2.1.0
studio1902/statamic-peak-browser-appearance: 3.1.1
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.3
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
