### ISSUE TITLE
Can't use Nova, Telescope Gate in Laravel

### ISSUE THREAD

**Issue by goellner** [statamic/cms#8337]
### Bug description

i am currently trying to get Laravel Nova and Statamic to work with eloquent and after debugging for 5 hours I found one issue in the statamic AuthServiceProvider:

```
 Gate::before(function ($user, $ability) {
            return optional(User::fromUser($user))->isSuper() ? true : null;
        });
```

This `before` hook also overrides gates defined in Laravel Nova, Telescope, Horizion, ... 

Example of Novas default gate: 
```
 Gate::define('viewNova', function ($user) {
        return in_array($user->email, [
            'taylor@laravel.com',
        ]);
    });
 ```
 Can the before be wrapped in something to only be applied to statamics auth? 
 
        

### How to reproduce

If you need a demo repo with Statamic and Telescope for example I could set one up for you if needed.

### Environment

```yaml
Environment
Application Name: HP
Laravel Version: 10.13.5
PHP Version: 8.1.18
Composer Version: 2.5.5
Environment: staging
Debug Mode: ENABLED
URL: cms.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.7.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
