### ISSUE TITLE
Fieldsets can import, but not reference other fieldsets

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#834]
Using the terminology from https://statamic.dev/blueprints#reusable-fields and it's subsections:

We are able to import entire fieldsets into another fieldset, but we can't reference a field from another fieldset.

Given a fieldset `resources/fieldsets/a.yaml` with fields `b` and `c`, this will work in `resources/fielsets/x.yaml` (and import both fields `b` and `c` into the replicator set):
```
fields:
  foo:
    type: replicator
    sets:
      bar:
        fields:
          - import: a
```
But this won't:
```
fields:
  foo:
    type: replicator
    sets:
      bar:
        fields:
          -
            handle: baz
            field: a.b
            config:
              display: Something overriding the display name configured for field b in a.yaml
```
