### ISSUE TITLE
Relative URL in live preview targets not working

### ISSUE THREAD

**Issue by helloiamlukas** [statamic/cms#8340]
### Bug description

We have been using [Custom Renderings](https://statamic.dev/live-preview#custom-rendering) for the Live Preview. After updating to Statamic 4, this does not work anymore.

Whenever the Live Preview is opened the following error is showing up in the Chrome console.

```
Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at q.updateIframeContents
```

### How to reproduce

Use a relative path for the preview target:

```yaml
preview_targets:
  -
    label: Entry
    format: /render-live-preview
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.13.5
PHP Version: 8.1.18
Composer Version: 2.4.0
Environment: local
Debug Mode: ENABLED
URL: cool-writings.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.7.0 Solo
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

### Additional details

For now this can be fixed by using an absolute URL:

```yaml
preview_targets:
  -
    label: Entry
    format: http://cool-writings.test/render-live-preview
```
