### ISSUE TITLE
Configure Collection instead of Configure Form string on Form edit page

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8350]
### Bug description

When you're on a form edit page in the CP the title says 'Configure Collection' instead of 'Configure Form'.
<img width="1291" alt="Screenshot 2023-06-25 at 21 28 49" src="https://github.com/statamic/cms/assets/69107412/72082bdd-7d2d-4aeb-b0a3-842102f81ba9">

### How to reproduce

Go the form edit page in the CP.

### Environment

```yaml
Environment
Application Name: Statamic Peak Development
Laravel Version: 9.52.9
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.3.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: dev-main
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.2
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
