### ISSUE TITLE
Debugbar no longer loads since v4.8.0

### ISSUE THREAD

**Issue by ryanmitchell** [statamic/cms#8352]
### Bug description

The debugbar on our staging site no longer loads since v4.8.0 (at a guess with the inclusion of the antlers performance profiler).

We are getting a JS error in the console `Invalid or unexpected token`, relating to this line in the logs:
https://pastebin.com/PXchbt1G

I can provide access to the site if this is required.

### How to reproduce

See above.

### Logs

```shell
https://pastebin.com/PXchbt1G
(GitHub couldn't cope with the length of the log)
```

### Environment

```yaml
Environment
Laravel Version: 10.13.5
PHP Version: 8.1.20
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: postmark
Queue: redis
Scout: meilisearch_multiple
Session: database

Statamic
Addons: 8
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.8.0 PRO

Statamic Addons
aerni/social-links: 3.1.0
doublethreedigital/runway: 5.0.10
jonassiewertsen/statamic-livewire: 2.12.0
pecotamic/sitemap: 1.4.6
statamic/eloquent-driver: 2.2.0
statamic/seo-pro: 5.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
