### ISSUE TITLE
Bard in bard inline formating Issue …

### ISSUE THREAD

**Issue by thepalk** [statamic/cms#8359]
### Bug description

Hi there, I've come to notice that the formatting when in a set in bard using the inline mode is not quite working as expected in Safari.

https://github.com/statamic/cms/assets/69767296/0dbe8d10-27fb-4b3b-a6ba-ea306acc72e2

### How to reproduce

This should do the trick:

```yaml
-
        handle: fliesstext
        field:
          collapse: false
          character_limit: '100000'
          always_show_set_button: false
          previews: true
          smart_typography: false
          buttons:
            - bold
            - italic
          container: assets
          save_html: false
          inline: false
          toolbar_mode: fixed
          link_noopener: true
          link_noreferrer: true
          target_blank: true
          reading_time: true
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          antlers: false
          remove_empty_nodes: false
          display: Text
          type: bard
          icon: bard
          listable: hidden
          instructions_position: above
          visibility: visible
          sets:
            externer_artikel:
              display: 'Externer Artikel'
              fields:
                -
                  handle: link_text
                  field:
                    collapse: false
                    always_show_set_button: false
                    previews: true
                    smart_typography: false
                    buttons:
                      - bold
                      - italic
                    save_html: false
                    inline: true
                    toolbar_mode: floating
                    link_noopener: false
                    link_noreferrer: false
                    target_blank: false
                    reading_time: false
                    fullscreen: true
                    allow_source: true
                    enable_input_rules: true
                    enable_paste_rules: true
                    antlers: false
                    remove_empty_nodes: false
                    display: 'Link Text'
                    type: bard
                    icon: bard
                    width: 50
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: link_url
                  field:
                    container: assets
                    display: Link
                    type: link
                    icon: link
                    width: 50
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: text_zum_link
                  field:
                    collapse: false
                    always_show_set_button: false
                    previews: true
                    smart_typography: false
                    buttons:
                      - bold
                      - italic
                    save_html: false
                    inline: false
                    toolbar_mode: floating
                    link_noopener: true
                    link_noreferrer: false
                    target_blank: false
                    reading_time: false
                    fullscreen: true
                    allow_source: true
                    enable_input_rules: true
                    enable_paste_rules: true
                    antlers: false
                    remove_empty_nodes: false
                    display: 'Text zum Link'
                    type: bard
                    icon: bard
                    instructions: 'Will only be added if used.'
                    listable: hidden
                    instructions_position: above
                    visibility: visible
```

### Environment

```yaml
Environment
Application Name: eight days a week
Laravel Version: 10.13.5
PHP Version: 8.2.6
Composer Version: 2.5.7
Environment: local
Debug Mode: ENABLED
URL: eightdaw.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 14
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.9.0 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.1.0
dryven/faviconator: 1.2.1
edalzell/forma: 2.0.2
jacksleight/statamic-bard-mutator: 2.3.0
jacksleight/statamic-bard-texstyle: 3.1.3
jacksleight/statamic-miniset: 1.0.0
pecotamic/sitemap: 1.4.6
rias/statamic-data-import: 1.3.0
rias/statamic-redirect: 3.1.0
silentz/akismet: 4.0.1
sitestein/statamic-form-webhooks: 2.0.0
statamic/collaboration: 0.6.0
takepart-media/statamic-oreos: 1.3.0
webographen/statamic-admin-log: 1.0.8
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
