### ISSUE TITLE
Relationship filter scope displays id instead of title in selected item

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8363]
### Bug description

When you use a custom relationship based query scope the selected item renders it's ID instead of it's Title. 

```php
/**
 * Define the filter's field items.
 *
 * @return array
 */
public function fieldItems()
{
    return [
        'id' => [
            'type' => 'entries',
            'create' => false,
            'collections' => ['outings'],
            'mode' => 'select',
            'max_items' => 1,
        ],
    ];
}
```

As you can see in the screenshot the list is populated correctly, but the selected item isn't. 

<img width="493" alt="Screenshot 2023-06-27 at 11 32 39" src="https://github.com/statamic/cms/assets/69107412/affca2d3-37a5-4ff9-af3e-a0f5d87b015f">

### How to reproduce

Create a custom query scope based on a relationship and using a select.
Select an entry in the filter bar

### Environment

```yaml
Environment
Application Name: Stichting Lutje Geluk
Laravel Version: 10.13.5
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: lutjegeluk.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: database

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.9.0 PRO

Statamic Addons
duncanmcclean/guest-entries: 3.1.0
roorda-ict/statamic-entries-export: 2.0.0
statamic/eloquent-driver: 2.3.1
studio1902/statamic-peak-browser-appearance: 3.1.1
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.3
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
