### ISSUE TITLE
Missing and broken images on bulk upload to S3

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#8369]
### Bug description

We have 2 sites that use S3 for assets and when we try to upload multiple images at once, they don't all show up and/or are broken.

On sites that use local assets we don't see this issue at all.

### How to reproduce

See video: https://share.cleanshot.com/GTSMZBxZ

### Logs

```shell
Request URL: https://www.zakat.org/cp/assets/cHVibGljOjoyMDIzLzA2L25pZ2VyLTEuanBn
Request data: []
Call to a member function id() on null

/home/forge/www.zakat.org/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php (23)
/home/forge/www.zakat.org/vendor/laravel/framework/src/Illuminate/Http/Resources/DelegatesToResource.php (155)
/home/forge/www.zakat.org/vendor/statamic/cms/src/Http/Resources/CP/Assets/Asset.php (14)
/home/forge/www.zakat.org/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php (107)
/home/forge/www.zakat.org/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceResponse.php (39)
/home/forge/www.zakat.org/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php (244)
/home/forge/www.zakat.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php (893)
/home/forge/www.zakat.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php (878)
/home/forge/www.zakat.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php (798)
/home/forge/www.zakat.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php (141)
/home/forge/www.zakat.org/vendor/statamic/cms/src/Http/Middleware/DeleteTemporaryFileUploads.php (18)
```

### Environment

```yaml
Environment
Application Name: Zakat Foundation of America
Laravel Version: 10.13.5
PHP Version: 8.2.1
Composer Version: 2.5.8
Environment: production
Debug Mode: OFF
URL: www.zakat.org
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / daily, front
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 11
Antlers: runtime
Stache Watcher: Disabled
Static Caching: half
Version: 4.7.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
doublethreedigital/runway: 5.0.10
edalzell/forma: 2.0.1
jonassiewertsen/statamic-livewire: 2.12.0
statamic/seo-pro: 5.2.0
transformstudios/events: 5.0
transformstudios/front: 2.0.4
transformstudios/github: dev-main
transformstudios/neon: dev-main
transformstudios/review: 4.1.0
transformstudios/simple: 4.2.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
