### ISSUE TITLE
Grid field: Add row text not displaying

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#837]
When creating a blueprint with a Grid fieldtype, the add row text does not display on the publish form..

Fieldset:

```
title: Actions
fields:
  actions:
    fields:
      -
        handle: label
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Label
      -
        handle: style
        field:
          options:
            link: Link
            primary: 'Primary Button'
            secondary: 'Secondary Button'
            dark: 'Dark Button'
          clearable: false
          multiple: false
          searchable: true
          taggable: false
          push_tags: false
          type: select
          localizable: false
          display: Style
      -
        handle: link
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Link
    mode: table
    max_rows: 0
    min_rows: 0
    add_row: 'Add Action'
    reorderable: true
    type: grid
    instructions: 'Add buttons or links'
    localizable: false
    width: 100
    display: Actions
```

**Publish Form:**
<img width="1134" alt="Screen Shot 2019-10-24 at 11 04 58 am" src="https://user-images.githubusercontent.com/414211/67532147-eb41b480-f710-11e9-80fc-022e4efd551a.png">
