### ISSUE TITLE
Filtering taxonomies by collection no longer working in V4(?)

### ISSUE THREAD

**Issue by michaelmannucci** [statamic/cms#8376]
### Bug description

Doing `{{ taxonomy:example collection="some_collection" }}` returns no results. Not sure if it's related to V4.

(found here in docs: https://statamic.dev/tags/taxonomy#parameters)

### How to reproduce

Create a taxonomy (collection of taxonomies?), create a collection, link a taxonomy in an entry, and do

`{{ taxonomy:example collection="some_collection" }}`

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.14.0  
PHP Version: 8.1.2        
Composer Version: 2.2.5   
Environment: local        
Debug Mode: ENABLED       
URL: eklektos-base.test   
Maintenance Mode: OFF     

Cache
Config: NOT CACHED        
Events: NOT CACHED        
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.9.1 Solo

Statamic Addons
spatie/statamic-responsive-images: 4.0.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
