### ISSUE TITLE
Nested Replicator performance issues after PR #6902

### ISSUE THREAD

**Issue by o1y** [statamic/cms#8392]
### Bug description

Since the implementation of PR #6902, which changed the `﻿v-if` conditions to ﻿`v-show`, there has been a noticeable degradation in performance in our "Page Builder" replicator field, which is using lots of nested replicator fields. I tracked the loading time of my replicator using the browser's performance profiler:

#### Firefox
* v-show: 4.5s 
* v-if: 1.8s

#### Chrome
* v-show: 1.197s
* v-if: 2.147s

The times only represent the Vue/JS loading time, until the Publish form is loaded. 

Thank you @jonassiewertsen, for pointing out the pull request!

### How to reproduce

* I've created a reproduction repository: https://github.com/o1y/statamic-replicator-performance
* Just clone it and open the Home Entry in the Pages collection in the control panel.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.14.1
PHP Version: 8.2.5
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: statamic-replicator-performance.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.9.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

By the way, it seems that there is a regression regarding the Bard Set ﻿`v-show`. It seems the change from #6902, was probably lost during resolving a merge conflict when [merging the 3.3 Branch](https://github.com/statamic/cms/commit/ee63549314abfadbe508e9533dcf10b23dc70cab#diff-7cfd02c396833cd32328461dbf72888ce7e804115318f3a4a3eb2a7d1cad865b): https://github.com/statamic/cms/blob/ee63549314abfadbe508e9533dcf10b23dc70cab/resources/js/components/fieldtypes/bard/Set.vue#L38
