### ISSUE TITLE
Extra border showing in `<publish-form>` component

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#8393]
### Bug description

When working with custom publish forms, I'm running into an issue with an extra, unnecessary border showing above the sidebar, where the 'Live Preview/Visit URL' buttons would show on entries.

I've only ran into this recently, so must have been caused by 4.x.

<img width="1246" alt="image" src="https://github.com/statamic/cms/assets/19637309/a260f1b5-bdc4-47d6-8e86-d0ccbc7b8ca7">

### How to reproduce

Either setup your own publish form (using the instructions from [the Statamic Documentation](https://statamic.dev/extending/publish-components#form)) or [install Simple Commerce](https://simple-commerce.duncanmcclean.com/installation) and go to create/edit a coupon and you'll see the issue.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.10.0
PHP Version: 8.2.3
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: sc-sandbox.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: GBP
Gateways: Stripe, Mollie, PayPal, Dummy
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Free Shipping
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\Standard\TaxEngine

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.9.2 PRO

Statamic Addons
doublethreedigital/sc-digital-products: 5.0.0
doublethreedigital/simple-commerce: 5.2.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
