### ISSUE TITLE
Slow preloading of Replicator Field meta data when importing many fieldsets

### ISSUE THREAD

**Issue by o1y** [statamic/cms#8395]
### Bug description

When creating a "Page Builder" using a combination of a Replicator and Bard Field with various imported Content Sets, the Replicator Field tends to load slowly. This is especially in situations where sets need to be nested, for example when creating a columns/layout or accordion/collapse set. This results in a performance problem as the Replicator Field needs to preload the same fields over and over.

I have identified two possible causes for this issue:

1. The `﻿toPublishArray()` method is being executed multiple times for the same fields. 
https://github.com/statamic/cms/blob/62451f1d39e3f998db1f6940d1111c43b8453016/src/Fields/Fields.php#L147-L150

3. The ﻿`preload()` method of the Replicator Field is loading the same metadata multiple times for the same config:

https://github.com/statamic/cms/blob/62451f1d39e3f998db1f6940d1111c43b8453016/src/Fieldtypes/Replicator.php#L203

I understand that this is a specific case that mainly affects those building Page Builders, like me :) However, I have noticed similar performance challenges mentioned on Discord, and we have also encountered them in our project.

### How to reproduce

* I've created a reproduction repository: https://github.com/o1y/statamic-replicator-performance/tree/publish-array-performance
* Clone it and check out the Branch `publish-array-performance` and open the Home entry in the pages collection.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.14.1
PHP Version: 8.2.5
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: statamic-replicator-performance.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.9.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
