### ISSUE TITLE
Forbidden filter: site for pages

### ISSUE THREAD

**Issue by colinupgraders** [statamic/cms#8400]
### Bug description

In Statamic 4 i get "Forbidden filter: site" when i want to get pages from the api.

### How to reproduce

I use filter[site] in the call.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.7
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.1.2 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
