### ISSUE TITLE
Globals and navigations with multisite through API

### ISSUE THREAD

**Issue by colinupgraders** [statamic/cms#8412]
### Bug description

I don't get the right data for globals and navigation when i use multisite. When I switch to other site for example the globals and navigation data stays in default value.

### How to reproduce

Get globals and navigation data through api.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.7
PHP Version: 8.2.6
Composer Version: 2.5.7
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.9.1 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
