### ISSUE TITLE
Moving/renaming of assets will not updated nested asset fields

### ISSUE THREAD

**Issue by el-schneider** [statamic/cms#8415]
### Bug description

Moving an asset or renaming a folder should update all references to that asset. 

It works, when the asset field is not nested inside a replicator field or similar, but does not if it is.

### How to reproduce

Here is a minimal reproduction: https://github.com/el-schneider/statamic-asset-renaming-issue 

To reproduce move the image to the folder and see how the `asset` field updates while the `replicator.0.nested_asset`does not.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.14.1
PHP Version: 8.2.7
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: renaming-issue.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
