### ISSUE TITLE
Stack selector pagination links gone

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8419]
### Bug description

The stack selector doesn't have pagination options anymore and you can only find unlisted page 1 items by using search.

<img width="1377" alt="Screenshot 2023-07-08 at 10 52 26" src="https://github.com/statamic/cms/assets/69107412/a3b0cee6-d928-489d-8d4c-62d33a62accb">

### How to reproduce

Add a whole lot of entries
Add a stack selector
Check the results

### Environment

```yaml
Environment
Application Name: Statamic Peak Development
Laravel Version: 9.52.10
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.10.1 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 3.0
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
