### ISSUE TITLE
Multiple assets selected on upload via assets fieldtype, regardless of max_files

### ISSUE THREAD

**Issue by dominikradl** [statamic/cms#8425]
### Bug description

The inline upload functionality of the asset fieldtype doesn't respect the set `max_files` limit, when a file was selected previously. When uploading through the fieldtype, all uploaded assets are selected.

### How to reproduce

1. Create an assets field inside a blueprint
2. Set `max_files` to `1`
3. Select an asset
4. Upload 2 files through the fieldtype
5. Now all 3 assets are selected

### Environment

```yaml
Environment
Application Name: ---
Laravel Version: 9.52.7
PHP Version: 8.1.18
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: ---
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.6.0 PRO

Statamic Addons
stillat/relationships: 2.1.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
