### ISSUE TITLE
Antlers parsing in field doesn't work with blade templates

### ISSUE THREAD

**Issue by jhhazelaar** [statamic/cms#8430]
### Bug description

Enabling the antlers parsing in field option in a field doesn't work with a blade template.

### How to reproduce

Example repo: https://github.com/jhhazelaar/statamic-blade-field-antler-parser

For antlers parsing page: https://statamic-blade-field-antler-parser.test/antlers-parser
For blade parsing page: https://statamic-blade-field-antler-parser.test/blade-parser

Halfway the page you see the antlers tag `{{ parser:parser }}` in de blade template example

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.14.1
PHP Version: 8.2.8
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: statamic-blade-field-antler-parser.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.10.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
