### ISSUE TITLE
handle_prefix + glide

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#8436]
### Bug description

I'm using `handle_prefix` with my partials, it works great, accept with `glide:url`

An example partial

```
{{ partial:partials/banner/_banner
    handle_prefix="basic_banner_"
    :title="title"
    :assets_tag="media_asset" 
}}
```

In `partials/banner/_banner` I've got this:

```
{{ title }}
{{ assets_tag }}
    {{glide:url preset='w2000_square'}}
{{ /assets_tag }}

```

`title` is using the `handle_prefix`, it works.

However, I can only get `glide:url` to work if I add the prefix to `:assets_tag,` like this

```
{{ partial:partials/banner/_banner
    handle_prefix="basic_banner_"
    :title="title"
    :assets_tag="basic_banner_media_asset" 
}}
```

### How to reproduce

Create a partial that uses glide, try to pass in parameter to glide.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.14.1
PHP Version: 8.2.2
Composer Version: 2.4.1
Environment: local
Debug Mode: OFF
URL: website.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.10.2 PRO

Statamic Addons
jonassiewertsen/statamic-jobs: 1.4.0
statamic/collaboration: 0.7.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
