### ISSUE TITLE
Augmentation: Selective raw variables inside augmented data

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#844]
Having some issues with Augmented data. Would it be possible to selectively show the raw data for a variable in an augmented data loop? This would make working with augmented data a little bit easier.

Raw:
```
{{ augmented_data|raw }}
    {{variable}}
{/augmented_data|raw }}
```

Selective:
```
{{ augmented_data }}
   {{ variable|raw }}
{{/augmented_data }}
```

<img width="1005" alt="Screen Shot 2019-10-24 at 3 27 43 pm" src="https://user-images.githubusercontent.com/414211/67534209-d1a46b00-f718-11e9-8370-22d36da0ad74.png">
<img width="1124" alt="Screen Shot 2019-10-24 at 4 28 48 pm" src="https://user-images.githubusercontent.com/414211/67534213-d5d08880-f718-11e9-8955-b34750ae3cd6.png">

**Comment by jasonvarga** [comment]
Being able to use |raw on fields inside Grids/Replicators/Bards is solved with bab391e9 (will be available in beta 15).

You can't disable augmentation per field, but maybe that's not necessary. This issue seems to be primary centered around select/radio fields that were previously augmenting to their labels. Since beta 13, you have to explicitly ask for the label. It defaults to the raw value.

If disabling augmentation per field is still something you feel you need, please reopen with an explanation of your use case.

**Comment by mikemartin** [comment]
@jasonvarga It seems there may have been a regression on this one. The default value seems to have gone back to being the select label.

**Comment by jasonvarga** [comment]
Oh?

**Comment by jasonvarga** [comment]
I can't see that. Can you give more details?

**Comment by mikemartin** [comment]
Hey @jasonvarga 

No problem. This is happening within a replicator set and I'm using the `select` fieldtype for `features_cols` and `features_type`. Here is how I'd expect my view to work:

```
<div class="grid grid-cols-1 sm:grid-cols-{{ features_cols }} {{ if features_type != 'columns' }}gap-12 {{ if large }}xl:gap-24{{ /if}}{{/if}}">
  {{ features }}
    {{ if features_type == 'cards' }}
      <div class="px-6 py-10 bg-white rounded-lg shadow-lg">
        {{ partial:elements/feature }}
      </div>
    {{ elseif features_type == 'columns' }}
      <div class="px-8 py-10 {{unless first }}border-gray-300 border-t lg:border-t-0 lg:border-l{{ /unless}}">
        {{ partial:elements/feature }}
      </div>
    {{ else }}
        {{ partial:elements/feature }}
    {{ /if }}
  {{ /features }}
</div>
```

However, `feature_cols` outputs the string `2 Columns` and `features_type` outputs `Columns`. I've tried using the `raw` modifier (`feature_cols|raw`) but it doesn't change the output.

Fieldset and replicator content below.

```
title: Features
fields:
  features_headline:
    type: text
    display: Headline
  features:
    fields:
      -
        import: feature
        prefix: feature_
    mode: table
    add_row: 'Add Feature'
    reorderable: true
    type: grid
    localizable: false
    listable: hidden
    display: Features
  features_cols:
    options:
      cols-2: '2 Columns'
      cols-3: '3 Columns'
    clearable: false
    multiple: false
    searchable: false
    taggable: false
    push_tags: false
    cast_booleans: false
    type: select
    localizable: false
    listable: hidden
    display: Columns
    width: 25
    default: 3
  large:
    type: toggle
    localizable: false
    width: 25
    listable: hidden
    display: Large
  stacked:
    type: toggle
    localizable: false
    width: 25
    listable: hidden
    display: Stacked
    default: true
  features_type:
    options:
      default: Default
      cards: Cards
      columns: Columns
    clearable: false
    multiple: false
    searchable: false
    taggable: false
    push_tags: false
    cast_booleans: false
    type: select
    localizable: false
    width: 25
    listable: hidden
    display: Type
    default: Default
```

replicator content:
```
blocks:
  -
    features:
      -
        feature_headline: 'Advanced data processing'
        feature_summary: 'Data can be interpreted in many ways. By combining and overlaying multiple data sources, we can unlock hidden insights.'
        feature_icon: icons/file-code-search.svg
      -
        feature_headline: 'Machine learning'
        feature_summary: 'With access to both extensive data analysis and existing datasets, our smart algorithms can automatically spot patterns and anomalies, accelerating discovery.'
        feature_icon: icons/brain.svg
      -
    features_cols: '3 Columns'
    stacked: true
    features_type: card
    type: features
    enabled: true
```
