### ISSUE TITLE
Impossible to hide Preview button on Term

### ISSUE THREAD

**Issue by lotarbo** [statamic/cms#8443]
### Bug description

Most of our sites - html files from Next.js static exports. So, we don't need preview button at all.
In Entry, i can hide button with custom Entry class and method 
```
    public function livePreviewUrl(): null
    {
        return null;
    }
```
but with term this doesn't work

### How to reproduce

Use statamic cms as headless cms for nextjs static exports

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.15.0
PHP Version: 8.2.6
Composer Version: 2.5.7
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.10.2 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
