### ISSUE TITLE
Antlers: SVG tag lexer error

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#8450]
### Bug description

When using an svg tag, this exception is logged by Antlers lexer:
```
ctype_digit(): Argument of type null will be interpreted as string in the future in /Users/mike/Sites/pilot/vendor/statamic/cms/src/View/Antlers/Language/Lexer/AntlersLexer.php on line 709
```

### How to reproduce

Add svg tag with parameters like class and aria-hidden.
`{{ svg:interface-delete class="h-3 w-3" aria-hidden="true" }}`

SVG file:
```
<svg viewBox="-0.25 -0.25 10.5 10.5" xmlns="http://www.w3.org/2000/svg" height="20" width="20" stroke-width="1.5"><path d="M9.5 0.5L0.5 9.5" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path><path d="M0.5 0.5L9.5 9.5" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path></svg>
```

### Environment

```yaml
Environment
Application Name: Pilot Pen Australia
Laravel Version: 9.52.9
PHP Version: 8.1.17
Composer Version: 2.4.0
Environment: local
Debug Mode: ENABLED
URL: pilot.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 14
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.11.0 PRO

Statamic Addons
aerni/social-links: 3.1.0
codedge/statamic-move-entries: dev-main
jacksleight/statamic-bard-mutator: 2.3.0
justbetter/statamic-image-optimize: 2.0.0
mikemartin/helpscout-beacon: 1.0.3
ncla/statamic-focal-point-fieldtype: 3.0.0
nineteensquared/instagram: 1.2.0
rias/statamic-color-swatches: 2.2.0
stillat/relationships: 2.1.1
studio1902/statamic-peak-browser-appearance: 2.0
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.3
studio1902/statamic-peak-tools: 3.2
swiftmade/statamic-clear-assets: 2.0.0
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
