### ISSUE TITLE
Updater copy composer command link is broken

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#8452]
### Bug description

Clicking the Copy action on the composer command modal throws this error:
`TypeError: Cannot read properties of undefined (reading 'writeText')`

### How to reproduce

Go to Updater > Addon > Update and click the copy link icon

### Environment

```yaml
Environment
Application Name: Coates Group
Laravel Version: 10.14.1
PHP Version: 8.1.17
Composer Version: 2.4.0
Environment: local
Debug Mode: ENABLED
URL: coatesgroup.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.11.0 PRO

Statamic Addons
rias/statamic-color-swatches: 2.2.0
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.6.1
studio1902/statamic-peak-tools: 3.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
