### ISSUE TITLE
Web middleware not getting merged

### ISSUE THREAD

**Issue by ilicmarko** [statamic/cms#8453]
### Bug description

According to the docs, you can [define a custom middleware](https://statamic.dev/extending/addons#middleware), which should be merged with the existing Statamic middleware.

https://github.com/statamic/cms/blob/ba62a751f0c79b74a647c9dc48dab8c676710050/src/Providers/AddonServiceProvider.php#L474-L483

This doesn't happen, because Statamic's middlewares get overwritten. This is problematic with `statamic.web` as the `StaticCaching` middleware will never be called.

https://github.com/statamic/cms/blob/ba62a751f0c79b74a647c9dc48dab8c676710050/src/Providers/AppServiceProvider.php#L162-L169

**Temporary fix:**
For anyone struggling with this a temporary fix is to include the cache middleware on your own:
```php
'statamic.web' => [
    \Statamic\StaticCaching\Middleware\Cache::class,
   // Other middleware
]
```

### How to reproduce

1. Create a new Statamic project
2. Create a dummy collection/page 
3. Enable `full` static caching
4. Validate that the cache is working (use debug bar)
5. Delete cache (important for the final step)
6. Add `'statamic.web' => []` in `$middlewareGroups` in `app/Http/Kernel.php`.
```php
protected $middlewareGroups = [
    'web' => [
        \App\Http\Middleware\EncryptCookies::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \App\Http\Middleware\VerifyCsrfToken::class,
        \Illuminate\Routing\Middleware\SubstituteBindings::class,
    ],

    'api' => [
        // \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
        \Illuminate\Routing\Middleware\ThrottleRequests::class.':api',
        \Illuminate\Routing\Middleware\SubstituteBindings::class,
    ],
    'statamic.web' => [] // Add this line
];
```
7. Refresh the page and you will see that caching stopped working.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.14.1
PHP Version: 8.2.3
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: dummy-statamic.ddev.site
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: full
Version: 4.9.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
