### ISSUE TITLE
Cannot filter users table by field title

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#8458]
### Bug description

When adding a Field filter on the users table and selecting an entries field, you can only filter using the ID and not the entry's title.

<img width="876" alt="Screenshot 2023-07-18 at 1 13 54 pm" src="https://github.com/statamic/cms/assets/414211/9cbd3858-b43b-4b91-b610-ede3379df686">
<img width="773" alt="Screenshot 2023-07-18 at 1 14 08 pm" src="https://github.com/statamic/cms/assets/414211/fe13873d-034a-435e-a354-18f843683b75">

### How to reproduce

- Go to /cp/users
- Add Field filter
- Select field with entry fieldtype
- Add contains condition with entry title

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.10.1
PHP Version: 8.1.17
Composer Version: 2.4.0
Environment: local
Debug Mode: ENABLED
URL: iveymbaa.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.11.0 PRO

Statamic Addons
jacksleight/statamic-memberbox: 2.0.1
statamic/migrator: dev-master
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
