### ISSUE TITLE
Entry field with long titles in small spaces looks odd

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8460]
### Bug description

The entries field should probably render a little more gracefully in small spaces like in this Grid field.

<img width="872" alt="Screenshot 2023-07-18 at 11 50 23" src="https://github.com/statamic/cms/assets/69107412/89de3bb6-d15e-4b7b-890f-9f236cf4ce9b">

### How to reproduce

Easiest would be to add an entries field to the sidebar of a blueprint and select an entry with a really long title.

### Environment

```yaml
Environment
Laravel Version: 9.52.10
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.11.0 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 2.3.0
jonassiewertsen/statamic-livewire: 2.12.0
rias/statamic-color-swatches: 2.2.0
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 4.0.1
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
