### ISSUE TITLE
Statamic Globals REST API entries field returns array of ids

### ISSUE THREAD

**Issue by martink635** [statamic/cms#8462]
### Bug description

Not sure if this behaviour is an issue or not, but when using the entries field on globals, does not yield to the same REST API output as using the same field in collections.

When used in globals and the content is fetched via the REST API, I get only an array of item IDs. 
When used in collections I get the small object with the properties: id, title, url, permalink, api_url

### How to reproduce

Create a global blueprint with the entries fieldtype.
Add the entries field type to a blueprint. 

Fill in the entries and call them via the REST API endpoints, and they are not the same.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.15.0
PHP Version: 8.2.7
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: ***
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.11.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
