### ISSUE TITLE
date field error message

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#8465]
### Bug description

After a while I realized, that members can not edit their profiles anymore. The members can edit some Information with the
 `{{ user:profile_form }}` - Tag.
When they save their edits, a timestamp should be saved with `{ now | format('Y-m-d H:i') }}` into a date field.
In the past this was working fine and I have no idea, when it stopped working.
But when I save now the changes, there is shown an error, that this field must be an array.
After changing the field to a text field, all works fine again.

### How to reproduce

```
{{ user:profile_form }}
{{ user }}
<input class="hidden" type="hidden" name="email" value="{{ email }}" readonly>
{{ /user }}
<input class="hidden" type="hidden" name="date_field" value="{{ now | format('Y-m-d H:i') }}" readonly>
{{ user:profile_form }}
```

### Environment

```yaml
Environment
Laravel Version: 9.52.10
PHP Version: 8.2.7
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 10
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.11.0 PRO

Statamic Addons
ddm-studio/cookie-byte: 1.3.0
heidkaemper/statamic-toolbar: 1.1.0
jezzdk/statamic-secret: 1.1
jonassiewertsen/statamic-live-search: 1.7.0
jonassiewertsen/statamic-livewire: 2.12.0
mitydigital/statamic-google-fonts: 1.0.3
nineteensquared/instagram: 1.2.0
stoffelio/statamic-404-logger: 1.0.1
transformstudios/review: 4.1.0
weareframework/pinpoint-image: 0.0.10
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
