### ISSUE TITLE
Icon fieldtype does not work when inside replicator

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#8467]
### Bug description

If you place the icon field type within replicator/set, you are not able to define a directory.

### How to reproduce

Create a replicator, add icon field type, set a custom directory.

### Environment

```yaml
Environment
Application Name: xxx
Laravel Version: 9.52.7
PHP Version: 8.2.7
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: xxx.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.11.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 2.12.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

If i set directory field to be `test`. And then dump the returning array of the resolveParts function this is what i get , and cant see test there. And `$hasConfiguredDirectory` is false.

```
array:4 [▼ // vendor/statamic/cms/src/Fieldtypes/Icon.php:80
  0 => ".../vendor/statamic/cms/src/../resources/svg/icons/regular"
  1 => ".../vendor/statamic/cms/src/../resources/svg/icons"
  2 => "regular"
  3 => false
]
```

However
