### ISSUE TITLE
z-index issue on selects inside grids inside replicators 

### ISSUE THREAD

**Issue by ryanmitchell** [statamic/cms#8468]
### Bug description

When using a select inside a grid inside a replicator there is a z-index issue on the autofill menu.

<img width="877" alt="Screenshot 2023-07-19 at 10 23 50" src="https://github.com/statamic/cms/assets/51899/08a52943-946f-4f4b-91a3-255669dcc7f8">

### How to reproduce

Download the rad pack mailchimp add-on.
Scroll down to the final field in the "Forms" tab.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.15.0
PHP Version: 8.1.8
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: statamic-coolwritings.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.x-dev PRO
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
