### ISSUE TITLE
Selected locale in tree resets when creating new entry

### ISSUE THREAD

**Issue by simonolog** [statamic/cms#8473]
### Bug description

When selecting a site/locale in the tree view of a collection in a multilang site and then creating an entry (regardless if through "Create entry"-button or context menu within the tree), the locale has changed back to the default site/locale in the publish form.

If you use the site/locale-selector in the top bar instead of the one right above the tree view, everything works as expected.

This is particularly confusing when an entry should be created as a child to an existing entry. As the locale resets to default, the new page will be created in default site and cannot be attached to the parent page (within the tree structure), as it can't find the parent page ID (which is in the non-default site) in the default page tree. Results in an exception and confuses the heck out of users.

### How to reproduce

- create fresh statamic4 site
- enable pro, add additional site, configure `pages` collection to use both locales
- go to `pages` collection, select the new site/locale in the selector above the tree view
- click the "Create entry" button

In the "Sites" part of the sidebar the default site will be active, instead of my just selected other site/locale.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.15.0
PHP Version: 8.2.7
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: statamic4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.11.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
