### ISSUE TITLE
Static Cache strips out custom headers

### ISSUE THREAD

**Issue by AntonCooper** [statamic/cms#8478]
### Bug description

Using the Static Caching half measures we've encountered an issue with response headers, applied via custom middleware or controller logic, being stripped out of a cached response. 

`Statamic\StaticCaching\Cachers\ApplicationCacher` only seems to cache the response contents and ignores any other response object details, including headers. This can result in cached responses missing important headers which may have been defined anywhere in the request stack.

### How to reproduce

Create a controller which returns a response with a `text/plain` header.
```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Statamic\Facades\Entry;

class AdsTxtController
{
    public function __invoke(Request $request): Response
    {
        $entry = Entry::find(1);

        return response($entry->content)->withHeaders([
            'Content-Type' => 'text/plain',
        ]);
    }
}

```

Add a route with the statamic.web middleware
```php
    Route::get('ads.txt', AdsTxtController::class)
        ->middleware('statamic.web');
```

Make a request to the endpoint - observe the content-type is different from the request without the cache middleware.
*With middleware*
![image](https://github.com/statamic/cms/assets/11951114/848a06bf-02d7-46d3-8ced-0ffed95cea2d)

*Without middleware*
![image](https://github.com/statamic/cms/assets/11951114/be2604cf-13eb-4e12-baa8-54ce4904e023)

### Environment

```yaml
Environment
Application Name: ****
Laravel Version: 9.52.7
PHP Version: 8.2.5
Composer Version: 2.5.7
Environment: local
Debug Mode: ENABLED
URL: ****.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: redis
Database: mysql
Logs: stack / single
Mail: log
Queue: redis
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Disabled
Static Caching: half
Version: 4.11.0 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 2.3.0
jacksleight/statamic-bard-texstyle: 3.1.3
jacksleight/statamic-distill: 0.4.2
mitydigital/feedamic: 2.2.5
statamic/collaboration: 0.7.2
statamic/eloquent-driver: 2.3.1
transformstudios/review: 4.1.0
```

### Installation

Existing Laravel app

### Antlers Parser

None
