### ISSUE TITLE
Form GraphQL not returning sections

### ISSUE THREAD

**Issue by SteJW** [statamic/cms#8482]
### Bug description

You can divide a form into sections, but it's not supported by GraphQL. Because it's visible in the CMS and I can't turn the functionality down, I would expect it to be supported in GraphQL.

### How to reproduce

Run a query:
```
query MyQuery {
  form(handle: "widget_form") {
    fields {
      instructions
      type
      display
      handle
      config
      width
    }
    title
    rules
    honeypot
    handle
  }
}
```

### Environment

```yaml
Environment
Application Name: Quadwinkel
Laravel Version: 9.52.10
PHP Version: 8.1.20
Composer Version: 2.5.8
Environment: production
Debug Mode: OFF
URL: 
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 17
Antlers: regex
Stache Watcher: Disabled
Static Caching: half
Version: 4.10.1 PRO

Statamic Addons
justbetter/statamic-image-optimize: 2.0.0
rias/statamic-data-import: 1.3.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
