### ISSUE TITLE
I can't see the draft preview unless I publish and put it back in draft

### ISSUE THREAD

**Issue by fernandogiroto** [statamic/cms#8486]
### Bug description

When I create a new entry and leave it as a draft, I can't see the preview of the page, it gives me a 404. But if I publish it and put it in draft again, it works. I want to be able to see the preview without having to publish.

**preview_targets:**
  -
    label: Entry
    url: '{permalink}'
    refresh: true

### How to reproduce

Create a new entry and leave it as a draft, I can't see the preview of the page, it gives me a 404

### Environment

```yaml
"statamic/cms": "4.11.0",
"laravel/framework": "^9.19",
"php": "^8.0.2"
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
