### ISSUE TITLE
Create Entry button gives "Page Not Found" error

### ISSUE THREAD

**Issue by mscruse** [statamic/cms#8488]
### Bug description

Fresh new site (and my existing sites) that are running 4.13.1 (note 4.13.0 is OK).

Create new entry in collection where the view is set to List View (Tree View is OK) results in "Page Not Found" error in CP.

### How to reproduce

- Create new collection.
- On the default screen of a new collection - Create Entry - works OK.
- Click create entry button to add second entry - Page not found error 
- Change to Tree View - click Create Entry button - works OK.
- Change back to List View - click Create Entry button - Page not found error.

This also happens on the default Pages collection if in list view, but tree view is OK.

### Logs

```shell
No log created.
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.16.0
PHP Version: 8.2.1
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: collectiontest.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.13.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

My test repo https://github.com/mscruse/statamic-collection-create-entry
