### ISSUE TITLE
Excessive whitespace in replicator when hide_display is true and enable_fullscreen is false

### ISSUE THREAD

**Issue by StudioNautilus** [statamic/cms#8489]
### Bug description

When you have a replicator with the display label hidden, the option for full-screen disabled and collapse set to accordion, these items are hidden, but the space they took is now whitespace:

![image](https://github.com/statamic/cms/assets/106429219/0a938bbc-6737-4d64-8dbe-59831a30f251)

### How to reproduce

Create a replicator and set:
- hide_display: true
- enable_fullscreen: false.
- collapse: accordion

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.16.1
PHP Version: 8.2.2
Composer Version: 2.3.7
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.13.1 Solo

Statamic Addons
goldnead/statamic-collapse-fieldtype: 1.0.5
jacksleight/statamic-bard-ipsum: 1.0.0
rias/statamic-button-box: 3.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
