### ISSUE TITLE
Footnote duplication while rendering with CommonMark

### ISSUE THREAD

**Issue by vhbelvadi** [statamic/cms#8495]
### Bug description

The standard footnote usage on Static with CommonMark is `[^x]` and `[^x]: Lorem ipsum...` where `x` is a number. The way this used to work on my site was with `{{ content | markdown }}` that would render the footnote superscripts and the footnotes themselves at the bottom of the content block, with anchor links.

Now the anchor links appear as expected as well as link as expected, but the footnotes list at the bottom appears twice. Specifically, it appears once in blank and the second time as expected with one caveat: there are now four backref anchor links to each footnote list item.

<img width="801" alt="Screenshot 2023-07-26 at 10 45 59 PM" src="https://github.com/statamic/cms/assets/13168700/3c5737e6-dfb0-4f85-990f-36a8bfe50fd2">

### How to reproduce

Use footnotes in the markdown field type as per usual.

Use `{{ content | markdown }}` to render it on the front end.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.10
PHP Version: 8.1.18
Composer Version: 1.10.26
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.13.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

### Additional details

Example page: https://vhbelvadi.com/legality-morality
