### ISSUE TITLE
Taxonomy view not being used when taxonomy is used on collection

### ISSUE THREAD

**Issue by sebastiandedeyne** [statamic/cms#8503]
### Bug description

According to the docs, when I visit `/tags/tools`, `resources/views/tags/show.antlers.html` template should be used.

<img width="728" alt="CleanShot 2023-07-28 at 14 57 18@2x" src="https://github.com/statamic/cms/assets/1561079/b535d33d-5e97-4dec-88e2-3fb45c043825">

In my case, Statamic is resolving `resources/views/posts/tags/show.antlers.html` instead, as the Tags collection is used my my Posts collection. Based on the docs, I'd assume `/tags/tools` would use (or at least fall back to) `resources/views/tags/show.antlers.html`, and `/posts/tags/tools` would use `resources/views/posts/tags/show.antlers.html`.

This logic is handled in `LocalizedTerm::template()` https://github.com/statamic/cms/blob/84568261d6446677ad78927ba47e9c3b1011bf62/src/Taxonomies/LocalizedTerm.php#L377-L379

### How to reproduce

- Create a Collection
- Create a Taxonomy and use it for the collection
- Create `resources/views/{taxonomy-name}/show.antlers.html`
- Template is not used for taxonomy because it's used for a collection

See https://github.com/sebastiandedeyne/sebastiandedeyne.com

### Environment

```yaml
Environment
Application Name: Sebastian De Deyne
Laravel Version: 10.16.0
PHP Version: 8.1.21
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: sebastiandedeyne.com-statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.13.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
