### ISSUE TITLE
Deleting a fieldset is not cascading itself from global set

### ISSUE THREAD

**Issue by aknEvrnky** [statamic/cms#8520]
### Bug description

I've created a fieldset. Then I've linked this fieldset to my global set. Then I figured out that I don't need a fieldset then deleted this fieldset.

After that, when I visit my frontend or my cp, I got an error that says fieldset couldn't be found.

### How to reproduce

create a new fieldset.
link this fieldset to an existing global set.
delete the fieldset.

It's done.

### Logs

Thrown exception log:
```
Fieldset test_field_set not found.
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.16.1
PHP Version: 8.2.7
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: blog-statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.13.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

I'm using blade but during the exception I don't think so it's related with view.
