### ISSUE TITLE
Add default user.yaml to resources/blueprints

### ISSUE THREAD

**Issue by twd3** [statamic/cms#853]
I got the error below after trying to edit my one and only user and it was because I didn't know I needed a default user YAML blueprint. Add a default like:
```
hide: true
fields:
  -
    handle: name
    field:
      type: text
      display: Name
  -
    handle: email
    field:
      type: text
      input: email
      display: Email Address
  -
    handle: roles
    field:
      type: user_roles
      width: 50
  -
    handle: groups
    field:
      type: user_groups
      width: 50
  -
    handle: avatar
    field:
      type: assets
      max_files: 1
```
This way people won't think it's broken when they go to edit their first user.

![screenshot-v3-tailwind test-2019 10 28-09_26_34](https://user-images.githubusercontent.com/16004958/67721976-8484fb00-f99d-11e9-97ba-443c2db32e08.png)
