### ISSUE TITLE
Hit target in entry listing table finnicky

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8535]
### Bug description

When you have a title with multiple lines, and you want to click it to get to the entry you have to explicitely click on the text and not the whitespace between the lines. If you click on the latter (which happens surprisingly often) you select the target. 

<img width="1181" alt="Screenshot 2023-08-02 at 11 55 15" src="https://github.com/statamic/cms/assets/69107412/6564389b-97fc-4c67-8422-ce1ad580d678">

### How to reproduce

Add a title that wraps multiple lines in the listing table.
Click between the text

### Environment

```yaml
Environment
Application Name: Stichting Lutje Geluk
Laravel Version: 10.17.0
PHP Version: 8.2.3
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: lutjegeluk.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: database

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.14.0 PRO

Statamic Addons
duncanmcclean/guest-entries: 3.1.1
roorda-ict/statamic-entries-export: 2.1.0
statamic/eloquent-driver: 2.5.0
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 4.0.1
studio1902/statamic-peak-tools: 3.2

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Navigation Trees: file
Navigations: file
Revisions: eloquent
Taxonomies: file
Terms: file
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
