### ISSUE TITLE
Parent field doesn't save selected page with revisions enabled

### ISSUE THREAD

**Issue by simonolog** [statamic/cms#8547]
### Bug description

In a collection that uses revisions, the parent field can not be used to select a different parent entry. Although unlinking an entry, selecting a different one and saving+publishing works, the parent field shows the previous entry again after reloading the page.

Note: If the child page is _not_ published, everything works as intended.

### How to reproduce

- create fresh statamic4 site
- enable revisions (generally and for pages collection)
- create two pages in Pages collection and publish both
- open publish form of first page, unlink "Home" in the `parent` field and select the second page, save+publish
- after reloading the page, the `parent` field shows "Home" again instead of the second page

---

Addition regarding the note (see above):
- unpublish first page
- unlink "Home", select second page, save
- after reloading the page, the `parent` field shows the second page (= working as intended)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.17.1
PHP Version: 8.2.7
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: statamic4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.15.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
