### ISSUE TITLE
Memory Leak since v4.15.0 when using `﻿statamic/ssg`

### ISSUE THREAD

**Issue by o1y** [statamic/cms#8550]
### Bug description

Starting from Statamic `v4.15.0`, the static site generator is running into a Memory Leak. It appears that the issue is caused by #8386.

### How to reproduce

I couldn't create a good reproduction using my large project, but after [patching out](https://gist.github.com/o1y/bd8f9960eded6f09f1f151dd037e00be) the mentioned commit, the Memory Leak appears to be gone. If you're unable to reproduce the issue, please let me know. I can then try to create a dedicated reproduction repository if needed.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.14.1
PHP Version: 8.2.5
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.15.0 PRO

Statamic Addons
statamic/ssg: 2.0.
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
