### ISSUE TITLE
Statamic 4 Barb Filed Type: "+" button overlaps content when editing

### ISSUE THREAD

**Issue by DuyTr** [statamic/cms#8557]
### Bug description

 "+" button overlaps content when editing barb field, attached image of Statamic version 3.4 and version 4.15

![Statamic 3 4](https://github.com/statamic/cms/assets/10933506/71bf9f52-c4e8-4362-a75f-967a62415d6c)
![Statamic 4 15](https://github.com/statamic/cms/assets/10933506/053e971e-c6df-4806-bf93-14060df63bb9)

### How to reproduce

In CP, visiting any barb field and start typing texts.

### Environment

```yaml
Environment
Laravel Version: 9.52.15
PHP Version: 8.2.5
Composer Version: 2.3.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.15.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
doublethreedigital/duplicator: 4.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
