### ISSUE TITLE
GlobalSetSaved event doesn't trigger anymore since 4.16

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8559]
### Bug description

Since 4.16 my GlobalSetSaved event doesn't trigger anymore. Possibly due to #8343?

Rolling back to 4.15 fixes it.

### How to reproduce

Try to run a GlobalSetSaved event (Peak Browser Appearance addon, generating favicons).

### Environment

```yaml
Environment
Laravel Version: 10.18.0
PHP Version: 8.2.3
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Localization
Installed: cs, da, de, en, nl, nn
LaravelLang\Attributes\Plugin: v2.4.0
LaravelLang\HttpStatuses\Plugin: v3.4.0
LaravelLang\Lang\Plugin: 12.24.2
Protected Locales: en
Publisher Version: v14.7.0

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.16.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.3.2
studio1902/statamic-peak-seo: 5.0
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
