### ISSUE TITLE
V4+ addons don't show up in the CP

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8560]
### Bug description

It seems that addons that are v4+ don't show up on the Addons page in the CP. Not in the All tab, but also not in the Installed tab. A while back I found a bug on the Marketplace on statamic.com which turned out to be related to a hard coded version check, which was swiftly resolved. Perhaps this check is also in the CP.

<img width="965" alt="Screenshot 2023-08-10 at 11 59 24" src="https://github.com/statamic/cms/assets/69107412/1137fbd3-34f5-4941-bf49-f733f73eba9b">
<img width="939" alt="Screenshot 2023-08-10 at 11 59 30" src="https://github.com/statamic/cms/assets/69107412/59260e70-987e-4589-9ee8-145b3523a8a0">

### How to reproduce

Hunt down the Peak Addons in the CP. Or Duncan's Guest Entries for example. 

### Environment

```yaml
Environment
Laravel Version: 10.18.0
PHP Version: 8.2.3
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Localization
Installed: cs, da, de, en, nl, nn
LaravelLang\Attributes\Plugin: v2.4.0
LaravelLang\HttpStatuses\Plugin: v3.4.0
LaravelLang\Lang\Plugin: 12.24.2
Protected Locales: en
Publisher Version: v14.7.0

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.16.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.3.2
studio1902/statamic-peak-seo: 5.0
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
