### ISSUE TITLE
Not clear there are more replicator sets when above a certain amount

### ISSUE THREAD

**Issue by CjRootStudio** [statamic/cms#8563]
### Bug description

Just a small UI/UX issue - when selecting a Replicator block with more than 6 sets, it is not clear there are more if you scroll down. Perhaps worth adding some kind of UI hint that there are more sets below?

For example, I have 4 extra sets below the 'CTA Boxes' row, but it isn't obvious that you need to scroll down to see them.

<img width="852" alt="Screenshot 2023-08-10 at 14 25 18" src="https://github.com/statamic/cms/assets/108793851/4915d43c-8cb8-4d11-a9cf-47223e3c4686">

### How to reproduce

Create a Replicator field with more than 6 sets. Ideally, add Icons and Instructions to each set to increase their size and further highlight the issue.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.16.1
PHP Version: 8.2.8
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: statamic.test/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.13.2 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.1.0
jacksleight/statamic-bard-texstyle: 3.1.3
jonassiewertsen/statamic-livewire: 2.12.0
rootstudio/cache-primer: 0.9
rootstudio/monitor: 0.2
statamic/collaboration: 0.7.2
statamic/eloquent-driver: 2.4.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
