### ISSUE TITLE
Nav tag recursive children not passing variable

### ISSUE THREAD

**Issue by miicah** [statamic/cms#8565]
### Bug description

Variables created outside a recursive children nav loop and referenced inside it, 'hold' the original value instead of changing it. I've used letters here as it's a bit easier to see, but in our real code we are using ints; the same issue occurs.

#### Navigation 
My basic 'main' nav I created is [here](https://gist.github.com/miicah/f52dcb803eb4507a98f578cfcf0f087d).

#### Antlers
The actual antler code is basically copy/pasted from the docs and is a simple recursive children loop.

```
        <nav>
            {{ counter = "z" }}
            
            {{ nav handle="main_nav" }}
                {{ if depth == 1 }}
                    <div class="mx-10">
                        <h3 class="mb-2">{{ title }} - {{ counter }}</h3>
                        {{ if children }}
                            <ul>{{ *recursive children* }}</ul>
                        {{ /if }}
                        
                    </div>
                {{ elseif depth == 2 }}
                    <li class="px-2 my-1">
                        <a href="{{ url }}">{{ title }} - Child of {{ counter }}</a>
                    </li>
                {{ /if }}

                {{ counter += "a" }}
            {{ /nav }}
        </nav>
```

#### Result:
<img width="237" alt="Screen Shot 2023-08-11 at 9 03 35 am" src="https://github.com/statamic/cms/assets/22931822/b3c67144-5599-49c0-9ce1-72daf2267889">

#### Expected result:
<img width="230" alt="Screen Shot 2023-08-11 at 9 14 19 am" src="https://github.com/statamic/cms/assets/22931822/72fe6d7b-3a72-4344-9fd6-e91fe682d07c">

### How to reproduce

1. Open a nav tag pair
2. Use and then increment a variable
3. Have recursive children
4. The variable used in the recursive children is the original value, not the incremented one

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.18.0
PHP Version: 8.2.8
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.16.0 Solo
```

### Installation

Starter Kit using via CLI

### Antlers Parser

regex (default)
