### ISSUE TITLE
Changing superuser params don't work

### ISSUE THREAD

**Issue by drpark** [statamic/cms#8579]
### Bug description

Saving superuser from here don't work /cp/users/2/edit , it says saving ok, but the superuser field is not changed in database

### How to reproduce

I did the existing laravel installation, and succeed to login in with my main app credentials. Creating a new user works fine with super admin rights, roles etc...

But when editing to remove super admin, saving says ok, but the data is not changed in users table.

### Environment

```yaml
Environment
Application Name: Test XXX
Laravel Version: 10.18.0
PHP Version: 8.1.2
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: test.xxxx.fr
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Localization
Installed: fr
LaravelLang\Attributes\Plugin: v2.4.0
LaravelLang\HttpStatuses\Plugin: v3.4.0
LaravelLang\Lang\Plugin: 13.0.0
Protected Locales: fr
Publisher Version: v14.7.0

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.17.0 PRO
```

### Installation

Existing Laravel app

### Antlers Parser

None
