### ISSUE TITLE
Creating a new Tab in Blueprints works in 4.13.2 but not in 4.14.0

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#8582]
### Bug description

I updated a project from 3.3.x to 3.4.x and then to 4.x. In CP when trying to add a new Tab in any of the Blueprints I get an error in the console. When reverting to 4.13.2 it works fine, but from 4.14.0 and onward it does not.

This is the error when pressing the "+" icon:
![Screenshot 2023-08-15 at 12 25 39](https://github.com/statamic/cms/assets/1135679/a7c19093-008a-4350-8c42-e8ce86a4642d)

And it seems like this is the reason:
![Screenshot 2023-08-15 at 10 56 23](https://github.com/statamic/cms/assets/1135679/de5ff47f-383f-48b2-b856-bf9d982465a1)

### How to reproduce

As this is a rather big project I'm not able to share it in this report, but I'll be happy to provide some information if needed.

### Environment

```yaml
Environment
Application Name: Bluegreen
Laravel Version: 9.52.15
PHP Version: 8.1.21
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: bgg.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.13.2 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
