### ISSUE TITLE
Replacing asset file browser doesnt show folders

### ISSUE THREAD

**Issue by lakkes-ra** [statamic/cms#8590]
### Bug description

When I click on „replace“ on an asset and browse for a new asset it only shows the images on the same level as the image I want to replace. For example: if I click on an image that is in the root folder, I only get the images that are also in the root folder. If I want to replace an image in the folder „products“ I am only shown the images from the folder products. 

I still can use the search to find all other assets. 

Here are some screenshots to explain better:  
![grafik](https://github.com/statamic/cms/assets/63732644/b5d08182-ef14-46ba-94ce-6e048e2d8a0a)
![grafik](https://github.com/statamic/cms/assets/63732644/c692783e-bbbb-4907-b8ce-dcb17963a85d)

### How to reproduce

Install a fresh statamic, put some folders and images into your assets container and reproduce the steps from above.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.18.0
PHP Version: 8.2.8
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: draft-bug.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.17.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
