### ISSUE TITLE
GlobalSet facade tries to save to table with wrong name

### ISSUE THREAD

**Issue by MtDalPizzol** [statamic/cms#8593]
### Bug description

I followed the instructions at [Global Repository](https://statamic.dev/repositories/global-repository) EXACTLY like in the docs to create a seeder.

However, when running the seeder, it fails when adding the localization to the global set, trying to use a table that doesn't exists. It's trying to insert to the table **`global_set_variables`** but the table in the database is called **`global_sets`**

Here's my code:

```php
<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Statamic\Facades\GlobalSet;

class DefaultPaymentMethodsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $globals = GlobalSet::make('payment_methods')->title('Formas de pagamento');

        $variables = $globals->makeLocalization('default');

        $variables->data([
            'payment_methods' => [
                [
                    'id' => 'lhyx36x6',
                    'max_installments' => '12',
                    'default_installment' => '12',
                    'type' => 'cc',
                    'enabled' => true,
                    'discount_amount' => '0.00',
                    'discount_percentage' => 0,
                ],
                [
                    'id' => 'lhyx3x3t',
                    'discount_type' => 'percentage',
                    'discount_percentage' => 10,
                    'type' => 'pix',
                    'enabled' => true,
                    'discount_amount' => '0.00',
                ],
            ],
        ]);

        $globals->addLocalization($variables); // <----------- Failing here

        $globals->save();
    }
}
```

Here's the output:

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'myapp.global_set_variables' doesn't exist (SQL: select * from `global_set_variables` where `handle` = payment_methods)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:760
    756▕         // If an exception occurs when attempting to run a query, we'll format the error
    757▕         // message to include the bindings with SQL, which will make this exception a
    758▕         // lot more helpful to the developer instead of just the database's errors.
    759▕         catch (Exception $e) {
  ➜ 760▕             throw new QueryException(
    761▕                 $query, $this->prepareBindings($bindings), $e
    762▕             );
    763▕         }
    764▕     }

  i   A table was not found: You might have forgotten to run your database migrations. 
      https://laravel.com/docs/master/migrations#running-migrations

      +20 vendor frames 
  21  database/seeders/DefaultPaymentMethodsSeeder.php:43
      Statamic\Globals\GlobalSet::addLocalization()

      +8 vendor frames 
  30  database/seeders/DatabaseSeeder.php:16
      Illuminate\Database\Seeder::call()
```

### How to reproduce

Just create the seeder and try to run it with `php artisan db:seed --class=DefaultPaymentMethodsSeeder`.

### Environment

```yaml
Environment
Application Name: My App
Laravel Version: 9.52.15
PHP Version: 8.2.9
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: myapp.localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: redis

Statamic
Addons: 2
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.17.0 PRO

Statamic Addons
doublethreedigital/runway: dev-main
statamic/eloquent-driver: 2.6.1

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: eloquent
Global Variables: file
Navigation Trees: file
Navigations: eloquent
Revisions: eloquent
Taxonomies: file
Terms: eloquent
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)
