### ISSUE TITLE
'join' in eloquent query_scopes overwrites ID   

### ISSUE THREAD

**Issue by simonolog** [statamic/cms#8594]
### Bug description

In one of our projects we're using eloquent users, with the user model having a `hasMany` relationship with another model (`EmployeeAffiliations` ). For a Users field we added a query_scope to filter the selectable users based on this relationship:   

```php
public function apply($query, $values)
{
	$scopes = […];

	return $query
    	→join('employee_affiliations', 'users.id', '=', 'user_id')
	    →whereIn('employee_affiliations.scope', $scopes);
}
```
   
We noticed however, that the user ids in the index view of the UserFieldtype field were wrong and in fact used the id of the row of the joined table, as it has the same column name (`id`). A web search found several hints that this is in fact a known thing in Laravel land (see e. g. [here](https://github.com/laravel/framework/issues/4962)), with the easy solution of adding a `select('users.*')`  to the query to make it work:   

```php
return $query
    →select('users.*)
    →join('employee_affiliations', 'users.id', '=', 'user_id')
    →whereIn('employee_affiliations.scope', $scopes);
```
Sadly, in our case, this *didn't* work – the ids were still wrong.   
   
Before summoning Erin to turn up and tell us to read [the docs](https://statamic.dev/tips/storing-entries-in-a-database#the-query-builder), we half realized half remembered that Statamics EloquentQueryBuilder isn't the same as Laravels actual Eloquent-Builder, but utilizes it under the hood. So, the addition of `select('users.*')`  has to be made on the Laravel builder, not on the EloquentQueryBuilder class. Unfortunately, from within the query\_scope we can't access that builder, as it is protected and doesn't have a getter.   
   
So, what eventually fixed the issue for us, was to add that statement to the constructor of the `UserQueryBuilder` :   
```php
class UserQueryBuilder extends EloquentQueryBuilder
{
    public function __construct(EloquentBuilder $builder)
    {
        $this→builder = $builder;
        $this→builder→select('users.*');
    }

    // …
}
```
   
With that addition, our query\_scope works as intended.   
   
Other options to fix the problem that came to mind would to extend the `select` function in the EloquentQueryBuilder …   
```php
public function select($columns = ['*'])
{
    $this->columns = $columns;
    // add this:
    $this->builder->select($this->columns);

    return $this;
}
```
… or adding a getter for the builder …   
```php
public function builder(): EloquentBuilder
{
    return $this->builder;
}
```
… so we can use the `select` method on the query within the query\_scope, either directly or via `$query→builder()→select('…')` .   
   
At a glance, the last option (adding a getter) seems to be the least invasive, as it doesn't *change* anything, but there is obviously the difference of using eloquent users (`Query\EloquentQueryBuilder`) or sth else (`Query\Builder`) , which probably should be taken into consideration.   
   
What do you think? I'm happy to create a PR with changes, but would be happy about feedback which way to go first.

### How to reproduce

- follow [instructions for using eloquent users](https://statamic.dev/tips/storing-users-in-a-database)
- add an arbitrary relationship to the user model (just make sure it has an `id` column)
- spin up some records for users as well as the relationship model
- create a new scope `php please make:scope Foo` and add a `join` to the query (e. g. `$query->join('my_relations', 'users.id', '=', 'my_relations.user_id')`)
- create a Users field in an entry blueprint and add the scope as query_scope
- open/create an entry with the users field, open the stack, select a person
- after closing the stack you should see either a different person than the one selected or an invalid id

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.18.0
PHP Version: 8.2.7
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: fhdort.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.17.0 PRO

Statamic Addons
doublethreedigital/duplicator: 4.0.1
elvenstar/statamic-meilisearch: 2.0.0
visuellverstehen/statamic-anchor-navigation: 0.3.4-beta
visuellverstehen/statamic-classify: 2.6.1
visuellverstehen/statamic-glossary-tooltips: dev-main
visuellverstehen/statamic-picturesque: 1.3.0
visuellverstehen/statamic-pixxio-flysystem: dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
