### ISSUE TITLE
Asset in private asset container can not be opened or downloaded in readonly asset fieldtype

### ISSUE THREAD

**Issue by rrelmy** [statamic/cms#8595]
### Bug description

Assets that are uploaded into private asset containers can not be opened in the readonly fieldtype (eg. form submissions).

Clicking the asset row opens a new tab with a corrupted URL
```
http://localhost/cp/forms/<form>/submissions/null
```

### How to reproduce

1. Create a new asset container linked to a private Laravel filesystem like this:
``` php
       'private' => [
            'driver' => 'local',
            'root' => storage_path('app/private'),
            'visibility' => 'private',
        ],
```
2. Create a form with an upload using the container
3. Submit a submission with a file
4. Open the form submission in the CP
5. Click on the asset row
6. See a «Page Not Found» page

The asset has no URL so the [Asset.open()](https://github.com/statamic/cms/blob/9a1b346cb9a641ba5e1bb33987f652af6cfc6755/resources/js/components/fieldtypes/assets/Asset.js#L79) fail. I would suggest to fallback to the download when no asset.url is available.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.15
PHP Version: 8.2.6
Composer Version: 7.1.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

…

Statamic
Addons: 8
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.18.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
