### ISSUE TITLE
Add set button inside bard overlaps text on new line

### ISSUE THREAD

**Issue by stefankempf** [statamic/cms#8603]
### Bug description

As the title says, when I'm on a new line (or proceed writing on any line actually), the plus button to add new sets is overlapping what I'm writing.

https://github.com/statamic/cms/assets/20299885/c3d963bf-402a-4af7-b476-c66328f0c5b6

### How to reproduce

Add bard, add sets, write text.

### Environment

```yaml
Environment
Laravel Version: 10.19.0
PHP Version: 8.2.8

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.18.0 PRO

Statamic Addons
appswithlove/statamic-one-click-content-translation: 4.5.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
