### ISSUE TITLE
Saved data from revealed revealer field is lost when the order of replicator sets is changed

### ISSUE THREAD

**Issue by o1y** [statamic/cms#8615]
### Bug description

When the order of replicator sets is changed, revealed revealer field loses the data that was previously stored.

![2023-08-23 11 44 58](https://github.com/statamic/cms/assets/1102712/5fbe8c70-ea42-46a7-9e24-65aee2cfd514)

### How to reproduce

1. Change the order of a replicator set. Save.
2. Change the order back. Save.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.14.1
PHP Version: 8.2.8
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.18.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

It seems that this bug is coming from https://github.com/statamic/cms/pull/7899
