### ISSUE TITLE
Custom Fieldtypes not working

### ISSUE THREAD

**Issue by wneid** [statamic/cms#8616]
### Bug description

I tried to create a new Fieldtype and followed the [docs](https://statamic.dev/extending/fieldtypes).
When I select the fieldtype and then want to fill it I get this message
![grafik](https://github.com/statamic/cms/assets/134514841/a6276cf3-1f2e-4f97-a06d-6d4f3c03ddc1)

### How to reproduce

1. I ran this command `php please make:fieldtype TogglePassword`
2. I added the cp.js to my AppServiceProvider
3. I edited my cp.js

AppServiceProvider boot method:
```
    public function boot()
    {
        Statamic::script('app', 'cp.js');
        Statamic::style('app', 'cp');

        ErrorPage::handle404AsEntry();
    }
```

cp.js:
```
import TogglePassword from "./components/fieldtypes/TogglePassword.vue";

Statamic.booting(() => {
    Statamic.$components.register('toggle_password-fieldtype', TogglePassword);
});
```

### Environment

```yaml
Environment
Laravel Version: 10.18.0
PHP Version: 8.1.17
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 8
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.17.0 PRO

Statamic Addons
arthurperton/popular: 1.1.0
ncla/statamic-focal-point-fieldtype: 3.0.0
rias/statamic-color-swatches: 2.2.0
stillat/meerkat: 3.1.0
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.3.2
studio1902/statamic-peak-seo: 4.0.1
studio1902/statamic-peak-tools: 3.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
