### ISSUE TITLE
Large assets crash server

### ISSUE THREAD

**Issue by aerni** [statamic/cms#8626]
### Bug description

I've got a private Digital Ocean Space whose content I'd like to see in the CP. So, I created an asset container and selected my S3 disk. The asset container in the CP loads forever and eventually crashes the server. There's only one file, but it's a 10GB mp4. I suppose this isn't meant to handle large assets?

### How to reproduce

- Upload a huge file to a DO Space
- Connect an asset container to your S3 disk
- See the CP crash

### Environment

```yaml
Environment
Application Name: Siloam Crowdfunding
Laravel Version: 9.52.15
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: siloam-crowdfunding.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.19.0 PRO

Statamic Addons
aerni/social-links: 3.1.0
jonassiewertsen/statamic-livewire: 2.12.0
spatie/statamic-responsive-images: 4.1.1
visuellverstehen/statamic-classify: 2.6.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
