### ISSUE TITLE
Entries Fieldtype removes entries?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#8631]
### Bug description

I'm using the entries fieldtype. I can add entries and it works as expected. However, I noticed when adding an entry that I've first filtered (in the entry selection modal) the other entires I've already added are removed?

The video below can show it better than I can explain it.

### How to reproduce

https://github.com/statamic/cms/assets/72254741/0ec638d9-3ca1-4f28-91c9-f0ad24e5ab2c

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.20.0
PHP Version: 8.2.2
Composer Version: 2.4.1
Environment: local
Debug Mode: OFF
URL: lbf-2022.test
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.19.0 PRO

Statamic Addons
jonassiewertsen/statamic-jobs: 1.4.0
jonassiewertsen/statamic-live-search: 1.7.0
jonassiewertsen/statamic-livewire: 2.12.0
statamic/collaboration: 0.7.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
