### ISSUE TITLE
No new presets generated when focal point is set / changed

### ISSUE THREAD

**Issue by GioChocolateBro** [statamic/cms#8632]
### Bug description

You expect images of all your presets to be there on upload. 

I just found out that after selecting a focal point the presets are deleted, which is desired behaviour of course, that there are no new ones generated.

-------

I have a headless setup and compute the path to the already generated images inside nuxt. This way I can use the path to my cdn straight away instead of having to talk to glide in laravel every request.

### How to reproduce

- have `generate_presets_on_upload` set to true
- upload an image
- presets are generated
- set, or change a focal point
- presets images are deleted
- no new presets images are generated

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.19.0
PHP Version: 8.1.22
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: glory.ddev.site
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.17.0 PRO

Statamic Addons
statamic/eloquent-driver: 2.6.1

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: file
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
