### ISSUE TITLE
User:Register_Form Tag does not format validation error for "email" field

### ISSUE THREAD

**Issue by Pixel-Tony** [statamic/cms#8640]
### Bug description

When trying to submit a `{{ user:register_form }}` and the submitted email address is already taken, validation error is not being translated to human-readable form, instead is returned as `validation.unique_user_value` string. 

### How to reproduce

1. Create a {{ user:register_form }} on some view.
2. Add an `<input>` field with attribute "name" set to "email".
3. If no users exist, create one from Control Panel.
4. Try to submit a form with email field filled with already registered email.

### Logs

```shell
None
```

### Environment

```yaml
Laravel Version: 10.20.0
PHP Version: 8.2.9
Composer Version: 2.5.8
Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.19.0 PRO

Statamic Addons
gioppy/statamic-metatags: 3.0.1
mitydigital/sitemapamic: 2.3.8
spatie/statamic-responsive-images: 4.1.1
stillat/antlers-components: 2.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

Issue content was previously mentioned in https://github.com/statamic/cms/issues/2977. Issue is marked as closed, but the bug is still present.
