### ISSUE TITLE
Some globals don't migrate properly after going multisite

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8642]
### Bug description

In a Peak site you get a bunch of globals by default. The issue I'm running into is that when you migrate to multisite the SEO global doesn't migrate for some reason. I never ran into this before.

### How to reproduce

- Install a clean Peak site
- Add some content to the SEO global
- Run the multisite command
- Realise that you don't want the default site to be named `default`, but `en` for example. Cancel the multisite command.
- Change `default` to `en` in your `sites.php`. 
- Run the multisite command again
- Add another language, e.g. `nl`
- Visit the CP
- Notice that the SEO global is gone
- Check the filesystem and see that the multisite command moved all global content to the correct site folders except `seo.yaml`, it's in a folder called `default`. 

Undo everything via git. Restart the process. Rename `default` to `en` in the `sites.php` and then run `php artisan cache:clear` **before** running the multisite command and everything migrates properly. 

Maybe the multisite command needs to automatically clear the cache before doing it's thing?

### Environment

```yaml
Environment
Application Name: Care About IT
Laravel Version: 10.20.0
PHP Version: 8.2.8
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: careaboutit.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Localization
Installed: en, nl
LaravelLang\Attributes\Plugin: v2.4.0
LaravelLang\HttpStatuses\Plugin: v3.4.4
LaravelLang\Lang\Plugin: 13.2.2
Protected Locales: en
Publisher Version: v14.7.0

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.19.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.3.3
studio1902/statamic-peak-seo: 6.0
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
