### ISSUE TITLE
Navigation Add "entry" Handle to Reserved Words

### ISSUE THREAD

**Issue by jonathan-bird** [statamic/cms#8657]
### Bug description

Fully explained in my discussion here, but I found that when using an "Entries" field type in Navigation (haven't tested how deep this goes so not sure if it affects collections), and use the handle of "entry", it causes relationships not to work at all on that field.

I'm using Blade, not Antlers.

Full details: in https://github.com/statamic/cms/discussions/8656#discussioncomment-6870526

### How to reproduce

* Create new app
* Setup new Navigation
* Edit Blueprint
* Add new "Entries" field type with the handle `entry`
* Loop over items using `@foreach (Statamic::tag('nav:desktop_menu')->sort('order')->fetch() as $key => $item)`
* When you go `dd($item['entry'])`, you will notice that raw is null, and `value()` is also null
* If you rename handle for field to be something other than `entry` (eg `entry_relationship`), then you will notice that raw actually returns the entry, and if you call `dd($item['entry_relationship']->value())`, you will see the full relationship as expected.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.21.0
PHP Version: 8.2.8
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: jonathanbird-statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.0.1

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.20.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
