### ISSUE TITLE
Subnavigation not visible

### ISSUE THREAD

**Issue by christophstockinger** [statamic/cms#8670]
### Bug description

I have set up a Statamic v4. I have defined several collections. The Collections are normally displayed on the left side of the menu when I click on the Collection menu item and am on the overview page.

However, if I now change the `CP_ROUTE` via the environment variable to the value `""`, the collections are no longer displayed in the sub-navigation.

### How to reproduce

- Setup a fresh statamic
- Define some collections
- Change the CP-Route with the .env-Varaible to `CP_ROUTE=""`

### Logs

```shell
No logs
```

### Environment

```yaml
Environment
Application Name: Konkav & K16
Laravel Version: 10.21.1
PHP Version: 8.2.10
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: k16-konkav-cms.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.20.0 PRO

Statamic Addons
aryehraber/statamic-uuid: 2.2.0
jonassiewertsen/statamic-documentation: 1.9.0
morethingsdigital/vercel-statamic: 0.0.9
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.5.1
studio1902/statamic-peak-seo: 5.0
studio1902/statamic-peak-tools: 3.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

I have a solution, which I contribute via a pull request.
