### ISSUE TITLE
List fieldset not editable after dragging

### ISSUE THREAD

**Issue by andywillekens** [statamic/cms#8672]
### Bug description

When using the list fieldset, you can add items, edit items and drag to re-order items.
If you re-order items, the items that changed position are no longer editable in Firefox and Safari.

https://github.com/statamic/cms/assets/5364383/c0bbfa66-efd9-4e60-bba5-6d7980ebb1af

In Chrome however, the ID's are messed up, if you would click on the 4e item it would edit the 3e item.

https://github.com/statamic/cms/assets/5364383/e9d613c0-54a9-4da8-bbd8-fe681710b673

### How to reproduce

- Add a few items in a list 
- Drag them to another position
- Try to edit the changed items

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.16.1
PHP Version: 8.2.10
Composer Version: 2.6.2
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.17.0 PRO

Statamic Addons
4rn0/statamic-v3-image-optimizer: 1.1.1
aerni/advanced-seo: 2.1.3
ptchr/statamic-basics: 1.x-dev
rias/statamic-redirect: 3.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
