### ISSUE TITLE
Static Cache - URLs ending with ? (question mark only) aren't working.

### ISSUE THREAD

**Issue by stanbridge-wcorrea** [statamic/cms#8673]
### Bug description

So, I was using the Static cache and was trying to understand why some URLs were failing to load the nocache tags. Seems like any URL ending on question mark, for example (www.example.com?) will not replace the nocache tags properly answering in a blank response for the nocache tags. 

### How to reproduce

Steps to reproduce: 

1) Have Static cache enabled. 
2) Use the nocache tag anywhere in your page. 
3) Visit that page with and without a question mark and see if it works. (www.example.com? and www.example.com) 
4) Check for the nocache tags replacement if they are there. 

PS: If you check the nocache request on the network tab on the browser, you'll see an empty response, debugging further I was able to find out that at some point the nocache replacer is ignoring the question mark to get the previous session.

### Environment

```yaml
Environment
Application Name: statamic_local
Laravel Version: 9.52.7
PHP Version: 8.2.7
Composer Version: 2.5.8
Environment: development
Debug Mode: ENABLED
URL: s11-statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.19.0 PRO

Statamic Addons
duncanmcclean/cookie-notice: 8.1.1
jacksleight/statamic-bard-mutator: 2.3.0
kind-work/two-fa: 1.5.1
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

### Additional details

I don't get an error or a 500 status, I just get an empty response for the nocache replacement response that doesn't occur on the URLs without ending on the question mark. 

It's better to compare the nocache (fetch request) of the example.com? and example.com to see what's wrong. 

(I was able to track down the code, but I don't have details since it was late.)
