### ISSUE TITLE
Set focal point preview breaks with specific filenames

### ISSUE THREAD

**Issue by GioChocolateBro** [statamic/cms#8675]
### Bug description

When I try editing an image's focal point, the preview won't load when there are special characters in the filename like `()`.

 I'm using a remote filesystem with the S3 driver on Digitalocean.

### How to reproduce

So `adf-samski-(small).jpg` wont work and when the filename is changed to  `adf-samski-small.jpg` it does.

### Environment

```yaml
Environment
Application Name: TNNA
Laravel Version: 9.47.0
PHP Version: 8.1.16
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: topnotch.ddev.site
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / daily, flare
Mail: mailgun
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.4.4 PRO

Statamic Addons
statamic/eloquent-driver: 2.6.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
