### ISSUE TITLE
Moving a set containing an open revealer doesn't update state correctly

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#8677]
### Bug description

When you move a set that contains an open revealer the open/closed state does not update correctly:

https://github.com/statamic/cms/assets/126740/c980e7b6-ff20-407a-b982-90542a8eb7b1

I think this is because the publish store's `setHiddenField` data needs to be updated when then `fieldPath` changes, which I tried to implement in the existing watcher but I couldn't figure out the right fix.

### How to reproduce

1. Create a replicator containing a set with a revealer
2. Swap the positions of a set with the revealer open and a set with the revealer closed

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.20.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
