### ISSUE TITLE
Bard entry links problem

### ISSUE THREAD

**Issue by karakhanyans** [statamic/cms#8681]
### Bug description

When we attach an entry link in **Bard** text component, it works fine. After editing the article, if you click on the link, it shows not an "entry link" but just a "URL" with an "entry:{uuid}" string, and after saving the article the URL breaks. 

![image](https://github.com/statamic/cms/assets/12999189/38fcf877-d6d6-4fef-b76b-6bf85c0d8cf6)

### How to reproduce

- Create a collection entry with the bard component, enter a text add an entry link, and save. 
- Edit the collection entry, click on the entry link inside the bard component ( see the entry link became URL string entry:{uuid}
- Save the collection 
- Check the URL on the website, it's broken.

### Environment

```yaml
Environment
Application Name: -
Laravel Version: 10.22.0
PHP Version: 8.2.4
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: -
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: daily
Mail: mailgun
Queue: redis
Session: file

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 3.8.0
PHP SDK Version: 3.21.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 0%
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 8
Antlers: regex
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.21.0 PRO

Statamic Addons
aerni/font-awesome: 2.0.0
aryehraber/statamic-logbook: 3.1.0
aryehraber/statamic-uuid: 2.2.0
joetannenbaum/antlers-stack-tags: 0.1.0
rias/statamic-redirect: 2.x-dev
statamic/seo-pro: 5.2.2
swiftmade/statamic-clear-assets: 2.0.0
xndbogdan/statamic-bard-text-color: 4.0.0
```

### Installation

Existing Laravel app

### Antlers Parser

None
