### ISSUE TITLE
Roles & Permissions form doesn't show the 'Utilities' section

### ISSUE THREAD

**Issue by K3CK** [statamic/cms#8691]
### Bug description

In several sites the 'Utilities' section was not shown in the 'Roles & Permissions' form. Thus it was e.g. not possible to allow cache clearing for restricted users. 

As a workaround it worked to add the permission string to the roles.yaml file manually. After doing that this sometimes did trigger the 'Utilities' section to being shown again (but not in all cases).

### How to reproduce

I can't tell how it can be reproduced. In some sites this occurred. In others not. New installations (with or without a starter kit) did work as expected. 

### Environment

```yaml
Site 1:
Environment
Application Name: xxx
Laravel Version: 9.52.15
PHP Version: 8.1.9
Composer Version: 2.6.2
Environment: production
Debug Mode: OFF
URL: synbrand.de
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single, flare
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Disabled
Static Caching: half
Version: 4.20.0 PRO

Statamic Addons
doublethreedigital/duplicator: 4.0.1
jonassiewertsen/statamic-livewire: 2.12.0


Site 2:
Environment
Application Name: mitmischen.de - Dein Portal zum Deutschen Bundestag
Laravel Version: 9.52.15
PHP Version: 8.2.10
Composer Version: 2.2.7
Environment: stage
Debug Mode: OFF
URL: mitmischen.stage.bundestag.de
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Disabled
Static Caching: half
Version: 4.21.0 PRO

Statamic Addons
elvenstar/statamic-meilisearch: 2.0.1
statamic/eloquent-driver: 2.6.2

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: file
Navigation Trees: file
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
