### ISSUE TITLE
Folder names cut off when you're typing quickly

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#8708]
### Bug description

Literally every time I create a new folder in Statamic, I hit enter, the realise the last few characters are missing from the folder's name.

https://github.com/statamic/cms/assets/19637309/bc55e6d7-1cbc-4af0-b8d9-19572a38e35d

It only seems to happen when I'm typing relatively fast. When I type slowly, and hit enter, it saves the full folder name.

### How to reproduce

1. Go to 'Assets' in the Control Panel
2. Create a new folder, type quickly
3. See that the last few characters are missing from the folder name.
4. Create a new folder, type slowly
5. See that the folder name was saved correctly.

### Environment

```yaml
Environment
Application Name: Biblical Soul Care
Laravel Version: 10.21.0
PHP Version: 8.2.10
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: biblicalsoulcare.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.20.0 PRO

Statamic Addons
doublethreedigital/runway: 5.2.0
duncanmcclean/static-cache-manager: 3.1.1
stillat/relationships: 2.1.1
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.5.1
studio1902/statamic-peak-seo: 6.0
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
