### ISSUE TITLE
Edited CP nav collapses when visiting nested elements

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/cms#8717]
### Bug description

Nesting a CP nav item under another one causes the parent to collapse when visiting the child nav item.

### How to reproduce

1. Take any two CP nav items and nest one under the other
2. Save the CP nav
3. Click on the parent nav item - the child nav item is revealed
4. Click on the child nav item - the parent collapses hiding child nav and causing confusion as to what page you are on.

### Logs

```shell
N/A
```

### Environment

```yaml
Environment
Application Name: Dev Site
Laravel Version: 9.52.15
PHP Version: 8.0.29
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: devsite.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.21.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 2.12.0
mitydigital/statamic-google-fonts: 1.0.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
