### ISSUE TITLE
Renaming assets doesn't update global fields

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8733]
### Bug description

When you rename in assets, Statamic recursively goes to all entries to update any potential references in asset fields. However it doesn't seem to do this for globals. 

### How to reproduce

Add an asset field to a global
Set an asset to your field
Rename that asset
Global asset field is now empty

### Environment

```yaml
Environment
Application Name: Stichting Agricola Laurentius
Laravel Version: 10.22.0
PHP Version: 8.2.8
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: agricolalaurentius.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Localization
Installed: cs, da, de, en, nl, nn
LaravelLang\Attributes\Plugin: v2.4.0
LaravelLang\HttpStatuses\Plugin: v3.4.4
LaravelLang\Lang\Plugin: 12.24.2
Protected Locales: en
Publisher Version: v14.7.0

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.21.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.5.1
studio1902/statamic-peak-seo: 7.0.1
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

**Comment by robdekort** [comment]
Yep

**Comment by jasonvarga** [comment]
Does the yaml in the global change? Or is it still a-peak.jpg?

**Comment by robdekort** [comment]
> Can you share the global blueprint? Anything field combination I try works so I think it must be something to do with the blueprint.

I just tested it with a basic blueprint. This one:
```yaml
tabs:
  general:
    display: General
    sections:
      -
        display: 'System pages'
        instructions: 'Configure system pages.'
        fields:
          -
            handle: assets_field
            field:
              mode: list
              container: images
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Assets Field'
              icon: assets
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
```
