### ISSUE TITLE
Empty form widget styling is not consistent with other widgets

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8734]
### Bug description

In it's empty state, the widget for form submissions is not consistent with the ones for empty collections. I feel the text string could use a bit of love.

<img width="485" alt="Screenshot 2023-09-19 at 15 54 19" src="https://github.com/statamic/cms/assets/69107412/cd4e7edd-8bad-4fc8-befd-697746111ef3">

### How to reproduce

Add a collection and form widget and make sure neither of them have entries. View the dashboard.

### Environment

```yaml
Environment
Application Name: Stichting Agricola Laurentius
Laravel Version: 10.23.1
PHP Version: 8.2.8
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: agricolalaurentius.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Localization
Installed: en, nl
LaravelLang\Attributes\Plugin: v2.4.1
LaravelLang\HttpStatuses\Plugin: v3.4.5
LaravelLang\Lang\Plugin: 12.24.2
Protected Locales: en
Publisher Version: v14.7.0

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.22.0 PRO

Statamic Addons
edalzell/forma: 2.1
ryanmitchell/statamic-translation-manager: dev-main
statamic-rad-pack/mailchimp: 4.1.1
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.5.2
studio1902/statamic-peak-seo: 7.0.2
studio1902/statamic-peak-tools: 3.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
