### ISSUE TITLE
Preview Targets format fields don't have same meta variables available as Route field

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/cms#8740]
### Bug description

When entering a preview target, I was expecting to be able to use `{mount}`, `{year}`, `{month}`, etc. in the format field.  It appears these are not available or are not functioning.

### How to reproduce

1. Create a new collection and enable publish dates on it
2. In the collection settings, add a new Preview Target with the following valid format: `/{year}`
3. Save the collection
4. Add a new item to the collection and attempt to preview it using the new target
5. If enable a breakpoint on [this line](https://github.com/statamic/cms/blob/master/resources/js/components/live-preview/UpdatesIframe.js#L37 ) in the JavaScript debugger you can see the url is: https://example.com/ instead of https://example.com/2023

### Environment

```yaml
Environment
Application Name: Dev Site
Laravel Version: 9.52.15
PHP Version: 8.0.29
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: devsite.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.22.0 PRO

Statamic Addons
heidkaemper/statamic-toolbar: 1.1.0
jonassiewertsen/statamic-livewire: 2.12.0
mitydigital/statamic-google-fonts: 1.0.3
webographen/statamic-widget-cache-controller: 1.0.2
webographen/statamic-widget-continue-editing: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
