### ISSUE TITLE
stache:warm performance issues

### ISSUE THREAD

**Issue by mauricewijnia** [statamic/cms#8744]
### Bug description

Warming the stache takes between 5-10 minutes in one of our projects.

The project has 5 sites with a total of 7000 entries. So about 1400 per language.

There seem to be two main issues that cause this in our case:
- The Associations index for the first taxonomy to get indexed takes about 60 seconds
- Our biggest collection takes almost all of the remaining time, so about 4 to 9 minutes depending on the machine
  - This collection has 700 entries per site
  - The collection is orderable and has a tree structure about 4 or 5 levels deep, disabling orderable reduces the index time to about 30 seconds.
  
7000 entries ofcourse is a lot of content, but to me it doesn't feel like it should cause performance issues of this level.

Are there any configuration options that I may have missed that could speed this up?
  
  

### How to reproduce

- Create a new statamic site with 5 sites
- Add a orderable collection with about 700 entries in each site
- Add a taxonomy to the collection
- Give each entry one or more terms from the taxonomy
- Create a tree structure going up to 5 levels deep in the collection
- Run `php please stache:refresh`

### Environment

```yaml
Environment
Laravel Version: 10.23.1
PHP Version: 8.2.10
Composer Version: 2.6.3
Environment: production
Debug Mode: OFF
Maintenance Mode: OFF

Cache
Config: CACHED
Events: CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: daily
Mail: smtp
Queue: redis
Session: file

Sentry
Enabled: YES
Environment: production
Laravel SDK Version: 3.8.0
PHP SDK Version: 3.21.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 10%
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.22.0 PRO

Statamic Addons
aryehraber/statamic-impersonator: 2.6.0
doublethreedigital/runway: 5.2.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
