### ISSUE TITLE
Stacked option on grid field causes fullscreen button to be hidden

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/cms#8748]
### Bug description

![image](https://github.com/statamic/cms/assets/3847288/1bf674c7-397f-43f5-b3b2-0d3b6d084d03)

The fullscreen button is hidden behind the grid items.

### How to reproduce

1. Create a replicator
2. Add a grid field to the default set
3. Add a text field to the grid field
4. Change the grid mode to "stacked"
5. Save
6. Create an entry and add a set
7. Add a row in the grid field
8. The grid fields will overlap the fullscreen button

### Environment

```yaml
Environment
Application Name: Dev Site
Laravel Version: 10.24.0
PHP Version: 8.1.21
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: devsite.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.22.0 PRO

Statamic Addons
heidkaemper/statamic-toolbar: 1.1.0
jonassiewertsen/statamic-livewire: 2.12.0
mitydigital/statamic-google-fonts: 1.0.3
rias/statamic-address-field: 1.1.0
stillat/antlers-components: 2.1.0
webographen/statamic-widget-cache-controller: 1.0.2
webographen/statamic-widget-continue-editing: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

In general I think the spacing above the grid field when "stacked" mode is enabled needs fixing.  Even a normal, non-nested grid field is butting up right next to the fullscreen button:

![image](https://github.com/statamic/cms/assets/3847288/9713d5aa-20cd-46bf-8541-598d39d6ca51)
