### ISSUE TITLE
Create fieldset/collection/taxonomy/etc handle generation does not remove hyphens surrounded by spaces

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/cms#8749]
### Bug description

When creating a fieldset/collection/taxonomy it would be nice to be able to use hyphens in the title and not get this weird behavior:

![image](https://github.com/statamic/cms/assets/3847288/c2314d97-838d-4f6b-93f1-0a4fa98c8604)

### How to reproduce

1. Create a fieldset/collection/taxonomy
2. Type a title that contains a hyphen in it like "Block - CTA"
3. The handle defaults to a weird syntax "block_-_cta"

### Environment

```yaml
Environment
Application Name: Dev Site
Laravel Version: 10.24.0
PHP Version: 8.1.21
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: devsite.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.22.0 PRO

Statamic Addons
heidkaemper/statamic-toolbar: 1.1.0
jonassiewertsen/statamic-livewire: 2.12.0
mitydigital/statamic-google-fonts: 1.0.3
rias/statamic-address-field: 1.1.0
stillat/antlers-components: 2.1.0
webographen/statamic-widget-cache-controller: 1.0.2
webographen/statamic-widget-continue-editing: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
