### ISSUE TITLE
Listable columns not showing up in stack picker

### ISSUE THREAD

**Issue by FrankPeters** [statamic/cms#8758]
### Bug description

I've made several columns listable but they are not showing up in the stack picker for the given taxonomy.

### How to reproduce

1. Edit blueprint/fieldset
2. Make column listable.
3. Go to a taxonomy stack picker
4. Observe that column is not showing up

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.15
PHP Version: 8.0.13
Composer Version: 2.6.2
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.21.0 PRO

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.1.3
private/package: dev-develop
statamic/eloquent-driver: 2.7.0
statamic/seo-pro: 5.2.2
xndbogdan/statamic-bard-text-color: 4.0.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Taxonomies: eloquent
Terms: eloquent
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
