### ISSUE TITLE
Collection search broken after 4.23.0 update

### ISSUE THREAD

**Issue by Utibu** [statamic/cms#8759]
### Bug description

We have noticed on the site we're currently developing that after the update to 4.23.0, the search for entries in our collections has stopped working an given us the following error:

> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'title) LIKE ? and `site` = ?' at line 1 (Connection: mysql, SQL: select count(*) as aggregate from `entries` where `collection` = page and LOWER(data->title) LIKE %test% and `site` = sv)

It seems to possibly be an unfortunate side effect from the newly added PR [8243](https://github.com/statamic/cms/pull/8243). 

After removing row 106 in the class EloquentQueryBuilder it seems to work. The row looks like the following:
`$this->builder->whereRaw('LOWER('.$this->column($column).') LIKE ?', strtolower($value), $boolean);`

Our best guess is that something in this line of code breaks the following Eloquent query builder and therefore it does not add quotes around the values.

### How to reproduce

Upgrade to 4.23.0 and search for entries inside a collection in the admin area. (Collections -> Pages -> Search bar)

Comment out the row described above and search again. Now it should not give the error, but search won't work because we removed the code adding the values.

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 10.24.0
PHP Version: 8.2.9
Composer Version: -
Environment: local
Debug Mode: ENABLED
URL: laravel.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single, bugsnag
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.23.0 PRO

Statamic Addons
statamic/eloquent-driver: 2.7.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
```

### Installation

Existing Laravel app

### Antlers Parser

None
