### ISSUE TITLE
CP Nav: Collections subnav not showing when editing entry

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#8760]
### Bug description

I've updated to the latest Statamic version and seeing an issue where the 'Collections' subnav isn't showing even though I'm currently viewing an entry.

<img width="1149" alt="image" src="https://github.com/statamic/cms/assets/19637309/e2ef12f5-7be0-462c-854d-8e65cd3a82fa">

### How to reproduce

1. Create a Statamic site
2. Go to edit an entry
3. See that the 'Collections' nav isn't showing as active or showing its children. 

### Environment

```yaml
Environment
Application Name: Biblical Soul Care
Laravel Version: 10.24.0
PHP Version: 8.2.10
Composer Version: 2.6.3
Environment: local
Debug Mode: ENABLED
URL: biblicalsoulcare.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.23.1 PRO

Statamic Addons
doublethreedigital/runway: 5.3.0
duncanmcclean/static-cache-manager: 3.1.2
stillat/relationships: 2.1.1
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.6
studio1902/statamic-peak-seo: 7.0.3
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
