### ISSUE TITLE
Impersonate action showing for current user

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#8761]
### Bug description

The current user check on the "Impersonate" action doesn't seem to work. I'm seeing the option when viewing actions for the currently logged in user. 

It doesn't look like this check is working:

https://github.com/statamic/cms/blob/87070a3186103e5bf4f6e6a596f194b70b2cde4e/src/Actions/Impersonate.php#L26

It may have something to do with the fact I'm storing users in the database. However, `$item` and `User::current()` seem to be returning the same `Statamic\Auth\Eloquent\User` instance so it must be that they don't exactly match.

### How to reproduce

1. New statamic site
2. Setup [database users](https://statamic.dev/tips/storing-users-in-a-database#content)
3. Go to 'Users' and try to impersonate the current user

### Environment

```yaml
Environment
Application Name: Biblical Soul Care
Laravel Version: 10.24.0
PHP Version: 8.2.10
Composer Version: 2.6.3
Environment: local
Debug Mode: ENABLED
URL: biblicalsoulcare.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.23.1 PRO

Statamic Addons
doublethreedigital/runway: 5.3.0
duncanmcclean/static-cache-manager: 3.1.2
stillat/relationships: 2.1.1
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.6
studio1902/statamic-peak-seo: 7.0.3
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
