### ISSUE TITLE
Link fieldtype inside bard does not display entered value correctly after saving.

### ISSUE THREAD

**Issue by bsandoz** [statamic/cms#8764]
### Bug description

When entering a URL or selecting an entry for a link field inside of a bard element, the entered value disappears in the editor after hitting save or collapsing the field, even though it is correctly saved in the .md file. After reloading, the value appears again.

### How to reproduce

1. Create a fieldset containing a bard field.
2. Inside of the bard, create a new set with a link field.
3. Add the bard fieldset to a page blueprint.
4. Go to a page, add a link inside the created bard field.
5. Enter any URL or select an entry, hit save or collapse and expand the link field.
6. Entered value is gone, link field shows "None" again.
7. Reload the page, value is back again.

### Environment

```yaml
Environment
Application Name: Startup B7K
Laravel Version: 10.15.0
PHP Version: 8.1.20
Composer Version: 2.5.5
Environment: production
Debug Mode: ENABLED
URL: startup.b7k.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: sendmail
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.13.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
