### ISSUE TITLE
Link fieldtype in a Grid seems to have issues

### ISSUE THREAD

**Issue by eminos** [statamic/cms#8765]
### Bug description

When adding a new row to a sibling Grid, the Link field's value is reset.

### How to reproduce

Setup this blueprint:

- Grid 1
--  Link
--  Grid 2

Write anything in the Link field.

When adding a new row to Grid 2, Link is reset.

### Environment

```yaml
This happens on demo.statamic.com as well.

Laravel Version: 10.24.0
PHP Version: 8.2.5

Statamic
Addons: 8
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.23.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
