### ISSUE TITLE
Apply ALL & Save (Statamic UI)

### ISSUE THREAD

**Issue by minemindmedia** [statamic/cms#8770]
### Bug description

While creating a page builder in the UI using many levels of Bard, I realized I must apply changes to each open level before I can eventually click save, in order to save the blueprint or fieldset. As a new user to Statamic, I suppose this would apply to most content in the UI.

### How to reproduce

Start building out a blueprint.
Add a Bard field, then add as many Bard fields within one another as you'd like.
You will eventually be many levels deep and will be required to backtrack out of each level clicking the apply button until you're back to the parent level and you can click save.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.24.0
PHP Version: 8.2.10
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: minemindmedia-app.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.23.2 PRO

Statamic Addons
krakero/tailwind-fieldtype: 1.0.2
ndx/statamic-bard-color-picker: 1.2.0
stillat/antlers-components: 2.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

Would be really convenient to have a way to apply all the of levels without backtracking.
Perhaps an additional button that says, "Apply All & Save" that will effectively apply all open panels and save the blueprint, fieldset, etc.
Would also be nice to have the option to "Apply All & Save" with the added option of staying on the current open panel or returning back to the blueprint, fieldset, etc.
