### ISSUE TITLE
Undefined constant "Illuminate\Console\Concerns\STDIN"

### ISSUE THREAD

**Issue by sthomas-cg** [statamic/cms#8771]
### Bug description

Clearing the application or image caches through the control panel causes an `Undefined constant "Illuminate\Console\Concerns\STDIN"` error. Clearing the content stache and static page cache work as expected though.

### How to reproduce

Create a new Statamic project and sign-in. Navigate to Utitlities > Cache and click the Clear button for Application Cache or Image Cache.

### Logs

```shell
local.ERROR: Undefined constant "Illuminate\Console\Concerns\STDIN" {"userId":"f39916ea-c248-42c9-9823-b96e4920f25d","exception":"[object] (Error(code: 0): Undefined constant \"Illuminate\\Console\\Concerns\\STDIN\" at /Users/-/Sites/test/vendor/laravel/framework/src/Illuminate/Console/Concerns/ConfiguresPrompts.php:27)
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.25.0
PHP Version: 8.2.10
Composer Version: 2.6.3
Environment: local
Debug Mode: ENABLED
URL: test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.23.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
