### ISSUE TITLE
Prebuilt frontend files prevent deploying statamic with url-prefix

### ISSUE THREAD

**Issue by singer-d** [statamic/cms#8773]
### Bug description

We are deploying our statamic instance with a path like `example.com/statamic-instance`.
Since upgrading from version 3 to version 4 the fonts can no longer be loaded.
Inside the generated tailwind.css the fonts are referenced with `url(/vendor/statamic/cp/build/assets/<fontfile>)`. This leads to the frontend trying to load the font via `https://example.com/vendor/statamic/cp/build/assets/<fontfile>` instead of `https://example.com/statamic-instance/vendor/statamic/cp/build/assets/<fontfile>`.
This could be solved by providing `base: './'` instead of `base: '/vendor/statamic/cp/build'` in the vite.config.js and rebuilding the dist.
Our current workaround is to have `cd vendor/statamic/cms && npm ci && rm -rf dist && npm run build -- --base=./` just before our `php artisan statamic:install`.

### How to reproduce

Deploy any statamic application to a url that has a url-prefix (e.g. https://example.com/my-app)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.15
PHP Version: 8.1.23
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: localhost:8000/abc
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Cache: statamic
Database: pgsql
Logs: stack / daily, stdout
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.23.2 PRO
```

### Installation

Existing Laravel app

### Antlers Parser

regex (default)
