### ISSUE TITLE
php please fails when resolving Command type

### ISSUE THREAD

**Issue by SylvesterDamgaard** [statamic/cms#8783]
### Bug description

By installing a package which publishes a Command using a Command class, the `php please` call fails.
This happens in packages using the InstallCommand in https://github.com/spatie/laravel-package-tools

### How to reproduce

Install spatie/laravel-prometheus as an example.

`composer require spatie/laravel-prometheus`

### Logs

```shell
[2023-09-29 09:05:16] local.ERROR: Illegal offset type in isset or empty {"exception":"[object] (TypeError(code: 0): Illegal offset type in isset or empty at /statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php:1327)
[stacktrace]
#0 /statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(920): Illuminate\\Container\\Container->getAlias(Object(Spatie\\LaravelPackageTools\\Commands\\InstallCommand))
#1 /statamic/vendor/statamic/cms/src/Console/Please/Application.php(26): Illuminate\\Foundation\\Application->make(Object(Spatie\\LaravelPackageTools\\Commands\\InstallCommand))
#2 /statamic/vendor/laravel/framework/src/Illuminate/Console/Application.php(263): Statamic\\Console\\Please\\Application->resolve(Object(Spatie\\LaravelPackageTools\\Commands\\InstallCommand))
#3 /statamic/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(404): Illuminate\\Console\\Application->resolveCommands(Array)
#4 /statamic/vendor/laravel/framework/src/Illuminate/Console/Application.php(130): Illuminate\\Support\\ServiceProvider->Illuminate\\Support\\{closure}(Object(Statamic\\Console\\Please\\Application))
#5 /statamic/vendor/laravel/framework/src/Illuminate/Console/Application.php(77): Illuminate\\Console\\Application->bootstrap()
#6 /statamic/vendor/statamic/cms/src/Console/Please/Kernel.php(19): Illuminate\\Console\\Application->__construct(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Events\\Dispatcher), '4.23.2')
#7 /statamic/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Statamic\\Console\\Please\\Kernel->getArtisan()
#8 /statamic/please(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"}
```

### Environment

```yaml
Well. It fails. ;) 

Environment
Application Name: Statamic
Laravel Version: 10.25.2
PHP Version: 8.2.11
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: statamic-debug.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.23.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
