### ISSUE TITLE
Visual bug when editing a nested list with entries links

### ISSUE THREAD

**Issue by helacyan** [statamic/cms#8793]
### Bug description

I have created a Header Nav in Globals Settings, where I want to process nested links as well. When I created one nav item and started creating nested ones, I noticed that after creating subsequent nested items, the labels of the previous ones turn into id, but after reloading they become labels again. It doesn't interfere with workability, but it can be visually confusing to some people.

![image](https://github.com/statamic/cms/assets/79014754/25abbae4-8e92-430c-a558-49c50c608cc9)

### How to reproduce

settings.yaml blueprint structure:
```
tabs:
  header:
    display: Header
    sections:
      -
        fields:
          -
            handle: header_nav
            field:
              fields:
                -
                  import: part_button
                -
                  handle: items
                  field:
                    fields:
                      -
                        import: part_button
                    mode: stacked
                    reorderable: true
                    fullscreen: true
                    type: grid
                    display: Items
                    icon: grid
                    localizable: false
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    hide_display: false
                    if:
                      url: '=== null'
                    replicator_preview: true
              mode: stacked
              reorderable: true
              fullscreen: true
              type: grid
              display: Nav
              icon: grid
              localizable: true
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              validate:
                - required
              replicator_preview: true
```
part_button.yaml Fieldset Structure
```
  title: "Part: Button"
  fields:
    -
      handle: url
      field:
        collections:
          - pages
        display: Url
        type: link
        icon: link
        listable: hidden
        instructions_position: above
        visibility: visible
        localizable: true
        hide_display: false
    -
      handle: label
      field:
        input_type: text
        antlers: false
        type: text
        display: Label
        icon: text
        localizable: true
        listable: hidden
        instructions_position: above
        visibility: visible
        hide_display: false
```

### Environment

```yaml
Environment
Application Name: My Localhost
Laravel Version: 10.21.0
PHP Version: 8.2.4
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: mylocalhost
Maintenance Mode: OFF
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
