### ISSUE TITLE
Deleting a root page causes whole page to throw 500 error

### ISSUE THREAD

**Issue by tobimori** [statamic/cms#8794]
### Bug description

When removing the home page in a tree, and the following entry in the tree has children, all subsequent requests to the site serve a 500 error because statamic throws an error when the home page has children.

It should *not* be possible to delete a root page from the panel.

### How to reproduce

Create a structure like this:

- Home
- Random page
  - Random page
  - Random page
- [..]

Now switch from the tree mode to the list mode & delete the home page.

The page will be deleted, but the request will be answered with a 500:
![CleanShot 2023-10-03 at 15 29 24@2x](https://github.com/statamic/cms/assets/29142128/e25140bb-6f8a-4d8a-b5e8-bf1dad1c6941)

And all following requests that somehow have to do parsing of the trees will also be answered with the same 500 error.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.25.2
PHP Version: 8.2.10
Composer Version: 2.6.3
Environment: local
Debug Mode: ENABLED
URL: enfore.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 11
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.24.0 PRO

Statamic Addons
aerni/advanced-seo: 2.2.0
doublethreedigital/duplicator: 4.0.1
eminos/statamic-group: 1.0.2
eminos/statamic-set-header-toggle: 1.0.0
fdmind/ignore-query-strings: 1.0.2
marcorieser/tailwind-merge-statamic: 0.2.0
ncla/statamic-focal-point-fieldtype: 3.0.0
rias/statamic-color-swatches: 2.2.0
rias/statamic-redirect: 3.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
