### ISSUE TITLE
data:text/javascript;base64 in start up and CSP headers

### ISSUE THREAD

**Issue by vicolsson** [statamic/cms#8795]
### Bug description

We've recently upgraded our Statamic sites (after way to long) and now it clashes with out CSP headers. It's this line https://github.com/statamic/cms/blob/master/resources/views/partials/scripts.blade.php#L24

Due to strict security regulations on our sites we must have CSP headers that regulate from where scripts can be loaded. Loading scripts as "data:..." is sadly not allowed. So that's currently blocking us from publishing the updated sites.

Do you think you'd be able to build some workaround? We've already opened up 'unsafe-inline' for Statamic if that helps.

### How to reproduce

Deploy Statamic to a host with:
`Content-Security-Policy: script-src 'self' 'unsafe-inline'`
Open up /cp and you get an error in the console and the CP doesn't work.

### Environment

```yaml
Environment
Application Name: ***
Laravel Version: 10.24.0
PHP Version: 8.2.10
Composer Version: 2.6.3
Environment: local
Debug Mode: ENABLED
URL: ***
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.23.1 PRO

Statamic Addons
statamic/ssg: 2.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
