### ISSUE TITLE
Default values are not saved for the data request

### ISSUE THREAD

**Issue by helacyan** [statamic/cms#8804]
### Bug description

For example, when creating a field and setting the default value, GraphQL query returns null, while in the admin panel itself the value is set correctly and you need to check the documents and click Save manually, this can be quite time-consuming. Is it possible to save this value without saving it manually in the documents after field creating?

### How to reproduce

1. Create a string type field with default value
2. Try to get the value in GraphQL

### Environment

```yaml
Environment
Application Name: My Localhost
Laravel Version: 10.21.0
PHP Version: 8.2.4
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: mylocalhost
Maintenance Mode: OFF
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
