### ISSUE TITLE
Replicator set using wrong related field 

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/cms#8820]
### Bug description

I have a site running 4.18.0

It has a replicator field with a `Slider` set. Inside the set I have a `product_link` field (looking at a `products` collection) and a `product_asset` field that is an Asset field.

In the template I've got

```
{{ if product_link:url }}
                        <a href="{{ product_link:url }}" class="mt-2 space-x-2 flex items-center transition duration-300 hover:text-blue  text-light-grey ">
    
                            <span>{{ trans:site.readmore }}</span>
                            <span class="material-icons-sharp bg-grey text-white rounded-full icon">
                                chevron_right
                            </span>
                        </a>
                        {{ /if }}
                        {{ if product_asset:url }}
                        <a href="{{ product_asset:url }}" class="mt-2  space-x-2 flex items-center transition duration-300 hover:text-blue text-light-grey">
                            <span>{{ trans:site.readmore }}</span>
                            <span class="material-icons-sharp bg-grey text-white rounded-full icon">
                                chevron_right
                            </span>
                        </a>
                            
                    
                        {{ /if }}
``` 

this works great in 4.18.0

however after updating to the 4.24.0, `product_asset:url` displays `product_link:url` from another `Slider` set.

Markdown as follows:

```
slider_holder:
  -
    id: 5LRZ5DYy
    slider_image: 'site/White-J,-transparent-background.png'
    slider_title: 'Manufacturing Plastic Solutions'
    slider_content: 'For over 50 years, we’ve been moulding high quality 100% recyclable products for industry.'
    type: slider
    enabled: true
  -
    id: jt2QDObD
    slider_image: carousel/j-logo-santa-hat-carousel_01.png
    slider_title: 'Christmas Closure'
    slider_content: 'warehouse will be closed from 22 December 2022 and offices from 23 December 2022. We will all be back on 03 January 2023 and our customer services team will be available weekdays from 0800 until 1630.'
    type: slider
    enabled: false
  -
    id: YJz27A3N
    slider_image: sfs-cat-mockup-2.2.png
    slider_title: 'Spill, Fire and Storage Catalogue'
    slider_content: 'Everything you need to know about our Spill containment, Fire safety and Storage products.'
    type: slider
    enabled: true
  -
    id: qt8mkuZy
    slider_image: hc1-bk-ye_002.png
    slider_title: 'IBC Hardcover'
    slider_content: 'Our nestable IBC spill pallet complete with a weathertight hardcover.'
    type: slider
    enabled: true
  -
    id: bB1J2dSm
    slider_image: firekart-png.png
    slider_title: 'Mobile fire extinguisher trolley'
    slider_content: 'A mobile fire stand designed to hold up to two 12kg fire extinguishers.'
    type: slider
    enabled: true
  -
    id: KIJNe9Ze
    slider_image: sj-110-006_05.jpg.png
    slider_title: 'Drum Spill pallet'
    slider_content: 'Ideal when working with drums containing liquids and hazardous chemicals.'
    type: slider
    enabled: true
    product_link: f50b85e2-4410-4db3-9ca6-a53968103fad
```

Appreciate it's a funky way to setup a carousel field 🥴

### How to reproduce

Create a fieldset using

```
title: 'Carousel Slider'
fields:
  -
    handle: slider_holder
    field:
      collapse: false
      sets:
        main:
          display: Main
          instructions: null
          icon: null
          sets:
            slider:
              display: Slider
              instructions: null
              icon: null
              fields:
                -
                  handle: slider_image
                  field:
                    mode: grid
                    container: assets
                    folder: /
                    restrict: false
                    allow_uploads: true
                    max_files: 1
                    display: 'Slider Image'
                    type: assets
                    icon: assets
                    listable: hidden
                    localizable: false
                -
                  handle: slider_title
                  field:
                    input_type: text
                    antlers: false
                    display: 'Slider Title'
                    type: text
                    icon: text
                    width: 33
                    listable: hidden
                    localizable: false
                -
                  handle: slider_content
                  field:
                    antlers: false
                    display: 'Slider Content'
                    type: textarea
                    icon: textarea
                    width: 66
                    listable: hidden
                    localizable: false
                -
                  handle: product_link
                  field:
                    max_items: 1
                    mode: default
                    collections:
                      - products
                    display: 'Product Link'
                    type: entries
                    icon: entries
                    listable: hidden
                    localizable: false
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    create: true
                    hide_display: false
                -
                  handle: product_asset
                  field:
                    max_files: 1
                    mode: list
                    container: assets
                    restrict: false
                    allow_uploads: true
                    show_filename: true
                    show_set_alt: true
                    type: assets
                    display: 'Product Asset'
                    icon: assets
                    localizable: false
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    hide_display: false
                    replicator_preview: true
      display: 'Slider Holder'
      type: replicator
      icon: replicator
      listable: hidden
      localizable: true
      instructions_position: above
      visibility: visible
      previews: true
      fullscreen: true
      hide_display: false
      replicator_preview: true

```

use the conditionals for the template.

### Environment

```yaml
Environment
Application Name: Site
Laravel Version: 9.52.15
PHP Version: 8.2.11
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: site.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Statamic
Addons: 3
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.18.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
cnj/seotamic: 4.0.0
rias/statamic-data-import: 1.3.0
```
```


### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

### Additional details

_No response_
