### ISSUE TITLE
Form listing from form field shows unpublished state circle

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8824]
### Bug description

When you use a form field to select a form, the forms in the stack get a grey dot suggesting they aren't published. However forms don't have a publish/unpublished state.

It should probably not be there at all for clarity.

<img width="1405" alt="Screenshot 2023-10-10 at 19 57 20" src="https://github.com/statamic/cms/assets/69107412/08ada916-e898-4c22-b115-e490c4e8f7ab">

### How to reproduce

1. Add a form
2. Add a form field to some fieldset
3. Click the form field
4. Notice the grey dot in front of each form you might have.

### Environment

```yaml
Environment
Application Name: Statamic Peak Development
Laravel Version: 10.26.2
PHP Version: 8.2.10
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.24.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.6
studio1902/statamic-peak-seo: 7.0.3
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
