### ISSUE TITLE
Renaming an asset folder with underscores to the same name but with dashes instead deletes all content inside

### ISSUE THREAD

**Issue by schwemmer** [statamic/cms#8825]
### Bug description

When a user attempts to rename an asset folder, changing underscores (_) to dashes (-) in the folder name, all content within the folder is unexpectedly deleted. The expected behavior is that the folder should be renamed while preserving all its content.

### How to reproduce

- Go to Assets
- Create a folder with at least one underscore in its name, e.g. "test_folder"
- Upload a few images into this folder
- Rename the folder by replacing underscores with dashes (e.g., "test-folder").
- Open the renamed folder
- All content will be gone

### Environment

```yaml
Environment
Application Name: Example Application
Laravel Version: 9.52.15
PHP Version: 8.2.7
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: localhost:8003
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.23.2 PRO

Statamic Addons
aryehraber/statamic-impersonator: 2.6.0
jacksleight/statamic-bard-texstyle: 3.1.3
textandbytes/cp-assets: dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

Perhaps these closed issues are related: #5064 and #5405
