### ISSUE TITLE
Multiple ViewModels raise an error

### ISSUE THREAD

**Issue by FlxRobole** [statamic/cms#8827]
### Bug description

My intention was to inject different sorts of behaviors into my templates. "View Models" (notice the plural "s") seemed to offer a brilliant approach to implement that. However, applying more than one view model into my collection raises an error. Turns out that multiple viewModels are not supported on a collection, only a single viewModel. 

If this constraint is intentional, please add it to the docs. If not, please add support for passing an array of viewModels in `Cascade.php` referenced in the logs.

### How to reproduce

Pass an array of view models into  `content/collections/pages.yaml`, e.g.:
```
inject:
  view_model: 
    - App\ViewModels\HeroViewModel
    - App\ViewModels\ProductsFilterFormViewModel
 ```

### Logs

```shell
local.ERROR: Class name must be a valid object or a string {"exception":"[object] (Error(code: 0): Class name must be a valid object or a string at /var/www/html/vendor/statamic/cms/src/View/Cascade.php:219)
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.21.0
PHP Version: 8.2.11
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: localhost:8080/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: array
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.19.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
