### ISSUE TITLE
Replicator preview not showing text input field after save

### ISSUE THREAD

**Issue by NicoRox** [statamic/cms#8839]
### Bug description

I have the following fieldset in my replicator

Text component
- id_value = text input
- bard_field = bard

when I add a new component in the replicator and fill in the `id_value` and `bard_field`, then collapse the fieldset. It shows the `id_value` / `bard_field` in the handle of the fieldset as expected (see screenshots)

<img width="795" alt="image" src="https://github.com/statamic/cms/assets/90255162/8020d363-7d85-4113-8305-8af94cd4c9d8">

<img width="784" alt="image" src="https://github.com/statamic/cms/assets/90255162/fa844f98-18cd-4f2d-863c-70ed83e1f0de">

After I save the page (and refresh) the `id_value` is not shown in the fieldset handle anymore (see screenshot all fieldsets have a filled `id_value` field and either a bard field or assets field)

<img width="850" alt="image" src="https://github.com/statamic/cms/assets/90255162/d5d69f44-49fd-4a96-b5a2-adeb63eed210">

I would expect to see the `id_value` field in the handle as first item

### How to reproduce

- setup clean statamic install
- create a replicator with a set containing a text input field as first field
- add the replicator to page blueprint
- edit home or create new page and add a replicator set to the page and fill in the first text field
- save the page and refresh
- now the set handle does not show the value

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.28.0
PHP Version: 8.2.10
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: statamic-test-project.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: array
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.27.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

The bug got introduced in statamic v4.26
The bug still persists in v4.27

I think it might be related to this pr #8716
