### ISSUE TITLE
Enforcing lowercase asset filenames omits the file extension

### ISSUE THREAD

**Issue by joshuablum** [statamic/cms#8841]
### Bug description

https://github.com/statamic/cms/pull/6031 introduced the option to lowercase the filename of assets (turned on by default).

A support request came in saying that the `statamic.assets.lowercase` config setting doesn't actually lowercase the file extension but just the filename and I was able to reproduce this behavior.

This can potentially lead to issues and file conflicts on certain OS and filesystems depending on whether they are case-sensitive or insensitive.

### How to reproduce

Upload an asset via the Control Panel with the `statamic.assets.lowercase` config option set to `true`.

Expected behavior: `TEST.JPG` turns into `test.jpg`
Current behavior: `TEST.JPG` turns into `test.JPG`

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.28.0
PHP Version: 8.2.11
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: filename-fix.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.x-dev Pro
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
