### ISSUE TITLE
[4.27 to 4.28] Cannot get my site to update locally 33mn after the release

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#8847]
### Bug description

Stuck on 4.27

### How to reproduce

composer update statamic/cms -W doesn't download v4.28

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.28.0
PHP Version: 8.2.0
Composer Version: 2.5.1
Environment: local
Debug Mode: OFF
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.27.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
