### ISSUE TITLE
Cache Clear is error

### ISSUE THREAD

**Issue by ottz0** [statamic/cms#8850]
### Bug description

When I run php artisan cache:clear I now get an error file_put_contents(FILE_LOCATION): Failed to open stream: No such file or directory.

I then have to run 

```
php artisan route:clear
php artisan config:clear
php artisan cache:clear
```

everytime as well as sail down and sail up to clear it which is annoying. 

### How to reproduce

Run php artisan cache:clear

### Environment

```yaml
Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.19.0 PRO
Environment
Laravel Version: 9.52.14
PHP Version: 8.2.2
Composer Version: 2.5.2
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
