### ISSUE TITLE
Poor Memory Management with Search Indexes (Searchables)

### ISSUE THREAD

**Issue by electroflame** [statamic/cms#8854]
### Bug description

When you have a large site with many entries (50k+), updating search indexes can pretty easily lead to running out of memory.

This is largely due to the use of `searchables()->all()`, which seems to load all entries in an index into memory, before releasing that memory.  Initially, I broke collections up into smaller collections (which helps with the Stache) but the search index will always fail as loading all of the searchables for the index (i.e. all collections tied to that index) before letting the garbage collector at it is a poor use of memory.

I'm using the Meilisearch addon, which also makes use of this call, but I've modified it slightly to fix this issue.

Changing this:
```
// Prepare documents for update
$searchables = $this->searchables()->all()->map(function ($entry) {
    return array_merge(
        $this->searchables()->fields($entry),
        $this->getDefaultFields($entry),
    );
});

// Update documents
$documents = new Documents($searchables);
$this->insertDocuments($documents);
```

To this:
```
$searchableProvidersReflection = new \ReflectionProperty(get_class($this->searchables()), 'providers');
$searchableProvidersReflection->setAccessible(true);

//Get the collection containing the provider data.
$providers = $searchableProvidersReflection->getValue($this->searchables());

//Now get the underlying collection of Entries
$collection = $providers['collection'];

//Now we have to get our keys, which should be the array of Searchable collections.
$collectionKeysReflection = new \ReflectionProperty(get_class($collection), 'keys');
$collectionKeysReflection->setAccessible(true);

$keys = $collectionKeysReflection->getValue($collection);

foreach($keys as $key)
{
    $coll = $providers['collection'];
    $this->updateProviderIndex($coll, $key);
    
    $coll = null;
    unset($coll);     

    echo('Indexed '.$key.PHP_EOL);
    sleep(1);
    gc_collect_cycles();
}
```
With updateProviderIndex looking like this:
```
private function updateProviderIndex($collection, $key)
{
    $collection->setKeys([$key]);
    $entries = $collection->provide()->map(function ($entry) {
                         return array_merge(
                             $this->searchables()->fields($entry),
                             $this->getDefaultFields($entry),
                         );
                });
    $documents = new Documents($entries);
    $this->insertDocuments($documents);
    
    $entries = null;
    unset($entries);
    
    $searchables = null;
    unset($searchables);
    
    $documents = null;
    unset($documents);
}
```
As you can probably tell, PHP is not my forte.  I made use of Reflection to get at the underlying data structures and update them one-by-one instead of loading everything into memory.  This is a very wrong and ugly way to do this (I didn't want to edit core files, so I was forced to work from the outside), but it *does* work, and it fixes the issue.  I'm not sure how the actual fix should be handled, but doing something like this ensures that the memory usage should only go as high as the largest collection you have (so, if needed, you can split collections into smaller ones and add them to the same search index).

### How to reproduce

- Install Statamic
- Generate a bunch of entries (thousands)
- Stick them into one or multiple collections
- Slap those collections into a search index
- Run `search:update`
- Watch memory utilization steadily increase until all of the collections have been indexed, instead of rising and falling as each collection is indexed separately

### Environment

```yaml
(This is my local machine, but it happens locally and on a live site)
Environment
Laravel Version: 9.52.8
PHP Version: 8.1.9
Composer Version: 2.3.10
Environment: local
Maintenance Mode: OFF

Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.20.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
