### ISSUE TITLE
Glide focalpoints not invalidated after saving

### ISSUE THREAD

**Issue by laborb-jf** [statamic/cms#8856]
### Bug description

I have an issue where the half-strategy cache get's not invalidated when changing the focal point of an asset.

It works, when the asset is changed or replaced.
I'm using the Glide tag to display assets in Statamic Pro 4.23.2.
Even when I'm setting the invalidation rules in the static_caching.php to rules' => 'all, it only refreshes the image when replaced or changed. Otherwise I have to either delete the static cache manually in the control-panel or i have to clear my browser cache.
Both options are not convenient for normal users and not usable for websites which modify their assets quite often.

### How to reproduce

1. Add an image in the Statamic Control Panel like a portrait of a person
2. Save, publish and check on page if it's displayed
3. Open the asset in the CP and set a zoom focal point onto the face e.g.
4. Save, publish and check on page if it's displayed
5. For me, it's not. And also not changes in the focal point once it's displayed due to forced refresh
6. `{{ glide src="{url}" alt="{title}" class="employee-portrait" width="800" height="500" ratio="3/2" }}`

### Environment

```yaml
Environment
Application Name: ***
Laravel Version: 9.52.15
PHP Version: 8.2.8
Composer Version: 2.6.4
Environment: local
Debug Mode: ENABLED
URL: ***
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: mysql
Logs: stack / single, mattermost
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: regex
Stache Watcher: Disabled
Static Caching: half
Version: 4.23.2 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.1.0
pecotamic/sitemap: 1.4.6
rias/statamic-redirect: 3.1.0
spatie/statamic-responsive-images: 4.1.1
statamic/collaboration: 0.7.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
