### ISSUE TITLE
Saving navigations: need to click 'Save Changes' twice for button to be disabled & dirty state to go away

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#8859]
### Bug description

I've realised that when adding items to navigations, you need to click the "Save Changes" button twice for the changes to be saved, the button to be disabled and for the browser dirty state to go away.

https://github.com/statamic/cms/assets/19637309/d0804ad0-936e-4168-979b-6037b7e5ea3d

### How to reproduce

1. Create a navigation
2. Add some entries to the navigation
3. Click 'Save Changes'
4. See that the button isn't yet disabled and when clicking onto another page, you see the browser's dirty state
5. Click 'Save Changes' again
6. See that the button is now disabled and you can freely click away onto another page

### Environment

```yaml
Application Name: Site Name
Laravel Version: 10.28.0
PHP Version: 8.2.10
Composer Version: 2.6.3
Environment: local
Debug Mode: ENABLED
URL: site-name.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.27.0 PRO

Statamic Addons
doublethreedigital/runway: 5.3.3
duncanmcclean/static-cache-manager: 3.1.2
stillat/relationships: 2.1.1
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.6.1
studio1902/statamic-peak-seo: 7.0.3
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
