### ISSUE TITLE
Log getting flooded with unnecessary/wrong log debug. 

### ISSUE THREAD

**Issue by stanbridge-wcorrea** [statamic/cms#8860]
### Bug description

So, I'm using full measure static caching and my log files are getting FLOODED by this: 

"Log::debug('Static cache loaded ['.$url.'] If you are seeing this, your server rewrite rules have not been set up correctly.');" 

Looking for the code that does this I found out that there is a conditional that checks if we have a "_lqs_" in our $path Line 80 - see [file on GitHub](https://github.com/statamic/cms/blob/4.x/src/StaticCaching/Cachers/FileCacher.php#L80). , however there is another conditional to ADD that "_lqs_" that is not being checked to add the log message Line 167 - see [file on GitHub](https://github.com/statamic/cms/blob/4.x/src/StaticCaching/Cachers/FileCacher.php#L167). 

What happens when the "_lqs_" is not added simply because it's not long? in this case we have a flooded log file without any error. 

Everything is working fine except for the fact that I have huge log files with unnecessary messages. 

### How to reproduce

Fresh install. 

Enable full measure static cache.

Warm the cache.

Put a nocache tag anywhere.

Visit any URL and check the log. 

### Environment

```yaml
Environment
Application Name: statamic_local
Laravel Version: 9.52.16
PHP Version: 8.2.7
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: s11-statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: full
Version: 4.28.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
