### ISSUE TITLE
Paginate tag outputs all segments to first array

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#8874]
### Bug description

Since upgrading to V4, the pagination tag appears to be broken. All of the page numbers appear without the slider. 

I did some code diving, and it looks like the paginator parameters are correct with `onEachSide`, but then it outputs all segments to the first array.
```
Statamic\Extensions\Pagination\LengthAwarePaginator {#22195▶
  #items: Statamic\Entries\EntryCollection {#22191▶
    #items: array:9 [▶]
    #escapeWhenCastingToString: false
  }
  #perPage: 9
  #currentPage: 1
  #path: "http://focuscare.test/blog"
  #query: []
  #fragment: null
  #pageName: "page"
  +onEachSide: 3
  #options: array:2 [▶
    "path" => "http://focuscare.test/blog"
    "pageName" => "page"
  ]
  #total: 108
  #lastPage: 12
}
```

Output from `$paginator->renderArray()`:
```
array:2 [▶
  "all" => array:12 [▶]
  "segments" => array:3 [▶
    "first" => array:12 [▶]
    "slider" => []
    "last" => []
  ]
]
```

### How to reproduce

Pagination code:

```
{{ paginate }}
<div class="space-y-4">
  <div class="flex justify-between space-x-1">
    {{ if prev_page }}
      <div class="hidden sm:inline-flex">
        {{ partial:button :link="prev_page" text="Previous Page" type="neutral" size="medium" }}
      </div>
    {{ else }}
      <div class="hidden sm:inline-flex">
        {{ partial:button text="Previous Page" type="disabled" size="medium" }}
      </div>
    {{ /if }}

    <div class="mx-auto flex space-x-1">
      {{ links:segments }}
        {{ first }}
          {{ if page == current_page }}
            {{ partial:button :link="url" :text="page" type="secondary" size="medium" }}
          {{ else }}
            {{ partial:button :link="url" :text="page" type="neutral" size="medium" }}
          {{ /if }}
        {{ /first }}

        {{ if slider }}
          {{ partial:button text="..." type="disabled" size="medium" }}
        {{ /if }}

        {{ if slider }}
          {{ partial:button text="..." type="disabled" size="medium" }}
        {{ /if }}

        {{ slider }}
            {{ if page == current_page }}
              {{ partial:button :link="url" :text="page" type="secondary" size="medium" }}
            {{ else }}
              {{ partial:button :link="url" :text="page" type="neutral" size="medium" }}
            {{ /if }}
        {{ /slider }}

        {{ if slider || (!slider && last) }}
          {{ partial:button text="..." type="disabled" size="medium" }}
        {{ /if }}

        {{ last }}
          {{ if page == current_page }}
            {{ partial:button :link="url" :text="page" type="secondary" size="medium" }}
          {{ else }}
            {{ partial:button :link="url" :text="page" type="neutral" size="medium" }}
          {{ /if }}
        {{ /last }}
      {{ /links:segments }}
    </div>

    {{ if next_page }}
      <div class="hidden sm:inline-flex">
        {{ partial:button :link="next_page" text="Next Page" type="neutral" size="medium" }}
      </div>
    {{ else }}
      <div class="hidden sm:inline-flex">
        {{ partial:button text="Next Page" type="disabled" size="medium" }}
      </div>
    {{ /if }}
  </div>
  <div class="flex justify-between space-x-1 sm:hidden">
    {{ if prev_page }}
      {{ partial:button :link="prev_page" text="Previous" type="neutral" size="medium" }}
    {{ else }}
      {{ partial:button text="Previous Page" type="disabled" size="medium" }}
    {{ /if }}
    {{ if next_page }}
      {{ partial:button :link="next_page" text="Next" type="neutral" size="medium" }}
    {{ else }}
      {{ partial:button text="Next Page" type="disabled" size="medium" }}
    {{ /if }}
  </div>
</div>
{{ /paginate }}
```

### Environment

```yaml
Environment
Application Name: Focus Care
Laravel Version: 10.28.0
PHP Version: 8.1.22
Composer Version: 2.4.0
Environment: local
Debug Mode: ENABLED
URL: focuscare.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.30.0 PRO

Statamic Addons
mattrothenberg/statamic-mapbox-address: 0.7.4
mikemartin/helpscout-beacon: 1.0.3
rias/statamic-redirect: 3.2.0
spatie/statamic-responsive-images: 4.1.1
withcandour/aardvark-seo: 3.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
