### ISSUE TITLE
Bard text align does not work if no headings are enabled

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/cms#8876]
### Bug description

If you create a bard field without any headings enabled along with text alignment enabled, and then try to align text it will not align the text.

I believe this is because the text alignment tiptap plugin assumes you have headings enabled on this line:
https://github.com/statamic/cms/blob/c24b6985543c91655100f6b8a7f27074a45ad3b9/resources/js/components/fieldtypes/bard/BardFieldtype.vue#L711

### How to reproduce

1. Create a bard field in a blueprint
2. Disable all headings buttons
3. Enable any text alignment buttons
4. Save the field
5. Create an entry using the blueprint
6. Attempt to align text in the bard field, it does not work

### Environment

```yaml
Environment
Application Name: Dev Site
Laravel Version: 10.29.0
PHP Version: 8.2.8
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: devsite.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Livewire
Livewire: v3.0.10

Statamic
Addons: 14
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.30.0 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.1.0
godismyjudge95/statamic-embera: 1.0.0
godismyjudge95/statamic-tailwind-dev-mode: 1.0.1
heidkaemper/statamic-toolbar: 1.1.1
jonassiewertsen/statamic-livewire: 3.0.0
mitydigital/statamic-google-fonts: 1.0.3
mitydigital/statamic-logger: 1.0.0
o1y/statamic-flexible-width: 1.0.0
rias/statamic-address-field: 1.1.0
statamic-rad-pack/meilisearch: 3.0.2
stillat/antlers-components: 2.1.0
teamnovu/statamic-images-missing-alt: 1.0.2
webographen/statamic-widget-cache-controller: 1.0.2
webographen/statamic-widget-continue-editing: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
