### ISSUE TITLE
Slug field cannot target sibling fields inside of replicator set

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/cms#8881]
### Bug description

It appears that the slug field can only target fields that are on the global scope of the entry but cannot retrieve values that are next to it (ie. inside a grid row or replicator set)

### How to reproduce

1. Create a replicator in a blueprint
2. Add a text field to the default set
3. Add a slug field to the default set
4. Set the "from" attribute on the slug field to target the text field from step 2
5. Save the field and blueprints
6. Create an entry using the blueprint
7. Add a set using the replicator field
8. Type in the label field - note the slug field does not auto generate

### Environment

```yaml
Environment
Application Name: Dev Site
Laravel Version: 10.29.0
PHP Version: 8.2.8
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: devsite.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Livewire
Livewire: v3.0.10

Statamic
Addons: 14
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.30.0 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.1.0
godismyjudge95/statamic-embera: 1.0.0
godismyjudge95/statamic-tailwind-dev-mode: 1.0.1
heidkaemper/statamic-toolbar: 1.1.1
jonassiewertsen/statamic-livewire: 3.0.0
mitydigital/statamic-google-fonts: 1.0.3
mitydigital/statamic-logger: 1.0.0
o1y/statamic-flexible-width: 1.0.0
rias/statamic-address-field: 1.1.0
statamic-rad-pack/meilisearch: 3.0.2
stillat/antlers-components: 2.1.0
teamnovu/statamic-images-missing-alt: 1.0.2
webographen/statamic-widget-cache-controller: 1.0.2
webographen/statamic-widget-continue-editing: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

I believe this is just a matter of telling the slug field that when it is nested under a set it needs to check an additional context for the field name.
