### ISSUE TITLE
Custom route parameter resolution logic can overlap with CP routes

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/cms#8897]
### Bug description

I am implementing some custom routes for a site and I happened to be implementing custom route parameter resolution logic using a parameter called "product."

Unfortunately this appears to be the same parameter name as what is used for Statamic's update changelog routes:
https://github.com/statamic/cms/blob/6a540f3b698f094539262ea33a0af91792706690/routes/cp.php#L247-L248
which is causing an error because my route resolution logic doesn't account for this.

Would be great if we could scope all of Statamic's route parameters - perhaps by prepending "statamic_" to the beginning of all parameters?

### How to reproduce

1. Add a custom route resolution call in the `RouteServiceProvider` similar to the following:
```php
Route::bind(
	'product',
	fn (string $slug) => Entry::query()
		->where('collection', 'products')
		->where('slug', $slug)
		->first() ?? throw new ItemNotFoundException,
);
```
2. Visit the update changelog page for Statamic (or any addon) - https://devsite.test/cp/updater/statamic
3. It will error because the above route resolution is unintentionally used for this CP route.

### Environment

```yaml
Environment
Application Name: Dev Site
Laravel Version: 10.29.0
PHP Version: 8.2.8
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: devsite.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Livewire
Livewire: v3.0.10

Statamic
Addons: 14
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.31.0 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.1.0
godismyjudge95/statamic-embera: 1.0.0
godismyjudge95/statamic-tailwind-dev-mode: 1.0.1
heidkaemper/statamic-toolbar: 1.1.1
jonassiewertsen/statamic-livewire: 3.0.0
mitydigital/statamic-google-fonts: 1.0.3
mitydigital/statamic-logger: 1.0.1
o1y/statamic-flexible-width: 1.0.0
rias/statamic-address-field: 1.1.0
statamic-rad-pack/meilisearch: 3.0.2
stillat/antlers-components: 2.1.0
teamnovu/statamic-images-missing-alt: 1.0.2
webographen/statamic-widget-cache-controller: 1.0.2
webographen/statamic-widget-continue-editing: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
