### ISSUE TITLE
Parent-Child URI not working when it has a (mounted) prefix

### ISSUE THREAD

**Issue by Aquive** [statamic/cms#8898]
### Bug description

I want to achieve this URI structure for my blogs.

`/blog/parent/child`

I tried several things, but the `/blog` part makes sure it doesn't work as expected. I can get `/parent/child` without the `/blog` part working, no problems there. As soon as I add the `/blog` part, the system adds it twice and becomes: `/blog/blog/parent/child`, which is of course undesirable.

I tried mounting `/blog`, I tried it without mounting, nu success. I tried several combinations without succes.

### How to reproduce

- Create a blog collection which is orderable
- Create a blog page
- Create a route: `/{mount}/{parent_uri}/{child}`
- Mount the page to the collection
- Create a parent blog
- Create a child beneath parent
- Click visit URL from child blog post and see its URI.

![0kZhfLkq4kAAAAASUVORK5CYII](https://github.com/statamic/cms/assets/197229/2b6aa98a-4bda-498b-b6bb-20f07cba3cc1)

### Environment

```yaml
Environment
Laravel Version: 9.52.6
PHP Version: 8.2.2
Composer Version: 2.2.21
Environment: local
Debug Mode: ENABLED
URL: blog.local
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.10.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.6.2
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
