### ISSUE TITLE
Exception: Duplicate entry [$uuid] in [$collection] collection's structure after reordering collection

### ISSUE THREAD

**Issue by o1y** [statamic/cms#8904]
### Bug description

When setting an order for collection entries in Statamic and saving the new order, an exception is thrown: "Duplicate entry [$uuid] in [pages] collection's structure." As a result, no entries will be shown in the collection listing anymore. The workaround is to delete the faulty collection tree manually and not reorder the collection.

### How to reproduce

1. Clone this repository: https://github.com/o1y/statamic-collection-structure-exception
2. Go to the pages collection.
3. Click "Reorder" and then "Save".

Result:
```
local.ERROR: Duplicate entry [d3d495c6-c7b5-4cf4-8740-b39fcde7119a] in [pages] collection's structure.
```

I suspect the error is caused by the slugs on certain entries. If you delete all the entries that have a slug ending with `_xyz` (in my example repository the files are `2022-02-02.2022-02-02_test`, `2022-02-20.2022-02-20_testtest`, `2022-03-25.2022-03-25_tt` and `2022-05-23.2022-05-23_qq`), the entries can be reordered as expected.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.29.0
PHP Version: 8.2.11
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.31.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
