### ISSUE TITLE
Importing users into Eloquent fails due to wrong column type checked

### ISSUE THREAD

**Issue by mynetx** [statamic/cms#8907]
### Bug description

In [Storing Users in a Database](https://statamic.dev/tips/storing-users-in-a-database#from-a-fresh-statamic-project), there's these instructions:

> 6. ...
> If you have existing file based users, edit the migration to change the id column to a uuid.
> ```php
> $table->uuid('id')->change();
> ```
> 
> 7. Run the migrations:
> ```shell
> php artisan migrate
> ```
> 
> 8. If you have existing file based users, import them:
> ```shell
> php please eloquent:import-users
> ```

While trying to run the second command, I’m seeing this error:

```error
Your users table must use UUIDs for ids in order for this migration to run
```

### How to reproduce

Follow the same steps as above.

This is my `User` model:

```php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, HasUuids, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'preferences' => 'json',
    ];
}
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.30.1
PHP Version: 8.2.11
Composer Version: 2.5.5
MySQL Version: 8.0.33
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.31.0 Solo
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None

### Additional details

After running the migrations, the column type of `users.id` is `CHAR(36)`. The code in `ImportUsers.php` expects a GUID or a STRING, however.

```php
        if (! in_array(Schema::getColumnType('users', 'id'), ['guid', 'string'])) {
            $this->error('Your users table must use UUIDs for ids in order for this migration to run');

            return;
        }
```

<img width="335" alt="Bildschirmfoto 2023-11-01 um 17 45 16" src="https://github.com/statamic/cms/assets/6348321/af44d45c-4ea3-4220-9da2-3591b5a8e17d">
