### ISSUE TITLE
Collection names only translated in CP Nav

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#8913]
### Bug description

I tried the new translation feature [#8664] and seems like one part is missing. This _may_ be related to Eloquent driver, but I'm not sure. The problem is collection names is translated in the Nav, but not in the list of collections.

![norwergian](https://github.com/statamic/cms/assets/1135679/ce36c089-500a-4796-8349-fe0a69ad4859)
![english](https://github.com/statamic/cms/assets/1135679/f739ed39-f9a8-43e4-aedf-e4a4defca4f3)

### How to reproduce

* Create a translation file for the selected language
* Add translations for collection names

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.15
PHP Version: 8.1.22
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: properti-master.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.31.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
properti/estate-items-import: dev-main
properti/integrations: dev-main
properti/properti-dashboard: dev-main
r8edge/imagemap: dev-main
r8edge/welcome-widget: dev-main
statamic/eloquent-driver: 2.6.1

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: eloquent
Collection Trees: file
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: file
Navigation Trees: file
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
