### ISSUE TITLE
Assets field not reorderable after site switch 

### ISSUE THREAD

**Issue by JoeriE** [statamic/cms#8920]
### Bug description

I have a multi language site setup with two languages. On a page there's a replicator field with a set that contains an assets field where they can add multiple images. The field is not translatable because the images stay the same on every language. 

When they enter the page in the cms in the not-origin version, the field is not editable / reorderable / .. which is correct. But if they switch to the origin language, the field is still not reorderable. After a refresh of the page, the field is again reorderable. Also the other way around is not correct: if they switch from origin to not-origin the field is still reorderable, but it shouldn't. After a refresh of the page, the field is working as expected. 

### How to reproduce

1. Create multi-site website
2. Add replicator field with a set containing an assets field. Don't make the field translatable 
3. Create a page and add images to the field
4. Duplicate this to the other language
5. Switching between sites without a page refresh will show the bug

### Environment

```yaml
Environment
Laravel Version: 10.30.1
PHP Version: 8.1.24
Composer Version: 2.6.5
Environment: staging
Debug Mode: ENABLED
Maintenance Mode: OFF

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Disabled
Static Caching: full
Version: 4.31.0 PRO

Statamic Addons
aerni/advanced-seo: 2.3.0
swiftmade/statamic-clear-assets: 2.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
