### ISSUE TITLE
User with only 'view {container} assets' permissions can still create folders

### ISSUE THREAD

**Issue by simonolog** [statamic/cms#8922]
### Bug description

Users that only have the `view {container} assets` permission still get the buttons for "upload" and "create folder". Clicking on "upload" shows the upload dialog and lets the user select a file, but triggers a permission error (incl. toast) after selecting/confirming a file. Clicking on "create folder" however let's the user simply create a folder.

![Screenshot_2023-11-03_14-12-53@2x](https://github.com/statamic/cms/assets/7941370/cb28dcbf-2400-4024-98a2-f77895a141f7)

![Screenshot_2023-11-03_14-15-52@2x](https://github.com/statamic/cms/assets/7941370/2d5c0669-e5a8-4c5e-b4ca-f4e65b6624d6)

### How to reproduce

Simply navigate to an asset container with a user that only has `view {container} assets` permission. Tested in both 4.x as well as 3.4.x.

### Environment

```yaml
Environment
Application Name: my site
Laravel Version: 10.22.0
PHP Version: 8.2.12
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: mysite.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: redis
Database: mysql
Logs: daily
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 8
Antlers: runtime
Stache Watcher: Enabled
Static Caching: half
Version: 4.20.0 PRO

Statamic Addons
doublethreedigital/duplicator: 4.0.1
elvenstar/statamic-meilisearch: 2.0.1
visuellverstehen/statamic-anchor-navigation: 0.3.5-beta
visuellverstehen/statamic-classify: 2.6.1
visuellverstehen/statamic-content-renderer: 0.1.1-beta
visuellverstehen/statamic-glossary-tooltips: dev-main
visuellverstehen/statamic-picturesque: 1.3.0
visuellverstehen/statamic-pixxio-flysystem: dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
