### ISSUE TITLE
Using CMD+K in Bard field does not allow you to create a link like the Markdown field does 

### ISSUE THREAD

**Issue by aaronbushnell** [statamic/cms#8930]
### Bug description

When you highlight text in the Bard editor and use CMD+K my expectation is that it'd open the link editor to hyperlink some bit of text. Unfortunately, it doesn't do that—but it _does_ work in the Markdown field. 

This might be something that can't be fixed within the CMS, but in a third-party JS library. Figured I'd log it just in case, though!

### How to reproduce

1. Highlight text in a Bard editor
2. Press CMD+K to try and link that text
3. See no link pop-up and feel kinda sad 😢 

### Environment

```yaml
Environment
Application Name: Statamic Starter
Laravel Version: 10.30.1
PHP Version: 8.2.11
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: statamic-starter.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.32.0 PRO

Statamic Addons
bencarr/statamic-hyperlink: 1.2.3
rias/statamic-redirect: 3.2.0
statamic/seo-pro: 5.2.2
trendyminds/guide: dev-main
trendyminds/palette: dev-main
trendyminds/tip: dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
