### ISSUE TITLE
Condition on asset field doesn't work

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#8943]
### Bug description

The condition 'Show when' 'asset' 'not null' doesn't work for me, and it's used as an example in the docs:
https://statamic.dev/conditional-fields#overview

I don't think I'm doing anything special or different to the example.

Thanks!

### How to reproduce

Try to only show a field when an asset field has an asset.

### Environment

```yaml
Laravel Version: 10.22.0
PHP Version: 8.2.5
Version: 4.21.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
