### ISSUE TITLE
Bard field inside a grid field with UI Mode set to "Table" throwing JS error

### ISSUE THREAD

**Issue by taylorcammack** [statamic/cms#8947]
### Bug description

Getting a `"TypeError: Cannot read properties of null (reading 'addEventListener')"` when placing a Bard field inside of a Grid field set to display as a table. It appears this error is also causing asset uploads to S3 containers to fail.

Was able to recreate on fresh Statamic install.

### How to reproduce

- Create a Grid field.
- Set UI Mode to "Table".
- Place a Bard field inside of it.
- On adding a row to the grid, it will throw the JS error.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.30.1
PHP Version: 8.2.11
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: bug-test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.32.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
