### ISSUE TITLE
 I updated from v3 to v4. Now i get a "Target class [...] does not exist." error for my addon.

### ISSUE THREAD

**Issue by colinupgraders** [statamic/cms#8948]
### Bug description

I updated to v4. Now i get a "Target class [...] does not exist." error for my addon.

### How to reproduce

Update to v4 from v3 with addon installed.

https://cms.biggelaarparket.upgraders.dev/!/timeslots/get_date/2023-11-7

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.16
PHP Version: 8.2.8
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.32.0 PRO

Statamic Addons
upgraders/timeslots: dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
