### ISSUE TITLE
The "Date" field is just spinning, and I receive a 500 error from the server. 

### ISSUE THREAD

**Issue by csongorur** [statamic/cms#8951]
### Bug description

 I encounter an error when trying to create or edit a collection entry. The "Date" field is just spinning, and I receive a 500 error from the server. 

### How to reproduce

![Screenshot 2023-11-08 at 11 19 07](https://github.com/statamic/cms/assets/30229029/3ed31ae5-4764-4f89-ae13-f8f46c55b68d)
![Screenshot 2023-11-08 at 11 19 37](https://github.com/statamic/cms/assets/30229029/892968d2-04a4-4d82-924f-0a793f360d0d)
![Screenshot 2023-11-08 at 11 20 53](https://github.com/statamic/cms/assets/30229029/e5446815-2005-43f9-81e4-d92ede7f7ec5)
![Screenshot 2023-11-08 at 11 21 03](https://github.com/statamic/cms/assets/30229029/6262eabb-3939-4b18-9311-4ce997ea31e7)

The value of the $value variable in this point is this json string and the Carbon::parse can't make a Carbon object from this json string.

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 10.31.0
PHP Version: 8.2.11
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.32.0 Solo
```

### Installation

Existing Laravel app

### Antlers Parser

None
