### ISSUE TITLE
The "Bard" field is just spinning, and I receive a 500 error from the server.

### ISSUE THREAD

**Issue by csongorur** [statamic/cms#8952]
### Bug description

 I encounter an error when trying to edit a collection entry. The "Bard" field is just spinning, and I receive a 500 error from the server.

### How to reproduce

![Screenshot 2023-11-07 at 16 19 59](https://github.com/statamic/cms/assets/30229029/6106af8d-eefe-458d-8e6f-802573569040)
![Screenshot 2023-11-08 at 10 39 31](https://github.com/statamic/cms/assets/30229029/a3fdb63d-36d1-4dba-9763-417d2f28b40f)
![Screenshot 2023-11-08 at 10 39 46](https://github.com/statamic/cms/assets/30229029/2a40cc28-5af5-494a-b8ba-143281f1d4c8)
The problem is this $document is an array.

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 10.31.0
PHP Version: 8.2.11
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.32.0 Solo
```

### Installation

Existing Laravel app

### Antlers Parser

None

**Comment by duncanmcclean** [comment]
Can you share the entry's markdown file?

**Comment by csongorur** [comment]
```
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: content
            field:
              buttons:
                - h2
                - h3
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - removeformat
                - quote
                - anchor
                - image
                - table
                - h1
                - h4
                - h5
                - underline
                - alignleft
                - aligncenter
                - alignright
                - alignjustify
              smart_typography: false
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: false
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: false
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: Content
              icon: bard
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              duplicate: false
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
title: Service

```
