### ISSUE TITLE
preferences: start_page doesn't work with multisite?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#8970]
### Bug description

I added a new role called `willow_park_editor` and added a custom start page `start_page: collections/willow_park` to `resources/users/roles.yaml`

When I impersonate  that user (`willow_park_editor`) the start page defaults to `/cp/dashboard`

### How to reproduce

- Create a multisite
- Create a role
- Under `/cp/preferences` give the role a custom start page
- Impersonate the user
- The start page will default to `/cp/dashboard` not the start page specified in `/cp/preferences`

### Logs

```shell
No logs to share.
```

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.33.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
