### ISSUE TITLE
Changing superuser params don't work (reopen)

### ISSUE THREAD

**Issue by andreas-eisenmann** [statamic/cms#8978]
### Bug description

This issue has been marked as stale by the robot but has not been solved: #changin

Using the eloquent driver, edit an **existing** user and try to set the "super" flag. It will not be saved.

### How to reproduce

Steps:

- Use the eloquent driver and store users in the database
- Add a new user without "super" flag
- Edit the previously added user and now set the "super" flag
- This flag will not be saved to database

Debugging:

When **creating** a new user via CP [\Statamic\Http\Controllers\CP\Users\UsersController::store](https://github.com/statamic/cms/blob/v4.32.0/src/Http/Controllers/CP/Users/UsersController.php#L145) is called. 
The "super" flag is set [here](https://github.com/statamic/cms/blob/v4.32.0/src/Http/Controllers/CP/Users/UsersController.php#L171) via:

```php
$user->makeSuper();
```

The implementation of `makeSuper()` in the eloquent driver updates the model instance:

```php
$this->model()->super = true;
```

And everything is fine, the flag will be saved to the database.

When **updating** an existing user via CP, trying to set the "super" flag to `true`, [\Statamic\Http\Controllers\CP\Users\UsersController::update](https://github.com/statamic/cms/blob/v4.32.0/src/Http/Controllers/CP/Users/UsersController.php#L245) is called. 
The "super" flag is set [here](https://github.com/statamic/cms/blob/v4.32.0/src/Http/Controllers/CP/Users/UsersController.php#L266) via:

```php
$user->super = $request->super;
```

In this case, the model instance is not being updated. [\Statamic\Auth\Eloquent\User::saveToDatabase](https://github.com/statamic/cms/blob/v4.32.0/src/Auth/Eloquent/User.php#L244) will save the model instance immediately to the database without taking account to the "super" flag which has been previously set.

What's the reason for that all values in [\Statamic\Http\Controllers\CP\Users\UsersController::update](https://github.com/statamic/cms/blob/v4.32.0/src/Http/Controllers/CP/Users/UsersController.php#L245) are being set via a dedicated method (e.g. `$user->set($key, $value)`, `$user->email($request->email)`, `$user->roles($request->roles)`, `$user->groups($request->groups)`) but "super" via magic property?

Maybe there should be also a special case for the key "super" in [\Statamic\Auth\Eloquent\User::__set](https://github.com/statamic/cms/blob/v4.32.0/src/Auth/Eloquent/User.php#L355) as it already exists for the key "timestamps"?

There's definitely no way to set the "super" flag on update when using the eloquent driver.

### Environment

```yaml
Environment
Application Name: XXXXXXX
Laravel Version: 10.29.0
PHP Version: 8.2.10
Composer Version: 2.6.3
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: pgsql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Localization
Installed: de, en
LaravelLang\Attributes\Plugin: v2.4.1
LaravelLang\HttpStatuses\Plugin: v3.4.5
LaravelLang\Lang\Plugin: 13.2.6
Protected Locales: de, en
Publisher Version: v14.7.0

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.30.0 PRO

Statamic Addons
statamic/eloquent-driver: 2.8.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
