### ISSUE TITLE
Navigation blueprint fields show synced/descynced label on non-multisite

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#8983]
### Bug description

I have a navigation with some fields in the blueprint. The navigation builder interface shows synced/desynced buttons when I'm not running a multisite. I don't think this used to be the case.

<img width="447" alt="Screenshot_2023-11-13_at_14 31 19" src="https://github.com/statamic/cms/assets/69107412/9c0391ad-79f1-4f6f-9c61-3d828ccc697b">

### How to reproduce

1. Create a new Statamic site.
2. Create a navigation.
3. Enable pages as a collection source for your navigation.
4. Link an entry.
5. Open the entry in the navigation stack.
6. See the sync icons.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.31.0
PHP Version: 8.2.10
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.33.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
