### ISSUE TITLE
Validation rules: required_if with url won't accept empty

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#8986]
### Bug description

I can't get these two rules to work together. I've tried the 'sometimes' toggle and that doesn't work either:

![image](https://github.com/statamic/cms/assets/20210934/825ed49d-2f3b-4001-b200-3aad790bfdaa)

![image](https://github.com/statamic/cms/assets/20210934/2cf1ed2b-8aa2-4443-b464-bd95bc12bdb6)

### How to reproduce

1. Set up a text field and a toggle field
2. Add 'required_if:toggle_field,true' and 'url' validation rules to text field
3. Try to save the empty text field

### Environment

```yaml
Laravel Version: 10.22.0
PHP Version: 8.2.5
Version: 4.21.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jasonvarga** [comment]
Make the text field `required|sometimes|url` and make it conditionally visible with the toggle.

```yaml
handle: reservations_url
field:
  type: text
  if: show_reservations_button
  validate:
    - sometimes
    - required
    - url
```
