### ISSUE TITLE
Text fieldtype does not allow autocomplete to be set

### ISSUE THREAD

**Issue by maurice-ellis** [statamic/cms#8988]
### Bug description

When setting the autocomplete for the fieldtype, it doesn't set

```php
[
    'handle' => 'name',
    'field' => [
        'type' => 'text',
        'autocomplete' => 'off'
    ]
]
```

Autocomplete options from the text fieldtype php file

```php
'autocomplete' => [
  'display' => __('Autocomplete'),
  'instructions' => __('statamic::fieldtypes.text.config.autocomplete'),
  'type' => 'select',
  'clearable' => true,
  'options' => [
      'additional-name',
      'address-level1',
      'address-level2',
      'address-level3',
      'address-level4',
      'address-line1',
      'address-line2',
      'address-line3',
      'bday',
      'bday-day',
      'bday-month',
      'bday-year',
      'cc-additional-name',
      'cc-csc',
      'cc-exp',
      'cc-exp-month',
      'cc-exp-year',
      'cc-family-name',
      'cc-given-name',
      'cc-name',
      'cc-number',
      'cc-type',
      'country',
      'country-name',
      'current-password',
      'email',
      'family-name',
      'given-name',
      'honorific-prefix',
      'honorific-suffix',
      'language',
      'name',
      'new-password',
      'nickname',
      'off',
      'on',
      'organization',
      'organization-title',
      'photo',
      'postal-code',
      'sex',
      'street-address',
      'tel',
      'tel-area-code',
      'tel-country-code',
      'tel-extension',
      'tel-local',
      'tel-local-prefix',
      'tel-local-suffix',
      'tel-national',
      'transaction-amount',
      'transaction-currency',
      'url',
      'username',
  ],
],
```

### How to reproduce

Set the autocomplete option in a text fieldtype config, but nothing will be set on the text fieldtype component. Below is the text fieldtype component. Not sure if there was a mistake, but autoselect was set, but no autocomplete.

```js
<template>
    <text-input
        ref="input"
        :value="value"
        :classes="config.classes"
        :focus="config.focus || name === 'title' || name === 'alt'"
        :autoselect="config.autoselect"
        :type="config.input_type"
        :isReadOnly="isReadOnly"
        :prepend="__(config.prepend)"
        :append="__(config.append)"
        :limit="config.character_limit"
        :placeholder="__(config.placeholder)"
        :name="name"
        :id="fieldId"
        @input="updateDebounced"
        @focus="$emit('focus')"
        @blur="$emit('blur')"
    />
</template>

<script>
import Fieldtype from './Fieldtype.vue';

export default {

    mixins: [Fieldtype]

}
</script>
```

And here is the text-input component, still nothing for autocomplete

```js
<template>
    <div class="flex items-center">
        <div class="input-group">
            <slot name="prepend" v-if="prepend">
                <div class="input-group-prepend">
                    {{ __(prepend) }}
                </div>
            </slot>
            <input
                ref="input"
                class="input-text"
                :class="classes"
                :id="id"
                :name="name"
                :value="value"
                :type="type"
                :step="step"
                :disabled="disabled"
                :readonly="isReadOnly"
                :placeholder="placeholder"
                :autofocus="focus"
                :min="min"
                @input="$emit('input', $event.target.value)"
                @keydown="$emit('keydown', $event)"
                @focus="$emit('focus')"
                @blur="$emit('blur')"
            >
            <slot name="append" v-if="append">
                <div class="input-group-append">
                    {{ __(append) }}
                </div>
            </slot>
        </div>
        <div class="text-xs ml-2" :class="limitIndicatorColor" v-if="limit">
            <span v-text="currentLength"></span>/<span v-text="limit"></span>
        </div>
    </div>
</template>

<script>
import LengthLimiter from '../LengthLimiter.vue'

export default {
    mixins: [LengthLimiter],
    props: {
        name: {},
        disabled: { default: false },
        classes: { default: null },
        id: { default: null },
        isReadOnly: { type: Boolean, default: false },
        placeholder: { required: false },
        type: { default: "text" },
        step: {},
        value: { required: true },
        prepend: { default: null },
        append: { default: null },
        focus: { type: Boolean },
        autoselect: { type: Boolean },
        min: { type: Number, default: undefined }
    },
    mounted() {
        if (this.autoselect) {
            this.$refs.input.select();
        }
        if (this.focus) {
            this.$refs.input.focus();
        }
    }
}
</script>

```

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 10.30.1
PHP Version: 8.2.3
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.31.0 PRO

Statamic Addons
thrtwoe/builder: dev-main
thrtwoe/jumpstart: dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
