### ISSUE TITLE
Unable to create Collection route using Entries fieldtype variable from the blueprint

### ISSUE THREAD

**Issue by chopperoon** [statamic/cms#9004]
### Bug description

I want to create a Collection route using a variable from the Collection blueprint. The variable comes from an Entries fieldtype (with Max items set to 1). 

The docs say that "You can use standard meta variables in addition to the variables from the collection's blueprint to define your route rule." 

I'd expect that I can use the variable from the Entries fieldtype in the Collection route. But when I output entries from the Collection on the front-end the route in `{{ url }}` uses the id (e.g 16a29ef9-3085-4b67-a4e5-45aa572959db) rather than the slug from the Entries fieldtype.

### How to reproduce

1. Create a Collection
2. Add an Entries fieldtype (with Max Items set to 1) to the Collection blueprint
3. Edit the Collection config to set a route using the handle of the Entries fieldtype
4. Output the `{{ collection }}` and see that `{{ url }}` doesn't use the slug

### Environment

```yaml
Environment
Application Name: XXXXXXXXXX
Laravel Version: 10.31.0
PHP Version: 8.2.7
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.33.0 PRO

Statamic Addons
simonridley/tracking-code-manager: 1.0.2
statamic/seo-pro: 5.2.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
