### ISSUE TITLE
Two integer_field fieldtypes breaks sort modifier?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#9005]
### Bug description

I've been trying to sort a grid fieldtype called `plots_field` using `sort($price_integer_field, 'asc')` but it just didn't sort properly, I couldn't figure out why? 

My blueprint contains two `integer` fieldtypes, `plot_integer_field` and `price_integer_field`

```
handle: plots_field
            field:
              fields:
                -
                  handle: plot_integer_field
                  field:
                    type: integer
                    display: Plot
                    icon: integer
                    width: 33
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
                -
                  handle: price_integer_field
                  field:
                    type: integer
                    display: Price
                    icon: integer
                    width: 33
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
```
This is my template loop, it's using `sort($price_integer_field, 'asc')`

```php
{{ collection:developments select="plots_field|price_integer_field|status_select_field|title" :from="segment_1" as="items" }}	
	<ul>
		{{ items }}
			{{ plots_field | where('status_select_field', 'available') | sort($price_integer_field, 'asc') }}
				<li>
					{{ price_integer_field  }} - {{ title }}
				</li>
			{{ /plots_field }}
		{{ /items }}
	</ul>	
{{ /collection:developments }}
```
The list below is the output, it should order the list lowest value to highest, but it doesn't.
```
300000 - The Meadow
400000 - The Meadow
500000 - The Meadow
200000 - The Meadow
100000 - The Meadow
200000 - The Terrace
100000 - The Terrace
300000 - The Terrace
```
However, when I remove/delete `plot_integer_field` from my blueprint, the ordering works (a bit better). The `plots_field` is sorted by `asc`. Ideally, I'd like to sort the entire list by price, the output appears to group the prices by entry, `The Meadow` and `The Terrace` are individual entries.

```
100000 - The Meadow
200000 - The Meadow
300000 - The Meadow
400000 - The Meadow
500000 - The Meadow
100000 - The Terrace
200000 - The Terrace
300000 - The Terrace
```

### How to reproduce

1. Create an blueprint with two integer fieldtypes
2. Use the sort modifier
3. It won't work
4. Delete a integer fieldtype
5. It'll now work!?

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.34.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by stephenmeehanuk** [comment]
Here's a basic example


Blueprint
```
handle: grid_field
            field:
              fields:
                -
                  handle: plot_number
                  field:
                    type: integer
                    display: Plot
                    icon: integer
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
                -
                  handle: integer_field
                  field:
                    type: integer
                    display: 'Integer Field'
                    icon: integer
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
                -
                  handle: select_field
                  field:
                    options:
                      for_sale: 'For Sale'
                      sold: Sold
                    taggable: false
                    push_tags: false
                    multiple: false
                    clearable: false
                    searchable: true
                    cast_booleans: false
                    type: select
                    display: 'Select Field'
                    icon: select
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
```

Here's the data

```
grid_field:
  -
    id: lp138npc
    integer_field: 500000
    select_field: for_sale
    plot_number: 1
  -
    id: lp138evl
    integer_field: 100000
    select_field: for_sale
    plot_number: 2
  -
    id: lp138hqy
    integer_field: 200000
    select_field: for_sale
    plot_number: 3
  -
    id: lp138lvq
    integer_field: 400000
    select_field: sold
    plot_number: 4
  -
    id: lp138jza
    integer_field: 300000
    select_field: for_sale
    plot_number: 5
```



The loop
```
{{ grid_field | group_by('select_field')}}
				{{ for_sale | sort($integer_field, 'asc')}}
					<li>{{ integer_field }} - {{ select_field.label }}</li>
				{{ /for_sale }}
{{ /grid_field }}
```
The output using `asc` (low to high) - wrong
```
500000 - For Sale
100000 - For Sale
200000 - For Sale
300000 - For Sale
```
Remove `plot_number` from the blueprint and the output is correct
```
100000 - For Sale
200000 - For Sale
300000 - For Sale
500000 - For Sale
```

Hope this explains it better.
