### ISSUE TITLE
Data Loss When Collection Entry Is Saved

### ISSUE THREAD

**Issue by DanielDarrenJones** [statamic/cms#9007]
### Bug description

We are seeing data being lost when saving entries, this appears to only affect data stored within a revealer tag (which we have been using extensively across our project). Initially we thought this was a browser issue, however we don't believe this is the case as this was happening on the latest chrome version.

We just had this happen when saving with the command+s feature after editing some data, here is a diff of the before and after of saving - weirdly it seems to completely remove the data from fields within a revealer although its seems random which data is being removed: https://www.diffchecker.com/eCI4c8nX/

We noticed the following error in the console:
<details>
  <summary>Console Error</summary>
  
 
![Screenshot 2023-11-16 at 15 03 32](https://github.com/statamic/cms/assets/8768709/5b9677cf-c7ba-47d4-84ef-aadec800bcab)

  
  ```javascript
  TypeError: Cannot use 'in' operator to search for '1' in [{"type":"heading","attrs":{"textAlign":"center","size":null,"tracking":null,"font":null,"weight":null,"uppercase":null,"level":1},"content":[{"type":"text","marks":[{"type":"bold","attrs":{"size":"bard-size-10xl","tracking":"bard-tracking-wider","font":"bard-font-mfred","weight":null,"uppercase":"bard-case-uppercase"}},{"type":"textColor","attrs":{"color":"#F28A07"}}],"text":"PELORUS"},{"type":"hardBreak"},{"type":"text","marks":[{"type":"bold","attrs":{"size":"bard-size-6xl","tracking":"bard-tracking-wider","font":"bard-font-mfred","weight":null,"uppercase":"bard-case-uppercase"}},{"type":"textColor","attrs":{"color":"#F28A07"}}],"text":"TRAVEL"},{"type":"hardBreak"}]},{"type":"set","attrs":{"id":"lo7d7mnw","enabled":true,"values":{"type":"buttons","buttons":[{"label":"Enquire","link_type":"url","target_blank":false,"url":"https:\/\/www.google.com","button_type":"button","button_colour":"white","show_controls":false,"entry":[],"email":null,"tel":null,"sms":null,"asset":[],"_id":"lo7d7nvb"}],"alignment":"center"}}},{"type":"paragraph","attrs":{"textAlign":"center","size":null,"tracking":null,"font":null,"weight":null,"uppercase":null}}]
    at data_set (app-932dbebf.js:171:8622)
    at app-932dbebf.js:187:4556
    at Array.forEach (<anonymous>)
    at Values.mergeDottedKeys (app-932dbebf.js:187:4544)
    at q.resetValuesFromResponse (app-932dbebf.js:187:6320)
    at app-932dbebf.js:188:73774
(anonymous) @ app-932dbebf.js:188
  ```
  
</details>

### How to reproduce

We don't have an exact set of steps to reproduce this currently - The issue is occurring on a fresh reload of the page though. We will update if we can track down a reliable way of reproducing this.

### Environment

```yaml
Environment
Application Name: Example
Laravel Version: 10.32.1
PHP Version: 8.2.11
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: example.test/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.34.0 PRO

Statamic Addons
doefom/currency-fieldtype: 1.2.2
jacksleight/statamic-bard-texstyle: 3.1.3
ndx/statamic-bard-color-picker: 1.2.0
withcandour/aardvark-seo: 3.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

<details>
  <summary>Hero - Full Screen Fieldset</summary>
   
  ```yaml
  title: 'Hero - Full Screen'
fields:
  -
    handle: slides
    field:
      collapse: false
      previews: true
      fullscreen: true
      sets:
        new_set_group:
          display: Sides
          instructions: null
          icon: null
          sets:
            slide:
              display: Slide
              instructions: null
              icon: null
              fields:
                -
                  handle: image_or_video
                  field:
                    options:
                      image: Image
                      video: Video
                    default: image
                    type: button_group
                    display: 'Image or Video'
                    icon: button_group
                    localizable: true
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    hide_display: false
                -
                  handle: image
                  field:
                    max_files: 1
                    min_files: 1
                    mode: list
                    container: images
                    restrict: false
                    allow_uploads: true
                    show_filename: true
                    show_set_alt: true
                    type: assets
                    display: Image
                    icon: assets
                    localizable: true
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    hide_display: false
                    validate:
                      - image
                    if:
                      image_or_video: 'equals image'
                -
                  handle: mobile_image
                  field: common.image
                  config:
                    display: 'Mobile Image'
                    if:
                      image_or_video: 'equals image'
                -
                  handle: video_url
                  field:
                    type: link
                    display: 'Video URL'
                    icon: link
                    localizable: true
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    hide_display: false
                    if:
                      image_or_video: 'equals video'
                    replicator_preview: true
                    container: when_to_go
                -
                  handle: mobile_video_url
                  field:
                    type: link
                    display: 'Mobile Video URL'
                    icon: link
                    localizable: true
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
                    if:
                      image_or_video: 'equals video'
                    container: when_to_go
                -
                  handle: simple_content
                  field: simple_content.simple_content
                  config:
                    localizable: true
                -
                  handle: show_controls
                  field:
                    mode: toggle
                    type: revealer
                    display: 'Show Controls'
                    icon: revealer
                    localizable: true
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    hide_display: false
                -
                  handle: show_color_overlay
                  field:
                    mode: toggle
                    type: revealer
                    display: 'Show Colour Overlay'
                    icon: revealer
                    localizable: true
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
                    if:
                      show_controls: 'equals true'
                    width: 66
                -
                  handle: color_overlay
                  field: common.color_overlay
                  config:
                    localizable: true
                    if:
                      show_controls: 'equals true'
                      show_color_overlay: 'equals true'
                    width: 50
                -
                  handle: color_overlay_percentage
                  field: common.color_overlay_percentage
                  config:
                    if:
                      show_controls: 'equals true'
                      show_color_overlay: 'equals true'
                    width: 50
                -
                  handle: show_padding
                  field: common.show_controls
                  config:
                    display: 'Show Padding'
                    width: 66
                    if:
                      show_controls: 'equals true'
                -
                  handle: enable_padding
                  field: common.enable_switch
                  config:
                    display: 'Enable Padding'
                    width: 33
                    if:
                      show_controls: 'equals true'
                      show_padding: 'equals true'
                -
                  handle: padding_top
                  field: common.padding
                  config:
                    display: Top
                    width: 25
                    if:
                      show_controls: 'equals true'
                      show_padding: 'equals true'
                -
                  handle: padding_right
                  field: common.padding
                  config:
                    display: Right
                    width: 25
                    if:
                      show_controls: 'equals true'
                      show_padding: 'equals true'
                -
                  handle: padding_bottom
                  field: common.padding
                  config:
                    display: Bottom
                    width: 25
                    if:
                      show_controls: 'equals true'
                      show_padding: 'equals true'
                -
                  handle: padding_left
                  field: common.padding
                  config:
                    display: Left
                    width: 25
                    if:
                      show_controls: 'equals true'
                      show_padding: 'equals true'
                -
                  handle: show_desktop_padding
                  field: common.show_controls
                  config:
                    display: 'Show Desktop Padding'
                    width: 66
                    if:
                      show_controls: 'equals true'
                      show_padding: 'equals true'
                -
                  handle: enable_desktop_padding
                  field: common.enable_switch
                  config:
                    display: 'Enable Desktop Padding'
                    width: 33
                    if:
                      show_controls: 'equals true'
                      show_padding: 'equals true'
                      show_desktop_padding: 'equals true'
                -
                  handle: desktop_padding_top
                  field: common.padding
                  config:
                    display: Top
                    width: 25
                    if:
                      show_controls: 'equals true'
                      show_padding: 'equals true'
                      show_desktop_padding: 'equals true'
                -
                  handle: desktop_padding_right
                  field: common.padding
                  config:
                    display: Right
                    width: 25
                    if:
                      show_controls: 'equals true'
                      show_padding: 'equals true'
                      show_desktop_padding: 'equals true'
                -
                  handle: desktop_padding_bottom
                  field: common.padding
                  config:
                    display: Bottom
                    width: 25
                    if:
                      show_controls: 'equals true'
                      show_padding: 'equals true'
                      show_desktop_padding: 'equals true'
                -
                  handle: desktop_padding_left
                  field: common.padding
                  config:
                    display: Left
                    width: 25
                    if:
                      show_controls: 'equals true'
                      show_padding: 'equals true'
                      show_desktop_padding: 'equals true'
                -
                  handle: show_alignment
                  field: common.show_controls
                  config:
                    display: 'Show Alignment'
                    width: 66
                    if:
                      show_controls: 'equals true'
                -
                  handle: enable_alignment
                  field: common.enable_switch
                  config:
                    display: 'Enable Alignment'
                    width: 33
                    if:
                      show_controls: 'equals true'
                      show_alignment: 'equals true'
                -
                  handle: alignment_horizontal
                  field: common.alignment_horizontal
                  config:
                    width: 50
                    if:
                      show_controls: 'equals true'
                      show_alignment: 'equals true'
                -
                  handle: alignment_vertical
                  field: common.alignment_vertical
                  config:
                    width: 50
                    if:
                      show_controls: 'equals true'
                      show_alignment: 'equals true'
                -
                  handle: show_desktop_alignment
                  field: common.show_controls
                  config:
                    display: 'Show Desktop Alignment'
                    width: 66
                    if:
                      show_controls: 'equals true'
                      show_alignment: 'equals true'
                -
                  handle: enable_desktop_alignment
                  field: common.enable_switch
                  config:
                    display: 'Enable Desktop Alignment'
                    width: 33
                    if:
                      show_controls: 'equals true'
                      show_alignment: 'equals true'
                      show_desktop_alignment: 'equals true'
                -
                  handle: desktop_alignment_horizontal
                  field: common.alignment_horizontal
                  config:
                    width: 50
                    if:
                      show_controls: 'equals true'
                      show_alignment: 'equals true'
                      show_desktop_alignment: 'equals true'
                -
                  handle: desktop_alignment_vertical
                  field: common.alignment_vertical
                  config:
                    width: 50
                    if:
                      show_controls: 'equals true'
                      show_alignment: 'equals true'
                      show_desktop_alignment: 'equals true'
      type: replicator
      display: Slides
      icon: replicator
      localizable: false
      listable: hidden
      instructions_position: above
      visibility: visible
      hide_display: false
      replicator_preview: true

  ```
  
</details>
