### ISSUE TITLE
Duplicate in multisite adds drafts even when the page hasn't been added to the other sites. 

### ISSUE THREAD

**Issue by DanielDarrenJones** [statamic/cms#9008]
### Bug description

When duplicating an entry which is only enabled on certain sites drafts are created for every site, this makes the entry show when you change to the other sites in the collection when it shouldn't.

<img width="1512" alt="Screenshot 2023-11-16 at 15 46 13" src="https://github.com/statamic/cms/assets/8768709/575ae26e-76de-46cc-99fe-a20d0e0590bd">
<img width="1512" alt="Screenshot 2023-11-16 at 15 46 57" src="https://github.com/statamic/cms/assets/8768709/353d5875-af74-4b49-b600-abc273bd7c5e">

### How to reproduce

On a multisite install:

1. Create an entry and leave it as not enabled on some sites
2. Duplicate the Entry
3. The entry will have drafts created for all of the sites (even the ones which aren't enabled)

### Environment

```yaml
Environment
Application Name: Example
Laravel Version: 10.32.1
PHP Version: 8.2.11
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: example.test/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.34.0 PRO

Statamic Addons
doefom/currency-fieldtype: 1.2.2
jacksleight/statamic-bard-texstyle: 3.1.3
ndx/statamic-bard-color-picker: 1.2.0
withcandour/aardvark-seo: 3.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
