### ISSUE TITLE
EntryCollection toArray() causes timeout

### ISSUE THREAD

**Issue by jonathan-bird** [statamic/cms#9012]
### Bug description

Upon upgrading statamic/cms from `4.32.0` to `4.33.0`, I found that all `Statamic::tag('collection:xxx')` code that uses `toArray()` stopped working. It broke on 2 separate Statamic sites upon upgrade.

I found that if I downgrade back to 4.32, it works perfectly. If I change `toArray()` to `all()` it works fine too. Not sure what's changed here.

Example code (note, there's only 6 items in this collection, other collections only have 1 or 2):

```
Statamic::tag('collection:platforms')
    ->sort('order')
    ->fetch()
    ->toArray()
```

I have had to stop my upgrades and keep them at 4.32 for now.

### How to reproduce

1. Create a collection
2. Create 1 test entry
3. Call it the tag via blade and use the toArray() method (see example code above)

### Environment

```yaml
Environment
Application Name: Brisbane South PHN
Laravel Version: 10.32.1
PHP Version: 8.2.11
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: bsphn-statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.1.0

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.35.0 PRO

Statamic Addons
aerni/advanced-seo: 2.3.0
jonassiewertsen/statamic-livewire: 3.0.0
mitydigital/sitemapamic: 2.3.8
mitydigital/statamic-two-factor: 1.1.4
```

### Installation

Existing Laravel app

### Antlers Parser

None
