### ISSUE TITLE
Unexpected behaviour when using range tag with parameter times set to zero

### ISSUE THREAD

**Issue by royvanv** [statamic/cms#9017]
### Bug description

Calling the `Range` tag with the parameter `times="0"` loops from 1 to 0, instead of not looping at all.

### How to reproduce

```antlers
{{ range times="0" }}
    {{ value }}
{{ /range times }}
```

Produces output:
```html
1 0
```

The assumption would be that looping 0 times would produce no output. 

The current behavior only seems logically when using the `to` parameter, in my opinion.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.32.1
PHP Version: 8.2.1
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Locales
Installed
LaravelLang\Attributes\Plugin: 2.5.0
LaravelLang\HttpStatuses\Plugin: 3.6.1
LaravelLang\Lang\Plugin: 13.6.1
Locales Version: 1.9.0
Protected
Publisher Version: 15.0.1

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.35.0 Solo

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.6.3
studio1902/statamic-peak-seo: 7.2.1
studio1902/statamic-peak-tools: 3.4.1
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
