### ISSUE TITLE
Accessing children entries from a Nav

### ISSUE THREAD

**Issue by chopperoon** [statamic/cms#9027]
### Bug description

My Pages Collection contains some entries with children. I have a Nav (Main Nav / `main_nav`) which contains some of the entries from Pages which have children. I want to loop over` nav:main_nav` and use the `children` tag pair to output links to the children. It seems that I have to add all children to the Nav itself in order to get output. I was hoping/expecting that adding just the entries that have children to the Nav would be enough. 

I can certainly add all children manually to the Nav, but this is quite laborious on a multisite with a significant number of children pages. Is this the intended behaviour? Or is there an alternative way to achieve what I'm looking for?

### How to reproduce

1. Add Children entries to a Parent in the default Pages Collection
2. Create a Nav and add the Parent Page
3. Loop over the Nav and try to get the `children `assigned in the Pages Collection

```
{{ nav:main_nav }}
<li>
    <a href="{{ url }}">{{ title }}</a>
    {{ if children }}
        <ul>
            {{ children }}
                <li>
                    <a href="{{ url }}">{{ title }}</a>
                </li>
            {{ /children }}
        </ul>
    {{ /if }}
</li>
{{ /nav:main_nav }}
```

### Environment

```yaml
Environment
Application Name: XXXXXXX
Laravel Version: 10.32.1
PHP Version: 8.2.7
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.35.0 PRO

Statamic Addons
simonridley/tracking-code-manager: 1.0.2
statamic/seo-pro: 5.3.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
