### ISSUE TITLE
Entry field tree view stack UI

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#9043]
### Bug description

The entries field stack now supports the regular list view and the tree view. There's two issues I think are worth discussing

1. Rarely I need the tree view. Should it default to the list view?
2. The hit target in the tree view is just the checkbox, in the list view it is the whole row. Users expect this in the tree view as well. 

<img width="1391" alt="Screenshot 2023-11-21 at 13 48 11" src="https://github.com/statamic/cms/assets/69107412/1cb7269e-7ce8-4ccd-8279-de57cd916f08">

### How to reproduce

Add an entry field that is structured.

### Environment

```yaml
Environment
Laravel Version: 10.32.1
PHP Version: 8.2.10
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Locales
Installed
LaravelLang\Attributes\Plugin: 2.5.0
LaravelLang\HttpStatuses\Plugin: 3.6.1
LaravelLang\Lang\Plugin: 13.6.1
Locales Version: 1.9.0
Protected
Publisher Version: 15.0.2

Livewire
Livewire: v3.2.1

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.36.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.0.0
rias/statamic-color-swatches: 2.2.0
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.7.0
studio1902/statamic-peak-seo: 7.2.1
studio1902/statamic-peak-tools: 3.4.1
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
