### ISSUE TITLE
Button groups should wrap in small containers

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#9044]
### Bug description

Every now and then at certain resolutions I notice the button group fieldtype doesn't wrap, which breaks the layout. This mostly happen in the navigation stack and the live preview sidebar. 

Example where the third item gets cut off and the fourth isn't visible
<img width="1310" alt="Screenshot 2023-11-21 at 14 10 54" src="https://github.com/statamic/cms/assets/69107412/0653e7b2-f8ca-4168-b6e7-67908790f1a9">

### How to reproduce

Add a button group with a bunch of fieldtypes to a blueprint.
Check it in small conditions (live preview)

### Environment

```yaml
Environment
Laravel Version: 10.32.1
PHP Version: 8.2.10
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Locales
Installed
LaravelLang\Attributes\Plugin: 2.5.0
LaravelLang\HttpStatuses\Plugin: 3.6.1
LaravelLang\Lang\Plugin: 13.6.1
Locales Version: 1.9.0
Protected
Publisher Version: 15.0.2

Livewire
Livewire: v3.2.1

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.36.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.0.0
rias/statamic-color-swatches: 2.2.0
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.7.0
studio1902/statamic-peak-seo: 7.2.1
studio1902/statamic-peak-tools: 3.4.1
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
