### ISSUE TITLE
Certain/ all fields statamic character limits are not enforced

### ISSUE THREAD

**Issue by AdD959** [statamic/cms#9067]
### Bug description

Most (if not all) text input fields have a statamic settings field called "Character Limit". After being notified by a user of one of my sites that this rule is not enforced, I can confirm in both v3 and v4 that this rule is not enforced upon page save, at least for basic text input fields. This means a CP user can input as much text as they please with no limits (other than the red warning) and still save the page with an unlimited length string.

See attached screenshots

![image](https://github.com/statamic/cms/assets/35370666/2c9aff3b-ac97-40fe-bb23-02b9eb3f6c7a)
![image](https://github.com/statamic/cms/assets/35370666/cf35d336-864b-4fbf-b269-35ba07fd7ba3)
![image](https://github.com/statamic/cms/assets/35370666/0382dccf-346e-4e10-9e3b-9b43a4cd67eb)

### How to reproduce

in the CP create a text field > assign a character limit > use this field somewhere and go over the character limit > save page. The page should save successfully without any restriction other than the red text warning. The associated markdown file will contain the full-length text input.

### Environment

```yaml
**V3 & V4**

Statamic 3.4.11 Pro
Laravel 8.83.27
PHP 8.2.6
Stache Watcher Enabled
Static Caching Disabled
aryehraber/statamic-impersonator 2.4.1
rias/statamic-button-box 2.0.3
rias/statamic-color-swatches 2.1.9
steadfastcollective/statamic-csv-exporter 2.2.0
withcandour/aardvark-seo 2.0.30



Environment
Application Name: Statamic
Laravel Version: 10.23.1
PHP Version: 8.2.6
Composer Version: 2.6.2
Environment: local
Debug Mode: ENABLED
URL: statamic-generic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.21.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
