### ISSUE TITLE
Date field in replicator preview still looks buggy

### ISSUE THREAD

**Issue by mmodler** [statamic/cms#9088]
### Bug description

I just tested v4.37.0 with improved date fieldtype replicator preview (https://github.com/statamic/cms/pull/9057) and i still see two issues:

![image](https://github.com/statamic/cms/assets/1906217/3becfa77-bc1e-4b92-b1de-a9dc017a9515)

1. Empty date fields show "null" as preview
2. Date preview is not in localized date format

### How to reproduce

1. Create empty date field and check preview
2. Set cp to custom date format, create date fieldtype with a value and check preview 

### Environment

```yaml
Laravel Version: 10.34.2
PHP Version: 8.1.18

Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.37.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
