### ISSUE TITLE
Creating entry in fresh installation throws 404 when redirect to list after

### ISSUE THREAD

**Issue by philippbuerger** [statamic/cms#9090]
### Bug description

In a fresh installation when I try to create an entry in the pages collection, I get an 404. The Entry is created, but I'm not correctly redirected to the collection overview. Staying on the entry after creation works fine.

### How to reproduce

Create a fresh project with Statamic and create an entry in the pages collection.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.34.2
PHP Version: 8.2.13
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: website.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.37.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
