### ISSUE TITLE
Entries fieldtype causing 500 errors

### ISSUE THREAD

**Issue by CjRootStudio** [statamic/cms#9091]
### Bug description

As of v4.37.0, the Entries fieldtype seems to be behaving strangely when using the 'Stack Selector' UI Mode.

When clicking the 'Link Existing Item' link on a Blueprint, everything seems to work as expected apart from the usual 'Cmd+S' shortcut seems to stop working after either selecting an entry or just closing the modal window. Along with this, when editing other pages using the same Blueprint, an occasional 500 error will be displayed. The 500 errors are solved by removing the field from the Blueprint.

This behaviour has been replicated on both existing and freshly created Blueprints (where the Entries fieldtype is the only field).

### How to reproduce

- Create a new Blueprint
- Add just an 'Entries' fieldtype, ensuring the 'Stack Selector' UI Mode is selected
- Link any Collection to the field
- Edit the page and select the 'Link Existing Item' option
- Either select an Entry or close the modal
- Cmd+S shortcut should stop working

### Environment

```yaml
Environment
Application Name: NNAS
Laravel Version: 10.33.0
PHP Version: 8.2.8
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: nnas-core.test/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 8
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.37.0 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.1.0
jacksleight/statamic-bard-texstyle: 3.1.4
jonassiewertsen/statamic-livewire: 2.12.0
rootstudio/cache-primer: 0.9
rootstudio/monitor: 0.2
rootstudio/turnstile: 0.2
statamic/collaboration: 0.7.3
statamic/eloquent-driver: 2.10.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Taxonomies: file
Terms: file
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
