### ISSUE TITLE
Make url and uri available in preview target routes

### ISSUE THREAD

**Issue by NeoIsRecursive** [statamic/cms#9103]
### Bug description

in #8742 many variables where made unavailable, which I think is a good thing, but we used `url` and `uri` in our statamic projects, which broke the preview feature for us. 

### How to reproduce

Make a collection and make a preview target with a url containing `{url}`, it will be empty.

```yaml
preview_targets:
  - label: Entry
    url: "{config:app.preview_url}/api/preview?url={url}"
    refresh: false
```

### Environment

```yaml
Environment
Laravel Version: 10.25.2
PHP Version: 8.2.10
Composer Version: 2.6.4
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.38.0 PRO

Statamic Addons
itiden/statamic-backup: 0.0.7
statamic/collaboration: 0.7.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

We run statamic headless and use the url and uri when getting entries in the frontend and then using it when previewing entries from graphql.

Our preview code (next.js):

```ts
import { NextApiHandler } from 'next';
import { z } from 'zod';

const PreviewQuerySchema = z.object({
  token: z.string().nonempty(),
  url: z.string().nonempty(),
});

const handler: NextApiHandler = (req, res) => {
  const query = PreviewQuerySchema.parse(req.query);

  res.setPreviewData({
    livePreviewToken: query.token,
  });

  res.redirect(query.url);
};

export default handler;
```
