### ISSUE TITLE
Modification to `hide_display` for linked field does not get saved (CP)

### ISSUE THREAD

**Issue by marcorieser** [statamic/cms#9107]
### Bug description

I created a field in a fieldset where `hide_display` is set to `false`. 
```yaml
handle: bg_color
field:
  options:
    dark-grey: 'Dark Grey'
    mid-grey: 'Mid Grey'
    light-grey: 'Light Grey'
  taggable: false
  push_tags: false
  multiple: false
  clearable: false
  searchable: false
  cast_booleans: false
  type: select
  display: 'Background Color'
  icon: select
  localizable: false
  listable: hidden
  instructions_position: above
  visibility: visible
  replicator_preview: true
  hide_display: false
  default: dark-grey
```

I linked that field in a blueprint and set the value for `hide_display` to `true` in the control panel. I expected that the display is not visible now but it still is. 

![Bildschirmfoto 2023-12-02 um 10 00 57](https://github.com/statamic/cms/assets/2395800/76500a9e-5801-4aa8-9c8b-043d4f7e4a23)

Had a look into the `page.yaml`and saw that the value for `hide_display` is missing:
```yaml
display: 'Page Builder'
fields:
  -
    handle: bg_color
    field: common.bg_color
```

However setting the value directly in the yaml as below works as expected:
```yaml
display: 'Page Builder'
fields:
  -
    handle: bg_color
    field: common.bg_color
    config:
      hide_display: true
```
![Bildschirmfoto 2023-12-02 um 10 11 33](https://github.com/statamic/cms/assets/2395800/b4b8d0fb-081b-43d3-976e-53c188cef5d4)

### How to reproduce

- Create a field in a fieldset
- Link the field inside a blueprint and toggle `hide_display` in the CP
- Examine the part for the linked field in the blueprint yaml file

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.34.2
PHP Version: 8.2.13
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: statamic-24-7prayer.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.38.0 PRO

Statamic Addons
marcorieser/statamic-vitals: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
