### ISSUE TITLE
Statamic\Fieldtypes\Link\ArrayableLink::url() shouldn't be private

### ISSUE THREAD

**Issue by FlorianMoser** [statamic/cms#9118]
### Bug description

[Redirects](https://statamic.dev/collections#redirects) produce a fatal error, when `Statamic\Routing\ResolveRedirect` calls `Statamic\Fieldtypes\Link\ArrayableLink::url()`.

### How to reproduce

1. Create a new Statamic installation
2. Edit the pages collection and enable `Entries in this collection may contain links (redirects) to other entries or URLs.`
3. Create a new page using the newly created `Link` blueprint
4. Visit the newly created page

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.34.2
PHP Version: 8.2.3
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: redirect.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.38.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by ryanmitchell** [comment]
I wasn’t able to replicate this on a new install. Can you provide the full stack trace to see if that helps  identify the issue?

**Comment by FlorianMoser** [comment]
Here's the [stack trace](https://flareapp.io/share/oPRZ6BAP).

**Comment by FlorianMoser** [comment]
And here's how the newly `created page /content/collections/pages/test.md` looks like:

```
---
id: df1691ff-d247-49af-a92d-0aeae4f20f42
blueprint: link
title: Test
redirect: 'entry::home'
updated_by: df8e4f29-b9e9-487a-87a1-e6fc4d34e196
updated_at: 1701848893
---
```

And the updated (automatically by Statamic) `created page /content/collections/pages.yaml`:

```
title: Pages
template: default
layout: layout
revisions: false
route: '{parent_uri}/{slug}'
sort_dir: asc
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
structure:
  root: true
```

And `resources/blueprints/collections/pages/link.yaml`, also created by Statamic when enabling the redirect feature:

```
title: Link
tabs:
  main:
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
          -
            handle: redirect
            field:
              type: link
              required: true
```

Besides that, only the `content/trees/collections/pages.yaml` tree has been updated, but the rest remains untouched.

Hope that helps.
