### ISSUE TITLE
Calling `toArray()` on a mounted collection entry causes an infinite loop

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#9119]
### Bug description

If you call the `toArray()` method on a mounted collection's entry it causes an infinite loop.

I think this was introduced in 4.33.0 in https://github.com/statamic/cms/pull/8928, removing that `$data['mount']` line fixes it. 

### How to reproduce

Fetch an entry that belongs to a mounted collection from the entry repository and call `$entry->toArray()`.

### Environment

```yaml
Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.33.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
