### ISSUE TITLE
Tree view for mount is empty

### ISSUE THREAD

**Issue by marcorieser** [statamic/cms#9120]
### Bug description

When trying to define the mount page for eg. the news collection the tree view is empty or broken.
![Bildschirmfoto 2023-12-05 um 11 34 21](https://github.com/statamic/cms/assets/2395800/625754fa-4c33-4236-8b5e-962b814f5594)

### How to reproduce

- Scaffold a new Statamic site
- Create a page "News"
- Create a Collection "News"
- Configure the News Collection
- Click `Link Existing Item` under "Mount"
- Ensure that you are in the tree view

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.34.2
PHP Version: 8.2.13
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: statamic-test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.38.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
