### ISSUE TITLE
Index template not added to mounted page when scaffolding views

### ISSUE THREAD

**Issue by marcorieser** [statamic/cms#9121]
### Bug description

> I think the following worked some time ago but not sure. Happy to open a FR if it was not.

I created a News collection, mounted the collection to the News Entry (pages) and clicked "Scaffold views" for `index` and `show` in the control panel.

This added `template: news/show` successfully to `content/collections/news.yaml` but the `content/collections/pages/news.yaml` is missing `template: news/index`.

### How to reproduce

- Scaffold a new Statamic site
- Create a page "News"
- Create a collection "News"
- Configure the news collection
- Mount the collection to the created "News" page
- Scaffold at least the `index` view for the news collection
- Check the yaml for that news page

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.34.2
PHP Version: 8.2.13
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: statamic-test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.38.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
