### ISSUE TITLE
Grid field to low when using `min_rows` and `max_rows`

### ISSUE THREAD

**Issue by marcorieser** [statamic/cms#9127]
### Bug description

When using a Grid field with `min_rows` and `max_rows` the height of the grey dragging area is too low since the trash icon is not present (I guess).

With `min_rows` and `max_rows`:
![Bildschirmfoto 2023-12-05 um 20 43 11](https://github.com/statamic/cms/assets/2395800/58762840-cfa2-47e3-988e-1c09286d417b)

Just `max_rows`:
![Bildschirmfoto 2023-12-05 um 20 43 06](https://github.com/statamic/cms/assets/2395800/a5d74aad-3503-41bb-9235-7b3ad772e4aa)

### How to reproduce

- Create a new Statamic site
- Create a field of type Grid with `min_rows` and `max_rows` set to `1`
- Render the field in the CP somehow

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.34.2
PHP Version: 8.2.13
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: statamic-24-7prayer.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.38.0 PRO

Statamic Addons
marcorieser/statamic-vitals: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
