### ISSUE TITLE
"You cant do this while logged in" toast after logging in

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#9132]
### Bug description

Sometimes you see the "You cant do this while logged in" toast right after logging into the CP. This was introduced in #9053.

### How to reproduce

I haven't figured out how exactly to trigger it yet, but it shows on the page directly after logging into the CP.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.34.2
PHP Version: 8.3.0
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.x-dev PRO (Just after 4.38.0, 3ce58cad6)
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
