### ISSUE TITLE
Missing "title" key in Fieldtypes.php for the new Group Field Type

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#9140]
### Bug description

Fieldtypes.php translation file is missing a "title" key for the new Group field type added in 4.37.
A key similar to "hidden.title" or "html.title"

### How to reproduce

Display the CP in another language than English, and add a new Group Field Type to a Blueprint. Burst in tears as suddenly "Group" is translated in your own language though you were kindly hopping it would remain untranslated because your great great great grandmother asked for it.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.30.1
PHP Version: 8.2.11
Composer Version: 2.6.5
Environment: local
Debug Mode: OFF
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.38.0 PRO

Statamic Addons
ryanmitchell/statamic-translation-manager: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
