### ISSUE TITLE
Form field in a bard set breaks image field html preview

### ISSUE THREAD

**Issue by mmodler** [statamic/cms#9174]
### Bug description

I have a bard field with various sets. One set has a form field and image field, both with replicator preview enabled. When the form field is altered, the html preview of the image field becomes broken:

![grafik](https://github.com/statamic/cms/assets/1906217/80b25f3d-313f-41d4-9c38-9f24fc761b66)

### How to reproduce

- Create a bard field
- Add a set with a form field and a image field, both with replicator preview true

### Environment

```yaml
Laravel Version: 10.35.0
PHP Version: 8.1.18
Antlers: runtime
Version: 4.39.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
