### ISSUE TITLE
Template field can't handle directories including a dot

### ISSUE THREAD

**Issue by Diewy** [statamic/cms#9177]
### Bug description

When the template directory path includes a dot (.), the system incorrectly truncates the directory path at the dot's position. This results in the display of incorrect files, as the system references a shortened, incorrect path.

E.g. when using Laravel Forge, the project directory is `/home/forge/subdomain.domain.com/`. The template field will try to display all files in `/home/forge/subdomain`.

See: `str_before($file->getPathname(), '.')` in https://github.com/statamic/cms/blob/4.x/src/Http/Controllers/CP/API/TemplatesController.php#L20

### How to reproduce

- Install Statamic in a folder with a .
- Create multiple templates
- Try to select a template

### Environment

```yaml
Environment
Application Name: hidden
Laravel Version: 10.35.0
PHP Version: 8.2.12
Composer Version: 2.6.6
Environment: staging
Debug Mode: OFF
URL: hidden
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.39.0 PRO

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.1.4
statamic/ssg: 2.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
