### ISSUE TITLE
GPX file is converted to XML

### ISSUE THREAD

**Issue by crackAT** [statamic/cms#9182]
### Bug description

When i'm uploading a gpx file in an asset field it will be uploaded/converted as xml.

Is there any setting for it? 
I added gpx extension to additional uploadable extensions in assets config

### How to reproduce

Upload gpx file in an asset field

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 10.35.0
PHP Version: 8.1.13
Composer Version: 2.5.5

Statamic
Addons: 19
Antlers: regex
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.38.0 PRO
```

### Installation

Existing Laravel app

### Antlers Parser

None
