### ISSUE TITLE
Read only icon in revision history is missing

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#9184]
### Bug description

If you have revisions enabled and you open a specific version of an entry in the history, the «read only» icon is missing in the top right.

<img width="1729" alt="Bildschirmfoto 2023-12-12 um 08 22 14" src="https://github.com/statamic/cms/assets/8265902/85764dbd-cbf2-429e-a78b-d55956862419">

### How to reproduce

- Create a revision
- Open a entry in the revision history (restore option) 

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.35.0
PHP Version: 8.2.13
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: v4-test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.40.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
