### ISSUE TITLE
Checkboxes fieldtype in a form adds additional null value

### ISSUE THREAD

**Issue by mmodler** [statamic/cms#9194]
### Bug description

In a form, we have a checkboxes fieldtype with one option. The relevant output of the field in frontend looks like this:

```
<input type="hidden" name="consent[]">
<input type="checkbox" name="consent[]" value="privacy_policy" required>
```

The saved submission data looks like this - expected but unintended in my opinion:

```
consent:
  - null
  - privacy_policy
```

I'm not sure if its better to filter out the null value server side or remove the hidden input.

### How to reproduce

Save a form with a checkboxes fieldtype, check the saved data.

### Environment

```yaml
Laravel Version: 10.35.0
PHP Version: 8.1.18
Antlers: runtime
Version: 4.40.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
