### ISSUE TITLE
Template Select field type listing full path instead of views path 

### ISSUE THREAD

**Issue by khorramMohammadMahdi** [statamic/cms#9196]
### Bug description

Hi everyone, i've installed a branch new statamic v4, it's seems like the Template Select field type is now working correctly, it's listing  files/templates with full path (C:/...) which is obviously wrong
thanks

### How to reproduce

install a new statamic and check out the template select field type

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.37.1
PHP Version: 8.1.6
Composer Version: 2.3.10
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.40.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
