### ISSUE TITLE
Slug sometimes updates after an entry is already published. 

### ISSUE THREAD

**Issue by ncristovao** [statamic/cms#9206]
### Bug description

Current Behavior:

1. Sometimes, after an entry is published, if you update the title (or whatever field the slug is based on), the slug will also update. This causes the previous page to 404 and causes a new URL to be generated. 
2. When creating an entry and saving (but not published), the slug is set. However, if you change the field the slug is based on before publishing, then the slug does not get updated, when it should since the entry is not live.

Expected behavior:

1. The slug should always update to the set field before an entry is published.
4. After the entry has been published, the slug should not update, unless the user clicks the regenerate button.

### How to reproduce

Unfortunately, I can't always re-produce the first error, but the second one happens every time. Save an entry. Reload. Update the title and the slug does not get updated.

### Environment

```yaml
Environment
Laravel Version: 10.28.0
PHP Version: 8.2.8
Composer Version: 2.6.6
Environment: production
Debug Mode: OFF
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: postmark
Queue: sync
Session: database

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.39.0 PRO

Statamic Addons
statamic/eloquent-driver: 2.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
