### ISSUE TITLE
Limited available columns if collection allows links

### ISSUE THREAD

**Issue by wesort** [statamic/cms#9208]
### Bug description

To be able to show/hide and reorder columns in a CP listing for a collection.

### How to reproduce

If a collection has the "Links" settings as `true` (toggled on), authors cannot see all of the "Available columns". 

Perhaps the auto-created `link.yaml` blueprint created for that collection is overriding the existing blueprint? 

![image](https://github.com/statamic/cms/assets/3920126/27908a3f-7ba4-40f6-bc30-d76a41084241)

<details><summary>Screenshot column picker with Links <code>true</code></summary>

![Screenshot 2023-12-14 22 18 22](https://github.com/statamic/cms/assets/3920126/63b78d3f-b7e2-4d84-8dcb-d63d74fa4e82)

</details>

<details><summary>Screenshot column picker with Links <code>false</code></summary>

![Screenshot 2023-12-14 22 17 46](https://github.com/statamic/cms/assets/3920126/4d8f959c-5ec8-405e-80e1-d60b21da5e87)

</details>

### Environment

```yaml
Environment
Application Name
Laravel Version: 9.52.16
PHP Version: 8.1.10
Composer Version: 2.6.6
Environment: production
Debug Mode: ENABLED
URL
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.41.0 Solo
```

### Installation

Existing Laravel app

### Antlers Parser

Runtime (default)
