### ISSUE TITLE
TypeError: this.nextTick is not a function at app-873ac5eb.js:188:74931 on Statamic v4.41

### ISSUE THREAD

**Issue by nfragkos** [statamic/cms#9221]
### Bug description

Getting this js error when saving a collection entry with the continue_editing option after save.

TypeError: this.nextTick is not a function
    at app-873ac5eb.js:188:74931

### How to reproduce

Go to the edit page of an entry, set the continue_editing option after save and click the save button.

### Environment

```yaml
Environment
Application Name: MyApp
Laravel Version: 10.35.0
PHP Version: 8.2.12
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: local.myapp.com
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.41.0 PRO

Statamic Addons
ndx/statamic-bard-color-picker: 1.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
