### ISSUE TITLE
Bard field in live preview is not fixed when scrolling

### ISSUE THREAD

**Issue by kristiana-s** [statamic/cms#9223]
### Bug description

When editing text within a bard field that is the main field on a blueprint, the bard header will scroll in regular entry editing mode but in live preview this doesn't work - in both dual window and pop-out mode.
Bard header should still be sticky in live preview especially since content can be squashed and longer when viewing in dual window mode.

This means you have to scroll back up if you want to format text if you're editing in live preview which can prove a bit frustrating if you have long articles for example.

Actual:  
<img width="604" alt="Screenshot 2023-12-18 at 09 33 12" src="https://github.com/statamic/cms/assets/9308935/70539834-5d5e-4ab8-ab98-646e2be9a5b1">

<img width="589" alt="Screenshot 2023-12-18 at 09 33 29" src="https://github.com/statamic/cms/assets/9308935/77109394-c4dd-4a17-a849-202abeaa51af">

Expected -  live preview bard is sticky like in main editing mode.

<img width="852" alt="Screenshot 2023-12-18 at 10 34 27" src="https://github.com/statamic/cms/assets/9308935/d27d5244-80e2-46d3-9f45-6bfa0142bedd">

### How to reproduce

Create a blueprint with a bard field as the main field. Create an entry and add content with multiple lines so page has to scroll. View the entry in live preview.

### Environment

```yaml
PHP 8.2.5 
Statamic version 4.40

aryehraber/statamic-captcha: 1.10.0
rias/statamic-data-import: dev-master
steadfastcollective/statamic-csv-exporter: 2.2.1
visuellverstehen/statamic-anchor-navigation: 0.3.5-beta
withcandour/aardvark-seo: 3.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
