### ISSUE TITLE
Missing Redirect after new Entry

### ISSUE THREAD

**Issue by crackAT** [statamic/cms#9224]
### Bug description

Since my update to 4.41.0 there is no redirect to the new entry edit url after creating a new entry. 

### How to reproduce

Create a new entry and wait until entry is saved. The url is /collections/article/entries/create/default

### Environment

```yaml
Environment
Laravel Version: 10.37.3
PHP Version: 8.1.25
Composer Version: 2.6.6
Environment: prod
Debug Mode: OFF
URL: www.bergwelten.com
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: database
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Statamic
Addons: 19
Antlers: regex
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.40.0 PRO

Statamic Addons
statamic/eloquent-driver: 2.10.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
```

### Installation

Existing Laravel app

### Antlers Parser

None
