### ISSUE TITLE
Can't set asset field - loads forever - production only

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#9233]
### Bug description

Hi,

A weird one here, I wonder if anyone has any ideas of what's going on...

I can upload assets in the assets section, and I seem to be able to upload assets within an entry too, but the trouble is that the field never gets set - It just loads forever.

I've tried this locally and there is no problem. Both environment uses the same remote filesystem.

I've updated Statamic to the latest, from 4.36.0 to 4.42.0 but the problem remains.

The console error says a request was made to `/cp/assets-fieldtype` but a 404 error was returned.

UPDATE: I can drag and drop files onto the field and everything works fine. Browsing and selecting, or uploading through browse, does not work.

<img width="542" alt="image" src="https://github.com/statamic/cms/assets/20210934/eecbf4b6-aacd-4d1b-a3fa-ced5041da9de">

### How to reproduce

No idea

### Logs

```shell
No relevant details in error logs.
```

### Environment

```yaml
Environment
Laravel Version: 9.52.16
PHP Version: 8.2.13
Composer Version: 2.6.6
Environment: production
Debug Mode: OFF
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single, slack
Mail: smtp
Queue: redis
Session: file

Statamic
Antlers: regex
Stache Watcher: Disabled
Static Caching: half
Version: 4.42.0 PRO

Statamic Addons
jonassiewertsen/statamic-live-search: 1.7.0
jonassiewertsen/statamic-livewire: 2.12.0
rias/statamic-redirect: 2.x-dev
spatie/statamic-responsive-images: 4.1.1
statamic/seo-pro: 5.3.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
