### ISSUE TITLE
Improve validate unique uri's in CollectionTreeController

### ISSUE THREAD

**Issue by juliawarnke** [statamic/cms#9236]
### Bug description

I have a project with almost two thousand entries in my pages collection and an associated collection tree wich is eleven levels deep. When the CollectionTree is saved the validation process of checking for duplicate uri's slows down the request massively. Even a max execution time of 240 seconds is sometimes not enough to prevent the control panel from crashing.

### How to reproduce

1. Create a pages collection
2. Activate the collection tree
3. Create a lot of entries. I used Entry::make() for it.
4. Enter the CollectionTree and move the entries around with multiple levels.
5. Save the CollectionTree
6. Repeat step 4. and 5.

### Environment

```yaml
Environment
Laravel Version: 10.33.0
PHP Version: 8.2.13
Composer Version: 2.6.2
Environment: production
Debug Mode: OFF
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: redis
Database: mysql
Logs: stack / daily, slack
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Disabled
Static Caching: half
Version: 4.36.0 PRO

Statamic Addons
elvenstar/statamic-meilisearch: 2.0.1
visuellverstehen/statamic-anchor-navigation: 0.3.6-beta
visuellverstehen/statamic-classify: 2.6.1
visuellverstehen/statamic-content-renderer: 0.1.1-beta
visuellverstehen/statamic-glossary-tooltips: dev-main
visuellverstehen/statamic-picturesque: 1.3.0
visuellverstehen/statamic-pixxio-flysystem: dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

We did a little digging and discovered that the `validateUniqueUri` method probably does a lot of unnecessary work in order to compare all uri's for uniqueness. For every entry a pages object is created which holds the entire collection tree and a lot more in order to compare parents and child entries afterwards. It seems like a lot for this purpose.

Besides putting `Statamic\Entries\UpdateStructuredEntryUris` and `Statamic\Entries\UpdateStructuredEntryOrder` in the queue in order to increase the performance, we found another quick fix that worked pretty well for us. We resolved the uri for each entry by accessing a new search index that holds all slugs. We then search for duplicate uri's.

We've replaced the CollectionTreeController with our own and overwritten the `validateUniqueUri` method with the following:

```
private function validateUniqueUris($tree)
{
    if (! $tree->collection()->route($tree->locale())) {
        return;
    }

    if (! $index = Search::index("pages_slugs")?->raw()) {
        // whatever needs to be done.
    }
        
    $this->pageSlugsIndex = json_decode($index, true);
    $pathsArray = $this->populatePathsArray($tree->tree());
    $uniquePathsArray = array_unique($pathsArray);
    $duplicatePaths = array_diff_key($pathsArray, $uniquePathsArray);
    
    if (! empty($duplicatePaths)) {
        $uri = preg_replace('/^\//', '', array_shift($duplicatePaths));
        throw ValidationException::withMessages(['uri' => trans('statamic::validation.duplicate_uri', ['value' => $uri])]);
    }
}

private function populatePathsArray(array $entries, $path = '')
{
    $paths = [];
    foreach ($entries as $entry) {
        $slug = $this->pageSlugsIndex["entry::{$entry['entry']}"]['slug'] ?? null;
        // Unpublished entries are not part of the index, and as they are nothing that is linked to, we can ignore them.
        if (! $slug) {
            continue;
        }

        if ($path === '') {
            $paths[] = $slug;
        } else {
            $paths[] = $path . '/' . $slug;
        }

        if (isset($entry['children'])) {
            $paths = array_merge($paths, $this->populatePathsArray($entry['children'], $path . '/' . $slug));
        }
    }

    return $paths;
}
```

Of course this code only works for our needs. But maybe this could be a starting point to improve this part of the core.
