### ISSUE TITLE
Mobile issues

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#9237]
### Bug description

Besides thee [tree view issue](https://github.com/statamic/cms/issues/7919) I discovered some more visual issues when visiting the CP on mobile.

**Overflow on fieldsets table with long titles**
![IMG_0365](https://github.com/statamic/cms/assets/69107412/0328ee78-ebee-4d23-bf84-c0a1ed811c8a)

**Within fields you can't scroll this panel**
![IMG_0366](https://github.com/statamic/cms/assets/69107412/06b5c5a4-201f-435b-a37b-8a7c0d914b4d)

### How to reproduce

Install peak
Go to fieldset on mobile for issue 1
Click on a fieldset and open a field for issue 2 (try to scroll down, you can't replicate this on desktop, has to be a mobile device)

### Environment

```yaml
Environment
Application Name: Statamic Peak Development
Laravel Version: 10.38.0
PHP Version: 8.3.0
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.42.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.3.3
studio1902/statamic-peak-commands: 3.1.0
studio1902/statamic-peak-seo: 7.5.0
studio1902/statamic-peak-tools: 4.1.0
```

### Installation

Starter Kit using via CLI

### Antlers Parser

Runtime (default)
