### ISSUE TITLE
Link fieldtype doesn't work properly within nested Replicator/Grid combination

### ISSUE THREAD

**Issue by morhi** [statamic/cms#9238]
### Bug description

It seems like the Link fieldtype stopped working properly from 4.41.0. For instance, when you select "URL" in a Link field, that is placed within a Bard set within a Replicator set, it will reset, as soon as you start typing or change anything else in the content. Downgrading to 4.40.0 fixes the issue. 

May be related to #9203, maybe not :) 

### How to reproduce

https://github.com/statamic/cms/assets/12037294/5512fa0e-b473-4f81-a938-fff9e6cf0bbb

### Environment

```yaml
Statamic
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.42.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
