### ISSUE TITLE
EntrySaved event is triggered twice

### ISSUE THREAD

**Issue by christophstockinger** [statamic/cms#9245]
### Bug description

I have developed a private addon for one of our websites and noticed that the EntrySaved event is triggered twice.

This means that listeners that listen to the event are also executed twice. But this should not happen! Especially if third-party systems etc. are still influenced by this.

### How to reproduce

You can easily reproduce this: Just register a Laravel event listener on the event and then write a log to the handle() method.

Alternatively, you can also reproduce the duplicate event via Telescope.

### Environment

```yaml
Environment
Application Name: Konkav & K16
Laravel Version: 10.39.0
PHP Version: 8.2.14
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: k16-konkav-cms.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 8
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.42.0 PRO

Statamic Addons
aryehraber/statamic-uuid: 2.2.0
jonassiewertsen/statamic-documentation: 1.9.0
morethingsdigital/personio: dev-main
morethingsdigital/statamic-nextjs: dev-main
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 2.7.0
studio1902/statamic-peak-seo: 5.0
studio1902/statamic-peak-tools: 3.4.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

Possibly the reason:
After initial research, I was able to trace it back to the CollectionTree being updated/saved after the entry was updated/saved. However, the CollectionTree then saves the entry again and this leads to the second event.

I think that saving the entry in the CollectionTree should take place unnoticed.
