### ISSUE TITLE
Rendering S3 avatar doesn't work

### ISSUE THREAD

**Issue by robfrancken** [statamic/cms#9246]
### Bug description

I have configured an S3 bucket for assets.

I am able to upload assets (i.e. for an article) without issue.

When I attempt to output the author's avatar, I get an invalid src url.

### How to reproduce

Create an S3 bucket with ACL's to allow public read access.

Upload an author avatar.

Render the avatar.

```html
{{ author }}
<img class="h-12 rounded-full" src="{{ avatar }}" alt="{{ name }}'s Profile Picture">
{{ /author }}
```
Viewing the source code appears as below.

```html
<img class="h-12 rounded-full" src="assets::author.jpg" alt="Author Name's Profile Picture">
```

### Logs

```shell
No errors in log file.
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.37.3
PHP Version: 8.1.26
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.41.0 Solo

Statamic Addons
pecotamic/sitemap: 1.4.6
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
