### ISSUE TITLE
Slow page loading time with too much Replicator (due to preview, enabled or disabled).

### ISSUE THREAD

**Issue by benoitdelorme** [statamic/cms#9248]
### Bug description

I have more than 50 replicator items in a page and they are each composed of ~10 fields.
Loading my page and fields takes more than 2 minutes with or without replicator preview enabled. 

### How to reproduce

- Create a Replicator field 
- Add ~10 fields inside Replicator (text, image, video etc...). 
- Assign the replicator to a page. 
- Add more than 50 replicator items with content

Examples: 
https://github.com/statamic/cms/assets/561485/2b1fd388-6790-4107-921b-b7dc322f114c

### Environment

```yaml
Environment
Application Name: laravel
Laravel Version: 10.35.0
PHP Version: 8.2.11
Composer Version: 2.5.5
Environment: local
Debug Mode: OFF
URL: raynault-vfx.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.38.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)

### Additional details

I know the problem is the preview function because I make changes in my local Statamic and rebuild it to fix issues.

In `statamic/cms/resources/js/components/fieldtypes/replicator/SET.vue`

A good start would be to modify the previewUpdated function to not emit `preview-updated` if `this.showFieldPreviews` is `false`.

```
previewUpdated(handle, value) {
     if(!this.showFieldPreviews) return; // add this line
     this.$emit('previews-updated', this.fieldPreviews = { ...this.fieldPreviews, [handle]: value });
},
```

I can open a PR to address this first bug but the problem still exists if preview is enabled.
