### ISSUE TITLE
Error Uploading Assets on 3.3

### ISSUE THREAD

**Issue by cwyrwas** [statamic/cms#9251]
### Bug description

![image (7)](https://github.com/statamic/cms/assets/82904380/6d91131b-3ab5-41ae-87ee-6a0b61eea55d)

Hi folks,
I've got a bit of a strange one, and I'm hoping that someone can provide a bit of clarity on what may be causing this.

I'm getting reports by some of our admin users that they are unable to upload images in the control panel. On the server, the Max File Upload Size is set to 500MB, and this particular image was only 869kb. We have multiple asset containers, one of which is direct on the server, and we also have a container configured with S3. Regardless of the container (whether it's directly on the server or on S3), they still receive the error in the image upon uploading. I have of course had them clear their cache and follow basic debugging practices, and they have encountered this error on multiple devices (although the devices are on the same network since they're located at an office). I have yet to trigger the error on my end, but we've had multiple reports from them. Is there anything that may be causing this? Just trying to rule out all possibilities as to what the issue might be.

We've been running this app in production for around 15 months with no issues, and it seems this has started to occur out of nowhere.

Thank you for all of your help.

### How to reproduce

Strangely enough, I am unable to reproduce on my end, but they can all replicate it on their network.

### Environment

```yaml
This issue triggers on both dev and prod, but here are the details from my local environment.

Environment
Application Name: Strategies
Laravel Version: 9.26.1
PHP Version: 8.1.6
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: ses
Queue: sync
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: full
Version: 3.3.64 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.0
cnj/seotamic: 2.1.0
doublethreedigital/duplicator: 2.3.2
jacksleight/statamic-bard-mutator: 1.1.2
jonassiewertsen/statamic-livewire: 2.9.0
optimoapps/statamic-bard-text-align: 1.0.2
visuellverstehen/statamic-classify: 2.4.0
```

### Installation

Existing Laravel app

### Antlers Parser

Runtime (default)
