### ISSUE TITLE
Replicator sets don't show on continue edit

### ISSUE THREAD

**Issue by danpkw** [statamic/cms#9262]
### Bug description

I have an entry with a replicator field, which has several sets. When I click 'Save & Publish' with the option set to 'Continue Editing' the page saves, but then only shows the 1st set of the replicator.

Refreshing the page then shows all sets again.

### How to reproduce

1. Create a fieldset with replicator field with 2 or more sets
2. Assign the fieldset to the `Page` blueprint.
3. Create a new entry under the `Pages` collection.
4. Add the replicator fieldset with 2 or more sets to the entry.
5. Save the entry
6. Go back into the entry, change the `After Saving` option to `Continue Editing`.
7. Resave the entry 

### Logs

```shell
app-dba30c62.js:5 TypeError: Cannot read properties of undefined (reading 'id')
    at app-dba30c62.js:414:21345
    at q.renderList [as _l] (app-dba30c62.js:5:17690)
    at q.M (app-dba30c62.js:414:21132)
    at M._render (app-dba30c62.js:5:24987)
    at q.N (app-dba30c62.js:5:29723)
    at M.get (app-dba30c62.js:5:42279)
    at M (app-dba30c62.js:5:42188)
    at mountComponent (app-dba30c62.js:5:29824)
    at Vue$3.$mount (app-dba30c62.js:5:102964)
    at Vue$3.$mount (app-dba30c62.js:9:800)
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.30.1
PHP Version: 8.1.23
Composer Version: 2.6.2
Environment: local
Debug Mode: ENABLED
URL: ---
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.42.1 Solo

Statamic Addons
anakadote/statamic-recaptcha: 1.0.9
gerttimmerman/statamic-zapier: 1.5
statamic/seo-pro: 5.4.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
