### ISSUE TITLE
Update to Statamic 4.42.1 seems to break "Update All" button in "Utilities -> Search"

### ISSUE THREAD

**Issue by mel-discepola** [statamic/cms#9267]
### Bug description

After updating to Statamic 4.42.1 (or doing a fresh install of 4.42.1), the "Update All" button in "Utilities -> Search" of the cp, returns the following error "Undefined array key 1".

### How to reproduce

- Using Statamic 4.42.1, login to the cp
- Via the GUI, go to Utilities in the left menu, then choose Search
- Click the blue "Update All" button at the top of the table 

### Environment

```yaml
Environment
Laravel Version: 10.32.1
PHP Version: 8.2.12
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: mysite.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.42.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
