### ISSUE TITLE
Children tag not working when specifying multisite url

### ISSUE THREAD

**Issue by MedRochon** [statamic/cms#9279]
### Bug description

When you specify the url of your multi-site, the children tag doesn't work in other sites.

### How to reproduce

Create a multi-site and specify the URL like that `'url' => env('APP_URL') .'/',`

Create a collection with parents-children relation for the 2 sites.

Use the {{ children }} tag to output the title.

Work with the default site, but not the second one.

Config :
```
'sites' => [
        'fr' => [
            'name' => 'Francais',
            'locale' => 'fr_CA',
            'url' => env('APP_URL') . '/',
        ],
        'en' => [
            'name' => 'English',
            'locale' => 'en_US',
            'url' => env('APP_URL') . '/en/',
        ],
    ],
```
    
default.antlers.html
```
{{ children }}
    {{ title }}
{{ /children }}
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.37.3
PHP Version: 8.2.13
Composer Version: 2.6.6
Environment: local
Debug Mode: ENABLED
URL: sandbox.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.x-dev PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
