### ISSUE TITLE
Creating a new entry in a collection and saving the page redirects to a url containing "undefined" and getting a 404

### ISSUE THREAD

**Issue by Utibu** [statamic/cms#9283]
### Bug description

After updating our site to >4.38 we seem to have a bug when creating a new entry, independent of which collection we're using. Cannot find any reports of this bug here in the issues either.

The bug is behaving like this:

After I've filled filled in some content/title for a non-existing entry, I press save. What used to happen is that I got redirected to the entry and could continue editing it, but what instead happens now is that I get redirected to a URL containing "undefined", and I see a error message "Page Not Found".

### How to reproduce

1. Press on the collection (pages for example)
2. Create a new entry
3. Type in a title and click save
4. The URL should now be like _cp/collections/pages/entries/create/undefined?created=true_ and a "Page Not Found" should show.

### Environment

```yaml
Application Name: Laravel
Laravel Version: 10.40.0
PHP Version: 8.2.11
Composer Version: -
Environment: local
Debug Mode: ENABLED
URL: laravel.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / bugsnag
Mail: smtp
Queue: database
Session: file

Locales
Installed
LaravelLang\Actions\Plugin: 1.4.1
LaravelLang\Attributes\Plugin: 2.9.1
LaravelLang\HttpStatuses\Plugin: 3.8.0
LaravelLang\Lang\Plugin: 13.12.0
Locales Version: 1.9.0
Protected
Publisher Version: 15.0.2

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.42.1 PRO

Statamic Addons
mitydigital/statamic-two-factor: 1.1.4
statamic/eloquent-driver: 2.10.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: file
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
```

### Installation

Existing Laravel app

### Antlers Parser

None
