### ISSUE TITLE
Dirty State after Save

### ISSUE THREAD

**Issue by AntonCooper** [statamic/cms#9294]
### Bug description

https://github.com/statamic/cms/assets/11951114/006afda0-6eec-4be5-bef6-4da004d250f4

We've having issues with the publish button being disabled due to a form dirty state after clicking save. This happens mainly on larger more complex pieces of content. Having the Vue devtools open exacerbates the problem, but it occurs every time there's a slight delay after clicking save.

The PR which introduced this problem;
https://github.com/statamic/cms/pull/9213

Maybe related;
https://github.com/statamic/cms/issues/9248

### How to reproduce

- Enable revisions
- Create a bard field with a set which contains another bard field
- Create entry with multiple instances of these sets (10+)
  -  The more complex the bard field, the more likely this issue is to occur
- Save and Publish
- Update a Bard field within one of the sets
- Click Save
- Observe a delay in saving, and a dirty state of the form after, preventing publishing.  

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.40.0
PHP Version: 8.2.8
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: statamic-demo.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.43.0 PRO
```
```


### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

_No response_

**Comment by duncanmcclean** [comment]
I've tried to re-create your setup from what I can see in the video but I'm struggling to reproduce this issue:

![CleanShot 2024-01-10 at 12 42 46](https://github.com/statamic/cms/assets/19637309/272d9675-702e-4899-891f-bfe382a103a9)

Can you provide the blueprint you're using for the entry in the video?

**Comment by AntonCooper** [comment]
It requires more than three sets to trigger this issue. The more sets you add the more likely I've found the problem to occur. In prod we have articles with 50+ sets which have bard fields in and it almost always happens. Having Vue dev tools open also help with getting the problem to happen. Below is an example fieldset I used in my initial report
```
title: 'Product Quote'
fields:
  -
    handle: product_name
    field:
      input_type: text
      antlers: false
      type: text
      display: 'Product Name'
      icon: text
      listable: hidden
      instructions_position: above
      visibility: visible
      hide_display: false
  -
    handle: brand
    field:
      input_type: text
      antlers: false
      type: text
      display: Brand
      icon: text
      width: 50
      listable: hidden
      instructions_position: above
      visibility: visible
      hide_display: false
  -
    handle: domain
    field:
      input_type: text
      antlers: false
      type: text
      display: Domain
      icon: text
      width: 50
      listable: hidden
      instructions_position: above
      visibility: visible
      hide_display: false
  -
    handle: quote
    field:
      buttons:
        - bold
        - italic
        - unorderedlist
        - orderedlist
        - removeformat
        - quote
        - anchor
        - bts_attributes
      smart_typography: false
      save_html: false
      inline: false
      toolbar_mode: fixed
      reading_time: false
      fullscreen: true
      allow_source: true
      enable_input_rules: true
      enable_paste_rules: true
      remove_empty_nodes: false
      antlers: false
      link_noopener: false
      link_noreferrer: false
      target_blank: false
      always_show_set_button: false
      collapse: false
      previews: true
      bts_styles_button: icon
      type: bard
      display: Quote
      icon: bard
      listable: hidden
      instructions_position: above
      visibility: visible
      hide_display: false
  -
    handle: quote_source
    field:
      input_type: text
      antlers: false
      type: text
      display: 'Quote Source'
      icon: text
      instructions: 'Usually the username if quoting a Talk post.'
      listable: hidden
      instructions_position: below
      visibility: visible
      hide_display: false
  -
    handle: quote_link
    field:
      type: section
      display: 'Quote Link'
      icon: section
      listable: hidden
      instructions_position: above
      visibility: visible
      hide_display: false
  -
    handle: button
    field:
      type: section
      display: Button
      icon: section
      instructions: 'The details for the CTA button. Usually "Buy now"'
      listable: hidden
      instructions_position: above
      visibility: visible
      hide_display: false
```
