### ISSUE TITLE
CP hangs when using the asset field (sometimes)

### ISSUE THREAD

**Issue by DanielDarrenJones** [statamic/cms#9299]
### Bug description

We have been getting an occasional issue on the control panel while uploading content to a new site where the control panel will just hang on the loading bar as shown below:
<img width="1439" alt="Screenshot 2024-01-10 at 14 04 18 (1)" src="https://github.com/statamic/cms/assets/8768709/c1bd855c-b8d2-4192-aa97-ba7b32812a47">
https://youtu.be/nwOplVv7prY

This appears to lead on to the following error on Chrome (reported by our clients team):
![image001](https://github.com/statamic/cms/assets/8768709/cc50df33-a8a9-481a-88a0-7a875a4a18a3)

And this on Safari:
<img width="1466" alt="image002" src="https://github.com/statamic/cms/assets/8768709/e5db5044-130e-4828-8d10-e88e75f56b9a">

This happens when selecting an image through the asset field. No errors are thrown in the backend logs, or in the browser logs from looking.

The team have also reported an issue when uploading images that it can become duplicated, but I'm not sure if this is at all connected, they have sent me a screenshot of one which became duplicated but can't be deleted:

### How to reproduce

Unable to consistantly reproduce, but the client has provided the following video showing the steps they take to upload and select an asset: https://youtu.be/sD7vl1bMLwg (I'm not sure why they are uploading in a separate tab).

Images are stored on S3 not locally.

### Environment

```yaml
Environment
Application Name: Pelorus
Laravel Version: 10.39.0
PHP Version: 8.2.12
Composer Version: 2.6.6
Environment: production
Debug Mode: OFF
URL: pelorus-travel.strattons.com/
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: redis

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.42.0 PRO

Statamic Addons
doefom/currency-fieldtype: 1.2.3
gerttimmerman/statamic-zapier: 1.5
jacksleight/statamic-bard-texstyle: 3.1.4
ndx/statamic-bard-color-picker: 1.2.0
ryanmitchell/statamic-translation-manager: 1.2.2
withcandour/aardvark-seo: 3.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)

### Additional details

Please let me know if there is any more info I can collect from the server or browser that would be helpful in solving this, it's causing a lot of problems with the client having to re-do work when they have to reload the page.
