### ISSUE TITLE
Route::get('/{category:slug}/{product:slug}

### ISSUE THREAD

**Issue by dijkr** [statamic/cms#9310]
### Bug description

This route should apply to the product table, but all /cms routes, wit the second segment after /cms, are applied to this route. I can partly solve this by adding this route before the route from the title:
`Route::get('/cms/collections', 'StatamicController@collections');`
`Route::get('/cms/assets','AssetsController@index');`
Because more routes are involved, pages won't load their content. 
I need the first part to load content from a collection, using `{{ collection:categorieen :slug:is="segment_1" }}`
Route::get('/product/{product:slug} solves the problem, but then the segment doesn't match a category.

### How to reproduce

Create a route with the first and second segment like this:
`Route::get('/{product:category}/{product:slug}`

### Environment

```yaml
Environment
Application Name: x
Laravel Version: 9.52.7
PHP Version: 8.0.30
Composer Version: 2.6.6
Environment: local
Debug Mode: ENABLED
URL: 192.168.0.20:8000
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.18.0 Solo
```
```


### Installation

Existing Laravel app

### Antlers Parser

Runtime (default)

### Additional details

_No response_
