### ISSUE TITLE
GCP bucket upload image failed

### ISSUE THREAD

**Issue by slin1233** [statamic/cms#9311]
### Bug description

I am trying to use GCP Bucket to connect to my asset. I was able to implement it, Currently it able to Upload folder, Delete Folder and Delete Pictures but It not uploading picture, When I tried to Upload the image it says it uploaded but it never upload to my gcs bucket or control panel. The preview URI is also Error Not Found When I try uploading which a local driver it works out but not with GCS Buckets.
![image](https://github.com/statamic/cms/assets/156369394/6340b4d4-ffaa-444a-b4bc-cff5518b8397)
![image](https://github.com/statamic/cms/assets/156369394/718c2d5b-08fa-451a-ac05-4811cca0781d)

### How to reproduce

When I tried to Upload the image it says it uploaded but it never upload to my gcs bucket or control panel. The preview URI is also Error Not Found When I try uploading which a local driver it works out but not with GCS Buckets.

Here is my filesystem setup I tried with and without the storage api uri
![image](https://github.com/statamic/cms/assets/156369394/d99d395e-adfb-4472-ab7f-1a311b7c71b2)

This is my Image.yaml

![image](https://github.com/statamic/cms/assets/156369394/0331b852-359e-4210-af9c-d7128fa2a48c)

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 9.52.16
PHP Version: 8.3.0
Composer Version: 2.6.6
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: pgsql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.42.1 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
