### ISSUE TITLE
Taxonomy route entries tag showing unpublished entries

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#9312]
### Bug description

The {{ entries }} tag lists unpublished entries that are tagged with the taxonomy term. Have needed to add a condition to remove the unpublished entries from the loop:

```
{{ entries 
        sort="date:desc"
        limit="30"
        paginate="true"
        on_each_side="1"
        status:in="published"
        as="articles" }}
```

### How to reproduce

- Create taxonomy term view (/categories/show.antlers.html)
- Add {{ entries }} tag to loop through tagged entries
- Unpublish tagged entry
- See unpublished entry

### Environment

```yaml
Environment
Application Name: Burlingame
Laravel Version: 9.52.16
PHP Version: 8.2.14
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: burlingame.test
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 17
Antlers: runtime
Stache Watcher: Disabled
Static Caching: half
Version: 4.44.0 PRO

Statamic Addons
aerni/advanced-seo: 2.3.0
aerni/livewire-forms: 8.1.0
aerni/social-links: 3.1.0
aerni/zipper: 2.3.0
duncanmcclean/static-cache-manager: 3.1.2
edalzell/forma: 2.1
jacksleight/statamic-bard-texstyle: 3.1.3
jacksleight/statamic-miniset: 1.0.0
jonassiewertsen/statamic-livewire: 2.12.0
justbetter/statamic-image-optimize: 2.1.1
mikemartin/helpscout-beacon: 1.0.3
mitydigital/statamic-logger: dev-main
rias/statamic-color-swatches: 2.2.0
rias/statamic-redirect: 3.2.0
siterig/mailerlite: dev-main
swiftmade/statamic-clear-assets: 2.0.0
webographen/statamic-widget-continue-editing: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Yes
