### ISSUE TITLE
Confusing multi-site UX

### ISSUE THREAD

**Issue by aerni** [statamic/cms#9319]
### Bug description

While not technically a bug, it still feels like one from a UX perspective. 

In a multi-site setup, a collection is visible even when it isn't configured for the selected site. A user only knows that the collection isn't available when the error pops up when clicking on the collection. I believe it would be much better if unavailable collections would not be shown in the first place. This should be a pretty simple fix. Happy to PR.

In the example below, the `articles` collection isn't configured for the `german` site. 

![CleanShot 2024-01-12 at 17 58 07@2x](https://github.com/statamic/cms/assets/23167701/d5d0a143-e402-403f-bf66-9377e8884f07)

### How to reproduce

1. Create multiple sites
2. Create a collection and only configure it for one site
3. Select a site the collection isn't configured for
4. Click on the collection

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.16
PHP Version: 8.2.14
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: statamic-advanced-seo.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.44.0 PRO

Statamic Addons
aerni/advanced-seo: dev-fix/multisite
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
