### ISSUE TITLE
Test mail not working

### ISSUE THREAD

**Issue by de-raaf-media** [statamic/cms#9328]
### Bug description

In the control panel in Utilities / email I tried to send a test email but nothing happened.

### How to reproduce

In the control panel in Utilities / email click on "Send Test Email"

### Environment

```yaml
Environment (removed privacy data)
Application Name: ***
Laravel Version: 10.34.2
PHP Version: 8.1.26
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: ***.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: database
Session: file

Simple Commerce
Currencies: EUR
Gateways: Dummy
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\UserCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Default shipping
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.32.0 PRO

Statamic Addons
aerni/factory: 1.4.0
doublethreedigital/simple-commerce: 5.6.2
statamic/eloquent-driver: 2.10.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Taxonomies: file
Terms: file
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)

### Additional details

In below example I temporary modified the EmailController.php. Only the raw email is successfully sent:

```
        Mail::raw('Hello from Statamic CP', function ($message) use($request) {
            $message->to($request->email)->subject('Welcome');
            $message->from('from@example.com', 'Your Application from CP');
        });

        Mail::to($request->email)->send(new Test);

        return back()->withSuccess(__('Test email sent.'));
```
