### ISSUE TITLE
Bard floating menu popovers snap to top left in Safari

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#9330]
### Bug description

When you have the floating menu enabled and open the bard link popover the menu closes and the popover snaps to the top left in Safari (16.4):

https://github.com/statamic/cms/assets/126740/c93d1f68-babf-4c1d-b2e9-8b136bfdcab3

Works fine in Chrome.

### How to reproduce

Create a bard field with the floating menu and open the link popup.

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.43.0 Solo

Browser: Safari 16.4
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
