### ISSUE TITLE
Collection crashes after reorderdering with views filter

### ISSUE THREAD

**Issue by hanneshoepfnerio** [statamic/cms#9331]
### Bug description

Finde description here
https://github.com/statamic/cms/discussions/9304#discussioncomment-8133484

### How to reproduce

In a collection in the backend, setup a "filtered view on a field" and save it.
Reorder collection elements. When in reorder mode select the previous created "view filter".
Reorder. Issue.

### Logs

```shell
array_flip(): Can only flip string and integer values, entry skipped
Users/username/Documents/Projekte/Detect/website/detectclassic/vendor/laravel/framework/src/Illuminate/Collections/Collection.php#425
ErrorException
     */
    public function flip()
    {
        return new static(array_flip($this->items));
    }

    /**
```

### Environment

```yaml
Environment
Application Name:
Laravel Version: 10.40.0
PHP Version: 8.2.12
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: website.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.44.0 PRO

Statamic Addons
example/my-addon: dev-test/structure
stillat/relationships: 2.1.3
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 4.0.0
studio1902/statamic-peak-seo: 8.0.0
studio1902/statamic-peak-tools: 4.2.0
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
