### ISSUE TITLE
Link field is emptied when adding a new replicator and selecting an image

### ISSUE THREAD

**Issue by DanielDarrenJones** [statamic/cms#9335]
### Bug description

When using a link field within a replicator we have come across this minor issue where when we link a destination and then move on to the next block, the link disappears. 

When we then go into the live preview the link is still there it just isn’t showing up on the back end. 

We have recorded a video of the bug here: https://youtu.be/7C2NUaA3Dcg

### How to reproduce

Create a link field within a replicator and also an asset field, set the link field to link to an entry, add a new replicator below and brown for an asset and it should clear the link field.

### Environment

```yaml
Environment
Application Name: Pelorus
Laravel Version: 10.40.0
PHP Version: 8.2.12
Composer Version: 2.6.6
Environment: production
Debug Mode: OFF
URL: [redacted]
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: redis

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.44.0 PRO

Statamic Addons
doefom/currency-fieldtype: 1.2.3
gerttimmerman/statamic-zapier: 1.5
jacksleight/statamic-bard-texstyle: 3.1.4
ndx/statamic-bard-color-picker: 1.2.0
ryanmitchell/statamic-translation-manager: 1.3.0
withcandour/aardvark-seo: 3.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
