### ISSUE TITLE
Go to listing on «Save & Publish» Button not working 

### ISSUE THREAD

**Issue by stefankempf** [statamic/cms#9342]
### Bug description

When choosing `go to listing` on the `save & publish` button, the page is simply getting refreshed and not redirected to the listing.

### How to reproduce

![CleanShot 2024-01-17 at 15 01 00](https://github.com/statamic/cms/assets/20299885/28fbf4b2-ce03-4251-b4e9-4a87beb0985d)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.41.0
PHP Version: 8.3.0
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: kbi.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.3.5

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.44.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
