### ISSUE TITLE
Chrome Out Of Memory Issue

### ISSUE THREAD

**Issue by DanielDarrenJones** [statamic/cms#9351]
### Bug description

We have had a report from one of our clients about an out-of-memory crash in Chrome when editing entries, we have been having other issues with crashes See (https://github.com/statamic/cms/issues/9299), but this seems to potentially be a separate issue after talking to @duncanmcclean. Below is the report from the one of our clients team with the context of the conversation being a continuation of trying to track down the cause of the crashes we reported previously:

It could have something to do with how much memory Statamic is using up when actively using it. I have two tabs open, the one I have actually been editing on is using 2.1 GB of memory usage, which seems like a huge amount. The next lowest is Canva at 650MB 9the document I have open is 275 tabs of images, the max number of tabs you can have is 300), and all other tabs are between 200MB-30MB.

![image](https://github.com/statamic/cms/assets/8768709/37403a5b-3e60-4621-ba2d-ad713bac70be)

For reference, all I have done on this page so far is:
Change page title
Change page thumbnail
Edit Body Block – update hero image from asset library and change word Indonesia to Papua New Guinea. 
Edit Breadcrumbs, changing text, and amending one link
Editing some text in the intro body block
 
It is a very lean page compared to some, so for it be using such a high memory seems concerning and could be the root of the issue on both Chrome & Safari. 
 
My Chrome crashed yesterday, but I didn’t have time to capture everything before it refreshed which is why I didn’t send it over, however I did manage to capture this on the web dev tools:

![image](https://github.com/statamic/cms/assets/8768709/3ff90906-77c4-495f-a18c-54d4d91e2dc1)

I checked my memory of all my Google Accounts I am logged into on this device, all accounts have way over 10GB of memory left so it wouldn’t be that slowing down. 
 
Here is the other Statamic’s tab memory usage, one that I had not made any edits on.

![image](https://github.com/statamic/cms/assets/8768709/e8dffcac-d9d1-40bc-abe8-edf1a0fc346b)

### How to reproduce

I haven't been able to reproduce this reliably, the client has been using two tabs, one with the asset page on to upload and manage assets, and another to create/duplicate as well as edit entries. I think this is leading to issues, but its really hard to track this down.

Our pages make use of the replicated quite heavily for a page builder style setup where each block can be customised, I believe they also make use of the live preview quite a lot.

### Environment

```yaml
Environment
Application Name: Pelorus
Laravel Version: 10.40.0
PHP Version: 8.2.12
Composer Version: 2.6.6
Environment: production
Debug Mode: OFF
URL: pelorus-travel.strattons.com/
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: redis

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.44.0 PRO

Statamic Addons
doefom/currency-fieldtype: 1.2.3
gerttimmerman/statamic-zapier: 1.5
jacksleight/statamic-bard-texstyle: 3.1.4
ndx/statamic-bard-color-picker: 1.2.0
ryanmitchell/statamic-translation-manager: 1.3.0
withcandour/aardvark-seo: 3.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
