### ISSUE TITLE
Forms do no support optional asset files

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#9354]
### Bug description

Currently, forms do not support optional asset fields. If filled out without an actual file submitted, the submission will fail with an error 500.

### How to reproduce

Create a form with an asset field an no validation (optional field).

### Logs

```shell
Cannot upload files without encoding as multipart form data. {"exception":"[object] (Statamic\\Forms\\Exceptions\\FileContentTypeRequiredException(code: 0): Cannot upload files without encoding as multipart form data. at /Users/andjsch/Sites/peak-site/vendor/statamic/cms/src/Http/Controllers/FormController.php:83)
```

### Environment

```yaml
Environment
Application Name: Statamic Peak
Laravel Version: 10.39.0
PHP Version: 8.3.0
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: peak-site.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.42.1 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 4.0.0
studio1902/statamic-peak-seo: 8.0.0
studio1902/statamic-peak-tools: 4.2.0
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None

### Additional details

PR in the works 😄
