### ISSUE TITLE
Trying to edit a global for other sites does nothing and throws a console error.

### ISSUE THREAD

**Issue by geertjanknapen1** [statamic/cms#9362]
### Bug description

We have three sites, English, Dutch and Czech. We've created a GlobalSet that holds Form Translations and a GlobalSet that holds normal Translations.

Adding values to the array in the English site works as intended, but when I try to switch sites nothing happens and it throws a console error.

`sites.php` contains the site, only abnormality is that the key for Czech is `cs` instead of `cz` (marketing department am I right):
```php
'sites' => [
        'en' => [
            'name' => 'English',
            'locale' => 'en_US',
            'url' => '/en',
        ],

        'nl' => [
            'name' => 'Dutch',
            'locale' => 'nl_NL',
            'url' => '/nl',
        ],

        'cs' => [
            'name' => 'Czech',
            'locale' => 'cs_CZ',
            'url' => '/cs',
        ],
    ],
```

GlobalSet:
<img width="562" alt="image" src="https://github.com/statamic/cms/assets/33750300/ce37eda6-552c-4ca2-8dbd-50965785f987">

When I select Czech or Dutch (in below menu) nothing happens and I see below error in console:
<img width="482" alt="image" src="https://github.com/statamic/cms/assets/33750300/04657a69-9c42-4464-9a0b-ee8f0a027fd6">

Console error:
```
DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'http://{MY_URL}/cpanel/globals/form_translations?site=cs' cannot be created in a document with origin 'https:/{MY_URL}' and URL 'https://{MY_URL}/cpanel/globals/form_translations?site=en'.
    at q.localizationSelected (https://{MY_URL}/vendor/statamic/cp/build/assets/app-acbfff7e.js:653:47284)
    at invokeWithErrorHandling (https://{MY_URL}/vendor/statamic/cp/build/assets/app-acbfff7e.js:5:37633)
    at q.I (https://{MY_URL}/vendor/statamic/cp/build/assets/app-acbfff7e.js:5:14221)
    at invokeWithErrorHandling (https://{MY_URL}/vendor/statamic/cp/build/assets/app-acbfff7e.js:5:37633)
    at M.$emit (https://{MY_URL}/vendor/statamic/cp/build/assets/app-acbfff7e.js:5:28219)
    at input (https://{MY_URL}/vendor/statamic/cp/build/assets/app-acbfff7e.js:653:44054)
    at invokeWithErrorHandling (https://{MY_URL}/vendor/statamic/cp/build/assets/app-acbfff7e.js:5:37633)
    at q.I (https://{MY_URL}/vendor/statamic/cp/build/assets/app-acbfff7e.js:5:14221)
    at invokeWithErrorHandling (https://{MY_URL}/vendor/statamic/cp/build/assets/app-acbfff7e.js:5:37633)
    at M.$emit (https://{MY_URL}/vendor/statamic/cp/build/assets/app-acbfff7e.js:5:28219)
```

### How to reproduce

Statamic multisite install in a new fresh Laravel project.

Add the sites as explained above.

Create a new GlobalSet (available in all sites) with a required array.
Blueprint `form_translations.yaml`:
```yaml
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: translations
            field:
              mode: dynamic
              type: array
              display: Translations
              icon: array
              localizable: false
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required

```

Try changing the site to any other value except the default (English) and see the error in console.

### Environment

```yaml
Environment
Application Name: {MY_APP_NAME}
Laravel Version: 10.40.0
PHP Version: 8.3.0
Composer Version: 2.6.6
Environment: local
Debug Mode: ENABLED
URL: {MY_URL}
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.44.0 PRO

Statamic Addons
withcandour/aardvark-seo: 3.0.0
```

### Installation

Existing Laravel app

### Antlers Parser

Runtime (default)

### Additional details

We're using Blade and custom logic to utilize the Globals as a translation-bucket so our Content Department can manage them without having to change code.

Above works for another of our websites and is setup in exactly the same way.
