### ISSUE TITLE
Bard content not including orderedList ProseMirror attributes in HTML output

### ISSUE THREAD

**Issue by kristiana-s** [statamic/cms#9363]
### Bug description

Have noticed that when writing lists in bard field - and if splitting list items with paragraphs in between, both in cms and the associated .md file, the list numbering is retained correctly. However this is not reflected when trying to output this text in antlers template. Have tried many modifiers but seems like the output of the `renderProsemirrorToHtml` method in Bard/Augmentor.php is stripping the marks out.

content in .md file
```
 bard:
  -
    type: heading
    attrs:
      level: 2
    content:
      -
        type: text
        text: test
  -
    type: orderedList
    attrs:
      start: 1
    content:
      -
        type: listItem
        content:
          -
            type: paragraph
            content:
              -
                type: text
                text: 'Lorem ipsum dolor sit amet, consectetur'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
  -
    type: orderedList
    attrs:
      start: 2
    content:
      -
        type: listItem
        content:
          -
            type: paragraph
            content:
              -
                type: text
                text: 'Lorem ipsum dolor sit amet, consectetur'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
  -
    type: orderedList
    attrs:
      start: 3
    content:
      -
        type: listItem
        content:
          -
            type: paragraph
            content:
              -
                type: text
                text: 'Lorem ipsum dolor sit amet, consectetur' ....
```

html as is output in the frontend - from `{{bard|dump}}` You can see no marks applied from orderedList to `<ol>` tags

```
   "type" => "text"
        "text" => 
Statamic\Fields
Value {#14880 
          #raw: "
<h2 id="test">test</h2><ol><li><p>Lorem ipsum dolor sit amet, consectetur</p></li></ol><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><ol><li><p>Lorem ipsum dolor sit amet, consectetur</p></li></ol><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><ol><li><p>Lorem ipsum dolor sit amet, consectetur</p></li><li><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></li><li><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></li></ol>"
```

Possibly related to an older issue - https://github.com/statamic/cms/issues/454

### How to reproduce

Create blueprint with bard field, enter text with a list broken up with paragraphs.
 This can include sets

Output in template via following in template file

```
{{ bard }}
  {{ if type == "text" }}
    <div class="text">
      {{ text }}
    </div>
  {{ elseif type == "image" }}
    <div class="image">
      <img src="{{ image }}" alt="{{ caption }}" />
    </div>
  {{ /if }}
...

{{ /bard }}
```

### Environment

```yaml
Laravel Version: 9.52.16
PHP Version: 8.2.11
Composer Version: 2.1.5
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF
Addons: 8
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.44.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
