### ISSUE TITLE
Entries field type does not allow collection with multiple blueprints to have a field with different field types

### ISSUE THREAD

**Issue by maurice-ellis** [statamic/cms#9373]
### Bug description

I added another blueprint to the Pages collection, but this one uses the markdown field type, which is different than a custom field type in the default blueprint. When I try to select an entry, I run into this error

```
Statamic\Markdown\Parser::parse(): Argument #1 ($markdown) must be of type string, array given, called in /Users/maurice/Documents/328/328studios.co/v2.1/vendor/statamic/cms/src/Markdown/Manager.php on line 15
```

Doing a little bit of digging, the Entries Fieldtype gets an entry blueprint. I believe it's assumed that the fields would be the same in both, but I'm using different field types. Ultimately, it tries to process an entry with a blueprint that doesn't match. In this case, it's trying to parse the content field in an entry that isn't using markdown, but my custom field type. 

This is not an issue if the content fields in both blueprints use the same fieldtype.

### How to reproduce

Create 2 blueprints, with a field with different field types. Attempt to select an entry using the entries field type, an error occurs depending on if the value is not what it expects. If it works, let's say both differing field types expect a string, it means it is processing a field value using the wrong field type.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.40.0
PHP Version: 8.3.0
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: localhost:3000
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.44.0 PRO

Statamic Addons
thrtwoe/components: dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
