### ISSUE TITLE
Toast-Notifications are displayed twice if saving entry of Multi-Site with 2 Languages

### ISSUE THREAD

**Issue by priskahuber** [statamic/cms#9384]
### Bug description

I have a Multi-Site installed (German and French).
I have a EntrySavedListener where I handle some data and save them to this collection. After this is done, the system informs the user with a Toast message.

After Updating a Multi-Site Statamic from 4.8.0 to 4.45.0, these Toast messages appear twice (one for each Language).
In 4.8.0 they only appeared once, which was right, because, if i save German Site i don't wont a Notification of the French one.

### How to reproduce

Create a Multi-Site with 2 Sites.
Create a EntrySavedListener, add `use Statamic\Facades\CP\Toast;` and add a Toast message p.e: `Toast::info('This is my Toast message')->duration(10000); ` in handle function.
Create/Edit a page and save it. Toast will appear twice (see screenshot).
![toast-message-twice](https://github.com/statamic/cms/assets/17765613/95646879-20b0-42a0-8941-4b10d5e1781d)

### Environment

```yaml
Environment
Application Name: SuisseNaiS 22222 Weiserflächen-Plattform
Laravel Version: 9.52.16
PHP Version: 8.1.23
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: suissenais2.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.45.0 PRO

Statamic Addons
statamic/collaboration: 0.8.1
stillat/relationships: 2.1.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
