### ISSUE TITLE
Collection max depth is not enforced when setting entry parent

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#9388]
### Bug description

If you set a collection's max depth you are prevented from going deeper when reordering entries, but you can still create deeper entries by setting an entry's parent in the publish form.

### How to reproduce

1. Create a collection with a max depth.
2. Create en entry with the parent set to an entry that's already at the max depth.

### Environment

```yaml
Statamic
Addons: 12
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.45.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
