### ISSUE TITLE
Recently introduced Entries Fieldtype Tree View addition works for Collections/Entries, but empty when used on Asset Blueprints

### ISSUE THREAD

**Issue by artemverbo** [statamic/cms#9403]
### Bug description

Related to this recent addition of a Tree View for Entries Fieldtype https://github.com/statamic/ideas/issues/666 

### How to reproduce

Add an Entries Fieldtype with a hierarchical structure to an Asset Blueprint. When switching to the Tree View on assets, the Entries list will be empty (normal list view still works and displays flat list of entries).

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.16
PHP Version: 8.1.22
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.36.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
