### ISSUE TITLE
Error viewing collection

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#941]
I've created a collection, `Pages` and a structure `Pages` and added 2 pages, `Home` and `About Us` (Home is the `parent` of About Us).

When I visit the `Pages` collection I get an error:
```
[2019-11-22 04:10:58] local.ERROR: Illegal string offset 'type' {"userId":"b66458d6-0a9d-4f0e-b4fc-277064fce83d","exception":"[object] (ErrorException(code: 0): Illegal string offset 'type' at /Users/erin/Sites/szc2/vendor/statamic/cms/src/Fieldtypes/Bard.php:185)
[stacktrace]
#0 /Users/erin/Sites/szc2/vendor/statamic/cms/src/Fieldtypes/Bard.php(185): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Illegal string ...', '/Users/erin/Sit...', 185, Array)
#1 /Users/erin/Sites/szc2/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(640): Statamic\\Fieldtypes\\Bard->Statamic\\Fieldtypes\\{closure}('', 0)
#2 [internal function]: Illuminate\\Support\\Collection->Illuminate\\Support\\Traits\\{closure}('', 0)
#3 /Users/erin/Sites/szc2/vendor/laravel/framework/src/Illuminate/Support/Arr.php(611): array_filter(Array, Object(Closure), 1)
#4 /Users/erin/Sites/szc2/vendor/laravel/framework/src/Illuminate/Support/Collection.php(352): Illuminate\\Support\\Arr::where(Array, Object(Closure))
#5 /Users/erin/Sites/szc2/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(642): Illuminate\\Support\\Collection->filter(Object(Closure))
#6 /Users/erin/Sites/szc2/vendor/statamic/cms/src/Fieldtypes/Bard.php(186): Illuminate\\Support\\Collection->reject(Object(Closure))
#7 /Users/erin/Sites/szc2/vendor/statamic/cms/src/Fields/Field.php(214): Statamic\\Fieldtypes\\Bard->preProcessIndex('')
#8 /Users/erin/Sites/szc2/vendor/statamic/cms/src/Http/Resources/CP/Entries/ListedEntry.php(59): Statamic\\Fields\\Field->preProcessIndex()
#9 /Users/erin/Sites/szc2/vendor/laravel/framework/src/Illuminate/Support/Collection.php(685): Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry->Statamic\\Http\\Resources\\CP\\Entries\\{closure}(Object(Statamic\\CP\\Column), 2)
```

`Pages` collection:
```
title: Pages
route: 'pages/{slug}'
blueprints:
  - page
structure: pages
revisions: false
```

`Pages` structure:
```
title: Pages
expects_root: true
tree:
  -
    entry: ae6a372e-0ca6-4e2c-b380-5be59fb6922e
    children:
      -
        entry: b326012c-f2ee-4091-90c7-7f72138af363
```

**Comment by jasonvarga** [comment]
I'm not sure the structure has to do with it. The error is coming from Bard. What's in the Bard field for those entries?

**Comment by edalzell** [comment]
nuthin. But is named `content` is that the problem

**Comment by jasonvarga** [comment]
Does it have `sets` defined on it?

**Comment by edalzell** [comment]
nope

**Comment by edalzell** [comment]
```
title: Post
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Title
      -
        handle: slug
        field:
          generate: true
          type: slug
          localizable: false
          display: Slug
      -
        handle: content
        field:
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          type: bard
          localizable: false
          display: Content
      -
        handle: author
        field:
          max_items: 1
          mode: select
          type: users
          localizable: false
          display: Author
```
