### ISSUE TITLE
Can't reset color

### ISSUE THREAD

**Issue by aerni** [statamic/cms#9410]
### Bug description

There is no way to remove the selected color if the field config doesn't have `allow_any: true`. The color should be resettable in both UI's.

https://github.com/statamic/cms/assets/23167701/09da9fba-31e9-478f-8431-ea7e4c95d7c2

### How to reproduce

Use these fields for the same setup as the demo video:

```yaml
fields:
  -
    handle: any_color
    field:
      swatches:
        - '#EBF5FF'
        - '#FFD9C9'
      allow_any: true
      type: color
      display: 'Any color'
      icon: color
      localizable: false
      width: 50
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
  -
    handle: fixed_colors
    field:
      swatches:
        - '#EBF5FF'
        - '#FFD9C9'
      allow_any: false
      type: color
      display: 'Fixed colors'
      icon: color
      localizable: false
      width: 50
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
```

### Environment

```yaml
Environment
Application Name: gomagazin
Laravel Version: 10.41.0
PHP Version: 8.2.15
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: go-unity.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single, sentry, flare
Mail: postmark_gounity
Queue: redis
Session: file

Locales
Installed
LaravelLang\Actions\Plugin: 1.4.1
LaravelLang\Attributes\Plugin: 2.9.2
LaravelLang\HttpStatuses\Plugin: 3.8.0
LaravelLang\Lang\Plugin: 13.12.0
Locales Version: 1.9.0
Protected
Publisher Version: 15.0.2

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 3.8.2
PHP SDK Version: 3.22.1
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 9
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.45.0 PRO

Statamic Addons
aerni/advanced-seo: 2.4.3
aerni/livewire-forms: 8.1.0
aerni/social-links: 3.1.0
jacksleight/statamic-bard-texstyle: 3.1.4
jonassiewertsen/statamic-jobs: 1.4.0
jonassiewertsen/statamic-livewire: 2.12.0
rias/statamic-redirect: 3.6.0
spatie/statamic-responsive-images: 4.1.1
stillat/relationships: 2.1.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
