### ISSUE TITLE
Update to 4.47 causing nocache tags to trigger timeout

### ISSUE THREAD

**Issue by taylorcammack** [statamic/cms#9437]
### Bug description

Updated to 4.47 and started getting timeouts with stacktrace related to different things depending on the load. Was only having an issue on the front-end, control panel loaded fine. 

Did a sanity check by yanking blocks of code and it finally kicked back in when I removed any instance of the nocache tag.

### How to reproduce

- Update to 4.47
- Include {{ nocache }}

### Environment

```yaml
Environment
Application Name: Gregg County
Laravel Version: 10.43.0
PHP Version: 8.3.0
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: gregg-county.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single, flare
Mail: log
Queue: sync
Session: file

Livewire
Livewire: v3.4.4

Statamic
Addons: 10
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.47.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
goldnead/statamic-collapse-fieldtype: 1.0.5
jonassiewertsen/statamic-livewire: 3.0.0
rias/statamic-data-import: 1.3.0
spatie/statamic-responsive-images: 4.1.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
