### ISSUE TITLE
Margin between title & description is handled different in bard sets

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#9438]
### Bug description

I just realized that fields in bard sets have a space between title and description, but fields on the top level do not. Shouldn't this be handled the same in both cases? 

<img width="919" alt="Bildschirmfoto 2024-02-01 um 11 46 26" src="https://github.com/statamic/cms/assets/8265902/da93a11d-93d7-49a5-a42d-b8ccc3a80508">

### How to reproduce

Create two fields in a bluprint, one of them need to be inside a bard set.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.43.0
PHP Version: 8.2.15
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: test-issues.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.47.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
