### ISSUE TITLE
Collection Widgets: Pagination is not at the bottom of the card

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#9439]
### Bug description

The pagination is not at the bottom of the card if you have two collection widgets side by side in your dashboard:

- Example 1: Limit entries in both widgets to 10. If a couple of entry titles needs more than one line, and the total of text-lines is different in each one, the pagination are not aligned at the bottom.
- Example 2: Limit one widget to 3 entries and one to 10.
- Example 3: Go to the last pagination section in one card, where there is a random number of entries.

<img width="960" alt="example 1" src="https://github.com/statamic/cms/assets/8265902/f003f92c-205a-4683-a106-b0e3b90dfaba">
<img width="939" alt="example 2" src="https://github.com/statamic/cms/assets/8265902/c044903e-da6f-419b-8396-13a04dc30b96">
<img width="947" alt="example 3" src="https://github.com/statamic/cms/assets/8265902/64b4e699-e4ea-43a7-8695-afafd46142d4">

### How to reproduce

Display two collection widgets side by side in your dashboard.

### Environment

```yaml
Environment
Application Name: SpielRaum CMS
Laravel Version: 10.43.0
PHP Version: 8.2.15
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: spielraum.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: sendmail
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.47.0 PRO

Statamic Addons
statamic/seo-pro: 5.4.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
