### ISSUE TITLE
 Route [password.reset] Not Defined in Statamic Version 4.44.0 PRO

### ISSUE THREAD

**Issue by emran-alhaddad** [statamic/cms#9457]
### Bug description

While working on the Juffali Commercial Vehicles Statamic site, I encountered a routing error when attempting to initiate a password reset. The error "Symfony\Component\Routing\Exception\RouteNotFoundException: Route [password.reset] not defined" was displayed. This was unexpected as the normal behavior should redirect to the password reset page. A screenshot of the error is attached for clarity.

### How to reproduce

Navigate to the password reset request page on the site.
Enter an email address to initiate a password reset.
Submit the password reset request.
Encounter the routing error message that [password.reset] is not defined.

### Environment

```yaml
Application Name: Juffali Commercial Vehicles
Laravel Version: 10.40.0
PHP Version: 8.3.0
Composer Version: 2.5.5
Environment: local
Debug Mode: Enabled
URL: jcv.brackets-tech.com.test
Maintenance Mode: Off
Statamic Version: 4.44.0 PRO
Addons Installed: mitydigital/statamic-two-factor (1.1.4), rias/statamic-redirect (3.5.0), statamic/eloquent-driver (3.0.1)
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

![image](https://github.com/statamic/cms/assets/65433346/98358f90-2d20-496d-b98c-279da71f82d8)
