### ISSUE TITLE
Directory seperator wrong on windows

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#9458]
### Bug description

The directory seperator from the template select field is wrong on windows with laragon.

### How to reproduce

![image](https://github.com/statamic/cms/assets/3351449/4f87e95c-e0c6-4bff-a7bd-070150cf6c48)

Error:
`View [karriere\listing] not found.`

 It should be `karriere/listing`. 

### Environment

```yaml
Application Name: Statamic
Laravel Version: 10.43.0
PHP Version: 8.2.7
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.46.0 PRO

Statamic Addons
ddm-studio/cookie-byte: 1.4.3
jonassiewertsen/statamic-livewire: 2.12.0
parfaitementweb/statamic-country-fieldtype: 1.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
