### ISSUE TITLE
Updates section is blank

### ISSUE THREAD

**Issue by ottz0** [statamic/cms#9462]
### Bug description

I'm trying to update statamic via local host but the section is blank. I know there are updates as my prod version has updates in this section but I don't have command line access to be able to update it.

### How to reproduce

I have tried composer dump-autoload and removed the cache but this area is still blank

![Uploading Screenshot 2024-02-06 at 2.45.19 pm.png…]()

### Environment

```yaml
Statamic
Addons: 9
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.44.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
