### ISSUE TITLE
customize columns glitched

### ISSUE THREAD

**Issue by Oleafeon** [statamic/cms#9473]
### Bug description

When there are alot of options in the customize columns it starts glitching on my windows pc like in the video but this does not happen on my mac

### How to reproduce

Create a collection
Add alot of options to the blueprint
open the customize collection option in cp

### Environment

```yaml
Laravel Version: 10.42.0
PHP Version: 8.2.6
Composer Version: 2.5.5
Statamic Version: 4.45.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

https://github.com/statamic/cms/assets/20043831/af618a90-4133-439e-81b4-507256584d63
