### ISSUE TITLE
Update badge missing in CP

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#9474]
### Bug description

I've noticed I don't see the update badge anymore in the control panel. Even when there are updates. Check this screen:
<img width="1478" alt="Screenshot 2024-02-07 at 10 27 48" src="https://github.com/statamic/cms/assets/69107412/78e6ce80-4443-4e6a-b83c-db08110877ea">

### How to reproduce

Check the CP on a site that has updates available. 

### Environment

```yaml
Environment
Application Name: Statamic Peak Development
Laravel Version: 10.42.0
PHP Version: 8.3.2
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.46.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 5.0.0
studio1902/statamic-peak-seo: 8.0.0
studio1902/statamic-peak-tools: 4.4.0
```

### Installation

Starter Kit using via CLI

### Antlers Parser

Runtime (default)
