### ISSUE TITLE
Rules array does get passed to the custom invalidator child class empty.

### ISSUE THREAD

**Issue by AlexanderFalkenberg** [statamic/cms#9475]
### Bug description

I want to use a custom invalidator class extending the default invalidator class, as described in the docs: https://statamic.dev/static-caching#custom-invalidator-class.

I want to reuse the rules array in the static_caching config file, but the rules array is empty. 

Values seem to not get passed down to the custom invalidator. 

```php
    $this->app->bind(DefaultInvalidator::class, function ($app) {
            return new DefaultInvalidator(
                $app[Cacher::class],
                $app['config']['statamic.static_caching.invalidation.rules']
            );
        });
``` 

### How to reproduce

Override the default static invalidator class with a custom one as per docs (see above). Try to dump 

```php
dd($this->rules)
``` 
Repo to try:
https://github.com/AlexanderFalkenberg/static-caching

### Environment

```yaml
Environment
Application Name: Statamic Peak
Laravel Version: 10.43.0
PHP Version: 8.3.2
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: static-caching.test/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 4
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: full
Version: 4.48.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 5.0.0
studio1902/statamic-peak-seo: 8.1.0
studio1902/statamic-peak-tools: 4.4.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)

### Additional details

- Peak Starter Kit
- Horizon
