### ISSUE TITLE
Error viewing collection with taxonomy

### ISSUE THREAD

**Issue by smcyr** [statamic/cms#950]
I upgraded a site from v2 to v3 and I have an error when viewing one of my collections:
`/cp/collections/case-studies/entries?sort=date&order=desc&page=1&perPage=50&search=&filters=e30%3D`

```
{
  "JSON":{
    "message":"Method Statamic\\Taxonomies\\TermCollection::handle does not exist.",
    "exception":"BadMethodCallException",
    "file":"D:\\projects\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\Macroable.php",
    "line":103,
    "trace":[
      {
        "file":"D:\\projects\\test\\vendor\\statamic\\cms\\src\\Fieldtypes\\Relationship.php",
        "line":72,
        "function":"__call",
        "class":"Illuminate\\Support\\Collection",
        "type":"->"
      },
      {
        "function":"Statamic\\Fieldtypes\\{closure}",
        "class":"Statamic\\Fieldtypes\\Relationship",
        "type":"->"
      },
      {
        "file":"D:\\projects\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Collection.php",
        "line":638,
        "function":"array_map"
      },
      {
        "file":"D:\\projects\\test\\vendor\\statamic\\cms\\src\\Fieldtypes\\Relationship.php",
        "line":77,
        "function":"map",
        "class":"Illuminate\\Support\\Collection",
        "type":"->"
      },
      {
        "file":"D:\\projects\\test\\vendor\\statamic\\cms\\src\\Fields\\Field.php",
        "line":214,
        "function":"preProcessIndex",
        "class":"Statamic\\Fieldtypes\\Relationship",
        "type":"->"
      },
      {
        "file":"D:\\projects\\test\\vendor\\statamic\\cms\\src\\Http\\Resources\\CP\\Entries\\ListedEntry.php",
        "line":59,
        "function":"preProcessIndex",
        "class":"Statamic\\Fields\\Field",
        "type":"->"
      },
      {
        "file":"D:\\projects\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Collection.php",
        "line":685,
        "function":"Statamic\\Http\\Resources\\CP\\Entries\\{closure}",
        "class":"Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry",
        "type":"->"
      },
      {
        "file":"D:\\projects\\test\\vendor\\statamic\\cms\\src\\Http\\Resources\\CP\\Entries\\ListedEntry.php",
        "line":63,
        "function":"mapWithKeys",
        "class":"Illuminate\\Support\\Collection",
        "type":"->"
      },
      {
        "file":"D:\\projects\\test\\vendor\\statamic\\cms\\src\\Http\\Resources\\CP\\Entries\\ListedEntry.php",
        "line":41,
        "function":"values",
        "class":"Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry",
        "type":"->"
      },
      ...
    ]
  }
}
```

Here is my blueprint:

```
taxonomies: false
title: 'Case studies'
create_title: 'Case studies'
sections:
  main:
    display: Main
    fields:
      -
        handle: seo
        field:
          type: blueprints
          display: SEO
          fieldset: _seo
      -
        handle: page_headline_single
        field:
          type: blueprints
          display: 'Page headline'
          fieldset: _page-headline-case-studies
          localizable: true
      -
        handle: view_listing
        field:
          type: section
          display: 'View (Listing)'
      -
        handle: style
        field:
          type: select
          display: Style
          options:
            black: black
            gray-light: 'Gray light'
            gray-dark: 'gray dark'
            yellow: yellow
            green: Green
          width: 50
      -
        handle: bg_pattern
        field:
          type: select
          display: 'Background pattern'
          options:
            none: None
            black: Black
            white: White
          width: 50
          default: None
      -
        handle: section_hero_image
        field:
          type: section
          display: 'Hero image ( Post )'
      -
        handle: hero_image
        field:
          type: assets
          display: 'Hero image'
          container: projets
          folder: /
          max_files: 1
          mode: grid
          width: 50
          restrict: false
      -
        handle: hero_image_mobile
        field:
          type: assets
          display: 'Hero image ( mobile )'
          container: projets
          folder: /
          max_files: 1
          mode: grid
          width: 50
      -
        handle: hero_custom_classes
        field:
          type: list
          display: 'Custom classes'
      -
        handle: section_feature_image
        field:
          type: section
          display: 'Feature image ( Banner )'
      -
        handle: feature_image
        field:
          type: assets
          display: 'Feature image'
          container: projets
          folder: /
          max_files: 1
          mode: grid
          width: 50
      -
        handle: feature_image_mobile
        field:
          type: assets
          display: 'Feature image ( mobile )'
          container: projets
          folder: /
          max_files: 1
          mode: grid
          width: 50
      -
        handle: content
        field:
          type: section
          display: Content
      -
        handle: client
        field:
          type: entries
          display: Client
          collection:
            - clients
          max_items: '1'
          sort: 'date:desc|title:asc'
          label: '{{ title }}'
          mode: tags
          width: 50
      -
        handle: year
        field:
          type: taxonomy
          display: Year
          max_items: 1
          sort: 'title:asc'
          label: '{{ title }}'
          taxonomy: year
          mode: panes
          width: 50
      -
        handle: languages
        field:
          type: taxonomy
          display: Languages
          sort: 'title:asc'
          label: '{{ title }}'
          taxonomy: languages
          mode: panes
          width: 50
      -
        handle: framework
        field:
          type: taxonomy
          display: Framework
          sort: 'title:asc'
          label: '{{ title }}'
          taxonomy: framework
          mode: panes
          width: 50
      -
        handle: contexte_title
        field:
          type: text
          display: 'Context title'
          localizable: true
      -
        handle: contexte
        field:
          type: bard
          display: 'Context body'
          container: main
          folder: /
          localizable: true
          save_html: true
          buttons:
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - html
            - image
            - quote
            - codeblock
            - h1
            - h2
            - h3
            - h4
            - h5
            - h6
            - anchor
      -
        handle: context_custom_classes
        field:
          type: list
          display: 'Custom classes'
      -
        handle: context_img_left
        field:
          type: assets
          container: logo
          folder: /
          restrict: false
          width: 50
          display: 'Image left'
      -
        handle: context_img_right
        field:
          type: assets
          container: main
          folder: /
          restrict: false
          width: 50
          display: 'Image right'
      -
        handle: section_challenge
        field:
          type: section
          display: Challenge
      -
        handle: challenge_custom_classes
        field:
          type: list
          display: 'Custom Classes'
      -
        handle: challenge_image
        field:
          type: assets
          container: projets
          folder: /
          restrict: false
          max_files: 1
          mode: grid
          width: 50
          display: 'Image (Phone)'
      -
        handle: challenge_gif
        field:
          type: assets
          container: projets
          folder: /
          restrict: false
          max_files: 1
          mode: grid
          width: 50
          display: 'GIF (Phone)'
      -
        handle: challenge_image_mobile
        field:
          type: assets
          container: projets
          folder: /
          restrict: false
          max_files: 1
          display: 'Image (mobile)'
      -
        handle: challenge__body
        field:
          type: bard
          display: Body
          container: main
          folder: /
          localizable: true
          width: 50
          save_html: true
          buttons:
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - html
            - image
            - quote
            - codeblock
            - h1
            - h2
            - h3
            - h4
            - h5
            - h6
            - anchor
      -
        handle: challenge__title
        field:
          type: text
          display: Title
          localizable: true
          width: 50
      -
        handle: challenge_background_image
        field:
          type: assets
          container: projets
          folder: /
          restrict: false
          display: 'Background image'
      -
        handle: section_website_image
        field:
          type: section
          display: 'Website image'
      -
        handle: website_image_desktop
        field:
          type: assets
          container: projets
          folder: /
          restrict: false
          max_files: 1
          mode: grid
          display: 'Image desktop'
          width: 50
      -
        handle: website_image_mobile
        field:
          type: assets
          container: logo
          folder: /
          restrict: false
          width: 50
          display: 'Image mobile'
      -
        handle: website_background_image_01
        field:
          type: assets
          container: main
          folder: /
          restrict: false
          width: 50
          display: 'Background Image 1'
      -
        handle: website_background_image_02
        field:
          type: assets
          container: main
          folder: /
          restrict: false
          width: 50
          display: 'Background Image 2'
      -
        handle: website_background_01_hposition
        field:
          type: select
          options:
            left: Left
            right: Right
          width: 25
          display: 'Horizontal Postition'
          default: Left
      -
        handle: website_background_01_vposition
        field:
          type: select
          options:
            top: Top
            bottom: Bottom
          width: 25
          display: 'Vertical Position'
          default: Top
      -
        handle: website_background_02_hposition
        field:
          type: select
          options:
            left: Left
            right: Right
          width: 25
          display: 'Horizontal Position'
          default: Right
      -
        handle: website_background_02_vposition
        field:
          type: select
          options:
            top: Top
            bottom: Bottom
          width: 25
          display: 'Vertical Position'
          default: Bottom
      -
        handle: section_solutions
        field:
          type: section
          display: Solutions
      -
        handle: solutions_image
        field:
          type: assets
          container: projets
          folder: /
          restrict: false
          max_files: 1
          mode: grid
          display: 'Solutions image'
          width: 50
      -
        handle: solution_image_mobile
        field:
          type: assets
          container: projets
          folder: /
          restrict: false
          width: 50
          display: 'Solution image mobile'
      -
        handle: custom_classes
        field:
          type: list
          display: 'Custom classes'
      -
        handle: solution_position
        field:
          type: select
          options:
            Top: Top
            Bottom: Bottom
          display: Position
          default: Top
      -
        handle: solution_extra_image_top
        field:
          type: assets
          container: projets
          folder: /
          restrict: false
          display: 'Extra Image Top'
      -
        handle: solution_extra_image_bottom
        field:
          type: assets
          container: projets
          folder: /
          restrict: false
          display: 'Extra Image Bottom'
      -
        handle: solutions__title
        field:
          type: text
          display: Title
          localizable: true
          width: 50
      -
        handle: solutions__body
        field:
          type: bard
          display: Body
          container: main
          folder: /
          localizable: true
          width: 50
          save_html: true
          buttons:
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - html
            - image
            - quote
            - codeblock
            - h1
            - h2
            - h3
            - h4
            - h5
            - h6
            - anchor
      -
        handle: section_decorative_image
        field:
          type: section
          display: 'Decorative image'
      -
        handle: decorative_image
        field:
          type: assets
          container: projets
          folder: /
          restrict: false
          max_files: 1
          mode: grid
          display: 'Decorative image'
      -
        handle: results
        field:
          type: section
          display: Results
      -
        handle: results__title
        field:
          type: text
          display: Title
          localizable: true
      -
        handle: results__body
        field:
          type: bard
          display: Body
          localizable: true
          save_html: true
          buttons:
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - html
            - quote
            - codeblock
            - h1
            - h2
            - h3
            - h4
            - h5
            - h6
            - anchor
      -
        handle: results__btn-url
        field:
          type: text
          display: 'Button URL'
          localizable: true
      -
        handle: result_image_left
        field:
          type: assets
          container: projets
          folder: /
          restrict: false
          width: 50
          display: 'Result image left'
      -
        handle: result_image_right
        field:
          type: assets
          container: projets
          folder: /
          restrict: false
          width: 50
          display: 'Result image right'
      -
        handle: view_context_home
        field:
          type: section
          display: 'Context (Home page)'
      -
        handle: context_home_title
        field:
          type: text
          display: Title
          localizable: true
      -
        handle: context_home_body
        field:
          type: bard
          display: Body
          localizable: true
          save_html: true
          buttons:
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - html
            - quote
            - codeblock
            - h1
            - h2
            - h3
            - h4
            - h5
            - h6
            - anchor
```
