### ISSUE TITLE
Fieldtypes in config overriding "sometimes" rule with preset $rules

### ISSUE THREAD

**Issue by caseydwyer** [statamic/cms#9507]
### Bug description

When building out the `configFieldItems` in a custom field, I think any (but at minimum the `numeric`) fieldtypes that have an inherent/preset `$rules`, together with a user-defined `sometimes` validation rule, will always throw errors (when they're not submitted). Pretty sure the preset `$rules`, in this context, is overriding or taking precedence over (ie, evaluated before) the `sometimes` rule. From `Floatval`, for example:

```php
protected $rules = ['numeric'];
```

Here's **[a repo that reproduces the issue](https://github.com/caseydwyer/bug-reproductions/tree/statamic-sometimes-rule-in-fieldtype-config)**, and a screencap of what this looks like with a bit of code + CP interface:

![config-bug](https://github.com/statamic/cms/assets/13950848/92d845e4-ff47-47d0-ade7-3027cea7c4de)

### How to reproduce

1. Grab the repro-repo™
2. Visit **[the Page blueprint](http://bug-reproductions.test/cp/collections/pages/blueprints/page/edit)** in browser
3. Click into the `Field with Replicator Field` (at the bottom)
4. Hit **Apply** without making any changes (should get validation errors)
5. Toggle on the `Root Toggle`
6. See the _Must be an integer._ error on the `Sometimes Float Field`
7. Inspect `FieldWithReplicator.php`, line 17, to make sure I'm not missing something obvious. 😬

### Environment

```yaml
<details>
  <summary>Environment</summary>

Application Name: Statamic
Laravel Version: 10.43.0
PHP Version: 8.2.5
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.48.0 Solo
</details>
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

I initially thought this was related to nested fields (ie, in a Replicator)—hence that setup in the blueprint. Left it in there because it _does_ also impact nested numerics...but it's not specific to that context, which is why I didn't emphasize it above.

Let me know if there's anything else I can do to help, here!
