### ISSUE TITLE
Template fieldtype proposing blueprints

### ISSUE THREAD

**Issue by smcyr** [statamic/cms#951]
I migrated a site from v2 to v3 and all my content with a template field show "An item with this ID could not be found". But the value isn't an ID, it's a string with, for example "articles/single" which refer to an existing view (articles/single.antlers.hmtl). And there is a button "Link Existing Item" which proposes blueprints instead of templates.

**Comment by jasonvarga** [comment]
Please show that field from the blueprint, and the value of the field in the entry.

**Comment by smcyr** [comment]
My blueprint:
```
taxonomies: false
title: _Template
fields:
  -
    handle: template
    field:
      type: template
      display: Template
      width: 50
```

My content, on the first line:
```
template: pages/contact
```

**Comment by jasonvarga** [comment]
Are you sure this is the field you're noticing that error on?

You can click the field label to switch it to the handle.

![](https://d.pr/i/bGscAd+)

**Comment by smcyr** [comment]
Here is a screenshot:
![Annotation 2019-11-22 105754](https://user-images.githubusercontent.com/664920/69440512-fa6b5080-0d16-11ea-863d-0729c8047600.png)

**Comment by smcyr** [comment]
Also, when I click on "Link Existing Item":
![Annotation 2019-11-22 105832](https://user-images.githubusercontent.com/664920/69440562-12db6b00-0d17-11ea-9190-a64c23e97c8a.png)

**Comment by jasonvarga** [comment]
That definitely says `template`!

Are you sure you're looking at the right blueprint?

**Comment by smcyr** [comment]
Wait a second, I see the problem... I have a blueprint `_template.yaml`:
```
taxonomies: false
title: _Template
fields:
  -
    handle: template
    field:
      type: template
      display: Template
      width: 50
```
Which I refer in my page blueprint:
```
taxonomies:
  tags: true
title: Contact
fields:
  -
    handle: template
    field:
      type: blueprints
      display: Template
      fieldset: _template
```
So maybe it's confused somehow

**Comment by jasonvarga** [comment]
Ah I see, this is related to the issue you opened at https://github.com/statamic/migrator/issues/12

There you say this:

> type: partial is now type: blueprints

That's not true.

`type: partial` should be changed to the new fieldset import syntax.

https://statamic.dev/blueprints#importing-fieldsets

eg. This in v2:

``` yaml
fields:
  template:
    type: partial
    fieldset: _template
```

should become this in v3:

``` yaml
fields:
  -
    import: template
```

and your `_template` blueprint should become a _fieldset_ and moved to `resources/fieldsets/template.yaml`.
