### ISSUE TITLE
Filesize units is not working in other language After Updating to 4.48

### ISSUE THREAD

**Issue by kungphung** [statamic/cms#9513]
### Bug description

We have added the size of the file with the tag {{ size }} in our template.
When the site has not the locale `en_US` in `config/statamic/sites.php` 
This is showing in the frontend.
`statamic::messages.units.MB` in stead of the correct `39 MB`.

I guess the translation is missing in all languages.

### How to reproduce

change locale in `config/statamic/sites.php`
create component with an asset field.

Add in antlers template 

```
{{ asset }}
{{ size }}
{{ /asset }}
```

### Environment

```yaml
Environment
Application Name: 
Laravel Version: 9.52.15
PHP Version: 8.2.11
Composer Version: 2.6.4
Environment: local
Debug Mode: ENABLED
URL: 
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.48.0 PRO
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
