### ISSUE TITLE
Issue with updating entries when using `JsonResource::withoutWrapping()`

### ISSUE THREAD

**Issue by vintagesucks** [statamic/cms#9518]
### Bug description

When using `JsonResource::withoutWrapping()`, updating an entry with "Continue Editing" causes the following to be missing:
* The entry title in the browser tab
* The entry title in the editor
* The `Visit URL` button in the editor sidebar

Demo:

https://github.com/statamic/cms/assets/13335308/edb310e3-2cf0-48a6-aeae-68c477ae3c52

### How to reproduce

Add the following to `app/Providers/AppServiceProvider.php::boot()` in a fresh statamic/statamic install:

```php
\Illuminate\Http\Resources\Json\JsonResource::withoutWrapping();
``` 

* Open any page (e.g. Home)
* Select `After Saving` → `Continue Editing`
* Click `Save & Publish`

---

Repo: https://github.com/vintagesucks/repro-statamic-updating-entries-without-wrapping

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.43.0
PHP Version: 8.2.15
Composer Version: 2.7.0
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.48.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)

### Additional details

Applying a change similar to https://github.com/statamic/cms/pull/9296 to the following code seems to fix the problem, but since I am not sure about the side effects of doing so, I opted to create an issue instead of a PR.

https://github.com/statamic/cms/blob/8ee617d374bd2689ab3a944a2363d71d44deda1a/src/Http/Controllers/CP/Collections/EntriesController.php#L262-L268
