### ISSUE TITLE
Field `type` variable not available in email form data

### ISSUE THREAD

**Issue by sjclark** [statamic/cms#9523]
### Bug description

`{{type}}` form field variables are no longer available when submitting forms - as per docs https://statamic.dev/forms#email-variables

### How to reproduce

1. Install Fresh Statamic latest
2. Create a basic form
3. Create and select an email template that includes `{{type}}` - ie.
```html
{{ fields }}
  <b>{{ display }}</b> {{ value }} - {{ type }}
{{ /fields }}
```
4. Submit form and receive back `name NameTextInput Text - ` (no type data)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.43.0
PHP Version: 8.2.15
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: stattest.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.48.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)

### Additional details

Possible the docs are wrong / need updating:
https://statamic.dev/forms#email-variables

As a side-note I couldn't find any instructions in the docs on where/how to create the view file for an email. I know from using Statamic where/how to do this but figure a paragraph describing how to do this would be helpful? (totally possible I missed it and/or it's not under [Forms](https://statamic.dev/forms#email-variables) or [Email](https://statamic.dev/email)?)
