### ISSUE TITLE
Issue with `link` inside `bard` when using `remove_empty_nodes: trim`

### ISSUE THREAD

**Issue by vintagesucks** [statamic/cms#9526]
### Bug description

When using `remove_empty_nodes: trim` within `bard`, updating an entry with "Continue Editing" will cause the `link` content to disappear, at least visually. It will be saved to disk and will be present on reload.

Demo:

https://github.com/statamic/cms/assets/13335308/521fa6de-ca27-400a-97ce-10a36fa88faf

### How to reproduce

Reproduction repo: https://github.com/vintagesucks/repro-statamic-continue-editing-link
* Open `Home` page
* Add `Test` set
* Select `URL` and enter `https://statamic.com/`
* Select `After Saving` → `Continue Editing`
* Click `Save & Publish`

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.44.0
PHP Version: 8.2.15
Composer Version: 2.7.0
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.48.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)

### Additional details

Applies only to newly added sets. Sets that existed when the entry was opened are not affected.
