### ISSUE TITLE
Error when viewing a page structure entry

### ISSUE THREAD

**Issue by smcyr** [statamic/cms#953]
When I click on my homepage entry in the CP, I get this error:
```
ErrorException
Undefined index: default
/cp/structures/pages/entries/db0ae4e3-4f10-4802-bc40-0b880cbf02c7/accueil 
Illuminate\Foundation\Bootstrap\HandleExceptions::handleError :47
D:\projects\mutation\vendor\statamic\cms\src\Routing\UrlBuilder.php:47
```
Here is my blueprint `home-page.yaml`:
```
taxonomies: false
title: 'Home page'
fields:
  -
    handle: seo
    field:
      type: blueprints
      display: SEO
      fieldset: _seo
      localizable: true
  -
    handle: section
    field:
      type: section
      display: 'Page headline'
  -
    handle: page_headline__tag
    field:
      type: text
      display: Tag
      localizable: true
      width: 33
  -
    handle: page_headline__title
    field:
      type: text
      display: Title
      localizable: true
  -
    handle: page_headline__body
    field:
      type: bard
      display: Body
      localizable: true
      save_html: true
      buttons:
        - bold
        - italic
        - unorderedlist
        - orderedlist
        - html
        - quote
        - codeblock
        - h1
        - h2
        - h3
        - h4
        - h5
        - h6
        - anchor
  -
    handle: content
    field:
      type: section
      display: Content
  -
    handle: features
    field:
      type: grid
      display: Features
      fields:
        -
          handle: title
          field:
            type: text
            display: Title
        -
          handle: body
          field:
            type: bard
            display: Body
            save_html: true
            buttons:
              - bold
              - italic
              - unorderedlist
              - orderedlist
              - html
              - quote
              - codeblock
              - h1
              - h2
              - h3
              - h4
              - h5
              - h6
              - anchor
        -
          handle: button_label
          field:
            type: text
            display: 'Button Label'
        -
          handle: button_url
          field:
            type: entries
            display: 'Button URL'
            max_items: 1
            sort: 'date:desc|title:asc'
            label: '{{ title }}'
            mode: panes
      mode: stacked
      max_rows: 2
      localizable: true
  -
    handle: case_study_feature
    field:
      type: entries
      display: 'Case study (feature)'
      collection:
        - case-studies
      max_items: '1'
      sort: 'date:desc|title:asc'
      label: '{{ title }} '
      mode: panes
```
