### ISSUE TITLE
Redirection URLs query strings are being removed when users are sent to login pages

### ISSUE THREAD

**Issue by sunscreem** [statamic/cms#9532]
### Bug description

When my users visit

https://mysite.com/someurl?token=1234

that page is protected using the usual `logged_in` scheme.

They therefore get redirect to:

https://mysite.com/loginpage?redirect=https://mysite.com/someurl

Note that the `?token=1234` has been stripped out.

They should be sent to

https://mysite.com/loginpage?redirect=https://mysite.com/someurl?token=1234

### How to reproduce

1. Install Statamic
2. Use logged in schema on front end.
3. Visit any URL with a query string attached, and as you get redirected you should see the query string removed.

### Environment

```yaml
Environment
Application Name: Faur
Laravel Version: 10.42.0
PHP Version: 8.2.3
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: faur.sunscreem.xyz
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single, bugsnag
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.46.0 PRO

Statamic Addons
statamic/seo-pro: 5.4.1
webographen/statamic-admin-log: 1.0.8
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

As @jasonvarga said [in this discussion](https://github.com/statamic/cms/discussions/9530#discussioncomment-8484580), the fix is probably just a case of:

https://github.com/statamic/cms/blob/d76a4b4d0743e809b0f63485e9d40be980787f4c/src/Auth/Protect/Protection.php#L68-L71

Changing `request()->url()` to `fullUrl()`
