### ISSUE TITLE
Collection pagination doesn't work for pages past one

### ISSUE THREAD

**Issue by JonKaric** [statamic/cms#954]
##### Issue

When on a collection, eg. `http://site.test/cp/collections/reviews`, the pagination *does* have the correct amount of pages, but only the first page returns any results.

##### My steps to recreate

1) Installed via composer
2) Installed migrator package
3) Used `migrate:site`

##### Example collection yaml file:

``` yaml
title: Reviews
layout: default
template: post
blueprints:
  - reviews
route: '/reviews/{slug}'
taxonomies:
  - air_date
  - air_loc
  - tags
date: true
date_behavior:
  past: public
  future: unlisted
sort_dir: desc
```
