### ISSUE TITLE
`smart_typography` on bard requires `enable_input_rules` to be true

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#9554]
### Bug description

I just spend an embarrassingly long time on figuring out why my Smart Typography toggle on this Bard field didn't do anything 😅. It turned out the toggle for Enable Input Rules was off, and Smart Typography requires this to be on. 

There's a PR incoming to add the validation to the field config fixing this. 

### How to reproduce

1. Turn on Smart Typography
2. Turn off Enable Input Rules 

Notice Smart Typography not working.

### Environment

```yaml
Environment
Application Name: Statamic Peak Development
Laravel Version: 10.44.0
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.49.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 6.0.2
studio1902/statamic-peak-seo: 8.2.0
studio1902/statamic-peak-tools: 4.4.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
