### ISSUE TITLE
Modifier [format('Y')] not found

### ISSUE THREAD

**Issue by de-raaf-media** [statamic/cms#9556]
### Bug description

If I use the format modifier with a parameter I get an error Modifier [format('Y')] not found.

### How to reproduce

In antlers {{ now }} renders February 21st, 2024 
{{ now | diffForOwls }} renders "oga dnoces 1". So modifiers are working.
{{ now | format('Y') }} throws an exception "Modifier [format('Y')] not found"

### Environment

```yaml
Environment
Application Name: ***
Laravel Version: 10.43.0
PHP Version: 8.1.26
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: ***.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.32.0 PRO

Statamic Addons
aerni/factory: 1.4.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
