### ISSUE TITLE
Cache not invalidating as expected when content is saved

### ISSUE THREAD

**Issue by nickbasile** [statamic/cms#9560]
### Bug description

We're having an issue where our published site is not showing changes made in the admin. 

We have a page blueprint with a repeater that lets us add new content sections to our pages. We turned off an existing block and added a new one. We can see the changes on the live preview, but when we save and publish the page the changes are not happening on the site. Is there something obvious we're missing?

We are using the git automation and our `STATAMIC_STATIC_CACHING_STRATEGY` is set to half.  We confirmed that the commits are happening as expected. We also tried running `php please static:warm` and `php please stache:refresh` but they didn't work either, and we don't really want to run that after every edit.

We have not made any changes to the `static_caching.php` file.

### How to reproduce

1. Create a page collection.
2. Add a repeater with various content blocks.
3. Add new page with content blocks.
4. Turn off a content block and add a new one.
![Screenshot 2024-02-21 at 10 16 01 AM](https://github.com/statamic/cms/assets/10423440/e32d984b-c2c1-46f0-ab59-db7ff06c6ded)
5. Save and publish page
6. Check live preview, it works.
7. Check site, it's still the old section.

### Environment

```yaml
Environment
Application Name: [redacted]
Laravel Version: 10.35.0
PHP Version: 8.3.2-1+ubuntu22.04.1+deb.sury.org+1
Composer Version: 2.7.1
Environment: production
Debug Mode: OFF
URL: [redacted]
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Disabled
Static Caching: half
Version: 4.44.0 PRO

Statamic Addons
alt-design/alt-sitemap: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
