### ISSUE TITLE
Programatically creating Entry with Parent fails

### ISSUE THREAD

**Issue by plexus77** [statamic/cms#9569]
### Bug description

I am programatically creating ordered entries and while the entry MD looks fine the parent/child relationships are not visible on the tree list screen or when editing the child

Collection config
```
title: Areas
template: default
layout: layout
taxonomies:
  - ranges
revisions: false
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
structure:
  root: false
  max_depth: 4
  slugs: true
```

Parent
```
---
id: 6ecce8f4-0681-4638-baaf-9a480fd8bf78
blueprint: area
title: External
updated_by: 1
updated_at: 1708567891
---
```

Child
```
---
id: 79d22b0b-320c-4c90-9c03-60e9c2cc4a35
blueprint: area
title: Bricks
parent: 6ecce8f4-0681-4638-baaf-9a480fd8bf78
updated_by: 1
updated_at: 1708568062
---
```

Is this a bug or is there something I'm missing here?

### How to reproduce

When I look at the entries in the tree view there is no parent child relationship, when I edit the child entry there is no parent visible and when I try to add one and save it doesn't work ie there is no relationship visible on the list page and when I return to the edit page it is unset again (even though the parent field is still present in the MD).  I drag the child into position press save and then everything seems to work from there on (note that there is no change to the parent field in the md).  

If I manually remove the parent field from the md and then use the admin ui to link the entry to it's parent it creates markdown exactly the same as the above.

### Environment

```yaml
Laravel Version: 10.45.1
PHP Version: 8.1.17
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 6
Antlers: runtime
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.49.0 PRO

Statamic Addons
aniket-magadum/insta-feeds: 1.0.1
mitydigital/iconamic: 1.1.6
ncla/statamic-focal-point-fieldtype: 3.0.0
rias/statamic-redirect: 3.6.2
statamic/collaboration: 0.8.1
tresdstudioweb/dynamic-select: 1.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
