### ISSUE TITLE
Structures are not limited to selected collections

### ISSUE THREAD

**Issue by skoontastic** [statamic/cms#957]
I have a collection linked to a navigation structure in the config, but when I click "Add Link > Link to Entry" it allows me to choose from all available entries, not just the ones in the chosen collection.

**Comment by jasonvarga** [comment]
Can you please post your `content/structures/{structure}.yaml` file?

**Comment by skoontastic** [comment]
```
title: 'Top Menu'
collections:
  - schools
tree:
  -
    entry: 1e738fb7-110f-452e-8ce9-a01f287975cb
  -
    title: PowerSchool
    url: 'https://getschools.powerschool.com'
```
