### ISSUE TITLE
Conditional logic not working against radio buttons

### ISSUE THREAD

**Issue by benfurfie** [statamic/cms#959]
**Describe the bug**
When creating a fieldset with a radio and an asset, the conditional display setting on asset does not show the radio button as an option to conditionally display against.

**To Reproduce**
1. Download the fieldset.
2. Click on the asset
3. Click into the 'conditions' tab
4. Click on select field
5. See error that 'Sorry, no matching options'.

**Expected behavior**
The radio options should appear as conditions to match against.

**Screenshots**
<img width="667" alt="Screenshot 2019-11-23 at 10 25 43" src="https://user-images.githubusercontent.com/10786699/69467568-b5115680-0ddc-11ea-9eb4-bb6b3547899e.png">

**Environment details (please complete the following information):**
 - Statamic Version: Beta
 - Fresh Install or Upgrade: Fresh
 - OS: macOS 10.15.1
 - Browser: Firefox
 - Web Server: Valet
 - PHP Version: 7.1
 - Addons installed: N/A

**Additional context**

```
title: 'Supporting Assets'
fields:
  file_type:
    options:
      download: Download
      video: Video
    inline: false
    type: radio
    localizable: false
    width: 100
    display: 'File Type'
  file:
    mode: list
    restrict: false
    allow_uploads: true
    max_files: 1
    type: assets
    localizable: false
    width: 100
    display: File
```
