### ISSUE TITLE
Taggable field z-index issue

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#9594]
### Bug description

The taggable field seems to have a layering issue:

<img width="848" alt="Screenshot 2024-02-27 at 12 11 47" src="https://github.com/statamic/cms/assets/69107412/4e6ba6c0-265c-4b35-bc45-5068038becd7">

### How to reproduce

Add a taggable field followed by some others (in my case a section). 

### Environment

```yaml
Environment
Laravel Version: 10.45.1
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.4.6

Statamic
Addons: 8
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.50.0 PRO

Statamic Addons
edalzell/forma: 2.1
jonassiewertsen/statamic-livewire: 3.0.0
rias/statamic-color-swatches: 2.2.0
statamic-rad-pack/mailchimp: 4.1.1
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 5.0.2
studio1902/statamic-peak-seo: 8.2.0
studio1902/statamic-peak-tools: 4.4.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
