### ISSUE TITLE
Users with just view permissions can create draft entries in multisite

### ISSUE THREAD

**Issue by marcorieser** [statamic/cms#9602]
### Bug description

Given a multisite where a role has the permission on all sites but for a collection only the `view COLLECTION entries` permission. The user can now view an entry, everything is read-only but he/she can click in the sidebar to create an entry for another site (eg. origin is german and no entry exists for french). Now a draft gets created for the selected site. The user is not able to publish but the draft exists. 

### How to reproduce

- create a new Statamic site
- make it multisite (min. 2 sites)
- create a collection
- make sure entries do not get auto propagated
- create an entry for a site
- create a role with access to all sites but only the `view` permission for the collection
- assign that role to a user
- login as that user
- visit the created entry in the cp
- click in the sidebar on another site

### Environment

```yaml
Environment
Application Name: 24-7 Prayer CH
Laravel Version: 10.45.1
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: statamic-24-7prayer.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Livewire
Livewire: v3.4.6

Statamic
Addons: 3
Antlers: runtime
Sites: 3 (German, French, Italian)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.50.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.0.0
marcorieser/statamic-vitals: 1.1.0
marcorieser/tailwind-merge-statamic: 1.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
