### ISSUE TITLE
Conditional field dropdown includes fields from other sets in Replicator

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#9603]
### Bug description

When configuring conditions on a field in a Replicator set, the field dropdown suggests fields from other sets in the Replicator, rather than just fields from the *current* set.

Reported in #9592.

### How to reproduce

1. Go to edit a blueprint or fieldset
2. Add a Replicator field
3. Add two sets in the Replicator & add a few random fields in both of them.
4. Open the settings for one of the fields
5. Go to "Conditions" and attempt to configure a field condition.
6. See the dropdown contain fields from other sets.

Example repo: https://github.com/martyf/statamic-conditional-suggestions

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.45.1
PHP Version: 8.2.13
Composer Version: 2.6.3
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.x-dev Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
