### ISSUE TITLE
Glide cache not cleared on reupload if `append_original_filename` is enabled

### ISSUE THREAD

**Issue by daun** [statamic/cms#9609]
### Bug description

Reuploading an image will only clear the Glide cache for that image if the 'append-original-filename' feature is disabled.

- Glide cache cleared on reupload: `statamic.assets.image_manipulation.append_original_filename=false`
- Glide cache **not** cleared on reupload: `statamic.assets.image_manipulation.append_original_filename=true`

My assumption would be that the cache should be cleared for both setups.

### How to reproduce

**Reproduce behavior**

- Set `append_original_filename` to `true`
- Upload an image
- Render the image in a front-end view using the Glide image server
- Reupload the image, but e.g. rotated by 180deg
- Refresh the frontend page: the image rendition will be of the first image

**Reproduce expected behavior**

- Set `append_original_filename` to `false`
- Repeat the previous steps but with a different image
- Reuploading the image and refreshing the page will correctly show the second image

### Environment

```yaml
Environment
Application Name: App
Laravel Version: 10.46.0
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.50.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
