### ISSUE TITLE
Breaking change in preview targets

### ISSUE THREAD

**Issue by aerni** [statamic/cms#9613]
### Bug description

Turns out PR https://github.com/statamic/cms/pull/8742 was a breaking change for me. I've got a preview target that relies on data being augmented in the `resolvePreviewTargetUrl` method. Augmentation has been removed in that PR.

The `seo_social_images_theme` is a custom fieldtype wrapper that derives its default value from a subfield.

```php
{site:permalink}/social-images/{seo_social_images_theme}/open_graph/{id}
```

The field is added to the blueprint on `EntryBlueprintFound` event. Augmentation made it possible to have the field return its default value even if the field's value hasn't been saved on the entry.

### How to reproduce

This is happening as part of my Advanced SEO addon. So there are lots of moving parts and I don't quite know a good way to share how to reproduce this. I'm happy to whip up a basic repo that uses the addon so you can see it in action if that helps.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.16
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: statamic-advanced-seo.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.44.0 PRO

Statamic Addons
aerni/advanced-seo: dev-fix/multisite
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
