### ISSUE TITLE
Tags in conditions not working like they were before

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#9615]
### Bug description

After [v4.50.0](https://github.com/statamic/cms/releases/tag/v4.50.0), it seems like the Antlers syntax for using tags in conditions isn't working the same way. I believe it's related to the changes in #9504.

For example, with my Simple Commerce addon, both of these syntaxes used to work:

```antlers
Cart: {{ if {sc:cart:has} }} {{ sc:cart:id }} ({{ sc:cart:count }} items) {{ else }} None {{ /if }}
Cart: {{ if {sc:cart:has} === true }} {{ sc:cart:id }} ({{ sc:cart:count }} items) {{ else }} None {{ /if }}
```

However, now, after v4.50.0, only one of those syntaxes works:

```diff
+ Cart: {{ if {sc:cart:has} }} {{ sc:cart:id }} ({{ sc:cart:count }} items) {{ else }} None {{ /if }}
- Cart: {{ if {sc:cart:has} === true }} {{ sc:cart:id }} ({{ sc:cart:count }} items) {{ else }} None {{ /if }}
````

Simple Commerce's tags are a bit funky since they have two colons (I have the concept of subtags, so SC has one tag, then there's subtags for the cart/checkout form/coupons/etc). I don't know much about the Antlers parser but that might be throwing something off?

### How to reproduce

1. Create a new site using the Simple Commerce Starter Kit
    * `statamic new cms-9615 duncanmcclean/sc-starter-kit`
2. Open the site, go to the "Products" page and add a product to the cart
3. In the footer, you'll see "Cart:", which should be followed by your order ID. This is using the syntax which still works.
    * `Cart: {{ if {sc:cart:has} }} {{ sc:cart:id }} ({{ sc:cart:count }} items) {{ else }} None {{ /if }}`
5. In the `resources/views/layout/_footer.antlers.html` view, update line 21 to this:
    * `Cart: {{ if {sc:cart:has} === true }} {{ sc:cart:id }} ({{ sc:cart:count }} items) {{ else }} None {{ /if }}`
6. Go back to the site and see "Cart: None"

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.46.0
PHP Version: 8.2.13
Composer Version: 2.6.3
Environment: local
Debug Mode: ENABLED
URL: antlers-tags-in-conditions-bug.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: GBP
Gateways: Dummy
Repository: Customer: DuncanMcClean\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DuncanMcClean\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DuncanMcClean\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Free Shipping
Tax Engine: DuncanMcClean\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 1
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.51.0 PRO

Statamic Addons
duncanmcclean/simple-commerce: 6.0.8
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
