### ISSUE TITLE
Empty form submission broken with Laravel Precognition in 4.50

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#9627]
### Bug description

If I submit an empty form I don't get any errors returned anymore. This did work in previous versions.

### How to reproduce

1. Install peak
2. Go to forms
3. Hit submit on an empty form

### Environment

```yaml
Environment
Application Name: Statamic Peak Development
Laravel Version: 10.46.0
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.50.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 6.1.0
studio1902/statamic-peak-seo: 8.2.0
studio1902/statamic-peak-tools: 4.4.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
