### ISSUE TITLE
Toggle form validation broken with Laravel Precognition in 4.50

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#9628]
### Bug description

If I submit an un-toggled toggle form I don't get an error returned anymore. This did work in previous versions.

### How to reproduce

Install peak
Go to forms
Fill in some fields, don't accept the consent toggle
Hit submit

### Environment

```yaml
Environment
Application Name: Statamic Peak Development
Laravel Version: 10.46.0
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.50.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 6.1.0
studio1902/statamic-peak-seo: 8.2.0
studio1902/statamic-peak-tools: 4.4.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
