### ISSUE TITLE
`stache:warm` does not work properly in multisite setup (multisite entries not being "linked" anymore)

### ISSUE THREAD

**Issue by Sm1lEE** [statamic/cms#9631]
### What happened?

When clearing all cache via the Cache Manager in the CP in a multisite setup, the connection between origin and translated pages is lost. An additional `Stache Warm` via the Cache Manager sometimes help, but not reliably. The problematic behavior specifically occurs, when you have the Cache Manager and the origin page (CP) opened in two separate tabs.

I've seen this first happen to a bunch of websites after upgrading to Statamic v4.51.0. We noticed that after a `cache:clear` command, the language switch did not work anymore. After further testing, we discovered the previously mentioned behavior of unlinked translation pages.

### What did you expect to happen?

I expected that after clearing the cache, the stache would automatically be filled up when I visit related entries or pages. As described above, this did not happen.

https://github.com/statamic/cms/assets/2184676/67b00a06-abfc-4250-976c-f475b27ebb0c

### How to reproduce

- Install the [Multisimplicity Starter Kit](https://statamic.com/starter-kits/statamic/multisimplicity): `statamic new mysite statamic/starter-kit-multisimplicity`
- install node modules: `npm install`
- build: `npm run production`
- open the Cache Manager in the control panel in browser tab 1
- open the home page "About The Getaway" in the control panel in browser tab 2
- clear all cache using the "Clear All" button in the control panel
- refresh browser tab 2, containing the "About The Getaway" page -> **the connection between the english origin and the two translated languages is lost**
- when visiting the frontend, the language switch is missing in the header

I could "solve" the issue by warming the stache multiple times after clearing all cache. While doing this, I also noticed that the Content Stache size increased the first 3, 4 times.
Another way was to navigate to the "About The Getaway" page via the CP after clearing the cache instead of switching to the already opened second tab.

### Logs

```shell
No entries in the log file.
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.46.0
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: local
Debug Mode: OFF
URL: mysite.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 3 (The Getaway, Die Flucht, L'Escapade)
Stache Watcher: Disabled
Static Caching: half
Version: 4.51.0 PRO
```

### Installation

Starter Kit using via CLI

### Antlers Parser

Runtime (default)
