### ISSUE TITLE
Statamic 4.51.0 introduces issues with locale selector

### ISSUE THREAD

**Issue by axelferdinand** [statamic/cms#9651]
### Bug description

Updating from 4.50.0 to 4.51.0 causes my locale selector to not work in my multisite. The localized pages still work, but my locale selector didn't show any other language than the default lang after update.

```
<div class="locale" data-ng-controller="locale" data-ng-class="{'locale--expanded': locale}">
    <button class="locale__item locale__item--toggle" type="button" data-ng-click="toggleLocale();">
        <span class="locale__item__flag locale__item__flag--{{ locales }}{{ if is_current }}{{ locale:name }}{{ /if }}{{ /locales }}"></span>
    </button>
    <nav class="locale__selector">
        {{ locales }}
        {{ if is_current }}
        <button class="locale__item locale__item--active" type="button" data-ng-click="toggleLocale(); disableMenu(); disableNoScroll();">
            <span class="locale__item__flag locale__item__flag--{{ locale:name }}"></span>
            <span class="locale__item__name">{{ locale:name }}</span>
        </button>
        {{ else }}
        <a class="locale__item" href="{{ url }}">
            <span class="locale__item__flag locale__item__flag--{{ locale:name }}"></span>
            <span class="locale__item__name">{{ locale:name }}</span>
        </a>
        {{ /if }}
        {{ /locales }}
    </nav>
</div>
```

### How to reproduce

Update from 4.50.0 to 4.51.0

### Environment

```yaml
Environment
Application Name: NAC
Laravel Version: 10.46.0
PHP Version: 8.3.3
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: nac.proto
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: postmark
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Sites: 3 (Norsk, English, Deutsch)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.50.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
doublethreedigital/duplicator: 4.0.1
mitydigital/sitemapamic: 2.3.9
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
