### ISSUE TITLE
Error using multiple guards for users

### ISSUE THREAD

**Issue by danielreales7** [statamic/cms#9664]
### Bug description

I have been setting up my user.php and auth.php to have multiple guards in my Statamic application. I have followed the documentation, and this is my code:

users.php:
```
'repository' => 'file',
'guards' => [
        'cp' => 'statamic',
        'web' => 'web',
    ],
```

auth.php:
```
'defaults' => [
        'guard' => 'web',
        'passwords' => 'resets',
    ],

'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'statamic' => [
            'driver' => 'session',
            'provider' => 'statamic',
        ]
    ],
 'providers' => [
        'users' => [
             'driver' => 'eloquent',
             'model' => App\Models\User::class,
        ],

        'statamic' => [
            'driver' => 'statamic',
        ],
    ],
```

The issue arises when I use {{ user:register_form }}, it always stores the users as .yaml instead of in the database. If I try to change 'repository' to eloquent, it throws an error:

call_user_func_array(): Argument #1 ($callback) must be a valid callback, first array member is not a valid class name or object

This error is because:
 'model' => App\Models\User::class, is null.

### How to reproduce

The repository contains a clean installation of Statamic v4.45, and I have followed the steps from this link:
[https://statamic.dev/tips/using-an-independent-authentication-guard](https://statamic.dev/tips/using-an-independent-authentication-guard)

And from this link:
[https://statamic.dev/tips/storing-users-in-a-database](https://statamic.dev/tips/storing-users-in-a-database)
but without adding $table->uuid('id')->change(); since I am not transferring the .yaml users.

### Logs

```shell
[2024-03-04 09:38:09] local.ERROR: call_user_func_array(): Argument #1 ($callback) must be a valid callback, first array member is not a valid class name or object {"exception":"[object] (TypeError(code: 0): call_user_func_array(): Argument #1 ($callback) must be a valid callback, first array member is not a valid class name or object at /Proyectos/test/vendor/statamic/cms/src/Auth/Eloquent/UserRepository.php:55)
[stacktrace]
```

### Environment

```yaml
Environment
Application Name: The Musical Boxes
Laravel Version: 10.41.0
PHP Version: 8.1.26
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: themusicalboxes.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.45.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 4.1.0
studio1902/statamic-peak-seo: 8.0.0
studio1902/statamic-peak-tools: 4.2.0
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
