### ISSUE TITLE
Custom CP nav features: nav items get no icon

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#9667]
### Bug description

I created a Nav item to group a few content structures within the CP navigation. However, nav items get no default icon at all. I'm aware that there's a (stale) [PR](#8023) in the works to set a custom icon, but I feel it should at least default to something. 

This is my nav in the CP nav editor:
<img width="957" alt="Screenshot 2024-03-05 at 11 22 37" src="https://github.com/statamic/cms/assets/69107412/fa3bf36c-9f3b-4040-9ab0-1ce4d31c0bad">

This is how it looks in the actual CP nav:
<img width="211" alt="Screenshot 2024-03-05 at 11 20 08" src="https://github.com/statamic/cms/assets/69107412/0f16b5ba-54e7-4e51-bbd7-cc76ed586dd5">

This is the data:
```yaml
nav:
  content:
    reorder: true
    items:
      'content::collections': '@inherit'
      'content::pricing':
        action: '@create'
        display: Pricing
        url: collections/tiers
        children:
          'content::collections::tiers': '@move'
          'content::collections::features': '@move'
          'content::taxonomies::groups': '@move'
```

### How to reproduce

Create a nav item under a section. Group some collections or taxonomies under it. 

### Environment

```yaml
Environment
Laravel Version: 10.46.0
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Locales
Installed
LaravelLang\Actions\Plugin: 1.5.2
LaravelLang\Attributes\Plugin: 2.9.4
LaravelLang\HttpStatuses\Plugin: 3.8.1
LaravelLang\Lang\Plugin: 13.12.0
Locales Version: 1.9.0
Protected
Publisher Version: 15.0.2

Livewire
Livewire: v3.4.6

Statamic
Addons: 7
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.52.0 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 2.3.0
jonassiewertsen/statamic-livewire: 3.0.0
rias/statamic-color-swatches: 2.2.0
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 7.0.0
studio1902/statamic-peak-seo: 8.2.0
studio1902/statamic-peak-tools: 5.0.1
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
