### ISSUE TITLE
404 error on item view after first save - using static cache (half strategy) 

### ISSUE THREAD

**Issue by jamie-b5** [statamic/cms#9668]
### Bug description

We are using static caching. Half strategy.

When we add an item to a collection and hit save the front end item url throws a 404. It does this until we save the item a second time, at which point the url resolves to the correct record.

### How to reproduce

1. Enable static caching (half strategy)
2. Create a new record in a collection
3. Visit the url of the item (front end) - this shows a 404
4. Save the record a second time
5. Visit the url of the item - now works

### Environment

```yaml
Environment
Application Name: Dave Whyte Animation
Laravel Version: 9.52.16
PHP Version: 8.1.21
Composer Version: 2.4.2
Environment: production
Debug Mode: OFF
URL: davewhyteanimation.com
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Disabled
Static Caching: half
Version: 4.52.0 PRO
```

### Installation

Other (please explain)

### Antlers Parser

None

### Additional details

Statamic install - cloned from a slightly earlier repo then updated.
