### ISSUE TITLE
No Search Results if the Input Contains a Slash

### ISSUE THREAD

**Issue by maltemichels** [statamic/cms#9674]
### Bug description

If I'm using the inbuilt local search driver and searching for a string which contains slashes, I get no results, because the slashes get escaped but the search input doesn't.

Context: I've tried to enable searching for an DOI (Digital Object Identifier) which looks like this: `10.14361/9783839466711`
Within the search index it get’s escaped to: `10.14361\/9783839466711`

### How to reproduce

1. Using a simple search form
2. Typing for example `10.14361/9783839466711` in the title of an entry
3. Search for `10.14361/9783839466711` returns no results

### Environment

```yaml
Environment
Laravel Version: 10.46.0
PHP Version: 8.1.27
Composer Version: 2.3.10
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.51.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
