### ISSUE TITLE
Global variable overriding form submission value

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#9696]
### Bug description

Form submissions are now sending to the client's email address instead of the recipient's email. It seems that the receipient {{ email }} value is being overridden by the global data.

It looks like this might be a result of https://github.com/statamic/cms/pull/8892.

### How to reproduce

1. Add a global email field to globals/global.yaml:

```
sections:
  main:
    display: Main
    fields:
      -
        handle: email
        field:
          type: text
          width: 33
```

2. Add email field to form:

```
title: 'Request Report'
sections:
  main:
    display: Main
    fields:
      -
        handle: email
        field:
          type: text
          display: Email
          validate: email|required
          instructions_position: above
          listable: true
          visibility: visible
          always_save: false
          input_type: text
          antlers: false
```

3. Create form email to send to recipient email:

```
email:
  -
    to: '{{ email }}'
    cc: raziel@burlingameproperties.com
    subject: '{{ community | title }} Annual Report'
    template: email/report-download
    html: email/annual/report
    text: email/annual/report-text
```

4. Email sends to Global {{ email }} value.

### Environment

```yaml
Environment
Application Name: Burlingame
Laravel Version: 9.52.16
PHP Version: 8.2.16
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: burlingame.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 17
Antlers: runtime
Sites: 1
Stache Watcher: Disabled
Static Caching: full
Version: 4.52.0 PRO

Statamic Addons
aerni/advanced-seo: 2.3.0
aerni/livewire-forms: 8.1.0
aerni/social-links: 3.1.0
aerni/zipper: 2.3.0
duncanmcclean/static-cache-manager: 3.1.2
edalzell/forma: 2.1
jacksleight/statamic-bard-texstyle: 3.1.3
jacksleight/statamic-miniset: 1.0.0
jonassiewertsen/statamic-livewire: 2.12.0
justbetter/statamic-image-optimize: 2.1.1
mikemartin/helpscout-beacon: 1.0.3
mitydigital/statamic-logger: dev-main
rias/statamic-color-swatches: 2.2.0
rias/statamic-redirect: 3.2.0
siterig/mailerlite: dev-main
swiftmade/statamic-clear-assets: 2.0.0
webographen/statamic-widget-continue-editing: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
