### ISSUE TITLE
Fields behind a revealer losing data

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#9697]
### Bug description

Similar to this issue: https://github.com/statamic/cms/issues/8615, I've noticed fields behind a revealer losing data again. This is critical, because in this case of Peak sites, all buttons on a page lose their entry field data. This causes all buttons on a page to lose their links, without the editor noticing. They only notice the next time they try to save the page as they then get greeted with a validation error for each button on the page.

The issue is: I do not know how replicate this issue, a customer just tells me this keeps happening. They're also not sure how/why. I've tried to trigger it changing the order of replicator fields (like in the original issue) but wasn't successful in triggering the issue that way.

But I figured let's report it anyways in case someone can think of a recent PR that might cause this behaviour. 

<img width="835" alt="Screenshot 2024-03-11 at 10 45 44" src="https://github.com/statamic/cms/assets/69107412/cd198f3e-a866-4f04-8ee9-f8dace77eb80">

### How to reproduce

I can't yet. Will update when I have more info. 

### Environment

```yaml
Environment
Laravel Version: 10.47.0
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.4.8

Statamic
Addons: 8
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.52.0 PRO

Statamic Addons
edalzell/forma: 2.1
jonassiewertsen/statamic-livewire: 3.1.0
rias/statamic-color-swatches: 2.2.0
statamic-rad-pack/mailchimp: 4.1.1
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 7.2.0
studio1902/statamic-peak-seo: 8.2.1
studio1902/statamic-peak-tools: 5.1.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by duncanmcclean** [comment]
Do you know if this issue only happens with the Entry fieldtype, or does it happen with other fieldtypes too?

**Comment by robdekort** [comment]
Good question. I don't know unfortunately, I think the client in this case only used the Entry fieldtype behind the revealer. I just assumed it regarded all fields behind the revealer.

**Comment by robdekort** [comment]
Oh, I can see in the data that everything behind the revealer got trashed:
```yaml
page_builder:
  -
    id: lrzf3si7
    cards:
      -
        id: lrzf42ub
        button:
          -
            id: lrzf5g6u
            label: 'Find out more'
```
