### ISSUE TITLE
Reorganizing assets in CP don't update any paths (at all)

### ISSUE THREAD

**Issue by axelferdinand** [statamic/cms#9701]
### Bug description

I just did a major restructuring within my Assets in CP, solely using the CP moving assets. According to the docs, paths to images are supposed to update, but (almost) all my assets are now unlinked in front-end.. 

I'm using the Assets fieldtype and Bard. I can share repo access, if wanted.

### How to reproduce

(see above)

### Logs

```shell
No logs
```

### Environment

```yaml
Environment
Application Name: NAC
Laravel Version: 10.47.0
PHP Version: 8.3.3
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: nac.proto
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: postmark
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Sites: 3 (Norsk, English, Deutsch)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.52.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
doublethreedigital/duplicator: 4.0.1
mitydigital/sitemapamic: 2.3.9
```

### Installation

Existing Laravel app

### Antlers Parser

None
