### ISSUE TITLE
Adding a new filter view with a name that already exists overwrites the existing one

### ISSUE THREAD

**Issue by mgschoen** [statamic/cms#9703]
### Bug description

In the entry listing, users can save a combination of filters as view and give them names. Whenever a user adds a new view and enters a name that already exists in their user preferences, Statamic replaces the existing view instead of appending a new one.

This problem can't even be bypassed by renaming the existing view first – if the new view's name is identical to the _original_ name of the existing view, the existing one will still be overwritten.

I would expect the "Create New View" functionality to always add a new view to the list – regardless of the name I choose.

### How to reproduce

- Go to any collection's entry listing
- Select some filters
- Click "Create New View"
- Enter Name "One"
- Rename your view: Open the context menu, select "Rename" and enter "Two". Click "Rename"
- Select "All"
- Select some different filters
- Click "Create New View" 
- Enter Name "One"
- Observe how the existing view named "Two" gets overwritten

https://github.com/statamic/cms/assets/22660469/f91e0a91-1463-4797-87f9-8cd7ba425a9d

### Environment

```yaml
Laravel Valet, plain Statamic installation following https://statamic.dev/quick-start-guide
```

### Installation

Starter Kit using via CLI

### Antlers Parser

Runtime (default)

### Additional details

I noticed filters get stored in an object in user preferences. The keys in this object are slugified variants of the name the user entered when creating the filter.

```yaml
preferences:
  collections:
    pages:
      filters:
        one: # <- this is the key I am talking about
          display: One
          filters:
            ...
        two:
          display: Two
          filters:
            ...
```

When I _rename_ a filter, the `display` value changes, but the key remains the same. If I renamed "One" to "Three" in the example above, the resulting yaml would be

```yaml
...
one: # remains the same
  display: Three # changes
  filters:
    ...
```

If I were to create a new filter called "One" now, I would accidentally overwrite my existing "Three" filter.
