### ISSUE TITLE
Navigation not viewable/editable via CP

### ISSUE THREAD

**Issue by mscruse** [statamic/cms#9708]
### Bug description

Since updating to 4.53.0 when going into the Navigation section of CP and viewing a Nav the tree is not displayed.

<img width="949" alt="Screenshot 2024-03-12 at 09 23 12" src="https://github.com/statamic/cms/assets/22737928/ce5f9359-1771-4630-aed2-76836bd077cc">

### How to reproduce

Update to 4.53.0 - go to Navigation and into a Nav.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.47.0
PHP Version: 8.2.1
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: conference.cica.com.au.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.53.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
mitydigital/iconamic: 1.1.6
mitydigital/statamic-google-fonts: 1.0.3
mitydigital/supportamic: 1.0.4
statamic/seo-pro: 5.4.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

Have tried this on several sites. Rolling back to 4.52.0 solves the issue.
