### ISSUE TITLE
New replicator UI has group description tooltip wrongly positioned

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#9713]
### Bug description

In the (cool) new replicator / bard ui, the question mark icon that shows the group description is wrongly positioned:
<img width="651" alt="Screenshot 2024-03-12 at 13 49 52" src="https://github.com/statamic/cms/assets/69107412/a490d6ce-446d-4b88-ad35-22c3cc323430">

### How to reproduce

Add groups
Give groups a description
Add a set from a group to your replicator
See wonky ❓

### Environment

```yaml
Environment
Application Name: Statamic Peak Development
Laravel Version: 10.47.0
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.53.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 7.2.0
studio1902/statamic-peak-seo: 8.2.1
studio1902/statamic-peak-tools: 5.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
