### ISSUE TITLE
Trouble uploading assets (.vcf file in my case)

### ISSUE THREAD

**Issue by japgroevemaker** [statamic/cms#9719]
### Bug description

![image](https://github.com/statamic/cms/assets/22168803/13aeebc1-f6e3-4cab-b9f8-294b9701f616)
I'm having trouble uploading .vcf (vcard) files. It keeps telling me that the given data is invalid.

In previous versions of statamic i didn't have this issue. An older project which is running on version 3.3.48 is handling .vcf files just fine.

### How to reproduce

Create a asset container with the following settings: 
![image](https://github.com/statamic/cms/assets/22168803/1897a023-bfcb-4234-a022-46fcfba255a2)

Next thing, create an asset field in a blueprint with these settings: 
![image](https://github.com/statamic/cms/assets/22168803/b6604d41-3cc4-40e1-9e27-8d638d4dcd84)

After that try to upload a .vcf file (vcard). This is the vCard of Apple Benelux in case you don't have a vCard  available. It is zipped because, ironically, GitHub doesn't accept the .vcf file format 
[apple.zip](https://github.com/statamic/cms/files/14578422/apple.zip)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.2
PHP Version: 8.2.8
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: base.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Sites: 2 (nl, en)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.53.1 PRO

Statamic Addons
statamic/eloquent-driver: 3.3.2

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
