### ISSUE TITLE
A field with a handle of page_builder already exists in version 4.53.1

### ISSUE THREAD

**Issue by tochkitx** [statamic/cms#9725]
### Bug description

Hello,

I had Statamic CMS version 4.47.0 installed and in it I had a fieldset with handle page_builder (it's a repeater with all the other fieldsets in it linked). After the update to version 4.53.1 I'm getting the error:

`A field with a handle of page_builder already exists`

and I cannot add more linked fieldsets to that page_builder fieldset.

After downgrading Statamic to 4.47.0 everything works fine.

### How to reproduce

Create fieldset with handle page_builder as a repeater and link another fieldset inside that fieldset.
Update statamic from version 4.47.0 to 4.53.1 and try to add new fieldset to page_builder fieldset.

### Environment

```yaml
I don't have details for the 4.53.1 version because I downgraded it back to 4.47.0

Details for downgraded version are:

Environment
Application Name: Kontron
Laravel Version: 10.48.2
PHP Version: 8.2.16
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: kontron-cms.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.47.0 PRO

Statamic Addons
eminos/statamic-tabs: 1.1.0
statamic/eloquent-driver: 3.0.5

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
