### ISSUE TITLE
Additional select field values never register as numeric.

### ISSUE THREAD

**Issue by AaronAtkinson** [statamic/cms#9727]
### Bug description

When using a [select field](https://statamic.dev/fieldtypes/select) with "allow additions" enabled, the [is_numeric modifier](https://statamic.dev/modifiers/is_numeric) fails to return true when a custom numeric value is provided in the select field.

### How to reproduce

In the cp, add a select field (handle = max_width), check the option "allow additions".
In an antlers template use the "is_numeric" modifier to evaluate if the select field's value is numeric.

ex:
```
{{ if max_width | is_numeric }}
   The value is numeric!
{{ else }}
   The value is not numeric!
{{ /if }}
```

Back in the control panel enter a custom numeric value in the select field (ex: 300).
The modifier fails to detect additional values as numeric. 

### Environment

```yaml
Environment
Application Name: Test
Laravel Version: 10.45.1
PHP Version: 8.2.10
Composer Version: 2.6.2
Environment: local
Debug Mode: ENABLED
URL: 127.0.0.1:8000/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.52.0 PRO

Statamic Addons
eminos/statamic-tabs: 1.1.0
goldnead/statamic-collapse-fieldtype: 1.0.5
```

### Installation

Existing Laravel app

### Antlers Parser

Runtime (default)

### Additional details

No sure if I'm doing something wrong here. The modifier correctly catches anything I've attempted similarly using variables

ex:
```
{{ maxWidth = 300}}
{{ if maxWidth | is_numeric }}
   The value is numeric!
{{ else }}
   The value is not numeric!
{{ /if }}
```
```
{{ maxWidth = "300"}}
{{ if maxWidth | is_numeric }}
   The value is numeric!
{{ else }}
   The value is not numeric!
{{ /if }}
```
Both correctly return the is_numeric block
