### ISSUE TITLE
Hiding the only Blueprint in a Collection leads to a fatal error

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/cms#9735]
### Bug description

Like the title says, if you use the available toggle to hide the only Blueprint you get an error after the fact that you can't hide the only Blueprint for a Collection.

### How to reproduce

1. Create a collection
2. Edit the blueprint for the collection
3. Toggle the "Hidden" toggle and save
4. Visit the collection page - a fatal error is received

### Environment

```yaml
Environment
Application Name: Website
Laravel Version: 10.48.2
PHP Version: 8.2.12
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: website.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Statamic
Addons: 18
Antlers: runtime
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.53.2 PRO

Statamic Addons
aerni/social-links: 3.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

I realize the appropriate measure is do some validation on the Blueprint create/edit page, but I personally would prefer if you *could* hide the only blueprint and instead it would make the Collection read only (ie. entries are created programmatically) by hiding the "Create Entry" button and disabling the create/edit endpoint for that Collection.
