### ISSUE TITLE
Unvalid HTML generated for CSRF input

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#9762]
### Bug description

Hi there,

As explained in [the Statamic doc here](https://statamic.dev/tags/form-create#overview):

> When using `form:create` tag, Statamic will automatically take care of opening your form with a proper [CSRF token](https://laravel.com/docs/csrf) .

Unfortunately the generated HTML seems to not be valid:

```html
<input type="hidden" name="_token" value="cN03woeRj5Q0GtlOj7GydsZcRwlyp9VLzfpwDFJZ" autocomplete="off">
```
 
As `autocomplete="off"` should not be used on `<input type="hidden">`.

### How to reproduce

Just create a form with the `form:create` tag.

### Environment

```yaml
Environment
Application Name: Jean-Marie Belloteau
Laravel Version: 10.48.3
PHP Version: 8.3.4
Composer Version: 2.7.2
Environment: local
Debug Mode: ENABLED
URL: immersion-pictures.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: null
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 1
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.53.2 PRO

Statamic Addons
statamic/seo-pro: 5.4.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
