### ISSUE TITLE
Text disappears in Bard field when entering Japanese characters in Safari 

### ISSUE THREAD

**Issue by schwemmer** [statamic/cms#9769]
### Bug description

When entering Japanese text in Safari (all versions), the IME (input method editor) appears with a dropdown of selections. After entering the Japanese text, you have to hit enter to accept the text. This works fine in Chrome and Firefox but in Safari, the text disappears. 

This started happening in v4.45 and did not happen before. After some digging, we found #9344 to be the cause of this. It is line 372 in resources/js/components/fieldtypes/bard/BardFieldtype.vue

This was introduced to fix an issue with dirty state but it seems that this.value is not properly updated in Safari with IME. We tried to fix it but could not find the best way to fix it.

### How to reproduce

- Use Safari on MacOS or iOS
- Create a Pages collection
- Add a "Content" field of type "Bard"
- Create an Entry and type in some Japanese characters
- Hit enter
- The text disappears

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 9.52.16
PHP Version: 8.1.6
Composer Version: 2.3.5
Environment: local
Debug Mode: ENABLED
URL: localhost:8003
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.45.0 PRO
```

### Installation

Existing Laravel app

### Antlers Parser

Regex (legacy)
