### ISSUE TITLE
Control panel OAuth login not working when using independent authentication guard

### ISSUE THREAD

**Issue by helloiamlukas** [statamic/cms#9773]
### Bug description

Currently it is not possible to use the OAuth login when using an [independent authentication guard](https://statamic.dev/tips/using-an-independent-authentication-guard).

The [OAuthController](https://github.com/statamic/cms/blob/4.x/src/Http/Controllers/OAuthController.php) always uses the default Laravel authentification guard defined in `auth.defaults.guard`, no matter what is defined in `statamic.users.guards.cp`.

I already tried to fix this [here](https://github.com/statamic/cms/pull/9717), but unfortunately it had unexpected side effects.

### How to reproduce

1. Setup OAuth as described in the [docs](https://statamic.dev/oauth)
2. Setup an independent authentication guard as described in the [docs](https://statamic.dev/tips/using-an-independent-authentication-guard)
3. Use the OAuth login for the control panel guard (has to be configured via `statamic.users.guards.cp`)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.4
PHP Version: 8.1.26
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: mysite.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.54.0 Solo
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
