### ISSUE TITLE
Assets Upload Button in CP Not Working

### ISSUE THREAD

**Issue by DuyTr** [statamic/cms#9779]
### Bug description

I noticed the Upload button didn't work in any of our company's projects.

So I clone from Statamic repository for a fresh install, also doesn't work.... 

### How to reproduce

Log in to CP > Visit an asset container > Click Upload Button > Nothing Happens 

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.4
PHP Version: 8.2.10
Composer Version: 2.3.7
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.54.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
