### ISSUE TITLE
Renaming handle for replicator sets results in hidden sets in editor

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/cms#9783]
### Bug description

Currently if you rename a set while it is in use, the content will remain in the entry file but the set will disappear from the backend.  I would imagine it will do the same if you deleted it.

Renaming replicator (and maybe Bard?) sets should either rename all instances of the set in use, warn you about renaming a set that is in use, or not allow you to rename the set if it is in use (least desirable).

Another solution would be to have a similar UI to the invalid set (ie. red background with a little preview of the content of the invalid set).  This would at least allow one to delete the renamed/deleted set and have a valid set of content again.

Personally I would prefer to have a warning about renaming/deleting in use sets and then have a ui to delete the set's in the entry editor after the fact.

### How to reproduce

1. Create a blueprint with a replicator and at least 2 sets in the replicator
2. Save a new entry using the blueprint and add one of each of the types of sets
3. Go back to the blueprint and rename one of the sets
4. Going back to editing the entry will show the set is gone, saving the entry will not get rid of the hidden set.

### Environment

```yaml
Environment
Application Name: Website
Laravel Version: 10.48.4
PHP Version: 8.2.12
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: website.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Statamic
Addons: 20
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.54.0 PRO

Statamic Addons
godismyjudge95/statamic-embera: 1.0.0
godismyjudge95/statamic-tailwind-dev-mode: 1.0.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
