### ISSUE TITLE
Unable to queue EntrySaved listener when collection has no route

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#9787]
### Bug description

If you add the `ShouldQueue` trait to an `EntrySaved` listener and the entry being saved belongs to a collection with no route set you will get a `Serialization of 'Closure' is not allowed ` error when saving.

This happens because in `EntriesController` the entries `slug` property is set to a closure. If the collection has a route set the slug getter is called during `validateUniqueUri`/`entryUri` and that replaces the closure with its return value. But if the collection has no route set the getter is never called so the closure is left behind, causing a serialisation error when the job is queued.

### How to reproduce

1. Create a collection with no route set
2. Create an entry
3. Add an `EntrySaved` listener that implements `ShouldQueue`
4. Try to save the entry

### Environment

```yaml
Statamic
Addons: 9
Antlers: runtime
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.53.2 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
