### ISSUE TITLE
Translations of frontend form error messages not working with 4 character language code

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#9789]
### Bug description

Error messages in a front end form with…
```
{{ errors }}
    {{ value }}<br>
{{ /errors }}
```
…are not translated, even if you have a validation.php file in a folder `/lang/de_CH/validation.php`. The error messages shows up in english instead. It looks like the folder name `de_CH` is the problem. If you change the folder name to `de` the translations are working fine. 

It does not matter whether you use `de` or `de_CH` in your `/config/sites.php`.

### How to reproduce

1. Change your site locale to `'locale' => 'de_CH',` in sites.php.
2. Create a {{ form:create… }} in a template view. Some of the form input fields are required and this is set up in your blueprint.
3. Create a validation.php file with your translations in `lang/de_CH/validations.php`.
4. Fill out the form. The default error message (i.e. "The XY field is required.") shows up in englisch.
5. Change folder name to `/de` and fill in the form again. The translation is now taken into account.

### Environment

```yaml
Environment
Application Name: Kochort CMS
Laravel Version: 10.48.4
PHP Version: 8.3.4
Composer Version: 2.6.2
Environment: local
Debug Mode: ENABLED
URL: kochort.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.54.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
