### ISSUE TITLE
File-Field "Upload File"-Link doesn't work

### ISSUE THREAD

**Issue by priskahuber** [statamic/cms#9794]
### Bug description

I've updated my Statamic CMS to 4.54.0 and tested it.
But i can't click on "Upload File" Link. I can click on the Button and drag & drop does work too, but not the link.
And after i clicked on the link an nothing happens I can't click on "Open Link", it wont open anything that opens a external window.
I inspected it and found the warning "window.open blocked due to active file chooser.". But there isn't any file chooser.
![ ](https://github.com/statamic/cms/assets/17765613/6a761595-81ce-43a7-9c2f-1d0c21da2c2a)
![Bildschirmfoto 2024-03-27 um 07 05 52](https://github.com/statamic/cms/assets/17765613/e86e08af-5932-4f63-929c-a73a5cce2877)

### How to reproduce

Update to 4.54.0 and click on link of a File-Field. It won't open File Browser.
After that try to click on "Open Url" 

### Environment

```yaml
Environment
Application Name: Doku-Tool Zukunftsbaumarten
Laravel Version: 9.52.16
PHP Version: 8.1.23
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: dokutool.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Sites: 2 (Deutsch, Français)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.54.0 PRO

Statamic Addons
b7k/excelimport: dev-master
statamic/collaboration: 0.8.1
stillat/relationships: 2.1.4
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
