### ISSUE TITLE
Can't sort assets once you've selected some

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#9801]
### Bug description

When you're in an asset field choosing assets, once you've chosen some, you can't sort (the headers disappear).

This makes choosing additional assets (especially newly uploaded ones) very time consuming.

### How to reproduce

1. Put an asset field in an entry blueprint, set to allow multiple assets.
2. Choose one asset
3. Notice you can't sort now

### Environment

```yaml
Environment
Application Name: Zakat Foundation of America
Laravel Version: 10.46.0
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: zakat.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 11
Antlers: runtime
Sites: 3 (zakat.org (EN), zakat.org (AR), zfinstitute.com (ZFI))
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.52.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
edalzell/forma: 2.1
jonassiewertsen/statamic-livewire: 2.12.0
statamic-rad-pack/runway: 6.4.1
statamic/seo-pro: 5.4.1
transformstudios/events: 5.3.3
transformstudios/front: 2.0.4
transformstudios/github: dev-main
transformstudios/neon: dev-fix/runway-update
transformstudios/review: 4.1.4
transformstudios/simple: 4.20.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
