### ISSUE TITLE
Renaming a Replicator set does not rename the usages of it across the site content

### ISSUE THREAD

**Issue by aaronbushnell** [statamic/cms#9807]
### Bug description

This might be intended behavior due to how Statamic stores content, but I've noticed that renaming a Replicator set doesn't seem to update the name within content entries that use it.

### How to reproduce

- Create a "Page Builder" Replicator fieldtype
- Add a "Testimonial" set 
- Create an entry that uses a "Testimonial" set
- Rename the "Testimonial" set to "Testimonials" (maybe one day you decide this should support multiple!)
- The block is either missing or broken on entries using this block because they didn't get renamed from `testimonial` to `testimonials`

### Environment

```yaml
Environment
Application Name: Statamic Starter
Laravel Version: 10.48.4
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: production
Debug Mode: ENABLED
URL: statamic-starter.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Session: file

Statamic
Addons: 7
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.55.0 PRO

Statamic Addons
bencarr/statamic-hyperlink: 2.0.1
rias/statamic-redirect: 3.6.2
statamic/seo-pro: 5.4.1
trendyminds/guide: dev-main
trendyminds/nerf: dev-main
trendyminds/statamic-palette: 1.0.4
trendyminds/tip: dev-main
```

### Installation

Other (please explain)

### Antlers Parser

Runtime (default)
