### ISSUE TITLE
Redirect fields that redirect to "First Entry" do not propagate to non-origin site entries

### ISSUE THREAD

**Issue by schwemmer** [statamic/cms#9813]
### Bug description

This is a bit of an edge case. When you redirect a page to the first entry, non-origin site entries need to be re-saved so that the 'redirect' property is explicitly added to the non-origin site entries (even though the Redirect field is not set to "localizable"). 
Alternatively, the content files for non-origin site entries need to be modified to include `redirect: '@child'`

### How to reproduce

- You need at least two languages (multi-site)
- Create a blueprint "Page: Redirect" or similar 
- Add a "Title" field
- Add a "Redirect Field", do not make it localizable
  - <img width="914" alt="Bildschirmfoto 2024-04-03 um 16 04 52" src="https://github.com/statamic/cms/assets/725398/f1f07605-d0cd-4bd9-b960-d300060c7d42">

- Create a page of type "Page: Redirect"
- Select "First Entry" from the "Redirect" field's dropdown menu
  - <img width="1244" alt="Bildschirmfoto 2024-04-03 um 16 05 07" src="https://github.com/statamic/cms/assets/725398/884b4a48-d7a3-4048-b8aa-b0443a80a718">
- Save the page
- Load the page in another language
- The "First Entry" is not propagated

### Environment

```yaml
Environment
Application Name: Example Application
Laravel Version: 10.43.0
PHP Version: 8.2.15
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: localhost:8003
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Pulse
Enabled: ENABLED
Version: v1.0.0-beta14

Livewire
Livewire: v3.4.4

Statamic
Addons: 3
Antlers: runtime
Sites: 2 (en, jp)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.55.0 PRO

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.1.6
```

### Installation

Existing Laravel app

### Antlers Parser

Runtime (default)
