### ISSUE TITLE
Removing sets from Bard causes errors

### ISSUE THREAD

**Issue by Diewy** [statamic/cms#9814]
### Bug description

Once a set within a Bard field is used, the set can't be removed anymore. When opening an entry with a Bard field with a non-existing set, the field doesn't initialize and can't be edited. 

### How to reproduce

1. Create a fieldset with a Bard field
2. Add sets that can be added in the Bard field
3. Create an entry, including the Bard field and the set.
4. Remove the set from the field.
5. Go to the entry -> Can't edit the Bard field anymore due to errors

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.4
PHP Version: 8.3.3
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: 
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Sites: 6 (Main - English, Main - Dutch, Main - French, and 3 more)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.55.0 PRO

Statamic Addons
doefom/currency-fieldtype: 1.2.3
jacksleight/statamic-bard-texstyle: 3.1.6
statamic/ssg: 2.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
