### ISSUE TITLE
Git integration throwing error unnecessarily

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#9817]
### Bug description

Getting an error like this:

```
Error: {"message":"Process Class: Git\nCommand: 'git' 'push' '--porcelain'\nError: Warning: Permanently added the ECDSA host key for IP address '140.82.112.4' to the list of known hosts.","context":[],"level":400,"level_name":"ERROR","channel":"production","datetime":"2024-04-02T21:31:14.110384-07:00","extra":[]}
```

Any chance you folks can not throw that as an error?

### How to reproduce

1. Use git integration
2. there is no step 2

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.43.0
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: transform.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: daily
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 11
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.48.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
edalzell/forma: 2.1
jonassiewertsen/statamic-jobs: 1.4.0
jonassiewertsen/statamic-livewire: 2.12.0
statamic/seo-pro: 5.4.1
transformstudios/events: 5.2.0
transformstudios/front: 2.0.4
transformstudios/github: dev-main
transformstudios/review: 4.1.4
transformstudios/simple: 4.18.0
transformstudios/uptime: dev-production
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
