### ISSUE TITLE
When editing an existing filter, the display name may be mistakenly overwritten

### ISSUE THREAD

**Issue by wiebkevogel** [statamic/cms#9824]
### Bug description

In the listing of an entry, multiple views can be saved. For example, if a user has saved two views and makes a change to one view later on, the display name of that view will be replaced by another view.

https://github.com/statamic/cms/assets/54707973/e140d59c-45c7-48d6-937a-87797b282903

### How to reproduce

1. Open the list view of a collection
2. Apply some filters
3. Save these filters as "Filter Number 1"
4. Go back to "All"
5. Apply different filters
6. Save these filters as "Filter Number 2"
7. Go back to "Filter Number 1" and change a value
8. Save these changes using the "Save" button.
9. "Filter Number 1" no longer exists, and there are now two filters with the name "Filter Number 2"

### Environment

```yaml
Laravel Version: 10.48.4
PHP Version: 8.3.4
Composer Version: 2.7.2

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.55.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

**Saved Preferences Before:**
```yaml
    filters:
        view_2024_10:
          display: 'View 2024/10'
          filters:
            fields:
              volume:
                operator: '='
                value: '2024'
              'null': null
              issue:
                operator: '='
                value: '10'
        view_2024_13:
          display: 'View 2024/13'
          filters:
            fields:
              volume:
                operator: '='
                value: '2024'
              'null': null
              issue:
                operator: '='
                value: '13'
```

**Saved Preferences After:**
```yaml
    filters:
        view_2024_10:
          display: 'View 2024/13'
          filters:
            fields:
              volume:
                operator: '='
                value: '2024'
              'null': null
              issue:
                operator: '='
                value: '200'
        view_2024_13:
          display: 'View 2024/13'
          filters:
            fields:
              volume:
                operator: '='
                value: '2024'
              'null': null
              issue:
                operator: '='
                value: '13'
```

**Blueprint:** 
```yaml
title: Issue
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: content
            field:
              type: markdown
              display: Content
              localizable: true
          -
            handle: author
            field:
              type: users
              display: Author
              default: current
              localizable: true
              max_items: 1
          -
            handle: template
            field:
              type: template
              display: Template
              localizable: true
          -
            handle: issue
            field:
              type: integer
              display: Issue
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: volume
            field:
              type: integer
              display: Volume
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'

```
