### ISSUE TITLE
 Icons are missing in My Preferences Save → Save to…

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#9825]
### Bug description

If you have roles and save preferences to a role the icons are missing in the dropdown.
<img width="993" alt="Bildschirmfoto 2024-04-05 um 10 03 16" src="https://github.com/statamic/cms/assets/8265902/26d5eca6-a14a-4d47-bd32-d3902bd64e46">

### How to reproduce

- Create a role
- Edit preferences
- ↓ Save to…

### Environment

```yaml
Application Name: Kochort CMS
Laravel Version: 10.48.4
PHP Version: 8.2.16
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: /
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.55.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
