### ISSUE TITLE
Button Group inside Grid renders too small

### ISSUE THREAD

**Issue by stefankempf** [statamic/cms#9830]
### Bug description

I added a button group inside a grid fieldtype and placed it to 50% width. I also have a conditionally shown textfield in the grid row (the issue is also happening when the textfield is always shown).

![Screenshot von 2024 04 05 um 21 14 21](https://github.com/statamic/cms/assets/20299885/dfca80b0-6039-47d6-b33d-3e19b1e1e941)

### How to reproduce

Add a grid fieldtype and place a button group with two options and a text field in it.

```
handle: its_me_the_button_group
            field:
              fields:
                -
                  handle: type
                  field:
                    options:
                      text: Text
                      umbruch: Umbruch
                    default: text
                    type: button_group
                    display: Typ
                    width: 50
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
                    validate:
                      - required
                -
                  handle: text_fragment
                  field:
                    input_type: text
                    antlers: false
                    type: text
                    display: Text-Fragment
                    width: 50
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
                    validate:
                      - 'required_if:{this}.type,text'
                    if:
                      type: 'equals text'
              mode: table
              reorderable: true
              fullscreen: true
              type: grid
              display: Animation
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
```

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Sites: 1
Version: 4.55.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
