### ISSUE TITLE
Paginator regression between v4.48 and v4.55

### ISSUE THREAD

**Issue by patrickomeara** [statamic/cms#9835]
### Bug description

I've just upgraded from v4.48 to v4.55 and the code I used to get the paginator is no longer working.

```php
        @php($articles = Statamic::tag('collection:articles')->paginate(10))
        {!! $articles['paginate']['auto_links']['paginator']->links() !!}
```

Is there a recommended way of using `Statamic::tag()` to get a custom pagination view?

When on v4.48 the custom view is used `resources/views/vendor/pagination/tailwind.blade.php`. But now the `LengthAwarePaginator` does not seem to be in the return array at all. Using `$articles['paginate']['auto_links']` doesn't use the custom view.

### How to reproduce

```php
        @php($articles = Statamic::tag('collection:articles')->paginate(10))
        {!! $articles['paginate']['auto_links']['paginator']->links() !!}
```

### Environment

```yaml
Environment
Application Name: Site
Laravel Version: 10.48.4
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: site.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: single
Mail: mailgun
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.55.0 PRO

Statamic Addons
statamic/seo-pro: 5.4.1
```

### Installation

Existing Laravel app

### Antlers Parser

None
