### ISSUE TITLE
Live Preview: Long set names cause overflow issues

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#9838]
### Bug description

When using Live Preview with Bard & Replicator fields with long set names, the toggle and "three dots" can sometimes overflow out of the live preview publish form container:

![image](https://github.com/statamic/cms/assets/19637309/38327b9a-1aa7-439f-87b6-aaa3bfc9eaf3)

Instead of overflowing, we should probably concatenate the set name and leave the toggle/three dots where they are. 

### How to reproduce

1. Add a Bard or Replicator field to a blueprint
2. Add a new set, with a relatively long name
3. Create/edit an entry
4. Add the set
5. Open Live Preview
6. Resize the publish form area
7. See the toggle/"three dots" overflow at a smaller size

### Environment

```yaml
Application Name: Duncan's Wonderful Sandbox
Laravel Version: 10.48.4
PHP Version: 8.3.0
Composer Version: 2.6.3
Environment: local
Debug Mode: ENABLED
URL: sandbox.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.x Pro
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
