### ISSUE TITLE
Full static cache + Live Preview + Ignore Query String (How to) 

### ISSUE THREAD

**Issue by stanbridge-wcorrea** [statamic/cms#9845]
### Bug description

Live preview is not showing the latest version since it relies on query string to load. 

I'm using full static cache strategy and I'm using the config "ignore_query_string" set to TRUE. 

### How to reproduce

Enable full static cache, set the config "ignore_query_string" to TRUE, try the live preview. 

### Environment

```yaml
Environment
Application Name: Stanbridge University
Laravel Version: 9.52.16
PHP Version: 8.2.6
Composer Version: 2.7.2
Environment: production
Debug Mode: OFF
URL: www.stanbridge.edu
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Sentry
Enabled: YES
Environment: production
Laravel SDK Version: 4.2.0
PHP SDK Version: 4.5.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 100%
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 5
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: full
Version: 4.48.0 PRO

Statamic Addons
duncanmcclean/cookie-notice: 8.1.1
duncanmcclean/static-cache-manager: 3.1.2
jacksleight/statamic-bard-mutator: 2.3.0
kind-work/two-fa: 1.5.1
mitydigital/statamic-two-factor: 1.1.4
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
