### ISSUE TITLE
Broken {{ glide:url }} returning empty string since v4.56.0

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#9846]
### Bug description

Since `v4.56.0`, the {{ glide:url }} tag seems to be broken as it output an empty string.

### How to reproduce

```twig
{{ image_src_tiny = {glide:media:url preset="original_ratio_360"} }}
{{ image_src_small = {glide:media:url preset="original_ratio_720"} }}
{{ image_src_medium = {glide:media:url preset="original_ratio_1440"} }}
{{ image_src_large = {glide:media:url preset="original_ratio_2880"} }}
{{ image_sizes = image_sizes ?? "100vw" }}
{{ image_srcset = "{image_src_tiny} 360w, {image_src_small} 720w, {image_src_medium} 1440w, {image_src_large} 2880w" }}
<img
     decoding="async"
     loading="{{ image_loading ?? "lazy" }}"
     src="{{ image_src_tiny }}"
     srcset="{{ image_srcset }}"
     sizes="{{ image_sizes }}"
     width="{{ media:width }}"
     height="{{ media:height }}"
     alt="{{ media:alt ?? media_caption }}"
/>
```

The above was working on `v4.55.0` but since `v4.56.0`, `glide:url` return an empty string:

```html
<img
     data-media
     decoding="async"
     loading="lazy"
     src=""
     srcset=" 360w,  720w,  1440w,  2880w"
     sizes="(min-width: 480px) 33vw, 100vw"
     width="3000"
     height="2001"
     alt=""
/>
```

### Environment

```yaml
Environment
Application Name: Jim Blue
Laravel Version: 10.48.4
PHP Version: 8.3.4
Composer Version: 2.7.2
Environment: local
Debug Mode: ENABLED
URL: jim-blue.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 1
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.56.0 PRO

Statamic Addons
statamic/seo-pro: 5.4.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
