### ISSUE TITLE
Collections "Max Depth" default results in errors when page depth > 1

### ISSUE THREAD

**Issue by sjclark** [statamic/cms#9847]
### Bug description

When a collections `Max Depth` is configured to be blank (ie. the default) creating any pages with a depth of more than one causes all pages site-wide to be unsaveable. Due to errors:
- On the Parent field: `This would exceed the maximum depth`
- In an error toast: `The given data was invalid`
- Nothing is logged in the laravel log or console

### How to reproduce

1. Download fresh latest statamic (4.56.0 at time of issue)
2. Make a page with children in the default collection (with `Max Depth` = infinite/blank; ie. default)
3. Attempt to edit any page collection-wide (of any depth) - and then receive errors and be unable to save any content

![Screenshot 2024-04-09 at 3 50 37 pm](https://github.com/statamic/cms/assets/4531017/d3080245-7e03-4128-80bb-7721a938f574)

![Screenshot 2024-04-09 at 3 47 32 pm](https://github.com/statamic/cms/assets/4531017/ccca8e5f-861b-45ec-8838-385378d12873)

![Screenshot 2024-04-09 at 3 47 40 pm](https://github.com/statamic/cms/assets/4531017/afe0e5ed-978b-45cf-b53d-9a930b380ecf)

![Screenshot 2024-04-09 at 3 39 26 pm](https://github.com/statamic/cms/assets/4531017/8ee1f82e-bbc5-48f2-a149-7826bc2f0dff)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.4
PHP Version: 8.2.16
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: widthtest.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.56.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)

### Additional details

Erin indicated it's likely to do with https://github.com/statamic/cms/pull/9799 /  https://github.com/statamic/cms/pull/9799/files

Specifically defining a depth resolves the issue.
