### ISSUE TITLE
Taxonomy terms in Route patterns not localized

### ISSUE THREAD

**Issue by klickreflex** [statamic/cms#9849]
### Bug description

On a multi-site with multiple languages, I want to include an entry's assigned taxonomy term in its URL. Terms are translated,  translated entries don't pick up the translated term slug in their routes.

### How to reproduce

**Concrete example:** 
- On a multisite setup, have a collection `articles` that uses a taxonomy `categories`.  
- Each entry can have max. 1 term 
- Set route pattern for `articles` to `/{mount}/{categories}/{slug}`
- Localize the terms' titles and slugs, e.g. `travel`  becomes `reisen` in a German locale 
- Create an entry in the articles collection, assign it a category and create a translation of it 

**Expectation:**
- When an entry is viewed in German, I'd expect the Route to pick up the localized term slug reisen instead of travel 

**Reality:**
- On every locale I get the source slug, e.g. /travel/tuscany-in-spring   becomes de/travel/toskana-im-fruehling , when it should be de/reisen/toskana-im-fruehling 

I've created a minimal setup to reproduce:
https://github.com/klickreflex/statamic-localized-taxonomy-slugs

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.4
PHP Version: 8.2.16
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: statamic-localized-taxonomy-slugs.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 2 (English, German)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.56.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
