### ISSUE TITLE
static:warm never ends?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#9852]
### Bug description

I've noticed that `php please static:warm --queue` isn't stopping?

I'm the only user logged in, and I'm not making any edits to entires. I'm checking the progress of the `static:warm` command by visiting `/cp/utilities/cache` and pressing refresh.

When the page count gets to around 500, I've noticed he page count drops? and the `static:warm` keeps on running?

I've been keeping an eye on this for a couple of hours and it keeps on doing the same thing.

This is my deploy script
```
php artisan cache:clear
php artisan config:cache
php artisan route:cache
php artisan statamic:stache:warm
php artisan statamic:search:update --all
php artisan statamic:static:clear
php please static:warm --queue
````

Is this perhaps related to another issue I'm seeing with invalidating cache on save? When I edit an entry and press save, the cache never clears? Maybe the invalidation job is never done because the `static:warm` never finishes?

These are my queue settings in Ploi. As you can see there's plenty of memory assigned to the queue worker.

<img width="663" alt="Screenshot 2024-04-09 at 15 35 52" src="https://github.com/statamic/cms/assets/72254741/cfaf5532-472c-4b03-91d0-046f91e36d33">

### How to reproduce

Seems like an issue with this website only, as the same site (same settings) running on a staging subdomain doesn't have any of these issues.

### Environment

```yaml
Environment
Application Name: Website Name
Laravel Version: 10.48.4
PHP Version: 8.2.12
Composer Version: 2.7.2
Environment: production
Debug Mode: OFF
URL: website.com
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: redis
Database: mysql
Logs: stack / single
Mail: log
Queue: redis
Session: redis

Livewire
Livewire: v3.4.9

Statamic
Addons: 6
Antlers: runtime
Sites: 1
Stache Watcher: Disabled
Static Caching: half
Version: 4.55.0 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 2.3.0
jonassiewertsen/statamic-jobs: 1.4.0
jonassiewertsen/statamic-live-search: 2.0.1
jonassiewertsen/statamic-livewire: 3.2.0
statamic/collaboration: 0.8.1
teamnovu/statamic-images-missing-alt: 1.0.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
