### ISSUE TITLE
API request cache keys too long

### ISSUE THREAD

**Issue by Smef** [statamic/cms#9859]
### Bug description

When using a database cache, API requests with long query parameters will use a cache key which exceeds the maximum limit for the key column. This creates a SQL error:

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'key' at row 1

Example: 
`/api/collections/products/entries?fields=c_id%2Cc_slug%2Ccoursewave_product_id%2Ctitle%2Cprice_base%2Cprice_bulk%2Cqty_25_minimum%2Ccolor_option%2Cprice_color%2Cdigital_option%2Cprice_digital%2Cphoto_sm%2Cphoto_sm_2x%2Cphoto%2Cphoto_2x%2Cphoto_lg%2Cphoto_lg_2x%2Cphoto_xl%2Cphoto_xl_2x%2Cphoto_2xl%2Cphoto_2xl_2x%2Cphoto_3xl%2Cphoto_3xl_2x%2Ccolor_option&filter%5Bstates%3Acontains%5D=ga&filter%5Btaxonomy%3Agrades%5D=7%2C8&filter%5Btaxonomy%3Asubjects%5D=math%2Cenglish%2Csocial-studies%2Cscience&limit=20&page=1&sort=state_specific%2C-featured`

A PR has been submitted https://github.com/statamic/cms/pull/9858 with a possible solution - hashing the API cache keys.

### How to reproduce

Use a database as a cache driver, then make an API request with a very long query parameter, as above.

### Environment

```yaml
Environment
Application Name: XXX
Laravel Version: 10.48.4
PHP Version: 8.2.13
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: XXX
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: database
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Scout: algolia
Session: database

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 3.8.2
PHP SDK Version: 3.22.1
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 1
Antlers: regex
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.56.0 PRO

Statamic Addons
statamic/eloquent-driver: 2.10.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Taxonomies: file
Terms: eloquent
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
