### ISSUE TITLE
Tables in Bard sets only save partial data

### ISSUE THREAD

**Issue by websmyth** [statamic/cms#9860]
### Bug description

Table fieldsets in Bard sets don’t save all data entered.

I have noticed this on a couple of live client sites and can reproduce in a fresh installation.

### How to reproduce

1. Create a Bard field with a set containing a Table fieldset
2. Create a table with multiple rows (~10-20), enter data into all of the cells. 
3. Save the entry
4. Refresh the CP page: the entry won’t have data saved in every cell where data was entered.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.7
PHP Version: 8.1.20
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: tables.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.56.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
