### ISSUE TITLE
[5.x] App commands aren't available in `please` when using new application structure

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#9875]
### Bug description

When using the new Laravel 11 application structure, commands from the `app/Console/Commands` directory aren't available in `php please`, even with the `RunsInPlease` trait added.

The command is available with `artisan`.

Related: https://github.com/statamic/cms/pull/9729

### How to reproduce

1. Create a new Laravel 11 application
2. Install Statamic 5
3. Create a new command
4. Add the `RunsInPlease` trait to the command
5. Run `php artisan` and see the command in the list of available commands
6. Run `php please` and you won't see the command in the list of available commands

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 11.0.7
PHP Version: 8.3.0
Composer Version: 2.6.3
Environment: local
Debug Mode: ENABLED
URL: laravel-11.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: reverb
Cache: database
Database: sqlite
Logs: stack / single
Mail: log
Queue: database
Session: database

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.0.0-alpha.3 Solo
```

### Installation

Existing Laravel app

### Antlers Parser

None
