### ISSUE TITLE
`@push` and `{{ push... }}` don't work together.

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#9880]
### Bug description

Trying to integrate Laravel views and antlers views with a shared layout and I have this in my antlers layout:

```
{{ stack:nav }}
```

But in the Blade views I can't do `@push('nav')` I have to do `@anters {{ push:nav }} @endantlers`

Would be great if they worked together.

### How to reproduce

Make an Antlers layout:

```html
<!DOCTYPE html>
<html>
    <body class="h-full">
      {{ stack:nav }}
      {{ $slot ?? template_content }}
    </body>
</html>
```

And in a Laravel route use `@push('nav')` and in an antlers view use `{{ push:nav }}`

### Environment

```yaml
Environment
Application Name: Glazed
Laravel Version: 10.48.7
PHP Version: 8.3.6
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: glazed.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: mysql
Logs: stack / daily, front
Mail: log
Queue: sync
Session: file

Pulse
Enabled: ENABLED
Version: v1.0.0-beta16

Livewire
Livewire: v3.4.10

Statamic
Addons: 2
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.56.1 PRO

Statamic Addons
statamic/seo-pro: 5.4.4
stillat/antlers-components: 2.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
