### ISSUE TITLE
Filesystems not loaded when installing a starter kit with `starter-kit:install` command

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#9884]
### Bug description

I'm sorry for this one in advance. 

To test my post install script in Peak I install Statamic v5 using `composer create-project` and then run `starter-kit:install --local`. After creating a super user I get an `InvalidArgumentException`:

```
  Disk [favicons] does not have a configured driver.

  at vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php:137
    133▕     {
    134▕         $config ??= $this->getConfig($name);
    135▕
    136▕         if (empty($config['driver'])) {
  ➜ 137▕             throw new InvalidArgumentException("Disk [{$name}] does not have a configured driver.");
    138▕         }
    139▕
    140▕         $name = $config['driver'];
    141▕

      +20 vendor frames

  21  [internal]:0
      Statamic\Assets\QueryBuilder::Statamic\Assets\{closure}("favicons")
      +13 vendor frames

  35  [internal]:0
      Statamic\Assets\AssetRepository::Statamic\Assets\{closure}(Object(Statamic\Assets\AssetContainer))
```

Peak contains a bunch of custom filesystems that are being  used by the asset containers it ships with. It seems those don't get properly loaded during the install. This does work as expected in v4.

The solution is to run the install command a second time. 

### How to reproduce

1. `composer create-project --prefer-dist --stability=dev statamic/statamic:dev-master`
2. `php please starter-kit:install studio1902/statamic-peak --local`

_Note:_ I'm installing a local version of Peak because the v5 version isn't released yet. You could replicate this using this [statamic-peak.zip](https://github.com/statamic/cms/files/14977821/statamic-peak.zip).

You will also need: [peak-addons.zip](https://github.com/statamic/cms/files/14977865/peak-addons.zip)

### Environment

```yaml
Environment
Application Name: My app
Laravel Version: 11.3.1
PHP Version: 8.3.6
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.0.0-alpha.3 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 6.1.0
studio1902/statamic-peak-seo: 8.2.0
studio1902/statamic-peak-tools: 4.4.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
