### ISSUE TITLE
Fieldtype date displays wrong value

### ISSUE THREAD

**Issue by mikolfaro** [statamic/cms#9885]
### Bug description

I created a date field for the users birth date.
Users are stored in the database and I am using a timestamp for the column (same happens if I use a date).

Appliying the changes described in https://github.com/statamic/cms/pull/8636 seems to fix the bug.

### How to reproduce

Set app timezone to `Europe/Rome`.
Select a date in the edit user page.
Save the form.
Refresh the page, the date shows the day before.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.5
PHP Version: 8.2.18
Composer Version: 2.2.4
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: pgsql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Sentry
Enabled: YES
Environment: local
Laravel SDK Version: 4.4.1
PHP SDK Version: 4.6.1
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 10%
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.56.1 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)

### Additional details

Users are stored in a Postgres DB (15.6)
