### ISSUE TITLE
[5.x] Possible memory leak when running `php please ssg:generate`

### ISSUE THREAD

**Issue by o1y** [statamic/cms#9888]
### Bug description

I just tested the new 5.x release on a more complex project (around 6k content files) with the Statamic Site Generator. It seems that the command requires significantly more memory resources than before. With V4 I have set the php memory limit to 512 MB. With the latest `v5.0.0-alpha.3`, the process always crashes with an exception at `Gathering content to be generated...`.

After increasing the memory limit to `2024 MB` I finally got a running static site generation process. It seems that the process is also longer than before.

* ssg runtime on`v5.0.0-alpha.3`: 12m 34s
* ssg runtime on `v4.x`: 11m 35s

### How to reproduce

I updated our existing Multi-Site Project to v5.0.0-alpha.3 and started the Static Site Generator using `php please ssg:generate`.

I know that the speed strongly depends on the project, templates, config etc. Let me know if you can't reproduce this issue, then I'll try to provide a test repo :)

### Logs

```shell
local.ERROR: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 327680 bytes) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Allowed memory size of 1073741824 bytes exhausted (tried to allocate 327680 bytes) at /.../statamic/vendor/laravel/framework/src/Illuminate/Collections/Arr.php:63)
[stacktrace]
#0 {main}
"}
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.3.1
PHP Version: 8.3.6
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: my-site.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: database
Session: file

Statamic
Addons: 3
Sites: 11 (English, Deutsch, Español, and 8 more)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.0.0-alpha.3 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 2.3.0
jacksleight/statamic-bard-texstyle: 3.1.6
statamic/ssg: 2.2.0
```

### Installation

Other (please explain)

### Antlers Parser

None
