### ISSUE TITLE
The Nova icon is not being displayed.

### ISSUE THREAD

**Issue by peimn** [statamic/cms#9899]
### Bug description

<img width="547" alt="image" src="https://github.com/statamic/cms/assets/5695187/1723639e-a663-4fdb-9efd-0aae28d88074">

### How to reproduce

add an icon fieldtype then scroll on nova item

### Environment

```yaml
Application Name: Laravel
Laravel Version: 11.3.0
PHP Version: 8.3.2
Composer Version: 2.6.6
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
```

### Installation

Existing Laravel app

### Antlers Parser

None
