### ISSUE TITLE
Regression in bard/replicator group set previews

### ISSUE THREAD

**Issue by caseydwyer** [statamic/cms#9900]
### Bug description

There seems to be a regression introduced in #9818, where the visibility of the set group's label & chevron are determined by the (existence of an) associated set group, instead of the total count of available set groups. As a result, the set group's label is shown even if there's only one option. If I understood the original intent of #9670 (and this change in particular), I don't think that's expected behavior.

PR incoming shortly. 👍

### How to reproduce

1. Set up a replicator field in a blueprint
2. Give it a single set group
3. Create a new record that uses the BP
4. Add a set from the group
5. See the label showing up despite the sole set group

### Environment

<details>
<summary>Environment</summary>

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.7
PHP Version: 8.2.5
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: statamic-sandbox.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.x-dev Solo
```
</details>

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
