### ISSUE TITLE
[5.x] SVG tag throws loadXML error when src value is empty

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#9902]
### Bug description

When using the following svg tag, the below error was thrown because the `icon` value did not exist:
`{{ svg src="{{ icon }}" class="w-6 h-6 lg:w-7 lg:h-7 text-primary-700" }}`

I could check that the value exists first but I think the SVG tag should fail gracefully if the source is empty.

### How to reproduce

Create svg tag with empty src value.
`{{ svg src="{{ foo }}" }}`

### Logs

DOMDocument::loadXML(): Argument #1 ($source) must not be empty
https://flareapp.io/share/NPLWLOrm

### Environment

```yaml
Environment
Application Name: Burlingame
Laravel Version: 11.3.1
PHP Version: 8.2.16
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: burlingame.test
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Livewire
Livewire: v3.4.10

Statamic
Addons: 0
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.0.0-alpha.3 PRO
```

### Installation

Other (please explain)

### Antlers Parser

Runtime (default)
