### ISSUE TITLE
Unable to apply sorting to a computed field in the CP

### ISSUE THREAD

**Issue by andreas-eisenmann** [statamic/cms#9908]
### Bug description

I have a computed field which should show up in list view in the CP, as described here in the documentation: https://statamic.dev/computed-values#showing-computed-values-in-the-control-panel

> You may also show this field as a column on your listings using the Listable setting, as shown above:

Alright, my computed field shows up in the list, but **sorting doesn't work**. If you click on the label of a column with a computed field, nothing happens. My customer really needs to apply sorting on a computed value. How is this supposed to work?

### How to reproduce

* Register a computed field `foo` in `\App\Providers\AppServiceProvider::boot()`:
```php
        \Statamic\Facades\User::computed('foo', static function (\Statamic\Auth\User $user, $value) {
            return $user->id();
        });
```
* Add a new field to the users blueprint according to the [docs](https://statamic.dev/computed-values#showing-computed-values-in-the-control-panel):
  * Type: Text
  * Handle: `foo`
  * Listable: Shown by default
  * Visibility: Computed
* Navigate to "Users" in the CP
* Try to apply sorting to the column "foo"

### Environment

```yaml
Environment
Application Name: Foo
Laravel Version: 10.28.0
PHP Version: 8.2.12
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: localhost/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.28.0 PRO

Statamic Addons
anakadote/statamic-recaptcha: 1.0.9
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.6
studio1902/statamic-peak-seo: 7.0.3
studio1902/statamic-peak-tools: 3.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
