### ISSUE TITLE
How to display entries from another multisite without localizing each?

### ISSUE THREAD

**Issue by AlexanderFalkenberg** [statamic/cms#9914]
### Bug description

I have a basic collection, which does not need any localization (images only). I want to show selected entries on multiple sites e.g. created on the German site on the English or Chinese version. 

I made an English version of the site with the following content:

` -
    awards:
      - 9ded2267-9aaf-4b02-a895-4fd11ade0c13` -> referencing a German entry

It's not displaying any entries or values to work with. 

Is it possible without propagation, which is making copies for each locale?

### How to reproduce

- Create a collection with entries in one locale / for one site.
- Reference those entries on a page and localize this page. 
- Entries are visible on one page but not the other, unless those entries are localized. 

### Environment

```yaml
Laravel Version: 10.46.0
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: #
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 12
Antlers: runtime
Sites: 5 
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.56.1 PRO

Statamic Addons
arthurperton/popular: 1.1.0
aryehraber/statamic-uuid: 2.2.0
jacksleight/statamic-bard-texstyle: 3.1.6
jonassiewertsen/statamic-documentation: 1.9.2
morethingsdigital/bite: dev-development
rias/statamic-redirect: 3.6.2
ryanmitchell/statamic-translation-manager: 1.4.1
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 3.2.0
studio1902/statamic-peak-seo: 7.5.0
studio1902/statamic-peak-tools: 4.4.2
thoughtco/statamic-blurhash: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
