### ISSUE TITLE
Missing some images?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#9919]
### Bug description

Not sure when it started, but I noticed some images are not loading on the frontend. Even though the image file is showing in the /cp and I can see the file on the sever.

### How to reproduce

Honestly not sure how to reproduce. Hoping support might have some suggestions. I'd rather not have to use `php please glide:clear` to fix this. As the site currently has 150000 odd images cached. It'll take a long time to regenerate.

There's no logs in `storage/logs`

### Environment

```yaml
Environment
Application Name: 
Laravel Version: 10.48.7
PHP Version: 8.2.12
Composer Version: 2.7.2
Environment: production
Debug Mode: OFF
URL: 
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: redis
Database: mysql
Logs: stack / single
Mail: log
Queue: redis
Session: redis

Livewire
Livewire: v3.4.10

Statamic
Addons: 6
Antlers: runtime
Sites: 1
Stache Watcher: Disabled
Static Caching: half
Version: 4.56.1 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 2.3.0
jonassiewertsen/statamic-jobs: 1.4.0
jonassiewertsen/statamic-live-search: 2.0.1
jonassiewertsen/statamic-livewire: 3.2.0
statamic/collaboration: 0.8.1
teamnovu/statamic-images-missing-alt: 1.0.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
