### ISSUE TITLE
Get an error in the CP when moving an asset into a folder

### ISSUE THREAD

**Issue by rl-ico** [statamic/cms#9930]
### Bug description

Dear Statamic team, 
every time I try to move an asset into a folder the CP yields the following error:
`foreach() argument must be of type array|object, null given`

The file gets moved though, but the error keeps the move dialog from closing after the operation.
This misleads the user to think that the operation has failed only to realize after a page refresh the file was indeed moved into the folder.

The same happens if the user tries to move the asset from inside the folder up to the root `/` or to another folder.

See short screen recording:
[statamic_move_asset_bug.webm](https://github.com/statamic/cms/assets/130561667/3c3b5251-a791-4cba-a30a-694a1927be1e)

### How to reproduce

1. Go to Assets
2. Create a folder ( if you don't have any)
3. Select an asset
4. Click move
5. Select the target folder from the dialog
6. Click move

### Environment

```yaml
Environment
Application Name: Test Site
Laravel Version: 10.48.8
PHP Version: 8.3.6
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: testsite.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.57.0 PRO

Statamic Addons
jacksleight/statamic-bard-ipsum: 1.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)

### Additional details

The users are stored in a mysql DB.
Other than that, everything is standard.
