### ISSUE TITLE
Clicking back button after filtering users returns raw json response

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/cms#9937]
### Bug description

Ran into this issue while creating a custom filter view for users.  If you filter the users table using any method of filtering, then click on any user, and then click the browser back button you get the JSON response (that I imagine feeds the Vue table) instead of the actual page.

### How to reproduce

1. Go to the users table
2. Use any filter (one that will leave at least one user visible)
3. Click on the user to view their profile info
4. Click the browser back button - you will be shown the raw JSON response from the last filter request.

### Environment

```yaml
Environment
Application Name: Website
Laravel Version: 10.48.4
PHP Version: 8.3.6
Composer Version: 2.7.2
Environment: local
Debug Mode: ENABLED
URL: website.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: redis
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: redis

Statamic
Addons: 5
Antlers: runtime
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.55.0 PRO

Statamic Addons
statamic-rad-pack/meilisearch: 3.2.1
statamic/eloquent-driver: 3.3.3
stillat/antlers-components: 2.1.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Taxonomies: file
Terms: file
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

I believe this may be due to how history is being manually pushed onto the history stack.  I might look into it if I have time.
