### ISSUE TITLE
`Video` field preview tries to preview invalid sources

### ISSUE THREAD

**Issue by Cube-Justin** [statamic/cms#9943]
### Bug description

I am currently loading a Vimeo video by using the `Video` field in the CMS.
When using a valid URL, such as: `https://vimeo.com/935832884` , the preview loads fine.
When inputting an invalid URL, such as: `blabla.test`, the preview is not loaded as would be expected.
However when inputting an Vimeo embed as a source, such as: 
```
<iframe src="https://player.vimeo.com/video/882020077?h=53a2cf6397" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
<p><a href="https://vimeo.com/882020077">FESTIVAL OF SLAPS</a> from <a href="https://vimeo.com/abdoucisse">Abdou Ciss&eacute;</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
```
The CMS still tries to load a preview, but this fails of course. The preview in this case is is an embed of the CMS:
<img width="873" alt="image" src="https://github.com/statamic/cms/assets/132989832/ab43f680-2b87-4c23-b04b-f690c72dcdb5">

### How to reproduce

1. Add a `Video` field to a blueprint
2. Insert the following text into the field:
```
<iframe src="https://player.vimeo.com/video/882020077?h=53a2cf6397" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
<p><a href="https://vimeo.com/882020077">FESTIVAL OF SLAPS</a> from <a href="https://vimeo.com/abdoucisse">Abdou Ciss&eacute;</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
```

### Environment

```yaml
Environment
Application Name: #confidential#
Laravel Version: 10.44.0
PHP Version: 8.3.4
Composer Version: -
Environment: production
Debug Mode: OFF
URL: #confidential#
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: DAILY
Mail: smtp
Queue: sync
Session: file

Sentry
Enabled: YES
Environment: production
Laravel SDK Version: 4.2.0
PHP SDK Version: 4.6.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 2
Antlers: runtime
Sites: 2 (Nederlands, Engels)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.48.0 PRO

Statamic Addons
pecotamic/sitemap: 1.4.6
statamic/eloquent-driver: 3.1.1

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: file
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: file
Revisions: eloquent
Taxonomies: file
Terms: eloquent
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
