### ISSUE TITLE
Fails to deploy with composer 2.7.3 because of dependency

### ISSUE THREAD

**Issue by ajnsn** [statamic/cms#9945]
### Bug description

Deploying Statamic 

```
In Application.php line 403:
                                                                                      
[Error]                                                                          
Call to undefined method Composer\Util\Http\ProxyManager::needsTransitionWarning()  
```

### How to reproduce

Composer 2.7.3, works with 2.7.2

"fyi"

See https://github.com/composer/composer/issues/11940 

Can be fixed by removing the composer/composer dependecy, see  [comment](https://github.com/composer/composer/issues/11940#issuecomment-2068728878)

### Environment

```yaml
Environment
Application Name: 
Laravel Version: 10.48.3
PHP Version: 8.2.6
Composer Version: 2.7.2
Environment: staging
Debug Mode: OFF
URL: 
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: daily
Mail: smtp
Queue: redis
Session: database

Livewire
Livewire: v3.4.9

Sentry
Enabled: YES
Environment: staging
Laravel SDK Version: 3.8.2
PHP SDK Version: 3.22.1
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 0%
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.53.2 PRO
```

### Installation

Existing Laravel app

### Antlers Parser

None
