### ISSUE TITLE
[5.x] Svg tag ignores `attr:x-show`

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#9948]
### Bug description

When adding an `attr:x-show` or `x-show` attribute to the SVG tag, it seems to get removed. I'm not sure however if this is intended behaviour in v5?

### How to reproduce

Use `attr:x-show` or `x-show` on an SVG tag in v5 alpha 5

### Environment

```yaml
Environment
Application Name: connect2id
Laravel Version: 11.4.0
PHP Version: 8.2.16
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: connect2id.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.0.0-alpha.5 PRO

Statamic Addons
rias/statamic-color-swatches: 2.2.0
studio1902/statamic-peak-browser-appearance: 3.4.0
studio1902/statamic-peak-commands: 8.2.0
studio1902/statamic-peak-seo: 8.11.0
studio1902/statamic-peak-tools: 6.0.0
trendyminds/statamic-palette: 1.0.4
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
