### ISSUE TITLE
[5.x] Fieldset builder: sluggish slugs

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#9959]
### Bug description

I don't think I've seen this in v4, but I could very well be wrong. I'm currently doing a new project in v5. I haven't found a way to replicate this, it just happens every now and then.

Upon adding fields in the fieldsets builder pretty often the slug doesn't generate completely.

**Demo time:**

https://github.com/statamic/cms/assets/69107412/b549a2df-a7ce-46b2-9be5-3c2eec1001c7

### How to reproduce

Play around with fields (nested). I'm using Safari. Will update if I find out more.

### Environment

```yaml
Environment
Application Name: connect2id
Laravel Version: 11.4.0
PHP Version: 8.2.16
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: connect2id.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.0.0-alpha.5 PRO

Statamic Addons
rias/statamic-color-swatches: 2.2.0
studio1902/statamic-peak-browser-appearance: 3.4.0
studio1902/statamic-peak-commands: 8.2.0
studio1902/statamic-peak-seo: 8.11.0
studio1902/statamic-peak-tools: 6.0.0
trendyminds/statamic-palette: 1.0.4
```

### Installation

Starter Kit using via CLI

### Antlers Parser

Runtime (default)
