### ISSUE TITLE
Can't install starter kit on Windows 11

### ISSUE THREAD

**Issue by the-goodies** [statamic/cms#9967]
### Bug description

Get this error when installing **any** starter kit using Windows 10 or 11:
```
In NewCommand.php line 555:

  There was a problem installing Statamic with the chosen starter kit!


new [--dev] [--license [LICENSE]] [--local] [--with-config] [--without-dependencies] [-f|--force] [--] <name> [<starter-kit>]
```

Also when installing a starter kit into an existing site:
```
php please starter-kit:install duncanmcclean/sc-starter-kit

 Clear site first? (yes/no) [no]:
 > no

Preparing starter kit [duncanmcclean/sc-starter-kit]...
Starter kit config [starter-kit.yaml] does not exist.
```

### How to reproduce

> statamic new my-new-website duncanmcclean/sc-starter-kit
```
Collections cleared successfully.
Navigations cleared successfully.
Trees cleared successfully.
Taxonomies cleared successfully.
Assets cleared successfully.
Globals cleared successfully.
Forms cleared successfully.
Users cleared successfully.
User groups cleared successfully.
User roles cleared successfully.
Blueprints cleared successfully.
Fieldsets cleared successfully.
Views cleared successfully.
Statamic configs reset successfully.
Preparing starter kit [duncanmcclean/sc-starter-kit]...
Starter kit config [starter-kit.yaml] does not exist.

In NewCommand.php line 555:

  There was a problem installing Statamic with the chosen starter kit!


new [--dev] [--license [LICENSE]] [--local] [--with-config] [--without-dependencies] [-f|--force] [--] <name> [<starter-kit>]
```

### Logs

```shell
Empty folder only with .gitignore
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.9
PHP Version: 8.3.6
Composer Version: 2.7.4
Environment: local
Debug Mode: ENABLED
URL: my-new-website.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.57.2 Solo
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
