### ISSUE TITLE
Big slow down in 4.51.0

### ISSUE THREAD

**Issue by jbreuer95** [statamic/cms#9971]
### Bug description

When i upgraded my site (1000+ unique entries) i noticed the base loading time increased with about 300ms, just to find the right page. After installing different versions and adding a ton of  dumps i found the culprit:
https://github.com/statamic/cms/pull/5502

Specifically the part in BasicStore.php@getItem

```
        if (method_exists($item, 'syncOriginal')) {
            $item->syncOriginal();
        }
```        

If i remove this piece of code and revert it to how it used to be , with it being called explicitly in the children stores, the slowdown goes away

### How to reproduce

- Have alot of unique pages with unique uri
- Add a timed measure around this part in CollectionStructure
```
            $thisCollectionsEntries = $this->collection()->queryEntries()
            ->where('site', $locale)
            ->get(['id', 'site'])
            ->map->id();
```

Measure it in 4.50.0 and 4.51.0 (or the latest version)
See the slowdown

### Environment

```yaml
Environment
Application Name: jelle_printenbind
Laravel Version: 9.52.16
PHP Version: 8.1.27
Composer Version: 2.5.7
Environment: development
Debug Mode: ENABLED
URL: printenbind.jelle.printenbind.nl
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: redis
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: database
Session: redis

Statamic
Addons: 0
Antlers: regex
Sites: 2 (NL, EN)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.52.0 PRO
```

### Installation

Existing Laravel app

### Antlers Parser

None
