### ISSUE TITLE
Add missing Vite content tag

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#9972]
### Description

It's actually not possible to inline asset using `{{ vite:content }}` while Laravel offer a method for that: [Laravel Vite inline assets](https://laravel.com/docs/11.x/vite#inline-assets)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.9
PHP Version: 8.3.6
Composer Version: 2.7.4
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: null
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 1
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.57.2 PRO

Statamic Addons
statamic/seo-pro: 5.4.4
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
