### ISSUE TITLE
Display Error in "Bard Fieldtype" Meta Information

### ISSUE THREAD

**Issue by DanielSchreurs** [statamic/cms#9980]
### Bug description

When you create a new Bard Fieldtype and set a character limit, the character counter does not display when entering text in the relevant resource. Instead, the keyword "count" is displayed. 

<img width="1250" alt="bug-Bard Fieldtype" src="https://github.com/statamic/cms/assets/8074967/702a45f9-8a9c-4a9a-b79e-a203441986ee">

### How to reproduce

To reproduce the bug, from a Blueprint, add a Bard Fieldtype and set a character limit for it. Note that this character limit is not found in the validation tab.
<img width="2559" alt="Bard Fieldtype" src="https://github.com/statamic/cms/assets/8074967/0f4804aa-2409-4f6a-b2aa-e259f923fb91">

### Environment

```yaml
Environment
Application Name: EAFC Namur Cadets
Laravel Version: 10.48.4
PHP Version: 8.3.4
Composer Version: 2.7.1
Environment
Debug Mode: ENABLED
URL: eafc-namur-cadets.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.57.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
