### ISSUE TITLE
ErrorException 'Undefined array key "type"' when Handling Empty set Handles in Replicator Field

### ISSUE THREAD

**Issue by yehor-hromov** [statamic/cms#9983]
### Bug description

A critical issue has been identified when working with replicator fields within blueprints. The bug arises when following a specific sequence of actions:

### How to reproduce

1. <b>Create Replicator Field:</b> Begin by creating a replicator field within any blueprint.
2.  **Add Set:** After creating the replicator field, proceed to add a set to it.
3. **Leave Handle Empty:** Within the set, intentionally leave the handle field empty.
4. **Save Blueprint:** Save the blueprint after configuring the replicator field and set.
5. **Add Content to Replicator Set:** Following the blueprint configuration, add content to the replicator set.
6. **Save Changes:** Save the changes made to the replicator set.
7. **Attempt to Load Frontend or Backend:** Upon attempting to load either the frontend or backend of the website, or even just reloading the backend interface, the following error occurs: ErrorException: Undefined array key "type"

### Environment

```yaml
Environment
Application Name: test
Laravel Version: 10.48.10
PHP Version: 8.3.6
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
URL: test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.57.2 PRO

Statamic Addons
alt-design/alt-password-protect: 1.1.2
jacksleight/statamic-bard-texstyle: 3.2.0
rias/statamic-data-import: 1.4.0
ryanmitchell/statamic-translation-manager: 1.5.0
spatie/statamic-responsive-images: 4.1.1
steadfastcollective/statamic-csv-exporter: 2.2.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
