### ISSUE TITLE
Fields Removed from Blueprint Persist in .md Files Even After Resave

### ISSUE THREAD

**Issue by yehor-hromov** [statamic/cms#9984]
### Bug description

When fields are removed from a blueprint and those fields previously held content, the content associated with those removed fields persists within the corresponding .md files, even after saving the page again. This behavior contradicts the expected behavior where removing fields from a blueprint should also remove their associated content from the .md files upon saving.

### How to reproduce

1. Create a new entry in with a blueprint containing multiple fields.
2. Fill in content for all fields.
3. Remove one or more fields from the blueprint.
4. Save the entry.
5. Reopen the entry and observe that the removed fields' content is still present in the .md file.
6. Make changes to the entry and save again.
7. Despite saving, the content associated with removed fields persists in the .md file.

### Environment

```yaml
Environment
Application Name: test
Laravel Version: 10.48.10
PHP Version: 8.3.6
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
URL: test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.57.2 PRO

Statamic Addons
alt-design/alt-password-protect: 1.1.2
jacksleight/statamic-bard-texstyle: 3.2.0
rias/statamic-data-import: 1.4.0
ryanmitchell/statamic-translation-manager: 1.5.0
spatie/statamic-responsive-images: 4.1.1
steadfastcollective/statamic-csv-exporter: 2.2.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)

### Additional details

This issue could potentially lead to data inconsistencies and confusion for users, especially when managing large amounts of content with frequent blueprint modifications. Resolving this issue would ensure that the data stored in .md files accurately reflects the structure defined by the blueprint and maintaining data integrity.
