### ISSUE TITLE
Statamic 5 - 404 on every page after upgrade to beta 1

### ISSUE THREAD

**Issue by DanielDarrenJones** [statamic/cms#9987]
### Bug description

After upgrading to v5 every page is now 404ing after clearing the stache.

### How to reproduce

Upgrade to v5, clear stache

### Environment

```yaml
Environment
Application Name: Pelorus
Laravel Version: 10.48.10
PHP Version: 8.3.6
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 7
Sites: 8 (Travel (GB), Travel (US), Aviation (GB), and 5 more)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.0.0-beta.1 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
doefom/currency-fieldtype: 1.3.0
gerttimmerman/statamic-zapier: 1.5
jacksleight/statamic-bard-texstyle: 3.2.0
ndx/statamic-bard-color-picker: 1.2.0
ryanmitchell/statamic-translation-manager: 1.5.0
statamic/eloquent-driver: 3.4.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Taxonomies: file
Terms: file
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)
