### ISSUE TITLE
[5.x] Global returning wrong value

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#9988]
### Bug description

This screenshot probably best explains the issue. The global `{{ seo:use_sitemap }}`  should return `false`, but it does return `true`.
<img width="1022" alt="Screenshot 2024-05-02 at 21 47 10" src="https://github.com/statamic/cms/assets/69107412/07ef0602-e8b0-49e9-8359-d421bc4f3ed1">

When I do `{{ seo | dump }}` and click into the data I do see the correct value: `false`. 

This also returns `true`: `{{ if seo:use_sitemap }}yes{{ else }}no{{ /if }}`.

Notes:
- This does work correct on v4.
- I could reproduce this on 2/2 v5 sites. 
- There's another boolean global that _does_ return the correct value. 

### How to reproduce

1. On v5: `php please starter-kit:install studio1902/statamic-peak:dev-feature/v5-support` .
2. Publish the SEO addon views and hack away in the sitemaps.xml or sitemap.xml views. 

Although, it might be an addon related issue and you perhaps see the correct value when dumping it from the published views. I don't know tbh. Haven't tested this yet.  If you have follow ups, let me know and I'd be happy to try!

### Environment

```yaml
Environment
Application Name: Statamic Peak Development
Laravel Version: 11.6.0
PHP Version: 8.2.16
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: statamic-peak.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.0.0-beta.1 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.4.0
studio1902/statamic-peak-commands: 8.3.0
studio1902/statamic-peak-seo: 8.13.1
studio1902/statamic-peak-tools: 6.0.0
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
