### ISSUE TITLE
[5.x] Serialize augmentationReferenceKey error

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#9992]
### Bug description

Getting this when loading the site/CP or trying to warm the stache after installing beta 1:

```
  serialize(): "augmentationReferenceKey" returned as member variable from __sleep() but does not exist

  at vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:84
```

I saw that https://github.com/statamic/cms/pull/9991 mentions `augmentationReferenceKey`, but this site doesn't use eloquent so not sure if that's related. Maybe this is already fixed?

### How to reproduce

Install beta 1, load the site/CP or warm the stache.

### Environment

```yaml
Environment
Application Name: Rego
Laravel Version: 10.48.10
PHP Version: 8.2.16
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: rego.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: sendmail
Queue: sync
Session: file

Livewire
Livewire: v3.4.12

Statamic
Addons: 8
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.0.0-beta.1 PRO

Statamic Addons
jacksleight/statamic-bard-ipsum: 1.0.0
jacksleight/statamic-bard-mutator: 2.3.0
jacksleight/statamic-bard-texstyle: 3.2.0
jacksleight/statamic-distill: 0.4.3
jacksleight/statamic-lazy-logo: 1.1.0
jacksleight/statamic-miniset: 1.1.1
mitydigital/feedamic: 2.3.1
mitydigital/sitemapamic: 2.3.9
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
