### ISSUE TITLE
Database Role inserting (string) role as opposed to id of the role

### ISSUE THREAD

**Issue by icemancast** [statamic/cms#9996]
### Bug description

When I add user with a role other than super admin using our local database roles I get the error in the screenshot below. 

I used a patch for this pr prior to it being imported and seemed to work: https://github.com/statamic/cms/pull/5686

I have since removed the patch and now have upgraded to the latest version as that pr was merged already. But looking at the insert error it seems it is trying to send the string of the role instead of the id that is associated with that role.

### How to reproduce

Make sure you are using database roles and groups as opposed to statamic. Have the latest Statamic installed and add a user and attach a non super admin role to him.

### Environment

```yaml
Environment
Application Name: Radix IoT
Laravel Version: 10.44.0
PHP Version: 8.2.18
Composer Version: 2.7.2
Environment: local
Debug Mode: ENABLED
URL: radixiot.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: mailgun
Queue: sync
Session: database

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.57.3 PRO
```

### Installation

Other (please explain)

### Antlers Parser

Runtime (default)

### Additional details

This is a hybrid laravel and statamic application. The client already had users in the database and a dashboard that uses those user roles. Attached is the sql error I get.

![Screenshot 2024-05-03 at 10 09 18 AM](https://github.com/statamic/cms/assets/110063/3682abf4-9515-42a9-bcaf-1b24c3b3fd7f)
